### ISSUE TITLE
Occtax - Champs additionnels

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#1007]
Il est souhaité pouvoir ajouter des champs additionnels dans Occtax en fonction du JDD. 
Et ces champs additionnels sont aussi présent dans le standard Occurrence de taxons du SINP.

Le principe proposé est de pouvoir décrire des champs additionnels (en lien avec la table des JDD ou dans la configuration en faisant référence à un id_dataset ?), par JDD, de différents types (liste simple ou multiple, booléen, radio, texte...), dont le contenu renseigné serait stocké dans un champs ``additional_data`` générique au format ``jsonb``.

Occtax étant structuré en 3 niveaux, il faut ajouter un champs ``additional data`` aux 3 tables (relevés, occurrence, dénombrement). A confirmer ?

Si on sélectionne un JDD pour lequel des champs additionnels ont été définis, alors on les affiche sur le formulaire dynamiquement au niveau du relevé, de l'occurrence ou du dénombrement (selon le niveau auquel ils ont été définis).
Pour leur configuration et leur affichage sur le formulaire Occtax, on se base sur le composant ``dynamic-form`` et ce qui a été fait sur les champs additionels dans le module Monitoring (https://github.com/PnX-SI/gn_module_monitoring).

De la même manière que pour le module Création de compte - http://docs.geonature.fr/admin-manual.html#customisation-du-formulaire.

Quand on affiche le détail d'un relevé, les valeurs des éventuels champs additionnels sont affichées.

Quand on exporte des observations, si elles concernent plusieurs JDD, le contenu du champs json est exporté tel quel dans un seul champs, car les champs additionnels peuvent être différents selon les JDD. 
Par contre si les données exportées ne concernent qu'un seul JDD avec des champs additionnels, alors on peut faire un pivot dynamique pour les remettre sous forme de colonne. 
Voir exemple de requête pivot à partir d'un champs json : https://github.com/PnX-SI/Ressources-techniques/blob/master/PostgreSQL/pivot_query.sql

On ajoute aussi un champs ``additional_data`` de type ``jsonb`` à la table ``gn_synthese.synthese`` alimenté lui aussi par le trigger Occtax > Synthèse. A voir comment agglomérer les infos pouvant venir de 3 champs ``additional_data`` dans Occtax vers un champs unique ``additional_data`` dans la table ``gn_synthese.synthese``.
Dans la fiche détail d'une observation de la Synthèse, afficher le contenu de ses champs additionnels. Idem dans les exports de la Synthèse (sans pivot, dans un seul champs). Les afficher aussi dans le fiche détail des observations dans le module Validation.

**Comment by jpm-cbna** [comment]
C'est intéressant car j'ai aussi la problématique de la gestion des champs supplémentaires spécifiques a un jeu de données lors de l'import dans les tables de GeoNature.

Il me semble préférable de pouvoir décrire le format de ces champs additionnels dans un champ du jeu de données et non pas dans un fichier de configuration. En effet, cela me permettra de gérer aussi ces champs via [l'import des infos du jeu de données](https://wiki-sinp.cbn-alpin.fr/database/import-formats#format_dataset_d_import).

**Comment by camillemonchicourt** [comment]
Oui dans les 2 cas, les champs additionnels seront définis par JDD.
En anticipation, le champs ``additional_data``est ajouté dans la Synthèse : https://github.com/PnX-SI/GeoNature/commit/5c10f81517c4ee0b30a838a0bd732b711706bc2e

**Comment by camillemonchicourt** [comment]
A voir où et comment définir la conf des champs additionnels, car on pourrait aussi imaginer que si un champs additionnel est défini mais sans être associé à un JDD alors il s'applique à Occtax dans tous les cas, tous les JDD

**Comment by DonovanMaillard** [comment]
pourrait on imaginer dans le module administratif avoir un objet "champs additionnels" qui soit une admin partagée pour tous les modules qui permettent ces champs additionnels ? 

On pourrait imaginer dans t_modules un booleen pour définir si chaque module accepte ou non dans chamos additionnels. Et a partir de la, l'administration permettrait de créer un champ additionnel, de le décrire, de l'associer à un ou des modules et a un ou des jeux de données ?

**Comment by camillemonchicourt** [comment]
Il semble important de pouvoir définir des champs additionnels globalement à une instance de GeoNature, ou de pouvoir les limiter à un JDD (dataset) ou un module.

Pour faciliter leur usage (directement dans la BDD mais pas que) je pense qu'il faudrait les définir dans une table dédiée (avec l'API qui va avec) plutôt que dans des fichiers de configuration (comme cela a été fait dans le module Monitoring).

Donc je propose de créer une table ``gn_commons.additonal_fields`` avec les champs ``type_widget``, ``label``, ``definition``, ``type_util``, ``required``, ``values``, ``code_nomenclature_type``, ``code_list``, ``min``, ``max``, ``hidden``, ``id_component``, ``id_module``, ``id_dataset``.

A voir si ``id_module`` et ``id_dataset`` ne doivent pas plutôt être dans une table de relation pour pouvoir associer un champs additionnels à plusieurs modules et/ou plusieurs JDD.

Si un champs additionnel n'est associé à aucun JDD alors il s'applique à tout le module. Exemple si un champs additionnel est associé au module Occtax mais à aucun JDD, alors il s'applique à tout le module Occtax.

Si il n'est associé à aucun module, alors il s'applique à tous les modules qui utilisent des champs additionnels (Occtax, Synthèse...).

**Comment by jpm-cbna** [comment]
La présentation des champs additionnels est réalisée dans la section _5.5.4 AttributAdditionel_ du standard OccTax v2.
Ci-dessous entre parenthèse et en italique le nom du concept dans le standard que j'ai essayé d'attribuer à un des champs proposés. Si le champ n'existait pas, je l'ai rajouté entre barres obliques. Si le champ est obligatoire dans le standard, il est en gras.

En gras les champs obligatoires qui me paraissent obligatoire dans les tables.

J'ai essayé de rajouter une description pour chaque champ ou une question quand cela me parait pas évident.

### `gn_commons.additional_fields`
- **id_additional_field**: identifiant auto-incrémenté du champ additionnel servant de clé primaire.
- **label** (=***nomAttribut***): nom de l'attribut. Libellé court et implicite de l’attribut additionnel.
- code: nom normalisé de l'attribut pouvant servir à réaliser une correspondance avec les fichiers d'import. Par exemple, le nom du champ toujours en minuscule sans accent et avec des mots séparés par un tiret bas ("_").
- **definition** (=***definitionAttribut***): définition précise et complète de l'attribut additionnel. Ne devrait on pas utiliser plutôt le nom *desc* pour ce champ plutôt que *definition* car c'est un nom d'attribut utilisé dans les tables _t_datasets_ et _t_acquisition_frameworks_ ?
- /quantitative/ (=***valeurAttribut*** et ***typeAttribut*** [!?]): booléen indiquant si le champ est de type quantitatif (=true) ou pas (=false).
- /unity/ (=*uniteAttribut*): unité de mesure de l’attribut additionnel exprimée en système international dès que possible (°C, m, kg, ha...). À remplir si /quantitative/ vaut _true_.
- /category/ (=***thematiqueAttribut***): un mot-clé correspondant à la thématique (=catégorie) relative à l'attribut additionnel.
- type_widget: le type du widget à utiliser pour ce champ dans les interfaces graphiques. Où trouver la liste ?
- type_util: correspond à quoi ?
- required: booléen indiquant si le champ est obligatoire ou pas.
- values: les valeurs possible du champ dans le cas d'un widget de type liste ?
- code_nomenclature_type: code du type de nomenclature à utiliser ? Pourquoi pas un id ?
- code_list: c'est le code de quelle liste ?
- min: valeur minimum dans le cas d'un champ de type ... ? Le champ /quantitative/ doit être à _true_ pour remplir ce champ.
- max: valeur maximum dans le cas d'un champ de type ... ? Le champ /quantitative/ doit être à _true_ pour remplir ce champ.
- hidden: le champ doit être caché dans les interfaces.

### `gn_commons.cor_additional_fields_modules`
- `**id_additional_field**`: identifiant du champ additionnel.
- `**id_component**`: identfiant du composant ? C'est en lien avec quelle table ?
- `**id_module**`: identifiant du module.
- `**id_dataset**`: identifiant du jeu de données.

**Comment by joelclems** [comment]
- `type_util`: il est utilisé dans le module_monitoring.
c'est quand on a des formulaire qui renvoie des id, et que l'on souhaite afficher une valeur
il ne sert pas pour les fomulaires mais pour l'affiche des valeur dans la page de propiétée ou des listes.
cela permet de faire le liens entre l'id et la valeur que l'on veut afficher
par exemple si `type_util`=`nomenclature` on va chercher la nomenclature correspondant et on affiche le champs `label_fr`
il sert aussi pour les utilisateur, jdd et taxon mais c'est un traitement qui est fait dans le module monitoring.
Il n'est peut être pas nécessaire ici

`code_list`: c'est le code d'une liste utilisateur pour le composant observers

**Comment by camillemonchicourt** [comment]
Après discussion avec @amandine-sahl, elle est favorable aussi à ce que les champs additionnels soient définis dans la BDD. 

Avec 2 points de vigilance : 
- Difficulté de renseigner ce type d'infos dans les champs d'une BDD et d'assurer la validité des infos renseignées, contrairement à des fichiers de configuration.
- Concernant la structure de la table. Ce serait bien d'avoir un champ de définition des contraintes assez souple. Dans TaxHub nous avons un champ contenant du json ce qui permet de s'adapter à tous les types de widget et potentiellement d'ajouter des types de champs, widgets, contraintes sans difficulté.

**Comment by camillemonchicourt** [comment]
Version 2.5.0 : Ajout d'un champs ``addtional_data`` de type ``jsonb`` dans la table ``gn_synthese.synthese``, en prévision de l'ajout des champs additionnels dans Occtax et Synthèse.

**Comment by metourneau** [comment]
Une première version du module Occtax avec un paramétrage de champs dynamiques dans le fichier de config est développée. Si cela vous intéresse, je peux la mettre à disposition.

Voila la procédure, dans le fichier de config geonature/external_modules/occtax/frontend/app/module.config.ts, un exemple de configuration assez imbuvable, je vous l'accorde:

```
 "add_fields": {
   1 : {
     'id_taxon_list' : 5,
     'releve' : [
        {
           "type_widget": "html",
           "class": "alert alert-primary",
           "attribut_name": "presentation",
           "html": "<p>A partir d'ici, on est dans le formulaire propre à la saisie des pélophylax <br><a href='' target='_blank'>lien vers le protocole</a></p>",
        },
        {
           "type_widget": "select",
           "attribut_label": "Expertise",
           "attribut_name": "expertise",
           "values": [
              "Débutant",
              "Expérimenté",
              "Chevronné"
           ],
           "required": false
        },
     ],
     'occurrence': [
        {
           "type_widget": "text",
           "attribut_label": "Numéro de la dérogation de capture",
           "attribut_name": "num_derogation",
           "required": false
        },
     ],
     'counting' : [
        {
           "type_widget": "radio",
           "attribut_label": "Prélèvement ADN effectué",
           "attribut_name": "prelev_adn",
           "required": false,
           "values": ["Oui", "Non"]
        },
        {
           "type_widget": "text",
           "attribut_label": "Lieu de stockage de l’ADN prélevé",
           "attribut_name": "lieu_stockage_adn",
           "required": false
        },
        {
           "type_widget": "html",
           "class": "",
           "attribut_name": "separation",
           "html": "<hr>",
        },
        {
           "type_widget": "medias",
           "attribut_label": "Prise de vue générale avec l’individu en main à côté d’un papier avec le code de l’individu",
           "attribut_name": "photo_general",
           "required": false,
           "schema_dot_table": "pr_occtax.cor_counting_occtax",
           "details": ['id_nomenclature_media_type', 'bFile', 'description_fr', 'author'],
           "hide_details_fields" : true,
           "default" : {
              'title_fr' : "Prise de vue générale",
              'description_fr' : "Prise de vue générale",
              'mnemonique_nomenclature_media_type' : 'Photo',
           }
        },
     ],
  },
}
```
![image](https://user-images.githubusercontent.com/53472638/96274047-5a728180-0fd0-11eb-9e57-556c936aeeef.png)
![image](https://user-images.githubusercontent.com/53472638/96274115-72e29c00-0fd0-11eb-8e3c-4ceb522f83fc.png)
![image](https://user-images.githubusercontent.com/53472638/96274237-9279c480-0fd0-11eb-89d2-9834c57248f0.png)
![image](https://user-images.githubusercontent.com/53472638/96274574-f3090180-0fd0-11eb-9f1c-947cabec2e48.png)

J'ai encore quelques soucis avec le module "media" qui supprime les médias de manière aléatoire. Y a t il une script qui purge les médias non référencés dans la table t_media?

**Comment by camillemonchicourt** [comment]
Super, merci pour ce travail et ce retour détaillé.
Oui, si c'est fonctionnel tu peux faire une PR ou sinon indiquée ta branche de travail.

Pour les médias, il y a bien une fonction qui supprime les médias orphelins de mémoire, mais @joelclems pourra en dire plus sur le sujet.

**Comment by metourneau** [comment]
Effectivement, j'ai développé sur la version 2.5.0. La PR sur la branch de dev embarque pleins de fichiers non modifiés.
La branch est disponible ici => github.com/metourneau/GeoNature/tree/geofit/pelophylax

**Comment by joelclems** [comment]
Sauf bug non repéré
Les medias sont effacés (en fait renommés en deleted_....) si le delete est effectuée par sqla.
Si la suppression se fait en base, les fichiers ne sont pas modifiés
Il y aurait effectivement besoin d'une procédure de mise à jour des médias (exécutée au début d'un appel d'une api qui concerne les médias)

**Comment by camillemonchicourt** [comment]
Attention, les médias ont un fonction bien à part et sont notamment stockés dans une table transversale bien à part. Voir https://github.com/PnX-SI/GeoNature/issues/620

Du coup il n'est pas prévu, ni recommandé d'utiliser les champs additionnels pour des médias. C'est pour cela que les médias que vous chargez comme des champs additionnels, ne sont pas stockés correctement dans la table dédiée, donc sont considérés comme orphelins, donc renommés ensuite en "deleted_..."
Le widget "medias" peut s'afficher dans les champs additionnels car il fait partie du Dynamic-form, cependant cela va le stocker mélangé avec les autres champs additionnels et poser différents soucis : 
- Des médias proprement rangés dans la table dédiée et des médias stockés dans les champs additionnels au milieu des informations attributaires
- Ce mélange des médias aux milieux des attributs additionnels va poser des soucis au niveau de l'affichage des champs additionnels classiques, mais aussi au niveau des exports

Les champs additionnels sont fait pour stocker les champs attributaires classiques (texte, liste, booléen), mais pas les médias qui ont un fonctionnement plus complexe et particulier. Et mélanger les 2 dans un même champs additionnel est fortement déconseillé.
Cela posera des soucis dans les exports et ne fonctionnera pas dans l'affichage des champs additionnels et des médias dans Synthèse et Validation.

Pour les médias, nous pensons qu'il faut garder l'utilisation des médias classiques déjà existants. Et si il faut des médias bien particuliers pour un JDD, alors il faut plutôt mettre un bloc de texte HTML avant les médias, indiquant les médias attendus pour ce JDD.

**Comment by joelclems** [comment]
Une solution pour pouvoir cadrer la saisie des médias, serait de pouvoir rajouter des champs additionels dansle formulaire des medias

par exemple ici un champs de type nomenclature avec la liste de types de prise de vue

ces champs additiononels seraient définis par un input `additionalFields` dans les composant médias
comme le composant medias  utilise lui même les formulaire dynamique ce serait possible à mettre en oeuvre (les champs additionels viennent juste s'ajouter aux champs existants)

ces champs seraient stockés dans un champs `additional_data` JSONB dans gn_commons.t_medias

**Comment by metourneau** [comment]
Pour le moment j'ai un peu triché. On peut ajouter le type media pour les dénombrements dans la configuration. Mais ils sont enregistrés dans les médias "classiques". L'avantage c'est que l'utilisateur est bien tenu par la main pour saisir ses photos ou ses sons avec titre/description/type de média pré remplis. Et toutes les fonctionnalités des médias sont conservées. L'inconvénient, c'est que lorsqu'il retourne sur son observation dans ocxtax, tous les médias se retrouve dans le champ médias, et ne sont donc pas classés comme lors de la saisie.

**Comment by camillemonchicourt** [comment]
OK pourquoi pas si ça ne tord pas le code d'Occtax et des médias.

**Comment by metourneau** [comment]
`//Champs additionnel de type media, On  l'enregistre dans les medias pour plus de maintenabilité et le gérer comme tout type de média
    this.form.value.cor_counting_occtax.map(counting => {
      if(counting.additional_fields){
        ModuleConfig.add_fields[this.idDataset]['counting'].map((widget) => {
          if(widget.type_widget == 'medias'){
            if (counting.additional_fields[widget.attribut_name]){
              counting.additional_fields[widget.attribut_name].forEach((media, i) => {
                counting.additional_fields[widget.attribut_name] = null;
                counting.medias.push(media);
              });
            }
            delete counting.additional_fields[widget.attribut_name];
          }
        });
      }
    })`
Voila le bout de code ajouté dans le submit des occurrences. Ce n'est pas très lourd. 
Ça ne tord pas l'existant mais ça ressemble un peu du spécifique.

**Comment by camillemonchicourt** [comment]
La PR #1094 de @metourneau a été reprise par Théo dans une branche dédiée, puis une PR en cours de relecture (https://github.com/PnX-SI/GeoNature/pull/1363).

En complément, une reprise du code Angular du module Occtax, mais aussi le passage de la définition des champs additionnels de Occtax dans la BDD plutôt que dans une configuration json, avec leur administration dans l'Admin de GeoNature : 

![image](https://user-images.githubusercontent.com/4418840/116856833-122d5080-abfc-11eb-8ef8-7ebe419c191e.png)

La table des champs additionnels a été créée dans le schéma ``gn_commons``, même si elle n'est utilisée que par Occtax pour le moment, car elle pourra servir dans d'autres modules à terme.

L'association d'une liste de taxons particulière à un JDD d'Occtax a été basculée dans la table des JDD et est administrable dans le formulaire des JDD.
En bonus, il est désormais possible de n'associer aucune liste de taxons à Occtax pour taper directement dans tout Taxref, ou de définir ce comportement de ne pas avoir de liste de taxons, uniquement pour certains JDD.

![image](https://user-images.githubusercontent.com/4418840/116857742-96340800-abfd-11eb-8a96-5b59ccc0edf5.png)

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.7.0.
Il est possible d'associer un champs additionnel à un JDD particulier ou non.
Si un champs additionnel n'est associé à aucun JDD, alors il s'applique à tous les JDD d'Occtax.
