### ISSUE TITLE
Lien MTD/Metadonnées

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#1008]
Le lien MTD/Metadonnées avait été construit dans le contexte DEPOBIO:
A la connexion d'un utilisateur, on récupère tous ses JDD. On met que l'utilisateur est "contact principal" du JDD, mais on ne renseigne pas les autres éventuels acteurs du JDD

Il faut parser les acteurs du JDD et renseigner correctement la correspondant JDD/acteurs.

**Comment by camillemonchicourt** [comment]
Oui en lien avec https://github.com/PnX-SI/GeoNature/issues/922

A voir aussi comment faire pour réconcilier les acteurs (personnes ou organismes) entre MTD et GeoNature. UUID commun ?

**Comment by TheoLechemia** [comment]
Seul des organismes sont rattachés au JDD et CA.
Utiliser en priorité l'UUID organisme pour faire la réconciliation (voir s'il existe déjà en BDD: `utilisateurs.bib_organismes`), sinon essayer de faire la réconciliation sur le nom

**Comment by jpanijel** [comment]
@alainlaupinmnhn > L'ensemble des champs "Contacts" saisis dans l'application MTD de l'INPN n'est pas récupéré dans le module GeoNature. Il manque notamment :
Contacts Plateforme, Fournisseurs, Producteurs, Contacts de la base de données de production. Chacune de ces informations de contact (organisme, SIRET, Nom, Email) peuvent contenir une ou plusieurs réponses. L'information Base de production (nom ex. Silène) serait aussi utile à récupérer je pense. 
Ces informations sont diffusées dans le web service MTD INPN (voir les infos avec Noémie); il faut les intégrer dans la table Dataset du module Métadonnées de GeoNature.

**Comment by DonovanMaillard** [comment]
Bonjour, pour info : 
Selon le script utilisé, l'ensemble des acteurs peut déjà etre récupéré via le service MTD INPN dans le schéma utilisateur (table bib_organisme). Par exemple sur l'instance du pole invertébrés on a bien les fournisseurs, producteurs, contacts principaux etc. Seule la base de production n'est pas stockée pour le moment. 

En revanche ces informations ne sont pas dans la table dataset, mais dans la table organismes et les correspondances cor_dataset_actor.

**Comment by camillemonchicourt** [comment]
A noter aussi, les acteurs d'un JDD peuvent être des organismes et/ou des personnes.

**Comment by alainlaupinmnhn** [comment]
Voici la liste de correspondance entre les différents acteurs sortis dans les fichiers XML de MTD et la table t_nomenclatures de Geonature :

(_`<balise XML MTD>`_ => _id_nomenclature_	|	_id_type_	|	_cd_nomenclature_	|	_mnemonique_)

### XML JDD :
- `<jdd:pointContactPF>` => 367	|	109	|	1	|	Contact principal
- `<jdd:pointContactJdd>` => 371	|	109	|	5	|	Fournisseur du jeu de données
- `<jdd:pointContactJdd>` => 372	|	109	|	6	|	Producteur du jeu de données
- `<jdd:contactBaseProduction>` => 373	|	109	|	7	|	Point de contact base de données de production

### XML Cadre d'Acquisition :
- `<ca:acteurPrincipal>` => 367	|	109	|	1	|	Contact principal
- `<ca:acteurAutre>` => 368	|	109	|	2	|	Financeur
- `<ca:acteurAutre>` => 369	|	109	|	3	|	Maître d'ouvrage
- `<ca:acteurAutre>` => 370	|	109	|	4	|	Maître d'oeuvre

**Comment by camillemonchicourt** [comment]
Attention, les ``id_nomenclature`` peuvent être variables d'une instance de GeoNature a une autre. C'est pour ça qu'on utilise jamais les ``id_nomenclature`` dans le code, mais seulement les codes.

**Comment by camillemonchicourt** [comment]
Mémo du fonctionnel actuel pour le lancement de DEPOBIO2 : 

![20201216_161915](https://user-images.githubusercontent.com/4418840/102369573-640e6a80-3fbc-11eb-8251-07e8f1efff05.jpg)

**Comment by camillemonchicourt** [comment]
Désormais on récupère bien les acteurs, mais pour chaque rôle on ne prend que les organismes. 
Dans MTD, poru chaque rôle on saisit en double un organisme et une personne (optionnelle) par organisme.
On a mis la récupération des personnes de côté pour le moment, car ce n'était pas forcément pertinent et en partie redondant : https://github.com/PnX-SI/GeoNature/issues/1196
