### ISSUE TITLE
Affichage des cadres d'acquisition et des jeux de données - Métadonnées - UX 

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/GeoNature#1010]
Je souhaitais partager mon retour d'utilisation de la page métadonnées utilisée pour traiter les cadres d'acquisitions et jeux de données. 

Est-ce qu'on peut laisser le choix à l'utilisateur de combien il en souhaite par pages ? (10, 50 ou 100) ou imposer un plus grand nombre ? Là avec 10 je dois cliquer deux fois pour atteindre ceux tout en bas. 

Ensuite un affichage dans l'ordre alphabétique des cadres pourrait être plus intuitif et faciliter la recherche en scroll ?

Merci pour les futurs retours et avis !

**Comment by camillemonchicourt** [comment]
Oui un paramètre serait bien. Dans tous les cas, 10 par défaut c'est galère. A minima, passer à 50 par page.

**Comment by Adrien-Pajot** [comment]
Ce qui pose la question de laisser à l'utilisateur un plus large choix de fonctionnalité paramétrables et donc d'une page dédiée aussi ?

**Comment by camillemonchicourt** [comment]
Non, je parle d'un paramètre au niveau d'une instance GeoNature.
Ce n'est pas utile de demander à chaque utilisateur de se paramétrer des choses.

**Comment by Adrien-Pajot** [comment]
En plus des deux demandes de cette issue, une troisième : 
Le nom du cadre d'acquisition intègre l'identifiant, est-ce important ? Pour une classification alphabétique ça ne servirait pas de le garder

**Comment by TheoLechemia** [comment]
Fait: https://github.com/PnX-SI/GeoNature/commit/53ea56b3b7bd35c18c0cc06015b8d1040bbd941d et https://github.com/PnX-SI/GeoNature/commit/6ca5789d445eb31c8cee2b5ec311f50f10995019

**Comment by Adrien-Pajot** [comment]
Test
