### ISSUE TITLE
Drop column with cascade

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/GeoNature#1016]
Attention l'usage de cascade est un peu "violent"
Si l'utilisateur a créé des vues spécifiques elles seront supprimées avec uniquement un petit message

https://github.com/PnX-SI/GeoNature/blob/1ecf3cfb9fb1cdbd6b4ea39d7c8d53a9f2de7bdc/data/migrations/2.4.1to2.4.2.sql#L298

Il faut bien faire attention à soit 
- le préciser dans les notes de version avec un grand warning
- revoir le fonctionnement de la mise à jour : bloquer la mise à jour tant que des vues autres que v_synthese_for_export, v_synthese_for_web_app, v_synthese_decode_nomenclatures, ... utilise le champ `id_nomenclature_obs_technique`

**Comment by camillemonchicourt** [comment]
OK tu as une solution pour bloquer la suppression des vues ? Ça me semble idéal.

**Comment by amandine-sahl** [comment]
On peut faire un truc du genre 

```
 DO $$
   BEGIN 
    IF (
        SELECT count(*)
        FROM information_schema.view_column_usage
        WHERE table_name = 'synthese' AND table_schema = 'gn_synthese' AND column_name = 'id_nomenclature_obs_technique'
        AND NOT view_schema || '.' || view_name IN ('gn_synthese.v_synthese_for_export', 'pr_occtax.v_releve_occtax', 'gn_synthese.v_synthese_decode_nomenclatures', 'gn_synthese.v_synthese_for_web_app', 'gn_commons.v_synthese_validation_forwebapp', 'gn_synthese.v_synthese_for_export')
        ) > 0
    THEN
        RAISE EXCEPTION 'Des vues doivent supprimées puis recrééer avant de relancer le script car elles dépendent de la colonne id_nomenclature_obs_technique ';
    ELSE
        RAISE NOTICE 'Pas de soucis de cascade lancer la suite du script ....';
        -- CODE 
    END IF;
   END
 $$ language plpgsql;
```

Mais je ne suis pas sur que ce soit le top

**Comment by camillemonchicourt** [comment]
Vas-y 😀

**Comment by lpofredc** [comment]
Ah ben j'étais justement dans cette problématique pour gérer des objets dependants de vues ou de champs... J'avais donc fait une fonction qui permet de lister les vues et vues matérialisées dépendantes d'une colonne. Et plus récemment une autre qui génère les requêtes de drop/create des vues et vues matérialisées dépendants d'une relation, utile lors d'un changement de typage d'un champ.

https://gist.github.com/lpofredc/b72eec930f45330c931c5c8e5e86d5ba

https://gist.github.com/lpofredc/e871541105322c5d571788812decdc84

**Comment by camillemonchicourt** [comment]
Dans un contexte assez similaire, @amandine-sahl a fait des fonctions dans TaxHub, utilisées lors de la migration de Taxref pour identifier des vues dépendantes, les sauvegarder, les supprimer, puis les recréer après avoir appliquer les modifications : https://github.com/PnX-SI/TaxHub/blob/master/data/generic_drop_and_restore_deps_views.sql

A noter aussi tant qu'on y est, pour modifier la taille d'un champs sans galérer avec les dépendances : https://sniptools.com/databases/resize-a-column-in-a-postgresql-table-without-changing-data/

**Comment by amandine-sahl** [comment]
Sinon voir => https://github.com/PnX-SI/Ressources-techniques/blob/master/PostgreSQL/vues_dependantes.rst

Par contre dans le cas présent je ne pense pas que l'automatisation soit vraiment possible. Les utilisateurs doivent revoir leurs vues car on supprime une colonne.

**Comment by camillemonchicourt** [comment]
Fait dans le script SQL de migration vers GeoNature 2.5.0, qui commence par vérifier et lister les vues dépendants d'un champs, pour les modifier ou les supprimer avant de continuer le script.

Et pour la méthode permettant de redimensionner un champs sans modifier toutes les tables et vues qui l'utilisent, cela a été utilisé dans la migration vers UsersHub 2.1.3.

Et noté dans les ressources partagées : https://github.com/PnX-SI/Ressources-techniques/blob/master/PostgreSQL/update_character_length.rst
