### ISSUE TITLE
Dynamic form : ajouter un composant select avec un Input api

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#1029]
Créer un nouveau composant de sélection à partir d'une liste pour le formulaire dynamique qui peut récupérer ses données à partir d'une api (on peut intégrer ou reprendre le composant `pnx-multiselect`)
 
avec comme inputs:

- `multiple`
- `searchBar`: possibilité de chercher dans la liste
- pour les données
  - `url`:  api de GN pour recupérer les données à partir d'une requete
    - avec une options pour dire que l'api et de GN ou de TaxHub
  - ou `values`: les données en dur
  - `keyValue`: le champs de la valeur renvoyée par le composant
  - `keyLabel`: le champs de la valeur affichée
  - `returnObject`: renvoie l'objet entier si `true` 
- pour l'affichage:
  - `typeDisplay`: affichage sous forme de select, ou de radio/checkbox, bouttons ou autres...

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.5.0

**Comment by joelclems** [comment]
Je réouvre l'issue  car le composant peut encore être amélioré/complété

- [ ] passage en **bootstrap** pour ne pas dénoter avec le reste (en modifiant le .html et à minima le .ts) *aide requise*
  - [ ] faire select avec un champs de recherche et des chips,  multiple ou simple

- [ ] **options d'affichage**
  - [ ] possibilté de choisir entre `select` et `radio` (choix simple) ou `checkbox` (choix multiple)

- [ ] **autocomplete** (l'api est rappelée à chaque changement du champs de recherche)
  - [ ] en choix simple
  - [ ] en choix multiple (plus dur??) 

- [ ] documenter
