### ISSUE TITLE
Renommage des fichiers de config exemples

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature#1034]
Il me semblerait plus lisible de pouvoir profiter de la coloration syntaxique des nos éditeurs de texte au niveau des fichiers de config d'exemples.

Pour permettre cela, je vous propose de modifier les extension `.ini.sample`, `.toml.example` et `.toml.sample` par `.sample.ini`, `.example.toml` et `.sample.toml`.

Cela implique de:
- [ ] corriger le scripts y faisant référence
- [ ] corriger la documentation y faisant référence

 Ce n'est pas primordial, mais cela fait un moment que cela me démange... Je souhaiterai recueillir votre avis sur le sujet ?

**Comment by camillemonchicourt** [comment]
Pas d'avis particulier sur le sujet, OK.

**Comment by DonovanMaillard** [comment]
Ce n'est pas un besoin particulier de mon côté et peut être pas un sujet prioritaire (comme la traduction en anglais des bib_ dans la bdd par exemple) , mais pas un soucis non plus si ca change :)

**Comment by RomainBaghi** [comment]
Bien vu, c'est en effet agaçant de voir ces fichiers d'exemple tout en gris alors que c'est tellement plus lisible en couleur.

**Comment by jbdesbas** [comment]
Le coté positif du *.exemple ou *.sample c'est qu'on voit tout de suite dans le navigateur que ces fichiers ne sont pas pris en compte (on les distingues ainsi des "vrais" fichier de conf).
A voir aussi côté script, c'est plus facile de faire `config.py.sample --> config.py` que `config.sample.py --> config.py`
La méthode actuellement utilisée semble être du coté des bonnes pratiques (cf nommage des logs rotatifs sur la plupart des systèmes : machin.log, machin.log.1, machin.log.2 , etc. )

**Comment by jpm-cbna** [comment]
À défaut, de trouver une quelconques recommandation sur le sujet dans les conventions de codage, j'ai recherché dans Github les 2 possibilités.  Effectivement le nommage actuel est le plus présent mais l'alternative existe... 

Ceci dit, je reste dubitatif sur le choix actuel car je suis plus souvent entrain de consulter ces fichiers que de les renommer. Et comme le dit @RomainBaghi c'est plutôt agaçant et largement moins lisible de les voir s'afficher systématiquement sans coloration syntaxique.

Aucun consensus ne semble ressortir pour l'instant. N'hésiter pas à rajouter des émojis de pouce vers le haut ou le bas sur l'un ou l'autre avis pour essayer de trancher la question.

**Comment by RomainBaghi** [comment]
Dommage que les éditeurs ne soient pas plus intelligents pour détecter le langage... 
La remarque de Jbdesbas est pertinente mais n'y a t-il pas des ruses en bash pour manier les renomages/recherches sans trop de difficultés même si le .sample n'est pas à la fin ? (ls *.sample.* )
C'est peut être moins fiable par contre.

**Comment by TheoLechemia** [comment]
Sur ce sujet qui semble autant passionner les foules, j'ai trouvé une solution pour que tout le monde puisse trouver le sommeil avec des variables colorés pleins les yeux :smiley: 

![image20](https://user-images.githubusercontent.com/15265745/93190438-aa48f900-f743-11ea-817d-e71899d8f9e0.png)

sur vscode, et la plupart des éditeurs, selectionnez le language du fichier en cliquant en bas à droite de l'écran, et les couleurs apparaissent :boom:

**Comment by jpm-cbna** [comment]
L'alternative proposé par @TheoLechemia est pas mal !
Pour les utilisateurs de Vim, il détecte correctement le type de fichier malgré l'extension terminant par `.sample` ou `.example`. Mais, si nécessaire, pour réaliser l'équivalant de la proposition de @TheoLechemia, il existe [plusieurs solutions](http://vimdoc.sourceforge.net/htmldoc/filetype.html#new-filetype) (voir la possibilité B).
