### ISSUE TITLE
Exports depuis la synthèse instables

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1039]
Sur la 2.4.1, et reproduit sur le serveur démo, l'export des métadonnées fonctionne parfois mais pas toujours. 

Si je télécharge les métadonnées des 100 premières obs affichées par exemple en arrivant sur la synthèse, ca semble OK dans mon cas. Mais si je fais une requête, des fois c'est bon des fois non. Sur le serveur démo par exemple, il suffit de sélectionner ou un deux Cadres d'Acquisition dans la requête pour que l'export ne fonctionne pas. 

Si je recherche avec un zonage geojson en particulier, ça ne marche pas non plus (ça vient peut être des données à récupérer, dans tous les cas il n'y a pas que le fait de requêter sur un cadre qui génère le soucis).

**Comment by DonovanMaillard** [comment]
En y regardant de plus près, ça semble pouvoir toucher tous les exports, pour les données, les métadonnées, aux formats shp, csv etc... 

à creuser ... Pour une même requête je peux télécharger le csv mais pas les métadonnées et les données en shp. Pour la même requête sur une autre instance, je ne peux rien télécharger, pas même le csv... Y compris sur la démo

**Comment by jpm-cbna** [comment]
@DonovanMaillard est ce que ton problème est comparable à celui-ci cbn-alpin/silene-geonature#28 ?

**Comment by DonovanMaillard** [comment]
Salut, 

Oui, très semblable, d'autant que je vois que tu avais requêté une espèce en particulier. Je n'avais pas testé sur les taxons mais j'avais ce comportement sur les métadonnées quand je requêtais un JDD ou un CA. 

Par contre il me semble que @TheoLechemia s'est penché sur la question dernièrement. A retester sur la 2.5.2 et voir si ce ticket est toujours valable.

**Comment by amandine-sahl** [comment]
A mon avis c'est en lien avec :  #883

**Comment by jpm-cbna** [comment]
@amandine-sahl Merci pour l'info. @DonovanMaillard  c'est donc surement corrigé dans la dernière version comme tu l'indiques. Je devrais mettre à jour l'instance de test de Silene dans une version develop qui intègre mes branches de développements fin octobre/début novembre. Je vérifierai si c'est réglé pour moi à cet occasion et je vous tiens au courant.

**Comment by TheoLechemia** [comment]
Oui c'est en lien avec #883 . Corrigé dans la 2.5.0
