### ISSUE TITLE
Problème lors de la migration entre les versions 2.0.1 et 2.1.0

### ISSUE THREAD

**Issue by geobrun** [PnX-SI/GeoNature#1045]
Bonjour,

J'ai récupéré le travail du précédent géomaticien de notre structure qui avait déployé GeoNature avec l'aide d'une stagiaire en juin 2019. J'ai mis à jour TaxHub et UsersHub dans leur dernière version sans grand souci en installant chaque version intermédiaire (TaxHub à 1.6.2 vers 1.7.2 et Usershub 2.0.3 vers 2.1.2). Je cherche maintenant à mettre à jour GeoNature de la version 2.0.1 à la version 2.1.0.

J'ai lancé le script suivant à partir du dossier "geonature" :

  ```console
sudo ./install/migration/migration.sh
  ```

Malheureusement, ce script ne va pas jusqu'au bout. Plus précisément, il n'arrive pas à exécuter les commandes "geonature" : 
  ```console
geonature update_configuration --build=false
geonature generate_frontend_modules_route
geonature generate_frontend_tsconfig
  ```

L'explication est qu'il n'arrive pas à charger le script "geonature_cmd.py" pour utiliser les commandes "geonature" (si j'ai bien compris comment cela fonctionne). C'est ce que je devine d'après le message d'erreur :
  ```console
Error: You must be in the GeoNature virtualenv to be able to run this script.
The virtualenv is made available once GeoNature has been installed and it's default directory is '/home/geonatureadmin/geonature/backend/../backend/venv'.
You can activate it by doing "source /home/geonatureadmin/geonature/backend/../backend/venv/activate/bin/activate".
If you installed GeoNature outside of a virtualenv, you can bypass this check by setting the GEONATURE_NO_VIRTUALENV env var to 1.
How ever, this setupis not officially supported by the GeoNature team.
  ```
Avant ce message d'erreur, il n'y a que deux warnings qui apparaissent :
  ```console
WARNING: The directory '/home/geonatureadmin/.cache/pip' or its parent directory is not owned or is not writable by the current user.
The cache has been disabled. Check the permissions and owner of that directory.
If executing pip with sudo, you may want sudo's -H flag.
  ```
et
  ```console
WARNING: You are using pip version 20.0.2; however, version 20.2.3 is available.
You should consider upgrading via the '/home/geonatureadmin/geonature/backend/venv/bin/python -m pip install --upgrade pip' command.
  ```

La commande
  ```console
source venv/bin/activate
  ```
me permet bien de rentrer dans l'environnement virtuel mais la commande suivante 
  ```console
python ../geonature_cmd.py install_command
  ```
donne l'erreur citée auparavant : "You must be in the GeoNature virtualenv to be able to run this script."

Quelqu'un a une idée pourquoi ce script python ne veut pas s'exécuter alors que l'environnement virtuel est bien activé dans la console ?

**Quelques informations sur mon environment**

- OS: Ubuntu 18.4.5 LTS (serveur Kimsufi OVH)
- Version de python : 3.6.9
- Version de pip : 20.2.3 (mais qui dit être lié à Python 2.7 ?)

**Comment by camillemonchicourt** [comment]
Sauf mention spécifique dans les notes de version, il ne faut pas passer par les versions intermédiaires. 
Il faut directement passer aux versions récentes.
Par contre il faut bien lire et appliquer les notes des versions intermédiaires, notamment les évolutions de BDD.

**Comment by TheoLechemia** [comment]
Oui comme le dit Camille, essayez d'installer la 2.4.1. Si ça ne fonctionne pas on pourra investiguer un peu plus

**Comment by geobrun** [comment]
Ok, je vais tester ça.

**Comment by geobrun** [comment]
J'ai essayé d'appliquer ce matin les notes intermédiaires indiquées pour passer de la version 2.0.1 à la version 2.1.0, sans passer par le script de migration. Malheureusement, je reçois un message d'erreur quand je tape la commande pour installer le module de validation :
```console
geonature install_gn_module /home/`whoami`/geonature/contrib/gn_module_validation/ /validation
```
Voici le message d'erreur que je reçois : 
```console
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 58, in install_gn_module
    raise GeoNatureError("dir {} doesn't exists".format(module_path))
geonature.utils.errors.GeoNatureError: dir /home/geonatureadmin/geonature/contrib/gn_module_validation/ doesn't exists
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 3, in <module>
    geonature.core.command.main()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 131, in install_gn_module
    ).format(module_code, ex)
UnboundLocalError: local variable 'module_code' referenced before assignment
```

D'après ce que je comprends au début du message, l'erreur se produit car il n'y a pas de dossier "gn_module_validation" dans le dossier "contrib" de GeoNature. Effectivement, comme je pars d'une version 2.0.1 de GeoNature pour faire ma mise à jour, ce module n'existe pas. J'ai donc copié le dossier "gn_module_validation" à partir de la version 2.1.0 pour la mettre dans ma version 2.0.1, puis relancé la commande d'installation du module de validation. Il y a du mieux, mais je reçois un nouveau message d'erreur : 
```console
/home/geonatureadmin/geonature/backend/venv/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
checking file
...ok
checking manifest
...ok
Checking file conformity
      install_gn_module  OK
cannot import name 'VLatestValidations'
Error while installing GN module 'VALIDATION'.The process returned:
        Module VALIDATION
                    File /home/geonatureadmin/geonature/contrib/gn_module_validation/backend/blueprint.py must have a variable call :
                        blueprint instance of Blueprint
```

Ce message me paraît bien obscur à la vue de mes compétences ! Quelqu'un a une idée du problème ?

Par ailleurs, je me demandais s'il n'était pas plus simple dans mon cas de refaire une installation propre de GeoNature ?

**Comment by camillemonchicourt** [comment]
Je comprends pas pourquoi tu essaies d'installer la 2.1.0.
Il ne faut pas passer par des installations de versions intermédiaires, sauf mention dans les notes de version.

**Comment by DonovanMaillard** [comment]
Bonjour  

Je procéderais en 2 temps. D'abord passer tous les scripts de migration sql de chaque version, puis faire la migration.sh de l'appli vers geinzture 2.4.1. 

Une fois que vous avez un geonature fonctionnel et a jour seulement  procédez a l'installation des modules complémentaires.

**Comment by DonovanMaillard** [comment]
En pricedeant comme vous le faites vitre version du module de validation n'est pas forcement a jour avec la bdd puisque vous avancez d'un côté et pas de l'autre :)

**Comment by geobrun** [comment]
Comme il y avait marqué dans les notes de version de la version 2.1.0 qu'il fallait installer le module de validation, j'ai cru qu'il s'agissait de quelque chose d'obligatoire suivre. Du coup, j'ai essayé de passer le script SQL donné pour la version 2.1.1, mais il a généré une erreur car ce script modifie des tables sur le schéma"gn_sensitivity"créé lors de l'installation du module de validation.

Peut-être qu'il y a quelque chose que je n'ai toujours pas compris sur comment passer d'une vieille version de GeoNature à une nouvelle ?

**Comment by geobrun** [comment]
Bonjour DonovanMaillard, je comprends vous dites, cela semble être une bonne solution. Malheureusement, cela semble a priori impossible car pour passer le script SQL de la version 2.1.1, il faut un schéma créé lors de l'installation du module de validation. :(

**Comment by camillemonchicourt** [comment]
Exact, bien vu, sinon il faut jouer directement le SQL qui est dans le dossier data du module Validation.

**Comment by geobrun** [comment]
Ok, j'avais déjà passé le script en question mais il s'était soldé par un échec a priori (log quasiment vide). En fait, le script shell appelait le script SQL de la migration que je n'avais pas transféré dans mon installation 2.0.1. Je vais donc repartir de là et faire ces mises à jour intermédiaires, sans les modules optionnels pour le moment. Merci !

**Comment by geobrun** [comment]
A priori, en copiant les scripts "2.0.1to2.1.0.sql", "data/core/sensitivity.sql", "data/core/sensitivity_data.sql" et "data/core/ref_geo_grids.sql" de la version 2.1.0 pour les mettre dans ma version 2.0.1, j'ai pu exécuter le scipt Shell "2.0.1to2.1.0_bis.sh" permettant de mettre à jour la base de données de GeoNature concernant les mailles.

Dans le fichier de log, j'ai néanmoins quelques erreurs qui ont été enregistrées : 
```console
psql:tmp/geonature/sensitivity_data.sql:6: NOTICE:  table "liste_taxons_sensibles" does not exist, skipping
psql:tmp/geonature/inpn_grids.sql:34: ERROR:  relation "temp_grids_1" already exists
psql:tmp/geonature/inpn_grids.sql:42: ERROR:  relation "temp_grids_5" already exists
psql:tmp/geonature/inpn_grids.sql:49: ERROR:  relation "temp_grids_10" already exists
psql:tmp/geonature/inpn_grids.sql:593504: ERROR:  duplicate key value violates unique constraint "temp_grids_1_pkey"
DETAIL:  Key (id)=(1) already exists.
CONTEXT:  COPY temp_grids_1, line 1
psql:tmp/geonature/inpn_grids.sql:616568: ERROR:  duplicate key value violates unique constraint "temp_grids_5_pkey"
DETAIL:  Key (id)=(1) already exists.
CONTEXT:  COPY temp_grids_5, line 1
psql:tmp/geonature/inpn_grids.sql:626198: ERROR:  duplicate key value violates unique constraint "temp_grids_10_pkey"
DETAIL:  Key (id)=(1) already exists.
CONTEXT:  COPY temp_grids_10, line 1
```

Est-ce qu'il s'agit d'erreurs importantes ? Sinon je vais essayer de passer à la version suivante de la base de données.

**Comment by DonovanMaillard** [comment]
Bonjour, 

concernant la Notice, il ne s'agit que d'une notice donc ce n'est en général pas bloquant. Concernant les Erreurs, il semble que les mailles 1/5/10km aient été créées à 2 reprises donc vous avez une erreur car les scripts tentent de rentrer des mailles déjà dans la base. 

Avant de poursuivre, vous pouvez tout de même vérifier : 
- Si vous avez bien des données dans le ref_geo pour les mailles 1, 5 et 10km, et si leurs nombres sont cohérents
- Si le schéma sensitivity est bien en place et comporte des données cohérentes. La table liste taxons sensibles semble être une table temporaire (je ne l'ai pas dans nos instances à jour), il faut voir dans le script ce qu'elle devait alimenter. Il y a peut être un COPY qui se fait en amont, avant le lancement du script sql. 

Pour les mailles, pour info sur une instance à jour sur la france métro, on a : 354800 Mailles 1km, 23060 Mailles 5km et 9625 Mailles 10km

**Comment by geobrun** [comment]
A priori, mon schéma "gn_sensitivity" est bien en place et il y a des données dans les tables qui sont dedans. Après avoir analysé les scripts SQL, la table" liste_taxons_sensibles" est effectivement une table temporaire. Elle est créée en début de script à partir d'un fichier CSV puis détruite en fin de script. Je suppose donc qu'il n'y a pas eu de problème d'import.

Pour les mailles, j'ai les mêmes résultats que vous, sauf pour les 1km où j'ai 593 450 entrées !

Je vais donc avancer !

**Comment by geobrun** [comment]
J'ai avancé la mise à jour de la BDD à la version 2.3.0 de GeoNature sans souci. En retestant GeoNature, mes utilisateurs ne peuvent plus se connecter, l'administrateur non plus. Par contre, je peux me connecter à UsersHub en adminsitrateur et tout semble correct de ce côté. De plus, si je suis connecté en administrateur sur UsersHub, cela me connecte sur GeoNature dans une version limitée où seuls "Accueil" et "Export" sont visibles sur le côté gauche. Cela ressemble fortement à ce problème : https://github.com/PnX-SI/GeoNature/issues/591

A l'époque, la personne avait totalement réinstallé GeoNature. DonovanMaillard avait proposé de mettre à jour GeoNature dans une version plus récente. Je vais donc poursuivre la migration avec les scripts SQL puis installer la dernière version de GeoNature et voir si cela règle le problème (en croisant les doigts). A moins que quelqu'un ait une idée pour régler ce problème avant que je continue ?

**Comment by DonovanMaillard** [comment]
A voir si Camille a des éléments, mais personnellement je continuerais jusqu'à la fin des MAJ. 

Il m'est arrivé sur les précédentes version d'avoir ce soucis, sans savoir si c'est un problème de cache ou autre. Dans tous les cas, en redémarrant à la suite postgresql puis l'ensemble applicatif et en vidant mon cache, ca fonctionnait de nouveau : de mémoire ça doit être
sudo /etc/init.d/postgresql restart
sudo supervisorctl restart all

Peut être qu'il n'y a pas besoin de tout relancer mais j'ai pris l'habitude de faire cette manipulation quand j'avais le soucis ;)

**Comment by geobrun** [comment]
Merci pour l'information ! Effectivement, il devait y avoir un problème au niveau des services. Je n'ai pas eu le temps de lancer vos commandes car en me connectant ce matin, le serveur me demandait de le redémarrer. J'ai donc fait un : 
```console
sudo reboot now
```

Ce qui a eu pour effet de redémarrer les services comme vous me le conseilliez. Je peux de nouveau me connecter en tant qu'utilisateur ! Par contre, c'est l'interface de TaxHub qui est de nouveau inaccessible. Ça m'arrive régulièrement : la page est bien chargée mais elle n'affiche rien. Pour régler ce problème, j'ai testé les commandes que vous m'avez indiquées mais elles n'ont eu malheureusement aucun effet. Je vais poursuivre la mise à niveau car c'est un problème que j'ai déjà rencontré par le passé et qui s'est toujours résolu !

**Comment by DonovanMaillard** [comment]
Super ! 

Pour taxhub, attention à votre URL.... il y a un petit couac qui traine, si votre url est du type mondomaine/taxhub, il faut bien mettre un / à la fin : mondomaine/taxhub/. Sans ça, il ne charge pas le contenu. personnellement j'ai passé taxhub, usershub et geonature sur des sous domaines qui leur sont propres

**Comment by geobrun** [comment]
Super, c'était exactement ça le problème ! Du coup, pour éviter ce genre de souci, vous conseillez de passer d'une URL du type "geonature.pnr-millevaches.fr/taxhub/" à une URL du type "taxhub.pnr-millevaches.fr" ?

Après installation de la version 2.4.1, je me retrouve avec une erreur 403 en allant sur mon site GeoNature. TaxHub et UsersHub fonctionnent encore, il doit y avoir un problème de redirection quelque part ? Mon fichier " /etc/apache2/sites-available/geonature.conf" est bien conforme à ce qui est marqué dans la documentation.

Voilà quelques anomalies que j'ai relevées lors du passage du script de migration de la version 2.4.1 : 
```console
cp: cannot stat '/home/geonatureadmin/geonature/../geonature_old/backend/static/images/*': No such file or directory
cp: cannot stat '/home/geonatureadmin/geonature/../geonature_old/backend/static/mobile/*': No such file or directory
cp: cannot stat '/home/geonatureadmin/geonature/../geonature_old/backend/static/exports/*': No such file or directory
rm: cannot remove 'external_modules/validation': No such file or directory
rm: cannot remove 'external_modules/occhab': No such file or directory
cp: cannot stat '/home/geonatureadmin/geonature/../geonature_old/contrib/gn_module_validation/config/conf_gn_module.toml': No such file or directory
cp: cannot stat '/home/geonatureadmin/geonature/../geonature_old/contrib/gn_module_occhab/config/conf_gn_module.toml': No such file or directory
cp: cannot stat '/home/geonatureadmin/geonature/../geonature_old/backend/static/medias/*': No such file or directory
```

Si je comprends bien, ces erreurs ne doivent pas poser de problème car il s'agit de récupérer des fichiers de configuration de l'ancienne version de GeoNature. Comme cette dernière n'avait presque pas été personnalisée, je ne pense pas que cela pose problème. Voici d'autres erreurs : 
```console
Installation du virtual env...
ERROR:root:ImportError: cannot import name 'ensure_text'
./install/migration/migration.sh: line 102: venv/bin/activate: No such file or directory
Defaulting to user installation because normal site-packages is not writeable
```
Et plus loin : 
```console
WARNING: You are using pip version 20.0.2; however, version 20.2.3 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
GeoNature requires Python 3.5 or higher. Check that you have installed GeoNature and that you have activated the GeoNature virtualenv.
Update configurations
./install/migration/migration.sh: line 122: geonature: command not found
./install/migration/migration.sh: line 123: geonature: command not found
./install/migration/migration.sh: line 124: geonature: command not found
./install/migration/migration.sh: line 125: geonature: command not found
./install/migration/migration.sh: line 126: geonature: command not found
./install/migration/migration.sh: line 127: geonature: command not found
./install/migration/migration.sh: line 128: geonature: command not found
./install/migration/migration.sh: line 130: geonature: command not found
Restarted supervisord
./install/migration/migration.sh: line 134: deactivate: command not found
```

Problème au niveau du virtualenv ?

**Comment by DonovanMaillard** [comment]
Sur l'URL, soit stocker un favoris avec le / pour éviter de l'oublier. Soit en effet, plus propre, le passer sur un sous-domaine (ou faire une redirection dans la conf apache qui ajoute un / à la fin, c'est possible aussi). 

Pour les retours de migration.sh, effectivement il cherche soit des fichiers personnalisés donc pas de soucis, soit des fichiers des modules validation ou occhab que vous n'avez pas encore à priori, donc pas de soucis à ce niveau. 

Enfin pour la fin, pouvez-vous vérifier votre  version de python? Ou vos versions de pythons s'il y en a plusieurs ?

**Comment by camillemonchicourt** [comment]
Je suis de loin, mais pour l'URL de TaxHub, on a pas mal galéré avec le slash.
Mais il est possible de mettre en place une redirection : https://github.com/PnX-SI/TaxHub/blob/master/docs/installation.rst#configuration-apache

> Si vous souhaitez que TaxHub soit accessible sans slash à la fin, par exemple sur http://ADRESSE_DU_SERVEUR/taxhub, ajoutez ces 2 lignes dans le Virtualhost du fichier /etc/apache2/sites-available/000-default.conf :
> 
> RewriteEngine  on
> RewriteRule    "taxhub$"  "taxhub/"  [R]

**Comment by geobrun** [comment]
Super, ça marche pour l'astuce de Camille avec TaxHub ! Je vais rester comme ça pour le moment.

Pour Python,
```console
python -V
```
me retourne Python 2.7.17 et

```console
python3 -V
```
me retourne Python 3.6.9

**Comment by DonovanMaillard** [comment]
Sur cette partie, je vais laisser @TheoLechemia apporter les réponses, je maitrise beaucoup moins. Mais il est possible (voire probable au vue des erreurs) que ca soit Python 2.7 qui soit lancé par défaut et non pas la 3.6. 

Si votre serveur n'héberge que GeoNature, à voir s'il faut conserver la 2.7. Sinon, il y a sans doute quelque chose à faire pour que ca soit 3.6 qui soit utilisée par défaut...

**Comment by geobrun** [comment]
Ok, merci pour votre aide en tout cas ! :)

Pour python, j'ai testé la solution donné en remplaçant une ligne dans le script de migration : https://github.com/PnX-SI/GeoNature/issues/998

J'ai remplacé : 
```console
if [[ $python_path ]]; then
  echo "Installation du virtual env..."
  python3 -m virtualenv -p $python_path venv
else
  python3 -m virtualenv venv
fi
```
par
```console
if [[ $python_path ]]; then
  echo "Installation du virtual env..."
  python3 -m venv venv
else
  python3 -m venv venv
fi
```

La partie avec le "$python_path" donnait encore une erreur. Avec ces nouvelles lignes, j'ai encore eu des erreurs qui se sont affichées mais le site GeoNature fonctionne maintenant !

J'ai juste un dernier dysfonctionnement à régler : je peux me logger dans GeoNature en utilisant l'adresse IP du serveur, mais par contre si j'essaye de me logger en utilisant l'URL avec le nom de domaine, cela ne marche pas. Je rentre mes identifiants mais rien ne se produit quand je clique sur "Se connecter". Seule la petite roue de chargement apparaît bien, mais après, il ne se passe rien. Comme si le site n'arrivait pas à me rediriger vers l'interface de GeoNature après avoir accepté mon identification. Une idée ?

**Comment by DonovanMaillard** [comment]
Sauf erreur, GeoNature sera amené à ne plus être maintenu sur Debian9 et les versions antérieures de Python d'ici aux prochaines versions. Peut être que l'utilisation de Python3 en dur dans le script de migration pourra être une solution à terme. 

Pour l'URL, est-ce que votre fichier de configuration est bien renseigné et à jour, ainsi que les API  ?

Si vous avez redirigé votre taxhub par exemple (je ne l'ai pas fait je ne sais pas exactement ce que fait la redirection), vérifiez que la nouvelle URL de l'API taxhub n'ait pas changé par rapport à la configuration (que ca ne soit pas taxhub//api au lieu de /api par exemple?)

**Comment by jpm-cbna** [comment]
@geobrun pour l'environnement virtuel Python, j'ai eu le même problème. J'ai aussi utilisé le module "venv" à la place du module "virtualenv". Cela fonctionne très bien ainsi avec GeoNature. Je n'ai pas poussé la recherche de l'origine du problème très loin mais il me semble qu'il est apparu lorsque j'ai mis en place les 2 versions majeures de Python sur ma machine. Je pense aussi que c'est l'utilisation de "`update-alternatives`" décrite ci-dessous qui l'a résolu de manière plus définitive. 

Sous Debian, si pour une raison ou une autre, il est nécessaire d'installer les 2 versions majeures de Python, il est utile de créer une entrée dans l'outil Debian "`update-alternatives`".

Exemple pour Python 2.7 et Python 3.7 sous Debian 10 :
- `python --version` : doit afficher "Python 2.7.16"
- `update-alternatives --list python` : doit afficher "update-alternatives: erreur: pas d'alternatives pour python"
- `update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1` : ajoute l'alternative python2.7 et doit afficher "update-alternatives: utilisation de « /usr/bin/python2.7 » pour fournir « /usr/bin/python » (python) en mode automatique"
- `update-alternatives --install /usr/bin/python python /usr/bin/python3.7 2` : ajoute l'alternative python3.7 et doit afficher "update-alternatives: utilisation de « /usr/bin/python3.7 » pour fournir « /usr/bin/python » (python) en mode automatique"
-`python --version` : doit maintenant afficher "Python 3.7.3"
- `update-alternatives --list python` : doit afficher

```
    /usr/bin/python2.7
    /usr/bin/python3.7

```

- `update-alternatives --config python` : permet de configurer l'alternative et de choisir la version de Python a exécuter par défaut. Dans le cas de GeoNature, il faudra choisir la version 3.7.
- `update-alternatives --remove python2.7` : permet de supprimer une alternative (ici 2.7) dans le cas où le paquet n'est plus installé sur le système.

**Comment by geobrun** [comment]
@jpm-cbna : merci pour le conseil ! Pour l'instant, je vais garder ça comme ça. Si je vois que j'ai encore des soucis lors de la prochaine mise à jour, j'appliquerai votre solution.

@DonovanMaillard : pour l'instant, je vais finalement garder cette mauvaise configuration sur l'URL. Ça permet d'éviter à des personnes qui connaissent le nom de domaine utilisé par notre GeoNature d'essayer de s'y connecter. Cela ne pose pas de problème pour le moment car le grand public n'est pas encore sensé s'y connecter. Il faudra donc connaître l'adresse IP du serveur pour pouvoir se connecter à GeoNature (même si elle est facile à trouver une fois qu'on a le nom de domaine...). Il faudrait du coup que je fasse de même pour rendre accessible TaxHub et UsersHub uniquement sur l'adresse IP, et ne garder en accessible via le nom de domaine que notre atlas. 

Je clos donc le sujet, merci à tous pour votre aide ! :)
