### ISSUE TITLE
Récupération des JDD et sélection automatique

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1049]
Bonjour, 

Lorsqu'un utilisateur n'a qu'un jeu de données disponible, le composant "dataset" renvoie une liste à 1 choix... 

Est-ce que dans ce cas, on ne pourrait pas sélectionner directment le seul JDD disponible (plutôt que d'afficher un blanc et devoir sélectionner le seul choix dispo?). 

Dans le cas où on a un unique JDD pour un protocole/module, ça éviterait d'avoir à saisir l'info. 

![Récupération JDD](https://user-images.githubusercontent.com/23358384/93476557-3b61d080-f8fa-11ea-8af9-aafc65d3de80.png)

**Comment by joelclems** [comment]
Juste pour info, j'ai crée un composant datalist (pour l'instant dans la branche monitoring) qui crée des select depuis une api.

Quand il n'a qu'un élement dans sa liste et que l'option required à `true` l'option est automatiquement choisie

dans le cadre de monitoring: 
voici sa config pour les datalist des modules
```
"datasets": {
      "type_widget": "datalist",
      "attribut_label": "Jeux de données",
      "multiple": true,
      "type_util": "dataset",
      "api": "meta/datasets",
      "application": "GeoNature",
      "keyValue": "id_dataset",
      "keyLabel": "dataset_shortname",
      "params": {
        "active": true,
        "orderby": "dataset_name"
      },
      "data_path": "data",
      "required": true
    },

```

et le  datalist de la visite:

```
"id_dataset": {
      "type_widget": "datalist",
      "attribut_label": "Jeu de données",
      "type_util": "dataset",
      "api": "meta/datasets",
      "application": "GeoNature",
      "keyValue": "id_dataset",
      "keyLabel": "dataset_shortname",
      "params": {
        "active": true,
        "orderby": "dataset_name",
        "module_code": "__MODULE.MODULE_CODE"
      },
      "data_path": "data",
      "required": true
    },
```

du coup si on a qu'un seul jdd pour ce module, il est choisi automatiquent pour la visite

le seul bémol c'est qu'il est en material...

**Comment by DonovanMaillard** [comment]
Merci @joelclems pour ces compléments et pistes (même si je comprends pas tout ;) ) 

Ce ticket est aussi à mettre en lien avec [cette remarque de @Judith](https://github.com/PnX-SI/gn_module_import/issues/145)

**Comment by camillemonchicourt** [comment]
Le composant `dataset` sélectionne l'unique JDD dans la liste si celle-ci n'en renvoie qu'un et que le champs st obligatoire.
