### ISSUE TITLE
Texte personnalisable dans l'email de confirmation d'inscription

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature#1050]
Afin de pouvoir transmettre des consignes supplémentaires à l'utilisateur de GeoNature suite à la validation de son inscription, il serait intéressant de pouvoir utiliser un paramètre de configuration supplémentaire.

Le texte en question serait défini au format HTML et serait placé en fin d'email juste avant la signature.

Ce paramètre optionnel serait compris dans la section `ACCOUNT_MANAGEMENT`. Le nom proposé est `ADDON_USER_EMAIL`. Par défaut, aucun texte supplémentaire n'est affiché.

Exemple de paramètre:
```
[ACCOUNT_MANAGEMENT]
    ADDON_USER_EMAIL = """<p>
            Toute l'équipe de GeoNature vous remercie pour votre inscription.
        </p>"""
```

**Comment by DonovanMaillard** [comment]
Une bonne idée en effet :) niveau pratique, faut il intégrer ce contenu html directement dans la conf, ou prévoir un template dédié dans les répertoires custom?

**Comment by jpm-cbna** [comment]
L'ajout du texte est prévu via un paramètre du fichier de config `geonature_config.toml` car les templates d'email sont côté backend en Python.
Je n'ai pas vu de mécanisme en place dans la code pour la personnalisation complète des templates d'email.

Pour une personnalisation complète des emails, il est toujours possible pour l'instant de remplacer les fichiers templates au format HTML présents dans `backend/geonature/core/users/templates/`. Bien entendu, cela nécessite de venir remplacer ces fichiers à chaque installation/mise à jour de GeoNature...

**Comment by TheoLechemia** [comment]
> Je n'ai pas vu de mécanisme en place dans la code pour la personnalisation complète des templates d'email.

Non pas de mécanisme de personnalisation des emails pour l'instant. 
Va pour ta proposition @jpm-cbna en attendant de mettre en place une vrai customisation.
