### ISSUE TITLE
[2.5.0 - OccTax] Le champ "technique de collecte campanule" ne s'affiche pas

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/GeoNature#1059]
Bonjour,

Je viens de passer à GeoNature 2.5.0. en suivant la doc : je n'ai vu aucune erreur à l'installation.

J'ai mis tous les champs du formulaire OccTax à `true` => je vois bien tous les champs sauf le "technique de collecte campanule" (ancienne "technique d'observation"). 

Il est toujours sensé être au niveau du relevé ? Il y a quelque chose de spécial à faire pour avoir ce champ ? 
Je ne sais pas trop où chercher pour trouver l'origine du problème...  

_EDIT :_ le champ "diffusion_level" ne s'affiche pas non plus

**Comment by camillemonchicourt** [comment]
> Je viens de passer à GeoNature 2.5.0. en suivant la doc : je n'ai vu aucune erreur à l'installation.

Bonne nouvelle !

Pour le champs qui ne s'affiche pas, il s'appuie sur le paramètre ``tech_collect`` à passer à ``true``, mais en effet dans le template il semblerait qu'on appelle encore l'ancien nom du paramètre : https://github.com/PnX-SI/GeoNature/blob/master/contrib/occtax/frontend/app/occtax-form/releve/releve.component.html#L270. ``obs_collect`` au lieu de ``tech_collect``.

Il est aussi possible que le champs ``diffusion_level`` ait été oublié du formulaire, car on l'a supprimé puis remis (https://github.com/PnX-SI/GeoNature/issues/516#issuecomment-696600360).

A noter, qu'il y a plusieurs champs secondaires masqués par défaut.
Et celui-ci est hors standard donc on a envisagé de le supprimer complètement, mais on l'a gardé dans Occtax uniquement pour le moment car certains l'utilisent (https://github.com/PnX-SI/GeoNature/issues/516#issuecomment-699855635). 
Cependant on conseille d'éviter de l'utiliser car il n'est pas dans le standard donc on n'est pas sur de ce qu'il adviendra par la suite. 
Il vaut mieux s'appuyer sur les méthodes d'observations, quitte à en ajouter certaines, éventuellement avec le mécanisme de nomenclatures filles (héritage)

**Comment by TheoLechemia** [comment]
C'est corrigé pour le champs "technique d'obs campanule". 
Pour le champs "diffusion_level" ce n'est pas un oubli. Pour l'instant il n'est pas saisissable. (on l'avait mis par erreur dans les champs paramétrables).  Il y a une reflexion plus large à avoir sur le sujet. Si on veut respecter le SINP, seuls les JDD privées peuvent choisir le niveau de diffusion.
