### ISSUE TITLE
[2.5.0 - OccTax] L'enchainement des relevés - bug

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/GeoNature#1060]
Je teste le nouveau formulaire après la migration vers GN 2.5.0.

Quelques remarques en vrac après ce premier test : 

- Les boutons pour récupérer les paramétrages des valeurs par défaut des champs du formulaire ne fonctionne pas, ou très partiellement.
- Lors de l'enchainement des relevés, les informations de relevé ou d'occurrence sont conservées de façon aléatoires (des fois ce sont les valeurs par défaut, puis pour le taxon suivant ce sont les valeurs conservées)
- L'enchainement des relevés se désactive à chaque validation de relevés et à chaque fin de saisie : 

  1. je l'active au niveau du relevé
  2. une fois enregistré, on passe sur la saisie des taxons : l'option "enchainement" en haut du formulaire est de nouveau décochée, je le recoche donc
  3. après enregistrement de mes taxons, je fini la saisie  
  4. là je reviens bien directement sur une page pour saisir un relevé, mais l'option "enchainement" en haut du formulaire est de nouveau décochée.

Je viens également de tester l'enchainement sur l'instance de démo de GeoNature et je rencontre les mêmes bug...

**Comment by camillemonchicourt** [comment]
OK merci pour ces retours.
En effet, dans Occtax v1 on avait uniquement la possibilité d'enchainer des relevés et cela gardait automatiquement les valeurs de certains champs d'un relevé à l'autre. Je n'ai pas vérifié que ce fonctionnement par défaut avait été conservé et fonctionnait.
On va voir pour corriger l'enchainement des relevés.

Comme discuté dans la PR de la refonte d'Occtax, je ne suis pas très convaincu par le fonctionnement et l'ergonomie du nouvel outil de conservation des valeurs d'un taxon à l'autre et d'un relevé à l'autre. Et je pense qu'il sort des principes de simplicité de GeoNature.
Si il a des bugs, à voir d'où ça vient. Dans tous les cas, il est possible de le désactiver.

**Comment by camillemonchicourt** [comment]
Le paramètre ``DISPLAY_SETTINGS_TOOLS`` a été renommé ``ENABLE_SETTINGS_TOOLS`` pour mise en cohérence avec les autres champs.
L'outil de conservation des valeurs de saisie fonctionne d'après nos tests, mais on l'a désactivé par défaut, car il pose des questions de fonctionnement. Ceux qui souhaitent peuvent l'activer.

Quand il est désactivé, on a remis en place le fonctionnement existant jusque là de l'outil "Echainer les relevés". Quand on enchaine les relevés, on conserve le JDD, les observateurs, les dates et heures d'un relevé à l'autre.
Quand l'outil est activé, alors on ne peut pas combiner ce fonctionnement avec celui défini par l'utilisateur.
