### ISSUE TITLE
Version UUID

### ISSUE THREAD

**Issue by jbdesbas** [PnX-SI/GeoNature#1063]
Salut à tous,

Suite à la mise à jour 2.5, j'ai un message d'erreur dans la synthèse  'Value error uuid_attached_row is not valid'.
Ceci provient de la fonction suivante, qui check si l'UUID est un UUID **v4** valide
https://github.com/PnX-SI/GeoNature/blob/6a98089f2f21613430cf972dc4b7cc2c9ce45308/backend/geonature/utils/utilssqlalchemy.py#L27-L36

Manque de bol, j'utilise des UUID **v1** (ex : 3ab6b938-0599-11eb-a4d9-8ea38e099656 ) (qui ont l'avantage de pouvoir permettre de retrouver, dans une certaine mesure, la machine qui a générer l'UUID)
Pour info (et avec quelques approximations) : la v4 est totalement aléatoire, alors que la v1 a une partie fixe liée à l'adresse MAC de la machine qui l'a généré. Pour moi, la v4 peut-être intéressante pour des raisons de sécurité, s'il ne doit **pas** pouvoir être fait de rapprochement entre 2 UUID ; ce qui n'est pas notre cas ici (je recherche même l'inverse).

Le problème peut facilement être corrigé en modifiant l’appelle la fonction, mais je voulais d'abord savoir s'il y avait une raison particulière au choix de la v4 ? (dans le code python, mais aussi dans les `DEFAULT` de la BDD)

**Comment by camillemonchicourt** [comment]
OK, on est parti sur le fait de générer des UUID le plus aléatoire possible, donc en version 4. 
Mais OK pour moi, pour être un peu plus permissif et ne pas vérifier la version dans la nouvelle fonction de contrôle des UUID

**Comment by amandine-sahl** [comment]
A priori on peut supprimer le test de la version sans problème.  Il faudra toute fois être vigilent à certains effets de bords.

Par contre il faut faire bien attention avec la version des uuid utilisée lors de la génération. Il faut mieux encourager et forcer la génération en version 4, car la version 1 n'est pas toujours "safe" `Depending on support from the underlying platform, uuid1() may or may not return a “safe” UUID. `

**Comment by camillemonchicourt** [comment]
Oui on reste sur le fait que GeoNature les créé en version 4, mais on allège le contrôle en autorisation qu'ils soient fournis dans une autre version. OK.
