### ISSUE TITLE
Formulaire dynamique: ajout d'un texte d'aide aux composants

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature#1065]
Afin, de pouvoir rajouter, un texte d'aide sous les composants dynamiques, nous proposons d'ajouter la possibilité [offerte par Bootstrap](https://getbootstrap.com/docs/4.5/components/forms/#help-text) aux composants de formulaire dynamique.

Dans le fichier de configuration, nous utiliserons un attribut `help` optionnel pouvant contenir du texte.
Il s'ajoute aux paramètres de configuration disponibles pour les composants dynamiques actuels.

Ce texte sera inséré sous le composant dynamique tel que décrit dans la documentation de Bootstrap avec le code HTML suivant: 
```
<small class="form-text text-muted">
    <!-- Ici le texte d'aide -->
</small>
```

**Comment by camillemonchicourt** [comment]
OK, à voir si ce n'est pas redondant avec l'ajout dans la 2.5.0 de la possibilité d'afficher une définition d'un champs sous forme de tooltip dans le Dynamic-Form ?
Help ou Définition, faut-il pouvoir utiliser l'un ou l'autre ?
Je dirai, pourquoi pas, ça peut être complémentaire.

**Comment by jpm-cbna** [comment]
La différence entre les deux, c'est que le texte d'aide est toujours visible alors que le tooltip d'Angular Material disparait quand tu es entrain de saisir dans le formulaire.
Le texte d'aide ajoute aussi très peu de modification de code, 1 ligne dans 1 fichier. Il est aussi fonctionnel pour tous les composants actuels.

**Comment by camillemonchicourt** [comment]
OK pouvoir utiliser les 2 est intéressant en effet.
