### ISSUE TITLE
Affichage des adresses e-mails dans la synthèse

### ISSUE THREAD

**Issue by jbdesbas** [PnX-SI/GeoNature#1066]
Salut,
Depuis le 2.5, la synthèse affiche le mail des observateurs. Sauf erreur de ma part, je n'ai rien trouvé dans la config permettant de désactiver cet affichage ?

**Comment by TheoLechemia** [comment]
Merci pour les tests ;)
je viens de rajouter un paramètre.

**Comment by camillemonchicourt** [comment]
Oui bien vu, c'était une fonctionnalité souhaitée du module Validation.
Les fiches infos des 2 modules ayant été factorisées (https://github.com/PnX-SI/GeoNature/issues/1053), on peut maintenant avoir les emails des observateurs dans la fiche info SYNTHÈSE. Cela peut être utile aux utilisateurs de pouvoir contacter les observateurs, mais cela peut aussi être non souhaitable.
Merci Théo pour le paramètre global.

**Comment by DonovanMaillard** [comment]
Je vais être tatillon, mais je vois bien le cas où les validateurs ont besoin de cette info, alors que les "seuls" lecteurs de la synthèse ne devraient pas y avoir accès :) 

Les droits pouvant différer d'un module à l'autre, ça semblerait plus pertinent d'avoir ce paramètre au niveau du module validation par exemple.

**Comment by TheoLechemia** [comment]
C'est pas possible en l'état !

**Comment by jbdesbas** [comment]
Salut,

Je n'ai pas trouver le paramètre dans la 2.5.5 pour désactiver l'affichage de l'adresse mail des observateurs ?

**Comment by camillemonchicourt** [comment]
``DISPLAY_EMAIL_INFO_OBS`` : https://github.com/PnX-SI/GeoNature/blob/master/backend/geonature/utils/config_schema.py#L216
Indiqué dans les notes de la 2.5.1 : https://github.com/PnX-SI/GeoNature/blob/master/docs/CHANGELOG.rst#251-2020-10-06

Mais on a du oublier de l'ajouter dans le fichier d'exemple de configuration, ou on oublie parfois certains nouveaux paramètres.

**Comment by jbdesbas** [comment]
OK merci Camille :+1: , ajout dans la PR #1254
