### ISSUE TITLE
Ouverture du module OCCTAX avec champs prédéfinis

### ISSUE THREAD

**Issue by metourneau** [PnX-SI/GeoNature#1071]
Bonjour,

Je suis en train de développer le "Module spécifique Pélophylax" et "Tortues marines" pour la SHF.
Pour l'heure nous sommes partie sur l'ajout de 3 formulaires dynamiques dans OCCTAX (relevé / taxon / dénombrement) en fonction du jeu de données sélectionné.
On doit pouvoir accéder au module à partir de la page d’accueil ( introduction.component ), donc à OCCTAX mais avec des champs pré-remplis (comme le jeu de données), ou avoir une liste de taxon réduite au taxon de l'étude, ou éventuellement cacher certains champs.

Je voulais savoir s'il y avait déjà des choses développées permettant de faire cela, sinon quelle approche vous semble la plus simple à mettre en place (pré-remplir le paramétrage de la valeur par défaut, passer des paramètres dans l'url, utliliser la session).

Merci

**Comment by camillemonchicourt** [comment]
Sujet complexe en effet.
Le discussion portait intialement sur le fait de dupliquer Occtax, ou d'enrichir Occtax avec des champs additionnels.
La solution de dupliquer Occtax en créant un module à part est celle qui permet de faire le plus de spécifique, mais donc moins générique, avec plus de maintenance (https://github.com/PnX-SI/GeoNature/issues/621).

Enrichir Occtax avec des champs additionnels définis par JDD est une solution plus globale, plus générique et ouvrant plus de possibilité. C'est celle retenue : https://github.com/PnX-SI/GeoNature/issues/1007

Mais si il y a beaucoup de spécificité, alors cela ne tient plus forcément la route.
Se pose aussi la question du public ciblé. Si cela concerne un public très large, voire le grand public, alors il vaut mieux y répondre avec l'outil GeoNature-citizen qui permet de définir des programmes de collecte ou d'enquêtes citoyennes et participatives. Cet outil est en train d'être enrichi avec la possibilité de définir des champs additionnels par programme (https://github.com/PnX-SI/GeoNature-citizen/issues/181).

Donc si le choix a été fait de s'appuyer sur Occtax, alors c'est bien un seul et même module, avec une seule entrée dans la table ``t_modules``, une seule entrée dans la barre latérale de navigation (quitte à la renommer "Saisie" ou "Inventaire" au lieu d'Occtax), un CRUVED, une route, une URL etc...

Le CRUVED permet déjà de ne proposer à un utilisateur une liste des JDD selon son organisme. Et un ticket proposait de selectionner automatiquement un item d'une liste déroulante quand celle-ci ne contient qu'une seule entrée.
Pour les listes de taxons définies par JDD, je crois qu'il y avait un ticket dédié mais je ne le retrouve plus. Ca a été évoqué ici : https://github.com/PnX-SI/GeoNature/issues/621#issuecomment-483995382
On pourrait le définir dans la table des JDD, et si il n'est pas renseigné, on utilise celui définit dans la conf gnérale du module Occtax. Idéalement on devrait se baser sur le "code_liste" en cours d'implémentation (https://github.com/PnX-SI/TaxHub/pull/223) plutot que sur un id_liste.

A noter aussi qu'il y a pas d'améliorations en cours des composants du Dynamic-form, avec l'ajout d'un composant "HTML" (https://github.com/PnX-SI/GeoNature/issues/1043) et pas mal d'autres choses, listées dans les tickets et PR récents.

Cacher certains champs est possible au niveau du module Occtax global, mais pas par JDD. Ca pourrait être implémenté dans la configuration, au même endroit où on configure les champs additionnels ?

**Comment by camillemonchicourt** [comment]
Sinon pourquoi pas faire en sorte que l'on puisse passer des paramètres au formulaire dans l'URL, genre http://mongeonature.fr/#/occtax/form?jdd=12 et que ça ouvre sur le formulaire de saisie, avec le JDD pré-selectionné.

**Comment by DonovanMaillard** [comment]
Ca serait super intéressant comme idée. 

Ca permettrait dans t_module de rajouter des lignes en pointant sur des "modules" qui ne sont que des "raccourcis" vers un occtax pré-renseignés et son URL complétée.
 
Il faudrait alors qu'à l'issue d'une saisie on retombe bien sur cette URL complétée et pas sur les valeurs par défaut paramétrées dans occtax, mais avec ce fonctionnement on peut imaginer faire apparaitre plusieurs "modules" qui sont des occtax pré-remplis selon 2, 3, X manières qui correspondent aux 2, 3, X méthodes les plus communes dans nos pratiques.

**Comment by camillemonchicourt** [comment]
Non car t_modules a un rôle central dans GeoNature, et on ne peut pas avoir 2 modules dans t_modules qui sont en fait le même module.

**Comment by metourneau** [comment]
Merci, je vais essayer de coupler le passage du paramètre dans l'url et l'implémentation de cette valeur par défaut pour enchaîner les saisies

**Comment by camillemonchicourt** [comment]
Oui pourquoi pas.
Cependant je ne pense pas que le lien direct vers le formulaire de saisie avec un JDD pré-défini cela soit très utile ni très pertinent. 
Car on passe directement de l'accueil de GeoNature à un formulaire de saisie.
Alors que la logique de fonctionnement des modules de GeoNature est : 
- Accès au module
- Carte/Liste des objets présents dans la module
- Filtre/export parmis les objets du module
- Ajout/modification/suppression d'un objet du module

**Comment by metourneau** [comment]
Effectivement, mais la demande est censée toucher un public élargi. On doit donc orienter l'utilisateur pour la saisie de ses pélophylax. C'est simplement un raccourci entre la page d’accueil et la saisie d'une observation pour un néophyte.
![image](https://user-images.githubusercontent.com/53472638/95433454-3f5c9d80-0950-11eb-9460-d491bb11a582.png)

**Comment by DonovanMaillard** [comment]
Aces cette finalité public élargi et une espèce en particulier, ça ressemble davantage à un programme GeoNature Citizen qu'à un objectif d'occtax, qui reste un outil de saisie "pro" si on suit la logique geonature/citizen ;)
