### ISSUE TITLE
Formulaire dynamique "text": ajouter une validation par expression régulière

### ISSUE THREAD

**Issue by FlorentRICHARD44** [PnX-SI/GeoNature#1073]
Ajouter une validation par expression régulière pour un champ de type "text" dans les formulaires dynamiques:
* ajout d'un paramètre "pattern"
* ajout d'un paramètre "pattern_message"
* prise en compte pour le type_widget=text seulement
* ajout d'un validator pattern
* ajout d'un message sous le champ text affiché en cas d'erreur de pattern

Exemple:
![image](https://user-images.githubusercontent.com/12184477/95475996-16a3ca80-0987-11eb-8dbd-d2fe19b8bd58.png)

**Comment by camillemonchicourt** [comment]
Merci, en effet, fonctionnalité intéressante et utile.
N'hésite pas à faire des petites PR par petite fonctionnalité comme celle-ci.

J'en profite pour rebondir sur l'exemple.
Pour limiter les erreurs et les saisies redondates, on évite toujours de demander à l'observateur de saisir des communes, des codes postales ou autres informations spatiales, les objets étant localisés, on calcule toutes les infos spatiales.
Sauf si on doit renseigner l'adresse d'un objet qui n'est pas localisé sur une carte bien sur.

**Comment by FlorentRICHARD44** [comment]
J'ai proposé la pull request.

Pour le champ "code postal" de mon exemple:
Je n'ai pas encore abordé la partie carte et géométrie dans mes développements, mais en effet il doit être possible de récupérer l'information par calcul.

**Comment by camillemonchicourt** [comment]
Merci. 
Oui calculable mais surtout je conseillerai de ne même pas afficher ce champs "code postal", ni même le stocker. C'est source d'erreur et calculable si besoin. 
On conseille d'éviter ce genre de champs dans GeoNature, mais à vous de voir si c'est dans un module spécifique.
