### ISSUE TITLE
Scripts d'installation

### ISSUE THREAD

**Issue by etot** [PnX-SI/GeoNature#1074]
Bonjour, deux remarques (mineures) sur le script d'installation : 

1. dans install_all.ini, je suggère d'ajouter au commentaire ligne 6 qu'il faut que l'URL commence par "http://" ... ça peut paraître évident mais l'installation ne fonctionne pas sans 
2. dans install_app.sh, ligne 89, pourquoi ne pas regénérer geonature_config.toml s'il existe déjà ? Actuellement, si on modifie install_all.ini et qu'on relance le script d'installation global, les modifs ne sont pas prises en compte.

Merci !

**Comment by camillemonchicourt** [comment]
OK le commentaire a été précisé (https://github.com/PnX-SI/GeoNature/commit/f3f2e66c3f30a2547b69457acf2221d83e4031dc). C'est vrai que quand ils ont une IP, les gens ne mettent pas toujours le http://, même si l'exemple de ce paramètre utilise http.
Cependant si on a mal renseigné ce paramètre, ou si l'IP, l'URL change, il n'est pas nécessaire de relancer une installation, il suffit de modifier le paramètre dans la configuration globale de GeoNature : http://docs.geonature.fr/admin-manual.html#configuration-generale-de-l-application

D'ailleurs, concernant le script d'installation globale (``install_all.sh``) je ne suis pas sur que l'on puisse le relancer sur une installation existante, @TheoLechemia ?

**Comment by TheoLechemia** [comment]
Si il est possible de lancer le script plusieurs fois. A condition de mettre le paramètre `drop_geonaturedb=true` si on veut réinstaller la base. 
J'ai corrigé la recréation du fichier de config.
