### ISSUE TITLE
[GeoNature 2.5.1] Blocage lors de l'installation des paquets npm

### ISSUE THREAD

**Issue by julienlusson** [PnX-SI/GeoNature#1077]
Bonjour,

Sur une Debian 10.6 fraîchement installée (version netinstall), le script d'installation se bloque à l'étape `Installation des paquets Npm`, il ne se passe plus rien alors que j'ai laissé la machine tourner pendant plusieurs heures .

J'ai retenté plusieurs installation à partir de zéro, et le blocage se fait toujours au même endroit (commande `npm ci --only=prod` du fichier install_app.sh).

Il n'y a rien de probant dans le fichier de log d'installation :
[install_all.log](https://github.com/PnX-SI/GeoNature/files/5353814/install_all.log)

**Comment by jpm-cbna** [comment]
Bonjour,
Après discussion avec @TheoLechemia , le problème provient peut être du réseau où votre serveur est installé.
Pouvez vous vérifier que vous avez bien accès depuis votre serveur [aux sites web nécessaire à l'installation de GeoNature](https://geonature.readthedocs.io/fr/latest/installation-all.html#configuration-serveur) ?
Dans votre cas, c'est surtout https://registry.npmjs.org qu'il faut tester.

**Comment by julienlusson** [comment]
La machine virtuelle n'a aucune restriction sur son accès internet, et a bien accès au dépôt npm.

D'ailleurs, après arrêt du script install_all.sh en faisant un ctrl + c, je viens de lancer le script `~/geonature/install/install_app.sh` à la main, et l'installation des paquets npm se passe sans soucis, et après avoir lancé le reste des commandes à la main, tout se passe bien et la plateforme fonctionne.

**Comment by jbrieuclp** [comment]
Votre VM est équipé de combien de RAM ? Peut-être qu'il y a une piste à creuser à ce niveau s'il n'y en a pas suffisamment...

**Comment by julienlusson** [comment]
La VM a 7,3 Go de RAM, et j'ai fait une vérification avec htop lors du blocage et elle était loin d'être saturée en RAM ou en CPU (4 vCPU). Et la VM a assez d'espace disque (40 Go).

**Comment by camillemonchicourt** [comment]
OK donc ce n'est pas le soucis.
Ce serait intéressant d'identifier le problème.
Peut-être un soucis temporaire au niveau de l'accès à certains paquets externes....

**Comment by DonovanMaillard** [comment]
sur npm j'ai eu le soucis une fois si je me souviens bien, j'avais mis ca sur le dos de ma VM et j'avais recommencé... la seconde fois c'était passé. Mais j'ai déjà eu des lenteurs à ce moment là avant que le script se poursuive.

**Comment by julienlusson** [comment]
Je ne suis pas sûr, car j'ai testé sur 3 jours différents avec le même soucis.

J'ai relancé l'installation à partir d'un snapshot (avec virtualbox) avec un `--verbose` sur la ligne `npm ci --only=prod`, à suivre donc !

**Comment by julienlusson** [comment]
Cette fois-ci, c'est passé sans soucis, ça devait venir de npm, peut-être mettre le verbose dans le script d'installation ? Ça permettrait de voir si l'installation bloque sur un paquet.

**Comment by DonovanMaillard** [comment]
Je vais refaire une ou deux install prochainement pour voir si je reproduis à nouveau :)

**Comment by DonovanMaillard** [comment]
Je viens de refaire une install all sur une VM debian10, j'ai de nouveau de soucis au même endroit, Installation des paquets Npm. 

En revanche il me retourne d'autres infos : 
Suite à cette ligne 'installation des paquets npm" il me retourne : WARN tarball tarball data for typescript@3.2.4 (etc) seems to be corrupted. 

En amont de ces soucis là, j'ai un certain nombre de choses qui se passent déjà pas très bien : 
pip3 : commande introuvable
Installation du virtualenv -> no module named virtualenv
grep /home/geonatureadmin/backend/venv/bin/activate -> aucun dossier de ce type
pip : commande introuvable
supervisorctl -> commande introuvable

**Comment by pbaumes** [comment]
Effectivement, ça devait être un problème lié aux droits de l'utilisateur de la BDD, car entre temps j'avais indiquer un nouvel utilisateur/mot de passe dans le "install_all.ini".

Je viens de procéder à une nouvelle installation from scratch, et désormais j'accède bel et bien au site.

Merci à vous !
