### ISSUE TITLE
Ajout d'un input "code nomenclature" dans le widget "media" pour la valeur par défaut du type de média

### ISSUE THREAD

**Issue by metourneau** [PnX-SI/GeoNature#1078]
Plutôt que les id des nomenclatures (qui peuvent être différents d'un GeoNature à l'autre) est-il possible d'utiliser les codes des nomenclatures ou de leurs types, justement faites pour être sur des valeurs communes à tous les GeoNature ?

_Originally posted by @camillemonchicourt in https://github.com/PnX-SI/GeoNature/issues/1072#issuecomment-706045122_

**Comment by joelclems** [comment]
par mnemonique ou code_nomenclature ?

**Comment by metourneau** [comment]
Effectivement, code renommé en mnemonique_nomenclature_media_type
