### ISSUE TITLE
Accueil: indicateur de chargement pour les stats

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature#1086]
Sur la page d'accueil de GeoNature, les statistiques peuvent mettre plusieurs secondes à se charger lorsque la base contient plusieurs millions de données dans la synthèse.
Actuellement, rien n'indique que leur calcul est en cours.

Il serait intéressant d'afficher une icône de chargement.

**Comment by camillemonchicourt** [comment]
Oui c'est long car on applique le CRUVED sur les chiffres.
Ce qui n'est pas forcément souhaitable.
Ça dépend des contextes.
Mais si on n'appliquait pas le CRUVED sur les stats alors le calcul serait instantané.

**Comment by jpm-cbna** [comment]
Oui, l'ajout de l'icône de chargement résout en partie le problème.

Pour aller plus loin, un idée sera de placer le résultat dans le datastorage local au navigateur de l'utilisateur (car le résultat est dépendant des droits de l'utilisateur) de façon à afficher un résultat instantané après le premier chargement. Nous pourrions lancer le chargement en arrière plan et mettre à jour le cache local et l'affichage une fois les résultats obtenus.

Pour pourrions afficher, en petit caractères au bas des stats la date et heure de la dernière mise à jour. Un message indiquant que les stats affichées sont dépendantes des droits de l'utilisateur serait aussi le bienvenu.

**Comment by camillemonchicourt** [comment]
Oui la question par rapport aux droits est de savoir si chez chiffres doivent refleter : 
- L'ensemble des données présentes dans l'instance GN (dans ce cas on enlève le filtre CRUVED qui alourdit le calcul)
- Les données que l'utilisateur peut consulter (dans ce cas on garde le CRUVED)

Je penche pour le premier cas, j’enlèverai le filtre.

**Comment by jpm-cbna** [comment]
Avec la version 2.3.2 de GeoNature, l'affichage des stats pour 6 millions d'observation met environs 12s sur un Public Cloud d'OVH où la base de données est installée sur espace de type Block Storage à ~2 500 IOPS.

@lpofredc pourrais tu me fournir les infos correspondantes concernant votre hébergement ? Cela me donnerait une idée des problèmes que je pourrai avoir avec le double de données. As tu cherché à optimiser la requête ? Si le CRUVED est supprimé, peut être faut il créer une table de cache côté serveur ? D'autres idées ?

**Comment by TheoLechemia** [comment]
Oui en y reflechissant, le CRUVED n'est pas forcément utile. ça fait comprendre au gens qu'ils sont sur une plateforme globale qui contient X données. 
Un paramètre pour ça ? pourquoi pas, mais attention à la multiplication des paramètres qui rende l'application difficilement testable.

**Comment by camillemonchicourt** [comment]
Oui moi j'irai aussi vers la simplification et pas un paramètre pour appliquer ou non le CRUVED.
Donc des stats basiques, un count de base ne devrait pas prendre 10 secondes.
Et juste un paramètre comme actuellement pour masquer ce bloc de stats si il n'est pas adapté au contexte.

**Comment by lpofredc** [comment]
Nous sommes sur un serveur dédié mais en **SATA** - non optimal donc - (choix volontaire pour des besoins de capacités de stockages) avec la perspective d'ajouter un stockage plus performant à terme (SSD ou NVMe, voire plusieurs pour utiliser différents tablespace) > https://www.online.net/fr/server-dedicated/core-4-s-sata. 

Nous disposons actuellement de 20 millions de lignes en synthèse.
![image](https://user-images.githubusercontent.com/22891423/95969741-66fbac00-0e0f-11eb-8a2c-b16d8e8a8dde.png)

Aussi, lorsque je m'étais penché sur ce pb pour biodiv-territoires, j'ai constaté que les `count distinct` sont peu performants, il est préférable de réaliser un `count` sur un `select distinct`. comme évoqué dans cette discussion: https://stackoverflow.com/questions/11250253/postgresql-countdistinct-very-slow

Par exemple: ce comptage me prend **50 sec** > https://explain.dalibo.com/plan/BaS
```sql
SELECT
    count(DISTINCT observers)
    FROM
        gn_synthese.synthese
;
```

Alors que réécrit commt suit, cela prend **8 sec** > https://explain.dalibo.com/plan/9oJ

```sql
SELECT
    count(observers)
    FROM
            (SELECT DISTINCT observers FROM gn_synthese.synthese) AS tmp
;
```


 


> Avec la version 2.3.2 de GeoNature, l'affichage des stats pour 6 millions d'observation met environs 12s sur un Public Cloud d'OVH où la base de données est installée sur un espace de type Block Storage à ~2 500 IOPS.
> 
> @lpofredc pourrais tu me fournir les infos correspondantes concernant votre hébergement ? Cela me donnerait une idée des problèmes que je pourrai avoir avec le double de données. As tu cherché à optimiser la requête ? Si le CRUVED est supprimé, peut être faut il créer une table de cache côté serveur ? D'autres idées ?

**Comment by jpm-cbna** [comment]
@lpofredc merci pour les informations sur l'optimisation des requêtes.

Concernant le stockage, c'est effectivement le point qui semble primordial avec Postgresql. En local, sur ma machine, j'ai les 3 types de solution de stockage : disque dur SATA, disque SSD et carte NVMe. Pour diverses raisons, j'ai pu tester le fonctionnement de Postgresql sur ces 3 types. Sans conteste le plus performant est le NVMe, 4 fois plus rapide que le SSD. Le disque dur SATA est le pire et je ne suis pas resté longtemps dans cette configuration car l'intégration des données prenait beaucoup trop de temps.
Le temps d’exécution des requêtes est proportionnel à la vitesse du disque. Une opération qui prenait 2 heures sur le disque SSD m'a pris 30 minutes sur le NVMe.
