### ISSUE TITLE
Leaflet Draw: marker en double

### ISSUE THREAD

**Issue by FlorentRICHARD44** [PnX-SI/GeoNature#1095]
Sur la carte, lorsque l'on utilise le composant 'leaflet-draw' avec un point, ce point est affiché en double (1 marker et 1 circlemarker).
![image](https://user-images.githubusercontent.com/12184477/96572825-9dcd3880-12cd-11eb-9b01-87f37339a7eb.png)
Les 2 points sont également éditables, mais bien sur non synchronisés lorsqu'on en déplace un.
![image](https://user-images.githubusercontent.com/12184477/96572997-d53be500-12cd-11eb-9e79-ffe4f54190b3.png)

Dans le code, [leaflet-draw.component.ts](https://github.com/PnX-SI/GeoNature/blob/develop/frontend/src/app/GN2CommonModule/map/leaflet-draw/leaflet-draw.component.ts) on peut voir que les 2 sont créés.
![image](https://user-images.githubusercontent.com/12184477/96572797-9443d080-12cd-11eb-8939-0de972492f32.png)

Est-ce un souhait d'avoir la fonctionnalité avec ces 2 points créés?
si oui, peut-on le rendre désactivable?
si non, j'aurais une préférence pour garder seulement le marker.

**Comment by camillemonchicourt** [comment]
Oui on ne devrait pas avoir un point en double quand on localise un point. 
Je pense aussi qu'on devrait seulement avoir un marker
