### ISSUE TITLE
les jdd créés automatiquement (inscriptions automatiques) ne sont pas validables

### ISSUE THREAD

**Issue by Amegilla** [PnX-SI/GeoNature#1099]
Tout est dans le titre...

Les jdd créés automatiquement lors de la création de compte ne sont, par défaut, pas validable.
J'aurai imaginé le contraire, cad, qu'ils soient par défaut validables.
Dans le cas de notre association, nos bénévoles se créent leur comptes, puis saisissent des données tout cela en autonomie. De mon coté je suis obligé de passer par là de temps en temps pour rendre validable tout ces nouveaux jdd car sinon les validateurs ne voient pas arriver tout les nouvelles contributions.
Vous en pensez quoi ?

Coté code, si je comprends bien, cela implique uniquement de rajouter  `validable=True,` ici : https://github.com/PnX-SI/GeoNature/blob/370c1e0cac18e9d2a6e2a6e8c07fc8e4e8f96c96/backend/geonature/core/users/register_post_actions.py#L134

**Comment by camillemonchicourt** [comment]
Oui en effet ça semble pertinent qu'ils soient validables par défaut.

**Comment by bouttier** [comment]
Le champs validable n’étant pas spécifié, il prend la valeur par défaut de la base qui est True.
Ce ticket est-il toujours d’actualité ??

**Comment by camillemonchicourt** [comment]
Oui si la BDD met TRUE par défaut, alors c'est OK et le ticket peut être fermé selon moi.
