### ISSUE TITLE
[Profil taxon] - Implémenter le SQL

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#1103]
- [x] Revoir le code SQL vis à vis de la convention de codage

- [x] Clarifier / revoir le nom de certaines tables

- [ ] Décrire les champs et les tables

- [x] Voir le travail de Gil et le fusionner avec l'existant

**Comment by DonovanMaillard** [comment]
- [ X ] Revoir le code SQL vis à vis de la convention de codage
- [ X ] Clarifier / revoir le nom de certaines tables
- [ ] Décrire les champs et les tables
- [ ] Voir le travail de Gil et le fusionner avec l'existant

Je viens de décrire les tables. Est-ce qu'il est nécessaire de décrire tous les champs ?

**Comment by DonovanMaillard** [comment]
Coté BDD je pense qu'on est presque bons. Je vais supprimer le champs 'exta-value" de la t_parameters qui ne sert à rien et je ferai une PR avec ces premiers éléments :)

**Comment by DonovanMaillard** [comment]
Bonjour, 

Un point sur les avancées, coté base je pense qu'on est OK cette fois  : 

- la notion d'organisme est supprimée dans les tables paramètres, qui n'était pas implémentée ailleurs
- les scripts  install_db et install_existing_db intègrent désormais les profils
- un script migration est préparé, en ajoutant les profils ET en suppimant les VM et fonctions que Gil avaient faites
- la doc est à jour

Je fais une PR pour tout ça
-

**Comment by camillemonchicourt** [comment]
Le SQL de création du schéma de la BDD des profils de taxons est dispo sur : https://github.com/PnX-SI/GeoNature/blob/develop/data/core/profiles.sql

**Comment by camillemonchicourt** [comment]
Profils de taxons intégrés dans la 2.9.0
