### ISSUE TITLE
[Profil taxon] Frontend

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#1105]
- [x] Occtax: afficher une alerte/retour utilisateur sur la cohérence de son observation

- [x] Synthese/Validation: pouvoir afficher le profil d'une espèce sur la modale d'une observation

- [x] Ajout d'une colonne "score" sur la liste du module validation. La colonne affiche un icone warning si la score n'est pas max, une icone "croix" si le score est de 0 et une icone "check" si le score est de 3

**Comment by lepontois** [comment]
Reste à faire sur le module occtax :
- Mettre en forme le message d'erreur après sélection du taxon (Toaster)
- Mettre en place l'évennement sur le champ "stade de vie" qui doit controler si la valeur sélectionnée est présente dans le résultat retourné après sélection du taxon (+ gérer l'intégration de l'erreur)

**Comment by DonovanMaillard** [comment]
Suite aux remarques de Camille, j'ai enlevé les icones "Check" de "Croix" qui pouvaient ête ambigus (donnaient l'impression qu'on avait qu'à clique l'icone pour valider/invalider la donnée)

J'ai mis des thumb_up, thumb_down et pan_tool pour le moment, je trouve ça clair et cohérent. 


En revanche les tooltips actuellement utilisés ne permettent que d'afficher un message texte en dur. Je trouverais pas mal qu'on bascule par la suite sur un "tooltip" ou popover plus riche, qui renvoie le score et liste les 3 checks altitude, phénologie, et distribution pour rendre l'info plus rapidement accessible :)

**Comment by TheoLechemia** [comment]
Cool, c'est un bon compromis.
Les tooltip sont assez limités au niveau de l'affichage. Mais c'est contournable en faisant du html/CSS simple qui s'affiche quand la souris passe dessus: https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_display_element_hover

**Comment by jpm-cbna** [comment]
> Les tooltip sont assez limitées au niveau de l'affichage. Mais c'est contournable en faisant du html/CSS simple qui s'affiche quand la souris passe dessus: https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_display_element_hover

Peut être que les [Popover de Bootstrap](https://getbootstrap.com/docs/4.5/components/popovers/) seraient adaptés à votre besoin ?
J'ai pas trouvé d'équivalant avec Angular Material. Par contre, je ne suis pas certain qu'ils fonctionnent directement avec Angular car ils demandent une bibliothèque supplémentaire. Ceci dit, ils peuvent servir d'exemple.

**Comment by camillemonchicourt** [comment]
Pour moi les thumb_up et thumb_down appellent une action de l'utilisateur, de LIKER, ou aimer la cohérence d'une observation.
Je trouver mieux d'afficher une note sur 3, éventuellement avec une couleur en arrière-plan de la case. Plus précis et moins sujet à incompréhension. Mais c'est anecdotique.

**Comment by DonovanMaillard** [comment]
![Uploading 20201110_164836.jpg…]()

Les popover fonctionnent bien . Me reste a voir pourquoi je renvoie des false avec ngif quand les valeurs sont true.

**Comment by DonovanMaillard** [comment]
![20201110_164836](https://user-images.githubusercontent.com/23358384/98699635-a4ece100-2377-11eb-80e4-fa78420e349c.jpg)

**Comment by TheoLechemia** [comment]
Je relance ce sujet pour finir la PR sur les profiles.
En testant sur une grosse BDD il s'avère que les fonctionnalités d'affichage et de filtrages des scores ne monte pas du tout en charge.
La faute à la vue `v_consistancy_data` et notament la fonction `check_profile_phenology` qui sont extrêmement lourde.
Plusieurs solutions:
- ajouter des triggers sur la synthèse pour calculer le score (pas pour)
- paginer la validation côté serveur (on perd la vue d'ensemble sur les données recherché, mais est-ce que c'est important pour la validation ?)
- on simplifie largement le calcul des profiles (à voir si à l'usage on à vraiment besoin des seuils - spatial précision et temporal precision pour chaque taxon ?)

**Comment by TheoLechemia** [comment]
J'en rajoute une petite couche: 
le calcul de la phénologie inclue l'exclusion des données imprécise spatialement (polygone trop grand) et temporellement (plage de date trop large), c'est ce qui la rend si lente. Imprécisions qui sont en plus paramétrable par taxon par taxon (via gn_profile.t_parameters)
Je serais plus partant pour que la fonction de vérification de la phénologie ne vérifie QUE la validité de la phénologie, et qu'on traite la question des données imprécise par ailleurs. On pourrait avoir des filtres qui font remonter toutes les données qui font plut de X mètre de superficie ou toutes les données qui ont une plage de date trop grande.

**Comment by camillemonchicourt** [comment]
Profils de taxons intégrés dans la 2.9.0
