### ISSUE TITLE
Champ jddId de la vue d'export de la synthèse disparu?

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature#1108]
Le champ `jddId` est mentionné comme valeur par défaut pour la variable `EXPORT_ID_DATASET_COL`. Or, il semble remplacé par `idSINPJdd`  dans la vue `gn_synthese.v_synthese_for_export`. 
https://github.com/PnX-SI/GeoNature/blob/370c1e0cac18e9d2a6e2a6e8c07fc8e4e8f96c96/data/core/synthese.sql#L905-L907
A priori surtout utilisé pour le CRUVED sur la route qui génère les exports depuis la synthèse, je ne comprends pas bien son usage. Sur une instance nouvellement installée (v2.5.1) et l'instance de démo officielle, les exports  fonctionnent sans soucis. Sur une instance récemment mise à jour à la version 2.5.2, l'api soulève l'erreur que le champ `jddId` est manquant dans la vue (retiré ici https://github.com/PnX-SI/GeoNature/commit/283d501352bbdaa3b6d773a32fb6806a36fda924#diff-67d9e2a223e75908c9da32e3fcc267d69f7e10c506eed71d5fa3b44d6663d288R908)... 

J'avoue ne pas bien comprendre la subtilité, les vues semblent pourtant identiques et le paramètre `EXPORT_ID_DATASET_COL` n'a pas été personnalisé. J'ai dû recréer la vue en ajoutant le champ `jddId` pour retrouver des exports fonctionnels.

message | the gn_synthese.v_synthese_for_export table     does not have a column jddId              If you change the gn_synthese.v_synthese_for_export table, please edit your synthese config (cf EXPORT_***_COL)
-- | --
raisedError | GeonatureApiError
status_code | 500

https://github.com/PnX-SI/GeoNature/blob/bda0181b7dc6d580f32765735425808739c175a7/backend/geonature/utils/config_schema.py#L195

**Comment by camillemonchicourt** [comment]
OK c'est peut-être une erreur de notre part. 🤔

**Comment by camillemonchicourt** [comment]
@TheoLechemia, une idée pourquoi le champs jddId a été supprimé de l'export de la synthèse ?
Car pas vraiment utile dans les exports et on a privilégié l'UUID ?
Si utile on laisse les 2 ? L'id du JDD et son UUID ?

**Comment by TheoLechemia** [comment]
Oui c'est une erreur de notre côté. Il faut laisser le id_dataset pour filtrer avec le CRUVED si E = 2

**Comment by camillemonchicourt** [comment]
OK je m'occupe de revoir un peu la vue, et j'en profite pour remettre ce champs.

**Comment by camillemonchicourt** [comment]
Fait dans https://github.com/PnX-SI/GeoNature/pull/1124, en même temps qu'une importante révision de la vue d'export Synthèse (en cours de finalisation dans ``develop``) : 
- Ajout des communes et d'infos taxonomiques
- Utilisation de noms de champs en minuscules mais plus compréhensibles par les utilisateurs finaux, à qui est destiné cet export, sans se limiter aux 10 caractères du format SHP qui va être remplacé par GPKG
- Corrections mineures diverses
