### ISSUE TITLE
Ajout d’autres types de médias – OCCTAX

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/GeoNature#1113]
Bonjour, 

Lorsqu’on ajoute un média pour une observation dans occtax, on a le choix entre des images, de l’audio, des pdf, des vidéos ou des liens.
![liste_ajout_media_form_occtax](https://user-images.githubusercontent.com/19465859/97592599-1f754280-1a01-11eb-8edb-cd03de68c89b.png)

Est-ce qu’on pourrait envisager d’ajouter d’autres types de médias ? Je pense en particulier à des tableurs csv ou excel (ou autre s’il y un besoin) ?

On a soulevé ce besoin en travaillant sur les champs additionnels de la saisie. Certaines infos n’ont pas forcément besoin d’être saisies directement dans occtax, mais simplement accessibles pour les utilisateurs au niveau d’une obs. Et ces infos sont dans des tableurs pour le cas de la SHF.

On imaginait ensuite que le média soit accessible via un lien de téléchargent, comme les PDF dans l’atlas par exemple.

**Comment by jbdesbas** [comment]
Bonjour,
Il me semble que les média ajoutés ici sont plutôt des preuves d'observations (repris dans le champs _digital_proof_ ?), auquel cas ces champs additionnels ne rentrent pas trop dans ce cadre.
Le commentaire ne fait pas l'affaire pour ce cas ? Il s'agit d'un tableau par observation ?

**Comment by Splendens** [comment]
Effectivement, le commentaire ne suffit pas. 
Dans le cas étudié, il s'agit d'infos liées à l'observation, mais sous forme de tableau :  prélèvement d'échantillons, mesures diverses... 

Si on ajoute ces infos en tant que champs additionnels (ce qui pourrait être le cas), cela va alourdir considérablement la saisie, ainsi que les exports, alors que ce n'est pas indispensable. Par contre, les utilisateurs on besoin d'avoir accès à ces infos lorsqu'ils consultent leurs observations, d'où l'idée de pouvoir ajouter d'autres types de médias.

**Comment by camillemonchicourt** [comment]
Les médias associés à une observation peuvent être une preuve mais pas que. 
On peut imaginer y associer des médias de type varié.
En fait, la liste des types de médias est une nomenclature. 
Il te suffit de l'enrichir avec d'autres types et ça devrait être bon.
Par contre certains types ont des contrôles et des comportements spécifique en terme d'affichage. Si tu ajoutes des types, ils n'auront pas de traitement spécifique, mais ça devrait fonctionner, non ?
