### ISSUE TITLE
Carte: ajouter une librairie d'export en image

### ISSUE THREAD

**Issue by FlorentRICHARD44** [PnX-SI/GeoNature#1116]
Je souhaite ajouter une librairie permettant d'exporter la carte Leaflet en image.
Le but dans mon cas est de générer un PDF contenant la carte avec toutes les positions d'un individu (CMR).
Mais cela pourrait être utile à d'autres pour des fichiers PDF mais aussi télécharger l'image (sans avoir à faire d'impression d'écran ou d'utiliser un autre outil de capture).

J'ai commencé à tester avec "leaflet-image" fait par mapbox [1],[2]  qui est proposé par Leaflet dans ses plugins  [3]
[1] https://github.com/mapbox/leaflet-image, 
[2] https://www.npmjs.com/package/leaflet-image
[3] https://leafletjs.com/plugins.html#printexport

Cela a l'air de plutôt bien fonctionner (testé avec fond OSM et des 'circlemarker'.
![image](https://user-images.githubusercontent.com/12184477/97885273-6f1c7c80-1d27-11eb-8f32-d6e28845785a.png)

Avez-vous déjà envisagé cette solution ou une autre?

**Comment by camillemonchicourt** [comment]
OK dans un autre projet on avait utilisé https://github.com/Flexberry/Leaflet.Export
A voir celui qui semble le plus robuste, maintenu et perenne ?

**Comment by camillemonchicourt** [comment]
Tu génères tes PDF côté client ?
Car pour le module Métadonnées, on a ajouté WeasyPrint pour générer des PDF des fiches côté serveur.

**Comment by FlorentRICHARD44** [comment]
Merci pour le lien avec Leaflet.Export. il fait "print" également ça peut être un plus. Je vais comparer les 2 du coup.

Je génère le PDF côté serveur avec weasyprint. je me suis inspiré du module métadonnées en effet. 

Quand l'utilisateur clique sur le bouton "Télécharger", je récupère l'image côté client, je l'envoie au server en dataURL dans mon service de génération du PDF, qui l'inclue en tant qu'image dans le template HTML et génère le PDF.

**Comment by FlorentRICHARD44** [comment]
Au final je suis resté sur leaflet-image:
* il est cité sur la liste des plugins Leaflet contrairement à leaflet-export
* leaflet-export contient une dépendence vers leaflet et pas la même version. ça ne me parait pas idéal.

**Comment by camillemonchicourt** [comment]
OK en effet il faut privilégier la stabilité.
