### ISSUE TITLE
Occtax->Synthese : Problème de MAJ de géométrie

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#1117]
P'tit problème de synchro de mise à jour de la géométrie dans la synthèse lors d'une modification de la géométrie d'un relevé sous occtax. 
Lors de la modif sous occtax seuls les champs `the_geom_4326` et `the_geom_point` sont modifiés. `the_geom_local `reste sur la touche. Le problème c'est que dans la synthèse, c'est le champ `the_geom_local` qui est surveillé pour déclencher le trigger `tri_insert_cor_area_synthese` qui recalcule les différentes intersections géographiques.

Je vois 2 solutions pour résoudre ce problème :
rectifier la fonction trigger de modif du relevé `pr_occtax.fct_tri_synthese_update_releve()` et ajouter
`the_geom_local = NEW.geom_local,` ici :
https://github.com/PnX-SI/GeoNature/blob/be2be6e2d8d03336061199c9dc73fcfd8e6c411d/contrib/occtax/data/occtax.sql#L869-L870

Ou plus radical, mais peut-être plus efficace en terme de gain de place disque et d'optimisation, supprimer les champs géographiques en double/triple (geom_local vs geom_4326 vs geom_point)

**Comment by TheoLechemia** [comment]
Hum, bizarre. Je n'ai pas testé, mais normalement c'est le trigger "tri_calculate_geom_local" qui calcule la geom local en BEFORE INSERT. 
https://github.com/PnX-SI/GeoNature/blob/6a98089f2f21613430cf972dc4b7cc2c9ce45308/contrib/occtax/data/occtax.sql#L984

**Comment by jbrieuclp** [comment]
Sur occtax y a pas de problème, `geom_4326`, `geom_local` et `geom_point` sont d'équerre. C'est lors triggers qui répercute une mise à jour du relevé occtax sur la synthèse qui n'est pas complet.

**Comment by TheoLechemia** [comment]
Ok, j'avais mal lu. 
Le champs geom_local est une sorte de cache pour ne pas avoir à refaire un "st_transform" sur toutes les lignes de la synthese. Le champs geom_point n'est lui pas directement utilisé dans GeoNature, on pourrait en effet discuter de son utilité.

**Comment by camillemonchicourt** [comment]
OK du coup le trigger d'update a été corrigé : https://github.com/PnX-SI/GeoNature/blob/develop/data/migrations/2.5.2to2.5.3.sql#L187

Et par sécurité on remet à jour tous les champs the_geom_local de la Synthèse pour les observations venant d'Occtax : https://github.com/PnX-SI/GeoNature/blob/develop/data/migrations/2.5.2to2.5.3.sql#L231
