### ISSUE TITLE
Debian9 - Pyenv bashrc ne se charge plus

### ISSUE THREAD

**Issue by Idaline** [PnX-SI/GeoNature#1118]
Bonjour !

J'ai installé sur mon debian 9 Python 3.7.9 avec pyenv comme expliqué ici : https://github.com/PnX-SI/GeoNature/blob/master/docs/installation-standalone.rst#python-37-sur-debian-9

Depuis, il faut que je lance à chaque début de session "source ~/.bashrc", sinon la compilation du frontend ne marche pas. Est ce qu'il manquerait une étape à la fin de l'installation de python ?

**Comment by TheoLechemia** [comment]
Salut,

Tu as quoi comme erreur quand tu ne lance pas la commande `source ~/.bashrc` ?

**Comment by Idaline** [comment]
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! geonature@0.0.0 build: `. ~/.nvm/nvm.sh; nvm use; ng build --prod --aot=false --build-optimizer=false`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the geonature@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/geonatureadmin/.npm/_logs/2020-11-03T09_24_25_268Z-debug.log

**Comment by TheoLechemia** [comment]
Est-ce que tu peux nous mettre le fichier de log complet /home/geonatureadmin/.npm/_logs/2020-11-03T09_24_25_268Z-debug.log
mais ça a plus l'air d'être un problème de nvm que de python ..

**Comment by Idaline** [comment]
Oui ça parait être un problème de nvm, mais c'est depuis l'installation de pyenv que ça me fait ça, et juste charger bashrc règle le soucis. Voici le log entier : 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.8
3 info using node@v6.17.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle geonature@0.0.0~prebuild: geonature@0.0.0
6 info lifecycle geonature@0.0.0~build: geonature@0.0.0
7 verbose lifecycle geonature@0.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle geonature@0.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/geonatureadmin/geonature/frontend/node_modules/.bin:/home/geonatureadmin/geonature/backend/venv/bin:/home/geonatureadmin/.pyenv/plugins/pyenv-virtualenv/shims:/home/geonatureadmin/.pyenv/shims:/home/geonatureadmin/.pyenv/bin:/home/geonatureadmin/.pyenv/plugins/pyenv-virtualenv/shims:/home/geonatureadmin/.pyenv/shims:/home/geonatureadmin/.pyenv/bin:/home/geonatureadmin/.pyenv/plugins/pyenv-virtualenv/shims:/home/geonatureadmin/.pyenv/shims:/home/geonatureadmin/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle geonature@0.0.0~build: CWD: /home/geonatureadmin/geonature/frontend
10 silly lifecycle geonature@0.0.0~build: Args: [ '-c',
10 silly lifecycle   '. ~/.nvm/nvm.sh; nvm use; ng build --prod --aot=false --build-optimizer=false' ]
11 silly lifecycle geonature@0.0.0~build: Returned: code: 3  signal: null
12 info lifecycle geonature@0.0.0~build: Failed to exec build script
13 verbose stack Error: geonature@0.0.0 build: `. ~/.nvm/nvm.sh; nvm use; ng build --prod --aot=false --build-optimizer=false`
13 verbose stack Exit status 3
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid geonature@0.0.0
15 verbose cwd /home/geonatureadmin/geonature/frontend
16 verbose Linux 4.9.0-7-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v6.17.1
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 3
22 error geonature@0.0.0 build: `. ~/.nvm/nvm.sh; nvm use; ng build --prod --aot=false --build-optimizer=false`
22 error Exit status 3
23 error Failed at the geonature@0.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3, true ]

**Comment by jbrieuclp** [comment]
J'ai l'impression que c'est la version de node (node@v6.17.1) qui ne semble pas être bonne. Pourtant dans le script d'install il y a bien la commande qui impose `nvm use 10.15.3`...
Avant de lancer le script d'installation (ou de migration ou autre), exécute la commande `nvm use 10.15.3`. Si ça marche il peut être nécessaire de chercher la commande permettant de mettre cette version de node par défaut.

**Comment by RomainBaghi** [comment]
j'ai eu le même souci, mais j'ai cru que c'était lié au fait que j'utilise 'oh my zsh' et j'ai résolu le pb en chargeant nvm dans le .bashrc comme décrit dans le post précédent de jpm-cbna.

**Comment by Idaline** [comment]
Merci pour votre aide ! :) alors : 
- mon bashrc est bon (j'ai les mêmes lignes que jpm-cbna)
- mon shell ne reconnait pas la commande nvm tant que je n'ai pas sourcé mon bashrc. 
- ma version nvm est par defaut la 13

Alors j'ai trouvé la solution au problème : il faut ajouter dans bash_profile la ligne : source ~/.bashrc

Reste à savoir pour l'installation de pyenv à supprimer ça ?! En tout cas, j'espère que ça en aidera d'autre ;).

**Comment by jpm-cbna** [comment]
Voir cet article pour comprendre [la différence entre les fichiers ~/.bashrc et ~/.bash_profile](https://www.it-connect.fr/bashrc-et-bash_profile-quelle-difference/). Comme indiqué dans l'article, effectivement, `~/.bash_profile` doit sourcer `~/.bashrc`.

Sur mon poste local comme sur mes serveurs (tous sous Debian 10) je n'ai pas de fichier `~/.bash_profile` dans le "home" des utilisateurs...
