### ISSUE TITLE
Occtax - Timeout (?) sur l'envoi des médias

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1120]
En faisant les tests suite à notre maj vers gn 2.5.2, mon collegue et moi avons remarqué que : 

- l'envoi de petits médias (quelques dizaines de ko) fonctionnent bien
- l'envoi de gros médias (quelques mo) renvoie un toaster rouge avec "erreur 502, bad gateway"

**Comment by joelclems** [comment]
C'est pendant le chargement ou au traitement du fichier?

**Comment by DonovanMaillard** [comment]
Le fichier se charge bien, on a bien la barre de chargement pleine et l'icône check. C'est lors du post du relevé quon a cette info

**Comment by joelclems** [comment]
C'est bizzare normalement la taille du fichier ne joue pas à ce niveau la.
Le fichier est bien présent dans le répertoire des médias?

**Comment by DonovanMaillard** [comment]
Je viens de reproduire pour aller vérifier tout ça. C'est bien à l'upload que j'ai eu le soucis (au temps pour moi, le check vert m'a induit en erreur) avec l'erreur complète suivante : 

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>502 Bad Gateway</title> </head><body> <h1>Bad Gateway</h1> <p>The proxy server received an invalid response from an upstream server.<br /> </p> <hr> <address>Apache/2.4.38 (Debian) Server at geonature.flavia-ape.fr Port 443</address> </body></html> 

Du coup, je n'ai bien pas le média de 3,8Mo dans geonature/backend/static/medias/thumbnails. Je n'ai que ma petite image de quelques kilos postée sur le relevé précédent.

**Comment by jpm-cbna** [comment]
Le problème doit venir du _timeout_ de la config du proxy dans le fichier Apache pour GeoNature. Il faut surement indiquer une valeur de _timeout_ équivalante à celle configurer dans le fichier `config/settings.ini` pour Gunicorn.

Il me semble que j'ai eu un problème équivalant pour les téléchargements de la Synthese. J'ai passé la valeur du paramètre `gun_timeout` du fichier `config/settings.ini` à `300` (secondes). En suite dans la config Nginx pour GeoNature, au niveau du proxy de l'API, j'ai rajouté les paramètres `proxy_read_timeout` (à 300 secondes aussi) et `proxy_connect_timeout` ceci:
```
location ^~ "/api/" {
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    
        # WARNING: up timeout to 300s for Synthese downloading
        # Set timeout like Gunicorn in GeoNature config/settings.ini file
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s; 
        proxy_pass http://127.0.0.1:8000/;# ATTENTION : bien mettre un slash final ! Sinon => 404
    }  
```
