### ISSUE TITLE
Occtax - Paramètre non fonctionnel pour l'outil de paramétrage de la saisie

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1121]
La roue crantée pour paramétrer la saisie est désactivée par défaut. 

En revanche le paramètre qui devrait permettre de l'afficher n'est pas fonctionnel, on ne peut pas activer la fonction :)

**Comment by TheoLechemia** [comment]
Non reproduit sur la 2.5.2.
Fait voir ton fichier de config ?

**Comment by jbdesbas** [comment]
OK pour moi sur la 2.5.5, l'ajout du paramètre _ENABLE_SETTINGS_TOOLS = true_ réactive bien la roue crantée.

**Comment by camillemonchicourt** [comment]
OK merci pour le retour. Idem pour nous.

**Comment by DonovanMaillard** [comment]
Ok aussi sur notre instance, merci ;)
