### ISSUE TITLE
question sur champ id_nomenclature_obs_meth

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#1123]
le champ id_nomenclature_obs_meth est remplacé par id_nomenclature_obs_technique dans la version 2.5.x de geonature mais dans la synthese la colonne pointe toujours sur les nomenclature du type 'obs_meth'. 
Du coup je ne comprends plus très bien. C'est parce que le standard a évolué dans ce sens ?

**Comment by TheoLechemia** [comment]
On a pas changé le mnemonique du type pour des problèmes d'intégrité. Le code "OBS_METH" est également utilisé en dur dans le code pour éviter d'utilisé les "id_nomenclatures".
Les nomenclature du type "OBS_METH" n'ont pas changé, mais ils correspondent maintenant au champs "id_nomenclature_obs_technique"

**Comment by camillemonchicourt** [comment]
Oui on a vraiment galéré avec ce changement de nom de champs "Méthode d'observation" en "Technique d'observation".
D'autant plus car par ailleurs, on avait anticipé l'intégration de Campanule en mettant un champs "Technique d'observation" dans GeoNature, en plus de "Méthode d'observation". On a donc du mettre ce champs de côté et renommer partout "Méthode d'observation" en "Technique d'observation".
Mais pour la nomenclature, on a gardé son nom ``OBS_METH``. Ça apporte de la confusion mais c'était plus simple par rapport aux contraintes d'intégrité comme indique Théo.

Cependant ce n'est pas idéal et confusant comme tu le soulignes. A voir si ça peut être revu aussi au niveau de la nomenclature pour bien aligner à tous les niveaux.
