### ISSUE TITLE
Problème de stockage à l'installation de GeoNature 2.5.2

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature#1125]
Bonjour,

Je cherche actuellement à installer un version neuve de GeoNature 2.5.2 sur un Debian 10.6

Je n'arrive malheureusement pas à accèder à GeoNature, ni UsersHub et TaxHub
Pouvez-vous m'aider à déchiffrer les logs svp ? 🙂
[install_db.log](https://github.com/PnX-SI/GeoNature/files/5487279/install_db.log)
[install_all.log](https://github.com/PnX-SI/GeoNature/files/5487280/install_all.log)

J'ai l'impression qu'il y a eu un problème de place sur les partitions... Pour info, voici les espaces disques de chaque part:
**root:** 5,4 GiB
**swap_1:** 24 GiB
**var:** 2,1 GiB
**tmp:** 440 MiB
**home:** 28 GiB

**Comment by camillemonchicourt** [comment]
En effet au moment de l'intégration des données INPN dans TaxHub (assez volumineuses) il semble y avoir eu un problème de place sur le disque, peut-être temporaire mais bloquant : 

```
TRUNCATE TABLE
psql:tmp/taxhub/data_inpn_taxhub.sql:158: PANIC:  n'a pas pu écrire dans le fichier « pg_wal/xlogtemp.23246 » : Aucun espace disponible sur le périphérique
la connexion au serveur a été coupée de façon inattendue
	Le serveur s'est peut-être arrêté anormalement avant ou durant le
	traitement de la requête.
psql:tmp/taxhub/data_inpn_taxhub.sql:158: la connexion au serveur a été perdue
```

Ensuite tout a planté car la BDD était alors en restauration : 

```
psql: FATAL:  le système de bases de données est en cours de restauration
FATAL:  le système de bases de données est en cours de restauration
```

Je n'y connais pas grand chose sur le sujet, mais je note que ton espace ``tmp`` a un espace limité, c'est peut-être là qu'a été le soucis car on y stocke des données temporairement le temps de les traiter. Et peut-être que PostgreSQL y fait des choses temporaires aussi le temps de traiter/insérer des données ?

**Comment by jpm-cbna** [comment]
Pourriez vous utiliser la commande suivante sur le serveur et nous fournir le résultat ?
La commande: `df -h` 
La commande affiche l'espace disque max et restant pour chaque partition.

**Comment by maximetoma** [comment]
Nous avons refait un test en augmentant les capacités des partitions var et temp à 7 et 5 Go respectivement et cela a fonctionné (problème d'espace donc)

Voici tout de même le résultat de la commande `df -h`:
![taille](https://user-images.githubusercontent.com/66769358/98127459-0532dd00-1eb7-11eb-84df-7f9ae9f3e3af.jpg)
