### ISSUE TITLE
Utiliser Fontawesome avec Mat-Icon

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature#1127]
Afin de pouvoir privilégier l'utilisation d'Angular Material au sein de GeoNature, il serait intéressant de pouvoir utiliser [les icônes Fontawesome](https://fontawesome.com/v4.7.0/icons/) avec [le composant Angular Material MatIcon](https://v7.material.angular.io/components/icon/api#MatIcon).

Il est possible de suivre [les indications suivantes](https://stackoverflow.com/questions/43837076/how-to-correctly-register-font-awesome-for-md-icon) afin d'enregistrer les icônes Fontawesome  (v4.7.0) auprès d'Angular Material.
Cette logique sera ajouter au fichier `GN2Common.module.ts` qui s'occupe actuellement de l'import des composant Material.

Cela permet ensuite d'utiliser le composant ainsi : `<mat-icon fontSet="fa" fontIcon="fa-shield"></mat-icon>`

**Notes** : au passage, nous pourrons trier alphabétiquement les _imports_, _declarations_, _providers_... cela permettra de rechercher plus rapidement un élément.

**Comment by TheoLechemia** [comment]
C'est parce que tu ne trouve pas les icones que tu veux dans ceux de material ?

**Comment by jpm-cbna** [comment]
Disons que les icônes Material sont bien riches mais il en manque toujours pour bien désigner ce que l'on souhaite...
En outre, ils sont déjà utilisé mais avec la syntaxe de base. En les enregistrant ainsi, cela favorisera l'utilisation de Material.
Enfin, la modification dans le code est vraiment légère...
