### ISSUE TITLE
Installation - paramètre grid à améliorer

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1133]
Sans le settings.ini de l'install all, si on passe le paramètre 

```
# Installe les grilles INPN (1, 5 et 10km)
install_grid_layer=false
```

Le script fait quand même le téléchargement des grilles et l'insertion en base...

**Comment by camillemonchicourt** [comment]
En effet la valeur de ce paramètre n'est pas répercuté dans le fichier ``settings.ini``. Voir https://github.com/PnX-SI/GeoNature/blob/master/install/install_all/install_all.sh#L148-L173

**Comment by DonovanMaillard** [comment]
fait dans la PR #1158
