### ISSUE TITLE
erreur lors de l'installation

### ISSUE THREAD

**Issue by David61200** [PnX-SI/GeoNature#1140]
Bonjour à tous
Néophyte dans le domaine, j'ai tenté à de multiples reprises d'installer geonature sur un serveur ovh (4 Go de ram, debian 10).
J'ai suivi les instructions pas à pas. j'ai même regardé un petit tuto sur YouTube montrant les différentes étapes :
https://www.youtube.com/watch?v=JYgH7cV9AjE
A la fin de l'installation j'ai bien le message que l'installation est terminé. j'arrive à aller sur la page de taxhub et de usershub sans problème. Par contre lorsque je vais sur ma page de geonature j'ai le message suivant:
"You don't have permission to access this resource."

Dans le fichier install-all.log j'ai trouvé ces messages d'erreurs:

File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "gn_permissions.t_actions" does not exist
LINE 2: FROM gn_permissions.t_actions
....

ENOENT: no such file or directory, stat '/home/geonatureadmin/geonature/frontend/src/tsconfig.app.json'
Error: ENOENT: no such file or directory, stat '/home/geonatureadmin/geonature/frontend/src/tsconfig.app.json'
...
error: taxhub:1 glob failed for /home/geonatureadmin/taxhub/var/log/*.log: Aucun fichier ou dossier de ce type
error: found error in file taxhub, skipping
error: uhv2:1 glob failed for /home/geonatureadmin/usershub/var/log/*.log: Aucun fichier ou dossier de ce type
error: found error in file uhv2, skipping

...

ERROR: CANT_REREAD: The directory named as part of the path /home/geonatureadmin/taxhub/var/log/taxhub-errors.log does not exist in section 'program:taxhub' (file: '/etc/supervisor/conf.d/taxhub-service.conf')
Restarted supervisord

Pouvez vous m'aider ?
Cordialement
David

**Comment by camillemonchicourt** [comment]
Merci pour ce retour. Il y a peut-être un problème lors de l'installation qui nous a échappé dans la version 2.5.3.

Pourriez partager des logs plus complets avec les fichiers complets : 

> Si vous rencontrez une erreur, se reporter aux fichiers de logs :
> 
>     Logs de l’installation de la base de données : /home/<MY_USER>/geonature/var/log/install_db.log
>     Log général de l’installation de l’application : /home/<MY_USER>/install_all.log

**Comment by David61200** [comment]
Je n'ai pas trouvé le fichier d'installation de la base de donnée. A la place j'ai trouvé le fichier gn_errors.log.
[gn_errors.log](https://github.com/PnX-SI/GeoNature/files/5528945/gn_errors.log)
[install_all.log](https://github.com/PnX-SI/GeoNature/files/5528946/install_all.log)

**Comment by camillemonchicourt** [comment]
Hum le fichier de log est censé être dans ``/home/<MY_USER>/geonature/var/log/install_db.log``, mais en effet je ne l'ai pas de mon côté non plus. A creuser.

Pour vos logs, en effet il semble y avoir un problème avec la table ``gn_permissions.t_actions`` qui serait manquante.
C'est dommage de pas avoir le logs d'installation de la BDD car c'est lui qui en dirait plus.

**Comment by camillemonchicourt** [comment]
On a jeté un oeil avec @amandine-sahl.
Plusieurs erreurs nous étonnent.
On se demande si vous n'avez pas lancer l'utilisateur avec l'utilisateur ``root`` et avez donc plusieurs problèmes de droits.

Car dans le fichier gn_errors.log il y a : ``Error: Error: '/home/geonatureadmin/geonature/var/log/gn_errors.log' isn't writable [PermissionError(13, 'Permission denied')]``

Il nous manque les logs de la BDD.

La table manquante est censée être installée par https://github.com/PnX-SI/GeoNature/blob/master/data/core/permissions.sql#L167

Vous pouvez réessayer l'installation de la BDD. Mais on suspecte un problème de permissions.

Pouvez-vous exécuter la commande ``ls -l`` dans le répertoire ``/home/geonatureadmin/geonature/`` et ``/var/log`` ? Et nous coller ce qu'elles renvoient ?

**Comment by David61200** [comment]
J'ai peut être mal interprété la phrase suivante :"Commencer la procédure en se connectant au serveur en SSH avec l’utilisateur linux root."
Avec OVH, je n'arrive pas a mettre a jour la liste des dépôts et d’écrire avec la commande suivante: nano /etc/apt/sources.list
Au départ je suis sous le nom d'utilisateur debian@vps...
Dois-je rester avec cet utilisateur ou bien passer en root@vps... ?

**Comment by amandine-sahl** [comment]
Le mieu est d'utiliser ponctuellement les droits super utilisateur. 
Pour cela il faut ajouter l'utilisateur debian au groupe root (si ce n'est pas le cas) pour pouvoir faire des commandes en utilisant sudo.

En tant que root faire : `adduser debian sudo` puis se déconnecter et se reconnecter avec l'utilisateur debian

**Comment by camillemonchicourt** [comment]
Oui le début de l'installation du serveur se fait avec ``root``. 
Mais ensuite il faut pas faire l'installation de GeoNature avec ``root`` qui est le super-administrateur, mais avec un autre utilisateur.
C'est bien indiqué dans la documentation : 

> Créer un utilisateur linux (nommé geonatureadmin dans notre cas) pour ne pas travailler en root

[...]

> Pour la suite de la documentation et pour l’administration courante de GeoNature, on n’utilisera plus jamais l’utilisateur root (utiliser geonatureadmin dans l’exemple de la documentation; su geonatureadmin pour change d’utilisateur). Si besoin d’exécuter des commandes avec des droits d’administrateur, on les précède de sudo.

**Comment by jpm-cbna** [comment]
> Dois-je rester avec cet utilisateur ou bien passer en root@vps... ?

@David61200 Sur les serveurs OVH, par défaut l'utilisateur `debian` fait partie du groupe `sudo`. En tout cas, c'est le cas sur les instance Public Cloud d'OVH. Sinon, suivre les indication fournie par @amandine-sahl.

**Comment by David61200** [comment]
je vous remercie tous pour votre aide précieuse. J'ai tout réinstallé... et cela fonctionne ;-)
Je pense que le problème provenait de la modification (ou de la mise en place) du mot de passe sur le root.
