### ISSUE TITLE
Mise à jour GeoNature 2.5.3, problème avec les modules externes

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature#1145]
Bonjour,

J'essaie actuellement de faire la mise à jour de la version 2.5.2 vers la 2.5.3. C'est la première fois que je fais une mise à jour GeoNature et je ne sais pas si ce problème existait déjà...

J'ai un plantage à la fin du script de migration à cause semblerait-il du module Dashboard (et monitoring peut-être). Quand je vais voir dans les dossiers serveur, j'ai effectivement une erreur sur les raccourcis vers Dashboard et Monitoring dans `geonature/external_modules`.

Voici l'erreur à la fin du script et le fichier de log mentionné:
![BUG_MAJ](https://user-images.githubusercontent.com/66769358/99237607-050cd880-27f9-11eb-80b7-93c8a1f7998d.jpg)

[2020-11-16T08_16_08_554Z-debug.log](https://github.com/PnX-SI/GeoNature/files/5545431/2020-11-16T08_16_08_554Z-debug.log)

Savez-vous pourquoi il y a un problème avec les module externes et la MAJ ? J'ai installé les dernière versions des deux modules.

[EDIT:] J'ai oublié effectivement de mentionner que les dossiers de monitoring et dashboard ne se copient pas depuis `geonature_old`

**Comment by maximetoma** [comment]
EDIT: C'est bon, effectivement j'ai réessayé en copiant les modules externes depuis `geonature_old` vers le nouveau `geonature` avant de lancer le script de MAJ et ça fonctionne à merveille :)

**Comment by camillemonchicourt** [comment]
Tu as copié manuellement certains modules avant de lancer le script de MAJ ?

**Comment by maximetoma** [comment]
Oui, Dashboard et Monitoring (qui sont les seuls modules externes que j'avais installé)

**Comment by camillemonchicourt** [comment]
OK j'ai une migration qui a raté hier, c'est du coup peut-être car il fallait que je migre manuellement le module Dashboard avant de la lancer le script.

**Comment by maximetoma** [comment]
Ah oui peut-être

**Comment by camillemonchicourt** [comment]
On a retesté, le script ``migrate.sh`` récupère bien tous les modules externes lors de son exécution.

**Comment by DonovanMaillard** [comment]
Même soucis chez moi en passant de 2.5.2 à 2.5.5. Le monitoring n'a pas suivi, j'ai une erreur 404 aujourd'hui ;)

**Comment by camillemonchicourt** [comment]
Plus de précisions ? Des erreurs renvoyées lors de la migration ? 
Je crois pas que ce soit le même soucis. On ne voit pas pourquoi @maximetoma a eu ce soucis.
On a fait une MAJ hier de 2.4.1 à 2.5.3 et pas de soucis, le script ``migrate.sh`` a bien rapatrié tout le contenu du dossier ``external_modules``.
Il le fait ici : https://github.com/PnX-SI/GeoNature/blob/master/install/migration/migration.sh#L42

Par contre pour toi, pour les sous-modules de monitoring c'est autre chose. Ils ne sont pas prévus ni connus de GeoNature lors de sa migration. 
Ils sont rangés à quel endroit dans ton serveur ?

A noter par contre qu'il y avait un autre soucis dans la récupération des fichiers dans le dossier ``backend/static`` mais c'est autre chose et ne bloque pas la migration. Corrigé dans la 2.5.5 sortie hier : https://github.com/PnX-SI/GeoNature/commit/b9c74752e6d1b89cc163aa24255eddb8e69e30e1

**Comment by DonovanMaillard** [comment]
Ok, je creuse un peu pour voir si je trouve et au besoin j'ouvre un ticket à part. 

Ils sont rangés sur /home/monuser/mon_sous_module.

**Comment by camillemonchicourt** [comment]
Oui il y a des liens symboliques qui sont créés vers les sous-modules quand on les installe mais je ne sais plus à quel endroit. Ils ne doivent pas être rapatriés par le script migrate.sh car Monitoring est un module à part. Mais on pourrait l'ajouter dans le script de migration en vérifiant avant si le dossier existe.
