### ISSUE TITLE
[OCCTAX ?] Problème de CRUVED

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#1146]
Je rencontre un problème lorsque je souhaite ajouter une observation à un relevé existant dont je ne suis ni observateur ni auteur (digitiser), pourtant j'ai des droits CRUVED à 3 (toutes les données) sur l'ensemble du module.
Dans ma table `gn_permissions.v_roles_permissions` j'ai des doublons pour un même module (`id_module`), une même action (`id_action`), un même objet (`id_object`) je peux avoir plusieurs filtre (`id_filter`) mes données et toutes les données en parallèle, qui proviennent de mes différents groupes de rattachement.
Dans OCCTAX (au moins dans OCCTAX) la variable `info_role`, utilisée dans les tests de droits, est chargée d'une donnée provenant de la table `gn_permissions.v_roles_permissions`, mais il me charge la ligne où j'ai le moins de droits (`id_filter = mes données`).

Du coup est-ce que c'est la table `gn_permissions.v_roles_permissions` qu'il faut retravailler pour prendre la valeur max des droits par module/action/objet ? Est-ce qu'il faut modifier le backend OCCTAX pour gérer les accès en utilisant la fonction `gn_permissions.cruved_for_user_in_module` ?

**Comment by Splendens** [comment]
J'ai eu le même problème sur les utilisateurs mis dans plusieurs groupes : le niveau des droits semble attribué aléatoirement / en fonction du dernier groupe défini / en fonction du dernier paramétrage dans le backoffice (?).

Le plus logique serait de récupérer le niveau de droit le plus élevé.

**Comment by jbrieuclp** [comment]
Un p'tit up sur ce sujet !
Personne d'autre n'a été confronté à ce problème dans d'autre module ?

**Comment by TheoLechemia** [comment]
> Le plus logique serait de récupérer le niveau de droit le plus élevé.

C'est le cas. Sauf si pour un groupe on a surcouché le CRUVED spécifiquement à un module, et que l'autre hérite de GeoNature, alors c'est le CRUVED surcouché qui prend le dessus.

J'essaye de regarder dans la semaine.

**Comment by jbrieuclp** [comment]
Bon je me faisait chier à dérouler l'algo pour exposer le problème, en fait la solution c'est ça :
Dans la fonction `get_user_permission`, la variable `module_code` n'est pas transmise à la fonction `query_user_perm`
https://github.com/PnX-SI/GeoNature/blob/a6891418b153d74111d01d9b870f628148b25649/backend/geonature/core/gn_permissions/tools.py#L173-L178 

Il faut modifier en ce sens pour ajouter la petite ligne fautive car absente `module_code=module_code,` :
```
user_cruved = query_user_perm(
        id_role=user["id_role"],
        code_filter_type=code_filter_type,
        code_action=code_action,
        module_code=module_code,
        object_code=code_object,
    )
```
Le `module_code` n'étant jamais envoyé, c'était les droits de GEONATURE qui était pris en compte, partout tout le temps !

Plus haut j'indiquais que je m'étais fait chier à dérouler l'origine du problème, du coup ça me fait de la peine de l'effacer. Si ça peut servir à comprendre le cheminement, façon boucher, je vous le mets dessous ! "_Il y'en a un petit peu plus, je vous le mets quand même !_"

--------



Pour le contexte, je suis dans le module OCCTAX et j'utilise un utilisateur présent dans 2 groupes d'utilisateurs :
- groupe 1 : "utilisateurs tout venant" = pour OCCTAX droit CRUVED sur ces propres données.
- groupe 2 : "salariés administrateurs" = pour OCCTAX droit CRUVED sur toutes les données de la BD.

Pour décrire le truc, ça se passe comme ça :
A l'ajout d'une observation dans un relevé dont je ne suis ni le créateur, ni observateur, je soumets mon formulaire qui arrive ici :
https://github.com/PnX-SI/GeoNature/blob/a6891418b153d74111d01d9b870f628148b25649/contrib/occtax/backend/blueprint.py#L560-L562
Les permissions de mon utilisateur sont vérifiées et il a des droits d'écriture pour OCCTAX => ok, il rentre dans la fonction. Au passage les info utilisateurs sont stockées dans la variable info_role.

Au niveau de la fonction OccurrenceHandler, il est vérifié les droits de modification sur le relevé auquel est ajouté l'occurrence.
https://github.com/PnX-SI/GeoNature/blob/a6891418b153d74111d01d9b870f628148b25649/contrib/occtax/backend/blueprint.py#L545
Et c'est à ce niveau là que ça coince, la fonction va vérifier le niveau de "filter" (=mes données, celles de mon organisme ou toutes les données)  présent dans la variable info_role, et en ce qui me concerne filter = 1 (=Mes données), je n'ai donc pas les droits d'ajouter d'occurrence sur ce relevé !

En fait c'est directement le décorateur `@permissions.check_cruved_scope` qui est trompé. Il se charge de récupérer l'utilisateur à partir du token et de récupérer ses droits depuis la vue `gn_permissions.v_roles_permissions` à partir de cette fonction 
https://github.com/PnX-SI/GeoNature/blob/a6891418b153d74111d01d9b870f628148b25649/backend/geonature/core/gn_permissions/tools.py#L135-L137

**Comment by TheoLechemia** [comment]
Merci d'avoir investigué et levé le bug ! Pour info, c'est une erreur qui date de l'implémentation de l'héritage au niveau des objets, ou j'avais fait pas mal de refactoring (https://github.com/PnX-SI/GeoNature/issues/1028) donc présent que depuis la 2.5.3
