### ISSUE TITLE
2.5 - Refonte fiche info et regressions

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#1147]
Quand j'ouvre la fiche info d'une observation OCCTAX dans la Synthèse :
- Je n'ai plus le bouton pour revenir à l'obs dans son module d'origine (Occtax) alors que c'était utile sur la fiche info
- J'ai un message indiquant "Aucun historique de validation" >> Je suis pas sur que cette info soit utile. Et de plus il devrait à minima y avoir une validation automatique lors de la saisie initiale ?

**Comment by TheoLechemia** [comment]
Il y a une validation automatique (valeur par défaut), mais pas d'historique car pas d'action manuel sur le statut de validation (aucune ligne dans t_validation)

**Comment by camillemonchicourt** [comment]
OK logique en effet 
Du coup ne pas afficher ce message car pas utile et laisse penser à une erreur ?

**Comment by TheoLechemia** [comment]
Oui j'ai désactivé le message. commit in progress !
