### ISSUE TITLE
[GN 2.5.2] les médias des taxons sont supprimés automatiquement ?

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/GeoNature#1148]
Je rencontre un soucis sur les médias associés aux dénombrements : j'ai l'impression que le ménage est fait régulièrement, sans qu'il n'y ai eu une intervention directement dans OccTax.

Pour tester, j'ai ajouté des observations avec un média associé. Le fichier était bien présent dans le dossier des médias, et présent en BD dans la table gn_common.t_medias avec le chemin d'accès à la photo et l'uuid associé à la bonne observation. Bref tout fonctionne correctement à l'ajout d'un média.

Et quelques jours plus tard, sans que je n'ai touché à quoi que ce soit, mes fichiers ont été renommés en "deleted_.." et les lignes correspondantes supprimées en BD.

(Concernant le pas de temps, je ne sais pas exactement : aujourd'hui le 16, j'ai toujours mes photos ajoutées le 13, mais pas celles ajoutées le 10.)

Est-ce que ce "nettoyage" est paramétrable ? 
Existe-t-il une procédure pour rétablir les médias supprimés ?

**Comment by joelclems** [comment]
Un immense merci de relever cet ennorme bug. 

Normalement le commit d25df97 permet de le resoudre en ne supprimant que les fichier vieux de plus de 24 h **Et** non associé à un média (uuid_attached_row est NULL).

Pour rétablir les médias, renommer les fichiers en enlevant le deleted_ devrait faire l'affaire. Les thumbnails eux sont créés *à la demande*

**Comment by Splendens** [comment]
Merci pour la réponse rapide !

J'ai testé le commit, et quand je lance un `geonature update_configuration`  je reçois l'erreur _`Syntax error : invalid syntax`_. Il a pas l'aire d'aimer le `and_`.

Pour le rétablissement des médias, sachant que les entrées en BD ont été supprimées, il va donc falloir tout repeupler à la main ?

**Comment by Splendens** [comment]
Bon, je ne devais pas avoir les yeux bien en face des trous quand j'ai copié le commit. Pas de soucis, ça passe !

**Comment by joelclems** [comment]
Effectivement il faut repeupler à la main car ils sont supprimé en base

**Comment by camillemonchicourt** [comment]
OK et donc il faut sortir une version corrective dès que possible en indiquant la méthode si des gens ont ajouté des médias dans des versions précédentes ?

**Comment by joelclems** [comment]
oui il faut sortir une version corrective dès que possible, par contre les médias sont perdus en base, il reste que les fichiers

**Comment by camillemonchicourt** [comment]
OK et est-ce que le nom de fichier permet de retrouver le lien avec l'objet auquel il avait été initialement rattaché ?

**Comment by joelclems** [comment]
Non c''est le nom du fichier d'origine

**Comment by joelclems** [comment]
La table `gn_commons .t_history_actions` contient toutes les opérations effectuées sur les médias, et donc les informations sur les médias supprimés

**Comment by camillemonchicourt** [comment]
Quelques précisions.
Les médias sont stockés dans une table transversale ``gn_commons.t_medias``. 
Physiquement ils sont stockés dans le dossier : ``/home/myuser/geonature/backend/static/medias``

Par exemple ``/home/myuser/geonature/backend/static/medias/2/43_plan_circulation_r.png`` où 2 correspond à son ``id_table_location`` et 43 à son ``id_media``.

A chaque fois qu'une action est realisée sur un média (ajout, modification, suppression), un script Python est exécuté pour vérifier les éventuels médias orphelins (associés à un objet qui n'existe plus), les supprimer de la table ``gn_commons.t_medias`` et renommer le fichier sur le serveur en le préfixant avec ``deleted_``.

Sauf qu'actuellement il y a un bug depuis la version 2.5.0 et tous les médias sont considérés comme orphelin et donc supprimés après 24h et une nouvelle action sur un média.
@joelclems a corrigé et identifié le bug et nous préparons une version 2.5.4 corrective.
Pour celle-ci @joelclems regarde comment restaurer les médias supprimés de la table ``gn_commons.t_medias`` grace à la table stockant tout l'historique des actions dans GeoNature (``gn_commons.t_history_actions``).
On peut déjà identifier toutes les suppressions de médias avec la requête : ``SELECT * FROM gn_commons.t_history_actions WHERE table_content->'id_media' IS NOT NULL AND operation_type = 'D'``

**Comment by joelclems** [comment]
Dans 5586dd0 Je propose deux scripts pou r pouvoir récupérer les médias
- `data/medias/restore_medias.sql` qui permet de recréer les ligne des médias dans`gn_commons.t_medias` depuis `gn_commons.t_history_actions`
-`data/medias/restore_medias.sh` pour renommer les fichier en enlevant `deleted_`

la combinaison des deux doit permettre de retrouver les médias

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.5.4

**Comment by Splendens** [comment]
Merci Joël !

La commande : `find . -type f -wholename './backend/static/medias/*deleted_*' | sed -e 'p;s/deleted_//' | xargs -n2 mv` fonctionne bien mais il y a un problème de droits non accordés (régler en passant root ou en mettant des sudo dans la commande.)

**Comment by joelclems** [comment]
si on met un sudo d'office, j'ai peur que cela perturbe les droits et que cela empeche flask de modifier ces fichiers, mais je ne maitrise pas du tout la question
