### ISSUE TITLE
Problème de version NVM

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#1159]
Lors d'une migration vers GN 2.5.4 sur un serveur Debian 10, l'erreur suivante se produit au moment de l'installation des paquets npm (script `migrate.sh`)
```
Found '/home/geonatadmin/geonature/frontend/.nvmrc' with version <v10.15.3>
Now using node v10.15.3 (npm v6.4.1)

> core-js@2.6.11 postinstall /home/geonatadmin/geonature/frontend/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
```
le script bloque à cette étape sans jamais rendre la main.

Une solution a été trouvé en changeant la version de NVM dans le fichier .nvmrc à `v10.16.3`.

TODO: étudier la possibilité de monter la version de nvm fournie par défaut. Voir https://github.com/PnX-SI/GeoNature-citizen/issues/244

**Comment by camillemonchicourt** [comment]
Ancienne version de GeoNature, Node.js a été mis à jour depuis.
