### ISSUE TITLE
utilisateur geonatadmin non visibles après un full install 2.5.5

### ISSUE THREAD

**Issue by olivier8064** [PnX-SI/GeoNature#1163]
Bonjour, 
Désolé si je pose une question de newbie linux..
J'ai fait une installation complète de geonature 2.5.5 sur Debian 9 (OVH). 
Je voudrais faire l'installation de tous les taxons de taxref avec les instructions pour "Personnaliser la liste des taxons saisissables dans le module" donc en me connectant à la base geonature2db avec l'utilisateur geonatadmin et non postgres..
en tapant cette instruction : 
`postgres@vps700912:~$ psql -d geonature2db -U geonatadmin`
j'ai ce message : 
`psql: FATAL:  authentification peer échouée pour l'utilisateur « geonatadmin »`
J'ai essayé d'autres méthodes.. Mais l'utilisateur geonatadmin n'est pas présent. J'ai vérifié en listant tous les utilisateurs : 
cat /etc/passwd | awk -F: '{print $ 1}'
je vois bien postgres, geonatureadmin etc.. mais pas geonatadmin..
J'ai bien réussi à me connecter à geonature2db mais avec l'utilisateur postgres comme le montre cette instruction \conninfo
```
geonature2db=# \conninfo
Vous êtes connecté à la base de données « geonature2db » en tant qu'utilisateur « postgres » via le socket dans « /var/run/postgresql » via le port « 5432 ».
```
pourtant lorsque je me connect avec l'utilisateur postgres et que je liste les bases (\l) j'ai bien 
le nom de la base "geonature2db" dont le propriétaire est "geonatadmin"

```
  Liste des bases de données
     Nom      | Propriétaire | Encodage | Collationnement | Type caract. |    Droits d'accès
--------------+--------------+----------+-----------------+--------------+-----------------------
 geonature2db | geonatadmin  | UTF8     | fr_FR.UTF-8     | fr_FR.UTF-8  |
 postgres     | postgres     | UTF8     | fr_FR.UTF-8     | fr_FR.UTF-8  |
 template0    | postgres     | UTF8     | fr_FR.UTF-8     | fr_FR.UTF-8  | =c/postgres          +
              |              |          |                 |              | postgres=CTc/postgres
 template1    | postgres     | UTF8     | fr_FR.UTF-8     | fr_FR.UTF-8  | =c/postgres          +
              |              |          |                 |              | postgres=CTc/postgres

```

Si une âme charitable peux me dire où je fais fausse route...

**Comment by camillemonchicourt** [comment]
Attention en passant, depuis la version 2.5 on ne supporte plus Debian 9, on est passé sur Debian 10.
Donc c'est pas conseillé du tout de faire des installations en Debian 10.

Pour le soucis indiqué, il faudrait voir si l'installation s'est bien passée mais j'en doute si c'est en Debian 9.

Il faudrait les logs (install_all.log et install_db.log) indiqués dans la documentation d'installation.

**Comment by camillemonchicourt** [comment]
Mais sinon si l'utilisateur geonatadmin est bien indiqué comme propriétaire de la BDD, alors c'est certainement uniquement la commande de connexion qui n'est pas bonne. Il faut renseigner le mot de passe de l'utilisateur geonatadmin.


Voir par exemple https://alvinalexander.com/blog/post/postgresql/log-in-postgresql-database/
"If for some reason you are not prompted for a password when issuing these commands, you can use the -W option, leading to these two command alternatives:

psql -d mydb -U myuser -W psql -h myhost -d mydb -U myuser -W
"

**Comment by olivier8064** [comment]
Je me suis trompé j'ai bien fait l'installation sur debian 10.

**Comment by camillemonchicourt** [comment]
OK tant mieux.
Alors je pense que c'est bon et que c'est juste la commande de connexion à ajuster. Voir ci-dessus.

Sinon ouvre les accès à ta BDD et essaie de t'y connecter avec pgAdmin ou QGIS.

**Comment by olivier8064** [comment]
Bon j'avais essayé de me connecter à geonatadmin avec pgadmin et ça ne fonctionnait pas... j'ai refait une installation complète et ça marche enfin. Je ne comprends pas ce qui s'est passé. La seule différence, c'est que la première fois, j'avais oublié de faire un "exec bash" à la fin de l'installation. 
L'essentiel est que ça fonctionne maintenant !

**Comment by fredperso** [comment]
Le problème de connexion évoqué dans le premier message est tout à fait normal ;) 

Le rôle de base de données `geonatadmin` existe bien sur ton serveur car il est propriétaire de la bdd geonature2db, mais il est uniquement un rôle de base de données postgresql, pas un compte système sur le serveur. 

Généralement pour une installation classique c'est `geonatuser` qui est l'utilisateur système (donc dans `/etc/passwd`, etc.).  

Dans ce cas, lancer un `psql -U geonatadmin -d geonature2db` soulèvera toujours une erreur, même depuis le compte système `postgres`. En fait, c'est lié aux modes d'authentification de PostgreSQL (dans le fichier de config `pg_hba.conf`).

Si on fait `psql -U mondbuser mabase` sans spécifier d'hôte (`-h monhote`), alors on est en type d'authentification `local` donc en mode `peer`. Dans ce cas de figure, seul les utilisateurs systèmes sont autorisés à se connecter et s'ils se connectent depuis leur compte, il ne leur alors est pas demandé de mot de passe. L'option  `-W` permet de demander un mot de passe mais la connexion échoue quand même (*because* `peer` :). 

Pour se connecter localement avec un utilisateur non système. La solution est simplement d'ajouter un hôte soit `psql -h monhote -U mondbuser mabase`, ce qui passe donc la connexion en mode `host` ou là, on est sur une méthode `md5`, donc avec mot de passe.

Plus d'infos sur la doc officielle ici: https://docs.postgresql.fr/11/auth-pg-hba-conf.html

A ce propos, @camillemonchicourt, y a-t-il une raison pour que, dans l'install habituelle, le propriétaire de la bdd geonature `geonatadmin` n'ai pas le même nom que l'utilisateur système `geonatuser` ?

**Comment by olivier8064** [comment]
@fredperso Merci beaucoup ! c'est tellement plus clair, je n'arrivais pas à trouver ces explications et je me doutais bien qu'il me manquait la lumière du SAVOIR :) Merci d'avoir éclairé ma lanterne ;)

**Comment by camillemonchicourt** [comment]
En effet, merci pour ces précisions car je ne suis pas calé sur le sujet.
Mais il y avait bien une confusion entre utilisateur serveur (linux) et utilisateur BDD (PostgreSQL).
Et sur la commande à exécuter avec un utilisateur PostgreSQL qui n'est pas aussi un utilisateur linux, pour laquelle il faut donc préciser l'hôte.

Quand on installe PostgreSQL sur un serveur linux, il créé un utilisateur serveur linux nommé ``postgres`` qui est aussi un utilisateur (superuser) de PostgreSQL.

Pour installer GeoNature, il faut créer un utilisateur linux, que l'on propose de nommer ``geonatureadmin`` mais qui être nommé autrement : https://github.com/PnX-SI/GeoNature/blob/master/docs/installation-all.rst#installation-de-lapplication.

Pour la BDD, il faut aussi créer un utilisateur de BDD que l'on propose de nommer ``geonatadmin`` mais là aussi il peut être nommé différemment : https://github.com/PnX-SI/GeoNature/blob/master/config/settings.ini.sample#L34

A une époque on proposait aussi de nommer l'utilisateur serveur et l'utilisateur de la BDD de la même manière (``geonatadmin``) mais on a justement préféré les différencier par défaut pour éviter les confusions des administrateurs entre l'utilisateur serveur et l'utilisateur BDD. Ça embrouillait les administrateurs. On pourrait même d'ailleurs leur mettre un nom encore plus différent pour encore moins de confusion.

On n'a plus d'utilisateur système nommé ``geonatuser``. On l'a peut-être utilisé à un moment, mais je n'en trouve plus vraiment de traces. On avait un utilisateur de BDD précédemment dans GeoNature v1 avec ce nom, utilisé uniquement pour l'application donc avec des droits plus faibles que ``geonatadmin``. C'était mieux au niveau sécurité mais cela complexifiait aussi la compréhension pour les administrateurs qui ne savaient pas quel utilisateur utilisé quand. On a donc simplifié avec uniquement un utilisateur de BDD nommé par défaut ``geonatadmin``. Libre à chacun d'avoir une gestion plus fine des utilisateurs de BDD et de serveur si ils ont des compétences plus pointues sur le sujet.

Il reste encore cependant des traces de anciens noms pas toujours homogénéisés selon les projets. Par exemple si on installe TaxHub tout seul, le nom de l'utilisateur de BDD proposé par défaut est toujours nommé ``geonatuser`` : https://github.com/PnX-SI/TaxHub/blob/master/settings.ini.sample#L31

Et dans GeoNature-atlas on avait encore un utilisateur nommé ``geonatuser`` que l'on a renommé ``geonatatlas`` pour réduire les confusions dans la release corrective 1.4.2 sortie aujourd'hui : https://github.com/PnX-SI/GeoNature-atlas/commit/8466b345f075b2552f961d2cdfdf8a1b5d4be28b

Voila, c'est pas forcément idéal mais on a pris le partie de simplifier. Reste encore certainement à homogénéiser et à clarifier.
