### ISSUE TITLE
pb migration 2.5.5 2.5.6

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#1167]
Les lignes du fichier de migration 

https://github.com/PnX-SI/GeoNature/blob/85636208b25b35652ab64623742c7064bb2bff36/data/migrations/2.5.5to2.5.6.sql#L47-L51

existent déjà dans 

https://github.com/PnX-SI/GeoNature/blob/85636208b25b35652ab64623742c7064bb2bff36/data/migrations/2.5.2to2.5.3.sql#L9-L15

ce qui lève une erreur

**Comment by TheoLechemia** [comment]
En fait il y a une erreur dans le script de création.. j'ai mis un "drop if exists" avant la recréation
