### ISSUE TITLE
GeoNature 2.5.5 | Problème CRUVED, curseurs qui bougent

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature#1170]
Bonjour,

J'aurais quelques petits soucis avec le CRUVED mais je ne sais pas si cela vient que de moi...
J'ai vu qu'il y a eu un problème sur le CRUVED depuis la 2.5.3 (https://github.com/PnX-SI/GeoNature/issues/1146) et je suis passé en 2.5.5 mais j'ai quelques bizarreries:

-  Quand je définis mon CRUVED pour mon groupe A sur mon module M, que je le valide et que je reviens sur la fenêtre d'édition, ça me positionne automatiquement le CRUVED selon le niveau le plus fort des autres modules 
![GN3](https://user-images.githubusercontent.com/66769358/100723433-0b3ab180-33c2-11eb-8bae-dfa274e8dca5.jpg)
![GN4](https://user-images.githubusercontent.com/66769358/100723450-0e35a200-33c2-11eb-811a-5c13f25cb945.jpg)
![GN1](https://user-images.githubusercontent.com/66769358/100722670-22c56a80-33c1-11eb-8a9d-2fbb97dd359b.jpg)
![GN2](https://user-images.githubusercontent.com/66769358/100722695-2a850f00-33c1-11eb-86c1-3251722a2328.jpg)

- Ensuite, je n'arrive plus à masquer les sous-modules de Monitoring pour tel ou tel groupe alors que les permissions indiquent 0. Je ne sais pas si ça a un lien avec le MAJ 0.2.0 de Monitoring
![GN5](https://user-images.githubusercontent.com/66769358/100724048-c06d6980-33c2-11eb-88a0-2e73ae1e5573.jpg)
![GN6](https://user-images.githubusercontent.com/66769358/100724053-c1060000-33c2-11eb-91a3-57cee50095be.jpg)

- Enfin, peut-être que tout est lié mais je n'arrive pas non plus à restreindre les occurrences de Synthèse et Validation selon l'organisme de l'utilisateur

**Comment by maximetoma** [comment]
> Quand je définis mon CRUVED pour mon groupe A sur mon module M, que je le valide et que je reviens sur la fenêtre d'édition, ça me positionne automatiquement le CRUVED selon le niveau le plus fort des autres modules

**_Précision à apporter:_** En fait, la permission se définie bien comme je l'ai mis (dans la base comme sur l'interface principale du CRUVED) quand je valide le CRUVED d'un module mais quand j'edit, les curseurs bougent de la position que j'avais définie juste avant.

> Ensuite, je n'arrive plus à masquer les sous-modules de Monitoring pour tel ou tel groupe alors que les permissions indiquent 0. Je ne sais pas si ça a un lien avec le MAJ 0.2.0 de Monitoring

Problème déporté sur le github de Monitoring, voir https://github.com/PnX-SI/gn_module_monitoring/issues/66

> Enfin, peut-être que tout est lié mais je n'arrive pas non plus à restreindre les occurrences de Synthèse et Validation selon l'organisme de l'utilisateur

Problème résolu, l'utilisateur que je testais n'avait pas le bon organisme d'attribué

**Comment by camillemonchicourt** [comment]
OK il ne s'ait pas du curseur (souris) mais en effet quand on modifie une permission, les valeurs ne sont pas correctement reprises.

**Comment by maximetoma** [comment]
Oui désolé je ne savais comme le formuler sur le moment :)
