### ISSUE TITLE
[OCCTAX] - Erreur chargement de l'utilisateur lors de l'édition d'un relevé

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1177]
Lorsqu'on édite un relevé sur occtax, le formulaire est en principe pré-rempli avec les infos du relevé qu'on édite. 

Lorsque le chargement de la page prend un peu de temps (cache nettoyé ou relevé à plusieurs dizaines de taxons), c'est l'observateur courant qui est récupéré (comme pour la saisie ?) et non pas l'observateur saisi lors de l'enregistrement précédent du relevé. 

Si je supprime mon propre nom d'observateur qui s'est pré-chargé, je retrouve bien l'observateur originel du relevé

Lorsque la page est rapide à charger (cache + relevé avec peu d'occurrences) la récupération se fait bien. L'exemple ci-dessous. 

![recuperation_observateur](https://user-images.githubusercontent.com/23358384/100904458-55f22180-34c7-11eb-8a1f-17a95bd75636.gif)

**Comment by camillemonchicourt** [comment]
Oui on a identifié le même soucis ce matin

**Comment by camillemonchicourt** [comment]
Le problème est de nouveau identifié dans la 2.6.
Corrigé dans la branche ``develop`` : https://github.com/PnX-SI/GeoNature/commit/738d7f5410604e0ed9359d462cc598e910763b7f
