### ISSUE TITLE
Gestion des données d'absence dans Geonature

### ISSUE THREAD

**Issue by jprgeofit** [PnX-SI/GeoNature#1187]
Dans le cadre du développement du module monitoring pour les protocoles POPReptile et POPAmphibien pour la SHF, nous souhaiterions savoir comment est géré l'absence de données. La mention "pas de données disponibles" est elle paramétrable par niveau ? La non observation d'animaux étant un type d'observation. Comment cela peut se gérer dans les exports ? 

@Marie, peut être as-tu d'autres éléments de précision à apporter sur ce ticket.

**Comment by TheoLechemia** [comment]
Bonjour,

la nomenclature "statut d'observation" permet de renseigné l'information de "présence" ou "absence". (http://standards-sinp.mnhn.fr/nomenclature/18-statut-dobservation-statutobservation-16-08-2016/).
Libre à chacun ensuite de paramétrer ses exports (dans la synthese et dans le module d'export en fonction des besoins)

**Comment by Splendens** [comment]
Bonjour !
Comme le dit Théo, les données d'absence sont bien gérées dans les nomenclatures, comme prévue dans le standard SNIP. La question était plutôt à poser côté Monitoring : dans le module monitoring, comment sont gérées/affichées les données d'absence ?  On peut par exemple faire une visite sur un site et ne contacter aucun taxon cible. Or dans ce cas, il est affiché quelque chose du style "aucune donnée disponible" alors qu'il y a bien une donnée de non observation.

**Comment by jprgeofit** [comment]
Ok, je pose repose la question côté monitoring
