### ISSUE TITLE
Saisie occtax - personnes extérieures à la structure

### ISSUE THREAD

**Issue by MNourrisson** [PnX-SI/GeoNature#1188]
Bonjour,
je suis en train de faire des tests afin que des personnes extérieures à la structure de puisse saisir des observations dans occtax. Mais je suis confrontée à un problème concernant la liste des jeux de données dans le formulaire de saisie.

Pour cela j'ai créé : 
- un compte "Agent test" appartenant à une structure extérieure et appartenant également à un groupe "Grp_ext" ;
- dans l'admin de géonature, j'ai paramétré le CRUVED associé au "Grp_ext" pour qu'il puisse accéder qu'a certaines fonctionnalités de géonature ;
- dans les métadonnées, j'ai créé un nouveau CA et un JDD avec comme organisme associé la structure de mon agent test (j'ai essayé également d'associer directement la personne sur le JDD).
![image](https://user-images.githubusercontent.com/34370970/101766508-2b195600-3ae3-11eb-9ba0-2ba9ac8f3112.png)

Dans le champs jeux de données du formulaire de saisie, je retrouve mon JDD ainsi que d'autres qui ne sont pas censé se trouver dans la liste car ils sont associés à ma structure et aux agents en interne.

![image](https://user-images.githubusercontent.com/34370970/101767369-6700eb00-3ae4-11eb-8820-82819680e104.png)

Est-ce que je loupe quelque chose dans mon paramétrage ? 
Merci par avance,
Mélanie

Version de Géonature : 2.5.5

**Comment by TheoLechemia** [comment]
La liste des jeux de données est basé sur le "R" de GeoNature. Quel est le CRUVED du groupe "grp ext" ? 
Sinon il existe une fonctionnalité de "création de compte" pour ce genre de cas d'usage.

**Comment by MNourrisson** [comment]
Voici le détail du CRUVED de grp_ext 
![image](https://user-images.githubusercontent.com/34370970/101775442-c3b5d300-3aef-11eb-9d80-ad10c0bb2c3c.png)
![image](https://user-images.githubusercontent.com/34370970/101775474-d0d2c200-3aef-11eb-8662-0f831959f649.png)

Je ne connais pas cette fonctionnalité "création de compte", je vais regarder. Merci

**Comment by TheoLechemia** [comment]
Avec un R = 3, les utilisateurs verront tous les JDD

**Comment by MNourrisson** [comment]
Exact, merci. Je pensais que c'était sur occtax qu'il fallait le modifier le "R".
