### ISSUE TITLE
Recompilation du FrontEnd de geonature 2.4.1

### ISSUE THREAD

**Issue by laurentm29** [PnX-SI/GeoNature#1190]
Bonjour,
La recompilation du frontend de géonature échoue avec les erreurs suivantes:
Une idée ?
Merci
```
:~/geonature/frontend$ npm run build

> geonature@0.0.0 build /home/geonatureadmin/geonature/frontend
> . ~/.nvm/nvm.sh; nvm use; ng build --prod --aot=false --build-optimizer=false

nvm is not compatible with the npm config "prefix" option: currently set to "/usr"
Run `npm config delete prefix` or `nvm use --delete-prefix v10.15.3 --silent` to unset it.
Found '/home/geonatureadmin/geonature/frontend/.nvmrc' with version <v10.15.3>
nvm is not compatible with the npm config "prefix" option: currently set to "/usr"
Run `npm config delete prefix` or `nvm use --delete-prefix v10.15.3` to unset it.
You are running version v6.17.1 of Node.js, which is not supported by Angular CLI v6.
The official Node.js version that is supported is 8.9 and greater.

Please visit https://nodejs.org/en/ to find instructions on how to update Node.js.

npm ERR! Linux 4.9.0-11-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! geonature@0.0.0 build: `. ~/.nvm/nvm.sh; nvm use; ng build --prod --aot=false --build-optimizer=false`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the geonature@0.0.0 build script '. ~/.nvm/nvm.sh; nvm use; ng build --prod --aot=false --build-optimizer=false'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the geonature package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     . ~/.nvm/nvm.sh; nvm use; ng build --prod --aot=false --build-optimizer=false
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs geonature
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls geonature
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/geonatureadmin/geonature/frontend/npm-debug.log
```

**Comment by camillemonchicourt** [comment]
Bonjour,
Les erreurs indiquent que vous utilisez une ancienne version de npm non supportée.

Et les messages indiquent aussi les logs à joindre pour plus de précisions.

Quel est votre contexte d'installation ?

**Comment by laurentm29** [comment]
L'installation a été réalisée sans problème fin aout 2020.
Aujourd'hui, j'ai modifié le fichier 'config/geonature_config.toml' pour définir le centre de la carte et j'ai lancé :
```
cd geonature/backend/
source venv/bin/activate
geonature update_configuration
```

Apparemment, l'update provoque ensuite une recompilation du frontend (équivalent à npm run build) et ça coince. Je pense qu'il faut définir explicitement une version de nvm (ou npm) quelque part.

**Comment by camillemonchicourt** [comment]
OK alors peut-être voir https://github.com/PnX-SI/GeoNature/issues/1122
Car on n'a pas du tout eu le soucis donc c'est étonnant.
Vous aviez utilisé le script d'installation globale (``install_all.sh``) ?
Et à la fin de l'installation, vous aviez bien exécuté la commande ``exec bash``

**Comment by DonovanMaillard** [comment]
Sans doute des pistes du côté de #837 et #832 qui ont été résolus avec une erreur semblable... les numero de version ont peut être changé depuis

**Comment by laurentm29** [comment]
Je suis allé vérifier la version de nvm dans le répertoire `$NVM_DIR/versions/node/`, j'ai bien v10.15.3.
A tout hasard, je reviens dans le répertoire `/geonature/frontend/` et je relance la compilation en tapant `npm run build` et la compile fonctionne parfaitement avec comme première ligne de log  :
```
Found '/home/geonatureadmin/geonature/frontend/.nvmrc' with version <v10.15.3>
Now using node v10.15.3 (npm v6.4.1)
```
Je n'explique pas le dysfonctionnement que j'ai rencontré, ça fonctionne désormais. Merci beaucoup pour votre aide

**Comment by camillemonchicourt** [comment]
OK super, à surveiller donc.
