### ISSUE TITLE
documentation sur l'affectation ou création de jeux de données

### ISSUE THREAD

**Issue by olivier8064** [PnX-SI/GeoNature#1209]
Bonjour, 

J'utilise la version 2.5.5 de geonature. 
J'ai créé un utilisateur X en lui affectant le groupe "grp_en_poste". 
Lorsque je me logue avec cet utilisateur X j'ai un message d'erreur m'indiquant qu'il n'y a pas de jeux de données créé. Effectivement dans le module "metadata" il n'y a rien. 
J'ai consulté tous les items de la doc sur le sujet : 
http://docs.geonature.fr/search.html?q=jeux&check_keywords=yes&area=default
j'ai pu voir que la clé se trouvait dans le schéma gn_meta. Je visualise bien les tables dans pgadmin et je voudrais simplement affecter le dataset_name "Contact aléatoire tous règnes confondus" au groupe "grp_en_poste" pour qu'il apparaisse dans le jeux de données de mon utilisateur X. 
Mais voilà, je suis bloqué à cette étape ;) 
Y a t il une doc qui expliquerait comment gérer ces jeux de données  ? Y a t il un autre moyen de gérer ces jeux de données (création / affectation)  par un module de géonature ? 
Idem d'ailleurs pour l'explication de la gestion des droits de "grp_en_poste" ou d'un autre groupe qu'on pourrait créer. 

Merci pour votre aide. 

Olivier

**Comment by camillemonchicourt** [comment]
Oui les JDD et CA sont administrables dans le module Métadonnées.

Et pour les droits voir la partie Gestion des droits dans la documentation d'administration de la BDD.

**Comment by camillemonchicourt** [comment]
Et concernant les JDD dans lesquels un utilisateur peut saisir quand il est dans le groupe En poste, de mémoire, il faut que lui-même ou son organisme soit acteur du JDD.

**Comment by olivier8064** [comment]
Merci Camille, 
Oui j'ai pu configurer les CA et JDD dans le module métadonnées en étant admin. D'ailleurs il serait utile je pense dans la doc de rappeler le lien direct avec une copie d'écran car tel que c'est rédigé, on peut penser qu'il faut aller dans la base de donnée directement. Mais il me reste une incompréhension sur la gestion des droits  : ou et comment accéder aux paramètres du CRUVED et de la portée. Mais je vais faire un autre ticket pour ne pas tout mélanger :)

**Comment by camillemonchicourt** [comment]
Tel que rédigé où ?

**Comment by olivier8064** [comment]
Dans le manuel administrateur, ici : 
https://docs.geonature.fr/admin-manual.html?highlight=jeux#metadonnees

**Comment by camillemonchicourt** [comment]
OK done : https://github.com/PnX-SI/GeoNature/commit/d956baf2875bb110c24afd36477586c6e5bb88af
