### ISSUE TITLE
suggestion pour documentation gestion des droits CRUVED et portée

### ISSUE THREAD

**Issue by olivier8064** [PnX-SI/GeoNature#1211]
Bonjour, 

Dans la documentation administrateur, il est indiqué que 
"La gestion des droits (permissions) des rôles, spécifique à GeoNature, est ensuite gérée dans un schéma (gn_permissions) et un module de GeoNature dédié". 
Il serait utile d'indiquer à cet endroit que ce module est accessible depuis le menu "admin " puis "Administration des permissions (CRUVED) et que la gestion de la portée s'effectue par ce même menu en éditant les permissions. 
Une copie d'écran serait aussi la bienvenue. 
Merci 
Olivier

**Comment by camillemonchicourt** [comment]
OK j'ai précisé un peu : https://github.com/PnX-SI/GeoNature/blob/develop/docs/admin-manual.rst

Mais cette documentation concerne la partie BDD, donc on ne doit pas spécialement y documenter le fonctionnement des modules, dont il faudrait plutôt enrichir la documentation, dans la documentation utilisateurs dédiée.

A noter aus @jpm-cbna est en train de revoir complètement le module d'administration des permissions pour le rendre plus ergonomique et plus complet : https://github.com/PnX-SI/GeoNature/issues/770

A noter aussi que tout le monde peut contribuer à la documentation.
Il suffit de se rendre directement sur le fichier concerné, idéalement dans la branche ``Develop``, et de le modifier avec le crayon en haut à droite : https://github.com/PnX-SI/GeoNature/blob/develop/docs/admin-manual.rst

Comme vous n'avez pas les droits pour contribuer directement dans le dépôt GeoNature, cela va créer automatiquement une copie du projet (fork) dans votre compte Github, faites les modifications proposées et ensuite cela vous proposera de proposer cette contribution (Pull request) directement sur le dépôt principal de GeoNature. Que nous pourrons alors valider ou non.
