### ISSUE TITLE
[METADONNEES] Pas de contrainte d'unicité sur les CA et JDD?

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature#1215]
Il n'existe pas de contrainte d'unicité sur les UUID des JDD et CA, est-ce volontaire? 

Cela peut poser des problème en cas d'import de données de sources tierces en BDD (risque de doublons de meta).

**Comment by camillemonchicourt** [comment]
En effet, comme ça a été fait sur les occurrences de taxons, il faudrait en ajouter aussi sur les JDD et CA.
Bien vu.

**Comment by lpofredc** [comment]
Ok, merci. Je m'en charge. Je propose d'ajouter la contrainte par ajout d'un index unique sur ces champs.
