### ISSUE TITLE
[OCCTAX] - Outil de paramétrage : manque méthode/technique d'observation

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1216]
Dans le mécanisme de la "roue crantée" , sans doute depuis le changement du champs méthode d'observation avec la mise à jour du standard (?),le champs des méthodes d'observation n'est pas paramétrable comme les autres champs.

**Comment by jbrieuclp** [comment]
En lien avec cette PR https://github.com/PnX-SI/GeoNature/pull/1155
