### ISSUE TITLE
[Question] Installation des modules externes

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature#1230]
Bonjour,

Suite à l'installation de la MAJ 0.2.1 de Monitoring, je me suis rendu compte que je dois à chaque fois adapter les chemins d'accès aux différents dossiers.

En fait, actuellement, tous mes modules externes (Monitoring, Export, Dashboard...) sont pour ma part installés dans le dossier `contrib` de `geonature`.
Or je remarque dans les chemins de mise à jour auxquels vous faites référence se situent à l'extérieur du dossier `geonature` donc au même endroit où sont stockés `taxhub` et `userhub`.

Par convention, vaut-il mieux que les modules externes soient installés et MAJ à l'extérieur de `geonature` dans le dossier `geonatureadmin` ou ma configuration actuelle n'est pas gênante ? Si c'est gênant, avez-vous une piste pour que je bouge les dossiers à l'extérieur de `geonature` sans tout casser ? :)

Merci d'avance pour votre retour,
Maxime

**Comment by TheoLechemia** [comment]
Oui il est recommandé de stocker les modules externes à l'exterieur de GeoNature. Sinon le lien symbolique créés dans external_modules vers le module externe ne fonctionne plus lors d'une migration. Le dossier "contrib" ne concerne que les modules du coeur de GN dont nous gérons le MAJ.
Pour bouger les modules de place... à l'aveugle comme ça, pas évident. Je dirais qu'en modifiant les liens symboliques créé dans "external_modules" pour les faire pointer vers le dossier déplacé, devrait suffire. 
N'hésite pas à faire à retour ici si tu as des difficultés

**Comment by DonovanMaillard** [comment]
Bonjour, 

Lors des mises à jour de GeoNature, on renomme le dossier geonature_old, et on télécharge la version à jour, qu'on nomme geonature (il vient donc remplacer l'ancien). Dans ce nouveau dossier, vous n'aurez pas les modules. Le script migrate.sh récupère certaines choses (liens symboliques, fichiers de conf, custom etc), à voir si contrib est récupéré aussi...

**Comment by maximetoma** [comment]
Merci beaucoup @TheoLechemia et @DonovanMaillard 
D'accord, je comprends mieux et je ne sais pas pourquoi j'avais installé les modules externes ici. Ca explique beaucoup de choses notamment liés à ce ticket: https://github.com/PnX-SI/GeoNature/issues/1145

Du coup, concernant le déplacement des dossiers en dehors de contrib, effectivement pour que ça marche j'ai modifié les liens symboliques dans les dossiers suivants :

- `/home/geonatureadmin/geonature/external_modules`
- `/home/geonatureadmin/geonature/frontend/src/external_assets`
- Pour Monitoring : `/home/geonatureadmin/gn_module_monitoring/config/monitoring`
- Pour Monitoring : `/home/geonatureadmin/gn_module_monitoring/frontend/assets`
- Puis re-build du frontend et c'est bon

Merci encore pour vos lumières :)

**Comment by camillemonchicourt** [comment]
Faut-il clarifer ou préciser la documentation quelque part en lien avec l'endroit où installer des modules externes ?

**Comment by lpofredc** [comment]
Des précisions sur la méthode génériques (car pas forcément identique pour tous les modules) sur la mise à jour des modules et une uniformisation de la localisation de l'information par modules serait aussi pas mal (dans le README pour EXPORT, IMPORT, dans un fichier de doc pour MONITORING :).
