### ISSUE TITLE
[METADONNEES] Affichage trop lent des CA et JDD avec gros jeux de données

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature#1231]
Dans la dernière version du module présent dans GeoNature v2.6.0.rc1, dans le cas de jeux de données peu nombreux (2) mais contenant beaucoup de données (plusieurs millions), les informations sur la page du module Métadonnées mettent trop de temps à s'afficher (~17 secondes).

L'utilisateur a l'impression que le module ne fonctionne pas car rien n'indique ce chargement.
A minima, il serait souhaitable d'afficher un spinner qui indique le chargement en cours des informations.

Idéalement, les informations ralentissant le chargement devrait être mise en cache ou chargé de manière asynchrone à part... La page devrait s'afficher en 1 ou 2 secondes max...

**Comment by camillemonchicourt** [comment]
Ok donc ça semble bien lié à la refonte de la liste des JDD, réalisée dans la 2.6 à venir, incluant le nombre de données par JDD qui doit être long à calculer pour les gros JDD.

En effet un spinner serait déjà une bonne chose.

**Comment by camillemonchicourt** [comment]
Idem sur la fiche détail des gros JDD.

**Comment by TheoLechemia** [comment]
J'ai ajouté des spinners sur la liste et la fiche détail JDD pour l'instant.
Pour la liste, une solution serait de charger uniquement le nombre de données par JDD quand un déplie un cadre d'acquisition.

**Comment by camillemonchicourt** [comment]
Ajout du spinner + chargement du nombre de données en parallèle pour ne pas retarder l'affichage de la liste, dans la 2.6.0
