### ISSUE TITLE
Comment effacer un jeu de donnée et éventuellement un cadre d'acquisition dans les métadonnées ? 

### ISSUE THREAD

**Issue by Heg0Damask** [PnX-SI/GeoNature#1235]
Bonjour, 
je souhaiterais savoir si on peut effacer un jeu de donnée d'un cadre d'acquisition sachant qu'aucun relevé ne pointe sur le jeu de données.
Est il possible d'effacer également un cadre d'acquisition qui ne possède pas de jeu de données ? 
Cette dernière question est moins importante car on peut renommer un cadre d'acquisition et le réutiliser ultérieurement.

Je demande ça car j'ai besoin de faire du ménage dans mes jeux de données.
merci pour votre aide

**Comment by camillemonchicourt** [comment]
Dans la version 2.5, il n'est pas possible de supprimer un JDD ou CA depuis l'interface du module Métadonnées, car potentiellement dangereux si des données y sont liées.
Donc faisable mais seulement directement dans la BDD.

Dans la 2.6 à venir, la liste des JDD du module Métadonnées a été totalement refondue (https://github.com/PnX-SI/GeoNature/issues/889) et il sera désormais possible de supprimer des JDD directement depuis le module Métadonnées, si ils n'ont pas de données liées.
