### ISSUE TITLE
Mise à jour 2.3.0 à 2.3.1 ou 2.4.0

### ISSUE THREAD

**Issue by CGuillaume** [PnX-SI/GeoNature#1242]
Bonjour,

Je tente depuis quelques jours de monter en version mon Geonature installé puis laissé en repos en version 2.3.0 sans succès.
Pour une première épreuve de maj, j’ai tenté, dans un premier temps, de le passer en version 2.3.1 pour commencer doucement. Voyant que ça ne fonctionnait pas je suis revenu en arrière avec un snapshot et j’ai fait les maj de taxhub et usershub (1.7.0 et 2.1.2) pour tenter le grand saut vers la 2.4.0. Les maj usershub et taxhub fonctionnent parfaitement mais pour geonature l’installation reste bloqué à l’étape de lancement du fichier migration.sh où la console s’arrête sur ça :

```
OK, let's migrate GeoNature version...
Found '/home/geonature/geonature/frontend/.nvmrc' with version <v10.15.3>
v10.15.3 is already installed.
Now using node v10.15.3 (npm v6.4.1)
Found '/home/geonature/geonature/frontend/.nvmrc' with version <v10.15.3>
Now using node v10.15.3 (npm v6.4.1)

> core-js@2.6.11 postinstall /home/geonature/geonature/frontend/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
```

Je pense bien faire toutes les étapes des notes de versions avant de lancer la migration.
Ni connaissant pas grand-chose et étant ma première maj je ne vois pas ce qui bloque je suis preneur de conseils.

Je met en pj les fichiers de log qui m'indique lorsque je quitte l'installation :
[2021-01-27T16_35_05_945Z-debug.log](https://github.com/PnX-SI/GeoNature/files/5881668/2021-01-27T16_35_05_945Z-debug.log)
[2021-01-27T16_36_36_507Z-debug.log](https://github.com/PnX-SI/GeoNature/files/5881667/2021-01-27T16_36_36_507Z-debug.log)

Merci d’avance :)
Guillaume

**Comment by camillemonchicourt** [comment]
OK un truc avec Node, ça me parle dans d'autres tickets. A creuser.

Mais sauf mention contraire dans les notes de version il n'est pas conseillé d'installer les versions intermédiaires mais plutôt directement la dernière version.

**Comment by DonovanMaillard** [comment]
à condition de passer tous les scripts de mise à jour de la base de données intermédiaire, pour GeoNature mais aussi TaxHub et UsersHub ;)

En effet ce soucis nvm a été vu par plusieurs d'entre nous et est discuté dans d'autres tickets fermés

**Comment by TheoLechemia** [comment]
On a le même soucis sur notre serveur de production (et uniquement là...). 
Solutionné en mettant `v10.15.3` dans le fichier `frontend/.nvmrc`

**Comment by camillemonchicourt** [comment]
En effet, voir https://github.com/PnX-SI/GeoNature/issues/1159

**Comment by CGuillaume** [comment]
Bonjour vous 3,

Effectivement c'est bien la version du .nvmrc et le passage en v10.16.3 solutionne tout.
J'avais pourtant regardé dans les tickets mais je ne suis pas encore trés à l'aise avec ces histoires de nvm.

Merci pour votre réactivtié, toujours au top.
Me voilà maintenant à jour, il y a plus qu'à intégrer des données et mettre les mains dedans pour maitriser un peu plus cet outil :)

@Bientôt
Guillaume
