### ISSUE TITLE
bug admin CRUVED occtax

### ISSUE THREAD

**Issue by jbdesbas** [PnX-SI/GeoNature#1248]
Bonjour,

J'ai constaté un bug au niveau de l'interface administrateur sur la gestion des droits : 
Je souhaite appliquer un CRUVED pour occtax à une liste d'utilisateur avec : 3C , 1R, 1U, 1V, 1D
Pas de problème pour cette partie, les droits s'applique correctement.
Sauf que lorsque je retourne sur le chois du cruved pour occtax (bouton "Edit"), le bouton radio pour R sélectionne par défaut le niveau 3 (ce qui autorise donc les utilisateurs à consulter l'ensemble des données sur occtax).
Pas vraiment bloquant donc comme bug, mais il faut être vigilant avant de valider.

**Comment by camillemonchicourt** [comment]
Je pense que c'est la même chose que https://github.com/PnX-SI/GeoNature/issues/1170, corrigé dans la 2.6.0 à venir.

**Comment by jbdesbas** [comment]
En effet !
