### ISSUE TITLE
mise à jour de GeoNature en root ou geonatureadmin ? 

### ISSUE THREAD

**Issue by olivier8064** [PnX-SI/GeoNature#1251]
Bonjour, 

Dans la doc, 
http://docs.geonature.fr/installation-standalone.html#mise-a-jour-de-l-application
Il n' est pas précisé s'il faut se logger en root ou avec l'utilisateur geonatureadmin pour faire les étapes de mise à jour
Merci pour votre aide. 
Olivier

**Comment by camillemonchicourt** [comment]
Il ne faut jamais se loguer en ROOT quand on travaille sur un serveur, mais avec l'utilisateur courant.
Et éventuellement faire certaines taches en ``sudo`` pour avoir les droits de super-utilisateur.

La documentation de GeoNature indique au début : 

> Pour la suite de la documentation et pour l’administration courante de GeoNature, on n’utilisera plus jamais l’utilisateur root (utiliser geonatureadmin dans l’exemple de la documentation; su geonatureadmin pour change d’utilisateur). Si besoin d’exécuter des commandes avec des droits d’administrateur, on les précède de sudo.

**Comment by olivier8064** [comment]
Merci Camille, réponse rapide et précise, comme toujours 😁
