### ISSUE TITLE
[MAJ 2.6.0/2.6.2] Erreur lors de l'installation (Cannot find module 'protractor')

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature#1252]
Je ne sais pas si ça un lien avec ce ticket: https://github.com/PnX-SI/gn_module_monitoring/issues/69

J'ai voulu installer la dernière version Saxifraga (d'ailleurs bravo encore !) sauf que je me suis hurté au premier problème suivant:

- Sur mon fichier CSS personnalisé, je faisais référence à des .png qui n'ont pas été copiés (ma faute) du coup lors de l'exécution du script `migration.sh`, le build du frontend a planté
- Après avoir copié ces fichiers, j'ai lancé manuellement donc la commande `geonature frontend_build` mais là j'ai toujours un problème de build du frontend. Le plus bizarre est que j'ai déjà eu l'erreur sur le ticket cité ci-dessus mais en faisant la manip de Joel cette fois-ci, ça ne fonctionne pas.

![image](https://user-images.githubusercontent.com/66769358/107012223-08c94f00-6799-11eb-8e89-90982bbb0cb3.png)

Ci-joint le log: [2021-02-05T08_46_05_208Z-debug.log](https://github.com/PnX-SI/GeoNature/files/5931257/2021-02-05T08_46_05_208Z-debug.log)

Avez-vous une idée du problème ? :)
Merci d'avance

**[EDIT:]** Je n'ai pas exécuté la commande de Joel au bon endroit.... Ca marche du coup. Par contre, c'est bizarre que ça fasse ça... Je suis toujours preneur si vous avez une explication !

**Comment by camillemonchicourt** [comment]
OK donc ton soucis est réglé ou tu es bloqué ?
Je ne sais pas trop de quoi il s'agit à propos de la "commande de Joël" ?
@joelclems une idée ?

**Comment by maximetoma** [comment]
Oui c'est réglé :)

Pour la commande de Joel, c'est celle qu'il a mentionné sur l'autre ticket:
https://github.com/PnX-SI/gn_module_monitoring/issues/69#issuecomment-762167372

A savoir celle-ci:
`npm install ngx-mat-select-search`

**Comment by camillemonchicourt** [comment]
OK bonne nouvelle, donc il n'y a pas de soucis avec la 2.6.0, bonne nouvelle. Elle ajoute beaucoup de choses et apporte pas mal de corrections aussi.
Pour la commande en question, je n'ai pas suivi, mais à voir si c'est à régler au niveau de Monitoring, ou de GeoNature ?

Pour les PNG, j'ai pas compris où ils étaient et pourquoi ça a fait planter le build ? Si il faut qu'on ajuste quelque chose au niveau de la migration pour gérer ton cas ?

**Comment by maximetoma** [comment]
Oui, il n'y a pas de soucis autrement !

Pour les PNG, en fait ça concerne la customisation du bandeau:
http://docs.geonature.fr/admin-manual.html#customiser-l-aspect-esthetique
Il est mentionné de mettre le bandeau dans le répertoire `geonature/frontend/src`.

Mais j'ai remarqué, après coup, que les fichiers n'ont pas été (prévus d'être) copiés.

**Comment by joelclems** [comment]
Je viens de refaire une install neuve en 2.6 + une  installation de monitoring en 0.2.1 et je n'ai pas eu de soucis

`ngx-mat-select-search` est dans le fichier package.json de GeoNature il devrait etre installé à l'installation.

dans le cas de t  migration est ce que tu avait fait `npm install` (ou `npm ci --only=prod` comme dans `install/migration/migration.sh`)

**Comment by maximetoma** [comment]
@joelclems non, j'ai juste exécuté la commande `./install/migration/migration.sh` où j'ai eu le premier plantage à cause des PNG, puis j'ai directement fait ensuite les commandes:
`cd /home/geonatureadmin/geonature/backend`
`source venv/bin/activate`
`geonature frontend_build`

**Comment by joelclems** [comment]
tu sais à quelle ligne il a planté?
j'imagine avant le npm ci ?

et une autre question  :est ce ça se passe bien au niveau des liens symbobliques du module monitoring (normalement on a un lien symbolique dans external module et ça bouge pas trop)  (il y avait une issue sur ça mais j'arrive plus à mettre la main dessus

**Comment by maximetoma** [comment]
Je ne sais pas trop... 😅 Voilà l'endroit où il a planté la première fois et la deuxième fois:

![image](https://user-images.githubusercontent.com/66769358/107020914-c1948b80-67a3-11eb-8583-daa04dad2ac0.png)
![image](https://user-images.githubusercontent.com/66769358/107020878-afb2e880-67a3-11eb-9a3d-173fe22b216f.png)

Oui sur le lien symbolique de monitoring, il n'y a pas de soucis chez moi ! Juste j'ai un temps de chargement un peu plus long comparé à la 2.5

**Comment by joelclems** [comment]
je pense que c'est à geonature frontend_build c'est dire quasiment à la fin du script
npm ci --only=prod de la ligne 111 est bien lancé
dans tes logs du dernier post il faudrait voir ce qu'il y a un peu plus haut si on a une erreur (ça correspond au `pip install -r requirements.txt` de la ligne 131 et

**Comment by joelclems** [comment]
En relançant un install_app.sh je tombe sur cette erreur que je n'avais pas le premier coup
ERROR in e2e/app.po.ts(1,38): error TS2307: Cannot find module 'protractor'.

**Comment by joelclems** [comment]
c'est bien resolu avec npm install ngx-mat-select-search, la question c'est pourquoi ce n'est pas fait avec npm install ??

**Comment by maximetoma** [comment]
Voici mes logs pour info:

[2021-02-05_deb_install_geonature_2_6_0.txt](https://github.com/PnX-SI/GeoNature/files/5932432/2021-02-05_deb_install_geonature_2_6_0.txt)

**Comment by TheoLechemia** [comment]
ngx-mat-select-search est bien dans la package-lock.json donc je ne comprend pas pourquoi il n'a pas été installé ?
https://github.com/PnX-SI/GeoNature/blob/master/frontend/package-lock.json#L6678
Egalement dans le package.json.
Je n'ai pas eu le problème lors de mes test d'install et de migration...

**Comment by maximetoma** [comment]
Je ne sais pas trop non plus....
Je viens de passer de la version 2.6.0 à la version 2.6.2 et j'ai de nouveau la même erreur....

Je passe le serveur en maintenance avant d'effectuer la MAJ, est-ce qu'il y aurait une certaine influence ?

Pour info, les logs de ma nouvelle MAJ: [2021-02-16T08_39_54_997Z-debug.log](https://github.com/PnX-SI/GeoNature/files/5987225/2021-02-16T08_39_54_997Z-debug.log)

**Comment by joelclems** [comment]
`protractor` est dans les `devDependencies` dans le fichier `package.json`, est ce qu'il ne faudrait pas le mettre dans `dependencies` ?

de plus dans le fichier `package-lock.json` ,la dépendande de `ngx-mat-select-search` n 'est pas explicite https://github.com/PnX-SI/GeoNature/blob/60c6f847a25d8024094217d119c1bef80f678554/frontend/package-lock.json#L6678-L6685
(je ne maitrise pas du tout le sujet mais je crois que le fichier `package-lock.json` date de 5 mois est c'est qu'il ne faut pas le refaire/mettre à jour ??)

**Comment by DonovanMaillard** [comment]
Bonjour, 

Pour info, sur une instance en 2.6.2 avec le monitoring, même soucis avec protractor lors de la montée de version vers GN 2.7.0. La commande de Joel a réglé le soucis : npm install ngx-mat-select-search

Le soucis est apparu au même moment que pour @maximetoma , à la fin du migrate.sh .

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.7.1.
En effet lors de la mise à jour de GeoNature (migration.sh) on réinstallait les dépendances JS de GeoNature, mais pas celles éventuelles des modules. C'est désormais ajouté dans le script migration.sh
