### ISSUE TITLE
2.6 erreur à la création d'une occurence/dénombrement

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#1255]
J'ai fait une installation nouvelle de GN 2.6
J'ai bien des données d'exemples dans occtax mais pas dans la synthèse

Dans occtax, lorsque j'enregistre un taxon je tombe sur cette erreur

```
(psycopg2.errors.ObjectNotInPrerequisiteState) ERREUR:  l'enregistrement « new » n'est pas encore affectée
DETAIL:  La structure de ligne d'un enregistrement pas encore affecté est indéterminée.
...
...
fonction PL/pgsql pr_occtax.insert_in_synthese(integer), ligne 40 à instruction SQL
instruction SQL « SELECT pr_occtax.insert_in_synthese(NEW.id_counting_occtax::integer) »
fonction PL/pgsql pr_occtax.fct_tri_synthese_insert_counting(), ligne 18 à PERFORM
```

Ma version de postgres est 10.15

**Comment by camillemonchicourt** [comment]
OK merci pour ce retour. Il faut donc creuser si il y a un soucis dans les triggers.

**Comment by joelclems** [comment]
l'erreur viendrai d'ici gn_synthese.fct_tri_cal_sensi_diff_level_on_each_statement();

**Comment by DonovanMaillard** [comment]
Pour simple info, pas rencontré de mon coté sur une instance mise à jour vers la 2.6.

**Comment by joelclems** [comment]
Normalement le commit corrige le bug. A tester

**Comment by joelclems** [comment]
L'ajout et la modification marchent bien dans occtax.

**Comment by camillemonchicourt** [comment]
OK il faut vérifier que le trigger dans le SQL d'installation et celui dans l'update 2.5.5to2.6.0.sql soient bien identiques ?

**Comment by TheoLechemia** [comment]
Le problème se pose que sur PG10 on dirait.
Merci pour la résolution

**Comment by joelclems** [comment]
il y a une legere différence la ligne qui posait probleme (avec le WHERE)n'est plus dans la migration
je n'ai aucune idée des implications mais il faudrait harmoniser

migration 2.5.5to2.6
```
          FROM NEW AS updated_rows
          LEFT JOIN ref_nomenclatures.t_nomenclatures t_diff ON t_diff.id_nomenclature = updated_rows.id_nomenclature_diffusion_level
        )

```
synthese.sql
```
      FROM NEW AS updated_rows
      LEFT JOIN ref_nomenclatures.t_nomenclatures t_diff ON t_diff.id_nomenclature = updated_rows.id_nomenclature_diffusion_level
      WHERE updated_rows.id_nomenclature_sensitivity IS NULL
    )

```

**Comment by camillemonchicourt** [comment]
A revoir donc dans un update 2.6.0t2.6.1.sql pour être certain ?

**Comment by joelclems** [comment]
il faut voir ce qu'il faut faire de cette ligne s'il faut la garder ou non?
j'imagine que le but est de determiner la sensibilité là elle ne l'est pas (ie egale à `NULL`), dans ce cas il faudrait la garder et la mettre dans le script de migration

**Comment by TheoLechemia** [comment]
J'ai fait un 2.6.0to2.6.1.sql avec cette correction
