### ISSUE TITLE
Script MAJ 2.6 - pour info

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1257]
Dans le script de maj, il y a lignes 317-318 les actions suivantes : 
DROP VIEW IF EXISTS pr_occhab.v_export_sinp;
    CREATE VIEW pr_occhab.v_export_sinp AS

Occhab étant un module qu'on peut, ou non, installer sur son instance, le schéma n'existe pas forcément, et donc la vue peut ne pas se créer. 

Rien de bien grave en soit mais ca peut etre bien, pour les modules, de vérifier si le schéma est présent avant de lancer le bloc de commandes qui y sont liées.

**Comment by camillemonchicourt** [comment]
Oui c'est une limite du fonctionnement actuel.
Ces modules sont dans le cœur mais optionnels.
Mais quand on fait les scripts de mise à jour de GeoNature on part du principe que la personne a tous les modules installés...

Ça amène 2 possibilités :
- ne pas permettre d'installer ou non les modules du cœur. Les installer d'office quand on installe GeoNature
- avoir des mécanismes de mises à jour par module, mêmes ceux du cœur, en les exécutant ou non si ils ont installés ou pas

C'est plutôt cette deuxième approche qui est prévue avec le travail d'Elie sur l'automatisation des mises à jour de la BDD avec Alembic

**Comment by DonovanMaillard** [comment]
Oui, dansl'idée on peut soit checker si le module existe avant de lancer son script/sa partie du script. Soit installer tout le coeur par défaut, mais l'activer ou non (afficher dans le menu ou non...) selon les paramètres de l'install. A voir, c'est dans tous les cas pas très bloquant et rapide à identifier/régler lors de la MAJ, c'est surtout pour optimiser encore un peu les choses à terme :)

**Comment by jpm-cbna** [comment]
Pour info, voici le code que j'utilise dans la migration des permissions (branche en cours de travail) pour gérer ce problème:
```SQL
DO
$$
BEGIN
    RAISE NOTICE 'Add OccHab available permissions if module installed' ;

    IF EXISTS (SELECT 1 FROM gn_commons.t_modules WHERE UPPER(module_code) = 'OCCHAB') THEN
        RAISE NOTICE 'OccHab module installed - Adding available permissions...' ;

        -- Ici le code SQL dépendant de la présence du module.

    ELSE
        RAISE NOTICE 'OccHab module NOT installed.' ;
    END IF;
END ;
$$ ;
```

**Comment by TheoLechemia** [comment]
Désolé, je l'ai corrigé vendredi mais ce n'était pas commité.

**Comment by camillemonchicourt** [comment]
On n'aura plus le soucis grâce à Alembic.
Occhab est maintenant une branche Alembic, qui n'est pas installée si le module n'est pas installé.
Si il y a des migrations Alembic de la BDD du schéma de Occhab, elles ne seront exécutées que pour ceux qui ont installé le module.
