### ISSUE TITLE
Fichiers de log et migration.sh

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1258]
Certains fichiers de log sont soit pas récupérés, soit récupérés avec des droits d'écritures qui ne conviennent pas semble-t-il. Un soucis déjà vu par Camille aussi de mémoire.

Ca bloque l'exécution du script migrate.sh qui ne se termine pas bien, les commandes geonature deviennent introuvables etc. Ca se règle très facilement en créant le fichier de log manquant, mais à voir si le script de migration peut pas générer les fichiers de log manquant à terme ou ignorer.

**Comment by DonovanMaillard** [comment]
Un petit complément/solution. 

Dans mon cas c'était le fichier de log  dans var/log/gn_export/cron.log . Ma version du module export était (très) à la ramasse. Ca a été corrigé depuis du coté du module exports à priori.

**Comment by camillemonchicourt** [comment]
Oui corrigé dans la 1.1.0 du module Export - https://github.com/PnX-SI/gn_module_export/issues/86
