### ISSUE TITLE
Installation de la bdd avec un port autre que 5432

### ISSUE THREAD

**Issue by JulienCorny** [PnX-SI/GeoNature#1266]
Salut,

Pour renforcer la sécurité, j'ai voulu installer GeoNature (2.6.0) avec un autre port Postgresql que celui par défaut (5432)

Lors de l'installation de la bdd, j'ai eu des erreurs comme celle-ci :

Creating 'gn_synthese' schema...
psql: n'a pas pu se connecter au serveur : Connexion refusée
        Le serveur est-il actif sur l'hôte « localhost » (::1)
        et accepte-t-il les connexionsTCP/IP sur le port 5432 ?
n'a pas pu se connecter au serveur : Connexion refusée
        Le serveur est-il actif sur l'hôte « localhost » (127.0.0.1)
        et accepte-t-il les connexionsTCP/IP sur le port 5432 ?

Je me suis rendu compte que dans le script geonature/install/install_db.sh, il n'y a pas de paramètre -p $db_port (provenant du settings.ini) dans les lignes de commandes. J'ai testé quelques lignes de ce script en rajoutant le port et ça marche. 

Est-ce que j'ai manqué quelque chose dans les config ? ou c'est quelque chose à mettre en place ?

Après c'est pas bien grave non plus, puisqu'on peut changer le port après l'installation, mais ça permet d'économiser du temps et des commandes parce qu'il faut modifier les fichiers de config et settings de geonature, taxhub et usershub

**Comment by camillemonchicourt** [comment]
On a peu ou pas testé cela, donc il est possible que l'utilisation de la variable de PORT ait été zappée dans certaines commandes.
Voir https://github.com/PnX-SI/GeoNature/issues/504

**Comment by camillemonchicourt** [comment]
Duplicate https://github.com/PnX-SI/GeoNature/issues/504
