### ISSUE TITLE
[Synthese] - Bug - affichage du filtre avancé "statut de validation" et +

### ISSUE THREAD

**Issue by lepontois** [PnX-SI/GeoNature#1267]
Bonjour,

Dans le module synthèse, lorsque je sélectionne dans les filtres avancés le filtre "statut de validation", le champ permettant la sélection des valeurs ne s'affiche pas.
Il ne s'affiche que si je sélectionne un second filtre avancé.

En dehors de ce bug, et façon plus générale, est-il où serait-il possible de pouvoir paramétrer les filtres affichés par défaut dans le bandeau de gauche ?
Cette question car nos données étant soumise à validation,  j'aimerais que le filtre sur le statut de validation soit très facilement accessible pour nos utilisateurs et sans avoir à passer par les filtres avancés. Même chose pour le statut de l’observation (présence / absence). Sans la configuration de ces deux champs de filtre, on peut avoir une lecture fausse des résultats (affichage d'un rond renseignant de l'absence ou de la donnée invalidée lue comme une donnée de présence valide si on n'entre pas dans le détail de l'observation)

Encore plus idéale serait de pouvoir paramétrer des valeurs par défaut pour certains champs. Ainsi par exemple, le champ statut de validation serait affiché dans le bandeau de filtres avec les valeurs "certain, probable, en attente de validation".

N'hésitez pas si besoin de précision

**Comment by DonovanMaillard** [comment]
Ce dernier point est discuté sur #968 ;)

**Comment by joelclems** [comment]
J'ai pas vraiment compris pourquoi cet élément avait un comportement différent des autres
On peut forcer le recalul des éléments caché/affichés qui est normalement déclenché par un changement dans le formulaire (et qui marche sauf dans ce cas..)

**Comment by camillemonchicourt** [comment]
Ce composant est potentiellement différent car il est mis à part et en premier dans le module de Validation où il est essentiel et dont le bloc de filtre est factorisé entre les modules Synthèse et Validation.
Mais peut-être à améliorer ?

**Comment by joelclems** [comment]
de ce que je vois le champs `id_nomenclature_valid_status` est déjà présent dans le form control (cf synthese), 

`https://github.com/PnX-SI/GeoNature/blob/d8257434f92b1529032b4ae9ff9f1bd3f39a01ac/frontend/src/app/GN2CommonModule/form/synthese-form/synthese-form.service.ts#L30

à la différence de tous les autres champs des filtres avancée qui n'existent pas de base, ce qui doit expliquer la différence de comportement

le commit précédent regle ce probleme en forcant cette mise à jour à l'ajout d'un nouveau filtre spécial

**Comment by TheoLechemia** [comment]
Corrigé par Joel. 
Je ferme
