### ISSUE TITLE
la date d'obs n'est pas affichée dans la synthèse sur safari (macOS)

### ISSUE THREAD

**Issue by vprunet** [PnX-SI/GeoNature#1268]
Bonjour,

Il y a un petit problème d'affichage de date sur le client web geonature 2.5(testé au PNM et sur l'instance de démo 2.5.6), seulement lorsqu'on utilise safari sur macOS. 
La date ne s'affiche pas dans la synthèse (colonne Date obs) ni dans la fenêtre popup de détail de l'observation. 
```
Error: InvalidPipeArgument: 'Unable to convert "2021-02-08 00:00:00" into a date' for pipe 't'
```
Vincent

**Comment by TheoLechemia** [comment]
Merci pour le retour.
On a déjà eu des remontée de bug lié à Safari et on peu de moyen de le tester et donc d'assurer une compatibilité sur ce navigateur.
On conseil l'utilisation de Firefox ou Chromium (et dérivés)

**Comment by xavyeah39** [comment]
Effectivement pas eu l'occasion de retester avec Safari car nos utilisateurs privilégient l'accès à GeoNature via Firefox. 
Mais pour info, j'ai un collègue qui m'a remonté ce problème sur Safari et iOS avec une autre application grand public (GeoPaysages). 
J'avais solutionné en ajoutant un `'T'` entre la date et l'heure dans le formatage. ([commit ici](https://github.com/PnX-SI/GeoPaysages/commit/43150abf19582387b99287716515302774a2ea96))
Il semble que ce soit lié à l'interprétation des standards de formatage des dates dans les différents navigateurs : [https://stackoverflow.com/questions/16616950/date-function-returning-invalid-date-in-safari-and-firefox/16620332](https://stackoverflow.com/questions/16616950/date-function-returning-invalid-date-in-safari-and-firefox/16620332)

**Comment by camillemonchicourt** [comment]
Si certains veulent contribuer les corrections pour Safari et macOS, on est preneur.

**Comment by Florulenta** [comment]
Bonjour, je voulais remonter ce bug, mais il est connu. SI sur Mac, on peut utiliser Firefox, le problème existe aussi sur iOS et l'installation de Firefox sur la tablette ne permet pas de le contourner car il me semble que c'est le moteur de Safari qui est utilisé.

Quelques pistes : 
[https://stackoverflow.com/questions/58619575/datepipe-is-not-working-in-safari-browser](https://stackoverflow.com/questions/58619575/datepipe-is-not-working-in-safari-browser)
[https://github.com/angular/angular/issues/12334#issuecomment-254096815](https://github.com/angular/angular/issues/12334#issuecomment-254096815) :
`I have found out the cause:

// Does not work IN SAFARI
date: string = '2016-01-20T19:00:00+0000';

// Works IN SAFARI
date: string = '2016-01-20T19:00:00';`

[https://stackoverflow.com/questions/4310953/invalid-date-in-safari](https://stackoverflow.com/questions/4310953/invalid-date-in-safari)

Sinon, je veux bien tester, je bidouille le php, le js et l'html, mais je ne suis pas habitué du tout à GitHub ni Angular ou aux autres frameworks. Peut-être qu'en ayant le bout de code qui affiche la date, je peux reproduire ça en "local" et faire des tests.

**Comment by vprunet** [comment]
testé à l'instant avec une version récente de safari sur geonature 2.14 . La date s'affiche correctement.
