### ISSUE TITLE
[BDD] Pas de contrainte d'unicité sur le couple id_type/area_code de l_areas.

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature#1270]
Dans `ref_geo.l_areas`, il n'y a pas de contrainte d'unicité sur le couple `id_type`/`area_code`. Est-ce un choix volontaire? ca me semble une sécurité intéressante.

**Comment by camillemonchicourt** [comment]
Je ne vois pas de raison particulière, ça peut être utile en effet de l'ajouter pour éviter les doublons.
