### ISSUE TITLE
Script MAJ 2.6 - question

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoNature#1275]
Lors de la mise à jours de plusieurs instances de 2.5.5 à 2.6.0, [le script SQL](https://github.com/PnX-SI/GeoNature/blob/master/data/migrations/2.5.5to2.6.0.sql#L477) me lève 2 erreurs :

Ligne 251 : `DROP TRIGGER tri_update_cor_area_synthese ON gn_synthese.synthese;`

> Sortie : ERREUR: le trigger « tri_update_cor_area_synthese » de la table « synthese » n'existe pas

Ligne 477 : `DROP FUNCTION gn_synthese.calcul_cor_area_taxon;`

> Sortie : ERREUR: n'a pas pu trouver une fonction nommée « gn_synthese.calcul_cor_area_taxon »

En ajoutant `IF EXISTS` sur ces 2 lignes ça passe, pas de soucis lors de la mise à jour et tout semble OK côté fonctionnement.

Comme j'ai remonté pas mal de versions + passage sur Debian 10 sur ces différentes instances, j'aimerai m'assurer de n'avoir rien loupé lors de l’exécution des scripts SQL des versions intermédiaires...
même si je n'ai rien trouvé dans ce sens en recherchant dans le dépôt sur ces 2 objets de la BDD.

Un lien avec un autre module (mobile ?) semblable à #1257 ?
Quelqu'un à t'il rencontré ce "problème" ?
Merci pour vos lumières !

**Comment by TheoLechemia** [comment]
C'est pas normal que le trigger `tri_update_cor_area_synthese`  et la fonction `calcul_cor_area_taxon` ne soit pas présent dans une version < à 2.6.0. (un oubli dans un script de migration du notre côté ou du tiens ?)
Tu dois du coup avoir un soucis dans tes données au niveau de l'intersection des données de la synthese avec le ref_geo (et par conséquence des recherches par zone géographique non consistante). Tu peux essayer de rejouer manuellement ce que fais le trigger, mais ça risque d'être un peu long (ça ne concerne que les données dont la géom aurait été modifiée)

Je MAJ le script avec le `IF EXISTS` au cas ou.

**Comment by xavyeah39** [comment]
> C'est pas normal que le trigger tri_update_cor_area_synthese et la fonction calcul_cor_area_taxon ne soit pas présent dans une version < à 2.6.0. (un oubli dans un script de migration du notre côté ou du tiens ?)

J'ai fais ces montées en versions sur 3 instances différentes (de 2.3.1 à 2.6.0). Effectivement, possible loupé de mon côté mais sur 3 instances je me dis que c'est moins probable... Cela dit, lors d'une ré-installation globale vierge en 2.4.1, je constate que ce trigger n'est pas présent non-plus...

> Tu dois du coup avoir un soucis dans tes données au niveau de l'intersection des données de la synthese avec le ref_geo (et par conséquence des recherches par zone géographique non consistante). Tu peux essayer de rejouer manuellement ce que fais le trigger, mais ça risque d'être un peu long (ça ne concerne que les données dont la géom aurait été modifiée)

J'ai contrôlé rapidement mais ce n'a pas l'air d'être le cas. Effectivement, dans le doute je vais ré-exécuter la fonction du trigger pour réactualiser `cor_area_taxon`

> Je MAJ le script avec le IF EXISTS au cas ou.

Merci !
