### ISSUE TITLE
Customisation de la page de login

### ISSUE THREAD

**Issue by Amegilla** [PnX-SI/GeoNature#1277]
Est-il prévu de pouvoir customiser la page de login ?
Ne serait-ce que pouvoir modifier le texte affiché en titre et modifier l'image de fond ?
De mon coté je customise cette page juste avec ces deux éléments et j'imagine que je ne suis pas le seul ?
merci pour vos retours

**Comment by DonovanMaillard** [comment]
bonjour, ça se fait en css pour l'image de fond, c'est déjà le cas chez nous. Quant au texte en titre, c'est le titre de l'application mais il faut que je regarde, c'était modifié un temps et ca ne l'est plus sur notre instance sans que j'aie passé trop de temps à en chercher la cause.

**Comment by Amegilla** [comment]
Je sais que mes modifs sont écrasées à chaque migration car il ne s'agit pas d'une page "custom". Je pense qu'elle pourrait faire partie des éléments customisables. A voir de quelle façon, peut-être uniquement pour le texte du titre.

**Comment by DonovanMaillard** [comment]
@jpm-cbna travaille en ce moment sur la customisation, je le tague au cas où il aurait des idées sur le sujet :) 

De mon coté le background ne disparait pas lors des migrations en effet, seulement le nom de l'appli.

**Comment by TheoLechemia** [comment]
Si elles sont dans custom.scss elle ne seront pas écrasé à chaque migration.
Par contre le reste (le nom par exemple) n'est pas modifiable à l'heure actuelle.

**Comment by Amegilla** [comment]
Merci pour vos retour, et pour la réactivité Donovan !

**Comment by Amegilla** [comment]
> 
> 
> @jpm-cbna travaille en ce moment sur la customisation, je le tague au cas où il aurait des idées sur le sujet :)
> 
> De mon coté le background ne disparait pas lors des migrations en effet, seulement le nom de l'appli.

C'est quand j'ai vu passer ces issues que j'en ai profité pour lancer ce sujet :)

**Comment by jpm-cbna** [comment]
Je confirme aussi que [le fichier de l'image du background](https://github.com/PnX-SI/GeoNature/blob/master/frontend/src/custom/images/login_background.jpg) est bien dans le dossier custom et n'est donc pas écrasé lors des migrations.

Mon ticket #1276 concernait plutôt la possibilité de gérer plus facilement le format des images personnalisables de GeoNature mais je note le besoin de customisation du titre du formulaire sur la page de login. En effet, j'ai testé le format webp qui [est maintenant largement supporté](https://caniuse.com/webp). J'obtiens des taux de compression bien meilleur que pour le jpg et le png avec des dégradations peu visible. De plus, il supporte facilement les différents types d'images (photo, dessin, logos...)...

J'essayerai de travailler sur ce sujet dès que j'aurai finaliser mon travail sur la gestion des permissions avec la pull-request #1259 ...

**Comment by camillemonchicourt** [comment]
OK si la PR de @DonovanMaillard pour utiliser le paramètre du nom sur la page LOGIN est OK, alors cela répond au besoin évoqué par @Amegilla.
