### ISSUE TITLE
[Bug] - formulaire de création de compte

### ISSUE THREAD

**Issue by lepontois** [PnX-SI/GeoNature#1279]
Bonjour,

Je suis en version 2.5.5
Je souhaite activer la possibilité que les nouveaux utilisateurs puissent créé un compte via le formulaire activer sur la page de login.

Après validation du formulaire, on rencontre une erreur (affichage d'un bandeau rouge sans message) laissant croire que la demande de création de compte n'a pas été prise en compte.

En regardant les logs j'ai le message suivant :
```
[2021-02-15 07:55:15 +0000] [29350] [ERROR] (psycopg2.errors.UndefinedColumn) column temp_users.confirmation_url does not exist
LINE 1: ...cation AS utilisateurs_temp_users_id_application, utilisateu...

[SQL: SELECT utilisateurs.temp_users.id_temp_user AS utilisateurs_temp_users_id_temp_user, utilisateurs.temp_users.token_role AS utilisateurs_temp_users_token_role, utilisateurs.temp_users.organisme AS utilisateurs_temp_users_organisme, utilisateurs.temp_users.id_application AS utilisateurs_temp_users_id_application, utilisateurs.temp_users.confirmation_url AS utilisateurs_temp_users_confirmation_url, utilisateurs.temp_users.groupe AS utilisateurs_temp_users_groupe, utilisateurs.temp_users.identifiant AS utilisateurs_temp_users_identifiant, utilisateurs.temp_users.nom_role AS utilisateurs_temp_users_nom_role, utilisateurs.temp_users.prenom_role AS utilisateurs_temp_users_prenom_role, utilisateurs.temp_users.desc_role AS utilisateurs_temp_users_desc_role, utilisateurs.temp_users.password AS utilisateurs_temp_users_password, utilisateurs.temp_users.pass_md5 AS utilisateurs_temp_users_pass_md5, utilisateurs.temp_users.email AS utilisateurs_temp_users_email, utilisateurs.temp_users.id_organisme AS utilisateurs_temp_users_id_organisme, utilisateurs.temp_users.remarques AS utilisateurs_temp_users_remarques, utilisateurs.temp_users.champs_addi AS utilisateurs_temp_users_champs_addi, utilisateurs.temp_users.date_insert AS utilisateurs_temp_users_date_insert, utilisateurs.temp_users.date_update AS utilisateurs_temp_users_date_update 
FROM utilisateurs.temp_users 
WHERE utilisateurs.temp_users.token_role = %(token_role_1)s 
 LIMIT %(param_1)s]
[parameters: {'token_role_1': '215985274295265816034341013954181300328', 'param_1': 1}]
```

Le champ temp_users.confirmation_url n'existe pas sur la table utilisateurs.temp_users.

Il ne semble pas y avoir de correctif à ce sujet sur la 2.6 (ou 2.6.1)

Merci

**Comment by TheoLechemia** [comment]
Salut,

Quelle est ta version de Usershub ?
A partir de la 2.5.0, il faut à minima la version 2.1.3 de UsersHub. La note de version n'indique pas explicitement de passer le script de migration en effet. (https://github.com/PnX-SI/UsersHub/blob/master/data/update_2.1.2to2.1.3.sql)

**Comment by lepontois** [comment]
Merci Théo, 
Effectivement, je suis en 2.1.2. 

J'ai pas testé de faire la mise à jour pour rester dans le même environnement que l'instance BRGM mais je pense qu'on doit pouvoir indiquer "Problème résolu"

**Comment by camillemonchicourt** [comment]
Hum hum, en regardant les notes de version de GeoNature, on ne fait pas référence au fait qu'il faut mettre à jour USersHub.
Si c'est le cas, il faut qu'on l'ajoute clairement.

**Comment by camillemonchicourt** [comment]
OK c'est bon.
Dans la 2.5.0, on a bien indiqué pour cette fonctionnalité particulière : 

> Création de compte : Envoi automatique d'un email à l'utilisateur quand son compte est validé. Nécessite la version 2.1.3 de UsersHub (#862 et #1035 par @jpm-cbna)
