### ISSUE TITLE
Synthèse - Ne pas afficher certains cadres d'acquisition

### ISSUE THREAD

**Issue by samuelpriou** [PnX-SI/GeoNature#1281]
Bonsoir, 

Lorsque nous filtrons les données de la synthèse avec le cadre d'acquisition, nous retrouvons "flore prioritaire" et "flore station" alors que nous ne n'utilisons pas ces deux modules dans GeoNature.

Il faudrait envisager un paramètre permettant de cacher ces deux cadres d’acquisition et d'autres ? dans la synthèse.

Merci

**Comment by DonovanMaillard** [comment]
Ca n'est pas dependant des modules installés dans l'instance ? Je ne les ai pas chez moi. Dans tous les cas si jamais utilsies ils peuvent être supprimées bdd
