### ISSUE TITLE
[Bug - Modification comportement] - non répliqué sur la synthèse

### ISSUE THREAD

**Issue by lepontois** [PnX-SI/GeoNature#1283]
Je viens de me rendre compte que sur la V2.5.5 si l'on change la valeur du champ comportement sur l'observation d'un taxon, ce changement n'est pas répliqué sur la synthèse. 

Le problème se situe sur le trigger pr_occtax.fct_tri_synthese_update_occ() où j'ai constaté que nous avons :
`id_nomenclature_behaviour = id_nomenclature_behaviour,`

qui serait à remplacer par :
`id_nomenclature_behaviour = NEW.id_nomenclature_behaviour,`

Ça ne semble pas être corrigé sur la 2.6 au regard du script SQL a exécuter pour la migration de la base.

**Comment by camillemonchicourt** [comment]
Trigger à revoir donc mais il faudrait aussi mettre à jour si il y a des données incohérentes entre Occtax et Synthèse modifiées entre temps.

**Comment by camillemonchicourt** [comment]
Aussi remonté sur https://github.com/PnX-SI/GeoNature/issues/1469 et corrigé dans la 2.8.0 par https://github.com/PnX-SI/GeoNature/commit/8c00e3f9cad6e5096e121939b8d45a414717cbcd
