### ISSUE TITLE
[Amélioration] - Fonction de calcul de la sensibilité

### ISSUE THREAD

**Issue by lepontois** [PnX-SI/GeoNature#1284]
Dans le cas ou nous avons deux règles différentes pour un même taxon en fonction du territoire (cor_sensitivity_area) il faut que la fonction de calcul de la sensibilité ne récupère que les critères pour le territoire où l'observation a été réalisé. 

Sauf erreur de ma part, il faudrait modifier gn_sensitivity.get_id_nomenclature_sensitivity de la façon suivante :

```
CREATE OR REPLACE FUNCTION gn_sensitivity.get_id_nomenclature_sensitivity(
	my_date_obs date,
	my_cd_ref integer,
	my_geom geometry,
	my_criterias jsonb)
    RETURNS integer
    LANGUAGE 'plpgsql'
    COST 100
    IMMUTABLE PARALLEL UNSAFE
AS $BODY$
DECLARE
          niv_precis integer;
          niv_precis_null integer;
      BEGIN
          niv_precis_null := (SELECT ref_nomenclatures.get_id_nomenclature('SENSIBILITE'::text, '0'::text));

          -- ##########################################
          -- TESTS unicritère
          --    => Permet de voir si un critère est remplis ou non de façon à limiter au maximum
          --      la requete globale qui croise l'ensemble des critères
          -- ##########################################

          -- Paramètres cd_ref
          IF NOT EXISTS (
              SELECT 1
              FROM gn_sensitivity.t_sensitivity_rules_cd_ref s
              WHERE s.cd_ref = my_cd_ref
          ) THEN
              return niv_precis_null;
          END IF;

          -- Paramètres durée de validité de la règle
          IF NOT EXISTS (
              SELECT 1
              FROM gn_sensitivity.t_sensitivity_rules_cd_ref s
              WHERE s.cd_ref = my_cd_ref
              AND (date_part('year', CURRENT_TIMESTAMP) - sensitivity_duration) <= date_part('year', my_date_obs)
          ) THEN
              return niv_precis_null;
          END IF;

          -- Paramètres période d'observation
          IF NOT EXISTS (
              SELECT 1
              FROM gn_sensitivity.t_sensitivity_rules_cd_ref s
              WHERE s.cd_ref = my_cd_ref
              AND (to_char(my_date_obs, 'MMDD') between to_char(s.date_min, 'MMDD') and to_char(s.date_max, 'MMDD') )
          ) THEN
              return niv_precis_null;
          END IF;

          -- Paramètres critères biologiques
          -- S'il existe un critère pour ce taxon
          IF EXISTS (
              SELECT 1
              FROM gn_sensitivity.t_sensitivity_rules_cd_ref s
              JOIN gn_sensitivity.cor_sensitivity_criteria c USING(id_sensitivity)
-- AJOUT LLP : Jointure pour pouvoir récupérer la géométrie du territoire associé à la règle et aux critères
              JOIN gn_sensitivity.cor_sensitivity_area sa USING(id_sensitivity)
	      JOIN ref_geo.l_areas a USING(id_area)
--FIN AJOUT LLP
			  
			  WHERE s.cd_ref = my_cd_ref
-- AJOUT LLP : Filtre pour ne conserver que les règles s'appliquant sur le territoire d'observation
			  AND (st_intersects(my_geom, a.geom) OR a.geom IS NULL)
--FIN AJOUT LLP
          ) THEN
              -- Si le critère est remplis
              niv_precis := (

            WITH RECURSIVE h_val(KEY, value, id_broader) AS  (
              SELECT KEY, value::int, id_broader
              FROM (SELECT * FROM jsonb_each_text(my_criterias)) d
              JOIN ref_nomenclatures.t_nomenclatures tn
              ON tn.id_nomenclature = d.value::int
              UNION
              SELECT KEY, id_nomenclature , tn.id_broader
              FROM ref_nomenclatures.t_nomenclatures tn
              JOIN h_val
              ON tn.id_nomenclature = h_val.id_broader
              WHERE NOT id_nomenclature = 0
            )
            SELECT DISTINCT id_nomenclature_sensitivity
            FROM gn_sensitivity.t_sensitivity_rules_cd_ref s
            JOIN gn_sensitivity.cor_sensitivity_criteria c USING(id_sensitivity)
            JOIN h_val a
            ON c.id_criteria = a.value
            WHERE s.cd_ref = my_cd_ref
            LIMIT 1
              );
              IF niv_precis IS NULL THEN
                  niv_precis := (SELECT ref_nomenclatures.get_id_nomenclature('SENSIBILITE'::text, '0'::text));
                  return niv_precis;
              END IF;
          END IF;
          -- ##########################################
          -- TESTS multicritères
          --    => Permet de voir si l'ensemble des critères sont remplis
          -- ##########################################

          -- Paramètres durée, zone géographique, période de l'observation et critères biologique
        SELECT INTO niv_precis s.id_nomenclature_sensitivity
        FROM (
          SELECT s.*, l.geom, c.id_criteria, c.id_type_nomenclature
          FROM gn_sensitivity.t_sensitivity_rules_cd_ref s
          LEFT OUTER JOIN gn_sensitivity.cor_sensitivity_area  USING(id_sensitivity)
              LEFT OUTER JOIN gn_sensitivity.cor_sensitivity_criteria c USING(id_sensitivity)
          LEFT OUTER JOIN ref_geo.l_areas l USING(id_area)
        ) s
        WHERE my_cd_ref = s.cd_ref
          AND (st_intersects(my_geom, s.geom) OR s.geom IS NULL) -- paramètre géographique
          AND (-- paramètre période
            (to_char(my_date_obs, 'MMDD') between to_char(s.date_min, 'MMDD') and to_char(s.date_max, 'MMDD') )
          )
          AND ( -- paramètre duré de validité de la règle
            (date_part('year', CURRENT_TIMESTAMP) - sensitivity_duration) <= date_part('year', my_date_obs)
          )
          AND ( -- paramètre critères
                  s.id_criteria IN (SELECT  value::int FROM jsonb_each_text(my_criterias)) OR s.id_criteria IS NULL
          );

        IF niv_precis IS NULL THEN
          niv_precis := niv_precis_null;
        END IF;

        return niv_precis;

  END;
```

C'est peut-être optimisable !

Il me reste à chercher comment gérer le cas où sur un même terrtoire on a deux règles différentes pour une même espèce:
- une règle avec des critères donnant un niveau de sensibilité à la maille 10
- une règle sans critère donnant un niveau de sensibilité à la commune

**Comment by lepontois** [comment]
Au niveau de la partie
```
-- Paramètres critères biologiques
-- S'il existe un critère pour ce taxon
```
J'ai retiré la condition suivante :
```
IF niv_precis IS NULL THEN
    niv_precis := (SELECT ref_nomenclatures.get_id_nomenclature('SENSIBILITE'::text, '0'::text));
    return niv_precis;
END IF;
```

Ainsi, si l'observation ne correspond à aucun critère de sensibilité du taxon la fonction continu, ce qui permet de prendre en compte l'éventuelle autre règle n'ayant pas de critère.

Ainsi adapté, mes tests semble concluant.
- Si j'observe un loup dans le 64 en repro, la sensibilité est à "Département et maille 10 x 10 km"
- Si j'observe un loup (toujours dans le 64) sans critère spécifique, la sensibilité est à "Département, Maille 10*10, Maille 5*5, espace, commune, ZNIEFF"
- Si j'observe un loup avec ou sans critère dans le 65, la sensibilité est à "Département et maille 10 x 10 km"
Ce sont les résultats attendus.

Cela dit, un regard expert et des tests plus complet serait à réaliser pour valider.

**Comment by amandine-sahl** [comment]
Essaye avec cette version.
Même si je m'interroge sur les tests unicritères vs multi

```sql

CREATE OR REPLACE FUNCTION gn_sensitivity.get_id_nomenclature_sensitivity(
	my_date_obs date,
	my_cd_ref integer,
	my_geom geometry,
	my_criterias jsonb)
    RETURNS integer
    LANGUAGE 'plpgsql'
    COST 100
    IMMUTABLE PARALLEL UNSAFE
AS $BODY$
DECLARE
          niv_precis integer;
          niv_precis_null integer;
          ids_rules integer[];
      BEGIN
          niv_precis_null := (SELECT ref_nomenclatures.get_id_nomenclature('SENSIBILITE'::text, '0'::text));

         -- Récupération des règles active pour le taxon dans le périmètre indiqué
         
		ids_rules := (
			SELECT array_agg(s.id_sensitivity) 
			FROM gn_sensitivity.t_sensitivity_rules_cd_ref s
			JOIN gn_sensitivity.cor_sensitivity_area sa ON s.id_sensitivity = sa.id_sensitivity 
			JOIN ref_geo.l_areas la ON sa.id_area = la.id_area 
			WHERE s.cd_ref = my_cd_ref
				AND (st_intersects(my_geom, la.geom) OR la.geom IS NULL)
       );
       
	   -- Si aucune règle valide pour le taxon dans la zone donnée
	   IF array_length(ids_rules, 1) IS NULL THEN
              return niv_precis_null;
	   END IF;
	   
      -- ##########################################
      -- TESTS unicritère
      --    => Permet de voir si un critère est remplis ou non de façon à limiter au maximum
      --      la requete globale qui croise l'ensemble des critères
      -- ##########################################
          -- Paramètres durée de validité de la règle
          IF NOT EXISTS (
              SELECT 1
              FROM gn_sensitivity.t_sensitivity_rules_cd_ref s
              WHERE s.id_sensitivity = ANY(ids_rules)
              AND (date_part('year', CURRENT_TIMESTAMP) - sensitivity_duration) <= date_part('year', my_date_obs)
          ) THEN
              return niv_precis_null;
          END IF;

          -- Paramètres période d'observation
          IF NOT EXISTS (
              SELECT 1
              FROM gn_sensitivity.t_sensitivity_rules_cd_ref s
              WHERE s.id_sensitivity = ANY(ids_rules)
              AND (to_char(my_date_obs, 'MMDD') between to_char(s.date_min, 'MMDD') and to_char(s.date_max, 'MMDD') )
          ) THEN
              return niv_precis_null;
          END IF;

          -- Paramètres critères biologiques
          -- S'il existe un critère pour ce taxon
          IF EXISTS (
              SELECT 1
              FROM  gn_sensitivity.cor_sensitivity_criteria c 
              WHERE c.id_sensitivity = ANY(ids_rules)
          ) THEN
              -- Si le critère est remplis
              niv_precis := (
		            WITH RECURSIVE h_val(KEY, value, id_broader) AS  (
						  SELECT KEY, NULLIF (value::int, -1) AS value, id_broader
						  FROM (SELECT * FROM jsonb_each_text(COALESCE(my_criterias, '{"NULL":  "-1"}'))) d
						  LEFT OUTER JOIN ref_nomenclatures.t_nomenclatures tn
						  ON tn.id_nomenclature = d.value::int
						  UNION
						  SELECT KEY, id_nomenclature , tn.id_broader
						  FROM ref_nomenclatures.t_nomenclatures tn
						  JOIN h_val
						  ON tn.id_nomenclature = h_val.id_broader
						  WHERE NOT id_nomenclature = 0
					) 
					SELECT DISTINCT 1
					FROM gn_sensitivity.t_sensitivity_rules_cd_ref s
					LEFT OUTER JOIN gn_sensitivity.cor_sensitivity_criteria c USING(id_sensitivity)
					JOIN h_val a
					ON c.id_criteria = a.value OR c.id_criteria IS NULL
					WHERE s.id_sensitivity = ANY(ids_rules)
					LIMIT 1
              );
              IF niv_precis IS NULL THEN
                  niv_precis := (SELECT ref_nomenclatures.get_id_nomenclature('SENSIBILITE'::text, '0'::text));
                  return niv_precis;
              END IF;
          END IF;
         
         
          -- ##########################################
          -- TESTS multicritères
          --    => Permet de voir si l'ensemble des critères sont remplis
          -- ##########################################
          -- Paramètres durée, zone géographique, période de l'observation et critères biologique
        SELECT INTO niv_precis s.id_nomenclature_sensitivity
        FROM (
          SELECT s.*, l.geom, c.id_criteria, c.id_type_nomenclature
          FROM gn_sensitivity.t_sensitivity_rules_cd_ref s
          LEFT OUTER JOIN gn_sensitivity.cor_sensitivity_area  USING(id_sensitivity)
		  LEFT OUTER JOIN gn_sensitivity.cor_sensitivity_criteria c USING(id_sensitivity)
          LEFT OUTER JOIN ref_geo.l_areas l USING(id_area)
        ) s
        WHERE s.id_sensitivity = ANY(ids_rules)
          AND (-- paramètre période
            (to_char(my_date_obs, 'MMDD') between to_char(s.date_min, 'MMDD') and to_char(s.date_max, 'MMDD') )
          )
          AND ( -- paramètre duré de validité de la règle
            (date_part('year', CURRENT_TIMESTAMP) - sensitivity_duration) <= date_part('year', my_date_obs)
          )
          AND ( -- paramètre critères
              s.id_criteria IN (SELECT value::int FROM jsonb_each_text(my_criterias)) OR s.id_criteria IS NULL
          );

        IF niv_precis IS NULL THEN
          niv_precis := niv_precis_null;
        END IF;

        return niv_precis;

  END;
 $BODY$
```

**Comment by lepontois** [comment]
Ça me semble nickel et peut-être même plus performant que ma version !

Merci pour le partage !

**Comment by Splendens** [comment]
Bonjour,

@lepontois , est-ce que les cas que tu décris fonctionnent bien chez toi (avec la fonction réécrite) ?

> Si j'observe un loup dans le 64 en repro, la sensibilité est à "Département et maille 10 x 10 km"
> Si j'observe un loup (toujours dans le 64) sans critère spécifique, la sensibilité est à "Département, Maille 1010, Maille 55, espace, commune, ZNIEFF"
> Si j'observe un loup avec ou sans critère dans le 65, la sensibilité est à "Département et maille 10 x 10 km"

Si oui, est-ce que tu pourrais partager tes entrées dans les différentes tables de gn_sensitivity pour cet exemple du loup ?
J'essaye de faire la même chose, mais je patauge avec la définition des règles de sensibilités différentes en fonction de critères (ou non) +/- une zone géographique.

**Comment by Splendens** [comment]
J'ai finalement réussi à avoir le même comportement que celui cité pour le Loup.
Quelques précisions si d'autres personnes se posaient les mêmes questions que moi :

- attention au champs `active` de la table  `gn_sensivity.t_sensitivity_rules`, qui doit être à `true`

- si on veut une définition des règles différentes en fonction d'un territoire et de critères :

1. Pour chaque critère (listés dans `gn_sensivity.cor_sensitivity_criteria` )  il faut ajouter une entrée correspondante dans la table `gn_sensivity.cor_sensitivity_area` (id de la règle - id de la zone géo).
2.  Dans `gn_sensivity.cor_sensitivity_criteria` , il faut ajouter une règle pour le cas où il n'y aurait pas de critère particulier saisi dans occtax (sous la forme : id_sensitivity - NULL -  id_type_nomenclature). Il faut ajouter cette valeur "null" pour chaque type de nomenclature pour lequel on a un critère lié à la sensibilité du taxon (statut biologique, comportement...). Cette valeur va servir de valeur par défaut à attribuer au taxon si jamais aucun critère de sensibilité particulière n'est trouvé.
3. Si j'ai bien pigé, dans `gn_sensivity.cor_sensitivity_area`, la règle à attribuer par défaut ( le critère à "null") est à renseigner en dernier, l'ordre des enregistrements en BD semble avoir une importance dans leur prise en compte (ou c'est autre chose ?).

-  s'il  y avait déjà des données d'occurrences saisies, la modification des règles et la mise à jour de la synthèse ne met à jour que le niveau de sensibilité. Il faut donc vérifier les niveau de diffusion de chaque entrée dans la synthèse et les mettre à jour au besoin.

D'ailleurs, la modification des infos dans un relevé OccTax ne modifie pas le niveau de diffusion dans la synthèse, seulement le niveau de sensibilité. 

Par contre, j'ai un problème avec les taxons qui peuvent avoir plusieurs niveaux de sensibilité selon des critères. Je ne comprends pas comment le niveau de sensibilité est sélectionné : je n'ai pas l'impression que l'ordre des entrées en BD ait une importance, et ce n'est pas forcément le niveau de sensibilité le plus haut qui est sélectionné... Quelqu'un en sait plus ou a eu besoin de plusieurs critères pour un même taxon ?

**Comment by TheoLechemia** [comment]
Dans la version actuelle il n'y a plus de vérification de l'existence d'une règle lié à une nomenclature (statut bio ou autre), car un taxon peut être sensible sans association à une nomenclature. Donc pas besoin de ton point "2" Marie.
Par contre pour l'ordre il faut s'y pencher un peu plus et que je reproduise le cas. On va y revenir dans la cadre de l'implémentation du floutage assez rapidement

**Comment by Splendens** [comment]
Ok, Merci Théo ! Effectivement, le point 2 ne semble pas nécessaire. Je pense que je me suis emmêlé les pinceaux en essayant de définir plusieurs critères sur des champs différents et sur des zones géographiques (que je ne parviens toujours pas à réaliser).

**Comment by bouttier** [comment]
Je pense supprimer les tests uni-critères. En effet :
- Je pense que Postgresql est suffisamment intelligent pour arrêter d’évaluer une ligne dès lorsqu’un critère du where est évalué à faux (je pense même que le planificateur est suffisamment intelligent pour commencer par les critères les plus rapide à évaluer), il n’y a donc pas lieu de procéder à ce genre d’optimisation soi-même à la main.
- Le contrôle uni-critère statut bio est erroné : dans le cas où on a plusieurs règles, si une règle ne s’applique pas en raison de son statut bio, alors l’observation est jugé non sensible, alors qu’une autre règle sans statut bio, ou alors avec un statut bio qui match, peut définir une sensibilité à l’observation. Maintenir 2 versions (uni/multi) d’un même contrôle amène à 2 fois plus d’erreurs, je préfère supprimer ce check que chercher à le corriger.

**Comment by bouttier** [comment]
Nouvelle fonction du calcul de la sensibilité, corrigé, couverte par les tests unitaires : https://github.com/PnX-SI/GeoNature/commit/f3b80057d6d59a58786c4db82a1578f57fdec419
