### ISSUE TITLE
Métadonnées - Sur la page des CA et JDD rendre le bouton actif/inactif dynamique

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/GeoNature#1290]
Discuté avec Théo et Camille : rendre le bouton vert/rouge qui siginifie si un jeu de données est actif ou pas dynamique pour que ça puisse être managé plus vite.

**Comment by DonovanMaillard** [comment]
Bonne idée, j'ai appuyé dessus plusieurs fois avant de comprendre qu'il n'était pas dynamique 🤣

**Comment by jbrieuclp** [comment]
Je peux intégrer cette proposition dans mes dev ici : #1291

**Comment by AmelieTagliaferro** [comment]
Bonjour, je reviens sur ce point, à quoi sert de savoir si le JDD est actif ou inactif ? cela conditionne sa diffusion ? je n'ai pas rès bien compris son utilité pour l'instant... 
Merci d'avance pour vos réponses,

**Comment by camillemonchicourt** [comment]
Cette fonctionnalité a été intégrée dans une version précédente et est fonctionnelle.
Un JDD inactif est un JDD qui est terminé, dans lequel il n'y a plus de nouvelles données.
Ainsi rendre un JDD inactif permet de ne plus le proposer dans la liste des JDD quand on saisit un relevé dans Occtax.

**Comment by AmelieTagliaferro** [comment]
Très bien merci :)
