### ISSUE TITLE
[Metadonnées] - Optimisation du chargement des données

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#1291]
La mise à jour du module métadonnée de géonature 2.6 est bien sympa, par contre qu'est ce qu'elle est lente !
Pour ~200 CA et ~1000 JDD, le chargement de la page de la liste met quasi 10 sec à s'effectuer. En cause un nombre impressionnant de requêtes exécutées.
Sans changer les fonctionnalités, j'ai réussi à reprendre le backend de cette première page en utilisant notamment marshmallow. Le chargement des données se fait en 1-2sec.
Je vais reprendre les quelques éléments manquant aux formulaires des CA et JDD et proposer la PR.

**Comment by camillemonchicourt** [comment]
Oui en effet.
Cette refonte a été faite par un prestataire sans optimisation.
Theo l'a reprise à l'essentiel pour limiter les soucis. Mais il y a encore des choses à reprendre c'est clair !

**Comment by jbrieuclp** [comment]
Je vais mettre à dispo une PR. 
Est fait pour le moment : 
- la reprise du fonctionnement de la page principale avec l'utilisation de Marshmallow,
- l'affichage des infos dans la page des détails selon qu'un module est installé ou pas. (#1294)
- la prise en compte du standard 1.3.10 des métadonnées dans les form (c'est en cours pour la gestion des acteurs et du type de role selon JDD ou CA)

Sera à faire le contrôle de l'ensemble des routes du modules et potentiellement leur mise en fonctionnement avec marshmallow

**Comment by Adrien-Pajot** [comment]
Merci pour cette réponse, je vais donc attendre cette PR pour commencer les dev sur le module !
