### ISSUE TITLE
[Métadonnées] - Accéder à un import depuis le JDD

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/GeoNature#1294]
Dans la nouvelle version du module MTD il est possible de voir les imports qui constituent un JDD. 
Il est même possible de voir le statut de celui-ci. 
Or, quand un import est en erreur, il serait intéressant de pouvoir y accéder en cliquant depuis le JDD.

**Comment by DonovanMaillard** [comment]
Bonjour, 

A plusieurs endroits du module métadonnées, le module d'imports est déjà très/trop "intrusif", et lorsqu'on est sur une instance sans module d'import ça amène à des incompréhensions (dans le menu et dans la fiche, boutons "importer dans le jdd" notamment). 

Il serait intéressant que ces fonctionnalités ainsi que les nouvelles que tu proposes ne soient actives que si le module d'import est disponible sur l'instance et si l'utilisateur courrant y a accès. 

D'une manière générale, est-ce qu'il ne serait pas plus pertinent, dans la manière de faire, que toutes ces fonctionnalités soient gérées du coté du module d'import et qu'elles viennent "surcoucher" ou se charger dans le module MTD, de manière à ce que le cruved et la disponibilité du module soient en cohérence avec l'affichage de toutes ces infos coté MTD ? Les modules seraient alors à même de compléter/surcoucher des infos accessibles depuis d'autres outlis (mtd etc).

**Comment by camillemonchicourt** [comment]
Oui c'est déjà pris en compte. Pour le bouton "Importer dans le JDD" c'est désactivable et on vérifie la présence du module.
Pour la liste des imports dans un JDD, ça vérifie aussi si il y a le module Import, ou du moins si il y a des imports.
C'est donc transparent pour ceux qui n'ont pas le module.

Mais l'idée de lister des sources plutôt que des imports dans les fiches des JDD est justement pour rendre cela plus générique.

**Comment by jbrieuclp** [comment]
Ouai ces actions sont bizarrement activable/désactivable. Mais il suffit simplement de récupérer la liste des modules présents dans l'instance de GN et d'afficher les fonctionnalités en conséquence.

**Comment by camillemonchicourt** [comment]
Oui pour le bouton IMPORTER DEPUIS UN JDD, on en avait en plus fait un paramètre car même en aillant le module d'import on peut vouloir ne pas activer cette fonctionnalité qui ne faisait pas consensus, et en plus peut poser des problèmes de CRUVED. Voir https://github.com/PnX-SI/GeoNature/issues/889#issuecomment-742655014

**Comment by camillemonchicourt** [comment]
En effet dans la 2.6, ce bouton avait été codé en dur en lien avec le module IMPORT.
Cela a été revu en 2.10.4 pour ne plus être spécifique au module IMPORT et ne pas faire appel à ce module dans le cœur de GeoNature : https://github.com/PnX-SI/GeoNature/issues/2151.

**Comment by camillemonchicourt** [comment]
Et pour le sujet initial de ce ticket, qui est un peu différent, il est bien possible désormais d'accéder directement au rapport d'un import, depuis la fiche d'un JDD auquel cet import est associé : 

![image](https://github.com/PnX-SI/GeoNature/assets/4418840/2d73cf4e-79e1-4d81-ac23-56165bff399c)
