### ISSUE TITLE
[OCCTAX] Quand le nom du taxon est "long" les boutons actions ne sont pas visibles

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/GeoNature#1299]
Il faudrait mettre les boutons actions avant le nom du taxon pour éviter tout problème.
![image](https://user-images.githubusercontent.com/3088650/111286983-10ef9680-8643-11eb-8530-ecba57219632.png)

**Comment by camillemonchicourt** [comment]
Fait dans la 2.7.0, mais du coup le nom est aligné à droite, ce que je ne trouve pas très ergonomique.
