### ISSUE TITLE
[OCCTAX] Ne trouve pas l'espèce via le nom vernaculaire #TaxHub #TaxRef

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature#1302]
Je ne sais pas si le sujet a déjà été abordé mais je n'ai pas réussi à retrouver le ticket si c'est le cas.

Un utilisateur m'a mentionné qu'il ne pouvait pas saisir (sur Occtax) la Sarcelle d'été dans le champ taxon (donc par son nom vernuculaire).
Effectivement, après vérification, le nom vernaculaire de n'était pas spécifiée (dans ma version de TaxRef)

Ainsi, j'ai appliqué la modification via le TaxHub (qui modifie le nom vernaculaire de la table `taxonomie.bib_noms` si je ne m'abuse?) et même en base directement dans la table TaxRef.

Or, il ne veut toujours pas le trouver dans Occtax.... Avez-vous une idée ?

## > TaxHub : 

![image](https://user-images.githubusercontent.com/66769358/111456394-3bab1f00-8717-11eb-8b99-7a9329c5c7a5.png)

## > Bib_noms : 

![image](https://user-images.githubusercontent.com/66769358/111456683-93498a80-8717-11eb-901f-bebc9f778045.png)

## > Taxref : 

![image](https://user-images.githubusercontent.com/66769358/111457068-06eb9780-8718-11eb-9d7d-a4446e4bce0f.png)

## > Recherche Occtax : 

![image](https://user-images.githubusercontent.com/66769358/111456305-20d8aa80-8717-11eb-9a97-25653b0bb1ee.png)

## > Liste Occtax:

![image](https://user-images.githubusercontent.com/66769358/111457110-1539b380-8718-11eb-9289-b3b4c40bbacf.png)

**Comment by camillemonchicourt** [comment]
Le sujet est lié à TaxHub.
Il y a une vue matérialisée qui remet à plat tout Taxref sous sa forme utilisée pour l'autocomplétion.
Quand on modifie le contenu de la table ``taxonomie.taxref``, il faut rafraichir le contenu de cette VM : https://github.com/PnX-SI/TaxHub/blob/master/data/taxhubdata.sql#L33

**Comment by maximetoma** [comment]
Ah oui okay, merci beaucoup !
Ca marche, il me manquait effectivement cette dernière étape.

**Comment by Splendens** [comment]
Vu qu'il y a la possibilité de modifier Taxref via l'interface de TaxHub, cela ne vaudrait-il pas le coup de mettre un trigger pour rafraichir cette vue ? Car vu le message de Maxime, c'est ce qui est attendu intuitivement par les utilisateurs. (Ou alors ne pas permettre la modification de Taxref avec UsersHub ?)

**Comment by camillemonchicourt** [comment]
On peut modifier Taxref dans TaxHub ???

**Comment by maximetoma** [comment]
Il ne me semble pas, seul la table `taxonomie.bib_noms` est modifiable via le TaxHub enfin à ma connaissance en tout cas

**Comment by Splendens** [comment]
Oula  non , désolée @Camille ! J'étais dans l'onglet "Taxon", ce doit bien être le bib_nom qu'on modifie !
Mais les changements ne sont tout de même pas répercutés dans la sélection des taxons sans mettre à jour la vm "autocomplete" (et la vm "search_taxon" de l'atlas si je me souviens bien).

@maximetoma pour Taxref : oui la modification des noms vernaculaires peut être utile, surtout s'il est manquant. Mais on peut aussi ajouter des taxons manquants car pas encore dans le référentiel, voire ajouter des groupes (par ex: sérotule) qui ne seront peut-être jamais dans Taxref. Ce serait probablement mieux d'avoir Taxref d'un côté (auquel on ne toucherait pas), et une table "perso" de taxonomie à côté et que les appli viennent taper dans les 2 (ou une vue agrégeant les 2).

Il y avait un discussion qui parlait de ces points sur le forum de TaxHub : https://github.com/PnX-SI/TaxHub/issues/163
