### ISSUE TITLE
Problème avec le script de mise à jour de la base de données

### ISSUE THREAD

**Issue by geobrun** [PnX-SI/GeoNature#1310]
Bonjour tout le monde

Mon installation de GeoNature est actuellement en version 2.5.3. Je souhaite passer en version 2.6.2. Avant cela, j'essaye d'exécuter le premier script intermédiaire de mise à jour de la base de donnée, comme indiqué dans les notes de version : [https://github.com/PnX-SI/GeoNature/blob/master/data/migrations/2.5.5to2.6.0.sql](https://github.com/PnX-SI/GeoNature/blob/master/data/migrations/2.5.5to2.6.0.sql)

Malheureusement, je reçois l'erreur suivante : 
`ERROR:  could not create unique index "unique_name_source"`
`DETAIL:  Key (name_source)=(Historique) is duplicated.`
`SQL state: 23505`

Quelqu'un a-t-il une idée d'où peut venir le problème ?

Bonne journée

**Comment by xavyeah39** [comment]
Salut Geoffrey,
Le script ajoute un index unique sur les valeurs du champ `name_source` de la table `gn_synthese.t_sources`.
Tu dois donc avoir des sources dans cette table dont le nom est dupliqué ("Historique" notamment).
Vérifie de sorte à modifier les noms de tes sources pour qu'ils soient unique et ça devrait rouler.
++

**Comment by geobrun** [comment]
Salut Xavier,

Merci pour tes éclaircissements ! Effectivement, c'était tout simple... La personne qui avait installé GeoNature il y a deux ans avait créé trois sources avec le même nom...

++
