### ISSUE TITLE
[Métadonnées] Suppression des JDD - bug dans la liste fenêtre principale

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/GeoNature#1312]
Bonjour,

La possibilité de supprimer les JDD sans données fonctionne bien lorsqu'on est sur la fiche du JDD en question.

Sur fenêtre principale des métadonnées, dans les listes de JDD, le bouton poubelle est bien actif seulement lorsque le JDD n'a pas de donnée associée. Mais au clic il ne se passe rien à part la fenêtre qui est colorée en gris.

**Comment by RNF-SI** [comment]
Bonjour, 

De mon côté, sur la fenêtre principale des métadonnées, dans les listes de JDD, au clic sur le bouton poubelle, il me renvoie vers le synthèse. D'ailleurs quand on passe la souris sur le bouton "afficher les données dans la synthèse", il y a une superposition de plusieurs bulles d'informations : 

![image](https://user-images.githubusercontent.com/43465924/115013675-a768df00-9eb1-11eb-94bc-45f30fd9334b.png)

**Comment by camillemonchicourt** [comment]
@bouttier c'est le soucis réglé par https://github.com/PnX-SI/GeoNature/commit/c76977b029533b3b68eb037c33ea668db39054cb ?

**Comment by bouttier** [comment]
Oui c’est ça.
