### ISSUE TITLE
fonctionnalité mes lieux, erreur de droits d'écriture

### ISSUE THREAD

**Issue by Amegilla** [PnX-SI/GeoNature#1316]
sur la version 2.6.2 (mis à jour depuis version plus ancienne), lorsque je tente d'enregistrer un lieux :

error: "('User 10\" cannot \"C\" in None', 403)"
...
"Http failure response for http://xx.xx.xx.xx/geonature/api/gn_commons/place: 403 FORBIDDEN"

J'imagine qu'il faut donner des droits particulier à l'utilisateur ? Il y a une manip en base à faire pour corriger cela ?

**Comment by TheoLechemia** [comment]
Il faut que ton utilisateur ai de droit C > 0 sur GeoNature

**Comment by Amegilla** [comment]
tout simplement... merci théo.
