### ISSUE TITLE
occtax, la carte dézoome quand on place un repère.

### ISSUE THREAD

**Issue by Amegilla** [PnX-SI/GeoNature#1317]
Lorsque je pose un point sur la carte lors de la saisie d'un relevé, la carte zoome ou dézoome (selon mon niveau de zoom) pour revenir à un niveau défini. Comment régler ce comportement  ?

**Comment by Amegilla** [comment]
Le comportement est différent pour les polygones et le lignes. Dans ce cas lorsque la géométrie est terminé, la carte est zoomé et centrée sur la géométrie.

**Comment by Splendens** [comment]
Salut Romain, 
Tu as trouvé une solution ? Car j'ai le même bug que toi de zoom /  dézoom lorsqu'on ajoute un point pour un relevé sur GN 2.6.2. (bug non présent sur la 2.5.5). Cela rend la saisie très pénible ! :(

**Comment by TheoLechemia** [comment]
Je regarde dès que j'ai un peu de temps ;)

**Comment by Amegilla** [comment]
Non pas de solutions pour l'instant !! Help Théo :)

**Comment by jbrieuclp** [comment]
Pour moi c'est cette ligne la fautive : 
https://github.com/PnX-SI/GeoNature/blob/550e860ad59463afc7b90f7c9a38a39b66a669d2/frontend/src/app/GN2CommonModule/map/marker/marker.component.ts#L57

Y avait eu des repasse sur ce component avec l'utilisation des observable. Pourquoi est-ce qu'elle a été conservée ? Elle peut probablement dégager, perso aussi je trouve ce dézoome très pénible.

**Comment by Amegilla** [comment]
Merci, cela semble résoudre le comportement.

**Comment by TheoLechemia** [comment]
Fixé dans la branche develop
