### ISSUE TITLE
[Mes lieux] - Le traitement ne se fait pas en base

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1319]
Coté BDD dans occtax (pr_occtax.t_releves_occtax) et dans la synthèse, un champs "place_name"existe pour stocker à priori le nom du lieu de l'observation. 

Dans la pratique, on peut effectivement utiliser la fonctionnalité "mes lieux" qui récupère bien la géométrie, mais le champs place_name n'est jamais renseigné, il reste à NULL dans occtax.

**Comment by camillemonchicourt** [comment]
Le champs texte "lieu" et la fonctionnalité "Mes lieux" n'ont rien à voir, ils sont indépendants.

**Comment by DonovanMaillard** [comment]
OK  alors je n'ai rien pigé ^^  le frontend permet de renseigner ce champs via un paramètre ?

**Comment by camillemonchicourt** [comment]
Oui les termes portent à confusion, c'est pas idéal.
Le champs "lieu" est un champs texte à saisir, c'est tout.
