### ISSUE TITLE
Mise en cache des stats de la page d'accueil

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature#1320]
Les stats affichées sur la page d'accueil de GeoNature peuvent être assez longue à s’exécuter si un grand nombre d'observations (+ de 9 millions) sont présentes dans la table `synthese`.

Pour éviter de lancer systématiquement ces requêtes à chaque affichage de la page d'accueil, il serait intéressant  de pouvoir stocker le résultat dans le cache local du navigateur (`local storage`). Les nombres affichées étant dépendant des permissions de l'utilisateurs, un système de cache côté serveur a été écarté.

Un paramètre de configuration `[FRONTEND] STAT_BLOC_TTL` permettra d'indiquer la fréquence de renouvellement de ce cache en seconde (par défaut `86400s` soit 1 jour).

Sur l'interface le texte `Dernière mise à jour <date> à <heure>` sera mentionné sous l'affichage des nombres pour indiquer à l'utilisateur la date à laquelle les valeurs ont été stockées et donc calculées. Ex. :
![Screenshot_20210324_225543](https://user-images.githubusercontent.com/51449363/112388849-12305b80-8cf4-11eb-96b3-1f29a86565fd.png)

**Comment by lpofredc** [comment]
Le cache est une bonne idée, mais cela me parait toujours problématique pour d'importantes quantités de données, notamment en raison des timeout. C'est en tout cas notre problème sur notre instance.

Il serait peut-être plus intéressant de gérer le cache côté serveur, dans le backend. cf. https://sysadmins.co.za/how-to-cache-data-with-python-flask/, c'est ainsi mutualisé pour toutes les connexions et soulagera d'autant la bdd. la durée de conservation du cache pourrait être configurée avec une valeur par défaut. 

Cette méthode pourrait être généralisée à d'autres données "statiques" de l'API.

**Comment by jpm-cbna** [comment]
Le choix du cache côté client a été fait ici car les données sont spécifique à chaque utilisateur. Dans ce cas précis, mettre les données en cache côté serveur, nous obligerait à stocker du cache pour chaque utilisateur. De plus, je ne pense pas qu'un simple décorateur `@cached(cache)` suffise car il faudrait préciser des infos provenant du cookie pour bien distinguer chaque appel à mettre en cache. Ceci dit c'est une excellente solution pour des web services dont les appels seraient commun à tous les utilisateurs avec un contenu relativement statique.

Enfin, je pense que même avec un cache côté serveur le problème du `timeout` va persister car si la base de données met plus de temps que le `timeout` pour répondre, le cache ne sera pas créé...

Juste pour savoir, le problème de timeout concerne combien d'observations dans la table `synthese` ? Le `timeout` en question est de quelle durée ?

**Comment by DonovanMaillard** [comment]
Et pour éviter ces soucis de timeout et temps de réponse de la bdd, avoir une vm qui calcule les stats dispo pour chaque rôle chaque nuit ca ne serait pas une option parmi d'autres?

**Comment by jpm-cbna** [comment]
@DonovanMaillard Dans ce cas là, une VM cela me semble vachement plus compliqué et lourd à maintenir que le cache dans le local storage.
Pour info, vous pouvez tester la fonctionnalité disponible dans cette pull-request https://github.com/PnX-SI/GeoNature/pull/1321. J'avais besoin de déployer rapidement ce mécanisme avant la mise en production du SINP PACA. Donc, je pourrais vous faire un retour d'expérience dessus. Mais en l'étant sur mon poste local, l'expérience utilisateur est bien meilleure !

**Comment by DonovanMaillard** [comment]
Ca marche, c'était simplement pour avoir cette option dans l'équation :)

**Comment by jbrieuclp** [comment]
Sinon autre proposition :
Changer la manière de récupération de ces stats d'une 1 route à 4 routes.
Actuellement il y a 1 routes qui lance 2 requêtes distinctes, 1 pour récupérer le nombre de JDD et 1 pour récupérer en même temps le nombre de données, le nombre d'observateur et le nombre de taxons.
Si chacun de ces nombres était accessibles par une route spécialisée, ils pourraient se charger tranquillement en parallèle les uns des autres sans attendre le résultat de la requête la plus longue.

Et pour la récupération des stats du nombre d'observateurs (celle qui fait ça `SELECT count(distinct(gn_synthese.synthese.observers)) AS count_3 FROM gn_synthese.synthese`), chez moi elle met 6sec pour 1.5 million de données, avec la mise en place d'un index sur ce champ, 0.7s...
Y a peut-être pas forcément besoin de partir dans la mise en place de cache, essaie de ton côté avec l'index dans un premier temps.

**Comment by jpm-cbna** [comment]
Alors, j'ai aussi fait des tests à la demande @TheoLechemia. J'ai modifié le web service `/synthese/general_stats` pour qu'il me renvoie seulement les valeurs nécessaires et je l'interroge avec Postman. Apparemment, c'est bien le calcul du nombre d'observateurs suivi de celui du nombre d'espèces qui pose problème. Ce n'est pas surprenant car les deux utilisent un `COUNT(DISTINCT ...)`.

@jbrieuclp Oui, effectivement, j'avais zappé mais de mon côté aussi j'ai mis un index sur le champ `observers`. C'est mieux mais avec 9,3 millions de données cela reste long...

Ci-dessous le détail des résultats avec l'index sur le champ `observers` :

En retirant seulement les observateurs :
```json
{
    "nb_data": 9309784,
    "nb_species": 22469,
    "nb_dataset": 877
}
```
Cela prend **~4,6s** (temps affiché par Postman).

Avec le résultat suivant sans observateurs ni JDD : 
```json
{
    "nb_data": 9309784,
    "nb_species": 22469
}
```
Cela prend **~3,51s**.

Avec les observateurs mais pas les JDD :
```json
{
    "nb_data": 9309784,
    "nb_species": 22469,
    "nb_observers": 31790
}
```
Cela prend **~8,9s**.

Seulement les JDD :
```json
{
    "nb_dataset": 877
}
```
Cela prend **88ms**.

Seulement les observations :
```json
{
    "nb_data": 9309784
}
```
Cela prend **747ms**.

Seulement les espèces :
```json
{
    "nb_species": 22469
}
```
Cela prend **3,73s**.

Seulement les observateurs :
```json
{
    "nb_observers": 31790
}
```
Cela prend **7,13s**.

**Comment by jbrieuclp** [comment]
Tu as un WHERE dans la requête ? Ou c'est juste `SELECT COUNT(DISTINCT(gn_synthese.synthese.observers)) FROM gn_synthese.synthese` ?

**Comment by jpm-cbna** [comment]
Alors la requête lancé par le web service ne contient pas de `WHERE`.

J'ai testé les 2 variations de la requête que tu proposes:
- `COUNT(DISTINCT(...)) `: ~11s
- `COUNT(*)` : ~5s

Actuellement le web service, exécute la requête suivante:
```sql
SELECT 
	COUNT(s.id_synthese) AS count_1, 
	COUNT(DISTINCT s.observers) AS count_2, 
	COUNT(DISTINCT s.cd_nom) AS count_3 
FROM gn_synthese.synthese AS s ;
```
Elle s'exécute en ~11s. 

Je peux tenter de séparer la requête en 3 distinctes et utiliser la technique du `COUNT(*)` avec la sous-requête et voir si le web service répond plus vite. Ceci dit comme tu le propose appeler ce web service de manière concurrente depuis le frontend pourrait aussi améliorer le résultat. Toutefois, cela ferait 4 requêtes à lancer sachant que les navigateurs en supporte généralement 6 concurrentes maximum vers le même domaine...

**Comment by jbrieuclp** [comment]
Sur le chargement d'un formulaire il y'a autant d'appel vers l'API qu'il ya de liste déroulante à charger. Ce qui est souvent bien plus que 6. Tu vas avoir 2 appels d'api qui vont se torcher en 0.2sec et 2 peut-être un peu plus long, mais qui seront plus léger que le gros actuel.

**Comment by lpofredc** [comment]
l m k l.     m

**Comment by lpofredc** [comment]
l m k l.     m

**Comment by lpofredc** [comment]
l m k l.     m

**Comment by lpofredc** [comment]
l m k l.     m

**Comment by lpofredc** [comment]
l m k l.     m
