### ISSUE TITLE
Accès grand public GeoNature - Synthèse, Dashboard, Métadonnées 

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/GeoNature#1323]
- [x] Créer un bouton 'Accès grand public' sur la page d'identification 
- [x] Création d'un user lecteur avec accès lecture sur les modules choisis (synthèse, dashboard, métadonnées) 
- [x] Gestion de l'authentification

**Comment by Adrien-Pajot** [comment]
Voir https://github.com/MathieuLagarde/GeoNature/blob/geofit/oeb/frontend/src/app/components/auth/auth.service.ts

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.7.0, mais la doc dédiée (https://github.com/Adrien-Pajot/GeoNature/blob/27b592944d795e81fd528cb92217df56e5f7d6c5/docs/user-lecteur.md) a disparue.
Ou alors elle a été intégrée dans la doc générale ?

**Comment by camillemonchicourt** [comment]
Doc inclue dans la doc admin : https://github.com/PnX-SI/GeoNature/commit/b87225556367aff7f958ce4efc9d28bce388b434
