### ISSUE TITLE
[OCCTAX] Export des médias

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#1326]
Une PR vient de nous proposer un export des médias dans Occtax.
Je trouve l'idée interessante, mais je me pose la question de son positionnement dans le module.
Dans les paramètres de format d'export des médias, un items "médias" a été ajouté, ce qui ajoute un bouton "format médias" à côté des boutons "format CSV, format GeoJson". Au delà de la sémantique, ce qui est un peu trompeur car au même niveau un export d'observation et un export de média (tout les médias correspondant à la recherche sont téléchargés et zippés).
J'ai aussi de serieux doute sur la monté en charge de cette fonctionnalité. Cela fonctionne sur un nombre faible de médias, mais lancer une requête qui contient 1000 photos va rapidement faire tomber le serveur, et la connexion internet de la personne qui télécharge les photos !!
Est-ce que la même fonctionnalité au niveau de la fiche info ne sera pas plus .. raisonnable ?

**Comment by TheoLechemia** [comment]
En fait je me demande l'utilité de pouvoir télécharger les médias si ceux ci ne sont pas rattaché à l'observation, ni à l'espèce ?

**Comment by camillemonchicourt** [comment]
En effet si on ajoute un export "medias" il ne faut pas l'ajouter comme format mais bien comme un autre type d'export.

Il faut pouvoir le désactiver car sa pertinence est discutable.

Je privilégierai aussi l'export des photos de tout un relevé sur la fiche d'un relevé.

Il faut aussi vérifier ce qu'il se passe si une observation a des médias qui ne sont pas des photos. Ou des photos sous forme d'URL distante.
Si cela ne concerne que les médias de type photo alors il faut le renommer en "photos". Si ça prend tous les médias peu importe leur type et les met dans un zip, alors c'est mieux et bien nommé "médias"

**Comment by camillemonchicourt** [comment]
Un paramètre ``ADD_MEDIA_IN_EXPORT`` a été ajouté dans la conf d'Occtax (à ``false`` par défaut).
Si il est passé à ``true``, cela ajoute 3 colonnes dans les exports (nom, description, URL)
