### ISSUE TITLE
Problème commande geonature dev_back

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#1330]
J'ai essayé de lancer le backend de geonature  sous la branche develop avec la commande shell `geonature dev_back` et je tombe sur cette erreur

ImportError: cannot import name 'get_app_for_cmd'

la fonction n'est plus présente dans le fichier `backend/geonature/utils/command.py`
mais appellée dans le fichier `/home/joel/info/dev/GeoNature/backend/geonature/utils/gn_module_import.py`

**Comment by TheoLechemia** [comment]
Désolé, c'est de ma faute.
C'est corrigé
