### ISSUE TITLE
[OCCATX] saisie du statut de l'observation

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/GeoNature#1333]
Nous avons constaté une différence de traitement dans la saisie des observations  entre l'application mobile et la saisie dans geonature.
Nous avions saisie 2 observations sur des vipères. Une était visible dans Atlas et pas l'autre. Les 2 étant trouvables dans l'application geonature.
Une était saisie dans l'application sur le mobile l'autre dans l'application geonature. Celle saisie sur le téléphone n'est pas visible dans Atlas.
En fait la donnée nomenclature_observation_status de la vue syntheseff est à null. 
La création de syntheseeff fait un left join sur cette donnée ce qui suppose qu'elle peut être nulle or on teste ensuite que cd_nomenclature = "Pr" ou "NSP" ce qui ne permet pas de remonter la ligne de l'observation.
(J'ai constaté d'ailleurs que dans la mise à jour de 2.4.1 à 2.5.5 cette vue n'était pas modifiée or le code a changé pour seulement cd_nomenclature='Pr' seulement ==> seul les observations noté présentes sont vues)

J'avoue que je ne comprends pas ce changement et pourquoi la valeur est nulle dans le cas de la saisie sur le téléphone.

Pouvez-vous faire une correction ?

(De notre côté j'ai fait une correction pour inclure même les lignes avec la donnée vide dans la vue pour qu'Atlas affiche ces observations)
Est ce normal ? doit-on obligatoirement avoir une valeur 'Pr' en saisie mais alors que veulent dire les autres informations. 
Camille si tu peux m'éclairer sur ce sujet.
D'avance merci,
Christian Bièche
Cistude Nature
(on avait 179 observations qui était passées à la trappe en base du coup ....)

**Comment by TheoLechemia** [comment]
Bonjour,

Pourquoi la nomenclature était renseigné à null dans l'appli mobile, elle n'a pas été rempli ? 
Est-ce que vous avez renseigné une valeur par cette nomenclature ?
Pour la vue de l'atlas, elle est fournie comme cela pour ne pas mettre les données d'absence, mais libre à chacun de se l'adapter

**Comment by camillemonchicourt** [comment]
OK cela renvoie à la question de la valeur par défaut du champs "Statut d'observation".
Je ne sais plus si elle est saisissable sur Occtax-mobile.
Dans notre cas, on ne permet pas non plus de la saisir dans Occtax-web car on considère que si on fait une observation dans Occtax c'est pour noter une présence.
Donc on pousse par défaut la valeur "Pr" sans que l'utilisateur puisse intervenir dessus.

Mais c'est vrai que ce n'est peut-être pas le cas quand on saisit depuis Occtax-mobile sans renseigner ce champs, il faudrait vérifier.

Au niveau de l'atlas, en effet on filtre sur ce champs pour ne pas prendre les éventuelles données d'absence qui pourraient être présentes dans la Synthèse.

**Comment by christianbieche** [comment]
D'accord merci pour ses informations. Effectivement on ne peut pas sur la version Web laisser une valeur nulle puisque les informations sont saisies via Liste et alors on peut saisir NSP.
Je ne sais pas vous répondre sur la partie téléphone, je constate juste l'effet de bord.
Bon je comprends la mise en place de la requête puisqu'effectivement cela semble logique de n'afficher que les observations notées "Pr".
Je vais donc garder ma mise en jour qui sera spécifique dans notre cas.
