### ISSUE TITLE
Problème de sécurisation (HTTPS)

### ISSUE THREAD

**Issue by geobrun** [PnX-SI/GeoNature#1336]
Bonjour,

Je poste mon message ici même s'il ne concerne pas directement GeoNature mais en réalité UsersHub, TaxHub et GeoNature-atlas. Cela me semble plus logique car je me suis inspiré de la documentation de GeoNature pour le passage de nos sites en HTTPS. De plus, je n'ai rien trouvé de concluant dans les issues des autres dépôts. J'utilise les dernières versions publiées de UsersHub, TaxHub et GeoNature-atlas.

Grâce à la documentation de GeoNature, j'ai réussi à faire certifier mon URL ``geonature.pnr-millevaches.fr`` via Let's Encrypt. Pour cela, j'ai utilisé la ligne de code suivante : 
``sudo certbot certonly --webroot --webroot-path /home/geonatureadmin/geonature/frontend/dist --domain geonature.pnr-millevaches.fr --email *********@pnr-millevaches.fr``
A noter que cela ne fonctionnait pas lorsque je laissais le ``--webroot-path`` avec ``/var/www/html``

Concernant UsersHub, TaxHub et GeoNature-atlas, cette même ligne de commande ne fonctionne pas chez moi. J'ai testé ``--webroot-path`` avec ``/var/www/html`` et ``/home/geonatureadmin/usershub`` pour UsersHub, cela ne fonctionne pas.

A noter que mon fichier ``/etc/apache2/sites-available/geonature.conf`` contient une mention ``DocumentRoot`` avec comme paramètre ``/home/geonatureadmin/geonature/frontend/dist``, ce qui n'est pas le cas dans les fichiers ``usershub.conf``, ``taxhub.conf`` et ``atlas.conf``. Dans mon fichier ``000-default.conf``, ``DocumentRoot`` a bien toujours comme paramètre ``/var/www/html``

Quelqu'un a-t-il une piste à me proposer ? Il doit y avoir quelque chose que je n'ai pas capté je pense...

**Comment by bouttier** [comment]
Bonjour,

Le plus simple est à priori d’utiliser la commande `certbot certonly --authenticator apache --installer none`. Il faut avoir préalablement installé le paquet `python3-certbot-apache`. Le plugin d’authentification apache s’occupe de rajouter les alias approprié dans tous les vhosts durant la génération du certificat pour être sûr que le webroot fonctionne.
Il est également possible d’utiliser la partie installer du plugin (`--installer apache` ou simplement `--apache` sans spécifier ni authenticator, ni installer) qui crée automatiquement un vhost identique avec la conf SSL activé.

**Comment by camillemonchicourt** [comment]
En effet la documentation de GeoNature sur le HTTPS est ancienne et complexe, alors que désormais avec ``certbot`` on peut mettre en place le HTTPS en 3 lignes, incluant même le renouvellement du certificat.

La méthode avec NGINX (à adapter à Apache) : 

```
## Installer Certbot
sudo apt install certbot
sudo apt install python3-certbot-nginx

## Lancer la commande permettant de mettre en place le certificat sur ce domaine et suivre les instructions
sudo certbot --nginx

## C'est fini !
```

**Comment by jpm-cbna** [comment]
Concernant Nginx, vous trouverez aussi de la documentation concernant la mise en place du SSL sur ces pages:
 - [pour GeoNature](https://wiki-sinp.cbn-alpin.fr/serveurs/installation/web-srv/geonature-nginx)
 - [pour Taxhub](https://wiki-sinp.cbn-alpin.fr/serveurs/installation/web-srv/geonature-taxhub-nginx)
 - [pour UsersHub](https://wiki-sinp.cbn-alpin.fr/serveurs/installation/web-srv/geonature-usershub-nginx)
 - [pour GeoNature-Atlas](https://wiki-sinp.cbn-alpin.fr/serveurs/installation/web-srv/geonature-atlas-nginx)

Il y a des exemples de commande `certbot` incluant des alias pour le nom de domaine. Dans le cas d'Apache, il faut juste remplacer `--nginx` par l'équivalant pour Apache.

**Comment by geobrun** [comment]
Ok, merci pour les informations, je vais regarder ça de plus près et vous ferai un retour le plus rapidement possible.

**Comment by geobrun** [comment]
Ok, ça marche vraiment au poil !

Petit récapitulatif pour les suivants (notamment pour les utilisateurs de services OVH). Il faut d'abord créer des enregistrements de type A dans votre zone DNS d'OVH en indiquant l'adresse IP du serveur. Vous devez en créer à la fois avec et sans "www" : par exemple, il faut une entrée du type "geonature.structure.fr" et une autre du type "www.geonature.structure.fr". Faire pareil pour UsersHub et Taxhub.

Lancer les commandes indiquées dans les précédents commentaires (en remplaçant "nginx" par "apache" si vous utilisez un serveur Apache (choix par défaut il me semble dans GeoNature) : 
```
## Installer Certbot
sudo apt install certbot
sudo apt install python3-certbot-nginx

## Lancer la commande permettant de mettre en place le certificat sur ce domaine et suivre les instructions
sudo certbot --nginx

## C'est fini !
```
Au niveau des instructions, c'est très simple, on vous demande les choses suivantes  : 
- indiquer les noms de domaines concernées par la sécurisation HTTPS (en général, laisser vide sauf besoin spécifique)
- éventuellement, accepter ou non de remplacer des certificats déjà installés
- activer ou nom une redirection automatique des requêtes HTTP vers HTTPS

Encore merci pour votre aide ! :)

**Comment by lpofredc** [comment]
Ne pas oublier de renouveler les certificats via une tache cron (de mémoire, ils périment tous les 3 mois). Par exemple ici avec une tâche hebdomadaire, certbot gère le reste automatiquement.

```cron
0 1 * * 1 certbot renew
```

**Comment by geobrun** [comment]
Ok, merci pour la précision, elle est effectivement essentielle !

**Comment by bouttier** [comment]
Le paquet debian `certbot` installe déjà la tâche cron ! :-)
Il est recommandé de ne pas créer de cron à heure fixe mais d’ajouter un temps aléatoire, afin d’éviter de surcharger les serveurs de letsencrypt avec les demande de renouvellement du monde entier à la même seconde, mais la tâche installée par le paquet `certbot` gère déjà cela pour nous également.

**Comment by geobrun** [comment]
Pas de bol, j'ai hérité d'une instance GeoNature qui tourne sous Ubuntu : visiblement, la tâche Cron n'avait pas été créée automatiquement... :(

**Comment by camillemonchicourt** [comment]
Oui Certbot s'en charge tout seul, c'est vraiment excellent et beaucoup plus simple que la documentation actuellement indiquée dans la doc de GeoNature :-)

**Comment by maximetoma** [comment]
> Le paquet debian `certbot` installe déjà la tâche cron ! :-) Il est recommandé de ne pas créer de cron à heure fixe mais d’ajouter un temps aléatoire, afin d’éviter de surcharger les serveurs de letsencrypt avec les demande de renouvellement du monde entier à la même seconde, mais la tâche installée par le paquet `certbot` gère déjà cela pour nous également.

Salut, j'ai eu à `renew` le certificat récemment et je me suis aperçu que je n'avais pas eu la tache cron de créé automatiquement, est-ce que tu aurais un exemple @bouttier ? :) Que je puisse la mettre manuellement dans mon fichier ^^

**Comment by camillemonchicourt** [comment]
Pour nous en mettant en place le cron initial avec simplement ``sudo certbot --nginx``, le renouvellement du certificat est automatique sans que l'on ait eu à mettre en place un cron.

**Comment by maximetoma** [comment]
Ah okay... il ne me l'a pas mis en refaisant `sudo certbot`, mais vu que j'ai refais cette commande sans le `--nginx` ça vient peut être de ça ?
Je re-testerai dans 3 mois :)

**Comment by camillemonchicourt** [comment]
Si j'ai bien compris, désormais et sur la plupart des OS, quand on installe Certbot, un cron de renouvellement automatique des certificats est mis en place.
Si ce n'est pas le cas sur votre serveur, à vous de mettre en place ce cron : https://absolutecommerce.co.uk/blog/auto-renew-letsencrypt-nginx-certbot

**Comment by maximetoma** [comment]
Okay merci beaucoup Camille, j'ai fait les étapes décrites dans le lien que tu as partagé et j'ai enfin le fichier cron à l'endroit indiqué ! :)
