### ISSUE TITLE
Pouvoir filtrer sur les obs avec média/photo

### ISSUE THREAD

**Issue by Amegilla** [PnX-SI/GeoNature#1338]
Ce serait utile de pouvoir retrouver facilement les données avec un média associé et filtrer par type de média.
Dans la synthèse et surtout dans le module validation.
Et peut même un petit picto sur les tableaux pour voir directement les obs avec un media.
Vous en pensez quoi ?

**Comment by camillemonchicourt** [comment]
Voir la PR sur le sujet : https://github.com/PnX-SI/GeoNature/pull/1246

**Comment by joelclems** [comment]
travail initié dans la branche synthese_filtre_medias

**Comment by camillemonchicourt** [comment]
Et les tickets liés au sujet : https://github.com/PnX-SI/GeoNature/issues/1179 ainsi que https://github.com/PnX-SI/GeoNature/issues/1180
