### ISSUE TITLE
supervisor → systemd

### ISSUE THREAD

**Issue by bouttier** [PnX-SI/GeoNature#1339]
GeoNature a pour plateforme cible officiellement supportée Debian 10, qui a Systemd pour système d’init.
L’utilisation d’un outil comme Supervisor n’a plus lieu d’être, toutes les fonctionnalités requises étant présente de base avec le système.
De plus, cela évite de devoir prendre en main un nouvel outil spécifique à GeoNature au lieu des outils ordinaires du système.
Ci-dessous un service file Systemd. Il est possible de modifier la config de Gunicorn en définissant d’autres variables d’environnement dans `/home/geonatureadmin/geonature/environ`.

TODO :

- [ ] Modification du processus d’installation
- [ ] Migration automatique de supervisor vers systemd ?
- [ ] Documentation

```
[Unit]
Description=GeoNature
After=network.target

[Service]
Type=simple
User=geonatureadmin
Group=geonatureadmin
WorkingDirectory=/home/geonatureadmin/geonature/
Environment=GUNICORN_PROC_NAME=geonature2
Environment=GUNICORN_NUM_WORKERS=4
Environment=GUNICORN_HOST=127.0.0.1
Environment=GUNICORN_PORT=8000
Environment=GUNICORN_TIMEOUT=30
EnvironmentFile=-/home/geonatureadmin/geonature/environ
ExecStart=/home/geonatureadmin/geonature/backend/venv/bin/gunicorn geonature.wsgi:app \
		--name "${GUNICORN_PROC_NAME}" --workers "${GUNICORN_NUM_WORKERS}" \
		--bind "${GUNICORN_HOST}:${GUNICORN_PORT}" --timeout="${GUNICORN_TIMEOUT}"
ExecReload=/bin/kill -s HUP $MAINPID
TimeoutStartSec=10
TimeoutStopSec=5
PrivateTmp = true
StandardOutput=append:/var/log/geonature.log
StandardError=inherit

[Install]
WantedBy=multi-user.target

```

**Comment by jbdesbas** [comment]
Salut,

En me renseignant un peu sur les différences notables entre supervisor et systemd, j'ai vu que supervisor avait une[ interface web intégrée](https://codesamplez.com/management/supervisord-web-interface-and-plugin).
![image](https://user-images.githubusercontent.com/6163107/114710404-f7b73400-9d2d-11eb-8635-86d10b8d2113.png)

Ca reste un gadget, et pas sûr que ca fasse vraiment pencher la balance par rapport à un outil intégré au système, mais c'est toujours appréciable.

**Comment by bouttier** [comment]
Systemd aussi :-)

https://cockpit-project.org/

**Comment by camillemonchicourt** [comment]
Fait dans la version 2.8.0 (2021-10-18)
