### ISSUE TITLE
Not Found sur le dossier /static

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#1340]
Salut,
J'ai beau chercher un peu partout je ne trouve pas l'origine du problème. L'API retourne du 404 si j'essaie d'accéder à une ressource présente dans le dossier `/static`. C'est tant pour le fichier bootstrap.css utilisé dans la page d'amin du CRUVED que l'accès aux différents médias.
Comme j'ai une 404, je ne pense pas que ce soit une mauvaise config d'apache. J'ai ce cas en prod comme en dev. J'ai l'impression que ça bloque au niveau de Flask mais où ? `/backend/geonature/app.py` ? `/backend/wsgi.py` ?
Quelqu'un aurait une piste ou mieux une solution ? 
Edit : je suis en 2.6.2

**Comment by TheoLechemia** [comment]
Tu as regardé quelles URL exactes sont appelées depuis la console de ton navigateur ?

**Comment by jbrieuclp** [comment]
"/geonature/api/static/node_modules/bootstrap/dist/css/bootstrap.css" en prod
"/static/node_modules/bootstrap/dist/css/bootstrap.css" en dev

**Comment by TheoLechemia** [comment]
Et en faisant un clic droit -> ouvrir dans un nouvel onglet sur la requête ?

**Comment by jbrieuclp** [comment]
404, je suis passé par le code HTML pour justement checker les URL donc nouvel onglet de compagnie.

**Comment by bouttier** [comment]
Tu peux montrer ta config apache ? Je ne vois pas particulièrement de raison à ce qu’une 404 exclue apache du problème.

**Comment by jbrieuclp** [comment]
sur la branche develop (donc sans aucune modif perso) c'est pareil.
404 pour `127.0.0.1:8000/static[...]` et le 404 est bien chopé dans la console du debugger de Flask en mode dev, donc ca rentre bien dans l'API.

La config Apache n'a pas changée depuis le début :
```
Alias /geonature /home/geonature/geonature/frontend/dist

<Directory /home/geonature/geonature/frontend/dist>
    Require all granted
</Directory>
<Location /geonature/api>
    ProxyPass http://127.0.0.1:8000
    ProxyPassReverse  http://127.0.0.1:8000
</Location>
```

**Comment by TheoLechemia** [comment]
> 404, je suis passé par le code HTML pour justement checker les URL donc nouvel onglet de compagnie.

C'est l'URL absolue appelé par la navigateur qui m'interesse. Il appelle quoi ?

**Comment by jbrieuclp** [comment]
http://outils.gretia.org/geonature/api/static/node_modules/bootstrap/dist/css/bootstrap.css

**Comment by jbrieuclp** [comment]
Bon en dev si je modifie cette ligne
https://github.com/PnX-SI/GeoNature/blob/a89266a4b82bde9bf0dfae6a56edd4764caf4a6a/backend/geonature/app.py#L46
en 
`app = Flask(__name__, static_folder="../static")`
ça passe...

Pour le moment je me retiens de faire la modif en prod pour voir le résultat...

**Comment by bouttier** [comment]
Oups, effectivement Amendine avait déjà identifié ce soucis ! C’est moi qui l’ai introduit en déplaçant l’ancien ficher server.py dans le package geonature ! Désolé, je pensais que ça avait été résolu. En pratique il serait certainement plus propre de déplacer le dossier static dans le package mais les conséquences sont assez importantes alors pour l’heure on se contentera de cette solution.

**Comment by jbrieuclp** [comment]
Ce n'était pas le cas sur demo.geonature.fr, mais je n'avais pas fait attention qu'elle était sous la 2.5.6.
Je viens de tester une migration sur cette version et ça remarche. 
Ok donc le bug est plié ! 
Et super, je viens de me rendre compte que je suis en 2.6.3 en prod... J'ai du y avoir une couille de merge avec develop à un moment là :-/

**Comment by bouttier** [comment]
Ceci dit il serait quand même bien de servir les fichiers statics directement par apache !
Il faudrait certainement une conf de ce genre :
```
Alias /api/static /home/geonature/geonature/backend/static
```
ainsi que la conf Directory
Mais il faudrait que je me renseigne un peu sur les bonnes pratiques pour la gestion des fichiers statics avec flask, je connais pas encore très bien.

**Comment by camillemonchicourt** [comment]
Oui c'est ce qu'on fait dans le module d'export sinon les téléchargements de gros fichiers étaient en timeout : https://github.com/PnX-SI/gn_module_export/issues/73

**Comment by jbrieuclp** [comment]
Du coup même topo pour les templates (entre autres pour ceux des PDF des métadonnées), il faut ajouter le paramètre `template_folder` à Flask de `app.py`
`app = Flask(__name__, static_folder="../static", template_folder="../templates")`

Pour l'histoire de la config apache ça n'a pas fonctionné en suivant la config proposée du PnX-SI/gn_module_export#73 probablement parce que `/static` est sur un sous-chemin d'`/api `(`/api/static`) et non un chemin indépendant. 
Mais en vrai il y aurait surement moyen de faire le taf avec apache à coup de `RewriteCond` et `RewriteRule` et peut-être `RedirectMatch` mais pas le temps de m'y atteler.

**Comment by camillemonchicourt** [comment]
Un alias Apache de tout le dossier ``/static`` comme proposé par @bouttier serait certainement un solution plus simple et efficace de ce que j'en comprends.
C'est ce qu'on fait dans le module Export pour un sous-dossier du répertoire ``/static`` pour le servir avec Apache.
Mais on pourrait généraliser à tout le dossier.

**Comment by jbrieuclp** [comment]
Oui, les exports sont dans un sous dossier de static mais la route pour accéder aux exports est indépendante, c'est `/dataexport/`. Alors que celle pour accéder aux médias est une route enfant de `/api`, c'est`/api/static`
La route /api est déjà un alias
