### ISSUE TITLE
Plus aucun module : unauthorized

### ISSUE THREAD

**Issue by RNF-SI** [PnX-SI/GeoNature#1344]
J'ai bêtement mis dans geonature_config.toml 
`ID_APPLICATION_GEONATURE = 1`
Avant de comprendre que le 1 était pour UsersHub et le 2 pour TaxHub (d'où le 3 pour GeoNature dans l'exemple...)

Du coup sur mon GeoNature je n'ai plus accès à rien, il me met une erreur 401, unauthorized, donc je pense que c'est lié :
![image](https://user-images.githubusercontent.com/43465924/114853662-50490880-9de4-11eb-9d00-a26f582866e8.png)

J'ai bien essayé de remettre 
`ID_APPLICATION_GEONATURE = 3`
voir de le supprimer, puis de relancer update_configuration, mais rien à faire je ne récupère rien sur GeoNature... 

Merci pour votre aide !

**Comment by RNF-SI** [comment]
Après de multiples essais je suis maintenant persuadé que le problème est dans la base de données. Mais dans quelle table trouver l'erreur ?

**Comment by camillemonchicourt** [comment]
Les erreurs sont toujours les mêmes ?
GeoNature a bien 3 comme ID_application dans UsersHub ?
Ton utilisateur a bien les droits de lecture sur l'application GeoNature dans UsersHub ?

**Comment by jbrieuclp** [comment]
Peut-être `utilisateurs.t_applications` ou `gn_commons.t_modules` ?

**Comment by RNF-SI** [comment]
Oui je tourne en boucle depuis ce matin... mon utilisateur fait partir de grp_admin et a donc tous les droits (donc 1 sur GeoNature) et dans UsersHub chaque appli a bien le bon id...
Dans utilisateurs.t_applications rien d'anormal semble t'il.
Dans gn_commons.t_modules, peut être GEONATURE active_frontend = false n'est il pas normal ?

**Comment by RNF-SI** [comment]
Bon, je ne sais pas ce qui s'est passé, je me suis déco et reco, et ça remarche... un grand mystère...

**Comment by camillemonchicourt** [comment]
OK c'était surement ton cache de navigateur ! :-)
