### ISSUE TITLE
problème inscription

### ISSUE THREAD

**Issue by RNF-SI** [PnX-SI/GeoNature#1347]
Bonjour,

Sur le formulaire d'inscription, lorsqu'il est validé, un petit bandeau rouge d'erreur apparait, sans contenu. 
L'inscription est pourtant bien effective, car la demande apparait dans UsersHub sous "demande de compte".
Mais aucun mail n'arrive dans ma boîte mail pourtant désignée dans VALIDATOR_EMAIL. 
Je pense donc qu'il s'agit d'un problème de FLASK-MAIL. 

Voici ma conf : 
```
[MAIL_CONFIG]
    MAIL_SERVER = 'smtp.gmail.com'
    MAIL_PORT = 465
    MAIL_USE_TLS = false
    MAIL_USE_SSL = true
    MAIL_USERNAME = 'equipe.rnf@gmail.com'
    MAIL_PASSWORD = '*********'
    MAIL_ASCII_ATTACHMENTS = false

[ACCOUNT_MANAGEMENT]
    ENABLE_SIGN_UP = true
    AUTO_ACCOUNT_CREATION = false
    AUTO_DATASET_CREATION = false
    VALIDATOR_EMAIL = 'zacharie.moulin-rnf@espaces-naturels.org'
    ENABLE_USER_MANAGEMENT = true
```
J'utilise un compte gmail parce que je suis sûr que ça marche, c'est la même chose que j'utilise dans une app perso sous FLASK-MAIL, en local cependant.

**Comment by camillemonchicourt** [comment]
Tu as surement une erreur qui remonte dans la console du navigateur au moment où le toaster avec l'erreur s'affiche ?

**Comment by jpm-cbna** [comment]
La configuration avec le serveur SMTP de Gmail n'est pas évidente. Le toater rouge sans message indique souvent un problème dans l'envoie de l'email. Vous trouverez des ressources sur le sujet dans la doc de Google https://support.google.com/a/answer/2956491 et éventuellement ici https://wiki-sinp.cbn-alpin.fr/serveurs/installation/postfix#configuration_smtp_a_utiliser

**Comment by RNF-SI** [comment]
Ok merci, je pensais que ça serait plus simple avec Gmail mais finalement ça marche bien avec mon adresse pro.
