### ISSUE TITLE
Problème utilisateur/organisme dans les JDD

### ISSUE THREAD

**Issue by geobrun** [PnX-SI/GeoNature#1352]
Bonjour,

En faisant du ménage dans la configuration des droits sur les jeux de données (suite à des problèmes rencontrés par nos agents), je rencontre un problème qui semble similaire à celui-ci: [1274](https://github.com/PnX-SI/GeoNature/issues/1274
).

J'ai testé avec un CRUVED très simple pour GeoNature (et donc répercuté dans Occtax) : C, R, U et D sont sur 1. Dans nos JDD, seul notre organisme apparaît comme contact principal. Nos agents sont bien rattachés à notre organisme dans UsersHub, mais ils ne sont pas mentionnés au niveau des JDD. Lorsqu'ils se connectent à GeoNature, les JDD de notre organisme n'apparaissent pas et un message apparaît : "Aucun jeu de données n'a été trouvé, contactez votre administrateur". Est-ce normal que nos agents n'héritent pas des jeux de données de notre structure ? Y a-t-il quelque chose que je n'ai pas compris ?

**Comment by TheoLechemia** [comment]
Bonjour,
Si les utilisateurs on un R=1 (mes données) il ne verront pas les données (et donc les JDD) de leur organisme, mais seulement les leurs.

**Comment by geobrun** [comment]
Ok, c'est ce que j'ai fini par déduire. Du coup, pour que les JDD apparaissent, il faut mettre un CRUVED à 2. Mais dans ce cas, ce qui ne me convenait pas, c'était que les agents de la structure pouvaient alors modifier les données des autres agents de la structure.

Du coup, la solution que j'ai trouvée (je ne sais pas si c'est la meilleure), c'est un CRUVED à 2 sur Geonature et un CRUVED à 1 sur Occtax. Comme ça, les agents peuvent voir tous les jeux de données de notre organisme mais ne peuvent modifier que leurs propres données dans ces jeux de données.

**Comment by camillemonchicourt** [comment]
On applique une portée à chaque action du CRUVED.
La portée 1 = Mes données
La portée 2 = Les données de mon organisme
La portée 3 = Toutes les données.

C'est à définir pour chaque action.

Donc tu mets par exemple un R et C à 2 (voir et créé des données de mon organisme) mais un U et un D à 1 pour ne pouvoir modifier ou supprimer que ses propres données.

C'est fait pour. Voir la doc administrateur sur la Gestion des droits.

**Comment by geobrun** [comment]
Ok, merci Théo et Camille, vos explications m'ont permis de comprendre ce qui clochait dans mon ancienne configuration.
