### ISSUE TITLE
Problème de redirection entre l'URL avec "www" et sans "www"

### ISSUE THREAD

**Issue by geobrun** [PnX-SI/GeoNature#1355]
Bonjour,

J'ai un petit souci de redirection. Notre GeoNature est configuré en HTTPS avec une URL du type "geonature.structure.fr" et des redirections qui vont bien (normalement). En indiquant dans un navigateur "www.geonature.structure.fr", la page de login s'affiche bien. Mais lorsque je me logge, GeoNature indique un petit temps de chargement mais reste sur la même page sans donner de message d'erreur. La situation se reproduit sur UsersHub (avec cette fois comme message d'erreur "Paramètres de connexion invalides"). Par contre, aucun problème pour me logger dans TaxHub avec une adresse du type "www.taxhub.structure.fr".

Dans le fichier GeoNature de configurations Apache, voilà ce qui est inscrit :
```
<VirtualHost *:80>
	ServerName geonature.structure.fr
	ServerAlias www.geonature.structure.fr
	DocumentRoot /home/geonatureadmin/geonature/frontend/dist

	<Directory /home/geonatureadmin/geonature/frontend/dist>
		Require all granted
	</Directory>
	#RewriteEngine  on
	<Location /api>
		ProxyPass http://127.0.0.1:8000
		ProxyPassReverse  http://127.0.0.1:8000
	</Location>

RewriteEngine on
RewriteCond %{SERVER_NAME} =geonature.structure.fr [OR]
RewriteCond %{SERVER_NAME} =www.geonature.structure.fr
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```

Dans mon fichier "geonature_config.toml", voilà ce que j'ai : 
```
URL_APPLICATION = 'https://geonature.structure.fr'
API_ENDPOINT = 'https://geonature.structure.fr/api'
API_TAXHUB = 'https://taxhub.structure.fr/api'
```

Ca donne l'impression que l'URL en "www" n'arrive pas à rediriger vers l'URL sans "www" lors du loggin.

Quelqu'un a une idée d'où peut venir mon problème ?

**Comment by gildeluermoz** [comment]
Je pense qu'il te faut une redirection explicite de https://www.geonature.structure.fr/ vers https://geonature.structure.fr/ de manière à ce que cette redirection se fasse dès l'ouverture du site et que tu ne puisses rien faire depuis https://www.geonature.structure.fr/

**Comment by camillemonchicourt** [comment]
Oui oui en effet. Il faut pas laisser le www. Ça peut se gérer directement dans les redirections de ton manager du domaine et des sous-domaines.

**Comment by gildeluermoz** [comment]
De ce que je comprends de ta conf apache, tu rediriges les appels http vers https mais ta conf GeoNature ne supporte pas 2 domaines différents. Ta conf apache permet d'entrer dans GeoNature avec l'url https://www.geonature.structure.fr/qqchose et comme ta conf geonature est faite sur ton domaine sans les www. ça coince.

**Comment by gildeluermoz** [comment]
Fais comme te dit Camille au niveau de la gestion de tes domaines et dans ta conf apache, retire le `[OR] RewriteCond %{SERVER_NAME} =www.geonature.structure.fr` et peut-être aussi le ServerAlias (pas sûr pour le coup). Le but est que si tu entres par l'adresse en www. tu sois d'office redirigé vers l'adresse sans le  www.

**Comment by geobrun** [comment]
Ok, merci pour les infos, je vais aller jeter un coup d'oeil dans le manager d'OVH alors et je vous tiens au courant.

**Comment by geobrun** [comment]
Ok, problème géré via le manager d'OVH. Merci pour vos conseils !
