### ISSUE TITLE
Errer REFERENCING pour 2.5.5to2.6.0.sql

### ISSUE THREAD

**Issue by Idaline** [PnX-SI/GeoNature#1358]
Bonjour !

Je ne peux pas lancer les commandes présentent dans le script 2.5.5to2.6.0.sql, telles que : 
    CREATE TRIGGER tri_insert_id_sensitivity_synthese
      AFTER INSERT ON gn_sensitivity.cor_sensitivity_synthese
      REFERENCING NEW TABLE AS NEW
      FOR EACH STATEMENT
      EXECUTE PROCEDURE gn_sensitivity.fct_tri_maj_id_sensitivity_synthese();

J'obtiens l'erreur : 
ERROR:  syntax error at or near "REFERENCING"
LINE 3:       REFERENCING NEW TABLE AS NEW

Savez vous pourquoi svp ?

**Comment by DonovanMaillard** [comment]
Bonjour, 

Quelle est votre version de postgresql? Cette fonction semble récente, à partir de la V10 à priori.

**Comment by Idaline** [comment]
Ah d'accord, si ce n'est que ça... Je suis effectivement en 9.6.19. Je vais tester avec la V10, merci !

**Comment by camillemonchicourt** [comment]
Oui il est indiqué dans les notes de la version 2.6 qu'il faut passer en Debian 10, pour disposer de PostgreSQL 10 ou plus, car on utilise désormais des fonctions qui ne sont pas dispos dans les versions précédentes.

**Comment by Idaline** [comment]
D'accord, j'avais pas fait le lien avec postGres. Merci !
