### ISSUE TITLE
Installation, dockerisation : applicatif et BDD indépendants 

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#1359]
Je me pose la question de pouvoir monter un application GeoNature (avec modules coeur / externes) sans forcement devoir installer une base.
La base serait gérée indépendamment (avec la contrainte d'avoir les bonnes correspondances de version avec l'applicatif).
On peut par exemple partir d'une base existante et vouloir reconstruire un application (+modules) qui possède déjà des modules externe (*changement de serveur etc..*)

### Applicatif
Un premier problème est l'utilisation des commandes geonature, en particulier la commande d'installation de modules qui  peuvent planter lorsque la base n'est pas présente (flask plante à cause des modèles qui ne trouve pas de correspondance en base), 
- pour les modules:
  - il faudrait pouvoir en faire des commandes shell avec des options pour installation du module (BDD, applicatif) ou les deux
    - applicatif:
      - installer les dépendances python, node
      - créer le lien symbolique dans external module (au moins pour le frontend pour les module packagés?)
      - créer le lien symbolique pour les assets du frontend
      - lister les modules dans un fichier `external_modules/index.ts` afin de pouvoir les importer dans le frontend
    - pas mal de choses vont aussi changer pour l'installation de modules avec le travail de @bouttier  
- pour les autres commandes nécessaires à l'installation:
  - dans la branche `feat/config`, il n'y a plus besoin des commande `ts_config`, `generate_frontend_config`, `ts_app_config`, le seul besoin est de lister les modules 

### Base
Il faudra sûrement unifier la procédure d'installation de la base pour les modules (peut être aussi les application) et pouvoir le faire indépendamment de l'applicatif
  - insérer la ligne du module dans gn_commons.t_modules
  - installer le schéma du module 
  - tout regrouper dans <module_dir>/install_db.sh ??
 
Une autre question est comment stocker en base les versions (TH UH GN (+ modules)) et gérer l'installation et les mise à jour de la base
- a voir avec le travail fait sur alembic fait par @bouttier 

L'idée derrière cela est de pouvoir créer un docker pour l'application geonature, faire ce travail pour les autres applications (UH TH ATLAS) et peut avoir un docker supplémentaire dédié à la gestion de la bdd et qui s'occupe d'orchestrer les différentes version pour la base de données.

**Comment by bouttier** [comment]
La fonction ``create_app`` ne génère plus aucun accès à la base de données, permettant d’utiliser la commande ``geonature`` sans base de données. Il est par exemple possible de générer la configuration frontend sans bdd installée.

De même l’installation des modules peut se faire sans base de données, notamment avec ``geonature install-gn-module --upgrade-db false …``. L’insertion des modules dans la table ``t_modules`` et l’installation / la mise à jour de leur schéma Alembic peut se faire à postériori avec la commande ``geonature upgrade-modules``.
