### ISSUE TITLE
Installation globale sur Ubuntu 20.04

### ISSUE THREAD

**Issue by CenRa** [PnX-SI/GeoNature#1360]
Bonjour à tous,
Je tente d'installer Géonature sur un serveur Ubuntu en 20.04 mais me heurte à un blocage pour usershub. Après l'installation Genonature et Taxhub fonctionnent mais userhub ne se lance pas. En regardant les logs d'installation je vois qu'il s'arrete sur l'installation de cffi.
Auriez-vous une idée?
Dans le script j'ai uniquement modifié le choix d'installation de Postgresql (v13) et remplacé les paquets suivants :
python-pip --> python3-pip
python-gdal --> python3-gdal
LaurentP

log_userhub en lançant uniquement usershub/install_app.sh

Création du fichier de configuration ...
préparation du fichier config.py...
Installation du virtual env...
ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'
Collecting https://github.com/PnX-SI/UsersHub-authentification-module/archive/1.4.4.zip (from -r requirements.txt (line 1))
  Using cached https://github.com/PnX-SI/UsersHub-authentification-module/archive/1.4.4.zip
Collecting bcrypt==3.1.4
  Using cached bcrypt-3.1.4-cp34-abi3-manylinux1_x86_64.whl (51 kB)
Collecting cffi==1.11.5
  Using cached cffi-1.11.5.tar.gz (438 kB)
Requirement already satisfied: click==6.7 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (6.7)
Requirement already satisfied: decorator==4.3.0 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (4.3.0)
Processing /home/geonatureadmin/.cache/pip/wheels/f2/a3/85/fe8b65a65a447c9906e3b7edb7d9e6c74dfa9c8425c3dd3007/Flask_Bootstrap-3.3.7.1-py3-none-any.whl
Collecting Flask-Cors==3.0.6
  Using cached Flask_Cors-3.0.6-py2.py3-none-any.whl (13 kB)
Collecting Flask-SQLAlchemy==2.3.2
  Using cached Flask_SQLAlchemy-2.3.2-py2.py3-none-any.whl (16 kB)
Collecting Flask-WTF==0.14.2
  Using cached Flask_WTF-0.14.2-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: flask==1.1.1 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (1.1.1)
Collecting gunicorn==19.9.0
  Using cached gunicorn-19.9.0-py2.py3-none-any.whl (112 kB)
Requirement already satisfied: infinity==1.4 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 12)) (1.4)
Processing /home/geonatureadmin/.cache/pip/wheels/1b/85/49/c1217f30386803cd8ebceee15fba48a1928b3f11b2858b4c14/intervals-0.8.1-py3-none-any.whl
Requirement already satisfied: itsdangerous==0.24 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (0.24)
Requirement already satisfied: Jinja2==2.10.1 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 15)) (2.10.1)
Requirement already satisfied: MarkupSafe==1.1 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 16)) (1.1.0)
Processing /home/geonatureadmin/.cache/pip/wheels/35/64/21/9c9e2c1bb9cd6bca3c1b97b955615e37fd309f8e8b0b9fdf1a/psycopg2-2.8.5-cp38-cp38-linux_x86_64.whl
Requirement already satisfied: pycparser==2.18 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 18)) (2.18)
Collecting python-dateutil==2.7.3
  Using cached python_dateutil-2.7.3-py2.py3-none-any.whl (211 kB)
Requirement already satisfied: six==1.11.0 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 20)) (1.11.0)
Requirement already satisfied: SQLAlchemy==1.3.19 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 21)) (1.3.19)
Collecting toml==0.10.0
  Using cached toml-0.10.0-py2.py3-none-any.whl (25 kB)
Processing /home/geonatureadmin/.cache/pip/wheels/92/10/7b/54139eccba0d1112a3b7b5571eaef1c1dd26b7f84698697dab/validators-0.12.6-py3-none-any.whl
Requirement already satisfied: Werkzeug==0.15.3 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 24)) (0.15.3)
Processing /home/geonatureadmin/.cache/pip/wheels/82/4c/8e/7d3b4910e1aab9a7b3238dbe95a2596db3e00816612bd74f17/WTForms_Components-0.10.3-py3-none-any.whl
Collecting WTForms==2.2.1
  Using cached WTForms-2.2.1-py2.py3-none-any.whl (166 kB)
Collecting requests==2.21.0
  Using cached requests-2.21.0-py2.py3-none-any.whl (57 kB)
Processing /home/geonatureadmin/.cache/pip/wheels/d3/40/52/5dae7760434a82caf8b8f88323029188b2d4ea3ac1235e550a/visitor-0.1.3-py3-none-any.whl
Collecting dominate
  Using cached dominate-2.6.0-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: idna<2.9,>=2.5 in ./venv/lib/python3.8/site-packages (from requests==2.21.0->pypnusershub==1.4.4->-r requirements.txt (line 1)) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./venv/lib/python3.8/site-packages (from requests==2.21.0->pypnusershub==1.4.4->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./venv/lib/python3.8/site-packages (from requests==2.21.0->pypnusershub==1.4.4->-r requirements.txt (line 1)) (1.24.3)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Building wheels for collected packages: cffi, pypnusershub
  Building wheel for cffi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/geonatureadmin/usershub/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rw8nw9xb/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rw8nw9xb/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-lfdr4upd
       cwd: /tmp/pip-install-rw8nw9xb/cffi/
  Complete output (49 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/cffi
  copying cffi/error.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/cparser.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/verifier.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/commontypes.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/lock.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/__init__.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/api.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/model.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/recompiler.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/_embedding.h -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.8/cffi
  running build_ext
  building '_cffi_backend' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/c
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/home/geonatureadmin/usershub/venv/include -I/usr/include/python3.8 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.8/c/_cffi_backend.o
  c/_cffi_backend.c: In function ‘b_do_dlopen’:
  c/_cffi_backend.c:4197:31: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   4197 |         *p_printable_filename = PyText_AsUTF8(s);
        |                               ^
  c/_cffi_backend.c: In function ‘b_callback’:
  c/_cffi_backend.c:5911:5: warning: ‘ffi_prep_closure’ is deprecated: use ffi_prep_closure_loc instead [-Wdeprecated-declarations]
   5911 |     if (ffi_prep_closure(closure, &cif_descr->cif,
        |     ^~
  In file included from c/_cffi_backend.c:15:
  /usr/include/x86_64-linux-gnu/ffi.h:334:1: note: declared here
    334 | ffi_prep_closure (ffi_closure*,
        | ^~~~~~~~~~~~~~~~
  In file included from c/cffi1_module.c:20,
                   from c/_cffi_backend.c:7370:
  c/call_python.c: In function ‘_get_interpstate_dict’:
  c/call_python.c:20:30: error: dereferencing pointer to incomplete type ‘PyInterpreterState’ {aka ‘struct _is’}
     20 |     builtins = tstate->interp->builtins;
        |                              ^~
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cffi
  Running setup.py clean for cffi
  Building wheel for pypnusershub (setup.py) ... done
  Created wheel for pypnusershub: filename=pypnusershub-1.4.4-py3-none-any.whl size=30769 sha256=adcd0d5b7bce29e3432abf3aca94c8e1db41e03624b11751b8b87f8efc32a95e
  Stored in directory: /tmp/pip-ephem-wheel-cache-jjyync_e/wheels/a0/29/26/ab4c9f5758b50556f9ccfa488b3c762a30d22bc14e75bc09bc
Successfully built pypnusershub
Failed to build cffi
Installing collected packages: cffi, bcrypt, visitor, dominate, Flask-Bootstrap, Flask-Cors, Flask-SQLAlchemy, WTForms, Flask-WTF, gunicorn, intervals, psycopg2, python-dateutil, toml, validators, WTForms-Components, certifi, requests, pypnusershub
    Running setup.py install for cffi ... error
    ERROR: Command errored out with exit status 1:
     command: /home/geonatureadmin/usershub/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rw8nw9xb/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rw8nw9xb/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fuirg6sf/install-record.txt --single-version-externally-managed --compile --install-headers /home/geonatureadmin/usershub/venv/include/site/python3.8/cffi
         cwd: /tmp/pip-install-rw8nw9xb/cffi/
    Complete output (49 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/cffi
    copying cffi/error.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/cparser.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/verifier.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/commontypes.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/lock.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/__init__.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/api.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/model.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/recompiler.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/_embedding.h -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.8/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/c
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/home/geonatureadmin/usershub/venv/include -I/usr/include/python3.8 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.8/c/_cffi_backend.o
    c/_cffi_backend.c: In function ‘b_do_dlopen’:
    c/_cffi_backend.c:4197:31: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     4197 |         *p_printable_filename = PyText_AsUTF8(s);
          |                               ^
    c/_cffi_backend.c: In function ‘b_callback’:
    c/_cffi_backend.c:5911:5: warning: ‘ffi_prep_closure’ is deprecated: use ffi_prep_closure_loc instead [-Wdeprecated-declarations]
     5911 |     if (ffi_prep_closure(closure, &cif_descr->cif,
          |     ^~
    In file included from c/_cffi_backend.c:15:
    /usr/include/x86_64-linux-gnu/ffi.h:334:1: note: declared here
      334 | ffi_prep_closure (ffi_closure*,
          | ^~~~~~~~~~~~~~~~
    In file included from c/cffi1_module.c:20,
                     from c/_cffi_backend.c:7370:
    c/call_python.c: In function ‘_get_interpstate_dict’:
    c/call_python.c:20:30: error: dereferencing pointer to incomplete type ‘PyInterpreterState’ {aka ‘struct _is’}
       20 |     builtins = tstate->interp->builtins;
          |                              ^~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/geonatureadmin/usershub/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rw8nw9xb/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rw8nw9xb/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fuirg6sf/install-record.txt --single-version-externally-managed --compile --install-headers /home/geonatureadmin/usershub/venv/include/site/python3.8/cffi Check the logs for full command output.
Found '/home/geonatureadmin/usershub/app/static/.nvmrc' with version <v10.15.3>
v10.15.3 is already installed.
Now using node v10.15.3 (npm v6.4.1)
Found '/home/geonatureadmin/usershub/app/static/.nvmrc' with version <v10.15.3>
Now using node v10.15.3 (npm v6.4.1)
npm WARN prepare removing existing node_modules/ before installation
added 6 packages in 0.796s
[sudo] password for geonatureadmin:
Module proxy already enabled
Considering dependency proxy for proxy_http:
Module proxy already enabled
Module proxy_http already enabled
No config updates to processes
Restarted supervisord
error: error setting owner of /home/geonatureadmin/geonature/var/log/gn_errors.log to uid 1001 and gid 33: Operation not permitted
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: NO)'
error: error running shared postrotate script for '/var/log/mysql/mysql.log /var/log/mysql/mysql-slow.log /var/log/mysql/mariadb-slow.log /var/log/mysql/error.log '

**Comment by camillemonchicourt** [comment]
L'installation sur Ubuntu 20 n'a pas encore été packagée.
On maintient Debian en version 10 actuellement.

Pour Ubuntu 20, c'est en cours de tests. 
Plusieurs personnes ont installé GeoNature et ses dépendances mais pas avec une installation globale.
Dans les 3 dépôts de GeoNature, UsersHub et TaxHub, il y a une branche dédiée nommée "ubuntu_20_04" avec les modifications nécessaires à l'installation sur cet OS, en attendant que cela soit intégrée, testée et donc fonctionnel avec l'installation globale.

D'ici là plusieurs personnes ont installé GeoNature sur Ubuntu 20 et pourront certainement t'indiquer ce qui a coincé dans ton cas ?

**Comment by camillemonchicourt** [comment]
Au niveau de UsersHub, voici justement ce qui a été modifié pour l'installer sur Ubuntu 20 : https://github.com/PnX-SI/UsersHub/compare/ubuntu_20.04

**Comment by CenRa** [comment]
Merci, effectivement je n'avais pas regardé les issues dans Usershub. L'install fonctionne beaucoup mieux en faisant quelques ajustements dans requirements.txt.
On va suivre de plus près les branches 20.04
++

**Comment by camillemonchicourt** [comment]
On verra quand on peut intégrer ces branches pour supporter directement Ubuntu 20.04, mais on se concentre sur Debian 10 en priorité.
Il y a aussi le dépôt dédié au déploiement Docker qui fonctionne mais est en cours d'amélioration car il a encore plusieurs limites.

**Comment by Adrien-Pajot** [comment]
Pour rebondir sur ce sujet, on se pose la question pendant le workshop de cette installation Ubuntu qui pose beaucoup de problème. Peut-on imaginer une installation unique packagée qui soit adaptée à Ubuntu ou Debian ? À voir avec le temps !
