### ISSUE TITLE
frontend : ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#1364]
Je tombe sur une erreur quand je veux insérer des médias dans occtax (en mode dev)

```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: undefined'. Current value: 'ngIf: Administrateur test'.
```
 est ce que quelqu'un a une idée pour solutionner `ExpressionChangedAfterItHasBeenCheckedError`

**Comment by TheoLechemia** [comment]
Salut,
oui c'est une erreur courante en Angular (elle ne s'affiche que quand le compileur est en mode developpement).
Et comme sont nom l'indique, ça siginifie qu'une variable a changé après l'initialisation de la page (ngOnInit à priori). Ca remonte l'erreur sur les variables qui sont associés à des "ngIf" ngFor etc... 
Mais j'ai jamais bien compris en quoi c'était un problème parce que la vue html est constamment mise à jour quand une variable de classe change, c'est le principe du databinding. 
Tu peux jouer avec les lifecycle hooks pour éviter cet erreur, en passant certaines variable dans "ngAfterViewInit", "ngAfterContentInit".

**Comment by joelclems** [comment]
Je suis bien de ton avis il ne devrait pas y avoir d'erreur la dessus
Je tombe dessus meme pour des assignations toutes simple...
il doit bien avoir une option pour cela

**Comment by joelclems** [comment]
J'arrive à quelque chose en mettant les actions dans
```
ngAfterViewChecked() {
```

**Comment by jbrieuclp** [comment]
Tu dois avoir la variable d'un service qui est modifiée en même temps et surement en opposition par des components différents ou des observables différents.
