### ISSUE TITLE
Installation Geonature

### ISSUE THREAD

**Issue by pbaumes** [PnX-SI/GeoNature#1376]
Bonjour tout le monde !

Après installation de "instal_all.sh" et ayant suivi la doc d'installation globale, je viens vers vous car je ne trouve pas de solution à mon problème.

voici les logs (install_all.log) => 

[install_all.log](https://github.com/PnX-SI/GeoNature/files/6494979/install_all.log)

En parallèle, j'ai essayé d'accéder au site "http://monIp.com/geonature" via le navigateur,  mais j'obtiens une erreur 403.

Je suis allé voir dans la conf apache générée, le path n'existe pas (/home/geonatureadmin/geonature/frontend/dist), je n'ai pas le répertoire "dist" en question.

J'ai donc essayé de lancer un "npm install", puis un "npm build", mais voici ce que j'obtiens à la suite de cette dernière commande : 

![Capture d’écran 2021-05-17 à 17 39 41](https://user-images.githubusercontent.com/7081838/118516761-e7ccae80-b736-11eb-8ca3-65c886c34dde.png)

Auriez-vous une idée du pb ?

Merci par avance.

**Comment by camillemonchicourt** [comment]
Dans le fichier install_all.log, on voit beaucoup de fois une erreur indiquant un problème de connexion à la BDD : ``sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  authentification par mot de passe échouée pour l'utilisateur ...``.

On dirait que l'utilisateur en question n'a pas les droits sur la BDD et cela a certainement bloqué l'installation ?

**Comment by pbaumes** [comment]
Effectivement, merci je n'avais pas vu, mais après avoir changer d'user et relancé le script, l'erreur précédente est désormais avsente des logs, en revanche le dossier "/home/geonatureadmin/geonature/frontend/dist" est toujours inexistant. 

Voici le fichier de log généré => 

[install_all_3.log](https://github.com/PnX-SI/GeoNature/files/6496173/install_all_3.log)

Il y a toute une série d'erreurs liée à une relation inexistante "ref_nomenclatures.bib_nomenclatures_types".

**Comment by TheoLechemia** [comment]
Bonjour,
serait-il possible d'envoyer le fichier "install_db.log" ?

**Comment by pbaumes** [comment]
Bonjour,

Merci pour votre retour, en effet, tout ne se passe pas bien pour l'installation de la BDD, voici les logs en question => 

[install_db.log](https://github.com/PnX-SI/GeoNature/files/6499291/install_db.log)

Pour le paramètre "drop_db" il s'agit d'un ajout à faire dans le "/home/geonatureadmin/install_all.ini" ? 
Je ne trouve pas ce paramètre dans les fichiers de conf.

**Comment by pbaumes** [comment]
J'ai passé le "drop_apps_db" à "true", j'ai relancé le script "install_all.sh" mais le résultat reste le même.

Je n'ai pas de nouveaux logs "install_db.log" générés, mais "gn_errors.log" oui => 

[gn_errors.log](https://github.com/PnX-SI/GeoNature/files/6499616/gn_errors.log)

**Comment by camillemonchicourt** [comment]
Vous avez des erreurs de partout car la BDD n'a pas été créée correctement.
On dirait encore un problème avec votre utilisateur de connexion à la BDD, mais on va regarder ça plus en détail.

**Comment by jbrieuclp** [comment]
"
psql: FATAL:  authentification par mot de passe échouée pour l'utilisateur  « geonatadmin »
FATAL:  authentification par mot de passe échouée pour l'utilisateur  « geonatadmin »
"
Le mot de passe est le bon ?

**Comment by camillemonchicourt** [comment]
Oui depuis le départ il semble y avoir des problèmes avec votre utilisateur qui se connecte àa la BDD, du coup ensuite l'installation se passe mal, et les commandes GeoNature suivantes ne passent pas correctement, donc pas de dossier frontend etc etc.

Le script ``install_all.sh`` créé lui-même un utilisateur par défaut et c'est celui-ci qu'il faut utiliser : https://github.com/PnX-SI/GeoNature/blob/master/install/install_all/install_all.sh#L127
Si on veut en utiliser un autre, il faut bien le créer, lui donner les bons droits etc...

Normalement le script ``install_all.sh`` s'occupe de tout créer par défaut pour que ça fonctionne.

**Comment by DonovanMaillard** [comment]
Pour info si utile, j'ai fait un install all récemment (mi avril) avec un utilisateur qui n'est pas le geonatadmin par défaut. Aucun soucis de mon coté, tout a bien fonctionné.

**Comment by camillemonchicourt** [comment]
Oui si on renseigne des noms différents d'utilisateur et son MDP avant de lancer le script ``install_all.sh`` alors ça fonctionne bien évidemment.
Mais si on les change après l'installation, là ça ne va pas fonctionner directement.

**Comment by pbaumes** [comment]
Effectivement, ça devait être un problème lié aux droits de l'utilisateur de la BDD, car entre temps j'avais indiquer un nouvel utilisateur/mot de passe dans le "install_all.ini".

Je viens de procéder à une nouvelle installation from scratch, et désormais j'accède bel et bien au site.

Merci à vous !

**Comment by pbaumes** [comment]
Effectivement, ça devait être un problème lié aux droits de l'utilisateur de la BDD, car entre temps j'avais indiquer un nouvel utilisateur/mot de passe dans le "install_all.ini".

Je viens de procéder à une nouvelle installation from scratch, et désormais j'accède bel et bien au site.

Merci à vous !
