### ISSUE TITLE
[Synthèse] - filtre statut observation et niveau de validation avec valeurs par défaut

### ISSUE THREAD

**Issue by lepontois** [PnX-SI/GeoNature#1377]
Bonjour,

Serait-il envisageable de faire évoluer la synthèse pour qu'on puisse lui paramétrer des filtres par défaut qui seraient alors affichés sur l'interface.

Par rapport à mon besoin, il faudrait que le filtre statut d'observation soit par défaut sur "présence" et le niveau de validation sur "certain / probable / en attente de validation".
L'objectif étant de réduire les risques de mauvaise lecture des données retournées par la recherche.
Ces filtres seraient alors visible sur l'interface afin que l'utilisateur sache qu'ils sont actif et qu'il puisse en modifier les valeurs s'il le souhaite.

Merci de me faire savoir si le développement de cette fonctionnalité pourrait être envisagé dans une prochaine release de GN et idéalement à quelle échéance (mais je suis peut-être trop groumant)

Merci !

**Comment by camillemonchicourt** [comment]
Ce sujet renvoie à 2 tickets : 
- https://github.com/PnX-SI/GeoNature/issues/968
- https://github.com/PnX-SI/GeoNature/issues/521

Pourquoi pas imaginer la possibilité de paramétrer des filtres renseignés par défaut. Ça pourrait être une bonne solution, assez générique.

Rien de prévu sur le sujet à ma connaissance.

**Comment by camillemonchicourt** [comment]
Fait dans la version 2.12.0 avec l'ajout de paramètre du module Synthèse permettant de définir des filtres activés par défaut et leur valeur associée : https://github.com/PnX-SI/GeoNature/pull/2262/files#diff-5b0da6f626536c3f89d4ccd93ac5892ac399fb7a9ab1944fb801efa53696cd58
