### ISSUE TITLE
Protocoles CONTACT et programmes ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#138]
Ajouter une liste déroulante BIB_programmes ?

**Comment by camillemonchicourt** [comment]
Réflexion en cours sur la V2 du Contact avec une notion de programme ou jeu de données.

**Comment by camillemonchicourt** [comment]
On va plutôt ajouter une liste déroulante des lots de données (actifs et dans lequel l'utilisateur a les droits de saisir). Chaque jeu de donnée étant rattaché à un programme.

**Comment by gildeluermoz** [comment]
On crée un ticket concernant les métadonnées auquel on rattache la notion de programme qui reste à éclaircir et à croiser avec la notion INPN de contexte d'aquisition
