### ISSUE TITLE
Problème de droits sur dataset 2.6.2

### ISSUE THREAD

**Issue by ClaireLagaye** [PnX-SI/GeoNature#1384]
J'ai fait la mise à jour de Geonaure depuis la 2.5.5 vers la 2.6.2 la semaine dernière
Cela s'est très bien passé et on apprécie les améliorations.

J'ai cependant un problème au niveau des droits d'éditions dans OCCTAX depuis cette mise à jour

J'ai un utilisateur 1000001 qui est dans le groupe grp_Admin et dans l'organisme PNV
Dans le CRUVED j'ai tout mis à 3 dans tous les modules pour grp_Admin
![image](https://user-images.githubusercontent.com/11782642/120995365-a05d9f00-c785-11eb-9ffc-2ce94dd14fec.png)

Mon dataset principal de Occtax est le 1 et il a comme contact principal et producteur le PNV

Cet utilisateur peut saisir dans occtax mais s'il essaye modifier cette saisie, il obtient une erreur et dans le log on a 
![image](https://user-images.githubusercontent.com/11782642/120994331-ad2dc300-c784-11eb-8199-ee376421b2bb.png)

Je me pose donc 3 questions:
- Quelle est la bonne façon d'octroyer des droits sur un dataset autre que le module métadonnées et de bien affecter le dataset à l'organisme de l'observateur ,
- Normalement si mon utilisateur est en CRUVED 3 sur tout, il devrait bien pouvoir tout modifier, même indépendamment des droits sur les datasets?
- Comment est-ce possible de saisir dans un dataset si on n'a pas les droits?

**Comment by TheoLechemia** [comment]
Bonjour Clair,
C'est assez bizarre... si l'utilisateur a des droits 3, aucune vérification n'est faite sur son accès à la données.
Est-ce que tu pourrais me donner le CRUVED de l'utilisateur avec lequel tu fais l'édition en allant dans le debugeur de ton  navigateur, onglet "application" , puis "localStorage" et copier l'ensemble de l'objet "modules" ?
Merci

**Comment by ClaireLagaye** [comment]
Salut Théo,
Merci de te pencher sur mon problème. Voici ce que j'ai dans l'objet modules, et en effet il n'y a pas que des 3

[{"id_module":1,"module_code":"ADMIN","module_label":"Admin","module_picto":"fa-cog","module_desc":"Backoffice de GeoNature","module_group":null,"module_path":"admin","module_external_url":null,"module_target":"_self","module_comment":"Administration des métadonnées et des nomenclatures","active_frontend":true,"active_backend":false,"module_doc_url":"http://docs.geonature.fr/user-manual.html#admin","module_order":null,"cruved":{"C":"3","R":"3","U":"3","V":"3","E":"3","D":"3"},"module_url":"https://geonature2.vanoise-parcnational.fr/geonature/#/admin"},{"id_module":9,"module_code":"DASHBOARD","module_label":"dashboard","module_picto":"fa-puzzle-piece","module_desc":null,"module_group":null,"module_path":"dashboard","module_external_url":null,"module_target":"_self","module_comment":null,"active_frontend":true,"active_backend":true,"module_doc_url":null,"module_order":null,"cruved":{"C":"3","R":"3","U":"3","V":"3","E":"3","D":"3"},"module_url":"https://geonature2.vanoise-parcnational.fr/geonature/#/dashboard"},{"id_module":7,"module_code":"EXPORTS","module_label":"exports","module_picto":"fa-puzzle-piece","module_desc":null,"module_group":null,"module_path":"exports","module_external_url":null,"module_target":"_self","module_comment":null,"active_frontend":true,"active_backend":true,"module_doc_url":null,"module_order":null,"cruved":{"C":"1","R":"3","U":"1","V":"0","E":"3","D":"1"},"module_url":"https://geonature2.vanoise-parcnational.fr/geonature/#/exports"},{"id_module":0,"module_code":"GEONATURE","module_label":"GeoNature","module_picto":"","module_desc":"Module parent de tous les modules sur lequel on peut associer un CRUVED. NB: mettre active_frontend et active_backend à false pour qu'il ne s'affiche pas dans la barre latérale des modules","module_group":null,"module_path":"/geonature","module_external_url":null,"module_target":"","module_comment":"","active_frontend":false,"active_backend":false,"module_doc_url":"http://docs.geonature.fr/user-manual.html","module_order":null,"cruved":{"C":"3","R":"3","U":"3","V":"3","E":"3","D":"3"},"module_url":null},{"id_module":8,"module_code":"IMPORT","module_label":"import","module_picto":"fa-puzzle-piece","module_desc":null,"module_group":null,"module_path":"import","module_external_url":null,"module_target":"_self","module_comment":null,"active_frontend":true,"active_backend":true,"module_doc_url":null,"module_order":null,"cruved":{"C":"3","R":"3","U":"3","V":"3","E":"3","D":"3"},"module_url":"https://geonature2.vanoise-parcnational.fr/geonature/#/import"},{"id_module":2,"module_code":"METADATA","module_label":"Metadonnées","module_picto":"fa-book","module_desc":"Module de gestion des métadonnées","module_group":null,"module_path":"metadata","module_external_url":null,"module_target":"_self","module_comment":null,"active_frontend":true,"active_backend":true,"module_doc_url":"http://docs.geonature.fr/user-manual.html#metadonnees","module_order":null,"cruved":{"C":"3","R":"3","U":"3","V":"3","E":"3","D":"3"},"module_url":"https://geonature2.vanoise-parcnational.fr/geonature/#/metadata"},{"id_module":5,"module_code":"OCCHAB","module_label":"occhab","module_picto":"fa-puzzle-piece","module_desc":null,"module_group":null,"module_path":"occhab","module_external_url":null,"module_target":"_self","module_comment":null,"active_frontend":true,"active_backend":true,"module_doc_url":null,"module_order":null,"cruved":{"C":"3","R":"3","U":"3","V":"3","E":"3","D":"3"},"module_url":"https://geonature2.vanoise-parcnational.fr/geonature/#/occhab"},{"id_module":4,"module_code":"OCCTAX","module_label":"occtax","module_picto":"fa-puzzle-piece","module_desc":null,"module_group":null,"module_path":"occtax","module_external_url":null,"module_target":"_self","module_comment":null,"active_frontend":true,"active_backend":true,"module_doc_url":null,"module_order":null,"cruved":{"C":"3","R":"3","U":"1","V":"0","E":"3","D":"1"},"module_url":"https://geonature2.vanoise-parcnational.fr/geonature/#/occtax"},{"id_module":3,"module_code":"SYNTHESE","module_label":"Synthese","module_picto":"fa-search","module_desc":"Application synthese","module_group":null,"module_path":"synthese","module_external_url":null,"module_target":"_self","module_comment":null,"active_frontend":true,"active_backend":true,"module_doc_url":"http://docs.geonature.fr/user-manual.html#synthese","module_order":null,"cruved":{"C":"1","R":"3","U":"1","V":"0","E":"3","D":"1"},"module_url":"https://geonature2.vanoise-parcnational.fr/geonature/#/synthese"},{"id_module":6,"module_code":"VALIDATION","module_label":"validation","module_picto":"fa-puzzle-piece","module_desc":null,"module_group":null,"module_path":"validation","module_external_url":null,"module_target":"_self","module_comment":null,"active_frontend":true,"active_backend":true,"module_doc_url":null,"module_order":null,"cruved":{"C":"1","R":"3","U":"2","V":"2","E":"3","D":"2"},"module_url":"https://geonature2.vanoise-parcnational.fr/geonature/#/validation"}]

**Comment by TheoLechemia** [comment]
Effectivement ton utilisateur a un ce CRUVED pour OCCTAX: {"C":"3","R":"3","U":"1","V":"0","E":"3","D":"1"},
Le problème du U=1 sur l'édition a été corrigé dans la prochaine release. Mais dans ton cas tu voudrait qu'il ai un U:3.
Est-ce que l'utilisateur fait parti de plusieurs groupes ? Si oui, est-ce que tu peux vérifier que tu as bien "surcoucher" le CRUVED pour le module OCCTAX, et que celui-ci n'est pas hérité du module GeoNature  ?

**Comment by ClaireLagaye** [comment]
Alors oui cet utilisateur fait partie d'un autre groupe qui a un cruved inférieur
![image](https://user-images.githubusercontent.com/11782642/121003131-75774900-c78d-11eb-8967-5224b932f48a.png)
mais ça paraît bien surcouché par rapport à Geonature

**Comment by ClaireLagaye** [comment]
Ah et si je surcouche OCCTAX en cruved 3 dans le groupe Admin ça résout mon problème
C'est vrai que je ne faisais pas du tout attention à cette question d'héritage

**Comment by camillemonchicourt** [comment]
Merci pour ces éléments. 
A l'usage on est plusieurs à se dire que la question de l'héritage des permissions n'est pas si pertinent qu'on le pensait initialement et complique souvent les choses.
Finalement il nous semble plus adapté de l'enlever et de vraiment donner EXPLICITEMENT les permissions que l'on veut attribuer à chaque groupe ou utilisateur.

Mais c'est un autre sujet assez dense et complexe, que l'on discutera dans un ticket dédié.

**Comment by jbdesbas** [comment]
> Effectivement ton utilisateur a ce CRUVED pour OCCTAX: {"C":"3","R":"3","U":"1","V":"0","E":"3","D":"1"},
> Le problème du U=1 sur l'édition a été corrigé dans la prochaine release. Mais dans ton cas tu voudrait qu'il ai un U:3.
> Est-ce que l'utilisateur fait parti de plusieurs groupes ? Si oui, est-ce que tu peux vérifier que tu as bien "surcoucher" le CRUVED pour le module OCCTAX, et que celui-ci n'est pas hérité du module GeoNature ?

Salut @TheoLechemia j'ai un souci qui empêche les utilisateurs de modifier un relevé (date, observateurs, commentaire de contexte), (message d'erreur), mais pas les occurrences de ce relevé (taxons, attributs, dénombrement, commentaire identification...). C'est à ça que tu fais référence quand tu parles du problème "U=1" ou il faut que je cherche la solution ailleurs ?

**Comment by TheoLechemia** [comment]
Salut,
ça ressemble à ce bug: https://github.com/PnX-SI/GeoNature/issues/1365
corrigé dans la prochaine release par ce commit: https://github.com/PnX-SI/GeoNature/commit/8d1e2d4a3e4a88c207efe2671a98b1a481d2dcfd
