### ISSUE TITLE
Phytosociologie

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/GeoNature#1390]
Un client me demande un module Phytosociologie.

J'avais cru comprendre que la phytosocio n'était plus vraiment a la mode ?
Est ce que c'est pertinent d'imaginer une mutualisation des moyens (CBN?) autour d'un tel module?

**Comment by camillemonchicourt** [comment]
Oui le sujet a été initié ici : https://github.com/PnX-SI/GeoNature/issues/178
Et ici, en partie : https://github.com/PnX-SI/GeoNature/issues/680

Il y a des débats sur la phytosocio en effet, mais un module dédié aux relevés de végétation serait utile et intéressant, pour faire de la phytosocio ou autre.

**Comment by AJambon** [comment]
Les champs additionnels d'occtax peuvent peut-être répondre ?

**Comment by camillemonchicourt** [comment]
Duplicate : https://github.com/PnX-SI/GeoNature/issues/680
