### ISSUE TITLE
Occtax : edition de relevé --> changement d'id_digitiser

### ISSUE THREAD

**Issue by jbdesbas** [PnX-SI/GeoNature#1392]
Salut,

Sur Occtax, lorsqu'un relevé est édité par un autre utilisateur que le saisisseur, le champs _id_digitiser_ est remplacé par l'identifiant du dernier utilisateur ayant modifié le relevé.
Ca peut également faire perdre le droit d'accès au relevé si le saisisseur n'est pas observateur.
Je ne pense pas que ca soit volontaire, le id_digitiser devrait toujours correspondre au saisisseur d'origine non ?

**Comment by camillemonchicourt** [comment]
Oui ça devrait rester celui d'origine je pense en effet

**Comment by jbrieuclp** [comment]
Est-ce qu'il s'envisage d'avoir l'enregistrement des utilisateurs ayant effectués des modifs ? On ne l'a pas dans la table t_history.

**Comment by TheoLechemia** [comment]
Oui ça pourrait être intéressant effectivement. Tu ouvres un autre ticket sur ça ?
