### ISSUE TITLE
Supprimer les SHP des zonages français

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#140]
Pour alléger le dépôt.
Les récupérer pendant l'installation en wget.
Exemple : https://inpn.mnhn.fr/docs/Shape/znieff1.zip
Attention pour DOM-TOM... Par exemple https://inpn.mnhn.fr/docs/Shape/glp_znieff1.zip pour la Guadeloupe.

**Comment by gildeluermoz** [comment]
opération impossible : les couches sont mises à jour et renommées par l'INPN, les urls changent et le nom des shp dans les zip téléchargeables changent aussi (avec date de mise à jour)...

**Comment by camillemonchicourt** [comment]
OK là les zip ont pas l'air d'avoir de date mais c'est un peu risqué oui...
Ou c'est les fichiers dans le zip qui changent?

**Comment by gildeluermoz** [comment]
Parfois c'est dans un rep, parfois non, parfois avec une date sur le rep et parfois sur les fichiers, parfois pas de dates, parfois les fichiers direct dans le zip avec ou sans date...

**Comment by camillemonchicourt** [comment]
Voir avec INPN si cela ne peut pas être stabilisé. Ça allégerait beaucoup l'archive du dépôt et garantirait de fournir des zonages à jour.

**Comment by camillemonchicourt** [comment]
En attendant ils ont été déplacés hors du dépôt pour l'alléger, dans http://geonature.fr/data/inpn/layers/

**Comment by gildeluermoz** [comment]
Fait en V1. A intégrer lors de création de ces zones en V2

**Comment by camillemonchicourt** [comment]
Et les mettre à jour en passant.
