### ISSUE TITLE
Perte de fiches Métadonnées dans le Catalogue

### ISSUE THREAD

**Issue by MathieuLagarde** [PnX-SI/GeoNature#1404]
Bonjour,
Sur GéoNature 2.6.2, je n'ai accès qu'à certains cadres d'acquisition (et donc jeux de données) dans le module Métadonnées.
Concrètement, dans le schéma gn_meta, j'ai 5 CA (t_acquisition_frameworks) et 11 JDD (t_datasets).
Dans le Catalogue des jeux de données, je ne retrouve que 3 des CA, et les JDD associés.
Je ne trouve pas de paramètres dans mes tables expliquant que 2 CA ne se retrouvent pas dans le module metadata.
Pourriez-vous m'aiguiller sur les pistes à creuser svp ?
Bonne journée,
Mathieu

**Comment by camillemonchicourt** [comment]
Certainement lié aux droits CRUVED de ton compte utilisateur ?

**Comment by MathieuLagarde** [comment]
Bonjour Camille,
Oui, je ne m'inquiétais pas de la perte éventuelle de données. Tout est bien présent en base.
Concernant le CRUVED, je suis connecté avec l'utilisateur admin, qui a les droits de portée "3" sur toutes les actions.
Ce que je n'arrive pas à comprendre, c'est pourquoi certains CA s'affichent, et d'autres non.

**Comment by camillemonchicourt** [comment]
Si c'est ça, il serait intéressant de remonter dans la liste les CA et JDD même si ils n'ont pas d'acteurs.

**Comment by camillemonchicourt** [comment]
OK intéressant.
A minima, les faire remonter dans la liste même si ils n'ont pas d'acteurs.

**Comment by jbrieuclp** [comment]
Normalement ça devrait être réglé avec marshmallow qui lie directos les relations du model de données.
Pour les alerte pour la saisie il y a les alertes du formulaire. 
Au niveau des fiches ou de la liste des métadonnées on peut mettre un "si acteur sinon" avec un message "Cette fiche ne contient pas d'acteur" en lien avec ce `If` qui existe presque déjà après ça https://github.com/PnX-SI/GeoNature/blob/58ff0cd1f89c6c875b362a9edc0a0c4cfce38357/frontend/src/app/metadataModule/metadata.component.html#L108
Idem au niveau des fiches ici :
https://github.com/PnX-SI/GeoNature/blob/58ff0cd1f89c6c875b362a9edc0a0c4cfce38357/frontend/src/app/metadataModule/af/af-card.component.html#L231
Je peux proposer une PR pour cette proposition.
