### ISSUE TITLE
[General] Cohérence entre branche Master et Release

### ISSUE THREAD

**Issue by hypsug0** [PnX-SI/GeoNature#1408]
Pas de de mises à jour ont été faiites depuis la dernière release (v2.6.2 de février dernier);, notamment le travail sur les champs additionnels. Est-ce normal? 

La branche master peut-elle être utilisée en prod?

**Comment by camillemonchicourt** [comment]
Non, on a mergé ``develop`` dans ``master`` il y a quelques semaines, pour vérifier les alertes de sécurité.
Mais il ne faut pas utiliser ``master`` actuellement.
``develop`` est OK, @TheoLechemia a encore fait pas mal de corrections ces derniers jours, on fait les derniers tests et ajustements et on release la 2.7.0.

**Comment by hypsug0** [comment]
Ok, merci.
