### ISSUE TITLE
2.7.0 - Fiche CA et JDD - Liste des JDD ne s'affiche plus

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#1410]
Depuis la 2.7.0, la fiche d'un CA n'affiche plus la liste des JDD et on a cette erreur dans la console : ``ERROR TypeError: Cannot read property 'creator' of undefined``.

EDIT : Le problème des routes en 404 sur la fiche JDD était due à un JDD sans données...

**Comment by TheoLechemia** [comment]
Fix: https://github.com/PnX-SI/GeoNature/commit/1f4352f41fbed9961bd7c3f1b36b81f740fb7be6
