### ISSUE TITLE
Création d'un relevé via une API GeoNature

### ISSUE THREAD

**Issue by Heg0Damask** [PnX-SI/GeoNature#1411]
Bonjour,

J'ai une base de relevés et je souhaiterais l'intégrer dans GeoNature.
J'ai utilisé l'API "http://monServeur/geonature/api/occtax/releve/" + numero de relevé qui marche très bien si le relevé existe.

Est il possible de modifier ce relevé par exemple modifier le commentaire et enregistrer la modification via une API ?

Et peut on créer un relevé vide et ensuite l'alimenter avec des données à l'aide du point précédent ?

Pour le moment je n'ai que des erreurs 500 car je ne sais pas quoi mettre dans les API situées ici : https://docs.geonature.fr/development.html#liste-des-routes

En version 2.3.2 j'utilisait l'API /occtax/releve qui marchait très bien et j'arrivais à modifier mes relevés, je suis maintenant en 2.6.2 et ça ne fonctionne plus comme avant.

Est ce que quelqu'un a une idée ?

merci

**Comment by camillemonchicourt** [comment]
L'application Occtax-mobile utilise l'API de GeoNature (Occtax, observateurs, datasets, nomenclatures...) pour récupérer les infos nécessaires au formulaire de saisie Occtax, puis poster un relevé. Par contre on ne fait que des posts complets.
Pas de modification d'un relevé dans son fonctionnement actuel.
Mais il y a certainement des possibilités avec les autres routes d'Occtax, qui ne sont pas utilisées par Occtax-mobile.

**Comment by Heg0Damask** [comment]
merci 
J'ai regardé les autres routes mais je ne vois pas par quel bout prendre le problème.

**Comment by camillemonchicourt** [comment]
Le module web Occtax utilise l'API pour toutes ses actions (update, delete, post d'un relevé seulement...).
Il est donc possible d'utiliser les mêmes routes que celles du module web Occtax.

**Comment by TheoLechemia** [comment]
Il n'y a pas de doc spécifique sur quel champs sont attendu par l'API. Mais ce sont ceux des modules SQLAlchemy décrit dans le code
Il faut regarder les logs de l'API pour voir quels champs entraine l'erreur 500.

**Comment by Heg0Damask** [comment]
Ok merci j'ai trouvé ! 

Donc pour créer un relevé vide, il faut utiliser la route suivante : **geonature/api/occtax/only/releve** ce qui permet d'obtenir un relevé avec un id_releve = **10** par exemple.

Ensuite on peut ajouter des occurences en utilisant la route suivante **geonature/api/occtax/releve/10/occurrence** ce qui donne une occurrence avec un id_occurrence = **190** par exemple et pour finir on peut modifier l'occurrence courante avec la route **geonature/api/occtax/occurrence/190** 

Et ça a l'air de coller, j'attends de voir ce que ça va donner avec mes relevés avec plus de 100 taxons...

**Comment by Heg0Damask** [comment]
Je dois encore chercher comment faire pour les photos maintenant

**Comment by TheoLechemia** [comment]
C'est dans un table à part. gn_commons.t_medias. Il faut rattaché un medias à un uuid de la table pr_occtax.cor_counting_occtax.
Il y a un route pour ça aussi dans gn_commons

**Comment by Heg0Damask** [comment]
merci, j'ai trouvé la route

Une fois l'occurrence créée est ce qu'on peut intégrer les liens vers les médias directement en SQL dans la table gn_commons.t_medias ?

Dans pr_occtax.cor_counting_occtax j'ai par exemple l'occurrence **7f313ce4-c6e8-418c-80f1-3e71bfca1a52** est ce que je peux directement faire un INSERT dans la table gn_commons.t_media avec (.....,uuid_attached_row,media_path) values(...,'7f313ce4-c6e8-418c-80f1-3e71bfca1a52','static/medias/4/3_Lynx.jpg') ?

Ou bien je risque de me heurter à des problèmes de contraintes d'intégrité.

Utiliser l'API dans ce cas n'est pas très rapide car je dois aller chercher le fichier image sur un serveur et le reUploader sur le nouveau serveur via l'api, alors que je dispose d'un fichier Excel avec les chemins vers les medias.

**Comment by camillemonchicourt** [comment]
Oui bien sur qu'il est possible d'insérer des médias directement dans la BDD.
Un exemple ici : https://github.com/PnX-SI/Ressources-techniques/blob/master/GeoNature/migration/sicen_to_occtaxV2/data/insert/media.sql

A noter que si vous importer des données externes, elles peuvent avoir vocation à alimenter Occtax si on veut pouvoir les modifier ensuite.
Mais sinon, la plupart du temps, c'est plutôt la synthèse qui a vocation à recevoir les données provenant de sources diverses.

**Comment by Heg0Damask** [comment]
Je suis d'accord c'est dans la synthèse que ça devrait aller tout ça mais c'est pas moi qui décide.

**Comment by Heg0Damask** [comment]
merci
