### ISSUE TITLE
2.7.0 - Déplacement de custom.css & médias custom

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1412]
Nous avons une image d'arrière plan sur la page de login, elle est stockée dans geonature/frontend/src/custom/images. 

Depuis la maj, pas de fond et une réponse 404 lorsque le navigateur recherche sur https://geonature.flavia-ape.fr/assets/custom/images/login_background.jpg

**Comment by DonovanMaillard** [comment]
-> simplement un point de vigilance : le fichier custom.css a été déplacé et renseignait des médias avec un chemin relatif... qui n'était plus bon, forcément. Pas un soucis avec la release donc, mais un point d'attention pour ceux qui chargent des images dans leur custom.css

**Comment by camillemonchicourt** [comment]
Ajouté dans les notes de version
