### ISSUE TITLE
[2.7] - OCCTAX : "mes lieux" ne dégrise pas le formulaire

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1414]
Lors de la saisie d'un nouveau relevé sur occtax, quand l'utilisateur sélectionne un lieu dans l'onglet "mes lieux", la géométrie est bien récupérée et affichée en interface. Cependant le formulaire reste grisé comme s'il n'avait pas sélectionné/créé de géométrie.

Pour le moment on doit donc créer un point pour débloquer le formulaire, puis ensuite aller chercher sa géométrie dans "mes lieux".

**Comment by TheoLechemia** [comment]
Je ne reproduit pas en local, ni sur le serveur de test: http://51.254.242.82/geonature/#/occtax/form/releve
Est-ce que tu as un message d'erreur dans la console du navigateur quand tu charge le lieu ?

**Comment by DonovanMaillard** [comment]
Vu avec théo, problème de leaflet. Tout fonctionne bien quand le lieu est un point, pas quand c'est une ligne ou un polygone.
