### ISSUE TITLE
2.7.2 - Métadonnées - N'affiche plus tous les roles disponibles

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature#1417]
Bonjour,

J'ai remarqué que je ne peux plus saisir tous les rôles quand je souhaites ajouter un acteur à un JDD ou à un CA.
Est-ce que les normes SINP ont changé ou est-ce un problème d'affichage de la liste déroulante ? :)

![image](https://user-images.githubusercontent.com/66769358/125762338-c8559a5d-e242-42d4-ac11-a13bafed262a.png)

Merci,
Maxime

-----
**EDIT**: En résulte un problème d’affichage également avec les autres acteurs déjà présents

![image](https://user-images.githubusercontent.com/66769358/125762775-5bdce716-e3d9-4fc1-afdd-f92135262ee8.png)

**Comment by camillemonchicourt** [comment]
OK pas normal ni souhaitable selon moi.

Le standard métadonnées du SINP suggère que certains rôles soient au niveau du CA et d'autres au niveau du JDD (discuté dans https://github.com/PnX-SI/GeoNature/issues/623).

Mais je pense qu'il ne faut pas l'imposer en dur dans GeoNature. 
Car chacun peut ajouter d'autres  nomenclatures de rôles et car cela peut varier selon les contextes.

Donc je ferai sauter cette contrainte si ça a été intégré en dur dans la 2.7, ou j'en ferai un paramètre.

**Comment by maximetoma** [comment]
Dak ! Oui personnellement, il est vrai que je mets les mêmes acteurs/rôles au niveau du CA comme au niveau du JDD

**Comment by DonovanMaillard** [comment]
Bonjour,

Même remontée chez nous, on structure nos cadres par rapport au type d'étude mais nos clients/prestations sont geres au niveau du jdd. La gestion nouvelle des acteurs ne colle plus avec notre manière de ranger nos donnees (qui n'est sans doute pas exemplaire au sens du SINP par ailleurs, mais qui répond à nos besoins :) )

**Comment by TheoLechemia** [comment]
Reglé par ce commit: https://github.com/PnX-SI/GeoNature/commit/e4fd6811c4e92fb188ddf3e26c00f9e3963fcc96
Par défaut tous les types de roles sont proposés, et il est possble de les limité via les paramètres: 
`CD_NOMENCLATURE_ROLE_TYPE_DS` et `CD_NOMENCLATURE_ROLE_TYPE_AF`

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.7.3.
