### ISSUE TITLE
Les commandes flask d'installation d'un sous module ne fonctionne plus dans la version 2.7.X

### ISSUE THREAD

**Issue by metourneau** [PnX-SI/GeoNature#1418]
Bonjour,
Les commandes d'installation d'un sous module (pour le monitoring et cmr) ne fonctionne plus dans la version 2.7 de Géonature. Il faut ajouter la variable d'environnement FLASK_APP à la main pour les faire fonctionner.
export FLASK_APP=/home/`whoami`/geonature/backend/geonature/app.py

**Comment by bouttier** [comment]
Deux autres solutions :

- `export FLASK_APP=geonature`
- Lancer la commande `flask` depuis le dossier `backend/geonature` (`app.py` est alors automatiquement détecté)

Dans la prochaine release (2.7.3), toutes les commandes de `flask` (`monitoring`, `cmr` mais aussi `db`, `shell`, …) seront accessible directement avec la commande `geonature` et ce depuis n’importe où sans variable d’environnement (avec le venv activé toute de même).

**Comment by joelclems** [comment]
Quelques améliorations avec les commandes cli du module monitoring d'apres les remarques de @bouttier (chargement depuis le blueprint), mais qui ne dispensent pas encore de définir `FLASK_APP` (attendre la 2.7.3)

https://github.com/PnX-SI/gn_module_monitoring/commit/6fec06ade40da260e4e34bb6280abbe33a602df6

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.7.3.
Utiliser désormais la commande ``geonature`` plutôt que ``flask``.
