### ISSUE TITLE
La mise à jour de la configuration ne met pas à jour la config apache (2.7.2)

### ISSUE THREAD

**Issue by metourneau** [PnX-SI/GeoNature#1420]
Bonjour,
la config Apache de géonature semble contenir le ServerName.
Il n'est pas mis à jour lors d'un update de la configuration:
geonature update_configuration

**Comment by TheoLechemia** [comment]
Non, la commande geonature ne touche pas à la conf apache. Elle synchronise simplement la conf backend en frontend

**Comment by metourneau** [comment]
Ca fonctionnait bien avant, idem pour l'accès au port 4200 sur un serveur distant. Maintenant on ne peut plus y accéder.

Du coup si on modifie l'adresse du serveur, la commande update_configuration ne suffit plus pour accéder à Géonature.

**Comment by camillemonchicourt** [comment]
Oui dans la version 2.7.0 un servername a été ajouté dans la conf Apache fournie par défaut, sinon le Flask admin avait un soucis quand on utilisait GeoNature sur une adresse IP : https://github.com/PnX-SI/GeoNature/commit/af2d955987a23dc8d29e78583206ef54f1ad953a

Pour simplifier et améliorer la génération des configurations Apache lors de l'installation globale, @TheoLechemia a remplacé les multiples ``sed`` et ``echo`` dans le script d'installation globale par des templates : https://github.com/PnX-SI/GeoNature/commit/f29be09f26ef0c99f3cb9063c8e54f32de0d174f

Mais forcément avec l'ajout d'un ServerName renseigné par le script d'installation globale, si on le change dans la configuration de GeoNature, il n'est pas modifié dans la conf Apache.

Ça fonctionnait avant car il n'y avait pas de ServerName dans la configuration Apache générée par défaut.

**Comment by metourneau** [comment]
Pour info.
Pour accéder au port 4200 (en mode développement) à distance, il faut ajouter l'option "--host 0.0.0.0" dans la commande start.
Voici la commande complète dans le fichier package.json
"start": ". ~/.nvm/nvm.sh; nvm use; ng serve --poll=2000 --host 0.0.0.0 "

**Comment by camillemonchicourt** [comment]
A voir pour mentionner dans la doc concernant la modification de l'URL à répercuter dans la conf Apache.
