### ISSUE TITLE
Gestion des comptes: "ValueError: Invalid salt"

### ISSUE THREAD

**Issue by AudreyEnGuyane** [PnX-SI/GeoNature#1421]
Re-Bonjour,

En testant l'outil "Identifiant ou mot de passe oublié", je reçois un "ValueError: Invalid salt" lors de l'envoi e l'adresse mail.
Idem sur la création d'un nouveau compte.
Est-ce parce que le login/mot de passe donné dans le geonature_config [USERSHUB] ne correspond par à celui dans la base? Si oui, c'est embêtant car je l'ai écrasé...
Une autre idée d'où ça pourrait venir?

A ce sujet, comment sont codés les mots de passe pass et pass_plus? MD5? (histoire de savoir comment le regénérer...)
Mais bon, comme un  "UPDATE... pass = md5('motdepassesecret') where id_role = ...;" ne fait pas avancer le schmilblick ...

**Comment by DonovanMaillard** [comment]
Bonjour, 

Si j'ai bien tout compris dans la doc à ce sujet, les login/pass de la config [USERSHUB] servent à l'application GeoNature, en lui donnant des accès administrateur pour créer/modifier les utilisateurs dans UH. Si ces login/pass sont écrasés, l'appli ne peut plus disposer des droits nécessaires pour ces accès, UsersHub ne doit pas permettre son authentification. 

De mémoire, le champs pass est en md5 tandis que pass_plus (notamment utilisable par taxhub selon sa config) est codé en hash (voir la commande gen_salt() dans pgsql pour le hashage... je n'ai pas retrouvé l'info, mais de mémoire il me semble que c'est 13 itérations qui sont utilisées.... vague souvenir)

Si vous avez toujours vous-même accès à Usershub en administrateur, vous pouvez sans soucis créer un nouvel administrateur, lui donner les droits sur l'appli UH ou l'intégrer à un groupe qui a ces droits, définir le nouveau login/pass dans la config de GeoNature et relancer la conf de l'appli (geonature update_configuration).

**Comment by AudreyEnGuyane** [comment]
Etant donné que l'installation était récente, que j'avais fait une manip' foireuse, je n'avais plus d'accès en admin avec un login/mot de passe valide.

J'ai résolu mon problème en 
1/ contraignant le mot de passe (codé en je-ne-sais-quoi) du compte admin sur la base du script d'installation du github directement dans la base de données
2/ en modifiant le ADMIN_APPLICATION_LOGIN dans le fichier geonature_config.toml
3/ en relançant un geonature update_config
4/ et enfin en remodifiant le mot de passe directement dans GeoNature ET dans le  geonature_config.toml (donc maintenant j'ai bien le bon mot de passe qui n'est pas celui de l'installation)
5/ en relançant un geonature update_config.

Je ne sais pas si c'était la méthode la plus simple mais ça a fonctionné...
Merci Donovan!
