### ISSUE TITLE
Problème avec la 2.7.3

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1424]
Je viens de tester la MAJ vers 2.7.3 depuis la 2.7.2. A la fin de la migration j'ai l'erreur suivante: 
ERROR in src/app/metadataModule/actors/actors.component.ts(6,28): error TS2305: Module '"../services/actor-form.service"' has no exported member 'ID_ROLE_DATASET_ACTORS'.
src/app/metadataModule/actors/actors.component.ts(6,52): error TS2305: Module '"../services/actor-form.service"' has no exported member 'ID_ROLE_AF_ACTORS'.
src/app/metadataModule/services/af-form.service.ts(6,28): error TS2305: Module '"./actor-form.service"' has no exported member 'ID_ROLE_AF_ACTORS'.
src/app/metadataModule/services/dataset-form.service.ts(7,28): error TS2305: Module '"./actor-form.service"' has no exported member 'ID_ROLE_DATASET_ACTORS'.

J'ai tenté d'ajouter les nouveaux paramètres avec les cd_nomenclatures qui correspondent, l'erreur persiste.

**Comment by camillemonchicourt** [comment]
Ooops, bien vu, merci pour les tests et retours rapides.
Corrigé dans la 2.7.4.

**Comment by DonovanMaillard** [comment]
Merci pour le correctif rapide :)
