### ISSUE TITLE
Affichage - le module admin ne s'affiche qu'en rafraichissant la page

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1427]
Sur le module admin de GeoNature, sur plusieurs instances (2.7 sur Debian10), je constate le même petit bug. Le module admin s'ouvre bien quand on clique sur admin dans le menu mais la page reste grise dans un premier temps. Il est nécessaire de rafraichir la page via le navigateur pour voir apparaitre son contenu (backoffice, nomenclatures etc)

**Comment by camillemonchicourt** [comment]
Ah oui reproduit sur notre instance de production.
@TheoLechemia, tu vois d'où cela peut venir ?

**Comment by TheoLechemia** [comment]
Non, je cherche..

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.9.0
