### ISSUE TITLE
[Droit] - limiter l'accès en lecture à certain jeux de données dans la synthèse

### ISSUE THREAD

**Issue by PNPyrenees** [PnX-SI/GeoNature#1431]
Bonjour,

En l'état, est-il possible d'ajouter une "permission" dans les droits qui permettrait de définir la liste des jeux de données auquel un groupe aurait les accès en consultation dans la synthèse (ou la liste des JDD auquel il n'a pas accès) ou est-ce que ça nécessite des développements spécifiques ?

Notre base intégrant les données du SINP, L'objectif serait de permettre à des utilisateurs d'accéder uniquement à nos données.

Merci par avance !

**Comment by geobrun** [comment]
Bonjour,

Oui, si je comprends bien ta question, tu peux gérer les permissions dans le module Administration avec le CRUVED en jouant sur le scope (mes données, les données de ma structure ou les autres données).

**Comment by PNPyrenees** [comment]
En fait, c'est un peu plus profond car l'objectif est de permettre à un utilisateur d'une autre structure que la notre de pouvoir accéder à toutes les données sauf certain jeu de données (JDD intégré de partenaire ne souhaitant pas une rediffusion large)

**Comment by geobrun** [comment]
Ah, je ne pense pas que ce soit prévu pour un JDD spécifique. Par contre, tu dois pouvoir t'arranger une solution entre la gestion du CRUVED et en jouant dans le module Métadonnées (en mettant la structure de la personne en question dans les contacts du JDD). Ce n'est pas terrible comme solution mais ça devrait fonctionner je suppose.

**Comment by TheoLechemia** [comment]
Oui je confirme, ce n'est pas possible.
Il y a toujours la possibilité de bloquer l'export pour les données qui ne sont pas les siennes (E=1). Ta personne en question pourra voir les données de tous le monde mais pas les exporter.

**Comment by PNPyrenees** [comment]
En effet geobrun, c'est un contournement mais comme tu dis pas terrible surtout quand on va faire remonter nos données au SINP... 

Merci Théo pour confirmer cette impossibilité actuelle.
Je pense que je ne dois pas être le seul à avoir ce besoin, est-ce une évolution envisageable à court / moyen terme ?
Je me dit que ce n'est pas grand chose (à l'instar des "autres permissions" du type taxonomique) mais je fais peut-être erreur...

**Comment by TheoLechemia** [comment]
On est plutôt en train de travailler sur la gestion de la sensibilité / diffusion de données. Ces nouvelles permissions permettront déjà de flouter les observations sensibles, mais également de pouvoir définir un niveau de diffusion pour les données "privées" (ce qui semble être ton cas). Ton fournisseur pourra choisir de diffuser ses données à la maille (2 / 5 / 10) par exemple.
ça pourrait coller ?

**Comment by camillemonchicourt** [comment]
Sinon tu mets le CRUVED de niveau 2 à ces groupes et tu mets leur organisme avec un rôle acteur dans les JDD que tu veux qu'ils voient.

**Comment by PNPyrenees** [comment]
Théo, Je pense que ce que tu proposes pourrait correspondre si on ajoute un niveau de diffusion qui serait "pas de diffusion".
Ainsi, je pourrais attribuer cette valeur aux données des partenaires qui ne souhaitent pas que nous rediffusions leur données.
Par contre, faut qu'en interne je puisse toujours accéder à ces données de façon précise. 

Merci Camille également, mais comme vu plus haut, ce n'est pas idéal car assez contraignant au moment de la remonté des données au SINP. Mais ça peut le faire pour répondre à une urgence ou de façon temporaire.

**Comment by PNPyrenees** [comment]
Cool, ça me semble parfaitement adapté.
Merci à tous pour vos réponses et bon dev' ;)
