### ISSUE TITLE
Amélioration de la vue gn_synthese.v_synthese_for_export (champ "communes")

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature#1434]
La génération du champs "`communes`" dans la vue "`gn_synthese.v_synthese_for_export`" est assez limitant actuellement.
Les fichiers ci-dessous fournissent le SQL, le temps d'exécution ainsi que la sortie de `EXPLAIN` d'une requête simplifiée correspondant à cette vue dans une base de 9 millions de données :
- [explain_export_subquery_in_from.txt](https://github.com/PnX-SI/GeoNature/files/6924896/explain_export_subquery_in_from.txt) : c'est le fonctionnement actuel => 14s.
- [explain_export_subquery_in_select.txt](https://github.com/PnX-SI/GeoNature/files/6924898/explain_export_subquery_in_select.txt) : avec une sous-requête corrélée dans la clause SELECT => ~0,457s.
- [explain_export_subquery_with_lateral_join.txt](https://github.com/PnX-SI/GeoNature/files/6924899/explain_export_subquery_with_lateral_join.txt) : avec une sous-requête dans un LEFT JOIN LATERAL => 0,415s.

La solution a base de `LEFT JOIN LATERAL` semble être la plus pertinente à mettre en place.

**Comment by bouttier** [comment]
Fait dans #2357 qui reprend ce qui avait été initialement fait dans #1435
