### ISSUE TITLE
Filtrage des taxons

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1436]
Bonjour, 

Une petite question/réflexion... le filtrage des taxons est devenu très permissif mais pas forcément très clair (pour moi en tous cas). On peut désormais : 

- Définir une liste de taxons saisissables pour Occtax (ou ne pas en définir -> le module va chercher tout le taxref)
- Définir une liste de taxons saisissables pour un JDD (ou ne pas en définir-> on récupère la liste du module)

Que se passe-til si j'ai par exemple une liste "papillons" au niveau d'un jeu de données, que ce jeu est saisissable dans occtax, mais que la liste définie pour le module occtax ne contient pas les papillons ?

Idem sur monitoring, je définis les amphibiens au niveau du sous-module, et mon JDD saisissable dans ce sous-module comporte uniquement les oiseaux ?

Ca amène aussi pas mal de complexités pour répercuter ces multiples paramétrages et cas de figure dans la version mobile d'occtax... Je me pose la question de la pertinence de cette double entrée pour définir quels taxons sont saisissables ou non. 

A l'échelle du Jeu de données, je comprends  bien l'intérêt et la pertinence : et ça renforce l'intérêt des métadonnées en accélérant la saisie et en catégorisant mieux les choses. Cependant avec cette nouvelle possibilité, est-il toujours pertinent de définir les taxons au niveau du module de saisie ? En plus de simplifier les choses, ca assurerait que les memes taxons soient saisissables au sein d'un jeu de données, quelque soit le module de saisie utilisé (mobile, web, occurrence,suivi etc)

**Comment by TheoLechemia** [comment]
> Que se passe-til si j'ai par exemple une liste "papillons" au niveau d'un jeu de données, que ce jeu est saisissable dans occtax, mais que la liste définie pour le module occtax ne contient pas les papillons ?


Si tu as mis une liste "papillons" pour ton JDD papillons, c'est cette liste qui sera utilisé quand ce JDD est selectionné. Peut importe si la liste de taxon par defaut d'occtax ne contient pas de papillon.
Quans tu selectionne un JDD qui n'a pas de liste pas de taxon, c'est celle d'occtax qui est utilisé, si il n'y en a pas dans occtax on prend tout Taxref.

Les liste de taxon au niveau des JDD ne sont pas pris en compte dans le mobile aujourd'hui.

> Cependant avec cette nouvelle possibilité, est-il toujours pertinent de définir les taxons au niveau du module de saisie

 Si on fait sauté la liste au niveau du module, ça veut dire qu'il faudrait avoir une liste de taxon pour tout ces JDD saisissable (si on veux pas tout taxref...), ça peut être un peu chiant. Après je pense que c'est aux modules d'évoluer pour prendre en compte ce nouveau paramètre de liste de taxon au niveau du JDD, et ainsi avoir une cohérence entre les différents modules de saisi

**Comment by DonovanMaillard** [comment]
Ca marche,  merci pour tes réponses. Donc on charge en priorité la liste de taxons du JDD. A défaut celle du module. A défaut tout taxref. 

La proposition que j'ai faite sur le mobile (depit gn_mobile_core) semble donc coller et répondre à ce fonctionnement
