### ISSUE TITLE
Commons modules innaccessibles

### ISSUE THREAD

**Issue by Gaetanbrl** [PnX-SI/GeoNature#1437]
Bonjour,

Je viens d'essayer l'installation de GeoNature pour la première fois et le script s'est bien déroulé en suivant l'[installation global](https://docs.geonature.fr/installation-all.html#installation-globale). La doc est au passage très complète ;) !

J'arrive à accéder à la page principale, à me connecter en admin mais je ne vois rien dans le module "Admin".

Les modules ne semblent pas accessibles et j'ai cette erreur dans la console : 

> http://192.xxx.x.xx/geonature/api/gn_commons/modules 401 (UNAUTHORIZED)

Est-ce un problème de droits sur des répertoires ?

![moduleAdminEmpty](https://user-images.githubusercontent.com/16317988/128322868-820e554c-ec0a-4eba-99f2-1081f1747c4a.gif)

Merci

---

Os : Debian 10

**Comment by TheoLechemia** [comment]
Bonjour,
La 401 sur /modules veut dire que vous utilisez l'API sans avoir de cookie (sans être connecté).
Il y a un un bug identifié sur le module admin: en raffraichissant la page, les boutons s'affiche :
https://github.com/PnX-SI/GeoNature/issues/1427

**Comment by Gaetanbrl** [comment]
Merci du retour, le refresh affiche bien les infos.
