### ISSUE TITLE
Bugs à l'install de l'atlas avec install_all

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#144]
Précédemment, les "user" n'étaient pas changés dans les chemins du settings.ini de l'atlas. Désormais, le champ est rempli automatiquement mais avec un bug : 

communes_shp=/home/donovanLINUX/atlas/data/ref/communes.shp
limit_shp=/home/donovanLINUX/atlas/data/ref/territoire.shp

et
chemin_custom_maille=/home/donovanLINUX/atlas/data/ref/custom_maille.shp

(LINUX) en trop. 

Idem, la clé IGN ne se renseigne pas dans les 3 champs utiles dans config.py, mais seulement dans le premier.

**Comment by camillemonchicourt** [comment]
Corrigé ?
