### ISSUE TITLE
Occtax - Export des champs additionnels

### ISSUE THREAD

**Issue by metourneau** [PnX-SI/GeoNature#1440]
Si l'on décoche "Exportable" dans le backoffice des champs additionnels, en particulier pour les champs de type HTML (il pourrait être par défaut non exportable)
![image](https://user-images.githubusercontent.com/53472638/128366378-5e3309c6-5c18-4875-b5f3-b3780a8d539d.png)
Les champs apparaissent tout de même dans les exports Occtax.

**Comment by TheoLechemia** [comment]
Merci, c'est corrigé.
Par contre on laisse le default exportable à True car on veut l'enlever que pour les champs HTML à priori
