### ISSUE TITLE
Reset table utilisateur initiale

### ISSUE THREAD

**Issue by Gaetanbrl** [PnX-SI/GeoNature#1444]
Bonjour,

# Description du problème rencontré

Je parcourais usershub et suite à une modification je n'arrive plus à me logger en tant qu'admin ou via un admin que j'ai créé.

Voici mes étapes : 

* Connexion à usershub en tant que admin/admin
* Création d'un user et ajout dans grp_admin
* Decconnexion
* Connexion avec le nouveau user créé
* Modification des droits du user en cours d'utilisation >> suppression groupe admin du user

Depuis je n'arrive plus à me reconnecter à usershub via admin/admin ou via le user créé. Je ne suis plus certain à 100% de la manipulation faite, vu que je ne peux pas me reconnecter pour reproduire avec un autre user.

La connexion à /geonature est également impossible.

Un restart des serveurs à permis de retrouver la connexion admin à /geonature mais pas avec le user créé.

# Question

Comment réinstaller par défaut la DB (retourné à l'état install global) ?

Un .backup est-il disponible dans les sources Git ?

# Environnement

Dernière version Installation Globale
Debian 10

Merci.

**Comment by DonovanMaillard** [comment]
Bonjour, 

Cette question concerne plutôt UsersHub, dont le dépôt dédié est ici : https://github.com/PnX-SI/UsersHub

Vous trouverez ici le script qui intégre les données par défaut dans la base Usershub https://github.com/PnX-SI/UsersHub/blob/master/data/usershub-dataset.sql

Dans votre cas vous devriez pouvoir simplement ajouter l'utilisateur admin par défaut dans la table t_role, ou simplement mettre à jour son mot de passe.

**Comment by Gaetanbrl** [comment]
Merci @DonovanMaillard je déplace l'issue.
