### ISSUE TITLE
Erreur lors du rafraichissement de la page d'accueil

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoNature#1447]
Suite à mise à jour de la 2.6.2 à la 2.7.5, lors de l'accès à la page d'accueil (ou son rafraîchissement), j'ai systématiquement l'erreur suivante de levée mais je ne parviens pas à identifier le soucis dans le contexte de mon instance :
```
Exception on /synthese [GET]
Traceback (most recent call last):
  File "/home/adminpnrp/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adminpnrp/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/adminpnrp/geonature/backend/geonature/core/gn_permissions/decorators.py", line 70, in __check_cruved_scope
    return fn(*args, **kwargs)
  File "/home/adminpnrp/geonature/backend/venv/lib/python3.7/site-packages/utils_flask_sqla/response.py", line 19, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/adminpnrp/geonature/backend/geonature/core/gn_synthese/routes.py", line 215, in get_synthese
    feature = d.get_geofeature(fields=columns)
AttributeError: Could not locate column in row for column 'get_geofeature'
```

Je ne constate à priori aucun dysfonctionnement mais je reçois un mail d'erreur à chaque fois que la page d'accueil est actualisée...
Quelqu'un a-t'il déjà rencontré ce soucis ?
Merci d'avance pour vos lumières !
++

**Comment by bouttier** [comment]
Bonjour,
Cette vue est censé être obsolète et ne plus être appelé … Il faudrait d’ailleurs la supprimer.
Il est donc assez mystérieux pourquoi celle-ci est encore appelée …
Est-ce qu’il y a des adaptations particulières sur votre instance pouvant expliquer l’appelle à cette vue ?

**Comment by xavyeah39** [comment]
Bonjour Elie,
Merci de ta réponse. 
Non, il n'y a eu aucune adaptation particulière sur le backend de notre instance pourtant...

**Comment by DonovanMaillard** [comment]
Lappel ne peut pas venir dun module ?

**Comment by xavyeah39** [comment]
> 
> 
> Lappel ne peut pas venir dun module ?

Aucune idée... Les modules import, export et dashboard sont installés, actifs et fonctionnels mais les modules du coeur Occhab et Validation sont désactivés sur cette instance.

**Comment by xavyeah39** [comment]
> 
> 
> Cette vue est censé être obsolète et ne plus être appelé … Il faudrait d’ailleurs la supprimer.
> Il est donc assez mystérieux pourquoi celle-ci est encore appelée …

Bon en me re-penchant sur cette erreur j'avoue ne pas bien capter quelle vue n'est pas sensée être appelée ni dans qu'elle voie investiguer...

**Comment by xavyeah39** [comment]
Après avoir regardé de plus près j'ai compris d'où venait le problème : 

L'appel à cette vue (obsolète comme indiqué par @bouttier et expliqué en commentaire dans [`/geonature/backend/geonature/core/gn_synthese/routes.py`](https://github.com/PnX-SI/GeoNature/blob/00489e8c8d4f9346ac1536b8e22c648be95848da/backend/geonature/core/gn_synthese/routes.py#L184-L195)) continuait à se faire depuis la page d'accueil car je me traîne une vieille version du fichier `/geonature/frontend/src/custom/components/introduction/introduction.component.ts` depuis la version 2.0.0-rc.4.2 de 2019... 

C'est un loupé de ma part car il était bien préciser de faire ces modifs dans [les notes de version de la 2.0.0](https://github.com/PnX-SI/GeoNature/releases/tag/2.0.0) - cf : https://github.com/PnX-SI/GeoNature/commit/f55af1d03474436450cc6c32f3ceeab62509450c

Désolé pour le dérangement du coup... :)
