### ISSUE TITLE
Trigger MAJ syntheseff

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#145]
J'ai modifié un `id_organisme` dans la table `florestation.t_stations_fs` mais cela n'a pas modifié l'`id_organisme` dans `synthese.syntheseff`.

Par contre ça a bien fonctionné quand j'ai modifié les `id_organisme` dans les données des contacts faune et flore.

Trigger d'update de la synthèse à corriger ?

**Comment by gildeluermoz** [comment]
Oh oh ! Joli.
Oui c'est à corriger dans le trigger de FS. Etonnant.

**Comment by gildeluermoz** [comment]
A discuter car actuellement le trigger est uniquement prévu pour les modifications pouvant être faites depuis l'interface. Si des modifications sont faites en admin sur d'autres champs, le trigger ne fait rien.
On peut changer ça. Actuellement ça ressemble à ça :
``
IF (
            new.id_station <> old.id_station 
            OR ((new.remarques <> old.remarques) OR (new.remarques is null and old.remarques is NOT NULL) OR (new.remarques is NOT NULL and old.remarques is null))
            OR ((new.insee <> old.insee) OR (new.insee is null and old.insee is NOT NULL) OR (new.insee is NOT NULL and old.insee is null))
            OR ((new.dateobs <> old.dateobs) OR (new.dateobs is null and old.dateobs is NOT NULL) OR (new.dateobs is NOT NULL and old.dateobs is null))
            OR ((new.altitude_retenue <> old.altitude_retenue) OR (new.altitude_retenue is null and old.altitude_retenue is NOT NULL) OR (new.altitude_retenue is NOT NULL and old.altitude_retenue is null))
        ) THEN
        --on fait le update dans syntheseff
        UPDATE synthese.syntheseff 
        SET 
            code_fiche_source = 'st' || new.id_station || '-' || 'cdnom' || monreleve.cd_nom,
            insee = new.insee,
            dateobs = new.dateobs,
            altitude_retenue = new.altitude_retenue,
            remarques = new.remarques,
            derniere_action = 'u',
            the_geom_3857 = new.the_geom_3857,
            the_geom_2154 = new.the_geom_2154,
            the_geom_point = new.the_geom_3857
        WHERE id_source = 5 AND id_fiche_source = CAST(monreleve.gid AS VARCHAR(25));
    END IF;``

**Comment by camillemonchicourt** [comment]
Oui en effet un trigger est surtout intéressant si il permet de gérer la BDD indépendamment de l'interface.

**Comment by gildeluermoz** [comment]
Faut-il revenir sur la V1 à ce niveau de détail ?

**Comment by camillemonchicourt** [comment]
Non on ne corrigera pas sur la V1, mais ça sera à prendre en compte dans les triggers de la V2. Si possible avec des triggers globaux, et pas uniquement liés aux usages depuis l'interface.
