### ISSUE TITLE
Erreur à la fin du log de install_all

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#146]
Erreur à la fin du script :

```
ALTER TABLE
	Grant...
	rm: impossible de supprimer Â«Â /etc/apache2/sites-available/atlas.confÂ Â»: Aucun fichier ou dossier de ce type
	Enabling site atlas.
	To activate the new configuration, you need to run:
	  service apache2 reload
```

C'est lié au fait que le script est supprimé si il existe déjà et donc cela renvoie une erreur si il n'existe pas mais ça laisse le doute sur le bon déroulement de l'installation.

**Comment by gildeluermoz** [comment]
Sur ce genre de soucis, il faudrait enrichir le script en testant l'existence du fichier

**Comment by gildeluermoz** [comment]
Done
