### ISSUE TITLE
Module METADATADA ?

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#1466]
Je ne comprenais pas pourquoi ma config n'était pas prise en compte... J'avais fait un copie/colle du bloc depuis le fichier .example
Du coup il faut corriger `[METADATADA]` vers `[METADATA]`
https://github.com/PnX-SI/GeoNature/blob/00489e8c8d4f9346ac1536b8e22c648be95848da/config/default_config.toml.example#L495-L496

**Comment by bouttier** [comment]
Corrigé : 5dd9215c33c1e8200a4e7d5fcfb5405031299eea
