### ISSUE TITLE
[2.7.5] Envoie de l'email de récupération des mots de passe en mode PROD

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/GeoNature#1471]
En production aucun email est envoyé à l'utilisateur. Le message de succès s'affiche bien mais la post opération n'est pas réalisée.

https://github.com/PnX-SI/GeoNature/blob/00489e8c8d4f9346ac1536b8e22c648be95848da/backend/geonature/core/users/routes.py#L35
Assigne les post-opérations a réaliser suite à une action sur l'api register de pypnusershub.

Mais lors de la récupérartion valeur par le module, elle n'est plus assignée

https://github.com/PnX-SI/UsersHub-authentification-module/blob/master/src/pypnusershub/routes_register.py#L211

J'aimerais bien comprendre la différence entre le mode production et development mais en mettant la valeur directement dans current_app ça fonctionne (`current_app.config["after_USERSHUB_request"] = function_dict`).

**Comment by DonovanMaillard** [comment]
Bonjour Amandine, 

Constaté également sur une des instances sur laquelle je travaille, l'absence de mail lors des demandes de créations de comptes. Tu me confirmes que c'est le même soucis qui est derrière ?

**Comment by joelclems** [comment]
Discuté avec @amandine-sahl amandine et @bouttier ,

une solution serait de creer une variable `after_USERHUB_request = {}` dans `pypnusershub/routes_register.py` et de l'importer et de l'assigner dans `geonature/core/users/register_post_actions.py`

**Comment by amandine-sahl** [comment]
La variable s'appelle : `REGISTER_POST_ACTION_FCT` et elle se trouve dans pypnusershub/env.py

fait via : https://github.com/PnX-SI/GeoNature/commit/788cee23695dd6f2f370019d8905f41dde1d1b36
et : https://github.com/PnX-SI/UsersHub-authentification-module/commit/dc790cd4fdd2bad0ab6c22fed32a71b1ad8956e8

**Comment by Splendens** [comment]
Est-ce que ce problème impacte aussi l'envoi des liens par mail du module export ?
(Je me pose la question car je reçois des erreurs similaires lors d'une tentative de réinitialiser un mot de passe ou lors d'une tentative de téléchargement de données avec le module export.)

**Comment by amandine-sahl** [comment]
Normalement non il n'y a aucun lien entre les deux. Pour le module export ça vient plutôt d'un soucis de configuration
