### ISSUE TITLE
Validation et synthèse - proposition de Style des interfaces 

### ISSUE THREAD

**Issue by Gaetanbrl** [PnX-SI/GeoNature#1474]
Bonjour,

Nous avons remarqué que les styles des deux fiches Information de Synthèse et Validation sont proches mais ne sont identiques. Cela nous a donné l'idée de repenser légèrement le style et l'aménagement des boutons et des informations.

Par exemple, pour le module Validation, nous pensons qu'il est important de rendre davantage visible le statut.
Aussi, si des interactions sont potentiellement rajoutées, il peut être intéressant de se demander où les intégrer dans la fiche ?

Vous trouverez donc ci-dessous 3 propositions sous forme de maquette (ou concept) qui vont dans ce sens et qui permette d'harmoniser l'intégration des boutons pour les fiches des deux modules.

Merci à @Agathe21 pour ces propositions.

⚠️ **_N'hésitez-pas à partager vos remarques, améliorations ou à proposer vos idées car ces maquettes sont faites pour ça._**

- **Validation**

Ici, le statut et le taxon sont mis à l'honneur. Ce type de présentation concerne aussi la fiche de Synthèse.
Nus proposons en plus une barre d'outils pour de nouvelles fonctionnalités. Cette barre peut se fermer ou s'ouvrir (une croix est visible à droite).

![Geonature_maquette01_validationNavBar](https://user-images.githubusercontent.com/16317988/133301689-e69601d3-50f3-4481-b67f-f72ad294311b.png)

Le changement de statut peut aussi être représenté dans une modal unique avec Material Angular.

![Geonature_maquette01_validationWindow](https://user-images.githubusercontent.com/16317988/133302348-78da3fa0-418a-4af5-b6ba-303d45241828.png)

- **Synthèse**

La fiche de la Synthèse reprendrai le même concept sans les informations propres à la validation : 

![Geonature_maquette01_navbaropen](https://user-images.githubusercontent.com/16317988/133302685-0ec89e57-1930-4715-98d7-cbc39ad6ab4c.png)

**Comment by camillemonchicourt** [comment]
Intéressant oui.
Vous pouvez proposer une pull request si vous le souhaitez.

**Comment by Gaetanbrl** [comment]
C'est noté, merci du retour.

**Comment by Gaetanbrl** [comment]
J'ai entamé les travaux sur cette issue et j'ai remarqué ce code :

https://github.com/PnX-SI/GeoNature/blob/7af2c82a97675daa965024a3879c7168aca2fdb1/frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.html#L68-L70

@camillemonchicourt est-ce qu'une observation peut avoir plusieurs auteur (ou observateur) ? Quel serait l'affichage actuel si c'est le cas ?

merci

**Comment by camillemonchicourt** [comment]
Oui en effet, une observation peut avoir plusieurs observateurs. Et ceux-ci peuvent avoir ou non une email de renseigné.

Exemple actuellement : 

![Capture d’écran de 2022-02-15 18-45-29](https://user-images.githubusercontent.com/4418840/154119203-29f9cd06-0ace-45b2-9030-5a42b09d35e8.png)

**Comment by Gaetanbrl** [comment]
@camillemonchicourt merci pour ce retour. 

J'ai pu reproduire et ajouter plusieurs observateurs et je vois par contre plusieurs soucis d'affichage et de control dans le code.

**1. Observateurs sans email**

Si un ou plusieurs observateurs n'ont pas d'email, on voit une valeur vide séparées par une ",". Il se peut alors qu'aucun mail ne soit affiché. j'imagine qu'il est rare de ne pas avoir d'email pour un user, mais ce cas peut visiblement arriver.
Dans ce cas de figure, le bouton mailto est affiché mais renvoi vers aucun mail.

`<a _ngcontent-mfm-c436="" target="_blank" href="mailto:,,">`
![image](https://user-images.githubusercontent.com/16317988/154244103-bcf71a33-9162-4e8d-992b-7e29a3cdc4df.png)


**2. Un seul bouton de contact**

On ne voit qu'un seul bouton mailto alors qu'on a plusieurs email de listées entre parenthèse. Est-ce voulu ? Si oui comment savoir quel observateur doit être contacté ?

Pour que ce soit plus "esthétique" dans le cas de plusieurs observateurs, je propose de rendre cliquable le nom de l'observateur avec une tooltip "contacter cet observateur". Chaque nom est alors un lien.

Pour un mail unique, je propose de garder ce fonctionnement de mail unique avec un bouton "contact" dans la toolbar que j'insère.

![image](https://user-images.githubusercontent.com/16317988/154245222-df770d06-d924-46ba-8f83-27d41bee6e70.png)

**3. Les tooltips & traduction**

Un bon nombre de tooltip / traduction ne sont pas visibles ou affichées derrière la modal.
Pour un affichage de la tooltip, je propose d'utiliser le coposant [ngbTooltip (ng-bootstrap)](https://ng-bootstrap.github.io/#/components/tooltip/api) (voir tooltip dans la capture du point 2 précédent): 

```
      <a
        class="no-link-style"
        ngbTooltip="{{'Synthese.InpnTaxon' | translate}}"
        placement="bottom"
```

**Comment by Gaetanbrl** [comment]
> On ne voit qu'un seul bouton mailto alors qu'on a plusieurs email de listées entre parenthèse. Est-ce voulu ? Si oui comment savoir quel observateur doit être contacté ?

##Erratum 

le mailto contient plusieurs destinataires.

`mailto:test@test.fr,testa@test.fr`

https://github.com/PnX-SI/GeoNature/blob/7af2c82a97675daa965024a3879c7168aca2fdb1/frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.ts#L148-L149

**Comment by camillemonchicourt** [comment]
Oui c'est logique il me semble d'envoyer un seul email par défaut mais aux différents observateurs si ceux-ci ont un email.

**Comment by camillemonchicourt** [comment]
Selon moi on fait un seul email d'envoi à tous ceux qui ont un email et libre à l'expéditeur de ne pas garder tous les destinataires.
Et en effet il faudrait mieux gérer les cas où un observateur n'a pas d'email, qui reste un cas fréquent.

**Comment by camillemonchicourt** [comment]
Hum je ne suis pas certain, car quand on modifie le statut de validation, alors on veut ajouter une autre validation.
On ne veut pas reprendre le commentaire de la validation précédente, etc...

**Comment by Gaetanbrl** [comment]
@camillemonchicourt @bouttier @TheoLechemia voici ma proposition en image. Tous les commentaires sont bien entendu les bienvenus  :wink:

![validSynthese](https://user-images.githubusercontent.com/16317988/154463585-7bcbf97b-cc7e-42a2-b217-e4f85b7bbf83.gif)

**Comment by camillemonchicourt** [comment]
OK ouais c'est bien sympa.
Un détail mais je mettrai la Fiche GeoNature avant le Fiche INPN qui est secondaire.
Et il faut bien que le maximum de cette page reste factorisée avec la page détail du module Synthèse, c'est le cas ?

**Comment by Gaetanbrl** [comment]
> Un détail mais je mettrai la Fiche GeoNature avant le Fiche INPN qui est secondaire.

J'ai respecté l'ordre initial. Je peux l'inverser ;)

> Et il faut bien que le maximum de cette page reste factorisée avec la page détail du module Synthèse, c'est le cas ?

Tout ce qui est dans la zone de détail de l'observation est toujours dans le module `pnx-synthese-info-obs` sauf pour l'interface de choix du statut qui était initialement dans le composant de validation et qui le reste encore.

C'est un événement envoyé depuis le composant synthèse vers le composant parent de validation qui permet d'afficher de choix du statut. Ce bouton n'apparaît que si on est dans la validation.

J'ai refacto un peu de code HTML et nettoyé un peu (lignes commentées, saut de lignes...). Vous pourrez faire la revue dans la PR qui suivra. De ce côté il me reste les règles de style de code ([autres bonnes pratiques GN](https://docs.geonature.fr/development.html#pratiques-et-regles-de-developpement)) à appliquer avant la PR.

**Comment by Gaetanbrl** [comment]
En attente de test sur release pour fermeture

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.10.0.
