### ISSUE TITLE
Données géographiques manquantes

### ISSUE THREAD

**Issue by Idaline** [PnX-SI/GeoNature#1475]
Bonjour à tous !

Nous aurions besoin de faire des requêtes indiquant le département, la région et le pays des observations. Or pour le moment les colonnes nom_reg et nom_dep sont vides et nous avons pas d'information sur le pays. Est ce qu'il est prévu d'arranger ça ? Ou avez vous une solution pour l'arranger individuellement svp ? 

Merci !

**Comment by DonovanMaillard** [comment]
Bonjour, 

Pour que ces zonages soient renseignés, il faut que les types "Régions" et "Départements"soient bien présents dans votre référentiel géographique. Ils sont désormais fournis avec les installations neuves (ref_geo_departements.sql et ref_geo_regions.sql ici https://github.com/PnX-SI/GeoNature/tree/master/data/core)

Si votre instance est plus ancienne, il faut mettre à jour le ref_geo avec ces référentiels.

**Comment by camillemonchicourt** [comment]
Oui le ref_geo est fourni avec des données de base.
Comme dit Donovan il s'est enrichi dans les dernières versions.
Mais il est fait pour que ceux qui le souhaitent le complètent avec les zonages et types de zonage qu'ils souhaitent.

**Comment by joelclems** [comment]
Il manque les regions dans les données de `ref_geo` proposée par geonature et qui servent dans le script d'installation de la base https://geonature.fr/data/ign/

**Comment by camillemonchicourt** [comment]
OK je ne sais plus pourquoi car le script d'intégration des régions (non utilisé par défaut actuellement lors de l'installation de GeoNature) fait appel à un fichier qui devrait se trouver là : https://github.com/PnX-SI/GeoNature/blob/master/data/scripts/ref_geo/insert_reg.sh

**Comment by Idaline** [comment]
Ah d'accord, je vais regarder, merci. Et quand est-il d'une colonne pays (et les communes associées) ? Avec le projet COBIODIV, GéoNature doit être en train de penser à l'international ?

**Comment by camillemonchicourt** [comment]
Je comprends pas la question des colonnes ?
Il n'y a pas de colonne à ajouter.

Le ref_geo est déjà fait pour que chacun puisse y ajouter les zonages et types de zonage qu'ils souhaitent.

Tu peux ajouter un type de zonage "pays" dans la table bib_type_area et ajouter les zonages des pays que tu veux dans la table l_area.

Ensuite tu pourras même ajouter le filtre par Pays dans la Synthèse en ajoutant le type "pays" dans la conf de GeoNature, partie sur les filtres géographique de la synthese

**Comment by Idaline** [comment]
Ok, oui c'est une solution de l'ajouter dans l_areas. Je pensais l'ajouter dans la table li_municipalities.

**Comment by camillemonchicourt** [comment]
La table li_municipalities est là pour ajouter des infos particulières sur les zonages de type "Communes" dans le ref_geo, mais elle n'a aucun usage ni utilité dans GeoNature.

**Comment by Idaline** [comment]
Ah ceci explique les colonnes nom_dep et nom_reg vides dans li_municipalies... Donc toujours passer par l_areas à la place. Merci !

**Comment by Idaline** [comment]
Effectivement, le fichier appelé par https://github.com/PnX-SI/GeoNature/blob/master/data/scripts/ref_geo/insert_reg.sh (http://geonature.fr/data/ign/reg_fr_admin_express_2020-07.zip) n'existe pas.

**Comment by bouttier** [comment]
Implémenté dans d3ffb4fb554f356715fda135372bad02fbdb0aae

**Comment by camillemonchicourt** [comment]
Régions intégrées avec Alembic dans la 2.9.0.
