### ISSUE TITLE
[synthese] pb outils de recherche par jeu de données

### ISSUE THREAD

**Issue by geomatiqueltc** [PnX-SI/GeoNature#1494]
Bonjour,

Nous venons d'installer Geonature à Lannion-Trégor Communauté. Quelques 80 jeux de données en provenance de Serena et de notre atlas cartographique de la biodiversité ont été intégrés.

Depuis Synthèse, le filtre de recherche associé aux Jeux de données ne fonctionne pas. La liste des JDD apparait bien, mais il est impossible de filtrer un JDD par mot clef.

Nous avons analysé les logs de geonature et également nettoyé la table t_dataset pensant que cela pouvait être lié à une erreur dans la base. Sans succès. Auriez-vous une idée ?

Nous recherchons également le moyen d'afficher la liste des jeux de données en fonction de la sélection du cadre d'acquisition. Est ce possible ?

Cordialement
Erwan Lefeuvre
Service Geomatique de LTC

**Comment by TheoLechemia** [comment]
Bonjour,
merci pour le retour. Le bug a été corrigé pour la recherche des JDD.
Pour le filtre des JDD en fonction des CA, c'est un autre développement, vous pouvez faire un ticket séparé pour proposer cette évolution.
