### ISSUE TITLE
Mise à jour de l’interpréteur Python dans GeoNature 2.6.2

### ISSUE THREAD

**Issue by Heg0Damask** [PnX-SI/GeoNature#1495]
Bonjour,
Je viens de finaliser tout mon projet GeoNature (Youpi), mais pas de chance pour moi mon formulaire d'inscription à GeoNature utilise la classe HTTPSConnectionPool car mon serveur est maintenant en https ! Sur la version de Python installée dans GeoNature la 3.7.3 cette classe est boguée. Comment faire pour passer mon interpréteur python en version 3.7.4+ dans le VirtualEnv de geonature ? 
Je suis sur une Debian 10 avec la version 2.6.2 de GeoNature.
merci d'avance

**Comment by Heg0Damask** [comment]
ça fait une grosse erreur au niveau du pip install --editable . 

ERROR: Project file:///..../geonature/backend has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.

**Comment by bouttier** [comment]
C’est ``pip install --editable ..`` depuis le répertoire ``backend`` (ou alors ``pip install --editable .`` depuis la racine de GeoNature)

**Comment by Heg0Damask** [comment]
Erreur dans les 2 répertoires pip install --editable .. ou pip install --editable .
ERROR: file:///...geonature does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**Comment by camillemonchicourt** [comment]
Bonjour, à notre connaissance le formulaire de création de compte fonctionne en 2.6 et dans les versions suivantes.
On ne comprend pas pourquoi vous utilisez la classe ``HTTPSConnectionPool`` au niveau de Python, le SSL étant habituellement géré par Apache.
Cela ne semble pas un cas d'usage classique de GeoNature et du HTTPS ?

**Comment by Heg0Damask** [comment]
Bonjour,
C'est le formulaire de création de compte qui utilise cette classe pour faire du https, et c'est comme ça que j'ai identifié la classe.
Quand j'utilise cette classe dans un script python autonome j'ai le même message d'erreur.

**Comment by bouttier** [comment]
Bonjour,
Je n’ai trouvé aucune occurrence de la classe ``HTTPSConnectionPool`` ni dans le code de GeoNature, ni dans le code des sous-module de GeoNature (en particulier ``UsersHub-authentification-module``).
Pouvez-vous en dire plus sur où voyez vous usage de la classe ``HTTPSConnectionPool`` ?

**Comment by camillemonchicourt** [comment]
Salut, on retrouve une référence à ``HTTPSConnectionPool`` dans cet autre ticket (https://github.com/PnX-SI/GeoNature/issues/944), lui aussi lié au formulaire d'inscription (https://docs.geonature.fr/admin-manual.html#creation-de-compte)

**Comment by Heg0Damask** [comment]
J'ai essayé mais ça ne change rien du tout sur la 2.6.2.

**Comment by camillemonchicourt** [comment]
Oui oui le ticket correspond à un vieux sujet lié à la version 2.3 de GeoNature.
C'était juste pour indiquer que le ``HTTPSConnectionPool`` était déjà ressorti dans un autre ticket lié au formulaire de création de compte.

**Comment by camillemonchicourt** [comment]
On a bien testé à nouveau le module de CREATION DE COMPTES dans la version 2.9.0 sur un serveur Debian 10 avec Python 3.7.3 en HTTPS (https://demo.geonature.fr) et on n'a rencontré aucun soucis.
Hormis un petit détail d'URL dans les emails envoyés, corrigé depuis et qui sera intégré dans la prochaine version : https://github.com/PnX-SI/GeoNature/issues/1620

Je propose donc de clore ce ticket car on ne voit pas de soucis ni de raison de modifier la version de Python.
