### ISSUE TITLE
geonature db autoupgrade ne connait pas l’option -x

### ISSUE THREAD

**Issue by bouttier** [PnX-SI/GeoNature#1500]
Dans ``02_create_db.sh`` ou dans ``migrate.sh`` on fait : ``geonature db autoupgrade -x data-directory=tmp/ -x local-srid=$srid_local``
Or ``autoupgrade`` ne support pas ``-x``, du coup la commande n’est pas exécuté.
Lors de l’installation d’une 2.8.0, cela a pour conséquence que le schéma des nomenclatures n’est pas à jour, les révisions suivantes ne sont pas appliqué :
```
11e7741319fd -> f8c2c8482419 (nomenclatures) (head), fix ref_nomenclatures.get_default_nomenclature_value
6015397d686a -> 11e7741319fd (nomenclatures), fix ref_nomenclatures.get_default_nomenclature_value
```

Solution : exécuter ``geonature db autoupgrade``

**Comment by camillemonchicourt** [comment]
OK ça mérite une 2.8.1 ça.

**Comment by bouttier** [comment]
Corrigé : a806cedbfe80fb4ba1aecaf6c676f5ed9357f507
Mais oui je pense aussi que ça mérite une 2.8.1 … Ok pour la releaser dès maintenant ?
