### ISSUE TITLE
[OCCTAX] - Taxon : annuler modification

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#1508]
Me souviens plus si c'était volontaire ou non que lors d'une **modification** d'un taxon il n'y ait pas de bouton "Annuler" ?
Actuellement si on modifie d'un taxon et que finalement on décide d'abandonner toutes modifs il faut reload la page.

Alors, si modif, ajout ou pas ajout du bouton annuler ?

**Comment by camillemonchicourt** [comment]
Fait dans la 2.9.0
