### ISSUE TITLE
[2.8.1] Proxy error

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature#1514]
**Version**
2.8.1
Debian 11

**Description du bug**
Bonjour,
Lors d'une installation depuis zéro (Serveur vide) et exécution d'install_all.sh, l'installation fonctionne mais j'obtiens des proxy errors d'Apache lors des appels au backend. Si je passe sur le serveur de développement de flask, tout fonctionne.
Cela semble assez lié à #1503 

En cherchant un peu cela pourrait venir de la variable d'environnement `SCRIPT_NAME` qui permet à Flask de se situer dans les urls relatifs (si j'ai bien compris)

**Potentielle solution**
J'ai commenté toutes ces lignes (qui n'étaient pas présentes dans ma version 2.7.4) : https://github.com/PnX-SI/GeoNature/blob/1017ca1ac8ea5766b55745cf32d20cd88302bc8e/backend/geonature/app.py#L63-L70

C'est assez violent comme modification (l'option `TEMPLATE_AUTO_RELOAD` et `SEND_FILE_MAX_AGE_DEFAULT` etc. pourraient être conservées) mais maintenant tout fonctionne. Il faudrait que je teste en commentant uniquement `SCRIPT_NAME`.

Merci d'avance pour vos retours

**Comment by bouttier** [comment]
Bonjour,
Est-ce que tu peux vérifier que dans le fichier ``/etc/apache2/conf-available/geonature.conf```, il y a bien ``/geonature/api`` à la fin des directives ``ProxyPass`` et ``ProxyPassReverse`` ? Elles avait été retirées accidentellement du template …

**Comment by mvergez** [comment]
Salut Élie,
Merci pour ton retour.
Effectivement, elles sont absentes, voici ma config :
```
<Location /geonature/api>
    ProxyPass http://127.0.0.1:8000
    ProxyPassReverse  http://127.0.0.1:8000
</Location>
```
Je vais tester et te tiens au courant.

**Comment by bouttier** [comment]
J’ai cherry-pick le fix sur master et avancé le tag 2.8.1 du coup pour les suivant : e1b010cbc3101c1e6a182b7b55593f15cfae44fe

**Comment by mvergez** [comment]
Désolé je n'étais pas revenu vers toi @bouttier, ça a super bien marché merci beaucoup !
