### ISSUE TITLE
Install all sur Debian11 et authentification GeoNature

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1515]
**Version**
2.8.1

**Description du bug**
Bonjour, 

Après une installation globale (install_all) de GeoNature 2.8.1 (avec UsersHub 2.2.1) sur Debian11, je ne parviens pas à m'authentifier sur GeoNature, ni avec admin/admin, ni avec un administrateur nouvellement créé. UsersHub semble bien fonctionner, et je parviens à me connecter à TaxHub et UsersHub avec admin/admin, il me semble donc que le problème vient de GeoNature. 

Pour info, le peu de logs remontés ci-dessous :

> [2021-10-26 09:42:15 +0200] [19250] [INFO] Starting gunicorn 19.7.0
> [2021-10-26 09:42:15 +0200] [19250] [INFO] Listening at: http://127.0.0.1:8000 (19250)
> [2021-10-26 09:42:15 +0200] [19250] [INFO] Using worker: sync
> /usr/lib/python3.9/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
>   return io.open(fd, *args, **kwargs)
> [2021-10-26 09:42:15 +0200] [19273] [INFO] Booting worker with pid: 19273
> [2021-10-26 09:42:15 +0200] [19274] [INFO] Booting worker with pid: 19274
> [2021-10-26 09:42:16 +0200] [19275] [INFO] Booting worker with pid: 19275
> [2021-10-26 09:42:16 +0200] [19276] [INFO] Booting worker with pid: 19276
> [2021-10-26 09:52:39 +0200] [19276] [INFO] Worker exiting (pid: 19276)
> [2021-10-26 09:53:12 +0200] [502] [INFO] Starting gunicorn 19.7.0
> [2021-10-26 09:53:12 +0200] [502] [INFO] Listening at: http://127.0.0.1:8000 (502)
> [2021-10-26 09:53:12 +0200] [502] [INFO] Using worker: sync
> /usr/lib/python3.9/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
>   return io.open(fd, *args, **kwargs)
> [2021-10-26 09:53:12 +0200] [1051] [INFO] Booting worker with pid: 1051
> [2021-10-26 09:53:12 +0200] [1057] [INFO] Booting worker with pid: 1057
> [2021-10-26 09:53:12 +0200] [1058] [INFO] Booting worker with pid: 1058
> [2021-10-26 09:53:12 +0200] [1063] [INFO] Booting worker with pid: 1063
> [2021-10-26 11:45:43 +0200] [502] [CRITICAL] WORKER TIMEOUT (pid:1051)
> [2021-10-26 11:48:02 +0200] [541] [INFO] Starting gunicorn 19.7.0
> [2021-10-26 11:48:02 +0200] [541] [INFO] Listening at: http://127.0.0.1:8000 (541)
> [2021-10-26 11:48:02 +0200] [541] [INFO] Using worker: sync
> /usr/lib/python3.9/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
>   return io.open(fd, *args, **kwargs)
> [2021-10-26 11:48:02 +0200] [1059] [INFO] Booting worker with pid: 1059
> [2021-10-26 11:48:02 +0200] [1060] [INFO] Booting worker with pid: 1060
> [2021-10-26 11:48:02 +0200] [1062] [INFO] Booting worker with pid: 1062
> [2021-10-26 11:48:02 +0200] [1063] [INFO] Booting worker with pid: 1063

**Comment by bouttier** [comment]
Bonjour,
Tu peux vérifier que tu as bien monté la branche alembic « geonature-samples » ?
Tu devrais avoir ``3d0bf4ee67d1`` indiqué lorsque tu fais ``geonature db current``.

**Comment by DonovanMaillard** [comment]
Merci Elie pour ton retour, 

Je n'ai pas cette ligne dans db current en effet. 

C'est en lien avec le paramète add_sample_data lors de l'install all ? Si oui, en effet je l'ai passé à false pour l'install, mais du coup admin/admin existe bien et a bien les droits de lecteur sur GeoNature dans UH...

**Comment by bouttier** [comment]
Hum je dis une bêtise. Oui en effet tu ne l’as pas car tu as mis add_sample_data à False. Mais ce n’est pas nécessaire pour que admin puisse se connecter à GeoNature. Le soucis vient donc d’ailleurs …
Est-ce que tu peux regarder dans la requête de connexion que l’ID_APPLICATION est correcte ? C’est-à-dire qu’il correspond bien à l’ID_APP de GeoNature en base de données (la valeur dans la conf n’est plus utilisé).

**Comment by DonovanMaillard** [comment]
La requête json est la suivante {"login":"admin","password":"admin","id_application":1}

L'id application est correcte dans la BDD sans soucis.

**Comment by bouttier** [comment]
Ah, je n’avais pas compris qu’il y avait une erreur 500 qui se produit !
Quelle est la backtrace de cette erreur ?

**Comment by DonovanMaillard** [comment]
Outch, tu viens de me faire découvrir un coin de firefox dont je ne soupçonnais pas l'existence, mais le message me semble bon à prendre. 

Donc internal server error, avec un "point d'arrêt sur les exceptions", qui donne : 
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

**Comment by bouttier** [comment]
Je me suis mal exprimé : c’est la backtrace côté serveur qui m’intéresse ! En somme, les logs de GeoNature sur le serveur (``/var/log/geonature.log``). Si une erreur 500 ce produit, tu dois avoir un peu plus de logs que ceux que tu as transmis dans le premier message du ticket.

**Comment by DonovanMaillard** [comment]
nop, je suis allé vérifié, je n'ai rien de nouveau dans ces logs... justee ces infos, les timeout et le line buffering not supported...

**Comment by bouttier** [comment]
Est-ce que tu peux montrer tes logs apache ? Normalement ``/var/log/apache2/geonature_error.log`` et ``/var/log/apache2/geonature_access.log``.
Je suis un peu surpris par la date de tes logs aussi (2021-10-26).

**Comment by DonovanMaillard** [comment]
Pour la date des logs, j'en ai bien d'aujoutd'hui mais c'est les mêmes donc je n'ai pas remis les lignes à jour. 

Pour les logs d'apache, en effet il y a quelque chose : geonature_error.log : 

> [Wed Nov 03 14:51:21.823444 2021] [proxy:warn] [pid 60861:tid 140128500557568] [client ::1:53242] AH01144: No protocol handler was valid for the URL /geonature/api/auth/login (scheme 'https'). If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule., referer: http://localhost/geonature/


geonature_access.log : 
[03/Nov/2021:14:51:21 +0100] "POST /geonature/api/auth/login HTTP/1.1" 500 798 "http://localhost/geonature/" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"

**Comment by bouttier** [comment]
Je pense que ton problème vient d’une régression de la conf apache qui a été corrigé, peut-tu vérifier que ton ficher ``/etc/apache2/conf-available/geonature.conf`` contient bien ``http://127.0.0.1:8000/geonature/api`` et non ``https://127.0.0.1:8000`` (comme corrigé par https://github.com/PnX-SI/GeoNature/commit/6d1c3856709f5d2e0a18510875291a2786ee3544)

**Comment by DonovanMaillard** [comment]
C'était bien ça ! Merci encore pour le dépannage :) et le correctif dans la prochaine version :)
