### ISSUE TITLE
[2.8.1] - Affichage des métadonnées sur une instance neuve (sans occurence)

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1528]
**Version**
2.8.1

**Description du bug**
Sur une instance neuve sans aucune occurrence, les métadonnées créées ne s'affichent pas. 

La route http://geonature.mondomaine.fr/api/synthese/observation_count_per_column/id_dataset renvoie une erreur 404

Je n'ai pas encore testé ce comportement sur une instance qui comporte des données mais pour un utilisateur qui n'a aucun droit sur les données existantes.

**Comment by bouttier** [comment]
Pour le problème de 404, c’est réglé via https://github.com/PnX-SI/Utils-Flask-SQLAlchemy/commit/6c38d584900ea8dc2feedeae5bad69981ebd7d40
J’ai tout de même ré-écrit la vue pour la rendre un peu plus lisible et robuste : 668f4bd788710618296b340cddaa769e80c714ef

**Comment by bouttier** [comment]
En revanche je n’ai pas de soucis pour voir les JDD/CA depuis le module méta-données sur une instance sans observations dans la synthèse. Si tu parles d’un autre endroit, peux-tu préciser où t’attends-tu à voir les métadonnées.

**Comment by DonovanMaillard** [comment]
Bonjour Elie, 

Sur une install_all avec des JDD, un cruved qui autorise un utilisateur à lire ce JDD,mais aucune donnée saisie dedans, le module mtd n'affiche rien sur deux de mes instances lorsqu'elles étaient vides. Je vais voir si je reproduis à nouveau en te conservant l'instance pour vérifier tout ça... merci pour ton retour,

**Comment by bouttier** [comment]
Problème déjà repéré par Camille. À priori il s’agit d’un problème de front car les CA/JDD sont bien présent dans la réponse de l’API.

**Comment by bouttier** [comment]
Fonctionne sur la develop. Le problème repéré par Camille été dû au CRUVED qui n’était pas calculé mais c’est réglé.
Je propose de marquer cette issue résolue et d’en ré-ouvrir une si le problème est encore présent en 2.9.

**Comment by DonovanMaillard** [comment]
Ok, merci pour ton retour, je ferme :)

**Comment by camillemonchicourt** [comment]
En général, il vaut mieux fermer un ticket quand il est corrigé ou réalisé dans une release.
