### ISSUE TITLE
[Synthese] Filtres : lien entre jeu de données et cadre d'acquisition non fonctionnel

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#1530]
Le lien de filtrage entre cadre d'acquisition et jeu de données de fonctionne pas. Tous les jeux de données sont affichés, même si un cadre d'acquisition est choisi comme filtre.

**Comment by bouttier** [comment]
Quelle version ?

**Comment by camillemonchicourt** [comment]
Je ne suis pas certain qu'il y ai déjà eu un filtre entre les champs CA et JDD dans la recherche de la synthèse.

**Comment by TheoLechemia** [comment]
Si c'était le cas avant !

**Comment by TheoLechemia** [comment]
C'est déjà corrigé dans la branche develop

**Comment by gildeluermoz** [comment]
> Quelle version ?

2.7.5

**Comment by gildeluermoz** [comment]
@TheoLechemia Merci
Je ne vois pas la `class TDatasetsQuery`. Du coup je ne peux pas reporter facilement la correction dans une 2.7.5 en dépannage.
Au pire ça attendra la mise à jour vers une prochaine version.

**Comment by camillemonchicourt** [comment]
Corrigé dans la branche ``develop``, sera intégré dans la prochaine release.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.9.0
