### ISSUE TITLE
Correspondance niveau de sensibilité ↔zones pour flouter

### ISSUE THREAD

**Issue by bouttier** [PnX-SI/GeoNature#1539]
L’implémentation du floutage par @jpm-cbna introduit des paramètres de configuration ``AREA_TYPE_FOR_DIFFUSION_LEVELS`` et ``AREA_TYPE_FOR_SENSITIVITY_LEVELS``. Or GeoNature possède une table ``gn_sensitivity.cor_sensitivity_area_type`` qui vient donc en concurrence avec les paramètres introduits.

Il faut donc :
- Choisir si l’on garde des paramètres, ou si l’on garde des entrées en BDD
- Dans le cas où la BDD est retenu, voir comment étendre ``cor_sensitivity_area_type`` pour les niveau de diffusions (renommer la table et son champs de nomenclature pour la rendre plus générique peut suffir)
- Dans le cas où les paramètres de config sont retenu, il serait sans doute plus simple d’avoir une simple correspondance nomenclature → type de zone, plutôt qu’une liste de dictionnaire ayant une clef ``label`` pour la nomenclature et une clef ``area`` pour la zone, peu pratique à l’usage et nécessitant d’être re-parcouru pour chercher les informations utiles

**Comment by camillemonchicourt** [comment]
OK je n'ai plus en tête à quoi sert cette table ou ce paramètre, mais si un fonctionnement a été mis en place dans la BDD, je privilégierai plutôt celui-ci.

**Comment by jpm-cbna** [comment]
Je ne connaissais pas cette  table et ne savais pas qu'elle pourrait servir à ça. Cela marche pour la sensibilité mais, **il va falloir géré aussi le cas de la config du floutage du niveau de diffusion**...

Par contre, si nous utilisons la base pour stocker cette configuration cela nous ouvre la possibilité de rajouter des champs dans la table Synthèse pour stocker les `id_area` de floutage de la sensibilité et du niveau de diffusion. C'est ce qui avait été envisagé à l'origine avec les champs: `the_geom_4326_diffusion_level` et `the_geom_4326_sensitivity`. Voir [le cahier des charges](https://wiki-sinp.cbn-alpin.fr/fonctionnalites/geonature/developpements-prioritaires#impact_de_la_geo-confidentialite_sur_les_interfaces).
