### ISSUE TITLE
MODULARITE V2 - revoir la vue synthese.v_nomade_classe

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#154]
Cette vue n'est pas modulaire car elle fait un UNION sur les schémas des différents modules

**Comment by camillemonchicourt** [comment]
Et ne plus parler de NOMADE. 
Éventuellement MOBILE mais ici c'est plus large. 

Par ailleurs, on a discuté dans la V2 de ne plus faire des listes de groupes dans TaxHub mais de s'appuyer sur les infos de TaxRef.

**Comment by gildeluermoz** [comment]
On ne change rien dans la V1.
On devra revoir les applications Androïd pour la V2. A cette occasion, la modularité sera établie et le traitement de ce point sera fait parmi toutes les actions à entreprendre dans le cadre de ce vaste chantier.
En attendant, ce ticket ne demande pas d'action spécifique. Je le ferme
