### ISSUE TITLE
[2.7.5] update_config impossible :  No module named 'wtforms.compat'

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/GeoNature#1546]
Je viens de faire une installation globale de GeoNature 2.7.5. Lorsque je lance un `geonature update_configuration`, j'ai cette erreur : `ModuleNotFoundError: No module named 'wtforms.compat'`

J'ai pourtant fait cette même installation il y a  2 ou 3 semaines, et je n'avais pas ce problème. Est-ce que quelque chose a changé dans le fichier d'installation entre temps, ou autre ?

**Comment by camillemonchicourt** [comment]
Oui c'est normal. La version de ``WTForms`` n'était pas spécifiée dans les dépendances de la version 2.7.5 de GeoNature, ni 2.8.0. Une nouvelle version de cette dépendance non compatible avec GeoNature est sortie et est donc celle qui s'installe automatiquement.

Évoqué ici : https://github.com/PnX-SI/GeoNature/issues/1522

Une version spécifique a été forcée dans ce commit : https://github.com/PnX-SI/GeoNature/commit/52224ffe510a69205dc4fd9066b009aca048343e
Et cela a été intégré dans la version 2.8.1.

Si tu veux installer une version 2.7.5, il faut que tu reportes ce commit, en forcant une version de WTForms.
Mais pourquoi faire une nouvelle installation de GeoNature en 2.7.5 :-)

**Comment by Splendens** [comment]
Ok, merci ! J'avais pas pigé que ça se répercutait sur les versions antérieures aussi.

**Comment by christianbieche** [comment]
J'ai rajouté le module wtForms.compat dans le fichier \home\geonatureadmin\geonature_old_2.7.5\backend\requirements-common.txt
Ajout à la fin du fichier de la ligne :
WTForms==2.3.3
Et j'ai repris complétement l'installation de l'application.
Cette fois ci le module est bien pris en compte et l'application est bien en 2.7.5.
Cependant je constate des erreurs dans l'application et dans les logs.

**Comment by christianbieche** [comment]
Dans le log de l'installation j'ai trouvé le warning suivant 
/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py:1899: 
SAWarning: Implicitly combining column t_modules.meta_create_date with column t_module_complements.meta_create_date 
under attribute 'meta_create_date'.  
Please configure one or more attributes for these same-named columns explicitly.
  util.warn(msg)

Comment corriger ?

**Comment by christianbieche** [comment]
Dernière chose 
J'avais installé le module import avant de faire l'installation, mais je ne le retrouve pas dans les menus de GEONATURE.

Les images associées aux modules monitorings ont disparus.

Il y a pourtant bien les liens dans geonature mais pas l'affichage dans l'application.

  (venv) geonatureadmin@vps635946:~/geonature/external_modules$ ls -lh
  total 8,0K
  lrwxrwxrwx 1 geonatureadmin www-data 37 avril  5 15:59 import -> /home/geonatureadmin/gn_module_import
  lrwxrwxrwx 1 geonatureadmin www-data 42 avril  5 15:59 monitorings -> /home/geonatureadmin/gn_module_monitoring/
  lrwxrwxrwx 1 geonatureadmin www-data 68 avril  5 15:59 occhab -> /home/geonatureadmin/geonature/../geonature/contrib/gn_module_occhab
  lrwxrwxrwx 1 geonatureadmin www-data 58 avril  5 15:59 occtax -> /home/geonatureadmin/geonature/../geonature/contrib/occtax
  lrwxrwxrwx 1 geonatureadmin www-data 72 avril  5 15:59 validation -> /home/geonatureadmin/geonature/../geonature/contrib/gn_module_validation

une idée pour corriger ce problème ?

**Comment by DonovanMaillard** [comment]
Bonjour, 

Il y a plusieurs choses dans ces logs. 

Sur le dernier point, c'est sans doute un export shapefile fait par un utilisateur. Dans les shapefiles, les noms de colonne sont limités à 10 caractères, donc ils sont normalisés. 

La clé dupliquée date d'hier... difficile de savoir ce qu'il se passe sans connaitre l'action qui a été faite pour générer ce log. Dans tous les cas ce n'est possiblement/probablement pas lié à la mise à jour.

Pour le log 
`/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py:1899:
SAWarning: Implicitly combining column t_modules.meta_create_date with column t_module_complements.meta_create_date
under attribute 'meta_create_date'.
Please configure one or more attributes for these same-named columns explicitly.
util.warn(msg)`

C'est lié au module monitoring, une mise à jour de BDD qui n'a pas été faite totalement, ou un manque dans les scripts de MAJ (mais je crois que j'étais tombé sur cette erreur et que c'est moi qui avais manqué un fichier de maj sql). 

Quant à Rostan, soit c'est un utilisateur qui est dans votre UsersHub soit quelqu'un  sans compte a essayé de se connecter, ce qui renvoie ce log cas son compte n'existe pas?

**Comment by DonovanMaillard** [comment]
> Dernière chose J'avais installé le module import avant de faire l'installation, mais je ne le retrouve pas dans les menus de GEONATURE.
Pas normal
 
> Les images associées aux modules monitorings ont disparus.
Voir la doc du module monitoring, il existe une fonction pour recharger les images lors des mises à jour


> Il y a pourtant bien les liens dans geonature mais pas l'affichage dans l'application.
> 
> (venv) geonatureadmin@vps635946:~/geonature/external_modules$ ls -lh total 8,0K lrwxrwxrwx 1 geonatureadmin www-data 37 avril 5 15:59 import -> /home/geonatureadmin/gn_module_import lrwxrwxrwx 1 geonatureadmin www-data 42 avril 5 15:59 monitorings -> /home/geonatureadmin/gn_module_monitoring/ lrwxrwxrwx 1 geonatureadmin www-data 68 avril 5 15:59 occhab -> /home/geonatureadmin/geonature/../geonature/contrib/gn_module_occhab lrwxrwxrwx 1 geonatureadmin www-data 58 avril 5 15:59 occtax -> /home/geonatureadmin/geonature/../geonature/contrib/occtax lrwxrwxrwx 1 geonatureadmin www-data 72 avril 5 15:59 validation -> /home/geonatureadmin/geonature/../geonature/contrib/gn_module_validation
> 
> une idée pour corriger ce problème ?
voir doc monitoring

**Comment by Splendens** [comment]
> Dans le log de l'installation j'ai trouvé le warning suivant
> /home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py:1899:
> SAWarning: Implicitly combining column t_modules.meta_create_date with column t_module_complements.meta_create_date
> under attribute 'meta_create_date'.
> Please configure one or more attributes for these same-named columns explicitly.
> util.warn(msg)
> 
> Comment corriger ?

Pour ce point, la réponse est là : https://github.com/PnX-SI/gn_module_monitoring/issues/118 et c'est un problème qui est dû aux versions de GN et des modules que vous utilisez. Ce ne serait pas plus simple de passer directement aux dernières versions vu que pas mal de bugs ont été corrigés entre temps ?

**Comment by christianbieche** [comment]
> > > Dans le log de l'installation j'ai trouvé le warning suivant
> > > /home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py:1899:
> > > SAWarning: Implicitly combining column t_modules.meta_create_date with column t_module_complements.meta_create_date
> > > under attribute 'meta_create_date'.
> > > Please configure one or more attributes for these same-named columns explicitly.
> > > util.warn(msg)
> > > Comment corriger ?
> > 
> > 
> > Pour ce point, la réponse est peut-être là : [PnX-SI/gn_module_monitoring#118](https://github.com/PnX-SI/gn_module_monitoring/issues/118) et c'est un problème dû aux versions de GN et des modules que vous utilisez. Ce ne serait pas plus simple de passer directement aux dernières versions vu que pas mal de bugs ont été corrigés entre temps ?
> 
> Comme je l'ai expliqué à Camille Montchicourt. Oui pourquoi pas mais la version 4.6.2 c'est passé sans problème et là cela ne marche plus en 2.7.5
> 
> la version suivant 2.8.1 implique des grosses modifications et il faut passer quand même avant par la 2.7.5 avant pour la 2.8.0. donc je ne vois comment cela va marcher.
> 
> Du coup je ne suis pas du coup confiant. Je ne peux pas bloquer les applications pendant 15 jours dans l'attente qu'éventuellement cela fonctionne.



> > Dernière chose J'avais installé le module import avant de faire l'installation, mais je ne le retrouve pas dans les menus de GEONATURE.
> 
> Pas normal. Les versions import/geonature sont bien compatibles entre elles (dernière version de chaque?)
> 
> > Les images associées aux modules monitorings ont disparus.
> 
> Voir la doc du module monitoring, il existe une fonction pour recharger les images lors des mises à jour
> 
> > Il y a pourtant bien les liens dans geonature mais pas l'affichage dans l'application.
> > (venv) geonatureadmin@vps635946:~/geonature/external_modules$ ls -lh total 8,0K lrwxrwxrwx 1 geonatureadmin www-data 37 avril 5 15:59 import -> /home/geonatureadmin/gn_module_import lrwxrwxrwx 1 geonatureadmin www-data 42 avril 5 15:59 monitorings -> /home/geonatureadmin/gn_module_monitoring/ lrwxrwxrwx 1 geonatureadmin www-data 68 avril 5 15:59 occhab -> /home/geonatureadmin/geonature/../geonature/contrib/gn_module_occhab lrwxrwxrwx 1 geonatureadmin www-data 58 avril 5 15:59 occtax -> /home/geonatureadmin/geonature/../geonature/contrib/occtax lrwxrwxrwx 1 geonatureadmin www-data 72 avril 5 15:59 validation -> /home/geonatureadmin/geonature/../geonature/contrib/gn_module_validation
> > une idée pour corriger ce problème ?

Pour le module Import. Je fais quoi ?
Il existe dans le répertoire, en base et dans les liens.
Peut-on le supprimer pour le recréer et si oui comment ? 
je n'ai pas vu comment faire. Il est installé mais pas utilisé.

**Comment by DonovanMaillard** [comment]
La doc est bonne, avec les versions à jour. 

Il n'y a pas besoin de passer par les versions 2.7.5, 2.8.0 etc, elles n'ont pas besoin de fonctionner (chacune d'elle utilise des dépendances qui ont pu devenir obsolètes). 

Il faut suivre : 

- Les notes de version de chaque application, mais sans télécharger/installer la  version en question. Ca inclue les changements de conf apache, le passage à systemctl au lieu de supervisor, toutes les configurations obsolètes etc.
- Les modifications de la base de données, d'abord via les fichiers .sql puis ensuite ca se passera avec Alembic
- Et enfin faire le migration.sh directement vers la version 2.9.2

Les mises à jour apportent des nouvelles fonctionnalités, mais aussi et surtout corrigent les problèmes de dépendances dont vous rencontrez certaines. Etre à jour permet également de remonter des bugs qui sont toujours d'actualité, et d'utiliser les fonctions qui sont en phase avec la doc qu'on trouve sur les branches principales des différents dépots comme monitoring (sinon il faut aller voir la doc directement de la version dans laquelle vous etes). 

Il est vrai que les versions 2.8 et 2.9 sont plus lourdes à mettre à jour, mais les processus de mise à jour restent très bien documentés, cela demande donc rigueur et patience, mais rester sur des versions anciennes n'est pas supportable car vous retrouverez toujours des soucis avec la version 2.9 si vous la passez dans 1 an par exemple, et la plupart d'entre nous auront oublié/corrigé ces soucis en passant dans les versions suivantes.

**Comment by camillemonchicourt** [comment]
En effet, il n'y a pas besoin d'installer la version 2.7.5 ni autre pour passer en 2.9.0.
C'est plus simple de passer directement aux dernières versions (quelques heures) plutôt que de galérer avec des anciennes versions, sur lesquelles on n'a plus tous les sujets en tête, et où des dépendances externes ont pu bouger indépendamment de GeoNature, comme c'est le cas avec ``wtforms``.

**Comment by christianbieche** [comment]
Bon je vois. il faut que je passe en 2.9.2.
Pas persuadé que cela va se passer tout seul mais bon.
Je ne peux pas faire cela dans l'immédiat malheureusement.
Merci de vos réponses.

**Comment by camillemonchicourt** [comment]
Tu peux passer en 2.7.5 si tu veux. Elle fonctionne et a été utilisée.
Mais depuis on a corrigé et arrangé beaucoup de choses, donc on conseille de passer directement aux versions récentes.

Et nous on doit se concentrer sur les versions récentes, ce qui nous demande déjà beaucoup d'énergie et d'investissement, au-delà de nos attributions et des enjeux de nos structures.

**Comment by christianbieche** [comment]
Merci Camille, c'est ce que j'avais envisagé de faire dans l'immédiat car j'ai un besoin spécifique, pour la saisie dans occtax.
Je ferais après "tranquillement" le passage à la 9.2
Il faut que je regarde dans le détail parce que j'utilise monitoring et les applications mobiles. 
donc je dois regarder toutes les dépendances qui ne sont pas dans les notes de version.
et j'ai déjà eu des surprises, donc j'essaye de tout regarder mais la préparation est longue.
Merci

**Comment by camillemonchicourt** [comment]
Les compatibilités sont bien indiquées quand il y a des particularités.
- Par exemple la 0.2.9 du module Monitoring indique bien qu'il lui faut la version 2.9.0 ou plus de GeoNature : https://github.com/PnX-SI/gn_module_monitoring/releases. Cela sous-entend bien sur que les versions suivantes de Monitoring (par exemple la 0.2.10) nécessitent aussi au moins la 2.9.0 si rien d'autre n'est indiqué
- Idem pour Occtax-mobile où on indique bien les versions compatibles quand il y a des particularités : https://github.com/PnX-SI/gn_mobile_occtax/releases

Que cela soit "long" est relatif. Pour certains cela prend quelques heures, pour d'autres plus.

On met de l'énergie pour le collectif à faire tout ça, au-delà de nos besoins, mais toute contribution ou amélioration est bienvenue.

Il faut bien entendu un serveur de test, comme ça on peut tester ça tranquillement avant de passer en production.

**Comment by christianbieche** [comment]
Je regarde en plus le fichier versions-compatibility.rst du répertoire ./docs de l'application GEONATURE
