### ISSUE TITLE
Association JDD-Liste taxons / Problème si ID et code différent

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#1549]
Retour de @AmelieTagliaferro :

L'association d'un JDD à une liste de taxons fonctionne bien, mais il faut être attentif lors de la création de la liste : 
les listes taxhub ont un ``id_liste`` et un ``code_liste`` dont le denier est modifiable par les admin.

Si les deux ne correspondent pas, lors du rattachement de la liste au JDD, il y aura un problème dans le module occtax pour aller chercher les informations dans la liste.  

Description du jdd associé à la liste et la seconde image en bleue est l'extrait de taxhub pour la liste en question : 
![idliste](https://user-images.githubusercontent.com/93383491/144572459-de02580f-1d34-475b-bebf-81b56c36a51f.png)

Sans modifier ces valeurs, il m'était impossible d'appeler les noms de la lsie sur taxhub en me référant au jdd créé alors qu'une fois les deux (code et id) égaux, j'ai pu entre des espèces provenant uniquement de la liste créée.
![liste taxhub](https://user-images.githubusercontent.com/93383491/144572474-df57ff6b-ec38-48f9-90b7-724e2c55a60c.png)

Parce que le JDD appelle l'id-liste qui peut si le gestionnaire TaxHub l'a fait être différent du ``code_liste``.

**Comment by camillemonchicourt** [comment]
Ce n'est pas normal.
L'id_liste et le code_liste sont fait pour être différents.
Il doit y avoir un soucis au niveau de Occtax ou GeoNature qui doit s'embrouiller entre id_liste et code_liste.
A vérifier.

**Comment by DonovanMaillard** [comment]
J'ai constaté le même soucis sur une de mes instances, la route api/taxref/allnamebylist/CODE?search_name=castor&limit=20 semble effectivement fonctionner avec le code et pas avec l'ID, alors que la correspondance dataset/list se fait sur l'ID de la liste de taxons. 

Il semblerait plus logique que la route fonctionne avec l'ID ?

**Comment by camillemonchicourt** [comment]
Le soucis semble venir d'une évolution au niveau de TaxHub 1.8.0 où un ``code_liste`` a été ajouté dans la table des listes, et la route attend désormais un ``code_liste`` mais Occtax lui envoie un ``id_liste``.

Voir https://github.com/PnX-SI/TaxHub/issues/346

**Comment by camillemonchicourt** [comment]
Retour en arrière dans la version 1.13.1 de TaxHub (nécessitant GeoNature 2.14 ou plus) en rebasant la route sur des `id_liste` - https://github.com/PnX-SI/TaxHub/issues/346
