### ISSUE TITLE
Pas de redirection sur la page de login après expiration de la session

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#1550]
**Version 2.7.5**

**Description du bug**
Quand la session expire, on devrait être redirigé vers une page de login. Mais visiblement ça ne le fait pas (voir capture d'écran ci-dessous). En se déconnectant explicitement avec le bouton et en se reconnectant ça fonctionne normalement. 

**Comportement attendue**
Redirection vers la page de login si la session est expirée

**Comment reproduire**
Laisser expirer une session (la nuit par exemple) et rouvrir l'url geonature le lendemain.
![unnamed](https://user-images.githubusercontent.com/10024739/144825709-76a24634-2a21-4157-82b4-fb84ada09404.png)

**Comment by camillemonchicourt** [comment]
J'ai constaté le même soucis sur le branche ``develop``.
Je ne sais pas si c'est vraiment quand ma session expire et/ou quand je me connecte sur UsersHub en parallèle sur le même navigateur.
En tout cas dans ce second cas, ça me fait le problème à chaque fois.

**Comment by bouttier** [comment]
Peut-être un conflit de cookie « token » ? Est-ce que vous êtes sur des sous-domaines différents, ou sur le même domaine avec un préfixe ?

**Comment by camillemonchicourt** [comment]
Dans mon cas c'était sur notre serveur de TEST sur une IP et des préfixes.
Mais le soucis est que quand la session est expirée cela ne renvoie pas au formulaire de login mais sur la Home de GeoNatire chargée partiellement.

**Comment by TheoLechemia** [comment]
J'ai recherché un peu aussi, c'est quand le cookie est "corrompu" qu'il y a ce comportement.
Quand il est absent ou trop vieux, la redirection est bonne.

**Comment by bouttier** [comment]
J’ai l’impression que ça vient de cette ligne : https://github.com/PnX-SI/GeoNature/blob/master/frontend/src/app/services/unauthorized.interceptor.ts#L19
Quelqu’un a une idée de pourquoi y’a cette exception ?
Sinon je l’enlève …

**Comment by gildeluermoz** [comment]
Depuis que je suis passé sur la 2.8.1, Je ne reproduis plus le soucis et je n'ai pas eu de retour du client en ce sens. Donc difficile à dire.
La conf DNS est sur des sous-domaines.
Merci

**Comment by bouttier** [comment]
Bon j’ai enlevé la ligne dont je parlais et en fait ça a cassé le mécanisme de redirection après login vers la page que l’on demandait. Mais c’est pas claire pourquoi ce problème se pose, il va falloir investiguer …
En attendant je pense rollback le fix, et donc on aura de nouveau cette erreur, mais elle me semble moins génante que casser la redirection.

**Comment by camillemonchicourt** [comment]
Oui en effet

**Comment by antoinececchimnhn** [comment]
Je suis d'accord avec @bouttier que la ligne coupable de la non redirection est . En revanche effectivement quand on la retire on a des erreurs. En revanche en retirant également cette ligne : https://github.com/PnX-SI/GeoNature/blob/master/frontend/src/app/services/unauthorized.interceptor.ts#L26 ça semble fonctionner. https://github.com/PnX-SI/GeoNature/blob/master/frontend/src/app/services/unauthorized.interceptor.ts#L19

Pour aller plus loin, je pense d'ailleurs que ce composant seul suffit, et que le check du cookie null devrait être supprmée (canActivate*) dans ce fichier https://github.com/PnX-SI/GeoNature/blob/master/frontend/src/app/routing/routes-guards.service.ts

**Comment by camillemonchicourt** [comment]
OK n'hésite pas si tu as testé et veut faire une PR.

**Comment by bouttier** [comment]
Hum, je pensais que le throw empty était justement là pour ne pas exécuter en plus le routes-guards … à moins que ça s’éxecute pas dans le bon sens ? Mais ouais si tu as un fix, envoie !

**Comment by antoinececchimnhn** [comment]
C'est fait 

Je pense que ce n'est pas qu'une question d'ordre, en effet le route-guards se "contente" de vérifier que le token n'est pas nul. Or le pb de redirection semble venir d'un token existant mais périmé/corrompu

**Comment by bouttier** [comment]
Corrigé par @antoinececchimnhn dans #1572
Le empyt() amené à executer le success du get, plutôt que le error (à cause de la 404), d’où des comportements inattendue.
