### ISSUE TITLE
[2.8.1] - Jeux de données personnel auto-générés non associés à Occtax par défaut

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1555]
**Version**
2.8.1

**Description du bug**
Par défaut, les jeux de données auto-générés lors de la création de comptes ne sont pas rattachés à Occtax. Ils sont donc créés mais non utilisés dans la pratique, sauf intervention d'un admin.

**Comportement attendue**
Rattachement automatique des jdd personnels au module Occtax

**Comment reproduire**
Créer un compte avec un JDD généré automatiquement

**Logs**
-

**Comment by camillemonchicourt** [comment]
C'était le cas avant quand la création de compte a été mise en place ?
Je n'en trouve pas de trace ?

**Comment by DonovanMaillard** [comment]
Je ne sais pas du tout sur les versions antérieures, à priori j'imagine que ça n'a jamais été le cas ? Mais c'est obscur pour les utilisateurs comme pour les admins, d'activer la création du JDD, de valider la personne, mais que le jeu ne soit pas dispo à la saisie.

**Comment by camillemonchicourt** [comment]
Oui il est possible que cette fonctionnalité de création de JDD automatiquement ait été faite avant que l'on ajoute le fait de devoir associer les JDD aux modules pour pouvoir y saisir (quand on a intégré le module Occhab).
Et à ce moment-là, la fonctionnalité de création automatique de JDD n'a pas été reprise à ce niveau pour pouvoir définir le (ou les) module(s) à associer par défaut aux JDD crées.

C'est le cas pour MTD : https://github.com/PnX-SI/GeoNature/blob/master/config/default_config.toml.example#L138-L141

Il faudrait donc faire pareil pour les JDD créés automatiquement, avec un paramètre pour définir le(s) module(s).
Ce n'est pas un bug mais une évolution.

**Comment by jbrieuclp** [comment]
Je me demande si je n'avais pas créé un trigger pour ça à l'époque. Marie (Splendens) m'a reparlé de ça qui est toujours en stand by.

**Comment by camillemonchicourt** [comment]
Oui ce ticket est redondant avec https://github.com/PnX-SI/GeoNature/issues/913
Et en complément, à élargir au fait de pouvoir définir en paramètre si ils sont validables ou non par défaut : 
- https://github.com/PnX-SI/GeoNature/issues/1099 qui est aussi en doublon avec https://github.com/PnX-SI/GeoNature/issues/975 :-)

A vos PR ! :-D

**Comment by camillemonchicourt** [comment]
> Edit : il y avait bien un trigger qui ajoute une ligne jdd/module occtax dans la table module_dataset, mais ce n'est pas la solution car lors de la creation d'un JDD depuis l'appli, si on spécifie le module occtax dans le liste de module associés, le trigger générera un doublon et l'enregistrement plantera. Il faut donc ajouter le module coté backend lors de la creation du compte et du JDD associé.

A priori en défrichant les précédents tickets, le trigger n'est pas fourni dans GeoNature, mais ajouté à la main sur ton instance. Et en effet, comme discuté dans l'autre ticket, il faudrait gérer ça au niveau Python (avec les paramètres et les tests qui vont bien) plutôt qu'en trigger.

**Comment by bouttier** [comment]
Done in 3ebf09937854056e1e8f6022a03248fb83b8d7b1
