### ISSUE TITLE
Installation packagée 2.8.1 : reférentiel de sensibilité non intégré dans gn_sensitivity

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoNature#1576]
Salut,
Après une install fraîche de la 2.8.1 sur un serveur debian10, (taxhub 1.9.2 et usershub 2.2.2), les tables du schéma `gn_sensitivity` sont vide et les données du référentiel national n'ont pas été intégrées.
Ai-je raté quelque chose ? Est-ce possible de rattraper ça en SQL.
Merci de vos retours !

**Comment by bouttier** [comment]
Bonjour,
Effectivement le référentiel de sensibilité a été perdu lors du passage à Alembic.
Il a été depuis remis dans la version en cours de développement et sera présent dans la v2.9 que l’on espère sortir aujourd’hui.
Il sera alors possible d’installer ces règles avec :
``geonature db upgrade ref_sensitivity_inpn@head``
Ceci sera spécifié dans le changelog :
https://github.com/PnX-SI/GeoNature/blob/028093b49fabc24ca6eb8cc2a45beb5cb74b9a88/docs/CHANGELOG.rst

**Comment by xavyeah39** [comment]
Ok merci !
Ce sera l'occasion de tester l'upgrade en 2.9 ;)
Bon courage pour la release !
