### ISSUE TITLE
Faire une doc d'insertion des données métiers des utilisateurs

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#16]

**Comment by camillemonchicourt** [comment]
Un exemple de déploiement et d'intégration de données historiques a été réalisé sur la 1.8.0 : http://geonature.readthedocs.io/fr/latest/install_all/2016-12-exemple-deploiement-pnr.html#integration-des-donnees-existantes-dans-geonature

A adapter et faire dans une doc générique dans la V2.

**Comment by camillemonchicourt** [comment]
Fait dans la V2 avec une présentation générale et 2 exemples détaillés : https://geonature.readthedocs.io/fr/latest/admin-manual.html#integrer-des-donnees
