### ISSUE TITLE
2.9.0 - Problème URL de réinitialisation du mot de passe

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#1620]
On vient de tester le module de création de compte sur la 2.9.0 de GeoNature, en l'activant sur le serveur de DEMO : https://demo.geonature.fr/geonature.
Tout fonctionne bien, la création d'un compte, l'envoi d'email, création automatique d'un CA et d'un JDD (associé par défaut à Occtax), gestion du compte, modification du MDP, réinitialisation du MDP

Par contre j'ai vu un soucis dans l'URL envoyée dans l'email de réinitialisation du MDP : https://demo.geonature.fr/geonature#/new-password?token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Il manque un / après "geonature' dans le lien généré

**Comment by camillemonchicourt** [comment]
C'est du au fait que le lien est généré à partir du paramètre ``URL_APPLICATION`` et qu'il n'y avait pas de "/" au début de la suite de l'URL. Corrigé avec https://github.com/PnX-SI/GeoNature/commit/3c9248414558d18b3accee0cc0db9c8b38ce6215

**Comment by mtaqarort** [comment]
Malgré la correction sur la version 2.9.1, le problème persiste encore (test fait aussi sur demo.geonature.fr), le lien envoyé par mail renvoie sur la page de connexion.

il faut copier manuellement le lien reçu et le coller **deux fois** sur le navigateur pour arriver au formulaire de réinitialisation de mdp !!
