### ISSUE TITLE
Simplifier le CRUVED minimum pour accéder à GeoNature et aux modules

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#1622]
Jusqu'à la 2.9.0, la page d'accueil et le menu listant les modules vérifiait obligatoirement le R du CRUVED de l'utilisateur connecté sur "GeoNature" devant être supérieur à 0.

Donc si on voulait créer un compte simple avec accès à seulement un ou 2 modules (compte associé à l'accès public par exemple), il fallait obligatoirement lui attribuer un CRUVED sur GeoNature dont héritait alors tous les modules, créer un CRUVED sur les modules auxquels l'utilisateur devait avoir accès, mais aussi sur tous les autres modules pour spécifier explicitement que l'utilisateur n'y a pas accès, car sinon il héritait de l'accès à tous les modules lié au CRUVED de GeoNature.

Il serait préférable de ne pas imposer un CRUVED sur "GeoNature" mais de pouvoir uniquement spécifier un CRUVED sur le module auquel on souhaite qu'il puisse accéder.

**Comment by DonovanMaillard** [comment]
D'une manière générale, je me pose de plus en plus la question personnellement sur cette notion d'héritage 

Dans la pratique je me dis que ca apporte finalement plus de flou dans la lisibilité des droits des uns et des autres, que de bénéfices. 

Devoir expliciter les droits de chaque groupe sur chaque module permettrait dy voir plus clair, et qu'un nouveau module ke soit accessible par personne par défaut aussi, que d'installer un module et devoir reprendre son cruved pour savoir qui peut y faire quelle action. Quitte à avoir un bloc "tous les modules" explicite. Qui permettent d'accorder les mêmes  droits par defaut sur tous les modules.

**Comment by camillemonchicourt** [comment]
Oui à l'usage il y a un consensus sur le fait de supprimer l'héritage des permissions dans GeoNature.
On avait fait ça pour simplifier la gestion des permissions mais en fait ça la complexifie et la rend moins lisible.

Je pense qu'on l'a évoqué dans d'autres tickets mais en effet on aimerait supprimer cet héritage.

Là c'est déjà un premier pas en n'imposant plus un CRUVED du GeoNature pour pouvoir accéder à GeoNature et sa page d'accueil.

**Comment by camillemonchicourt** [comment]
Fait avec les PR et commits : 
- https://github.com/PnX-SI/GeoNature/pull/1621
- https://github.com/PnX-SI/GeoNature/commit/e86d81001254a27bff869a353ad9e3be81d7a50b

Désormais on ne vérifie plus le R du CRUVED de l'utilisateur sur le module "GeoNature" pour l'accès à la page d'accueil ni à la liste des modules.
On vérifie uniquement que l'utilisateur peut accéder à GeoNature avec un login et mot de passe corrects.

Sur la page d'accueil, on vérifie si l'utilisateur a un R>0 sur Synthèse (ou GeoNature par héritage si pas de CRUVED défini sur Synthèse) pour lui afficher ou non la carte des 100 dernières observations et les statistiques globales de la page d'accueil. Et désormais les statistiques globales se basent sur le R de Synthèse (ou le R de GeoNature par héritage si l'utilisateur n'a pas de CRUVED sur Synthèse mais en a un sur GeoNature).
