### ISSUE TITLE
Fichier de log trop volumineux

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#1627]
**Version**
2.8.1

**Description du bug**
Le fichier geonature.log fait 33Go après 3 mois de fonctionnement
![image](https://user-images.githubusercontent.com/10024739/150029044-dc1a2c89-68c4-4244-9457-357dfc1bfd3e.png)

**Comportement attendue**
rotation des logs

**Comment by bouttier** [comment]
Il faut effectivement remettre le logrotate suite au déplacement des logs dans ``/var/log``.

Ou alors passer aux journaux binaire de systemd qui gère ça en interne et qui prennent beaucoup moins de place sur le disque :

- Commenter les lignes ``StandardOutput`` et ``StandardError`` dans ``/etc/systemd/system/geonature.service``
- ``systemctl daemon-reload``
- ``systemctl restart geonature``
- Pour consulter les logs : ``journalctl -lu geonature``
- Pour afficher les 50 dernières lignes de log puis afficher en directe les nouvelles lignes : ``journalctl -lu geonature -n 50 -f``

**Comment by camillemonchicourt** [comment]
OK à clarifier car je ne vois pas de trace dans le changelog quand on aurait déplacé les logs.

La doc est bien à jour (https://docs.geonature.fr/admin-manual.html#logs), mais chez nous on a toujours des logs qui s'écrivent dans /home/myuser/geonature/var/log/gn_errors.log.
Ainsi qu'un dossier /home/myuser/geonature/var/log/gn_export/cron.log.

Je pense que cela a changé avec la 2.8.0 et le passage de supervisor à systemd ?

Pour la rotation des logs, en effet c'est embêtant. 
Il faudrait la mettre en place automatiquement lors de l'installation ou utiliser directement les journaux binaires et voir comment l'appliquer pour ceux qui sont déjà passés en 2.8.
Et adapter la documentation si besoin.

**Comment by DonovanMaillard** [comment]
oui, changé dans la 2.8 avec systemd ;)

**Comment by gildeluermoz** [comment]
J'ai appliqué la procédure proposée par @bouttier en attendant un fonctionnement stabilisé.
Sur une autre instance qui tourne depuis qq jours (avec 3 observations exemples dans la base), les logs font 14 Ko...
Je ne sais pas ce qui s'est produit sur l'instance avec 33Go de log mais effectivement il faut remettre en place la rotation des logs et une limite de taille car visiblement geonature peut produire beaucoup de log.
Et comme le dit Camille, il faut mettre ça en place à l'install sinon, ça peut finir par bloquer le serveur si le disque se rempli totalement.

**Comment by bouttier** [comment]
systemd supprime les vieux logs pour toujours laisser un certain % d’espace disque disponible :-)

**Comment by Splendens** [comment]
J'allais ouvrir une issue sur la taille des logs, mais je profite celle là ! 
Lorsqu'on télécharge des données en shapefile (pas csv et geojson) depuis la synthèse, la génération de toute l'extraction est loggée, ce qui a vite fait de faire des fichiers de log monstrueux. Par exemple, après le téléchargement de 5000 observation, j'ai un geonature.log de plus de 3Go.

**Comment by camillemonchicourt** [comment]
Rotation des logs remise en place dans la version 2.10.0
