### ISSUE TITLE
Utilisation de ID_APPLICATION_GEONATURE

### ISSUE THREAD

**Issue by RNF-SI** [PnX-SI/GeoNature#1635]
Versions :
Geonature : 2.9.0
Taxhub : 1.9.3
UsersHub : 2.2.2 

Bonjour, 

J'essaye de configurer 2 GeoNatures, qui fonctionneraient sur le même usershub. 
J'ai tenté de faire un FDW sous postgres, pour récupérer le schéma "utilisateurs" de mon instance A vers l'instance B. 
Mais j'ai une erreur 500 ensuite pour la connexion à mon instance B. 
Un classique `SELECT * FROM utilisateurs.t_roles` marche bien que le schéma soit natif ou en FDW. 

Je me suis dit ensuite que le problème venait peut être des autorisations des utilisateurs vers une application. J'ai donc essayé de comprendre comment fonctionnent les applications dans UsersHub. 
J'ai ajouté le GeoNature de mon instance B (id:4) dans les applications sous UsersHub. 
J'ai ensuite modifié le paramètre `ID_APPLICATION_GEONATURE=4` dans geonature_config.toml et fait un update_configuration. 
Aucune erreur apparente à cet instant. 

En voulant relancer update_configuration pour d'autres modifications, j'ai maintenant le message d'alerte "Warning: unable to find GeoNature application, database not yet initialized?" puis un message d'erreur : 

```
Generating frontend routing
Generating frontend routing
...ok


...ok


Update app configuration
Update app configuration
Generating configuration
Generating configuration
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 33, in <module>
    sys.exit(load_entry_point('geonature', 'console_scripts', 'geonature')())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/main.py", line 160, in update_configuration
    update_app_configuration(build)
  File "/home/geonatureadmin/geonature/backend/geonature/utils/command.py", line 144, in update_app_configuration
    create_frontend_config()
  File "/home/geonatureadmin/geonature/backend/geonature/utils/command.py", line 132, in create_frontend_config
    'ID_APPLICATION_GEONATURE': current_app.config['ID_APP'],
KeyError: 'ID_APP'
```

J'ai essayé d'aller modifier geonature/frontend/src/conf/app.config.ts avec `"ID_APPLICATION_GEONATURE": 4` mais pas plus de succès

Comment rétablir ça (remettre ID_APPLICATION_GEONATURE=1 peut être mais comment relancer update_configuration) ?

Comment paramétrer les applications pour gérer les droits depuis le seul UsersHub de mon instance A ?

Merci pour vos retours!

**Comment by camillemonchicourt** [comment]
Oui, jamais testé mais ça devrait fonctionner.
Dans UsersHub, il faut bien que chaque GeoNature ait un id_application différent et que tu indiques bien le ``ID_APPLICATION_GEONATURE`` correspondant dans la conf de chaque GeoNature.

Et ensuite pour prendre en compte les modifications de la configuration, il faut lancer les commandes dédiées : https://docs.geonature.fr/admin-manual.html#configuration-generale-de-l-application

Attention, après le ``geonature update_configuration`` il faut lancer ``sudo systemctl restart geonature``, c'est bien ce que tu as fait ?

Si tu as une erreur 500, il nous faudrait les éventuelles erreurs remontées dans la console du navigateur mais surtout les logs d'erreur de GeoNature (https://docs.geonature.fr/admin-manual.html#logs).

**Comment by RNF-SI** [comment]
Oui j'ai bien relancé le service geonature (j'utilise `sudo service geonature restart` mais on est d'accord que c'est la même chose ?)

Le problème c'est que maintenant que j'ai voulu changé le `ID_APPLICATION_GEONATURE` je ne peux plus faire de `geonature update_configuration` (voir le message d'erreur plus haut). Même si je remet 1. 

Pour ce qui est des logs pour la connexion, les voicis : 

```
[SQL: SELECT utilisateurs.v_userslist_forall_applications.pass AS utilisateurs_v_userslist_forall_applications_pass, utilisateurs.v_userslist_forall_applications.pass_plus AS utilisateurs_v_userslist_forall_applications_pass_plus, utilisateurs.v_userslist_forall_applications.id_role AS utilisateurs_v_userslist_forall_applications_id_role, utilisateurs.v_userslist_forall_applications.nom_role AS utilisateurs_v_userslist_forall_applications_nom_role, utilisateurs.v_userslist_forall_applications.prenom_role AS utilisateurs_v_userslist_forall_applications_prenom_role, utilisateurs.v_userslist_forall_applications.id_application AS utilisateurs_v_userslist_forall_applications_id_applicati_1, utilisateurs.v_userslist_forall_applications.id_organisme AS utilisateurs_v_userslist_forall_applications_id_organisme, utilisateurs.v_userslist_forall_applications.identifiant AS utilisateurs_v_userslist_forall_applications_identifiant, utilisateurs.v_userslist_forall_applications.id_droit_max AS utilisateurs_v_userslist_forall_applications_id_droit_max 
FROM utilisateurs.v_userslist_forall_applications 
WHERE utilisateurs.v_userslist_forall_applications.identifiant = %(identifiant_1)s AND utilisateurs.v_userslist_forall_applications.id_application = %(id_application_1)s]
[parameters: {'identifiant_1': 'admin', 'id_application_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2022-01-20 14:25:54 +0100] [409671] [CRITICAL] (psycopg2.errors.UndefinedObject) ERREUR:  correspondance utilisateur non trouvée pour « geonatadmin »

[SQL: SELECT utilisateurs.v_userslist_forall_applications.pass AS utilisateurs_v_userslist_forall_applications_pass, utilisateurs.v_userslist_forall_applications.pass_plus AS utilisateurs_v_userslist_forall_applications_pass_plus, utilisateurs.v_userslist_forall_applications.id_role AS utilisateurs_v_userslist_forall_applications_id_role, utilisateurs.v_userslist_forall_applications.nom_role AS utilisateurs_v_userslist_forall_applications_nom_role, utilisateurs.v_userslist_forall_applications.prenom_role AS utilisateurs_v_userslist_forall_applications_prenom_role, utilisateurs.v_userslist_forall_applications.id_application AS utilisateurs_v_userslist_forall_applications_id_applicati_1, utilisateurs.v_userslist_forall_applications.id_organisme AS utilisateurs_v_userslist_forall_applications_id_organisme, utilisateurs.v_userslist_forall_applications.identifiant AS utilisateurs_v_userslist_forall_applications_identifiant, utilisateurs.v_userslist_forall_applications.id_droit_max AS utilisateurs_v_userslist_forall_applications_id_droit_max 
FROM utilisateurs.v_userslist_forall_applications 
WHERE utilisateurs.v_userslist_forall_applications.identifiant = %(identifiant_1)s AND utilisateurs.v_userslist_forall_applications.id_application = %(id_application_1)s]
[parameters: {'identifiant_1': 'admin', 'id_application_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)
{"type": "bug", "msg": "Unkown error during login"}
[2022-01-20 14:25:54 +0100] [409671] [INFO] {"type": "bug", "msg": "Unkown error during login"}
```

**Comment by camillemonchicourt** [comment]
C'est ton FDW qui semble pas bon.
``ERREUR:  correspondance utilisateur non trouvée pour « geonatadmin »``.

Ton application B essaie de se connecter avec l'utilisateur de BDD ``geonatadmin`` à l'application A (ou l'inverse), mais tu as pas du mapper cet utilisateur de BDD au niveau de ton FDW, ou un truc du genre.

**Comment by RNF-SI** [comment]
En effet, j'avais pas compris que la commande 

```
CREATE USER MAPPING FOR USER SERVER bdd_geonature_global
    OPTIONS ("user" 'geonatadmin', password 'monmdp');
```

renvoyait par défaut le USER courant. Et comme il faut être sous postgres pour le faire, ça a fait un user postgres... 
Il faut donc faire : 

```
CREATE USER MAPPING FOR geonatadmin SERVER bdd_geonature_global
    OPTIONS ("user" 'geonatadmin', password 'monmdp');
```

Ok pour ça. Mais du coup comment je fais pour résoudre le `Warning: unable to find GeoNature application, database not yet initialized?` ?

**Comment by camillemonchicourt** [comment]
Oui je m'embrouille toujours avec les FDW, je m'étais fait une petite doc pour m'y retrouver : https://github.com/PnX-SI/Ressources-techniques/blob/master/PostgreSQL/FDW.rst

Pour le message c'est un warning, je ne suis pas certain que cela soit un problème, je sais pas.

Corrige le FDW, applique les modifications de la config, vois ce que ça donne et dis nous.

**Comment by RNF-SI** [comment]
Oui c'est bon pour le FDW, j'ai remis ID_APPLICATION_GEONATURE=1 dans geonature_config.toml parce que c'est ce qui avait bugué, mais je ne peux pas appliquer les modifications à cause de cette erreur... j'ai toujours 

```
Generating frontend routing
Generating frontend routing
...ok


...ok


Update app configuration
Update app configuration
Generating configuration
Generating configuration
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 33, in <module>
    sys.exit(load_entry_point('geonature', 'console_scripts', 'geonature')())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/main.py", line 160, in update_configuration
    update_app_configuration(build)
  File "/home/geonatureadmin/geonature/backend/geonature/utils/command.py", line 144, in update_app_configuration
    create_frontend_config()
  File "/home/geonatureadmin/geonature/backend/geonature/utils/command.py", line 132, in create_frontend_config
    'ID_APPLICATION_GEONATURE': current_app.config['ID_APP'],
KeyError: 'ID_APP'
```

**Comment by RNF-SI** [comment]
Un commentaire de @bouttier dans l'issue #1527 précise :  

"Le paramètre ID_APPLICATION_GEONATURE étant désormais récupéré dynamiquement et non plus à partir de la config, il faut le récupérer depuis curent_app.config au lieu de l’objet config importé."

Du coup c'est une erreur de ma part d'avoir voulu le remettre dans `geonature_config.toml` ? Où le configurer donc ?

**Comment by camillemonchicourt** [comment]
Ah OK, je ne sais pas trop, j'ai pas tout suivi.
Si c'est le cas, c'est à indiquer dans la doc et les exemples de configuration.

Possible que ce paramètre n'ai plus d'usage et qu'ils prenne dynamiquement l'application qui a pour code "GN". Dans ce cas ça va pas faire ton affaire en l'état, ou alors d'avoir qu'une seule application "GN" utilisée par tes 2 applications...
Et donc si c'est le cas, que l'on ne configure plus de id_applications et que tu veux que chaque GN soit distingué dans ton UsersHub, il va falloir remettre un paramètre en place pour que l'on puisse paramétrer un CODE_APPLICATION à utiliser et ne pas utiliser en dur celui qui a le code_application "GN".

Mais ton soucis vient potentiellement de là, si c'est maintenant l'application qui a le code "GN" qui est utilisée dans tous les cas...

**Comment by RNF-SI** [comment]
Effectivement ça ressemble donc à ça... je n'avais plus de GN dans mes applications (j'avais GNG et GNS), et là j'ai remodifié GNG en GN, et le update_configuration à refonctionné. 
Merci pour ton aide. 
Embêtant ce changement dans mon cas effectivement...

**Comment by camillemonchicourt** [comment]
OK on va voir pour rendre le code_application customisable

**Comment by RNF-SI** [comment]
Super merci 👍

**Comment by camillemonchicourt** [comment]
Fait ici : https://github.com/PnX-SI/GeoNature/commit/dc713683561f861cbacd7d00a37de727d0c16593
Sera intégré dans la prochaine release.
En attendant, si tu en as besoin, tu peux reporter cette évolution sur ton serveur et utiliser ce nouveau paramètre ``CODE_APPLICATION``, surcouchable dans le fichier ``config/geonature_config.toml``.

**Comment by RNF-SI** [comment]
Quelle efficacité ! Merci pour la rapidité de mise en œuvre !

**Comment by Gaetanbrl** [comment]
>Oui je m'embrouille toujours avec les FDW, je m'étais fait une petite doc pour m'y retrouver : https://github.com/PnX-SI/Ressources-techniques/blob/master/PostgreSQL/FDW.rst

En complément Dalibo a publié [un billet](https://public.dalibo.com/exports/formation/manuels/modules/v2/v2.handout.html) sur les connexions distantes Foreign data wrappers (FWD) PostgreSQL.
