### ISSUE TITLE
Accès public à Géonature

### ISSUE THREAD

**Issue by metourneau** [PnX-SI/GeoNature#1650]
**Version**
Version 2.8.1

**Description du bug**
Est ce possible d'avoir un accès public via URL, sans devoir cliquer sur le bouton "Accès public"?

Les paramètres ont été ajoutés afin d'avoir un accès public à l'application, mais je ne trouve pas comment accéder à l'application via une URL (type geonature.fr?acces=public). Il me semblait que l'OEB avait mis à disposition le code pour l'implémenter.

**Comment by camillemonchicourt** [comment]
Cette fonctionnalité a été mise en place ici : https://github.com/PnX-SI/GeoNature/issues/1323
En s'inspirant de https://github.com/MathieuLagarde/GeoNature/blob/geofit/oeb/frontend/src/app/components/auth/auth.service.ts qui n'avait pas été contribué et de manière plus générique.

Oui bonne idée de pouvoir directement passer par un lien qui évite la page de login.
Je ne crois pas que cela soit possible actuellement, mais toute contribution est bienvenue.

**Comment by TheoLechemia** [comment]
Logiquement si dans l'url, tu as partagé la page à laquelle tu veux accéder : 
ex : 127.0.0.1/#/occtax
tu sera redirigé vers /occtax après avoir cliqué sur le boutton "accès public"

**Comment by camillemonchicourt** [comment]
Oui mais là l'objectif est de pouvoir accéder à la page d'accueil de GeoNature directement sans passer par la page de login.
Comme ils avaient fait sur https://data.biodiversite-bretagne.fr/accueil, quand tu cliques sur la loupe, où ça t'ouvre directement GeoNature dans le module Synthèse (en restant dans l'atlas).

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.11, mais semble ne pas fonctionner en production, ou aléatoirement.

**Comment by camillemonchicourt** [comment]
Voir la PR de doc : https://github.com/PnX-SI/GeoNature/pull/2230
Et la PR de correction : https://github.com/PnX-SI/GeoNature/pull/2312
