### ISSUE TITLE
[2.9.1] Problème de mise à jour : gn_profiles innexistant

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature#1669]
**Version**
2.9.1

**Description du bug**
Le module Validation retourne une erreur 500.
En creusant un peu, le schéma gn_profiles n'a pas été créé suite à la montée de version.

**Comment reproduire**
Mise à jour de la 2.8.1 à la 2.9.1 directement, sans installer la 2.9.0.

**Logs**
Extrait du fichier ``/geonature/var/log/gn_errors.log``: [gn_errors.log](https://github.com/PnX-SI/GeoNature/files/7958869/gn_errors.log)

**Comment by camillemonchicourt** [comment]
Il ne semble y avoir aucune erreur récente dans ces logs.
Mais si j'ai bien suivi, les logs sont désormais dans ``/var/log/geonature.log``

Il y a eu des erreurs indiquées lors de la procédure de mise à jour de GeoNature ?

**Comment by maximetoma** [comment]
Ah oui effectivement ! Désolé, voici le bon fichier : [geonature.log](https://github.com/PnX-SI/GeoNature/files/7958999/geonature.log)

**Comment by bouttier** [comment]
Le schéma de base de données est-elle bien à jour ? Que donne la commande ``geonature db autoupgrade`` ?

**Comment by camillemonchicourt** [comment]
Ouais alors pas mal d'erreurs dans celui-ci, par exemple : 

```
ERREUR:  la colonne t_additional_fields.default_value n'existe pas
```

Remonté de nombreuses fois, alors que cette évulition est faite par Alembic dans https://github.com/PnX-SI/GeoNature/blob/master/backend/geonature/migrations/versions/1eb624249f2b_add_default_value_in_additionalfields_.py

Puis : 

```
ERREUR:  la relation « gn_profiles.vm_valid_profiles » n'existe pas
```

Aussi fait dans une migration Alembic.
Donc tes migrations Alembic ont eu un soucis (bizarre) ou alors elles n'ont pas été exécutées.

**Comment by maximetoma** [comment]
@bouttier La commande me renvoi ceci :
[geonature_db_autoupgrade.txt](https://github.com/PnX-SI/GeoNature/files/7959100/geonature_db_autoupgrade.txt)

@camillemonchicourt ah... comment on peut réappeler la migration ? pour gn_profiles, ça va même jusqu'à la non-existence du schéma :)

**Comment by camillemonchicourt** [comment]
On peut les relancer avec ``geonature db autoupgrade`` donc c'est fait :-)
Il faut éplucher les logs que tu viens d'envoyer.

**Comment by camillemonchicourt** [comment]
Ah bah non pas grand chose dans ces logs. Là je sais pas, je laisse @bouttier compléter ce qu'il faut faire.

**Comment by bouttier** [comment]
Hum, j’aimerai bien comprendre comment tu as fini avec les champs additionnels créées en base, mais sans qu’alembic en ait connaissance. Aurais-tu fais des choses à la main qui pourrait l’expliquer ?

**Comment by maximetoma** [comment]
Peut-être... Il y a eu un blocage assez long au bout d'un moment et j'ai refresh la base pour voir si ça venait de là.... Peut-être un peu trop barbare......

**Comment by camillemonchicourt** [comment]
C'est pas toi qui aurait créé à la main le champs bib_organismes.additional_data ?
Une migration Alembic essaie d'ajouter ce champs mais dit que ce champs existe déjà...

**Comment by maximetoma** [comment]
Euh alors pas sur cette MAJ... Mais c'est peut-être possible, j'ai souvenir d'avoir du rajouter une colonne sur une précédente MAJ, après je ne sais plus si c'était sur bib_organismes mais plutôt une autre table
En tout cas oui le colonne existe en base, est-ce que si je la supprime et relance `geonature db autoupgrade` ça marchera ?

**Comment by bouttier** [comment]
Ça me semble la meilleur chose à tenter.

**Comment by camillemonchicourt** [comment]
Oui ça devrait au moins réussir à passer cette migration, et donc les suivantes qui créeront gn_profiles, etc...
Mais c'est sur que si on touche sa BDD, il faut bien l'avoir en tête et le faire en connaissance de cause, sinon les scripts qu'on fait pour la mettre à jour vont coincer. A éviter ou à tracer en connaissance de cause.

Autre question. Qu'entends-tu par ``refresh la base`` ? Tu as redémarré PostgreSQL pendant qu'une requête longue de mise à jour était en train de s'exécuter ?

**Comment by maximetoma** [comment]
C'est bon merci beaucoup ! Ca venait de ça de cette colonne....
Je pensais qu'il s'agissait une colonne qui n'avait pas réussie à se créer mais ça devait ne pas être le cas ? En tout cas, oui j'éviterai à l'avenir et en cas de doute je posterai un ticket :)

@camillemonchicourt Et oui c'est bien ça... Je pense bien que c'est en aucun cas une bonne manip à faire.... Je ne voyais malheurement pas comment stopper la requête...

**Comment by bouttier** [comment]
Je relativise la gravité du redémarrage de postgresql, alembic effectuant la mise-à-jour du schéma dans une transaction, donc cela évite de retrouver la base dans un état inconsistant.
