### ISSUE TITLE
maj 2.9.0 blocage de la commande geonature db autoupgrade

### ISSUE THREAD

**Issue by maki2a** [PnX-SI/GeoNature#1671]
**Version**
Version de GeoNature affectée par le bug. 2.9.0

Après mise à jour de geonature 2.7.5 en version 2.9.0 (mise à jour aussi de taxhub et usershub) j'ai finalisé par le passage à alembic. En fin de note de version en 2.8.0, j'ai lancer la commande geonature db autoupgrade qui commence bien par mettre à jour la base mais qui bloque sur une mise à jour (j'ai laissé tourner tout le weekend).
La commande geonature db current donne:
(venv) geonatureadmin@geonat21:~/geonature$ geonature db current
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
0dfdbfbccd63 (head)
3fdaa1805575 (effective head)
46e91e738845
62e63cd6135d (effective head)
6afe74833ed0
f5436084bf17 (effective head)
2984569d5df6 (effective head)
ede150d9afd9 (head)
f61f95136ec3 (effective head)
96a713739fdd (effective head)
3842a6d800a0 (effective head)
4fb7e197d241 (effective head)
72f227e37bdf (effective head)
7d6e98441e4c (head)
944072911ff7 (head)
1715cf31a75d (effective head)
a763fb554ff2 (effective head)
6015397d686a
fa35dfe5ff27
f06cc80cc8ba
586613e2faeb (head)

et la commande geonature db autoupgrade 
(venv) geonatureadmin@geonat21:~/geonature$ geonature db autoupgrade
Context impl PostgresqlImpl.
Will assume transactional DDL.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 6015397d686a -> 11e7741319fd, fix ref_nomenclatures.get_default_nomenclature_value
INFO  [alembic.runtime.migration] Running upgrade 11e7741319fd -> f8c2c8482419, fix ref_nomenclatures.get_default_nomenclature_value
INFO  [alembic.runtime.migration] Running upgrade f8c2c8482419 -> b820c66d8daa, fix ref_nomenclatures.get_nomenclature_label
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 6afe74833ed0 -> e0ac4c9f5c0a, add indexes on FK referencing l_areas.id_area
INFO  [alembic.runtime.migration] Running upgrade fa35dfe5ff27 -> 830cc8f4daef, add additional_data field to bib_organismes

Je n'ose pas relancer brutalement le serveur car la console ne répond  pas et reste bloquée sur cette dernière ligne.

**Comment by camillemonchicourt** [comment]
OK cela ressemble à un autre ticket discuté vendredi #1669
Avez-vous lancer ces commandes sur une 2.8.0 ou sur une 2.9.0 ?

Pouvez-vous partager les logs de GeoNature ? Dans /var/log/geonature.log

**Comment by maki2a** [comment]
Bonjour,
J'avais lu ce ticket donc je me suis abstenu de faire un reboot brutal.
La commande a été lancée sur une 2.9.0 (passage de la 2.7.5 à la 2.9.0)
Les logs geonature:

[2022-01-28 15:38:48 +0100] [20711] [INFO] Starting gunicorn 20.1.0
[2022-01-28 15:38:48 +0100] [20711] [INFO] Listening at: http://127.0.0.1:8000 (20711)
[2022-01-28 15:38:48 +0100] [20711] [INFO] Using worker: sync
[2022-01-28 15:38:48 +0100] [20714] [INFO] Booting worker with pid: 20714
[2022-01-28 15:38:48 +0100] [20715] [INFO] Booting worker with pid: 20715
[2022-01-28 15:38:48 +0100] [20716] [INFO] Booting worker with pid: 20716
[2022-01-28 15:38:48 +0100] [20718] [INFO] Booting worker with pid: 20718
[2022-01-28 16:46:03 +0100] [20711] [CRITICAL] WORKER TIMEOUT (pid:20714)
[2022-01-28 16:46:04 +0100] [20711] [WARNING] Worker with pid 20714 was terminated due to signal 9
[2022-01-28 16:46:04 +0100] [22052] [INFO] Booting worker with pid: 22052
[2022-01-31 08:50:20 +0100] [20711] [CRITICAL] WORKER TIMEOUT (pid:20715)
[2022-01-31 08:50:21 +0100] [20711] [WARNING] Worker with pid 20715 was terminated due to signal 9
[2022-01-31 08:50:21 +0100] [33581] [INFO] Booting worker with pid: 33581

Ce qui correspond bien au fait que j'ai lancé lacommande db autoupgrade 2 fois

**Comment by camillemonchicourt** [comment]
On pense que c'est simplement la BDD qui est lockée car en cours d'utilisation par ailleurs ou autre et qui bloque donc une migration (ajout du champs ``additional_data`` sur ``bib_organismes``).
On vous conseille donc de restart les services des applications UsersHub, TaxHub et GeoNature (``sudo systemctl restart nomapplication``) puis relancer le db autoupgrade. Les migrations seront finalisées proprement car Alembic gère bien de ne pas laisser la BDD dans un état intermédiaire.

Si ça ne suffit pas, redémarrer PostgreSQL (puis les services des différentes applications).

Tenez-nous au courant.

**Comment by camillemonchicourt** [comment]
Plutôt que restart les applications, on dirait même de stopper les applications (``sudo systemctl stop nomapplication``) pour bien les delocker, puis lancer le db autoupgrade. Et quand il est finit start les applications (``sudo systemctl start nomapplication``).

**Comment by maki2a** [comment]
J'ai un problème d'accès à mon serveur hébergé au rectorat de corse.
J'applique les restart dès que possible

**Comment by maki2a** [comment]
[pb_db_autoupgrade.txt](https://github.com/PnX-SI/GeoNature/files/7976603/pb_db_autoupgrade.txt)
Bonjour,
Après le db autoupgrade j'ai une erreur:La clé (id_dataset)=(2) n'est pas présente dans la table « t_datasets
Ci dessus la copie complète du terminal.
Faut-il bidouiller à la main la base pour rajouter une clef dans la table t_datasets?
Le serveur fonctionnait correctement en 2.7.5, seul les imports de plus de 1000 données plantaient.

**Comment by camillemonchicourt** [comment]
Oui là c'est clair, il y a un soucis dans vos données qui bloque une migration vu le message : 
```
psycopg2.errors.ForeignKeyViolation: ERREUR:  une instruction insert ou update sur la table « cor_dataset_territory » viole la contrainte de clé
étrangère « fk_cor_dataset_territory_id_dataset »
DETAIL:  La clé (id_dataset)=(2) n'est pas présente dans la table « t_datasets ».
```

La migration en question est : https://github.com/PnX-SI/GeoNature/blob/master/backend/geonature/migrations/versions/5f4c4b644844_delete_cascade_cor_dataset_territory.py

Elle ajoute la suppression en cascade sur le champs ``id_dataset`` de ``gn_meta.cor_dataset_territory``

```
ALTER TABLE gn_meta.cor_dataset_territory
        ADD CONSTRAINT fk_cor_dataset_territory_id_dataset FOREIGN KEY (id_dataset) 
        REFERENCES gn_meta.t_datasets(id_dataset) ON UPDATE CASCADE ON DELETE CASCADE;
```

Donc ce que je comprends c'est que dans la table ``gn_meta.cor_dataset_territory`` vous avez une ligne qui fait référence au JDD ayant comme identifiant 2, mais que celui-ci n'existe plus dans la table ``gn_meta.t_datasets``.
Ce JDD a du être supprimé sans que sa référence dans ``gn_meta.cor_dataset_territory`` ne soit supprimé. C'est justement pour ça qu'on ajoute la suppression en cascade.
Il faut donc que vous supprimiez la ligne qui fait référence au JDD ayant ``id_dataset``=2 dans la table ``gn_meta.cor_dataset_territory``, puis relancer l'autoupgrade.
A voir si d'autres données sont concernées.

**Comment by maki2a** [comment]
Après huit suppressions dans cette table, l'autoupgrade a fonctionné.
Merci pour votre aide
Pour la suite, j'ai besoin de mettre à jour le module import, d'installer le module export et de mettre à jour geonature en version 2.9.1.
Dans quel ordre vaut-il mieux faire ces màj?

**Comment by camillemonchicourt** [comment]
OK super. Merci pour les retours.
Si vous êtes en 2.9.0 l'ordre n'est pas important. 
Mais en effet il faut mettre à jour les modules dans leurs versions compatibles avec la 2.9

**Comment by maki2a** [comment]
Dernière question:
Le serveur est en debian 10, dois-je le faire passer en version 11?

**Comment by camillemonchicourt** [comment]
Non car le module IMPORT n'est pas encore bien compatible avec Debian 11.
Il vaut mieux attendre un peu.

**Comment by maki2a** [comment]
Merci encore et bonne journée
