### ISSUE TITLE
[2.9.1 - métadonnées] liste de saisie non alimentée dans les JDD

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/GeoNature#1672]
**Version**
GeoNature 2.9.1 et TaxHub 1.9.4

**Description du bug**
Exactement comme ces deux issues ; https://github.com/PnX-SI/GeoNature/issues/1632 et https://github.com/PnX-SI/GeoNature/issues/1438 , les listes de saisies ne remontent pas dans le champ  "Liste de taxons (facultatif)" des fiches JDD.

(La route  https://taxhub.mondomaine.com/api/biblistes/ renvoi bien toutes mes listes de taxons.)

**Comment by camillemonchicourt** [comment]
La version 2.9.1 était censée corriger cela. Testé OK de notre côté.
Tu as vérifié dans la console du navigateur si la route interrogée par l'application était la bonne ?

**Comment by Splendens** [comment]
On voit ça où ?
Il n'y a pas d'erreur dans la console, et dans "network" je n'ai rien pour les listes de taxons.
![Capturemtf](https://user-images.githubusercontent.com/19465859/151810864-8431cb3f-fa29-4e26-9f7d-b23bb72d76ac.PNG)

(Quand j'ajoute une liste au JDD directement en BD, il y a le comportement attendu dans OccTax, le problème est uniquement dans les fiches de métadonnées).

**Comment by Splendens** [comment]
Histoire de comparer, j'ai regardé ça avec différentes versions de GN (accès en sous-domaine pour GN et TaxHub + https).

- Avec la 2.7.5, pas de pb particulier, la liste des taxons est chargée dans la fiche JDD.
- Avec la 2.8.1, la liste n'est pas chargée, et il y a une erreur dans la console :
`Mixed Content: The page at 'https://geonature.mondomaine.fr/#/metadata/dataset' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://taxhub.mondomaine.fr/api/biblistes/'. This request has been blocked; the content must be served over HTTPS.`

- Avec la 2.9.0 et la 2.9.1, la liste des taxons n'est pas récupérée dans la fiche JDD, mais pas d'erreur en console.

**Comment by camillemonchicourt** [comment]
OK pour l'erreur remontée en 2.8.1 le soucis vient du fait que ton GN est en https mais pas TH, donc c'est ton navigateur qui bloque l'appel et non pas GN.

**Comment by Splendens** [comment]
J'accède pourtant à Taxhub en Https, ça avait même posé problème lors de la migration de 2.7.5 à 2.8.1 (https://github.com/PnX-SI/GeoNature/issues/1516)

**Comment by Splendens** [comment]
Pardon, j'ai oublié de préciser : j'ai bien mis ce paramètre dans la conf de taxhub

```
APPLICATION_ROOT = '/'
# Set this to 'https' if you use encryption
PREFERRED_URL_SCHEME = 'https'

```

**Comment by Splendens** [comment]
Je viens de passer l'accès à taxhub sur /taxhub (`https://geonature.mondomaine.com/taxhub`). Même constat : tout fonctionne (occtax, taxhub, etc.) mais toujours pas de listes de taxons dans les fiches JDD.

**Comment by joelclems** [comment]
Le problème n'est pus présent dans develop 

https://github.com/PnX-SI/GeoNature/blob/bedfa19007c4016c535773266f3321b3a610e2a8/frontend/src/app/GN2CommonModule/form/data-form.service.ts#L164-L167

mais toujours présent dans la 2.9.1 ou dans master

https://github.com/PnX-SI/GeoNature/blob/7af2c82a97675daa965024a3879c7168aca2fdb1/frontend/src/app/GN2CommonModule/form/data-form.service.ts#L163-L166

**Comment by camillemonchicourt** [comment]
OK la PR https://github.com/PnX-SI/GeoNature/pull/1616/files était censé réglé le soucis intégré dans la 2.9.1, mais ce n'est donc pas le cas...

Je ne vois pas ce qui a été fait depuis la ``develop`` qui ne serait pas dans la 2.9.1.
Sachant que la ``develop`` contient le passage à Angular version 12.

**Comment by bouttier** [comment]
De ce que tu montres @joelclems, la correction a bien été intégré dans la 2.9.1 (ajout du « / »). La différence que l’on voit est, sauf erreur, une correction lié au passage à Angular 12.
De ce que je comprend de ce que dit @Splendens, il ne s’agit pas du même problème : la requête n’est même pas effectué dans son cas.
Le problème est reproduit sur https://demo.geonature.fr/geonature/ (2.9.1)

**Comment by joelclems** [comment]
c'est cette ligne qui pose pb et qui renvoie une liste vide (cf d44101d)

https://github.com/PnX-SI/GeoNature/blob/7af2c82a97675daa965024a3879c7168aca2fdb1/frontend/src/app/GN2CommonModule/form/data-form.service.ts#L164

**Comment by bouttier** [comment]
Oups bien vu, j’ai mergé ta PR dans hotfixes.
