### ISSUE TITLE
[métadonnées] Ajout d’un bouton pour supprimer un cadre d’acquisition

### ISSUE THREAD

**Issue by bouttier** [PnX-SI/GeoNature#1673]
Actuellement, seul les jeux de données peuvent être supprimé.
Note : il ne sera possible de supprimer un cadre d’acquisition uniquement si celui-ci n’a pas de jeux de données associés.

**Comment by gildeluermoz** [comment]
Après une installation toute neuve, les cadres d'acquisition exemples ne peuvent pas être supprimés. Notamment le CA habitat.
Il faut le faire en base. Ce que l'utilisateur ne peut pas faire via l'interface.
A noter que ce CA habitat est créé avec 2 champs obligatoires non renseignés et sans acteur. Si on souhaite le modifier, il faut au préalable renseigner ces champs pour que le bouton enregistrer soit actif.

**Comment by JulienCorny** [comment]
Est-ce que cette fonctionnalité est planifiée dans une prochaine release ? ou le travail commencé sur une branche ?

**Comment by camillemonchicourt** [comment]
Non pas prévu, mais ça serait une bonne chose.

**Comment by edelclaux** [comment]
Salut ! 
Le code amène plusieurs questions

## Trace de la possibilité de suppression
On trouve à tous les étages les méthodes permettant la suppression d'un cadre d'acquisition.
Côté front: 
- module metadata: https://github.com/PnX-SI/GeoNature/blob/2108176e5a00ad8b904bcb24de3d8786ffbdf4ba/frontend/src/app/metadataModule/metadata.component.ts#L173
- data form service: https://github.com/PnX-SI/GeoNature/blob/2108176e5a00ad8b904bcb24de3d8786ffbdf4ba/frontend/src/app/GN2CommonModule/form/data-form.service.ts#L589

Côté back:
- route de suppression: https://github.com/PnX-SI/GeoNature/blob/2108176e5a00ad8b904bcb24de3d8786ffbdf4ba/backend/geonature/core/gn_meta/routes.py#L784
- is deletable: https://github.com/PnX-SI/GeoNature/blob/2108176e5a00ad8b904bcb24de3d8786ffbdf4ba/backend/geonature/core/gn_meta/models/aframework.py#L124

Côté test: 
- test de la suppression: https://github.com/PnX-SI/GeoNature/blob/2108176e5a00ad8b904bcb24de3d8786ffbdf4ba/backend/geonature/tests/test_gn_meta.py#L207


**Qu'est-ce qu'il s'est passé ? Est-ce que ça a été possible à un moment, puis retiré ? Pour quelles raisons ? C'est quoi le piège :D** 

## Critère "is_deletable"

Le critère actuel de détermination de la possibilité de suppression ou non, "is_deletable", est le suivant:
```python
def is_deletable(self):
    return not (
        db.session.scalar(
            exists()
            .select_from()
            .where(TDatasets.id_acquisition_framework == self.id_acquisition_framework)
            .select()
        )
    )
```

Il me semble qu'il faut contrôler également la parentalité du CA avant de le supprimer. S'il est parent, et qu'un autre CA le référence, il ne doit pas pouvoir être supprimé. 

Est-ce que vous confirmez ?  Est-ce que vous pensez à d'autres critères ?

## List

Il y a deux méthodes utilisées pour lister des cadres d'acquisitions: 
- get_acquisition_frameworks: https://github.com/PnX-SI/GeoNature/blob/2108176e5a00ad8b904bcb24de3d8786ffbdf4ba/backend/geonature/core/gn_meta/routes.py#L524
- get_acquisition_frameworks_list: https://github.com/PnX-SI/GeoNature/blob/2108176e5a00ad8b904bcb24de3d8786ffbdf4ba/backend/geonature/core/gn_meta/routes.py#L597

La seconde est marquée comme dépréciée depuis un an et demi (< 2.12 il me semble).

Est-ce effectivement le cas ? Qu'est-ce qui a empêché sa suppression ?

**Comment by camillemonchicourt** [comment]
Selon moi, le seul élément à vérifier côté front et back est qu'on ne puisse supprimer un CA que si il n'a pas de JDD associé. Et si il n'a pas de CA enfant en effet.

**Comment by edelclaux** [comment]
> Selon moi, le seul élément à vérifier côté front et back est qu'on ne puisse supprimer un CA que si il n'a pas de JDD associé. Et si il n'a pas de CA enfant en effet.

Je penche pour faire la vérification côté back, et transmettre au front le résultat du calcul du critère via un booleén (is_deletable, ou quelque chose comme ça). Ca permettrait de centraliser la logique.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.15
