### ISSUE TITLE
Retour utilisation foreign schema utilisateurs

### ISSUE THREAD

**Issue by RNF-SI** [PnX-SI/GeoNature#1675]
Suite de l'issue #1635 

Avec les modifications du code_application de la release 2.9.1, j'ai donc pu paramétrer mes deux GeoNature dans un seul UsersHub. 
J'ai mis en place un foreign schéma dans mon GeoNature B qui pointe vers mon GeoNature A. 
L'authentification se fait sans problème et sans perte de performance à priori, mais sur des applications vierges à ce jour. 

Le problème est venu lorsque j'ai voulu paramétrer le CRUVED de mon GeoNature B, j'ai eu cette erreur en voulant valider mes paramètres : 
```
ERREUR:  une instruction insert ou update sur la table « cor_role_action_filter_module_object » viole la contrainte de clé
étrangère « fk_cor_r_a_f_m_o_id_role »
DETAIL:  La clé (id_role)=(14) n'est pas présente dans la table « t_roles ».
```

En fait, en allant voir dans ma base de données, je me suis rendu compte que la foreign key « fk_cor_r_a_f_m_o_id_role » pointe vers ma table utilisateurs_old.t_roles (j’avais renommé mon schéma initial utilisateurs au cas où), dans laquelle il n'y a donc pas le role en question. 
J’ai voulu changer ça mais bien logiquement il est impossible de d’avoir une foreign key qui pointe vers une foreign table (ni même vers une vue matérialisée d’ailleurs, j’ai regardé au cas où). 

Ma seule solution a donc été de faire sauter cette contrainte. 
Je n’ai pas eu d’erreur à la validation, mais mes paramètres n'étaient pas pris en compte par GeoNature.

Il a fallu que je change également la vue `gn_permissions.v_roles_permissions` afin de remplacer les `utilisateurs_old` par `utilisateurs`.

Ça fonctionne maintenant très bien, mais quel risque d'avoir fait sauter la contrainte de foreign key ? 
Et quels risques dans les mises à jour futur ? J'ai d'ailleurs fait les changements en BDD à la main, Alembic ne devrait pas trop apprécier ça...

**Comment by camillemonchicourt** [comment]
OK merci pour ce retour.
En effet, je n'avais pas pensé à cette limite des FDW qui ne peuvent pas gérer les clés étrangères.
Du coup, pas le choix à ma connaissance que de faire sauter les clés étrangères.
Pas bloquant mais plus risqué au niveau BDD car celle-ci ne peut pas gérer et garantir l'intégrité et la cohérence des données.
Il y a d'ailleurs d'autres endroits qui doivent faire référencé avec des clés étrangères dans GeoNature.

Alembic ne posera pas de soucis, sauf si une future migration ajoute justement une clé étrangère vers une table du schéma ``utilisateurs`` ou en utilise une qui a été supprimée. Alors la migration Alembic bloquera et il faudra l'adapter.

Donc non conseillé, mais ça devrait fonctionner, mais en traçant bien les adaptations réalisées et à bien garder en tête lors des futures mises à jour.

Sinon privilégier un système de réplication des données, avec dblink ou autre, pour ne pas avoir à supprimer les clés étrangères...
