### ISSUE TITLE
màj 2.7.5 vers 2.9 : référentiels régions et sensibilité

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoNature#1679]
Bonjour, 
Un retour sur une mise à jour en cours d'une instance GN en 2.7.5 vers la 2.9.1.

J'ai suivi les notes de versions de la 2.7.5 à la 2.9.1 en mettant également à jour Taxhub et Usershub (sans appliquer leurs migrations alembic).
Ensuite, je met à jour GeoNature directement en v2.9.1 sans passer par les v2.8.x intermédiaires) : 
La mises à jour des applis semblent OK et je n'ai pas d'erreurs.

Je lance ensuite les migrations Alembic en suivant bien les notes de versions de la 2.8.0 et en "stampant" les branches suivantes pour tenir compte des éléments déjà présents dans ma base : 
```
geonature db stamp f06cc80cc8ba  # GeoNature 2.7.5
geonature db stamp 0dfdbfbccd63  # référentiel géographique des communes
geonature db stamp 3fdaa1805575  # référentiel géographique des départements
geonature db stamp 586613e2faeb  # référentiel géographique des mailles 1×1
geonature db stamp 7d6e98441e4c  # référentiel géographique des mailles 5×5
geonature db stamp ede150d9afd9  # référentiel géographique des mailles 10×10
geonature db stamp 1715cf31a75d  # MNT de l’IGN
geonature db stamp f57107d2d0ad # Module Occtax
geonature db stamp 2984569d5df6 # Module Occhab
```
Comme je n'ai pas intégré les régions dans `ref_geo`, je ne les "stamp" pas (comme proposé dans la note de versions de la 2.9.0).

Comme je n'ai pas non-plus le référentiel de sensibilité d'installé en 2.7.5 et que je ne suis pas passé par les versions 2.8, je ne le "stamp" pas et n'applique pas non plus la commande alembic proposée pour réinstaller ce dernier manuellement (car celui-ci devrait s'installer automatiquement avec la migration de la base en 2.9 si je capte bien).

Je lance la commande alembic de màj de la BDD `geonature db autoupgrade`, la migration s'opère sans erreur mais les régions n'ont pas été intégrées dans `ref_geo.l_areas` et rien non-plus dans la table `gn_sensitivity.cor_sensitivity_area`.

En revanche, si je lance ensuite la commande alembic proposée pour réinstaller le référentiel de sensibilité manuellement dans la note de la 2.9.0 (`geonature db upgrade ref_sensitivity_inpn@head`), la migration et l'import des régions se lance...

Je ne suis pas encore très familier avec Alembic donc pas certain d'avoir tout bien fait mais j'ai scrupuleusement suivi les notes de versions, testé à plusieurs reprises et surtout, je n'ai pas installé la 2.8...

L'installation du ref de sensibilité et des régions est bien censé se faire automatiquement lorsqu'on passe en v2.9.x non ?
J'avais déjà eu le soucis sur une install vierge d'une autre instance en 2.8 mais une reinstallation en 2.9.0 avait bien corrigé le soucis comme indiqué par @bouttier dans #1576

Merci pour vos retours !

**Comment by bouttier** [comment]
Le référentiel de sensibilité n’est pas censé s’installer automatiquement en passant à la 2.9, mais bien manuellement avec l’exécution de la commande ``geonature db upgrade ref_sensitivity_inpn@head``. Il est normale que cette commande commence par installer le référentiel des régions, les règles de sensibilités étant régional et donc nécessitant le référentiel géographique approprié.
En revanche, lors d’une installation vierge, et ce à partir de la 2.9, le référentiel de sensibilité est automatiquement installé.

**Comment by xavyeah39** [comment]
OK merci pour ta réponse claire et rapide !
Proposition pour le préciser dans la note de versions de la 2.9.0 :

> Si vous avez installé GeoNature 2.8.X **ou si vous mettez à jour GeoNature depuis une version <= 2.7.5**, le référentiel de sensibilité n’a pas été installé automatiquement. Vous pouvez l’installer manuellement :
> 
>   `geonature db upgrade ref_sensitivity_inpn@head`

**Comment by bouttier** [comment]
En théorie, le référentiel de sensibilité était installé automatiquement en version 2.7.5, et les utilisateurs mettant à jour depuis la 2.7.5 devrait simplement stamper le référentiel de sensibilité.

Pourquoi déclares-tu ne pas avoir de référentiel de sensibilité ? Tu sembles bien en avoir un à la vue des conflits d’unicités qui s’ensuivent.

**Comment by xavyeah39** [comment]
Alors oui, peut-être mal exprimé : 
J'ai bien le ref de sensibilité iinstallé de la 2.7.5 mais seulement en partie...
De ce que je comprend de la note de version de la 2.9, celui-ci a besoin du référentiel des régions (actuelles et anciennes) mais je eux, je les ai pas en 2.7.5. 
Du coup je n'ai pas non plus les correspondances entre les règles de sensibilités dans `cor_sensitivity_area`.
Comme les opérations SQL opérées par telle ou telle branche d'alembic sont moins lisibles pour moi que des scripts SQL j'avoue avoir un peu de mal a capter où stamper et à quelle branche m'accrocher :)

**Comment by xavyeah39** [comment]
Je ne sais pas si c'est la bonne méthode mais voilà ce que j'ai fais  : 

- Ajouté un stamp sur le référentiel de sensibilité déjà présent en 2.7.5 (comme indiqué dans la note de la 2.9.0) : `geonature db stamp 7dfd0a813f86`
- Ajouté les régions dans `ref_geo.l_areas` : `geonature db upgrade ref_geo_fr_regions@head` et `geonature db upgrade ref_geo_fr_regions_1970@head`

Comme le peuplement de la table `gn_sensitivity.cor_sensitivity_area` est réalisé lors de l'install du référentiel de sensibilité et que je l'ai stampé pour évité un nouvel INSERT des règles déjà présentes dans `gn_sensitivity.t_sensitivity_rules` (violation de PK), j'ai sû peupler manuelllement en SQL `cor_sensitivity_area` en reprenant les instructions SQL du fichier de migration alembic 7dfd0a813f86_insert_inpn_sensitivity_referential.py : 

```sql
INSERT INTO gn_sensitivity.cor_sensitivity_area
    SELECT DISTINCT ON (id_sensitivity) s.id_sensitivity, a.id_area
    FROM gn_sensitivity.t_sensitivity_rules s
    JOIN ref_geo.l_areas a
        ON REPLACE(s.id_territory, 'INSEER', '') = a.area_code
    JOIN ref_geo.bib_areas_types t
     ON t.id_type = a.id_type AND t.type_code IN ('REG', 'REG_1970')
    WHERE s.sensitivity_territory = 'Région'
    ORDER BY s.id_sensitivity,  array_position(ARRAY['REG','REG_1970'], t.type_code::text)
;
INSERT INTO gn_sensitivity.cor_sensitivity_area
    SELECT DISTINCT id_sensitivity, id_area
    FROM gn_sensitivity.t_sensitivity_rules   s
    JOIN ref_geo.l_areas
        ON REPLACE(id_territory, 'INSEED', '') = area_code AND  id_type = (SELECT id_type FROM ref_geo.bib_areas_types  WHERE type_code ='DEP')
    WHERE sensitivity_territory = 'Département'
;
REFRESH MATERIALIZED VIEW gn_sensitivity.t_sensitivity_rules_cd_ref
;
```

**Comment by camillemonchicourt** [comment]
OK merci pour ces retours précieux.

Donc : 
- Il faut qu'on creuse pour préciser à ceux qui font des mises à jour depuis une version 2.7 sans le référentiel de sensibilité comment l'installer
- Il aussi qu'on creuse pour ceux qui l'avaient installé auparavant pourquoi il manque des bouts pour pas qu'ils n'aient à faire les manipulations manuelles que tu as faites

**Comment by camillemonchicourt** [comment]
Les référentiels de sensibilité ont été complètement mis à jour et les commandes d'intégration du référentiel revu dans la 2.11.0.
Je ferme ce ticket car à priori caduque, mais n'hésite pas à faire un retour si tu as toujours des soucis avec ce référentiel en passant sur la version 2.11.
