### ISSUE TITLE
GN 2.9 - Responsive écran d'accueil 

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/GeoNature#1682]
Bonjour, 

Un petit point de responsive sur l'écran d'accueil. Sur petit écran lorsque le bandeau latéral est ouvert cela donne ça : 

<img width="915" alt="Bug_GN_responsive_accueil (1)" src="https://user-images.githubusercontent.com/62794251/152507233-6d1b4974-c43c-42ae-8f2d-7ad0aaaa8b26.PNG">

**Comment by camillemonchicourt** [comment]
On vient justement de faire un petit ajustement responsive de la page d'accueil pour que les 2 blocs de droite passent l'un sous l'autre quand on est sur petit écran : https://github.com/PnX-SI/GeoNature/pull/1677.

OK donc il faut voir aussi le bloc et menu de gauche.

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.10.0
