### ISSUE TITLE
develop - GET modules retourne UNAUTHORIZED 401

### ISSUE THREAD

**Issue by Gaetanbrl** [PnX-SI/GeoNature#1688]
**Version**
branche develop du 09/02/2022

**Note**
Dans cette issue le `mode dev` fait référence à GeoNature lancé via des commande `npm run start`  et `geonature dev_back` conformément à [la documentation pour passer en mode dev](https://docs.geonature.fr/installation.html#passer-en-mode-developpement).

**Description du bug**
J'avais suivi la doc d'installation globale et la doc de passage en `mode dev` sur une version 2.8.x et tout se passait bien, j'avais pu faire des tests, des développements etc.

Maintenant je suis repassé sur la branche develop (+ à jour et + simple pour reprendre les dev en cours) mais le passage en `mode dev` ne semble pas permettre par défaut l'accès aux modules (et à d'autres ressources ?) lors de la connexion du user admin de base (signin) car l'appel `/gn_commons/modules` retourne `"GET //gn_commons/modules HTTP/1.1" 401 ` lors du fetch :

https://github.com/PnX-SI/GeoNature/blob/f3ab01e1403074059c7ea0a791b06ab88cb7b309/frontend/src/app/components/auth/auth.service.ts#L105

Mais que ce soit en mode dev ou en mode "normal" cet appel semble également réalisé lorsque j'arrive sur la page d'authent sans être connecté. J'ai donc cette erreur à chaque arrivée sur la page d'authent (redirection après logout déconnexion compris) avec l'affichage de la popup rouge "401...".

https://github.com/PnX-SI/GeoNature/blob/bc851e7fa16fdf9f909c127759953249e76748c9/frontend/src/app/services/unauthorized.interceptor.ts#L15

Je me demande également si l'admin par défaut a les bonnes infos, mais droits semblent correct et suffisants : 
```
id_organisme: -1
id_role: 3
nom_complet: "Administrateur test"
nom_role: "Administrateur"
prenom_role: "test"
user_login: "admin"
```

**Capture**

![modules_401](https://user-images.githubusercontent.com/16317988/153209732-ad4a8ae6-60a5-4361-85ca-2f06361020ca.gif)

**Comportement attendue**

Accéder à geonature via http://127.0.0.1:4200 avec les modules disponibles et les fonctionnalité du mode "normal" hors mode dev.

**Comment reproduire**
1. Installer geonature depuis la branche develop
2. Modifier la config `/geonature/config/geonature_config.toml` pour avoir :

```
URL_APPLICATION = 'http://127.0.0.1:4200'
API_ENDPOINT = 'http://127.0.0.1:8000'
API_TAXHUB = 'http://127.0.0.1:5000/api'
ID_APPLICATION_GEONATURE = 3
```

3. Modifier la config `geonature/frontend/src/conf/app` pour avoir

```
"URL_APPLICATION": "http://127.0.0.1:4200",
 "API_TAXHUB": "http://127.0.0.1:5000/api",
 "API_ENDPOINT": "http://127.0.0.1:8000",
 "ID_APPLICATION_GEONATURE": 3
```

4. stop le service geonature de base
```
sudo systemctl stop geonature
```
5. lancer le front
```
cd /geonature/frontend && npm run start
```
...qui lance la commande `ng serve --poll=2000 --configuration=development`

6. lancer le back
```
cd backend
source venv/bin/activate
geonature dev_back
```
7. accéder à `http://127.0.0.1:4200` (et non http//127.0.0.1:4200/geonature)
8. se connecter en admin
9. voir que les modules ne s'affichent pas et voir l'erreur 401 dans la console

**Logs**
Log serveur backend :
`127.0.0.1 - - [09/Feb/2022 14:23:36] "GET /gn_commons/modules HTTP/1.1" 401 -`

**Comment by Gaetanbrl** [comment]
Merci pour la réponse @TheoLechemia 

> Le front devrait répondre sur 127.0.0.1:4200 et non 127.0.0.1:4200/geonature
désolé c'est une erreur de ma part à la saisie de l'étape 7 >> tout a été bien appelé via 127.0.0.1:4200 sans le /geonature (comme vu sur la capture).

>Est-ce que tu peux vérifier la présence d'un cookie nommé "token" (onglet application puis cookie du débuggeur du navigateur).
Que renvoie l'appel de la route de login (onglet network du debugger)?

J'avais vérifié et j'ai bien le token qui contient ces infos : 

```
{
  "_password": "21232f297a57a5a743894a0e4a801fc3",
  "id_role": 3,
  "nom_role": "Administrateur",
  "prenom_role": "test",
  "id_application": 3,
  "id_organisme": -1,
  "identifiant": "admin",
  "id_droit_max": 6
}
```

**Comment by TheoLechemia** [comment]
Ok merci pour les infos.
Est-ce que tu as le body exacte de la 401 ? ça peut aider à voir le soucis.
Tu dois aussi voir passer l'info sur la console qui a lancé le "geonature dev_back".
Sinon ça se passe ici pour le code : https://github.com/PnX-SI/GeoNature/blob/develop/backend/geonature/core/gn_permissions/tools.py#L50
Et mettant des traces tu devrait voir ce qu'il se passe

**Comment by Gaetanbrl** [comment]
> Est-ce que tu as le body exacte de la 401 ?
Oui le voici (si c'est bien le body de la réponse que tu souhaites) :

`{"code": 401, "description": "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.", "name": "Unauthorized"}`


> Tu dois aussi voir passer l'info sur la console qui a lancé le "geonature dev_back".

oui , j'avais fait abstraction des lignes qui précedent la 401 dans la console du backend, mais je vois un élément particulier : 
`662c6344-c4a7-42c3-a197-e87514d35c1b] Invalid token: the token not corespoding to the current app`

Voici les logs complète du serveur :

$geonature dev_back

```
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 500-933-969
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/json/__init__.py:211: DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in ItsDangerous 2.1. Use Python's 'json' module instead.
  rv = _json.dumps(obj, **kwargs)
127.0.0.1 - - [09/Feb/2022 16:17:57] "OPTIONS /auth/login HTTP/1.1" 200 -
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/json/__init__.py:211: DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in ItsDangerous 2.1. Use Python's 'json' module instead.
  rv = _json.dumps(obj, **kwargs)
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/itsdangerous/jws.py:201: DeprecationWarning: JWS support is deprecated and will be removed in ItsDangerous 2.1. Use a dedicated JWS/JWT library such as authlib.
  super().__init__(secret_key, **kwargs)
[eceda0ea-5c58-49af-9471-0fdf86d133d1] Invalid token: the token not corespoding to the current app
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/json/__init__.py:253: DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in ItsDangerous 2.1. Use Python's 'json' module instead.
  return _json.loads(s, **kwargs)
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/itsdangerous/jws.py:201: DeprecationWarning: JWS support is deprecated and will be removed in ItsDangerous 2.1. Use a dedicated JWS/JWT library such as authlib.
  super().__init__(secret_key, **kwargs)
127.0.0.1 - - [09/Feb/2022 16:17:57] "POST /auth/login HTTP/1.1" 200 -
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/json/__init__.py:211: DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in ItsDangerous 2.1. Use Python's 'json' module instead.
  rv = _json.dumps(obj, **kwargs)
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/itsdangerous/jws.py:201: DeprecationWarning: JWS support is deprecated and will be removed in ItsDangerous 2.1. Use a dedicated JWS/JWT library such as authlib.
  super().__init__(secret_key, **kwargs)
[662c6344-c4a7-42c3-a197-e87514d35c1b] Invalid token: the token not corespoding to the current app
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/json/__init__.py:211: DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in ItsDangerous 2.1. Use Python's 'json' module instead.
  rv = _json.dumps(obj, **kwargs)
127.0.0.1 - - [09/Feb/2022 16:17:57] "GET /gn_commons/modules HTTP/1.1" 401 -
```

**Comment by TheoLechemia** [comment]
C'est un problème d'id_application.
Est-ce que tu peux regarde l'id de l'app geonature dans utilisateurs.t_applications ?

**Comment by Gaetanbrl** [comment]
> Est-ce que tu peux regarde l'id de l'app geonature dans utilisateurs.t_applications ?

Oui bien sur.
![image](https://user-images.githubusercontent.com/16317988/153236330-42af4a5c-1bb4-49ff-a8d4-7b25f89dc583.png)



Dans /geonature/config/geonature_config.toml et geonature/frontend/src/conf/app le numéro est 3 (et pas 1 comme dans la table) :

`ID_APPLICATION_GEONATURE = 3`


Si c'est le problème ... je ne comprend pas pourquoi on a ces deux numéros différents ? Une diff de version de la doc ?

**Comment by pierrejego** [comment]
Je rencontrais le même soucis avec ID_APPLICATION=3
L'ID_APPLICATION est bien à 1 dans la base de données, en modifiant de côté conf ça fonctionne.

C'est donc juste une erreur dans la doc. Et je pense d'ailleurs que l'ajout de ID_APPLICATION dans le fichier geonature_config.toml ne sert pas non plus.

Merci !

**Comment by Gaetanbrl** [comment]
@TheoLechemia je confirme, garder 1 à la place de 3 permet de résoudre le problème et les modules répondent.

Par contre TaxHub ne semble pas démarré du tout. Il doit manquer un élément.

**Comment by Gaetanbrl** [comment]
> Par contre TaxHub ne semble pas démarré du tout sur 127.0.0.1:5000. Il doit manquer un élément.


@TheoLechemia j'ai stoppé le service natif taxhub et j'ai démarré via venv taxhub et 127.0.0.1:5000 semble maintenant accessible :

```
$ sudo systemctl stop taxhub
$ cd ~/taxhub
$ source venv/bin/activate
$ flask run

```
**Sais-tu quels sont les effets de bord / conséquence dans le fonctionnement entre usershub / geonature / taxhub / autres modules de démarrer à la main via le virtual env le module taxhub ?**

**Comment by TheoLechemia** [comment]
On a changé les id_applications fourni à l'installation dans une version précédente, il faudrait mettre à jour la doc effectivement. Ou est-ce que tu as vu de ID_APPLICATION = 3 ?

> Sais-tu quels sont les effets de bord / conséquence dans le fonctionnement entre usershub / geonature / taxhub / autres modules de démarrer à la main via le virtual env le module taxhub ?
Il n'y en a pas normalement.
Quel est l'erreur 500 qui t'étais renvoyé ?

**Comment by pierrejego** [comment]
Pour l'ID_APPLICATION = 3 c'est ici : 
https://docs.geonature.fr/installation.html#passer-en-mode-developpement

Je viens de faire une PR pour prendre en compte la modification
https://github.com/PnX-SI/GeoNature/pull/1690

**Comment by TheoLechemia** [comment]
merci
