### ISSUE TITLE
Installation GN2.9.1: attention au SRID!

### ISSUE THREAD

**Issue by AudreyEnGuyane** [PnX-SI/GeoNature#1695]
**Version 2.9.1**
Version de GeoNature affectée par le bug.

**Description du bug**
L'installation des données "Sensitivity" nécessitent d'avoir les données des régions et départements. Ceci produit une erreur pour les territoires ayant un SRID <> 2154.
Attention donc aux DOM !

**Comportement attendue**
==> utiliser un ST_TRANSFORM avec le SRID local ?
==> pouvoir choisir de ne pas installer le référentiel de sensibilité depuis le install_all.ini ?

**Comment reproduire**
Lancer un install_all.sh avec un SRID local différent de 2154 (testez 2972!)

**Logs**
```
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidParameterValue) ERREUR:  Geometry SRID (2154) does not match column SRID (2972)

[SQL:
        INSERT INTO ref_geo.l_areas
            (id_type, area_code, area_name, geom, geojson_4326)
        SELECT
            ref_geo.get_id_area_type('REG') as id_type,
            insee_reg,
            nom,
            geom,
            public.ST_asgeojson(public.st_transform(geom, 4326))
        FROM ref_geo.temp_fr_regions
    ]
```

**Comment by bouttier** [comment]
Fix de @joelclems qui sera intégré en 2.10

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.10
