### ISSUE TITLE
faire une doc présentant la logique de l'application et de BDD

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#17]
Faire aussi une petite vidéo ou un pdf avec des captures d'écran de l'appli

**Comment by camillemonchicourt** [comment]
Fonctionnement général désormais expliqué dans la DOC : http://geonature.readthedocs.io/fr/latest/install_all/2016-12-exemple-deploiement-pnr.html#fonctionnement-general

A rendre plus générique dans le cadre de la V2.

**Comment by camillemonchicourt** [comment]
Amorcé dans la V2 : https://github.com/PnX-SI/GeoNature/blob/frontend-contact/docs/development.rst

**Comment by camillemonchicourt** [comment]
Fait dans la documentation d'administration : https://geonature.readthedocs.io/fr/latest/admin-manual.html#
