### ISSUE TITLE
occhab/occatax autocomplete - Valeurs de la liste habitat non lisibles

### ISSUE THREAD

**Issue by Gaetanbrl** [PnX-SI/GeoNature#1701]
**Version**
Branche : develop
Navigateur : Chrome 98.0.4758.82 (Build officiel) (64 bits)

**Description du bug**
Les valeurs de la liste Habitats sont masquées sous la carte car au moins une valeur a un grand nombre de caractère. La liste a donc une largeur (width) trop large et passe sous la carte.

![habitat_field](https://user-images.githubusercontent.com/16317988/153580229-217d1381-d4aa-4a2a-adc9-1ad296e5661e.gif)

**Comportement attendue**
Voir toutes les valeurs, avoir un retour à la ligne ou la valeur "coupée" si un libellé habitat est trop long.

**Comment reproduire**
- Ouvrir le module occtax
- Créer une observation
- Cliquer sur la carte
- Saisir une valeur dans la liste

**Comment by Gaetanbrl** [comment]
L'effet est inversé avec un écran 15 pouces, on voit le début mais pas la fin.

**Comment by camillemonchicourt** [comment]
On fermera quand ce sera dans une release pour que les autres voient que c'est corrigé mais pas releasé.

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.10
