### ISSUE TITLE
Changement fonds carto

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/GeoNature#1703]
Bonjour,

Dans Geonature nous utilisons les fonds IGN (scans 5 et orthophoto) et une couche openstreetmap. Depuis peu les fonds IGN ne s'affichent plus dans la synthèse et dans le module Occtax. IGN ayant changé sa politique d'accès aux données via son API, nos URL d'accès ne sont plus valables. Ces URL se trouvent dans le fichier /home/nom_user/geonature/frontend/src/conf/app.config.ts
Si on effectue des modifications dans ce fichier, comment faire pour qu'elles soient prises en compte ? Il y a surement une commande à lancer ? Quelle est la procédure ?

Une fois qu'on saura comment mettre à jour ce fichier de config, on va regarder comment réécrire les URL pour mettre à jour les fonds IGN. Il y a de la doc sur https://geoservices.ign.fr/ avec les pages Découverte, Essentiels et Experts.
Y a t'il quelqu'un qui a mis à jour les fonds IGN dans le fichier de conf avec les préconisations récentes d'IGN ? Si oui, serait il possible d'avoir votre fichier de config pour s'en servir comme base d'aide ?

Merci.

**Comment by amandine-sahl** [comment]
Il faut mettre à jour le fichier `config\geonature_config.toml`. Un exemple est disponible ici : https://github.com/PnX-SI/GeoNature/blob/7af2c82a97675daa965024a3879c7168aca2fdb1/config/default_config.toml.example#L208

Puis mettre à jour la configuration de GeoNature et relancer l'application

```sh
  source backend/venv/bin/activate
  geonature update_configuration
  sudo systemctl restart geonature
```

**Comment by camillemonchicourt** [comment]
Oui en effet, il ne faut pas toucher au fichier ``/home/nom_user/geonature/frontend/src/conf/app.config.ts`` qui est généré automatiquement à partir du fichier ``config\geonature_config.toml``

Voici un exemple avec les flux IGN : 

```
BASEMAP = [
        {"name" = "IGN Scan 25", "layer" = "https://wxs.ign.fr/MACLE/geoportail/wmts?LAYER=GEOGRAPHICALGRIDSYSTEMS.MAPS&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}", "attribution" = "&copy IGN"},
        {"name" = "IGN ortho", "layer" = "//wxs.ign.fr/ortho/geoportail/wmts?&REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&STYLE=normal&TILEMATRIXSET=PM&FORMAT=image/jpeg&LAYER=ORTHOIMAGERY.ORTHOPHOTOS&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}%27,%27(c)", "attribution" = "&copy IGN"},
        {"name" = "OpenStreetMap", "layer" = "//{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png", "attribution" = "&copy OpenStreetMap"},
        {"name"= "OpenTopoMap", "layer" = "//a.tile.opentopomap.org/{z}/{x}/{y}.png", "attribution" = "© OpenTopoMap"}
    ]
```

Pour le Scan 25, il faut générer une nouvelle clé (depuis la 1° février).
Pour l'ortho, elle est disponible de manière ouverte sans clé spécifique.

Idem pour le Plan IGN v2 et le cadastre que tu peux aussi ajouter : 
- Plan v2 IGN : https://wxs.ign.fr/cartes/geoportail/wmts?&REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&STYLE=normal&TILEMATRIXSET=PM&FORMAT=image/png&LAYER=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}
- Cadastre IGN : https://wxs.ign.fr/parcellaire/geoportail/wmts?&REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&STYLE=normal&TILEMATRIXSET=PM&FORMAT=image/png&LAYER=CADASTRALPARCELS.PARCELS&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}

**Comment by Chrispnv** [comment]
Merci pour les infos, ça remarche !!
Est ce que cela ne vaudrait pas le coup de mettre un petit chapitre dans la doc concernant la manière de mettre à jour les fonds carto IGN ou autre ? Je veux bien le faire, je ne sais pas si j'ai les droits.

Oui je vais redemander une clé IGN pour les scans 25.

D'ailleurs, de votre coté avec l'assouplissement de l'IGN quels fonds vous privilégiés dans Geonature ou autre, c'est à dire les fonds IGN, les fonds libres... Comment vos agents réagissent ?

**Comment by TheoLechemia** [comment]
On a remis le scan 25. Ils ne sont pas fan du plan IGN v2 (ou du changement, je sais pas ! )
