### ISSUE TITLE
V2 - MCD protocole générique ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#171]
Voici une première réflexion sur une structure de MCD générique : 

![mcd_simple_geonature2_0 2](https://cloud.githubusercontent.com/assets/4418840/24913509/b3e93d42-1ed1-11e7-8fab-9276bfa6c063.png)

L'idée est d'avoir un tronc commun entre tous les protocoles intégrés qui correspond au Qui, quand, où ? dans une table RELEVE et Quoi ? dans une table observations et de décliner les parties spécifiques aux protocoles dans les schémas de chaque protocole. 

Cela permet de factoriser la partie QUI, QUOI, QUAND, OU, de la centraliser, de simplifier l'alimentation de la synthèse. 
Cela s'inspire des principes de l'ontologie OBOE (https://github.com/NCEAS/oboe/) et de ses Super-contextes, contextes...

**Comment by camillemonchicourt** [comment]
Ce modèle s'appuierait sur l'héritage entre le QUOI et le SOUS-QUOI notamment. 
Néanmoins l'héritage a pas mal de limitations (http://docs.postgresqlfr.org/9.6/ddl-inherit.html) au niveau des index et contraintes de clés étrangères qui ne s'appliquent qu'aux tables mères mais pas aux héritiers. 
A ce sujet, voir : https://www.developpez.net/forums/d1011899/bases-donnees/postgresql/heritage-postgresql/

Il y a aussi des protocoles qui ne rentrent pas dans ce MCD générique comme Flore prioritaire où on a un geom zone de prospection = ZP, un geom aire de présence = AP et le cd_nom est rattaché à la table des ZP car on recherche un taxon lors d'une prospection sur une ZP et si on trouve, on fait des AP, si on trouve pas = absence dans la ZP.

**Comment by camillemonchicourt** [comment]
Moi je m'interroge si cela simplifie ou complexifie la compréhension et lecture des données. 
Si cela simplifie ou complexifie l'architecture des données. 

Car certaines passent par le cœur, d'autres non (protocoles externes, protocoles complexes, données partenaires) et car ce cœur est très proche de la synthèse.

**Comment by camillemonchicourt** [comment]
Concernant l'héritage, on a un cas un peu similaire où le MCD utilise une notion de tables mères (Evenements) et tables filles (Interventions, Foncier, Itinéraires, POIs, Aménagements...) mais sans utiliser l'héritage de PostgreSQL : https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/CCTP_annexe1-MCD.pdf

Dans Geotrek, pas mal de choses sont gérés au niveau du model de Django et de l'application. L'héritage certainement aussi, ce qui n'est pas très satisfaisant.

**Comment by camillemonchicourt** [comment]
Pour les autres aspects de détail concernant les évolutions de la BDD, voir les issues taguées "database" : https://github.com/PnEcrins/GeoNature/issues?q=is%3Aissue+is%3Aopen+label%3Adatabase

**Comment by gildeluermoz** [comment]
Comme les modif en web se font sur l'appli et la base du réseau de conservation de la Flore Alpes Ain, idéalement la synchro flore patrimoniale de nos tablettes devraient se faire dans leur base et plus sur la notre.
Ensuite on récupère dans notre base GeoNature les données flore patrimoniales PNE dans des tables en FDW (exit les 2 jobs Talend). J'ai déjà testé ces FDW entre nos bases et ça fonctionne.
Il y a un soucis pour ça : la synchro desktop des mobiles synchronise toutes les données produites : faune, flore, inv, mortalité vers la même web api...
Je crois qu'on peut configurer la webapi pour lui donner une base flore, une base faune et une base invertébrés.
A tester.

Si tout ça fonctionne, on ne cherche pas à faire rentrer le protocole flore patrimoniale, trop "exotique" dans le modèle de la V2.

**Comment by camillemonchicourt** [comment]
Oui dans les 2 cas c'est un protocole "exotique" avec son propre schéma mais dans la BDD de GeoNature et avec trigger vers la synthèse.

**Comment by camillemonchicourt** [comment]
Amandine Sahl :

> 
>  - Sur la question de la centralisation d'une table média dans le cœur de GeoNature vs par protocole (#191). Je suis partagée, la question n'est pas tranchée. D'un coté je trouve la mutualisation pertinente car elle permet de mettre en place un socle de méthodes génériques qui posent un cadre et facilitent la création de nouveaux protocoles, d'un autre cela rajoute des contraintes et peut complexifier les requêtes.
> 
>  - Un point sur lequel je m'interroge est la potentielle centralisation de la table relevé. C'est un changement de paradigme par rapport à GeoNature, mais si on réfléchit bien, on pourrait avoir une entrée unique : relevé (ou contexte primaire) sur lequel on ajoute des données protocoles (via la mention au lot de données).

**Comment by gildeluermoz** [comment]
Ok pour une table médias dédiée à la taxonomie (TaxHub).

Concernant une ou plusieurs tables pour les médias des protocoles. Il faut se poser la question du besoin de partage de médias entre protocoles. Je n'en vois pas trop. 
Je vois un d'inconvénient majeur à partager les médias des protocoles :
* Ce partage doit être implémenté dans l'interface pour permettre le rattachement d'un média existant à un enregistrement dans un protocole : lister tous les médias, filtrer, rechercher, cocher ! = gros boulot, et alourdissement des interfaces.
* Ce partage doit être traduit dans le modèle par le rattachement de chaque média à un ou plusieurs protocoles.

**Je propose : **
* une table centrale unique dans un schéma ``medias``
* une clé étrangère dans **des** tables de correspondance : une par protocole.
* pas de partage possible d'un média par plusieurs protocoles (au moins au départ) afin de ne pas avoir à construire d'interface pour lister, filtrer, rechercher, cocher.
* l'ajout ou la suppression des médias se font via l'interface du protocole, dans un onglet média sur le modèle de TaxHub = pas de gestion globale de tous les médias de la table ``medias.t_medias``.
* création d'un 'component' permettant de factoriser l'interface et les fonctionnalités de l'onglet médias dans les formulaires des protocoles faisant usage de médias.

Je fais une proposition d eMCD en ce sens. A amender.

**Comment by camillemonchicourt** [comment]
Oui clairement, il n'y a pas de raison d'avoir une gestion d'une bibliothèque de médias avec des relations N-N. Un média se rapport à une et une seule observation. C'est son objectif premier que d'illustrer UNE observation. 

Concernant la centralisation du cœur des protocoles dans un schéma et factorisé, j'en ai discuté avec @DonovanMaillard et il pense aussi que ça complexifie la lisibilité, que ça a potentiellement un caractère bâtard si certains protocoles passent par le cœur et d'autres et d'autres non et surtout que cela créé une redondance entre le cœur et la synthèse qui sont très proche mais n'ont pas le même contenu. 

Le seul avantage que l'on voit à cela est le fait que l'alimentation PROTOCOLE vers SYNTHESE est centralisé et factorisé puisqu'il se fait entre le cœur et la synthèse.

**Comment by camillemonchicourt** [comment]
Autre question globale sur le MCD de GeoNature, on a de plus en plus de schémas globaux (`taxonomie`, `medias`, `meta`, `synthese`...) et en même temps de plus en plus de schémas de protocoles ou données sources de partenaires. 

Pour faciliter la lisibilité et les regrouper, je préfixerai bien tous les schémas qui concernent des protocoles avec des données sources. 

Par exemple avec `p` pour protocole ou `ds` pour données source. 

- ds_contactfaune
- ds_contactflore
- ds_florestation
- ds_cbna
- ds_silenepaca
.....

**Comment by DonovanMaillard** [comment]
Donc pas de "pré-synthèse" avant la synthèse pour les contacts?

->  👍

**Comment by camillemonchicourt** [comment]
Non.

**Comment by camillemonchicourt** [comment]
OK on ferme ce ticket car tout ça a évolué depuis. 
On a potentiellement un tronc commun pour les protocoles de suivi (gn_monitoring) avec la partie Sites de suivi et Visites qui est centralisé et extensibles. 
Pas de centralisation des relevés.
