### ISSUE TITLE
OccTax : erreur ajout relevé

### ISSUE THREAD

**Issue by RNF-SI** [PnX-SI/GeoNature#1725]
**Version**
2.9.1 (sur Debian 11)

**Description du bug**
Erreur à l'ajout d'un relevé dans OccTax (`Action non permise:[object Object]`).

Dans les logs c'est indiqué qu'il y a une violation de contrainte NOT NULL pour le champs id_nomenclature_grp_typ.
Comment celui-ci est-il censé être défini ? Automatiquement ? En tout cas ça ne semble pas être paramétrable dans l'ajout de relevé, comme indiqué dans le tableau ici https://github.com/PnX-SI/GeoNature/blob/master/docs/implementation_gn_standard_occtax2.0.ods 

**Logs**
```
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « id_nomenclature_grp_typ » dans la relation « t_releves_occtax »
DETAIL:  La ligne en échec contient (5, cbf9c422-a0db-4830-bc76-4ea84c7e9381, 3, 9, null, null, null, null, 2022-02-17 00:00:00, 2022-02-17 00:00:00, null, null, null, 18, 18, null, null, null, web, null, 01010000206A08000028E7BE4CAA841641C336C79EF7915841, 0101000020E610000001000080203DF3BF49F03C367F7E4640, null, null, {}).
```

**Comment by camillemonchicourt** [comment]
Pour les champs affichables ou non, il faut se référer à https://github.com/PnX-SI/GeoNature/blob/master/contrib/occtax/config/conf_gn_module.toml.example#L160
Il semble bien affichable.

Jamais vu cette erreur de mémoire, donc je comprends pas pourquoi toi tu l'as....

**Comment by gildeluermoz** [comment]
Est-ce que la table `pr_occtax.defaults_nomenclatures_value` est bien remplie.
A priori il n'y a pas que cette nomenclature qui aurait une valeur null, il y a bcp de `null` dans le `INSERT INTO` est ça ne semble pas normal.

**Comment by RNF-SI** [comment]
A priori elle est bien remplie oui :

![image](https://user-images.githubusercontent.com/43465924/154924889-5a2c8b99-8037-4bc8-9c07-fa495c533aae.png)

Sur mon autre instance, je n'ai pas ce problème. 

Du coup je pense qu'il vient certainement du fait que j'ai un foreign schema pour "utilisateurs", c'est la seule différence entre les deux instances...

**Comment by RNF-SI** [comment]
J'ai fait le ménage dans la BDD car il y avait encore de nombreuses FK qui pointaient vers le mauvais schema utilisateurs (voir la liste des FK supprimées dans #1675).

Pour l'instant ça n'a pas solutionné mon problème. Je vais voir du côté des triggers peut être.

**Comment by RNF-SI** [comment]
C'est bon j'ai identifié le problème. 

C'est bien lié à mon foreign schema. En fait l'`id_organism `pour ALL n'est pas le même de base dans les deux instances. Dans l'instance d'origine de la table utilisateurs, il est égal à 2 (1 étant pour "ma structure test") alors que dans l'autre instance il est égal à 1 (2 étant pour "ma structure test"). En remplaçant donc `1` par `2` pour toutes les valeurs de `id_organism` dans `pr_occtax.defaults_nomenclatures_value` ça marche bien !
