### ISSUE TITLE
Evol validation - Flux de Discussion sur une occurrence 

### ISSUE THREAD

**Issue by Gaetanbrl** [PnX-SI/GeoNature#1731]
> Vu avec @TheoLechemia et @camillemonchicourt ce jour)

_La proposition ci-dessous pourra évoluer selon les besoins de picardie-nature (commanditaire) et de la communauté GeoNature.
N'hésitez-pas à intervenir pour tout commentaire / suggestions sur les aspects techniques ou fonctionnelles._

## Description fonctionnelle

Cette évolution a pour but de permettre aux validateurs d'échanger entre eux sur une occurrence au sein du composant partagé de la synthèse. La modification sera donc réalisée dans le cœur.

Par défaut, cette fonctionnalité sera visible au sein de la modal de `VALIDATION` et pour la modal `SYNTHESE` :

- Un paramètre `<boolean> ENABLE_SYNTHESE_DISCUSSION` permettra d'ajouter ou non cette fonctionnalité dans la modal de SYNTHESE.

- Un paramètre `<boolean> ENABLE_VALIDATION_DISCUSSION` permettra d'ajouter ou non cette fonctionnalité dans la modal de VALIDATION.

Pour l'UI, un nouvel onglet "Discussion" (label pouvant évoluer) sera ajouté dans le composant partagé de la synthèse comme proposé ici :

![image](https://user-images.githubusercontent.com/16317988/155332011-28c86e06-cbed-44fe-b6cc-32d3d535d883.png)

Il sera alors possible d'ajouter un commentaire par un clic dans la toolbar (toolbar ajoutée via PR 1724) ou via un clic dans l'onglet "Discussion" puis un autre clic sur un bouton type "Ajouter un commentaire".

Le clic sur le bouton fera apparaître une zone de saisie libre avec deux boutons d'envoi du commentaire ou d'annulation.

![image](https://user-images.githubusercontent.com/16317988/155330817-8b700840-d4fa-444b-bbfe-392de357a432.png)

Les échanges seront affichés dans un fil de discussion à l'image des commentaires d'une issue GitHub.

## Description technique

* DB
Une nouvelle table `t_discussions` sera ajoutée dans le schéma `gn_synthese`.
Cette table contiendra les champs suivants : 

champ | type
-- | --
id_discussion | PK
id_synthese | string
id_role | string
content | json
date | date
id_module | number

> le champ id_module permettra d'afficher dans la SYNTHESE que les commentaires de la SYNTHESE . Idem pour la VALIDATION.

* Backend

Les endpoints suivants seront ajoutés (e.g `/synthese/discussions`)
type | url | params | détail
-- | -- | -- | --
GET | `discussions/<string:id_synthese>` | | Obtenir les notes d'une occurrence
PUT | `discussions/<string:id_synthese>` | content (type: string) | Ajouter un commentaire dans la discussion de l'occurrence

Attention :
> Les routes de modification / suppression des commentaires pourront être créent mais ce comportement n'est pas encore défini / prévu. Si un commentaire doit être signalé, il pourrait être envisageable de contacter un administrateur pour la gestion des commentaires concernés.

* Frontend

Le composant partagé sera concerné : 

https://github.com/PnX-SI/GeoNature/blob/master/frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.ts

**Comment by Gaetanbrl** [comment]
# Suivi des travaux

- [ ] Script de création de la table
- [ ] Ajout de l'onglet "Discussion" avec i18n
- [ ] Endpoints CRUD `/comments/`
- [ ] Test CRUD
- [ ] UI d'ajout d'un commentaire
- [ ] Annulation de la saisie d'un commentaire
- [ ] Sauvegarde d'un commentaire (PUT /comments `<id_synthese><commentaire:string>`)
- [ ] Affichage de tous les commentaires d'une occurrence (GET /comments `<id_synthese>`) récupérés en `JSON`
- [ ] Ajout et prise en compte du paramètre SYNTHESE_TALK `<boolean>`
- [ ] Documentation
- [ ] Tests `.py` et `.ts`

**Comment by Gaetanbrl** [comment]
Merci pour ces précision, je reprendrai ce complément.

Pour l'ajout d'une nouvelle table, quelles sont les bonnes pratique, scripts à cibler de préférence ? (e.g pour la migration ? première install ?)

**Comment by camillemonchicourt** [comment]
Pour la BDD, on ne touche plus au fichier SQL.
Tout se fait avec des migrations Alembic depuis la version 2.8 de GeoNature.
Voir https://docs.geonature.fr/admin-manual.html#administration-avec-alembic

A voir aussi un début de documentation sur les tests unitaires au niveau backend : https://github.com/PnX-SI/GeoNature/pull/1713/files

**Comment by Gaetanbrl** [comment]
Merci je vais regarder ces liens.
Le descriptif de l'issue vient d'être mis à jour avec tes remarques précédentes.

**Comment by jpm-cbna** [comment]
Est ce qu'il est prévu que des emails soient envoyés suite à l'ajout du commentaire ? Et si oui vers qui ? Le "contact principal" du jeu de données de l'observation ?

Peut être avez vous envisagé la possibilité d'avoir un flux RSS/ATOM sur les commentaires ajoutés ?

**Comment by Gaetanbrl** [comment]
> Est ce qu'il est prévu que des emails soient envoyés suite à l'ajout du commentaire ?

Cette fonctionnalité est en dehors du scope technico-fonctionnel de cette issue.

Une évolution permettant d'avoir des notifications est cependant prévue ultérieurement et pourra permettre de notifier des utilisateurs pour ce type d'action.

**Comment by jpm-cbna** [comment]
> Une évolution permettant d'avoir des notifications est cependant prévue ultérieurement et pourra permettre de notifier des utilisateurs pour ce type d'action.

Merci pour la réponse. C'était surtout pour avoir une idée des évolutions futures envisagées vis à vis de cette fonctionnalité.

**Comment by jpm-cbna** [comment]
@camillemonchicourt Le document est très intéressant et très complet. Il me permet de comparer le fonctionnement actuel de la validation dans notre SI métier avec les futures évolutions de GeoNature.

**Comment by TheoLechemia** [comment]
C'est la bonne démarche ! 
C'est un paramètre sur la longueur du champs discussion ? Si oui je partirai sur `DISCUSSION_MAX_LENGTH` ou sur pas de paramètre sauf si c'est vraiment utile !

**Comment by Gaetanbrl** [comment]
> Si oui je partirai sur DISCUSSION_MAX_LENGTH

Tout à fait d'accord j'avais déjà changé le nom.

**Comment by Gaetanbrl** [comment]
Voici une proposition pour l'affichage d'une discussion dans le module de validation suite au besoin exprimé par @jbdesbas.
Dans le module SYNTHESE, la discussion n'affichera pas les modifications du statut.

Je prends tous retours ;)

![image](https://user-images.githubusercontent.com/16317988/157270567-cdf4d265-b227-463b-a24a-83d81330fc28.png)

**Comment by camillemonchicourt** [comment]
OK merci. 
Je m'interroge par contre sur le fait d'intercaler entre les discussions les changements de statut de validation.
C'est intéressant et ça a du sens dans le module de Validation, mais par contre beaucoup moins quand cet onglet sera aussi disponible dans le module Synthèse, où les discussions ne seront pas forcément liées à la validation de la donnée.

**Comment by Gaetanbrl** [comment]
@camillemonchicourt oui c'est certain, c'est pour cela qu'on a pas prévu d'afficher cette info de statut de validation pour le module SYNTHESE. Ca ne sera affiché que dans le module VALIDATION.

**Comment by Gaetanbrl** [comment]
@camillemonchicourt pour compléter mon précédent commentaire, voici un rendu de cette même occurrence mais avec l'onglet Discussion dans le module de SYNTHESE :

![image](https://user-images.githubusercontent.com/16317988/157279727-e9b2568a-2401-468f-8116-2c9184ad19b4.png)


Ce qui change : 

* Les commentaires sont dédiés à la SYNTHESE (l'ajout d'un commentaire de SYNTHESE n'est donc visible que dans le module SYNTHESE et pas dans le module VALIDATION qui n'a que des commentaires relatifs à la VALIDATION)
* Les statuts ne sont pas affichés car on est dans le module SYNTHESE

**Comment by camillemonchicourt** [comment]
Hum hum j'avais pas compris qu'il y avait des discussions liées à la Synthèse et d'autres liées à la Validation.
Et on ne pense pas que cela soit souhaitable.
Dans le cas où on est dans une logique globale de discussion, ouvertes dans le module Synthèse et dans le module Validation, alors ce sont les mêmes échanges que l'on affiche dans les 2 modules, il ne faut pas séparer les discussions par module.
On discute sur une observation, peu importe le module.

Dans le module Validation, dans ce cas, on veut pouvoir voir les discussions faites entre observateurs concernant l'observation, et éventuellement y répondre, que l'on soit dans le module Validation ou dans la Synthèse.

Ceux qui ne veulent pas que les discussions soient ouvertes à tous mais seulement aux validateurs qui ont accès au module Validation utiliseront pour cela le paramètre ``ENABLE_SYNTHESE_DISCUSSION`` pour le passer à ``false``.

**Comment by Gaetanbrl** [comment]
En effet je pense qu'on ne s'est pas compris car ce fonctionnement était le résultat de notre dernier échange (que les validateurs puissent échanger entre eux sans que ce soit forcément à la vue de tous dans leur rôle de modération des statuts).

On peut modifier / adapter ce comportement c'est l'objectif des propositions dans les issues.

**Comment by camillemonchicourt** [comment]
Ça me semble dommage de séparer les discussions. @TheoLechemia pense pareil.

**Comment by pierrejego** [comment]
Les développements qui ont été réalisé permettent d'avoir deux discussions différentes. Les échanges des validateurs n'ont pas pour objectif d'être publique ( dans le cahier des charges pour lequel nous avons répondu), or ils deviendraient publique si on active la discussion dans la synthèse
 
Ce qu'on a prévu permet justement d'avoir un flux de discussion publique dans la synthèse et un flux en accès uniquement pour ceux qui ont accès au module de validation.

Et il est possible d'activer soit  : 
- la discussion de la synthèse
- la discussion de la validation
- soit les deux

Je pense qu'il serait intéressant d'en parler ensemble ou en cotech geonature pour avoir un avis plus global.
@jbdesbas @jpm-cbna  vous en pensez quoi ?

**Comment by camillemonchicourt** [comment]
Oui à discuter.
Car je ne vois pas l'intérêt de séparer les discussions dans le module Validation de celles dans le module Synthèse, par contre ça a pas mal d'inconvénients et limite l'usage de l'outil de discussions.

Ce que j'avais retenu est que comme il est souhaité des discussions entre validateurs uniquement dans votre cahier des charges, dans ce cas la fonctionnalité ne serait pas activée dans la Synthèse, mais pas que les échanges soient séparés.

A discuter si besoin en effet.

**Comment by Gaetanbrl** [comment]
Suite à notre échange de ce matin, voici une nouvelle proposition  à valider @jbdesbas @TheoLechemia @camillemonchicourt : 

* Commentaire du statut visible via une tooltip au dessus du badge du statut
* Un icône en forme de message permet de voir quels sont les statuts avec commentaires
![image](https://user-images.githubusercontent.com/16317988/157917575-545e7734-1740-4836-9dd6-19561647eef6.png)

* Le flux de discussion est identique entre l'onglet discussion du module STYNHESE et celui de VALIDATION

* Lorsqu'un utilisateur supprime son message, on modifie en réalité le contenu par du contenu vide et on affiche qu'il y a un message qui a été supprimé (oeil barré)

![image](https://user-images.githubusercontent.com/16317988/157918498-68e36875-b0cd-499a-b95c-44487d4267ca.png)

* Le passage de la souris sur l'icône permet de voir qui a supprimé et quand

![image](https://user-images.githubusercontent.com/16317988/157918533-735d4094-e350-44fc-a28f-1b741a68fc2b.png)

## Preview

![image](https://user-images.githubusercontent.com/16317988/157917244-c7870494-78c2-4f77-88e8-8df32b74a4ae.png)

**Comment by camillemonchicourt** [comment]
OK pour moi, je trouve ça vraiment très bien comme ça.

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.10.0.
