### ISSUE TITLE
V2 - Généricité des filtres Synthèse

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#174]
Il a par exemple été demandé : 

> Pouvoir remplacer les filtres "taxons patrimoniaux" et "taxons protégés" par "taxons N2000" + "taxons protégés" + "taxons listes rouges"

A voir comment rendre cela générique en pouvant paramétrer les attributs de TaxHub utilisés comme filtres. 

On pourrait gérer cela en paramètre dans GeoNature avec une liste des ID des attributs TaxHub à utiliser.

**Comment by gildeluermoz** [comment]
Modifier la vue ``vm_taxref_list_forautocomplete`` pour y intégrer les attributs taxhub ou ``id_theme=Geonature``
Côté frontend: se baser sur des pseudo champs pour afficher les filtres.

**Comment by camillemonchicourt** [comment]
Dans la V2 les filtres sur les attributs sont génériques, dynamiques et paramétrables.
