### ISSUE TITLE
GN 2.9.2 : Désinstallation de modules externes 

### ISSUE THREAD

**Issue by JeromeMaruejouls** [PnX-SI/GeoNature#1745]
Bonjour,
Je rencontre des problèmes pour réinstaller un module externe (Monitoring notamment).
J'ai supprimé les lignes correspondantes dans t_modules et les tables et lignes crées dans la base lors de l'installation du module.
J'ai supprimé le lien symbolique dans external_module.
Lorsque je retente l'installation du module, j'ai un message me spécifiant que le module est déjà installé.
De plus, dans la configuration du CRUVED du module admin, les modules concernés sont toujours présents.
Savez vous ce qui pourrait rester de ce module et qui empêche la réinstallation ?

Et autre question : à quoi servent les deux booléens active_frontend et active_backend de la table t_module ? Pour le front end, je pense qu'en cas d'activation, il serait bien que les modules ne soient plus accessible dans le menu. Qu'en pensez vous ?

(sans autre solution, je repartirai d'une installation propre)

**Comment by camillemonchicourt** [comment]
A voir si tu as vraiment besoin de désinstaller un module ?
C'est vrai que ce n'est pas vraiment prévu actuellement.

Voir aussi cette discussions : https://github.com/PnX-SI/GeoNature/issues/900
Voir aussi : https://github.com/PnX-SI/gn_module_import/issues/149

---------------------------

``active_frontend `` et ``active_frontend`` permettent d'avoir des modules qui n'ont qu'un backend ou qu'un frontend dans GeoNature, mais ça doit pas être ton cas. Il n'y a pas de modules officiels de GeoNature qui sont concernés par un de ces 2 cas. Ils ont tous un backend et un frontend dans GeoNature.

**Comment by JeromeMaruejouls** [comment]
Je finalise la mise mise à jour de tout mes modules sur la dernière version de GN. Et vu que j'avais un peu trafiqué lors de l'install de ce module monitoring, je préfèrerais pouvoir repartir d'une base saine.

Mais c'est bon, j'ai réussi à relancer l'install. J'avais dû laisser trainer une donnée en base. Maintenant l'install s'est bien déroulé et je vais pouvoir lancer l'installation des sous modules.

Merci !
