### ISSUE TITLE
[2.9.1] Erreur 401 lors de la validation d'une saisie sur Occtax ou Monitoring

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature#1747]
**Version**
2.9.1

**Description du bug**
Code 401 retourné lors d'une validation de formulaire (Monitoring ou Occtax) pour l'un de mes utilisateurs.
Plusieurs test ont été fait et:
- Il n'y a pas de problème en me connectant sur son compte en navigation privé sur mon ordi, et en saisissant une occurrence (sur Mozilla)
- Il n'y a pas de problème en se connectant sur son compte sur son ordi, et en saisissant une occurrence (sur Edge)
- Il y a un problème en se connectant sur son compte sur son ordi, et en saisissant une occurrence (sur Mozilla)
- Nous avons la même version de Mozilla
- Il a pu saisir 5 occurrences avant que le problème survienne
- J'ai arrêté et redémarrer GeoNature, j'ai vidé son cache, rien n'y fait

**Comportement attendue**
Déconnexion (retour sur la page de login) lors de la validation d'une occurrence dans le module Occtax ou Monitoring

**Logs**
Pas de log mais une capture d'écran des avertissements et erreurs
![error_401](https://user-images.githubusercontent.com/66769358/156341555-8699bc07-0f9a-422b-b1d6-564214b9a14b.jpg)

**Comment by TheoLechemia** [comment]
Une piste : 
l'appel à l'API se fait en HTTP alors que le front à l'air d'être servi en HTTPS ?

**Comment by maximetoma** [comment]
Ah ? Bizarre de quel manière le front peut-il être servi en HTTPS ?
Normalement il est bien servi en HTTP

**Comment by TheoLechemia** [comment]
Non pardon j'ai mal lu les warning.
Mais il faut investigué du côté des warnings, car c'est justement l'absence de token dans la requête qui provoque la 401.

**Comment by TheoLechemia** [comment]
Est-ce que tu peux envoyer le contenu du cookie :
![cookie](https://user-images.githubusercontent.com/15265745/157037134-15281a3a-2849-4f41-98b6-d914e15213c8.png)

**Comment by maximetoma** [comment]
Ah okay, il faut que je revoie avec l'utilisateur, je te transmets dès que possible !

**Comment by maximetoma** [comment]
Bon... on a retesté sur la machine de l'utilisateur sur Firefox aujourd'hui et tout semble bien fonctionner !
Il m'a juste indiqué que la dernière fois il était en télétravail et aujourd'hui il est sur la réserve mais avec la même machine

Pour le moment je ferme le ticket mais s'il a de nouveau le problème, je le réouvrirai en copiant toutes les logs (ou du moins le contenu du cookie) :) Merci quand même @TheoLechemia !
