### ISSUE TITLE
Signaler une occurence

### ISSUE THREAD

**Issue by pierrejego** [PnX-SI/GeoNature#1750]
La proposition ci-dessous peut évoluer selon les besoins et les échanges.
Picardie-nature est le commanditaire de cette demande
N'hésitez-pas à intervenir pour tout commentaire / suggestions sur les aspects techniques ou fonctionnelles.

_### Description fonctionnelle_

En tant qu'**utilisateur**
Je souhaite **signaler une observation en y ajoutant un commentaire**
Afin d'effectuer **d'aider les opérations de validation**.

En tant qu'**utilisateur qui a saisi un signalement**
Je souhaite **supprimer le signalement que j'ai ajouté**
Afin d'effectuer de **corriger une erreur de saisie. ( mauvais signalement)**

En tant que **validateur**
Je souhaite **lister les observations signalées**
Afin d'effectuer **de mettre à jour l'occurrence**

En tant que **validateur**
Je souhaite **supprimer les signalements**
Afin de **montrer que le signalement a été pris en compte**

Cette évolution permet de rajouter une interaction entre les utilisateurs de la plateforme et les validateurs.

Une fois le signalement ajouté via la fiche de détails de la synthèse ou la validation.
Il faut l'ajouter dans la synthèse et pas uniquement dans la validation pour que les utilisateurs qui ne sont pas validateur puisse ajouter un signalement

![image](https://user-images.githubusercontent.com/11499415/156388377-e3d1f0b9-3dca-4c12-91e5-fced3e32ec93.png)

Un click sur le bouton "drapeau" ouvrira une modale ressemblant à la modification de statut de validation avec uniquement une zone commentaire.

On pourra voir facilement les signalements dans la liste des occurrences dans les modules validation et synthèse (via une icone drapeau orange)

![image](https://user-images.githubusercontent.com/11499415/156380388-e29e1cf5-f709-4c59-9321-612b429658d5.png)

Il reste encore à définir la zone dans la partie frontend ou le commentaire du signalement pourrait être vu.

_### Description technique_

- Base de données

Une nouvelle table t_reporting sera ajouté dans le schéma gn_commons

champ | type
-- | --
id_reporting | PK
id_synthese | string
id_role | string
comments | string
date | date
type_reporting | number

Le type_reporting va servir à différencier les signalements des autres possibilités comme l'épinglage d'une occurence ( évolution à venir)

- Backend

Ajout de endpoint permettant l'ajout et la suppression d'un signalement
Encore à définir

A noter qu'il ne peut y avoir qu'un seul signalement par id_synthèse et que l'historique des signalements n'est pas gardé.

- Frontend

Modification de la fiche de synthèse pour ajout d'un bouton de signalement et d'une zone de saisie (et d'un bouton de suppression si il y a un signalement et que c'est la personne connecté qu'il l'a renseigné)
Modification de la recherche pour ajout d'un filtre sur le signalement (synthèse et validation)
Modification de la liste de observation ( synthèse et validation) pour ajout des flags de signalement
Modification de la fiche de validation pour ajout d'un bouton de suppression de signalement

_### Suivi des travaux_

- [ ] Modification de la base de données
- [ ] Modification des services
- [ ] Ajout de la saisie d'un signalement
- [ ] Suppression d'un signalement
- [ ] Suppression d'un signalement automatique en cas de changement de statut de validation

**Comment by camillemonchicourt** [comment]
Je me demande si il ne faudrait pas utiliser la table ``t_discussions`` en cours d'ajout pour éviter de créer encore une autre table ?

Sinon, comme pour la table ``t_discussions``, je pense qu'il faut plutôt mettre cette table ``t_reports`` dans le schéma ``gn_synthese``.

Penser aussi à ce que cette fonctionnalité soit désactivable avec un paramètre dédié comme pour les discussions.

**Comment by pierrejego** [comment]
oui bonne idée,
a essayer de lier avec #1731 pour la partie backend et service

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.10.0.
