### ISSUE TITLE
GN 2.9.2 : Validation : erreur 500 lors du filtre sur "Possède des médias"

### ISSUE THREAD

**Issue by JeromeMaruejouls** [PnX-SI/GeoNature#1757]
Bonjour à tous,
Dans la dernière version, lorsque l'on filtre les observations qui possèdent un médias, on a le serveur qui renvoie une erreur 500. Pas de soucis dans la synthése.
Bug observé sur mes serveurs et sur l'instance démo de géonature.

**Comment by Gaetanbrl** [comment]
L'attribut `has_media` est manquant pour la vue Synthese utilisée pour le filtre : 
`'Synthese' has no attribute 'has_medias'`

https://github.com/PnX-SI/GeoNature/blob/7a63991560b564d69e465bd9494e957df5741ca3/backend/geonature/core/gn_synthese/models.py#L265

has_media est en effet existant mais sur la vue `VSyntheseForWebApp` :

https://github.com/PnX-SI/GeoNature/blob/7a63991560b564d69e465bd9494e957df5741ca3/backend/geonature/core/gn_synthese/models.py#L395

La PR avec le fix suivra ce commentaire.
