### ISSUE TITLE
V2 - Module d'import CSV

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#176]
Proposer un outil en interface pour importer des données sans devoir le faire en tant qu'administrateur dans la BDD. 

- A partir d'un CSV avec un format bien prédéfini.
- Message d'erreur si les données ne correspondent pas au format attendu
- Message d'erreur si doublons ?

L'import doit-il se faire dans un protocole bien particulier (ContactFaune notamment) ou cela doit être paramétrable ? Pouvoir choisir à quel jeu de données cela doit être rattaché ?

Ou alors importer directement dans la Synthèse ?

S'inspirer de https://github.com/TheoLechemia/BDN/tree/master/Apps/importCSV

**Comment by gildeluermoz** [comment]
Englober l'ensemble dans une transaction de manière à pouvoir faire un roolback pour annuler l'insertion en totalité si erreur.

**Comment by sig-pnrnm** [comment]
Cette fonctionnalité sera très utile. 👍 

A moins que ce travail soit fait en amont de l'import, un point d'attention particulière sera la reconnaissance des taxons : le cd_nom n'est pas toujours fourni avec les fichiers, et les données récupérées ne contiennent souvent qu'une colonne "nom_latin".
Celle-ci n'étant pas forcément basée sur la nomenclature TAXREF, la reconnaissance automatisée peut créer des erreurs.

Du coup, à l'import, il serait bon d'avoir la visibilité d'une sorte de "table de contrôle", avec `nom_source`, `nom_matché` et `cd_nom` pour les valeurs uniques d'occurences de taxons.

SERENA dispose d'une fonction sympa pour cela : "trouve taxons", qui permet d'avoir en plus de cette correspondance, un pourcentage de correspondance, qui permet d'identifier rapidement les erreurs potentielles. Je ne pense pas que ce soit très compliqué à écrire comme fonction.

**Comment by camillemonchicourt** [comment]
Concernant la recherche d'un cd_nom à partir du nom d'un taxon, un travail a été amorcé ici : https://github.com/PnX-SI/GeoNature/issues/445
A voir si il ne vaut pas plutôt utiliser directement l'API Taxref qui fait ça bien.

Concernant le module d'import, la suite des discussions est dans le nouveau dépôt dédié : https://github.com/PnX-SI/gn_module_import

**Comment by gildeluermoz** [comment]
A voir si une fonction centrale de GeoNature doit dépendre du fonctionnement d'un service externe.
