### ISSUE TITLE
Auto validation des comptes : Perte de l'information de champ structure 

### ISSUE THREAD

**Issue by mtaqarort** [PnX-SI/GeoNature#1760]
Geonature 2.9.1

Dans notre plateforme régionale, nous avons activé l'option d'auto validation des comptes Geonature, le nom de la structure renseigné par l'utilisateur est perdu après la validation de compte par ce dernier. l'administrateur ne peut plus assigner l'organisme dans usershub, l'information n'est plus disponible dans la base de données.

Peut être utiliser ce champs sous forme de champ supplémentaire ou ajouter cette information dan un nouveau champ.

**Comment by camillemonchicourt** [comment]
Oui c'est pas un bug. C'est un champs texte qui est stocké dans la table temporaire des utilisateurs, en attente de leur validation manuelle par un administrateur.

Dans le cadre de la validation automatique des comptes par l'utilisateur, il n'y a pas de mécanisme qui a été mis en place pour renseigné l'organisme de la personne.
D'ailleurs dans ce cas, on ne pourrait plus se baser sur un champs texte, mais il faudrait une liste déroulante basée sur la table des organisme de UsersHub.

Donc c'est bien une évolution à envisager, mais pas un bug à corriger.

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.13.0.
