### ISSUE TITLE
RefGeo et install requirements

### ISSUE THREAD

**Issue by Gaetanbrl** [PnX-SI/GeoNature#1769]
Ref à la PR #1713 .

Ce sujet a été évoqué avec @bouttier mais j'obtiens des erreurs. Cette issue aidera aussi à couvrir la procédure de récupération (mise à jour) des dépendances (requirements).

## Description 

Contexte de départ :
Sur une branche de travail, j'ai réalisé un rebase pour récupérer les derniers commits de la branche develop.
Suite à ce rebase le service geonature ne démarre plus : 

```
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/routes.py", line 29, in <module>
    from geonature.core.gn_synthese.models import (
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/models.py", line 24, in <module>
    from ref_geo.models import LAreas
ModuleNotFoundError: No module named 'ref_geo.models'
```

Suite à ce commit https://github.com/PnX-SI/GeoNature/commit/b64dcea253cb817492f28302bfcfb4275e083b53, il faut en effet mettre à jour les dépendances.

J'ai donc lancé les commandes : 

```
source ~/geonature/backend/venv/bin/activate
cd ~/geonature
pip install -e . -r requirements-common.txt -r requirements-submodules.txt
```
## Erreur 

J'obtiens l'erreur :

`ERROR: Could not open requirements file: [Errno 2] Aucun fichier ou dossier de ce type: 'requirements-common.txt'
`

Les fichiers `requirement-x` sont en effet localisés dans `~/geonature/backend`.

Je lance donc la commande suivante en précisant la localisation des fichiers : 

`pip install -e . -r backend/requirements-common.txt -r backend/requirements-submodules.txt`

Mais j'obtiens à nouveau une erreur : 

```
(venv) geonatureadmin@debian:~/geonature$ pip install -e . -r backend/requirements-common.txt -r backend/requirements-submodules.txt 
Obtaining file:///home/geonatureadmin/geonature
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Obtaining pypnusershub from file:///dependencies/UsersHub-authentification-module#egg=pypnusershub (from -r backend/requirements-submodules.txt (line 1))
ERROR: pypnusershub from file:///dependencies/UsersHub-authentification-module#egg=pypnusershub (from -r backend/requirements-submodules.txt (line 1)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

Un fichier `setup.py` ne semble pas présent (pourtant bien présent dans `~/geonature` mais je pense que ce n'est pas le même qui est nécessaire).

**Comment by Gaetanbrl** [comment]
J'ai lancé la commande suivante et ca a fonctionné : 

`pip install -e ~/geonature -r requirements.txt`

```
  Running setup.py develop for geonature
Successfully installed fiona-1.8.21 geoalchemy2-0.11.1 geonature-2.10.0.dev0 pypn-ref-geo-1.0.1 pypn_habref_api-0.3.0 pypnnomenclature-1.5.1 pypnusershub-1.5.9 taxhub-1.9.4 utils-flask-sqlalchemy-0.2.6 utils-flask-sqlalchemy-geo-0.2.2
```

Par contre j'ai toujours l'erreur avec ref_geo @bouttier @TheoLechemia 

```
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/routes.py", line 29, in <module>
    from geonature.core.gn_synthese.models import (
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/models.py", line 24, in <module>
    from ref_geo.models import LAreas
ModuleNotFoundError: No module named 'ref_geo.models'
```

**Comment by bouttier** [comment]
Le RefGeo inclue les modèles dans une version non releasé, disponible uniquement en dev.
Il faut donc installer les dépendances en tant que sous-modules :
```
git submodule init && git submodule update
pip install -e . -r backend/requirements-common.txt -r backend/requirements-submodules.txt
```

**Comment by bouttier** [comment]
Je vois que tu avais bien lancé cette commande ``pip``, mais tu n’avais pas initialisé les sous-modules (du coup les dossiers des modules dans ``backend/dependencies`` sont vide, et donc sans ``setup.py``).

**Comment by Gaetanbrl** [comment]
@bouttier les submodule sont déjà init et update.
La seconde commande me retourne une erreur comme indiqué en haut : 

`ERROR: pypnusershub from file:///dependencies/UsersHub-authentification-module#egg=pypnusershub (from -r backend/requirements-submodules.txt (line 1)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.`

**Comment by pierrejego** [comment]
![image](https://user-images.githubusercontent.com/11499415/157853987-211a287c-c8e2-4e97-9dbf-6acb12eecf6b.png)
 
même erreur ici

**Comment by pierrejego** [comment]
Et pourtant submodule bien à jour
![image](https://user-images.githubusercontent.com/11499415/157854088-417d56bd-ca54-4e60-bf21-6153b92f8f4b.png)

**Comment by bouttier** [comment]
Je me suis trompé, il faut lancer le pip depuis le dossier backend :
``cd backend && pip install -e .. -r requirements-commons.txt -r requirements-submodules.txt``
Va vraiment falloir nettoyer la doc à ce sujet …

**Comment by pierrejego** [comment]
Pas mieux,
le .. ne semble pas être pris en compte et il trouve pas les fichiers requirements.

```
(venv) geonatureadmin@geonature:~/geonature/backend$ pip install -e .. -r requirements-commons.txt -r requirements-submodules.txt
ERROR: Could not open requirements file: [Errno 2] Aucun fichier ou dossier de ce type: 'requirements-commons.txt'
```

**Comment by bouttier** [comment]
Autre typo … c’est évidemment ``requirements-common.txt`` sans le s final.

**Comment by pierrejego** [comment]
Ah oui pas vu celle la

**Comment by pierrejego** [comment]
Par contre toujours la même erreur au lancement
```
 File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/routes.py", line 29, in <module>
    from geonature.core.gn_synthese.models import (
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/models.py", line 24, in <module>
    from ref_geo.models import LAreas
ModuleNotFoundError: No module named 'ref_geo.models'
```

**Comment by Gaetanbrl** [comment]
Idem, comme déjà commenté, même erreur au lancement du `dev_back` le soucis ne vient pas des requirements qui passent bien comme commenté plus haut, mais de `reg_geo.models` qui n'est pas reconnu installé alors que pour résumé : 

* On a bien un init + update des submodules
 
![image](https://user-images.githubusercontent.com/16317988/157877883-e4fdbaa7-71d6-41f7-9190-c2a887d2dff6.png)

* On a bien reinstall les requirements
`
Successfully installed geonature-2.10.0.dev0 pypn-ref-geo-1.0.1 pypn_habref_api-0.3.0 pypnnomenclature-1.5.1 pypnusershub-1.5.9 taxhub-1.9.4 utils-flask-sqlalchemy-0.2.6 utils-flask-sqlalchemy-geo-0.2.2`

* le `geonature dev_back` retourne une erreur et le service ne démarre pas :

```
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/routes.py", line 29, in <module>
    from geonature.core.gn_synthese.models import (
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/models.py", line 24, in <module>
    from ref_geo.models import LAreas
ModuleNotFoundError: No module named 'ref_geo.models'
```

**Comment by Gaetanbrl** [comment]
Branche develop du fork picardie-nature (à jour avec develop PnX-SI/GeoNature):
https://github.com/picardie-nature/GeoNature/commits/develop

Dernier commit de la branche : 
05856732c85614a9a4e421cfdbd1e7f910671a90

Commit RefGeo : 
https://github.com/PnX-SI/RefGeo/tree/815512cd4ae4da28fd031c21428160378d997028

**Comment by pierrejego** [comment]
On était sur une branche de picardie-nature issue-1727-PR.
Mais je viens de faire un checkout de la developp
commit 05856732c85614a9a4e421cfdbd1e7f910671a90 (HEAD -> develop, origin/develop)

Et commit 9bc11320a76a912808ca2c09b6fdf544740eae1c (HEAD, tag: 1.0.1, origin/master, origin/HEAD, master)
pour RefGei

**Comment by bouttier** [comment]
Ce n’est pas le dernier commit de la branche ``develop`` du RefGeo. Il est donc normal de ne pas bénéficier des modèles qui ont été introduit par le commit https://github.com/PnX-SI/RefGeo/commit/999c59a20840660113b59422401787cbb2e2d598.

Le dernier commit de la branche ``develop`` de GeoNature (https://github.com/PnX-SI/GeoNature/commit/05856732c85614a9a4e421cfdbd1e7f910671a90) pointe bien le dernier commit de la branche ``develop`` du RefGeo (https://github.com/PnX-SI/RefGeo/commit/815512cd4ae4da28fd031c21428160378d997028) comme cela peut être vérifié ici : https://github.com/PnX-SI/GeoNature/tree/develop/backend/dependencies

**Comment by pierrejego** [comment]
Ok donc il faut faire en plus des manips un 
```
cd backend/dependencies/RefGeo
git checkout develop
```

Il faudrait point le submodule RefGeo de la developp sur le commit de la branche develop  et pusher la modif

**Comment by Gaetanbrl** [comment]
Oui en l'état lors du submodule init update on ne pointe pas vers la bonne branche (HEAD) comme indiqué par Pierre : 

commit 9bc11320a76a912808ca2c09b6fdf544740eae1c (HEAD, tag: 1.0.1, origin/master, origin/HEAD, master)

Il ne faudrait pas préciser dans le .gitmodules le commit ou branch à utiliser ? sinon c'est la master qui est prise par défaut

**Comment by bouttier** [comment]
Comme je le disais, la ``develop`` de GeoNature pointe déjà sur le commit approprié du RefGeo, comme cela peut être vérifié ici : https://github.com/PnX-SI/GeoNature/tree/develop/backend/dependencies
Il n’est donc pas nécessaire de checkout develop manuellement.
En revanche, il faut demander à Git de mettre le RefGeo sur le bon commit avec ``git submodule update`` (depuis le dépôt GeoNature). Il peut être vérifié que le RefGeo est sur le bon commit avec ``git status`` (depuis GeoNature toujours).

**Comment by Gaetanbrl** [comment]
> a develop de GeoNature pointe déjà sur le commit approprié du RefGeo

Le git submodule update a pourtant été réalisé plusieurs fois comme on l'a bien compris (et comme on peut le faire ailleurs que dans GeoNature).

On a quand même du passer manuellement sur develop dans le repo RefGeo manuellement pour avoir le bon commit.
Dans tous les cas Merci @bouttier pour le pointage de l'origine du problème.

On restera bien d'accord qu'il faut bien vérifier les commits de départ pour les submodules, surtout quand on doit faire des rebase sur des branches en retard dans un fork.

✔️ Les autres commandes on bien fait le job et le dev_back démarre à présente correctement.

Je clos.
