### ISSUE TITLE
Rendre les secteurs indépendants des communes

### ISSUE THREAD

**Issue by ClaireLagaye** [PnX-SI/GeoNature#177]
Avec les regroupements de commune (et la création de la commune géante de Val-Cenis regroupant 5 communes) on a maintenant 2 secteurs qui se partagent la même commune...
Ou alors rendre générique ces localisations de données / recherches géographiques?

**Comment by camillemonchicourt** [comment]
En effet, on avait eu le même problème avec l'application POLICE et l'application GEOTREK. 
Dans la V2 on veut rendre plus générique cette notion de SECTEURS qui ne concernent que les parcs nationaux, et pour le point évoqué, le mieux est peut-être de rendre les communes et les secteurs indépendants, plutôt que devoir gérer du N-N.

**Comment by camillemonchicourt** [comment]
On n'a plus de secteurs dans la V2. 
Si des structures veulent des secteurs, elles pourront les mettre dans la table générique des LAYERS.
