### ISSUE TITLE
Changement de couleur des infobulles (tooltip) dans la synthese

### ISSUE THREAD

**Issue by metourneau** [PnX-SI/GeoNature#1775]
**Version**
2.9.2

**Description du bug**
Les tooltips changent de couleur (elles deviennent grises). Ca écrase tous les autres styles

**Comportement attendue**
Pas de changement de style

**Comment reproduire**
Tout le temps dans la synthèse

Le problème vient d'une mauvaise utilisation de la librairie "material" dans le fichier geonature/frontend/src/app/GN2CommonModule/form/synthese-form/synthese-form.component.scss

Il ne faut pas surcharger la class cdk-overlay-pane
```
.cdk-overlay-pane {
  &.mat-tooltip-panel {
    .mat-tooltip {
      color: black;
      background-color: rgba(231, 228, 228, 0.85);
      border-radius: 3px;
      font-size: 15px;
      padding: 10px;
    }
  }
}
```
mais créer une classe 

```
.my-tooltip{
  color: black;
  background-color: rgba(231, 228, 228, 0.85);
  border-radius: 3px;
  font-size: 15px;
  padding: 10px;
}
```

et attribuer cette classe aux tooltip souhaités

```
<button
      class="btn btn-sm btn-outline-shadow period"
      data-toggle="collapse"
      data-target="#collapsePeriod"
      matTooltip="Ajouter une période"
      matTooltipClass="my-tooltip"
>
```

Bonne journée

**Comment by Gaetanbrl** [comment]
Je pose ici une référence au commentaire sur les tooltip (ce n'est peut-être pas la meilleure solution mais ca a bien marché pour certains dev)

https://github.com/PnX-SI/GeoNature/issues/1474#issuecomment-1041337456

> Un bon nombre de tooltip / traduction ne sont pas visibles ou affichées derrière la modal.
Pour un affichage de la tooltip, je propose d'utiliser le coposant [ngbTooltip (ng-bootstrap)](https://ng-bootstrap.github.io/#/components/tooltip/api) (voir tooltip dans la capture du point 2 précédent):

**Comment by Gaetanbrl** [comment]
> on peut également augmenter le z-index du container

C'est vrai, mais si on met une valeur +++ à chaque problème d'affichage, le conflit n'est que reporté jusqu'au prochain overlay à afficher en top.

Une ref sur ce sujet ici  : 

https://www.digitalocean.com/community/tutorials/css-z-index

> In CSS code bases, you’ll often see z-index values of 999, 9999 or 99999. This is a perhaps lazy way to ensure that the element is always on top. It can lead to problems down the road when multiple elements need to be on top. Most of the time you’ll find that a z-index of 1 or 2 will suffice for your needs.

**Comment by metourneau** [comment]
T'as raison. Je suis feignant.
J'ai pas pris le temps de chercher la bonne valeur du z-index. 1080 pour Bootstrap et 1000 pour Material, donc un z-index à 1080 suffit. 
Le problème se pose quand on mélange les librairies, pour le coup Select et Modal boostrap et tooltip Material

**Comment by Gaetanbrl** [comment]
> J'ai pas pris le temps de chercher la bonne valeur du z-index

On a tous ce reflex avec les z-index mais je me suis déjà fait piégé et au bout d'un moment ca ne passe plus (ex: modal sur modal >> oui ca peut arriver...).

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.10
