### ISSUE TITLE
[install pour dev] geonature.utils.module.NoManifestFound: Can not find manifest.toml for module OCCTAX

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature#1782]
Je tente de refaire une installation propre de mon geonature pour le dev sans passer par l'install_all pour éviter de tout redéplacer et faire le git init (trop de données à re-télécharger).

Etapes réalisées:
Récupération de la dernière version de la branche develop
Installation du backend et des submodules
```
cd install
./01_install_backend.sh
git submodule init && git submodule update
cd backend
source venv/bin/activate
pip install -r requirements-submodules.txt
```
Jusqu'ici, tout va bien.

Par contre, lorsque je lance le script `02_install_db.sh`, je rencontre cette erreur... occtax est bien dans le dossier external_modules.

Quelqu'un a une piste ? 
Merci.

```
...
    for module_object, module_config, module_blueprint in import_backend_enabled_modules():
  File "/home/fcloitre/Dev/gn_projects/geonature/backend/geonature/utils/module.py", line 111, in import_backend_enabled_modules
    yield import_gn_module(module_object)
  File "/home/fcloitre/Dev/gn_projects/geonature/backend/geonature/utils/module.py", line 97, in import_gn_module
    module_config, module_blueprint = import_legacy_module(module_object)
  File "/home/fcloitre/Dev/gn_projects/geonature/backend/geonature/utils/module.py", line 35, in import_legacy_module
    raise NoManifestFound(f"Can not find manifest.toml for module {module_object.module_code}")
geonature.utils.module.NoManifestFound: Can not find manifest.toml for module OCCTAX
```

**Comment by joelclems** [comment]
Est ce que tu part d'une base existante ou les modules dont occtax sont dans gn_commons.t_modules

Le module occtax est passé en module packagé, en backend c'est un module python
la commande suivante devrait résoudre le problème
```
pip install -e <chemin vers geonature>/contrib/occtax
```
il faudra peut être faire de même avec les modules occhab et validation

**Comment by lpofredc** [comment]
Merci @joelclems, c'était en effet la solution au pb

> Est ce que tu part d'une base existante ou les modules dont occtax sont dans gn_commons.t_modules
> 
> Le module occtax est passé en module packagé, en backend c'est un module python la commande suivante devrait résoudre le problème
> 
> ```
> pip install -e <chemin vers geonature>/contrib/occtax
> ```
> 
> il faudra peut être faire de même avec les modules occhab et validation
