### ISSUE TITLE
GN 2.9.1 : Occtax : Accès à la liste des jeux de données

### ISSUE THREAD

**Issue by randiflora** [PnX-SI/GeoNature#1786]
Bonjour,

Je rencontre un problème de droits d'accès que je n'arrive pas à résoudre :
En tant qu'utilisateur avec des droits d'administrateur, j'ai créé tous les cadres d'acquisitions et les jeux de données associés dont la structure a besoin. J'ai associé les jeux de données à tous les modules de Geonature.

Cependant, les autres utilisateurs, en création de relevés dans Occtax, ne voient aucun jeu de données dans la liste. Ces utilisateurs, créés dans UsersHub avec un profil rédacteur pour Géonature, appartiennent tous à un même groupe. Quels CRUVED dois-je affecter à ce groupe pour qu'ils voient les jeux de données que j'ai créés ?

Voici les CRUVED actuels du groupe d'utilisateurs en question :
ADMIN
    Créer (C) : 0
    Lire (R) : 0
    Mettre à jour (U) : 0
    Valider (V) : 0
    Exporter (E) : 0
    Supprimer (D) : 0
GEONATURE 	
    Créer (C) : 1
    Lire (R) : 3
    Mettre à jour (U) : 1
    Valider (V) : 0
    Exporter (E) : 3
    Supprimer (D) : 1
METADATA 	
    Créer (C) : 2
    Lire (R) : 3
    Mettre à jour (U) : 2
    Valider (V) : 0
    Exporter (E) : 3
    Supprimer (D) : 1
OCCHAB 	
    Créer (C) : 1
    Lire (R) : 3
    Mettre à jour (U) : 1
    Valider (V) : 0
    Exporter (E) : 3
    Supprimer (D) : 1
VALIDATION 	
    Créer (C) : 0
    Lire (R) : 0
    Mettre à jour (U) : 0
    Valider (V) : 0
    Exporter (E) : 0
    Supprimer (D) : 0
OCCTAX 	
    Créer (C) : 1
    Lire (R) : 3
    Mettre à jour (U) : 1
    Valider (V) : 0
    Exporter (E) : 3
    Supprimer (D) : 1
SYNTHESE 	
    Créer (C) : 1
    Lire (R) : 3
    Mettre à jour (U) : 1
    Valider (V) : 0
    Exporter (E) : 3
    Supprimer (D) : 1
DASHBOARD 	
    Créer (C) : 1
    Lire (R) : 3
    Mettre à jour (U) : 1
    Valider (V) : 0
    Exporter (E) : 3
    Supprimer (D) : 1

Avez-vous besoin de plus d'infos ?
Merci d'avance.

**Comment by TheoLechemia** [comment]
Bonjour,
Quel version de GeoNature avez-vous ?
Depuis la version 2.9 ce sont les permissions d'occtax qui sont vérifiés pou afficher la liste des JDD dans le module Occtax. Sur les version anterieurs ce sont les permissions sur GeoNature.
Est-ce que les JDD sont marqué comme "actif" ?
Est-ce que vos utilisateurs font parti de plusieurs groupes ?

**Comment by randiflora** [comment]
Merci de votre réponse et pour les détails concernant la gestion de ces permissions sur GeoNature.
La version de GeoNature est la 2.9.1, les JDD sont bien actifs et les utilisateurs concernés appartiennent tous au même groupe.
J'ai reçu également une réponse de Donovan Maillard, sur la liste "geonature-info", où j'avais posé ma question à tort :

> ... Leur droit d’écriture (C) pour Occtax est de 1, ça implique qu’ils ne peuvent saisir des données que dans leurs propres jeux de données, donc que les utilisateurs soient mentionnés « personnellement » comme acteurs du jeu de données.

Je pense que ça répond à ma question, je vérifierai ça jeudi.
Merci encore.

**Comment by camillemonchicourt** [comment]
En effet, il faut comprendre les 2 aspects.
Les JDD proposés à la saisie à un utilisateur dans la Saisie Occtax, dépend de son CRUVED "C" sur le module Occtax, depuis la version 2.9. Voir https://github.com/PnX-SI/GeoNature/issues/659#issuecomment-972829195

Si ce CRUVED est égal à 1 (Mes données), alors l'utilisateur pourra saisir que dans les JDD sur lesquels il est directement acteur.
Si ce CRUVED est égale à 2 (Les données de mon organisme), alors l'utilisateur pourra saisir dans tous les JDD sur lesquels il est directement acteur et/ou son organisme est directement acteur.

**Comment by randiflora** [comment]
Ok, merci pour ces précisions. Je viens de corriger les CRUVED et ça fonctionne bien.
Merci à tous.

**Comment by GwenUrcpie** [comment]
Bonjour,
Est-ce que c'est possible d'ouvrir un jeu de données à tout un organisme, sans citer tous ses membres, sachant que le C de occtax est égal à 1 (Mes données). Typiquement c'est un jeu de données opportuniste général, mais je dois quand même partitionner les jdd au sein de l'organisme.

**Comment by TheoLechemia** [comment]
Oui il est possible d'ouvrir un JDD à tout un organisme 

<img width="442" height="467" alt="Image" src="https://github.com/user-attachments/assets/a2beefe4-baa0-4652-ac81-1cd258e409fe" />

Par contre le C=1 va vérifier que la personne est personnellement actrice du JDD, en son nom propre, pas via son organisme. Pour que toute les personnes d'un organisme puisse saisir dans un JDD qui est associé seulement à son organisme, il faut mettre un C=2

**Comment by GwenUrcpie** [comment]
D'accord mais si je veux ouvrir ce JDD à l'organisme, tout en gardant le C = 1 a priori ce n'est pas possible ?
En fait j'ai un organisme avec beaucoup de monde et de projets différents, ça fait que la liste des JDD est longue et ça peut provoquer des erreurs de saisie / de la confusion, du coup j'aurais tendance à garder C = 1 mais j'ai quand même besoin d'ouvrir un JDD à l'organisme entier. 
Dans ce cas là, il faudrait mettre C = 2 en effet et affecter les JDD directement aux agents qui en ont besoin sans citer l'organisme, le problème c'est que j'ai tendance à quand même citer l'organisme dans les métadonnées pour des besoins de clarté l'ors de la transmission de données.

**Comment by camillemonchicourt** [comment]
Le fonctionnement est celui indiqué précédemment, ainsi que dans la documentation et rappelé par Théo : 
Si ce CRUVED est égale à 2 (Les données de mon organisme), alors l'utilisateur pourra saisir dans tous les JDD sur lesquels il est directement acteur et/ou son organisme est directement acteur.

Je ne vois pas bien comment vous voudriez faire des exceptions pour certains JDD ?
Ça ferait 2 mécanismes différents pour définir dans quels JDD on peut saisir ?

Pouvez-vous préciser le fonctionnement que vous souhaiteriez ?
Dans tous les cas, il faudra en prendre en charge le développement.
