### ISSUE TITLE
SYNTHESE - Dates de recherche par défaut

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#179]
Pouvoir les configurer ou les désactiver pour qu'il n'y ait pas de date par défaut.

**Comment by camillemonchicourt** [comment]
Actuellement dans GN2, on n'en renseigne pas par défaut.
A voir si il faut pouvoir en paramétrer par défaut ou pas.

**Comment by DonovanMaillard** [comment]
C'est un avis perso, je ne mettrais pas de date par défaut. Déjà car c'est difficile de savoir ce que l'utilisateur a le plus de chances/l'habitude de rechercher. Et à l'inverse, ca crée des erreurs : "je n'avais pas vu que par défaut je ne cherchais les données que depuis 2000" par exemple. 

C'est une erreur que j'ai pas mal vue chez les (anciens) collegues qui ne voyaient pas les mentions anciennes car elles ne ressortaient pas dans la synthèse si on changeait pas la date à chaque recherche

**Comment by gildeluermoz** [comment]
tout a fait d'accord avec Donovan

**Comment by camillemonchicourt** [comment]
OK aussi. Donc on laisse comme ça, sans valeur par défaut.
