### ISSUE TITLE
Amélioration affichage du composant pnx-taxonomy (Synthese / Validation)

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature#1803]
Le texte afficher dans le menu déroulant est trop grand.
Dans le module Synthese s'est presque illisible.
Il faudrait diminuer la taille de la police et réduire les `padding` pour afficher plus clairement les noms scientifiques.

Par ailleurs, il serait intéressant que la liste des noms s'affiche au-dessus de tous les autres éléments dans la Synthese.

Exemple de rendu final:
![Screenshot_20220327_222154](https://user-images.githubusercontent.com/51449363/160299660-eb2f517c-dc1d-4362-85eb-b961c1e1cd0b.png)

**Comment by TheoLechemia** [comment]
Si tu arrives à l'afficher au dessus je suis preneur. J'ai jamais réussi à le faire !

**Comment by Gaetanbrl** [comment]
je link cette PR https://github.com/PnX-SI/GeoNature/pull/1702
