### ISSUE TITLE
Module de validation des données

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/GeoNature#181]
Bonjour à tous,

Après quelques mois d'utilisation de GeoNature au Parc Normandie-Maine, mes collègues du pôle Patrimoines Naturels formalisent actuellement leurs besoins sur GeoNature (notamment en vue des développements de la V2 et d'une petite enveloppe dédiée en dévellopements)
Un des points prioritaires pour eux serait la mise en place d'un **module de validation des données**.

Je ne sais pas si vous avez déjà évoqué ce besoin, mais j'ouvre donc cet "issue" pour en discuter avec vous (je crois que Camille m'avait dit que les PN n'en avaient pas besoin, leurs données étant considérées comme valides à la source).

Le principe : 
Une observation se voit attribuer un "statut de validation" par un ou plusieurs validateur(s) (utilisateur(s) avec des droits particuliers).
Un validateur peut avoir des droits de validation uniquement sur certains groupes taxonomiques (ex. _Robert valide les données Oiseaux_ ; _Germaine valide les données Botaniques_ ; ...)

L'objectif serait d'avoir une interface la plus ergonomique possible (la validation peut être un processus très pénible !), avec possibilité de validations par lot : par "espèce" (_je valide toutes les données de Rougegorge_), par "observateur" (_je valide toutes les données de Germaine_), par date, par lieu, ... et par croisement de différents critères (_je valide toutes les données Oiseaux de Germaine du mois de mars_)

Pour ce qui est des statuts de validité, il faudrait avoir plusieurs catégories (non encore définies, mais du genre "validé", "invalidé", "besoin d'infos complémentaires", "douteux", ...). Et que toutes les données non validées soient considérées "en attente de validation").

L'objectif serait que ce module soit le plus générique possible, activable ou non dans GeoNature.
 ##
Peut-être même (à vous de me dire), cela devrait être indépendant : "GeoNature-Validation".

Voila, n'hésitez pas à me faire part de vos remarques sur ce besoin :)

**Comment by camillemonchicourt** [comment]
Concernant un module de validation, nous n'en avons pas le besoin au PNE mais d'autres parcs nationaux en ont besoin.
Du coup le PNVanoise a commencé à développer un module de validation pour les données flore, en se basant sur le travail de @TheoLechemia sur BDN-Guadeloupe : https://github.com/TheoLechemia/BDN
Pour faciliter les choses, Theo leur a isolé le module de validation (https://github.com/TheoLechemia/validationNaturaliste) qu'ils ont retravaillé pour leur besoin. Je ne sais pas où ils en sont. @ClaireLagaye et @Chrispnv pourront peut-être en dire plus. 

Dans tous les cas, dans le premier doc sur la V2 de GeoNature (http://geonature.fr/documents/2017-04-GN2-Fonctionnalites-0.1.pdf), le sujet de la validation est évoqué. 

Voici les éléments : 

> Ajout dans le contact des champs : 
> - Validation / Relecture (Désactivable)
> - Validateur, renseigné automatiquement lors de la validation. Basé sur une liste de UsersHub (1-N)
> 
> **Validation des données :**
> 
> - Outil de validation ? Dans chaque outil ou global ?
> - Première validation automatisée pour mettre de côté les observations exceptionnelles
> - Validation/Relecture manuelle avec possibilité de filtre et de validation par lot.
> - Ajouter une raison d’invalidation sous forme de texte ?
> - Ajouter à cela un mécanisme d’identification automatique des potentiels doublons (même date, taxon et géométrie).
> - Génération automatique de l’identification nationale de chaque occurrence de taxons
> - Message automatique lors de la saisie de données aberrante/exceptionnelle ?

Il est important que la validation soit activable/désactivable pour ceux qui ne veulent pas la mettre en oeuvre. 

Il faut bien définir les règles d'alimentation de la Synthèse et de possibilité d'export en fonction de la validation. 

Il faut voir si l'on valide les données au niveau de leur protocole ou au niveau de la Synthèse ? Si l'on fait une interface globale ou si il y a un outil de validation dans chaque protocole ? Si c'est une interface globale, comment fait-on remonter les infos spécifiques à un seul protocole qui peuvent être utiles à la validation mais par définition ne sont pas communes à toutes les données ?

**Comment by camillemonchicourt** [comment]
Pour la validation, voir aussi le guide SINP : http://spn.mnhn.fr/spn_rapports/archivage_rapports/2016/SPN%202016%20-%2077%20-%20guide_validation_occ_tax_SINP_V1.pdf

**Comment by sig-pnrnm** [comment]
Merci pour toutes ces infos Camille.
Bonne nouvelle que ce module ait déjà été réflechi et commencé d'être développé.
Si une instance de GeoNature permet de tester l'interface de @TheoLechemia , je suis intéressé pour mettre mon nez dedans.

> Il faut voir si l'on valide les données au niveau de leur protocole ou au niveau de la Synthèse ?

Il me paraitrait plus pertinent de valider au niveau de la source : donc au protocole. Le statut de validation d'une donnée doit accompagner cette donnée depuis sa source. Il s'agit d'une information élémentaire, au même titre que l'Observateur, le Taxon ou le Déterminateur.

> comment fait-on remonter les infos spécifiques à un seul protocole qui peuvent être utiles à la validation mais par définition ne sont pas communes à toutes les données ?

Les infos de la Synthèse me semblent suffisantes pour la validation, mais dans l'idéal, il serait bon de pouvoir accéder si besoin à l'ensemble des données de la source (protocole).

**Comment by TheoLechemia** [comment]
@sig-pnrnm Vous pouvez tester l'interface sur vos propres BDD, ou sur une BDD test. Il faut juste une table avec des relevés (qui, quoi, ou, quand, + un champs 'validation'), et une table taxref et ça fonctionne.
Je vais faire une petite doc et des captures d'écran dans les jours qui viennent.

**Comment by sig-pnrnm** [comment]
Je reviens sur ce sujet.

> Vous pouvez tester l'interface sur vos propres BDD [...] Je vais faire une petite doc et des captures d'écran dans les jours qui viennent.

N'étant pas familier des installations, je n'ose pas trop me lancer là dessus de peur de mettre la pagaille dans ma VM dédiée à GeoNature.
Si possible, ce serait très intéressant pour nous de pouvoir visualiser cette interface sur un serveur de demo.
Ca permettrait de faire vivre le [Github dédié](https://github.com/TheoLechemia/validationNaturaliste) de nos retours, suggestions, ... et ce en prévision d'un développement que ma structure pourrait financer si nécessaire.

Qu'en pensez-vous ?
(et dans tous les cas, la doc avec les captures d'écrans nous intéresse aussi !)

**Comment by TheoLechemia** [comment]
Désolé j'ai un peu oublié le sujet entre temps...
Voilà une capture d'écran.
![module_validation](https://user-images.githubusercontent.com/15265745/32328463-5a119ba2-bfda-11e7-9719-c7bdf31dc1b4.png)
J'essaye de l'installer sur un serveur de démo dans les prochains jours.
De toute façon il est prévu de faire un module de validation dans Géonature 2.
Ce module là n'est pas développé avec les technos qu'on utilise actuellement (JQuery côté front). Mais ça peut être intéressant d'avoir des retours pour le reprendre.

**Comment by sig-pnrnm** [comment]
Super : merci Théo ! (en plus, tu nous fais voyager dans les îles :-) )
Hâte de pouvoir tester sur ce serveur de demo

**Comment by camillemonchicourt** [comment]
Les points à discuter : 

- Un module de validation par protocole ou un module de validation dans chaque protocole ?
- Si un seul module global, comment on peut accéder aux infos spécifiques du protocole qui peuvent être utiles pour la validation ? Champs texte aggloméré dans la synthèse ?
- Validation automatique de certaines données (tout un protocole, tout un JDD, tout un groupe...) 
- La validation se fait dans la synthèse uniquement ou aussi au niveau des données sources ? 
- Quelles règles de mise en avant des observations extraordinaires (jamais vu à telle altitude, jamais vu à telle période, jamais vu dans tel zonage...)
- Quel MCD pour la validation des données ?
- Fonctionnalités de l'interface - Validation en masse (avec filtre par espèce, JDD, observateur, déterminateur....)

Voir « Extension validation v1.0 pour occurrences de taxons v1.2.1 » (http://standards-sinp.mnhn.fr/extension-validation-v1-0-pour-occurrences-de-taxons-v1-2-1)

**Comment by gildeluermoz** [comment]
> Si un seul module global, comment on peut accéder aux infos spécifiques du protocole qui peuvent être utiles pour la validation ? Champs texte aggloméré dans la synthèse ?

Si occurrence de taxon devient plus un outil qu'un protocole, il est possible que tous les modules l'utilisent. Du moins comporte les champs nécessaires à l'export au standard . Dans ce cas, tous les champs utiles à la validation, dont les champs minimaux obligatoires (à définir) devraient être présents dans tous les protocoles destinés à produire de l'occurence de taxon. Dans ce cas, il est possible qu'un module de validation unique agrège ces infos de pls protocoles. Il suffirait alors de déclarer en paramètre les modules à moissonner. La difficulté sera sans doute d'écrire dans le bon schéma et dans le bon champ de validation dont le nom devrait être standardisé (ou déclarer dans les paramètres du module de validation)
A creuser.

Si on pense que d'autres champs que ceux du standard d'occurrence seraient potentiellement nécessaires à la validation. On doit passer à une validation par module.
Dans ce cas, voir ce qui peut-être factorisé.

**Comment by camillemonchicourt** [comment]
Dans le cadre de l'audit et du workshop GeoNature de cette semaine, un travail est en cours pour faire de ce module un exemple de modularité en le développant comme un module externe, intégrable dans GeoNature : https://github.com/PnX-SI/gn_module_validation

**Comment by camillemonchicourt** [comment]
Ce qui est prévu pour le moment : 

- Une vue basée sur la Synthèse permet de renvoyer au module toutes les données
- Un formulaire liste l'ensemble de ces données
- Il est possible de filtrer ces données (taxon, date, observateur, source, commune...)
- On peut afficher le détail d'une donnée pour en afficher tous les champs de la synthèse
- Quand le module media aura été ajouté au module OccTax, il sera aussi possible d'afficher les médias associés à une occurrence de taxon
- Après filtre, il est possible de valider en masse toutes les données résultants du filtre
- Le V du CRUVED devrait être utilisé pour ne retourner à l'utilisateur que les données sur lesquelles il a des droits de validation (en fonction de la portée de son V mais aussi des modules où il dispose du V)
- Une donnée est validée au niveau de sa source. Les triggers allant de la donnée source vers la synthèse permettent de répercuter la validation d'une donnée dans la synthèse
- Pour les statuts de validation, on s'appuie sur la nomenclature 101 du SINP : https://github.com/PnX-SI/GeoNature/blob/develop/data/core/data_nomenclatures.sql#L436-L440
- En plus du statut de validation, il serait utile de stocker automatiquement une date de validation de la donnée. Ainsi que le validateur et un éventuel commentaire de validation
- Depuis le module de validation, il faudrait être en capacité d'aller modifier directement la donnée source si le validateur souhaite corriger une erreur sur une donnée
- La question de l'identification automatique de donnée exceptionnelles est mise de côté pour le moment
- Idem pour la notification à l'observateur de la validation de ses données

**Comment by pierrelapenu** [comment]
Point qui peut avoir son importance dans le processus de validation : lors de validations en masse, il serait important de pouvoir renseigner le champ "commentaire de validation" pour toutes les données validées. Pour le validateur, il faudrait, lors d'une validation en masse, qu'une fenêtre où il peut saisir le commentaire s'affiche et que le texte soit mis à jour sur toutes les observations concernées.

**Comment by camillemonchicourt** [comment]
OK donc en effet mettre un commentaire commun à toutes les validations faites en une fois.
OK c'est noté.

**Comment by sig-pnrnm** [comment]
_(désolé pour le silence prolongé sur ce développement dont nous avons lancé la prestation, mais en stand by pour l'instant : nous allons pouvoir relancer le travail prochainement)_
Ce champ `commentaire` de validation a en effet son importance pour les validation en masse, mais PAS UNIQUEMENT ! C'est effectivement une information importante (bien que non obligatoire) pour l'ensemble des validations.

**Comment by camillemonchicourt** [comment]
Oui bien sur

**Comment by camillemonchicourt** [comment]
Module développé dans un dépôt dédié (https://github.com/PnX-SI/gn_module_validation), puis intégré dans le cœur de GeoNature dans sa version 2.1.0.
