### ISSUE TITLE
Possibilité d'épingler une occurrence

### ISSUE THREAD

**Issue by Gaetanbrl** [PnX-SI/GeoNature#1819]
_Besoin formulé par [Picardie Nature](https://github.com/picardie-nature)._

Lorsqu'une observation est soumises à discussion, un validateur ou un observateur peut avoir besoin d'ajouter un tag pour retrouver rapidement cette observation. La possibilité d'épingler permet alors de "marquer" des occurrences pour répondre par exemple à ce type de cas d'usage.

Chaque marquage est donc strictement propre à un utilisateur (elle lui appartient). Un utilisateur ne peut donc voir que ses marquages et pas ceux des autres.

Une observation peut donc être marquée :
* Par plusieurs observateurs
* Une fois par observateur

Une épingle peut être manuellement enlevée par son propriétaire via un clic le même bouton qui a servi à l'ajout.

### Détails techniques

La table `t_reports` contiendra les épingles sur le même fonctionnement que les signalements #1750.
La date sera donc connue et permettra ultérieurement une purge sur les marquages qui serait trop anciens.
La table BibReportsTypes contient déjà le type `pin` qui sera utilisé spécifiquement pour cette fonctionnalité.

### Critères d'acceptation

1. Ouvrir la liste SYNTHESE ou VALIDATION
2. Cliquer sur une occurrence
3. Cliquer dans la toolbar des actions sur `Epingler`
4. Accéder au module VALIDATION ou SYNTHESE
5. Voir dans la liste une punaise sur les occurrence épinglées
6. Rechercher via un filtre avancé sur le champ spécifique `Est épinglée`
7. Ne voir que les occurrences marquées par l'utilisateurs
8. Supprimer le filtre avancé `Est épinglé`
9. Voir toutes les occurrences dans la liste
10. Cliquer sur une observation épinglées
11. Cliquer dans la toolbar sur le bouton `Ne plus épingler" (la couleur du bouton est différente car il y a déjà une épingle)
12. Retourner dans la liste et voir que l'observation n'est plus épinglées
13. Reproduire l'étape `6` et ne pas voir l'observation concernées par l'étape `11`

**Comment by Gaetanbrl** [comment]
@jbdesbas est-il possible de valider que ce fonctionnement est bien conforme et qu'on a pas oublié de cas d'usage ?

**Comment by jbdesbas** [comment]
@Gaetanbrl OK. La gestion des épinglages sur la synthèse n'était pas demandée (validation seulement), mais ca me parait tout de même pertinent.

**Comment by Gaetanbrl** [comment]
> La gestion des épinglages sur la synthèse n'était pas demandée

@camillemonchicourt un retour sur ce point ?

**Comment by camillemonchicourt** [comment]
Oui comme les signalements, c'est utile de l'avoir des 2 côtés.
Mais avec un paramètre pour activer ou non globalement la fonction d'epinglagle (masquant aussi le filtre "Est épinglé".

**Comment by Gaetanbrl** [comment]
> Mais avec un paramètre pour activer ou non 

Oui tout à fait

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.10.0.
