### ISSUE TITLE
Trigger occtax-> Synthese : Erreur sur l'update des dénombrements/occurrences 

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#1821]
**Version**
2.9.1

**Description du bug**
Lorsqu'on saisit un relevé avec une occurrence (espèce A) qui comporte 2 dénombrements (1 male 1 femelle pour faire simple), puis qu'on le valide, les données sont postées en synthèse. 

Si on retourne éditer le relevé en question sous occtax, puis qu'on corrige en remplacant Espèce A par espèce B : 
- En synthèse, le premier dénombrement est bien corrigé avec Espèce B
- Le 2eme dénombrement quant à lui n'est pas modifié, on a donc l'un des sexes qui reste associé à l'espèce A

**Comportement attendue**
L'édition d'une occurrence rafraichit en cascade tous les dénombrements associés dans la synthèse

**Comment by camillemonchicourt** [comment]
Le trigger est corrigé dans la PR https://github.com/PnX-SI/GeoNature/issues/1821, en intégrant aussi la reprise des données qui peuvent avoir un soucis lié dans la Synthèse, et en ajoutant des tests automatiques pour que le soucis ne puisse plus se reproduire.
