### ISSUE TITLE
Supprimer la table gn_sensitivity.cor_sensitivity_synthese

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#1837]
Le calcul automatique de la sensibilité a été mis en place dans GeoNature v2 étape par étape, en s'appuyant sur les standards et règles du SINP.

Ces règles de sensibilité permettent de calculer automatiquement la sensibilité ou non d'une observation.

Mais on avait prévu initialement de pouvoir aussi écrire et stocker une sensibilité manuelle dans une table dédiée ``gn_sensitivity.cor_sensitivity_synthese`` : https://github.com/PnX-SI/GeoNature/issues/871#issuecomment-735751525

Cela pour 2 raisons : 
- Nous avions en partie fait une confusion entre "Niveau de sensibilité" et "Niveau de diffusion" en considérant que le second dépendait du premier, alors que ce sont 2 champs indépendants
- Car certains règles de sensibilité sont spécifiques et gérées sous forme de commentaire et non automatisables

Donc on avait prévu de pouvoir stocker une "sensibilité manuelle" pour pouvoir surcoucher la sensibilité calculée automatiquement.

Le premier point a été clarifié et revu dans la version 2.9.2, en décorrélant "Niveau de sensibilité" et "Niveau de diffusion" : https://github.com/PnX-SI/GeoNature/issues/1711
Le premier étant calculé automatiquement à partir des règles, le second permettant de flouter des données non sensibles (privées ou que l'on ne souhaite pas diffuser pour diverses raisons, autres que celles des règles de sensibilité) même si cela n'est plus conforme au SINP.

Pour le second point, ces règles spécifiques sont censées être supprimées dans les évolutions en cours des règles de sensibilité. Et il reste possible de les répercuter manuellement dans le "Niveau de diffusion" qui n'est pas calculé automatiquement.

La sensibilité manuelle ne devrait pas exister et n'est pas ou peu utilisée dans la pratique.
Éventuellement on peut avoir un "Niveau de diffusion" manuel voire subjectif, même si ce n'est pas conforme au SINP.

Tout cela amène à supprimer la table ``gn_sensitivity.cor_sensitivity_synthese`` qui complexifie la BDD, sa lisibilité, sa compréhension et son utilisation, créé une redondance partielle des données et qui n'était pas utilisée jusqu'à présent.

La suppression de cette table et des triggers associés est en cours dans la PR https://github.com/PnX-SI/GeoNature/pull/1710

**Comment by bouttier** [comment]
La PR a été mergé dans GeoNature 2.10.0
