### ISSUE TITLE
POST requête avec Python

### ISSUE THREAD

**Issue by nleguillarme** [PnX-SI/GeoNature#1838]
Bonjour, j'essaie de poster une requête de création d'un relevé avec le code python suivant

```
import requests
url = "https://obica.osug.fr/geonature/api/occtax/only/releve"
headers = {'Content-type': 'application/json', 'Accept': 'text/plain'}
r = requests.post(url, data=data, headers=headers, auth=(user, mdp))
```

La requête me retourne un code HTTP 200, mais je suis redirigé vers la page de login
```
You should be redirected automatically to target URL: <a href="https://obica.osug.fr//#/login?next=%2Focctax%2Fonly%2Freleve%3F">https://obica.osug.fr//#/login?next=%2Focctax%2Fonly%2Freleve%3F</a>.  If not click the link.
```

Je suppose qu'il y a un problème d'authentification, mais je ne trouve pas d'info là dessus dans la doc.

**Comment by DonovanMaillard** [comment]
Bonjour, 

Le auth ne comporte pas uniquement un user (login) et un mot de pass (password), mais également un id_application (pour savoir si l'utilisateur à les droits ou non sur cette appli de mémoire). J'avais eu ce soucis quand j'avais voulu me connecter avec R. 

Voir la requête json postée par le navigateur quand tu te log sur GeoNature :) Après il y a des applications python comme gn2pg qui se loguent à geonature, si besoin de voir la manière dont la connexion est faite

**Comment by DonovanMaillard** [comment]
(du coup ce n'est pas un bug ;) )

**Comment by nleguillarme** [comment]
Merci @DonovanMaillard et @camillemonchicourt j'ai réussi à m'en sortir avec vos infos et les ressources supplémentaires sur l'import depuis Python.
