### ISSUE TITLE
Liens d'accès au module de saisie d'une observation depuis la VALIDATION

### ISSUE THREAD

**Issue by Gaetanbrl** [PnX-SI/GeoNature#1839]
_Expression de besoin formulée par [Picardie Nature](https://github.com/picardie-nature)._

L'issue #1455 a permis de démarrer des échanges et réflexions autour de la modification des observation à différentes étapes dans le cycle de vie d'une occurrence dans GeoNature, de l'import à la consultation d'une observation dans l'interface du module de SYNTHESE ou VALIDATION.

Cette issue ne concerne que la modification des occurrences pour un validateur et donc dans le module VALIDATION (et / ou SYNTHESE si nécessaire) selon le besoin initial :

> La validateur doit pouvoir, depuis l’interface de validation, modifier certains champs. La
liste des champs modifiables doit être paramétrable par fichier de configuration (comme
pour le module de saisie OccTax).

### Proposition fonctionnelle

Un échange avec la communauté (notamment @camillemonchicourt @TheoLechemia @bouttier ) et Picardie-Nature (@jbdesbas) a permis de valider la proposition suivante pour répondre à ce besoin :

> Depuis la fiche d’information Validation, et quand cette solution technique est possible, nous proposons d’ajouter des liens vers l’interface d’édition des modules concernés.
Ce fonctionnement existe déjà pour accéder au module OccTax depuis la fiche d’information d’une observation.
Ces liens pourront potentiellement être paramétrables dans un fichier de configuration (comme pour activer ou non un signalement).
Cette solution permet d’accéder rapidement aux interfaces de saisie sans devoir retrouver une occurrence dans un module spécifique.

> En cas de nouveau module, l’ajout d’un lien sera simple via un petit développement de complexité très limité. Un lien sera alors visible dans la fiche de Validation d’une observation sous forme de bouton.
Cette solution moins complexe est en accord avec le fonctionnement modulaire de GeoNature. Il correspond aux différents retours visibles dans l’issue GitHub #1455.

Cette proposition impactera moins fortement la structure / architecture de GeoNature sans remettre en question le fonctionnement relationnel et modulaire actuel.

### Proposition technique

* **Etat des lieux**

La source des occurrence est stockée dans la table `gn_synthese.t_source` et contient la PK id_source qui est une clé étrangère de la table gn_synthese.Synthese.
La table Synthese a donc un champ id_source permettant de lier une occurrence et la source.

* **Proposition**

Une relation (`source = relationship(TSources)`) sur le modèle `Synthese` pourra permettre pour chaque occurrence de récupérer le champ `url_source` (e.g `#/occtax/info/id_counting`) et donc d'obtenir une route de l'application vers le module de saisie dédié (e.g. `/#/occtax/info/id_counting/17`).

Lorsqu'un nouveau module permettant la saisie doit avoir une URL dans le module de validation, il sera alors nécessaire de déclarer les informations de la source dans la table `t_sources`.
Un paramètre / une config sera à prévoir pour que GeoNature rajoute les informations spécifiques dans la table `t_sources`.

Ce fonctionnement étant universel il permettra à tous les modules de prévoir ce fonctionnement comme le fait actuellement OCCTAX afin d'afficher une occurrence selon un id (UUID ou id_synthese, selon le fonctionnement propre du module).

**Toutes les remarques sont bien entendu les bienvenues, notamment sur la partie technique pour prendre la meilleure direction possible dès le début des développements.**

**Comment by TheoLechemia** [comment]
Oui c'est au module de prévoir son script Alembic écrivant dans t_sources

**Comment by Gaetanbrl** [comment]
> Pour moi, il suffit de bien déclarer le module dans la table t_sources et le lien est alors généré automatiquement.

Oui l'ajout représenté un développement à prévoir pour le gestionnaire du module :
* qui doit le prévoir dans le module à développer
* qui a un module déjà développé et doit prévoir une évolution pour rajouter la source dans la table

En l'état tout est fonctionnel donc pour qui a bien saisi les infos dans la table t_source.
