### ISSUE TITLE
1.8.4 - 2 problèmes d'installation - FATAL

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#184]
La version 1.8.4 contient 2 problèmes : 

- Une ligne d'`install_db.sh` (https://github.com/PnEcrins/GeoNature/blob/1.8.4/install_db.sh#L48) renomme le mauvais fichier et doit être remplacée par : 

`sudo sed -i "s/MYPGUSER/$user_pg/g" /tmp/grant.sql`

La correction est faite dans la branche `develop`.

- Il y a un problème dans l'intégration des données dans certaines tables du schéma `utilisateurs` où il semble y avoir des problèmes de clé. Le script s'appuie sur le fichier `https://github.com/PnEcrins/UsersHub/blob/master/data/usershub.sql`, en prenant le fichier dans la branche `master` https://github.com/PnEcrins/GeoNature/blob/1.8.4/install_db.sh#L51-L56

Voir les erreurs remontées dans `log/install_db.log` : 

```
psql:data/utilisateurs/usershub.sql:740: ERREUR:  la requête n'a pas de destination pour les données résultantes
ASTUCE : Si vous voulez annuler les résultats d'un SELECT, utilisez PERFORM à la place.
CONTEXTE : fonction PL/pgsql inline_code_block, ligne 6 à instruction SQL
DO
psql:data/utilisateurs/usershub.sql:780: ERREUR:  une instruction insert ou update sur la table « cor_role_droit_application » viole la contrainte de clé
étrangère « cor_role_droit_application_id_application_fkey »
DÉTAIL : La clé (id_application)=(1) n'est pas présente dans la table « t_applications ».
CONTEXTE : instruction SQL « INSERT INTO cor_role_droit_application (id_role, id_droit, id_application) VALUES (1, 6, 1) »
fonction PL/pgsql inline_code_block, ligne 3 à instruction SQL
psql:data/utilisateurs/usershub.sql:798: ERREUR:  une instruction insert ou update sur la table « t_menus » viole la contrainte de clé
étrangère « t_menus_id_application_fkey »
DÉTAIL : La clé (id_application)=(14) n'est pas présente dans la table « t_applications ».
CONTEXTE : instruction SQL « INSERT INTO t_menus (id_menu, nom_menu, desc_menu, id_application) VALUES (9, 'faune - Observateurs', 'listes des observateurs faune', 14) »
fonction PL/pgsql inline_code_block, ligne 3 à instruction SQL
psql:data/utilisateurs/usershub.sql:815: ERREUR:  une instruction insert ou update sur la table « cor_role_menu » viole la contrainte de clé
étrangère « cor_role_menu_application_id_menu_fkey »
DÉTAIL : La clé (id_menu)=(10) n'est pas présente dans la table « t_menus ».
CONTEXTE : instruction SQL « INSERT INTO cor_role_menu (id_role, id_menu) VALUES (1, 10) »
fonction PL/pgsql inline_code_block, ligne 3 à instruction SQL
```

**Comment by gildeluermoz** [comment]
La deuxième erreur est aussi corrigée dans la branche develop : https://github.com/PnEcrins/UsersHub/commit/272a3b379e0c1119e48e38a1c0c9f91a895d428a

Il faudrait soit récupérer le fichier sql dans la branche develop soit faire un merge des corrections dans le master.

**Comment by camillemonchicourt** [comment]
Oui si on ne sort pas rapidement la 1.9.0, ça serait bien de faire une 1.8.5 en attendant. 

A priori il peut prendre seulement certains commits d'une branche pour les intégrer dans une autre : http://stackoverflow.com/questions/881092/how-to-merge-a-specific-commit-in-git

**Comment by camillemonchicourt** [comment]
Réglé dans la 1.9
