### ISSUE TITLE
Proposition style circleMarker pour observations Synthese

### ISSUE THREAD

**Issue by ch-cbna** [PnX-SI/GeoNature#1847]
**Version**
develop

**Description**

Suite au [commit d'Antoine](https://github.com/PnX-SI/GeoNature/commit/e324c4c331ceaf97820b17d94e7230cd7ac31282) (sur la branche "feat/data-blurring-develop"), toutes les observations sont réunies par géométrie.
Dans la Synthèse, une géométrie est représentée par un circleMarker simple (petit cercle bleu). Le style actuel du circleMarker ne permet pas à l'utilisateur de se rendre compte du nombre d'observations sur une même géométrie. A mon avis, il serait plus pertinent (et visuel) de faire varier le rayon de ce circleMarker de manière proportionnelle au nombre d'observations et d'afficher en son centre le nombre d'observations (comme pour l'affichage en cluster).

Ce nouveau rendu est bien entendu ouvert à discussion. Qu'en pensez-vous ?

**Rendu**
![image](https://user-images.githubusercontent.com/102586824/162997267-73d39ee5-eb95-4b48-b16c-2c862c373196.png)

**Comment by DonovanMaillard** [comment]
Bonjour,

Je trouve ca tres sympa et lisible en effet, attention cependant à avoir une taille mini et maxi (on a vite fait d'avoir 150 observations sur un même point) pour que les valeurs extrêmes soient ni trop grosses ni trop petites si possible.

**Comment by camillemonchicourt** [comment]
Si je comprends bien, le cercle du marqueur serait proportionnel au nombre de points regroupés ?

J'ai souvent utilisé ou vu utiliser cette librairie Leaflet de cluster avec les cercles de même taille, en les gardant de même taille.

Je trouve ça bien et suffisant, surtout qu'un cluster peut regrouper des centaines d'objets donc ça ferait alors un cercle très très gros ?

**Comment by ch-cbna** [comment]
En effet, on peut rester sur le même principe que la librairie Leaflet de cluster, en conservant la taille des cercles et en rajoutant uniquement le nombre d'observations.

Cependant, d'un point de vue cartographique, il est plus juste de faire varier la taille d'un symbole lorsqu'il s'agit de représenter une variable quantitative de stock (ici, le nombre d'observations).

Concernant la taille de cercles, si le nombre maximum d'observations par point est 150, alors on peut modifier le calcul de la taille du radius. Sur l'image du commit, le **radius = 10 + nb d'observations**. Ainsi la taille minimum est fixée à 10 pixel. Afin que le radius n'augmente pas de manière démesurée, on peut modifier : radius = 10 + (nb d'observations / 2).

Un exemple ci-dessous pour 150 observations sur la même géométrie
![image](https://user-images.githubusercontent.com/102586824/163009970-1a0a4967-3563-422c-ac7b-cbe5f0b7c1f5.png)

Je suis d'accord également avec le fait de garder une cohérence avec l'affichage cluster.

**Comment by DonovanMaillard** [comment]
Ca reste une augmentation proportionnelle au nombre de donnees, sans limite max. En fonction des jeux de données (rattachement aux controides,  données biblio etc) ca risque de poser soucis avec un gros classer qui passe au dessus d'un petit voisin etc. 

Je trouve que l'affichage est intéressant mais avec ce risque sur de gros regroupements

**Comment by camillemonchicourt** [comment]
Je suis mitigé.
Il peut y avoir plusieurs centaines d'objets dans un cluster.
Ça fonctionne bien avec le fonctionnement par défaut du cluster où on fait juste varier le chiffre, et la couleur de mémoire.

Le cluster est utilisé comme ça partout où j'ai vu donc ça a du être éprouvé.

**Comment by ch-cbna** [comment]
Vous pouvez retrouver ces modifications sur ma branche : [https://github.com/ch-cbna/GeoNature/tree/feat/meshes](url)

Concernant le regroupement des observations sur une même géométrie, est-ce que vous trouvez pertinent d'afficher le nombre d'observations dans le circleMarker ?

**Comment by DonovanMaillard** [comment]
Oui, afficher le nombre d'observations regroupées (comme actuellement) est une info intéressante je trouve. 

Plutôt qu'un fonctionnement avec un rayon qui augmente proportionnellement, potentiellement jusqu'à l'infini, est ce qu'il ne faut pas prévoir simplement 3 tailles de points, petit jusqu'a 10 données, moyen jusqu'à 100 et grand au délà par exemple ?

**Comment by camillemonchicourt** [comment]
En fait le composant Leaflet.markercluster a déjà un comportement prévu avec 3 classes de taille et de couleur : 

![map](https://user-images.githubusercontent.com/4418840/163132577-01d633aa-50ad-4263-b31c-c17a70c7bef4.png)

Je resterai sur ce fonctionnement natif, pour éviter trop de variations et des tailles trop grandes.

**Comment by ch-cbna** [comment]
Je suis d'accord pour respecter le fonctionnement de markerCluster, la question se pose davantage pour le niveau inférieur au cluster, lorsque l'on affiche les circleMarker. Avec l'agrégation des observations par géométrie il devient intéressant d'imiter le comportement des cluster au niveau des circleMarker. Cette fois-ci, une proposition avec uniquement deux tailles de circleMarker : petite lorsque qu'1 géométrie = 1 observation / moyenne lorsque 1 géométrie = plusieurs observations. 

Qu'en pensez-vous ?
![image](https://user-images.githubusercontent.com/102586824/163153982-fdedcbd8-372e-4b19-ab16-6b647308d9eb.png)

**Comment by DonovanMaillard** [comment]
Pour le coup, avoir des clusters dans des clusters me semble assez peu lisible. Une fois qu'on est à ce niveau de détail, on a zommé sur un cluster donc on sait qu'on a plusieurs données. Je resterais sur un point bleu unique à ce niveau (au pire avec le chiffre dedans).

**Comment by ch-cbna** [comment]
D'accord, merci pour ton avis :)

Voilà le rendu avec uniquement l'ajout du nombre observations
![image](https://user-images.githubusercontent.com/102586824/163155412-14645e88-ea7a-4f94-a9be-2442e879f073.png)

Par contre, à partir de 100 observations par géométrie, le nombre dépassera du cercle...

**Comment by jpm-cbna** [comment]
> Par contre, à partir de 100 observations par géométrie, le nombre dépassera du cercle...

D'où l’intérêt du cercle avec une taille proportionnelle au nombre d'observation qui permettait de toujours afficher correctement le nombre d'observation...

Ceci dit, les clusters n'ont pas une taille fixe. Leur taille s'agrandit si le nombre à afficher ne rentre pas dans le cercle.
Je pense que l'on peut donc essayer d'avoir le même comportement. On agrandit le cercle de façon à ce qu'il contiennent toujours le nombre centré à l'intérieur.

**Comment by camillemonchicourt** [comment]
Style retenu : 

![image](https://user-images.githubusercontent.com/4418840/208126928-b87a0672-8186-4849-9017-849a91685da1.png)

**Comment by camillemonchicourt** [comment]
Ainsi désormais : 
- On ne renvoie qu'une seule fois la géométrie quand plusieurs observations ont la même géométrie, donc cela améliore les performances de chargement
- On sélectionne dans la liste l'ensemble des observations quand on clique sur une géométrie qui concerne plusieurs observations, donc on améliore la lisibilité

![image](https://user-images.githubusercontent.com/4418840/225137128-c392aaba-c84a-4bfa-92d2-c6520cc61c78.png)

Autre exemple avec un relevé linéaire avec une géométrie un peu complexe que l'on ne charge qu'une seule fois (au lieu de 3 dans ce cas), et pour laquelle on voit bien désormais qu'elle a 3 observations associées, quand on clique dessus : 

![image](https://user-images.githubusercontent.com/4418840/225138169-73b6bb20-8d8d-4ab1-9e86-58ce38f3b875.png)

**Comment by camillemonchicourt** [comment]
Le bug d'affichage des géométries multi-points a nécessité de revenir à un utilisation du classique circle-marker : https://github.com/PnX-SI/GeoNature/issues/2536#issuecomment-1690599807
