### ISSUE TITLE
Compilation en production sans AOT

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature#1855]
**Version**
develop

**Description du bug**
La compilation de GeoNature pour la production utilise les options suivantes: `ng build --aot=false --build-optimizer=false --configuration production`
La [compilation AOT](https://angular.io/guide/aot-compiler) n'est pas activée.

**Comportement attendue**
Avec le passage à Angular 12, il semble plus intéressant d'utiliser la compilation **AOT** et donc la commande de compilation suivante: `ng build --aot=true --build-optimizer=true --configuration production`

**Comment reproduire**
Compiler GeoNature avec la commande: `npm run build`

**Comment by camillemonchicourt** [comment]
Voir https://github.com/PnX-SI/GeoNature/commit/becf8bbb73c1aba1ca7ac1b379e3e1ab347955ae

**Comment by camillemonchicourt** [comment]
Fait dans la 2.11.0
