### ISSUE TITLE
[Synthese] Question sur les routes non protégées

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature#1863]
Bonjour,

Est-il volontaire qu'une partie des routes ne soient pas protégées (souvent pas de login requis ou pas de CRUVED). Cela concerne surtout le module `gn_synthese`.

Quelques exemples du module `gn_synthese`:
- https://demo.geonature.fr/geonature/api/synthese/sources (selon moi le plus sensible car selon l'usage, la source peut présenter un enjeu de confidentialité)
- https://demo.geonature.fr/geonature/api/synthese/color_taxon
- https://demo.geonature.fr/geonature/api/synthese/observation_count
- https://demo.geonature.fr/geonature/api/synthese/taxa_count
- https://demo.geonature.fr/geonature/api/synthese/observations_bbox
- https://demo.geonature.fr/geonature/api/synthese/taxa_distribution

D'autres du module `gn_monitoring`:

- https://demo.geonature.fr/geonature/api/gn_monitoring/siteslist
- https://demo.geonature.fr/geonature/api/gn_monitoring/siteareas/35

**Comment by DonovanMaillard** [comment]
Par cohérence, il faudrait à minima avoir un cruved R=1 sur le module synthèse pour accéder à ces routes,puisque c'est ce niveau de droit qui donne accès au module et une partie de ses données.

**Comment by camillemonchicourt** [comment]
Correction et protection de ces routes, ainsi que de nombreuses autres à l'occasion de la version 2.13.0 et de sa refonte complète des permissions.

**Comment by amandine-sahl** [comment]
Les routes 
* https://demo.geonature.fr/geonature/api/gn_monitoring/siteslist
* https://demo.geonature.fr/geonature/api/gn_monitoring/siteareas/35

Sont des routes de GeoNature, qui ne sont utilisées ni par GeoNature, ni par Monitoring. 
Elles sont peut être à supprimer vu qu'elles n'ont actuellement pas d'usage.
