### ISSUE TITLE
Espèce présente non dénombrée et/ou classes d'abondance

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/GeoNature#187]
Ayant fait de la saisie ce week-end de données de papillons de nuit, je me rends compte qu'il manque dans les protocoles "`Contact Faune`" et "`Contact Invertébrés`" la possilité de saisir des données sans information de dénombrement (juste "espèce présente").
Il manque également la possibilité de saisir des "classes d'abondance".

Dans les deux cas (espèce présente ou classe d'abondance), il serait pertinent de pouvoir le préciser que ce soit au niveau du taxon (dans sa globalité) OU pour chaque stade / sexe : 
![geonature_denombrements](https://cloud.githubusercontent.com/assets/26482054/26061252/a55225ac-3987-11e7-89c5-2e554d0fc60f.png)
(simulation dégoutante, à "cosmétiser" : d'ailleurs, pour ne pas alourdir l'écran de saisie, le mode dénombrement précis / classe d'abondance pourrait se "switcher" par un bouton type [Bootstrap Toggle](http://www.bootstraptoggle.com/)) 

Je ne sais pas si c'est à l'ordre du jour de la V2, alors je lance la suggestion !

**Comment by camillemonchicourt** [comment]
Concernant ce qui est prévu dans le CONTACT, tous les champs etc... c'est détaillé dans le document de définition : http://geonature.fr/documents/2017-04-GN2-Fonctionnalites-0.1.pdf

Voir https://github.com/PnEcrins/GeoNature/issues/168

**Comment by camillemonchicourt** [comment]
Cela ne veut pas dire que c'est arrêté et définitif, au contraire. 

Mais que je veux bien que les propositions/commentaires/remarques/propositions soient faites sur la base de ce qui a été proposé dans ce doc, aussi listé dans le WIKI - https://github.com/PnEcrins/GeoNature/wiki/V2-:-Contact-(R%C3%A9flexion)

Merci !

**Comment by gildeluermoz** [comment]
Le dénombrement est typiquement un sujet à débat. Chacun a sa façon de faire. Être générique demande la mise en place de mécanisme complexe pour permettre la prise en compte de tous les cas de figure. Mais au final, ce soucis légitime du naturaliste de rendre compte au mieux ce qui a été vu n'a que peu d'application sur le plan de l'usage des données. 

Combien de traitements ayant une vraie valeur scientifique ont eu besoin de faire parler les valeurs de dénombrement (je parle bien de contact occasionnel) ?
Quelle est la valeur scientifique d'un dénombrement lors d'une observation occasionnelle, en dehors de tout protocole ?
Et pour les rares cas où ça pourrait l'être, comment traiter l'hétérogénïté entre des données de simple présence non dénombrée (=0 par ex), de dénombrement précis (=12), de classe (=entre 10 et 50) et toutes les valeurs =1 car l'observateur n'a pas dénombré mais à noté 1 plutôt que 0 car il en a au moins vu 1 et qu'il ne veut pas noter 0 parce que ce n'est pas réalité ?

Chacun peut en avoir un usage qui lui est propre. Il ne faut donc pas cherche à faire qq chose de complexe sinon ou va encore passer un temps interminable de palabres sur le sujet. De mon point de vu, le dénombrement est une information non traitable dans le cadre d'un contact occasionnel, du fait de l'absence de protocole et de cadre. C'est une simple information du même niveau que la remarque.
Sans valeur pour la machine (traitement) mais utilisable uniquement lors de la relecture des données par un humain (une par une). Une simple information.

Un champ integer me semble suffisant au vu de la validité de cette valeur. Quelle différence en "75" ou même "65" et "entre 50 et 100". Et surtout, si on a une fois "65" et une fois "entre 50 et 100", quel traitement peut-on faire sur cette information ?
Par contre si on a toujours un nombre, on peut au moins le rattacher automatiquement à des classes lors du traitement ou même de la restitution (export).

**Comment by YannBaillet-FlaviaAPE** [comment]
Je suis d’accord avec toi Gil

je pense qu'il faut avoir toujours un chiffre entier, car les champs "50 à 100" pour exemple, lors des analyses sont toujours ramenés au chiffre inférieur c'est-à-dire 50. De plus, ces ordres de grandeur sont perçus différemment d'une personne à une autre et ne sont donc souvent pas très fiables.

Je pense, pour être confronté régulièrement à ce problème de dénombrements avec les papillons, qu'il faut noter le nombre qui se réfère au nombre minimum d'individus déterminé avec certitude, c'est-à-dire 1, après, à voir l’intérêt réelle de dénombrer ou non. Si c'est le cas, il faut alors soit conserver les individus ou les compter simultanément afin d'éviter les doubles comptages.

Le 0 me semble plus pertinent pour identifier l’absence d'une espèce rechercher. Pour les analyses statistiques, c'est souvent des données qui nous manquent et qui ne ressortent pas à cause de la mauvaise utilisation du 0.

Enfin, tout ça pour vous dire que je prône souvent la liberté de choix, mais que sur certains champs cela génère des problèmes de traitement analytique du fait d'une trop grande hétérogénéité, d'autant plus quand on traitre plusieurs centaines de milliers de données.

**Comment by sig-pnrnm** [comment]
Bonjour à vous, et désolé pour le délai de réponse !
> De mon point de vu, le dénombrement est une information non traitable [...] C'est une simple information du même niveau que la remarque.

Alors, je suis 100% d'accord sur le fait que l'on ne peut faire aucune analyse mathématique sur ce genre d'information. De manière plus générale même, hors de protocoles particuliers, même l'effectif numérique est pour moi inutilisable.

Il s'agit bien d'une information à valeur de **commentaire**.

Par contre, ce genre de commentaire est très utile pour, par exemple, des responsables d'Atlas taxonomiques, qui réalisent des bilans de connaissance et répartition d'espèces.

Pour avoir fait cet exercice sur différents groupes taxonomiques (libellules, papillons), pour chaque espèce, on fait le point sur l'ensemble des données. Et pour certaines espèces, il est utile de rentrer dans les commentaires, avant de rédiger la fiche espèce (ce n'est pas l'ordinateur qui travaille, mais le cerveau humain).

Du coup, les informations d'abondance sont des commentaires utiles. Le fait de les normaliser (listes déroulantes) n'a pas pour objectif de tenter d'en faire des analyses scientifiques (mathématiques), mais bien de permettre à l'observateur de saisir plus rapidement ses **commentaires**.

Un cas qui me semble important à prendre en considération, c'est la notion de "**espèce présente**".
Pour les chasses aux papillons de nuit par exemple, on ne note que très rarement l'effectif, qui n'a pas vraiment d'intérêt (trop de paramètres externes qui vont influencer).
Dans ce cas, avec un champ numérique uniquement, on mettrait "1" en effectif (au moins 1 individu).

Mais alors, comment distinguer ces données de véritables données avec 1 individu dénombré ? (exemple d'une espèce jamais observée, pour laquelle l'observateur souhaite préciser qu'il n'y avait qu'un individu présent).
Un simple "commentaire normalisé" (case à cocher par exemple) permet de ne pas saisir de "fausses informations" (1 n'est souvent pas égal à "1 individu", mais à "espèce présente non dénombrée").

Voila comment procède une certaine base "concurrente" ;-) 
![denombrement](https://cloud.githubusercontent.com/assets/26482054/26542466/40804af4-445a-11e7-8af1-472da30e24da.png)
Personnellement, pour le pratiquer dans pas mal de groupes taxonomiques, ça permet d'aller vite dans la saisie de ses commentaires d'effectifs.
**Qui ne restent que des commentaires !** :-)

**Comment by camillemonchicourt** [comment]
Pour le Contact, on se base dans la V2 sur le standard OCCURRENCES DE TAXONS : 
https://github.com/PnX-SI/GeoNature/blob/docker/data/modules/contact/contact.sql#L101-L108

Avec un denombrement MIN et un MAX. 

Et pour chaque dénombrement on stocke aussi : 
- Type de dénombrement, Nomenclature des types de dénombrement possibles (comptage, estimation...)
- Objet du dénombrement, Nomenclature des objets qui peuvent être dénombrés

Pour les types de dénombrements, des valeurs sont proposés par défaut selon la nomenclature INPN (http://standards-sinp.mnhn.fr/nomenclature/21-type-de-denombrement-16-08-2016/) : https://github.com/PnX-SI/GeoNature/blob/docker/data/core/data_nomenclatures.sql#L192-L195

Idem pour les objets du dénombrement : https://github.com/PnX-SI/GeoNature/blob/docker/data/core/data_nomenclatures.sql#L244-L253

Libre à vous de désactiver/rajouter des valeurs aux différentes nomenclatures.
