### ISSUE TITLE
[UH 2.2.2] Erreur lors de la création automatique de compte depuis Geonature

### ISSUE THREAD

**Issue by JeromeMaruejouls** [PnX-SI/GeoNature#1874]
Bonjour à tous,

Je rencontre une erreur sur Userhub lors de la création de compte depuis géonature. Normalement, l'inscription est automatique. Tout fonctionnait bien après les dernières mises à jour. Mais depuis peu, les inscriptions se retrouvent en attente dans UH (onglet Demandes de compte) et lors de la validation manuelle, j'obtiens une erreur 500 sur la route xxx/api/users/after_confirmation

Après cela, l'utilisateur est bien créé mais sans jeu de donnée personnel (donc impossible de saisir).

Une idée ?

**Comment by JeromeMaruejouls** [comment]
> Effectivement la variable `function_dict` n'est pas définit. C'est lié à ce commit. [PnX-SI/GeoNature@788cee2](https://github.com/PnX-SI/GeoNature/commit/788cee23695dd6f2f370019d8905f41dde1d1b36) Tu peux remplacer `function_dict` par `REGISTER_POST_ACTION_FCT` à la ligne 290.

Merci @TheoLechemia
Si je comprends bien, je remplace : 
`after_confirmation_fn = function_dict.get(type_action, None)`
Par : 
`after_confirmation_fn = REGISTER_POST_ACTION_FCT.get(type_action, None)`

La définition de 'function_dict' à la fin du fichier register_post_actions.py n'est donc plus utilisé ?
Ce qui m'intrigue le plus, c'est que j'ai l'impression que cela n'a plus marché du jour au lendemain sans mise à jour ou autre (mais je me trompe peut etre)
Merci en tout cas !

**Comment by TheoLechemia** [comment]
c'est ça

**Comment by JeromeMaruejouls** [comment]
C'est bon, tout refonctionne normalement. Merci pour la réactivité. Je te laisse fermer le ticket ou l'associer à une prochaine release.
Bonne journée

**Comment by camillemonchicourt** [comment]
Correction intégrée dans la 2.10.3
