### ISSUE TITLE
flux WFS sur un geoserver connecté à geonature

### ISSUE THREAD

**Issue by AmelieTagliaferro** [PnX-SI/GeoNature#1877]
Bonjour, 
je ne sais pas si mon message a sa place ici, mais je m'interroge si quelqu'un a déjà réalisé un accès en flux WFS aux données multi géométries de geonature ?

Pour expliquer : notre base geonature est accessible via un geoserver d'où notre "atlas" interne se connecte (au schéma gn_experts, v_sinp_synthese) pour afficher ensuite toutes les données geonature. 
Cet atlas propose des accès en flux à la couche WMS (raster) et WFS. Le WMS affiche bien les multigéométries mais le WFS ne montre que les points. 
![image](https://user-images.githubusercontent.com/93383491/166458589-4f4fff5a-d2e6-4fce-b04c-38b62539471f.png)
Avez vous déjà pu afficher les données multi géométrie de geonature en flux WFS ? 

Merci d'avance pour votre retour, 
Bonne journée,

**Comment by jbdesbas** [comment]
Bonjour,

Le problème ne vient probablement pas du flux, mais de QGIS qui ne gère pas les couches WFS avec différents type de géométries (_mixed geometry_). 
La piste serait d'ajouter 3 flux WFS en ajoutant un filtre CQL sur le type de géométrie : https://gis.stackexchange.com/questions/103789/force-geometry-type-in-mixed-geometry-wfs-layer-in-qgis

ou alors, plus simple pour les utilisateurs, créer 3 flux _point_, _ligne_, _polygone_ sur le geoserver en filtrant le type de géométrie.

**Comment by AmelieTagliaferro** [comment]
Bonjour, 

Merci pour ton retour, c'est en effet la solution que nous avions imaginé (la seconde) si on ne trouvait ^^

**Comment by camillemonchicourt** [comment]
OK, intéressant.
La solution concerne donc QGIS, et pas GeoNature.
