### ISSUE TITLE
Migration entre deux serveurs

### ISSUE THREAD

**Issue by geobrun** [PnX-SI/GeoNature#1879]
Bonjour tout le monde,

Notre structure possède un environnement GeoNature (UH, TH, atlas) installé sur un Ubuntu 18.04. Cet OS m'a déjà donné du fil à retordre par le passé lors de précédentes mises à jour de GeoNature, et à mon avis, cela va devenir encore plus compliqué par la suite ! Ce choix d'OS avait malheureusement déjà été effectué avant mon arrivée dans la structure.

Du coup, je souhaite migrer notre environnement sur un serveur Debian 11. Voici la procédure que j'envisage de suivre :
- Installation d'un environnement GeoNature tout neuf sur Debian (je pense que lors des mises à jour réalisées sur le serveur Ubuntu, je n'ai pas réussi à garder la base de données complètement intacte)
- Réimport des JDD/données présents dans notre GeoNature actuel (via une sauvegarde/restauration des tables en question par exemple)

Pensez-vous qu'il s'agit de la meilleure méthode ? Vais-je rencontrer des problèmes auxquels je n'ai pas songé (notamment lors du réimport des données je suppose) ?

**Comment by jpm-cbna** [comment]
Si les 2 versions de GeoNature sont identique, c'est peut être envisageable. Sinon, il peut y avoir des différences de structure entre les tables de l'ancienne base et celles de la nouvelle.

**Comment by DonovanMaillard** [comment]
Bonjour, je l'ai fait de mon coté sans trop de soucis, en faisant un peu différemment : 

- Mise à jour de la BDD dans la dernière version
- dump global de la BDD avec pg_dump
- Installation neuve sur le nouveau serveur, avec le même nom de base, meme utilisateur postgresql etc pour éviter les soucis
- suppression de la BDD geonature neuve
- restauration de la sauvegarde globale avec pg_restaure (ou psql \i monfichier.sql de mémoire)

Ca évite d'aller voir le détail table par table, avec les vues à remettre, avec les correspondances et les dépendances à aller faire dans l'ordre (les roles et les jdd avant les tables de correspondances  ,puis ensuite la synthèse avec sa clé étrangère vers les id_dataset, idem pour les nomenclatures etc etc). 

Ca prend assez peu de temps en faisant comme ca.

**Comment by geobrun** [comment]
Merci pour ton retour @DonovanMaillard !

Effectivement, c'est la solution la plus simple, mais par contre, si j'ai des problèmes dans ma base de données actuelle, je vais les récupérer... Pour l'instant, ce n'est pas bloquant, tous les éléments que j'utilise fonctionnent, mais je ne serai pas étonné de rencontrer de nouveau des problèmes dans le futur ! J'ai déjà "réparé" ma base de données actuelle plusieurs fois lors de précédentes migrations... :(

**Comment by DonovanMaillard** [comment]
oui, c'est bien un risque d'avoir des fonctions en double, des trucs pas supprimées dans une précédente note de version (ou une note de version non jouée ... on l'a tous fait, avouons!), etc. 

Mais repousser les données de toutes les tables avec leurs ID etc et garder les intégrités.... c'est pas forcément un truc bien joyeux non plus. Faut voir si l'option --data de pg_dump permet de récupérer les données avec leurs ID sans les structures de tables ni fonctions. Bon si vous avez assez peu de modules, il n'y a pas 500 tables à re peupler non plus. mais pas certain que ca soit plus fiable comme méthode que de faire un dump si vous voulez etre sur que vos id_nomenclatures, id_role, id_area etc ne changent pas en cours de route.

**Comment by geobrun** [comment]
Oui, je pense que je risque de m'amuser à repeupler tout ça... C'est peut-être effectivement plus simple de "réparer" la base quand ce sera nécessaire plutôt que de passer du temps maintenant à réimporter table par table avec toutes les erreurs que cela pourrait également générer en plus. J'ai encore quelques jours devant moi pour y réfléchir !

**Comment by DonovanMaillard** [comment]
Oui, après en soit la logique n'est pas si hardue non plus (c'est ce que je fais pour mes sauvegardes en cas de crash). L'ordre de restauration doit etre : 

1. Les tables de référentiel (d'abord les bib_, puis tables comme l_areas, t_roles, t_nomenclatures etc)
2. Les tables de données (t_acquisition_frameworks, t_datasets, t_releves_occtax, t_occurences etc)
3. Les tables de correspondances (cor_count_occtax, cor_area_synthese, cor_dataset_actor etc

En théorie, la synthèse devrait meme se recalculer seule à l'intégration des données dans occtax. Mais il vaut mieux désactiver les triggers et repousser à la main (comme pour cor_area_synthese) ca épargne quelques heures de calculs et d'intersections... 

En tous cas bon courage ! c'est toujours un bon ménage sur les serveurs, mais jamais un joyeux moment....

**Comment by lpofredc** [comment]
Il doit y avoir autant de méthodes que de personnes à le faire ;). J'ai justement une migration couplée d'une montée en version en cours:
- GeoNature 2.7.5 > 2.9.2 (je n'ai pas de médias ni de personnalisation compliquées à reprendre)
- Debian 10 > 11
- PostgreSQL 11 > 14 (externalisée)

Les étapes:

1. Installation d'une suite GeoNature vierge (via les scripts d'install complets) sur la nouvelle infrastructure.

2. Dump de la base de donnée (en direct sans passer par l'intermédiare d'un fichier...) avec les commandes suivantes :

```bash
## Récupération des utilisateurs PostgreSQL
pg_dumpall <parametres de connection à la bdd source>  -r | psql <paramatres de connection de la nouvelle bdd>
# Dump et restauration de la bdd sur le nouveau serveur PostgreSQL
## On récupère le script pour créer la seule fonction située dans public
wget https://raw.githubusercontent.com/PnX-SI/GeoNature/master/data/core/public.sql
## On dump et restaure tout sauf le schéma public
psql <paramatres de connection de la nouvelle bdd> -f public.sql
pg_dump <parametres de connection à la bdd source> -N public | psql <paramatres de connection de la nouvelle bdd>
```

3. Lancer les MaJ GeoNature de la bdd

**Comment by geobrun** [comment]
Ca y est, j'ai terminé la migration entre notre deux serveurs ! Ca n'a pas été une mince affaire, surtout du fait de mes connaissances limitées sur certaines subtilités du SQL...

Finalement, j'ai opté pour la solution réinstallation complète et réimport "table par table" (plutôt que le réimport total de la BDD). C'est pour cela que la migration m'a pris pas mal de temps...

Voilà un petit retour à propos des choses sur lesquelles j'ai buté : 

- J'ai rencontré un problème à l'installation de GeoNature en définissant un mot de passe utilisateur contenant des caractères spéciaux (testé avec les caractères # et ?). De mémoire, le processus se bloquait au niveau de l'installation de la BDD avec un mot de passe du type "abcde#123". Je n'ai malheureusement pas noté le message d'erreur, mais je me souviens que la console affichait un truc du genre "mot de passe erroné" en indiquant le mot de passe "abcde" (donc tronqué à partir du caractère spécial). Je n'ai pas ouvert de ticket à ce propos car si je suis le seul à avoir rencontré ce problème, c'est que le souci venait sûrement d'une configuration spécifique sur ma machine Debian ?
- J'ai rencontré également un problème sur la prise en compte du port de BDD que j'avais spécifié dans le fichier "install_all.ini". Après installation, seul TaxHub avait pris en compte le port que j'avais spécifié. J'ai du le remodifier dans les fichiers de configuration de GeoNature et UserHub pour que tout fonctionne. Du coup, je suppose que l'installation a bien été réalisée sur le bon port, et que c'est seulement dans la configuration des applis que le port n'a pas été repris ?
- Le plus gros souci que j'ai rencontré est que les ID de nomenclature dans la BDD fraîchement installée différaient de ceux de ma base de données d'origine. Du coup, pour chaque table réimportée contenant des identifiants de nomenclature, j'ai du remplacé les anciens identifiants par les nouveaux. Je suppose que ces changements de nomenclature ont du être réalisés à cause de l'ajout de nouvelles nomenclatures qui n'existaient pas encore lors de ma première installation de GeoNature ?
- Globalement, il faut faire attention aux numéros de module/application dans les tables réimportées qui peuvent différer avec celles de la BDD d'origine.
- Concernant la réinstallation de l'atlas, les fonctions de rafraîchissement des VM n'ont pas été créées lors de l'installation de la BDD de l'atlas. Effectivement, en regardant le script d'installation, je n'ai pas trouvé de lignes lançant ces scripts ("atlas.vm_refresh.sql" par exemple).
- Toujours concernant l'atlas, il y a quelques lignes où le port n'est pas indiqué pour le lancement des fichiers ".sql". Du coup, la restauration échouait car les connexions en question utilisaient le port 5432 par défaut. J'ai préparé une petite correction que je vais transmettre en PR.
- J'ai eu des soucis pour passer mon nouveau GeoNature en HTTPS. La commande indiquée dans la documentation de GeoNature `sudo certbot certonly --webroot --webroot-path /var/www/html --domain mondomaine.fr --email monemail@mondomaine.fr` ne fonctionnait pas. Parfois, la commande échouait, parfois elle fonctionnait mais aucun fichier de configuration "sécurisé" dans "/etc/apache2/sites-avaiblables" n'avait été créé. Au final, c'est la commande suivante qui a fonctionné de mon côté : `sudo certbot --apache`
- J'ai aussi un peu pataugé sur la reconfiguration de GeoNature/TaxHub/UsersHub sur un sous-domaine car la documentation qui existait avant sur ce sujet à disparu. Ou alors je n'ai pas réussi à la retrouver ?
- Après la migration, un utilisateur de notre structure a rencontré un problème de saisie dans Occtax : ses nouveaux relevés/occurrences généraient une erreur car leurs identifiants étaient réattribués à partir de 1. J'ai résolu le souci en réglant les séquences (par exemple "t_releves_occtax_id_releve_occtax_seq") pour qu'elles redémarrent à partir du dernier identifiant rentré dans mon ancienne BDD.

Si quelqu'un le souhaite, je peux faire un retour plus détaillé sur l'ordre de restauration des tables/schémas que j'ai suivi.

**Comment by DonovanMaillard** [comment]
Bonjour, 

Pas la manière de faire la plus rapide en effet, mais moins radical :) j'ai fait un changement de serveur aussi ce weekend, en faisant une install neuve + remontage complet de la BDD. 

Pour le mot de passe, le # dans les fichiers de conf .ini indiquent les commentaires. Le "#123" a donc été traité comme un commentaire

Pour les id_nomenclatures, le plus simple aurait été de tronquer la nouvelle table, et de la re-peupler avec votre ancienne t_nomenclatures ? 

Les id_applications m'ont vallu un peu de recherche aussi en effet, c'est vite piégeux :) 

Pour HTTPS, il faut qu'on supprime cette (vieille) doc ... elle n'est plus à jour, et en effet il y a des méthodes bien plus simples et automatisées en installant des paquets python-certbot 

La configuration apache sur les sous-domaines ne tient pas que de GeoNature mais de Apache d'une manière générale. Avec les fichiers .conf de geonature, usershub et taxhub qui ont été mis en places (à la 2.8 je crois), ça changeait un peu la donne sur ce point. Si ca peut vous rassurer, cette doc date de celle de HTTPS qui a été faite en même temps, donc elle était également obsolète;.. Elle ne vous aurait pas bcp servi. 

Le fait de supprimer puis réimporter la base dans son ensemble a le défaut de ne pas "nettoyer" la base dans le même temps, en laissant des relevés vides, des nomenclatures obsolètes, des éventuels soucis de contraintes absentes ou autrees choses oubliées au fil des migrations. Mais ca limite quand même grandement les soucis sur les séquences, les id qui viennent des référentiels etc, et accélère grandement la chose quand meme (j'ai changé de serveur en 5-7h je dirais)

**Comment by DonovanMaillard** [comment]
On a surtout pas les mêmes bases de données; j'étais sur une instance très simple avec peu de données et de modules :) ca change tout !

pour le ? je ne pense pas en effet, l'explication est moins évidente ... 

Apache reste obscur pour beaucoup d'entre nous, en théorie les fichiers de votre ancien serveur auraient du continuer à fonctionner sur le nouveau. Dans tous les cas, ces changements de serveur sont intéressants à documenter/paertager, ça reste un gros morceau qui reste utile occasionnellement :)

**Comment by geobrun** [comment]
C'est vrai que j'avais pas mal de JDD, le module monitoring à réinstaller et un atlas à restaurer également !

Pour le ?, peut-être que c'est moi qui me suis emmêlé les pinceaux quelque part !

Pour Apache, j'aurais pu effectivement récupéré les anciens fichiers de configuration. Mais comme pour la BDD, je n'avais pas fait les choses très propres la première fois, donc je préférais repartir de zéro et n'insérer que les lignes nécessaires dans les fichiers !
