### ISSUE TITLE
GeoNature 2 - étudier l'opportunité d'un module dédié aux relevés d’absence

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#188]
Plutôt que de gérer ou de perdre des informations d'observation via les contacts et /ou un usage hétérogène du dénombrement, créer un module permettant de décrire la prospection, le ou les taxons cibles. Analyser la représentation et l'usage de ce type de données très particulier en synthèse, export, etc...

**Comment by camillemonchicourt** [comment]
Sur le principe de ne pas tordre le Contact en voulant y faire rentrer l'absence je suis tout a fait pour.

Le contact est le contact d'une espèce comme son nom l'indique. 
Et il ne faut pas faire croire aux utilisateurs qu'il permet de faire du suivi.

Donc je vais dans le sens de ta solution. 

Mais je pense qu'il ne faut pas le faire du tout.
Ça n'a pas de sens de faire du "Contact absence".
Soit on fait du contact, soit du suivi mais pas un mix des 2 dont les données ne sont ni mobilisables ni traitables.

**Comment by camillemonchicourt** [comment]
On valide l'impossibilité de saisir de l'absence dans le CONTACT.

**Comment by camillemonchicourt** [comment]
Par défaut dans Occtax, le champs est présent mais masqué et c'est donc la valeur définie dans la BDD qui est poussée (``présent`` par défaut mais modifiable). 

Même si ça semble tordu, libre à chacun d'afficher ce champs pour permettre aux utilisateurs de modifier la valeur à chaque saisie d'occurrence de taxon.

Pour le reste, l'identification de l'absence est privilégié dans des protocoles de suivi car c'est déjà le cas avec le module SUIVI FLORE TERRITOIRE.

La question principale qu'il reste est de voir comment on gère les données d'absence dans la Synthèse et les exports.

Pour le moment, elles seront présentes comme les occurrences de présence. 
La nomenclature "Statut de l'observation" est affichée dans le détail d'une occurrence : ``Statut de l'observation | Présent``

Un module Contact Absence n'est pas prévu donc je clos l'issue. Ceux qui veulent noter de l'absence dans Occtax peuvent le faire en affichant le champs. 
Pour l'absence ce sont donc plutôt des protocoles de suivi qui sont privilégiés.

**Comment by gildeluermoz** [comment]
Ce n'est un occtax absence qu'il faut, c'est un module suivi très très générique, peut-être basé uniquement sur gn_monitoring. Mais effectivement ce n'est pas d'actualité.

**Comment by pierrelapenu** [comment]
"Même si ça semble tordu", la possibilité existe et le champ est effectivement présent dans occurrence de taxon.  Je pense que c'est bien de donner cette possibilité de signaler une absence lors d'une visite sur un lieu donné où on recherche une espèce particulière (ce n'est pas un suivi de site mais on fait un effort de prospection particulier qui ne donne rien sur une zone qui peut être définie plus ou moins précisément).
En revanche, si le champ existe et qu'on donne la possibilité de l'activer, il me semble qu'il faut garantir que les données d'absence ne puissent pas être interprétées comme des données de présence.
Afin d'éviter cela, n'est-il pas possible de filtrer les données d'absence pour la synthèse et l'atlas ?
Elles peuvent en revanche être conservées effectivement pour les export puisqu'elles sont bien identifiées.

**Comment by camillemonchicourt** [comment]
Oui la Synthèse est basée aussi sur le standard Occurrence de taxons donc on y retrouve aussi cette info qu'il s'agit d'une occurrence d'absence avec une nomenclature bien identifiée.
Et donc on peut décider ou non d'intégrer ces occurrences dans la Synthèse ou pas.

**Comment by samuelpriou** [comment]
Je partage le point de vue de Pierre. il serait donc intéressant de pouvoir saisir une absence lors d'un effort de prospection particulier qui ne donne rien.

**Comment by camillemonchicourt** [comment]
Oui c'est bien le cas pour ceux qui le souhaitent comme indiqué plus haut.

**Comment by samuelpriou** [comment]
Merci !

**Comment by pierrelapenu** [comment]
J'avais réagi à la citation de Camille : "La question principale qu'il reste est de voir comment on gère les données d'absence dans la Synthèse et les exports. Pour le moment, elles seront présentes comme les occurrences de présence."
Si on peut exclure les données d'absence de la synthèse et de l'atlas et qu'elles sont identifiées dans les exports, pas de problème.

**Comment by camillemonchicourt** [comment]
Cette nomenclature est présente dans la BDD de Occtax et de la Synthèse mais pas traitée différemment des autres. 
J'ouvre un ticket sur le sujet - https://github.com/PnX-SI/GeoNature/issues/521
