### ISSUE TITLE
Champs additionnels bool

### ISSUE THREAD

**Issue by ca-rock** [PnX-SI/GeoNature#1885]
Bonjour,
Je voudrais configurer un champ additionnel type checkbox, de sorte que le résultat dans le json soit {"monchamp":true} si la case est cochée, sinon {"monchamp":false}.
Je n'ai pas trouvé la bonne façon de remplir le champs "valeurs" et "valeur par défaut", quelqu'un peut m'éclairer ?
Merci

**Comment by DonovanMaillard** [comment]
Bonjour, 

Vous trouverez la réponse ici #1464 :)

**Comment by ca-rock** [comment]
Bonjour,
j'ai trouvé deux compromis grâce au post #1464 

1/ Avec les configurations suivantes : 

Nom du champ = utilisation_jumelles
Label du champ = Utilisation de jumelles
type widget = Bool_radio
Valeurs = ["oui", "non"]

L'affichage est :
![jumelles_ouinon](https://user-images.githubusercontent.com/99525491/168732317-a8efc14e-b01a-43d7-8b99-1b803ec28157.PNG)

En cochant oui, le résultat en base est:  "utilisation_jumelles": true
En cochant non : "utilisation_jumelles": false

Donc parfait.

2/ Autre essai avec cet exemple : 

Nom du champ = comptage_wetlands
Label du champ =        _<--laissé vide (1 espace)_
type widget = Bool_radio
Valeurs = ["Comptage wetlands"]

L'affichage est :
![wetlands_oui](https://user-images.githubusercontent.com/99525491/168732538-27104f76-28e7-4195-bdfc-0d71323fcae9.PNG)

Si coché: "comptage_wetlands": true
Sinon "comptage_wetlands": null

Je préfère l'affichage du second exemple malgré le null au lieu du false, je vais partir là dessus. 

Je ferme donc le ticket ! Merci
