### ISSUE TITLE
Commentaire général au niveau de la Fiche

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/GeoNature#189]
En espérant que cela n'ait pas déjà été débatu précédemment pour la V2, je vous fait part d'un point d'amélioration qui m'est remonté de plusieurs collègues et dont j'ai moi-même ressenti le besoin.

Il serait utile de disposer d'un champ "commentaire" pour l'ensemble des taxons d'une fiche contact.

A l'heure actuelle, si on veut préciser une info générique pour tous les taxons, il faut la répéter à chaque commentaire de taxon.

Pour ne pas alourdir le nombre de champs de la synthèse, il suffirait de concaténer les 2 commentaires (de la fiche et du relevé) dans 1 seul champ par la suite.
Pour ce qui est de l'ergonomie de saisie, ce genre de champs facultatifs seraient judicieusement placé dans une DIV masquée par défaut (accessible par un "+" par exemple).

(pour rejoindre les discussions précédentes, cela reste bien entendu des "commentaires", donc pas des données sur lesquelles ont ferait des stats ou des analyses, mais des données importantes quand même)

**Comment by sig-pnrnm** [comment]
J'ai un doute sur le fait que cette proposition ne corresponde pas à la suggestion (issue #188 ) de Gil d'un

> module permettant de décrire la prospection

Je ne sais pas trop ce à quoi correspond un "module" dans GeoNature ? Cela s'ajouterait au protocole "contact", de manière optionnelle ? Si oui, c'est parfaitement ce qui me semblerait pertinent.
(bien que pour moi, ces informations n'aient valeur que de commentaires)

**Comment by camillemonchicourt** [comment]
Un module est un schéma de BDD et formulaire à part pour ne pas mélanger Contact et absence. 
Donc ça ne répond pas à ta demande.

**Comment by sig-pnrnm** [comment]
Ok, mais alors du coup, est-ce que ce besoin de "commentaire global" s'est déjà faire ressentir ?

J'insiste sur le fait que, dans mon idée, cela ne nécessiterait même pas de modifier la structure des tables de GeoNature : une simple "concaténation" du commentaire global et du commentaire du taxon répondrait au besoin.

Exemple en condition "réelles" : 

Chasse de nuit Papillons : 

Commentaire global :
```
Chasse de nuit avec lampe à Vapeur de mercure + néon UV.
Arrêt de la chasse cause bourasques de vent à 23h.
```
Commentaire taxon : 
```
1 femelle pond sur le drap
```
Ce qui donnerait, concaténé dans un champ commentaire formaté en XML/HTML (par exemple, mais JSON possible aussi) : 

```
<commentaire global>Chasse de nuit avec lampe à Vapeur de mercure + néon UV.<br>Arrêt de la chasse cause bourasques de vent à 23h.</commentaire global>
<commentaire taxon>1 femelle pond une 20aine d'oeufs sur le drap</commentaire taxon>
```

Qu'en pensez-vous ?

**Comment by gildeluermoz** [comment]
Oui en V2. 
Tu cites le format xml. Tu y vois un usage précis ?

**Comment by sig-pnrnm** [comment]
> Tu cites le format xml. Tu y vois un usage précis ?

C'est juste que je me dis qu'en concaténant les 2 informations (`commentaire global` + `commentaire taxon`) dans un champ `commentaire`, il sera utile pour la machine de pouvoir les "déconcaténer" (en cas de modification de donnée à postériori par exemple).

Du coup, j'ai pensé qu'un language type XML/JSON permettait d'attribuer des balises/attributs à chaque "sous-partie" de ce champ commentaire, pour les distinguer.

**Comment by gildeluermoz** [comment]
Je vois. A creuser mais à partir du moment ou les informations sont garées ailleurs dans la base (schéma source), il est possible de les reconstruire proprement. Donc introduire un language verbeux comme le xml va faire grossir la base. Si le besoin se présente, il sera toujours possible de le faire à postériori ou via une requête sur le schéma source.

**Comment by sig-pnrnm** [comment]
> à partir du moment ou les informations sont garées ailleurs dans la base

Je suppose que tu veux donc dire que dans la source, le champ `commentaire général` est bien distinct du champ `commentaire taxon`
Si les champs sont bien distincts, pas besoin de language informatique pour les distinguer effectivement : je faisais juste cette proposition dans le cas où on ne voudrait pas créer de nouveau champ spécifique.

**Comment by gildeluermoz** [comment]
Oui dans la logique de ma réponse, on créer comme tu le proposes, deux niveaux de commentaires.

**Comment by camillemonchicourt** [comment]
Champs intégré dans le MCD du Contact V2 : https://github.com/PnX-SI/GeoNature/blob/docker/data/modules/contact/contact.sql#L36
