### ISSUE TITLE
Champs additionnels - Filtre dans Valeurs

### ISSUE THREAD

**Issue by ca-rock** [PnX-SI/GeoNature#1894]
Bonjour,
Dans les champs additionnels, pour un type widget "nomenclature", est-il possible de n'afficher qu'une sélection de valeurs (comme avec l'attribut "filters" de monitorings) ? J'ai testé des listes d'id_nomenclature, de cd_nomenclature, des objets du type {"cd_nomenclature":["1","2"]}, sans succès.
Merci!

**Comment by TheoLechemia** [comment]
Bonjour,
C'est `cd_nomenclatures` avec un `s`. A tester

**Comment by ca-rock** [comment]
J'ai testé : 
![Capture](https://user-images.githubusercontent.com/99525491/169463177-6eb0beae-4105-40c6-a726-d523006b1c6c.PNG)
mais ça ne change rien, la liste n'est pas filtrée

Le champ "Valeur par défaut" est lui bien pris en compte pourtant (j'utilise le type nomenclature "Objet du dénombrement" avec une valeur par défaut à "Individu").

**Comment by TheoLechemia** [comment]
Effectivement, c'est que sur branche develop. Dispo dans la prochaine release

**Comment by DonovanMaillard** [comment]
ça ne fonctionne pas dans les autres attributs avec la variable filter ? Globalement j'avais r&éussi à faire sur les champs additionnels tout ce qu'on peut faire sous monitoring de mémoire
