### ISSUE TITLE
V2 : médias

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#191]
Dans le cadre du contact, quelqu'un a créé une table ``taxonomie.t_photos_taxon`` avec une clé étrangère ``id_taxon_cfaune`` sur la table ``contactfaune.t_taxon_cfaune``
**Remarque et question** :
* Si cette table ne concerne que le contact, il faut la mettre dans le schéma ``contactfaune`` pour des questions de modularité de l'installation (avec un ``contactfaune.sql``) et de logique (elle concerne uniquement les observations faites dans le cadre du contact faune).
* On a potentiellement besoin de faire le lien avec d'autres types de médias (vidéos et sons notamment) donc le terme de photos me semble trop restrictif.
* Conserve t-on cette logique d'une table médias par module ou factorise t-on tous les médias dans une seule table ?
* Dans ce dernier cas utilise t-on la table ``taxonomie.t_medias`` (utilisée actuellement par TaxHub) + ajout d'un ``id_media`` dans ``contactfaune.t_taxon_cfaune`` ?
* Faut-il prévoir un mécanisme qui permet d'exclure de l'atlas par exemple, certains médias d'un taxon qui ne seraient pas pertinents ? 
* Il faut prévoir le cas de medias attachés à l'observation d'un taxon qui seront finalement ensuite rattachés à un autre taxon.

**Comment by camillemonchicourt** [comment]
Ça doit aller dans taxonomie si c'est lié au taxon. 
Si c'est lié à une observation c'est autre chose. Ça ne doit pas aller dans `taxonomie`. Comme tu dis, soit dans le schéma du protocole concerné soit dans un schéma commun et factorisé mais pas `taxonomie`. 
Et dans ce cas la table doit plutôt s'appeler `contactfaune.t_photos_observations`.

**Comment by sig-pnrnm** [comment]
Pour ajouter ma participation à cette reflexion, je fait part du fait que ce besoin de module "photos d'observations" (contact si protocole contact), est un **besoin important remonté de mes collègues**, notamment en lien avec le processus de validation des données.

Donc, pour nous les photos sont à rattacher au protocole utilisé pour la saisie (contact), et non au taxon (effectivement avec la possibilité de changer de taxon lié si le processus de validation invalide la donnée).

> Et dans ce cas la table doit plutôt s'appeler `contactfaune.t_photos_observations`.

Ca me semble la bonne solution.

**Comment by gildeluermoz** [comment]
Compléments sur les principes dans la base de données :
* Le schéma d'un module doit pouvoir être ajouter ou supprimer facilement de la base. A ce titre :
    * aucun objet (table, foreign table, séquence, vue, fonction, trigger) des schémas du cœur (meta, layers, taxonomie, utilisateurs, synthese, etc...) ne doit pointer vers les objets du schéma d'un module  .
    * aucun objet du schéma d'un module ne doit pointer vers les objets du schéma d'un autre module.
    * toutes les objets propres à un module sont dans le schéma du module.
* Chaque module dispose d'un script sql indépendant qui permet d'ajouter le module en base.

**Comment by gildeluermoz** [comment]
Ok, merci pour vos contributions et vos réponses. Je pars sur une ``contactfaune.t_medias``.
Du coup on peut imaginer qu'un média concerne une observation ``contacfaune.t_obs_cfaune" ou un des taxons observés ``contacfaune.t_taxon_cfaune".
Dans chacun de ces deux tables j'ai une clé étrangère pointant vers ``contactfaune.t_medias``.

**Comment by camillemonchicourt** [comment]
Oui je penche plus pour intégrer ça à chaque protocole quand celui-ci le justifie. Pour le moment je ne vois pas vraiment d'autres protocoles où on aurait besoin de photos/medias.

Par contre si on décide de factoriser une partie des protocoles dans un nouveau dédié à cela, alors on pourra aussi y factoriser les médias. Mais cela dépendra des choix fait sur ce sujet - https://github.com/PnEcrins/GeoNature/issues/171

Si le protocole ne prévoit que des photos, alors je partirai plus sur  `contactfaune.t_medias` que sur `contactfaune.t_medias`, ça sera plus précis et sans kiproko.

**Comment by gildeluermoz** [comment]
Les changements sur le modèle sont tjs très impactants; Le protocole ne prévoit rien de bien défini. Le type de média pouvant servir à la validation d'une donnée ne me semble pas devoir être restreint à la photo. Exemple, les orthoptères, les chiros, les cigales où le chant est déterminant et parfois plus discriminant que la photo. Donc ``contactfaune.t_medias_cfaune`` me parait plus prudent, plus adapté et plus ouvert.

**Comment by sig-pnrnm** [comment]
> Donc contactfaune.t_medias_cfaune me parait plus prudent, plus adapté et plus ouvert.

👍 Tu as raison !

**Comment by camillemonchicourt** [comment]
OK j'avais pas vu ce genre de cas. Je capte, OK !
Petit détail, pas besoin de remettre `cfaune` dans le nom de chaque table vu qu'elles seront dans le schema `contactfaune`.

**Comment by gildeluermoz** [comment]
Ce sujet est à trancher. IL est aussi valable pour les noms de tables.
En lien avec le modèle PG traduit en objets Python (ou PHP), pas de risque de doublons.
Avantage, le nom de champ est unique, il n'y a pas d'ambiguïté et dans un 
``SELECT id_media_cfaune FROM contactfaune.t_medias_cfaune mc, taxonomie.t_medias m``
 tu peux oublier l'alias ``m`` ou ``mc`` car le nom du champ est unique.
Inconvénient c'est lourd.
Je n'ai pas de religion mais il faudra ci-possible être homogène.
Si qq'un connait les bonnes pratiques...

**Comment by camillemonchicourt** [comment]
Amandine :  

> - Je suis d'accord pour séparer ceux de taxonomie, de ceux des protocoles (car TaxHub est un module indépendant et doit le rester)

**Comment by DonovanMaillard** [comment]
Salut à tous, 

Ok également pour une séparation des photos/médias de taxo et des obs... sur plein d'apsects (clarté, modularité, mauvais rattachements si erreurs de détermination lors d'observations etc). 
Ok aussi pour média plutôt que photos... même si l'utilisation de son, aussi intéressante soit-elle, me semble anecdotique dans la pratique.

**Comment by camillemonchicourt** [comment]
Finalement on valide le principe d’avoir un schéma commun dédié aux médias des différents protocoles.

**Comment by camillemonchicourt** [comment]
Dans Geotrek, la table est : 

```
CREATE TABLE geotrek.fl_t_fichier
(
  id integer NOT NULL DEFAULT nextval('fl_t_fichier_id_seq'::regclass),
  content_type_id integer NOT NULL,
  object_id integer NOT NULL,
  attachment_file character varying(512) NOT NULL,
  filetype_id integer NOT NULL,
  creator_id integer NOT NULL,
  titre character varying(128) NOT NULL,
  legende character varying(128) NOT NULL,
  date_insert timestamp with time zone NOT NULL,
  date_update timestamp with time zone NOT NULL,
  auteur character varying(128) NOT NULL,
  marque boolean DEFAULT false,
  attachment_video character varying(200) NOT NULL DEFAULT ''::character varying,
  attachment_link character varying(200) NOT NULL,
  CONSTRAINT fl_t_fichier_pkey PRIMARY KEY (id),
  CONSTRAINT content_type_id_refs_id_b5ae9576dda7a04 FOREIGN KEY (content_type_id)
      REFERENCES django.django_content_type (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT creator_id_refs_id_6b473886ce977280 FOREIGN KEY (creator_id)
      REFERENCES django.auth_user (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT filetype_id_refs_id_703a9ddc1c89500b FOREIGN KEY (filetype_id)
      REFERENCES geotrek.fl_b_fichier (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT paperclip_attachment_object_id_check CHECK (object_id >= 0)
```

**Comment by DonovanMaillard** [comment]
Du coup, un schéma média, mais une table par protocole?  Aucun média rattaché directement au schéma taxo pour l'alimentation de l'atlas? Taxhub irait directement écrire dans le schéma média? :)

**Comment by camillemonchicourt** [comment]
Non non, TaxHub on touche, il a ses propres médias liés aux taxons. 
Mais dans GeoNature, on créé un schéma `medias` pour les médias des observations des différents protocoles. 

On dissocie bien les médias des taxons et ceux des observations.

**Comment by DonovanMaillard** [comment]
Ok super! Mais un seul schéma pour tous les protocoles, puisqu'il s'agit dans tous les cas de médias liés à des obs. Ca me semble plus clair! :)

**Comment by camillemonchicourt** [comment]
Oui c'est ça !

**Comment by camillemonchicourt** [comment]
Gil mentionnait cette proposition : 

- une table centrale unique dans un schéma medias
- une clé étrangère dans des tables de correspondance : une par protocole.
- pas de partage possible d'un média par plusieurs protocoles (au moins au départ) afin de ne pas avoir à construire d'interface pour lister, filtrer, rechercher, cocher.
- l'ajout ou la suppression des médias se font via l'interface du protocole, dans un onglet média sur le modèle de TaxHub = pas de gestion globale de tous les médias de la table medias.t_medias.
- création d'un 'component' permettant de factoriser l'interface et les fonctionnalités de l'onglet médias dans les formulaires des protocoles faisant usage de médias.

**Comment by camillemonchicourt** [comment]
Voir le schéma `media` : https://github.com/PnX-SI/GeoNature/blob/docker/data/core/medias.sql

**Comment by gildeluermoz** [comment]
done !
