### ISSUE TITLE
V2 - Tableau de bord - Accueil

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#192]
Dans la V2, il est souhaité améliorer la page d'accueil de l'outil pour en faire un vrai tableau de bord avec un aperçu des données existantes dans la BDD, quelques graphiques sur la répartition des données, un aperçu des dernières données, des liens directs vers les différents modules. 

Une première maquette pour illustrer cela avait été réalisée : 

![gn2-dashboard](https://user-images.githubusercontent.com/4418840/27587487-d852c22a-5b44-11e7-85da-02069db642a9.png)

Il est défini qu'une sidebar est présente sur la page d'accueil mais est aussi intégrée dans les différents modules. Il est donc important d'en faire un composant/template générique que l'on peut intégrer dans des modules spécifiques. 

Par ailleurs, cette sidebar est composée d'outils intégrés à GeoNature mais peut aussi contenir des modules GeoNature spécifiques à une structure voire des modules externes. 

Cette sidebar doit donc être générée dynamiquement avec des items renvoyant à des modules (page ou protocole), avec la possibilité d'ajouter ou désactiver des modules. 

A noter aussi que les accès aux différents modules peuvent dépendre des droits de l'utilisateur connecté. 

Les statistiques globales peuvent présenter les données dans les BDD, par organisme, par règne, par groupe INPN, par année, par protocole...

**A GARDER EN MÉMOIRE**

- Définir une méthode permettant d’afficher ou non les boutons des différents protocoles selon les
droits de l’utilisateur connecté
- Multilingue (Flask-Babel ou AngularJS)
- Mécanisme d’authentification globale pour ne pas avoir à se connecter à chaque protocole. Mais
permettre aux protocoles d’être autonomes et d’avoir leur propre authentification si ils sont
installées de manière indépendante ?

**Comment by camillemonchicourt** [comment]
Premiers développements : 
![gn-dashboard](https://user-images.githubusercontent.com/4418840/29164643-70e52e40-7dc0-11e7-9a02-cdb7bf473d6b.jpg)

**Comment by samuelpriou** [comment]
Cette nouvelle ergonomie donne envie de voir le futur Geonature !

**Comment by DonovanMaillard** [comment]
Juste une petite note ici pour garder en mémoire le point vu l'autre jour à l'oral : 
Parmi les graphs, des courbes d'accumulation d'espèces années par années, ça peut être cool (nombre d'espèces cumulées comprenant des données au 31 decembre de chaque année). Si possible, par grand groupe (groupe 2 INPN?), sinon, à discuter.

**Comment by camillemonchicourt** [comment]
Penser aussi à pouvoir activer/desactiver chaque bloc avec des paramètres.

**Comment by DonovanMaillard** [comment]
Le must du must serait que l'outil prévoit les blocs, et que l'administrateur puisse choisir ce qu'il y met comme graphs ;) Mais ça devient surement ingérable pour vous, et ça complique encore un peu la mise en place de l'outil pour ceux qui veulent faire simple...

**Comment by camillemonchicourt** [comment]
Concernant les statistiques, il y aura les principales sur la page d'accueil mais on prévoit aussi d'avoir un module STATISTIQUES avec plus de stats et graphiques. 

On avait parlé de ne plus les baser sur les lots ou les protocoles mais plutôt sur les programmes. Voir https://github.com/PnX-SI/GeoNature/issues/135

Le nombre d'espèces est intéressant. On peut le voir de différentes manières. Le nombre d'espèces total dans la BDD chaque 31 décembre (pour voir les nouvelles espèces découverts année après année) ou bien le nombre d’espèce saisies chaque année (pour voir la diversité des espèces observées chaque année). 

Les stats seront plus génériques et paramétrables que dans la V1 mais ils seront automatisés, et on ne pourra pas faire un outil de stats paramétrables graph par graph etc. Pas dans un premier temps en tout cas.

**Comment by DonovanMaillard** [comment]
D'accord! Pour le volet espèce, les 2 infos sont intéressantes, et assez complémentaires. 
Pour le volet stats plus complet, en effet ça peut être intéressant, même si en soit tout peux se calculer sur demande sur R a posteriori si on veut des analyses précises. Pour le fait que tout n'es pas paramétrable, au moins dans un premier temps, je comprends  que ça simplifie beaucoup les choses! 

Par contre, est-ce bien utile d'avoir un "vrai" bloc statistiques sur la première page, si on a un module statistiques en plus? Est-ce que dans ce cas un simple nombre de données, d'espèces, de communes comme sur l'atlas ne suffit pas? Je trouve ça un peu paumatoire d'avior des stats sur l'accueil et RE des stats sur un onglet spécifique

**Comment by camillemonchicourt** [comment]
On va voir ça. Mais l'idée des stats est de donner un aperçu général et rapide des données, de leur évolution et de leur répartition, aux agents qui saisissent des données mais ne feront pas de R ou autre.

**Comment by DonovanMaillard** [comment]
Oui bien sur! Mais tout ça sera dans un onglet statistique. C'est le fait d'en mettre une partie en accueil et une partie en onglet "statistique" qui m'étonne.

**Comment by camillemonchicourt** [comment]
OK ça va alors, tu comprendras. :-)

La logique d'une page d'accueil est de montrer le principale et ensuite de faire rebondir les gens. 

Donc quelques graphs principaux et un gros bouton en dessous du genre "VOIR TOUTES LES STATS". 

Comme quand sur un site tu as les dernières actus et à côté un gros bouton VOIR TOUTES LES ACTUS. 

On affichera aussi les dernieres observations et et un bouton en dessous CONSULTER LA SYNTHESE...

**Comment by DonovanMaillard** [comment]
Ton coté marketting me laissera toujours sans voix ;) M'étonne pas que tu sois atterri un étage trop haut ;)

**Comment by camillemonchicourt** [comment]
Baser la liste des modules du MENU sur un table, permettant de renvoyer vers des modules internes ou externes.

**Comment by camillemonchicourt** [comment]
Voir aussi https://github.com/PnX-SI/GeoNature/issues/290

**Comment by camillemonchicourt** [comment]
La suite dans le module dédié : https://github.com/PnX-SI/gn_module_dashboard
