### ISSUE TITLE
V2 - Proposition log exports et téléchargements de données

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#193]
Bonjour à tous, 

Me voila de retour, pour proposer pour la V2 un archivage des exports de données. En clair, une table qui répertorie qui a téléchargé quoi et quand : Notamment pour les exports partenaires (et si possible pour les exports faits sur la base de requêtes dans la synthèse, mais à la limite ça me semble moins prioritaire). Le but étant de savoir si les partenaires utilisent l'outil ou non, à quelle fréquence.  Dans ce cas précis, on connait la nature des données exportées puisque la requête est fixe. 
Dans le second cas.... possible de sauvegarder la requête d'une manière ou d'une autre? Plutôt que de sauvegarder les fichiers exportés, qui pour le coup prendraient pas mal de place... à discuter sur ce dernier point selon les besoins et avis de chacun, 

Donovan

**Comment by DonovanMaillard** [comment]
Un petit up, puisqu'on en parlait avec Camille récemment ;) 

c'est susceptible d'intéresser d'autres personnes?

**Comment by camillemonchicourt** [comment]
On n'est pas sur un forum Donovan ! :-D

Pas besoin de UP....

**Comment by camillemonchicourt** [comment]
Tu te prends pour Facebook à vouloir tracer les utilisateurs ?

En plus cela a des consequences renforcées à partir de cette année: https://www.cnil.fr/fr/reglement-europeen-sur-la-protection-des-donnees-ce-qui-change-pour-les-professionnels

**Comment by camillemonchicourt** [comment]
Fait dans le module d'export en cours de développement : https://github.com/PnX-SI/gn_module_export

Par contre ça ne logue que les exports réalisés dans ce module transversal. Pas les exports fait directement dans chaque module (Synthèse, Occtax...).
