### ISSUE TITLE
Installation Globale Geonature 2.9.2

### ISSUE THREAD

**Issue by fggn6** [PnX-SI/GeoNature#1961]
2.9.2
Version de GeoNature affectée par le bug.

Description du problème rencontré (message d’erreur, code HTTP de retour inattendu, …).
Bonjour,  lors de la commande d'installation **./install_all.sh 2>&1 | tee install_all.log**
L'installation reste bloquée sur **Processing 1/1: /tmp/tmpab236m51/BDALTIV2_250M_FXX_0098_7150_MNT_LAMB93_IGN69.asc**
Obligé de tuer la l'installation et de la relancer.
Mais l'installation après relance n'est jamais valide

**Comment by bouttier** [comment]
Bonjour,
L’installation de la BDALTI est particulièrement long (1 à 2h …), combien de temps avez-vous attendu ?
Pour sauter cette étape, mettre ``false`` dans le fichier ``config/settings.ini``.
