### ISSUE TITLE
Trouver un remplacant à la bibliothèque ``geog``

### ISSUE THREAD

**Issue by bouttier** [PnX-SI/GeoNature#1972]
Cette bibliothèque permet de générer un WKT à partir d’un point et d’un rayon. Elle est utilisé dans les filtres de la synthèse.

Or celle-ci n’est plus supporté (dernière release il y a 7 ans), génère un warning (corrigé upstream mais pas releasé https://github.com/jwass/geog/pull/1) et rajoute l’énorme dépendance qu’est ``numpy`` utilisé nulle part ailleurs dans GeoNature.

**Comment by joelclems** [comment]
On pourrait remplacer l'utilisation de `circle_from_point` et le `st_intersect` par l'utilisation d'un `st_distance_within` 

https://github.com/PnX-SI/GeoNature/blob/f241a299f8dc54e72ac1eb77829d27e2a57c7873/backend/geonature/core/gn_synthese/utils/query_select_sqla.py#L297-L306

**Comment by lpofredc** [comment]
En effet, autant utiliser PostGIS (via GeoAlchemy) qui est parfaitement adapté à cet usage.

**Comment by bouttier** [comment]
Hum, ``ST_Within`` permet de savoir si un WKT A est inclus dans un WKT B. Ça ne me semble pas résoudre notre problème de génération de cercle.

**Comment by bouttier** [comment]
Oups, je n’avais pas lu le ``D`` du ``DWithin`` ! J’ai rien dit !

**Comment by bouttier** [comment]
Fait dans #1993

**Comment by joelclems** [comment]
J'y pense seulement mainteant mais il y a peut être un point de vigilance à avoir et vérifier si radius est donné en dégré et non en mètres.

je crois que le rayon est donné par layer.getRadius() qui renvoie des metres

https://github.com/PnX-SI/GeoNature/blob/f241a299f8dc54e72ac1eb77829d27e2a57c7873/frontend/src/app/GN2CommonModule/map/leaflet-draw/leaflet-draw.component.ts#L147-L150

https://leafletjs.com/reference-0.7.7.html#circle-getradius

il faudrait le convertir en degrés pour l'utiliser dans st_dwithin

**Comment by bouttier** [comment]
Les géométries sont converties en géographie de manière à pouvoir utiliser des mètres avec ``ST_DWithin``.
Je n’ai pas vérifié si le front envoi bien des mètres, mais les tests unitaires du backend attendaient bien des mètres.

**Comment by joelclems** [comment]
ok je viens de voir l'utilisation de `ST_GeogFromWKB` dans `ST_DWithin`, ça doit être tout bon dans ce cas
