### ISSUE TITLE
[ Install ] Import des exmple de taxons

### ISSUE THREAD

**Issue by pierrejego** [PnX-SI/GeoNature#1979]
**Version**
develop

**Description du bug**
Lors de l'installation d'une nouvelle plateforme avec les données d'exemple, l'installation échoue car il ne trouve pas taxonomie_taxons_example

C'est certainement lié à https://github.com/PnX-SI/GeoNature/commit/906305b15590566d89c1f624a145f2e1bb027720 les taxons n'étant plus géré par alambic

**Comportement attendue**
Exemple de taxons inséré en base

**Comment reproduire**
Lancer une installation sur une serveur vierge en mode prod avec insertion des données exemples

**Logs**

Inserting sample dataset of taxons for taxonomic schema...
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
ERROR [flask_migrate] Error: Can't locate revision identified by 'taxonomie_taxons_example'

**Comment by bouttier** [comment]
Est-ce que tu installes bien le requirements-dev.txt et non le requirements.txt (qui nécessite de faire des releases des sous-modules) pour être mis à jour ?

**Comment by pierrejego** [comment]
Oui

**Comment by bouttier** [comment]
Je vois dans ton ticket que du dis « en mode prod », c’est donc le requirements.txt qui est utilisé et non le requirements-dev.txt.
C’est donc « normale » que ça ne fonctionne pas, mais on va tâcher de faire les releases nécessaires dans les jours à venir.

**Comment by bouttier** [comment]
Mais il reste bien le montage d’une branche de taxon d’exemple dans le script d’installation de la db, peu importe le mode. Je le vire.
Merci pour le retour.

**Comment by bouttier** [comment]
1d00a7ddd5ab9ebc07fb0a3099bb1ab90f22ff26

**Comment by pierrejego** [comment]
Effectivement j'ai dis prod, mais en fait j'ai modifié deux choses -> 
dans l'install_backend.sh ligne 88 j'ai remplacé dev par prod pour avoir les bons requirements en -dev 
et dans l'install_all.sh j'ai remplacé ligne 76 dev par prod et l'url github vers la  branche develop

C'est le seul moyen que j'ai trouvé pour installer geonature en mode dev et le reste en mode prod (taxhub/userhub).
Si tu lances le script en mode dev en pointant vers la developp l'install ne se fait pas du tout
