### ISSUE TITLE
[2.9.2] Installation nouvelle instance bloquée, psycopg2 ne s'installe pas ?

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature#1994]
**Version**
2.9.2

**Description du bug**
Blocage dans l'installation d'une nouvelle instance GeoNature, psycopg2 n'a pas l'air de vouloir s'installer, bloque ensuite la suite de l'installation, la base de données ne se créée pas

**Logs**
[install_all.log](https://github.com/PnX-SI/GeoNature/files/9487570/install_all.log)

**Comment by camillemonchicourt** [comment]
Salut, une petite recherche de l'erreur (``./psycopg/psycopg.h:35:10: fatal error: Python.h: Aucun fichier ou dossier de ce type``) sur internet renvoie souvent le même soucis.
Par exemple ici : https://stackoverflow.com/questions/22938679/error-trying-to-install-postgres-for-python-psycopg2

Il faudrait installer au préalable ``sudo apt install python3-dev``

**Comment by maximetoma** [comment]
Dak merci beaucoup ! Oui ça a résolu le pb psycopg mais après j'ai eu un pb avec postgis, mais j'ai réussi à le débloquer 

C'est niquel, l'install s’est bien passée autrement :)
Enfin normalement mais je n'arrive pas à me connecter à mon serveur via le navigateur...

**Comment by camillemonchicourt** [comment]
Ce n'est pas normal que ce soucis de psycopg soit apparu au niveau de l'installation globale de GeoNature version 2.9, qui fonctionnait bien avant.
Donc forcément une dépendance qui a bougé entre temps.

**Comment by pierrejego** [comment]
Pour info, je viens de refaire aussi plusieurs installation et pas de soucis de psycopg.

Juste un soucis de version de nvm utilisé avec le script d'installation en mode dev, ça build bien en 14.15 mais pas en 16.12 comme le script essaye de le faire.

**Comment by DonovanMaillard** [comment]
sur certains de mes projets python mais jamais dans GeoNature, je n'arrive pas à installer psycopg2. Je règle le soucis en installant psycopg2-binary qui passe sans soucis et sans conséquences (identifiées) pour l'appli,
Peut être une question d'OS, de version de python, de virtualenv ou autre...

**Comment by maximetoma** [comment]
Pour ma part, je suis sur Debian 11 et Python 3.9.2

**Comment by bouttier** [comment]
``python3-dev`` et ``libpq-dev`` rajoutés à la liste des paquets nécessaires : https://github.com/PnX-SI/GeoNature/commit/b4d26421952a777e1869686ce76319f61e56c054
