### ISSUE TITLE
[2.9.2] Problème accès GeoNature avec serveur OVH

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature#2002]
**Version**
2.9.2

**Description du bug**
Je n'arrive à joindre mon GeoNature sur notre nouveau serveur OVH
J'ai voulu installer une nouvelle instance vierge pour commencer sur notre nouveau serveur mais je n'arrive pas à accéder au serveur: en tapant l'ip publique dans la barre de recherche, ça recherche en boucle avant d'afficher cette page : 

![image](https://user-images.githubusercontent.com/66769358/189654713-340e18ed-ab9a-4af6-8d28-0c5cbe4f5e20.png)

En vérifiant, tous les status sont au vert geonature, taxhub, usershub et apache2

Avez-vous une idée du problème ? Apache mal configuré ? Problème côté serveur ? Côté OVH ? Y-a-t-il eu des antécédents avec des installations sur des serveurs OVH ?

Merci :)

**Comment by TheoLechemia** [comment]
Est ce que tu as les logs d'installation ?
Tu as cette erreur quand tu vas sur IP/geonature ?
Est ce qu'il y a des logs serveurs ?

**Comment by maximetoma** [comment]
Oui même erreur pour ip/geonature

Log de l'install (dans `/home/user/geonature/install`) : [install.log](https://github.com/PnX-SI/GeoNature/files/9548224/install.log)
Log de GeoNature (dans `/var/log`) : [geonature.log](https://github.com/PnX-SI/GeoNature/files/9548223/geonature.log)
Log de Apache (dans `/var/log/apache2`) : [error.log](https://github.com/PnX-SI/GeoNature/files/9548221/error.log)
Log de Apache (dans `/var/log/apache2`) : [geonature_access.log](https://github.com/PnX-SI/GeoNature/files/9548222/geonature_access.log)

**Comment by TheoLechemia** [comment]
Est ce que tu as un repertoire `dist` dans le repertoire frontend ?

**Comment by maximetoma** [comment]
Oui

**Comment by pierrejego** [comment]
Bonjour,
est-ce que tu peux nous montrer la conf apache ?
le contenu du fichier geonature de site-enable et le contenu des fichiers de conf-available ?

 A priori tu ne dois pas arriver jusqu'a ton serveur apache. Donc soit un soucis d'accès à la machine mais a priori tu y accédes en ssh pour faire l'installation donc ça ne doit pas être ça, soit peut être comme le dit @TheoLechemia un soucis de conf apache.

**Comment by maximetoma** [comment]
Oui j'arrive à me connecter au serveur en ssh et même à la BDD via pgAdmin

La conf de geonature

    <VirtualHost *:80>
        ServerName 162.19.89.37
    
        IncludeOptional /etc/apache2/conf-available/geonature.conf
        IncludeOptional /etc/apache2/conf-available/taxhub.conf
        IncludeOptional /etc/apache2/conf-available/usershub.conf
    
        ErrorLog "/var/log/apache2/geonature_error.log"
        CustomLog "/var/log/apache2/geonature_access.log" combined
    </VirtualHost>

La conf des fichiers de conf-available
[charset.txt](https://github.com/PnX-SI/GeoNature/files/9554254/charset.txt)
[geonature.txt](https://github.com/PnX-SI/GeoNature/files/9554255/geonature.txt)
[localized-error-pages.txt](https://github.com/PnX-SI/GeoNature/files/9554256/localized-error-pages.txt)
[other-vhosts-access-log.txt](https://github.com/PnX-SI/GeoNature/files/9554257/other-vhosts-access-log.txt)
[security.txt](https://github.com/PnX-SI/GeoNature/files/9554258/security.txt)
[serve-cgi-bin.txt](https://github.com/PnX-SI/GeoNature/files/9554259/serve-cgi-bin.txt)
[taxhub.txt](https://github.com/PnX-SI/GeoNature/files/9554260/taxhub.txt)
[usershub.txt](https://github.com/PnX-SI/GeoNature/files/9554261/usershub.txt)

**Comment by jbrieuclp** [comment]
Tu n'as pas un pare feu qui bloque le port 80 ou 443 ?

**Comment by maximetoma** [comment]
@jbrieuclp Non pas de pare-feu, et notre pare-feu interne ne bloque pas ces ports-là

**Comment by lpofredc** [comment]
Que donne la commande suivante?

```sh
systemctl status apache2
```
Si apache2 est en échec, peux-tu renvoyer le retour de la commande 

```sh
apachectl -t
```

Des tests sur les ports web 80 et 443 avec telnet ne donnent rien.

```sh
telnet 162.19.89.37 80
telnet 162.19.89.37 443
```

**Comment by maximetoma** [comment]
Salut @lpofredc

Voici ce que me donne `systemctl status apache2`

![image](https://user-images.githubusercontent.com/66769358/189849291-d500eda4-8047-4f07-a704-5e6276185198.png)

**Comment by jbrieuclp** [comment]
Ton utilisateur Debian qui gère geonature est bien rattaché au groupe www-data ?
Est-ce que si tu remets la config apache de base tu arrives à accéder à la page d'accueil d'apache, celle par défaut ?

**Comment by maximetoma** [comment]
> Tu n'as pas un pare feu qui bloque le port 80 ou 443 ?

@jbrieuclp en revérifiant, tu avais raison, c'était ça.... merci beaucoup encore pour toute votre aide :)
