### ISSUE TITLE
[METADONNEES] Optimisation du frontend

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature#2004]
Bonjour,

## Contexte
Suite à des discussions avec l'ARB île de France, un problème de performances a été observé sur leur instance à cause d'un nombre important de jeux de données. Plusieurs dizaines de secondes de chargement sont nécessaires avant de pouvoir accéder à un Cadre d'Acquisition (CA) ou à un Jeu De Données (JDD).
En testant chez moi, je reproduis le problème avec une centaine de CA contenant chacun 20 JDD, j'ai un petit délai de chargement du front après que la requête back ait été complétée.
 
## Proposition
Pour optimiser les requêtes, il serait intéressant tout d'abord de ne charger les JDD qu'au moment où l'utilisateur déroule l'accordéon. En effet, l'utilisateur n'a pas tout le temps besoin de disposer de tous les JDD à tout moment.
Cela implique :
- Requête `GET` au backend en ne prenant que les CA
- Requête `GET` au backend lors du déroulement de l'accordéon d'un CA pour obtenir les JDD associés
- Revoir la fonction de recherche pour faire un appel au backend avec un ilike sur les JDD et CA (`id`, `name`, `start_date`)

Enfin paginer côté backend, comme mentionné ici #1559, pourrait améliorer les performances côté back et donc côté front.

Je suis en train de parcourir un peu le code pour voir comment faire tout ça.

Dites moi ce que vous en pensez !

**Comment by camillemonchicourt** [comment]
Il est clairement identifié qu'il faut paginer les métadonnées côté serveur.
Aucun intérêt de le faire côté client comme actuellement et c'est problématique quand on commence à avoir beaucoup de JDD.

Donc oui, c'est dans la liste des choses à faire et toute contribution sur le sujet serait bienvenue.

Il faudra certainement revoir la recherche dans les métadonnées en même temps.

**Comment by mvergez** [comment]
Merci beaucoup pour ton retour @camillemonchicourt, j'essaie de m'en occuper dans une PR !

**Comment by jpm-cbna** [comment]
@mvergez Sur les sites des SINP, j'ai aussi effectivement un problème de performance. La pagination côté serveur devrait résoudre en grande partie le problème.

Mais plus précisément, sur nos sites, c'est le web service https://expert.silene.eu/api/synthese/observation_count_per_column/id_dataset qui bloque l'affichage car il met plusieurs secondes à s’exécuter.
Son problème c'est qu'il cherche à récupérer en un seul appel le nombre d'observations de tous les jeux de données rapatrié côté client ! En plus, ce nombre d'observation n'est affiché que lorsqu'on déroule l'accordéon d'un CA. Il serait à mon avis aussi très intéressant de faire appel à ce web service uniquement au moment de l'ouverture d'un CA.

**Comment by antoinececchimnhn** [comment]
@mvergez
Une pagination a été mise en place sur la liste des imports pour la v2 du module, je pense que ça peut être relativement proche du besoin sur les metadonnées

**Comment by mvergez** [comment]
@jpm-cbna, merci beaucoup pour ton retour ! J'espère pouvoir résoudre rapidement ce problème de pagination alors ! Je vais jeter un coup d’œil au service `observation_count_per_column`, je te dirai !

Merci beaucoup également pour ton retour @antoinececchimnhn ! Je pense m'en inspirer très fortement ;)

**Comment by jpm-cbna** [comment]
@mvergez Au sujet de la pagination côté serveur, j'en ai aussi mis une en place dans [le module Conservation Strategy](https://github.com/cbn-alpin/gn_module_conservation_strategy/blob/develop/frontend/app/strategy/taxa-list/taxa-list.component.ts#L45) sur une [datatable Angular Material](https://v12.material.angular.io/components/table/overview).

J'ai l'impression que le module Métadonnées n'utilise pas une datatable mais une liste... Ceci dit `mat-paginator` est utilisé et je l'emploie aussi...
C'est assez simple à mettre en place et je n'ai pas rencontré de problème majeur. J'ai trouvé la mise en place de la datatable Angular Material aussi beaucoup plus simple qu'avec le composant `ngx-datatable`. Mais l'expérience avec `ngx-datatable` m'a surement aidé.

Il me semble avoir suivi [un tutoriel dans ce style](https://blog.angular-university.io/angular-material-data-table/) pour mieux comprendre.

**Comment by mvergez** [comment]
Super un grand merci à toi @jpm-cbna, c'est super tous ces liens, je vais regarder tout ça ! 
Oui Métadonnées utilise une liste qui s’agrandit au fur et à mesure. Donc il faudrait changer ça en une table Angular Material. Pas mal de refact du coup !

**Comment by bouttier** [comment]
Je reprend les améliorations proposé par @mvergez en les complétant car il reste quelques troues dans la raquette il me semble. J’ai coché ce que ta PR @mvergez semble couvrir.

- [x] La recherche dite rapide est désormais une recherche backend
- [ ] Ne plus renvoyer les JDD lors de l’appelle à la route des CA : suppression du paramètre``datasets=1`` – supprimer également son support par le backend car il pose problème avec la recherche par JDD)
- [ ] Paginer la liste des CA
- [ ] Afficher pour chaque CA le nombre de JDD total
- [ ] Dans le cas d’une recherche par JDD, afficher, pour chaque CA, le nombre de JDD trouvés sur le nombre JDD total
- [x] Au clic sur un CA, récupérer ses JDD
- [ ] Paginer la liste des JDD – c’est je pense important également, certains CA pouvant avoir énormément de JDD
- [ ] Dans le cadre d’une recherche, les critères de recherche portant sur les JDD doivent être transmis lors de la récupération des JDD afin de ne récupérer que les JDD appropriés

En ce qui concerne la recherche rapide, celle-ci effectue une recherche à la fois sur les CA et les JDD, cela veut dire que dans les CA renvoyés, nous avons à la fois :

1. Des CA qui répondent aux critères de recherche
2. Des CA qui ne répondent pas aux critères de recherche, mais qui contiennent des JDD répondant aux critères de recherche

La récupération des JDD pour un CA dépend de ce cas :

1. Récupération de tous les JDD du CA
2. Transmission des critères de recherche afin de récupérer uniquement les JDD qui répondent aux critères

Le frontend sait qu’on se trouve dans le cas 2 dès lors que le CA possède un nombre de JDD trouvés.

Attention au cas d’une recherche rapide où les critères match à la fois un CA et certains de ses JDD :
- On renvoi tous les JDD car le CA match ?
- Ou on renvoi uniquement les JDD qui match, peu importe alors le fait que le CA match ?

**Comment by camillemonchicourt** [comment]
Selon moi, le fonctionnement devrait être : 

- Si la recherche matche avec un CA > Je renvoie le CA et tous ses JDD
- Si la recherche matche avec un JDD > Je renvoie son CA et uniquement le JDD qui matche
- Si la recherche matche un CA et un JDD > Je renvoie ce CA et uniquement le JDD qui matche (pour être cohérent avec le premier cas)

**Comment by lpofredc** [comment]
En complément à ces différents échanges et à la PR #2027, il serait aussi intéressant de limiter drastiquement le contenu des API utilisées sur la page d'accueil du module métadonnées (cf. capture d'écran).

- L'API `api/meta/acquisitionframework` renvoie un json très lourd et très (trop) complet alors que les données affichées dans la liste sont très réduites (l'exemple ci-après montre qu'un JSON de 8Mo est renvoyé pour 452 CA). D'autant plus que la donnée détaillée est de nouveau chargée individuellement sur la page de consultation du CA.  
- L'API de comptage par JDD est longue à être générée (dans mon cas 2 minutes pour pour 1500 JDD et 30M données).
- L'API des roles renvoie tous les roles de la bdd, alors que très peu sont acteurs. Notre cas est particulier avec 170000 roles mais ça mériterait d'être amélioré car ce scénario est aussi possible sur des instances nationales.

![Sélection_285](https://user-images.githubusercontent.com/22891423/217644495-09a13c73-d867-4fb8-92bf-f98d63acdb14.png)

**Comment by bouttier** [comment]
- Il est prévu de récupérer les CA de manière paginé, et sans intégrer les JDD qui seront récupéré indépendamment. Le JSON renvoyé sera donc bien plus léger.
- Actuellement l’API de comptage compte toutes les observations pour tous les JDD. Il est prévu de remonter uniquement le compte des observations pour les JDD qui sont récupéré (à la demande), ce qui devrait également alléger cette étape.
- Les acteurs sont renvoyé avec les CA / JDD. L’API des roles est interrogé non pas pour afficher les acteurs, mais pour sélectionner les acteurs lors de l’édition / la création de CA / JDD. Il est donc bien nécessaire de permettre la sélection de n’importe quel rôle, y compris qui n’est pas déjà acteur. Cependant, c’est effectivement beaucoup trop lourd sur des instances. Ce problème n’est pas directement en lien avec ce ticket, et j’ai donc ouvert un autre ticket pour sujet (#2330).

**Comment by lpofredc** [comment]
Parfait, merci @bouttier pour ces réponses. Concernant le premier point, il me paraît pertinent d'aller plus loin que la pagination en allégeant significativement le contenu de la réponse d'API. Peut-être avec un filtrage dynamique des champs à retourner, à l'image de ce qui se fait sur l'API GeoTrek avec le querystring `fields` (cf. https://hevodata.com/learn/rest-api-best-practices/#s4).
 
Les informations du CA affichées dans la liste des CA sont:

- id du CA
- uuid du CA
- nom du CA
- nom et role des acteurs
- date de création

Or, l'API renvoie pour un item de plus de près de 200 lignes... le delta est énorme.

```json
 {
    "acquisition_framework_desc": "test",
    "acquisition_framework_end_date": null,
    "acquisition_framework_name": "Animaux sur la route", <<<<
    "acquisition_framework_parent_id": null,
    "acquisition_framework_start_date": "2023-01-01", <<<<
    "cor_af_actor": [
      {
        "id_acquisition_framework": 132,
        "id_cafa": 251,
        "id_nomenclature_actor_role": 359,
        "id_organism": 5,
        "id_role": null,
        "nomenclature_actor_role": {
          "active": true,
          "cd_nomenclature": "1",
          "definition_default": "Contact principal",
          "definition_fr": "Contact principal",
          "hierarchy": "109.001",
          "id_broader": 0,
          "id_nomenclature": 359,
          "id_type": 109,
          "label_default": "Contact principal",
          "label_fr": "Contact principal", <<<<
          "mnemonique": "Contact principal",
          "source": "SINP",
          "statut": "Valid\u00e9"
        },
        "organism": {
          "additional_data": {},
          "adresse_organisme": "",
          "cp_organisme": "",
          "email_organisme": "",
          "fax_organisme": "",
          "id_organisme": 5,
          "nom_organisme": "CD", <<<<
          "tel_organisme": "",
          "url_logo": "",
          "url_organisme": "",
          "uuid_organisme": "50c99251-d546-4e86-ba26-880b20473233",
          "ville_organisme": ""
        },
        "role": null
      }
    ],
    "creator": {
      "active": true,
      "date_insert": "2021-12-01T16:39:55.523486",
      "date_update": "2023-01-23T11:15:04.280222",
      "desc_role": null,
      "email": "elie.bouttier@ecrins-parcnational.fr",
      "groupe": false,
      "id_organisme": -1,
      "id_role": 3,
      "identifiant": "admin",
      "nom_complet": "Administrateur test",
      "nom_role": "Administrateur",
      "prenom_role": "test",
      "remarques": "utilisateur test \u00e0 modifier"
    },
    "cruved": {
      "C": true,
      "D": true,
      "E": true,
      "R": true,
      "U": true,
      "V": true
    },
    "ecologic_or_geologic_target": null,
    "id_acquisition_framework": 132, <<<<
    "id_digitizer": 3,
    "id_nomenclature_financing_type": 383,
    "id_nomenclature_territorial_level": 357,
    "initial_closing_date": null,
    "is_parent": false,
    "keywords": null,
    "meta_create_date": "2023-01-30T12:29:04.950301",
    "meta_update_date": null,
    "opened": true,
    "t_datasets": [
      {
        "active": true,
        "bbox_east": null,
        "bbox_north": null,
        "bbox_south": null,
        "bbox_west": null,
        "cor_dataset_actor": [
          {
            "id_cda": 285,
            "id_dataset": 150,
            "id_nomenclature_actor_role": 359,
            "id_organism": 5,
            "id_role": null,
            "nomenclature_actor_role": {
              "active": true,
              "cd_nomenclature": "1",
              "definition_default": "Contact principal",
              "definition_fr": "Contact principal",
              "hierarchy": "109.001",
              "id_broader": 0,
              "id_nomenclature": 359,
              "id_type": 109,
              "label_default": "Contact principal",
              "label_fr": "Contact principal",
              "mnemonique": "Contact principal",
              "source": "SINP",
              "statut": "Valid\u00e9"
            },
            "organism": {
              "additional_data": {},
              "adresse_organisme": "",
              "cp_organisme": "",
              "email_organisme": "",
              "fax_organisme": "",
              "id_organisme": 5,
              "nom_organisme": "CD",
              "tel_organisme": "",
              "url_logo": "",
              "url_organisme": "",
              "uuid_organisme": "50c99251-d546-4e86-ba26-880b20473233",
              "ville_organisme": ""
            },
            "role": null
          },
          {
            "id_cda": 286,
            "id_dataset": 150,
            "id_nomenclature_actor_role": 364,
            "id_organism": 5,
            "id_role": 144,
            "nomenclature_actor_role": {
              "active": true,
              "cd_nomenclature": "6",
              "definition_default": "Producteur du jeu de donn\u00e9es",
              "definition_fr": "Producteur du jeu de donn\u00e9es",
              "hierarchy": "109.006",
              "id_broader": 0,
              "id_nomenclature": 364,
              "id_type": 109,
              "label_default": "Producteur du jeu de donn\u00e9es",
              "label_fr": "Producteur du jeu de donn\u00e9es",
              "mnemonique": "Producteur du jeu de donn\u00e9es",
              "source": "SINP",
              "statut": "Valid\u00e9"
            },
            "organism": {
              "additional_data": {},
              "adresse_organisme": "",
              "cp_organisme": "",
              "email_organisme": "",
              "fax_organisme": "",
              "id_organisme": 5,
              "nom_organisme": "CD",
              "tel_organisme": "",
              "url_logo": "",
              "url_organisme": "",
              "uuid_organisme": "50c99251-d546-4e86-ba26-880b20473233",
              "ville_organisme": ""
            },
            "role": {
              "active": true,
              "date_insert": "2023-01-30T12:25:02.136422",
              "date_update": "2023-01-30T16:13:56.723392",
              "desc_role": null,
              "email": "lafartre@gmail.com",
              "groupe": false,
              "id_organisme": 5,
              "id_role": 144,
              "identifiant": "anddupont58",
              "nom_complet": "Dupont Andr\u00e9",
              "nom_role": "Dupont",
              "prenom_role": "Andr\u00e9",
              "remarques": ""
            }
          }
        ],
        "cruved": {
          "C": true,
          "D": true,
          "E": true,
          "R": true,
          "U": true,
          "V": true
        },
        "dataset_desc": "test",
        "dataset_name": "Donn\u00e9es collect\u00e9es par le CD",
        "dataset_shortname": "CD58",
        "id_acquisition_framework": 132,
        "id_dataset": 150,
        "id_digitizer": 3,
        "id_nomenclature_collecting_method": 396,
        "id_nomenclature_data_origin": 76,
        "id_nomenclature_data_type": 323,
        "id_nomenclature_dataset_objectif": 422,
        "id_nomenclature_resource_type": 321,
        "id_nomenclature_source_status": 73,
        "id_taxa_list": 106,
        "keywords": null,
        "marine_domain": false,
        "meta_create_date": "2023-01-30T12:33:01.135912",
        "meta_update_date": "2023-02-07T18:25:57.881731",
        "terrestrial_domain": true,
        "unique_dataset_id": "33b4e4eb-7281-4a17-af26-5f6f7834927b",
        "validable": true
      }
    ],
    "target_description": null,
    "territory_desc": null,
    "unique_acquisition_framework_id": "6b958e3c-5825-4e2c-a14d-1e54f40432c1" <<<<
  }
```

**Comment by mvergez** [comment]
Je suis d'accord avec toi @lpofredc, il faudrait limiter les données renvoyées par l'API au maximum. Cela pose question de la gestion des `fields` de manière globale dans GeoNature et pas que dans le module métadonnées. Cela pose aussi question du point de vue utilisateur de l'api en brut : comment savoir quels sont ces fields ? On renvoie tout par défaut et c'est le front qui filtre ?

J'avais écrit une issue sur les bonnes pratiques Rest (#2273), peut-être faudrait-il en ouvrir une pour les `fields` ? 

Merci pour tes retours en tout cas !

**Comment by bouttier** [comment]
J’ai pas d’opposition de principe à ce qu’on essaye d’alléger la taille des réponses de l’API, mais ça me semble pas du tout la priorité.

C’est globalement la logique de graphql de permettre au frontend de spécifier les champs qu’il souhaite que le backend lui renvoi. Sauf que :
- Il y a beaucoup de temps à passer pour déterminer la liste précise des champs à récupérer
- Récupérer 30 champs au lieu de 200, quand on récupère 10k JDD, ça ne change pas le problème qui est qu’il ne faut pas récupérer tous les JDD en premier lieu → l’optimisation de la liste des champs n’est pas la priorité
- On est pas outillé pour cela. Certain ont, dans leur vue, passé directement à ``as_dict`` l’argument ``fields`` fournit par le front. Très mauvaise pratique car on peut alors demander n’importe quoi, y compris des informations auxquelles on est pas censé pouvoir accéder. Il faudrait donc avoir des outils adaptés permettant de spécifier une liste de champs disponible, et de vérifier que les champs demandé par le frontend sont bien autorisé.

Un tel outillage est un pré-requis à ce type d’optimisation. Ce n’est pas un travail énorme que de se munir d’une telle boite à outil, mais ce n’est pas ma priorité, dans la mesure où on a des problèmes de performance bien plus majeur (récupération de *tous* les JDD, comptage de toutes les observations de la synthèse, …).

**Comment by bouttier** [comment]
Requête pour récupérer pour chaque CA le nombre de JDD ainsi que le nombre de JDD qui correspond au filtre de recherche :
```
from geonature.core.gn_meta.models import TAcquisitionFramework, TDatasets


DS1 = sa.orm.aliased(TDatasets)
DS2 = sa.orm.aliased(TDatasets)

TAcquisitionFramework.query.with_entities(
    TAcquisitionFramework.id_acquisition_framework
).join(DS1).outerjoin(DS2).add_columns(
    func.count(sa.distinct(DS1.id_dataset)).label("matching_ds_count"),
    func.count(sa.distinct(DS2.id_dataset)).label("total_ds_count"),
).filter(
    sa.or_(
        TAcquisitionFramework.acquisition_framework_name.ilike("%Test%"),
        DS1.dataset_name.ilike("%dataset%"),
    )
).group_by(
    TAcquisitionFramework.id_acquisition_framework
).all()
```

**Comment by bouttier** [comment]
Afin de procéder itérativement, une première PR couvrira le scope fonctionnel suivant :
- la recherche rapide devient une recherche générique côté backend
- les JDD sont récupéré à la demande

La remonté du nombre de JDD qui match et du nombre de JDD total lors de la récupération des CA ne fera pas partie de cette première itération. En conséquence, le front ne sera pas capable de savoir s’il doit ou non transmettre les filtres de recherche lors de la récupération des JDD. Comme solution de contournement en attendant, le front transmettra les filtres de recherche lors de la récupération des JDD dans tous les cas. Le backend devra préalablement vérifier si les filtres match le CA, et si c’est le cas, il renverra l’ensemble des JDD sans appliquer les filtres. Cette vérification préalable pourra être retiré dans le futur lorsque le front gérera l’envoie des filtres de recherche uniquement lorsque nécessaire.

**Comment by camillemonchicourt** [comment]
- Chargement des JDD à la demande fait dans https://github.com/PnX-SI/GeoNature/pull/2336
- Recherche rapide côté serveur (backend) : https://github.com/PnX-SI/GeoNature/pull/2336

**Comment by camillemonchicourt** [comment]
Fait dans la 2.12.0.
La partie pagination de la liste côté backend pour être une amélioration complémentaire, à traiter dans un ticket dédié.
