### ISSUE TITLE
[Carte] Améliorer la robustesse de la recherche OpenStreetMap et restreindre sur certains pays

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature#2010]
Bonjour,

Suite à des discussions avec l'ARB Ile de France, il a été remonté des problèmes avec la recherche OpenStreetMap sur la carte. En effet, il y avait une erreur du type "Invalid bounds" quand on cliquait sur certains résultats de la recherche. 

Cela est dû aux résultats d'OpenStreetMap qui contiennent ou non l'attribut `geojson`.

Je vais faire une PR qui :
- corrige ce problème en vérifiant que l'attribut `geojson` existe sinon prend l'attribut `boundingbox`
- ajoute un paramètre en configuration pour permettre de restreindre sur certains pays, comme le mentionne la [documentation OpenStreeMap](https://nominatim.org/release-docs/latest/api/Search/#result-limitation). Cela pourrait permettre une meilleure expérience utilisateur et ne pas avoir trop de résultats.

J'espère que cela vous conviendra

**Comment by camillemonchicourt** [comment]
Oui intéressant.

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.10.0, mais paramètre vide par défaut.
