### ISSUE TITLE
CONTACT - Formulaire saisie Taxons

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#203]
- [x] La liste renvoyée se base sur `bib_noms`. 
- [x] Un seul champ concatène nom vernaculaire et nom latin
- [x] Nom latin affiché en italique
- [x]  Requête lancée en Ajax au bout d'un certain nombre de lettres (paramétrable) car la liste peut être très dense (tout taxref)
- [x] Nombre d'éléments renvoyés paramétrable
- [x] Ordre des résultats ? 
- [x]  possibilité de rechercher les première lettres de l'espèce puis de la sous-espèce.

**Comment by camillemonchicourt** [comment]
Remarques @DonovanMaillard sur le formulaire : 

- Basculer Technique observation dans Observation (voir #205)
- Renommer "Commentaire" du bloc RELEVE en "Informations sur le relevé" car sinon les gens vont y saisir leur commentaire taxon
- Taxon à mettre sur une ligne entière
- Griser le reste des champs du bloc TAXON tant que le taxon n'a pas été choisi
- Avancé à basculer en fin du bloc TAXON
- Mettre le Commentaire dans le bloc Avancé, masqué par défaut
- Naturalité à gérer au niveau du taxon et non pas de l'occurrence, sinon ça sera très souvent mal renseigné
- Clarifier le bloc Denombrement car actuellement, on dirait que le bouton + ajoute le taxon au relevé
- Liste des taxons saisis, ne pas afficher l'observateur car on a cette info au niveau du bloc RELEVE commun, mais plutôt afficher Taxon, Methode+Technique (pour visualiser des eventuelles erreurs de saisie) et dénombrement total

**Comment by sig-pnrnm** [comment]
Serait-il envisageable dans ce formulaire d'utiliser une autocomplétion basée sur les débuts de genre et début d'espèce ?
Exemple : je saisis "`po ve`", il me propose "`Pouillot véloce`", ou je saisis "`d rot`", il me propose "`Drosera rotundifolia`".
C'est très apprécié de beaucoup de naturalistes que je fréquente, et ce dans différents outils (Visionature entre autres).

L'intérêt principal est que ça évite d'avoir à saisir le nom de genre en entier (la plupart du temps, 3 lettres suffisent pour tomber sur l'espèce recherchée).

**Comment by camillemonchicourt** [comment]
Oui c'est déjà fait.

**Comment by sig-pnrnm** [comment]
> Oui c'est déjà fait.
Cooool ! :) 👍
