### ISSUE TITLE
[Métadonnées] Les fiches PDF des jeux de données ne remontent pas les acteurs/contacts

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#2034]
**Version**
2.9.2

**Description du bug**
Lors de l'export des fiches JDD, la section "contacts" reste vierge dans les PDF (reproduit sur l'instance de démo)

**Comportement attendue**
Récupérer la liste des contacts dans la fiche PDF d'un jeu de données

**Comment reproduire**
Exporter la fiche PDF d'un jeu de données

**Logs**
ras

**Comment by Gaetanbrl** [comment]
@DonovanMaillard où sont stockés les contacts ?

**Comment by DonovanMaillard** [comment]
Bonjour, 

Dans les deux tables de correspondances gn_meta.cor_acquisition_frameworks_actors et cor_datasets_actors, qui pointent vers le utilisateurs.bib_organismes et utilisateurs.t_roles pour identifier les personnes et structures liées aux métadonnées

**Comment by Gaetanbrl** [comment]
merci je suis en train de modifier la mécanique d'export PDF  des méta, je vais voir si je peux corriger l'absence de contact au passage.

**Comment by DonovanMaillard** [comment]
super merci :)

**Comment by Gaetanbrl** [comment]
Après rajout des infos dans le code de la route de génération des PDF pour les datasets : 

![image](https://user-images.githubusercontent.com/16317988/208889686-d7422075-d381-4422-8061-e5ec2d618d4e.png)
