### ISSUE TITLE
Map-list : Faire remonter les geométries selectionnées depuis le tableau

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#2036]
**Version**

2.9.2

**Description du bug**

Dans le composant map-list (par exemple dans occtax),
- Lors d'un click sur le tableau, l'object geographique correspondant peut être *caché* par une ou plusieurs geométries et être innacessible par un click sur la carte

**Comportement attendue**

Il faudrait pouvoir remonter cet object en haut de la pile

**Comment reproduire**
- Faire deux relevés sur un même point.
- Cliquer sur le tableau puis sur le point associé, pour un des deux, l'accès au point est impossible

** Solution**
 
Lors d'un click sur le tableau, 
- Ajouter un `layer.bringToFront()` lors du traitement de la geometrie correspondante

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.10.0
