### ISSUE TITLE
Techniques d'observation au relevé ou occurrence ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#205]
Dans le cadre du travail sur le MCD du Contact (https://github.com/PnX-SI/GeoNature/issues/183), on a eu un important débat sur les techniques d'observation (de CAMPAnule).

- SCÉNARIO 1 : on les associe au RELEVÉ et auquel cas on ne peut avoir qu'un relevé par technique d'observation
- SCÉNARIO 2 : on les associe à l'occurrence

La plupart du temps on n'utilise qu'une technique d'observation à la fois, sur un point donné. Mais avec le scénario 1 on ne peut pas faire un point avec des occurrences dans plusieurs groupes ou règnes.

Cela impacte aussi la logique de saisie et son interface : 

- Choix d'un groupe ou d'une technique d'observation ?
- Liste des groupes ou techniques d'observation limité par l'autre ?
- Pré-remplir/Limiter les différentes listes en fonction du groupe sélectionné initialement ou limiter en fonction du taxon sans choisir les groupes. 

Dans le cas du scénario 2, il faudra récupérer la valeur saisie pour la première occurrence pour ne pas avoir à la re-sélectionner dans la liste dans le cas d'un grand nombre d'observations avec la même technique.

**Comment by camillemonchicourt** [comment]
Aperçu de la V0 du formulaire : 

![contact-form-v0](https://user-images.githubusercontent.com/4418840/29589537-e39d7ee0-8795-11e7-8dfb-77911f8778ad.jpg)

**Comment by camillemonchicourt** [comment]
Plus largement ça souleve aussi la question si les techniques d'obs doivent etre limitees dans certains modules pour ne pas en proposer certaines qui ne pourraient etre choisies dans le Contact mais etre utilisees dans d'autres protocoles. Voir aussi, potentiellement lié : https://github.com/PnX-SI/GeoNature/issues/202

**Comment by camillemonchicourt** [comment]
Point de vue @DonovanMaillard : 

- Sur un pointage, pouvoir saisir plusieurs groupes, plusieurs méthodes, plusieurs techniques
- Ne pas contraindre la liste des taxons en fonction des techniques mais l'inverse
- Si on a un campagnol ou un lézard dans une observation par piège Barber, on le gère en commentaire ou alors libre à chacun d'ajouter des groupes à une technique d'obs
- Disposer ensemble les champs technique d'observation et méthode d'observation dans la saisie car ça va ensemble. 
- Faciliter la saisie dans le cas d'un grand nombre de données avec la même technique (en récupérant la technique du taxon précédent par exemple) mais aussi la méthode

**Comment by camillemonchicourt** [comment]
On retient ces propositions et on passe les Techniques d'observation dans la table de l'observation d'un taxon, avec la méthode d'observation.

**Comment by gildeluermoz** [comment]
done

**Comment by camillemonchicourt** [comment]
Après réflexion, travail sur le standard METADONNEES et discussion avec les chargés de mission, la technique d'observation devrait plutôt s'attacher au JEU DE DONNEES.

**Comment by camillemonchicourt** [comment]
Bon éternel question de où on met cette technique d'observation. 
Les dernières discussions penchaient pour les associer au RELEVE.

**Comment by camillemonchicourt** [comment]
Rebasculé au niveau du RELEVE
