### ISSUE TITLE
Arrêt du support des modules non packagés avec GeoNature 2.11

### ISSUE THREAD

**Issue by bouttier** [PnX-SI/GeoNature#2058]
Avec GeoNature 2.7.5 a été introduit le support des modules packagés, c’est-à-dire installable grâce à un fichier ``setup.py`` et dont le schéma de base de données est géré par une branche Alembic. À titre d’exemple, les modules du cœur de GeoNature ont été packagés.

Actuellement, les modules « legacy », qui ne possède pas de ``setup.py`` mais un fichier ``manifest.toml`` sont encore supporté par GeoNature.

Dans la version 2.11 de GeoNature, les modules « legacy » ne seront plus supportés et tous les modules devront obligatoirement être packagé. Ceci est notamment une étape nécessaire pour une Dockerisation propre et efficace de GeoNature.

Si vous avez connaissance de module non-packagé, vous pouvez l’indiquer ici afin que l’on s’assure qu’ils l’ont bien été avant de sortir la version 2.11 de GeoNature.

**Comment by antoinececchimnhn** [comment]
Excellente nouvelle ! 

Dashboard ne l'est pas encore offciellement, il y a toutefois une PR ouverte sur le sujet https://github.com/PnX-SI/gn_module_dashboard/pull/45

**Comment by DonovanMaillard** [comment]
Merci ! Je vérifierai ce point sur le module cmr en cours de développement :) à mon avis il n'est pas packagé à ce stade, ça sera dinc une correction à anticiper dans le lot des développements restants.

**Comment by camillemonchicourt** [comment]
Voir aussi https://github.com/PnX-SI/GeoNature/issues/1272 pour plus de détail sur le packaging des modules, ainsi que le template de module : https://github.com/PnX-SI/gn_module_template

Exemples de packaging de modules : 
- https://github.com/PnX-SI/gn_module_dashboard/pull/45/commits/1ac9c6bbb5437ec6f96228afcd223d5740edfb26
- https://github.com/PnX-SI/gn_module_export/pull/107/files
- https://github.com/PnX-SI/gn_module_import/commit/0f81b19c9c78417026cfcc4355b089aed97f6228

**Comment by camillemonchicourt** [comment]
Les modules communs (Export, Import, Monitoring et Dashboard) sont disponibles dans des versions packagées.
