### ISSUE TITLE
Préfixer les schemas BDD

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#206]
Autre question globale sur le MCD de GeoNature, on a de plus en plus de schémas globaux (`taxonomie`, `medias`, `meta`, `synthese`...) et en même temps de plus en plus de schémas de protocoles ou données sources de partenaires. 

Pour faciliter la lisibilité et les regrouper, je préfixerai bien tous les schémas qui concernent des protocoles avec des données sources. 

Par exemple avec `p` pour protocole ou `ds` pour données source. 

- ds_contactfaune
- ds_contactflore
- ds_florestation
- ds_historique
- ds_cbna
- ds_silenepaca
.....

**Comment by camillemonchicourt** [comment]
On retient `pr_` pour les différents protocoles, `pa` pour les données partenaires, `ref` pour les référentiels, `gn` pour le cœur de GeoNature : 

- gn_medias
- gn_meta
- gn_synthese
- ref_users (nécessite modification UsersHub)
- ref_nomenclature
- ref_taxonomy (nécessite modification de TaxHub d'abord et attention à GN-atlas à mettre en cohérence)
- ref_geographic
- pr_contact
- pr_flora_station
- pr_chiro_monitoring
- pa_cbna
- .....

**Comment by gildeluermoz** [comment]
Les conventions de nommage pour  les protocoles qui n'existe pas encore ne peuvent pas être mise en place.
Les modifications du nom des schémas taxonomie et utilisateurs sont extrêmement impactantes pou rles SI en place. Je les déplace dans 2 nouveaux tickets.
