### ISSUE TITLE
[OCCTAX] - Mise à jour d'un relevé à période de date 

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#2071]
Salut,
Je ne l'ai pas testé sous develop, mais en 2.9.2 quand j'édite un relevé qui a une date_min <> date_max, la date max prend la valeur de la date_min dans le formulaire.

Je suspecte un problème sur l'observable en dessous, mais il faut tester sous develop (ce que, en l'état, je ne peux pas faire)

https://github.com/PnX-SI/GeoNature/blob/7c722aa6ee7774e0acbfbfef4ee58072a54c08a8/contrib/occtax/frontend/app/occtax-form/releve/releve.service.ts#L294-L310

**Comment by jbrieuclp** [comment]
Ok... Je ne reproduis pas en dev de 2.9.2 x_x

**Comment by jbrieuclp** [comment]
Bon... Reproduit sur le serveur de demo en 2.11, j'vais voir ce qu'il se passe !

**Comment by camillemonchicourt** [comment]
Enfin si, parfois je reproduis

**Comment by TheoLechemia** [comment]
C'est la 20ème fois que ce truc pète, et il est censé y avoir un test dessus...
Est-ce que ça te vas si on utilise cette fonction https://github.com/PnX-SI/GeoNature/blob/master/frontend/src/app/GN2CommonModule/form/form.service.ts#L129 . On ne l'active QUE si on est en création et pas en édition.
Cette fonction est déjà utilisé dans Occhab, comme ça on utilise le même truc partout

**Comment by TheoLechemia** [comment]
Ok effectivement, il y a un paramètre pour ne pas remplir la valeur par défaut avec le date du jour.
Bref peu importe, je serais pour utiliser la même fonction partout en modifiant l'algo de cette fonction. Et de ne déclencher cette fonction que si on est pas en mode édition. Avec le `emitEvent = false`, j'ai un peu peur qu'on ne comprenne pas le pourquoi du comment et que le problème revienne

**Comment by TheoLechemia** [comment]
Bon j'ai essayé de reprendre les deux observables que tu avais écris pour en faire une fonction générique utilisable partout et je trouve deux problèmes : 
- si on utilise cette fonction dans un service ou alors dans un hook qui suit la création du formulaire, on rate le premier "valueChange" de la date_min qui initialise le formulaire à `null`, et donc on ne passe pas dans le `pairwise`, donc le premier changement de date_min ne synchronise pas `date_max`, et donc par la suite `date_min != date_max`, donc plus de synchro.
- autre soucis, si on utilise l'input `defaultToday` sur le composant "date",  alors on initialise d'abord `date_min` et `date_max` avec la date du jour, ensuite les valeurs de l'API arrivent, donc on change la date avec les valeurs du relevé. Si la date max du relevé est la date du jour, alors la date_min précédente est égale à la date_max précédente, donc on change la date_max par la valeur de date_min -> bug

=> proposition : on n'associe plus la synchronisation des dates aux événements déclenché pas le `formcontrol.valueChanges` car ceux-ci sont déclenché à la fois par des `patchValue` de l'API que des changements manuels par l'utilisateur. La synchronisation des dates est uniquement déclenché par un événement manuel de l'utilisateur (selection sur le date picker ou changement direct de la date sur l'input), qui est elle même déclenché par le nouvel `output` `onSelectOrKeyIn` du composant date

**Comment by jbrieuclp** [comment]
Le problème initiale provient du fait que l'observable du date_min set le date_max en envoyant l'info du changement, l'observable du date_max se lançait alors à son tour pour setter le date_min en envoyant l'info du changement, l'observable du date_min se lanç... etc. etc. Jusqu'à ce que les valeurs se stabilisent et que ne correspondent plus au filter qui stoppait l'emballement.
Le fait de spécifier comme option {emitEvent: false} empêche cet emballement. On souhaite observer une action de l'utilisateur et non quand la valeur est settée dynamiquement. Du coup, en tout cas sur les dates, il est nécessaires de bloquer l'emitEvent quand la valeur est settée automatiquement.

**Comment by jbrieuclp** [comment]
Pour ton premier problème si tu forces une valeur de déclenchement à null ou defaultToday par startWith(ENABLE_DEFAULT_TODAY ? defaultToday : null) dans le pipe ca ferait le job ?

Pour le second soucis je ne vois pas d'où il provient, distincUntilChanged ne déclenche rien si c'est la même valeur et le date_min est setté que s'il est vide. 🤔

**Comment by TheoLechemia** [comment]
> Pour ton premier problème si tu forces une valeur de déclenchement à null ou defaultToday par startWith(ENABLE_DEFAULT_TODAY ? defaultToday : null) dans le pipe ca ferait le job ?

oui ça peut marcher... mais comme je disais plus haut, il y a un problème de logique plus globale, d'ou ma volonté de ne plus passer par les `valueChanges`.
Nous ce qu'on veut c'est uniquement synchroniser les dates quand l'utilisateur les changent manuellement. Hors le `valueChanges` est déclenché aussi quand on le patch via l'API. Ce qui nous amenait à faire plein de vérification : si max est null, si les valeurs sont égales, vérifier qu'on a bien mis une valeur au début sinon le `pairwise` n'est pas déclenché etc etc... ça fait pleins de trucs à vérifier et c'est pour ça que le truc a pété pleins de fois.
La on vérifie uniquement si le `date_max` est pristine, si oui on le MAJ, sinon on ne le touche pas. (idem pour le `date_min`)
