### ISSUE TITLE
Générer automatiquement ID permanent SINP

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#209]
Voir http://standards-sinp.mnhn.fr/faq-identifiant-permanent/
Et https://inpn.mnhn.fr/docs/standard/sinp_identifiantpermanent.pdf

**Comment by gildeluermoz** [comment]
Première proposition de mise en place. Le contenu est modifiable.

**Comment by camillemonchicourt** [comment]
Le SINP a décidé de simplifier et de se limiter au UUID sans le préfixer de l'URL de la plateforme. 
Du coup les modifications ont été faites dans la BDD : https://github.com/PnX-SI/GeoNature/blob/frontend-contact/data/modules/contact/contact.sql#L145

`unique_id_sinp uuid NOT NULL DEFAULT public.uuid_generate_v4()`

**Comment by gildeluermoz** [comment]
reste à supprimer les entrées à ce propos dans ``gn_meta.t_parameters``.
Je préfère que Théo le fasse en lien avec l'usage éventuel des id_parameter correspondant dans le front.
C'est là https://github.com/PnX-SI/GeoNature/blob/frontend-contact/data/core/meta.sql#L571

**Comment by camillemonchicourt** [comment]
Les évolutions de l'ID permanent proposés par le GT Architecture du SINP sont détaillées dans la note : http://www.naturefrance.fr/sites/default/files/fichiers/ressources/pdf/note_identifiant_sinp_1.pdf

**Comment by gildeluermoz** [comment]
De mon point de vu tout est en place sur ce point.
Camille si tu n'a rien de particulier en tête on peut fermer ce ticket.
On en ouvre un autre ou on le réouvre si qq détails à corriger.

**Comment by camillemonchicourt** [comment]
OK en effet les références ont été supprimées de `gn_meta.t_parameters`
