### ISSUE TITLE
nvm v16.13 not found

### ISSUE THREAD

**Issue by Gaetanbrl** [PnX-SI/GeoNature#2096]
**Version**
develop
ref #2094

**Description du bug**
Le tag `v16.13` de release Node.js du fichier `frontend/.nvmrc` n'existe pas. C'est le tag `v16.13.0` qui permet à NVM d'installer la bonne version.

https://nodejs.org/fr/download/releases/

![image](https://user-images.githubusercontent.com/16317988/199062356-f33c85fa-70b2-4c96-b7c2-7eb7e335af39.png)

https://github.com/PnX-SI/GeoNature/blob/8c105340915fa87bb803045e1b1a18513f24a0a3/install/05_install_frontend.sh#L101

https://github.com/PnX-SI/GeoNature/blob/8c105340915fa87bb803045e1b1a18513f24a0a3/frontend/.nvmrc#L1

**Comportement attendue**
Installer la version à partir du fichier `.nvmrc`.

**Comment reproduire**
Suivre les étapes du fichier install_all.sh (plus particulièrement 05_install_frontend.sh).

**Logs**

ERREUR 

```
geonatureadmin@debian:~/geonature/frontend$ nvm install
Found '/home/geonatureadmin/geonature/frontend/.nvmrc' with version <v16.13>
Version 'v16.13' not found - try `nvm ls-remote` to browse available versions.
```

SUCCES

```
geonatureadmin@debian:~/geonature/frontend$ nvm install
Found '/home/geonatureadmin/geonature/frontend/.nvmrc' with version <v16.13.0>
Downloading and installing node v16.13.0...
Downloading https://nodejs.org/dist/v16.13.0/node-v16.13.0-linux-x64.tar.xz...
########################################################################################################################################## 100,0%
Computing checksum with sha256sum
Checksums matched!
Now using node v16.13.0 (npm v8.1.0)
```

**Comment by bouttier** [comment]
Merci, corrigé : 92e2143f016859a4523e7cfd1a43c2b8eed3e947
