### ISSUE TITLE
Saisie de cadre d'acquisition parent

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#2097]
**Version**
2.10

**Description du bug**
Il n'est pas possible de saisir un CA parent, 
- le composant de selection des CA parent n'est accessible que quand le CA édité est lui même un CA parent (cela devrait être le contraire)
- l'api `/list/acquisition_frameworks` ne prend pas en compte le parametre `is_parent`

**Comportement attendue**
Pouvoir choisir un CA parent parmis ceux qui vérifient `is_parent = True` 

**Comment reproduire**
Essayer d'attribuer un ca parent

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.10.0
