### ISSUE TITLE
Problème de mot de passe contenant un caratère spécial ( caractère @ dans notre cas)

### ISSUE THREAD

**Issue by Eric-a-BRUNO** [PnX-SI/GeoNature#2112]
Version de GeoNature affectée par le bug. **2.10.0**

**Description du bug**
Le mot de passe défini pour le compte postgres de l'administrateur (compte geonatadmin par défaut) contient un @. Lorsque l'on veut ouvrir la page  GeoNature (../geonature/#/login?route=%2F) ou TaxHub (/taxhub/#!/taxref) ou usershub (../usershub/login ) on obtient pour les deux premiers une erreur de login pour la page usershub le message d'erreur "Service Unavailable - The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later." 
Ce problème semble similaire à celui évoqué dans https://github.com/PnX-SI/GeoNature/issues/1879 par geobrun on Jun 6
Remarque : si on remplace le caractère @ par le caractère _ cela fonctionne.
**Comportement attendu**
Le compte postgres d'administration geonature2db devrait supporter les caractères spéciaux dans le mot de passe administrateur GeoNature.

**Comment reproduire**
- mettre mot de passe geonatadmin sous la forme xxxxxxxxxx@xxxxxxxxxxx
- faire un systemctl restart usershub
- usershub ne fonctionne plus...
- mettre mot de passe geonatadmin sous la forme xxxxxxxxxx_xxxxxxxxxxx
- faire un systemctl restart usershub
- usershub fonctionne à nouveau

**Logs**
Extrait du fichier ``/var/log/geonature.log`` dans le cas d’une erreur 500.

**Comment by camillemonchicourt** [comment]
Les caractères spéciaux fonctionnent mais seulement pas le `@`
C'est assez logique, car la connexion à la BDD utilise un `@` comme séparateur : https://github.com/PnX-SI/GeoNature/blob/master/config/geonature_config.toml.sample#L6
Donc si le password utilise un `@`, cela met le bazar dans cette chaîne de connexion.

Voir le sujet évoqué dans un autre projet si cela peut apporter des pistes : https://community.snowflake.com/s/article/Password-with-special-character-may-cause-authentication-failure-at-SQLAlchemy

**Comment by Eric-a-BRUNO** [comment]
Bonjour,
Pour info et complément : dans la "vieille" version 2.1.2 que nous utilisons cela fonctionne avec un mot de passe contenant un @ 
Et dans la 2.9.2 dont nous avons testé l'install avant de passer à la 2.10.0 cela fonctionnait aussi.

**Comment by camillemonchicourt** [comment]
Ah OK, je n'avais pas compris que le soucis était arrivé dans la 2.10, on va regarder du coup.

PS : A noter que la 2.10.0 était une pre-release et qu'elle avait quelques soucis, notamment au niveau de la mise à jour depuis une version 2.9.
Cela a été corrigé, ainsi que quelques autres points dans la version 2.10.1 que nous venons de publier.
Il faut donc passer directement sur la version 2.10.1.

**Comment by bouttier** [comment]
De ce que je comprend, il s’agit non pas d’un problème avec GeoNature mais avec UsersHub. Mais je ne comprend pas trop pourquoi il serait nouveau …
De ce que je comprend, le problème est « normal » : il faut échapper``@`` en le remplaçant par ``%40``. Est-ce que cela fonctionne en faisant cela ?

**Comment by bouttier** [comment]
Oui, dans le paramètre ``SQLALCHEMY_DATABASE_URI``, dans la configuration de GeoNature, de TaxHub et de UsersHub.

**Comment by camillemonchicourt** [comment]
Après modification de ces paramètres, il faut relancer les différents services : 
- sudo systemctl restart geonature
- sudo systemctl restart taxhub
- sudo systemctl restart usershub
- sudo systemctl restart geonature-worker

**Comment by bouttier** [comment]
Est-ce que cela a résolu le problème ?

**Comment by Eric-a-BRUNO** [comment]
Bonjour,
J'ai fait le test suivant sur notre version en cours :  GeoNature version 2.10.0

# remplacement du @ par %40 dans les fichiers :
/home/geonatureadmin/geonature/config/geonature_config.toml
/home/geonatureadmin/usershub/config/config.py
/home/geonatureadmin/taxhub/apptax/config.py

# Réactivation du mot de passe compte administrateur postgres contenant un @ 

# relance des différents services :
sudo systemctl restart geonature
sudo systemctl restart taxhub
sudo systemctl restart usershub
sudo systemctl restart geonature-worker

Vidage du cache du navigateur, au cas où et test d'ouverture des applis : 
https://mon_ip/geonature/#/login
https://mon_ip/usershub/login
https://mon_ip/taxhub/#!/taxref
Tout semble fonctionner nickel, les trois appli s'ouvrent et acceptent le loggin en 'admin'

Question : faudra-t-il faire cette manip lorsque nous migrerons vers la v 2.10.1 ou cela devrait-il fonctionner directement avec le compte avec mot de passe @  ?

Merci pour vos réponses !

**Comment by bouttier** [comment]
Le processus de migration récupère les fichiers de configuration existant, que vous avez donc déjà corrigez, il n’y aura rien à faire de plus !
Le problème étant résolu, je clos l’issue du coup.

**Comment by Eric-a-BRUNO** [comment]
Bonjour,
Je ne sais pas si cela peut aider mais j'ai retrouvé où j'avais dû résoudre ce problème de caractères spéciaux dans les mots de passe.
C'était pour l'import des médias depuis l'INPN via le script import_inpn_media au niveau du fichier : 
/home/geonatureadmin/taxhub/data/scripts/import_inpn_media/config.py

A l'époque j'avais résolu ainsi : 

"""
    FICHIER DE CONFIGURATION A ADAPTER A VOTRE BDD et aux CDREF que vous souhaitez enrichir de medias
"""
`# SQLALCHEMY_DATABASE_URI = "postgresql://USER:PASSWORD@HOST:PORT/DBNAME"`
`# la ligne ci-dessus pose un problème lorsque le mot de passe contient @ ou : `
`# on la remplace par :`
CON_DBNAME = "nom_de_la_db_gn2db"
CON_USER = "nom_du_user"
CON_PWD = "pass@user#1"
CON_HOST = "localhost"

**Comment by SamyM71** [comment]
Bonjour,
Même problème que @Eric-a-BRUNO à la différence que le mot de passe contient `%`.

**Comment by bouttier** [comment]
`%` → `%25`

Utiliser https://www.urlencoder.org/fr/ pour d’autres caractères spéciaux posant problèmes.
