### ISSUE TITLE
TSLint has been deprecated in favor of ESLint

### ISSUE THREAD

**Issue by Gaetanbrl** [PnX-SI/GeoNature#2113]
**Version**
develop

**Description du bug**

TSLint est identifié comme déprécié dans la roadmap TSLint : 

https://github.com/palantir/tslint/issues/4534
https://www.npmjs.com/package/tslint

C'est un point d'attention vu les dépendances du Frontend GeoNature :

https://github.com/PnX-SI/GeoNature/blob/ef3bc6680a3b96b7345ef8d225e8b3b5c3b6db05/frontend/package.json#L93-L94

**Comment by bouttier** [comment]
Hello,
On n’utilise plus ``tslint`` mais ``prettier`` : https://github.com/PnX-SI/GeoNature/blob/master/frontend/package.json#L9
Il y a une PR en attente qui fait ce nettoyage : https://github.com/PnX-SI/GeoNature/pull/2075/files#diff-da6498268e99511d9ba0df3c13e439d10556a812881c9d03955b2ef7c6c1c655L67

**Comment by Gaetanbrl** [comment]
super, c'est noté merci ;)
