### ISSUE TITLE
  `module_object` n'est pas défini dans app.py

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#2143]
https://github.com/PnX-SI/GeoNature/blob/73404f2cbb0a418c5701ec57627130b290df9a3a/backend/geonature/app.py#L200

 `module_object` n'est pas défini

remplacer `module_object.module_code` par `module_code` ?

**Comment by bouttier** [comment]
Merci, corrigé : c55a6c12489339a4a43226c1d1c8d325bfe63e44
