### ISSUE TITLE
[Occtax] [gn_occtax_mobile] Pouvoir ajouter des médias

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#2148]
# Pouvoir renseigner les médias avec l'api V1 des relevés occtax

Pour pouvoir gérer les médias dans l'application `occtax_mobile`

# Bug

L'api plante lorsque l'on cherche à ajouter les infos sur les médias

# Proposition

Modifier l'api pour prendre en compte les médias

## Piste

- Traiter les medias comme les observateur ou autres
- ou utiliser bien utiliser from_dict de utils_flaks_sqlalchemy, comme dans `gn_module_monitoring`
  
### Tests

- [x] créer une fixture avec des infos sur les médias
- [x] créer un test qui va appeler des api pour
  - [x] créer un media
  - [x] créer un relevé avec ce média
  - [ ] supprimer le releve
  - [ ] supprimer le media

### Occtax api v1

- [x] améliorer l'api
  - [x] faire comme ce qui est fait pour les observateur, occurrences, dénombrement
  - [x] ou bien utiliser from_dict (comme ce qui est fait dans `gn_module_monitoring`)
    - [x] optionel -> on peut choisir l'une ou l'autre méthode
    - [ ] a finaliser

**Comment by DonovanMaillard** [comment]
Bonjour, 

Pour Occtax-mobile on envisagerait de passer sur l'API V2 directement, pour  pouvoir ne pas conserver la V1.

**Comment by TheoLechemia** [comment]
Après discussion, il nous semble pas judicieux de continuer sur le fonctionnement actuel qui poste le médias dans un premier temps sans uuid de rattacherment pour l'updater dans un second temps via l'objet posté.
L'idée est de poster l'occurrence et ses dénombrements et d'attendre le retour de la route pour poster les médias avec les uuid nouvellement créé. Le retour JSON du backend garanti que l'ordre des dénombrements est le même que dans le JSON posté
TODO : 
- L'api POST /media ne doit plus permettre le post sans uuid de rattachement
- L'api POST /<id_releve>/occurrence ne doit plus contenir un tableau de médias
- le composant frontend "médias" ne doit plus poster directement quand on clique sur valider, mais renvoyer le média sous forme d'un output. Le composant parent se charger de stocker les médias créés. Au retour du POST de l'occurrence, il se charge de poster les médias en se basant sur l'ordre du JSON renvoyé et le tableau de médias qu'il a stocké.

Les changements en front sont assez conséquent et peuvent planifié dans un second temps. En l'état le mobile peut déjà poster les médias séparément à la suite du post des occurrences.

**Comment by joelclems** [comment]
Il faudra aussi adapter ça dans monitoring (occtax, monitoring (module, site, visite, observation, groupe de site).

le fonctionnement actuel permettait de pouvoir adapter la gestion des médias dans plusieurs situations car la partie fichier était gérée par le composant médias et sans devoir surcharger les composant et les routes autours (tout se passait dans la modélisation avec le lien sur uuid_attached_row)

il y a aussi une vérification du media lors du post avec le composant media

est ce qu'il ne serait pas possible de garder le fonctionnement actuel de pouvoir poster un media sans uuid de rattachement

cela n’empêchera pas de proposer de renseigner les médias une fois que le relevé a été crée (on peut donner des valeurs par defaut aux champs d'une liste de media donc un uuid_attached_row par defaut si le releve est déja crée)

**Comment by TheoLechemia** [comment]
Non l'idée n'est pas de surcharger les routes autours. Au contraire, la route /occurrence ne se soucie plus des médias. Pareil pour les composants, il peuvent utilisé un service "Medias" qui se charger de poster pour eux.
Le fonctionnement actuel qui est assez confortable je te l'accorde, n'est pas vraiment standard et assez peu lisible pour quiconque voudrait utilisé notre API... Et il permet aussi de créer des médias "orphelins" (si je ne POST pas après avoir créer N médias par exemple)
