### ISSUE TITLE
[Metadonnées] Importer dans ce jeux de données => Erreur 404

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/GeoNature#2151]
**Version**
2.10.3

**Description du bug**
Lorsque l'on clique sur l'action `Importer dans ce jeux de données` :  Il redirige vers la page :  `#/import/process/step/1?datasetId=335&resetStepper=true` qui n'existe pas

**Comment by bouttier** [comment]
Actuellement le bouton d’import est hardcodé dans GeoNature, peu importe que le module d’import soit installé ou non. C’est une très mauvaise pratique, et c’est bien pour ça que ce lien est cassé.
Je suis pour dans un premier temps supprimer ce bouton. Et le remettre mais avec un mécanisme permettant au module d’import, lorsqu’il est installé, de venir insérer son bouton dans le module met-adonnées.

**Comment by camillemonchicourt** [comment]
OK à voir car le projet DEPOBIO tenait à ce que ce bouton soit proposé depuis le module Métadonnées, mais en effet il ne devrait être présent que si le module Import est installé...

**Comment by antoinececchimnhn** [comment]
Effectivement de mon côté on me remonte que cette fonctionnalité est nécessaire pour les utilisateurs DEPOBIO

**Comment by camillemonchicourt** [comment]
Oui mais elle a été développée de manière non satisfaisante car en dur, même si le module IMPORT n'est pas installé. 🤔

**Comment by antoinececchimnhn** [comment]
Ce n'est cependant pas une régression introduite par la 2.10 ni la refonte de l'import. Pas de blocage de notre pour la faire évoluer je pense tant que la solution mise en place nous permet un déploiement en début de semaine prochaine ;)

**Comment by camillemonchicourt** [comment]
Oui c'était déjà le cas en effet dans les versions précédentes.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.10.4
