### ISSUE TITLE
Connexion impossible sur un autre domaine que celui de la configuration

### ISSUE THREAD

**Issue by bouttier** [PnX-SI/GeoNature#2161]
**Version**
2.10

**Description du bug**
Lorsque l’on se connecte sur par exemple ``localhost`` alors que ``127.0.0.1`` est renseigné dans la configuration (``URL_APPLICATION``), la route de login accepte de nous connecter mais on reste déconnecté car le cookie ne se trouve pas sur le bon domaine.

**Comportement attendue**
Cookie d’authentification à placer sur le domaine sur lequel est reçu la requête d’authentification.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.14.0
