### ISSUE TITLE
Erreur frontend dans le module validation

### ISSUE THREAD

**Issue by bouttier** [PnX-SI/GeoNature#2183]
**Version**
2.10 & develop

**Description du bug**
Il y a une erreur du frontend dans le module validation :
```
ERROR TypeError: this.table is undefined
    ngOnChanges validation-synthese-list.component.ts:243
    Angular 6
    ValidationComponent_Template validation.component.html:60
    Angular 27
    RxJS 5
    Angular 17
    webpackJsonpCallback jsonp chunk loading:77
    <anonymous> default-src_app_shared_syntheseSharedModule_synthese-shared_module_ts.js:2
```

**Comment reproduire**
Se rendre dans le module validation

**Comment by Gaetanbrl** [comment]
Je reproduis également avec blocage de l'application et le message : 

```
core.js:6498 ERROR TypeError: Cannot read properties of undefined (reading 'emptyMessage')
    at DatatableComponent_Template (swimlane-ngx-datatable.js:3941:544)
    at executeTemplate (core.js:9618:1)
    at refreshView (core.js:9484:1)
    at refreshComponent (core.js:10655:1)
```

**Comment by Gaetanbrl** [comment]
@bouttier pour le pas à pas :

[onTableClick()](https://github.com/PnX-SI/GeoNature/blob/develop/contrib/gn_module_validation/frontend/app/components/validation-synthese-list/validation-synthese-list.component.ts#L87)

[this.setSelectedObs()](https://github.com/PnX-SI/GeoNature/blob/develop/contrib/gn_module_validation/frontend/app/components/validation-synthese-list/validation-synthese-list.component.ts#L113)

[this.table // undefined](https://github.com/PnX-SI/GeoNature/blob/develop/contrib/gn_module_validation/frontend/app/components/validation-synthese-list/validation-synthese-list.component.ts#L213)

![image](https://user-images.githubusercontent.com/16317988/205586953-d379ed55-6165-40e9-a280-41140734455a.png)

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.11.0
