### ISSUE TITLE
Données d’exemple OccTax inséré dans la synthèse sans source

### ISSUE THREAD

**Issue by bouttier** [PnX-SI/GeoNature#2186]
**Version**
develop

**Description du bug**
Les données d’exemple d’OccTax (branche ``occtax-samples``) sont inséré dans la synthèse avec la colonne ``source`` à ``NULL``. En conséquence, les données n’apparaissent pas dans la synthèse (car jointure dans la vue ``v_synthese_for_web_app`` utilisé par la route ``for_web``) (mais apparaissent dans le module validation !).

Il serait sans doute pas mal, outre comprendre d’où vient ce soucis et le résoudre, de mettre une contrainte ``NOT NULL`` sur la colonne ``source`` de la synthèse.

**Comment by camillemonchicourt** [comment]
A mon souvenir, en 2.9 (et en 2.10 je crois) les données d'exemple étaient insérées dans Occtax et aussi affichées dans le module Synthèse.

A voir ce qui a changé et pourquoi.

Et en effet pour la contrainte sur la colonne id_source, ça serait une bonne chose.

**Comment by bouttier** [comment]
La colonne ``id_source `` est calculé à partir de ``id_module``, qui n’est pas fourni dans les données d’exemple ! Je l’ai rajouté, avec également une dépendance de la branche ``occtax-samples`` vers la révision qui rajoute la colonne ``id_module``.
Je vais rajouté un ``NOT NULL`` sur ``id_source`` dans la synthèse, mais également sur ``id_module`` dans OccTax.

**Comment by bouttier** [comment]
Je pense qu’on va intégrer ça à la 2.10 dans la mesure où l’id_source null fait planter le frontend donc l’impact est assez conséquent !

**Comment by camillemonchicourt** [comment]
Ok cela explique pourquoi ça fonctionnait avant la 2.10

**Comment by bouttier** [comment]
Finalement l’impact est assez limité :
- les données dans la synthèse ne s’affiche pas car on utilise la vue v_synthese_for_web_app qui fait un join sur la source, donc les doles données dans la synthèse ne s’affiche pas car on utilise la vue v_synthese_for_web_app qui fait un join sur la source, donc les données avec id_source = NULL ne remonte pas
- dans le module validation, les données sont présentes (car on utilise directement la table synthèse), mais si on regarde le détail de l’observation, on a un message dans la console javascript car on essaye d’afficher sans succès le nom de la source, cependant le front reste utilisable donc ça semble pas si critique.nnées avec id_source = NULL ne remonte pas dans le module validation, les données sont présentes (car on utilise directement la table synthèse), mais si on regarde le détail de l’observation, on a un message dans la console javascript car on essaye d’afficher sans succès le nom de la source, cependant le front reste utilisable donc ça semble pas si critique.

⇒ 2.11

**Comment by bouttier** [comment]
Si vous avez des données avec ``id_source = NULL`` dans la synthèse (dû aux données d’exemple), l’autoupgrade peut mal se passer si GeoNature (contrainte ``NOT NULL`` sur ``id_source``) est mis à jour avant OccTax. Dans ce cas, upgrader d’abord OccTax (``geonature db upgrade occtax@head``) puis relancer l’autoupgrade (``geonature db autoupgrade``).

**Comment by bouttier** [comment]
complété par #2210

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.11.0
