### ISSUE TITLE
Données d'install sans source

### ISSUE THREAD

**Issue by Gaetanbrl** [PnX-SI/GeoNature#2187]
**Version**
Develop

**Description du bug**
Les 3 observations disponibles à l'installation n'ont pas de source.
Cela provoque diverses erreurs dans la console et ne permet pas le bon fonctionnement du module /validation.

**Comportement attendue**

Ne pas afficher les observations sans source ?

**Comment reproduire**
1. install branche develop mode dev
2. Aller dans /synthese >> les observations ne sont pas présentes
3. Aller dans /validation
4. Afficher le détail d'une observation
5. Voir que la modal n'a pas un comportement normal

**Logs**
Extrait du fichier ``/var/log/geonature.log`` dans le cas d’une erreur 500.

**Proposition**

Ajouter un filtre dans le blueprint.py :

https://github.com/PnX-SI/GeoNature/blob/develop/contrib/gn_module_validation/backend/gn_module_validation/blueprint.py#L137

... pour avoir en plus  : 

> Synthese.id_source.isnot(None)

... tel que :

`query = query.filter(Synthese.the_geom_4326.isnot(None), Synthese.id_source.isnot(None)).order_by(Synthese.date_min.desc())
`

** capture **

Voici les sources des 3 obs avec 1 observation rajoutée via occtax : 

![image](https://user-images.githubusercontent.com/16317988/205352808-0d05a890-adf8-4571-882e-e99aa68eae42.png)

**Comment by bouttier** [comment]
Identique à #2186

**Comment by Gaetanbrl** [comment]
je clos cette issue @bouttier ca te va si identique à 2186  ?
