### ISSUE TITLE
MAJ GeoNature : liste des fichiers de conf à copier

### ISSUE THREAD

**Issue by MoulinZ** [PnX-SI/GeoNature#2190]
Je suis en train de faire le passage à GeoNature 2.10.4. Je cherche l'info des fichiers de conf à copier, qui n'est pas (plus ?) disponible sur la page https://docs.geonature.fr/installation.html#mise-a-jour-de-l-application. Je ne voudrais pas en oublier... Merci pour le retour !

**Comment by bouttier** [comment]
Bonjour Zacharie, quels fichiers de configuration avais-tu l’habitude de copier ? Le fichier de configuration de GeoNature est censé être récupéré automatiquement par le script de mise-à-jour : https://github.com/PnX-SI/GeoNature/blob/master/install/migration/migration.sh#L31

**Comment by MoulinZ** [comment]
Salit Élie, ah oui c'est ça le script fait tout lui-même, c'est la différence avec les maj de modules... Merci et désolé pour cette question bête ^^ peut être utile de le préciser dans la doc, si je suis pas le seul à me poser cette question. Bonne journée !
