### ISSUE TITLE
[2.9.1] performances sur les permissions - vue gn_permissions.v_roles_permissions

### ISSUE THREAD

**Issue by JulienCorny** [PnX-SI/GeoNature#2196]
Bonjour,

On a rencontré un souci de performance sur les permissions sur une instance GeoNature (2.9.1) qui a aboutit à un timeout pour la requete geonature/api/gn_commons/modules lors du login des utilisateurs avec les droits admin.

Plus précisément on s'est rendu compte que le souci vient de la requête de la bdd vers la vue gn_permissions.v_roles_permissions (dans _build_query_permission geonature/core/gn_permissions/tools.py). Etant donné que l'instance a beaucoup d'utilisateurs et modules installés, la vue gn_permissions.v_roles_permissions fait presque 200000 lignes. Or cette vue est requêtée pour chaque module pour lesquels le user a les droits, donc particulièrement long pour les users admin (> 30 secondes = timeout).

On a réglé le problème de performance temporairement en remplaçant la vue gn_permissions.v_roles_permissions par une vue matérialisée, mais c'est pas idéal car il faut la mettre à jour lorsque les droits sont modifiés (même si ça reste mieux que d'augmenter le timeout...).

Est-ce qu'une mise à jour de GeoNature vers 2.10.4 pourrait améliorer ce problème ? D'après https://github.com/PnX-SI/GeoNature/issues/2162, la vue gn_permissions.v_roles_permissions va être supprimée. c'est prévu pour la 2.11 ?

**Comment by camillemonchicourt** [comment]
Oui le soucis est identifié et c'est notamment pour cela qu'il est prévu de supprimer la vue ``v_roles_permissions``.
Travail prévu, mais non planifié.
Ça sera pas dans la 2.11.
