### ISSUE TITLE
[Home Content] Affichage carte 100 dernières observations

### ISSUE THREAD

**Issue by ch-cbna** [PnX-SI/GeoNature#2200]
**Version**
develop

**Description**
Suite à la PR #1881 qui consiste à agréger les observations par géométrie dans la synthèse et ajouter un mode d'affichage des observations par mailles, la carte présentant les 100 dernières observations dans la page d'accueil de GeoNature a été affectée.

![image](https://user-images.githubusercontent.com/102586824/206496437-476f7bb6-9f75-4631-86ed-3e56b8e8d9a0.png)

**Explication**
Cette carte repose sur 'MapService' qui n'est pas utilisé dans la synthèse, et qui n'a donc pas été modifié dans la PR #1881.

Cependant, les données affichées sur cette carte (accueil) sont requêtées à partir de la même route (/for_web) que les données de la synthèse.

La synthèse ne reposant pas sur 'MapService', dispose de son propre affichage. Suite à la PR #1881, les observations sont regroupées par géométries, et les circleMarker ont été remplacés par des markers affichant le nombre d'observations sur une même géométrie. 

![image](https://user-images.githubusercontent.com/102586824/206497582-a3bb54b4-b0b6-48c5-96b1-bee2ac736d82.png)

**Questionnements**
Cette PR étant sur le point d'être intégrée, il me semble pertinent de discuter du fonctionnement de la carte des 100 dernières observations sur la page d'accueil.

Souhaitez-vous que l'affichage des données de la synthèse et de la carte des 100 dernières observations (accueil) soit identique ? 

Si oui, cela implique de modifier 'MapService' afin qu'il fonctionne de la même manière que la synthèse.
Lorsqu'il y aura une observation sur une géométrie, la popup restera la même qu'actuellement : nom du taxon, date d'observation et observateur(s).
Lorsqu'il y aura plusieurs observations  sur une géométrie, il faudrait penser un autre mécanisme de popup pour pouvoir contenir tous les noms des taxons, dates et observateurs. Ce sujet est ouvert à propositions. On pourrait imaginer une liste ou encore un tableau...

Si non, l'affichage resterait sur l'ancien fonctionnement, c'est-à-dire avec des circleMarker et sans regroupement par géométrie. 
Cela implique de modifier à nouveau le webservice "/for_web" pour qu'il ne regroupe pas les géométries selon un paramètre qu'on lui passerait. 

Vous pouvez retrouver les modifications liées à la PR#1881 sur ma branche : https://github.com/ch-cbna/GeoNature/tree/feat/meshes

**Comment by bouttier** [comment]
Pour ma part, je pense que, en l’absence d’une liste qui permet de sélectionner l’ensemble des observations concerné lorsque l’on clique sur une géométrie (comportement de la synthèse), il est préférable de rester sur un affichage des observations une à une.

- Modification de la route ``for_web`` pour pouvoir sélectionner entre normal / groupé / maille
- Activer le clustering leaflet pour le MapService afin de pouvoir sélectionner individuellement chaque observation :

![2022-12-08-182808_1920x1080_scrot](https://user-images.githubusercontent.com/1125589/206522534-9c65de37-bc7e-4c3a-8722-0ecd22524185.png)

**Comment by camillemonchicourt** [comment]
Oui sur la HOME, je resterai simple sur l'affichage actuel.

**Comment by jpm-cbna** [comment]
De mon point de vue, l'affichage des observations une à une pose problème quand il y en a plusieurs sur le même point... Du coup, je pencherai plutôt pour l'affichage des infos dans la popup. L'utilisation d'une barre de scroll vertical pourrait résoudre le problème du nombre d'infos à afficher.

Au passage, je propose de rajouter 2 paramètres de config en plus de l'existant `DISPLAY_MAP_LAST_OBS`:
  - `DISPLAY_MAP_LAST_OBS_NUMBER (**integer**)`: permettant de modifier le nombre d'observation. La valeur 100 est beaucoup trop arbitraire et ne permet pas de satisfaire tous les cas de figure.
  - `DISPLAY_MAP_LAST_OBS_AREA` (**boolean**): permettant d'activer l'affichage par mailles. Ce qui résoud le problème des observations multiples sauf si on veut afficher toutes les observations d'une maille (plus complexe à gérer)... Si `true`, la valeur du paramètre de config `SYNTHESE.AREA_AGGREGATION_TYPE` sera utilisé pour déterminer le type de zonage pour le rendu. Une alternative serait de modifier le web service `/for_web` pour qu'il puisse récupérer le type de zonage à utiliser via l'URL.

Les paramètres de config entrant en jeu:
```properties
[FRONTEND]
    DISPLAY_MAP_LAST_OBS = true
    DISPLAY_MAP_LAST_OBS_NUMBER = 100
    DISPLAY_MAP_LAST_OBS_AREA = true
[SYNTHESE]
    AREA_AGGREGATION_TYPE = "M5"
```

**Comment by antoinececchimnhn** [comment]
![image](https://user-images.githubusercontent.com/90315145/207013049-44875cfb-08bf-4862-abc9-51673c794abf.png)
Il me semble que le comportement avec la popup qui scroll avait été adopté pour les instances déployant la branche floutage (cf screenshot)
