### ISSUE TITLE
Reprise accès public

### ISSUE THREAD

**Issue by antoinececchimnhn** [PnX-SI/GeoNature#2202]
Pour l'heure l'accès public à GeoNature fonctionne comme suit:

- Création d'un utilisateur et de son mot de passe
- Appel de la route de login avec le mot de passe de l'utilisateur en clair

Cette solution pose donc un soucis clair: N'importe qui peut s'amuser à changer le mot de passe. 

Nous proposons d'ouvrir une route `public_access` qui s'occuperait d'authentifier un utilisateur public sans avoir besoin de son mot de passe

**Comment by camillemonchicourt** [comment]
Depuis la version 2.10, le bouton permettant d'accéder à l'espace utilisateur est masqué pour l'utilisateur "public" : https://github.com/PnX-SI/GeoNature/issues/1844

Comme indiqué par @bouttier dans la PR (https://github.com/PnX-SI/GeoNature/pull/1845), il faudrait aussi que cela soit contrôlé niveau backend.

**Comment by antoinececchimnhn** [comment]
Ca n'empêche que d'avoir un mot de passe qui transite en clair n'est pas très propre. Et je rejoins Elie, cacher le bouton ne permet pas de garantir que le mdp ne sera pas modifié

**Comment by camillemonchicourt** [comment]
Oui clairement.

**Comment by camillemonchicourt** [comment]
Sur le sujet, voir aussi https://github.com/PnX-SI/GeoNature/pull/1653

**Comment by camillemonchicourt** [comment]
@VincentCauchois, ce changement nécessite aussi de revoir la doc sur cette partie - https://github.com/PnX-SI/GeoNature/blob/master/docs/admin-manual.rst#acc%C3%A8s-public

**Comment by camillemonchicourt** [comment]
Les paramètres actuels : 
```
# Configuration de l'accès sans authentication
[PUBLIC_ACCESS]
    PUBLIC_LOGIN = "user123456"
    PUBLIC_PASSWORD = "toto987654"
    ENABLE_PUBLIC_ACCESS = true
```
ont été remplacés par un paramètre unique ``PUBLIC_ACCESS_USERNAME`` où vous devez renseigné le login de votre utilisateur public.

Vous devrez donc modifier votre configuration de l'accès public si vous l'utilisiez, lors du passage à la version 2.11.
