### ISSUE TITLE
Prevent access to front-end URL "/user" for public user

### ISSUE THREAD

**Issue by VincentCauchois** [PnX-SI/GeoNature#2218]
**Version**
V 2.10

**Description du bug**.
Lorsque l'utilisateur est loggé en public-access, il peut accéder à l'URL "/user", et dès lors essayer de modifier ses informations.

**Comportement attendu**
L'utilisateur public ne doit pas pouvoir accéder à cette URL. Les autres utilisateurs, quant à eux, doivent toujours pouvoir y accéder.

**Comment reproduire**
Se connecter en tant qu'utilisateur public, et accès direct via URL "<GEONATURE_URL>/user".

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.11.0.
