### ISSUE TITLE
Doc sensibilité

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#2234]
quelques remarques concernant la doc traitant de la sensibilité : 

- dans son arborescence ici : https://docs.geonature.fr/admin-manual.html#gestion-de-la-sensibilite elle comporte des chapitres qui ne concernent pas que la sensibilité : fonctions, table transversales, triggers vers la synthèse, triggers dans la synthèse.

- cette doc est bien complète pour ce qui concerne la gestion du référentiel et de sa traduction vers la synthèse mais il manque une partie concernant l'usage fait par GN du contenu du champ id_nomenclature_sensitivity. En effet, ce champ a vocation a être utilisé pour dégradé la localisation des observations concernées mais on ne sait pas si c'est le cas par défaut (affichage en synthèse, export sinp par défaut du module export, éventuellement vue par défaut de l'atlas). Un petit mot sur le sujet en intro ou en conclusion me paraitrait utile.

**Comment by camillemonchicourt** [comment]
Bien vu, en effet il y a un soucis dans l'arborescence de la documentation, suite à l'intégration de la partie sur la SENSIBILITE.

Actuellement aucun usage n'est fait dans GeoNature, des infos liées à la sensibilité.
C'est un travail en cours, détaillé ici - https://github.com/PnX-SI/GeoNature/issues/1394

**Comment by gildeluermoz** [comment]
:+1:  Merci

**Comment by camillemonchicourt** [comment]
Correction ici - https://github.com/PnX-SI/GeoNature/commit/2935faf50162baf3df1f9345c01b0968ad20c23e

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.11.1
