### ISSUE TITLE
[GN 2.10] Dupplication d'Occtax : configuration du module dupliqué

### ISSUE THREAD

**Issue by JeromeMaruejouls** [PnX-SI/GeoNature#2244]
Bonjour à tous.
Je suis en train de tester les dernières nouveautés Geonat (v2.10.4 actuellement).
J'ai une question concernant la duplication d'Occtax pour créer un nouveau module : en suivant la documentation, j'ai réussi à dupliquer le module : tout fonctionne normalement, le module s'affiche et je peux saisir dans les JDD configurés.
Par contre, je n'arrive pas à configurer le formulaire pour choisir les champs spécifiques ou cacher certains autres : 
 - dans le fichier conf_gn_module.toml , on peut configurer les champs qui s'affichent dans occtax, mais j'ai l'impression que c'est commun à toutes les instances d'occtax.
 - dans l'interface ADMIN / Bibliothèque de champs additionnels, on peut rajouter des champs, mais lors de la sélection du module, je n'ai que le premier module d'OccTax dans la liste, et pas la seconde instance que je viens de créer. Une idée ?

Merci d'avance pour votre aide !

**Comment by TheoLechemia** [comment]
Bonjour,
Pour l'affichage/masquage des champs, c'est bien global à toute les "instances" Occtax.
Pour les champs additionnels, c'est un oubli dans la doc. Dans la conf GeoNature, il faut rajouter une section `ADDITIONAL_FIELDS` pour dire quels modules modules sont implémentés : 

```
[ADDITIONAL_FIELDS]
    IMPLEMENTED_MODULES = ["OCCTAX", "OCCTAX_DUPLIQUE"]
```

**Comment by JeromeMaruejouls** [comment]
Merci @TheoLechemia . En rajoutant le code [ADDITIONAL_FIELDS], j'arrive bien à rajouter des champs à mon module.

Du coup, si je comprends bien, lorsque l'on duplique Occtax, on obtient un module identique au module Occtax principal, mais avec des champs supplémentaires. Pas de possibilités aujourd'hui de modifier l'interface pour masquer certains champs (avec valeur par défault dans la bdd) ?

**Comment by TheoLechemia** [comment]
C'est ça

**Comment by JeromeMaruejouls** [comment]
Ok, merci ! Je ferme le ticket.

**Comment by camillemonchicourt** [comment]
Documentation complété : https://github.com/PnX-SI/GeoNature/commit/8e684fbfbdc97a392e9ae68947ffb03e98ab8a36
