### ISSUE TITLE
Installation Globale - Geonature 

### ISSUE THREAD

**Issue by naidinp** [PnX-SI/GeoNature#2256]
Bonjour à tous,

Je ne sais pas s'il faut ouvrir un ticket dans cette partie "Issues" mais le cas échéant je vais le transférer dans Discussions. 

Je rencontre un problème d'installation basique en suivant la documentation officielle : https://docs.geonature.fr/installation.html#installation-globale

ma config matérielle : serveur ovh vps avec 4Go RAM et 2 vCores et 80Go d'espace disque ; Debian 10 64bits

Le serveur est nouvellement installé avec la version Debian 10.

Mon problème est que l'installation bloque à ce niveau et il est bloqué depuis plus d'une heure :

> INFO  [alembic.runtime.migration] Will assume transactional DDL.
> Created temporary directory '/tmp/tmp_m8vy6y7'
> Downloading 'RefSensibiliteV15_20220331.zip'…
> Ajout de règles de sensibilité 'Référentiel sensibilité TAXREF v15 20220331'
> 24208 règles ajoutées
> INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
> INFO  [alembic.runtime.migration] Will assume transactional DDL.
> INFO  [alembic.runtime.migration] Running upgrade  -> 1715cf31a75d, Insert default French DEM (IGN 250m BD alti)
> INFO  [alembic.runtime.migration] Created temporary directory '/tmp/tmp06rvep61'
> INFO  [alembic.runtime.migration] Downloading 'BDALTIV2_2-0_250M_ASC_LAMB93-IGN69_FRANCE_2017-06-21.zip'…
> Processing 1/1: /tmp/tmpqxvonqiv/BDALTIV2_250M_FXX_0098_7150_MNT_LAMB93_IGN69.asc

..dois-je attendre ou recommencer l'installation ?

Merci pour votre aide.

**Comment by DonovanMaillard** [comment]
cette étape peut en effet être très longue, 4Go de RAM étant le minimum attendu en plus. Plus d'une heure ca devient long mais pas forcément alarmant à mon avis ;)

**Comment by naidinp** [comment]
Bonjour,

Merci pour votre réponse, je le laisse tourner … jusqu'au timeout!

**Comment by camillemonchicourt** [comment]
Oui l'intégration dans la base de données du modèle numérique de terrain national fourni par défaut peut être long.
Voir ne pas aboutir si les ressources du serveur sont saturées.

Il est possible de désactiver cette intégration dans le fichier de configuration de l'installation globale. Et d'intégrer votre propre MNT ensuite manuellement seulement sur le territoire.

PS : si c'est un nouveau serveur, dommage de ne pas être parti directement sur Debian 11.

**Comment by naidinp** [comment]
> 

Les ressources du serveur sont même pas à la moitié : 
proc : 53% 
mem : 0,34GB/3,76GB 

Effectivement je vais voir à la prochaine installation et désactiver cette intégration car je n'ai pas de MNT propre ; je suis en phase de découverte du produit afin de pouvoir comprendre le fonctionnement pour une future installation.

PS : prochaine installation sera sur une Debian 11 👍

**Comment by naidinp** [comment]
...effectivement, le maitre mot c'est .....patience !

Merci pour l'aide.

Belle soirée
