### ISSUE TITLE
Finir de traduire la BDD en anglais

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#227]
Une grosse partie est faite mais il reste encore des éléments. 
Quelques tables (comme t_programmes >> t_programs), des noms de champs, des contraintes, les VM, des fonctions. 

- [x] SENSIBILITE >>> SENSITIVITY

A passer en revue ou compléter la liste.

**Comment by camillemonchicourt** [comment]
Renommage en `t_programs` done.

**Comment by gildeluermoz** [comment]
j'ai aussi renommé organisme en organism + qq bricoles.
Refais un tour mais je ne vois plus grand chose à passer en Anglais au niveau table et champs de la base (hormis qq commentaires éventuellement).

**Comment by camillemonchicourt** [comment]
OK j'ai fait le tour, OK pour moi pour les schémas validés. 
On verra ref_geographical, gn_synthesis... en temps voulu, quand on bossera dessus.
