### ISSUE TITLE
MAJ - Doc d'import manuel 

### ISSUE THREAD

**Issue by Gaetanbrl** [PnX-SI/GeoNature#2271]
**Version**
- sup. égale 2.10

**Description du bug**
Dans un passé pas si loin, je suivais cette doc pour importer des données sans passer par le module d'import (je ne souhaite pas l'utiliser pour ce cas).

https://docs.geonature.fr/import-level-1.html?highlight=import#insertion-des-donnees-dans-la-synthese

Visiblement le champ `id_nomenclature_obs_meth` n'existe plus dans gn_synthese.synthese.

**Comportement attendue**

Import des données via la requête de la documentation.

**Comment reproduire**
1. Créer une table temporaire
2. Y ajouter  des données [INPN](https://inpn.mnhn.fr/accueil/recherche-de-donnees)
3. Ajouter un dataset

```
INSERT INTO gn_meta.t_datasets(id_acquisition_framework, dataset_name, dataset_shortname, dataset_desc, id_nomenclature_data_type, keywords, marine_domain, terrestrial_domain, active)
VALUES
(1, 'Données Faune 2008-2010', 'Faune 2008-2010', 'Données faune du PNE entre 2008 et 2010', 326, 'Faune, PNE', FALSE, TRUE, TRUE)

```
5. Insérer les nouvelles syntheses
([voir doc](https://docs.geonature.fr/import-level-1.html?highlight=import#insertion-des-donnees-dans-la-synthese))

**Logs**

```
ERROR: ERREUR:  la colonne « id_nomenclature_obs_meth » de la relation « synthese » n'existe pas
LINE 5:  id_nomenclature_obs_meth,
```

**Comment by Gaetanbrl** [comment]
Fonctionne avec ces requêtes dans l'ordre : 
-- 0 - connect to DB with PSQL

`\c geonature2db
`

**-- 1 create schema**

```
CREATE SCHEMA tmp_import_data;
GRANT USAGE ON SCHEMA tmp_import_data TO geonatadmin;
GRANT ALL ON SCHEMA tmp_import_data TO geonatadmin;
```

**-- 2 import csv data from Qgis to geonature DB**

**-- 3 create CA**

```
INSERT INTO gn_meta.t_datasets(id_acquisition_framework, dataset_name, dataset_shortname, dataset_desc, id_nomenclature_data_type, keywords, marine_domain, terrestrial_domain, active)
VALUES
(1,'Données Patrinat IDF openobs 1697 - 2020', 'Observations patrinat Openobs', 'Données Patrinat IDF openobs 1697 - 2020', 326, 'faune, flore, idf, patrinat, mnhm, openobs', FALSE, TRUE, TRUE)
```

**-- 4 Insert data into synthese table**


```
INSERT INTO gn_synthese.synthese(
	unique_id_sinp,
	id_source,
	id_dataset,
	-- id_nomenclature_obs_meth,
	count_min,
	count_max,
	cd_nom,
	nom_cite,
	altitude_min,
	altitude_max,
	the_geom_4326,
	the_geom_point,
	the_geom_local,
	date_min,
	date_max,
	observers,
	-- comments,
	last_action
) (SELECT
	"idSINPOccTax"::uuid ,
	1 AS id_source,
	1699 AS id_dataset, -- read id dataset in DB first !!!
	-- gn_synthese.get_default_nomenclature_value('METH_OBS') AS id_nomenclature_obs_meth,
	0::integer,
	0::integer,
	"cdNom"::integer,
	"nomCite",
	"altitudeMin"::integer,
	"atitudeMax"::integer,
	ST_SetSRID(ST_MakePoint("longitude"::numeric, "latitude"::numeric),4326) AS the_geom_4326,
	ST_Centroid(ST_SetSRID(ST_MakePoint("longitude"::numeric, "latitude"::numeric),4326)) AS the_geom_point,
	ST_Transform(ST_SetSRID(ST_MakePoint("longitude"::numeric, "latitude"::numeric),4326),2154) AS the_geom_local,
	"dateObservation"::date,
	"dateObservation"::date,
	observateur,
	-- commentaire,
	'I' AS last_action -- code de la dernière action effectuée: Valeurs possibiles 'I': insert, 'U': update
 FROM tmp_import_data_patrinat.patrinat_idf);
 ORDER BY "dateObservation"
```

**Comment by camillemonchicourt** [comment]
Oui le champs ``id_nomenclature_obs_meth`` a été remplacé par ``id_nomenclature_obs_technique`` dans la version 2.5.x, donc il y a pas mal de temps, mais cela n'a pas été répercuté dans la doc d'import, qui a certainement vocation à disparaître, d'autant plus depuis que le module IMPORT est disponible et fonctionnel.

Mais en attendant, j'ai modifié la doc pour ne plus faire référence à cette colonne dont le nom a été modifié : https://github.com/PnX-SI/GeoNature/commit/bdc28bebdd270e2de9a755071bfe9df50db20e31

**Comment by Gaetanbrl** [comment]
Merci @camillemonchicourt
