### ISSUE TITLE
Customisation Page Login - nom application

### ISSUE THREAD

**Issue by naidinp** [PnX-SI/GeoNature#2272]
Bonjour à tous,

J'ai suivi la documentation et la majorité des éléments à modifier (logo, message page d'accueil .....) est spécifié mais pas le nom de l'application.

Pouvez-vous m'indiquer à quel niveau on peut paramétrer cet élément ?

Merci

**Comment by camillemonchicourt** [comment]
Certainement : https://github.com/PnX-SI/GeoNature/blob/master/config/default_config.toml.example#L28-L29

**Comment by naidinp** [comment]
Top - Merci
