### ISSUE TITLE
Créer réferentiel géographique

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#228]
Schéma à nommer `ref_geo` sur la base de celui de @amandine-sahl  (https://github.com/PnX-SI/GeoNature/blob/4d318894ab0a4d03a1ffee601741e9e80391928c/data/core/ref_geographique/schema.sql)

Par contre on n'aura qu'une table des zonages appelée `l_areas`
On aura aussi `bib_areas_types`, `l_municipalities` (car les communes ont pas mal d'infos spécifiques), `l_grid`.

A voir comment on gère le MNT local.

Et les applis se baseront sur une VM pour récupérer tous les zonages et les afficher dynamiquement dans un Gestionnaire de couche par exemple ou pour les intersecter avec des données.

**Comment by camillemonchicourt** [comment]
@gildeluermoz indique : 

Le script d'install de la BDD comporte maintenant l'installation du référentiel géographique (pensez à compléter votre settings.ini à partir du sample)

Qq infos :
pour le moment seuls sont insérées les communes et le mnt

Les communes sont celles de France, ancien geoflat = admin-express (dernière version dispo, juin 2017, normalement il y a une mise à jour mensuelle). C'est gratuit mais il faut étudier les licences pour en faire part dans la licence GeoNature.

Je n'insère que les données ultra basiques : id_municipality = insee, le nom et le geom. A coté, j'ai créé une table `l_municipalities_additional` qui n'est pas remplie pour le moment mais qui comprend tous compléments souhaités. On reparlera de cette table. Je pense que son rôle est un rôle d'extension du référentiel de base. A voir si on conserve ce principe. On pourrait la livrer plus simple (soi que les champs de l'admin-express, soit juste un `id_municipality`). Autre option, chacun est libre de compléter sa table `l_municipalities` avec des champs propres à sa structure. Autre options, réfléchir à un mécanisme générique de base + extension type les attributs de taxhub ou autre.

Pour le ref geo :
- création du schéma et des tables d'abord pour avoir un SRID sur les geom des tables du mnt
- téléchargement et insertion dans la table `dem` du mnt France à 250m (le 75m faisant 1.3Go décompressé) puis vectorisation dans une table `dem_vector` (9 millions de polygones, c'est un peu long à créer : 10min environ) puis indexation gist de la table vecteur. 
- Les 2 fonctions d'Amandine ont été légèrement adaptées et elles fonctionnent.
       - `ref_geo.fct_get_altitude_intersection(geom)`
       - `ref_geo.fct_get_municipality_intersection(geom)`

**Comment by camillemonchicourt** [comment]
OK super. Comme l'ensemble du référentiel géographique, on pourra aussi intégrer une option pour les découper sur la base d'une couche SIG du territoire.

**Comment by gildeluermoz** [comment]
On ferme le ticket et on découpe en taches plus petites
https://github.com/PnX-SI/GeoNature/issues/237

**Comment by sig-pnrnm** [comment]
Une question sur le sujet du référentiel géographique : avez-vous envisagé la possibilité de gérer un réferentiel de lieux-dits / adresses ?
D'ailleurs, n'aurait-il pas été judicieux d'utiliser l'[API de la Base Adresse Nationale (BAN)](https://adresse.data.gouv.fr/api).

Par exemple, cette requête : [https://api-adresse.data.gouv.fr/reverse/?lon=-0.15026&lat=48.5629](https://api-adresse.data.gouv.fr/reverse/?lon=-0.15026&lat=48.5629) retourne bien un JSON avec tout plein d'infos géographique dérivées (commune, rue, ...) format l'adresse précise : 

`{"attribution": "BAN", "limit": 1, "features": [{"geometry": {"type": "Point", "coordinates": [-0.150248, 48.563509]}, "type": "Feature", "properties": {"type": "housenumber", "y": 6833891.4, "housenumber": "5002", "postcode": "61320", "context": "61, Orne, Normandie (Basse-Normandie)", "citycode": "61074", "distance": 67, "importance": 0.065, "x": 467620.1, "label": "5002 Le Chapitre 61320 Carrouges", "name": "5002 Le Chapitre", "street": "Le Chapitre", "city": "Carrouges", "score": 0.9999981677173955, "id": "61074_B037_8bc845"}}], "licence": "ODbL 1.0", "type": "FeatureCollection", "version": "draft"}`

Après, à voir quels infos on voudrait stocker en base.

Qu'en pensez-vous ?

**Comment by camillemonchicourt** [comment]
Le référentiel est une première base mais à vocation à devenir un projet à part entière : GeoHub. Qui permettra de centraliser les données géographiques de référence pour les utiliser dans différentes applications sans avoir à les mettre à jour dans chacune (dans la logique de UsersHub ou TaxHub). 

Pour le moment, on y a mis que ce qui est essentiel à GeoNature, c'est-à-dire les communes, les zonages (où chacun met tout ce qu'il veut comme zonage, un peu comme dans Geotrek) et le MNT. 

Il n'y a pas d'usage prévu de lieux-dits, adresses dans GeoNature mais pourquoi pas l'ajouter si c'est utile à d'autres BDD par la suite.

Quand on pourra on en fera un projet à part entière avec son dépôt. On veille aussi à ce que ce référentiel soit générique et international. :-)

Côté application, pour le moment, on a mis un petit moteur de recherche de lieu sur les cartes qui s'appuie sur l'API OSM. On verra si on le laisse.

**Comment by camillemonchicourt** [comment]
Le ``ref_geo`` avec sa structure de BDD mais aussi ses modèles ont été sortis de GeoNature (https://github.com/PnX-SI/GeoNature/pull/1754), dans un dépôt dédié (https://github.com/PnX-SI/RefGeo), notamment pour en faciliter l'usage dans d'autres projets/outils, comme TaxHub.

A terme il est souhaité d'y inclure aussi ses routes, pour le rendre encore plus indépendant.
