### ISSUE TITLE
[GN 2.10] Erreur lors du changement de mot de passe

### ISSUE THREAD

**Issue by geoek** [PnX-SI/GeoNature#2288]
**Version**
2.10

**Description du bug**
Depuis la migration vers 2.10, il est impossible de changer son mot de passe : 
 - depuis la page de login : on reçoit bien le mail, qui redirige désormais vers la bonne url (corrigé en 2.10) Mais lorsque l'on valide le nouveau mot de passe, on obtient l'erreur : HttpErrorResponse
Http failure response for https://geonature.biodiv-occitanie.fr/api/users/password/new: 500 INTERNAL SERVER ERROR
 - Si lorsque l'on est connecté, on va sur le formulaire pour changer le password, même comportement.
 - Par contre, il est possible de le changer depuis Usershub

Je ne vois rien dans les différents logs (geonature ou usershub).

Avez-vous le même comportement ? Une idée d'où ça pourrait venir ?

Merci d'avance !

**Comment by bouttier** [comment]
Bonjour,
Le problème est situé au niveau de UsersHub, et vous pouvez certainement observer l’erreur suivante dans ses logs :
```
subject table for an INSERT, UPDATE or DELETE expected, got Column('id_role', Integer(), table=<cor_role_token>, primary_key=True, nullable=False).
```
Ce problème est corrigé sur la branche develop de UsersHub : https://github.com/PnX-SI/UsersHub/commit/3a10a354679feeeab57437bc4254b3f8d21e738b

**Comment by JeromeMaruejouls** [comment]
Merci beaucoup @bouttier, je vais faire la modif ! (par contre, pour les logs, je crois que je n'avais rien aussi dans ceux de usershub, mais c'est peut etre moi qui ait mal cherché !)

**Comment by camillemonchicourt** [comment]
Corrigé dans la version 2.3.3 de UsersHub que vous pouvez donc mettre à jour.
