### ISSUE TITLE
Migration - récupération du fichier environ

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#2301]
Certaines variables comme le  timeout sont configurées dans un fichier environ à la racine de GeoNature, sauf erreur de ma part c'est toujours le cas sur le dernieres versions. Il serait donc intéressant de récupérer ce fichier lors de la migration :)

**Comment by bouttier** [comment]
C’est fait : https://github.com/PnX-SI/GeoNature/blob/fa7673af25abee2d38ace9bae2ee78489a81cea8/install/migration/migration.sh#L46
