### ISSUE TITLE
Installation des modules import et export : Missing file manifest.toml

### ISSUE THREAD

**Issue by juliettefabre** [PnX-SI/GeoNature#2305]
**Version**
2.10.4

**Description du bug**
Je n'arrive pas à installer les modules import (2.0.4) et export (1.3.0). Pour chacun de ces modules la commande d'installation renvoie la même erreur:
```
geonatureadmin@oreme-geonature:~$ source geonature/backend/venv/bin/activate
(venv) geonatureadmin@oreme-geonature:~$ geonature install-gn-module ~/gn_module_import IMPORT
checking file
Error while installing GN module .The process returned:
	Missing file manifest.toml
```

**Comment by bouttier** [comment]
Bonjour,
Les modules IMPORT et EXPORT ont été packagé (présence d’un fichier ``setup.py`` au lieu du ``manifest.toml`` précédent).
La version 2.11 de GeoNature ne supporte plus que les modules packagés, et la commande lancée aurait fonctionnée correctement.
La version 2.10 de GeoNature est une version de transition gérant les modules packagé et non-packagé.
Pour installer un module packagé avec cette dernière, il faut lancer la commande suivante :
``geonature install-packaged-gn-module ~/gn_module_import IMPORT``

**Comment by juliettefabre** [comment]
Bonjour, 
Super merci !
Juliette

**Comment by juliettefabre** [comment]
J'ai encore un souci ..
L'installation des modules a bien fonctionné (pas d'erreur). J'ai relancé GeoNature.
Je peux voir les modules depuis la page d'accueil de GeoNature mais quand je clique sur l'un ou l'autre j'ai ce type d'erreur dans la console :
`Cannot find module './exports/frontend/app/gnModule.module'`

**Comment by bouttier** [comment]
Est-ce que vous avez bien rebuildé le frontend ?
```
cd frontend
nvm use
npm run build
```

**Comment by juliettefabre** [comment]
A non en effet, merci. Mais désolée je cumule, il semblerait que le rebuild n'aboutit pas :
```
$ npm run build

> geonature@0.0.0 build
> ng build --aot=false --build-optimizer=false --configuration production

Warning: Support was requested for IE 11 in the project's browserslist configuration. IE 11 support is deprecated since Angular v12.
For more information, see https://angular.io/guide/browser-support
✔ Browser application bundle generation complete.
Killed
```
Et j'obtiens une erreur 403 sur GeoNature ...

**Comment by camillemonchicourt** [comment]
Quand ça dit ``Killed``, c'est le même sujet qu'évoqué par ailleurs.
Les ressources du serveur sont saturées et le build du frontend n'aboutit pas.
Donc il faut tenter de redémarrer le serveur et relancer le build du frontend.

**Comment by juliettefabre** [comment]
OK merci !

**Comment by juliettefabre** [comment]
Même problème après reboot .. Il doit y avoir un souci ailleurs, ça marchait avant ..

**Comment by camillemonchicourt** [comment]
Si la commande de build renvoie ``Killed``, c'est vraiment que les ressources de ton serveur saturent et il arrive pas au bout.

**Comment by bouttier** [comment]
Cela peut être confirmé en utilisant la commande ``sudo dmesg`` et en observant des messages de type ``oom-killer`` (out-of-memory killer)

**Comment by juliettefabre** [comment]
Oui oui le process est tué suite à un manque de ressource, mais je veux dire que ce n'est peut-être pas normal que le rebuild prenne autant de ressources ? Car j'ai bien réussi à builder le frontend initialement lors de l'installation de GeoNature ? Ca me paraît étrange qu'il n'y arrive plus suite à l'installation de 2 modules. Je me dis qu'il y a peut-être quelque chose qui ne lui plait pas suite à l'installation de ces modules et que ça le fait ramer. Je vais essayer d'obtenir une VM avec + de RAM.

**Comment by camillemonchicourt** [comment]
Peux-tu nous redire les ressources de la VM ?

**Comment by gildeluermoz** [comment]
J'ai régulièrement ce pb sur des vps OVH avec 4go de ram. Mais après reboot, jusque là, c'est tjs passé.
En 2.9 comme en 2.11
Non testé en 2.10.

**Comment by juliettefabre** [comment]
C'est une VM avec 4Go de RAM et 20Go d'espace.

**Comment by bouttier** [comment]
Bonjour,
Vous pouvez essayer d’arrêter geonature et son worker, usershub & taxhub avant de lancer le build puis de les redémarrer après :
```
sudo systemctl stop geonature
sudo systemctl stop geonature-worker
sudo systemctl stop usershub
sudo systemctl stop taxhub
```

**Comment by juliettefabre** [comment]
> Bonjour, Vous pouvez essayer d’arrêter geonature et son worker, usershub & taxhub avant de lancer le build puis de les redémarrer après :
> 
> ```
> sudo systemctl stop geonature
> sudo systemctl stop geonature-worker
> sudo systemctl stop usershub
> sudo systemctl stop taxhub
> ```

yes, ça a marché avec cette méthode, merci !!
