### ISSUE TITLE
Requêtes par statut n'aboutissant pas

### ISSUE THREAD

**Issue by MathieuLagarde** [PnX-SI/GeoNature#2329]
Bonjour,

Nous avons mis à jour notre instance de dév avec la version 2.11.2 de GéoNature.

**Description du bug**
J'ai configuré le fichier `config/geonature_config.toml` avec ces paramètres:

```
# Configuration de la Synthese
[SYNTHESE]
  RED_LISTS_FILTERS = [
        { "id" = "worldwide", "show" = false, "display_name" = "Liste rouge mondiale", "status_type" = "LRM" },
        { "id" = "european", "show" = true, "display_name" = "Liste rouge européenne", "status_type" = "LRE" },
        { "id" = "national", "show" = true, "display_name" = "Liste rouge nationale", "status_type" = "LRN" },
        { "id" = "regional", "show" = true, "display_name" = "Liste rouge régionale", "status_type" = "LRR" },
        { "id" = "regionalmig", "show" = true, "display_name" = "Liste rouge régionale des oiseaux migrateurs", "status_type" = "LRRm" },
        { "id" = "regionalnich", "show" = true, "display_name" = "Liste rouge régionale des oiseaux nicheurs", "status_type" = "LRRn" },
    ]
    STATUS_FILTERS = [
        { "id" = "protections", "show" = true, "display_name" = "Taxons protégés", "status_types" = ["PN", "PR", "PD"] },
        { "id" = "regulations", "show" = true, "display_name" = "Taxons réglementés", "status_types" = ["REGLII", "REGL", "REGLSO"] },
        { "id" = "invasive", "show" = true, "display_name" = "Espèces envahissantes", "status_types" = ["REGLLUTTE"] },
        { "id" = "znief", "show" = true, "display_name" = "Espèces déterminantes ZNIEFF", "status_types" = ["ZDET"] },
    ]
```

J'ai également passé le paramètre `enable` de nombreux textes qui ne nous concernaient pas à false dans la table `taxonomie.bdc_statut_text`.

A partir de là, lors de tests de requêtes sur les statuts avec les filtres taxonomiques avancés, la recherche ne semble pas fonctionner pour:
	* Les listes régionales ne fonctionnent pas, qu'elles concernent le "status_type" "LRR", "LRRm" ou "LRRn".
	* Espèces déterminantes ZNIEFF

Y a t'il d'autres configurations à prendre en compte pour faire fonctionner ces requêtes ?

Merci pour votre aide.

**Comment by jpm-cbna** [comment]
Est ce que l'interface du formulaire de recherche de la Synthese contient bien tous les champs que vous avez listé dans votre fichier de configuration ? Les champs "Liste rouge régionale des oiseaux migrateurs" et "nicheurs" apparaissent bien ?

Est ce que la  table `taxonomie.bdc_statut_cor_text_area` contient bien des correspondances avec les textes dont vous avez laissé le champ "enable" à "true" dans la table `taxonomie.bdc_statut_text` ?

Concernant les "Liste rouge régionale des oiseaux migrateurs" et "nicheurs", je ne voie pas ces codes (champ `cd_type_statut`) dans la table `taxonomie.bdc_statut_type`. Est ce que c'est spécifique à votre base ?

Voilà, ce que j'obtiens avec les paramètres de config par défaut :
![Screenshot_20230216_111708](https://user-images.githubusercontent.com/51449363/219336954-1792890c-f0ac-44fc-a4c0-86d55ee795e8.png)

```toml
    RED_LISTS_FILTERS = [
        { "id" = "worldwide", "show" = true, "display_name" = "Liste rouge mondiale", "status_type" = "LRM" },
        { "id" = "european", "show" = true, "display_name" = "Liste rouge européenne", "status_type" = "LRE" },
        { "id" = "national", "show" = true, "display_name" = "Liste rouge nationale", "status_type" = "LRN" },
        { "id" = "regional", "show" = true, "display_name" = "Liste rouge régionale", "status_type" = "LRR" },
    ]
    STATUS_FILTERS = [
        { "id" = "protections", "show" = true, "display_name" = "Taxons protégés", "status_types" = ["PN", "PR", "PD"] },
        { "id" = "regulations", "show" = true, "display_name" = "Taxons réglementés", "status_types" = ["REGLII", "REGL", "REGLSO"] },
        { "id" = "invasive", "show" = true, "display_name" = "Espèces envahissantes", "status_types" = ["REGLLUTTE"] },
        { "id" = "znief", "show" = true, "display_name" = "Espèces déterminantes ZNIEFF", "status_types" = ["ZDET"] },
    ]
```

**Comment by camillemonchicourt** [comment]
Mathieu, il faudrait aussi préciser ce qu'il se produit concrètement quand tu indiques "ne semble pas fonctionner" ?
Et fournir les logs d'erreur GeoNature et TaxHub correspondant au moment du soucis que tu indiques ?

**Comment by MathieuLagarde** [comment]
Bonjour,
Merci pour vos réponses.
Jean-Pascal, mon problème venait de ma table `taxonomie.bdc_statut_cor_text_area` que je n'avais pas identifiée. Je l'ai peuplée avec les valeurs manquantes, et les requêtes aboutissent désormais. Les autres tables étaient théoriquement bien peuplées.

Les "Liste rouge régionale des oiseaux migrateurs" et "Liste rouge régionale des oiseaux nicheurs" sont bien des valeurs spécifiques à ma base. J'ai dû les créer pour distinguer deux listes rouges publiées dans un même document, et donc, indistinguables dans la BDC.

Camille, pour préciser ce qu'il se passait: après sélection de mes critères de recherche (en l'occurrence, des statuts), puis lancement de la recherche, celle-ci semblait tourner, mais n'aboutissait pas au résultat souhaité. Les données s'affichant étant celles s'affichant pas défaut à l'ouverture de la page "Explorer les données".

Merci à vous!

**Comment by camillemonchicourt** [comment]
Oui cette table est remplie par la commande ``link-bdc-statut-to-areas``, intégrée dans TaxHub 1.10.5.

A noter dans TaxHub 1.11.0, la nouvelle commande pour n'activer que les textes correspondant à son territoire : 

> Ajout d'une commande permettant d'activer les textes de la BDC_statuts concernant uniquement son territoire (par ``area_code`` de départements) : ``flask taxref enable-bdc-statut-text -d <MON_DEP_1> -d <MON_DEP_2> --clean``
