### ISSUE TITLE
Missing librairy `sentry_sdk`

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#2332]
**Version**
2.11.2

**Description du bug**
La librairie `sentry_sdk` n'est pas dans les fichiers de requirements.
Si on renseigne le paramètre de config `SENTRY_DSN` on tombe sur une erreur quand on veut charger sentry_sdk

**Comportement attendue**
ajouter `sentry_sdk` aux requirements (`requirements-common.in` ??)

**Comment reproduire**
renseigner `SENTRY_DSN`. Redemarrer l'appli
Étapes à suivre pour reproduire le problème (sur quelle page se rendre, sur quel bouton cliquer, avec quelles données présentes, …).

**Logs**
Extrait du fichier ``/var/log/geonature.log`` dans le cas d’une erreur 500.

**Comment by VincentCauchois** [comment]
Salut,

Dans l'optique où **l'intégration à Sentry n'est pas prévue par défaut** pour une installation de GeoNature : je pense qu'il vaut mieux ne pas ajouter la librairie `sentry_sdk` dans les requirements.

Il vaut mieux **installer cette librairie et configurer Sentry au besoin**, et **a posteriori de l'installation de GeoNature**. 

------------------------------------------------------------------------------------------------------

**Configuration de Sentry pour GeoNature** :
_effectuée pour les instances GINCO et DepoBio, basées sur GeoNature_

Dans ce cas-là, il faut **se mettre dans le répertoire geonature** ; habituellement "/home/\`whoami\`/geonature/" ; **puis effectuer les commandes suivantes** :  
``` 
source backend/venv/bin/activate
pip install --upgrade 'sentry-sdk[flask]'
```
⚠️ _Il faut installer sentry-sdk avec l'extra flask, comme c'est le cas avec cette dernière commande, ceci afin d'avoir une intégration correcte entre Sentry et Flask (API GeoNature)._

Finalement, une fois un **projet Flask "monapp-geonature" créé sur Sentry** et le **DSN récupéré**, il suffit de **rajouter cette ligne dans le fichier "geonature/config/geonature_config.toml"** de configuration de geonature :
`SENTRY_DSN = "dsn_pour_mon_projet_sentry_geonature"`

Penser, enfin, à effectuer les **actions après modification de la config : https://docs.geonature.fr/admin-manual.html#post-config-change** 

⚠️Il s'agit d'une **configuration de Sentry pour l'API de GeoNature uniquement** : 
- **Pour avoir un monitoring de TaxHub et de UsersHub** : il faut créer 2 autres projets flask sur Sentry, puis rajouter dans les fichiers de config associés ; habituellement ``/home/`whoami`/taxhub/apptax/config.py`` et ``/home/`whoami`/usershub/config/config.py`` ; les lignes suivantes : 
```
import sentry_sdk
from sentry_sdk.integrations.flask import FlaskIntegration

sentry_sdk.init(
    dsn="dsn_pour_mon_projet_sentry",
    integrations=[
        FlaskIntegration(),
    ],

    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    traces_sample_rate=1.0,

    # By default the SDK will try to use the SENTRY_RELEASE
    # environment variable, or infer a git commit
    # SHA as release, however you may want to set
    # something more human-readable.
    # release="myapp@1.0.0",
)
```
- **Pour avoir un monitoring du frontend** : la documentation de Sentry a une partie dédiée à l'intégration avec Angular : https://docs.sentry.io/platforms/javascript/guides/angular/. ⚠️ Pas effectué pour les instances GINCO et DepoBio.

------------------------------------------------------------------------------------------------------

**Proposition** : 
On pourrait plutôt ajouter une section "Configuration de Sentry" dans la docs de GeoNature.

**Comment by mvergez** [comment]
Salut !

Et pourquoi ne pas mettre ce package dans un `extras_require` du `setup.py` ? On aurait juste à faire `pip install -e .[sentry]` par exemple. On peut même spécifier plusieurs `extras_require` si besoin : `pip install -e .[tests,doc,sentry]`.

Un paramètre `use_sentry` pourrait également figurer dans le `settings.ini` pour tout configurer automatiquement :)

**Comment by bouttier** [comment]
Oui je pensais en effet à le rajouter aux extras_require.

Le paramètre dans le settings.ini me semble une bonne idée car en l’état ça pose problème à chaque upgrade comme on re-crée le venv (mais c’est sans doute une bêtise d’ailleurs).

**Comment by joelclems** [comment]
Est ce que c'est vraiment couteux de charger la librairie par défaut? 
Cela éviterai des manipulation ou des paramètre de config en plus.

**Comment by bouttier** [comment]
J’aurai plutôt tendance à supprimer toute référence à Sentry, et donc supprimer le paramètre ``SENTRY_DSN``, et laisser la liberté aux admins de configurer l’outil de collecte de trace de leur choix, s’il en souhaite un, via un fichier de configuration python libre (configurable via la variable d’environnement ``GEONATURE_SETTINGS``). C’est la logique qui prévaut en Django.

Les manipulations et paramètres seraient évité en arrêtant de supprimer le venv et se contentant de le mettre à jour.

Ceci dit, j’ai commencé à rajouter du code spécifique Sentry dans le module d’import afin d’en profiler les performances. Il n’est donc pas totalement aberrant de considérer Sentry comme un choix assumé par GeoNature …

**Comment by mvergez** [comment]
> Est ce que c'est vraiment couteux de charger la librairie par défaut?

C'est dommage d'installer et donc de télécharger des choses dont on a pas besoin. Installer une librairie c'est aussi la maintenir à jour et gérer les dépendances. Enfin si d'autres utilisateurs veulent utiliser un autre outil que Sentry, c'est cool qu'ils n'aient pas à l'installer par défaut.

Je suis d'accord avec @bouttier qu'il faudrait n'avoir aucune référence à Sentry (même si c'est un super outil !) dans GeoNature pour exactement les mêmes raisons. Cela fait aussi plus de code à maintenir.

**Comment by bouttier** [comment]
J’ai changer le script ``01_install_backend.sh`` pour ne plus détruire le venv mais se contenter de mettre à jour ce qu’il contient.
Je vais modifier le script ``migrate.sh`` afin d’utiliser ``01_install_backend.sh`` et donc avoir le même comportement.

**Comment by bouttier** [comment]
C’est fait : https://github.com/PnX-SI/GeoNature/blob/fa7673af25abee2d38ace9bae2ee78489a81cea8/install/migration/migration.sh#L123
