### ISSUE TITLE
Admin permissions - Permissions d'un groupe sans utilisateur associé ne s'affichent pas

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#2344]
Si j'ai un groupe qui n'a pas d'utilisateur associé, que je modifie les permissions de ce groupe, celles-ci sont bien enregistrées dans la table des permissions des rôles, mais ne s'affiche pas dans le CRUVED du groupe.

C'est lié à une jointure dans la vue sur laquelle se base les permissions qui a un soucis : ``gn_permissions.v_roles_permissions``.

Le contournement est d'avoir au moins un utilisateur associé à ce groupe.

Mais cela confirme l'intérêt du travail en cours de refonte des permissions, qui prévoit notamment de supprimer cette vue.

**Comment by bouttier** [comment]
Corrigé par #2353
Cette vue reste peu optimisée pour les instances avec de nombreux groupes et utilisateurs.

**Comment by camillemonchicourt** [comment]
La vue `gn_permissions.v_roles_permissions` peu performante a été supprimée dans la version 2.12.0.
