### ISSUE TITLE
[Notifications] Appel double de la route notifications/count

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature#2356]
Bonjour,

### Contexte

J'ai remarqué que l'appel à la route `notifications/count` se fait 2 fois lorsqu'on actualise la page depuis n'importe quel module (sur l'accueil aussi).
Ce double appel semble venir du fait que `this.updateNotificationCount()` soit appelé dans `ngOnInit()` ici : 
https://github.com/PnX-SI/GeoNature/blob/7552602e3fff3b12bd009d2efd8ca3450a763838/frontend/src/app/components/nav-home/nav-home.component.ts#L54-L57
Mais également dans `onModuleChange()` ici : 
https://github.com/PnX-SI/GeoNature/blob/7552602e3fff3b12bd009d2efd8ca3450a763838/frontend/src/app/components/nav-home/nav-home.component.ts#L96-L99

### Proposition

L'appel dans `ngOnInit()` semble inutile et serait donc à supprimer car la méthode `onModuleChange()` est appelée quoiqu'il arrive. Qu'en pensez-vous ?
Je peux faire une PR dans ce sens si vous validez cette option.

Merci d'avance !

**Comment by TheoLechemia** [comment]
Bien vu !
Est-ce qu'on a besoin de MAJ le nombre de notification quand on change de module ? Pas sur si ? 
Peut être que le onInit suffit du coup ?

**Comment by mvergez** [comment]
Merci @TheoLechemia pour ton retour !
Bonne question, je pense qu'il y a besoin de maj car le `OnInit` n'est pas rappelé quand on "navigue" dans GeoNature. Et si on navigue pendant un certain temps, il est nécessaire d'être informé des notifications qui peuvent être arrivées entre temps. Qu'en penses-tu ?

**Comment by TheoLechemia** [comment]
Ok, c'est ce que je voulais vérifier, t'es allé plus vite. Ok pour le onChange du coup

**Comment by mvergez** [comment]
Top merci ! La PR arrive !
Oui c'est ce que je voulais vérifier aussi avant d'ouvrir l'issue :)

**Comment by bouttier** [comment]
Merci pour ce fix !

Si je comprend bien, là on récupère les notifications uniquement si on change de module. Est-ce que le top, ça serait quand même pas que dans le onInit, on récupère les notifications toutes les X secondes (et de virer le onUpdate) ?
