### ISSUE TITLE
Le tutoriel ne permet pas d'obtenir une configuration HTTPS pour Apache (Debian 11)

### ISSUE THREAD

**Issue by Dece** [PnX-SI/GeoNature#2371]
**Version**
2.11.2 sur Debian 11.

**Description du bug**
La configuration d'Apache pour l'accès en HTTPS n'est pas faite par la procédure d'installation.

**Comportement attendue**
Les commandes de la documentation devraient suffire à fournir une configuration Apache fonctionnelle en HTTPS.

**Comment reproduire**
[Suivre la documentation d'installation](https://docs.geonature.fr/installation.html#https).

**Commentaires**
Pour résoudre ce problème on a utilisé `certbot run --apache` après la génération des certificats. La commande certonly fait que la configuration du virtualhost Apache n'est pas mise à jour pour le HTTPS, et vu les scripts/templates qui n'ont que la configuration HTTP, je suppose que le tutoriel s'attend à ce que certbot s'occupe de dupliquer la configuration pour avoir le HTTPS mais tel quel ça n'est pas le cas. Vu que le tutoriel semble avoir été écrit pour Debian 9, le comportement de certbot a changé depuis ?

**Comment by camillemonchicourt** [comment]
Oui Certbot est bien plus simple désormais.

**Comment by camillemonchicourt** [comment]
Cela ne concerne pas GeoNature.
On l'a mis dans la documentation pour faciliter la tâche à ceux qui ne savent pas comment passer en HTTPS mais on pense à retirer cette documentation car elle n'est pas à jour, donc fausse et ne concerne pas GeoNature.

**Comment by Dece** [comment]
OK ! On a trouvé la documentation tout de même bien pratique sur cet aspect pour assister l'installation lorsqu'on est pas sysadmin, et elle a le mérite d'être là, je vous fais une PR au cas où pour compléter, je préférais m'assurer avant que j'avais bien compris.

**Comment by camillemonchicourt** [comment]
OK mais alors on peut diviser cette doc par 10.
Si j'ai bien suivi, il suffit de lancer ``sudo certbot --apache`` et c'est tout.
Pas besoin d'expliquer la commande CERTBOT, ni où sont rangés les certificats, ni comment les renouveler car c'est désormais automatiquement géré par Certbot.

**Comment by Dece** [comment]
J'étais en train d'installer GeoNature sur un petit serveur pour vérifier que mes corrections de docs étaient sans risques mais vu le grand coup de balai je pense qu'on peut clore :P merci !

**Comment by camillemonchicourt** [comment]
Je veux bien que tu testes la doc et voir si la commande indiquée suffit, car j'ai fait ça de mémoire.
Mais je pense que c'est fonctionnel et bien plus simple. :-)

**Comment by dece** [comment]
C'est confirmé !
