### ISSUE TITLE
Réinitialiser BDD Geonature

### ISSUE THREAD

**Issue by Uiio86** [PnX-SI/GeoNature#2378]
**Version**
Version de Geonature 2.9.2
Version de Taxhub 1.9.4
Version de UsersHub 2.2.2.

**Question**

J'aimerai réinitialiser la BDD de geonature (taxhub et usershub également) telle qu'elle est après son installation.
Sans a avoir à réinstaller l'application ou la VM

**Comment by camillemonchicourt** [comment]
En plus si tu lances seulement le script 03_create_db.sh de GeoNature, cela va créer uniquement les schémas et tables de GeoNature, pas ceux de TaxHub et UsersHub qu'il faudra installer manuellement par ailleurs...

**Comment by camillemonchicourt** [comment]
Pas de retour ? Je ferme.
