### ISSUE TITLE
[GN 2.11] occtax - modifier un habitat dans un relevé

### ISSUE THREAD

**Issue by JulienCorny** [PnX-SI/GeoNature#2384]
Bonjour,

La mise à jour du champ Habitat d’un relevé dans le module occtax n’est pas répercutée dans la table gn_synthese.synthese pour les observations correspondant à ce relevé. 

Pour reproduire : 
Créer un relevé dans occtax sans indication d’habitat, avec des observations associées à ce relevé, terminer la saisie (donc tout est envoyé correctement vers la synthèse). Revenir dans le relevé occtax, ajouter un habitat, valider la modif : la modif d’habitat n’est pas propagée à la synthèse (cd_hab reste null). 

Il semble que le souci vient de pr_occtax.fct_tri_synthese_update_releve() qui ne contient pas de cd_hab ?

Est-ce que vous avez déjà identifié le souci ? Ou est-ce que c’est volontaire car les caractéristiques d’un habitat peuvent changer avec le temps, donc ça pourrait potentiellement modifier l’observation à tort ?

(testé sur 2.11.0)

**Comment by TheoLechemia** [comment]
Il faut aussi vérifier que cette info s'affiche sur la "fiche info" d'une observation dans la synthese. Sinon faire une jointure sur la table habref pour avoir le nom de l'habitat et pas uniquement son cd_hab

**Comment by JulienCorny** [comment]
A quel endroit ce serait le mieux d'afficher l'info d'habitat dans la fiche info d'une observation dans la synthèse ? 

Est-ce qu'il ne faudrait pas créer un onglet supplémentaire "Habitat" ? puisque cette info ne s'intègre pas vraiment dans les onglets existants

**Comment by DonovanMaillard** [comment]
Salut Julien, 

A priori il n'y aura qu'un item à afficher sur les habitats pour les données qui viennent docctax et pour les données de synthèse de taxons en général. 

Le plus simple serait peut être de l'afficher dans l'en-tete ?

**Comment by camillemonchicourt** [comment]
Le champs `cd_hab` a bien été ajouté dans les tables `pr_occtax.t_releves_occtax` et `gn_synthese.synthese` dans la version 2.5.0 quand on est passé à la V2 du standard Occurrences de taxons : https://github.com/PnX-SI/GeoNature/blob/master/data/migrations/2.4.1to2.5.0.sql#L324

Il a bien été intégré dans la fonction d'insertion des relevés Occtax vers la Synthèse (https://github.com/PnX-SI/GeoNature/blob/master/data/migrations/2.4.1to2.5.0.sql#L348) mais en effet pas dans la fonction de mise à jour des relevés (`fct_tri_synthese_update_releve`).

Le champs a aussi été ajouté dans les exports de la Synthèse (`gn_synthese.v_synthese_for_export`) mais pas dans la vue utilisée par le module web Synthèse (`gn_synthese.v_synthese_for_web_app`).

Il faudrait donc : 
- Reprendre la fonction `pr_occtax.fct_tri_synthese_update_releve` pour qu'elle prenne en compte les modifications de l'habitat d'un relevé
- Faire une migration pour corriger les éventuelles habitats qui ont été modifiés dans des relevés Occtax
- Ajouter le filtre "Habitat" dans les filtres avancés de la Synthèse
- Afficher le champs "Habitat" de la Synthèse dans les fiches infos des observations

Pour ce dernier point, ce champs "Habitat" reste assez secondaire et est peu renseigné.
Je ne suis pas trop favorable à ce qu'on le mette bien plus en avant que d'autres champs d'une occurrence de taxon, souvent bien plus renseignés.
Donc pas favorable à ce qu'on en fasse un onglet dédié, ni à le mettre dans l'en-tête des fiches infos des observations dans la Synthèse.

Selon moi, c'est un champs de l’occurrence comme les autres, à ajouter dans le premier onglet "Détail de l'occurrence".

**Comment by JulienCorny** [comment]
Merci Donovan et Camille pour vos réponses. 

En fait un champ "Habitat associé" est déjà présent dans les fiches infos des observations de la synthese (branche develop) comme suggéré par Donovan (le champ s'affiche seulement si un habitat est renseigné) :

![image](https://user-images.githubusercontent.com/40057801/229822257-3d047023-9885-4a1c-90e6-0360777ef39e.png)

Personnellement, je trouve que c'est plus logique ici dans l'en-tête, parce que c'est pas vraiment une info sur l'occurrence en soi

**Comment by camillemonchicourt** [comment]
OK bon bah ça fait un sujet de réglé. :-)

**Comment by camillemonchicourt** [comment]
La partie BDD (trigger et correction des données mises à jour dans Occhab) a été intégrée dans la version 2.12.1.

Reste le fait d'ajouter le filtre par habitat dans les filtres avancés de la Synthèse.

**Comment by bouttier** [comment]
Le bug initialement décrit par cette issue est bien résolu. Peut-on ouvrir une autre issue pour cette demande de fonctionnalité de filtre par habitat ? Ça évite de devoir relire l’ensemble des discussions à chaque fois pour comprendre pourquoi l’issue d’un bug résolu est encore ouverte :-)
