### ISSUE TITLE
Mail de validation seulement envoyé au premier destinataire

### ISSUE THREAD

**Issue by rgilh-geomatys** [PnX-SI/GeoNature#2389]
**Version**
Geonature 2.11.0

**Description du bug**
Après avoir renseigné les destinataires dans `VALIDATOR_EMAIL` et configuré l'envoie de mail, le mail de validation n'est envoyé que au premier destinataire spécifié.

**Comportement attendue**
Le mail de validation est envoyé à tous les destinataires spécifiés.

**Comment reproduire**
- Configurer l'envoie de mail en désactivant la création de compte automatique
- Remplir le champ `VALIDATOR_EMAIL` comme spécifié dans le fichier d'exemple
```
    VALIDATOR_EMAIL = """
        Exemple1 <exemple1@exemple.com>,
        Exemple2 <exemple2@exemple.com>
        """
```

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.13.0
