### ISSUE TITLE
Intégrer la liste des communes dans le POST du contact

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#239]

**Comment by amandine-sahl** [comment]
Si j'ai bien compris l'idée est que lors de l'insertion le json contienne les communes?

**Comment by TheoLechemia** [comment]
Yes c'est ça. 


		Théo LECHÉMIA 
Développeur WEB et bases de données (GeoNature) 

Parc national des Écrins 
Tél : +33 (0)4 92 40 20 38 
[ http://www.ecrins-parcnational.fr/ | www.ecrins-parcnational.fr ] 


De: "amandine-sahl" <notifications@github.com> 
À: "PnX-SI/GeoNature" <GeoNature@noreply.github.com> 
Cc: "Théo Lechémia" <lechemia.theo@gmail.com>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 7 Septembre 2017 17:24:13 
Objet: Re: [PnX-SI/GeoNature] Intégrer la liste des communes dans le POST du contact (#239) 



Si j'ai bien compris l'idée est que lors de l'insertion le json contienne les communes?

**Comment by camillemonchicourt** [comment]
On a décidé de ne pas poster les communes dans le CONTACT. 
Ce sera fait en trigger au niveau de la synthèse.
