### ISSUE TITLE
[GN 2.11.2] Erreur 404 - Chargement de l'api de Monitoring

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature#2398]
**Version**
2.11.2

**Description du bug**
Erreur 404 lors du chargement de la route https://mongeonature.fr/api/monitoring/config
Après montée en version 2.11.2 à partir de la version 2.10.4 et mise à jour du module monitoring en 0.4.1
Les modules ne se chargent pas

**Comportement attendue**
Chargement du module monitoring

**Comment by pierre56** [comment]
Bonjour @maximetoma,
J'ai fait la maj de la 2.11.1 hier et j'ai eu le mm soucis.

Pour le résoudre, dans la table gn_commons.t_modules.
Il faut modifier le champs module_path et passer de "MONITORINGS" a "monitorings"
pour les différents modules.

J'espère que cela va t'aider :)

**Comment by maximetoma** [comment]
Merci beaucoup @pierre56 !

Mon problème était légèrement différent, au lieu de "MONITORINGS", de mon côté il était écrit "monitoring" sans le s

Je n'ai pas fait attention si le module_path avait cette valeur avant ou si c'est avec la mise à jour qu'il y a le s qui est oublié

Cependant, je n'ai pas pu redémarrer geonature-worker.service, il n'existe pas chez moi...
Failed to restart geonature-worker.service: Unit geonature-worker.service not found.

Après je n'ai pas fait la MAJ avec Docker, est-ce que c'est un service spécial pour Docker ? Ou rien à voir ?

**Comment by pierre56** [comment]
Si je peux aider, c'est avec plaisir 😄 

J'ai souvent eu des soucis avec cette table et les conventions de nommages variables pour les modules (lower/upper et singulier/pluriel) et donc les appels url.
D'après ce que j'ai pu voir dans les derniers changelog, la norme est désormais en minuscule pour tout et d'habitude au singulier (sauf pour monitorings apparemment^^).

Concernant le worker, je n'utilise pas docker et je ne me rappelle plus ce que fais précisément ce worker 😅 
Il me semble qu'il s'agit de gunicorn ou des logs, faut que je retrouve son utilité, Je relance tout les services par habitude.

**Comment by mvergez** [comment]
Bonjour,

Pour apporter des précisions sur le `geonature-worker` c'est un service (au sens de `systemd`/`systemctl`) permettant d'exécuter des tâches de façon séparée par rapport au backend (pour ne pas bloquer le backend avec des processus longs). Il utilise pour cela `celery`. Ce worker a, il me semble, été introduit avec le module d'import pour traiter les imports en tâche de fond sans perturber le backend. Et donc a été ajouté à GeoNature 2.10.0 . Je ne crois pas qu'il soit utilisé sur d'autres modules mais je me trompe sûrement !

Dans ton problème, le service n'est pas trouvé, il n'a pas du être créé ou l'activé lors de tes mises à jour. Il est dispo ici si tu veux l'ajouter : https://github.com/PnX-SI/GeoNature/blob/master/install/assets/geonature-worker.service en s'inspirant de ce script d'installation : https://github.com/PnX-SI/GeoNature/blob/master/install/02_configure_systemd.sh pour l'ajouter à systemd.

Celery doit aussi utiliser un "message broker" et ici c'est Redis, l'as-tu installé comme préconisé dans la version 2.10.0 (`# sudo apt install redis`) : https://github.com/PnX-SI/GeoNature/releases/tag/2.10.0 ?

**Comment by maximetoma** [comment]
Merci @mvergez !

Oui redis est bien installé
J'ai repris les éléments comme tu m'a dit et geonature-worker ne veux pas se lancer, j'ai peut être oublié quelque chose

![image](https://user-images.githubusercontent.com/66769358/225927828-c3267117-f281-41d6-bbc3-ce7395cea524.png)
![image](https://user-images.githubusercontent.com/66769358/225927901-6514a524-405b-4040-904b-590161af0dc0.png)

**Comment by camillemonchicourt** [comment]
J'y connais rien au worker.
Tu peux éventuellement regarder ses logs, mais ça dira surement la même erreur que celle affichée dans la capture que tu as fourni : ``nano /var/log/geonature/geonature-worker.log``

**Comment by maximetoma** [comment]
Je n'ai aucun fichier de log de créé pour le worker 🙃

**Comment by mvergez** [comment]
J'ai l'impression que Celery n'est pas installé dans le venv de GeoNature... Pourtant il est bien dispo dans les requis : https://github.com/PnX-SI/GeoNature/blob/6e6e90382484f9d616c03ff73cfb934da3656ed4/backend/requirements-common.in#L1

Tu as utilisé le script migration.sh pour faire la migration avant la 2.10.4 ?

**Comment by maximetoma** [comment]
Ma montée de version de la 2.9 vers 2.10 remonte à trois mois, normalement j'ai bien suivi les notes de version

Dans mon repertoire geonature actuel, j'ai un dossier celery dans `/home/<user>/geonature/backend/venv/lib/python3.9/site-packages`

![image](https://user-images.githubusercontent.com/66769358/225959062-1aa39911-c72a-4ece-880f-41bbac9f1627.png)

**Comment by mvergez** [comment]
Ahhh je viens de voir ! Il te manque `/home/<user>/geonature` avant `/backend/venv/bin/` après le ExecStart dans ton service. Il faut que tu édites le fichier de ton service.
Tu as dû oublier de remplacer le `BASE_DIR` par `/home/<user>/geonature` ici : https://github.com/PnX-SI/GeoNature/blob/6e6e90382484f9d616c03ff73cfb934da3656ed4/install/assets/geonature-worker.service#L11-L21

**Comment by maximetoma** [comment]
Bien vu ! Merci beaucoup il s'est bien activé cette fois-ci :)

**Comment by camillemonchicourt** [comment]
Ce fichier est censé être généré automatiquement si j'ai bien suivi.
C'est pas normal il me semble qu'il ne soit pas correctement rempli automatiquement. 
A voir si il y a un soucis quelque part.

**Comment by gildeluermoz** [comment]
Je n'ai pas creuser le sujet pour le moment, je reviendrai vers vous après analyse plus fine mais sur 2 de mes instances qui sont en 2.11.2 mais avec des montées de version progressives depuis au moins la 2.7.5 le service geonature-worker est absent. Alors que sur des instances créées initialement en 2.11 ou en 2.9, je n'ai pas ce souci.
Il faut que je vérifie les différents contextes mais il semblerait que ce service ne soit pas ou pas bien créée lors de migrations.

**Comment by mvergez** [comment]
Effectivement, sur une installation depuis zéro il est bien configuré.
C'est étrange car il y a bien ici : https://github.com/PnX-SI/GeoNature/blob/6e6e90382484f9d616c03ff73cfb934da3656ed4/install/migration/migration.sh#L128-L131
l'appel au script permettant de créer le service geonature-worker : https://github.com/PnX-SI/GeoNature/blob/6e6e90382484f9d616c03ff73cfb934da3656ed4/install/02_configure_systemd.sh#L22
Peut-être que ce dernier plante avant l'exécution de cette ligne...

**Comment by gildeluermoz** [comment]
Je ne sais pas trop à quoi correspond ce `mode = prod ` mais est-ce qu'il n'y aurait pas un lien avec ceci dans l'execution de `geonature/install/02_configure_systemd.sh`

```
if [[ "${MODE}" != "prod" ]]; then
    echo "Skip configuration of systemd as not in prod mode"
    exit 0
fi
```
Donc une sortie silencieuse.

OU ici 

```
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
. "${SCRIPT_DIR}/utils"
```
Dans la récup de `utils` ou plus généralement dans la récupération des paths dans le contexte de la migration.
En gros dans le contexte de l'installation initiale `install_all.sh` , tjs depuis `/home/user/` , ça fonctionne bien mais dans la migration, il peut y avoir des variantes.
L'installation initiale se fait depuis la racine du `/home/user/ ` mais la migration peut être lancée depuis la racine du `/home/user/` ou depuis n'importe ou ailleurs comme `/home/user/geonature/` ou `/home/user/geonature/install/`. Est-ce que ces variantes sont bien gérées pour la récupération du `settings.ini` ?

Il y a aussi un pb avec les logs, (la suite du script). Dans la dernière instance que j'ai migrée et où le worker ne fonctionne pas, j'ai aussi les anciens logs qui ont bien été déménagés dans `/var/log/geonature/geonature.log` mais après migration, les nouveaux logs s'écrivent tjs dans le fichier `/var/log/geonature.log` ...???

**Comment by camillemonchicourt** [comment]
OK la piste du `mode=prod` est surement la bonne.
Ce paramètre a été ajouté au fichier `settings.ini` dans la 2.8.0 : https://github.com/PnX-SI/GeoNature/commit/4cacdd48e12f2a85467264d2583211d65bf3a0c0

Mais ceux qui ont mis à jour depuis les versions d'avant, n'ont pas ajouté ce paramètre dans leur fichier `settings.ini`...

Et donc si ce paramètre n'est pas renseigné, alors `if [[ "${MODE}" != "prod" ]];` est vrai et donc ça zappe ce que fait ce fichier `02_configure_systemd.sh`.

On a corrigé ça ailleurs en inversant la condition en `if [[ "${MODE}" = "dev" ]];` dans plusieurs fichiers comme on voit ici : https://github.com/search?q=repo%3APnX-SI%2FGeoNature%20%24%7BMODE%7D&type=code, mais pas celui-ci.

Donc ceux qui ont installé GeoNature avant la 2.8.0 ont ce soucis, car ils n'ont pas le paramètre `mode=prod` dans `settings.ini`

**Comment by bouttier** [comment]
C’est corrigé en février 2023 via 9d118b937e

**Comment by gildeluermoz** [comment]
Merci @bouttier pour cette correction importante. Les corrections à opérer sur ce point suite à migration ne sont pas facile à opérer.
Est-ce qu'il est possible d'ajouter une note de version à ce propos dans les releases antérieures ?

**Comment by camillemonchicourt** [comment]
A priori rien de spécial à faire car le script 02_configure_systemd.sh est exécuté dans le script migration.sh, donc cela remis au carré par la prochaine exécution du script migration.sh, à venir très bientôt dans la 2.12.0.

**Comment by bouttier** [comment]
Je confirme que le script `02_configure_systemd.sh` sera exécuté par le script `migration.sh` donc tout rentrera dans l’ordre lors de la prochaine migration (ou de l’exécution manuel du script `02_configure_systemd.sh`).
