### ISSUE TITLE
[GN 2.11.2] : Occhab api /habref/typo 'CorListHabitat' is not defined

### ISSUE THREAD

**Issue by cen-cgeier** [PnX-SI/GeoNature#2405]
Bonjour à tous,
**Version**
Version de GeoNature affectée par le bug.
2.11.2

**Description du bug**
J'ai activé le paramètre `ID_LIST_HABITAT = 1` dans le fichier de configuration de Occhab `geonature/contrib/gn_module/occhab/config/conf_gn_module.toml`.

Après mise à jour des configurations `geonature update-configuration,` l'application web renvoie une erreur serveur :
![image](https://user-images.githubusercontent.com/96542451/226310740-a4026585-995f-4a23-812c-5dd670a9f919.png)

**Comportement attendue**
Le renvoie de la liste configurée dans le module Occhab sans erreurs côté serveur.

**Comment reproduire**
définir le paramètre `ID_LIST_HABITAT = 1` dans le fichier `geonature/contrib/gn_module/occhab/config/conf_gn_module.toml`

**Logs**
``` py
[2023-03-20 10:20:01 +0100] [791878] [ERROR] Exception on /habref/typo [GET]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/utils_flask_sqla/response.py", line 19, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/pypn_habref_api/routes.py", line 139, in get_typo
    .join(CorListHabitat, CorListHabitat.cd_hab == Habref.cd_hab)
NameError: name 'CorListHabitat' is not defined
```
**Tentative de résolution**
En explorant les différents models, j'ai remarqué que la définition de la table `cor_list_habitat` dans le fichier `pypn_habref_api/models.py` ne correspond pas à l'objet attendu dans la fonction `get_typo()` du fichier `pypn_habref_api/routes.py`.
j'ai donc tenté de modifier la requête tel que suit :
``` py
...
from pypn_habref_api.models import (
    Habref,
    AutoCompleteHabitat,
    TypoRef,
    CorespHab,
    BibHabrefTypoRel,
    cor_list_habitat,
)
...
    if params.get("id_list"):
        sub_q = (
            DB.session.query(Habref.cd_typo)
            .select_from(Habref)
            .join(cor_list_habitat, cor_list_habitat.c.cd_hab == Habref.cd_hab)
            .distinct(Habref.cd_typo)
            .filter(cor_list_habitat.c.id_list == params.get("id_list"))
        )
        q = q.filter(TypoRef.cd_typo.in_(sub_q))
```
Après execution de la commande `sudo systemctl restart geonature`. Tout semble rentré dans l'ordre.
Qu'en pensez-vous ? 
Souhaitez-vous que je fasse une PR sur la branche `develop` de [Habref-api-module](https://github.com/PnX-SI/Habref-api-module).

**Comment by bouttier** [comment]
Bonjour,
Merci pour le retour. J’ai profité de l’occasion pour simplifier le filtre en utilisant l’ORM : https://github.com/PnX-SI/Habref-api-module/commit/d5b1c8c8147edc58588742df0a6c0cd25535c0d3
