### ISSUE TITLE
Intégrer la liste des communes dans le GET du contact

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/GeoNature#241]

**Comment by gildeluermoz** [comment]
Est-ce qu'on ajoute un champ ``active``
L'idée : 
on garde toutes les communes de France dans la table ce qui permet de saisir hors territoire.
on active les communes du territoire grace à un intersets avec le geom du territoire (TODO)
on peut mettre à jour le geom des communes du territoire si on a mieux que la couche fr du admin-express
on peut activer comme on veut d'autres communes.

**Comment by camillemonchicourt** [comment]
Je pense que c'est dommage de garder toutes les communes de FRANCE dans le référentiel. 
Ça va alourdir la BDD, sa sauvegarde et les intersections, non ?
Et ça fait des manips en plus à faire pour activer/désactiver les communes que l'on souhaite utiliser. 
Rien n'empêche d'avoir un territoire un peu élargit pour pouvoir saisir en dehors de celui-ci. 
Par contre dans toutes les modules de recherches où on pourra chercher que par commune, on pourra faire en sorte de ne lister que les communes qui ont au moins UNE donnée.

**Comment by amandine-sahl** [comment]
Ce serait bien de rajouter le champ source dans ref_geo.l_municipalities
pour savoir d'où viennent les données et par conséquent leur précision.

**Comment by gildeluermoz** [comment]
Est-ce que si on le met dans bib_areas_types qui décrit chaque type de zone ça le ferait ? Considérant que toutes les communes ont une source et une précision communes.

**Comment by camillemonchicourt** [comment]
`bib_areas_types` normalement c'est que lié à `l_areas`. A discuter donc si on le relie aussi à `l_municipalities`.

**Comment by gildeluermoz** [comment]
heu non ! Faudrait faire un MCD de ``ref_geo`` pour que ce soit plus clair.
``bib_area_types`` décrit les ``l_areas`` et ``l_municipalities`` est une fille de ``l_areas``

**Comment by camillemonchicourt** [comment]
Oui oui j'ai compris entre temps avec notre discussion d'hier. Et mis le ticket https://github.com/PnX-SI/GeoNature/issues/245

**Comment by amandine-sahl** [comment]
obsolète

**Comment by camillemonchicourt** [comment]
Il y a quand même la partie sur la manière de gérer les communes du territoire. On garde totu avec un champs `active` ? On découpe avec le territoire ? Autre ?

**Comment by camillemonchicourt** [comment]
OK c'est noté dans un ticket dédié #275
