### ISSUE TITLE
Synthèse : filtres statuts + commune renvoie toujours "No data to display"

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#2416]
**Version**
2.11.2

**Description du bug**
Lorsque l'on requête en synthèse avec un statut taxonomique + une commune, l'application retourne un résultat vide.
Si l'on cumule statuts + observateurs, ça fonctionne
Si on cumule statuts + département ça fonctionne
Si on cumule statuts + région ça ne fonctionne pas

**Comportement attendue**
Un retour des observations répondants aux combinaisons de critères

**Comment reproduire**

- Faire d'abord la requête sur une commune contenant des données. 
- Parmi les résultats : ouvrir la fiche d'une observation contenant un taxon ayant un statut (en vérifiant dans l'onglet taxonomie de la fiche d'obs)
- Noter un des statuts (par exemple "Liste rouge nationale : Préocupation mineure")
- Ajouter un critère de filtre avec le statut noté.
- Relancer la requête.

Exemple sur https://demo.geonature.fr/geonature/#/synthese

- commune : Seignosse (40) --> renvoi 4 résultats dont la salamandre tachetée en liste rouge nationale avec Préocupation mineure
- ajouter le filtre Liste rouge nationale : Préocupation mineure --> **"No data to display"**
- retirer la commune et ajouter "Administrateur test" dans observateur --> 268 résultats
- retirer l'observateur, ajouter un cadre d'acquisition : Contact aléatoire tous règnes confondus --> 70 résultats
- retirer le filtre statut et ajouter le fitre sur la commune "Valjouffrey" --> 1 résultat
- 

On peut ainsi tester différentes combinaisons de filtres en s'assurant toujours que la combinaisons doit renvoyer au moins un résultat

**contrôles réalisés**
les areas utilisées comme filtres sont `enable = true` dans `ref_geo.l_areas`
les areas utilisées comme filtres sont présentes dans `gn_synthese.cor_area_synthese`
Chacun des filtres utilisé seul renvoie bien des résultats

**Comment by gildeluermoz** [comment]
Un autre utilisateur m'a pointé le pb et demandé de supprimer le filtre par commune pour éviter toute ambiguïté sur la raison amenant à ce que la requête ne retourne aucun résultat : bug ou réellement aucun résultat.

**Comment by camillemonchicourt** [comment]
Reproduit en 2.12.0.
Il vaudrait mieux identifier le soucis et le corriger.
Surtout que les communes sont dans la même table que les départements et régions...

**Comment by amandine-sahl** [comment]
Effectivement il y a un soucis dans la construction des requêtes, tous les filtres se mélagent, ce qui fait que les résultats renvoyés ne sont pas congruents.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.12.1, qui améliore globalement les recherches avec des statuts de protection, les résultats et les performances.
Explications dans la PR - https://github.com/PnX-SI/GeoNature/pull/2450
