### ISSUE TITLE
Synthèse : timeout si beaucoup de résulats

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#2417]
**Version**
2.11.2

**Description du bug**
sur une instance avec 130 000 observations, 
si je filtre sur liste rouge : en danger --> j'obtiens un résultat en qq secondes
si je filtre sur liste rouge : préocupation mineure --> j'obtiens un timeout : 

```
HttpErrorResponse
Http failure response for https://mondomaine.fr/geonature/api/synthese/for_web: 502 Proxy Error 
```
Le serveur est un VPS 2016 avec 8 Go de Ram

**Comportement attendu**

- Un message plus clair pour comprendre que c'est un timeout
- Permettre à la requête d'aboutir dans les 30 secondes par défaut

**Comment reproduire**
tester des requêtes sur de grosses instances avec : "liste rouge nationale : préocupation mineure"

**Comment by camillemonchicourt** [comment]
OK je capte pas pourquoi selon le type de liste rouge, cela aboutit ou non. 
Mais je ne connais pas bien la BDC statuts et elle a différentes limites.
A creuser si c'est optimisable ?

Pour le message du Timeout plus explicite, fait ici si j'ai bien compris - https://github.com/PnX-SI/GeoNature/issues/2419

**Comment by camillemonchicourt** [comment]
Message du timeout amélioré dans la 2.12.0.

**Comment by gildeluermoz** [comment]
Oui c'est ça. 
Ce sujet du timeout est récurrent et peu compréhensible pour l'utilisateur. Est-ce qu'il ne faudrait pas l'augmenter par défaut ?
Plutôt qu'un timeout qui stop tout et retourne une erreur, est-ce qu'il existerait un moyen de proposer à l'utilisateur de prolonger ou stopper le process ?

**Comment by camillemonchicourt** [comment]
A priori la recherche par statut a été revue et optimisée dans la 2.12.1.
Cela corrige le soucis ?
