### ISSUE TITLE
Module observation citoyenne

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#242]
Plusieurs structures souhaitent pouvoir mettre en place des programmes d'observation (Contact) citoyenne connecté à GeoNature. 

Exemple de proposition @sig-pnrnm : 

> L'idée est d'avoir une page de saisie la plus épurée/simple possible, avec entrée principale par photos (qui réponde à la question "m'as-tu vu").
> Exemple : une galerie de photo issue de GeoNature-atlas (sélection d'espèces faciles à reconnaitre, d'espèces patrimoniales et/ou peu notées) : quand on clique sur une photo, ça ouvre le formulaire de saisie qui demande la date et le lieu (option effectif et option commentaire).
> Du basique de basique, le plus simple possible, car le public visé est scolaire + élu + très grand public.
> 
> Dans la logique de GeoNature (si vous pensez que cela peut l'intégrer), cela pourrait se faire via un nouveau protocole.

**Voici les premiers éléments proposés/discutés :** 

- Mettre en place un module dédié (avec son propre dépôt donc)
- Le concevoir de manière générique pour pouvoir l'utiliser pour plusieurs programmes, groupes, taxons...
- Le module aurait une interface simple dédiée mais alimenterait un schéma dans la BDD de GeoNature
- Ne pas imposer la création d'un compte pour saisir des données mais éventuellement la rendre possible pour proposer des services avancés

**Voici ma première proposition :** 

- Un programme s'appuie sur une liste de noms créée dans TaxHub. Cela permet de choisir la liste des taxons du programme (éventuellement de proposer aussi des synonymes).
- TaxHub permet aussi d'associer des photos et attributs de description aux taxons que l'on pourra réutiliser
- Le module propose une page d'accueil avec des blocs paramétrables/customisables/masquables comme GeoNature-atlas (Texte d'introduction, Statistiques, Carte des dernières observations...). Cette page d'accueil propose l'accès à la saisie d'observations
- Dans une première version, la création d'un compte n'est pas nécessaire pour saisir une donnée pour ne pas freiner et complexifier la participation
- Un schéma de BDD par défaut minimal est proposé : 
   - Observateur (champ libre mais auto-completion si l'observateur a déjà été utilisé pour une précédente obs)
   - Email / téléphone observateur (optionnel)
   - Date
   - Taxon observé. 3 cas. Soit le programme ne concerne qu'un seul taxon et ce champ n'est pas affiché, soit il concerne un petit nombre d'espèce et elles peuvent être affichés sous forme de mur d'images (venant de TaxHub), soit on affiche une liste classique en utilisant le composant taxonomy de GeoNature V2
   - Champs commentaire/remarque
   - Pointage sur la carte en localisant sur la carte en utilisant le composant Map de GeoNature V2, avec possibilité d'imposer un zoom minimum pour pouvoir saisir (paramétrable)
- A voir dans un second si le programme nécessite quelques champs spécifiques. Possibilité de mettre en place un mécanisme de pseudo-champs comme on a avec les attributs de TaxHub
- Possibilité de créer des pages HTML d'information (présentation programme, présentation des taxons) sur le modèle de la page de Présentation de GeoNature-atlas

**Comment by camillemonchicourt** [comment]
J'intégrerai aussi une page avec la carte/liste de TOUTES les observations faites dans la cadre du programme. Dès qu'une saisie est faite, elle apparait dans ce module. Ca permet d'être dynamique, réactif et que les utilisateurs aient un retour direct sur leur participation et voit celles des autres, éventuellement s'auto-corrigent...

Le fait de valider les données du programme avant de les intégrer dans la Synthèse, les exports partenaires, l'atlas global... est un autre sujet et concerne la chaine global du GeoNature. Mais au niveau de chaque programme, je trouve ça important que les données ne soient pas verrouillées et bloquées par des attentes de validation.

**Comment by camillemonchicourt** [comment]
J'oubliai aussi les médias (photos ou autre). 
On a prévu de développer un composant media dans GeoNature (pour pouvoir associer une photo, un son à une observation du Contact ou tout autre protocole). 
On pourra réutiliser ce composant Angular pour l'ajout de photo sur une observation d'un programme de Science citoyenne.

**Comment by camillemonchicourt** [comment]
Exemple intéressant : http://urbangene.heig-vd.ch
Dont le code est disponible sur Github : https://github.com/MediaComem/urbangene

**Comment by camillemonchicourt** [comment]
A articuler avec 65MO
http://cesco.mnhn.fr/fr/content/recrutement

**Comment by sig-pnrnm** [comment]
En effet, ça correspond tout à fait à l'idée du projet.
La plaquette de présentation est dispo sur ce lien : [http://vigienature.mnhn.fr/sites/vigienature.mnhn.fr/files/uploads/images/Plaquette65MO_BD.pdf](http://vigienature.mnhn.fr/sites/vigienature.mnhn.fr/files/uploads/images/Plaquette65MO_BD.pdf)
A voir si le(s) module(s) "citoyen(s)" de GeoNature doivent être intégrées au projet 65MO, "labellisés" 65MO, ou rester indépendant (mais complémentaires).

**Comment by camillemonchicourt** [comment]
Je viens d'avoir un échange avec l'équipe de 65MO. 
Le projet se positionne sur les programmes de sciences participatives avec un réseau de participants et d'animateur autour de données protocolées.
Ils vont proposés différents outils créer du lien entre participants, rendre les données visibles entre participants pour créer de l'émulation, du dialogue mais aussi du contrôle qualité des données entre participants. 
Le projet intègre aussi des outils de restitution propres à chaque protocole. 

Actuellement le projet se compose : 
- d'un SGBD (Nuxeo + MongoDB) qui est en NoSQL (description du modèle de données dans un json)
- d'un CMS (CSF - Citizen Science Framework) basé sur Wordpress et PHP Symfony
- d'un portail des sciences participatives qui catalogue les projets et permet de structurer et d'articuler les programmes
- d'une plateforme d'analyse des données (prospective) pour permettre une analyse collaborative des données et des partages de process de traitement et d'analyse

Le projet se concentre donc sur des programmes en réseau liées à des données protocolées et sur la construction de communauté de participants et de dialogue entre eux. 

Il n'y a donc pas de redondance avec notre projet qui n'est pas couvert par 65MO. En effet dans notre cas, il s'agit plutôt de mettre en place une application de signalement (j'ai vu tel espèce à telle date et tel endroit) dans le cadre d'un projet territorial comme un ABC avec un besoin d'ergonomie le plus simple possible.

**Comment by camillemonchicourt** [comment]
Premier maquettage de ce module GeoNature-citizen : 

# 1. ACCUEIL

![gn-citizen-01](https://user-images.githubusercontent.com/4418840/34996702-b1db016c-fada-11e7-8cec-a6860c00d0e1.jpg)

A l'arrivée sur l'application, on affiche une page d'accueil avec un message introductif. Dans l'exemple, elle est proposée sous forme de modale, simple. Cette modale comporte son template HTML que chacun peut modifier avec le contenu souhaité.

Elle pourrait aussi prendre la forme d'une page d'accueil complète qui intégrerait ou non la carte/liste des observations.

# 2. LISTE/CARTE DES OBSERVATIONS

![gn-citizen-02](https://user-images.githubusercontent.com/4418840/34996707-b4f10f4a-fada-11e7-82fc-a606c80c74fb.jpg)

- Elle permet de visualiser l'ensemble des observations faites par les participants au programme. 
- Pour chaque observation on affiche la date, l'espèce (si on est dans le cadre d'un programme multi-espèces), la photo de l'observation, l'observateur (si il a été renseigné), le commentaire de l'observation
- Par défaut on affiche les dernières observations. 
- A voir si on peut afficher toutes les observations présentes dans le programme, si il faut fixer une limite (paramétrable) du nombre d'observations affichables. 
- Quelques filtres sont proposés (masquables au niveau de la configuration) pour filtrer sur une espèce, une période, un observateur.
- Il y a une interaction entre la carte et la liste. 
- La liste n'affiche que les résultats présents sur l'étendue cartographique affichée. 
- Comme dans GeoNature-atlas, 2 fonds carto sont proposés au visiteur : carte/plan (paramétrables dans la configuration du module). 
- Comme dans GeoNature-atlas, il est aussi possible de créer des pages statiques (pages HTML) permettant de présenter le programme, les partenaires, donner des synthèses des résultats, donner des informations sur les espèces...

**PHASE 2 :** 

- Proposer un module de synthèse statistiques des données (nombre d'observations par année...)
- Pouvoir ajouter un commentaire sur une observation existante
- Pouvoir modifier une observation ? Seulement l'auteur d'une observation ou l'administration mais vu qu'on n'a pas d'authentification, on ne peut pas proposer de modification au niveau interface ?

# 3. AJOUT OBSERVATION

![gn-citizen-03](https://user-images.githubusercontent.com/4418840/34996710-b956093c-fada-11e7-990b-8d0620788a0e.jpg)

Depuis la liste des observations ou la page d'accueil, on peut cliquer sur le bouton AJOUTER UNE OBSERVATION pour ouvrir le formulaire de saisie. 

Celui-ci contient les différents champs : 
- Choix de l'espèce si on est dans un programme multi-espèces, sous forme de photos si on n'a que quelques espèces proposées, soit sous forme de liste autocomplétée si on est sur un programme avec un grand nombre d'espèces proposées
- Localisation sur la carte (point uniquement, possibilité de paramétrer un zoom minimum de localisation)
- Date de l'observation (date du jour par défaut)
- Observateur (champs libre optionnel avec auto-complétion des observateurs déjà saisis)
- Email + téléphone observateur (optionnel et non affiché sur l'interface publique)
- Commentaire de l'observation
- Upload d'une photo de l'observation (avec champ légende + auteur optionnel ?)

# 4. ARCHITECTURE et BASE DE DONNEES

- Le module GeoNature-citizen est une application à part entière avec son propre dépôt et sa procédure d'installation
- Sa BDD peut être installée de manière autonome ou son schéma ``gn_citizen`` peut être intégré dans la BDD de GeoNature.
- A voir comment faire si une GeoNature comporte plusieurs modules GN-citizen. Dans le schéma ``gn_citizen``, on pourrait avoir une table qui liste les modules de Collecte citoyenne. 
- Un module s'appuie sur une liste de noms de taxons dans TaxHub (``id_liste`` renseigné dans la conf du module)
- Pour que les données d'un module GN-citizen alimente la synthèse de GeoNature, il faut que le module soit déclaré comme un jeu de données à part entière dans le schéma ``gn_meta`` de GeoNature + un trigger qui alimente le schéma ``gn_synthese`` depuis le schéma ``gn_citizen``

**Comment by samuelpriou** [comment]
A lecture de toutes les très bonnes idées déjà détaillées, voici les points que nous souhaiterions voir pris en compte.
 
**Le système d'identification par la création d'un compte** avec une adresse mail valide nous semble indispensable pour pouvoir utiliser les données recueillies dans ce cadre notamment pour les raisons suivantes :

- possibilité de rattacher toutes les observations a un observateur (formatage du nom toujours identique)
- faciliter le travail de validation (historique de l'observateur, demande d'info complémentaires, ...)
- faciliter le travail d'animation (possibilité de faire un retour mail sur l'intérêt des données, invitations sur des évènements de sciences participatives...).
- offrir la possibilité aux observateurs de modifier et supprimer leurs données (propriété intellectuelle) et respect du RèGlement européen sur la Protection des Données (RGPD).
- répondre au format des données élémentaires d'échange pour faciliter le versement des données issues de ces programmes dans les bases nationales.
- possibilité de se voir attribuer des **badges ou un statut** (comme dans les forums pour les utilisateurs fréquents) - optionnel mais fonctionne bien auprès des utilisateurs.

Il serait utile de pouvoir extraire facilement les adresses mails des contributeurs à la base de données notamment si les données participent à un autre projet (je me souviens que c'était très compliqué pour l'INPN lorsqu'ils ont du mettre toutes les données de cardobs en ligne et de faire le tour de tous les utilisateurs de l'outil qui avaient contribué). Cela permettrait aussi de pouvoir animer le réseau d'observateurs, de partager des découvertes, d'inscrire les observateurs à une newsletter...

Le système de badge peut inciter certains contributeurs à se prendre au jeu en mettant des rangs/grades/statuts/badges/niveau... aux observateurs. Ainsi ont peu imaginé que le nombre d'obervations soit rappelé en dessous du nom de l'observateur, ou un certain nombre de points selon le nombre de données saisie et l'ancienneté de l'observateur; la régularité des observations (3mois d'affilée avec au moins 1 obs, 6mois, 1an...) Désignation du meilleur contributeur de l'année.......... Bref, tout est possible c'est à définir si quelqu'un d'autre pense que c'est une bonne idée.

Il faudrait alors définir une petite charte qui serait envoyée par mail et qui rappelle les conditions dans lesquelles les données peuvent être utilisées par les établissements.

OK pour associer des médias, ça nous semble également indispensable pour faciliter la validation.

OK pour la validation dans la **synthèse**. Cependant la finalité des données de la synthèse en interne est d'offrir une seule table comprenant toutes les données validées qui sont mobilisables pour les portés à connaissance. Il faudrait donc pouvoir s'assurer que des données non validées n'apparaissent pas dans les données utilisées par les différents chargés de missions afin de garder un jeu de données propre et fiable. Il nous semble également que le SINP souhaitent que ces données issues de collecte citoyenne soient mises dans des schémas différents et restent traçables, même une fois validées. Il faut donc s'assurer que cette traçabilité reste possible.

**Comment by camillemonchicourt** [comment]
Concernant le stockage des données, il est bien prévu que le module de Collecte Citoyenne ait son propre schéma avec ses tables propres dans la BDD, mais aussi que ses données alimentent la Synthèse comme les autres modules/protocoles (par trigger). 
Pour avoir une approche unifiée et globale dans GeoNature, on a prévu de valider les données au niveau de la Synthèse, pour ne pas à avoir à développer des interfaces de validation spécifiques à chaque module. 
La Synthèse comprendra donc des données validées/non validées/invalidées mais cela ne prédéfinit pas comment elles seront accessibles et diffusées. 
On pourra par exemple choisir que seules les données validées soient affichées ou exportées, soient diffusées dans l'API public, soient diffusées dans GN-atlas etc...

Concernant l'identification. En effet si elle est imposée, elle permet d'avoir plus d'infos comme tu le mentionnes. Mais elle constitue aussi un frein important à la participation. Par ailleurs, on peut envisager de ne pas avoir d'authentification mais de proposer ou imposer un nom d'observateur. 
Cela sera moins carré et permettra moins de choses que de le gérer proprement dans la BDD. 
Cela ne permettra pas en effet d'avoir des infos sur chaque utilisateur et d'afficher des badges ou nb d'obs etc...

Du coup mon idée initiale était de commencer par un module simple sans identification, puis de l'enrichir dans un second de la possibilité de mettre en place une identification. 
Les 2 seraient ainsi possible au moment de la mise en place du programme de Collecte citoyenne. 

C'est une piste pour proposer en premier lieu un outil plus simple à développer mais aussi plus simple à utiliser puis de l'enrichir. C'est aussi pour pouvoir commencer les développements avec un petit budget puis faire évoluer l'outil. 

Mais pour évaluer le surcout, on peut directement le mettre en option dès le premier cahier des charges.

**Comment by gildeluermoz** [comment]
**D'une manière générale quelles conséquences aura ce module très "à coté" de l'objet principal et professionnel de GeoNature sur le MCD, l'organisation des contenus de la base, les fonctionnalités de GeoNature et notamment les modules synthèse et validation.**

**L'intégration des observations en synthèse est à évaluer avec précaution et pose de nombreuses questions**.
* quid de l'affichage des observations de la collecte citoyenne. Il faut une interface de saisie mais aussi de visualisation dédiée de toutes les données de la collecte citoyenne. Ce qui pose la question de les mélanger ou pas avec les autres connaissances du territoire (synthèse bis ?)
* quid de l'usage des observations en attente de validation ?
* Toutes les structures utilisant GeoNature ne souhaiterons pas forcement avoir le même usage de ces données (atlas, synthèse GeoNature, exports). Il est donc essentiel que tous les usages reposent sur des vues paramétrées selon la volonté de chacun. Mais faire reposer la synthèse (et surtout son indispensable moteur de filtrage) sur une vue pose la question épineuse des performances.

**Autres questions** :
* Faut-il créer les observateurs enregistrés dans le schéma utilisateurs. Si oui ou si non quelles conséquences ?
* Quelle gestion des métadonnées : acteurs (propriétaire, gestionnaire, fournisseur, etc.) , organisme, etc. Mais aussi des droits CRUVED (sans organisme ?).
* Il y a une certaine proximité dans le mode de recueil et pour certaines fonctionnalités avec occtax (notion finale d'occurrence de taxons, preuve numérique, validation, ...). Faut-il factoriser les dev ; quoi et comment ?

**A savoir** : 
* la liste des taxons proposés à la saisie sera forcement limitée par ce qui est présent dans bib_noms. On passe potentiellement à coté de la découverte de taxons nouveaux. A moins de tout proposer et mettre en place un mécanisme d'alerte.

**Comment by camillemonchicourt** [comment]
Les conséquences sont uniquement au niveau de la BDD car tout le module et les interfaces ne seront pas dans GeoNature mais bien à part, à côté, comme GeoNature-atlas. 
Donc il n'y a pas de conséquences. 
Hormis sur la question des observateurs à bien réfléchir. 

Il y aura un schéma gn_citizen dans la BDD GeoNature. 
Libre à chacun de les envoyer dans la Synthèse ou non. Si oui, elles seront traitées comme les autres sources de données. 
La question de la validation, des métadonnées et de l'affichage par exemple ne sera pas différent des autres sources de données.

**Comment by gildeluermoz** [comment]
Si le module validation est générique aussi pour ce module, tu envoies toutes les données de ce module dans la synthèse pour ensuite les valider. Donc dans la synthèse tu mélanges bien citizen et le pro ...
Si tu dis que ça ne pose pas de soucis...

**Comment by sig-pnrnm** [comment]
Merci à vous pour ces échanges très intéressants.
Pour répondre aux inquiétudes de Gil, voici quelques éléments : 

> Donc dans la synthèse tu mélanges bien citizen et le pro ...

En effet oui. Mais n'oublies pas que le module de validation (en cours de développement) ajoute cette notion de "statut de validation" à chaque donnée de la synthèse. Du coup, les données en provenance du module citoyen auront un statut de validation particulier qui permettra de les filtrer pour les utilisations derrière GeoNature (GeoNature-Atlas par exemple).

Ne maitrisant pas tous les tenants et aboutissants de GeoNature, v2 en particulier, je ne vois donc pas en quoi cela poserait un souci ?

Selon les discussions en cours pour le développement du "module validation", il a été retenu de se baser sur la synthèse, mais de construire des filtres de recherche pour la validation. Parmi ces filtres, cela me fait penser qu'il faudra aussi pouvoir filtrer par "module/protocole source", et donc de ne faire la validation que pour (ou pour tous sauf) le "module citoyen".

**Comment by gildeluermoz** [comment]
Si le module citoyen est totalement indépendant, ce n'est donc pas un module comme les autres. Je n'ai pas analysé les conséquences de ça. L'atlas a sa propre base. Il est donc lui totalement indépendant et peut fonctionner sans la base GN.

Il n'y a pas que la validation qui va distinguer ces données. Il faut analyser dans le détails. La synthèse comporte de nombreux champs et lien avec le reste de la base. 
Par exemple ``gn_synthese.defaults_nomenclatures_value`` permet de définir des valeurs par défaut pour certaines nomenclatures quand elle ne sont pas fournies. A voir si c'est toujours identique entre citoyen et pro. Sinon ce sera à définir dans citoyen.
Je repose cette question :
Toutes les structures utilisant GeoNature ne souhaiterons pas forcement avoir le même usage de ces données (atlas, synthèse GeoNature, exports). Il est donc essentiel que tous les usages reposent sur des vues paramétrées selon la volonté de chacun. Mais faire reposer la synthèse (et surtout son indispensable moteur de filtrage) sur une vue pose la question épineuse des performances.
Dit autrement comment faire pour filtrer les données de la synthèse avec un formulaire commun et des volonté d'usage différentes (la synthèse renvoie ou pas les données citoyennes)
quelle politique pour la gestion des données sensibles parmi les données citoyennes

Les datasets et les cadres d'acquisitions sont liés à des acteurs eux même liés à un id_organisme ou un id_role desquels sont déduit le CRUVED, utilisé en synthèse pour savoir quoi afficher. Comment reconstituer ça si on a pas d'utilisateur logué ?

Où seront mis les medias de citizen ? Dans gn_medias ou pas ? Les routes du backend de gn_medias auront besoin d'une authenfication. Il faudrait donc refaire des routes dédiées citizen pour une gestion des médias de citizen sans authentification.

gn_citizen, peut-il/doit-il avoir ses propres listes de taxons. Taxhub ? Lien potentiel entre la synthèse et le schéma taxonomie géré par taxhub; Obligation pour la synthèse de ne connaitre que taxref ?

Pour moi il y a mélange des genres et si on le fait il faut bien évaluer dans quelle mesure le cadre pro va contraindre citizen car on ne fera pas l'inverse.

**Comment by camillemonchicourt** [comment]
En effet, ce n'est pas un gn_module au sens où il s'agit d'un module intégré dans GeoNature mais plutôt d'un outil modulaire pouvant s'intégrer (ou pas) dans l'environnement GeoNature, comme l'atlas. 
En effet l'atlas a sa propre BDD mais elle peut aussi être intégrée à la BDD de GeoNature comme certains ont fait. 

Là ça serait la même logique que l'atlas, mais cette fois-ci en amont, alors que l'atlas est en aval. 

Le module GeoNature-citizen n'aurait pas besoin de GeoNature obligatoirement, mais il aurait besoin de TaxHub. 

Sa BDD pourrait être intégrée à celle de GeoNature ou non. 

Concernant ``gn_synthese.defaults_nomenclatures_value``, beaucoup d'autres données présentes dans la Synthèse n'en auront pas. Toutes les données provenant d'autres sources, comme les données des partenaires par exemple. 

Pour moi les données du module GeoNature-citizen ne sont pas différentes que des données saisies depuis d'autres outils ou fournies par des partenaires. 

Concernant le fait que la Synthèse repose sur une vue, je vois ce que tu veux dire. En effet cela apporterait une souplesse très intéressante mais poserait de gros problèmes de performances non souhaitables. 
Éventuellement elle pourrait s'appuyer sur des vues matérialisées pour apporter de la souplesse tout en gardant les performances. Mais elle nécessiterait de mettre en place des mécanismes de mise à jour des VM. 
A priori je resterait sur l'idée d'une table pour rester simple.

Pour moi, le fait d'avoir des données GN-citizen dans la Synthèse ne pose pas de problème, au contraire. C'est la même chose que des données internes ou partenaires qui ne seraient pas encore validées mais apparaîtraient dans la Synthèse. 
On peut décider de les faire apparaître ou non lors d'une recherche/export au même titre que celles des autres cadres d'acquisition. 
On peut décider de les intégrer ou non dans les exports et bien sur dans les usages comme ceux de GN-atlas. 
Donc le fait de les intégrer/diffuser/exporter se pose après la Synthèse. 

Sinon libre à chacun de ne les stocker que dans le schéma gn_citizen et de ne pas les remonter du tout dans la Synthèse. Ou bien (non souhaitable mais possible) d'ajouter une interface de validation au niveau  du module GN-citizen et de ne les remonter dans la Synthèse qu'une fois validées.

Pour les données sensibles, même traitement que pour toutes les autres données dans la Synthèse. 

Concernant l'organisme, dans un programme de Collecte citoyenne pour moi l'organisme associé est celui qui porte et anime le programme. 
Les observateurs sont ceux saisis au moment de la saisie ou INCONNU si non renseigné. 
D'où l’intérêt de GeoNature V2 qui dissocie les observateurs et les organismes associés à une donnée par l'intermédiaire des métadonnées du jeu de données. 

En effet il y a une réflexion à avoir sur les médias. GN-citizen ne devant pas être dépendant de GeoNature et de sa gestion des médias. Ce qui pousserait à ce que GN-citizen ait son propre système de gestion des médias mais ça serait dommage. 
Cela fait écho avec le questionnement qu'on a eu il y a eu quelques jours, sur le fait d'externaliser la gestion des médias dans un sous-module comme celui des nomenclatures pour pouvoir l'utiliser dans d'autres projets. A voir avec @amandine-sahl 

Concernant les taxons, on est parti sur l'idée qu'une instance de GN-citizen pouvait ne concerner qu'un taxon, qu'une liste de taxons (définie dans TaxHub) où tous les taxons du territoire (taxonomie.bib_noms). Donc en effet il est lié à une liste dans TaxHub. Il pourrait aussi se servir des médias et attributs présents dans TaxHub. Que Taxref à priori.

Pour moi, cela ne pose pas de problème et est juste une source de données externe comme des données saisies dans un autre outil ou fournis par des partenaires. 

Cette réflexion et ces questions sont importantes à se poser mais vont dans le sens de le confirmer.

**Comment by camillemonchicourt** [comment]
- PNM : Besoin OK mais souhait d'avoir authentification
- SMCG : Besoin OK, sera utilisé que pour faune, car flore sera fait avec Telabotanica. Authentification en option, pas d'urgence sur le sujet
- PNRNM : Missions sous forme de jeu, application mobile Android/iphone, à priori sur la base de l'application Noé.

A noter aussi : 

- Dans le cas d'une saisie possible sur plusieurs taxons, pouvoir filtrer par groupe
- Mettre l'authentification en option avec toutes les fonctionnalités qui vont avec (création de compte, gestion des droits, espace Mon compte, voir mes données....)

**Comment by AudreyEnGuyane** [comment]
Bonjour à tous,

Pour le PAG, il serait question d'ouvrir la saisie dans le cadre de l'ABC de Saül (dans un premier temps). Les groupes taxo à couvrir seront multiples mais, d'après les échanges que j'ai pu lire, ce sera géré par TaxHub. Donc je ne vois pas de soucis si on peut faire la saisie dans un même module (qu'il s'agisse d'un oiseau, d'un escargot ou d'un champignon...). Mais je m'interroge: quelle différence entre un agent connecté et un habitant/visiteur connecté lors de la saisie? A part le cadre....

Au vu du réseau web qui règne sur notre territoire, le principal réseau utilisé est le réseau téléphonique & 3G (ou plutôt 0,3G...). Donc pour nous, il serait primordial que l'appli mobile prenne en charge cette saisie citoyenne.

Je tiens à souligner qu'ajouter la possibilité de joindre un média me semble important car il sert à la validation de la donnée. En contexte tropical (qui plus est en forêt amazonienne), ça change grandement la donne...

**Comment by camillemonchicourt** [comment]
L'idée là est de proposer une interface très simple et accessible en dehors de GeoNature. 
Pour des partenaires, on peut en effet, tout à fait imaginer les faire saisir directement dans GeoNature. Dans ce cas pas besoin de ce module GeoNature-citizen. 

En effet dans le module GN-citizen, on pourra définir des listes de taxons saisissables grâce à TaxHub. 1 module GN-citizen = 1 liste TaxHub

Attention, il s'agit d'une application web et non pas mobile.

Oui pour l'ajout de médias, c'est prévu.

**Comment by AudreyEnGuyane** [comment]
> Attention, il s'agit d'une application web et non pas mobile.

Mince. Voilà qui va être fâcheux pour nos projets de saisie citoyenne dans un village sans web et autres sites isolés.
Je vais aller explorer l'étendue du projet mobile pour en savoir plus. Ça m'évitera de faire des hors-sujets...

**Comment by camillemonchicourt** [comment]
Si vous voulez financer la déclinaison GN-citizen-mobile c'est avec plaisir !

**Comment by samuelpriou** [comment]
**Spécifications du module d'authentification de GeoNature-citizen** 

**Spécificités à l'installation :**

Lors du déploiement de l'application, la structure doit pouvoir choisir le mode d'authenfication souhaité :

- Authentification obligatoire
- Authentification facultative
- Pas d'authentification

**Création des comptes utilisateurs :**

Lorsque l'utilisateur arrive sur le site GeoNature-citizen, celui ci doit avoir la possibilité de créer un compte en fonction du type d'installation choisi.
Si l'utilisateur souhaite créer un compte alors une interface permet de créer ce compte.

Lors de l'enregistrement de l'utilisateur, les champs sont :

- un login *
- un mot de passe *
- un nom *
- un prénom *
- une adresse mail valide *
- une structure (optionnel)
(*) champs obligatoires

Avant la confirmation de validation du compte :
- l'utilisateur doit accepter la charte d'utilisation de l'application et des données (export des données vers les partenaires et le SINP) et des photos (photos libres de droit par défaut)
- l'utilisateur choisi ou non de s'abonner à une newsletter

A la fin de la création du compte, un mail de validation est envoyé à l'utilisateur pour vérifier la validité de sa boite mail. L'utilisateur valide le compte en cliquant sur le mail réceptionné.
Si l'utilisateur a oublié son mot de passe ou son login, un lien de réinitialisation lui est renvoyé par mail en saisissant l'adresse mail.

**Tableau de bord / compte de l'utilisateur :**

C'est l'interface qui permet à l'utilisateur d’accéder aux informations qui le concernent. L'utilisateur y accède soit via un lien “Mon compte” soit en cliquant sur son login depuis l'écran de collecte citoyenne.

Il permet alors la consultation(C) et/ou la modification des données suivantes (M):
- un login (C)
- un mot de passe (C/M)
- un nom (C)
- un prénom (C)
- une adresse mail valide (C/M)
- une structure (C/M)

Possibilité de supprimer le compte et les données qui y sont associés (RGPD) ???

Il permet aussi d'accéder à ses statistiques :
	- nombre d'observation par groupe (flore, vertébrés, invertébrés).
	- nombre de taxons différents observés
	- ancienneté de l'inscription
	- voir ses badges

Il permet de réaliser un export des données au format .ods reprenant tous les champs renseignés par l'observateur mais pas les données renseignées à posteriori comme la validation de la donnée.

**Administration de l'authentification :** 

2 niveaux d'administration

1) administrateur (création/modification/suppression des animateurs + droits des animateurs)

2) animateur
- création/modification/suppression des utilisateurs
- création/modification/suppression des données
- création/modification/suppression des badges automatiques et manuels
- attribution suppression des badges pour les utilisateurs
- gestion de l'abonnement à la newsletter
- accès à un outil d'extraction des utilisateurs par groupe et notamment une liste d'adresses mail utilisable dans zimbra

**Gestion des badges:** 

Les badges sont une forme de récompense attribuée à l'utilisateur pour sa contribution. Il doit être composé de deux systèmes.

Un système automatique (paramétrable par les animateurs) qui attribue des badges aux utilisateurs en fonction de leurs statistiques:
- nombre de données (par exemple: or>5k données, argent>1k données, bronze>100 données)
- ancienneté du compte (par exemple: œuf=7j, chenille=6mois, papillon=1an)
- mission réussie (pour des journées spécifiques voir plus bas)

Un système manuel (paramétrable également par les animateurs) qui permet de regrouper les utilisateurs dans plusieurs catégories, par exemple: observateur fiable, observateur non fiable, scolaire, AEM partenaire...)

Les animateurs doivent pouvoir créer de nouveaux badges automatiques en définissant les seuils de déclenchements de ces badges selon les éléments suivants:
- cibler sur un plusieurs taxons (par exemple: les oiseaux, la vanesse des pariétaires, la faune, la flore, tout)
- définir un seuil de nombre d'observations à partir duquel il se déclenche (de 1 à n)
- définir des bornes de dates pendant laquelle l'obtention est possible pour créer des évènements (muguet le 01/05, marathon des oiseaux...)
Ils doivent pouvoir créer des badges manuels également qui sont gérés sous la forme de liste.

**Comment by camillemonchicourt** [comment]
OK, merci pour ces compléments. 
Un point important est à définir : GeoNature V2 est construit pour pouvoir ouvrir la saisie/consultation de certains modules à des partenaires (assos, structures partenaires, protocoles partagés...). 
Dans ce cas là, on utilise les fonctionnalités de GeoNature V2 et la gestion des droits associées (CRUVED par module) intégrée dans UsersHub. 

Dans le cas du module GN-citizen avec authentification, il semblerait que des partenaires soient aussi ciblés. Néanmoins la gestion des utilisateurs et organismes sera décorrélée de GeoNature et UsersHub donc il n'y aura pas de rapprochement possible (ID différents notamment).

**Comment by orovellotti** [comment]
Deux remarques :

1/ gamification: les badges doivent êtres décernés de manières non linéaires. Je m’explique, c’est une forme de valorisation inattendue qui doit surprendre et valoriser surtout les premières contributions. Pour faire avancer les contributeurs dans la courbes des contributions.

Il faut aussi prévoir un système linéaire, du type points et surtout leader board qui fonctionne très bien pour les gros contributeurs

2/offline: on doit pouvoir imaginer des solutions en progressive web app pour travailler en offiline partiel sans faire une application.

Bises 
Olivier

**Comment by samuelpriou** [comment]
Merci Olivier pour ces remarques intéressantes.
Nous conserverons probablement ces idées lors de la rédaction du CCTP.

**Comment by DonovanMaillard** [comment]
Bonjour à tous, 

Je débarque un peu en retard sur les débats mais j'essaie de rattraper le train en marche. 

Quid de la gestion par un organisme de plusieurs enquêtes distinctes? On aurait 2 portails? 2 onglets ou 2 pages sur un même portail? 

Concernant les champs, est-ce qu'une preuve d'existence peut être prévue? Sous forme de pseudo-champ, ou se gère autrement? Je prends l'exemple du projet citique qui nécessite une collecte et une remontée des tiques à l'INRA grand est. 

Je sors un peu du cadre et ma remarque aurait davantage sa place coté synthèse mais puisque c'est abordé ici : on aura dans la synthèse des données valides, invalides, non validées : possibilité de gérer un paramètre de requpetes "données validées uniquement" coché par défaut pour éviter effectivement que toutes les données afffichées soient prises pour argent comptant comme une "réparition", ou qu'un coup d'oeil rapide donne "ouais, l'espèce est présente à tel endroit" ? 

Concernant l'affichage des données citoyennes dans la synthèse, idem : on peut imaginer que cette source de données soit décochée par défaut? (avec un paramètre à l'install pour laisser le choix à la structure par exemple ? Une asso risquera de cocher oui là ou un PNR ou PNx cochera le plus souvent non à priori ? )
Coté authentification, pour une question d'animation de réseau, de retours sur investissement pour les contributeurs et de RGPD aussi, l'adresse mail semble intéressante à collecter en effet. Après, si ca se rentre dans usershub comme demandé par Gil, la table utilisateur risque de devenir un joyeux bordel avec les "j'ai oublié mon compte 11 fois, j'en fais un 12eme" et donc 12 ID observateur différents par exemple. Utiliser l'adresse mail seule comme "ID" (comme login en gros) peut être une solution? 

Merci au PAG de financer l'application mobile! (ha non, j'ai mal compris? ;) )

**Comment by camillemonchicourt** [comment]
Les développements ont commencé et les discussions continuent dans le dépôt dédié au projet : https://github.com/PnX-SI/GeoNature-citizen

**Comment by camillemonchicourt** [comment]
Une consultation vient aussi d'être lancée : http://www.mercantour-parcnational.fr/fr/documents/developpement-dune-application-web-de-collecte-citoyenne-en-lien-avec-geonature

**Comment by camillemonchicourt** [comment]
Détails, corrections et évolutions dans le dépôt de l'application : https://github.com/PnX-SI/GeoNature-citizen
