### ISSUE TITLE
[OCCTAX] - relevesList : erreur si digitiser === null

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#2421]
Même si le fait d'utiliser l'app pour saisir ses données fait que le digitiser est toujours renseigné, il peut arriver (sur un transfert de la synthèse à occtax par exemple) que cette info soit absente de la donnée. En BD la contrainte NOT NULL n'est pas spécifiée pour ce champ. 
![image](https://user-images.githubusercontent.com/15981479/227161364-8ad5a31f-9514-4bb4-a073-c8db54f0e578.png)

Côté front si le digitiser n'est pas renseignée ça lève une erreur sur le code collé en dessous et la suite des infos n'est plus affichée.
https://github.com/PnX-SI/GeoNature/blob/da182f1b7ee2c71891c7d080413a8c4b1b9e80be/contrib/occtax/frontend/app/occtax-map-list/occtax-map-list.component.html#L93-L95

Il suffirait de remplacer le bloc du dessus par ça pour régler le problème :
`<div><strong>Saisi par : </strong> {{ row?.digitiser?.nom_complet || '-'}} </div>`
Au moins avec ça on gère si `digitiser === null` ou s'il est `undefined`

**Comment by camillemonchicourt** [comment]
Oui ce champs n'est pas obligatoire, donc cela devrait être répercuté côté Frontend.
On veut bien une PR.
