### ISSUE TITLE
Configuration centralisée de la configuration des modules

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#2423]
Depuis la version 2.11.0 de GeoNature, il est possible de centraliser les fichiers de configuration des modules dans le dossier de configuration de GeoNature.

Cela permet de : 
- Simplifier la configuration de GeoNature et de ses modules en ayant toutes les configurations dans un seul dossier
- Simplifier le fait de donner accès à des administrateurs secondaires à qui on peut ainsi donner accès seulement à un dossier de configuration
- Simplifier la mise à jour des modules en ayant plus besoin de récupérer manuellement leur fichier de configuration à chaque mise à jour du module
- Récupérer automatiquement tous les fichiers de configuration de tous les modules lors de la mise à jour de GeoNature (fait automatiquement par le script `migration.sh`)
- Recharger automatiquement GeoNature à chaque fois qu'un fichier .toml de configuration de GeoNature ou d'un module est modifié (https://github.com/PnX-SI/GeoNature/pull/2418). Cela ajouté à la configuration dynamique du frontend intégré dans la version 2.12.0 fait que désormais la modification d'un fichier de configuration de GeoNature ou d'un module est automatiquement répercutée dans l'application sans devoir lancer aucune commande. On peut ainsi imaginer donner accès en FTP au dossier `~/geonature/config/` à des administrateurs secondaires pour qu'ils puissent modifier la configuration de leur GeoNature et ses modules, sans qu'ils aient un accès SSH pour lancer des commandes
- Simplifier l'organisation des fichiers ainsi que la dockerisation

Pour faire cela, les fichiers (optionnels) de configuration de chaque module doivent être dans le dossier `~/geonature/config/` et être nommés `<module-code>_config.toml`.

Dans la 2.12.0, on a décidé d'en faire la norme et de ne plus documenter la configuration des modules dans la dossier `config` de chaque module.
Pour faciliter cela, le script `migration.sh` de la version 2.12.0 se charge d'aller chercher la configuration de chaque module dans son dossier pour la centraliser et la renommer dans le dossier `config` de GeoNature.
La configuration des 3 modules intégrés dans GeoNature sont aussi automatiquement déplacés et renommés (`config/occtax_config.toml`, `config/occhab_config.toml` et `config/validation_config.toml`).

Cela est aussi répercuté dans la documentation de GeoNature, ainsi que dans les 4 modules principaux que nous maintenons. 
Exemple pour le module Import : https://github.com/PnX-SI/gn_module_import/pull/441/files.

**Comment by gildeluermoz** [comment]
Est-ce que les fichiers exemples de la conf des modules seront centralisés aussi ?
possiblement pratique ;)

**Comment by camillemonchicourt** [comment]
Non pas possible car GeoNature ne connait pas les modules externes tant qu'ils ne sont pas installés.
Et c'est chaque module qui fait évoluer ses paramètres en fonction de ses évolutions, donc il faut que ces fichiers restent dans chaque module.

De toute façon ces fichiers d'exemples sont incomplets, pas à jour et à virer pour être remplacés par une Doc de configuration dans chaque module.

**Comment by camillemonchicourt** [comment]
Cela a été répercuté dans la documentation de configuration des modules : https://docs.geonature.fr/installation.html#configuration-du-module
