### ISSUE TITLE
Surcharger le CSS du composant "Observers"

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#243]
On utilise ce composant pour le multiselect des observateurs:
https://www.primefaces.org/primeng/#/autocomplete

Impossible de surcharger le CSS pour afficher l'input avec un border rouge tant que le champ n'est pas rempli...

Voir: https://github.com/PnX-SI/GeoNature/blob/frontend-contact/frontend/src/core/GN2Common/form/observers/observers.component.scss

**Comment by gildeluermoz** [comment]
Ne pas hésiter à prendre le temps qu'il faut pour le choix de ces composants assez centraux et que l'on utilisera souvent.
C'est un investissement important car on peut se retrouver bloqué avec un composant faible, mal intégrer ou pas suffisamment paramètrable.
