### ISSUE TITLE
[gn_commons] Questionnements sur la synchronisation des médias

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature#2436]
## Contexte

Dans le cadre d'une prestation avec l'ARB île de France, nous nous sommes posés des questions sur le traitement des média sur le système de fichier du serveur.

## Explications

A chaque insertion ou modification d'un média, une requête POST/PUT est émise à la route `/media` qui ensuite fait appel entre autres à cette fonction : 
https://github.com/PnX-SI/GeoNature/blob/6e6e90382484f9d616c03ff73cfb934da3656ed4/backend/geonature/core/gn_commons/medias/routes.py#L97

Qui est située ici : https://github.com/PnX-SI/GeoNature/blob/6e6e90382484f9d616c03ff73cfb934da3656ed4/backend/geonature/core/gn_commons/repositories.py#L391

Si je ne dis pas de bêtises, lorsque cette fonction est appelée, tous les fichiers médias présents dans leur dossier de stockage sont recherchés : https://github.com/PnX-SI/GeoNature/blob/6e6e90382484f9d616c03ff73cfb934da3656ed4/backend/geonature/core/gn_commons/repositories.py#L426

Et ces derniers sont éventuellement renommés en `deleted_` s'ils n'existent plus en base.

## Problématique

A chaque création ou modification d'un seul média, tous les fichiers présents sur le système de fichiers sont "traités", ce qui peut être un processus long quand il y a beaucoup de média. 

## Question
Pensez-vous qu'il serait possible de revoir cette synchronisation en ne la faisant que sur l'objet effectivement traité ?

## Potentielles solutions
Il serait possible d'utiliser un hook sqlalchemy de type post_delete/post_insert/post_update ([doc SQLAlchemy](https://docs.sqlalchemy.org/en/14/orm/events.html#sqlalchemy.orm.MapperEvents.after_delete)) ou quelque chose du genre pour traiter le fichier directement lors de sa modification en base.
Nous faisons cela sur d'autres projets pour gérer le lien entre la base de données et un système de stockage s3 et cela fonctionne plutôt bien. Ce sont néanmoins des cas plus simples que GeoNature...

Peut-être d'autres solutions sont possibles.

----

Merci d'avance pour vos retours !

**Comment by joelclems** [comment]
Le but de la fonction sync media est de faire du nettoyage sur les medias

- supprimer les médias sans uuid_attached_row et plus vieux que 24h
- supprimer les médias dont l'object attaché n'existe plus

elle n'a pas forcement besoin d'être appellée à chaque insert/ update de media et elle pourrait n'être appellée qu'une fois par jour  avec `celery_beat`

Pour info il existe un hook dans app.py pour supprimer le fichier media quand la ligne est supprimée dans TMedia

https://github.com/PnX-SI/GeoNature/blob/6e6e90382484f9d616c03ff73cfb934da3656ed4/backend/geonature/app.py#L120-L125

**Comment by camillemonchicourt** [comment]
En effet, il ne faudrait pas appeler cette commande de nettoyage des médias orphelins à chaque ajout ou modification d'un média, pour ne pas alourdir cette opération.
Et du coup renommer cette commande `sync_media` en `clean_attachments` je pense.

**Comment by mvergez** [comment]
Merci beaucoup pour vos retours et ces explications !
Et donc pour bien comprendre pour l'`uuid_attached_row` : dans quel cas un media peut se retrouver sans `uuid_attached_row` ? Et pourquoi traiter ceux qui sont plus vieux que 24h ?
Merci d'avance pour vos explications !

**Comment by joelclems** [comment]
Par exemple dans monitoring, quand on crée un site on peut lui attacher des medias

on va uploader et enregister les medias
puis on va valider et enregistrer le site

si on a validé les medias et qu'on a arreté avant de valider le site le ou les medias n'auront pas d'uuid_attached_row

24h c'est arbitraire pour laisser le temps de valider apres avoir saisi les medias

en ce qui concerne les fichiers orphelin, cela peut arriver si l'on supprime des medias en bdd directement

**Comment by mvergez** [comment]
Ah oui je comprends, c'est parce que les médias sont uploadés avant de valider la création d'un objet attaché. 

Merci en tout cas pour ces explications @joelclems ! Si j'ai un peu de temps j'essaierai d'ouvrir une PR qui va dans ce sens !
