### ISSUE TITLE
[METADONNEES] Pertes de performances de la route /meta/datasets avec de nombreux jeux de données (par rapport à GN 2.11.2)

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature#2444]
**Version**
2.12 (testé sur develop qui, à ce jour, est quasi identique à master)

**Description du bug**
Suite aux développements de cette PR : #2336, il a été introduit une perte de performances : moins de 0.5 sec en GN2.11.2 contre lus ou moins 5sec (je n'ai pas attendu la fin du test), voire même 10sec avec `order_by` pour 2000 jeux de données.
Cette perte se fait sentir sur les instances avec de nombreux jeux de données et plus précisément pour des utilisateurs ayant accès à de nombreux jeux de données. Cela est visible notamment au niveau des modules utilisant le composant front `<pnx-datasets>` (permettant de sélectionner un jeu de données) qui appelle tous les jeux de données dès sont initialisation.

Cette perte est due à l'introduction de la validation du résultat de la requête SQL avec Marshmallow sur la route GET `/meta/datasets`.
Ici : https://github.com/PnX-SI/GeoNature/blob/5999efb11113081f1f9e8c65d44130318069c7b6/backend/geonature/core/gn_meta/routes.py#L155. 
Appellant la méthode `jsonify` de la librairie `flask-marshmallow` : https://github.com/marshmallow-code/flask-marshmallow/blob/0b7c186fe3c607cbff5df921ba6973aa15926407/src/flask_marshmallow/schema.py#L14

**Comportement attendu**
Un chargement des jeux de données rapide (moins de 0.5sec)

**Comment reproduire**
Faire un appel à la route `/meta/datasets` sur GeoNature 2.11.2 et GeoNature 2.12 pour voir la différence de performance.
Pour être plus rigoureux, j'ai écrit ce petit script python qui permet d'exécuter 1000 appels et de diviser le temps total d'exécution par 1000. Ce n'est pas l'analyse la plus rigoureuse mais cela donne une idée.

Ce script nécessite la librairie `requests`
```python
import requests
import timeit

HOST = "http://localhost:8000/"

def login():
    req = requests.post(f"{HOST}auth/login", json={
        "login": "admin",
        "password": "admin"
    })

    return req.cookies


def get_datasets(cookies):
    req = requests.get(f"{HOST}meta/datasets?orderby=dataset_name", cookies=cookies)

    return req.status_code

def get_perf(iterations: int=10):
    exec_time = timeit.timeit('get_datasets(cookies=cookies)', 
                              setup='cookies = login()', 
                              globals=globals(), 
                              number=iterations)
    print(f"{iterations} loops, average: {exec_time/iterations}s")
    

if __name__ == "__main__":
    get_perf(1000)
```

**Potentielles solutions**

 Cette validation est importante mais nous devons trouver un moyen de rétablir ou se rapprocher des performances passées. Plusieurs solutions :
- Paginer le résultat : ce qui sera fait à terme mais demande trop de travail pour un simple correctif
- Créer une nouvelle route retournant peu de champs. Route spécifique pour le composant `<pnx-datasets>` où, il me semble, que seuls `id_dataset` et `dataset_name` suffisent. Mais cela multiplie les routes...
- Éditer la route actuelle GET `/meta/datasets` en rendant disponible le paramètre only, permettant au front de spécifier uniquement les champs dont il a besoin.
- Faire l'inverse : renvoyer par défaut un minimum de champs et laisser le front spécifier les champs dont il a besoin : solution très intéressante permettant de charger uniquement les données dont on a besoin mais trop de travail pour un simple correctif
- Empêcher `<pnx-datasets>` de charger tous les jeux de données à son initialisation : mais de toute manière il devra les charger à un moment donné.
- Autres propositions ?

Qu'en pensez-vous ?

Merci d'avance pour vos retours !

**Comment by camillemonchicourt** [comment]
OK donc on gagne bien en performances dans le module METADONNEES car on n charge plus tous les JDD, mais seulement ceux d'un CA quand on clique dessus.
Par contre la récupération des JDD est plus longue désormais car les résultats de la route son validés.

Donc cela impacte les modules utilisant un champs listant les JDD comme Occtax, Synthèse, etc... quand il y a beaucoup de JDD.

Pour moi la solution serait : 

> Éditer la route actuelle GET /meta/datasets en rendant disponible le paramètre only, permettant au front de spécifier uniquement les champs dont il a besoin.

Pour moi un route doit renvoyer tous les champs par défaut, mais pouvoir spécifier une liste de champs quand on n'a besoin que de certains.
Je ne sais pas si cela suffirait à revenir à des performances acceptables ?

**Comment by bouttier** [comment]
@mvergez Qu'entends-tu par les résultats sont validé par Marshmallow ? De ce qu'il me semble, seules les requêtes sont validées, ce qui ne devait pas prendre beaucoup de temps. Les réponses sont sérialisées, mais la méthode jsonify de Marshmallow est plutôt censé être plus rapide que as_dict.
Sur la lourdeur de la réponse lié à la quantité de champs inutiles, il est aussi possible qu'on inclus par défaut des relationships que l'on n'incluées pas précédemment. À noter qu'il faut joinedloader les acteurs même si on ne les sérialise pas afin de vérifier les permissions.

**Comment by mvergez** [comment]
Salut @bouttier,
J'ai fait le test de `as_dict` vs `jsonify` et `as_dict` est plus rapide. Je viens de refaire le test : 
```python
return [d.as_dict() for d in query.all()]
```
Au lieu de 
```python
return dataset_schema.jsonify(query.all(), many=True)
```
Même en enlevant `cor_dataset_actor`,` cor_dataset_actor.nomenclature_actor_role`, `cor_dataset_actor.organism`, `cor_dataset_actor.role`, `as_dict` est plus performant...

Je pensais qu'il y avait validation des champs à la sérialisation alors qu'en fait c'est uniquement à la dé-sérialisation (https://github.com/marshmallow-code/marshmallow/issues/682). Donc je ne sais pas d'où ça peut venir.

Je vais relancer du profiling pour voir d'où ça vient dans Marshmallow/flask-marshmallow
J'ai testé avec : `ProfilerMiddleware` de `werkzeug` puis `snakeviz` et ça fonctionne bien.

**Comment by jbrieuclp** [comment]
Dans les log de postgres (en configurant `log_statement = 'all'`) on voit que pour chaque JDD récupéré est exécutée cette requete : 
```
SELECT (SELECT count(gn_synthese.synthese.id_synthese) AS count_1 
	FROM gn_synthese.synthese 
	WHERE gn_synthese.synthese.id_dataset = gn_meta.t_datasets.id_dataset) AS synthese_records_count 
	FROM gn_meta.t_datasets 
	WHERE gn_meta.t_datasets.id_dataset = 1670
```
Donc quand on la multiplie avec moulte JDD ça fait péter le timer !..
Je n'ai pas encore investigué sur le pourquoi du comment, mais je vais chercher.

**Comment by jbrieuclp** [comment]
Du coup en commentant les lignes suivantes pas de changement : 
https://github.com/PnX-SI/GeoNature/blob/7fc3cb091cb063c394989d51b348970fc8992ed3/backend/geonature/core/gn_meta/routes.py#L140-L142

Par contre en commentant ces lignes la requêtes passe en 1.3 sec
https://github.com/PnX-SI/GeoNature/blob/7fc3cb091cb063c394989d51b348970fc8992ed3/backend/geonature/core/gn_synthese/models.py#L655-L661
Le truc c'est que je comprends pas à quel endroit cette classe se trouve chargée par cette route :-/

**Comment by mvergez** [comment]
Merci pour tes investigations @jbrieuclp. Je regarde côté marshmallow en parallèle parce qu'il met plus de temps à sérialiser par rapport à `as_dict()` (0.5s vs 12s)...

**Comment by mvergez** [comment]
Mais effectivement tu as raison, en analysant, Marshmallow a l'air de faire des selects en plus qui ne sont pas faits dans le `as_dict()` ...

**Comment by jbrieuclp** [comment]
En fait je viens de me rendre compte que ce qui est en fin de fichier `backend/geonature/core/gn_synthese/models.py` n'a rien à voir avec la class `SyntheseLogEntry`. Regarde l'indentation Joe !🙄
Là le champ différé `synthese_records_count` est chargé par défaut. Il faut qu'il soit optionnel, c'est ça qui nous met dedans niveau perf, d'autant que pour une liste de JDD on s'en balance du nombre de données associées !

**Comment by mvergez** [comment]
Oui mais normalement elle est `deferred` non ?
De la doc sqlalchemy (https://docs.sqlalchemy.org/en/20/orm/mapping_api.html#sqlalchemy.orm.column_property): 

> deferred – when True, the column property is “deferred”, meaning that it does not load immediately, and is instead loaded when the attribute is first accessed on an instance

**Comment by jbrieuclp** [comment]
Oui en deferred=True elle fait une requete par ligne de donnée
En deferred=False elle fait une requête SQL unique (et degueu) pour charger les counts en one shot (qui met 15s à s'exécuter)

**Comment by mvergez** [comment]
Oui mais il fait le select uniquement si tu appelles `TDatasets.synthese_records_count`. Et j'ai l'impression que Marshmallow le fait...

J'ai fait le test en ajoutant dans le schéma Marshmallow : https://github.com/PnX-SI/GeoNature/blob/5999efb11113081f1f9e8c65d44130318069c7b6/backend/geonature/core/gn_meta/schemas.py#L41

La ligne suivante (pour tester) : 
```python
synthese_records_count = fields.Integer(load_only=True)
```
Pour qu'il ne la dump pas en sérialisant car il a l'air de le faire même si on lui dit de ne pas le faire...

**Comment by mvergez** [comment]
Donc ! Si on fait un 
```python
dataset_schema = DatasetSchema(only=only, exclude=["synthese_records_count"])
```
ça fonctionne ! La requête prend 1sec

**Comment by jbrieuclp** [comment]
De mon côté je cherchais à intégrer la définition de ce champ virtuel au sein du model `TDatasets` pour pas qu'elle soit définie au niveau du `gn_synthese.model.py`. Sauf que la référence circulaire nous met dedans, du coup j'étais en train de chercher comment faire appel à la table synthese depuis le MetaData de SQLAlchemy...

Par rapport au exclude il faut faire gaffe à ce que ça ne rentre pas en conflit avec ça :
https://github.com/PnX-SI/GeoNature/blob/7fc3cb091cb063c394989d51b348970fc8992ed3/backend/geonature/core/gn_meta/routes.py#L132-L142

De fait est-ce qu'il ne faudrait pas le faire comme ça : 
 ```
only = [ 
     "+cruved", 
     "cor_dataset_actor", 
     "cor_dataset_actor.nomenclature_actor_role", 
     "cor_dataset_actor.organism", 
     "cor_dataset_actor.role", 
 ] 
 exclude = []

 if params.get("synthese_records_count", type=int, default=0): 
     query = query.options(undefer(TDatasets.synthese_records_count)) 
     only.append("+synthese_records_count") 
else:
     exclude.append("synthese_records_count") 

[...]
dataset_schema = DatasetSchema(only=only, exclude=exclude)
```

Quitte à ajouter au exclude les autres infos non nécessaires au listing des JDD : les bbox, id_nomenclature_collecting_method, id_nomenclature_data_origin, id_nomenclature_data_type, id_nomenclature_dataset_objectif, id_nomenclature_resource_type, id_nomenclature_source_status, id_taxa_list, keywords, terrestrial_domain

**Comment by mvergez** [comment]
> De fait est-ce qu'il ne faudrait pas le faire comme ça :

Oui je suis en train de le faire exactement comme ça, c'était juste pour le test. ça marche pour les autres champs, merci !

Ah mince pour la référence circulaire. ça doit être pour cela que @bouttier avait choisi cette solution externe au model

**Comment by mvergez** [comment]
Je vais mettre le exclude dans une PR séparée plutôt que dans #2445, ce sera plus propre

**Comment by jbrieuclp** [comment]
Ouai comme tu es dessus, je te laisse gérer la PR sinon ça va être le zbeul dans la gestion des PR. Idem si tu peux gérer l'issue #2454 en même temps c'est top !

**Comment by mvergez** [comment]
Au final j'ai créé 2 PR comme ça ne touchait pas au même code. 
J'espère que celle pour #2454 te conviendra !

**Comment by bouttier** [comment]
Corrigé dans #2462 

Le schéma Marshmallow a été modifié pour exclure les champs marqué `deferred` comme c’est fait dans `as_dict`.

Le fait que `synthese_records_count` n’était pas correctement exclus faisait que le front l’obtenait sans même le demander ; @mvergez a corrigé cela pour que le front demande bien ce champs exclu par défaut.

**Comment by camillemonchicourt** [comment]
Soucis de performances corrigé dans la 2.12.1.

Reste une optimisation possible, mais plutôt pour la 2.13.0 car à faire plus globalement à partir de https://github.com/PnX-SI/GeoNature/pull/2445
