### ISSUE TITLE
Occtax - Afficher tous les champs du formulaire par défaut

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#2446]
Bonjour, 

Nous discutons du coté d'occtax mobile, à supprimer le bouton "avancé" pour que les champs soient soit masqués totalement, soit affichés totalement, mais pas moitié/moitié derrière bouton "avancé". 

Coté web, ce bouton ne nous apporte pas grand chose de plus, à chaque saisie il faut cliquer dessus pour accéder à tout le formulaire. Chez Flavia depuis plusieurs versions, je change la valeur par défaut du bouton avancé, pour que son état soit "expanded". Je voudrais en faire un paramètre d'occtax pour ne pas avoir à revenir dessus à chaque version, et rendre ça configurable pour tout le monde. 

Est-ce que ca vous semble pertinent d'ajouter un paramètre dans la conf pour qu'on puisse activer par défaut tous les champs du formulaire sans passer par ce bouton ?

**Comment by camillemonchicourt** [comment]
Oui OK, pourquoi pas.

**Comment by mvergez** [comment]
Je suis passé par là et je me suis permis de le faire dans la PR ci-dessus, j'espère que ça vous ira !

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.13.0.
