### ISSUE TITLE
[2.12] - Un champs additionnel "select" passe en grisé une fois rempli

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#2447]
**Version**
2.12.0

**Description du bug**
J'ai sur une instance un champs additionnel de type select. Comme vu dans la note de version, j'ai mis à jour ma liste de valeurs pour obtenir le dictionnaire suivant : 

> [{"label": "Bois rongé", "value": 1}, {"label": "Barrage", "value": 1}, {"label": "Autre (observation directe, piège photo etc)", "value": 3}]

Une fois rempli dans le formulaire de saisie, le champs en interface prend la valeur "value" et non pas le label. Et ce champs devient grisé. 

J'ai également testé en conservant value=label, avec les quotes : même chose, mon texte s'affiche bien dans le champs mais dans tous les cas, grisé et non modifiable. Faut pas se planter à la saisie ;)

**Comportement attendue**
Afficher le label et non pas la value une fois le champs rempli. Et conserver le champs modifiable même une fois renseigné. 

**Comment reproduire**
Configurer un champs additionnel de type "select" et faire une saisie dessus.

**Comment by DonovanMaillard** [comment]
Idem si on conserve les listes "à l'ancienne" en faisant marcher la rétrocompatibilité.

**Comment by camillemonchicourt** [comment]
Corrigé dans la PR https://github.com/PnX-SI/GeoNature/pull/2451 qui sera incluse dans une 2.12.1 corrective.

**Comment by DonovanMaillard** [comment]
merci à vous !

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.12.1
