### ISSUE TITLE
[2.12] Affichage incorrect des noms de champs dans la modale d'info synthese/validation

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#2448]
**Version**
2.12

**Description du bug**
Dans la modale d'info de la synthèse (en principe idem en validation donc), les noms de champs de certaines nomenclatures ne sont pas explicites: 

Idem sur l'onglet discussion dont le libellé affiché est erronné, et sur les infos en entête (uuid, observateur etc).
<img width="1400" alt="Capture d’écran 2023-04-02 à 10 01 59" src="https://user-images.githubusercontent.com/23358384/229340399-b28f948d-954b-46e7-822e-5e6471bd84a4.png">

**Comportement attendue**
Afficher des libellés explicités

**Comment reproduire**
Consulter une fiche info dans le module synthèse

**Comment by jbrieuclp** [comment]
J'ai eu la même chose sur le passage a la 2.11 c'était juste le cache du navigateur qui posait problème. Tu peux tester en navigation privée et dans le doute reboot !

**Comment by DonovanMaillard** [comment]
Effectivement, soucis de cache du navigateur :)

Merci à toi pour la piste ! 

D'une manière générale j'ai souvent des choses qui restent dans le cache, et pour laquelle des utilisateurs m'appellent.
