### ISSUE TITLE
[2.12.0] Erreur 500 - api/gn_commons/modules

### ISSUE THREAD

**Issue by cen-cgeier** [PnX-SI/GeoNature#2449]
Bonjour à tous, 
J'ai des difficultés à la mise à jour de la nouvelle version de GéoNature que je ne parviens pas à résoudre. 
Lors de l'installation tout semble s'être bien passé ! (chouette)
Mais en fait non :)

**Version**
GN_OLD=2.11.2 
GN=2.12.0
Exports=1.4.0
Import=2.1.0
Monitorings=0.5.0
Dashboard=1.3.0
TaxHub=1.11.1
UsersHub=2.3.3

**Description du bug**
Après le login à GéoNature, j'obtiens une erreur 500 sur l'API /gn_commons/modules
![image](https://user-images.githubusercontent.com/96542451/229490818-ca2ab21a-ce7f-4cb8-af81-e0667070d3d7.png)

En testant de me connecter à UsersHub et à TaxHub, aucun des deux ne fonctionnent. 
UsersHub n'affiche pas d'erreur à la connection mais boucle sur la page de login. Les logs n'affichent rien.
TaxHub affiche un message d'erreur d'authentification mais les API possèdent toutes un `code 200 OK`
![image](https://user-images.githubusercontent.com/96542451/229506928-ff0171fa-4a3c-4c80-9f8b-5e6d9c081d01.png)

**Comportement attendue**
le chargement de la page d’accueil et des différents module.

**Comment reproduire**
J'ai chargé, renommé les différents modules et réalisé la procédure de mise à jours de GN2.12.0 

**Logs**
``` py
[2023-04-03 10:12:30 +0200] [2557027] [ERROR] Exception on /gn_commons/modules [GET]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_permissions/decorators.py", line 18, in decorated_view
    return view_func(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_commons/routes.py", line 70, in list_modules
    cruved = get_scopes_by_action(module_code=module.module_code)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_permissions/tools.py", line 202, in get_scopes_by_action
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_permissions/tools.py", line 203, in <dictcomp>
    def get_scopes_by_action(id_role=None, module_code=None, object_code=None):
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_permissions/tools.py", line 192, in get_scope
    we should filter non-scope permissions *before* inheritance.
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_permissions/tools.py", line 181, in get_permissions
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_permissions/tools.py", line 168, in _get_permissions
    permissions = get_user_permissions_by_action(id_role)[action_code]
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_permissions/tools.py", line 168, in <lambda>
    permissions = get_user_permissions_by_action(id_role)[action_code]
AttributeError: 'NoneType' object has no attribute 'module_code'
```

J'ai tenté un certain nombre de chose mais il semble que je ne parvienne pas à débuger  cette api correctement. Auriez-vous des conseils ou une idée de ce qu'il se passe mal ?
Merci d'avance pour le retour

**Comment by TheoLechemia** [comment]
Bonjour,
ça semble venir d'une ligne de la table `gn_permissions.cor_role_action_filter_module_object` qui contiendrait une ligne dont le "id_module" ne correspond pas à aucun module en base (`gn_commons.t_modules`). La clé étrangère est manquante sur cette table, c'est une erreur de notre part.
Est-ce que tu peux vérifier si c'est bien ça ?

**Comment by cen-cgeier** [comment]
J'ai oublié un autre retour dans mon premier message : 
J'ai lancé plusieurs fois, depuis ce matin le fichier `geonature/install/migration/migration.sh`. 
A partir du deuxième lancement j'ai obtenu un message d'erreur de PosixPath sur la ligne 58 du fichier `geonature/backend/geonature/core/command/create_gn_module.py`
``` py
attributeerror 'PosixPath' object has no attribute 'readlink'
```

Il semble que `readlink()` soit de trop dans la commande :
``` py
if module_frontend_path != module_symlink.readlink().resolve():
         ....
```
Je suis en python 3.8.10 dans le venv de GéoNature.

**Comment by camillemonchicourt** [comment]
OK, tu as du supprimer un module, mais on n'a pas géré les conséquences dans la table des permissions `cor_role_action_filter_module_object`.

Peux-tu supprimer les lignes dans `cor_role_action_filter_module_object` qui ne correspondent plus à un module de ton GeoNature et ça devrait régler le soucis.

**Comment by cen-cgeier** [comment]
Bonjour @camillemonchicourt,
J'ai supprimé ces lignes et tout fonctionne à merveille !
MERCI !

**Comment by camillemonchicourt** [comment]
OK il faut que l'on gère ce cas des modules supprimés ayant des permissions associés, dans une release corrective.

Pour les autres sujets, il vaut mieux privilégier un sujet par ticket, sinon on ne s'y retrouve pas.

**Comment by camillemonchicourt** [comment]
Le deuxième sujet (qui n'a rien à voir) mentionné dans ce ticket (https://github.com/PnX-SI/GeoNature/issues/2449#issuecomment-1494307615) est corrigé ici : https://github.com/PnX-SI/GeoNature/pull/2464

> A partir du deuxième lancement j'ai obtenu un message d'erreur de PosixPath sur la ligne 58 du fichier geonature/backend/geonature/core/command/create_gn_module.py
