### ISSUE TITLE
Création d'un compte avec domaine @mailden.fr : 400 bad request

### ISSUE THREAD

**Issue by kazemar** [PnX-SI/GeoNature#2453]
Lors de la création d'un nouveau compte avec une adresse @mailden.fr, à l'étape de l'envoi du mail de confirmation, le serveur répond
HttpErrorResponse 400 BAD REQUEST

La création avec un compte différent fonctionne sans souci (mail de confirmation bien envoyé).

Edit : ajout de détails
- Version de Geonature : 2.11.2
- Erreur rencontrée sur Mac (Firefox) et Windows (Chrome)
- L'envoi du mail a été fait sur chacun de ces postes en utilisant un mail différent
- Les manips ont été faite le 03/04/2023 vers 19h depuis le wifi de Nature en Occitanie (réseau "Natureo")

(Screenshot fait pour cet issue avec un compte fictif, mais le problème est survenu avec une vraie adresse)
![image](https://user-images.githubusercontent.com/6574960/229579406-b5c92b2b-3eb8-4e93-8a86-1396d4a25791.png)

**Comment by camillemonchicourt** [comment]
Il faudrait les logs du serveur pour identifier plus clairement le soucis.

Mais selon moi le soucis ne vient  pas de l'extension email.

**Comment by kazemar** [comment]
Plus d'infos :
- erreur rencontrée sur Mac (Firefox) et Windows (Chrome)
- l'envoi du mail a été fait sur chacun de ces postes en utilisant un mail différent
- les manips ont été faite le 03/04/2023 vers 19h depuis le wifi de Nature en Occitanie (réseau  "Natureo")

**Comment by camillemonchicourt** [comment]
OK il faudrait voir avec l'administrateur du serveur du GeoNature en Occitanie pour avoir les logs du serveur au moment du soucis.

Ainsi que la version de GeoNature et UsersHub.

**Comment by kazemar** [comment]
Ok oui, j'ai réuni tous les détails que j'avais dans mon post initial.

**Comment by camillemonchicourt** [comment]
Je viens de tester sur un serveur de démo avec un compte utilisant un email mailden.fr et n'ait pas eu de soucis.

Comme évoqué précédemment, il n'y a pas de raison que ça passe avec un autre type d'email mais pas celui-ci.
Il faudrait avoir les logs de votre serveur GeoNature pour identifier le soucis.

**Comment by camillemonchicourt** [comment]
@JeromeMaruejouls ?

**Comment by TheoLechemia** [comment]
C'est une erreur 400, il n'y aura pas de log côté serveur. Il faut regarder s'il y a des messages dans la console de debug du navigateur

**Comment by kazemar** [comment]
Je viens de tester avec le même PC + navigateur que hier, mais depuis une autre connexion -> pas de souci.
J'ai demandé à la personne qui rencontrait hier l'erreur de réessayer, j'attends son retour.

**Comment by JeromeMaruejouls** [comment]
Bonjour à tous,
Dans un premier temps, quand vous rencontrez une erreur sur une installation spécifique de géonature, je pense qu'il est préférable de contacter l'administrateur du serveur, qui lui, créera un ticket github si nécessaire.
Je viens de tester la création de compte avec succés. Je pense que le problème vient plutôt d'une "surcharge" serveur au moment de la création du compte (j'ai fait un peu de maintenance hier).
Je vérifierai les logs dans la journée quand même.

**Comment by geobrun** [comment]
Je confirme : j'ai eu le même type de message d'erreur sur mon instance pendant que je faisais de la maintenance dessus. J'imagine que cela vient effectivement d'une surcharge car une fois les opérations de maintenance terminées, tout est redevenu normal.

**Comment by kazemar** [comment]
Ok, je ferme l'issue alors
