### ISSUE TITLE
erreur a l'install dans geonature_config.toml  manque des "/"

### ISSUE THREAD

**Issue by libes-osu** [PnX-SI/GeoNature#2456]
**Version**
Version de GeoNature affectée par le bug.

v 2.12.0

**Description du bug**
Description du problème rencontré (message d’erreur, code HTTP de retour inattendu, …).

lors de l'installation par le script install.sh
j'ai eu une erreur /home/geonatureadmin/geonature/config/geonature_config.toml
sur les URL ci dessous il n'y avait qu'un seul "/" à http://

URL_APPLICATION = 'http:/geonature.osupytheas.fr/geonature'
API_ENDPOINT = 'http:/geonature.osupytheas.fr/geonature/api'
API_TAXHUB = 'http:/geonature.osupytheas.fr/taxhub/api'

j'ai rajouté le / manquant et ai relancé l'install

**Comportement attendue**
Description du comportement attendue en lieu et place du problème rencontré.

**Comment reproduire**
Étapes à suivre pour reproduire le problème (sur quelle page se rendre, sur quel bouton cliquer, avec quelles données présentes, …).

**Logs**
Extrait du fichier ``/var/log/geonature.log`` dans le cas d’une erreur 500.

**Comment by libes-osu** [comment]
idem dans les fichiers

/etc/apache2/sites-available/geonature_maintenance.conf
/etc/apache2/sites-available/geonature.conf

il manque un "/" dans l'URL http://

**Comment by camillemonchicourt** [comment]
C'est étonnant car j'ai testé le script plein de fois sans soucis.
Le script d'installation prend la valeur saisie dans le paramètre `my_url` dans le fichier `install_all.ini` (https://github.com/PnX-SI/GeoNature/blob/master/install/install_all/install_all.ini#L11).

Tu es certain de ne pas avoir oublié un / quand tu as saisi `my_url` dans le fichier `install_all.ini` ?
Peux-tu vérifier cette variable dans ton fichier `install_all.ini` ?

**Comment by libes-osu** [comment]
honte à moi 
je vais trop vite
une issue en moins, merci
