### ISSUE TITLE
Localisation Observations - Ajouter un module MES LIEUX

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#246]
Il est actuellement possible de localiser une observation en 
- dessinant un point, ligne ou polygone directement sur la carte
- saisissant des coordonnées GPS
- importer un fichier GPX, KML ou GeoJSON

Il a été évoqué la possibilité pour chaque utilisateur de gérer une liste de lieux qui lui sont propres et qu'il utilise régulièrement (nom+geom) et qu'il peut choisir dans une liste déroulante au lieu de pointer la localisation sur la carte. 

Cette table des lieux d'un utilisateur ne serait utilisé que pour la localisation du point dont on stockerait bien le geom dans l'observation et non pas l'ID du lieu. 

Nécessite un petit module pour gérer ses lieux...

**Comment by RomainBaghi** [comment]
Ce serait effectivement très utile de pouvoir enregistrer des géométries.
En effet, dans occtax on est obligé de redessiner le polygone/point/transect à chaque fois que l'on veut saisir un nouveau relevé, même si c'est toujours le même endroit. 
Ce serait sans doute utile si ces lieux enregistrés étaient visibles par tout le monde... à réfléchir.
mercii

**Comment by DonovanMaillard** [comment]
Bonjour, 

C'est une discussion que j'ai eue hier également avec mon collegue qui saisit... Je trouve personnellement que ca a sa place sur des modules de suivis, mais pas forcément sur occtax, qui est censé servir essentiellement pour des données collectées hors protocole, et pour lesquelles avoir des polygones approximatifs suffit, quitte à les refaire "à chaque fois". La réflexion étant que si on revient régulièrement sur un polygone donné, c'est qu'on y fait un suivi. 
En mettant ça dans occtax, on risque aussi rapidement de se retrouver avec des listes très longues de polygones visités précédemment par l'utilisateur...

Une possibilité au passage étant de filtrer les géométries par jeu de données (ce qui est pertinent dans le cas d'un suivi notamment, chaque suivi/étude ayant son lot de parcelles). Mais dans ce cas, ça veut dire que contrairement à occtax, il faudrait d'abord sélectionner le jeu de données, et ensuite définir la géométrie.

**Comment by gildeluermoz** [comment]
Sans les enregistrer et les associer à un utilisateur/ jeu de données, etc... qui complexifie bcp le mcd, on peut imaginer un mécanisme qui propose les géom existantes dans un rayon de x mètres autour du pointage (100 m par ex). Si ce mécanisme est activé (param ou interface ?) l'utilisateur se voit proposer une liste de geom parmi lesquelles il peut choisir celle de l'obs qu'il est en train de saisir.

**Comment by camillemonchicourt** [comment]
Ce qui a été demandé initialement n'a pas vocation à être partagé entre utilisateurs, ce n'est pas une liste complète et de référence.
Encore moins une logique de site ou de suivi, ce n'est pas lié à un JDD ou un protocole.

C'est une table simple avec id_role, nom_lieu et geom_lieu où un utilisateur peut avoir enregistré le point de son jardin et du lac d'à côté où il fait souvent des observations.
Sur la carte une petite liste déroulante de ses lieux lui est proposée et quand il en choisit un, ça lui localise son relevé en utilisant le geom de son lieu.

**Comment by RomainBaghi** [comment]
J'achète !

**Comment by gildeluermoz** [comment]
Combien ?

**Comment by DonovanMaillard** [comment]
Autre qu'une liste... Ce qui peut (??) s'imaginer c'est que quand on fait une saisit, la carte sur occtax n'est pas vierge mais affiche toutes les geometries des données saisies par l'utilisateur précédemment. Ça prend toutes les géométries qui sont sont la bbox de la carte courante et l'utilisateur peut zommer et salectionner une entité déjà utilisée, ou créer une nouvelle geom.

Ça évite de gérer une liste avec des noms de sites etc, c'est juste que l'interface récupérer les geom des données précédentes pour l'id digitizer courant...  Ça semblerait pas plus pratique ?

**Comment by TheoLechemia** [comment]
Romain m'avait déjà parlé de ça au téléphone. ça peut être une idée interessante oui.

**Comment by DonovanMaillard** [comment]
Salut ! 

Juste pour voir s'il y a eu du nouveau sur les réflexions à ce sujet, et le fonctionnement qui pourrait être adopté :) Comme e disais à camille et comme je le mettais plus haut, dans un cadre de suivi (ou de protocoles) ca semble pertinent. Je réfléchis à un module qui puisse répondre aux besoins pour le protocole chronoventaire, et cette question se pose du coup :) (l'avantage du chronoventaire, c'est que peu de choses changent par rapport à occtax :) )

**Comment by camillemonchicourt** [comment]
De mon côté, je reste sur le besoin initial de pouvoir gérer une petite liste de lieux individuelle avec un nom et une géométrie pour pouvoir localiser mon jardin ou le lac d'à côté.

Pour les suivis et les notions de site, c'est un autre sujet, géré dans le schéma ``gn_monitoring`` de GeoNature, central pour gérer les sites et les visites des protocoles de suivi.

**Comment by jprgeofit** [comment]
Dans le cadre de la prestation de Geofit pour la SHF, voici ci-joint des spécifications fonctionnelles pour la mise en place d'un module "Mes Lieux" dans Occtax
[Specs Mes lieux_Geonature_SHF.docx](https://github.com/PnX-SI/GeoNature/files/4592124/Specs.Mes.lieux_Geonature_SHF.docx)

**Comment by camillemonchicourt** [comment]
Voir PR https://github.com/PnX-SI/GeoNature/pull/984

**Comment by camillemonchicourt** [comment]
J'ai testé la fonctionnalité. Je pense que l'ergonomie pourrait être amélioré par la suite.
C'est dommage que pour une petite fonctionnalité comme celle-ci, cela ajoute 2 boutons dans les outils de localisation.
Je n'ai pas trouvé cela très clair et ergonomique non plus de faire une localisation et ensuite de l'enregistrer.

L'idéal aurait été d'avoir un seul bouton MES LIEUX, qui affiche la liste des lieux sélectionnables. Avec un + à côté de la liste de MES LIEUX pour en ajouter un. Et là une modale de saisie avec Carte + Nom.

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.5.0.
Reste à revoir l'ergonomie, car il n'est pas souhaitable d'ajouter 2 boutons pour une telle fonctionnalité.
Une seule modale peut suffire à enregistrer un lieu ou selectionner un lieu.
