### ISSUE TITLE
[Validation] Impossible de sélectionner un filtre avancé

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature#2470]
**Version**
2.12

**Description du bug**
Impossible de sélectionner un filtre avancé (voir démo : https://demo.geonature.fr/geonature/#/validation) : 
![image](https://user-images.githubusercontent.com/85738261/231226642-65041c04-b01a-4770-b4d7-d83e018d156f.png)

**Comportement attendu**
Pouvoir sélectionner un filtre avancé. Avoir un menu déroulant.

**Comment reproduire**
Aller dans le module validation dans les filtres puis dans la section "Filtres avancés" 

**Solution proposée**

Il semble manquer les lignes suivantes : 

```typescript
this._fs
  .processDefaultFilters(this.config.SYNTHESE.DEFAULT_FILTERS)
  .subscribe((processedDefaultFilters) => {
    this._fs.processedDefaultFilters = processedDefaultFilters;
    this._fs.searchForm.patchValue(this._fs.processedDefaultFilters);

    this.loadAndStoreData(this._fs.formatParams());
  });
```
Dans cette méthode : https://github.com/PnX-SI/GeoNature/blob/aeb2cd1939cb4d498ea575a02ac34a2d08494445/contrib/gn_module_validation/frontend/app/components/validation.component.ts#L32-L46

Si vous êtes OK, je peux faire une PR

**Comment by camillemonchicourt** [comment]
OK, je ne sais pas pourquoi il y a le soucis dans le module VALIDATION mais pas dans la SYNTHESE alors que tout ce bloc est censé être factorisé entre les 2 modules, mais je vois bien le bug.
Pour la solution, pas d'avis.

**Comment by joelclems** [comment]
Cela viendrai de ce commit
https://github.com/PnX-SI/GeoNature/commit/a12c38cd4d85e4d4dbf9124d27812b5604fe2615

on a pas forcement envie d'avoir les meme filtre par defautl pour la synthese et la validaiton

il faudrait refaire marcher les filtre avancé dans un premier temps et voir si on met en place un config.VALIDATION.DEFAULT_FILTERS

**Comment by camillemonchicourt** [comment]
C'est bien de ne pas appliquer de filtres par défaut dans la Synthèse.
C'est un module pour les experts où il est important de bien tout voir par défaut.
