### ISSUE TITLE
"Internal Server Error" sur usershub

### ISSUE THREAD

**Issue by libes-osu** [PnX-SI/GeoNature#2471]
**Version**
Version de GeoNature affectée par le bug.

2.12.0

**Description du bug**
Description du problème rencontré (message d’erreur, code HTTP de retour inattendu, …).

j'ai installé geonature avec l'installation globale... sur une debian 11 

tout s'est bien passé 
http://139.124.2.131/geonature fonctionne
http://139.124.2.131/usershub fonctionne
mais
http://139.124.2.131/usershub provoque un "Internal Server Error"

il doit peut etre rester des scories d'une install précédente  ? car la 1ere install que j'ai faite j'avais pris le module usershub a part

**Comportement attendue**
Description du comportement attendue en lieu et place du problème rencontré.

**Comment reproduire**
Étapes à suivre pour reproduire le problème (sur quelle page se rendre, sur quel bouton cliquer, avec quelles données présentes, …).

**Logs**
Extrait du fichier ``/var/log/geonature.log`` dans le cas d’une erreur 500.
[install_all.log](https://github.com/PnX-SI/GeoNature/files/11209148/install_all.log)

**Comment by camillemonchicourt** [comment]
En regardant les logs de l'installation globale, tout a l'air d'avoir bien fonctionné.
Ensuite il semblerait que tu aies fait autre chose ? Modifier l'URL de ton serveur dans des configurations ? Réinstaller UsersHub tout seul ?
Il faudrait plus expliciter ce que tu as fait car je ne vois pas ce que tu entends pas "le probleme est que j'ai peut etre aussi pris le module usershub à part en dehors de l'install globale"

Dans ce cas, c'est plutôt un ticket UsersHub à faire, et surement regarder https://github.com/PnX-SI/UsersHub/issues/144

Voir la valeur du paramètre `URL_APPLICATION` dans le fichier ~/usershub/config/config.py ?

Tu as fermé le ticket volontairement car le soucis est résolu ?

**Comment by libes-osu** [comment]
eh bien je l'ai reinstallé en important le module à part 

oui effectivement l'URL etait restée avec un seul "/".. bien vu
je viens de corriger dans config.py , mais  l'erreur internal serveur persiste

il doit falloir relancer une config ?

M

**Comment by camillemonchicourt** [comment]
Il faut redémarrer UsersHub pour que la modification de la configuration soit prise en compte. Sûrement indiqué dans la doc.
sudo systemctl restart usershub (de mémoire)

**Comment by libes-osu** [comment]
parfait, merci
tout est rentré dans l'ordre usershub est en place :-)
j'avais relancé geonature, mais pas le module usershub

je vais me faire la main sur 'lutilsiation de l'ensemble de l'aplication
puis essayer d'installer le module atlas par la suite

merci a+
je ferme ce ticket

Maurice
