### ISSUE TITLE
Permissions : association de plusieurs filtres à une permission

### ISSUE THREAD

**Issue by bouttier** [PnX-SI/GeoNature#2472]
Dans le but de pouvoir restreindre une permission, non pas uniquement à une portée mais également à d’autres critères (taxonomiques, géographiques, sensibilité, …), il est nécessaire de faire évoluer le schéma des permissions.

- La table `cor_role_action_filter_module_object` devient `t_permissions`
- La table `t_filters` devient `bib_filters_values`
- Une nouvelle table `t_filters` est créée avec une FK vers les permissions et une FK vers les types de filtres.

Une contrainte d’unicité assurera qu’il n’existe qu’un unique filtre par type de filtre pour une permission donnée.

L’API d’accès aux permissions (`@check_cruved_scope`, `get_scopes_by_action`) assurera la rétro-compatibilité. Comme à présent, lorsque plusieurs permissions existent, le cruved maximum est renvoyé. En revanche, le cruved d’une permission donnée devra être calculé à partir d’une liste de filtre :
- S’il y a un filtre autre que SCOPE, le scope sera 0 (les permissions avec des filtres complexes sont ignoré par l’API « scope »)
- S’il y a un filtre SCOPE, sa valeur sera retenue
- S’il n’y a pas de filtre, le scope sera 3

Le SCOPE 3 est en conséquence retiré de `bib_filters_values` car équivalent à une absence de filtre. À noter que le SCOPE 0 sera également retiré avec la suppression de l’héritage des permissions (module GN vers les autres modules, objet ALL vers les atures objets).

**Comment by camillemonchicourt** [comment]
La nouvelle t_filters ne serait pas plutôt une table de correspondance du genre cor_permissions_filters ?

**Comment by bouttier** [comment]
Cette structure a été confronté à une autre solution consistant à, plutôt que d’introduire la table `t_filters`, ajouter une colonne à la table `t_permissions` par type de filtre (donc une colonne `scope_filter`, une colonne `geo_filter`, etc…).
Cela est possible car une permission est associé à un unique type de filtre (ce qui été déjà proposé via la clé sur le couple `id_permission` / `id_filter_type`).
L’avantage majeur est de pouvoir typer correctement la colonne en fonction du type de filtre, plutôt que de se restreindre à des filtres textuels. Ainsi, il est possible de mettre une FK vers un `cd_nom` ou un `id_area` par exemple.
Les tables `bib_filters_type` et `bib_filters_values` disparaissent ; la table `bib_filters_scope` apparait avec uniquement les valeurs des scopes, et ainsi `t_permissions.scope_filter` (de type int !) a une FK vers `bib_filters_scope`.

Autre sujet, la déclaration des permissions disponibles dans chaque module / objet / action (`t_permissions_available`). Celle-ci, plutôt que d’avoir une FK vers `bib_filters_type` contient donc également une colonne (booléenne) par type de filtre. Il n’est donc plus nécessaire d’avoir plusieurs lignes pour chaque type de filtre disponible pour une permission donnée.

**Comment by jpm-cbna** [comment]
Avec la solution proposé le 14 avril, comment fait-on pour gérer les valeurs multiples pour les filtres géo et taxo ?
Ajout de tables `cor_permission_filter_geo` et `cor_permission_filter_taxo` à la place des colonnes dans la table t_permissions ?

**Comment by camillemonchicourt** [comment]
Oui des tables de correspondance serait certainement l'idéal pour bien gérer et typer les filtres et en garantir la cohérence avec des clés étrangères vers Taxref ou l_areas.

**Comment by camillemonchicourt** [comment]
Le nouveau modèle de données des permissions a été intégré dans la 2.13.0.
