### ISSUE TITLE
API: GET contact/releves - rajouter infos taxons

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#248]
Il faudrait que le JSON renvoyé par cette route contienne des infos sur le taxon (nom_verna, nom valide, lb_nom et nom_complet_html) pour pouvoir les afficher dans le module carte-liste. Pour l'instant il n'y a que le cd_nom et le nom_cite.

**Comment by amandine-sahl** [comment]
A mon sens cette route drevrait être basée sur une vue

**Comment by camillemonchicourt** [comment]
OK fait et basé sur une vue.
