### ISSUE TITLE
Gérer des valeurs par défaut pour les nomenclatures

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#249]
L'idéal serait de le gérer directement dans la BDD car on n'aura pas tous les mêmes nomenclatures activées. Avec un champ booléen `default`. 

Mais comme les valeurs des nomenclatures peuvent dépendre du taxon, je ne vois pas encore clairement où il faudrait le gérer. `cor_taxref_nomenclature` ?

Si aucun taxon n'est selectionné, alors le défaut est une certaine nomenclature, si un taxon est selectionné ça peut être un autre. Il faut aussi surement définir un mécanisme de priorité entre ALL, regne, group2inpn si il trouve plusieurs default ?

**Comment by TheoLechemia** [comment]
Si on veut qu'il y ai des nomenclatures par défaut en fonction du taxon renseigné, pas le choix de le mettre dans  ``cor_taxref_nomenclature``. Mais du coup ça implique qu'il n'y ai pas de valeur par défaut tant qu'on a pas renseigné de taxon. 

Par contre j'ai remarqué qu'il y avait des nomenclatures qui n'était pas dans ``cor_taxref_nomenclature``, donc qui n'apparaissent jamais une fois le taxon sélectionné.

**Comment by camillemonchicourt** [comment]
Hum les nomenclatures c'est pas taxon par taxon mais par regne ou group2inpn.

Du coup la c pareil, les valeurs par defaut des nomenclatuures doivent etre par regne ou group2inpn

**Comment by TheoLechemia** [comment]
Oui en base on gère bien ça par groupe/regne
Mais dans le formulaire il faut avoir renseigné le taxon pour récupérer le groupe/regne et déduire la valeur par défaut

**Comment by camillemonchicourt** [comment]
Oui OK c ça. Quand on ouvre le formulaire les valeurs par defaut doivent correspondre à ALL er quand on choisit un taxon elles doivent eventuellement changer pour correspondre aux valeurs par defaut du regne ou group2inpn du taxon.

**Comment by gildeluermoz** [comment]
A la création de la table, set default via une fonction prenant les valeurs dans la ``meta.t_parameters``.

Etudier une ``meta.cor_default_ nomenclature_taxref_module`` avec possibilité de surcharge.
En backend, voir la vue et/ou la requête permettant de remonter l'unique valeur par défaut d'un taxon.

**Comment by gildeluermoz** [comment]
On a un gestion des valeurs par défaut dans le core et une par module.
Je ferme. Rouvrir un ticket si besoin de régler qq détails.
