### ISSUE TITLE
2.9 - Configuration module validation

### ISSUE THREAD

**Issue by LafageDenis** [PnX-SI/GeoNature#2498]
Bonjour, 

J'essaye d'ajouter des colonnes au module de validation mais le fichier de configuration ne semble pas pris en compte. 
Je précise que je suis sous la version 2.9.2.

J'ai suivi la doc [ici]([https://docs.geonature.fr/installation.html#module-config]) 
J'ai donc rajouté dans geonature/config/ un fichier validation_config.toml qui contient : 

```
[[COLUMN_LIST]]
column_label = "Taxon"
column_name = "taxref.nom_vern_or_lb_nom"
min_width = 250

[[COLUMN_LIST]]
column_label = "Date obs"
column_name = "date_min"
min_width = 100

[[COLUMN_LIST]]
column_label = "Jeu de données"
column_name = "dataset.dataset_name"
max_width = 100

[[COLUMN_LIST]]
column_label = "Observateur"
column_name = "observers"
min_width = 100

[[COLUMN_LIST]]
#column_label = "Stade de vie"
#column_name = "nomenclature_life_stage.label_default"
#min_width = 50
```
Je fais ensuite un 

```
sudo systemctl reload geonature
```
Aucun changement n'intervient. La colonne "Stade de vie" n'est pas ajoutée.

Merci d'avance

**Comment by jbrieuclp** [comment]
Salut Denis,
Il faut que tu "reconstruises" ton geonature : 
```
source ~/geonature/backend/venv/bin/activate
geonature update-configuration
sudo systemctl reload geonature
deactivate
```

Ca devrait être mieux

**Comment by LafageDenis** [comment]
Oui j'avais essayé ça aussi sans succès. 
J'ai même un fichier de conf dans ```contrib/gn_module_validation/config``` et un dans ```geonature/config```

Je précise que je n'ai aucune erreur lors de l'update...

**Comment by LafageDenis** [comment]
Ça y est j'ai trouvé !
Il fallait faire un : 
``` geonature update-module-configuration VALIDATION ```

En espérant que ça serve à ceux qui sont encore sur des vieilles versions !
