### ISSUE TITLE
[Synthèse/Validation] Question : une observation épinglée est visible de tous

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature#2507]
Dans le cadre d'une prestation pour l'Agence Régionale de la Biodiversité île de France, nous nous sommes demandés si les épingles sur les observations fonctionnaient comme prévu.

En effet, il semblerait que les autres utilisateurs puissent voir les observations épinglées par un utilisateur. Pour reproduire : 
- Se connecter en tant qu'admin
- Épingler une observation
- Se déconnecter puis se connecter en tant qu'agent ou autre utilisateur
- Rechercher les observations épinglées (via le filtre avancé "Est épinglé") 
- L'observation épinglée plus haut apparait

Est-ce le fonctionnement prévu ?
En re-parcourant la PR : https://github.com/PnX-SI/GeoNature/pull/1843, il semblerait que non :

> Un utilisateur ne peut voir que les épingles qu'il a créé lui-même

Merci d'avance pour vos éclaircissements !

**Comment by bouttier** [comment]
En effet il manque l’`id_role` dans le filtre : https://github.com/PnX-SI/GeoNature/blob/5e25a8c0541472e8aedb9c66eb989e544f8174ef/backend/geonature/core/gn_synthese/utils/query_select_sqla.py#L261

**Comment by camillemonchicourt** [comment]
En effet, les épingles sont censées être individuelles. Voir https://github.com/PnX-SI/GeoNature/issues/1819
Donc c'est un soucis si ce n'est pas répercuté dans la recherche de la Synthèse.

**Comment by mvergez** [comment]
Top merci pour vos retours, j'ai fait une PR qui règle le souci

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.12.3
