### ISSUE TITLE
Creation utilisateur - mauvais URL de confirmation

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#2511]
**Version**
2.12

**Description du bug**
Dans le mail renvoyé au validateur pour confirmer la creation de compte, dans le liens à clicker le nom de domaine est remplacé par une IP (locale de qui plus est)

cela viendrait de l'appel à `url_for`avec l'option `_external=True` ici 
https://github.com/PnX-SI/GeoNature/blob/5e25a8c0541472e8aedb9c66eb989e544f8174ef/backend/geonature/core/users/register_post_actions.py#L48

**Comportement attendue**
Un lien avec le nom de domaine et non l'ip

**Comment reproduire**
On peut ajouter une route de test dans gn_commons.route par ex (url : `.../geonature/api/gn_commons/test`

```            
@routes.route("/test", methods=["GET"])
def test():
    """
        test url_for
    """
    # return current_app.config['API_ENDPOINT'] + url_for("users.confirmation", token='youk')
    
    return url_for("users.confirmation", token='youk',  _external=True)
```
https://outils.cevennes-parcnational.net/demo-sipaf/geonature/api/gn_commons/test

**Proposition**

Remplacer `url_for("users.confirmation", token='youk',  _external=True)` par `current_app.config['API_ENDPOINT'] + url_for("users.confirmation", token='youk')`

**Comment by bouttier** [comment]
`url_for` avec `_external=True` utilise la variable `SERVER_NAME` définie par le middleware `ProxyFix` à partir du header `X-Forwarded-Host`, définie par ton reverse-proxy (généralement Apache). Je suspect donc une mauvaise configuration de ton proxy.

**Comment by joelclems** [comment]
C'est exactement ça

en rajoutant les options  ` proxy_set_header` dans la conf nginx ça marche

```
location /some/path/ {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass ....
}
```

https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/
