### ISSUE TITLE
[Synthèse] Ajout d'un filtre (id_source)

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature#2513]
Salut !

Dans le cadre d'une prestation pour l'Agence Régionale de la Biodiversité en île de France, un filtre sur la source de provenance de la donnée dans la synthèse est souhaitée.

J'ai testé un fonctionnement rapide en ajoutant "id_source" dans la fonction `filter_other_filters` et en ajoutant dans `dynamicFormConfig.ts` : 
```typescript
{
    type_widget: 'datalist',
    attribut_label: 'Source de la donnée',
    api: 'synthese/sources',
    application: 'GeoNature',
    keyValue: 'id_source',
    keyLabel: 'name_source',
    data_path: '',
    required: false,
  }
```

Et ça fonctionne très bien !

Néanmoins, je ne sais pas si l'utilisation du `type_widget: 'datalist'` est à privilégier. Ma question est donc la suivante : 
- Préférez-vous créer un composant spécifique pour cette utilisation ?
- Un widget spécifique ? à la `type_widget: 'observers'` ?
- On reste sur ça ?

Qu'en pensez-vous ?

Merci beaucoup pour vos retours !

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.13.0.
