### ISSUE TITLE
filtre avancé id_synthese

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#2516]
J'ai une demande du Parc des Pyrénées pour ajouter un filtre avancé `id_synthese`

**Comment by bouttier** [comment]
Je me demande s’il ne devrait pas être possible de saisir plusieurs id synthèse ?

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.13.0, avec un seul id_synthese possible en recherche.
