### ISSUE TITLE
[2.12.2] champ additionnel checkbox non fonctionnel

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/GeoNature#2518]
**Version**
2.12.2

**Description du bug**
J'ai un champ additionnel de type checkbox ("Test_add") au niveau du relevé. Comme expliqué dans la note de version, j'ai mis à jour la liste des valeurs :
`[{"label": "trois", "value": 3}, {"label": "quatre", "value": 4}, {"label": "autre", "value": "autre"}]`

Je remplis une ou plusieurs valeurs dans la checkbox du formulaire, puis j'enregistre le relevé => ok, j'ai bien mon _additional_fields_ renseigné correctement.

Si je retourne sur le formulaire du relevé pour l'éditer, les checkbox ne retournent aucune valeur (aucune n'est cochée). Si j'essaye de rechecker des cases pour modifier mon relevé, le résultat est assez aléatoire. Par exemple, en essayant plusieurs fois de suite, je me retrouve avec ce type de valeur dans _additional_fields_ :  `{"Test_add": ["3", "4", "4", "autre", "3", "4", "3"]}`

**Comportement attendu**
Afficher les valeurs dans les checkbox une fois le champ rempli et enregistré. 

**Comment reproduire**
Configurer un champ additionnel de type "checkbox", puis faire un test de saisie avec ce champ.

**Comment by joelclems** [comment]
Il faudrait essayer en changeant la liste de valeur avec 
```
[{"label": "trois", "value": "3"}, {"label": "quatre", "value": "4"}, {"label": "autre", "value": "autre"}]
```

ou les champs `value` sont des string et non des nombres, car la valeur renvoyée par le composant est une liste de chaine de caractères

**Comment by joelclems** [comment]
j'ai testé et ça avec avec cette modif
https://github.com/PnX-SI/GeoNature/pull/2520/files

**Comment by Splendens** [comment]
Parfait, ça fonctionne. Merci pour la correction !

**Comment by joelclems** [comment]
Idéalement il faudrait pouvoir gérer mieux ça quand on a des entier pour valeurs, mais ça résoud le pb en attendant

**Comment by joelclems** [comment]
le commit [73ced60](https://github.com/PnX-SI/GeoNature/commit/73ced60e6297b7b98123d8d2b676d4e625343deb) permet de d'utiliser des entier pour les valeurs

**Comment by camillemonchicourt** [comment]
Le problème sera corrigé dans la prochaine version de GeoNature.

Comme indiqué par @TheoLechemia dans la PR : 

Le problème vient bien du fait qu'avant on postait toujours des "string" même si le tableau de `values` comportait des entiers.  Cette PR corrige bien le problème.
Attention cependant, il faut donc que tout ceux qui utilisaient des checkbox, continuent à avoir des "string" dans la clé `values` : `[{"label": "Un", "value": "1"}]` sans quoi il y aura des problèmes à l'édition. Ou alors qu'il fasse un UPDATE en base pour convertir leur `string` en entier.

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.13.0.
