### ISSUE TITLE
Erreur 401 – Ecrans Login

### ISSUE THREAD

**Issue by LudmillaT** [PnX-SI/GeoNature#2521]
Bonjour, 
Nous rencontrons des difficultés après avoir changé le nom de domaine de notre application GeoNature en suivant la documentation des réserves naturelles (https://si-en-reseau.reserves-naturelles.org/documentation-geonature/domaine.html) 

**Version**
GeoNature : 2.11.0
Taxhub : 1.10.7

**Description du bug**

Tout d’abord lorsqu’on se connecte avec un compte existant, ou qu’on est loger de mémoire sur GeoNature on ne rencontre à priori aucune erreur dans le fonctionnement de la plateforme. 
Cependant, lorsqu’on est sur la page login il y a une erreur dans la console : Failed to load resource: the server responded with a status of 401 (UNAUTHORIZED) cf image ci-dessous 

![image](https://user-images.githubusercontent.com/102731713/234791284-91b92ff7-26f8-4903-9f55-823ca410373c.png)

Cette erreur n’empêche pas la connexion mais on ne peut ni changer de mot de passe ni créer un nouveau compte, si on essaie une erreur 502 (Proxy Error) apparait cf image ci-dessous

![image](https://user-images.githubusercontent.com/102731713/234793282-6f5f2bfc-41dc-4427-926c-6db6c321035d.png)

Du coter de taxhub aucune erreur.

**Comportement attendue**
Possibilité de crée des comptes et récupérer des identifiant 

**Comment reproduire**
A priori le seul changement qu’on a fait est, comme je le signalé plus haut, un changement de nom de domaine selon la docs des réserves naturelles

**Logs**

```
[2023-04-27 09:32:54 +0200] [416741] [CRITICAL] WORKER TIMEOUT (pid:416744)
[2023-04-27 09:32:54 +0200] [416744] [INFO] Worker exiting (pid: 416744)
[2023-04-27 09:32:54 +0200] [422493] [INFO] Booting worker with pid: 422493
```

On a tenté de modifier les paramètres de configuration mais sans succès. Auriez vous des idées de ce qui peut provoquer cette erreur ? 
Merci d’avance pour vos retours

**Comment by mvergez** [comment]
Bonjour,

> Cependant, lorsqu’on est sur la page login il y a une erreur dans la console : Failed to load resource: the server responded with a status of 401 (UNAUTHORIZED) cf image ci-dessous

Je crois que sur certaines instances, un appel au backend était effectué pour tester si on était connecté ou pas. Ce comportement semble donc normal.

> Cette erreur n’empêche pas la connexion mais on ne peut ni changer de mot de passe ni créer un nouveau compte, si on essaie une erreur 502 (Proxy Error) apparait cf image ci-dessous

Cela n'est cependant pas normal. 
Il y a un worker timeout ce qui veut dire que le backend met du temps à répondre, et donc est "tué" pour qu'il puisse redémarrer. Quand on change de mot de passe ou que l'on crée un compte, le backend envoie un e-mail. Avez-vous testé que l'envoi d'e-mail depuis le serveur fonctionne ? 
Si vous avez changé de nom de domaine, l'avez-vous aussi changé pour le serveur mail ? (Peut-être que cela n'a rien à voir...)

**Comment by LudmillaT** [comment]
Bonjour @mvergez, 

Avant le changement de nom de domaine les mails fonctionnaient correctement et nous n'avons rien modifier de ce coter là. 

Aussi avant la mise en place du serveur mail j'avais rencontrer quelques problèmes lier a l'envoie de mail justement mais dans ce cas l'inscription était prise en compte par UsersHub (elle apparaissait dans Demandes de compte) ce qui n'est pas le cas ici. 

Du coup ça pourrais peut-être un problème de communication entre GeoNature et UsersHub ?

**Comment by mvergez** [comment]
C'est étrange... Parce qu'à ce que je vois, si vous avez juste changé de nom de domaine et suivi la doc que vous avez mentionné à la lettre ça devrait fonctionner. Mais oui cela doit venir en effet de la communication entre GeoNature UsersHub

Quelques pistes : 
- Avez-vous actualisé le paramètre `URL_USERSHUB` dans la configuration GeoNature ? (exemple ici : https://github.com/PnX-SI/GeoNature/blob/5e25a8c0541472e8aedb9c66eb989e544f8174ef/config/default_config.toml.example#L76-L81)
- A l'inscription, le backend fait un appel à l'`URL_USERSHUB`, il faudrait tester que le serveur soit capable de le faire. Par exemple, si vous avez mis l'adresse avec le nom de domaine plutôt que quelque chose comme "http://127.0.0.1:5001" cela peut ne pas marcher

En espérant que cela vous aidera...

Bon courage !

**Comment by LudmillaT** [comment]
Oui j'ai actualisé `URL_USERSHUB` avec le nom de domaine (avant le changement cela fonctionner comme ça)  j'ai aussi tester avec `http://localhost:5001/` et d'autres variante mais à chaque modification rien ne change.

En tout cas merci pour vos retours @mvergez ça me permet d'explorer certaines piste !

**Comment by camillemonchicourt** [comment]
Bonjour. As-tu toujours le soucis ? Ou pu identifier le problème ?

**Comment by LudmillaT** [comment]
Bonjour, 
Le souci est toujours là, mais nous n'avons pas plus investigué dessus car apparu sur une version test, le problème a l'air d'être intervenue après un changement de nom de domaine. Pour la version plus définitive sur laquelle on va travailler, nous ne ferons pas ce changement donc le problème ne devrait pas se reproduire ou nous recommencerons à chercher une solution à ce moment.

**Comment by LudmillaT** [comment]
Pour revenir sur cette erreur le vrai problème était l'apparition d'une erreur 502 lors de la création de compte ou de la récupération de mots de passe. 

Pour résoudre cette erreur nous avons modifier le fichier `/etc/hosts` et ajouter la ligne `127.0.0.1	mon_serveur.fr` en s'aidant des fichier mis en ligne par le CBN alpin (https://wiki-sinp.cbn-alpin.fr/serveurs/installation/hosts-hostname).

Dorénavant tout fonctionne correctement.

**Comment by camillemonchicourt** [comment]
OK ça doit être assez spécifique à votre contexte car faire cela n'a pas été remonté auparavant.
