### ISSUE TITLE
[2.12.2] Synthese - Recherche  et export via fichier local (shp, geojson)

### ISSUE THREAD

**Issue by pierre56** [PnX-SI/GeoNature#2522]
**Version**
[2.12.2]

**Description du bug**

Objectif : Recherche et Export des données depuis la synthèse a partir de la geom d'un fichier local shp

je voudrais savoir si c'est  une erreur de ma part ou une régression.
Je n'utilisais pas la fonction donc j'ai un doute si le feat existe.
Mais il me semble que mes collègues m'ont remonté un jour qu'il pouvait mettre du shp et que ça marchait bien.

**Comportement attendue**

Dans la synthèse, il faudrait pouvoir importer un shapefile ou un geojson.
Et lancer la recherche a partir de l'objet.
Puis permettre les différents export a partir de cette recherche.

**Comment reproduire**

Ajout un fichier local, Grace a l'onglet "Load local file" du composant map. 
Mais il manque le format shp (il me semble que c'était faisable avant)
Dans la version actuelle, j'ai réussi a importer un geojson en 4326 converti d'un shp.

Cependant lorsque je lance la recherche, j'ai une erreur qui pète et ça ne cherche pas sur le geom importé.
![image](https://user-images.githubusercontent.com/26764293/234910760-1d1f0f85-7c84-464f-93e8-c323f5232b8a.png)

**Logs**

```
[2023-04-27 17:23:53 +0200] [407147] [ERROR] Exception on /synthese/for_web [POST]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_permissions/decorators.py", line 56, in decorated_view
    return view_func(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/routes.py", line 190, in get_observations_for_web
    synthese_query_class.filter_query_all_filters(g.current_user, scope)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/utils/query_select_sqla.py", line 414, in filter_query_all_filters
    self.apply_all_filters(user, scope)
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/utils/query_select_sqla.py", line 392, in apply_all_filters
    self.filter_other_filters()
  File "/home/geonatureadmin/geonature/backend/geonature/core/gn_synthese/utils/query_select_sqla.py", line 341, in filter_other_filters
    wkt = loads(str_wkt)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/shapely/wkt.py", line 22, in loads
    return geos.WKTReader(geos.lgeos).read(data)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/shapely/geos.py", line 327, in read
    raise TypeError("Only str is accepted.")
TypeError: Only str is accepted.

```

Je vais faire l'export en manuel, et je demande aux collègues de moins utiliser le shp a cause des limitations.
Mais ça reste quand mm le format le plus courant lors d'échanges entre structures.

Merci

**Comment by mvergez** [comment]
Bonjour @pierre56,

Je viens de regarder rapidement avec un geojson (je pense que le fonctionnement est le même que le shapefile) et le bug apparait aussi.
En réalité, j'ai l'impression que le bug a l'air d'être apparu récemment. Après analyse, voilà le souci : 
- Lecture du fichier geojson/wkt en front
- Envoi d'un wkt en backend via le json suivant (simplifié volontairement) : 
```json
{"modif_since_validation":false,
 "geoIntersection":
       ["MULTIPOLYGON (((5.37051721694198 43.1766980975547, 5.3707068000919 43.176523852765)))"]
}
```
- geoIntersection est un tableau 
- Or le récent commit suivant https://github.com/PnX-SI/GeoNature/commit/5c8e5f36dbefb5129a9ea13c926035580ab4ccd7#diff-5f82a87cc3b476fb1d08f9ccecf3bf746aa8653dd1fe144bf7300cad957effcfR319-R333, ne parcours plus chaque élément du tableau mais le donne tel quel, d'où l'erreur : "Only str is accepted"

A voir ce qu'en pensent les autres, mais je pense qu'il faudrait revenir comme cela était avant. J'ai testé et cela fonctionne. Je peux faire une PR si besoin

**Comment by camillemonchicourt** [comment]
Bonjour.

Il n'est possible de charger que des fichiers au format GeoJSON ou KML, qui sont traitables par le frontend, contrairement au SHP qui devrait être géré côté serveur et n'est donc pas prévu.

OK si il y a une régression sur le chargement des GeoJSON.

**Comment by camillemonchicourt** [comment]
Pour ce commit en question, @bouttier a fait en sorte de bien reprendre les filtres et de les typer quand on a vu que les filtres booléens avaient un soucis.
Je ne pense pas qu'il faille revenir en arrière sur ça.
On a vérifié tous les filtres mais sûrement que celui-ci nous a échappé lors des tests.

**Comment by mvergez** [comment]
Merci @camillemonchicourt pour ces précisions.
Effectivement je me suis mal exprimé : je proposais de revenir en arrière sur spécifiquement ce filtre, pas le reste.

A voir avec @bouttier donc.

**Comment by mvergez** [comment]
Au passage, pour convertir facilement des shp en geojson, https://mapshaper.org/ fonctionne plutôt bien

**Comment by bouttier** [comment]
Après discussion avec @TheoLechemia, il apparait plus pertinent que le front envoi directement du geojson plutôt que du WKT (la conversion du geojson en WKT datant probablement de l’époque où les filtres étaient envoyés en query string).

**Comment by bouttier** [comment]
Correction dans la PR #2527

**Comment by camillemonchicourt** [comment]
OK merci pour le retour.
On clôturera vraiment le ticket quand celui-ci sera disponible dans une release officielle et disponible pour tous.

**Comment by pierre56** [comment]
@camillemonchicourt 
j'en tiendrais compte pour les prochains tickets 👍

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.12.3

**Comment by bouttier** [comment]
C’est disponible en 2.12.3 !
