### ISSUE TITLE
[2.12.3] Champ additionnel "Select" reste grisé et non modifiable si une valeur par défaut est renseignée

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/GeoNature#2540]
**Version**
2.12.3

**Description du bug**
Sur une instance, j'ai des champs additionnels de type select. Comme expliqué dans la note de version, j'ai mis à jour les listes de valeurs, par exemple : 

`[{"label": "N", "value": "N"}, {"label": "NE", "value": "NE"}, {"label": "E", "value": "E"}, {"label": "SE", "value": "SE"}, {"label": "S", "value": "S"}, {"label": "SO", "value": "SO"}, {"label": "O", "value": "O"}, {"label": "NO", "value": "NO"}, {"label": "indifférente", "value": "indifférente"}]`

Si je renseigne une valeur par défaut pour ce champ, la case correspondante dans le formulaire contient bien la bonne valeur, mais la case reste grisée et n'est pas modifiable.

**Comportement attendu**
Avoir la valeur par défaut renseignée pour un champ et pouvoir le modifier.

**Comment reproduire**
Configurer un champ additionnel de type "select" avec une valeur par défaut et tester un saisie.

**Comment by Splendens** [comment]
Ah oui, sans les guillemets ça fonctionne bien pour mes valeurs textuelles.
Merci !

**Comment by camillemonchicourt** [comment]
A indiquer quelque part dans la doc des champs additionnels, ou dans les textes d'aide de l'admin des champs additionnels ?

**Comment by TheoLechemia** [comment]
J'ai précisé le texte d'aide.
Pour le texte d'aide en plus petit, ça viendra avec la prochaine version de Flask-admin (1.6.1)

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.13.0, et texte d'aide amélioré.
