### ISSUE TITLE
[INSTALL] Diviser le fichier `install/03_install_db.sh`

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#2544]
Séparer le fichier `install/03_install_db.sh` en plusieurs parties (https://github.com/PnX-SI/GeoNature/blob/master/install/03_create_db.sh)

on pourrais garder ce fichier qui ferait appel à deux scripts

- `install/db/install_db`
  -  avec toutes les actions nécéssitant `sudo -u "postgres"`
  - on pourrait créér le script `create_extension.sql` pour pouvoir le réutiliser par ailleurs (cf dockerisation)
    - https://github.com/PnX-SI/GeoNature/blob/2c3b17f7e2bdbf2cd23c8d2be52c7b47b5ad4baf/install/03_create_db.sh#L80-L84  

- `installdb/process_migration_and_data.sh`
  - pour jouer toutes les migrations alembic
     - `geonature db upgrade`
     - `geonature db autoupgrade`
  - et les commandes d'insertions de données     
    - `geonature taxref ...`
    - `geonature sensitivity ...`
    - !! à rendre `reusable` (pouvoir tester si la commande à déjà été jouée auparavent (en regardant dans la base ...)

On pourrait ensuite réutiliser le fichier  `installdb/process_migration_and_data.sh` dans les actions de test des modules 
  - peut être en faisant une version `ligth` qui suffirai aux test du module 
    - ou l'on installe qu'un type de maille ou autre
    - et ou on n'installe pas les statuts
    - voir:

https://github.com/PnX-SI/gn_module_import/blob/9e1c7170129721d4a0e88d61b7193d9f2fe5e98d/.github/workflows/pytest.yml#L96-L103

**Comment by camillemonchicourt** [comment]
Si on garde ce fichier qui fait lui-même appel à 2 scripts, on va commencer à s'y perdre et pas simple en terme de lisibilité, non ?

Je partirai plutôt sur découper ce script en 2 : 
- 03a_install_db_structure.sh
- 03b_install_db_data_migrations.sh

**Comment by joelclems** [comment]
j'hésitais entre les deux, il faudra bien répercuter le changement de nom partout (script et docs)

**Comment by joelclems** [comment]
petit points à régler

- les logs
  - pour la partie create db on pourrais laisser tel quel
  - pour la partie alembic data on peut logger la sortie du script `03b_install_db_data_migrations.sh |& tee -a "${LOG_FILE}"`
    - ça joue sur l'emplacement des fichiers 
- gérer `DATA_DIRECTORY` (selon si on est en `MODE=dev`

**Comment by joelclems** [comment]
J'ai choisit de garder la partie `install_db`telle quelle dans le script `03_install_db.sh` (elle n'a pas vocation à être utilisée ailleurs)
(j'ai seuelement ajouter un fichier `create_extentions.sql` pour référencer les extentions installées (hors `posgis` & co) pour pouvoir l'utiliser ailleurs).

et de placer la partie `alembic` + commande d'installations de données (`taxref`, `sensitivity`) dans un script à part et appelé dans `install/db/process_migration_and_data.sh`

il y aussi un fichier `install/db/process_migration_and_data_for_test.sh`, un peu plus ligth pour les actions `pytest.yml` et `cypress.yml` (ça irai presque pour le module d'import si ce n'est qu'on a des grille en 10 et pas en 5) (https://github.com/PnX-SI/gn_module_import/blob/master/.github/workflows/pytest.yml)

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.13.0
