### ISSUE TITLE
Occtax, formulaire de saisie : recherche de taxons très lente

### ISSUE THREAD

**Issue by Amegilla** [PnX-SI/GeoNature#2551]
seveur ovh 8Go ram, installation geonature récente (2.11, début d'année)
version geonature : 2.12.3
version taxhub : 1.11.1

Bonjour, 
J'ai un problème sur mon instance geonature :
le déroulant de propositon de noms pour la saisie d'un taxon prends 5 à 10 secondes à s'afficher ce qui rends la saisie de relevés très très lente !

J'ai testé des requêtes en bdd sur la table vm_taxref_list_forautocomplete et le délai de réponse est très rapide donc cela ne semble pas venir de là.

J'ai laissé un terminal ouvert avec la commande 'top' lancée pour voir ce qu'il se passait sur mon serveur en même temps qu'un recherche de taxon dans le formulaire. Je vois jusqu'à 6 tâches posgres qui se lancent en même temps. Comme si à chaque lettre ajoutée dans le formulaire une requête se lancait. Ce qui pourrait expliquer la lenteur...
Vous avez déjà a eu ce pb ? Des idées de tests/solutions pour trouver d'ou cela peut venir ?

merci pour votre aide

**Comment by TheoLechemia** [comment]
Salut,
Est-ce que tu peux renvoyer le retour de la commande : 
`geonature db status taxonomie`
et lister les index présents sur la vue materialisé "taxonomie.vm_taxref_list_forautocomplete"

**Comment by Amegilla** [comment]
OK c'est bon j'ai trouvé ! 
Mes Jdd n'ont pas de id_taxa_list, la colonne est à 'null' et donc la requete se fait sur absolument tout taxref.
Si je mets une liste (100) là c'est instantané.
OUF!
J'espère que cela sera utile à d'autres si jamais.

**Comment by camillemonchicourt** [comment]
Hum.
On n'est censé associer un JDD à une liste de taxons seulement quand un JDD nécessite une liste spécifique, pas sur tous les JDD.

Pour tous les JDD, soit on s'appuie sur la paramètre global d'Occtax définissant une liste de JDD pour tous les JDD n'ayant pas de liste de taxons spécifique, soit on n'en définit pas et ça tape dans tout Taxref, et c'est censé fonctionner correctement dans ce cas aussi.

En plus si il y a plusieurs connexion PG qui se lancent à chaque fois qu'on tape une lettre, il y a peut-être un truc à améliorer ou revoir ?

**Comment by TheoLechemia** [comment]
Pour les connexions à PG, effectivement ce n'est pas normal.
Et pour les perfs : @mvergez a fait une PR qui ajoute des index sur la VM. ça marche très bien, même sur tout Taxref (c'est pas encore releasé dans TaxHub)

**Comment by Amegilla** [comment]
Ok, où est défini le parmètre global occtax pour la liste de saisie par défaut ?
Cela n'a de toute façon pas trop de sens (pour la saisie) de rechercher dans tout taxref.
Et dans la synthèse, j'ai des perfs qui ne sont pas ultra rapide mais satisfaisantes, c'est pas le même mécanisme ?

**Comment by TheoLechemia** [comment]
Le paramètre d'occtax est là : 
https://github.com/PnX-SI/GeoNature/blob/master/contrib/occtax/occtax_config.toml.example#L13

C'est à peu près le même mécanisme dans la synthèse, mais ça interroge uniquement les taxons présent dans la synthèse

**Comment by Vottana** [comment]
[Geonature 2.12.3, Debian 11, 32 Go de ram, 8 CPU, 500 Go de disque]

Bonjour à toutes et tous, 

je me permets de rouvrir cette issue, (ou peut-être dois-je en poster une nouvelle ?).
J'ai exactement le même problème. Notre instance est enfin installée, le serveur est tout neuf, mais la recherche de taxons est extrêmement lente. Pour les lettres "pie" cela mets entre 15 et 20 secondes pour que la liste de choix s'affiche.
En testant avec une instance Geonature qui a environs 67000 taxons, la liste s'affiche quasi instantanément. Nous en avons environs 14000.

J'ai essayé la commande `top`, j'avoue ne pas du tout savoir comment lire les informations qui en ressortent, ou voir les infos qui pourraient m'aider dans mon problème (je vais potasser les tutos dans l'internet 🤓)
J'ai bien créé ma liste de taxons, avec le code `id_taxon_list = 100`, dans `bib_noms` et `cor_nom_listes`.
J'ai créé un fichier de configuration `occtax_config.toml` avec le paramètre `id_taxon_list = 100`, mais je me demande :
- où doit être placé ce fichier ? Dans le doute, je l'ai mis à 2 endroits : geonature/config et geonature/contrib/occtax. Logiquement je le mettrais dans occtax...mais... qui sait !
- est-ce qu'il faut l'activer comme pour les fichier .conf ? J'ai essayé le `update-module-configuration` [https://docs.geonature.fr/admin-manual.html#configuration-d-un-gn-module] mais j'ai le message d'erreur "commande introuvable" (j'ai essayé aussi en mettant : `update-occtax-configuration`). 

J'ai essayé la commande `geonature db status taxonomie` mais cela me renvoie `commande introuvable`. 
Et donc, d'après vos échanges, cela n'est pas en lien avec les JDD, mais ça a apparemment résolu le problème ?

Merci d'avance pour vos retours,
Vottana
