### ISSUE TITLE
[OCCTAX]Modification localisation relevé non disponible

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/GeoNature#2552]
**Version**
2.11.2 ; 2.12.2

**Description du bug**
Sur la carte, l'icone de modification des géométries du relevé n'est pas actif (et indique `No Layer to edit`). Il est donc impossible de déplacer un point. 

**Comment reproduire**
Dans le module occtax, modifier un relevé

**Comment by TheoLechemia** [comment]
Si c'est un point, on utilise pas leaflet draw, tu peux directement cliquer à un autre endroit sur la carte, ou déplacer le point (je remarque cependant un bug sur le déplacement...)
