### ISSUE TITLE
MAP component - Pouvoir uploader un fichier GPX

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#256]
Évoqué sur https://github.com/PnX-SI/GeoNature/issues/246

Dans un premier temps on peut utiliser le plugin https://github.com/makinacorpus/Leaflet.FileLayer développé pour Geotrek-admin et qui permet de charger et afficher un (ou plusieurs) fichier(s) GPX, KML ou GeoJson et de l'afficher sur la carte. Pour les GPX les attributs de la balise NAME sont affichés en tooltip au survol. 

A voir ensuite pour pouvoir sélectionner un objet et utiliser sa géométrie comme GEOM du relevé.

**Comment by gildeluermoz** [comment]
C'est une très bonne piste intermédiaire en effet.
Pour la suite, un même GPX peut contenir points lignes et polygones. L'interface devra donc prévoir l'ergonomie et les fonctionnalités permettant de choisir parmi les géométries du GPX, celle qui sera utilisée pour l'observation. Un bon morceau. Voir comment scinder ce ticket en 2 parties.

**Comment by camillemonchicourt** [comment]
Oui dans un premier temps utiliser Filelayer permet de répondre à 80% du besoin car on charge un fichier, il affiche les points, lignes et polygones de celui ci directement et le contenu de la balise name au survol d'un objet sur la carte. L'utilisateur n'a plus qu'à localiser son observation sur la carte en s'appuyant sur les objets affiches sur celle-ci.

Pouvoir en plus selectionner un des objets et utiliser sa géométrie ajoute une grosse mécanique pour pas forcément grand chose.

Je commencerai donc bien uniquement par le plugin Flielayer et à voir ensuite si il faut aller plus loin.

**Comment by camillemonchicourt** [comment]
Composant générique créé à partir du plugin Leaflet.FileLayer : https://github.com/PnX-SI/GeoNature/commit/2f4e58cc378643da45dac3204702720eb6f6a848

Et mis en place dans le module Synthèse pour le moment : https://github.com/PnX-SI/GeoNature/commit/0a9c23a50815c80ac469fd74b4c3b07be2b7564c

**Comment by camillemonchicourt** [comment]
Le plugin permet de charger un GPX, KML ou GeoJSON. 
Toutes les infos associées aux objets qu'ils contiennent sont affichées dans le tooltip au survol de l'objet. 
Dans la Synthèse, les objets chargés peuvent être utilisées comme zone de recherche. 
Le plugin sera aussi ajouté dans les modules de saisie comme Occtax pour pouvoir afficher des points de repères et leurs attributs directement sur la carte.

![2018-12-geonature-filelayer](https://user-images.githubusercontent.com/4418840/50290876-48c00180-046d-11e9-9617-25ac2366141a.gif)

**Comment by camillemonchicourt** [comment]
A ajouter sur le module Occtax.

**Comment by DonovanMaillard** [comment]
Au passage, sur la rc4.1 le chargement d'un geojson pour une recherche dans la synthese n'est pas fonctionnel pour moi. Le zonage fait le tour de la terre au nord globalement....  J'ai essayé en 2154 et 4326 même résultat.
Une piste ?

**Comment by camillemonchicourt** [comment]
Ça doit être ton GeoJSON.
Voir http://wiki.geojson.org/GeoJSON_draft_version_5

Il fonctionne dans QGIS ?
Par défaut il faut mieux faire des GeoJSON en 4326.

Partage le ici pour voir.

**Comment by camillemonchicourt** [comment]
Je confirme que c'est ton export SHP >> GeoJSON qui a pas été bon. 
Il faut bien exporter en GeoJSON, projection 4326 et là ça fonctionne bien avec ton fichier.

**Comment by DonovanMaillard** [comment]
Oups. J'ai pourtant vérifié plusieurs fois. Et j'ai donc fait la même erreur plusieurs fois.... Merci ! Et désolé du dérangement, je vais me cacher ;)

**Comment by TheoLechemia** [comment]
Intégration de cette fonctionnalité dans Occtax: https://github.com/PnX-SI/GeoNature/commit/ac178c4d4f057acf303e1badf39937bdd0745ebf
