### ISSUE TITLE
Synthese form - Recherche des observateurs avec/sans accent et plusieurs observateurs en même temps

### ISSUE THREAD

**Issue by andriacap** [PnX-SI/GeoNature#2568]
Bonjour,

Dans le cadre d'une prestation avec l'ARB IDF , il a été évoqué le fait de pouvoir : 

- Faire une recherche d'observateur insensible aux accents
- Filter la recherche sur plusieurs observateur (à ma connaissance on ne peut effectuer une recherche que sur un observateur en particulier)

Je vais suggérer une PR pour pouvoir proposer ces fonctionnalités là.
Merci pour vos retours et au plaisir d'échanger sur le sujet .

Bonne fin de journée

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.13.0.
