### ISSUE TITLE
Enregistrement relevé - Redirection vers MapList

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#257]
Quand on enregistre un relevé, rediriger automatiquement vers la page MapList du module.

**Comment by TheoLechemia** [comment]
Done.
A voir si on demande à l'utilisateur si il veut rester sur la page formulaire pour enchaîner sur un autre relevé ?

**Comment by gildeluermoz** [comment]
On peut envisager 3 boutons : 
* ``Enregistrer`` --> on reste sur le formulaire et on passe en update du relevé en cours si on y est pas déjà. L'utilisateur peut poursuivre et compléter son relevé. Utile surtout s'il est long (bcp de taxons). Ca permet une sauvegarde intermédiaire évitant de tout perdre pour une raison x ou y.
* ``Enregistrer et fermer``  -->  revenir sur le MapList
* ``Enregistrer + nouveau relevé``  -->  on vide le formulaire pour un nouveau relevé.
Voir un 4ème : 
* ``Enregistrer et dupliquer``  --> on ne duplique que la partie relevé

**Comment by camillemonchicourt** [comment]
Je ne suis pas favorable à avoir différents boutons, différents scénarios de navigation. Ca complexifie, et oblige à comprendre ce qu'on a derriere chaque bouton. 

Pour moi il ne doit y avoir qu'un circuit : 
MAPLIST >> AJOUT/EDITION RELEVE >> ENREGISTREMENT >> MAPLIST et ça boucle si on veut modifier/ajouter un autre relevé. 

Pour la duplication, je pense que c'est un faux besoin. C'était utile quand on avait une approche par observation avec chacun leur localisation. Mais vu qu'on travail par relevé, ça perd son utilité. Dupliquer un relevé est surement peu utile. 
A voir à l'usage mais je préfère ne pas le proposer pour le moment. 
Et si on doit mettre en place une duplication, je la ferai depuis la liste car ça permet de dupliquer n'importe quel relevé, pas seulement celui qu'on vient de saisir.

**Comment by camillemonchicourt** [comment]
Le défaut de cela est que l'on enregistre que quand le relevé global est fait. 
Pour un long relevé, en cas de soucis, on a un risque de perte de ce qui est en cours.
