### ISSUE TITLE
Affichage de la variable au lieu de la valeur

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#2576]
**Version**
2.12.3

**Description du bug**
Sur la carte, le bouton mailles affiche le nom de la variable
![image](https://github.com/PnX-SI/GeoNature/assets/10024739/c6d8503b-bbbd-4011-bcbe-effcce0b8a5a)

**Comportement attendu**
Utiliser la valeur "Mailles" qui se trouve dans le fichier i18n/fr.json
est-ce qu'il manquerait l'installation de la librairie qui fait le translate ou est-ce un bug ? Dans la demo en 2.12.2 ça affiche bien le texte "Mailles".

**Comment reproduire**
J'ai migré de la 2.11.2 à la 2.12.3. Je n'ai pas vu de message d'erreur et tout le reste fonctionne très bien.

**Comment by mvergez** [comment]
Bonjour,

C'est étrange, je n'ai pas eu ce comportement en develop. Je n'ai pas testé en 2.12.3, mais j'ai dû y passer à travers un commit et ça ne me rappelle rien.

La traduction est chargée dynamiquement, donc il y aurait eu d'autres soucis un peu partout s'il y avait un problème de librairie je pense.

Le front fait bien appel à la route assets/i18n/fr.json ?
Quel est le contenu de la réponse ? Ce contenu ci dessous est bien présent sous la clef `synthese` ? 
```json
    "Map": {
      "AreasToggleBtn": "Mailles"
```

**Comment by gildeluermoz** [comment]
Merci Maxime.
Effectivement Camille c'est un soucis de cache. Ni ctrl + F5 ni ctrl + r ne fonctionne mais si je charge la page dans un autre navigateur ça affiche bien "Mailles".
Merci à tous les 2, je vais effacer mon cache navigateur
