### ISSUE TITLE
Customisation du Logo structure

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#2582]
**Version**
2.12.3

**Description du bug**
Après migration de la 2.11.2 vers 2.12.3, le fichier du logo de la structure est bien migré vers `geonature/custom/images/logo_structure.png` mais c'est le logo par défaut qui s'affiche (image : MON LOGO). Si je retire le logo dans geonature/backend/static/images/logo_structure.png, il n'y a plus de logo sur l'interface. Si je place le logo custom dans `geonature/backend/static/images/logo_structure.png` le logo custom s'affiche. Mais, à la prochaine migration il faudra refaire la manip.

**Comportement attendue**
Utilisation du fichier placé dans le répertoire `custom/images`

**Comment reproduire**
placer son logo dans le répertoire `custom/images`.

**Comment by gildeluermoz** [comment]
`Après migration de la 2.11.2 vers 2.12.3, le fichier du logo de la structure est bien migré vers geonature/custom/images/logo_structure.png mais c'est le logo par défaut qui s'affiche (image : MON LOGO)`

Oui, j'ai bien vu cette doc, et comme précisé ci-dessus, le fichier du logo customisé est bien dans geonature/custom/images/logo_structure.png mais il n'est pas pris en compte.

Je me demande si le soucis ne vient pas de la conf apache. Pourtant j'utilise bien la conf fournie par défaut. Avec ceci : 
```
# CUSTOM STATIC FILE
RewriteEngine On
# Define STATIC_FILE environment variable
RewriteRule "^/geonature/api/static/(.*)$" - [env=STATIC_FILE:$1,chain]
# Test if custom static file exists (not tested for non static file thanks to previous chain flag)
RewriteCond "/home/bradmin/geonature/custom/%{ENV:STATIC_FILE}" -f
# If so, redirect to custom static file instead of default static file
RewriteRule "^/geonature/api/static/(.*)$" "/home/bradmin/geonature/custom/$1" [L]
<Directory "/home/bradmin/geonature/custom">
    Require all granted
    AllowOverride None
    Options -Indexes
</Directory>
```

**Comment by gildeluermoz** [comment]
Si ça fonctionne chez vous, il doit y avoir qq chose qui ne va pas de mon coté. Je rechecke tout ça.

**Comment by camillemonchicourt** [comment]
Oui j'ai bien ça aussi dans le fichier `/etc/apache2/conf-available/geonature.conf`, lui-même appelée/incluse dans `/etc/apache2/sites-available/geonature-le-ssl.conf` : 

```
# CUSTOM STATIC FILE
RewriteEngine On
# Define STATIC_FILE environment variable
RewriteRule "^/geonature/api/static/(.*)$" - [env=STATIC_FILE:$1,chain]
# Test if custom static file exists (not tested for non static file thanks to previous chain flag)
RewriteCond "/home/demo/GeoNature/custom/%{ENV:STATIC_FILE}" -f
# If so, redirect to custom static file instead of default static file
RewriteRule "^/geonature/api/static/(.*)$" "/home/demo/GeoNature/custom/$1" [L]
<Directory "/home/demo/GeoNature/custom">
    Require all granted
    AllowOverride None
    Options -Indexes
</Directory>
```

**Comment by gildeluermoz** [comment]
Ok ! Ce n'est pas moi qui ai fait la conf apache sur ce serveur et j'ai du la décortiquer un peu. Il manquait le `IncludeOptional /etc/apache2/conf-available/geonature.conf` dans le Vhost.
Merci Camille.

**Comment by camillemonchicourt** [comment]
Ah oui en effet si le vhost n'incluait pas la conf disponible, alors cette dernière n'est pas utilisée et donc ne sert à rien.
