### ISSUE TITLE
[Dev][PERMISSIONS][SYNTHESE][SENSITIVITY] Support de la sensibilité dans les routes d'exports de la synthèse

### ISSUE THREAD

**Issue by VincentCauchois** [PnX-SI/GeoNature#2584]
## CONTEXTE

Travail de refonte des permissions : https://github.com/PnX-SI/GeoNature/pull/2487#issuecomment-1517899647

## DESCRIPTION

Reprise des routes `export_...` du module synthèse, pour y intégrer le nouveau décorateur `@permissions_required`, à la place de `@permissions.check_cruved_scope`, et pour y gérer le filtrage des données sensibles (mode binaire : OUI ou NON je peux voir des données sensibles).

Les routes concernées sont les 4 suivantes - https://github.com/PnX-SI/GeoNature/blob/master/backend/geonature/core/gn_synthese/routes.py#L446-L720 : 
- `export_taxon_web`
- `export_observations_web`
- `export_metadata`
- `export_status`

## QUESTIONS

- Est-ce qu'il faut calculer le champ `nb_obs`, pour l'export des metadata, en fonction des observations permises à l'utilisateur ? Ou bien le compte total, absolu, des observations de ce jeu de donnée ?
--> Compte total, absolu, des observations du JDD, et qui peut inclure des observations non visibles par l'utilisateur.

- Avoir ou non l'option d'une liste des ID synthèse, dans les paramètres POST pour filtrer les vues ? Une telle liste est fournie lors d'un appel POST à la route, depuis le frontend (?) Correspond à la liste visible depuis le module frontend synthèse, et donc fournie par la route `get_observations_for_web` (?)

- Utilisation de méthodes GET seulement ? POST uniquement ? Ou les deux ?

### Tests fonctionnels et fixtures (pytest)
- [x] Données de test : observations dans `synthese` (observations sensibles et non sensibles, observations avec statuts de protection ou sans statut de protection), permissions avec différents scopes et niveaux de sensibilité.
    - [x] Avec fixtures (pytest) : `synthese_data_with_sensitive`
    - [x] /!\ Avoir des observations qui induisent réellement un statut "Donnée sensible" avec calcul de sensibilité, et pas seulement par écriture en dur de l'id_nomenclature_sensitivity correspondant à une donnée sensible.
- [ ] Rendre les tests complets et robustes
    - [ ] Bien vérifier que certaines données ne sont pas retournées, étant donné les filtres d'appartenance, de sensibilité, ...
- [x] PB : les 4 tests `test_export_` aboutissent quand ils sont lancés individuellement, ou seulement eux 4, mais échouent quand on lance tous les tests de la classe TestSynthese, ou bien tous les tests Pytest ... 
--> Problème lié à l'exécution de la requête de récupération d'un couple (cd_nom, id_area) sensible, ...

### Routes d'export API synthèse
- [x] Implémenter le filtre par permissions, incluant sensibilité, dans les routes
  - [x] `export_taxon_web`
  - [x] `export_observations_web`
  - [x] `export_metadata`
  - [x] `export_status`
--> /!\ Ne pas utiliser de `DB.engine.execute` dans les routes, au risque de ne pas retrouver les données introduites dans le contexte de la session courante. Utiliser `DB.session.execute` à la place

### Vérification des performances 

--> à faire ?

### Tests frontend (Cypress)

--> à faire ?

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.13.0
