### ISSUE TITLE
INSTALL_ALL - Versions PHP ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#259]
https://github.com/PnX-SI/GeoNature/blob/master/docs/install_all/install_all.sh#L25-L28

Ne plus imposer PHP5, qui n'est pas dispo dans Debian 8. 
Idem pour postgresql-server-dev-9.4 dont il ne faudrait pas imposer la version (passer sur postgresql-server-dev-all). 

A voir si UsersHub et GeoNature 1 fonctionnent en PHP7...

Ne plus modifier les sourceslist Debian 8 (voir https://github.com/PnX-SI/GeoNature/blob/master/docs/install_all/README.rst)

**Comment by gildeluermoz** [comment]
php 5.6 est le php de debian 8. Normalement c'est sur debian 9 qu'on doit passer en php 7.
Du coup je ne comprends pas bien.
A priori @amandine-sahl dit que usershub fonctionne avec php7. Par contre geonature 1.9 est basé sur une très vieille version de symfony (1.4). Il y a de forte chance qu'il soit incompatible php7.

**Comment by camillemonchicourt** [comment]
La dernière v1 (1.9.1) est compatible Debian 9.
