### ISSUE TITLE
[Map] Retenir le fond de carte sélectionné à travers les modules

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature#2619]
Bonjour,

Dans le cadre d'une prestation pour l'Agence Régionale de la Biodiversité en île de France, un problème est remonté dans l'enchaînement des saisies sur Occtax concernant le fond cartographique. En effet, ce dernier est remis par défaut à chaque saisie.

Plus généralement, le fond de carte sélectionné est toujours remis à zéro, quand l'utilisateur navigue dans les modules ou recharge sa page. 

Pour palier à cela, je pensais le stocker dans le `localStorage`. Qu'en pensez-vous ? Je fais une PR en attendant pour que vous ayez l'implémentation sous les yeux.

Merci d'avance pour vos retours !

**Comment by TheoLechemia** [comment]
Si l'idée est de garder l'emprise de la carte entre les sessions, oui localStorage. Si c'est juste entre les modules, on peut utiliser un service Angular

**Comment by camillemonchicourt** [comment]
Ce n'est pas l'emprise de la carte que l'on veut garder, mais le fond de carte utilisé.

**Comment by mvergez** [comment]
Effectivement, je suis d'accord avec toi @TheoLechemia. L'objectif est aussi de garder pendant les sessions, je ne l'ai pas précisé. Pour que quand on recharge la page, le fond de carte soit conservé

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.13.0.
