### ISSUE TITLE
[Installation Geonature 2.12.3] Installation réussie mais erreur 404 sur l'adresse de l'application

### ISSUE THREAD

**Issue by Vottana** [PnX-SI/GeoNature#2624]
Bonjour à tous, 
Novice dans le domaine des applications sur serveur (linux ou autre), je me suis quand même lancée dans l'installation de Geonature sur notre serveur (debian 11). J'y suis presque...ou pas du tout.
L'installation s'est bien déroulée (je pense), message "l'installation est terminée", mais j'ai une "erreur 404 Page not found" lorsque je vais  sur l'adresse de l'application.
Nous avons sur notre serveur une interface de gestion de serveur (Plesk), j'y accède via une url (https://ns307.evxonline.net:8443).
Et c'est cette url que j'ai saisie dans le fichier d'installation, _install_all.ini_, au lieu de l'adresse IP... Fatale erreur ?
Aussi bien avec http://mon_url/geonature ou http://mon_adresse_IP/geonature, je tombe sur une erreur 404.
Nous avons modifié le fichier _geonature_config.toml_, pour mettre l'adresse IP à la place de l'url sur les 3 sites, 
_URL_APPLICATION, API_ENDPOINT, API_TAXHUB,_ mais rien à faire, impossible d'accéder à l'appli.

Est-ce qu'il vaut mieux tout désinstaller et repartir de zéro (notre serveur est vide, tout nouveau tout beau), en mettant l'adresse IP, ou il y a des fichiers que je peux modifier après coup pour résoudre le problème ?
Par ailleurs, est-ce que le problème vient vraiment de là : l'url de Plesk au lieu de l'adresse IP dans le fichier d'installation ?

Merci d'avance pour votre aide,
Bonne journée,
Vottana

**Comment by camillemonchicourt** [comment]
Oui le fait que tu aies mis l'URL de gestion de serveur et non pas l'URL finale sur laquelle ton GeoNature serait installée va forcément poser soucis.
Le script `install_all.sh` se charge de tout configurer automatiquement à partir de cette URL définie dans le fichier de configuration `install_all.ini`.

Les différents paramètres de GeoNature, TaxHub et UsersHub, la configuration Apache, etc...

Donc si tu veux changer/corriger cette URL après coup, il faut bien la changer partout (dont dans la configuration de TaxHub et de UsersHub, la conf Apache, etc...), et rebuilder l'application. 
On en a discuté dans d'autres tickets de mémoire, mais je n'ai plus tout en tête.

Le plus simple selon moi est de relancer une installation : 
- Tu supprimes les dossiers `geonature`, `taxhub` et `usershub` de ton serveur dans le dossier où tu les as installé
- Tu modifies la paramètre `drop_geonaturedb` de `install_all.ini` pour le passer à `true` pour qu'il supprime bien ta BDD si tu relances une installation
- Tu corriges le paramètre `my_url`
- Tu relances une installation globale en relançant le script `install_all.sh`

**Comment by Vottana** [comment]
Merci Camille pour ton retour. 
J'ai bien supprimé les 3 dossiers, modifié `install_all.ini`, relancé `install_all.sh`. 
L'installation se termine mais j'ai toujours l'erreur 404.
Un collègue m'avait conseillé de supprimer les fichiers Geonature  d'Apache dans etc/apache/sites-available et conf-available, je ne l'avais pas fait avant de relancer l'installation.
Je vais tous supprimer et refaire une 3e tentative.

**Comment by camillemonchicourt** [comment]
OK donc le soucis est surement autre chose.

Il nous faudrait des logs de GeoNature (et Apache ?) pour pouvoir identifier le soucis.

Les logs de GeoNature sont dans `/var/log/geonature/geonature.log`.
Ceux de apache doivent être dans `/var/log/apache2/`.

Sans logs, impossible d'en dire plus sur le soucis.

**Comment by Vottana** [comment]
Salut salut,
voici les logs en pj. Les logs d'apache semblent vides...
[geonature_access.log](https://github.com/PnX-SI/GeoNature/files/12025158/geonature_access.log)
[geonature_error.log](https://github.com/PnX-SI/GeoNature/files/12025159/geonature_error.log)
[geonature-worker.log](https://github.com/PnX-SI/GeoNature/files/12025160/geonature-worker.log)
[geonature.log](https://github.com/PnX-SI/GeoNature/files/12025161/geonature.log)

**Comment by MoulinZ** [comment]
Je reprend la discussion ici @Vottana ça sera plus simple. 
Camille j'ai aidé regardé avec @Vottana pour sa configuration. 
J'ai bien l'impression que le problème vient d'Apache. J'ai testé de créer /var/www/test.html et de faire un fichier conf pour ce dernier, mais il dit que /var/www/test.html n'existe pas, donc il ne doit pas plus réussir à aller chercher geonature et autre

**Comment by camillemonchicourt** [comment]
OK donc on vous laisse le soucis de votre côté ?

On a fait de nombreuses installations globales de la 2.12 sans soucis.

Regardez aussi le fichier de log install_all.log pour voir si il y a un soucis avec Apache lors de l'installation.

Mais cela semble être un problème de votre contexte serveur.

**Comment by MoulinZ** [comment]
Bon en fait l'histoire du conf qui trouve pas le fichier c'est de ma faute, j'avais mis un fichier pour DocumentRoot. Plus d'erreur quand je met le dossier parent, avec un fichier index.html. 
Les logs d'apache existent, mais les droits empechent d'y accéder directement il faut faire sudo nano `/var/log/apache/error.log`
En voici un extrait depuis le dernier reboot d'apache : 

```
[Wed Jul 12 11:01:52.019794 2023] [mpm_event:notice] [pid 674790:tid 140651408727360] AH00492: caught SIGWINCH, shutting down gracefully
[Wed Jul 12 11:01:56.047065 2023] [ssl:warn] [pid 676057:tid 140185357565248] AH01909: default-51_159_197_116:443:0 server certificate does NOT include an ID which matches the server name
[Wed Jul 12 11:01:56.047453 2023] [:notice] [pid 676057:tid 140185357565248] ModSecurity for Apache/2.9.6 (http://www.modsecurity.org/) configured.
[Wed Jul 12 11:01:56.047470 2023] [:notice] [pid 676057:tid 140185357565248] ModSecurity: APR compiled version="1.7.0"; loaded version="1.7.0"
[Wed Jul 12 11:01:56.047481 2023] [:notice] [pid 676057:tid 140185357565248] ModSecurity: PCRE compiled version="8.39 "; loaded version="8.39 2016-06-14"
[Wed Jul 12 11:01:56.047498 2023] [:notice] [pid 676057:tid 140185357565248] ModSecurity: LUA compiled version="Lua 5.1"
[Wed Jul 12 11:01:56.047506 2023] [:notice] [pid 676057:tid 140185357565248] ModSecurity: YAJL compiled version="2.1.0"
[Wed Jul 12 11:01:56.047515 2023] [:notice] [pid 676057:tid 140185357565248] ModSecurity: LIBXML compiled version="2.9.10"
[Wed Jul 12 11:01:56.047523 2023] [:notice] [pid 676057:tid 140185357565248] ModSecurity: Status engine is currently disabled, enable it by set SecStatusEngine to On.
[Wed Jul 12 11:01:56.048977 2023] [suexec:notice] [pid 676057:tid 140185357565248] AH01232: suEXEC mechanism enabled (wrapper: /usr/lib/apache2/suexec)
[Wed Jul 12 11:01:56.431845 2023] [ssl:warn] [pid 676065:tid 140185357565248] AH01909: default-51_159_197_116:443:0 server certificate does NOT include an ID which matches the server name
[Wed Jul 12 11:01:56.467888 2023] [mpm_event:notice] [pid 676065:tid 140185357565248] AH00489: Apache/2.4.56 (Debian) OpenSSL/1.1.1n mod_fcgid/2.3.9 configured -- resuming normal operations
[Wed Jul 12 11:01:56.467985 2023] [core:notice] [pid 676065:tid 140185357565248] AH00094: Command line: '/usr/sbin/apache2'

```

**Comment by MoulinZ** [comment]
J'en suis maintenant à peu près certain, le problème vient du fait que plesk est installé, et que l'adresse ip de base redirige vers plesk. Et que du coup ça semble court-circuiter les fichiers de conf d'apache. Reste à voir comment régler le problème.

**Comment by camillemonchicourt** [comment]
Oui ça semble confirmer un soucis de votre contexte, Apache arrive à capter le server_name ou un truc du genre.
Donc pas lié à GeoNature il me semble.

**Comment by Vottana** [comment]
Je demande à l'hébergeur de supprimer Plesk. Et je retente une installation ?

**Comment by MoulinZ** [comment]
En fait le problème c'est que Plesk tourne avec Nginx (serveur web qui fait la même chose qu'Apache). Du coup il y a conflit entre les deux, et le serveur semble prioriser Nginx (surement une conf quelque part qui fait ça). Donc forcément tout ce qu'on lui demande avec apache ça marche pas. 
2 options : 
- demander à l'hébergeur de dégager plesk, et de remettre le serveur à 0 pour pas être embêté avec les conf obsolètes de plesk (en plus vous payez plesk pour rien)
- refaire la conf de geonature sur nginx. Ca doit pas être bien plus compliqué qu'apache, mais c'est pas la configuration par défaut de GeoNature, du coup ça peut compliquer les choses pour le futur peut être

Je partirai sur la 1ère option, ça me semble le plus simple, surtout quand on est pas très à l'aise avec l'administration système

**Comment by camillemonchicourt** [comment]
Oui on ne peut pas faire tourner Nginx et Apache en parallèle à ma connaissance.
C'est possible de faire tourner GeoNature avec Nginx mais il faut connaître comment ça fonctionne et le gérer dans le temps, si on fait des évolutions au niveau de la conf Apache de GeoNature.

Donc il faut maîtriser les configurations de serveur web.

**Comment by Vottana** [comment]
Bonjour à tous les 2,

Merci pour votre aide et vos messages. J'ai contacté l'hébergeur pour supprimer Plesk et je retente l'instal. Ma collègue de Franche-Comté à le même souci, avec Plesk et Nginx. 
Je trouve quand même ballot de proposer aux novices sur serveur une plateforme de gestion pour les aider mais qui entre en conflit avec un serveur web ultra utilisé par d'autres appli...
Enfin, c'est peut-être une réflexion de débutante :)
Je ferme l'issue.
Bel été à tous.
