### ISSUE TITLE
Date picker : problème de local

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#2627]
Sur un ordi dont la locale semble en français, il y a des textes bizarre sur le datepicker : 
![Capture d’écran du 2023-07-10 21-38-34](https://github.com/PnX-SI/GeoNature/assets/15265745/445b2f7c-fbb4-4dbd-bf29-eea031f16379)
("Peut" à la place "mai" et "dix" à la place de 10)

**Comment by DonovanMaillard** [comment]
problème de traduction de may ... qui peut vouloir dire "peut". Qu'est-ce qui fait la traduction dans le datepicker ?

**Comment by DonovanMaillard** [comment]
de mémoire on m'a remonté déjà des soucis de traductions comme ça, qui venaient du navigateur. je n'observais pas le comportement sur tous les terminaux

**Comment by lpofredc** [comment]
est-ce sous Google Chrome? La traduction automatique du navigateur provoque ce genre de pb: Station devient Gare, et les mois abbrégés ne sont plus des mois.


![Capture d’écran du 2023-07-24 12-13-24](https://github.com/PnX-SI/GeoNature/assets/22891423/702cb652-6b9c-417e-ae8b-3837ef4a6b3b)

![Capture d’écran du 2023-07-24 12-13-51](https://github.com/PnX-SI/GeoNature/assets/22891423/f28d7c58-1c31-416b-9d28-70889b4bb0e6)

**Comment by TheoLechemia** [comment]
Ah mais oui, c'est de la traduction automatique de navigateur ! Bien vu
