### ISSUE TITLE
[custom/css/frontend.css] Paramètre non appliqué

### ISSUE THREAD

**Issue by pbarille** [PnX-SI/GeoNature#2632]
Bonjour,

Je fais des tests de modification graphique de l'interface de Geonature 2.12 via le dossier custom/css/frontend.css en tentant par exemple de passer cette propriété :  
`.no-link-style {
   color : #084a8d
}`  
  
Mais lors de l'ouverture d'une fiche dans geonature, la console de mon navigateur m'indique qu'elle n'a pas été appliquée et que le style .no-link-style[_ngcontent-uix-c290] est appliqué.

Y-a-t-il une possibilité de surcoucher ce type de style via les customs ?

Merci !
Bonne journée

**Comment by TheoLechemia** [comment]
Bonjour,
Depuis la 2.12 les fichiers de surcouche du frontend sont dans le répertoire : `backend/static/css/frontend.css`
C'est un petit loupé dans la doc, on va ajouter ça

**Comment by TheoLechemia** [comment]
Petite erreur, c'est ici : 
`/geonature/custom/css/frontend.css`
et la doc : `https://docs.geonature.fr/admin-manual.html#customisation

**Comment by pbarille** [comment]
Bonjour,

Merci pour ce retour.
C'est bien ce chemin ~/geonature/custom/css/frontend.css que j'ai utilisé mais j'ai l'impression que les paramètres de couleurs de boutons de l'application (tout ce qui est en violet) n'accepte pas les surcouches css.

Peut-être que je m'y prend mal ?

Merci !

**Comment by pbarille** [comment]
Ca fonctionne !
Merci beaucoup !
J'ai l'impression que c'est le !important qui change tout :)
