### ISSUE TITLE
[Configuration domaine GeoNature 2.10.3]

### ISSUE THREAD

**Issue by LudmillaT** [PnX-SI/GeoNature#2635]
Bonjour, 

Nous venons d’installer la version 2.12.3 de GeoNature (sous Debian 11), lors de l’installation j’ai utilisé un nom de domaine en http (http://odin-beta.anbdd.fr/geonature). L’installation c’est à priori bien passer et le site était disponible à l’adresse indiquer dans le fichier `install_all.ini`, cependant les sites apparaissent en non sécuriser, j’ai donc voulu régler ce problème en passant en https (https://odin-beta.anbdd.fr/geonature). 
Pour cela j’ai suivi la docs des réserves naturelles (https://si-en-reseau.reserves-naturelles.org/documentation-geonature/domaine.html) docs qu’on avais déjà utiliser pour une version test de notre plateforme et qui avais marché. Cependant, cette fois, après avoir taper la commande `sudo certbot` et mis à jour les différents fichier config de geonature et usershub quand je recherche le site j’ai une erreur **‘404 The requested URL was not found on this server.**’ 
Je pense que l’erreur viens de notre configuration apache mais en la comparant avec notre version test qui marche je ne trouve rien qui me saute aux yeux, mais n’étant pas spécialisé dans le domaine il est possible que des choses m’échappent. Si certains d’entre vous ont des pistes qu’en a ce qui pourrais causer ce problème je suis preneuse. 

Si jamais ça peux être utile, voici les logs :

- geonature.log
```
[2023-07-18 16:15:35 +0200] [53763] [INFO] Worker exiting (pid: 53763)
[2023-07-18 16:15:35 +0200] [53764] [INFO] Worker exiting (pid: 53764)
[2023-07-18 16:15:36 +0200] [53503] [INFO] Shutting down: Master
[2023-07-18 16:15:36 +0200] [54687] [INFO] Starting gunicorn 20.1.0
[2023-07-18 16:15:36 +0200] [54687] [INFO] Listening at: http://127.0.0.1:8000 (54687)
[2023-07-18 16:15:36 +0200] [54687] [INFO] Using worker: sync
[2023-07-18 16:15:36 +0200] [54689] [INFO] Booting worker with pid: 54689
[2023-07-18 16:15:36 +0200] [54690] [INFO] Booting worker with pid: 54690
[2023-07-18 16:15:36 +0200] [54691] [INFO] Booting worker with pid: 54691
[2023-07-18 16:15:36 +0200] [54692] [INFO] Booting worker with pid: 54692
```

- geonature-worker.log
```
[2023-07-18 15:46:00,385: INFO/MainProcess] Connected to redis://localhost:6379/0
[2023-07-18 15:46:00,388: INFO/MainProcess] mingle: searching for neighbors
[2023-07-18 15:46:01,393: INFO/MainProcess] mingle: all alone
[2023-07-18 15:46:01,398: INFO/MainProcess] celery@anbdd3 ready.
[2023-07-18 16:14:29,057: INFO/MainProcess] beat: Shutting down...
[2023-07-18 16:14:32,174: INFO/MainProcess] Connected to redis://localhost:6379/0
[2023-07-18 16:14:32,175: INFO/Beat] beat: Starting...
[2023-07-18 16:14:32,177: INFO/MainProcess] mingle: searching for neighbors
[2023-07-18 16:14:33,183: INFO/MainProcess] mingle: all alone
[2023-07-18 16:14:33,190: INFO/MainProcess] celery@anbdd3 ready.

```
- geonature_error.log
```
[Tue Jul 18 04:45:50.984594 2023] [core:error] [pid 38503:tid 140504066938624] [client 213.109.202.66:54892] AH10244: invalid URI path (/cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh)
[Tue Jul 18 08:48:19.241369 2023] [core:error] [pid 38502:tid 140502942873344] [client 193.32.162.190:56302] AH10244: invalid URI path (/../../mnt/mtd/Config/Account1)
[Tue Jul 18 10:17:06.687473 2023] [core:error] [pid 41522:tid 140504477984512] [client 193.32.162.190:45226] AH10244: invalid URI path (/../../mnt/mtd/Config/Account2)
```

Merci d’avance pour vos retours.

**Comment by camillemonchicourt** [comment]
Tu as changé le server_name dans la configuration Apache ?

**Comment by LudmillaT** [comment]
Tu parle du fichier : `apache2/sites-available/geonature.conf` ?  Si c'est le cas, oui on a changé le server_name, le fichier est renseigné comme ça :
```
<VirtualHost *:80>
    ServerName odin-beta.anbdd.fr

    IncludeOptional /etc/apache2/conf-available/geonature.conf
    IncludeOptional /etc/apache2/conf-available/taxhub.conf
    IncludeOptional /etc/apache2/conf-available/usershub.conf

    ErrorLog "/var/log/apache2/geonature_error.log"
    CustomLog "/var/log/apache2/geonature_access.log" combined
RewriteEngine on
RewriteCond %{SERVER_NAME} =odin-beta.anbdd.fr
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```

**Comment by TheoLechemia** [comment]
Il faut le faire sur le fichier de conf généré par certbot, qui doit contenir une balise `VirtualHost *:443`
il faut également changer l'URL de l'application dans le fichier de conf `config/geonature_config.toml` et `frontend/src/assets/config.json`

**Comment by LudmillaT** [comment]
Pour les fichiers de configuration de geonature j'ai vérifié, je les avais bien modifiés
Le fichier de conf géréré par le certbot c'est le fichier `apache2/sites-available/default-ssl.conf` ? Si c'est le cas il commence comme ça :
```
<IfModule mod_ssl.c>
	<VirtualHost _default_:443>
		ServerAdmin obn@anbdd.fr
		ServerName odin-beta.anbdd.fr
```

**Comment by TheoLechemia** [comment]
Je ne suis pas sur que certbot modifie le default-ssl.conf.
Habituelement, il crée un fichier du genre `geonature-le-ssl.conf`

**Comment by LudmillaT** [comment]
Après quelques recherches mon problème venais bien du fais qu'il n'y avais pas de fichier `geonature-le-ssl.conf` de crée par certbot donc je l'ai crée manuellement, je l'ai mis dans `apache2/sites-available/` et dans `apache2/sites-enabled/` et j'ai relancer apache ce qui à eu l'air de régler mon problème car j'arrive a accéder à mon site en https.

Merci pour votre aide ! je clos le sujet.

**Comment by LudmillaT** [comment]
> OK c'est pas normal d'avoir du le créer à la main. 🤔 Et je trouve bizarre aussi que le fichier default-ssl.conf ait été modifié et indique le server_name de ton serveur...

Pour le faite de devoir crée le fichier à la main, a priori ce serait parce que les certificat pour le serveur été déjà à jours.
Pour le fichier SSL c'est possible qu'il ai été modifié par quelqu'un d'autre dans ma structure, j'ai pas plus d'info à ce sujet pour l'instant.
