### ISSUE TITLE
Impossible d'utiliser une liste de taxons avec code_liste ≠ id_liste

### ISSUE THREAD

**Issue by SamyM71** [PnX-SI/GeoNature#2643]
### Version
2.12.3

### Description du bug

Une nouvelle liste de taxons est créée dans TaxHub, avec `id_liste` = 102 et `code_liste` = 'MA_LIST'.
Cette liste est peuplée avec les taxons voulus puis est associée dans Geonature à un jeu de données.

Dans OccTax, lors de la saisie d'une nouvelle observation avec ce jeu de données, la saisie de taxon est impossible et renvoie le message suivant dans le navigateur web :

> Aucun taxon trouvé pour cette recherche Veuillez renseigner un taxon

> HttpErrorResponse
> Http failure response for https://domaine.tld/taxhub/api/taxref/allnamebylist/102?search_name=chev&limit=20: 400 BAD REQUEST 

### Comportement attendu 

La liaison à l'API de TaxHub devrait se faire avec **`id_liste`** plutôt que `code_liste`.
Contournement actuel : modifier `code_liste` et lui attibuer la même valeur que `id_liste`.

### Comment reproduire

Créer une liste de taxons avec un `code_liste` différent de `id_liste`.

**Comment by camillemonchicourt** [comment]
Oui ticket en doublon, déjà identifié dans https://github.com/PnX-SI/GeoNature/issues/1549

**Comment by SamyM71** [comment]
Bonjour,


Désolé, je n'avais pas regardé trop en arrière.


Samy

**Comment by camillemonchicourt** [comment]
Retour en arrière dans la version 1.13.1 de TaxHub (nécessitant GeoNature 2.14 ou plus) en rebasant la route sur des `id_liste` - https://github.com/PnX-SI/TaxHub/issues/346
