### ISSUE TITLE
Occtax, formulaire de saisie : recherche de taxons très lente

### ISSUE THREAD

**Issue by Vottana** [PnX-SI/GeoNature#2646]
[Geonature 2.12.3, Debian 11, 32 Go de ram, 8 CPU, 500 Go de disque]

Bonjour à toutes et tous,

je me permets de faire suite à cette issue : [https://github.com/PnX-SI/GeoNature/issues/2551](url)
J'ai exactement le même problème. Notre instance est enfin installée, le serveur est tout neuf, mais la recherche de taxons est extrêmement lente. Pour les lettres "pie" cela mets entre 15 et 20 secondes pour que la liste de choix s'affiche.
En testant avec une instance Geonature qui a environs 67000 taxons, la liste s'affiche quasi instantanément. Nous en avons environs 14000.

J'ai essayé la commande `top`, j'avoue ne pas du tout savoir comment lire les informations qui en ressortent, ou voir les infos qui pourraient m'aider dans mon problème (je vais potasser les tutos dans l'internet 🤓)
J'ai bien créé ma liste de taxons, avec le code `id_taxon_list = 100`, dans `bib_noms` et `cor_nom_listes`.
J'ai créé un fichier de configuration `occtax_config.toml` avec le paramètre `id_taxon_list = 100`, mais je me demande :
- où doit être placé ce fichier ? Dans le doute, je l'ai mis à 2 endroits : `geonature/config` et `geonature/contrib/occtax`. Logiquement je le mettrais dans occtax...mais... qui sait !
- est-ce qu'il faut l'activer comme pour les fichier .conf ?
J'ai essayé le `update-module-configuration` [https://docs.geonature.fr/admin-manual.html#configuration-d-un-gn-module](url) mais j'ai le message d'erreur `commande introuvable` (j'ai essayé aussi en mettant : `update-occtax-configuration`).

J'ai essayé la commande `geonature db status taxonomie` mais cela me renvoie `commande introuvable`. Bref, je tatonne sans trop savoir où je vais.
Et donc, d'après vos échanges, cela n'est pas en lien avec les JDD, mais ça a apparemment résolu le problème ?

Merci d'avance pour vos retours,
Vottana

**Comment by Vottana** [comment]
Bonjour Maxime, 
Je vous mets une copie d'écran. 
![image](https://github.com/PnX-SI/GeoNature/assets/15034095/e8991e0d-ffdf-4961-84f2-78d3b5d2e00c)

Mais j'ai fais des tests sur d'autres instances Geonature et ce n'est pas aussi long. Je dois avoir mal configuré quelques choses mais quoi....

**Comment by camillemonchicourt** [comment]
Étonnant car même si on ne créé pas de liste de taxons, ça recherche par défaut dans tout Taxref et ça fonctionne bien, c'est assez réactif.
La création d'une liste de taxons saisissable est optionnelle et permet surtout d'éviter des erreurs en ne proposant que des taxons présents sur le territoire.

Pour la conf d'Occtax, il y a un exemple ici - https://github.com/PnX-SI/GeoNature/blob/master/contrib/occtax/occtax_config.toml.example

Et voir la doc pour que ce fichier de conf soit pris en compte : https://docs.geonature.fr/installation.html#module-config

A sa première création, il faut lancer une commande.
Mais ensuite, à chaque modification du fichier, le rechargement de la conf est automatique (depuis la version 2.12.0).

**Comment by camillemonchicourt** [comment]
Dans la capture écran, je crois comprendre que ça filtre bien sur la liste "100".
Pour en être certain tu peux essayer de chercher un taxon qui n'est pas dans ta liste de taxons.

> Par rapport à la liste taxonomique, elle est forcément prise en compte puisque des taxons sont proposés. Lors de l'installation, je n'avais aucun taxon. Lors de la saisie, aucune liste de choix ne s'affichait. Là, j'en ai bien une.

Ça c'est pas normal, car depuis plusieurs versions, si on ne spécifie pas de liste de taxons dans Occtax, alors cela recherche dans tout Taxref.

Mais peut-être que là ça n'arrivait pas à aboutir dans ton contexte.
De notre côté, quand on installe un GeoNature tout neuf, la recherche dans Occtax basée sur tout Taxref fonctionne et ne met pas 10 secondes à répondre.

**Comment by Vottana** [comment]
J'ai copié le fichier occtax_config.toml.example en modifiant le paramètre 
```
# id of the taxon list -- taxonomie.bib_listes. Use for the taxonomy search in the occtax forml
# default = None: search on full taxref
id_taxon_list = 100
```
J'ai mis ce fichier occtax_config.toml dans le répertoire geonature/config.
J'ai lancé les commandes : 
```
sudo systemctl daemon-reload
sudo systemctl restart geonature
```
J'ai relancé la page web de geonat, en supprimant les caches, pour être sûre... Résultat, 19 secondes pour avoir une liste avec les 3 lettre "pie"
En testant avec un taxon qui n'est pas dans ma liste, je n'ai aucune proposition. Occtax ne tape pas dans tout le Taxref.
Je pensais donc au départ que créer une liste de taxon était obligatoire pour pouvoir saisir...

**Comment by SamyM71** [comment]
Bonjour,


Ça ne répondra pas à tes problèmes de performances, mais peut-être voir 
du côté de la vue matérialisée taxonomie.vm_taxref_list_forautocomplete 
et la rafraîchir ?


Samy

**Comment by gildeluermoz** [comment]
Il y a semble t-il un soucis qq part car 20 secondes ça semble très long mais dans la version 1.11.2 de taxhub, il y a une évolution sur ce point : 

> Optimisation de la route allnamebylist lors de la recherche par nom "search_name"

Des index sont créés sur la vue matérialisée `taxonomie.vm_taxref_list_forautocomplete` avec cette révision Alembic : 
apptax/migrations/versions/27fd7e2b4b79_add_vm_taxref_list_forautocomplete_index.py
Attention, si tu crées ces index manuellement dans la base, tu prends le risque qu'Alembic lève une erreur en tentant de recréer des index existants lors de la prochaine mise à jour.
Si tu ne maitrise pas Alembic, je te déconseille de bidouiller la base pour corriger ce soucis qui a peut-être une autre origine.

Attention, la release 1.11.2 de taxHub ainsi que les releases suivantes, ne sont pas compatibles avec GeoNature 2.12.3. Il faut donc attendre GN 2.13 pour profiter de cette évolution. J'ai pu tester, les performaces de recherche de taxons sont bien meilleures avec les index.

**Comment by Vottana** [comment]
Bonjour à tous, 

Je reviens sur le problème de lenteur qui n'est malheureusement toujours pas résolu.
Avec l'aide de Colas Geier du CEN Isère nous avons regardé l'installation et la base, fait des tests sur l'application. Apparemment tout semble bien installé, mon geonature-worker était désactivé. Après activation, cela a réduit de moitié les temps de réponse. Nous passons de 15-20 s à 6-10 s. Ce qui reste quand même très long pour faire de la saisie.

Il y a, dans notre instance, un problème avec le paramètre `search_name` : 
la requête `https://taxhub.cen-bourgogne.fr/api/taxref/allnamebylist/100?search_name=moi&limit=20` met 6.68 s à répondre avec 6.51 s d'attente de réponse du serveur.
En enlevant `search_name`, donc avec juste `https://taxhub.cen-bourgogne.fr/api/taxref/allnamebylist/100?=moi&limit=20` nous avons une réponse en 1.68 s avec 1.45 s d'attente.

Nous avons regardé la base, pas de problèmes identifiés, les index sont présents, les liens entre les clés également.
Nous fait un vacuum, un rafraîchissement de la VM.

J'ai contacté l'hébergeur pour savoir si un paramètre quelconque pouvait ralentir la base.
Pour la saisie des habitats, elle est très rapide : 421 ms dont 236 ms (avec les lettres "for",
`https://geonature.cen-bourgogne.fr/api/habref/habitats/autocomplete?search_name=for`). 
Donc est-ce vraiment un problème de lenteur du serveur ? Il est lent uniquement sur la recherche de taxons.

Si vous avez des pistes, je suis preneuse.

Merci d'avance pour vos retours,
Bonne journée,
Vottana

**Comment by TheoLechemia** [comment]
Bonjour,

Combien met de temps un "`select * from taxonomie.vm_taxref_list_forautocomplete limit 20;`" 
Combien y-a-t-il d'élément dans la liste 100 par curiosité ? (`select count(*) from taxonomie.cor_nom_liste cnl where id_liste = 100;)` et dans bib_nom : `select count(*) from taxonomie.bib_noms bn; `


Et enfin combien de temps prend cette requete : 

```
select * 
from taxonomie.vm_taxref_list_forautocomplete a
join taxonomie.bib_noms bn on bn.cd_nom = a.cd_nom 
join taxonomie.cor_nom_liste cnl on cnl.id_nom = bn.id_nom 
where cnl.id_liste = 100
limit 20;
```

merci

**Comment by Vottana** [comment]
Bonjour Theo,

Via Pgadmin4 :
> Combien met de temps un "`select * from taxonomie.vm_taxref_list_forautocomplete limit 20;`"

564 ms

> Combien y-a-t-il d'élément dans la liste 100 par curiosité ? (`select count(*) from taxonomie.cor_nom_liste cnl where id_liste = 100;)` et dans bib_nom : `select count(*) from taxonomie.bib_noms bn; `

Dans cor_nom_liste = 14 181 lignes
Dans dans bib_nom = 14 182 lignes (j'ai supprimé un taxon via Taxhub hier pour tester si une modification et un enregistrement de la liste via Taxub résoudrait le problème de lenteur)

> Et enfin combien de temps prend cette requete :
> ```
> select * 
> from taxonomie.vm_taxref_list_forautocomplete a
> join taxonomie.bib_noms bn on bn.cd_nom = a.cd_nom 
> join taxonomie.cor_nom_liste cnl on cnl.id_nom = bn.id_nom 
> where cnl.id_liste = 100
> limit 20;
> ```
176 ms

**Comment by TheoLechemia** [comment]
Ok. la dernière requête est exactement celle qui est lancée par la route... du coup le problème ne vient pas de la base mais de Flask...
tu peux essayer un restart de geonature ... : `sudo systemctl restart geonature`

**Comment by Vottana** [comment]
Pas de changement, nous avons déjà fait plusieurs restart de geonature auparavant.
Je dois essayer la customisation de Postgresql, voir si ça améliore un peu les délais.

**Comment by TheoLechemia** [comment]
Non le problème ne vient pas de postgres, mais de l'appli Python ..
Je sèche un peu. Il faudrait faire des tests plus avancé en ayant accès à la machine

**Comment by TheoLechemia** [comment]
Ceci dit, la route sans "search_name" est plutôt "rapide" : `https://taxhub.cen-bourgogne.fr/api/taxref/allnamebylist/100`
la lenteur à l'air de venir du filtre .
Combien de temps met cette requête: 

```
select a.* , similarity(a.search_name, '%capra%')
from taxonomie.vm_taxref_list_forautocomplete a
join taxonomie.bib_noms bn on bn.cd_nom = a.cd_nom 
join taxonomie.cor_nom_liste cnl on cnl.id_nom = bn.id_nom 
where cnl.id_liste = 500 and a.search_name ilike unaccent('%capra%') 
limit 20;
```

`capra` à éventuellement remplacer par un nom de taxon que tu as dans tes listes

**Comment by Vottana** [comment]
Avec id_liste = 100 non ? (je n'ai pas d'autre liste que 100 pour l'instant)
Avec id_liste = 100 et %moi%, cela met 394 ms pour avoir la résultat.
Si certains veulent l'accès à la machine, je file les codes d'accès volontiers

**Comment by TheoLechemia** [comment]
Oui `id_liste = 100` pardon.
Contact moi ou Camille par mail on va essayer de regarder

**Comment by Vottana** [comment]
Bonjour à tous,
j'avais fermé l'issue sans donner la conclusion :
la source de la lenteur n'a pas pu être identifiée.
Théo a "désactivé la fonctionnalité qui rendait la recherche insensible à la casse pour avoir des temps de réponse acceptable", Nous passons de 20 s. à (un peu moins) de 2 s. 
Le type de serveur pourrait jouer aussi, nous avons un HDD et pas un SSD. Je vais voir également auprès de l'hébergeur si une migration est possible.
En attendant la prochaine version qui j'espère pourra résoudre le problème, merci à tous pour vos interventions et votre aide !
Vottana
