### ISSUE TITLE
[SYNTHESE] Obs avec médias

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#2652]
Il serait utile de pouvoir identifier rapidement, via une icone ou un filtre, les observations qui disposent de medias attachés.
Est-ce faisable, envisagé ?

**Comment by camillemonchicourt** [comment]
Oui c'est déjà existant.
Dans les filtres avancés : "Possède des médias"

**Comment by gildeluermoz** [comment]
Ok nickel merci.
