### ISSUE TITLE
Changement nombre d'observations par defaut sur carte

### ISSUE THREAD

**Issue by naidinp** [PnX-SI/GeoNature#2655]
Bonjour,
je cherche comment changer le nombre d'observations (100) par défaut sur la carte de la page d'Accueil mais j'y arrive pas.
Pouvez-vous m'indiquer si cella est possible ?

Merci d'avance.

**Comment by camillemonchicourt** [comment]
Il y a un paramètre `NB_LAST_OBS` pour définir le nombre d'observations par défaut quand on arrive dans le module SYNTHESE : https://github.com/PnX-SI/GeoNature/blob/master/config/default_config.toml.example#L303-L305

Mais à priori pour la petite carte affichée sur la page d'accueil, on ne peut que l'afficher ou la masquer, on ne peut pas paramétrer le nombre d'observations qu'elle contient : https://github.com/PnX-SI/GeoNature/blob/master/config/default_config.toml.example#L156-L157

Ça pourrait être une petite évolution à développer.

**Comment by naidinp** [comment]
Bonjour,
Merci pour l'info. Je vais voir si on peut faire cette évolution en interne et vous la proposer pour intégration.
Bonne journée.
