### ISSUE TITLE
[mes lieux] questions sur le fonctionnement

### ISSUE THREAD

**Issue by lpojgc** [PnX-SI/GeoNature#2656]
Bonjour,
J'explore la fonctionnalité mes lieux d'occtax mais ne comprends pas tout.
J'ai l'impression que cette fonctionnalité permet "simplement" d'associer une géométrie aux données mais que l'on perd l'information concernant le nom du lieu.
En effet, après avoir sélectionné le nom du lieu, il apparait sur la fenêtre du carte mais dans la partie de description du relevé le champ "nom lieu" est vide, je peux d'ailleurs y renseigner l'information que je veux et que je retrouve en synthèse (sans lien avec le nom de lieux), ce qui rejoint en partie [le ticket](https://github.com/PnX-SI/GeoNature/issues/1319) de Donovan.
Mes questions :
- me confirmez vous que le comportement que je décris est normal ?
- est-il possible lorsque l'on utilise la fonctionnalité "mes lieux" de garder une trace du nom de la localité (idéalement sans la ressaisir) ?
Merci d'avance
Julien

**Comment by lpojgc** [comment]
oups, il ne s'agit pas d'un bug mais d'une question, mais je n'arrive pas à changer le label...

**Comment by camillemonchicourt** [comment]
Oui c'est ce qui est indiqué dans le ticket de Donovan.
La fonctionnalité "Mes lieux" et le champs texte "lieu" sont indépendants.

La fonctionnalité "Mes lieux" est décrite ici - https://github.com/PnX-SI/GeoNature/issues/246.
Elle sert uniquement à mémoriser des lieux personnels non partagés avec les autres utilisateurs pour localiser rapidement et facilement des observations que l'on fait souvent (mon jardin, un lac...).

Donc c'est normal que cela ne renseigne pas le champs "lieu" quand on localise une observation à partir d'un de ses lieux personnels.

**Comment by lpojgc** [comment]
OK, merci pour le lien vers le ticket, je ne l'avais pas trouvé...
