### ISSUE TITLE
[Synthese] Filtre module de provenance

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature#2670]
Bonjour,

Dans le cadre d'une prestation pour l'Agence Régionale de la Biodiversité en île de France, un nouveau filtre a été ajouté dans la synthèse pour filtrer selon la source (https://github.com/PnX-SI/GeoNature/issues/2513). Après discussions avec eux ce filtre pourrait être amélioré en regroupant les imports par exemple. En effet, si l'instance dispose de beaucoup d'imports, le filtre d'`id_source` ne permet pas de filtrer suivant **tous** les imports mais seulement un seul import.

### Proposition

Ajouter un nouveau filtre "Module de provenance" se basant sur la colonne `id_module` de la table `gn_synthese.t_sources` cela permettrait de filtrer sur tous les imports mais aussi sur tout le module monitorings par exemple.

Qu'en pensez-vous ?

Merci d'avance pour vos retours !

**Comment by andriacap** [comment]
Bonjour,

Pour rebondir sur ce sujet, des devs ont été réalisés et sont sur la PR #2701

**Comment by camillemonchicourt** [comment]
Fait dans la 2.13.2
