### ISSUE TITLE
V2 - MCD METADATA

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#268]
Finaliser les notions de jeux de données et de contexte d'acquisition/programmes

**Comment by camillemonchicourt** [comment]
Bien avancé, faire un point dans ce ticket.

**Comment by camillemonchicourt** [comment]
Encore pas mal d'ajustements/nettoyage faits la semaine dernière.

**Comment by camillemonchicourt** [comment]
Le schéma ``meta`` a été implémenté sur la base du standard Métadonnées du SINP : http://standards-sinp.mnhn.fr/metadonnees-1-3-9/

Une interface d'administration des Cadres acquisition et Jeux de données a été mise en place.

**Comment by camillemonchicourt** [comment]
A compléter et basculer sur le standard 1.3.10
