### ISSUE TITLE
2.13.0 - Déconnexion non effective

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#2682]
Lorsque l'on se déconnecte en 2.13.0, on est bien renvoyé vers la page de login, mais on a toujours accès à l'API de GeoNature ainsi qu'aux différentes pages de l'application.

Reproduit seulement sur un serveur, en production, pas en local en mode dev.

**Comment by TheoLechemia** [comment]
Corrigé par https://github.com/PnX-SI/UsersHub-authentification-module/commits/develop et https://github.com/PnX-SI/GeoNature/commit/c07978ca18a6d91ad036a31852b84936f3fa653e

**Comment by camillemonchicourt** [comment]
Il y a toujours un soucis dans la 2.13.1.

**Comment by camillemonchicourt** [comment]
Corrigé dans la prochaine version avec la correction sur UsersHub-authentification-module (https://github.com/PnX-SI/GeoNature/pull/2711)

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.13.2
