### ISSUE TITLE
Quelle est la version minimale pour installer GeoNature ?

### ISSUE THREAD

**Issue by Guts** [PnX-SI/GeoNature#2694]
Bonjour,

Je cherche à installer GeoNature et à entrer dans le code source. Dans la [doc](https://github.com/PnX-SI/GeoNature/blob/master/docs/installation.rst?plain=1#L7), Python 3 est mentionné mais sans précision sur la mineure minimale. Dans le setup.py on trouve mention de la 3.6 mais c'est un tag donc juste indicatif et cette version est dépréciée depuis 2018 donc j'imagine que c'est pas ça non plus.

Et la 3.7 est [EOL](https://endoflife.date/python) depuis juin dernier.

Je peux proposer une PR pour ajouter cette information ensuite.

**Comment by camillemonchicourt** [comment]
GeoNature est compatible avec Debian 10, 11 et 12 actuellement. Le support de Debian 10 sera prochainement arrêté.

Donc la compatibilité actuelle est Python 3.7 à 3.11 (de mémoire).
Dans la 2.14, avec la suppression du support de Debian 10, on passera à Python 3.9 minimum.

**Comment by Guts** [comment]
Si je comprends bien, vous considérez seulement la version par défaut de Python installée sur la distribution Debian, c'est cela ?

Après tout, je peux installer quasiment la version que je veux sur une Debian 11 par exemple.

Cela signifie t'il que GeoNature n'est compatible qu'avec Debian ? ou est-ce que ça dépend de la disponibilité des dépendances dans les entrepôts officiels (ou pas ?) des paquets correspondant ?

**Comment by camillemonchicourt** [comment]
On maintient l'installation et le fonctionnement sur Debian, mais il est possible de le faire fonctionner sur d'autres systèmes.
Et depuis peu, des images Docker sont disponibles pour les différents outils, permettant de les déployer sur différents systèmes.
