### ISSUE TITLE
Occtax-mobile pouvoir spécifier une url absolue pour l'apk

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#2708]
**Version**
2.13 

**Description du bug**
Si l'on défini une url absolue pour la config mobile en base, les settings renvoyés sont un dictionnaire vide

**Comportement attendu**
Pouvoir définir soit une url aboslue soit une url relative

**Comment reproduire**
dans geonature admin mettre `Chemin relatif de l'APK`  à null et  donner une valeur à `URL externe de l'APK`

**Piste**

Dans l'api le chemin du fichier de config est défini par rapport au fichier apk relatif (il doit se trouver dans le meme répertoire).
Il faudrait pouvoir mettre ce chemin en dur (<media>/mobiles/occtax/settings.json) et le rendre indépendant de l'apk

https://github.com/PnX-SI/GeoNature/blob/a978d6aa6e2d85b51aa644f0e2aee74e67b1cb6d/backend/geonature/core/gn_commons/routes.py#L205-L222

**Comment by camillemonchicourt** [comment]
C'était géré initialement. 
A voir pourquoi et quand ça a sauté.

**Comment by camillemonchicourt** [comment]
OK je comprends, si l'APK est ailleurs, donc sur un chemin absolu, il ne trouve plus le fichier `settings.json`.

Testé sur la démo, l'API renvoie alors : 

```json
{"app_code": "OCCTAX", "id_mobile_app": 3, "package": "fr.geonature.occtax2", "settings": {}, "url_apk": "https://github.com/PnX-SI/gn_mobile_occtax/releases/download/2.6.1/occtax-2.6.1-generic-release.apk", "url_settings": null, "version_code": "3187"}
```

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.13.2
