### ISSUE TITLE
Mettre un champs observateur en texte libre

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#271]
- [x] mettre en place un paramètre pour choisir quel type de champs on veut
- [x] rajouter le champs ``observateur_libre `` en BDD
- [x] adapter le POST coté front
- [x] adapter le POST coté API

**Comment by TheoLechemia** [comment]
J'ai rajouté un fichier de configuration pour le module contact:
dans ce fichier il y a un paramètre:`` observersAsText`` qui est un booléén. Si celui-ci est à ``true`` on affiche un input simple en texte libre, sinon on affiche le composant ``observers`` qui renvoie des ID. 
Le front est OK pour poster le relevé avec ce nouveau champ.
@amandine-sahl  est-ce que tu peux te charger des modifications à faire côté back ?

**Comment by TheoLechemia** [comment]
Pour les exports, cela pose la question de l'organisme, qui est un champ obligatoire dans le standard d'occurrence.
Avec un champ en texte libre on perd l'organisme de l'observateur.

**Comment by camillemonchicourt** [comment]
Pour l'organisme et les droits on se basera sur le JDD de la donnee et non pas sur l'observateur si je me souviens bien.

**Comment by TheoLechemia** [comment]
Pour le MTES oui, il faudra pendre l'organisme producteur du JDD.
Dans d'autre cas, genre ATBI avec des organismes extérieurs qui viennent alimenter un jeu de donnée, ça peut causer des erreurs.
