### ISSUE TITLE
2.13 - Importer dans un JDD depuis Métadonnées

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#2713]
Un raccourci avait été développé depuis la module Métadonnées pour pouvoir accéder directement au module IMPORT depuis la liste des JDD, dans la version 2.6.
Ce bouton et développement était spécifique et faisait référence au module IMPORT dans le cœur de GeoNature, ce qui n'est pas souhaitable.

Le fonctionnement a été revu dans la version 2.10.4 pour ne plus être spécifique au module IMPORT et ne pas y faire référence : https://github.com/PnX-SI/GeoNature/issues/2151

Mais le bouton n’apparaît pas (plus ?) dans la liste des JDD quand on a le module IMPORT installé.

Il faut configurer quelque chose ? Ou alors la fonctionnalité a un soucis ? Ou alors une régression liée aux permissions ?

**Comment by bouttier** [comment]
Corrigé par https://github.com/PnX-SI/GeoNature/pull/2729 et https://github.com/PnX-SI/gn_module_import/pull/483

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.13.2 (qui nécessite au de MAJ le module Import en version 2.2.3)
