### ISSUE TITLE
2.13 Description du cadre d'acquisition qui ne s'affiche pas

### ISSUE THREAD

**Issue by marie-laure-cen** [PnX-SI/GeoNature#2716]
geonature 2.13.0 nouvellement installé

Dans la fiche du cadre d'acquisition de notre geonature, la description ne s'affiche pas, que ce soit pour les cadres d'acquisition créés par défaut lors de l'installation ou pour les cadres d'acquisition créés après.

![ca_1](https://github.com/PnX-SI/GeoNature/assets/143165944/d167cfbf-b0aa-46b3-9e97-f0d9b8b1c31d)

![ca-2](https://github.com/PnX-SI/GeoNature/assets/143165944/6e15ac78-c4c7-4a06-8a15-9e916890fe56)

**Comment by mvergez** [comment]
Effectivement, cette description n'apparait pas. J'ai corrigé ça : 
![image](https://github.com/PnX-SI/GeoNature/assets/85738261/7d7c7067-e044-4c3d-b8ae-ff4998c49a49)

Est-ce que cela vous convient ?

Pour l'aspect développement j'ai simplement rajouté ces balises : 
```html
<div class="a">
     <b>Description :</b> {{ af?.acquisition_framework_desc }}
</div>
```
Si ça vous va je fais une PR

**Comment by camillemonchicourt** [comment]
Ah oui bien vu, le champs a été oublié dans la fiche.
Cool si tu peux faire une PR.

**Comment by marie-laure-cen** [comment]
Merci !
