### ISSUE TITLE
Problème de performance serveur GeoNature

### ISSUE THREAD

**Issue by RNF-SI** [PnX-SI/GeoNature#2717]
Bonjour,

Suis-je le seul à avoir des problèmes de performance sur un serveur ou GeoNature est installé ?
J'ai une instance sur un serveur avec 80000 observations. Seul GeoNature (2.13.0) et TaxHub sont installés sur ce serveur (8GB de RAM, 4 coeurs, 300 GB HDD, Debian 11). 
Je dirai que d'ordinaire ça se passe bien. Mais des fois l'appli est simplement inutilisable. Quand je vais voir sur le serveur, j'ai 6GB/8GB d'utilisés, d'où le ralentissement conséquent de la machine. Même en ssh c'est compliqué de travailler tellement c'est lent. 
Si je fais un `htop `(ou un `top`), je n'identifie pas ce qui me bouffe de la RAM. D'ailleurs si je stop les services de geonature, taxhub, apache et postgres je n'ai quasiment plus rien, pourtant ma RAM reste au plus haut niveau et la machine est toujours inutilisable. 

La commande `free `me donne le résultat suivant :
```
               total       utilisé      libre     partagé tamp/cache   disponible
Mem:         8147780     6226796      124836       62064     1796148     1603228
```

Une commande me sauve : `geonature update_configuration`. Ca met beaucoup de temps (puisqu'au début le serveur est surchargé, mais finalement la RAM retombe à un niveau tout à fait normal (autour de 1,07 GB) et ça remarche du feu de dieu :

```
               total       utilisé      libre     partagé tamp/cache   disponible
Mem:         8147780     1048364     5340656       66880     1758760     6774808
```

Qu'est-ce qui provoque ça ? Une tâche de fond à priori, puisque ça ne semble pas être le résultat d'une action sur geonature. Est-ce que d'autres ont ce problème ? et comment le résoudre ?

Je précise que c'est le cas également sur une autre instance sur un autre serveur, et que la version actuelle est la 2.13.0 mais j'ai déjà ce problème depuis longtemps.

**Comment by lpofredc** [comment]
Peut-être creuser du côte de geonature-worker. N'y a-t-il pas des taches programmées gourmandes (génération d'exports ?).

**Comment by RNF-SI** [comment]
Je ne vois pas quelle tâche, le module d'export n'est pas installé...

**Comment by RNF-SI** [comment]
Peut être existe t'il un outil pour suivre l'évolution de la conso de RAM ?

**Comment by DonovanMaillard** [comment]
Bonjour, 

Je crois que @xavyeah39 s'est penché sur la question, il constate aussi que quelle que soit la RAM de sa machine elle sature : plus il y en a, plus ça consomme

**Comment by RNF-SI** [comment]
Oui en effet, sur un des serveurs je suis monté à 16 GB de RAM, et ça consomme tout ce qu'il y a. Mais comment faire pour que GeoNature ne devienne pas inutilisable ?

**Comment by xavyeah39** [comment]
Salut !

Effectivement, j'ai constaté le même problème de surconsommation de ressources sur les instances dont je m'occupe depuis màj en 2.12. (actuellement on est en 2.13.0 )
Après investigation, on dirait que ce sont les workers Celery et les process gunicorn exécutés qui ouvrent des connexions PostgreSQL qui semblent ne jamais se fermer.

On dirait aussi que les connexions "utilisateurs" ne sont pas toujours fermées après déconnexion (web ? synchro mobile ?).
Ces connexions qui restent ouvertes continuent de consommer de la RAM alors que leur statut dans postgresql est "idle" (inactive). Et d'après les logs du worker geonature, les transactions vers la BDD sont bien terminées.
Rien d'anormale en soit que certaines connexions restent ouvertent dans PG mais certaines continuent de consommer jusqu'à 20% de RAM alors qu'elles sont en état inactif... et sont toujours ouvertes plusieurs jours après leur exécution.

C'est le cas semble-t'il avec les tâches planifiées comme le rafraichissement des profils de taxons, des données du module Dashboard ou du nettoyage auto des médias.
Des tâches qui sont depuis la 2.12 lancés par des tâches planifiées Celery.

Pour identifier, j'ai regardé les process consommant de la mémoire avec htop `--sort-key=PERCENT_MEM`

![image](https://github.com/PnX-SI/GeoNature/assets/16793813/6892008c-3e59-42c1-8717-f09d22c5b52d)


Dans la vue ``pg_catalog.pg_stat_activity`` on peut faire correspondre avec les transactions en cours via le PID indiqué dans HTOP.
C'est là que je vois que l'état des connexions est à "idle" (inactive) sur les PID les plus consommateurs de RAM.

On voit aussi l'heure d'execution qui est la plus souvent aléatoire (connexions utilisateurs ou syncro mobile) mais on y voit aussi que certaines des connexions ouvertes s'execute de nuit (tâches planifiées).

![image](https://github.com/PnX-SI/GeoNature/assets/16793813/f2227d4c-86c4-4459-b4f1-49e10bd0120f)


Si j'arrête les services geonature, geonature-worker, taxhub et usershub les uns après les autres tout en surveillant le htop, l'ensemble des connexions postgresql ouvertes (et qui consomment + de 50% de RAM) se ferment toutes et la VM retrouve une consommation de RAM plus raisonnable.
Je remarque aussi que si je fais une modif dans le fichier de conf de GeoNature (auto-appliquée désormais) alors que ces connexions gourmandes sont toujours ouvertes, pouf, la plupart disparaissent de htop et la RAM baisse sur la VM.

Pourtant, quand on inspecte les logs du worker geonature, on remarque que l’exécution de ces tâches aboutisse bien... mais la connexion à la base semble restée ouverte...

![image](https://github.com/PnX-SI/GeoNature/assets/16793813/83b8ea27-5d60-4683-bf22-91796fc0c120)


D'ailleurs, en passant, on dirait bien qu'il y ai un soucis sur l'heure d’exécution des tâches Celery au vu de l'horodatage des logs :
la tache CLEAN_MEDIA_ATTACHMENT est programmée par défaut à 1h du matin mais sont exécution est loguée à 3h dans les geonature-worker.log (ainsi que dans pg_stat_activity):
Les +2h de décalage horaire font penser à un soucis de timezone (au niveau de Celery ?). 
En tout cas nos VM sont bien à l'heure et configurées avec avec NTPDATE.

Je n'ai pas non plus d'autre tâche CRON qui s’exécute hormis celles qui sont désormais intégrés à GeoNature avec Celery.

Mais le problème de consommation de ressource me semble plus global car là où j'ai eu le plus de soucis de saturation de ressources c'est avec le module d'import qui fonctionne aussi désormais avec des workers désormais.
Pour nous il est devenu presque impossible à utiliser sur des jeux de données conséquents et/ou avec de nombreuses geométries complexes (polygones).
La consommation de RAM explose aussi durant les process de vérification des imports, saturation aussi de la mémoire Swap puis plantage du kernel et oom killer qui tue les process et plante les imports. Bien plus critique donc...

@gildeluermoz a déjà remonté ce type de soucis dans cet issue du module d'import [#442](https://github.com/PnX-SI/gn_module_import/issues/442)
Avec un renvoi vers cette autre issue côté GeoNature : #2613

Je me suis basé sur ses retours pour augmenter la swap sur mes machines (qui en avait déjà autant que de RAM). J'ai aussi augmenté la RAM pour voir mais plus on en met plus ça consomme...
Ça m'a permis de faire passer certains gros imports avec les versions récentes du module mais un peu dans la douleur... (et en ajoutant parfois jusqu'à 20go de swap pour que ça passe !)
Comme lui, j'ai cru au début que cela pouvait venir de nos conf postgresql personnalisées selon les ressources des VM mais on ne dirait pas...

Nous n'utilisons pas encore le module d'export mais il est fort possible qu'il y ai aussi ce genre de soucis sur l’exécution des tâches de fond.

A+

**Comment by gildeluermoz** [comment]
Bonjour à tous,
Qq retours sur mon expérience à ce propos.
La consommation de la RAM qui reste haute, y compris dans les contextes décrits par @xavyeah39 ou @RNF-SI n'est pas forcement un soucis. Linux attribue de la RAM aux process qui en sollicitent et ne la libère que si d'autres process nouveaux en ont besoin. De sorte, la RAM semble toute consommée mais cela ne veux pas dire qu'il va y avoir un manque de mémoire.
Ceci explique cela

> Je me suis basé sur ses retours pour augmenter la swap sur mes machines (qui en avait déjà autant que de RAM). J'ai aussi augmenté la RAM pour voir mais plus on en met plus ça consomme...

ou ceci : 

>  il constate aussi que quelle que soit la RAM de sa machine elle sature : plus il y en a, plus ça consomme


Par contre les gros imports qui demandent beaucoup de RAM, c'est un vrai soucis qu'il serait pertinent de résoudre à la manière de ce qui a été fait depuis la 1.5 du module d'export. J'ai pu tester le comportement de la consommation mémoire avec htop sur de gros exports avant et après la 1.5 : c'est le jour et la nuit. Avant la 1.5, la mémoire monte progressivement jusqu'à la fin de l'import. S'il est trop grand, lorsque RAM + swap sont dépassés : plantage (oom killer tue postgres). ceci explique cela : 

> Ça m'a permis de faire passer certains gros imports avec les versions récentes du module mais un peu dans la douleur... (et en ajoutant parfois jusqu'à 20go de swap pour que ça passe !)

Et après vérification, ce n'est pas postgres qui est en cause mais gunicorn.

Pour @RNF-SI, 2 commentaires sur le retour de ta commande `free` : 
1- soit tu n'as pas de swap, soit tu n'as pas copié la ligne concernant le swap. Si tu n'as pas de swap : https://www.it-connect.fr/comment-ajouter-de-lespace-de-swap-sur-gnu-linux-debian-10/
2 - rien d'anormal dans la mémoire disponible, 

> Quand je vais voir sur le serveur, j'ai 6GB/8GB d'utilisés, d'où le ralentissement conséquent de la machine. 

a priori, ce n'est pas ça qui ralenti ton serveur. Les problèmes de manque de mémoire vont ralentir le serveur si le swap est sur un disque dur lent (SATA par ex). Le symptome que j'ai constaté sur un manque de RAM n'est pas un ralentissement mais plutôt un plantage.

> Même en ssh c'est compliqué de travailler tellement c'est lent.

Là c'est extrême. Les seules fois où j'ai pu constater de telles lenteurs, c'est un problème de disque dur (occupation de l'espace proche de 100%).
Que donne la commande `df -h` dans ce cas ? Si remplissage, utilise `du -hs` pour trouver le ou les répertoires responsables.
Est-ce que ton swap est sur un disque dur SATA ou SSD/Nvme ?

Est-ce que tu peux nous donner qq spec concernant la techno de tes disques, le swap, etc ?
A noter, OVH ne livre pas d'espace de swap sur ses VPS, il faut le créer manuellement en utilisant la méthode données dans le lien ci-dessus. J'ai testé sur 7 ou 8 serveurs, ils ne plantent plus depuis ...

**Comment by bouttier** [comment]
Pouvez-vous tester le correctif proposé dans la PR #2724 et faire un retour ?

**Comment by gildeluermoz** [comment]
Merci Elie
Comme je ne gère pas de contenu, je ne peux pas tester sur de gros import par exemple. 
Est-ce que @xavyeah39 ou @RNF-SI peuvent faire le test ?

**Comment by camillemonchicourt** [comment]
Si j'ai bien suivi ce correctif ne concerne pas le soucis des gros imports, mais le fait que les taches Celery ouvrent des connexions à la BDD sans les fermer donc celles-ci s'empilent et font monter la RAM.

**Comment by RNF-SI** [comment]
Je viens de voir que ça a été intégré dans la dernière version de GeoNature. Je fais la maj demain et je vous tient au courant. merci !

**Comment by RNF-SI** [comment]
Petit retour après quelques jours sous la 2.13.2 :
J'ai ce matin à nouveau ma RAM qui s'est envolée (alors même qu'il ne s'est rien passé sur l'application à priori - ni saisie, ni import, ni export). 
htop me donne le résultat suivant (ordonné par conso de RAM) : 
![Capture d'écran 2023-10-03 092405](https://github.com/PnX-SI/GeoNature/assets/43465924/7ce2be77-5c6f-4ee3-bbcf-9df4082351e2)

J'ai ensuite arrêté les services suivants un a un : geonature, geonature-worker, postgresql, apache2, taxhub.
un nouveau htop me donne ça : 
![Capture d'écran 2023-10-03 093015](https://github.com/PnX-SI/GeoNature/assets/43465924/c11ef3e5-054c-403d-bb12-551e8c3fcd97)

La somme des tâches ne fait donc clairement pas 4.87 G de RAM... (il n'en manque qu'une de visible sur la capture).

**Comment by lpofredc** [comment]
Et que donne la commande `free -h` maintenant ? Il est possible qu'une partie de la RAM soit du cache, utilisé mais disposable.

**Comment by RNF-SI** [comment]
total       utilisé      libre     partagé tamp/cache   disponible
Mem:           7,8Gi       1,3Gi       5,1Gi        17Mi       1,3Gi       6,2Gi
Partition d'échange:      974Mi        45Mi       929Mi

Mais ici la RAM est retombée et j'ai relancé les services
