### ISSUE TITLE
[Synthese] Remplacer le nom de l'espèce par un lien hypertexte dans la liste des observations

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature#2718]
Bonjour,

Dans le cadre d'une prestation pour l'Agence Régionale de la Biodiversité en île de France, il a été demandé s'il était possible, dans la liste des observations de la synthèse, de remplacer le nom du taxon par un lien vers la fiche du taxon de GeoNature.

Quelque chose comme cela : 
![image](https://github.com/PnX-SI/GeoNature/assets/85738261/9811e04a-b253-4a5c-9720-015451a4d1a9)

Est-ce que cela vous intéresse ?

Merci d'avance pour vos retours !

**Comment by DonovanMaillard** [comment]
personnellement, je trouve ça un peu "paumatoire" qu'en cliquant sur une ligne d'observation, on arrive sur une info qui n'est pas directement liée à l'obs en elle-même :confused:

**Comment by mvergez** [comment]
L'objectif n'est pas de pouvoir cliquer sur une ligne d'observation mais sur le nom de l'espèce en question. Cela permettrait d'accéder à la fiche espèce plus rapidement

**Comment by camillemonchicourt** [comment]
Je pense aussi que ça serait bien que le nom d'espèce voire toute la ligne soit cliquable, mais pas pour aller à la fiche de l'espèce, mais pour ouvrir le fiche de l'observation.
Quand on a une ligne de résultats, il faut faciliter l'accès vers le détail de chaque objet.
Mais pas des raccourcis vers une autre page car là sinon c'est difficilement compréhensible.
Liste d'objets >> Détail de chaque objet

**Comment by Adrien-Pajot** [comment]
Cette idée est tout à fait pertinente et logique. Elle est d'ailleurs faite dans tous les outils mondiaux de qualité comme iNaturalist ou eBird par exemple.

**Comment by camillemonchicourt** [comment]
C'est une liste d'observations. Je clique sur un objet de la liste je dois arriver au détail de l'observation, sinon je ne comprends pas qu'il y a une fiche info de l'observation.

**Comment by mvergez** [comment]
J'ai l'impression qu'il y a une incompréhension entre cliquer sur la ligne du tableau (qui aujourd'hui s'illumine en vert) et cliquer sur un élément de la ligne du tableau (l'espèce, le jdd, l'observateur).

Donc, pour être certain de comprendre, pour toi @camillemonchicourt, si on clique sur la ligne on accède à l'info de l'observation mais peut-on cliquer sur le jdd par exemple, pour aller dans métadonnées ? Cliquer sur l'espèce pour aller sur la fiche espèce etc. ?

**Comment by camillemonchicourt** [comment]
Oui oui j'ai bien compris.
Même si cela complexifie l'usage et la compréhension d'une liste de résultats, on peut avoir des liens secondaires dans une liste de résultats pour l'enrichir.
Mais dans ce cas, il faut bien comprendre qu'on un lien principal vers le détail de l'objet et des liens secondaires vers des sous-objets des objets de la liste de résultats.

Dans notre cas, on n'a pas de lien principal vers l'objet de la liste, mais seulement un petit bouton "i".
Si on ajoute un lien sur le nom de l'espèce vers la fiche de l'espèce, alors ce lien secondaire prendra clairement le dessus sur le lien principal de l'objet principal de la liste (l'observation).

Si on fait ça, un grand nombre d'utilisateurs vont cliquer sur le nom en pensant accéder au détail de l"observation, mais accéderont en fait au détail de l'espèce de l'observation...

Dans ebird, c'est discutable, mais ça fonctionne car dans la liste des observations, on a un lien vers l'observation ET un lien vers l'espèce.

Mais globalement pour faire clair et simple d'utilisation, on retrouve classiquement : 
Recherche d'objets > Liste de résultats d'objets > Détail objet > Détail sous-objets ou objets liés

**Comment by DonovanMaillard** [comment]
L'autre réflexion à avoir c'est faut-il mutiplier les liens ou non ? Parce que ce même lien serait logique pour le JDD qui est aussi affichable dans la liste des résultats. Et pourquoi pas à terme une fiche "observateur" en cliquant sur l'observateur etc. 

A mon avis dans la synthèse, on consulte avant tout des données donc je limiterais à un lien vers la fiche détail de l'obs. Une fois dessus, on a accès à la fiche taxon sans soucis. Mais on le voit dans les réponses, c'est assez subjectif et 50/50 ici

**Comment by mvergez** [comment]
> un grand nombre d'utilisateurs vont cliquer sur le nom en pensant accéder au détail de l"observation

Je trouve quand même cela vraiment illogique (et c'est le cas dans INaturalist).

Le souci c'est que si on clique sur la ligne au lieu du "i" on ne pourra pas voir l'obs sur la carte parmi les autres. Et donc il faudra mettre un autre bouton du type "Voir cette obs sur la carte" donc effectivement ça complexifie.

On reste comme ça alors, je transmets cela à l'ARB. Merci beaucoup pour vos retours !

**Comment by camillemonchicourt** [comment]
Si on veut ajouter un lien vers les fiches espèces directement depuis la liste des observations, il faut reprendre cette liste au niveau design et fonctionnement.

**Comment by camillemonchicourt** [comment]
Dans iNaturalist, c'est bien fait, car il y a bien un lien principal et bien présent et visible sur l'observation (objet principal), mais aussi un lien secondaire direct vers le fiche d'un observateur : 

![image](https://github.com/PnX-SI/GeoNature/assets/4418840/a601091a-c5b1-45d2-9d8c-448a15095a94)

**Comment by mvergez** [comment]
Oui effectivement, mais je parlais plus du lien de l'espèce ici. Mais l'idée serait la même : avoir un lien vers l'observateur pour dans le futur avoir une fiche observateur, un lien vers le jdd vers métadonnées.

C'est juste dommage de devoir faire 2 clics alors qu'on a la possibilité d'en faire qu'un. Mais si vous pensez que cela nuit à l'expérience utilisateur alors on ferme cette issue et on ne parle plus de cette "fonctionnalité".

**Comment by camillemonchicourt** [comment]
Je pense que c'est envisageable si on revoit globalement le fonctionnement de la liste des observations de la Synthèse.
Car en l'état le lien vers la fiche espèce prendrait le dessus sur le lien vers la fiche Observation, ce qui serait bien dommage.

**Comment by TheoLechemia** [comment]
ça fait un moment que je me dit qu'on pourrait mettre en avant la fiche espèce de GeoNature en mettant un lien sur l'espèce dans les listes (pas que la Synthese, mais Occtax, Monitoring etc...). Je trouve pas que mettre un lien sur l'espèce va faire croire qu'on va accéder à la fiche observation. Les boutons "action" en début de ligne sont assez explicites, et très courant dans tous les outils (cf Flask admin ou tous les outils de CRUD) : il y a toujours une ligne avec des boutons d'action en début de ligne : "voir", "éditer", "supprimer" 
![image](https://github.com/PnX-SI/GeoNature/assets/15265745/10ca10d4-d596-42d6-a3e0-8718a78aae43)

**Comment by camillemonchicourt** [comment]
Oui pour un CRUD et une admin. 
Mais la synthèse n'est justement pas un CRUD et je pense qu'elle mériterait d'être plus désignée et plus web (voir iNaturalist qui est bien sympa par exemple) et moins Admin.
Dans les principes UX du web, c'est Recherche > Résultats > Détail, en faisant le plus simple et le moins de dispersion possible pour être certain que l'utilisateur comprenne et arrive à sa page de détail. 
Une fois sur cette page, on lui montre tout les détails et on lui propose plein d'autres suggestions pour rebondir sur d'autres choses, d'autres pages, les objets secondaires, etc...

Mais je suis d'accord d'enrichir les pages espèces (qui ont peu d'intérêt actuellement) et de leur donner plus de visibilité et de chemins d'accès.

**Comment by edelclaux** [comment]
Allez, je remets une pièce dans la machine ! 

J'ai un peu de mal à comprendre la réticence à rendre le nom du taxon, ou du JDD, cliquable.

Aujourd'hui, dans l'import, on a un exemple de ce fonctionnement, qui ne me semble pas confus.
![image](https://github.com/user-attachments/assets/bf3c047a-a9a0-432f-9b1d-d3ed8801a0be)

J'ai du mal à comprendre la confusion que vous souhaitez éviter. Le fonctionnement pourrait être assez similaire. 
![image](https://github.com/user-attachments/assets/72055eb9-b93f-4334-ae4c-d9db65d6fa57)

En rendant le nom cliquable, ça ne me parait pas perturber outre mesure la compréhension de la liste. Au contraire, ça me parait assez standard comme comportement.

Personnellement, j'imagine une navigation qui permet plusieurs chemins: 
![image](https://github.com/user-attachments/assets/1441e294-6a77-4cef-adc1-fd1bc6770c84)






> Remarque: La question de savoir si l'accès à l'observation se fait via un click sur la ligne ou via un click sur un bouton info me parait être une question  indépendante.

**Comment by camillemonchicourt** [comment]
Ouais ouais pourquoi pas.
Je continue à penser que mettre un lien sur le premier mot de la liste peut apporter un peu de confusion et laisser penser qu'on va accéder au détail de l'objet listé (l'observation donc) et donc pas sur un objet périphérique (la fiche de l'espèce observé), d'autant plus que le (i) n'est pas très visible, mis en avant.

Mais pourquoi pas si la majorité est convaincue.

**Comment by edelclaux** [comment]
Comment on déclenche un vote ?

**Comment by TheoLechemia** [comment]
Je redonne mon avis aussi ;)
Pour utiliser inaturalist regulièrement, je trouve contre-intuitif d'être redirigé vers la fiche de l'observation quand on clique sur le nom de l'espèce. Je me fait avoir à chaque fois.
La le fait d'avoir les boutons d'action sur le côté et des liens qui redirige vers des pages connexes, ça me parait assez clair et explicite.
(ça fait un +1 pour le lien ;) )

**Comment by camillemonchicourt** [comment]
Pas besoin de vote il me semble, et ce n'est pas trop notre pratique. :-)
Je pense que ce n'est pas un sujet central. On voit que les avis sont partagés. Donovan et moi y voyons une possible confusion, d'autres sont convaincus. 
Dans tous les cas, il est intéressant de donner plus de visibilité et d'accès à cette fiche d'espèce (en cours d'enrichissement).
Je pense que ce serait mieux de faire cela en même temps qu'un travail sur le design des cartes/listes (comme discuté sur https://github.com/PnX-SI/GeoNature/issues/557#issuecomment-1970084182) pour éviter de possibles confusions. 

Mais on peut déjà tester, ajouter le lien vers la fiche espèce sur le nom des taxons observés, si on le fait aussi en même temps sur le nom du HDD (pour montrer qu'il y a différents liens secondaires). Et voir ce que ça donne.
Si les avis sont vraiment partagés, on pourra toujours y mettre un petit paramètre pour l'activer ou non, et chacun pourra alors faire comme il veut.

**Comment by DonovanMaillard** [comment]
On peut aussi voir si ce petit "i" ne peut pas être plus explicite avec un picto "oeil" ou autre, pour bien montrer que ce lien là renvoie sur l'observation et pas autre chose...

**Comment by edelclaux** [comment]
> On peut aussi voir si ce petit "i" ne peut pas être plus explicite avec un picto "oeil" ou autre, pour bien montrer que ce lien là renvoie sur l'observation et pas autre chose...

J'aime bien l'oeil dans l'absolu, mais je penche pour garder le "i" par cohérence. Dans Occtax, Occhab, Metadonnées, et Import, c'est un petit "i" qui est utilisé.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.15
