### ISSUE TITLE
Intégrer l'heure dans le formulaire du contact

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#273]
Les champs ``date_min`` et ``date_max`` sont de type ``timestamp`` en BDD. Donc concaténer l'heure à la date pour l'intégrer en base

**Comment by camillemonchicourt** [comment]
Ce ne sont pas 2 champs bien distincts dans OCCTAX ?
Je croyais qu'on avait dit qu'on partait sur 2 champs JOUR MAX et MIN et 2 champs HEURE MIN HEURE MAX. 
Au final, je n'ai pas de préférence. :-)

**Comment by TheoLechemia** [comment]
Comme le timestamp permet de tout stocker dans le même champ, c'est bête d'en recréer deux nouveaux je trouve. Après pour les exports, on distingue heure et date grâce à la vue

**Comment by camillemonchicourt** [comment]
OK impec

**Comment by camillemonchicourt** [comment]
Par contre comme savoir si l'heure a été précisée ou non du coup?

Si l'heure est à 0000 alors c'est que le champs heure n'a pas été rempli ?

**Comment by TheoLechemia** [comment]
Ah ouais... pas top du coup

**Comment by TheoLechemia** [comment]
Du coup, la 1ere version avec des champs "heure_min" et "heure_max" séparé parait plus propre.
Je veux bien essayé de m'y coller, pour me familiarisé un peu avec le back. Je teste dans une branche à part.

**Comment by TheoLechemia** [comment]
Petit problème:
quand on ne rempli pas l'heure, en base le champs est bien à NULL, mais la route getOneReleve (/releve/<id>) renvoie une chaîne de caractère "None": ça pose un problème côté front ou il y a une expression régulière pour vérifier si ce champ est bien au format "HH:MM:SS"
