### ISSUE TITLE
Erreur maj 2.13.0>2.13.2

### ISSUE THREAD

**Issue by RNF-SI** [PnX-SI/GeoNature#2732]
**Version**
2.13.2

**Description du bug**
Erreur lors de la mise à jour, conflit de dépendances à pypnusershub :
```
ERROR: Cannot install -r requirements.txt (line 244), -r requirements.txt (line 298), geonature==2.13.2 and pypnusershub==1.6.10 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pypnusershub==1.6.10
    pypnnomenclature 1.5.4 depends on pypnusershub>=1.6.0
    taxhub 1.12.1 depends on pypnusershub<2.0 and >=1.6.8
    geonature 2.13.2 depends on pypnusershub<2 and >=1.6.11
```

**Comportement attendu**
Mise à jour sans problème

**Comment reproduire**
Faire la mise à jour de GeoNature depuis la 2.13.0 vers la 2.13.2

Je ne sais pas si c'est lié au saut de la 2.13.1. Dois je refaire une maj vers cette version avant de relancer le script de migration vers la 2.13.2 ?

**Comment by camillemonchicourt** [comment]
Tu veux dire vers une 2.13.2 ?

**Comment by RNF-SI** [comment]
oui pardon, 2.13.2 bien sûr

**Comment by RNF-SI** [comment]
j'ai tenté de refaire une install de la 2.13.1, qui fonctionne bien (même si j'ai peut être des problèmes de bases de données dû aux branches alembic...)
J'ai retenté ensuite l'installation de la 2.13.2 et j'ai la même erreur.

**Comment by camillemonchicourt** [comment]
Petite erreur de ma part que Pierre vient de corriger : https://github.com/PnX-SI/GeoNature/pull/2734

Et il vient de refaire la release 2.13.2 qui devrait être OK désormais.
