### ISSUE TITLE
[Occtax GN2.13.2] Liste des taxons non alimentée pour la saisie

### ISSUE THREAD

**Issue by AudreyEnGuyane** [PnX-SI/GeoNature#2738]
**Version**
GN 2.9 puis 2.13.2

**Description du bug**
Dans le module de gestion des métadonnées, une liste de taxons (id 101) a été affectée au jeu de données.
Il correspond à une liste d'espèces définie dans TaxHub.
Lors de la saisie dans Occtax sur ce jeu de données, aucun taxon n'est saisissable.

**Comportement attendu**
Qu'on puisse saisir une donnée sur les taxons listés !

**Comment reproduire**
1/ créer une liste de taxons et y affecter quelques espèces (avec TaxHub).
2/ limiter la saisie à cette liste de taxons dans les paramètres d'un JDD à l'aide du champ "liste des taxons (facultatif)" (module Métadonnées)
3/ créer un nouveau relevé dans occtax et tenter de saisir un des taxons de la liste

**Logs**

**Comment by camillemonchicourt** [comment]
Je viens de tester et en fait ça fonctionne, mais y a bien un soucis.... :-)

Ton problème doit être lié à ça : https://github.com/PnX-SI/GeoNature/issues/1549

On interroge un code_liste mais en passant l'id_liste, donc si ils sont différents, ça ne trouve pas la liste...

C'est un truc qu'on doit corriger côté GeoNature.
Mais en attendant, la solution est de renseigner le code_liste avec l'id de la liste au niveau de TaxHub.

**Comment by AudreyEnGuyane** [comment]
Mais déjà le cas...
![code_et_id_liste_LoutreEtTapir](https://github.com/PnX-SI/GeoNature/assets/37804139/c31704d8-cae8-4e35-a7ed-7f6e88020423)

**Comment by joelclems** [comment]
Je viens de tester et ça marche, il faut par contre taper au moins trois lettres pour avoir un résultat (marche avec `lou` `tap`)

**Comment by AudreyEnGuyane** [comment]
Après vérification, en effet, ça fonctionne sur l'instance de recette... Mais pas sur la prod...
![erreur_listeTaxo](https://github.com/PnX-SI/GeoNature/assets/37804139/c96f9a04-a2e1-45c4-a95e-c4846c1b01a8)

**Comment by DonovanMaillard** [comment]
Bonjour MissT, il semble que vous n'avez pas de liste dont le code est 101. Attention, les codes doivent etre égaux aux identifiants pour marcher, c'est pas normal mais c'est un soucis identifié. Change simplement le code de ta liste 101 pour y mettre "101" et ca passera sans doute

![Capture d’écran 2023-10-05 à 14 07 39](https://github.com/PnX-SI/GeoNature/assets/23358384/e8d55b04-4afb-4901-bbe0-d058a8b6574f)

**Comment by AudreyEnGuyane** [comment]
Gros mea culpa: le code liste sur la recette est bien 101 mais pas sur la prod... 
Ca fonctionne et j'ai honte de vous avoir sollicité pour ça...
C'est une caractéristique à noter dans le manuel de TaxHub...

**Comment by camillemonchicourt** [comment]
Non c'est bien un soucis à corriger côté GeoNature / Occtax.

**Comment by DonovanMaillard** [comment]
Oui c'est la route qui appelle le code alors qu'on lui passe un id si je ne me trompe pas...
