### ISSUE TITLE
[frontend] Suppression du fichier app.config.ts (?)

### ISSUE THREAD

**Issue by jacquesfize** [PnX-SI/GeoNature#2747]
Je suis en train de cartographier le backend et frontend de Geonature. Au cours de mon voyage (:smile:), je suis tombé sur le fichier `app.config.ts` (dans le dossier `frontend/src/conf`) qui contient une version JSON du fichier de configuration de Geonature (`config/geonature_config.toml`). Selon @TheoLechemia , ce fichier n'est plus censé être utilisé, ni généré. Est-ce bien le cas ?

Si oui, je propose de :
  - [x] Vérifier si des modules tierces de Geonature utilisent encore ce fichier 
  - [x] Modifier le programme d'installation de Geonature pour supprimer la génération du fichier `app.config.ts`
  - [x] Supprimer le template  présent dans `frontend/src/conf`

**Comment by TheoLechemia** [comment]
Merci !
Il y a aussi un tour à faire côté backend pour supprimer les fonction / commandes geonature qui se chargeaient de créer ce fichier. Notamment : https://github.com/PnX-SI/GeoNature/blob/master/backend/geonature/utils/command.py#L22 et https://github.com/PnX-SI/GeoNature/blob/master/backend/geonature/core/command/main.py#L75

**Comment by Pierre-Narcisi** [comment]
Je pense qu'il faudra aussi modifier la CI pour enlever la partie où on l'imprime : https://github.com/PnX-SI/GeoNature/blob/master/.github/workflows/cypress.yml#L106
