### ISSUE TITLE
[Synthese] Utilisation du paramètre SYNTHESE.LIST_COLUMNS_FRONTEND pour personnaliser les colonnes

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature#2749]
Bonjour,

Dans le cadre d'une prestation pour l'Agence Régionale de la Biodiversité en île de France, je me suis aperçu que le paramètre frontend `SYNTHESE.LIST_COLUMNS_FRONTEND` ne fonctionnait pas comme prévu.

En effet, j'ai voulu ajouter la colonne `meta_update_date` dans le paramètre `LIST_COLUMNS_FRONTEND` dans le fichier `geonature_config.toml`. Cette colonne existe bien dans la vue `v_synthese_for_web_app`. Or la colonne est vide en frontend.

Cela vient de ces lignes : 
https://github.com/PnX-SI/GeoNature/blob/7ee68c5555ecd4e3d1b252dd78254a492cd2d7eb/backend/geonature/core/gn_synthese/routes.py#L152-L175

Qui remonte uniquement ces colonnes de la vue. En ajoutant manuellement `meta_update_date` dans cette liste cela fonctionné.

Cela me fait me poser 2 questions : 
1. Est-il possible de charger le paramètre `LIST_COLUMNS_FRONTEND` pour ajouter les colonnes demandées ?
2. Y a-t-il pas trop de colonnes remontées qui ne sont pas utilisées par le frontend ?

Je propose de traiter le premier point ci-dessus, est-ce que cela vous convient ?

Merci d'avance pour vos retours !

**Comment by camillemonchicourt** [comment]
Oui le principe est que l'on puisse customiser et afficher ou non des champs différents de ceux proposés par défaut, à partir des champs présents dans la vue `v_synthese_for_web_app`.
Donc si on ne peut pas prendre les champs qu'on veut dans cette vue, ce n'est pas souhaitable.

Sauf si le fait d'ajouter des champs dans la route `/for_web` va alourdir la réponse de cette API pour tous, en renvoyant dans tous les cas tous les champs listés, tout le temps, même si ils ne sont pas demandés dans la configuration des colonnes à afficher.
