### ISSUE TITLE
Configuration Message d'Accueil

### ISSUE THREAD

**Issue by naidinp** [PnX-SI/GeoNature#2756]
Bonjour à tous,

j'aimerais configurer le message de la Page d'accueil qui est :

> Bienvenue dans votre Outil de Saisie des Observations

> Cette zone permet d'afficher .....

J'ai surcouche la section dans le fichier geonature_config.toml, rebuilde le front et redemarré Geonature mais rien n'y fait, j'ai toujours le même message d'accueil.

Merci pour votre aide ou idées.

Bonne journée.

PS : version GeoNature v2.11.0

<img width="505" alt="geonat_accueil" src="https://github.com/PnX-SI/GeoNature/assets/56413576/555d43e8-00c4-45c3-8c1a-7ed7bd9c8c26">

<img width="721" alt="geonature_config" src="https://github.com/PnX-SI/GeoNature/assets/56413576/52aaee0d-04fc-4e66-a637-ac9080347e32">

**Comment by Jacobe2169** [comment]
Bonjour,

La modification du message d’accueil de Geonature  dans le fichier `geonature_config.toml` est une nouveauté de la version 2.12.0 (Voir la release https://github.com/PnX-SI/GeoNature/releases/tag/2.12.0). Si vous restez en 2.11.0, vous pouvez modifier le message dans le fichier `frontend/src/custom/components/introduction/introduction.component.html`

**Comment by naidinp** [comment]
Merci pour votre réponse ; effectivement j'aurai du le trouver avant de poser la question .....erreur de commande grep !
Bonne journée à tous.
