### ISSUE TITLE
Ajout/Mise à jour des diagrammes sur l'architecture de Geonature dans documentation 

### ISSUE THREAD

**Issue by jacquesfize** [PnX-SI/GeoNature#2760]
Bonjour à tous,

Fraichement embauché au parc des Écrins, j'ai commencé par faire un état des lieux de Geonature, son fonctionnement global, l'organisation de sa base de données, de son code. A l'aide de `draw.io`, j'ai produit plusieurs "cartes" - plutôt diagrammes - pour naviguer dans Geonature. @camillemonchicourt proposer d'intégrer ses diagrammes à la documentation de Geonature. Ça permettrait de mettre à jour les diagrammes existants. 

J'ouvre cette _issue_ pour partager ce travail et faire appel à vos contributions pour améliorer (voir tout chambouler :smile: ) ces diagrammes afin de les déposer dans la documentation plus tard.

Ne sachant pas trop où déposer le fichier** (en .drawio), je mets à disposition celui-ci dans cette _issue_. Pour ceux qui ne connaisse pas `drawio`, c'est un outil de création de diagramme gratuit et open-source. De plus, il est compatible avec tous les OS.

[architecture_globale.zip](https://github.com/PnX-SI/GeoNature/files/13042953/architecture_globale.zip)

[**] Faire une nouvelle branche ?

**Comment by camillemonchicourt** [comment]
Merci, j'ai ouvert le document directement sur https://app.diagrams.net/

Et j'ai exporté les différents diagrammes pour qu'on puisse les consulter directement ici pour un aperçu global : 

**1. Architecture globale :** 

![architecture_globale-Global](https://github.com/PnX-SI/GeoNature/assets/4418840/6de56e76-ee57-4ee7-a93a-5e8b6b6d8a9f)

**2. Rôle des modules :** 

![architecture_globale-Rôle des modules](https://github.com/PnX-SI/GeoNature/assets/4418840/1c9ab678-4f27-48eb-a860-dcc462a8eb65)

**3. Base de données :** 

![architecture_globale-Base de données](https://github.com/PnX-SI/GeoNature/assets/4418840/fe5dcfad-55ba-469d-ac57-7cd0a912264b)

**4. Base de données (détails) :** 

![architecture_globale-BDD détails](https://github.com/PnX-SI/GeoNature/assets/4418840/fc496852-5479-4a5c-bfc7-5e95a8c94a64)

**5. Backend (organisation) :** 

![architecture_globale-Backend Organisation](https://github.com/PnX-SI/GeoNature/assets/4418840/da9579e7-c1ab-4d76-a732-c9d5f3adf2e1)

**6. Frontend (organisation) :** 

![architecture_globale-FrontEnd Organisation](https://github.com/PnX-SI/GeoNature/assets/4418840/2b8c3fcd-4ed9-4f07-a4d8-96ea58df94e6)

--------------------------

Revoici le fichier des diagrammes avec quelques ajustements de forme et corrections mineures : 
[architecture_globale.zip](https://github.com/PnX-SI/GeoNature/files/13043565/architecture_globale.zip)

Je verrai bien l'intégration de ces schémas dans la documentation.
Par exemple, une partie pourra remplacer les schémas caduques dans la partie BDD (https://docs.geonature.fr/admin-manual.html#base-de-donnees) et une autre pourrait introduire les parties Backend et Frontend de la documentation de développement (https://docs.geonature.fr/development.html#developpement-backend)

**Comment by marie-laure-cen** [comment]
Pour mieux comprendre la structure de GeoNature au début, j'ai fait des diagrammes "simplifiés" / des extraits du diagramme dans ce genre-là :

![GN_structure_occtax](https://github.com/PnX-SI/GeoNature/assets/143165944/909c9c09-879f-4544-9f49-4c5022d9827b)

Est-ce que ça peut vous intéresser ?

**Comment by camillemonchicourt** [comment]
Oui très intéressant ce schéma. Ca clarifie bien les bases pour les nouveaux qui sont souvent perdus avec ces concepts. 
A voir où on pourrait glisser ça dans la doc.

Le schéma de données `gn_monitoring` est bien un élément global et générique du cœur de GeoNature.
Il est ensuite utilisé par le module Monitoring, mais aussi d'autres modules plus spécifiques de protocoles de suivi.

**Comment by jacquesfize** [comment]
Merci @marie-laure-cen, je les ai ajoutés dans le fichier drawio. J'ai aussi ajouté un "pseudo" MCD qui donne une vue globale entre entités (observations de taxons, géométries, etc..), les modules et les sources de données (TaxRef, HabRef,etc..).

![architecture_globale-MCD](https://github.com/PnX-SI/GeoNature/assets/4259846/0f79e49b-2028-4175-92e4-26b25a4fba12)

**Comment by camillemonchicourt** [comment]
Fichiers source du diagramme intégré dans la 2.14.0.
