### ISSUE TITLE
Installation instance dev sous Proxmox

### ISSUE THREAD

**Issue by naidinp** [PnX-SI/GeoNature#2762]
Bonsoir,

Je voudrais installer une instance de dev sous une VM proxmox mais impossible d'accéder à l'application qui est installé dans le répertoire /geonature malgré la redirection des ports et un bon accès sur le port 80 de la machine virtuelle depuis l'extérieur.

Existe t'il une doc pour la configuration pour une machine virtuelle VM sous proxmox ? ou avez-vous une idée  ....la j'ai plu d'idées.

Merci à tous.

**Comment by TheoLechemia** [comment]
Bonjour,
Il n'y a pas de configuration spéciale au fait que ce soit une VM sous proxmox.
Si vous voulez faire du dev sur la VM, vous pouvez regarder la doc ici : https://docs.geonature.fr/development.html#passer-en-mode-developpement
Le front se lance sur le port 4200 et le backend sur le port 8000. Il faut que ces ports soient accessible depuis l'exterieur

**Comment by naidinp** [comment]
Bonjour,
Merci pour les informations.
