### ISSUE TITLE
[Installation] Installation instance développement GeoNature

### ISSUE THREAD

**Issue by naidinp** [PnX-SI/GeoNature#2763]
Bonsoir à tous,
j'essaye d'installer une instance GeoNature 2.11.0 sur un serveur Debian 11 nouvellement installé mais j'ai cette erreur et l'installation s'arrête 
`[Install]
WantedBy=multi-user.target
/var/log/usershub/usershub.log {
    su geonatureadmin geonatureadmin
    daily
    rotate 8
    size 100M
    create
    compress
    postrotate
    systemctl reload usershub || true
    endscript
}
Module proxy already enabled
Considering dependency proxy for proxy_http:
Module proxy already enabled
Module proxy_http already enabled
Vous pouvez maintenant démarrer UsersHub avec la commande : sudo systemctl start usershub
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py:302: DeprecationWarning: '_app_ctx_stack' is deprecated and will be removed in Flask 2.3. Use 'g' to store data, or 'app_ctx' to acces                    s the current context.
  queries = _app_ctx_stack.top.sqlalchemy_queries
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py:304: DeprecationWarning: '_app_ctx_stack' is deprecated and will be removed in Flask 2.3. Use 'g' to store data, or 'app_ctx' to acces                    s the current context.
  queries = _app_ctx_stack.top.sqlalchemy_queries = []
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py:302: DeprecationWarning: '_app_ctx_stack' is deprecated and will be removed in Flask 2.3. Use 'g' to store data, or 'app_ctx' to acces                    s the current context.
  queries = _app_ctx_stack.top.sqlalchemy_queries
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/script/revision.py:195: UserWarning: Revision f63a8f44c969 is present more than once
  util.warn(
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/script/revision.py:195: UserWarning: Revision 9445a69f2bed is present more than once
  util.warn(
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/alembic/script/revision.py:195: UserWarning: Revision 6ec215fe023e is present more than once
  util.warn(
ERROR [flask_migrate] Error: Branch name 'usershub' in revision 9445a69f2bed already used by revision 9445a69f2bed
geonatureadmin@geonature-dev:~$
`

Avez-vous une idée d'où ca peut venir ?

Je vous joins également une capture d'écran pour plus de lisibilité peut-être.

Merci d'avance pour vos idées.

<img width="967" alt="error_install_geonature" src="https://github.com/PnX-SI/GeoNature/assets/56413576/ffde1c71-6049-49e8-b310-b079be72babd">

**Comment by Jacobe2169** [comment]
Bonjour,
Il semble que les révisions de usershub soit déjà appliquées dans votre base de donnés. La base de données était vide avant l'installation ? Est-ce que vous pouvez lancer un `geonature db status` ? Normalement, vous devriez voir si les révisions `userhub` ont déjà été appliquées.

**Comment by camillemonchicourt** [comment]
Si il y avait déjà une BDD installée et que vous avez relancé une installation, il faut plutôt renseigner "drop_geonaturedb=true" sinon la réinstallation ne fonctionne pas.

**Comment by naidinp** [comment]
> Si il y avait déjà une BDD installée et que vous avez relancé une installation, il faut plutôt renseigner "drop_geonaturedb=true" sinon la réinstallation ne fonctionne pas.

...effectivement ! je n'ai pas pensé à cette ligne.
Merci, c'est noté.
