### ISSUE TITLE
[Synthese] Attribut Taxhub dans la recherche taxonomique avancées ne fonctionne pas en mode multiselect

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature#2767]
**Version**
2.13.3

**Description du bug**
Quand on ajoute un attribut taxhub via la configuration : 
```toml
[SYNTHESE]
ID_ATTRIBUT_TAXHUB = [102, 103]
```

Et que ces attributs taxhub (localisés dans `taxonomie.bib_attributs`) ont un `type_widget` : `multiselect`, l'affichage ne fonctionne pas : 
![image](https://github.com/PnX-SI/GeoNature/assets/85738261/39a382e5-bba2-4f6a-bcb3-e32d9ba73fae)

**Comportement attendu**
Il faudrait que les labels s'affichent

**Comment reproduire**
Créer un attribut taxhub dans la table `taxonomie.bib_attributs` exemple : 
102	atlas_milieu	Milieu	{"values":["Forêt","Prairie","eau"]}	false	Habitat, milieu principal du taxon	text	multiselect			1	3

### Solution 

Supprimer ces lignes : https://github.com/PnX-SI/GeoNature/blob/22b577a5809a177d6ff75d0bb838dc8060d7a304/frontend/src/app/GN2CommonModule/form/synthese-form/advanced-form/synthese-advanced-form-store.service.ts#L66-L70

Je ferai une PR dans ce sens

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.13.4.
