### ISSUE TITLE
[MAP] Disparition de la géométrie existante lorsqu'on annule une création de nouvelle géométrie

### ISSUE THREAD

**Issue by andriacap** [PnX-SI/GeoNature#2778]
Bonjour,

Dans le cadre d'une prestation pour le développement de nouvelles fonctionnalités pour le module monitoring j'ai pu remarqué qu'il n'y avait pas de gestion d'événement lié à l'annulation de création de nouvelle géométrie sur une géométrie existante.

Pour illustrer mes propos, voici une image présentant le problème UX (au niveau du module OCCTAX) que peut rencontrer un utilisateur :

![geometry_no_kept_after_canceled_create_new_one](https://github.com/PnX-SI/GeoNature/assets/111564663/f105e712-4bb5-40f3-b79b-3dfdf492d862)

Au niveau technique , la gestion d'événement leaflet `Draw.Event.DRAWSTOP` n'est pas implémentée dans GeoNature. J'ai proposé alors un developpement pour implémenter la gestion de ce cas de figure que je vais partager dans une PR.

Merci et bonne jpurnée

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.14.0
