### ISSUE TITLE
[Occtax] Nom latin dans la liste des relevés

### ISSUE THREAD

**Issue by Vottana** [PnX-SI/GeoNature#2787]
Bonjour à tous, 

À la demande de certains collègues, je voulais mettre le nom latin à la place du nom vernaculaire dans la liste des relevés d'Occtax, mais dans le fichier occtax.config.toml, ce n'est apparemment pas possible ? Il n'y a que le taxon qui est disponible, qui renvoie le nom vernaculaire (ou latin s'il n' y a pas de noms français).

```
# Columns which are default display in the list
default_maplist_columns = [
    { prop = "taxons", name = "Taxon(s)" },
    { prop = "date_min", name = "Date début", max_width = "100" },
    { prop = "observateurs", name = "Observateur(s)" },
    { prop = "dataset_name", name = "Jeu de données" }
]

# Available columns which can be add manualy by user
available_maplist_column = [
    { prop = "altitude_max", name = "altitude_max" },
    { prop = "altitude_min", name = "altitude_min" },
    { prop = "comment", name = "Commentaire" },
    { prop = "date_max", name = "Date fin" },
    { prop = "date_min", name = "Date début" },
    { prop = "id_dataset", name = "ID dataset" },
    { prop = "id_digitiser", name = "ID rédacteur" },
    { prop = "id_releve_occtax", name = "ID relevé" },
    { prop = "observateurs", name = "observateurs" },
    { prop = "taxons", name = "taxons" }
]
```
Par ailleurs, le jeu de données ne renvoie rien, il est pourtant bien renseigné lors de la saisie, est-ce normal ? Que dois-je corriger dans ma configuration ?
![image](https://github.com/PnX-SI/GeoNature/assets/15034095/c04709f2-02f0-49fb-8f78-06db1cdef9d0)

Ces infos (nom latin et JDD) sont bien affichées dans la synthèse, donc ce n'est bien grave si je ne peux pas personnaliser la liste des relevés d'Occtax, mais si à tous hasard il y avait une solution pour ces 2 questions, je suis preneuse.
Merci d'avance et à bientôt,
Vottana

**Comment by camillemonchicourt** [comment]
Pour l'affichage des JDD dans la liste des relevés Occtax, je ne sais pas, je vois pas.
Car ça fonctionne aussi sur le serveur DEMO et production, et il n'y a pas eu de soucis identifié ou de correction sur le sujet.

Il faudrait voir si c'est un problème d'affichage avec des erreurs dans la console du navigateur ?
Ou un soucis si vous avez touché au fichier de configuration d'Occtax, avec une faute de frappe ou autre du genre ?

**Comment by Vottana** [comment]
Version GN 2.12.3
Merci pour vos retours rapide, ça fonctionne pour le nom latin, merci !
Pour le JDD, je ne vois pas où serait l'erreur, j'ai fait un copier-coller du fichier exemple et ça ne s'affiche toujours pas. Pas d'erreur dans la console mais j'avoue ne pas bien savoir où chercher dans cette console.
Ce n'est pas bien grave, car l'info est dans la synthèse, je ferme l'issue, je continuerai à chercher.  
Bonne journée !
