### ISSUE TITLE
Réinstallation de Geonature à partir d'une base de donnée existante.

### ISSUE THREAD

**Issue by JeromeMaruejouls** [PnX-SI/GeoNature#2788]
Bonjour à tous,

Voici le problème auquel je suis confronté : 
 - J'ai un Geonature fonctionnel en production en version 2.11.2 (avec module Monitoring et Dashboard).
 - Avant de lancer la mise à jour en 2.13, j'aimerai tester la procédure sur un serveur test. J'ai donc fait un backup de la bdd, et j'ai réinstallé Usershub et Taxhub dans les memes versions que ma prod. Tout fonctionne correctement.
 - Par contre, en installant Geonature (2.11.2), je rencontre une erreur sur le script 4 (install gn modules) lié à la migration alembic 2984569d5df6 (create occhab schema) : ResolutionError: No such revision or branch '2984569d5df6'
Si je fais un geonature db status, j'obtiens le même message. Cette migration dépend uniquement de f06cc80cc8ba (bdd en 2.7.5)

Si je fais un geonature db status sur mon serveur de prod, tout fonctionne correctement, et la base semble correcte. (je suis un peu perdu par contre entre le résultat de la commande db status, qui montre les migrations installées, et la table public.alembic_version qui contient beaucoup moins de migrations.

Avez-vous une idée de ce qui pourrait provoquer cette erreur ? Existe-t-il une autre méthode pour réinstaller un Géonature à partir d'une BDD existante ?

Merci d'avance pour vos conseils !

**Comment by gildeluermoz** [comment]
Est-ce qu'il ne faudrait pas plutôt faire un `install_all` en 2.11.2 puis quand tout fonctionne, tu remplaces la base par le dump de ta base de prod ?

**Comment by DonovanMaillard** [comment]
Oui la manipulation de Gil est bien plus simple et fonctionnelle, un install all, drop db  de la base vide et pg_restore de la base récupérée de la production , je l'ai fait à plusieurs reprises sans soucis. Bien penser aussi à installer les modules en plus de l'install all avant de restaurer la base (dans les mêmes versions que la prod bien entendu)

**Comment by JeromeMaruejouls** [comment]
Je confirme, tout fonctionne parfaitement après une réinstallation (avec création de DB) puis en remplaçant la base par celle sauvegardée ! Merci
