### ISSUE TITLE
Config fond carto MAPCONFIG.BASEMAP changement GeoPlateforme

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature#2789]
L'IGN est entrain de changer les URL des web services cartographiques dans le cadre de [sa migration vers la GeoPlateforme](https://geoservices.ign.fr/bascule-vers-la-geoplateforme). 

Ce changement implique potentiellement de modifier les URL utilisées dans le paramètre `[MAPCONFIG] BASEMAP` du fichier de configuration de GeoNature [geonature_config.toml](https://github.com/PnX-SI/GeoNature/blob/master/config/geonature_config.toml.sample).

Les exemples fournis dans le fichier de config [default_config.toml.example](https://github.com/PnX-SI/GeoNature/blob/master/config/default_config.toml.example#L211-L226) seront donc à modifier.

Ci-dessous un exemple de configuration possible avec les nouvelles URL GeoPlateforme :
```toml
[MAPCONFIG]
    BASEMAP = [
        {"name" = "OpenStreetMap",    "layer" = "//{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png", "attribution" = "&copy; OpenStreetMap", "maxZoom" = 22, "maxNativeZoom" = 19},
        {"name" = "OpenTopoMap",      "layer" = "//a.tile.opentopomap.org/{z}/{x}/{y}.png", "attribution" = "&copy; OpenTopoMap", "maxZoom" = 22, "maxNativeZoom" = 17},
        {"name" = "GoogleSatellite",  "layer" = "//{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}", "subdomains" = ["mt0", "mt1", "mt2", "mt3"], "attribution" = "&copy; GoogleMap", "maxZoom" = 22, "maxNativeZoom" = 22},
        {"name" = "IGN SCAN 25&reg;", "layer" = "https://wxs.ign.fr/<clef-api-ign>/geoportail/wmts?LAYER=GEOGRAPHICALGRIDSYSTEMS.MAPS&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}", "attribution" = "&copy; IGN-F/Geoportail", "maxZoom" = 22, "maxNativeZoom" = 18},
        {"name" = "IGN Ortho",        "layer" = "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&LAYER=HR.ORTHOIMAGERY.ORTHOPHOTOS&FORMAT=image/jpeg", "attribution" = "&copy; IGN", "maxZoom" = 22, "maxNativeZoom" = 19},
        {"name" = "IGN Cadastre",     "layer" = "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&LAYER=CADASTRALPARCELS.PARCELS&FORMAT=image/png", "attribution" = "&copy; IGN", "maxZoom" = 22, "maxNativeZoom" = 19},
        {"name" = "IGN Plan v2",      "layer" = "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&LAYER=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&FORMAT=image/png", "attribution" = "&copy; IGN", "maxZoom" = 22, "maxNativeZoom" = 19},
        {"name" = "BRGM Géologie", "url" = "https://geoservices.brgm.fr/WMS-C/?", "service" = "wms", "layers" = "GEOLOGIE", "attribution" = '&copy; BRGM - <a href="https://infoterre.brgm.fr/viewer/" target="_blank">BD Charm-50</a>'}
    ]
```

**Note sur l'exemple de config** : 
  * penser à modifier la valeur `<clef-api-ign>` pour l'accès au SCAN25. Pour l'instant le SCAN25 ne semble pas avoir d'URL de web service au format GeoPlateforme.
  * tous les fonds sont au format `WMTS` sauf le fond carto géologique "BD Charm-50" du BRGM au format `WMS-C`. Le problème du fond carto géologique, c'est l'accès à la légende. Un lien vers [l'outil carto InfoTerre](https://infoterre.brgm.fr/viewer/) a été rajouté sur l'attribution du fond. L'interface du BRGM permet d'accéder à une légende dynamique.
  * les paramètres `maxZoom` et `maxNativeZoom` permettent à Leaflet d'extrapoler les tuiles des zooms manquant du `maxNativeZoom` jusqu'au `maxZoom`.

**Comment by mvergez** [comment]
Merci beaucoup pour toutes ces infos @jpm-cbna !!!

**Comment by camillemonchicourt** [comment]
OK, merci pour ces éléments.
En effet, on pourrait déjà modifier les appels aux services IGN dans le fichier d'exemple car les nouvelles URL sont déjà fonctionnelles.
Il faudra surveiller ce qu'il se passe pour le SCAN25, car pour le moment cela reste l'ancienne URL.

Pour le fond géologique, c'est un peu différent car c'est une autre ressource et on ne la fournit pas actuellement par défaut, mais pourquoi pas l'ajouter si c'est une ressource classique et utile.

Merci.

**Comment by camillemonchicourt** [comment]
Pour le SCAN25, de nouvelles infos.
Il semble qu'il faudra bien modifier les URL dès cette fin d'année mais que l'outil pour demander des clés spécifiques ne sera pas encore en place, donc qu'il faudra une clé partagée en attendant : https://geoservices.ign.fr/actualites/2023-11-20-acces-donnesnonlibres-gpf

**Comment by edelclaux** [comment]
J'ai fait un ptit travail sur la gestion des basemaps/reflayers de la config: 
[PR 2844](https://github.com/PnX-SI/GeoNature/pull/2844)

L'idée est multiple: 
- mettre à jour les défault, example, etc. avec les nouvelles urls
- ajouter des 'preset' qui permettent d'encapsuler dans géonature les définitions de basemaps et ref_layers récurrents (osm, otm, ign, etc.). Et donc d'encapsuler, par exemple, la mise à jour des urls ign
- déplacer la responsabilité de l'uniformisation de la config du frontend vers le backend

A voir si ça vous convient à tout le monde

**Comment by TheoLechemia** [comment]
Pour le "en dur", je parlais des URL des preset. Par exemple dans le preset OSM il y a ça : `//{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png`. Pourquoi le fond `hot` plutôt qu'un autre ? De ce que je comprend, tu peux aussi surcoucher ce paramètre. Mais je pense à l'utilisateur lambda qui ne fait pas de code, il faut : 
- qu'il comprenne le concept des "preset"
- qu'il connaisse les preset à disposition
- qu'il comprenne que certains paramètre sont surcouchable 
- qu'il connaisse la liste de ces paramètre surcouchable
C'est un mécanisme un peu "nouveau", qui diffère un peu avec l'existant qui consiste à regardé quel sont les paramètre dispo dans le config.example et le copié / coller dans la conf.
Je trouve que ça ajoute un peu de "magie" qui peut être à la fois confortable et paumatoire pour l’utilisateur final

**Comment by edelclaux** [comment]
Comme ça ne semblait pas convenir à tout le monde, j'ai fermé la PR [2844](https://github.com/PnX-SI/GeoNature/pull/2844) et ouvert une beaucoup plus minimaliste qui met à jour le strcit minimum --> [PR 2859](https://github.com/PnX-SI/GeoNature/pull/2859)

**Comment by gildeluermoz** [comment]
Hier, sur tous les serveurs que je gère, les fonds plan et ortho ne fonctionnaient plus. Etonnant car l'IGN parle d'une bascule au 15 mars et d'une redirection d'URL au moins temporaire. https://geoservices.ign.fr/bascule-vers-la-geoplateforme
Etonnant aussi, ça ne fonctionnait plus sur TOUTES les instances GeoNature mais ça fonctionne sur les atlas. Je n'ai pas creusé pour identifier une différence. Peut-être parce que les urls GeoNature sont derrières une authentification et pas l'atlas.
En basculant les URL sur la geoplateforme, ça fonctionne pour plan et ortho.

Les scans 25 ne fonctionnent plus non plus. Il est noté qu'un nouveau dispositif d'authentification doit être mis en place mais que l'ancien système doit continuer de fonctionner, or ça ne fonctionne plus. Idem, je n'ai pas trouvé de syntaxe avec la clé partagée (ign_scan_ws).
A priori le nouveau système d'authentification n'est pas encore super fonctionnel. Voir l'info donnée par @camillemonchicourt plus haut.

Ca ne fonctionne plus sur occtax-mobile. J'ai tenté plusieurs syntaxe d'écriture des urls geoplateforme, sans succès. 

**A noter** ici : https://geoservices.ign.fr/bascule-vers-la-geoplateforme

> L’usage du protocole HTTPS / TLS 1.2 est imposé pour accéder aux géoservices, sans exception possible

Est-ce bien le cas pour Occtax-mobile ?

**Comment by gildeluermoz** [comment]
Syntaxe pour le scan 25 avec la clé provisoire : 
[[MAPCONFIG.BASEMAP]]
    name = "SCAN25 IGN"
    url = "https://data.geopf.fr/private/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&apikey=ign_scan_ws&LAYER=GEOGRAPHICALGRIDSYSTEMS.MAPS&EXCEPTIONS=text/xml&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&FORMAT=image/jpeg&STYLE=normal"
    maxZoom = 22
    maxNativeZoom = 18
    attribution = "&copy; IGN-F/Geoportail"

Si qq'un a une syntaxe pour ortho et plan sur mobile je suis preneur.

**Comment by jacquesfize** [comment]
Bonjour @gildeluermoz 

Les configurations de BASEMAP  par défaut ont été mise à jour pour la 2.14. Tu peux les trouver ici : https://github.com/PnX-SI/GeoNature/blob/0fb7d7639b3e396db22d73b4b4635fc19e8fe690/config/default_config.toml.example#L207

**Comment by gildeluermoz** [comment]
Merci @jacquesfize 
Ca correspond à ce que j'ai mis en place et qui fonctionne.
Par contre, est-ce que tu as essayé l'accès à ces flux de la geoplateforme sur occtax-mobile ?

**Comment by camillemonchicourt** [comment]
En effet, il y a un incident en cours sur les anciens flux (http://wxs.ign.fr) : https://geoservices.ign.fr/actualites/2024-28-02-actu-incident

**Comment by jacquesfize** [comment]
> Merci @jacquesfize 
> 
> Ca correspond à ce que j'ai mis en place et qui fonctionne.
> 
> Par contre, est-ce que tu as essayé l'accès à ces flux de la geoplateforme sur occtax-mobile ?

Pas encore 😔

**Comment by edelclaux** [comment]
> Merci @jacquesfize Ca correspond à ce que j'ai mis en place et qui fonctionne. Par contre, est-ce que tu as essayé l'accès à ces flux de la geoplateforme sur occtax-mobile ?

Salut ! Est-ce que tu as fini par trouver une syntaxe pour IGN ortho et plan sur mobile ? 
Je suis en plein dedans, et je n'arrive qu'à faire fonctionner l'ancienne URL.
