### ISSUE TITLE
Formulaire: récupérer les valeurs de la dernière occurrence

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#279]
Quand on enchaîne les saisies d'occurrence il serait intéressant de récupérer la technique d'obs et/ou la méthode d'obs, le stade de vie etc...

**Comment by gildeluermoz** [comment]
Oui et non.
Oui si ça correspond au besoin de l'utilisateur.
Non si ce n'est pas le cas (avec risque de forçage de l'erreur).

Proposition, positionner une sorte de verrou à coté de chaque champ où ça peut être pertinent. Si ce verrou est activé ça duplique la valeur. Sinon, on met la valeur par défaut ou rien s'il n'y en pas.

A voir si ce comportement se reproduirait d'un relevé à l'autre. En gros, à trimbaler avec la session de l'utilisateur ou non.

**Comment by camillemonchicourt** [comment]
Ça ramène aussi au débat de savoir si la méthode d'observation ne devrait pas plutôt être au relevé. C'est sans fin et y aura jamais de réponse VRAIE.

**Comment by DonovanMaillard** [comment]
Exact mais la norme sinp répond à ça a mon sens : c'est à l'occurrence. La question est juste de faciliter la saisie. Sachant que cette "mémoire" permet quand même de changer la valeur et donc d'avoir plusieurs methods dans un relevé

**Comment by camillemonchicourt** [comment]
Dans la version 2.5.0, un outil de conservation des infos saisies précédemment dans les différents champs a été développé et est activable avec un paramètre dédié : https://github.com/PnX-SI/GeoNature/issues/692
