### ISSUE TITLE
état du currentModule lors de la navigation vers la page d'accueil en appuyant sur précédent 

### ISSUE THREAD

**Issue by edelclaux** [PnX-SI/GeoNature#2795]
**Version**
Version: GeoNature version [2.13.3](https://github.com/PnX-SI/GeoNature/releases)

**Description du bug**
1) Se rendre sur la page d'accueil
2) Cliquer sur un module, n'importe lequel
3) Cliquer sur précédent
![image](https://github.com/PnX-SI/GeoNature/assets/150020787/2a72224b-8d8f-49d5-a70e-64ad0699c53d)

**Comportement attendu**
On s'attend à ce que l'accès à la page d'accueil via un bouton précédent mette le currentModule à null

**Comment reproduire**
cf Description.

**Remarque**
Les modules ne sont pas concernés, car ils s'appuient sur ```canActivate: [ModuleGuardService]``` qui vérifie et ajuste l'état du currentModule

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.14.0
