### ISSUE TITLE
Trier "Mes lieux" par ordre alphabétique 

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#2804]
Bonjour, 

On m'a demandé s'il était possible de trier la liste de "mes lieux" par ordre alphabétique pour faciliter la sélection quand la liste est longue. 

J'ai fait une (modeste) PR en ce sens.

**Comment by jacquesfize** [comment]
Bonjour @DonovanMaillard , tu as un lien vers la PR ?

**Comment by jacquesfize** [comment]
Lien vers la PR https://github.com/PnX-SI/GeoNature/pull/2805

**Comment by camillemonchicourt** [comment]
Fait dans la 2.13.4.
