### ISSUE TITLE
Pas de visualisation des données intégrées via postgreSQL

### ISSUE THREAD

**Issue by marie-laure-cen** [PnX-SI/GeoNature#2807]
**2.13.0 / 2.13.3**
Version de GeoNature affectée par le bug.

**Description du bug**

J'ai encore un petit problème désolée 😅

J'ai réalisé des scripts pour transformer et injecter des données SICEN directement dans la base de données postgreSQL de GeoNature. Lors de l'intégration des données de la première antenne (~105 000 données), tout s'est bien passé (version GeoNature 2.13.0). Les données apparaissent, sont requêtables dans la synthèse etc.
J'ai réalisé le même type de scripts d'intégration avec la version 2.13.3 (~400 000 données) pour la seconde antenne. Arrivé à la fin de l'intégration des dénombrements, ces derniers ne s'affichent pas dans GeoNature dans OccTax alors que les relevés et les occurrences oui. Les données ne sont pas requêtables dans la Synthèse. L'ajout du dénombrement a bien l'air d'apparaître dans la couche gn_commons.t_history et quand je fais des requêtes postgresql, les données sont bien là.

Différence entre les 2 intégrations :

- je n'ai pas pu ajouter le dénombrement tout de suite après les occurrences : il s'est passé 3j entre les l'intégration des occurrences et celle des dénombrements (au lieu d'une nuit lors de la première intégration).
- cette fois ci il y a plusieurs dénombrements (mâle, femelle...) sur certaines occurrences alors que les données précédentes étaient plus "simple" (1 occurrence = 1 dénombrement).

Est ce que c'est une question d'opération programmée ou autre qui ne s'est pas encore faite ? Est ce que comme il y a eu un laps de temps important, la synthèse s'est figée sur un statut sans dénombrement? Est ce que c'est juste la mise en cache ou autre qui est plus longue vu le nombre de données?

**Comment by camillemonchicourt** [comment]
Pour info, il y a 2 exemple partagés d'import de données SICEN vers GeoNature : 
- https://github.com/PnX-SI/Ressources-techniques/tree/master/GeoNature/migration/sicen
- https://github.com/PnX-SI/Ressources-techniques/tree/master/GeoNature/migration/sicen_to_occtaxV2

Le fait que les dénombrements aient été importés dans un second temps ne devrait pas être un soucis. 
Il y a bien un trigger qui est déclenché quand une donnée est insérée dans la table `pr_occtax.cor_counting_occtax` : `tri_insert_synthese_cor_counting_occtax`, qui lance la fonction `pr_occtax.insert_in_synthese`, etc etc...

Il faudrait analyser en détail votre procédure et vérifier les tables dans Occtax pour voir si tout a bien été intégré comme il faut. 
Mais là, ça dépasse le périmètre de GeoNature lui-même. C'est plutôt la gestion qu'en fait chacun.
Ce qui est dans le périmètre actuel de GeoNature est : Importer des observations en Synthèse uniquement avec le module IMPORT.
Si vous voulez importer manuellement des observations directement dans le module Occtax, là c'est à chacun de voir, et c'est plus complexe.

**Comment by marie-laure-cen** [comment]
Merci. C'est en effet c'est un problème d'injection dans la synthèse même si le trigger est activé... les données n'y ont pas été ajoutées

**Comment by marie-laure-cen** [comment]
J'ai réinjecté les données par lots plus petits et ça fonctionne => ça doit être un problème de capacité de traitement de notre installation
