### ISSUE TITLE
[OCCTAX] Problème de chargement de liste de JDD lors de la création d'un relevé 

### ISSUE THREAD

**Issue by andriacap** [PnX-SI/GeoNature#2815]
**Version**
Version de GeoNature affectée par le bug : 2.13.3 (pas testés les autres versions)

**Description du bug**

Dans le cadre d'une prestation avec l'ARB IDF , il a été remonté une erreur concernant la liste des jdd affichés dans le formulaire du relevé occtax. La liste des jdd affichés concerne l'ensemble des JDD (soit basé sur les permissions associés au Module METADATA ALL Lecture --> tous les JDD) alors que les permissions censés être affichés sont ceux liés aux permission OCCTAX ALL Création --> les données de mon organismes.

**Comportement attendu**
Le comportement attendu serait dans le cas de figure présenté ci dessus de n'afficher les JDD n'appartenant qu'à ceux de l'organisme de l'utilisateur connecté et non l'ensemble des JDD.

**Comment reproduire**
Au niveau du module des permissions dans Admin  --> Il est possible d'observer le problème en appliquant les permissions suivantes à un utilisateur : 
- Module (METADA) , Objet (ALL), Action (R), Label ( lire les métdonnées) , portée (tout)
- Module (OCCTAX), Objet (ALL), Action (C), Label (Créer des relevés), portée (de mon organisme)

Au niveau du module OCCTAX --> se rendre sur le module et cliquer sur "Ajouter un relevé" . Voir la liste des JDD (tous les jdd affichés)

**Résolution de l'erreur**

Dans le fichier ici : 

https://github.com/PnX-SI/GeoNature/blob/22b577a5809a177d6ff75d0bb838dc8060d7a304/frontend/src/app/GN2CommonModule/form/datasets/datasets.component.ts#L88-L104

L'observable n'est pas associée à une `Subscription` et du coup n'est pas `unsubscribe` lorsque le composant est "détruit" . Du coup ce qui se passe c'est que la requête qui appel la liste des JDD (`POST /meta/datasets?orderby=dataset_name`) sur la base des permissions OCCTAX / ALL / C / données de mon organisme est surcouché par la requête qui est passée sur les permissions de METADATA/ALL/R/ Tout.

Pour palier à ce problème on ajoute `ngOnDestroy` dans lequel on unsubscribe la "Subscription" à  l'Observable .

Je vais créer une PR pour résoudre ce bug.

**Comment by andriacap** [comment]
Salut @TheoLechemia  ,

Merci pour ton retour . J'ai bien vérifié les droits  (voir image ci dessous) 

![Capture-20231204123007-1896x905](https://github.com/PnX-SI/GeoNature/assets/111564663/afe617ec-38e2-4d81-993a-35e67409fa00)

J'avais du mal a reproduire le problème de l'ARB égalemernt mais en réalité le problème survient si la requête sur les droits liés à la première requête (`POST /meta/datasets?orderby=dataset_name` se fini après celle lancée pour lire les droits de création dans occtax.)

En mode debug , si tu tentes à différentes reprise tu auras un moment où la liste des jdd sera l'ensemble des jdd (et tu verras que la  requête `POST /meta/datasets?orderby=dataset_name` s'est éxécuté deux fois avec celle qui appelle l'ensemble des jdd qui surcouche l'autre requête qui renvoie normalement les jdd que de son organisme ). Tu peux mettre un breakpoint dans le code ici et  te rendre coté front sur la page de formulaire de relevé Occtax : 

https://github.com/PnX-SI/GeoNature/blob/22b577a5809a177d6ff75d0bb838dc8060d7a304/frontend/src/app/GN2CommonModule/form/datasets/datasets.component.ts#L88-L104

Tente aussi en changeant les droits et en remettant les droits qui génère le bug. 

Ci dessous les images avec la liste des jdd renvoyées (dans le premier cas avec seulement les jdd de l'organisme, et dans l'autre cas l'ensemble des jdd). Et pourtant les permissions sont les mêmes 

![Capture-20231201171450-1039x909](https://github.com/PnX-SI/GeoNature/assets/111564663/fe5f2d5d-79b1-4c5a-8c1c-7232fc6c48a9)
![Capture-20231201171358-1057x905](https://github.com/PnX-SI/GeoNature/assets/111564663/9e10bc95-3e17-47e9-b2a1-15f85d6c1d97)


Merci à toi pour ton retour

**Comment by TheoLechemia** [comment]
j'arrive pas à reproduire, même en mettant un time.sleep sur la route des JDD dans le cas ou elle est appelé par le module métadonnée. 
A mon avis ça vient de l'input `creatableInModule` du composant datasets qui ne doit pas être mis au moment l'appel.
Est ce que tu arriverais à voir le contenut du POST (payload) pour les deux requêtes qui tu vois passer (et dans le cas ou tu as le bug)

**Comment by andriacap** [comment]
Je pense savoir pourquoi tu arrives pas à reproduire le bug , car tu dois peut être avoir peu de données  (JDD, utilisateurs etc) comparé à l'ARB-IDF ? 
Le corps des requêtes `POST /meta/datasets?orderby=dataset_name` qui se lancent (avec leur temp d'éxécution) : 
1. corps de la 1ère requête lancée : 
   * {"module_code":"OCCTAX"}  
    * Durée : 7 sec
2. corps et temps de la 2nde requête lancée une fois sur le tab :
    * {"active":true,"module_code":"OCCTAX","create":"OCCTAX"}  
    * Durée : 611ms
    
 Et d'ailleurs je remarque que systématiquement le bug survient lorsque la première requête est beaucoup trop longue par rapport à la deuxième requête. La première requête peut aller jusqu'à 12sec de chargement (l'autre est plus rapide, de l'ordre de 500ms à 2sec)

**Comment by andriacap** [comment]
Pour revenir sur le `ngOnDestroy` , lorsqu'il est mis en place il est permet bien de stoper la première requête `POST /meta/datasets?orderby=dataset_name` dès lors qu'on va sur le tab `Releve` qui lance la deuxième requête `POST /meta/datasets?orderby=dataset_name` avec le corps requête : 
`{"active":true,"module_code":"OCCTAX","create":"OCCTAX"}`

**Comment by TheoLechemia** [comment]
Ok je viens de comprendre.
Le problème vient de ce store : https://github.com/PnX-SI/GeoNature/blob/master/frontend/src/app/GN2CommonModule/form/datasets/dataset.service.ts qui est utilisé dans le composant ici : https://github.com/PnX-SI/GeoNature/blob/master/frontend/src/app/GN2CommonModule/form/datasets/datasets.component.html#L4

Le premier appel à `/meta/datasets?orderby=dataset_name` vient de la page carte/liste d'occtax qui charge pour les filtres la liste des JDD accessible en lecture à l'utilisateur.
Ensuite tu va sur la page du formulaire, le second appel est fait, et il finit avant le second. Donc le store contient les données du premier..
On avait dû faire ce store pour cacher des données, mais il est inopérant car on veut des listes différentes suivant les cas donc il faut le virer.
Le ngDestroy fonctionne car quand tu quitte la page carte liste, il annule l'appel à la route donc il ne remplit pas le store. En virant le store on aura plus besoin du ngDestroy (car de toute façon ça ne soulagerait pas le serveur car la requête est déjà lancée)
Il faudrait aussi voir pourquoi la route met 12sec à répondre, il y a des truc à améliorer de ce côté là

**Comment by andriacap** [comment]
Super merci pour ta réponse. J'ai mis à jour la PR liée ( #2816 ) 

Pour le temps de requête ça fait effectivement partie des requêtes à améliorer en terme de performance .. On en a listé d'autre notamment dans la synthese .

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.13.4.
