### ISSUE TITLE
EXPORT - Schéma dédié dans la BDD

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#282]
Les vues devraient être dans un schéma dédié. Idem pour le SQL de création des vues, dans un fichier SQL dédié.

**Comment by TheoLechemia** [comment]
Comme les exports dépendent de chaque module, qui ne font pas nécessairement partir du "coeur", ça me paraissant plus logique de mettre les vues dans leur schéma propre. Et on aurait une table dans un schéma "export" qui liste toutes les vues en fonction des modules installés.

**Comment by gildeluermoz** [comment]
Oui mais attention à la rupture de modularité : ne pas mettre des vues utilisant un schéma d'un module dans le core. Exemple pour l'export du pr_contact, faire un export_contact.sql et n'utiliser dans ce fichier que les schémas du core et celui du pr_contact.
Si on export.sql est crée dans le core, il ne doit pointer sur aucun schéma des modules.

**Comment by gildeluermoz** [comment]
Oui Théo c'est ça, on rédigeait en même temps. 
Ça n’empêche pas de faire un fichier ``export_contact.sql`` à mettre dans le module contact.

**Comment by camillemonchicourt** [comment]
Actuellement on exporte les données à partir de ce qui est dans le contact, mais à terme on tapera directement dans la synthèse. 
L'export SINP occurrence de taxon se fera directement dans la Synthèse. 
Il est générique et fourni par défaut dans GN, libre à chacun de l'utiliser/l'activer ou non.

**Comment by camillemonchicourt** [comment]
OK et le fichier `export_contact.sql` créé une vue qui est bien dans le schéma EXPORTS.

**Comment by gildeluermoz** [comment]
Oui on peut. Dans ce cas il faut faire un ``export.sql`` dont le role unique à ce stade sera de créer un schéma gn_exports.
par contre si on fait ça, c'est comme pour les valeurs par défault, si tu désinstalles un module faudra trouver les vues à supprimer dans ce schéma. Donc ???

**Comment by camillemonchicourt** [comment]
Yes ça c'est le problème du gars qui gère son GeoNature et sa cohérence. 
Mais selon moi c'est mieux de regrouper toutes les vues dans un même schéma. 
Désinstaller un module, je suis pas sur que ça arrive, et c'est un truc d'admin.

**Comment by gildeluermoz** [comment]
niet ! C'est pas une raison pour volontairement compliquer le travail des admin.

**Comment by camillemonchicourt** [comment]
OK donc pour le moment on laisse les vues dans les schémas des modules concernés. 
A voir si on créé un schéma EXPORTS qui ne contiendrait que des trucs génériques et la table qui liste les vues/exports.

**Comment by gildeluermoz** [comment]
On résume
* Un schéma ``gn_exports`` avec un fichier ``exports.sql``. Dans ce schéma les utilisateurs admin feront leur tambouille.
* On laisse les vues des modules dans les modules, même si c'est une vue pour l'export. Si elle utilise une table du module, elle ne doit pas être dans le core ou un autre module pour des raisons de modularité et de simplification de la désinstallation du module.
* On créé dans le schéma ``gn_exports`` une table ``t_config_exports`` qui liste les vues et permet de les retrouver avec  champ ``schema``, ``view_name`` + des champs pour gérer les droits d'accès (groupes, users, organismes, etc...) ainsi que des champs ``label_export_button``, ``desc_export`` pour le nom des boutons, la description de l'export, etc...
* L'export occurrence de taxons, livré par défaut, sera basé sur la synthèse uniquement et sera au standard SINP.

**Comment by gildeluermoz** [comment]
DONE : bf85ad9ebef2f89eae52626b140cbbcfe0cfaf8b
