### ISSUE TITLE
[SYNTHESE] [VALIDATION] Problème d'affichage lors de la désactivation des profils de taxons

### ISSUE THREAD

**Issue by ahurabielle-picnat** [PnX-SI/GeoNature#2820]
**Version**
2.12.3

**Description du bug**
Si on désactive les profils de taxon, le nom (scientifique et vernaculaire) du taxon n'apparaît plus dans les informations du taxon, à la fois sur la synthèse et la validation.
![image](https://github.com/PnX-SI/GeoNature/assets/114409810/43d99842-d845-4c91-9e70-3e3e5f1c15e5)

**Comportement attendu**
Avoir le nom scientifique et vernaculaire qui s'affiche dans les deux cas
![image](https://github.com/PnX-SI/GeoNature/assets/114409810/ff93a97a-471e-4a4e-8c62-870fdadd7ff1)

**Comment reproduire**
- Désactiver le profil de taxon (ajout de l'option `ENABLE_PROFILES = false` dans la partie `[FRONTEND]` du fichier config `geonature_config.toml`
- Aller dans la synthese et cliquer sur le `i` pour ouvrir une fiche d'information sur une observation.

**Problème identifié**
Dans le fichier `frontend/src/app/shared/syntheseSharedModule/synthese-info-obs/synthese-info-obs.component.html`, ligne 38, un test est fait sur `config.FRONTEND['ENABLE_PROFILES']`, probablement à cause du lien (page `/synthese/taxon /...` )
A mon sens, il faudrait retirer ce if et revoir ce code.

**Comment by camillemonchicourt** [comment]
En effet il faudrait contrôler ce paramètre uniquement pour mettre ou non le lien sur le nom du taxon, mais pas pour afficher ou non le taxon...

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.14.0
