### ISSUE TITLE
[OCCTAX] Inversion de valeurs par défaut sur les dénombrements

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature#2822]
**Version**
 2.13.3 (pas testés les autres versions)

**Description du bug**
Il y a une inversion des valeurs par défaut sur les champs `id_nomenclature_sex` et `id_nomenclature_obj_count` de la table `pr_occtax.cor_counting_occtax`

**Logs**
![image](https://github.com/PnX-SI/GeoNature/assets/66769358/d971ca6a-bf33-4cb3-a749-ceefe15237ae)

Je ne sais pas à quelle version est apparu le bug

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.14.1
