### ISSUE TITLE
Supprimer la lib ngx-mat-select-search#inputs

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#2827]
Cet lib https://github.com/bithost-gmbh/ngx-mat-select-search#inputs est utilisé dans le frontend pour faire des `mat-select` avec recherche.
Il est possible de faire la même chose sans utiliser de librairie externe : 
https://stackoverflow.com/questions/48442794/implement-a-search-filter-for-the-mat-select-component-of-angular-material

Voir #2826

**Comment by camillemonchicourt** [comment]
Fait dans la 2.14.1.
