### ISSUE TITLE
BDD et schéma PUBLIC

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#283]
Il est peut-être inévitable d'avoir des éléments spécifiques à GeoNature dans le schéma `public` mais si c'est possible ce serait mieux de ne rien y ajouter de spécifique à GeoNature pour la portabilité de la BDD. 

Du coup cette fonction pourrait plutôt aller dans le schéma `meta` : https://github.com/PnX-SI/GeoNature/blob/develop/data/core/public.sql#L14 ?

**Comment by amandine-sahl** [comment]
C'est vraiment une fonction de bas niveau qui concerne potentiellement tout les schémas et qui est très bien dans public à mon avis

**Comment by camillemonchicourt** [comment]
Si on colle des choses spécifiques dans le schéma `public`, ça pose des problèmes importants de portabilité de la BDD, notamment si on souhaite l'intégrer dans une BDD existante. 
Si on regarde les contraintes techniques de maintenance/hébergement de certaines structures, ils demandent notamment à ce qu'il n'y ait rien de spécifique dans le schéma `public`. 
Pour moi ça colle bien avec `meta`, c'est une fonction lié aux métadonnées des données, de tout schéma confondu en effet, c'est pas un problème. C'est dommage de noyer cette fonction spécifique dans toutes les fonctions natives de PG du schéma `public` et du coup de rendre spécifique le schéma `public` juste pour une fonction.

**Comment by gildeluermoz** [comment]
1 - Cette fonction n'a rien de spécifique à ``meta``, elle est utilisée partout avec les ``meta_create_date`` et ``meta_update_date`` de n'importe quelle table, potentiellement de tous les schémas.
2 - Comme est elle utilisée partout, lors de la création de la base, la première fois qu'elle est "appelée" lors de la création d'une table, il faut que le schéma qui l'héberge existe (et évidement qu'elle soit créées). Du coup faut la mettre dans le premier schéma qu'on créé. Ce schéma ne sera pas forcement le plus logique pour l'héberger (le premier schéma créé après ``utilisateurs`` et ``taxonomie`` est ``ref_nomenclatures``...). Sinon il faut réorganiser totalement le mode de découpage et d'appel des scripts sql dans le ``instal_db.sh``.
Je vois bien le soucis, purement de principe, de ne pas la mettre dans public. Sur le plan technique et maintenance, je ne vois pas trop. Nous pourrions par contre retenir un principe utilisé antérieurement : préfixer aussi les fonctions applicatives du schéma ``public`` par un ``app_`` ou un ``gn_``
Sur une fonction aussi générique, sa présence dans public ne me gène pas plus que ça. En outre, son déplacement peut constituer un travail important.

**Comment by camillemonchicourt** [comment]
Oui oui je vois bien que cette fonction est utilisée dans tous les schémas. De la même manière que les fonctions géographiques de `ref_geo` ont vocation à être appelées depuis d'autres schémas. 
La date étant une logique de métadonnées, je verrai bien cette fonction dans `meta`. 
OK je capte le problème d'ordre de création des schémas. Ça a du sens de créer le schéma `meta` avant les schémas des protocoles. 
Le principe concerne la lisibilité générale de la BDD mais aussi sa portabilité. Par exemple pour ceux qui voudraient installer la structure de GeoNature dans une BDD existante. C'est pour ça que le BRGM par exemple demande à ce qu'il n'y ait rien de spécifique dans le schéma `public`. C'est assez sain en terme de lisibilité mais aussi en terme technique. 
C'est dommage de casser ce principe juste pour une fonction qu'on colle dans `public` mais en effet il y a plus grave et plus prioritaire...
A minima, la préfixer de `gn_` serait déjà un bon point.

**Comment by gildeluermoz** [comment]
Si tu installes dans une BDD existante, ça va juste ajouter une fonction dans public. Techniquement ce n'est pas un soucis. Effectivement faut savoir que la fonction en question est une fonction applicative. Mais la portabilité est un faux argument. Tu ne déplaces pas un schéma d'une base à l'autre comme ça. Tous les schémas ont des dépendances vers les autres et il faut casser des FK, des vues, les reconstruire, etc... Donc écrire un script dédié à ça. Idem si tu veux créer un nouveau GeoNature dans une base existante, c'est plus facile mais il faudrait aussi créer un script pour ça ou adapter l'existant pour qu'il fasse qq vérifs avant de lancer les SQL. Dans les deux cas, tu lances le ``public.sql`` comme les autres.

``gn_meta`` utilise ``ref_nomenclatures`` donc tu dois les créer dans l'ordre prévu. 
Maintenant avec un peu de travail, on peut revoir la chose. Créer tout ce qui est méga générique dans un script ``init.sql`` comme tous les ``CREATE SCHEMA...`` + cette fonction dans le schéma ``gn_meta``. Mais faut revoir tous les scripts et y supprimer les ``CREATE SCHEMA...``.
Ceci rend aussi moins "packagé" la création des schémas.

**Comment by camillemonchicourt** [comment]
Maintenant qu'on a le schema gn_commons, si cette fonction est toujours utilisée, on peut la basculer du schema public et la mettre dans gn_commons où on elle a toute sa place et on l'identifiera mieux.

**Comment by camillemonchicourt** [comment]
Je crois qu'on peut supprimer le fichier ``data/public.sql`` (https://github.com/PnX-SI/GeoNature/blob/develop/data/core/public.sql) car la fonction est maintenant dans le schéma ``gn_commons`` : https://github.com/PnX-SI/GeoNature/commit/92b707e9acb16951027ab048251ac5dc09d66e39 
Mais pas certain alors je vous laisse vérifier.

**Comment by camillemonchicourt** [comment]
@TheoLechemia ?

**Comment by TheoLechemia** [comment]
La fonction était encore utilisée. 
On la remplace par la fonction dans gn_commons et on supprime le fichier public.sql : https://github.com/PnX-SI/GeoNature/commit/db494f43476183dc4116da573f95b0ca0e829e81

**Comment by camillemonchicourt** [comment]
En fait, on fait un retour en arrière car on fait une confusion entre 2 fonctions : https://github.com/PnX-SI/GeoNature/commit/ced6c7d1e6d938d953475ae5dcf3578d75400d56

- ``gn_commons.fct_trg_log_changes()`` permet de garder l'historique des modifications sur une donnée et d'en stocker le détail dans ``gn_commons.t_history_actions``. Nécessite de déclarer la table à historiser dans ``gn_commons.bib_tables_location``
- ``public.fct_trg_meta_dates_change()`` permet de remplir les champs date ``meta_create_date`` et ``meta_update_date`` de tables pour lesquelles on souhaite calculer automatiquement la date de création et de dernière mise à jour. Nécessite de déclarer un trigger sur les tables souhaitées qui exécute cette fonction. Utilisé sur les métadonnées (CA et JDD), la synthèse, les nomenclatures et le référence géographique (``ref_geo``)

**Comment by camillemonchicourt** [comment]
Oui c'est ça, c'est complémentaire et c'est 2 manières d'avoir des infos sur les données. 

Reste aussi la question de la dépendance des schémas et l'idée évoquée d'intégrer la fonction pour gérer les meta_date_update et meta_date_create dans chaque schéma de référentiel pour qu'ils soient bien indépendants. 

Mis de côté pour l'instant dans le ticket https://github.com/PnX-SI/GeoNature/issues/374
