### ISSUE TITLE
Export Occtax : champs additionnels vides

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#2837]
**Version**
2.13

**Description du bug**
La colonne `additional_data` des exports d'occtax est vide si un des champs additionnel du relevé / occurrence ou dénombrement est vide.
C'est cette ligne qui pose pb : 
`   (occ.additional_fields || rel.additional_fields) || ccc.additional_fields AS additional_data`
-> `NULL || {"test": 1} || {"test2": 2} => NULL`. Elle devrait renvoyer `{"test": 1, "test2": 2}`
Il faut vérifier si chaque champs n'est pas NULL et le remplacer par un json vide si c'est le cas

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.15
