### ISSUE TITLE
[Metadonnées] - Absence du type de financement

### ISSUE THREAD

**Issue by pierre56** [PnX-SI/GeoNature#2840]
**Version**
2.13.4

**Description du bug**
 Absence du type de financement dans la page de métadonnées (CA et JDD)

**Comportement attendu**
 Affichage du type de financement dans la page de métadonnées dans sa section.

**Comment reproduire**
Aller sur le module métadonnées et sélectionner un CA puis JDD.
L'information est présente dans le formulaire mais non affichée via l'interface dans la fiche descriptive.

Exemple avec geonature démo :
https://demo.geonature.fr/geonature/#/metadata/af_detail/132
![image](https://github.com/PnX-SI/GeoNature/assets/26764293/74651578-9655-4b5e-a80a-8574d52eaf46)
![image](https://github.com/PnX-SI/GeoNature/assets/26764293/4c562131-179a-49e1-a5e6-f85ebc91ccca)
 (pareil pour le JDD)

**PR associée**
https://github.com/PnX-SI/GeoNature/pull/2838

**Rendu**

![image](https://github.com/PnX-SI/GeoNature/assets/26764293/917c81ca-2a06-488e-a571-2162a34f46a8)

**Remarque**

 j'ai mis le type de financement en avant dernier, après les infos acteurs et avant les mots clés car ça me paraissait cohérent. C'est une information importante pour les collègues donc il faut qu'elle soit facile a trouver.
 
En amélioration future possible, mes collègues me demandent de pouvoir les discriminer facilement.
Donc je me disais que ça pourrait être bien d'avoir : 
un affichage "mode financement" activable sur la page d'accueil du module Metadonnées avec un code couleur
vert = public
jaune = mixte
rouge = privé

Mais la PR répond au besoin initial d'avoir l'information sans avoir les droits de modification du CA/JDD pour ouvrir le formulaire.

Merci

**Comment by marie-laure-cen** [comment]
En lien, il manque également dans l'affichage des métadonnées la précision sur le territoire

![erreur_geographie](https://github.com/PnX-SI/GeoNature/assets/143165944/f02efb7d-2c8f-4c9e-9eb2-e0154ee2cbb1)

![erreur_geographie2](https://github.com/PnX-SI/GeoNature/assets/143165944/c7527eb9-66b5-4d65-bc6e-bbe7b908011c)

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.14.0
