### ISSUE TITLE
proxy error 502 lors de l'affichage des données d'une espèce

### ISSUE THREAD

**Issue by Aurelien-Cheylan** [PnX-SI/GeoNature#2843]
**Version**
2.0.1

**Description du bug**
Bonjour, 
Sur une page espèce, ici pour la loutre, les données sont traitées du côté des graphs et stats mais aucune donnée ne s'affiche sur la carte. J'ai une erreur proxy pouvez m'aider,
Merci,
Ci-dessous le message d'erreur 
XHRGET
http://www.observatoire-mammiferes.fr/atlas/api/observationsMaille/60630
[HTTP/1.1 502 Proxy Error 91487ms]

**Comportement attendu**
Affichage des données de la loutre
Les données s'affichent pour l'ensemble des espèces sauf la loutre.

**Comment reproduire**
Se rendre sur cette page
http://www.observatoire-mammiferes.fr/atlas/espece/60630

Bonne journée, bonnes vacances et bon Noël !

**Comment by gildeluermoz** [comment]
Il doit y avoir plus d'info dans les logs de l'atlas, a priori dans /var/log/geoanture-atlas.log
Il est préférable d'utiliser le dépot de geonature atlas https://github.com/PnX-SI/GeoNature-atlas pour les issues concernant ce dépôt.

**Comment by TheoLechemia** [comment]
Bonjour,
L'erreur 502 est un "timeout" du serveur. La requête met trop de temps à répondre pour le serveur.
Au vu du portail, cela peut venir du nombre trop important d'observations, ou d'une customisation du code par rapport à la version officielle... :innocent:

**Comment by Aurelien-Cheylan** [comment]
Bonjour,
Merci pour vos réponses. Désolé c'est la première fois que je post un message sur votre github. Je suis le nouveau geomaticien de la SFEPM. Il y avait déjà une instance de géonature dans la structure, qui a été un peu modifié. J'essaie de me dépatouiller. L'an dernier j'ai intégré beaucoup de données et maintenant je tente de mettre tout ça à jour sur le geonature atlas.
Le geonature atlas sur le lien observatoire des mammifères que j'ai posté précédemment n'est pas directement connecté à la base de données sur laquelle je travaille, mais c'est une mise à jour à partir de VMs qui reprennent le code sql officiel. 
Je suis débutant dans la navigation dans la partie backoffice de geonature. Est-ce que vous pouvez me dire plus précisément où je peux trouver les logs ? Je n'ai rien à l'emplacement "/var/log/geoanture-atlas.log" ou bien à quoi devraient ressembler ce fichier de log ?
ps : est ce que je ferme ce ticket et en ouvre un autre dans la section atlas ?
Aurélien

**Comment by camillemonchicourt** [comment]
OK en effet les réponses précédentes sont une confusion car ce dépôt est celui de GeoNature.
Votre soucis semble bien différent et au niveau de GeoNature-atlas, ce qui n'a rien à voir et doit en effet être discuté et analysé sur le dépôt de GeoNature-atlas.

GeoNature ne connait pas GeoNature-atlas, c'est GeoNature-atlas qui se branche sur GeoNature.

Pour les logs, il faut voir où ils sont rangés dans la documentation et le dépôt Github de GeoNature-atlas, et regarder sur le serveur qui héberge votre GeoNature-atlas et pas celui qui héberge votre GeoNature si ils sont sur des serveurs (ou VM) différents.
