### ISSUE TITLE
Langue de la documentation 

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/GeoNature#285]
Certain éléments de la documentation sont en Français et d'autre en Anglais

https://github.com/PnX-SI/GeoNature/blob/frontend-contact/docs/development.rst

Il serait bon de choisir un langage unique.
Merci

**Comment by camillemonchicourt** [comment]
On était 100% français dans la V1 avec un peu de franglais dans le code par ci par là. 
Dans la V2 on a mis en place le multilingue côté applicatif, il est géré aussi dans la BDD et on a traduit toute la BDD en anglais. 
Concernant la doc on aimerait basculer en anglais mais on ne veut pas non plus que ce soit un frein à faire de la doc pour ceux qui sont moins à l'aise avec l'anglais. 
Donc pour l'instant ça reste mixte avec volonté de basculer en anglais.
