### ISSUE TITLE
[OCCTAX] Enregistrement des champs additionnels

### ISSUE THREAD

**Issue by marie-laure-cen** [PnX-SI/GeoNature#2858]
**Version**
2.13.3

**Description du bug**
L'enregistrement des données dans certains champs additionnels semblent être découpés lettre par lettre si une valeur par défaut est imposée sans les guillements.
~~- L'affichage des valeurs pour les datalist et autres checkbox se font bien à la saisie et mais pas à la lecture des données sur les relevés et les occurrences (je n'ai pas regardé comportement dans les dénombrements) : la valeur affichée est value et pas label comme à la saisie.~~

![champs_addi_bug2](https://github.com/PnX-SI/GeoNature/assets/143165944/a48eeb51-7be0-48db-a635-b9feb5a5a92c)

**Comment by TheoLechemia** [comment]
Pour l'affichage de valeurs des champs additionnels en lecture, ça nécessiterait de charger la configuration des champs additionnels pour retrouver les labels à partir des "ID" écrit en base (plus compliqué pour champs avec widget Datalist)
Pour le premier problème, c'est un joli bug à corriger

**Comment by camillemonchicourt** [comment]
Les 2 sujets n'ont rien à voir il me semble, il vaudrait mieux faire 2 tickets car sinon on ne sait plus trop de quoi on parle et ce que l'on résout ou pas.

**Comment by marie-laure-cen** [comment]
J'ai séparé les 2 sujets

**Comment by Pierre-Narcisi** [comment]
Je n'arrive pas a reproduire serait-il possible d'avoir plus de details sur le bug ? Quelle champs a été créé, peut être un screenshot de la configuration de l'admin ? et dans quelle table se trouve le problème ?

**Comment by marie-laure-cen** [comment]
ça devait être sur une précédente version de GeoNature (et je ne m'en étais pas rendu compte) car en effet ça ne le fait plus...

**Comment by Pierre-Narcisi** [comment]
Pas de problèmes, je close l'issue
