### ISSUE TITLE
V2 branche ou depot ?

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/GeoNature#286]
Bonjour 

Pourquoi la V2 est dans la branche frontend-contact ?
https://github.com/PnX-SI/GeoNature/tree/frontend-contact

Il existe aussi une branche geonature2 ?
https://github.com/PnX-SI/GeoNature/tree/geonature2

Peut être qu'il serait judicieux de faire un nouveau dépôt ?

Merci

**Comment by camillemonchicourt** [comment]
Oui pour le moment.

**Comment by camillemonchicourt** [comment]
Dès que la dernière V1 est sortie (1.9.1), on créé une branche 1.9.X qu'on garde de côté. 
On bascule les développements de GN V2 dans la branch DEVELOP. 
Dès qu'on a une première V2 fonctionnelle, on bascule les développements dans le MASTER et on release une 2.0.0 ou 2.0.0beta selon l'avancement.

**Comment by camillemonchicourt** [comment]
Les derniers développement (en attente de release) de la V1.X ont été basculés dans une branche 1.9.1. 

Les développements en cours de la V2 ont été basculés de la branche frontend-contact (supprimée) à la branche develop.

Voir https://github.com/PnX-SI/GeoNature/issues/307
