### ISSUE TITLE
[2.13] [SYNHESE] Impossible de personnaliser les champs d'export de la synthèse

### ISSUE THREAD

**Issue by JeromeMaruejouls** [PnX-SI/GeoNature#2860]
**Version**
2.13.3

**Description du bug**
Depuis la mise à jour de mon serveur de 2.11 à 2.13, je ne peux plus personnaliser l'export des champs de la synthèse. J'ai bien personnalisé ma vue v_synthese_for_export, et j'ai rajouté les champs supplémentaires dans le fichier geonature_config.toml ([SYNTHESE] Export_columns). Tous mes exports (Geojson, csv ou shp) ne contiennent pas les champs additionnels.

**Comment reproduire**
Modifier la vue v_synthese_for_export en ajoutant des champs d'une jointure par exemple, et rajouter le nom de ces champs dans geonature_config.toml
Restart Geonature + rebuild du frontend (peut être pas nécessaire)

**Logs**
Rien de particulier dans les logs.

Est-ce que c'est moi qui aie raté quelque chose depuis la 2.11 ?

**Comment by camillemonchicourt** [comment]
La possibilité de pouvoir modifier la vue des exports est discutable et fragile, car on peut être amené à faire évoluer cette vue dans le cœur de GeoNature.
Par exemple dans la version 2.12 on a améliorer les performances des exports Synthèse en révisant cette vue : https://github.com/PnX-SI/GeoNature/issues/1434

Donc ça écrase les éventuelles modifications que certains auraient faite (peut-être ton cas ?) ou sinon ça les empêche d'en bénéficier ce qui est dommage.

Et donc il vaudrait mieux déconseillé voire interdire de pouvoir customiser cette vue. 
Éventuellement trouver un autre moyen si certains ont besoin d'adapter les champs des exports, sans bricoler chacun la vue.

Et si certains ont des besoins complémentaires sur les exports Synthèse, pourquoi ne pas les faire globalement pour tous (sous réserve que cela ne pénalise pas les performances des exports) ?

Sinon, je ne vois rien entre la 2.11 et la 2.13 qui aurait changé et fait qu'on ne peut plus customiser les champs des exports Synthèse, mais là j'ai peut-être rate quelque chose, car je ne maitrise pas la partie technique.

**Comment by JeromeMaruejouls** [comment]
Oui, je comprends ton point de vue. Mais dans la doc, cela est bien précisé que c'est une possibilité avancée. Et dans la mise à jour 2.12, il est précisé de sauvegarder sa vue avant. Donc tout est bien clair et cohérent et semble montrer que la possibilité de personnalisation est toujours là. Concernant de futur problème lors de mise à jour (avec alembic), un simple avertissement dans la doc pour préciser de remettre la vue initiale et c'est réglé !

Concernant les champs supplémentaires, il y a de mon coté des données spécifiques à la région Occitanie (zones biogéographiques par exemple) et je ne pense pas que cela intéresse tout le monde. Je verrai plus, comme c'était avant, un export de base bien optimisé avec la possibilité de ratjouter des champs, avec un impact potentiel sur les performances.

Du coup, je me demande si ce bug vient de moi (meme si j'ai l'impression d'avoir fait la meme procédure qu'en 2.11) ou de mon install ou si tout le monde est concerné depuis la 2.12 ou 2.13 ?

Certains ont réussi ?

**Comment by amandine-sahl** [comment]
Nous sommes en GN 2.13.3 et nous ne rencontrons pas ce soucis. Notre vue d'export est toujours personalisée

**Comment by JeromeMaruejouls** [comment]
> Nous sommes en GN 2.13.3 et nous ne rencontrons pas ce soucis. Notre vue d'export est toujours personalisée

Merci beaucoup @amandine-sahl !
Du coup, @camillemonchicourt , le problème vient de chez moi. Je vais tester ça petit à petit pour voir pourquoi ma conf d'export de 2.11 ne passe pas. Je vous tiens au courant s'il y a des avertissements à mettre dans la doc.

**Comment by amandine-sahl** [comment]
Ci dessous ma configuration et ma vue
```
    # Formats d'export disponibles ["csv", "geojson", "shapefile", "gpkg"]
    EXPORT_FORMAT = ["csv", "geojson", "shapefile", "gpkg"]
    
    # Nom des colonnes obligatoires de la vue ``gn_synthese.v_synthese_for_export``
    EXPORT_ID_SYNTHESE_COL = "idSynthese"
    EXPORT_ID_DATASET_COL = "jdd_id"
    EXPORT_ID_DIGITISER_COL = "id_digitiser"
    EXPORT_OBSERVERS_COL = "observateu"
    EXPORT_GEOJSON_4326_COL = "geojson_4326"
    EXPORT_GEOJSON_LOCAL_COL = "geojson_local"
    # Nom de la colonne id_dataset de la vue ``gn_synthese.v_metadata_for_export``
    EXPORT_METADATA_ID_DATASET_COL = "jdd_id"
    EXPORT_METADATA_ACTOR_COL = "acteurs"
     # Champs à afficher dans l'export / voir non des champs de la vue gn_synthese.v_synthese_for_export dans la base
    EXPORT_COLUMNS   = [
            "regne",
            "group1_inpn",
            "group2_inpn",
            "classe",
            "ordre",
            "famille",
            "rang",
            "nom_valide",
            "nom_vern",
            "nom_cite",
            "status",
            "st_znieff",
            "patrimonial",
            "freq_estimee",
            "endemisme",
            "marcoeur_33",
            "lr_fr",
            "lr_eu",
            "lr_monde",
            "date_debut",
            "date_fin",
            "stade_vie",
            "sex",
            "meth_obs",
            "comportement",
            "biologique_statut",
            "sensibilite",
            "nb_min",
            "nb_max",
            "alt_min",
            "alt_max",
            "observateu",
            "commune",
            "zone_pnc",
            "zone_bioge",
            "st_validat",
            "validateur",
            "cd_nom",
            "cd_ref",
            "comment_releve",
            "comment_occurrence",
            "idSynthese",
            "jdd_nom"
        ]

```
[v_synthese_for_export.txt](https://github.com/PnX-SI/GeoNature/files/13974122/v_synthese_for_export.txt)

**Comment by jbrieuclp** [comment]
Salut,
Tu n'as pas ces 3 champs dans ta vue, c'est peut-être ça le problème :
```
"lr_fr",
"lr_eu",
"lr_monde"
```
