### ISSUE TITLE
[Rapport Import, Frontend] Affichage avancé de statistiques au sujet par exemple de la répartition

### ISSUE THREAD

**Issue by edelclaux** [PnX-SI/GeoNature#2862]
Afficher des graphiques spécifiques tel que le graphique de répartition des espèces. La solution technique pour permettre aux destination de spécifier leur composant graphique est à discuter.

**Comment by camillemonchicourt** [comment]
Actuellement on a un graphique et on peut choisir le rang utilisé ou se baser sur un groupe INPN : 

![image](https://github.com/PnX-SI/GeoNature/assets/4418840/3f35bc4a-6245-485e-942c-af978b67cde3)

Mais ce composant est spécifique à la Destination Synthèse et on doit passer à une solution générique qui s'adapte aux différentes destinations.

Pour la Destination Synthèse, on veut surtout l'info de la répartition taxonomique des données importées. 
Que ce soit sous forme de graphique n'a pas trop d'importance.
Par contre pour ce cas, si il faut stocker la statistique dans un champs générique, il faudra certainement fixer un rang ou groupe, sans laisser la possibilité de basculer entre rangs ou groupes.

**Comment by DonovanMaillard** [comment]
Fixer en dur un rang ou un groupe ne me semble pas souhaitable, selon les utilisateurs ou selon les imports, ça conduira à avoir un graphique/tableau qui n'apporte aucune info pertinente : si j'importe un inventaire des libellules pour un ABC, j'ai forcément 100% d'insectes ou d'odonata, l'info n'est intéressante que si je descend au genre ou à l'espèce. Du coup, vouloir reprendre ce graph ou un tableau avec le même niveau de restitution pose un peu question...

Qu'on importe des taxons ou des habitats on a un cd (cd_nom/cd_hab). A chaud je verrais 2 "graphs" qui pourraient etre développés de manière générique et donner une information pertinente dans tous les cas : 
- Soit on illustre la structure du lot de données (= 1 barplot avec pour chaque cd sa fréquence: ca permet de voir si on a beaucoup de cd_nom/cd_hab et si leur fréquence est plutot équitable ou non -> 90% de mes données sont sur un seul habitat par exemple)
- Soit on illustre les cd_nom/cd_hab "principaux" du lot de données dans un camembert : quels sont les 10/20/50 entités qui ont été le plus relevées et avec quel % pour chaque, en regroupant tous les autres cd dans une catégorie "Autre"

Niveau développement ça permet de mettre en place un seul graph et d'aller simplement compter les cd_nom cd_hab et leur fréquence, chaque source donnant son cd en paramètre ?

**Comment by camillemonchicourt** [comment]
@DonovanMaillard ta proposition reste assez spécifique SYNTHESE / OCCHAB.
On devra aussi pour importer des sites et/ou Visites-Observations dans Monitoring, peut-être plus tard des CA et JDD dans Métadonnées, et aussi depuis des modules plus spécifiques qu'on ne connait pas, comme ZH ou autre.

**Comment by DonovanMaillard** [comment]
oui mais ce graph n'a peut etre simplement pas de sens sur des metadonnées, donc il faudrait simplement le désactiver si on importe autre chose que des taxons ou des habitats. Si on importe des observations dans monitoring on a un cd_nom. Si on importe des sites on a aucun rang ou groupe à renseigner. Et on a pas tellement besoin d'avoir ce type d'information sur des sites, on veut juste savoir combien de sites/lignes on a rentré ?

**Comment by DonovanMaillard** [comment]
oui, c'était simplement un exemple. Le rapport sert surtout à la personne qui a fait l'import ou au fournisseur des données pour avoir un bilan de ce qu'on a pu intégrer depuis les données qu'il nous a transmises. 

Ce que je veux dire c'est que par exemple, si on me donne un fichier des libellules acquises dans le cadre d'un ABC ou autre, ce type de grahpique avec un rang fixé ne m'apportera rien (que ca soit la classe, l'ordre, le groupe 1, le groupe 2 ou le groupe 3 inpn). Et dans les imports, c'est fréquent d'avoir des taxons limités à un groupe/rang si c'est transmis par un expert. Dans ces cas là, le graph ne sert a rien donc fixer le rang n'est pas une bonne option à mon sens

**Comment by camillemonchicourt** [comment]
@orovellotti, là on parle des rapports d'import dans GeoNature, pas de statistiques générales dans GeoNature.

Par rapport aux retours de @DonovanMaillard, c'est vrai qu'on serait bien parti sur un truc plus global et générique, mais on peut aussi considérer qu'on fait un truc pour les imports de taxon (cd_nom) et un pour les imports d'habitats (cd_hab) qui correspondent à de nombreux cas dans GeoNature, et ne pas les utiliser pour les autres. 
Mais ça resterait assez complexe de pouvoir calculer la répartition taxonomique ou des habitats de l'import de manière générique, à différents niveaux de rang taxonomique et cela peut importe la destination. 🤔

**Comment by camillemonchicourt** [comment]
Dans la 2.15 qui intègre le module Import, on est donc parti sur un truc global et générique où chaque module de destination des imports définit lui-même les critères utilisés pour le graphique du rapport de synthèse : 

![image](https://github.com/user-attachments/assets/08a9192e-f1de-4ffd-93a8-f3a0fcb5dea0)

![image](https://github.com/user-attachments/assets/454a507a-3d87-455d-9208-0678edd8c908)

![image](https://github.com/user-attachments/assets/e2e83dc7-a942-478c-9a2f-568bf3a387bb)

![image](https://github.com/user-attachments/assets/92548885-4cb6-414a-99bd-e2620e553750)

![image](https://github.com/user-attachments/assets/d4ce606a-b4d2-48ec-8388-f0e92dd3bc88)

Donc on ne perd pas en fonctionnalité et on gagne en possibilité et en généricité.
