### ISSUE TITLE
[IMPORT][OCCHAB_V1] Squash migration

### ISSUE THREAD

**Issue by edelclaux** [PnX-SI/GeoNature#2863]
Actuellement la branche Alembic import perdure, mais intégrée au dépôt de GeoNature. Cela rend simple la migration, mais n’est pas forcément souhaitable à terme, et elle devrait être intégré à la branche geonature (après la mise en place d’une migration unique d’installation du module d’import ?).

**Comment by jacquesfize** [comment]
Malheureusement, c'est pas une fonction qui est incluse dans Alembic. C'est une tâche compliqué qui pourrait poser des problèmes lors des mises à jours... La solution, je pense, est d'ajouter une migration dans la branche de GeoNature qui dépend (`depends_on`) de la dernière révision de import pour automatiser l'application des migrations de `import`.
