### ISSUE TITLE
[IMPORT/BACKEND/CHANGELOG] Faire évoluer les Dockerfile pour intégrer Import V3

### ISSUE THREAD

**Issue by edelclaux** [PnX-SI/GeoNature#2864]
Il faut documenter le passage à l’import v3 dans le cas où on a déjà le module v1/v2.

À priori, il faut :
- Installer la dernière version de GeoNature
- pip uninstall gn_module_import
- geonature db autoupgrade

> Attention: compatibilité docker + migrate.sh

Il faut également répercuter cette modification sur geonature docker service

> Prochaine révision d'import: sur la branche géonature, pas sur la branche import

**Comment by camillemonchicourt** [comment]
Fait automatiquement dans le script de mise à jour de GN : https://github.com/PnX-SI/GeoNature/blob/master/install/migration/migration.sh#L137-L143

A finaliser dans GeoNature-Docker-services.
