### ISSUE TITLE
Login: afficher des messages d'erreurs

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#289]
Si mauvais identifiant ou mot de passe

**Comment by gildeluermoz** [comment]
├── typescript@2.6.2 invalid 
└── UNMET PEER DEPENDENCY zone.js@0.8.18 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents: 
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3 
npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of @angular/common@^2.2.3 but none was installed. 
npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of @angular/core@^2.2.3 but none was installed. 
npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of zone.js@^0.7.2 but none was installed. 




		
	Gil DELUERMOZ 
Chargé de mission développement web et bases de données 

Parc national des Écrins 
Tél : +33 (0) 4 92 40 20 38 (lundi et mardi) 
+33 (0)4 92 21 08 49 (mercredi et jeudi matin) 
[ http://www.ecrins-parcnational.fr/ | www.ecrins-parcnational.fr ] 

[ http://actu.ecrins.info/ ] 


De: "Théo Lechémia" <notifications@github.com> 
À: "PnEcrins" <GeoNature@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Mercredi 6 Décembre 2017 10:11:58 
Objet: [PnX-SI/GeoNature] Login: afficher des messages d'erreurs (#289) 



Si mauvais identifiant ou mot de passe
