### ISSUE TITLE
lint - html and scss are not included in CI linting

### ISSUE THREAD

**Issue by edelclaux** [PnX-SI/GeoNature#2890]
Linting des fichiers html et scss

- Environnement de développement
- Checks de la CI

Une configuration partagée devrait être mise en place.
Une étape de vérification du bon lint devrait être ajoutée à la CI.

La documentation suggère d'utiliser le formatter par défault de vscode.
https://docs.geonature.fr/development.html#html

Les possibilités sont: 

- utilisation de _prettier_
  Une configuration supplémentaire devrait être mise en place pour rendre le résultat satisfaisant

- utilisation du linter par défault de vscode. 
  La configuration par défault + [les réglages proposés dans la documentation de géonature](https://docs.geonature.fr/development.html#html) sont satisfaisant. 

La config du linter peut-être forcée pour les utilisateurs de vscode via un .vscode/settings.json dans l'environnement de développement.

Afin de pouvoir intégrer le lint à npm run format et côté pipeline CI, il faut pouvoir éxécuter le linter hors vscode. Il me semble que le linter par défault de vscode ets beautifier, qui doit pouvoir être installé et appliqué via npm.

**Comment by TheoLechemia** [comment]
Salut,
Je ne suis personnellement pas fan du résultat des linter sur le html.. Mais le projet grossissant c'est peut être une étape nécessaire.
Si on le rend obligatoire, il faut pouvoir linter sans vscode, car tout le monde ne l'utilise pas. Comme on utilise déjà prettier pour les fichiers .ts, à mon sens il faut utiliser ça.

**Comment by edelclaux** [comment]
J'ai fait une PR pour pouvoir jouer un peu et affiner les paramètres, ou changer la lib de linting si jamais

**Comment by camillemonchicourt** [comment]
Fait dans la 2.14.1
