### ISSUE TITLE
Revoir HOME et customisation

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#290]
- Message d'intro modifiable
- Supprimer galerie photo
- Pouvoir masquer la carte et les graphs

**Comment by camillemonchicourt** [comment]
Premier exemple de customisation CSS pour l'instance nationale : 

![01-home-mtes](https://user-images.githubusercontent.com/4418840/35049195-7d183c86-fb9f-11e7-8ebb-7bfafccfe6d7.jpg)

**Comment by camillemonchicourt** [comment]
Pour le message d'intro, template HTML et composant JS surcouchable dans frontend/src/custom/component/introduction/

Pour la carte et les stats, on la vire en attendant d'avoir la Synthèse.

Galerie photo et stats ont déjà été supprimés.

**Comment by camillemonchicourt** [comment]
La carte a aussi été supprimée.

**Comment by camillemonchicourt** [comment]
La customisation a été précisée dans la documentation : https://geonature.readthedocs.io/fr/latest/admin-manual.html#customisation

Une carte simple des 100 dernières obs présentes dans la Synthèse a été intégrée.

**Comment by TheoLechemia** [comment]
Fait
