### ISSUE TITLE
Double chargement des fond de carte

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#2902]
**Version**
2.13.x

**Description du bug**
Lorsqu'on sélectionne un autre fond de carte que celui par défaut, celui-ci est gardé en mémoire (localstorage) pour la prochaine session. Si l'utilisateur rafraîchit sa page, il tombe bien sur le dernier fond de carte qu'il a choisi et non le fond de carte par défaut. Cependant les requêtes HTTP du fond de carte par défaut sont toujours appelées. Cela double tous les appels HTTP, et si celui qu'on a choisi ne se charge pas on se retrouve avec une mosaïque de deux fond de carte différent

**Comment by jacquesfize** [comment]
Tu sais comment on peut reproduire ?

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.14.1.
