### ISSUE TITLE
Coupure d'accès récurrence à GeoNature / opérations de maintenance ?

### ISSUE THREAD

**Issue by marie-laure-cen** [PnX-SI/GeoNature#2908]
Version : 2.13.3
Serveur Debian 11 bull's eye

**Description du bug**
Il nous arrive de manière régulière de ne pas pouvoir accéder à l'application web de GeoNature pendant un laps de temps allant de quelques minutes jusqu'à une quarantaine de minutes. Cela peut se passer à plusieurs moments de la journée mais principalement le matin vers 9h et en fin de journée vers 16-17h.

Nous ne savons pas trop quelle est la cause mais nous soupçonnons des tâches de maintenance qui s'effectuent en arrière-plan : y a t'il une commande qui permet d'afficher le log des tâches exécutées en arrière-plan par GeoNature et ses dépendances ?

Merci d'avance pour vos réponses

**Comment by camillemonchicourt** [comment]
Nous n'avons pas ce soucis de notre côté.
Il y a plusieurs taches lancées automatiquement avec le worker Celery et Celery Beat (https://docs.geonature.fr/installation.html?highlight=beat#taches-planifiees) : 
- Suppression des médias orphelins
- Vues matérialisées du module Dashboard
- Génération des exports planifiés du module Export
Mais ces taches automatiques ne sont lancées que la nuit vers minuit, 1h du matin, 3h du matin et ne sont pas très longues.

Peut-être voir au niveau des logs de GeoNature et de son worker Celery : https://docs.geonature.fr/admin-manual.html?highlight=celery#logs

Mais c'est peut-être plus global des choses qui tournent sur le serveur indépendamment de GeoNature ?

**Comment by gildeluermoz** [comment]
As-tu essayé de restart les services 

- `sudo systemctl restart geonature.service` 
- et `sudo systemctl restart geonature-worker.service` 
- et éventuellement `sudo service postgres restart`. 

Tu peux aussi chercher à voir ce que fait le serveur durant ces phases problématiques : 

- commande `top` ou `htop` s'il est installé te montreront éventuellement les services qui sollicitent beaucoup le serveur.
- `free -m` te donne la charge mémoire 

a retrouver mais tu peux  aussi demander via une requête sql, quelles sont les requêtes en cours d'exécution. Ca te dira depuis quand elles tournent et si c'est très (trop) long, essayer de diagnostiquer pourquoi.

**Comment by marie-laure-cen** [comment]
Merci pour vos réponses. Je vais essayer tout ça
