### ISSUE TITLE
Ajout de liens externe sur la page de connexion à GeoNature

### ISSUE THREAD

**Issue by RNF-SI** [PnX-SI/GeoNature#2917]
Bonjour,

Dans notre cas spécifique, nous avons développé notre SI autour de UsersHub. Nous avons donc développé un formulaire d'inscription et un formulaire de réinitialisation de mot de passe externe à GeoNature. 2 instances GeoNature et plusieurs autres applications maison sont reliées à UsersHub.

Nous avons donc les paramètres de `ACCOUNT_MANAGEMENT` de GeoNature réglées sur `ENABLE_SIGN_UP = false` et `ENABLE_USER_MANAGEMENT = false`.

Cela gêne un peu l'expérience utilisateurs, en particulier l'absence du lien "Mot de passe oublié" (qui est quand même souvent utilisé...). Ils nous contactent donc à chaque fois pour qu'on les redirige vers le bon formulaire. 

Je propose donc d'ajouter un paramètre dans `ACCOUNT_MANAGEMENT` permettant de générer des liens avec des textes de remplacement qui s'afficheraient en dessous des champs identifiant et mot de passe, sous forme de liste :
```
EXTERNAL_LINKS = [
        { "label" = "Mot de passe oublié", "url"= "https://mon.formulaire.de.motdepasse" },
        { "label" = "Inscription", "url"= "https://mon.formulaire.dinscription" },
        { "label" = "Un autre lien", "url"= "https://un.autre.lien" }
    ]
```

Cela vous semble t'il possible et pertinent ? Je peux faire une proposition de PR le cas échéant.

**Comment by camillemonchicourt** [comment]
La solution proposée me semble pertinente.

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.14.0.
