### ISSUE TITLE
[IMPORT][BACKEND][OCCHAB] Lister les tests à ajouter

### ISSUE THREAD

**Issue by edelclaux** [PnX-SI/GeoNature#2921]
## PR #2925 
> l'ajout de la pr dans la propriétés associée ne fonctionne pas. 
> l'assignation de l'issue à moi même m'est m'interdit

# DESCRIPTION

[Périmètre] coverage des tests 

Actuellement il y a un test, qui réalise l'import un fichier. Ce test réalisé aujourd'hui autour de l'import de données du module occhab est insuffisant.

L'objectif de cette issue est de faire un travail préparatoire au développement de ces tests, en partant des résultats du coverage

> A priori: 
> Il faudrait enrichir ce fichier afin qu'il couvre d'autre cas, comme un mauvais uuid ou station de rattachement non trouvée.
> Il faudrait également enrichier les tests afin de vérifier que les erreurs attendues sont bien levées.
> On peut égaement imaginer que d'autres tests soient rajoutés rajoutés pour des cas spécifiques, avec par exemple d’autres mappings, excluant certains champs.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.15
