### ISSUE TITLE
Bug sur suppression de champ additionnel

### ISSUE THREAD

**Issue by AudreyEnGuyane** [PnX-SI/GeoNature#2923]
**Version**
GN 2.13.3 (instance PAG et démo)

**Description du bug**
Lorsque l'on demande la suppression d'un champ additionnel via le bouton supprimer ou via la coche + With Selected >Delete, une page "internal server error" s'affiche.
Pas de soucis en passant en direct par la base de données (suppression en cascade des objets associés ou du lien avec le.s jdd associé.s.

**Comportement attendu**
Que le champ se supprime depuis l'interface d'administration ... (avec peut-être un message de demande confirmation?)

**Comment reproduire**
Choisissez un champ à supprimer en le cochant puis menu en haut: With Selected >Delete
ou cliquez sur l'icône de suppression en début de ligne sur la liste des champs additionnels.

**Logs**
Extrait du fichier ``/var/log/geonature.log`` dans le cas d’une erreur 500.

**Comment by gildeluermoz** [comment]
Il est normal de ne pas prévoir en base des `DELETE CASCADE` qui peuvent conduire à de la perte involontaire de données. Il ne me semble donc pas souhaitable que la suppression d'un champ additionnel conduise à la suppression des données associées, sans avoir de vision sur ce qui est supprimé en cascade.
Par contre, que l'erreur soit capturée et explicitée dans un message serait préférable.

**Comment by jacquesfize** [comment]
Alors, il y a bien une suppression en cascade des données associées avec les champs additionnels de OCCTAX. Toutefois, ce sont uniquement les données présentes dans les tables de correspondences : `cor_field_dataset`, `cor_field_module` et `cor_field_object`. Ces dernières renseignent l'association entre les champs et les modules, jeux de données et objet concernés. Par conséquent, si un champ est supprimé, les données associées dans OCCTAX sont toujours disponibles dans la base.

Du coup, c'est bien un bug. La correction est disponible dans la PR #2930 et sera intégré dans la 2.14.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.14.0
