### ISSUE TITLE
Lien "Accueil" ne pointe pas sur la page d'accueil

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#2934]
**Version 2.13.3**

**Description du bug**
Quand on clique sur le lien qui vient avec le mot "Accueil" dans l'image ci-dessous, on tombe sur
https://demo.geonature.fr/ au lieu de https://demo.geonature.fr/geonature
![image](https://github.com/PnX-SI/GeoNature/assets/10024739/82c02cbc-4fdc-4997-8cfa-28f46f2d06c1)

**Comportement attendu**
Le lien pointe sur la page d'accueil de GeoNature.

**Comment reproduire**
Cliquer sur le mot "Accueil" à gauche du logo dans le bandeau supérieur.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.14.1.
