### ISSUE TITLE
[OCCTAX] champs additionnal_fields obligatoire au niveau des schéma Marshmallow

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#2937]
Le champs `additionnal_fields` de la table `t_occurrences` est marqué comme `not null` au niveau de la validation Marshmallow alors qu'il ne l'est pas dans le modèle ni dans la base.
Il y a également un hook `post_dump` pour empecher un valeur NULL dans ce champs : 
```
@post_dump
def remove_additional_none_val(self, data, **kwargs):
    if "additional_fields" in data and data["additional_fields"] is None:
        data["additional_fields"] = {}
    return data
```
Pour moi, c'est de l'historique : les trigger vers la synthese géraient mal la concatenation des champs additionnels aux niveau "relevé" / "occurrence" / "dénombrement". Actuellement ça ne pose plus de soucis 
-> 
` COALESCE(releve.additional_fields, '{}'::jsonb) || COALESCE(occurrence.additional_fields, '{}'::jsonb) || COALESCE(new_count.additional_fields, '{}'::jsonb)`

Pour moi on peut enlever cette validation au niveau du schéma Marshmallow

**Comment by camillemonchicourt** [comment]
Fait dans 2.14.1.
