### ISSUE TITLE
Merge relationship sqlachemy 

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#294]
Quand on "merge" un jeu de données en base (table `gn_meta.t_datasets`), la table `cor_datasets_actor` renvoie une erreur d'intégrité:

```
duplicate key value violates unique constraint "check_is_unique_cor_dataset_actor_role"
DETAIL:  Key (id_dataset, id_role, id_nomenclature_actor_role)=(27, 9188, 393) already exists.
```

L'ORM essaye de créer un ligne qui existe déjà.
Dans le modèle 'TDatasets' la relation vers la table 'cor_datasets_actor' est définit comme ça:

```    cor_datasets_actor = relationship(
        "CorDatasetsActor",
        lazy='joined',
        cascade="all, delete, delete-orphan"
    )
```

Quand on retire la contrainte d'intégrité en base et qu'on effectue le "merge", aucun nouvel enregistrement n'est ajouté, mais celui-ci est bien mis à jour.

Mystère à éclaircir...

**Comment by camillemonchicourt** [comment]
Mystère éclairé depuis !
