### ISSUE TITLE
[SYNTHESE] Choix d'affichage des colonnes de la liste 

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#2946]
Dans Occtax, on permet à l'utilisateur de changer les colonnes affichées sur la liste via la petite roue crantée en haut de la liste.
Cela affiche une modale avec la liste des champs disponibles, et quand on coche une colonne, elle s'affiche sur le tableau.

![Capture d’écran du 2024-03-05 16-30-53](https://github.com/PnX-SI/GeoNature/assets/15265745/8c95a559-7c93-453f-b976-ac15b0a30691)
![Capture d’écran du 2024-03-05 16-31-03](https://github.com/PnX-SI/GeoNature/assets/15265745/e37765d0-3be2-4dc9-a950-3cfd0f0f5382)

Dans la synthese, ce mécanisme n'existe pas. Il m'a été demandé de pouvoir afficher les nom latin. Plutôt que de l'imposer à tout le monde, je trouve ce mécanisme interessant.

**Comment by camillemonchicourt** [comment]
Oui si ça n'alourdit pas les performances de chargement des données quand on fait une recherche.

**Comment by TheoLechemia** [comment]
La liste des colonne affichée dans la synthèse est contrôlée par ce paramètre :`DEFAULT_COLUMNS_API_SYNTHESE` qui vaut par défaut: 
```
[
    "id_synthese",
    "date_min",
    "observers",
    "nom_valide",
    "dataset_name",
]
```

donc en l'état on ne pourrait pas rajouter dynamiquement d'autre colonne que celle renvoyées par ce paramètre car ce sont les seules chargées par l'API. Si on les rajoute au paramètre, elles seront affichées par défaut. 
Il faudrait rajouter un second paramètre `ADDITIONNAL_COLUMNS_API_SYNTHESE` ...

**Comment by camillemonchicourt** [comment]
Fait dans la 2.14.1, avec l'ajout du paramètre `ADDITIONAL_COLUMNS_FRONTEND` (https://github.com/PnX-SI/GeoNature/blob/2.14.1/config/default_config.toml.example#L285)

![image](https://github.com/PnX-SI/GeoNature/assets/4418840/aa9348f4-5638-48af-a7e4-2f39427a9318)
