### ISSUE TITLE
marshmallow et postgresql connection strings

### ISSUE THREAD

**Issue by vprunet** [PnX-SI/GeoNature#2947]
La validation marshmallow des liens postgresql: est trop  restrictive.
https://github.com/PnX-SI/GeoNature/blob/ec1f160330a211a7debca96545dba67d602ff5ca/backend/geonature/utils/config_schema.py#L192C4-L198C6

Elle rejette par exemple les liens valides  "postgresql://" (connexion par défaut, typiquement par socket unix) et "postgresql://?service=mon_service_postgresql" (connexion à un service défini dans .pg_service.conf ).

Ces types de connexions présentent de nombreux avantages dont celui d'éliminer les mots de passe, c'est dommage de ne pas les supporter dans les applications geonature.

Ci dessous le lien vers la syntaxe des connection strings postgresql.
https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING-URIS

**Comment by jacquesfize** [comment]
En effet, ça serait intéressant de faire une modification de la `regexp` pour autoriser ses différents moyens de connexions. N'hésite pas à faire une PR si l'envie t'en prends ! :+1:

**Comment by camillemonchicourt** [comment]
Fait dans la 2.14.1
