### ISSUE TITLE
Refondre le système de config

### ISSUE THREAD

**Issue by ksamuel** [PnX-SI/GeoNature#296]
Avoir un système de configuration central, avec héritage, et dont on peut définir la source de manière extérieure.

- [x] Décider d'autoriser les live settings => backend ou non ?
- [x] Avoir un fichier central
- [x] Décider du format de sérialisation
- [x] Décider du schema de donnée
- [ ] Décider du hook
- [x] Sortir la commande de lancement du projet
- [x] Décider si on génère les autres fichiers à partir de là ou si le reste du monde lit la conf centrale =>  Coder générateurs de fichiers de config si on génère
- [x] Coder un générateur de fichier central
- [x]  Coder le loader de conf avec validation, messages d'erreurs et hook de changement

**Comment by amandine-sahl** [comment]
Pas de live settings 
Pas de Hooks
