### ISSUE TITLE
[2.13.3] Champs additionnels / valeur par défaut de type texte passe en grisé si le texte commence par un nombre

### ISSUE THREAD

**Issue by helene-rossignol** [PnX-SI/GeoNature#2978]
**Version**
2.13.3

**Description du bug**
Bonjour,
J'ai ajouté un champ additionnel de type select pour avoir des classes de précision de localisation pour mes points : 
[{"label": "GPS", "value": "GPS"}, {"label": "0 à 10 m", "value": "0 à 10 m"}, {"label": "10 à 100 m", "value": "10 à 100 m"}, {"label": "100 à 500 m", "value": "100 à 500 m"}, {"label": "Lieu-dit", "value": "Lieu-dit"}, {"label": "Commune", "value": "Commune"}]

Lorsque je demande une valeur par défaut sur une value n'incluant que du texte (GPS, Commune, Lieu-dit), aucun souci, la valeur par défaut apparaît bien dans la liste déroulante et peut-être modifiée si besoin.

En revanche, lorsque je veux choisir par défaut une valeur qui commence par une nombre (10 à 100 m, 100 à 500 m). La case se grise et n'est plus modifiable. Si j'ajoute des guillemets, l'ensemble de l'expression apparaît bien entre guillemets dans une case de texte mais n'est pas modifiable. Si je ne mets pas de guillemets, seulement le premier nombre apparaît dans une case de texte et n'est pas modifiable. Si je remplace cette valeur numérique par du texte (exemple : Dix à 100 m), plus de souci.

**Comportement attendu**
Que l'expression puisse être considérée comme du texte, même si elle comprend des nombres, s'afficher par défaut dans une liste déroulante modifiable

**Comment by camillemonchicourt** [comment]
En testant sur le serveur de DEMO, c'est plus complexe que ça.

Sur un champs où la valeur par défaut est "0 à 10 m" cela fonctionne, mais un autre où la valeur par défaut est "0 à 500 m", cela ne fonctionne pas : 

![image](https://github.com/PnX-SI/GeoNature/assets/4418840/1805c0e4-9cc4-488c-931e-517439f710c0)

![image](https://github.com/PnX-SI/GeoNature/assets/4418840/43dab652-5fb1-433b-9647-778a919626b1)

**Comment by jacquesfize** [comment]
Les modifications apportées pour résoudre ce problème sont disponibles dans la version 2.14.2 de GeoNature.
