### ISSUE TITLE
Problème de lien entre la synthèse et occtax suite à migration

### ISSUE THREAD

**Issue by CynthiaBorotPNV** [PnX-SI/GeoNature#2994]
**Version**
2.14.0

**Description du bug**
Suite à la migration de Geonature de v2.13.2 vers la 2.14.0, dans la synthèse, le lien ne se fait plus avec occtax lors de la visualisation de l'observation via le module de saisie :
![image](https://github.com/PnX-SI/GeoNature/assets/31919455/f3b170f8-e31d-4493-ac5c-ef517c04228f)

L'url de la page affichée se termine par "undefined" et le détail de l'observation ne s'affiche jamais :
![image](https://github.com/PnX-SI/GeoNature/assets/31919455/22ca8b31-ae0c-4186-b71a-0b33ac99f491)

**Comment reproduire**
Dans la synthèse, click sur "Voir l'observation dans le module de saisie" d'une observation quelconque.

**Logs**
Nous ne retrouvons pour le moment pas de logs d'erreur liés à ce problème ni côté postgresql, ni côté apache, ni côté géonature, ni côté console du navigateur.

**Comment by camillemonchicourt** [comment]
Doublon de https://github.com/PnX-SI/GeoNature/issues/2907
Bien vu, c'est corrigé dans la branche DEVELOP en cours, et ça sera intégré dans la 2.14.1 que l'on espère sortir dans les prochains jours.
