### ISSUE TITLE
[IMPORT][FRONTEND] Afficher le nom de la destination lors des étapes de création d'un import

### ISSUE THREAD

**Issue by edelclaux** [PnX-SI/GeoNature#2999]
PR: [https://github.com/PnX-SI/GeoNature/pull/3000](https://github.com/PnX-SI/GeoNature/pull/3000)

## Contexte

Lors de la création de l'import, le nom de la destination est visible uniquement dans l'URL.

## Description de la tâche

- [x] Ajouter au dessus de la barre de progression (centré) par un <span> (ou autre) qui indique la destination de l'import en cours de création
- [x] Faire différentes proposition de mise en forme (cadre, taille, couleur....)

**Comment by jpanijel** [comment]
Si le ticket n'est pas encore fini ce serait bien de rajouter aussi le nom du JDD sélectionné
