### ISSUE TITLE
DOC - intégrer un MCD commenté 

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#30]
En lien avec https://github.com/PnEcrins/GeoNature/issues/17

**Comment by camillemonchicourt** [comment]
Déjà mettre un MCD sans commentaire serait un bon début !

**Comment by gildeluermoz** [comment]
si Xavier pouvait le fournir ça serait bien. Ce qu'il a fait avec pgmodeler est bien. Il faut le mettre à jour avec le modèle flore.
Pour tout comprendre il faudrait tout de même mettre qq commentaires sur le rôle central de certaines vues voir aussi concernant les triggers

**Comment by xavier-pnm** [comment]
Pas de soucis. Je remet à jour (et en forme) celui que j'avais généré avec PGModeler + quelques commentaires et je vous l'envoi pour validation. a+

**Comment by camillemonchicourt** [comment]
Le MCD de la V 1.8.3 a été réalisé par @xavier-pnm : https://github.com/PnEcrins/GeoNature/blob/master/docs/2017-01-mcd_geonaturedb_1.8.2.png

A venir : MCD de la V2.

**Comment by camillemonchicourt** [comment]
MCD du Contact V2 discuté ici ! https://github.com/PnX-SI/GeoNature/issues/183

**Comment by camillemonchicourt** [comment]
Le MCD de la V2 est expliqué dans la doc : https://geonature.readthedocs.io/fr/latest/admin-manual.html#base-de-donnees

Mais difficile de faire un MCD complet, et encore plus de le commenter. 

Si ça tente quelqu’un ???

**Comment by camillemonchicourt** [comment]
Un MCD de la 2.1 a été intégré par @jpm-cbna dans la doc : https://github.com/PnX-SI/GeoNature/tree/master/docs
Il serait à mettre à jour, voir à générer automatiquement, mais ça fait une bonne base.
