### ISSUE TITLE
SAWarning et DeprecationWarning

### ISSUE THREAD

**Issue by CynthiaBorotPNV** [PnX-SI/GeoNature#3010]
**Version**
2.14.0

**Description du bug**
Juste pour votre information, depuis l'installation de cette dernière version il y a beaucoup de message de type SAWarning pour des conflits relationnels en BDD ou de type DeprecationWarning pour l'usage de fonctions python deprecated 

**Logs**
Exemple lors de l'utilisation de la commande `geonature` 
.../geonature/backend/venv/lib/python3.11/site-packages/flask_admin/contrib/sqla/view.py:369: **SAWarning**: relationship 'TMonitoringModules.datasets' will copy column t_datasets.id_dataset to column cor_module_dataset.id_dataset, which **conflicts with relationship(s): 'TDatasets.modules**' (copies t_datasets.id_dataset to cor_module_dataset.id_dataset). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="modules"' to the 'TMonitoringModules.datasets' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
return model._sa_class_manager.mapper.iterate_properties
.../gn_module_monitoring/backend/gn_module_monitoring/config/utils.py:142: **DeprecationWarning**: read_text is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
  config_txt = importlib.resources.read_text(
/usr/lib/python3.11/importlib/resources/_legacy.py:80: DeprecationWarning: open_text is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.

**Comment by camillemonchicourt** [comment]
Oui ce sont des warnings au niveau du module Monitoring, où il y a différentes mises à jour en cours.

**Comment by CynthiaBorotPNV** [comment]
Nous avons eu aussi ce type de warnings à d'autres occasions depuis l'installation. C'est simplement à titre indicatif.

**Comment by camillemonchicourt** [comment]
Oui merci pour l'info. 👍
Ils concernent bien le module Monitoring et sont affichés à chaque fois que l'on relance des commandes GeoNature.
