### ISSUE TITLE
Dynamic Form : button radio non séléctionné en édition

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#3011]
**Version**
2.14.1

**Description du bug**
Lorsqu'on revient en édition sur un champs additionnel (dynamic form) de type "radio", l'item préalablement sélectionné n'est pas sélectionné.
Le bug se produit uniquement quand les valeurs de l'input radio commence par un chiffre 😵‍💫 

**Comment reproduire**
Créer un champs additionnel du type "radio" et l'associé à Occtax. Mettre ces valeurs dans le champs "valeurs" : 
`[{"label": "100", "value": "100"}, {"label": "10", "value": "10"}, {"label": "autre", "value": "autre"}] `
Créer un relevé en remplissant ce champs, puis revenir en édition sur le relevé -> l'item n'est pas séléctionné.

Si on enlève cette ligne https://github.com/PnX-SI/GeoNature/blob/master/frontend/src/app/GN2CommonModule/form/dynamic-form/dynamic-form.component.html#L222
ça fonctionne bien et le formcontrol est bien mis à jour via le `onRadioChange`

**Comment by jacquesfize** [comment]
Lié surement à #2978
