### ISSUE TITLE
[FRONTEND] Transformer le graphique Synthèse en piechart

### ISSUE THREAD

**Issue by jacquesfize** [PnX-SI/GeoNature#3013]
## Contexte

Le graphique pour le moment est un diagramme à barre alors que l'ancien graphique était un piechart.

## Description de la tâche

- [x] Reprendre le graphique de la synthèse fait dans https://github.com/PnX-SI/GeoNature/pull/3002
- [x] Le transformer en `piechart` à l'aide de https://docs.bokeh.org/en/latest/docs/examples/topics/pie/donut.html

**Comment by camillemonchicourt** [comment]
Fait dans la 2.15
