### ISSUE TITLE
Installer pylint, flake8, mypy, pytest, coverage, sphinx, editorconfig et tox

### ISSUE THREAD

**Issue by ksamuel** [PnX-SI/GeoNature#302]
- [x] pylint
- [x] flake8
- [x] mypy
- [x] pytest
- [x] coverage
- [x] sphinx
- [x] editorconfig
- [x] tslint
- [x] pipenv 
- [x] tox => décider si on l'utilise ou pas
- [x] documenter le lancement de ces outils

**Comment by camillemonchicourt** [comment]
Top !
