### ISSUE TITLE
Question : Où sont stockées les images upload avec la saisie d'une observation Occtax

### ISSUE THREAD

**Issue by Amegilla** [PnX-SI/GeoNature#3020]
Bonjour, 

Je suis entrain de remonter un serveur geonature et j'aimerais rapatrier les images uploadées via occtax mais je ne les retrouve pas
sur mon ancien serveur.

merci

**Comment by camillemonchicourt** [comment]
Quelle version de GeoNature ?

**Comment by camillemonchicourt** [comment]
Ça a évolué dans la 2.12.0, donc faut voir si tu es avant ou après.

Tu trouveras des réponses dans https://github.com/PnX-SI/GeoNature/issues/2306

**Comment by camillemonchicourt** [comment]
A vérifier car de mémoire, mais il me semble qu'avant c'était dans "backend/static/media/" et après dans "backend/media/".

**Comment by Amegilla** [comment]
Salut, 

ok merci, cela confirme que j'ai perdu mes médias :)
J'ai tenté de la 2.13 à la 2.14 mais j'ai eu des bugs pendant la migration, et je ne me souviens plus si je n'ai pas tenté de le relancer la migration une seconde fois ce qui aurait pu supprimer/écraser les médias (?) ... en tout cas plus rien dans ces deux répertoires et même dans mon geonature_old. 
J'ai fait une upgrade de debian 11 vers 12 juste avant et cela m'a mis le bazar dans les libraires postgis et sans doute ailleurs... Bref, j'ai réinstallé mon vps à zéro pour repartir sur de bonnes bases.

**Comment by camillemonchicourt** [comment]
Euh bah non, c'est pas normal ça. On n'est pas censé perdre des médias... 🤔
Quand tu consultes une observation où tu avais mis un média directement dans GeoNature, tu vois plus son media ?
Et dans la table des médias dans la BDD, tu as du contenu référencé ?

Et si tu lances un "grep" dans tout le dossier GeoNature avec le nom d'un fichier, tu ne le retrouves pas ?
Sinon, tu as des sauvegardes j'espère ?
