### ISSUE TITLE
[INSCRIPTION] L'inscription renvoie une erreur 500

### ISSUE THREAD

**Issue by andriacap** [PnX-SI/GeoNature#3043]
**Version**
Version de GeoNature affectée par le bug : 2.13.4

**Description du bug**
L'inscription sur GeoNature ne fonctionne plus (voir image ci dessous). Sachant que ç fonctionnait bien auparavant 
![image](https://github.com/PnX-SI/GeoNature/assets/111564663/ed0a4128-45d5-4093-a6ce-f5b17beab640)

**Logs**
Extrait du fichier ``/var/log/geonature.log`` dans le cas d’une erreur 500  

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='geonature.snpn.com', port=443):
Max retries exceeded with url: /geonature/api/pypn/register/post_usershub/create_temp_user
 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3565692430>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Est ce que ça vous évoque un problème que vous avez déjà rencontré ? 

Merci d'avance

**Comment by jbrieuclp** [comment]
Un caractère spécifique dans le mot de passe ? Genre un @ qu'il faudrait transformer en %40 peut-être.

**Comment by andriacap** [comment]
> Ah non, moi je parlais dans tes fichiers de config .toml et non dans le mdp utilisateurs. Regarde plus spécifiquement dans tes logs postgres tu y trouveras peut être ton bug

Il n'y a pas non plus de caractères spéciaux.  Je vais explorer vos autres pistes , merci !
