### ISSUE TITLE
Apprendre à mettre en ouvre HTTPS

### ISSUE THREAD

**Issue by ksamuel** [PnX-SI/GeoNature#305]
- [ ] En local avec auto-signature
- [ ] En prod avec certbot
- [ ] Ajouter la redirection http vers https dans le server (ex: apache, nginx, etc)

**Comment by camillemonchicourt** [comment]
Et sinon au niveau du domaine chez l'hébergeur avec redirection du http vers https ?

**Comment by ksamuel** [comment]
Il faut faire ça dans nginx. Je vais le rajouter en tache.

**Comment by camillemonchicourt** [comment]
Doc à intégrer.
