### ISSUE TITLE
Paramêtrage champs additionnels html

### ISSUE THREAD

**Issue by marie-laure-cen** [PnX-SI/GeoNature#3052]
Bonjour,

Je n'arrive pas à paramétrer les champs additionnels html. Dans la documentation, si je suis l'exemple, il faut remplir uniquement la partie "attribut additionnel" du champ additionnel, c'est ça? . Dans mon instance, le champs n'apparait pas.

Version de GeoNature : 2.13.4

Tests (sur valeur, sur attribut additionnel et sur les deux) : 
`{"html": "un texte tout simple"}`
`{"html": "un texte tout simple", "class": "alert alert-primary"}`

et j'ai essayé de rattacher au relevé, à l'occurrence et aux 2

Je n'ai pas trouvé d'exemple de paramétrage boite HTML dans l'instance test de GeoNature.

**Comment by TheoLechemia** [comment]
Bonjour,

je viens de créer un champs additionnel de type HTML avec une classe alert, il s'affiche dans Occtax : 
https://demo.geonature.fr/geonature/api/admin/tadditionalfields/edit/?id=30&url=/geonature/api/admin/tadditionalfields/?page%3D1
Tu peux t'en inspirer

**Comment by marie-laure-cen** [comment]
Je vois le problème... je n'ai pas accès au module Occtax dans le champs module donc forcément ça ne s'affiche pas!

**Comment by TheoLechemia** [comment]
Il faut qu'Occtax soit dans le paramètre : 
["ADDITIONAL_FIELDS"]["IMPLEMENTED_MODULES"]
tu as dupliqué Occtax c'est bien ça ?

**Comment by marie-laure-cen** [comment]
oui j'ai testé ça... je vais regarder, merci :)
