### ISSUE TITLE
la route `/geo/areas` ne gère plus le filtre par `type_code` multiple

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#3057]
**Version**
2.14.x

La route `geo/areas?areas` est appelé par le frontend en formatant les `type_code` avec des virgule -> `http://127.0.0.1:8000/geo/areas?type_code=COM,LI&without_geom=true`. 
Côté backend, on utilise la méthode `getlist` pour récupérer les paramètres, qui ne gère pas ce type de formatage de paramètre avec virgule. Le paramètre est interprété comme ça : `['COM,LI']`
 Voir https://github.com/PnX-SI/RefGeo/pull/22/files#diff-19f667bdfa1648f7f9d813579a50a035d96ce694de907491e2b9193bc4293b0dR217
cela se produit quand on utilise la config suivante de GN : 

```
[SYNTHESE]
    AREA_FILTERS = [
        { "label" = "Communes", "type_code" = ["COM", "LI"] }
    ]
```

**Comment by jacquesfize** [comment]
Ca vient de la manière dont flask récupére les listes dans les arguments GET... pour déclarer une liste d'élément comme paramètre, il faut faire ça : http://<url>?arg=val1&arg=val2

**Comment by jacquesfize** [comment]
J'ai fait une PR, pour résoudre le problème : https://github.com/PnX-SI/RefGeo/pull/26

**Comment by jacquesfize** [comment]
Les modifications apportées pour résoudre ce problème sont disponibles dans la version 2.14.2 de GeoNature
