### ISSUE TITLE
Réoganiser les branches

### ISSUE THREAD

**Issue by ksamuel** [PnX-SI/GeoNature#307]
- [x] Déplacer develop sur 1.9.1
- [x] Faire de frontend contact la nouvelle branche develp

**Comment by ksamuel** [comment]
Tous les developpeurs doivent faire:

git branch -d develop
git fetch
git checkout develop

@camillemonchicourt : il faut que tu le fasse avant d'utiliser git

**Comment by camillemonchicourt** [comment]
OK super. 
J'ai pas de clone Git donc ça va. :-D

**Comment by camillemonchicourt** [comment]
Suite à la réorganisation des branches, j'ai fait les MAJ des liens dans la DOC : https://github.com/PnX-SI/GeoNature/commits/develop
