### ISSUE TITLE
[IMPORT][LISTE] Reprise des informations concernant les nombres de lignes et d'entités importées dans la liste des imports

### ISSUE THREAD

**Issue by edelclaux** [PnX-SI/GeoNature#3070]
# DESCRIPTION

L'intitulé de la colonne "Nb de données" est incohérent avec la colonne stat "Nb de données importées".

![Image](https://github.com/PnX-SI/GeoNature/assets/56294090/b0a6c20b-0b36-4000-a5af-b20f635e61d3)

# PROPOSITIONS

Alternatives :
- Renommer la colonne "Nb de données" en "Nb de lignes" (sous-entendu "nombre de lignes dans le fichier")
- Afficher les nombres d'entités importées et d'entités "ignorées" (ou "non importées")

# TODO

- [ ] Faire des propositions de design/implémentation

**Comment by edelclaux** [comment]
Il me semble que la notion d'entité n'est pas très pertinente au niveau de l'interface utilisateur. 
J'aurai envie de parler d'observations, de stations ou encore d'habitats.

Il me semble qu'il faudrait supprimer la données générique "nombre d'entité", et la remplacer par les statistiques des propres aux imports. 

Une plan de redistribution de l'information pourrait être:
- page liste: 
  - supprimer la colonne "Nb de données"
  - optionnel (pertinent ?): ajouter une colonne générique: "Nombre de ligne valide"
- enrichir les statistiques de la synthèse
  - ajouter "nombre d'observations importées"
  - ajouter "nombre taxons distincts observés" (ou quelque chose de mieux formulé)
- page rapport: enrichir la section description:  
  - ajouter lignes valides
  - ajouter lignes no valides
  - supprimer "Nombre d’entités importées" (l'information sera dans les statistiques de l'import, afficher automatiquement)
- page rapport: enrichir la section "données invalides"
  - ajouter une section "lignes invalides", qui résume le compte 
  
![image](https://github.com/PnX-SI/GeoNature/assets/150020787/f0e1c8f2-283f-4c1d-a397-f0a424544cbf)

Exemple pour Synthèse, même chose pour Occhab: 
![image](https://github.com/PnX-SI/GeoNature/assets/150020787/0991352f-00dc-4b3b-ab9e-059480b66f9e)

**Comment by edelclaux** [comment]
Merci pour ton retour


Pour ce qui est du bug

**Comment by edelclaux** [comment]
Merci pour ton retour.

- La colonne avec les "nombre de lignes du fichier / nombre de lignes importées": 
Ca me va tout à fait de fusionner ça. D'autant que l'alternative "nombre d'objet importés" est filou: il peut y avoir plusieurs objets sur une même ligne. 
Par contre, j’inverserai les deux chiffres: importées / total
**Qu'est-ce qui te semble ok comme nom de colonne ?**

- Bug d'alignement des colonnes: Je ne sais pas comment faire. Je crois qu'il faut [Voir issue](https://github.com/orgs/PnX-SI/projects/13/views/7?filterQuery=-no%3Astatus+&pane=issue&itemId=64947167)

- Stats tooltip: ok, voir PR

- Je proposais de changer la phrase "nombre de taxons importés", parce qu'il me semble qu'on importe des observations, pas des taxons. Mais c'est le métier qui décide :)


Tu as un avis sur mes modifications de la section Rapport d'import web / "Données invalides" ?

**Comment by camillemonchicourt** [comment]
> Par contre, j’inverserai les deux chiffres: importées / total

Oui bien sur.

> Je proposais de changer la phrase "nombre de taxons importés", parce qu'il me semble qu'on importe des observations, pas des taxons. Mais c'est le métier qui décide :)

En effet, ça peut être confusant. Alors partons juste sur "nombre de taxons".

> Tu as un avis sur mes modifications de la section Rapport d'import web / "Données invalides" ?

Rapidement, j'ai pas pu analyser dans le détyail, mais il me semble qu'on a le même avis sur le sujet. Actuellement c'est peu clair et confus et ce que tu proposes me semble améliorer, clarifier et rendre ça plus lisible.

**Comment by edelclaux** [comment]
Ok, je commence à développer alors !

**Comment by camillemonchicourt** [comment]
Fait dans la 2.15 si j'ai bien suivi.

Avec le nombre de lignes importées et le nombre de lignes totales.
Et les stats en fonction de la destination : 

![image](https://github.com/user-attachments/assets/79ff483a-d438-419f-a79e-389e446d355a)

![image](https://github.com/user-attachments/assets/54ea40aa-12f9-4695-aca8-69dd836b9b45)

Idem dans le rapport d'import : 

![image](https://github.com/user-attachments/assets/dba815ff-7e32-4076-974a-58e64559bd76)

![image](https://github.com/user-attachments/assets/babdbb8e-3f16-4f51-89fd-3ff9cefde796)

A bien tester et préciser si certains points évoqués plus haut restent à faire ?
