### ISSUE TITLE
Perte d'affichage des acteurs dans la fenêtre "Information sur l'observation"

### ISSUE THREAD

**Issue by MathieuLagarde** [PnX-SI/GeoNature#3086]
Bonjour,

**Version**
A la suite des mises à jours suivantes (qui se sont bien déroulées):
taxhub: 1.12.1 -> 1.14.1
usershub: 2.3.4 -> 2.4.3
geonature: 2.13.3 -> 2.14.2

**Description du bug**
Nous perdons l'affichage des "Acteurs", dans l'onglet "Métadonnées", de la fenêtre "Information sur l'observation", de la page "Explorer les données".
Le texte ne s'affiche pas, mais les puces typographiques s'affichent bien.

**Comportement attendu**
Affichage des acteurs et de leurs rôles.

**Comment reproduire**
Sur la page "Explorer les données", cliquer sur le picto "information" à côté des données (volet de droite), puis sur l'onglet "Métadonnées".

**Comment by marie-laure-cen** [comment]
Même problème vu hier sur notre instance (v14.2 aussi)

**Comment by camillemonchicourt** [comment]
OK, confirmé sur le serveur de DEMO : 
![image](https://github.com/PnX-SI/GeoNature/assets/4418840/b6948e4f-9a6e-4490-8fea-190af46b4270)

**Comment by Pierre-Narcisi** [comment]
Normalement le problème seras réglés dans la prochaine release grace a cette PR:  #3095
