### ISSUE TITLE
MapList - Occtax / Afficher date relevé par défaut

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#309]
Plutôt que le champ Observateur, moins intéressant.

**Comment by TheoLechemia** [comment]
On affiche date début et date fin par défaut.

**Comment by TheoLechemia** [comment]
Le fichier ``contact.config.ts`` contient le paramètre ``default_maplist_columns`` pour choisir les colonnes qu'on affiche par défaut.
