### ISSUE TITLE
[GN 2.14.2] Erreur 404 – Inscription et récupération de mot de passe

### ISSUE THREAD

**Issue by LudmillaT** [PnX-SI/GeoNature#3090]
Bonjour, 
Nous venons d’installer notre version production d’ODIN qui correspond à un GeoNature version 2.14.2 mis en place sur un serveur Debian 12. L’installation de GeoNature c’est aussi accompagner de l’instalation d’UsersHub 2.4.3 et de TaxHub 1.14.1. L’installation se déroule correctement GeoNature, UsersHub et TaxHub sont bien disponible et tout semble fonctionner correctement à l’exception des inscriptions et de la récupération de mot de passe. 

**Version**
GeoNature 2.14.2 et UsersHub 2.4.3

**Description du bug**
Tout d’abord lorsqu’on se connecte avec un compte existant, ou qu’on est loger de mémoire sur GeoNature on ne rencontre à priori aucune erreur dans le fonctionnement de la plateforme. 
Cependant, lorsqu’on essaie de récupérer son mot de passe il y a une erreur dans la console : 404 Not Found  cf image ci-dessous : 

![image](https://github.com/PnX-SI/GeoNature/assets/102731713/a8f1d49d-2a43-43f8-b732-549680a3330e)

On a la même erreur si on cherche à créer un compte. 

**Comportement attendu**
Possibilité de crée des comptes et récupérer des identifiant.

**Comment reproduire**
J’ai suivi la documentation d’installation est de passage en HTTPS (https://docs.geonature.fr/installation.html). 

**Logs**
Extrait du fichier ``/var/log/apache2/access.log`` :
`::1 - - [06/Jun/2024:16:47:26 +0200] "POST /usershub/api_register/test_connexion HTTP/1.1" 404 488 "-" "python-requests/2.32.2"
::1 - - [06/Jun/2024:16:47:26 +0200] "POST /usershub/pypn/auth/login HTTP/1.1" 404 487 "-" "python-requests/2.32.2"
`
On à tenter quelques trucs qui n’ont pas abouti, auriez des idées de ce qui peut provoquer cette erreur ? 

Merci d’avance pour vos retours 

NB : ce n’est pas la premières fois que je rencontre des problèmes avec les inscription et la récupérations d’identifiant mais les erreur que je rencontre ne sont jamais les même.

**Comment by jacquesfize** [comment]
Bonjour @LudmillaT,

Serait-il possible d'avoir un extrait du log de GeoNature ? (le fichier - > /var/log/geonature/geonature.log normalement)

**Comment by LudmillaT** [comment]
Bonjour, 

Je n'ai pas mis les logs geonature parce qu'il ne rien ne se déclenche quand je lance l'inscription, j'ai retenter un inscription à 13h50 (10/06/2024) et les logs sont les suivants : 

```[2024-06-07 17:12:49 +0200] [13794] [INFO] Shutting down: Master
[2024-06-07 17:12:49 +0200] [14367] [INFO] Starting gunicorn 22.0.0
[2024-06-07 17:12:49 +0200] [14367] [INFO] Listening at: http://127.0.0.1:8000 (14367)
[2024-06-07 17:12:49 +0200] [14367] [INFO] Using worker: sync
[2024-06-07 17:12:49 +0200] [14368] [INFO] Booting worker with pid: 14368
[2024-06-07 17:12:49 +0200] [14369] [INFO] Booting worker with pid: 14369
[2024-06-07 17:12:50 +0200] [14370] [INFO] Booting worker with pid: 14370
[2024-06-07 17:12:50 +0200] [14371] [INFO] Booting worker with pid: 14371
[69b82d85-bf56-448a-9c74-65ff23c65241] {"type": "password", "msg": "Mot de passe invalide"}
[2024-06-08 19:18:08 +0200] [14369] [INFO] {"type": "password", "msg": "Mot de passe invalide"}
```
Oui UsersHub est accessible à l'adresse suivante : https://odin.anbdd.fr/usershub/users/list

Merci d’avance pour vos retours

**Comment by LudmillaT** [comment]
Dans la config j'ai  ```URL_USERSHUB = "http://localhost/usershub"```. J'avais aussi essayer avec `URL_USERSHUB = "http://127.0.0.1:5001"` et `URL_USERSHUB = https://odin.anbdd.fr/usershub` mais rien ne fonctionner.

**Comment by jacquesfize** [comment]
Normalement `https://odin.anbdd.fr/usershub` devrait fonctionner... est-ce que c'est la même erreur que sur le screenshot ?

**Comment by LudmillaT** [comment]
Je viens de tester en mettant  `URL_USERSHUB = "https://odin.anbdd.fr/usershub"` et effectivement c'était ça le problème, j'avais tester avec `URL_USERSHUB = "http://odin.anbdd.fr/usershub"` mais je n'avais pas pensé à mettre https...

Merci beaucoup pour votre aide !!
