### ISSUE TITLE
Bandeau de cookie modules Geonature

### ISSUE THREAD

**Issue by rgoffinet** [PnX-SI/GeoNature#3109]
Bonjour, 

Nous utilisons  à Rennes Metropole Geonature et ses modules atlas et citizen depuis maintenant plus de 2 ans. 
Notre DPO nous demande de mettre en place un bandeau de cookie (de préférence tarteaucitron) sur tous les fronts afin de respecter la réglementation RGPD/CNIL.

Avez-vous déjà testé l'installation d'un bandeau de cookie ou initié des travaux en ce sens ?

Merci d'avance !

**Comment by camillemonchicourt** [comment]
Oui ce sujet est discuté sur les outils en questions.
Ce dépôt concerne l'outil GeoNature où le besoin est moins important car il s'agit d'un outil métier, avec authentification.
Par contre, pour GeoNature, c'est discuté et prévu de l'ajouter dans le cadre d'une prestation de Nantes Métropole qui démarre après l'été : https://github.com/PnX-SI/GeoNature-atlas/issues/527
A discuter sur ce dépôt si des compléments sont à apporter.

Sur GeoNature-citizen, il n'y a rien de précis de prévu, mais un sujet périphérique a été discuté ici : https://github.com/PnX-SI/GeoNature-citizen/issues/213
A compléter, discuter sur ce dépôt, et financer si des évolutions sont souhaitées.
