### ISSUE TITLE
Export SINP - Adaptation

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#311]
- Les imports SHP ont été intégrés et donc les noms de champs ont été raccourcis. Il faut donc revoir les noms de champ dans les exports
- Les formats date ne sont pas les bons (``/`` à la place des ``-`` conformément à ce qu'on a dans les SHP)
- Vérifier les autres champs (``geometrie`` devenu ``wkt`` par exemple)
- Il faut peut-être supprimer les UUID des JDD car GINCO les intègre lui-même (à confirmer car c'est dommage de les enlever de l'export générique)
- Annee-ref-commune et Annee-ref-departement vont basculer en facultatif. Ca concerne que les données rattachées à une géométrie

**Comment by camillemonchicourt** [comment]
Si il y a des colonnes en plus, GINCO va bloquer, il faut le même nombre de colonnes. 
Donc il faut enlever le UUID JDD pour le moment. Aucune info de métadonnées car c'est GINCO qui va gérer. 
Quand le pétitionnaire se connecte à GINCO, il doit renseigner son ID TPS puis choisir le JDD qu'il va importer dans GINCO (dans une liste déroulante).

**Comment by camillemonchicourt** [comment]
Le standard OCCURRENCE DE TAXON - DEPOT LEGAL BIODIVERSITE a été mis à jour à l'instant sur le site NatureFrance : http://www.naturefrance.fr/sites/default/files/fichiers/ressources/pdf/standard_fichier_depot_donnees_brutes_biodiversite_v1-projet.pdf

Il renvoie aussi à ce document pour le georeferencement : http://www.naturefrance.fr/sites/default/files/fichiers/ressources/pdf/sinp_principes_cas_usages_geo-referencement.pdf

**Comment by camillemonchicourt** [comment]
Vu que le format a des spécificités liés au DEPOT LEGAL BIODIVERSITE, se pose la question de garder un export SINP générique (avec JDD etc..) et un autre à côté spécifique DLB ?

**Comment by TheoLechemia** [comment]
Pas hyper pratique de faire des exports par JDD sans avoir le JDD ID dans la vue ...
Je vais voir ce que je peux faire

**Comment by camillemonchicourt** [comment]
Pour le moment on a pas le choix.
Sinon tu le mets juste dans le nom du fichier.

**Comment by TheoLechemia** [comment]
Oui mais pour filtrer sur le JDD il faut forcément l'avoir dans la table.
Je l'ai laissé de la vue, et je l'enlève à la génération du CSV... C'est crado mais la vue est hyper spécifique MTES de toute façon

**Comment by TheoLechemia** [comment]
Fait 9323feff176c335bd43273d9b92f4afb0523652f

A tester dans Ginco

**Comment by camillemonchicourt** [comment]
Du coup c'est une vue EXPORT spécifique pr_contact.export_occtax_dlb.
Et on a gardé la vue générique pr_contact.export_occtax_sinp
