### ISSUE TITLE
Installation incomplète de la v2.14.0

### ISSUE THREAD

**Issue by CynthiaBorotPNV** [PnX-SI/GeoNature#3112]
**Version**
Geonature 2.14.0
Debian 12

J'ai réalisé 2 fois l'installation complète avec le même résultat.
Ci joint les logs de l'install.
[install_all.log](https://github.com/user-attachments/files/16094278/install_all.log)

Quelqu'un arriverait-il à me dire ce qui ne tourne pas rond dans cette install ? Merci !

**1) Répertoire geonature/frontend/dist absent**

/var/log/apache2/geonature_error.log
`AH01630: client denied by server configuration: /home/gnadmin/geonature/frontend/dist`

Par contre mentionné dans la conf  /etc/apache2/conf-available/geonature.conf
```
AliasMatch "^/(.*)$" "/home/gnadmin/geonature/frontend/dist$1"
<Directory "/home/gnadmin/geonature/frontend/dist">
    Require all granted
</Directory>
```
J'ai vu que l'issue [#406](https://github.com/PnX-SI/GeoNature/issues/406) en parlait et donc en suivant la méthode donnée par  @TheoLechemia, cela semble avoir complété cette installation
```
cd <home>/geonature/frontend
npm install
npm run build
sudo apachectl restart
```
**2) Erreur dans le fichier /etc/apache2/conf-available/geonature.conf**

Toujours une erreur du même type, mais là le problème semblait venir de la regexp de l'alias
```
[Wed Jul 03 13:48:43.592533 2024] [authz_core:error] [pid 253965:tid 139770088834752] [client 62.102.224.250:64563] AH01630: client denied by server configuration: /home/gnadmin/geonature/frontend/distgeonature
[Wed Jul 03 13:48:43.711571 2024] [authz_core:error] [pid 253965:tid 139770080442048] [client 62.102.224.250:64563] AH01630: client denied by server configuration: /home/gnadmin/geonature/frontend/distfavicon.ico, referer: http://151.80.250.141/geonature/
[...]
```
/etc/apache2/conf-available/geonature.conf
`AliasMatch "^/(.*)$" "/home/gnadmin/geonature/frontend/dist$1"`
Correction
`AliasMatch "^/geonature(.*)$" "/home/gnadmin/geonature/frontend/dist$1"`

**3) le service géonature n'est pas créé dans le répertoire /etc/systemd/system**
Les fichiers suivant sont manquants

- geonature.service
- geonature-reload@.path
- geonature-reload.service
- geonature-worker.service

Je les ai copié de la prod et ai relancé le service avec un` sudo systemctl restart geonature`

**4) Pas de logs pour geonature dans /var/log mais pour taxhub et usershub ok.**

**5) Erreur sur le forntend**
```
geonature/assets/config.json:1 
Failed to load resource: the server responded with a status of 404 (Not Found)
```
Effectivement le répertoire geonature/assets est manquant

**6) Je m'arrête là ;-)**

**Comment by gildeluermoz** [comment]
Ton pb semble plus large, mais regarde cette issue, potentiellement en lien : https://github.com/PnX-SI/GeoNature/issues/2852

**Comment by CynthiaBorotPNV** [comment]
Pourtant le home de mon user gnadmin est bien en 755 contrairement à d'autres
```
gnadmin@debian-2-dev:~$ll ..
total 32
drwx------ 5 dev         dev          4096 27 juin  17:00 dev
**drwxr-xr-x 8 gnadmin     gnadmin      4096  4 juil. 08:31 gnadmin**
drwx------ 8 gps3vallees gps3vallees  4096  3 juil. 11:04 gps3vallees
drwx------ 2 root        root        16384 26 juin  17:45 lost+found

```
L'utilisateur dev a été créé lors de l'install de l'OS mais gnadmin a été créé après coup.

**Comment by CynthiaBorotPNV** [comment]
En regardant dans les scripts d'install (02_configure_systemd.sh), je me rend compte qu'en mode "dev" les services ne sont pas installés.
