### ISSUE TITLE
[IMPORT] Contrôle de données pour la destination occhab

### ISSUE THREAD

**Issue by jacquesfize** [PnX-SI/GeoNature#3114]
Bonjour à tous,

Avec @Pierre-Narcisi, dans le cadre de l'import multi-destination, nous avons mis à jour les contrôles de données pour la destination OccHab. Cette issue résume le travail effectué jusqu'à présent.

Dans un besoin de rendre plus explicite les contrôles de données, certaines fonctions communes à toutes les destinations sont déplacées dans les `check_transient_data` : `init_rows_validity` et `check_orphan_rows`.`init_rows_validity`, responsable de l'initialisation de la validité des lignes, a été modifié pour vérifier si l'identifiant d'une entité existe déjà dans la table de destination. Si l'identifiant d'une entité existe dans la destination alors aucun contrôle de données est effectué sur cette entité. Pour faciliter ce processus, nous avons déplacé la méthode `generate_missing_uuid` pour générer les UUID avant tous contrôle de données ! De plus, elle a été modifié pour générer un uuid unique par entité si un `id_station_source` est indiqué !

Autre grand changement, quand une entité est importée pour la première fois, les informations de cette dernière doivent être répétées sur chaque ligne où cette dernière apparaît. Nous avons ajouté un contrôle de données permettant de vérifier la cohérence des données indiqués pour une même entité (`check_entity_data_consistency`).

Pour prendre de l'avance sur l'import monitoring, nous avons ajouté une colonne dans la table `bib_fields` permettant d'indiqué l'entité parente. Nous avons aussi ajouté de nouveaux contrôle de type : `numeric` et `boolean`

Une petite refactorisation du code a été effectué :

- Renommage de méthodes (eg. geography -> geometry)
- Code d'erreur sont stockées dans ImportCodeError
- Séparation du code dans `check_transient_data()` de l'import OccHab
- Ajouter de la docstring et des annotations de types dans la déclaration des méthodes

**Comment by camillemonchicourt** [comment]
Fait dans la 2.15 avec l'import multi-destination, l'intégration du module dans le cœur de GeoNature et l'ajout des imports vers le module Occhab.
