### ISSUE TITLE
Compatibilité python 3.4

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#313]
Le code doit être compatible python 3.4
https://github.com/PnX-SI/GeoNature/blob/develop/backend/Pipfile#L44
https://github.com/PnX-SI/GeoNature/blob/develop/geonature_cmd.py#L21

pathlib retourne un code d'erreur sur un server debian 8. ``Path as no attribut read_text``
En vérifiant, l'Objet Path ne comporte effectivement pas cet attribut sur le serveur en 3.4. alors qu'il est présent sur un serveur en 3.5.

**Comment by TheoLechemia** [comment]
Done with https://github.com/PnX-SI/GeoNature/commit/7d081fae61c75c52ff35d385ef130d4f2e233a95
