### ISSUE TITLE
FESP_FRONTEND_1 - Passage sur le frontend de la fiche espèce

### ISSUE THREAD

**Issue by edelclaux** [PnX-SI/GeoNature#3131]
# Epic: "Fiche espèce" [#2981](https://github.com/orgs/PnX-SI/projects/20/views/1?verticalGroupedBy%5BcolumnId%5D=Status&pane=issue&itemId=66942678)

Les derniers éclaircissements ont amené à ajuster un peu les tâches sur le développement de la fiche espèce.
Il s'agit ici de maintenant ici de mettre en place non seulement le design, mais aussi la version MVP de la fiche espèce.

Cette dernière doit comprendre à minima:

- Des propriétés
- Des Indicateurs
- Un onglet Carte des observations
- Un onglet Profile

## Design

Le design sera conforme à la version précédente de cette issue (décrite ci-dessous), à laquelle sont intégrés les retours de Camille dans la discussion autour de cette issue

## Propriétés

- Nom latin
- Identifiant (cd\_nom)
- Noms vernaculaires

> _Qu'en est-il des Groupes INPN ? Souhaite-t-on les faire apparaitre sur la fiche espèce ?_

Les status, picto, le rang taxonomique, etc. seront traités par la suite, dans un espace de travail dédié.

## Indicateurs

Les indicateurs affichés actuellement sont définis pour la validation, sur les plans techniques et métiers.

### Contenu

Actuellement, ce sont des indicateurs liés à la validation.

Nous avons considéré les indicateurs suivants:

- Nombre d'observations
- Nombre d'observateurs
- Nombre d'"areas"

> _Dans les profiles, il y avait les indicateurs suivant: sont-ils à intégrer également à la fiche espèce ?_
>
> - _Première observation_
> - _Dernière observation_
> - _Plage altitude_

### Floutage

> Qu'est-ce que signifie concrètement la prise en compte du floutage au niveau du calcul des statistiques ?
>
> Quelles informations sont sensibles ? Comment les masquer ?

### Format de la route

Nous suggérons que la route utilisée pour le calcul des indicateurs se forme comme suivant:

`/synthese/taxon/stats/<cd_nom>`

-> area\_type as parameter

> _Est-ce que ça vous convient_

## Carte des observations

Même comportement que la synthèse --> Le plus simple ici est l'utilisation de la route _for\_web_, avec cd\_ref en paramètre.

> /synthese/for\_web/\<cd\_ref>

Cette approche permet notamment la prise en compte transparente du floutage.

> _Quelle est la vision de cette route ? Est-ce que c'est un socle sur lequel s'appuyer, ou il y a une envie de désengorger la méthode ?_
>
> _Est-ce que ça vous convient ?_

## Onglet Profile

La, c'est simple, on bouge tout l'actuel dans l'onglet profile

> _Est-ce que ça vous convient ?_

____

## Version Précédente, design uniquement:

Travail sur le frontend de la fiche espèce. On souhaite ici conserver sensiblement le même contenu, en travaillant un peu plus les alignements, en ajustant les espaces, etc.
S'appuyer sur la même stack que le reste de GN.
Ajouter une pile d'onglets avec un mécanisme d'activation ou nom des onglets via la config.
Cette nouvelle série d'entrée dans la config serait:
```toml
[FRONTEND.FICHE_ESPECE]
DISPLAY_COLUMN_XXX = false
```
Il s'agit ici d'un travail portant uniquement sur le frontend. Les nouveaux éléments présents dans la capture d'écran ci-dessous (e.g nouveaux indicateurs) seront traités dans des issues séparées.
![Image](https://github.com/PnX-SI/GeoNature/assets/150020787/db493559-c099-48fd-bcff-c3a213642840)

**Comment by camillemonchicourt** [comment]
Si l'on désactive les infos sur les observateurs car on ne veut pas partager ces infos personnelles à tous les utilisateurs, il ne faut pas seulement les masquer côté Front-end, elles ne doivent aussi ne pas être accessibles niveau backend.

**Comment by edelclaux** [comment]
J'ai un peu survolé de la mise à disposition du contenu des différents onglets, elle sera traitée pour chaque onglet individuellement.
Tu as raison d'étendre la portée de la config à l'app.

Je propose la gestion de la config de la fiche espèce pour ne pas la limiter au frontend:
```toml
[FICHE_ESPECE]
WITH_XXX = false # e.g WITH_OBSERVERS = false
```

**Comment by camillemonchicourt** [comment]
SPECIES_SHEET

**Comment by edelclaux** [comment]
Ok, merci. J'attaque

**Comment by camillemonchicourt** [comment]
OK, merci pour ces compléments de l'analyse technique de ce sujet.

> Qu'en est-il des Groupes INPN ? Souhaite-t-on les faire apparaître sur la fiche espèce ?

Oui, au même titre que les groupes taxonomiques, il sera important d'avoir les différents groupes INPN (1, 2 et 3) auquel appartient le taxon (dans un onglet "Taxonomie" un peu comme on a sur les fiches observations de la synthèse mais avec plus de détails ?). Et pour le picto principal, on s'appuiera surement sur un des groupes (2 comme GN-atlas ?) car ils sont pas mal pour rapidement comprendre de quel type d'espèce il s'agit.

> Dans les profils, il y avait les indicateurs suivant: sont-ils à intégrer également à la fiche espèce ?
> 
> - Première observation
> - Dernière observation
> - Plage altitude

Il faut les remettre dans les profils en effet en l'état.
Certainement en précisant ce que sont les profils et en redisant que les infos dans les profils s'appuient uniquement sur les données valides.

Et les remettre globalement au niveau de la fiche. Mais là les chiffres seront potentiellement différents car ils s'appuieront sur toutes les données, pas uniquement les valides.

Mais là ça soulève une grosse question sur les données des fiches espèces. 
Doit-on prendre en compte les permissions sur la Synthèse et donc aussi la portée.

- Si je n'ai pas de R du tout sur la Synthèse, je n'accède pas du tout aux fiches espèces : ça ça me semble assez logique
- Si j'ai un R de portée 1 oui 2, alors je ne calcule les infos sur les fiches espèces seulement avec mes observations ou celles de mon organisme ??? C'est ce qu'on a fait avec les chiffres globaux sur la Home de GeoNature mais ça veut dire que tout le monde n'a pas les mêmes chiffres sur le nombre de données dans une même instance de GeoNature. C'est cohérent mais un peu bizarre en même temps. 🤔
Et un peu plus lourd à calculer, car si j'ai un R2, alors il faut vérifier que je suis acteur ou mon organisme sur les JDD de chaque observation...
Mais en même temps, c'est bien cohérent avec ce que je verrai sur la carte des observations du taxon sur la carte de la fiche espèce vu qu'on va s'appuyer sur la même route que la Synthèse et donc appliquer la portée du R sur la Synthèse, le floutage, etc...
Donc je pencherai plus sur l'idée qu'il faut appliquer les mêmes permissions et scope etc partout sur tous les chiffres, graphiques, etc. Mais tout le monde ne verra pas la même fiche espèce....

Par contre les profils s'appliquent sur TOUTES les données, sans appliquer de filtres de permissions, et c'est logique aussi car sinon les profils perdent leur sens et raison d'être...
Cela avait d'ailleurs posé quelques soucis car on avait potentiellement accès à des données sensibles dans les profils plus précises que ce qu'on peut voir par ailleurs dans la Synthèse... Je ne retrouve plus la discussions sur le sujet.


> Qu'est-ce que signifie concrètement la prise en compte du floutage au niveau du calcul des statistiques ?
> Quelles informations sont sensibles ? Comment les masquer ?

Globalement il ne faut pas pouvoir accéder à des données sensibles plus précisément dans les fiches espèces que ce à quoi peut accéder par ailleurs dans la Synthèse.
Mais comme ce sont des données synthétisées, je ne vois pas trop de cas. Sauf la carte des observations du taxons mais le sujet est traité ensuite et en s'appuyant sur la même route que la synthèse on aura donc les mêmes permissions et données comme tu le mentionnes.
Mais par exemple dans les fiches observations de la Synthèse, si on a des permissions avec floutage, on n'affiche pas les zonages de taille inférieure au zonage de floutage dans la liste des zonages de l'observation.
A garder en tête donc.

> /synthese/taxon/stats/<cd_nom>
> -> area_type as parameter
> Est-ce que ça vous convient ?

Oui sur la forme, ça nous semble coller.
Mais plutôt `/synthese/taxon/stats/cd_ref/`
Sur `cd_ref` car il faut agréger les calculs sur toutes les observations des synonymes d'un même taxon. Et bien penser à agréger les éventuelles observations sur les taxons inférieurs...
Cette route pourrait renvoyer ces propriétés : 
- first_observation
- latest_observation
- nb_observations
- nb_observers
- alt_min
- alt_max
- medias (sous-objet optionnel si mentionné explicitement dans un paramètre `fields`)
- areas (sous-objet optionnel si mentionné explicitement dans un paramètre `fields` et limité à des types de zonages si spécifiés avec des CODE_AREA_TYPE dans un paramètre `area_types`)

> /synthese/for_web/<cd_ref>
> Cette approche permet notamment la prise en compte transparente du floutage.
> Quelle est la vision de cette route ? Est-ce que c'est un socle sur lequel s'appuyer, ou il y a une envie de désengorger la méthode ?
> Est-ce que ça vous convient ?

Oui comme évoqué c'est très bien d'utiliser la même route qu'ailleurs pour la cohérence, les permissions, le floutage, etc...
On aura donc aussi une éventuelle portée qui s'applique, mais c'est cohérent au regard de ce qui est évoqué plus haut.
Pour la route, elle a un nom et une construction que l'on aimerait revoir pour être plus REST, plus standard et ne plus parler de "for_web", mais c'est un sujet plus global de reprise de l'API de GeoNature pour la rendre utilisable à l'extérieur de GeoNature. Et donc si on la renomme et la revois au niveau de la Synthèse, on le répliquera ici aussi.

> La, c'est simple, on bouge tout l'actuel dans l'onglet profil
> Est-ce que ça vous convient ?

Oui il faudra peut-être en profiter pour caler quelques éléments de vocabulaire. Par exemple parler de "valide" partout (première observation valide, plage d'altitude valide...) et mettre une petite phrase de contexte plus clair.

Et dans le détail `WITH_OBSERVERS` ne nous plait pas trop comme nom de paramètre, mais on en recausera, c'est un détail.

Mais pour ces paramètres, il faudra bien réfléchir pour que ça masque l'onglet, mais aussi l'API, donc peut-être à affiner car le fonctionnement niveau API ne sera peut-être pas homogène si c'est pour les observateurs, pour la carte des observations, les profils, etc...

**Comment by edelclaux** [comment]
Merci pour ces réponses !

### Picto

Je rajoute les informations sur le picto principal dans l'issue dédiée.

### Taxonomie

Je note l'apparition de l'onglet "Taxonomie" :)

Je vais créer une un élément du board dédié à l'affichage des informations de taxonomie + statuts.

- onglet Taxonomie ou format "en-tête"
- information des groupes
- informations sur l'abre taxonomique
- informations des status

### Profile

Ok, merci pour les confirmations.

### Indicateurs Fiche espèce

Ok pour ajouter les mêmes que la fiche espèce.
On aura donc:

- Observations valides
- Première obervations
- Dernière observation
- Plage d'altitude
- Nombre d'observateurs
- Nombre de communes

### Permissions

| Synthese | Fiche Espèce |
| -------- | ------------ |
| R | R |
| R1 ou R2 | R vs Rorganismes |

***Sur le point R vs Rorganismes, comment on tranche ?***

> Profiles: on ne touche pas au calcul actuel

### Floutage

Ok, merci pour les précisions.

### cd_ref

Tout à fait! Je me suis trompé dans mon message..

***A propos --> quel est la bonne pratique pour récupérer, à partir d'un cd_ref, les taxon inférieurs de manière récursive ? \
Vous avez un exemple quelques part ?***

### Nom de paramètres

Pas de soucis, quand vous en trouvez un cool, on le change :)

**Comment by edelclaux** [comment]
Ce serait une bonne idée "Période d'obseration" au lieu de "Première" et "Dernière"

![image](https://github.com/user-attachments/assets/95a26310-27bb-452c-9e2f-3aa72961a2f9)

**Comment by edelclaux** [comment]
Je suis pas sur de savoir comment interpréter les yeux tex avery..
![image](https://github.com/user-attachments/assets/99d4c254-46d5-4749-89fe-6e9c6d0f46f5)

**Comment by camillemonchicourt** [comment]
Que je réfléchis. 🤣

**Comment by DonovanMaillard** [comment]
> Que je réfléchis. 🤣

Tu sais faire ça?! 

Padon... @edelclaux pour moi le terme période renvoie à la période de l'année, surtout sur les profiles et fiches espèces où on aborde plus ou moins les questions de phénologies. En plus, ces infos là permettent de voir un peu ce qu'on a dans la base mais c'est pas des infos qui concernent l'espèce (c'est pas ses dates d'apparition/disparition etc, c'est juste la connaissance qu'on en a). Parler des "bornes", des "premières/dernières observations" etc oui. Période je suis plus dubitatif.

**Comment by DonovanMaillard** [comment]
Pour les questions de données sensibles. Effectivement il ne faut pas que les profils et les fiches espèces "trahissent" la localisation des données qui sont floutées par ailleurs. On peut imaginer un paramètre pour simplement ne pas calculer/servir de fiche espèce et de profil pour les données qui sont sensibles, ou simplement ignorer les données avec une nomenclature "sensible" en synthèse. 

Pour les permissions, le plus logique à mon avis est que chacun ait des infos qui collent aux données auxquel il a accès. Si on a choisi que untel ne peut pas lire les données dans le module synthèse, alors il ne doit pas pouvoir les lire ou les déduire ailleurs, tant que c'est faisable/pas usine à gaz...

**Comment by camillemonchicourt** [comment]
Ouais voilà, pour le terme "période" je réfléchissais à ce que tu expliques justement @DonovanMaillard. 😘
J'aimais bien l'idée de regrouper, raccourcir et simplifier mais ça peut apporter de la confusion la notion de "période".
On est d'accord.

**Comment by gildeluermoz** [comment]
Je partage le point de vue de Camille et d'une manière générale, il faut se poser la question de la pertinence/cohérence et de l'usage des profils pour des personnes qui n'ont pas accès à l'ensemble des données de la base.

**Comment by jpm-cbna** [comment]
> Il y a juste les profils, où la carto peut permettre d'avoir une localisation plus précise que à quoi il a droit dans la Synthèse... Donc éventuellement, masquer la carto des profils si l'utilisateur est censé avoir les observations floutées pour cet espèce. 🤔

Sur la branche `feat/sinp`, effectivement, la carto des profils ne prend pas en compte les données sensibles.  Par contre, il faut également masquer dans l'onglet Zonage, les zonages trop précis vis à vis du niveau de floutage de l'observation. C'est l'objectif du champ `size_hierarchy` de la table `ref_geo.bib_areas_types`. Je ne sais pas si cela a été pris en compte dans l'onglet Zonage sur la branche `master` ?

**Comment by camillemonchicourt** [comment]
@jpm-cbna, il me semble que tu parles de l'onglet "Validation" sur les fiches des observations de la Synthèse.
Le sujet ici sont les fiches espèces par taxons qu'elles prévoient de faire évoluer.

Dans la fiche d'une observation, si celle-ci est sensible et que l'utilisateur ne peut la voir que floutée, alors en effet, on n'affiche pas les zonages inférieurs au zonage de floutage : https://github.com/PnX-SI/GeoNature/blob/master/docs/CHANGELOG.md?plain=1#L89

Pour la carto des profils, si l'espèce est sensible et que l'utilisateur ne peut voir certaines observations que floutées, alors il faut masquer toute la carte plutôt que de l'afficher avec des données partielles, ce qui serait faux par rapport au concept de Profil.
