### ISSUE TITLE
A_DISC_1 - [HOME][DISCUSSIONS] Ajout d'une section "Dernières discussion"

### ISSUE THREAD

**Issue by andriacap** [PnX-SI/GeoNature#3138]
## Description:
On souhaite ajouter une section  "Dernière Discussions" sur la page d'accueil. Voir l'epic #2983.

### Config
Cette section sera optionnelle et désactivée par défault. Sa configuration sera gestion basée sur une nouvelle entrée booléenne (optionnelle, à false par défaut) dans la config:
```toml
[HOME]
   DISPLAY_LATEST_DISCUSSIONS  = true
 ```

### Route et permissions
Cette section reposera sur la route existante de la synthèse suivante: `/synthese/reports?type=discussions`
La prise en compte des permissions est donc déléguée à cette route, et ne nécessitera pas de développement particulier.

La route sera enrichie de deux fonctionnalités: 
- la possibilité de pagination
- la possibilité de renvoyer des informations sur l'observation concernée
   - nom latin
   - observateur: nom prénom
   - date de l'observation

### Redirection vers la synthèse
La version actuelle de la synthèse propose une route dédiée à une fiche d'observation. Cette route ne permet pas d'accéder à un onglet particulier. Un développement est à envisager (voir ticket à définir)

### Frontend
![Image](https://github.com/PnX-SI/GeoNature/assets/150020787/379e8123-26a6-40ed-b71b-ae30caa8d123)
Le design final est à affiner. Il devra intégrer: 
- l'affichage paginée de la liste
- un élément de renvoi vers la discussion et la fiche observation dans la synthèse

### Développements envisagés et discussions

Pour le moment la route GET `/reports` doit frocément fournir `idSynthese` en query params , sinon ça renvoie une 404. 
Est ce que ce comportement est souhaité ?Dans la logique de la route actuelle et pour avoir une API plus REST est ce qu'il ne faudrait plutot pas avoir `/reports/<id_synthese>` , donc `id_synthese` écrire en snake_case plutot qu'en camelCase et l'avoir en path parameters plutôt query parameters ?

Est ce qu'il est souhaité de créer une route disctinte pour requêter sur les discussions  ou est ce qu'on modifie cette la route existante `synthese/reports` et gérer l'absence d" id_synthese dans la requête ?

**Comment by camillemonchicourt** [comment]
OK. Un détail : 
LAST > LATEST

**Comment by andriacap** [comment]
Salut Camille,

Bien vu ! Merci

**Comment by jacquesfize** [comment]
Bonjour à tous,

Ok pour la modification de la route `synthese/reports`, c'est plus logique en effet ! Concernant, la possibilité d'absence d'identifiant de synthèse, ça serait pour récupérer les dernières discussions toutes observations confondues ? Dans tous les cas, il ne faut pas créer une nouvelle route mais plutôt compléter l'existante. C'est une possibilité avec Flask

```python
@routes.route("/reports", methods=["GET"])
@routes.route("/reports/id_synthese", methods=["GET"])
@permissions_required("R", module_code="SYNTHESE")
def list_reports(permissions,id_synthese):
     ....
```

Pour ce qui est de la pagination, c'est très fortement souhaité !

**Comment by andriacap** [comment]
Bonjour Jacques , merci pour ton retour et ta réponse ! 

Ok ça marche pour compléter l'existant ! Et ok pour paginer c'était prévu :) 

On pensait également rajouter des query params pour ne récupérer que les "reports" (discussions) auxquels l'utilisateur connecté à participé . Ce qui permettrait de filtrer les discussions coté clients 

La nomenclature du query params et son implémentation et par défaut à false (vu que ça sera paginé ça devrait pour être pas trop lourd ) . 
- `my_reports = request.args.get("my_reports", 'true').lower() == 'true'

Coté frontend on aurait un bouton  "toggle/switch" . 

Encore merci pour vos retours  !
