### ISSUE TITLE
Charger des assets depuis un module externe

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#314]
Le fichier angular-cli.json permet de lister les répertoires ou se trouve les "assets".
Malheureusement, il n'accepte pas des répertoires exterieurs au projet...

Message d'erreur: 
"An asset cannot be read from a location outside the project."

Voir le bug report sur le sujet : 
https://github.com/angular/angular-cli/issues/8783

**Comment by gildeluermoz** [comment]
Et si on fait un lien symbolique ``my_ext_modules_assets`` dans là où sont localisés les assets du core ?
Est-ce qu'angular suit le lien et n'y voit que du feu ou il bloque ?
Si ça passe, on ajoute le lien symbolique lors de la procédure d'installation du module.

**Comment by TheoLechemia** [comment]
Done: 10d72114618c4724f746653eb02962058abe909d

**Comment by gildeluermoz** [comment]
Yep. Bien joué !
Un soucis plus en moins.
