### ISSUE TITLE
Tooltip des ng-select qui ne disparaissent pas

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#3142]
**Version**
Probablement depuis que la lib ng-select a été intégrée

**Description du bug**
Il arrive parfois que dans les listes déroulantes ng-select la tooltip qui correspond à la valeur survolée ne disparaisse pas quand la souris se place dessus. Du coup ça gène la lisibilité des valeurs suivantes et potentiellement empêche le fait d'en sélectionner une.
Ca semble plus se produire sous chrome ou edge sous windows. J'ai reproduit plus difficilement sous Firefox sous windows. Par contre je n'ai pas réussi à avoir le bug sous linux avec chromium ou je n'ai pas suffisamment insisté. Et j'ai l'impression qu'il faut attendre un peu avec une tooltip ouverte avant de la survoler pour que le problème arrive. 

J'ai préparé une PR pour placer la tooltip à droite de la liste. Maintenant pouvez-vous me dire si ce serait nécessaire de rendre paramétrable le positionnement de ces tooltips via un paramètre [FRONTEND] > NG_SELECT_TOOLTIP_POSITION par exemple ?

**Comment by Pierre-Narcisi** [comment]
Ca me semble être un bon changement, je pense juste pas que ce sois utile d'avoir un paramètre de config pour ca par contre

**Comment by Pierre-Narcisi** [comment]
#3143

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.15
