### ISSUE TITLE
[Validation] sélection des champs à afficher

### ISSUE THREAD

**Issue by blaisegeo** [PnX-SI/GeoNature#3159]
Bonjour;

**Version**
2.14.2

**Description du bug**
Impossibilité de modifier les champs affichés dans le module Validation.

**Comportement attendu**
La modification du fichier ~/geonature/contrib/gn_module_validation/validation_config.toml devrait permettre d'enlever ou d'ajouter des champs dans l'affichage des observations dans la validation delon la doc.

**Comment reproduire**
Copie du fichier ~/geonature/contrib/gn_module_validation/validation_config.toml.example dans ~/geonature/contrib/gn_module_validation/validation_config.toml.
Dernier bloc de 4 lignes (pour le champ "Observateur") commenté.
$ sudo systemctl daemon-reload
$ sudo systemctl restart geonature
Vidage du cache du navigateur, reconnexion à GeoNature.
Le champ "Observateur" est toujours affiché dans les enregistrements de la validation.

**Logs**
Pas d'erreur dans /var/log/geonature.log.

**Comment by camillemonchicourt** [comment]
Pourtant un sujet similaire avait été remonté sur https://github.com/PnX-SI/GeoNature/issues/2498 mais il a bien pu masquer une colonne de la liste des observations du module Validation.

A préciser cependant : Cela ne change les champs que dans la liste des observations du module Validation, pas dans les fiches détail des observations.

Si tu confirmes que cela ne fonctionne pas, il faudra qu'on teste et investigue plus en détail.

**Comment by blaisegeo** [comment]
Je ne faisais pas la bonne manip finalement.

Je copiais le fichier ~/geonature/contrib/gn_module_validation/validation_config.toml.example dans le fichier validation_config.toml dans le même répertoire : ~/geonature/contrib/gn_module_validation/
 et non dans le répertoire ~/geonature/config comme c'est bien indiqué dans la doc et dans l'issue citée plus haut.

J'ai modifié le front et le back à la main pour vérifier que ça réagissait bien, puis j'ai relu encore la doc pour me rendre compte de mon erreur, c'était donc moi le bug !

Désolé pour le bruit.
