### ISSUE TITLE
[Validation] erreur mineure dans un commentaire de default_config.toml.example pour le choix des champs à afficher

### ISSUE THREAD

**Issue by blaisegeo** [PnX-SI/GeoNature#3163]
**Version**
2.14.2

Dans le fichier ~/geonature/config/default_config.toml.example, il est indiqué à la ligne 274 : 

`# La liste des colonnes affichables est celle de la vue gn_synthese.v_synthese_for_export+ nom_vern_or_lib_nom et count_min_max
`

alors qu'il semble que ce soit plutôt les champs de la vue gn_synthese.v_synthese_for_web_app qui sont affichables, non ?

Dans ce même fichier default_config.toml.example, il y a une typo à la ligne 271 : 

`# Choisr le champ 'prop' parmis les colonnes suivantes : `

parmis -> *parmi

**Comment by camillemonchicourt** [comment]
Exact, n'hésite à proposé une correction de cela avec un pull request.
Si tu n'as pas d'environnement GeoNature local, tu peux le faire directement en modifiant les fichiers dans Github.

**Comment by blaisegeo** [comment]
Pull request effectuée.
