### ISSUE TITLE
[map] Erreur affichage ref_geo.l_areas sur cartes leaflet / params = {limit = xxxx}

### ISSUE THREAD

**Issue by marie-laure-cen** [PnX-SI/GeoNature#3168]
**Version**
 2.14.1

**Description du bug**
Les requêtes pour afficher les géométries sauvegardées dans ref_geo.l_areas s'arrêtent au bout de quelques géométries (4 actuellement pour les deux catégories affichées par défaut). J'ai l'impression que ce phénomène se produit depuis le passage à la 2.14.

J'ai corrigé les géométries donc a priori ce n'est pas une erreur provenant de celle-ci.

Je n'ai pas d'erreur de requête réseau a priori et rien dans les logs

![ref_geo](https://github.com/user-attachments/assets/e99333b1-e080-4c14-9bb1-9d1e01cedc03)

**Comment by camillemonchicourt** [comment]
C'est dans quel contexte ?
Pour afficher sur une carte une couche présente dans la ref_geo ?
Il y a eu quelques corrections et améliorations du RefGeo avant la 2.14 (https://github.com/PnX-SI/RefGeo/releases), c'est peut-être un effet de bord. 🤔

**Comment by marie-laure-cen** [comment]
C'est pour l'affichage des cartes via le paramètrage de geonature_config.toml

```
[[MAPCONFIG.REF_LAYERS]]
    code = 'SCEN'
    label = 'Site de catégorie 1 du CEN Normandie'
    type = 'area'
    activate = true
    style = {color = 'DarkRed', fill = true, fillOpacity = '0.5', weight = 2 }
	params = {limit = 5000}
```
![ref_geo_carto](https://github.com/user-attachments/assets/1a5d642b-0d8b-467d-b806-9c06dd9c8af7)

**Comment by camillemonchicourt** [comment]
OK faut qu'on regarde si quelque chose à changer au niveau de la route /geo/areas/

**Comment by gildeluermoz** [comment]
En testant avec les communes sur une de mes instances, c'est le `limit` qui pose pb.
Si tu retires le `limit`, ça renvoit bien toutes les communes, si tu mets un `limit=1000`, ça ne revoit qu'une commune, si tu mets un `limit=2000` ça ne renvoit de 2 communes et un `limit=5000` renvoit 5 communes ...
Vous pouvez tester aussi sur la demo
https://demo.geonature.fr/geonature/api/geo/areas?type_code=COM&format=geojson&limit=2000
https://demo.geonature.fr/geonature/api/geo/areas?type_code=COM&format=geojson

**Comment by marie-laure-cen** [comment]
je confirme que c'était bien ça

**Comment by camillemonchicourt** [comment]
Aille OK, donc y a un soucis avec le LIMIT au niveau de RefGeo.
Certainement un effet de bord de développements entre la 1.4 et la 1.5 : https://github.com/PnX-SI/RefGeo/compare/1.4.0...1.5.3

**Comment by gildeluermoz** [comment]
Le soucis est ici https://github.com/PnX-SI/RefGeo/blob/master/src/ref_geo/routes.py#L230 il faut retirer le `[0]`
J'ai testé et ça corrige pb. Un limit=20 renvoie 20 communes Je fait une PR.

**Comment by gildeluermoz** [comment]
https://github.com/PnX-SI/RefGeo/pull/33

**Comment by gildeluermoz** [comment]
@marie-laure-cen le fix est pour le coup ultra simple à faire sur ton instance.
tu retires le `[0]` ligne 230 dans ce fichier `~geonature/backend/venv/lib/python3.11/site-packages/ref_geo/routes.py`
et tu redémarres le service geonature `sudo systemctl restart geonature.service`

**Comment by marie-laure-cen** [comment]
Merci!

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.15
