### ISSUE TITLE
MapList - Problemes Refresh Filters

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#317]
- Le bouton ne vide pas le champs OBSERVATEURS
- Il ne réinitialise pas les filtres REGNE et GROUPE
- Si on filtre sur un observateur, 2 appuis successifs sont nécessaires sur le bouton pour que la liste de données soit réinitialisée

Bonus : Si je cherche ``test`` dans Observateurs il ne m'affiche pas les relevés dont l'observateur est ``test2`` ni celles dont l'observateur est ``test, test2``.

**Comment by TheoLechemia** [comment]
Premier fix: 13cae672b0ff14922b2d44a858a7a8fb0a2ff90e
