### ISSUE TITLE
Amélioration gestion dossier custom/

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature#3179]
GeoNature possède maintenant un dossier `custom/` à la racine de son arborescence pour y placer des fichiers qui seront utiliser pour surcharger/remplacer des fichiers existants dans d'autres dossier de l'arborescence de GeoNature.

Pour éviter que lorsqu'on clone un dépôt GeoNature, le contenu de ce dossier apparaisse systématiquement dans les **fichiers non suivis** avec la commande `git status`, serait-il envisageable de remplacer le fichier `.gitkeep` par un fichier `.gitignore` qui contiendrait ceci:

```
# Ignore everything in this directory
*
# Except this file
!.gitignore
``` 

Cela aurait l'avantage de maintenir la présence du dossier custom/ vide dans l'arborescence de GeoNature tout en forçant Git à ignorer son contenu qui n'a pas vocation a être ajouté au dépôt.

**Comment by Pierre-Narcisi** [comment]
Il semble possible d'ignorer le contenu du dossier custom en passant directement par le gitignore principale en ajoutant les lignes suiantes : 

```
custom/*

!custom/.gitkeep
```

cela permettrais d'éviter d'avoir plusieurs fichier gitignore

**Comment by camillemonchicourt** [comment]
En effet, il me semble qu'actuellement on privilégie plutôt de tout centraliser dans le gitignore global de GN.

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.15.
