### ISSUE TITLE
MapList - Pouvoir filtrer sur les nomenclatures

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#318]
En n'affichant dans les listes déroulantes que les valeurs qui ont au moins une donnée ?

**Comment by TheoLechemia** [comment]
Fait avec un générateur de filtres dynamique:
bf5ff5362e242fb0b86fd28c0a7c03c9851f7a53
2d84f14f306d7246bec0d580b933c5ab40f7e5aa
1119781d892526cc3e4c361e9391acea42c7f76e
d1375454551dca22d0a94b266807e13e0e21a07d

**Comment by camillemonchicourt** [comment]
C'est fait. Les filtres affichés sont déclarés dans le fichier ``https://github.com/PnX-SI/GeoNature/blob/develop/contrib/occtax/frontend/app/contact-map-list/filters-list.ts``

Actuellement non surcouchable, pas multilingue et ne prend pas en compte la CONF du module qui définit les champs à afficher à la saisie. 

Pourrait être géré au niveau de la BDD pour être modifiable et multilingue.
