### ISSUE TITLE
[FRONTEND] Composant "ModalInfoObsComponent" inutilisé

### ISSUE THREAD

**Issue by edelclaux** [PnX-SI/GeoNature#3186]
Le composant **ModalInfoObsComponent**
`geonature/frontend/src/app/syntheseModule/synthese-results/synthese-list/synthese-info-obs/modal-info-obs.component.{ts, html}` n'est jamais utilisé.

Je suppose qu'il faut le supprimer. Mais je préfère avoir confirmation :)

**Comment by camillemonchicourt** [comment]
Fait dans la 2.15
