### ISSUE TITLE
A_DISC_3 - [HOME][DISCUSSIONS] Améliorer le filtre par l'utilisateur courant

### ISSUE THREAD

**Issue by edelclaux** [PnX-SI/GeoNature#3194]
## Epic [#2983](https://github.com/PnX-SI/GeoNature/issues/2983)

Cette tâche fait suite à la tâche [#3183](https://github.com/PnX-SI/GeoNature/issues/3138) `[HOME][DISCUSSIONS] Ajout d'une section "Dernières discussion"` (voir image ci dessous)

----

La première version du filtre permet de sélectionner les discussions créées par l'utilisateur courant.

On s'intéresse ici à l'élargissement de ce critère aux conditions suivantes : 
- il a **participé** à la discussion concernée
- il a **saisi** l'observation qui est commentée
  ce filtre sera basé sur le champs `id_digitizer`  
- il **fait partie des observateurs**
  ce filtre sera basé sur le champs `cor_observer_synthese`
  L'auteur de l'observation sera naturellement inclus car il fait partie des observateurs

> Le champs "determiner" n'est pas assez fiable pour être pris en compte. Et pas très utile

**Comment by camillemonchicourt** [comment]
En effet il ne faut pas prendre en compte le compte "determiner".

**Comment by edelclaux** [comment]
Ok, merci

**Comment by camillemonchicourt** [comment]
Fait dans la 2.15.
Cependant la pagination n'est pas recalculée quand on filtre les discussions.
