### ISSUE TITLE
[FRONTEND][FORM][UX] Le champ radio bouton requis ne change pas visuellement

### ISSUE THREAD

**Issue by andriacap** [PnX-SI/GeoNature#3210]
Bonjour ,

Je créé cette issue concernant un problème de comportement de composant radio bouton si le formulaire le considère comme étant invalide car "requis".

**Version**
Version de GeoNature affectée par le bug (toutes les versions depuis l'utilisation du radio button  ?) 

**Description du bug**
Même si obligatoire le champ lié au widget "radio button" reste identique (pas de feedback à l'utilisateur permettant d'indiquer que le champ est obligatoire) 

**Comportement attendu**
Le widget de type "radio"  doit avoir une bordure rouge si le champ est requis. 

**Comment reproduire**
Se rendre sur un protocole monitoring ou autre module faisant référence à ce champ radio bouton. 

Une PR de proposition de solution va suivre.

Merci pour vos retours.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.15
