### ISSUE TITLE
Commande Geonature pour charger un MNT

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#323]
Par défaut si le paramètre ``install_default_dem`` est à true, un MNT de toute la France au 250m est inséré en base durant l'installation
Faire une commande pour changer ce MNT par un MNT d'un territoire fourni par l'utilisateur.

**Comment by camillemonchicourt** [comment]
Duplicate https://github.com/PnX-SI/GeoNature/issues/235
