### ISSUE TITLE
Composant Search Taxon et nom FR

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#324]
Quand on cherche un nom FR, n'afficher qu'une ligne correspondant au nom de référence latin.

Voir https://inpn.mnhn.fr/accueil/index

**Comment by TheoLechemia** [comment]
J'ai modifié la table ``vm_taxref_list_forautocomplete`` qui avait quelques incohérences.
Avant le champ ``search_name`` était construit en concatenant le ``nom_français`` ou ``lb_nom`` avec le ``nom_complet_html``. Or le ``nom_complet_html`` contient le ``lb_nom`` du taxon et non son nom valide. Le nom valide, qui est important pour la saisie n'était donc jamais remonté.

Exemple de notre recherche
![rana_avt_zoom](https://user-images.githubusercontent.com/15265745/36203091-a4bd50d0-1186-11e8-9a82-177e84425416.png)

 et celle de l'INPN 

![rana_alpina_inpn_zoom_bis](https://user-images.githubusercontent.com/15265745/36203290-4adff062-1187-11e8-84d7-301256256510.png)

Le ``search_name`` est donc maintenant construit avec le ``nom_valide``

Sauf que cela pose le problème suivant : 
![ablette_zoom](https://user-images.githubusercontent.com/15265745/36203457-f11ad1c2-1187-11e8-8571-ddc8fe21fd0b.png)
On a des doublons quand le ``search_name`` est construit à partir du ``nom_français`` + ``nom_valide`` (puisque c'est le lb_nom qui est différent, et qu'il n'est pas affiché).
Donc on doit enlever les synonymes français dans la sous requête. (ça ne doit pas poser de problème puisque les synonymes français sont déjà concaténé dans le ``nom_français``)

A voir si ce fonctionnement convient. En tout cas à 1ere vue, la recherche parait plus pertinente.

**Comment by camillemonchicourt** [comment]
Dans TaxHub : https://github.com/PnX-SI/TaxHub/commit/30001d552f3945e7b2a5f18dc3457c1a9b4ee69b

**Comment by sig-pnrnm** [comment]
Une fonctionnalité intéressante du moteur de recherche de l'INPN (retenue dans pas mal d'outils naturalistes que j'ai pratiqués), qui ne me semble pas activée dans les moteurs de recherches de GeoNature, c'est la recherche par "morceaux de mots"
Pour saisir une espèce, ne saisir que quelques lettres du nom de genre + quelques lettres du nom d'espèce permet d'aller TRES TRES vite sur l'espèce voulue.

Exemple avec `dro rot` pour `Drosera rotundifolia` : 

![search_espece](https://user-images.githubusercontent.com/26482054/36215434-65b305d0-11ac-11e8-9c4b-3dd448c02c8f.png)

Ca fait gagner du temps, notamment sur les genres où il y a de nombreuses espèces à scroller.

**Comment by camillemonchicourt** [comment]
Si c'est le cas dans GeoNature, on en a déjà parlé. 
Mais il faut à minima saisir les 3 premières lettres de chaque. 
On affine le moteur de recherche là. On a encore des améliorations à intégrer.
