### ISSUE TITLE
[Documentation] Etapes pour la Mise à jour / Montée en version

### ISSUE THREAD

**Issue by naidinp** [PnX-SI/GeoNature#3240]
Bonjour à tous,

Nous devons procéder à une mise à jour de Geonature, TaxHub et UsersHub pour être en phase avec la version OccTax Mobile [décrite ici](https://github.com/PnX-SI/gn_mobile_occtax/releases/tag/2.7.1-rc0) qui résout le problème d'affichage de fond ortho photos sur l'appli mobile.

Actuellement nous sommes en version : 
geonature : 2.11.0v
occtax v2.6.1.3210

Ayant consulté depuis plusieurs jours la documentation (**_est elle à jour ?_**) je trouvé que la trame pour une migration/màj vers la dernière stable est trop peu documenté (peut-être c'est normal)

Quelqu'un/une peut-il me donner les étapes détaillées et la marche à suivre pour réaliser cette migration ? je n'ai pas envie de cracher le serveur de prod, même si je vais réaliser un snapshot et des bkp de la base et du répertoire de l'appli.

Je vous remercie d'avance pour votre aide.

Bonne journée.

**Comment by jacquesfize** [comment]
Bonjour @naidinp,

Le processus de migration est détaillé dans la documentation de GeoNature ici : https://docs.geonature.fr/installation.html#mise-a-jour-de-l-application. Je confirme qu'elle est bien à jour ! 

Voici une trame qui peut vous aider : 
- :warning:  Si vous mettez à jour votre instance GeoNature de prod, faites des sauvegardes !! :warning: 
- Télécharger GeoNature dans la version souhaitée ici : https://github.com/PnX-SI/GeoNature/releases
- Extraire l'archive téléchargée contenant la version souhaitée de GeoNature
```shell
unzip GeoNature-2.X.X.zip
```
- Renommer le dossier contenant la version antérieure de GeoNature en ajoutant le suffixe `_old`
```shell
mv geonature geonature_old
```
- Renommez le dossier extrait de l'archive (par ex. GeoNature-2.14.2) par `geonature` (ou autre si vous souhaitez ! La suite de la trame s’appuie sur `geonature`)
```shell
mv GeoNature-2.X.X geonature
```
- Entre la version de votre GeoNature et la version souhaitée : **lire les différentes notes de versions indiquant les actions administrateurs à effectuer avant le processus de migration** ! Souvent, il s'agit de mettre à jour les modules GeoNature installés (import, export, dashboard, etc.) et/ou de TaxHub et/ou UsersHub.
- Si des mises à jour de modules GeoNature sont nécessaires, comme l'indique la documentation, remplacer le dossier contenant chaque module par un dossier contenant la nouvelle version de ce dernier.
```shell
# exemple pour le module d'import
cd <dossier contenant vos modules GeoNature>
mv gn_module_import gn_module_import_old
wget https://github.com/PnX-SI/gn_module_import/archive/refs/tags/2.3.1.zip
unzip 2.3.1.zip
mv gn_module_import-2.3.1 gn_module_import
```
- Enfin, lancer le script de migration depuis la racine du dossier `geonature` nouvellement crée:
```shell
./install/migration/migration.sh
```
:warning: **Si votre dossier contenant l'ancienne version de GeoNature ne s'appelle pas `geonature_old`, il important de lancer le script de migration avec comme argument le nom de ce dernier** :warning: 

 ```shell
./install/migration/migration.sh <nomdossier>
```

En espérant que cela puisse vous aider !

**Comment by naidinp** [comment]
> Bonjour @naidinp,
> 
> Le processus de migration est détaillé dans la documentation de GeoNature ici : https://docs.geonature.fr/installation.html#mise-a-jour-de-l-application. Je confirme qu'elle est bien à jour !
> 
> Voici une trame qui peut vous aider :
> 
> * ⚠️  Si vous mettez à jour votre instance GeoNature de prod, faites des sauvegardes !! ⚠️
> * Télécharger GeoNature dans la version souhaitée ici : https://github.com/PnX-SI/GeoNature/releases
> * Extraire l'archive téléchargée contenant la version souhaitée de GeoNature
> 
> ```shell
> unzip GeoNature-2.X.X.zip
> ```
> 
> * Renommer le dossier contenant la version antérieure de GeoNature en ajoutant le suffixe `_old`
> 
> ```shell
> mv geonature geonature_old
> ```
> 
> * Renommez le dossier extrait de l'archive (par ex. GeoNature-2.14.2) par `geonature` (ou autre si vous souhaitez ! La suite de la trame s’appuie sur `geonature`)
> 
> ```shell
> mv GeoNature-2.X.X geonature
> ```
> 
> * Entre la version de votre GeoNature et la version souhaitée : **lire les différentes notes de versions indiquant les actions administrateurs à effectuer avant le processus de migration** ! Souvent, il s'agit de mettre à jour les modules GeoNature installés (import, export, dashboard, etc.) et/ou de TaxHub et/ou UsersHub.
> * Si des mises à jour de modules GeoNature sont nécessaires, comme l'indique la documentation, remplacer le dossier contenant chaque module par un dossier contenant la nouvelle version de ce dernier.
> 
> ```shell
> # exemple pour le module d'import
> cd <dossier contenant vos modules GeoNature>
> mv gn_module_import gn_module_import_old
> wget https://github.com/PnX-SI/gn_module_import/archive/refs/tags/2.3.1.zip
> unzip 2.3.1.zip
> mv gn_module_import-2.3.1 gn_module_import
> ```
> 
> * Enfin, lancer le script de migration depuis la racine du dossier `geonature` nouvellement crée:
> 
> ```shell
> ./install/migration/migration.sh
> ```
> 
> ⚠️ **Si votre dossier contenant l'ancienne version de GeoNature ne s'appelle pas `geonature_old`, il important de lancer le script de migration avec comme argument le nom de ce dernier** ⚠️
> 
> ```shell
> ./install/migration/migration.sh <nomdossier>
> ```
> 
> En espérant que cela puisse vous aider !

Bonjour @jacquesfize 

Merci pour ce retour rapide et le détail de cette trame.
Je vais planifier cette migration et vous tenir au courant.

Bonne fin d'après midi.

**Comment by camillemonchicourt** [comment]
OK merci pour ces retours.
J'avais plutôt l'impression que la documentation d'installation et de mise à jour de GeoNature était assez complète. 
Mais si vous avez des suggestions ou compléments, n'hésitez pas à les partager ou à y contribuer.

A noter aussi : 
- Il n'est pas nécessaire d'installer chaque version intermédiaire, vous pouvez passer directement de GeoNature 2.11.x à 2.14.x
- Il faut bien lire les éventuelles notes de version de chaque release de toutes les versions entre celle dont vous disposez et celle que vous allez installé.

Par exemple, GeoNature n'est plus compatible avec Debian 10.
Il y a des évolutions importantes dans la version 2.12 (https://github.com/PnX-SI/GeoNature/releases/tag/2.12.0)
