### ISSUE TITLE
Expiration du token de l'api

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#325]
Au bout d'un moment de navigation sur l'application, l'API fonctionne plus et renvoie que le token est expiré. 
Ce même token est toujours en cookie et n'est pas expiré.

De plus, le système de déconnexion du front (qui vérifie si il y a un token en cookie) ne fonctionne que lorsque l'on change de module (le système est lié au routing d'angular). On peut rester dans un module sans jamais se faire déconnecté, le tout avec un API qui ne répond plus.

**Comment by gildeluermoz** [comment]
J'avais le même genre dans GN1. On avait fait une fonction qui check la validité de la session et on la lançait sur certaine action. Par exemple tout appel au serveur.

**Comment by TheoLechemia** [comment]
Ok merci Gil, c'est fait. 
Sur chaque appel à l'API un intercepteur se charge de vérifier si le token est toujours là. Sinon, redirection vers la page de login

**Comment by camillemonchicourt** [comment]
Expiration du token allongé à 7 jours : https://github.com/PnX-SI/GeoNature/commit/554e28db25e93f9e245790e5c9479dedbbd7998b
