### ISSUE TITLE
[synthèse] URL mal construire pour les médias PDF

### ISSUE THREAD

**Issue by PaulLabruyere** [PnX-SI/GeoNature#3260]
**Version**
détectée sur 2.12.3
confirmée sur le site démo (2.14.2)

**Description du bug**
Bonjour !

Lorsqu'une observation est liée à un média de type "PDF" stockée avec l'instance geonature (dans le dossier `backend/media/attachments`), le média n'est pas retrouvé lorsqu'on cherche à l'afficher dans la fiche de l'observation (module synthèse / validation).

Le problème semble venir de la construction de l'URL : 
* pour les autres types de fichiers stockés sur le serveur (photos, sons, vidéos), l' API appelle une url correcte ".../geonature/api/**/media**/attachments/{media_path}" (avec un / en trop avant media qui ne semble pas gênant)
* mais pour les médias typés PDF, l'url construite est ".../geonature/api/**undefined**/attachments/{media_path}" 

Noter que : 
* Si le pdf est stocké sur un autre serveur (avec l'url complète dasn `media_url`), la fiche synthèse l'affiche correctmeent dans le petit lecteur pdf qui va bien. 
* Si on clique sur le titre du média, il ouvre un nouvel onglet avec l'url correcte, et le pdf est bien retrouvé.
-> Le problème semble donc se limiter à la construction de l'URL pour le lecteur intégré.

**Comportement attendu**
Construire l'URL de la même façon quel que soit le type de média stocké.

**Comment reproduire**
Une observation portant un média "pdf" a été ajoutée sur Occtax. elle est visible [ici](https://demo.geonature.fr/geonature/#/synthese/occurrence/12178).

**Logs**
Avec la console du navigateur activée, ouvrir l'onglet média pour voir la requête en erreur et l'URL erronnée.

**Comment by camillemonchicourt** [comment]
Corrigé par https://github.com/PnX-SI/GeoNature/pull/3266/commits/55f7e76eb1f0a9de4b6dd18877fa1dc91bf8cf9e
A voir si on peut faire autrement qu'un iframe.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.15
