### ISSUE TITLE
Erreur 500 avec utilisation filtres avancés

### ISSUE THREAD

**Issue by mi-cbna** [PnX-SI/GeoNature#3267]
**Version**
Biodiv AURA expert

**Description du bug**
L'erreur "Erreur 500 "apparait en activant certains filtres avancés mais pas avec tous !
ex : Statut biogéographique

![erreur500](https://github.com/user-attachments/assets/1a64778b-f3aa-434a-b8c6-9e1809109d8c)

Bon courage,

Marc

**Comment by jacquesfize** [comment]
Bonjour @mi-cbna, est-ce que tu peux spécifier la version de GeoNature sur laquelle tu as eu ce bug ?
