### ISSUE TITLE
Réduire la liste des filtres avancés ou mieux expliciter ?

### ISSUE THREAD

**Issue by mi-cbna** [PnX-SI/GeoNature#3268]
Version
Biodiv AURA expert

Ce serai bien de réduire cette liste ou alors de mieux expliciter les intitulés de filtres car certains ne sont pas compréhensibles.
Peut-être ne garder que ceux qui sont les plus souvent utilisés.

A voir,

Marc

**Comment by marie-laure-cen** [comment]
bonjour, quels sont les filtres à expliciter ?

**Comment by camillemonchicourt** [comment]
Je suis aussi preneur de précisions ?
Dans quel module ? Quels filtres ? Quelques exemples et propositions ?
