### ISSUE TITLE
Problème d'installation, commande sed : option inconnue pour « s »

### ISSUE THREAD

**Issue by blaisegeo** [PnX-SI/GeoNature#3274]
**Version**
Version de GeoNature affectée par le bug.
2.14.2

**Description du bug**
Description du problème rencontré (message d’erreur, code HTTP de retour inattendu, …).
Sur un serveur tout neuf Debian 12 mis à jour, le script d'installation de GeoNature install_all.sh ne s'exécute pas jusqu'au bout.
Il s'interrompt ainsi : 

...
...
  inflating: GeoNature-2.14.2/tox.ini
  inflating: GeoNature-2.14.2/tslint.json
Installation de la base de données et configuration de l'application GeoNature ...
sed: -e expression n°1, caractère 62: option inconnue pour « s »
geonatureadmin@ici:~$

Cela semble venir de la série de commandes sed ligne 100 et suivantes.
C'est très bizarre, j'ai déjà réalisé plusieurs installations de GN 2.14.2 sur Debian 12 cette année, sans n'avoir jamais rencontré ce problème.
Une idée ?

**Comportement attendu**
Description du comportement attendu en lieu et place du problème rencontré.
Installation complète et réussie.

**Comment reproduire**
Étapes à suivre pour reproduire le problème (sur quelle page se rendre, sur quel bouton cliquer, avec quelles données présentes, …).
geonatureadmin@ici:~$ ./install_all.sh 2>&1 | tee install_all.log

**Logs**
Extrait du fichier ``/var/log/geonature.log`` dans le cas d’une erreur 500.
Fin des logs d'installation ci-dessus.

**Comment by blaisegeo** [comment]
Trouvé !
J'avais un caractère slash (/) dans le mot de passe postgres pour la variable $user_pg_pass, ce que sed n'a pas l'air de trop aimer !
Je ferme l'issue, désolé pour le bruit.

**Comment by camillemonchicourt** [comment]
Le mieux serait quand même la gestion de ce cas, non ?

**Comment by blaisegeo** [comment]
Ca serait préférable, oui, de pouvoir avoir des mots de passe avec des caractères spéciaux. Il faudrait étudier comment gérer ces instructions sed avec n'importe quel caractère spécial.

Je pensais que c'était uniquement le slash ( / ) qui posait problème, j'avais laissé des points d'interrogations ( ? ) dans ce mot de passe de l'utilisateur postgres et ça a également planté l'installation avec une erreur identique à celle décrite sur cette issue #2222 : 
https://github.com/PnX-SI/GeoNature/issues/2222

Je me suis donc limité à uniquement des caractères alphanumériques et là c'est bon.

En attendant que çe "problème" soit résolu, ce pourrait être utilie de spécifier cette limitation dans le choix des caractères de ce mot de passe, dans la documentation d'installation au niveau du paragraphe "Configurez votre installation en adaptant le fichier install_all.ini " ou mieux, dans ce fichier install_all.ini lui-même car c'est assez courant qu'on utilise des caractères spéciaux dans les mots de passe, la plupart des systèmes d'authentification un peu sérieux l'imposent, même.
