### ISSUE TITLE
[GN 2.15] Version minimale du module Monitoring

### ISSUE THREAD

**Issue by JeromeMaruejouls** [PnX-SI/GeoNature#3286]
Dans le changelog de la 2.15, il est spécifié que le module Monitoring doit être mis à jour en 1.0.0 minimum.

Dans le dépot Github, la dernière version est la 0.7.3 : https://github.com/PnX-SI/gn_module_monitoring/releases

Erreur dans le changelog ou alors la version 1.0.0 n'est pas encore sortie ? (je penche sur ça vu le serveur de démo et la gestion des sites !)

**Comment by jacquesfize** [comment]
La dernière version de Monitoring sera bientôt disponible dans les jours qui viennent :) la démo possède une version très proche de la release (branche develop).

**Comment by JeromeMaruejouls** [comment]
Ok, c'est bien ce que je pensais ! Merci pour l'info :)

**Comment by camillemonchicourt** [comment]
En effet, la 1.0.0 de Monitoring est prête et dispo dans la branche `develop` du module Monitoring.
Le changelog est ici : https://github.com/PnX-SI/gn_module_monitoring/blob/release/1.0.0/docs/changelog.md

On fait les derniers tests et correctifs avec @amandine-sahl.

Tout test en testant la branche `develop` de Monitoring avec la 2.15 de GeoNature est bienvenue.
