### ISSUE TITLE
Pouvoir ouvrir dans un nouvel onglet

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#332]
Suite à l'audit : 

L’ouverture dans un nouvel onglet des éléments du menu principal n’est actuellement pas
possible, ce qui limite la productivité d’un outil destiné à la saisie. Il faut s’assurer
notamment que le clic milieu, le clic droit + « ouvrir dans un nouvel onglet » et le Ctrl + clic
soient disponibles.

**Comment by TheoLechemia** [comment]
Done: 2a0464cb684615853fcd110a34520a0e2d0caf57
