### ISSUE TITLE
Search taxon / Rechercher sur debut mot en priorité

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#334]
Actuellement on recherche sur les chaines de caractère. 
En regardant mieux la recherche INPN, il serait plus pertinent de rechercher sur le début des mots. 
Du moins en priorité, quitte à renvoyer les autres résultats à niveau secondaire. 
Pour répondre à https://github.com/PnX-SI/GeoNature/issues/324#issuecomment-365664425 notamment.

**Comment by TheoLechemia** [comment]
Fait avec https://github.com/PnX-SI/TaxHub/commit/109d2c30576b4bf8bd06a9fdd8b9de906d6c7728
On filtre la liste des taxons retournés sur le début de la saisie de l'utilisateur et on affiche en premier les taxon de référence (ordrer_by cd_nom=cd_ref DESC)

**Comment by camillemonchicourt** [comment]
Mais du coup ne rechercher que sur le début du nom du taxon n'est pas forcément idéal. 
Idéalement ça devrait remonter en premier les taxons qui commencent par ce qui est recherché mais aussi cherché au milieu de la chaîne...
