### ISSUE TITLE
BDD - Sensibilité

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#335]
Schéma nomenclature

SENSIBILITY
Modification/ ajout de colonnes :

-  source
-  id (PK) et ajouter contrainte d'unicité
-  actif (oui/non)
-  fk_territoire
-  commentaire

**Comment by DonovanMaillard** [comment]
Bonjour, 

Il est en effet discuté que l'atlas soit adapté par la suite pour un affichage mixte, permettant de traiter ces sensibilités. Dans l'idée encore naissante, on aurait donc un choix à l'install pour avoir des mailles ou des points pour les espèces "normales", mais les espèces sensibles seraient affichées à la maille dans tous les cas : 5km ou commune je crois selon les espèces, puisqu'un standard définit la sensibilité selon différents critères (espèce, statut, avec une notion de durée et de précision de la diffusion soit à la maille soit à la commune). 

Reste à voir qui fait ces adaptations. Selon les couts engendrés, les délais, et le fait qu'on finance ou non un autre développement (en discussion), il est possible que nous (Flavia, en Rhone-Alpes) nous penchions sur le problème, mais peut-être que nous ne serons pas les seuls. En tous cas, c'est bien en discussion, dans le but justement de bien continuer à diffuser la donnée la plus précise possible pour 95% des espèces, mais tout en restant prudents pour des espèces particulières avec ces risques de pillage.

**Comment by DonovanMaillard** [comment]
Camille, il n'y a pas une notion de durée également dans les champs que tu décrits? C'est ce que me disait Gil l'autre jour. De même pour la notion de stades (préciser à quels stades une espèce est sensible?). 

Actif oui/non, c'est pour "ignorer" une sensibilité?

**Comment by AudreyEnGuyane** [comment]
> des  points pour les espèces "normales", mais les espèces sensibles seraient affichées à la maille dans tous les cas
C'est parfait pour moi.

> Reste à voir qui fait ces adaptations.
Je n'ai hélas pas de compétences en développements. Par contre, j'avais proposé de m'atteler aux documentations utilisateur quand les modules seront opérationnels. Ce n'est pas grand chose à ce stade mais bon, si je peux apporter juste ça...

**Comment by DonovanMaillard** [comment]
Je n'ai pas moi même la compétence non plus, mais on pourrait financer un prestataire pour faire ça. En fait on a un premier développement (les modules cartograhiques de l'appli mobile) qui était prévu mais qui sera peut être pris en charge par le parc de la Vanoise. Si c'est la Vanoise qui paye ce module cartographique, notre budget pourrait passer sur la mise à jour de l'atlas pour gérer la sensibilité, c'est en tous cas ce que je proposerai en priorité. 

Une chose qui pourra être commencée bientôt sera un bout de cahier des charges, qui peut se réfléchir à plusieurs. Ca servira de base à celui qui fera le développement, que ça soit nous ou non...

**Comment by camillemonchicourt** [comment]
Concernant la sensibilité dans GeoNature, on a commencé à mettre en place tout un mécanisme de calcul automatique discuté ici https://github.com/PnX-SI/GeoNature/issues/284

C'est bien au niveau de chaque occurrence de taxon que la sensibilité est calculé et définie. 

On se base sur le standard et les règles du SINP pour intégrer un mécanisme standard. 
Les règles ne peuvent pas être définies globalement au niveau d'un taxon, car souvent la sensibilité s'applique à un taxon dans un contexte précis (rapace en nidification mais pas en vol, loup au terriers..).
En effet il y a aussi une notion de durée. 

Par défaut, on intègrera dans la BDD les règles nationales (voir tableau http://www.naturefrance.fr/actions/groupe-de-travail-donnees-sensibles). Chacun pourra y ajouter ses éventuelles règles régionales, voir ses règles locales. 

En fonction des règles, certaines occurrences de taxon se verront attribuer un niveau de sensibilité (maille, commune, département, pas de définition...).

Une fois qu'on aura cette info sur chaque occurrence, elle pourra être utilisée pour les exports vers les partenaires mais aussi pour adapter les affichages dans les outils de diffusion comme GeoNature-atlas. 

Si l'on suit bien les standards, dans l'atlas il faudrait flouter les données concernées mais pas forcément tout un taxon. Ca va poser un problème d'affichage/lisibilité mais on y réfléchit avec le PnCevennes. 

En attendant GeoNature V2, on avait imaginé faire cela à l'espèce : https://github.com/PnEcrins/GeoNature-atlas/issues/117
Mais ce n'est pas vraiment satisfaisant. 

@Donovan, actif (oui/non) c'est en effet pour activer ou non une règle. Pour les durées etc... c'était une ébauche de MCD, on a mis un peu de côté pour le moment.

@AudreyEnGuyane, si tu veux des infos générales sur le projet et l'avancement, tu peux suivre ça dans https://github.com/PnX-SI/GeoNature/issues/168

Voir aussi la doc qui inclut déjà une doc utilisateur mais aussi plein d'autres choses : http://geonature.fr/docs/2-0-0-beta2/
