### ISSUE TITLE
Création module gn_media

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/GeoNature#336]
- [ ] gestion des fichiers
- [ ] controle des noms des fichiers
- [x] routes list, insert, update, delete media

**Comment by camillemonchicourt** [comment]
On duplique ce qui a été fait dans TaxHub ou on en fait un sous-module externe pour pouvoir l'utiliser dans différents projets ?

**Comment by camillemonchicourt** [comment]
Revoir le MCD de gn_media pour appliquer les évolutions discutées ici https://github.com/PnX-SI/GeoNature/issues/339#issuecomment-375716476

**Comment by camillemonchicourt** [comment]
Quelques compléments ont été fait dans le partie backend (https://github.com/PnX-SI/GeoNature/blob/develop/backend/geonature/core/gn_commons/repositories.py) pour l'usage des médias dans le module https://github.com/PnX-SI/gn_module_monitoring

**Comment by camillemonchicourt** [comment]
Fait avec ``gn_commons.t_medias`` et la partie backend associée.
Complet dans GeoNature 2.5.0 (à venir)
