### ISSUE TITLE
Création module gn_monitoring

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/GeoNature#337]
- [ ] Gestion des sites
- [ ] Gestion des visites
- [ ] Gestion des fichiers
- [x] Gestion des configs pour le client

**Comment by camillemonchicourt** [comment]
Le schéma générique ``gn_monitoring`` a été mis en place dans la 2.0.0-rc.1 pour gérer la partie générique des modules de suivi (sites et visites centralisés) et les routes associées.

Ce schéma générique est fonctionnel et est utilisé depuis par 4 modules de suivi : 
- https://github.com/PnCevennes/gn_module_suivi_chiro
- https://github.com/PnX-SI/gn_module_suivi_habitat_territoire
- https://github.com/PnX-SI/gn_module_suivi_habitat_station
- https://github.com/PnX-SI/gn_module_suivi_flore_territoire
