### ISSUE TITLE
Suivi Module Habitat

### ISSUE THREAD

**Issue by vpilorge** [PnX-SI/GeoNature#338]
Bonjour, 

J'ouvre une issue afin de pouvoir discuter et échanger des documents (maquettes, CRs, etc) concernant la création du module Habitat.

Dans un premier temps, vous trouverez en pièce jointe le compte rendu de la réunion du 20 février ainsi que le mcd.

![2018-03-12-mcd_suivi_hab_territoire](https://user-images.githubusercontent.com/37339550/37470055-f2e41b30-2866-11e8-8f6e-a579fa05e9b2.png)
[CR_NS_CBNA_200218-CM.pdf](https://github.com/PnX-SI/GeoNature/files/1815773/CR_NS_CBNA_200218-CM.pdf)

Cordialement, 

Vincent P. (Natural Solutions)

**Comment by camillemonchicourt** [comment]
OK merci pour ce ticket général. 
Ensuite je pense qu'on aura intérêt à mettre en place un dépôt Github dédié au module pour les développements du module. 
Si possible en le créant sur https://github.com/PnX-SI et en vous donnant tous les droits dessus. 

Sinon à noter que @gildeluermoz  a avancé sur la partie générique du MCD de suivi (tables en jaune) : https://github.com/PnX-SI/GeoNature/blob/develop/data/core/monitoring.sql

Et @amandine-sahl a commencé à travailler sur un backend/API pour cette même partie : https://github.com/PnCevennes/projet_suivis_backend_core

**Comment by vpilorge** [comment]
Ok, c’est noté, merci pour le retour rapide et les informations !

Totalement d’accord pour utiliser un dépôt dédié au dev, ce sera plus simple et plus pratique pour discuter et se mettre d’accord.

Vincent

De : Camille Monchicourt
Envoyé le :jeudi 15 mars 2018 15:48
À : PnX-SI/GeoNature
Cc : VincentPilorge; Author
Objet :Re: [PnX-SI/GeoNature] Suivi Module Habitat (#338)

OK merci pour ce ticket général.
Ensuite je pense qu'on aura intérêt à mettre en place un dépôt Github dédié au module pour les développements du module.
Si possible en le créant sur https://github.com/PnX-SI et en vous donnant tous les droits dessus.
Sinon à noter que @gildeluermoz a avancé sur la partie générique du MCD de suivi (tables en jaune) : https://github.com/PnX-SI/GeoNature/blob/develop/data/core/monitoring.sql
Et @amandine-sahl a commencé à travailler sur un backend/API pour cette même partie : https://github.com/PnCevennes/projet_suivis_backend_core

**Comment by camillemonchicourt** [comment]
Voila le dépôt pour le module SHT, dans lequel tu as les droits d'écriture : https://github.com/PnX-SI/gn_module_suivi_habitat_territoire.

**Comment by vpilorge** [comment]
Ok, c'est parfait, merci beaucoup !

2018-03-15 16:13 GMT+01:00 Camille Monchicourt <notifications@github.com>:

**Comment by orovellotti** [comment]
Bonsoir Camille

Il nous faudrait aussi un depot pour le module validation et le module export ?

Merci

**Comment by camillemonchicourt** [comment]
OK. 
- Pour le module Suivi Habitat Territoire, la discussion continue ici : https://github.com/PnX-SI/gn_module_suivi_habitat_territoire/issues/1
- Pour le module Suivi Habitat Station, on fera un dépôt en temps voulu
- Pour le module Interopérabilité (pas export qui est autre chose) suivi par le PNC, j'ai créé le module : https://github.com/PnX-SI/gn_module_interoperabilite
- Pour le module Validation, il faut que je vois avec @sig-pnrnm si il est OK pour qu'on le mette sur https://github.com/PnX-SI/ ou si il faut le mettre sur le Github de leur organisation. Un dépôt avait déjà été créé avec une amorce de module : https://github.com/PnX-SI/gn_module_validation
A voir si on repart de ce travail ou pas.

**Comment by orovellotti** [comment]
Ok bien compris
