### ISSUE TITLE
Intall_db.sh ne prend pas en compte la variable serveur de base de données

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/GeoNature#340]
La base de données est créée sur localhost. Idem pour la suppression

**Comment by amandine-sahl** [comment]
Je n'avais pas fait gaffe au commentaire de settings.ini où c'était clairement indiqué. On peut revenir en arrière sur ma modif

**Comment by gildeluermoz** [comment]
tu le fais ?

**Comment by camillemonchicourt** [comment]
De ce que je comprends, Amandine a fait la modification déjà. 
Mais si je ne dis pas de bêtise, le script installant la BDD, il ne peut pas travailler sur un autre serveur car il n'aura pas les droits de création de la BDD sur un autre serveur. 

Mais si on affine le script en ajoutant plus de paramètre, pour permettre d'installer la BDD GeoNature dans une BDD existante, en installant ou pas les schémas référentiels, alors on pourrait gérer plus de cas comme le souhaitait @amandine-sahl
