### ISSUE TITLE
Création d'une route qui permet de récupérer de façon générique les données d'une vue

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/GeoNature#342]
Utilisation prévu dans le module "monitoring" mais potentiellement utile à tout le monde. A voir où on place le code

- [x] Récupération des données d'une vue non mappée (avec limit, offset)
- [x] Filtres : c-a-d construire des where à partir de paramètres
- [x] Création d'une route

**Comment by camillemonchicourt** [comment]
Excellent. En effet, ça vaut le coup d'ajouter un répertoire pour les routes génériques. 
Genre `backend/geonature/core/utils/` ?

**Comment by camillemonchicourt** [comment]
Fait et fonctionnel.

**Comment by patkap** [comment]
Pardon de réouvrir l'issue, mais il me semble opportun de considérer maîtriser/protéger les accès à la route `generic_view` .

**Comment by TheoLechemia** [comment]
ça me parait complexe (mais nécessaire) de protéger une telle route.
On peut vérifier que l'utilisateur qui interroge à la route a des droit de "Read" supérieur à 0 dans GeoNature. Mais on ne peut pas allé plus loin dans la vérification des droits dans la mesure ou n’importe qu’elle vue peut être interrogée. 
Tu as une autre idée @patkap ?

**Comment by patkap** [comment]
limiter les accés les acces à 0, 1, une liste, une ou plusieurs classe d'ip selon l'activation d'une option en conf ?

**Comment by camillemonchicourt** [comment]
Ça dépend quel est l'objectif ?
Si c'est de ne pas les ouvrir à l'extérieur alors on peut juste les protéger de manière globale avec un user global et générique de GeoNature.
Si c'est d'y appliquer le CRUVED de l'utilisateur alors c'est plus complexe en effet mais sinon on lui applique que le CRUVED global de l'utilisateur sur l'application GeoNature.
