### ISSUE TITLE
Occtax: tous les champs du standards doivent être affichable/masquable

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#344]

**Comment by camillemonchicourt** [comment]
Top, ça donnera bien plus de souplesse à chacun. 
En profiter pour virer le champs Complément méthode détermination, puisqu'on s'est accordé sur le fait de ne garder qu'une liste en la complétant. Déjà dans l'interface puis dans la BDD, le modèle et l'API.

A voir ce que l'on fait avec Technique d'observation, qui est dans Campanule mais pas encore dans le standard d'occurrences de taxons, que l'on a mis au relevé pour le moment mais qui soulève pas mal de questions. Déjà ça permettra de le masquer pour ceux qui le souhaitent. 

A voir à terme ce que l'on fait avec le champs HABITAT, qui si je me souviens bien, est le seul champs de Occurrences de taxons que l'on a pas reporté dans Occtax. Ca serait bien de l'ajouter, vu qu'il est masquable. Mais ce n'est pas juste une nomenclature mais une liste basée sur Habref, donc à creuser un peu plus.
