### ISSUE TITLE
Backup - restore et check inter-tables

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#348]
J'ai essayé de faire un backup puis une restauration de la base GeoNature.

Quand on lance le dump, ce warning s'affiche:

```
pg_dump: NOTICE: there are circular foreign-key constraints on this table:
pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.
pg_dump:   t_nomenclatures
```

Puis quand on lance le restore:

```
t_acquisition_frameworks": ERROR:  Error : id_nomenclature and id_type didn't match. Use nomenclature with corresponding type (id_type). See ref_nomenclatures.t_nomenclatures.id_type
```

En fouillant un peu, je suis tombé sur ça:

https://dba.stackexchange.com/questions/75613/disable-all-constraints-and-table-checks-while-restoring-a-dump (réponse validée).
Il explique que d'après la norme SQL, toutes les contraintes doivent être immutables et ne doivent dépendre que d'éléments qui sont sur la ligne qui est insérée (pas de référence à d'autres table par exemple), puis qu'il faut utiliser les triggers pour faire ce genre de "check"... Or on a beaucoup de check qui font ça (notamment tous les checks sur champs nomenclatures, dans occtax, meta ...)

Jusqu'à maintenant, je n'ai pas réussi à restaurer la base (sauf en virant tous les check) puisque l'installation doit respecter un certain ordre pour fonctionner.

A creuser.

**Comment by camillemonchicourt** [comment]
Faire des triggers risque de poser des problèmes de performances et c'est lourd à mettre en place, maintenir. 

Peut-être plutôt mettre en place une fonction qui désactive/active les check ?

**Comment by amandine-sahl** [comment]
Il faut écrire les contraintes de façon à ce qu'elles apparaissent dans la section post-data ou lieu de pre-data du backup pour éviter tout problème.

**Comment by camillemonchicourt** [comment]
Voir https://dba.stackexchange.com/questions/75613/disable-all-constraints-and-table-checks-while-restoring-a-dump

**Comment by camillemonchicourt** [comment]
OK donc ajouter ``NOT VALID`` à la création de chaque contrainte, les positionne dans le post-data. 
Bon à savoir. Merci pour les modifications.

Exemple : 
```SQL
ALTER TABLE t_occurrences_occtax
  ADD CONSTRAINT check_t_occurrences_occtax_bio_status CHECK (ref_nomenclatures.check_nomenclature_type(id_nomenclature_bio_status,13)) NOT VALID;
```

**Comment by gildeluermoz** [comment]
Ok, nickel. Est-ce que ça se justifie pour les contraintes des FK aussi ?

**Comment by amandine-sahl** [comment]
Non pour les Fk postgresql les gère bien, il insère les données mères avant les filles. Le soucis c'est vraiment les checks avec des selects car il ne les prend pas en compte pour ordonner l'insertion des données dans la section data.

**Comment by camillemonchicourt** [comment]
A tester.

**Comment by camillemonchicourt** [comment]
Fait.
