### ISSUE TITLE
Nomenclatures - Trier par ordre alphabétique

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#350]
A faire au niveau de l'API plutot qu'au niveau du Front

**Comment by TheoLechemia** [comment]
Sur le sous module : 440022646e40b91cc28c3f619bb83279b9d54317

**Comment by gildeluermoz** [comment]
Est-ce qu'il faut envisager d'ordonner les nomenclatures avec un champ ``tri`` ?

**Comment by camillemonchicourt** [comment]
Les tris sont toujours subjectifs.
L'alphabetique le plus simple et rapide à lire selon moi.
