### ISSUE TITLE
Occtax - Saisie - Dates par défaut

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#351]
Lors de la saisie d'un relevé, remplir les dates avec la date du jour par défaut.

**Comment by TheoLechemia** [comment]
Done: 421605ca1639e9bbb3813fa1e53d70493378ec15

**Comment by gildeluermoz** [comment]
Est-ce qu'on remet un bouton hier comme dans la V1 ?

**Comment by camillemonchicourt** [comment]
Je dirai plutot non pour simplifier le plus possible.
Cliquer dans le champs ouvre le calendrier et il a juste à basculer sur la date à hier.

**Comment by RomainBaghi** [comment]
Après avoir testé la saisie de nombreux relevés, je m'aperçois que j'ai souvent oublié de préciser la date. 
Plusieurs collègues mon fait cette remarque aussi et nous pensons que la date du relevé ne doit pas être remplie par défaut car il en résulte beaucoup trop d'oublis. Sur 20 relevés rentrés, j'en ai 7 ou j'ai oublié de modifier la date et pourtant j'étais concentré :)

**Comment by camillemonchicourt** [comment]
OK alors je proposerai l'ajout d'un paramètre au niveau d'Occtax pour activer ou non ce comportement. 
Car nous on utilise ça dans GeoNature 1 depuis de nombreuses années et ça va nickel.
