### ISSUE TITLE
Occtax map-list: clarifier l'interface

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#361]
Problème avec les filtres: les utilisateurs croient que c'est un formulaire.

- [x] Mettre le bouton "ajouter" en bas de la liste
- [x] Mettre un bouton de recherche plus lisible
- [x] Rendre le bouton des filtres avancés plus lisible

**Comment by camillemonchicourt** [comment]
Modifications de l'interface : 
![map-list](https://user-images.githubusercontent.com/4418840/38811832-ecb8223c-418a-11e8-96cc-de55fdebf433.png)
