### ISSUE TITLE
Export shapefile générique

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#366]
Créer un export shapefile générique à partir d'une classe SQLAlchemy

**Comment by TheoLechemia** [comment]
Fait avec : 807297882b5377d94cbeecead80aabc3d958df4a

Création d'un décorateur de classe ``shapeseralizable`` qui ajoute:
- une méthode de classe ``as_shape`` qui crée 3 shapefile (point, ligne, polygone) dans un fichier zipé à partir des données passées en paramètre . Voir son utilisation ici : https://github.com/PnX-SI/GeoNature/blob/develop/contrib/occtax/backend/blueprint.py#L654
- une méthode ``as_list`` qui sérialise un objet de la classe en tableau (pour les besoin de la création du shapefile)

On utilise ici la librairie "pyshp", qui est un librairie légère pour créer des shapefiles, plutôt que OGR et GDAL, beaucoup plus lourde et pas forcément nécessaire pour les besoin que l'on a.

TODO:

[  ] Ajouter un fichier de projection avec la lib "pyproj"
[ ] Gérer la suppression des fichier créer pour soulager le serveur
[ ] Gérer les erreurs

**Comment by TheoLechemia** [comment]
TODO:
- [ ] Ajouter la fonctionnalité de serialisation shapefile au ``GenericTable``
- [ ] Créer une vue générique pour les exports

**Comment by camillemonchicourt** [comment]
Finalement après avoir utilisé pyshp qui posait pas mal de problème d'usage mais aussi d'installation, on bascule sur Fiona (https://pypi.org/project/Fiona/).

**Comment by TheoLechemia** [comment]
TODO:

- [ ] Ajouter un cron qui supprime les fichiers shapefiles créés

**Comment by gildeluermoz** [comment]
On ne peut pas plutôt supprimer systématiquement le fichier dès qu'il est téléchargé par l'utilisateur ?
Ça permet de faire faire le boulot par l'appli et non par le cron qui est un param serveur indépendant de l'appli.

**Comment by TheoLechemia** [comment]
Si ``path_to_zip`` est un paramètre utilisateur, il pourra faire un joli ``rm /* | at now + 7 days`` sur le serveur , une petite bombe à retardement !!

**Comment by Gustry** [comment]
Au développeur de vérifier que le path/to/zip est correct bien sur, que le fichier existe etc :)
J'ignorais que cela pouvait être un paramètre utilisateur.

**Comment by gildeluermoz** [comment]
Pas besoin d'avoir un paramètre qui vient du client. C'est le script qui crée le fichier zip qui va le nommer et qui se charge aussi du rm avec les paramètres proposés par @gustry.

Si tu lances un cron via l'appli, autant lancer directement la ou les commandes que contient le cron. Du coup je ne vois pas trop l'intérêt du cron dans ce contexte.

Je regarde dans gn1 et d'autres applis comment on gère ça. Il y a plusieurs pistes.
L'une d'elle peut être de supprimer tous les fichiers anciens en lisant leurs paramètres de date à chaque fois que tu veux en créer un nouveau. Ainsi tu n'ajoutes jamais un fichier sans avoir nettoyé au préalable les archives.

**Comment by gildeluermoz** [comment]
Le téléchargement, la création d'un fichier, la lecture d'un fichier, sont des commandes système et on le fait dans les applis. Pour un rm, il faut effectivement vérifier que le fichier existe et que le client ne puisse rien envoyer de malicieux en lien  avec l'action.

Je pense qu'il faut creuser la piste de ne pas écrire le fichier avec le "content type" dans le teaser HTML ; sans un chemin de téléchargement. Genre retourner le zip comme tu retournes un json (que tu n'écris nulle part). Dans ce cas, c'est le serveur qui gère l'envoi du contenu.

**Comment by TheoLechemia** [comment]
La solution de vider les répertoire des shapefiles avant d'en créer un nouveau me semble la plus simple.

Et je ne pense pas que ce soit possible d'utiliser le Content-Type comme on le fait avec de JSON ou du CSV.  Dans le cas du shapefile, les librairies qu'on utilise pour les créer écrive de toute façon les fichiers sur le serveur (le .dbf, .shp, .shx etc...). Quand on envoie des fichiers JSON on n'écrit rien sur le serveur, on renvoie quelque chose qui est en mémoire.

**Comment by camillemonchicourt** [comment]
La suppression des fichiers existants avant qu'un nouvel export soit généré a été mise en place : https://github.com/PnX-SI/GeoNature/commit/5315c27cf00e7d28fcc156a6b3999ef34338eb3b
C'est le plus simple. A voir à l'usage si ça ne pose pas de problèmes, par exemple si 2 personnes demandent un export quasiment en même temps. 
Pour éviter ce cas, l'idée d'un répertoire temporaire peut être intéressante. 

Quand il est en train d'être créé, le fichier est écrit dans un autre répertoire (ou sous répertoire), ainsi si quelqu'un d'autre demande un export ça ne supprime pas ce fichier en cours de création. Quand le fichier a été généré dans le répertoire temporaire il est déplacé dans le répertoire des zip et téléchargé par le client. A voir si c'est faisable ?

**Comment by gildeluermoz** [comment]
Il ne faut pas vider le répertoire mais supprimer tous les fichiers de plus de 24 ou 48h.
Tu peux passer une commande du genre :
find /path/to/files* -mtime +2 -exec rm {} \;
Explanation hère :-)
https://www.google.fr/amp/s/www.howtogeek.com/howto/ubuntu/delete-files-older-than-x-days-on-linux/amp/

**Comment by TheoLechemia** [comment]
Fait avec une fonction dans ``filemanager`` qui permet de passer en paramètre la période d'ancienneté (en jour) des fichiers à supprimer
