### ISSUE TITLE
Supprimer trigger gn_monitoring.fct_trg_add_obs_geom() ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#367]
Supprimer le trigger ``gn_monitoring.fct_trg_add_obs_geom()`` permettant de fournir le geom du site à la visite s'il n'est pas rempli pour la visite.
Car il n'est plus utilisé ?

**Comment by gildeluermoz** [comment]
On en est ou de ça, on supprime le geom de visite  finalement ?

**Comment by camillemonchicourt** [comment]
Oui ça a été supprimé : https://github.com/PnX-SI/GeoNature/commit/27e7f1148026d7cb45b948f608b4194973a617d0#diff-f081fae6427554cf6d4de290bba0ca7e
Mais il semble resté un trigger. J'ai vu ça en passant alors je l'ai noté.

**Comment by gildeluermoz** [comment]
DONE : 4b610975412e4816f488cd396825d1dd6705a933
