### ISSUE TITLE
Occtax et geom

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#370]
Au POST, écrire dans la "geom" locale à partir de la geom_4326 (st_transforms).

Voir https://stackoverflow.com/questions/36579355/sqlalchemy-set-default-value-of-one-column-to-that-of-another-column

**Comment by camillemonchicourt** [comment]
Sinon dans la v1 on le faisait en trigger je crois.

**Comment by camillemonchicourt** [comment]
Ouais à voir car ça garantit que les 2 geom sont cohérents. 
Notamment si on edite des données sans passer par l'appli, alors on ne modifie qu'un geom.

**Comment by gildeluermoz** [comment]
Faire une fonction trigger générique qui reçoit en paramètre le nom des champs `geom_4326` et `geom_local` et qui utilise le paramètre global `srid_local` de `gn_meta.t_parameters`

**Comment by TheoLechemia** [comment]
Done
