### ISSUE TITLE
Recentraliser fichiers dans l'arborescence de l'application

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#375]
Le fait d'avoir migré la conf et les logs dans `/etc/` est intéressant pour la mise à jour de l'application. 
Cependant c'est moins lisible et surtout ça bloque les possibilités d'un serveur multi-instance de GeoNature.

En regardant, les applis WEB ne font pas ça (Drupal, Lizmap....). C'est plutôt une logique d'application lourde locale. 

Après discussion avec Amandine, on partirait sur un répertoire `var/` dans GeoNature avec un répertoire `log` et un répertoire `config`.

A voir pour les modules externes si on garde la possibilité de les avoir en dehors de GeoNature, ou si on fait un répertoire `external_modules` à côté de `contrib`.

**Comment by gildeluermoz** [comment]
je vote pour tout mettre dans le répertoire de l'appli.
Il faut aussi un `tmp` dont on pourra personnaliser l'effacement selon le besoin et non brutalement à chaque reboot du serveur (ou du poste de travail du developpeur)

**Comment by camillemonchicourt** [comment]
Banzai !
