### ISSUE TITLE
Déplacer t_parameters dans le schema gn_commons

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#376]
La table `t_parameters` est actuellement dans le schéma `gn_meta`, il serait plus logique qu'elle soit dans `gn_commons`

**Comment by TheoLechemia** [comment]
Done: 2eef21e142eb5452538dbd724bb977a09c26e792

**Comment by amandine-sahl** [comment]
déplacer les routes '/list/parameters', '/parameters/<param_name>/<int:id_org>' dans commons et voir s'il y a des répercussions dans le front (a priori non)
