### ISSUE TITLE
Synthèse SINP, droits sur données précises ou floutées

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#379]
Bonjour, 

J'ai évoqué le sujet avec Camille à quelques reprises. Dans le cas d'un usage multi-structure et SINP de geonature, il est hors cadre que l'accessibilité des données puisse se faire uniquement par organisme (les portées du CRUVED) et ne tienne pas compte des données sensibles. Cette notion de sensibilité ne se gère pas dans le CRUVED et ça me semble aussi bien ainsi pour ne pas tout compliquer, alors que l'usage SINP n'est pas la vocation première de geonature. 

J'y ai réfléchi de mon coté et le plus simple me semblait de créer un nouveau module "Diffusion SINP", qui affiche :
-  les données non-sensibles de manière précise comme dans la synthèse
- et les données dites sensibles (toujours elles...) de manière floutées (maille technique 5x5, 10x10 ou communale) selon les cas. 

L'objectif serait donc de faire un nouveau module, copié sur la synthèse (même interface pour l'utilisateur), mais qui aille chercher ses données sur une vue paramétrable, directement depuis la synthèse. On peut ainsi donner accès à la "diffusion SINP" pour les membres, et un accès à la synthèse (plus complète donc car les données sensibles sont traitées comme toutes les autres) aux collectivités et validateurs (forcément). 
Les possibilités, exports etc ne changent pas, le requêtage, l'interface, pareil. 
Sur ce module diffusion SINP, pas forcement besoin des fonctions de suppression/modification des données mais à la fois, le plus simple est de les laisser comme dans la synthèse et de ne pas les ouvrir avec le CRUVED j'imagine. Par contre naturellement il n'est pas question que ce module puisse intervenir dans la validation. 
Dans le cas d'un usage multistructure avec par exemple 2 structures partenaires, il peut être sympa de laisser Create, Update, Delete pour donner un portail de saisie, duquel on pourrait voir les données de la structure partenaire sauf données sensible? perso je m'en moque un peu, mais ca peut etre une occasion d'ouvrir cette possibilité, à voir et discuter ensemble.

Est-ce que ce module serait susceptible d'intéresser d'autres utilisateurs? Est-ce qu'il vous semble pertinent? Niveau développement, j'ai l'impression qu'il ne faudrait pas grand chose (on reprend la synthèse, on la renomme, on la base sur une vue de la "vraie" synthèse), je me trompe? (ça, ça veut dire combien je prévois sur mes lignes budget? :D )

Merci à vous!

**Comment by camillemonchicourt** [comment]
En soit ce n'est pss pertinent du tout de dupliquer pour y afficher les memes donnees mais en partie dégradées.

Mais ça peut être une bidouille pour arriver resultat souhaité. 

Vu que c'est une duplication d'un module, pas de budget particulier à prévoir. 

A moins qu'il faille ajouter globalement des fonctionnalités à la Synthèse.

**Comment by DonovanMaillard** [comment]
Donc toi tu ferais comment? On ajouterait à la portée "mes données, les données de mon organismes, toutes les données" une portée sur les données sensibles? Mais dans ce cas on se retrouve avec des trucs 'toutes les données pour mon organisme mais seulement les données non sensibles des autres'? 

Je me dis qu'au moins avec ce second module ca peut se gérer classiquement, et surtout la diffusion différenciée des données selon leur sensibilité ne concerne que ceux qui veulent ce module, propre aux SINP sans "embêter" tout le monde ? 

A voir selon les autres avis :)

**Comment by camillemonchicourt** [comment]
Soit on fait comme tu dis, soit on ajoute un tag pour ça dans UsersHub.

**Comment by gildeluermoz** [comment]
Je pensais aussi qu'il faut d'abord explorer la création d'un tag nouveau dédié à ce besoin car il n'est jamais simple de maintenir les dupliquas.
A creuser et évaluer, y compris la traduction en interface.

**Comment by camillemonchicourt** [comment]
Suite à la révision du CRUVED et sa réintégration dand GeoNature (https://github.com/PnX-SI/GeoNature/issues/517), on a abordé les choses différemments, avec des types d'objet sur lesquels s'appliquent les CRUVED. Soit sur des portées, soit une sensibilité, soit des objets géographiques...
