### ISSUE TITLE
Infos complémentaires sur les taxons - A gérer avec une vue

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#38]
Suite à la suppression des champs spécifiques du PNE dans `bib_taxons` (reproducteur, statut_migration, frequence, importance...) et les 3 bibliothèques associées (https://github.com/PnEcrins/GeoNature/commit/ccbdc12e9e2df32aa38dff34afc5d2c460e8de2d), ces infos n'apparaissent plus dans la fiche taxon dans l'appli SYNTHESE.

Pour permettre à chaque structure d'avoir des infos spécifiques sur les taxons, chacun pourra ajouter des champs dans la table `bib_taxons` (+ éventuellement les bib associées). 
L'application affichera le contenu d'une vue `v_infos_taxon` que chacun pourra se construire à sa guise à partir de ses champs spécifiques relatifs au taxon.

**Comment by gildeluermoz** [comment]
Prévoir l'affichage de champs dont le nom et le nombre ne sont pas prédéfini, qu'ils soient dans une vue ou dans une table est très complexe. Rapport faisabilité/intéret à évaluer

**Comment by camillemonchicourt** [comment]
Il s'agirait plutôt de se baser sur les attributs des taxons et non pas sur des champs ajoutés comme imaginé initialement.

**Comment by gildeluermoz** [comment]
C'est une idée mais actuellement il n'y a pas de besoin d'usage précis.

**Comment by camillemonchicourt** [comment]
Si ajd on a mis en dur des filtres taxons Patrimoniaux, Protégé, ... dans le formulaire CONTACT. 
Donc soit on les vire, soit on rend cela générique ?

**Comment by camillemonchicourt** [comment]
Ah non je mélange en fait avec https://github.com/PnX-SI/GeoNature/issues/174
A moins que cela soit lié ?

**Comment by camillemonchicourt** [comment]
Dans GN V2, les attributs de TaxHub peuvent être utilisés dynamiquement pour comme filtres, et être affichés sur le détails de chaque observation. 

Les attributs de TaxHub présents dans la Synthèse de GeoNature sont paramétrables dans la configuration globale de GeoNature.
