### ISSUE TITLE
Application mobile participative pour les ABC

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/GeoNature#382]
En parralèle du "[Module observation citoyenne](https://github.com/PnX-SI/GeoNature/issues/242)" #242 , le Parc Normandie-Maine lance une consultation pour la création d'une application mobile participative pour les ABC (Android + iPhone).
Contrairement au module citoyen, cette application a avant tout un objectif ludique et pédagogique, mais sera selon nous complémentaire à ce module, avec des liens envisageables entre les deux.

Le cahier des charges est disponible à cette adresse : 
[Cahier des charge consultation](http://www.parc-naturel-normandie-maine.fr/observatoire/CdC_Marche_Developpement_Module_ABC.pdf).

**Date limite de réception des offres : le 25 juin 2018 17h**

**Comment by camillemonchicourt** [comment]
Merci pour cet info. 

Quelques compléments/pistes à la lecture du CDC : 
- L'ensemble du module disposerait bien de son propre schéma dans la BDD GeoNature, ce qui permettrait de l'intégrer dans l'environnement GeoNature, ou bien de l'installer indépendamment (comme GN-atlas).
- Ce module pourrait regrouper plusieurs missions, à voir comment gérer ces missions dans la BDD. 
- Ce module pourrait s'appeler GeoNature-mission
- Admin pour gérer les missions, leur description, les images...
- A voir comment gérer de manière générique les infos générales quand on ouvre l'application.
- A voir comment gérer le portail web de restitution ? Est-ce un portail web ouvert qui affiche toutes les observations comme prévu dans GN-citizen ? Ou y a t-il des fonctionnalités quand on est connecté, pour accéder à son compte, ses missions, ses points etc... ?

Dans le schéma de BDD de GeoNature-mission : 
- Une table des utilisateurs (pseudo, login, mdp, email)
- Une table pour leurs points/missions réalisées
- Une table des observations, associées aux missions et utilisateurs, avec photos attachées
- Une table pour gérer les missions. Certaines missions concernent une espèce, d'autres plusieurs. En plus de(s) l’espèce(s), stocker un titre, une description, un niveau, une photo, une période... A voir si chaque missions à un rubriquage similaire (Info espèce, Où trouver l'espèce, Comment l'identifier, Les pièges à éviter) ou sinon les rubriques d'info associées à chaque mission peuvent être gérées de manière générique (titre, picto, texte/image).
- A voir comment gérer le "mission particulière" et les observations associées

**Comment by Adrien-Pajot** [comment]
Slt, 
Qu'est devenue cette appli ? 
On a plus accès au CDC donc je sais pas si on doit garder le ticket ouvert ou juste faire un pont dans la doc vers l'appli si elle existe.

**Comment by samuelpriou** [comment]
GeoNature citizen ?

**Comment by camillemonchicourt** [comment]
Le PNR n'a pas retenu GN-citizen finalement et de mémoire plutôt NOÉ pour faire cette application qui ne semble plus valorisée : https://play.google.com/store/apps/details?id=fr.parc_naturel_normandie_maine.MissionNature
