### ISSUE TITLE
Dépendance entre nomenclatures et taxonomie

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#384]
Pour éviter la dépendance du schéma ``ref_nomenclatures`` au schéma ``taxonomie`` (https://github.com/PnX-SI/GeoNature/issues/374), il faudrait déplacer la table ``cor_taxref_nomenclature`` du schéma ``ref_nomenclatures`` au schéma ``taxonomie``.

C'est ``taxonomie`` qui doit dépendre de ``ref_nomenclatures`` et non l'inverse, comme actuellement.

**Comment by camillemonchicourt** [comment]
Ce point est plus discutable. 
Par contre, une bonne chose serait que la création de cette table de correspondance entre nomenclatures et taxonomie soit dans un SQL à part pour ne pas imposer la dépendance entre ces 2 schémas quand on utilise que les nomenclatures dans un projet sans rapport avec la taxonomie.

**Comment by gildeluermoz** [comment]
Il serait intéressant de créer une carte des dépendances entre schémas. Notamment les 4 schémas référentiels : utilisateurs, taxonomie, nomenclature et géo.

**Comment by camillemonchicourt** [comment]
Oui je les ai indiqué dans le ticket https://github.com/PnX-SI/GeoNature/issues/374

**Comment by camillemonchicourt** [comment]
Après re-discussion sur le sujet, il ressort que cette question est relative aux nomenclature. Il s'agit bien de filtrer les nomenclatures à partir de la taxonomie. 
Cette table garde donc sa place dans le schéma ``ref_nomenclatures``. Cependant pour ne pas imposer la dépendance entre ces 2 schémas, il est retenu de : 

- [ ] Laisser le SQL au niveau du schéma ``ref_nomenclatures`` mais dans un fichier SQL à part pour permettre de l'exécuter ou non lors de la création du schéma (pour ceux qui voudraient le schéma ``ref_nomenclature`` dans un projet autre que GeoNature où il n'est pas question de taxonomie)
- [ ] Créer un ``install_db.sh`` au niveau du dépôt Nomenclature (https://github.com/PnX-SI/Nomenclature-api-module) avec un paramètre dans son ``settings.ini`` permettant de choisir si on installe cette table ``cor_taxref_nomenclature`` ou non
- [ ] Ajouter un paramètre similaire dans le ``config.py`` du module Nomenclatures pour savoir si le lien avec la taxonomie est utilisée ou non (utile au niveau des routes)

**Comment by camillemonchicourt** [comment]
Voir commits : 
- https://github.com/PnX-SI/Nomenclature-api-module/commit/7e938801774a708255fbadfdf2e1b5178e431ea2
- https://github.com/PnX-SI/Nomenclature-api-module/commit/00689581df9616b4f97f3114823856d77a3eddd7

**Comment by camillemonchicourt** [comment]
Concernant le install_db du module nomenclature, c'est noté ici : https://github.com/PnX-SI/Nomenclature-api-module/issues/10
