### ISSUE TITLE
Synthèse - Recherche de taxons

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#385]
Dans la V2, on a évoqué le fait de ne plus faire de lien entre Synthèse et ``taxonomie.bib_noms`` pour permettre d'intégrer des données dans la Synthèse dont les taxons ne sont pas forcément dans ``taxonomie.bib_noms``. Cela simplifierait l'intégration de données partenaires notamment. 

Cependant cela questionne sur la recherche de taxons dans le module Synthèse : 
- Baser la liste des taxons sur une liste (elle-même basée sur ``taxonomie.bib_noms``)
- Baser la liste des taxons sur ``taxonomie.bib_noms``
- Baser la liste des taxons sur tout Taxref

Si on ne veut permettre d'avoir des données dans la synthèse dont les taxons ne sont pas dans ``taxonomie.bib_noms``, seule la troisième solution est cohérente. Cependant c'est dommage d'avoir une énorme liste de taxons dans la Recherche. 

La première solution n'est pas souhaitable car à chaque ajout d'une donnée, il faut l'ajouter dans ``taxonomie.bib_noms`` mais aussi dans une liste. 

La deuxième solution semble donc la plus cohérente, mais nécessite d'avoir tous les taxons présents dans la synthèse dans ``taxonomie.bib_noms``.

**Comment by gildeluermoz** [comment]
La 4ème solution est celle de GeoNature V1. La liste des taxons est un 
``SELECT DISTINCT cd_nom FROM gn_synthese.synthese``
Ca évite aussi de ne pas avoir de réponse vide.

**Comment by camillemonchicourt** [comment]
Ah bah oui, bien vu!
Ça règle les problèmes évoqués. 

Bon avec le CRUVED, il est possible qu'un utilisateur voit des taxons pour lesquels il n'aura pas de résultat mais c'est pas un problème. 

Merci !

**Comment by gildeluermoz** [comment]
J'ai mis une requête simple pour illustrer l'idée mais en V1 on a une vue ``synthese.v_taxons_synthese`` et ``synthese.v_tree_taxons_synthese`` qui remontes des infos taxonomiques mais aussi concernant les statuts et la patrimonialité. On la construit comme on veut.
On peut envisager une vue matérialisée pour les perf avec un refresh qui se fait uniquement si un nouveau taxon qui n'existait pas dans la synthèse y entre.

**Comment by camillemonchicourt** [comment]
OK ça me semble impec. Restons sur une vue pour le moment, et on verra si on les migre en VM, ou libre à chacun d'en faire des VM.

**Comment by camillemonchicourt** [comment]
Par contre si on base la liste des taxons sur un ``SELECT DISTINCT cd_nom FROM gn_synthese.synthese``, alors on ne pas retrouver un taxon par un synonyme pour lequel aucune observation n'aurait été associé au moins une fois. 
A voir si c'est un faux problème ou si il faut aussi proposer les synonymes de tous les taxons présents au moins une fois dans la synthèse.

**Comment by gildeluermoz** [comment]
Le chargement des synonymes, on l'a vu dans l'atlas, multiplie le nombre de propositions par presque 10.
Selon le mode de chargement de la liste, on peut le faire (si on est en ajax, avec autocomplétion basée sur la saisie de l'utilisateur).
Dans ce cas, on peut choisir n'importe quel synonyme et le résultat comporte un regroupement de tous les synonymes du taxons de référence (on utilise le cd_ref). 
Le biais de ça c'est que l'utilisateur tape un nom et le résultat retourne un ou d'autres noms, qu'il ne connait pas et qu'il n'identifie pas instinctivement comme des synonymes. C'est vu comme un bug par l'utilisateur novice. Mais c'est le meilleur compromis.
Ce qui donnerait ceci pour construire la liste :
`SELECT cd_nom FROM taxonomie.taxref WHERE cd_ref IN (SELECT DISTINCT taxonomie.find_cdref(cd_nom) FROM gn_synthese.synthese);`
Et ceci pour le résultat
`SELECT * FROM gn_synthese.synthese WHERE cd_nom IN (SELECT cd_nom FROM taxonomie.taxref WHERE cd_ref = taxonomie.find_cdref(my_given_cd_nom));`

**Comment by camillemonchicourt** [comment]
Oui ça peut compliquer la lisibilité, bonne remarque.
Mais ça dépend aussi comment c'est fait et comment ça remonte. 

Le moteur de recherche de l'INPN recherche dans tout Taxref et ça fonctionne bien : https://inpn.mnhn.fr

On a mis en place un composant similaire dans la saisie Occtax. 
A tester.

**Comment by TheoLechemia** [comment]
Actuellement pour la recherche des taxons d'Occtax on se base sur la table ``taxonomie.vm_taxref_list_forautocomplete`` (une vm qui est en faite une table mise à jour via des triggers lors de l'insertion d'un nom dans une liste).
Cette table ressemble à ça : 
```
SELECT 
concat(lb_nom, '=' nom_valide) as search _name
UNION
concat(nom_vern, '=' ,nom valide) as search _name
 where cd_nom=cd_ref
```
Elle permet de de rechercher en français et en latin sur tous les synonymes. L'effet bug que tu décrit Gil est limité parce qu'on affiche toujours le "nom_valide" dans la proposition, et qu'une fois sélectionné on affiche bien le "nom_valide" dans le champs input.

Le problème c'est que cette table se base sur ``bib_noms`` et sur les listes, donc que si des taxons de la synthese ne sont pas dans ``bib_noms``, il ne remonteront pas pour la recherche.

Je suis assez pour garder ce même mécanisme de recherche dans tout GeoNature. Donc soit on garde l'intégrité en `bib_nom` et les taxons de la synthese, soit on duplique le fonctionnement de cette vue  dans une VM de la synthese que l'on construit à partir de la requête que Gil a fournit (``SELECT DISTINCT cd_nom...``).
Je suis plus partant de la 2ème option, d'autant que ça pourrait nous servir pour améliorer la recherche des taxons dans l'Atlas qui est un peu toute pourrie !

Votre avis ?

**Comment by camillemonchicourt** [comment]
Je suis assez pour pouvoir dé-corréler la Synthèse de ``bib_noms``.
Je suis pour aussi que la logique de recherche soit similaire dans tous les modules.
Par contre selon les modules, la liste des taxons renvoyée n'est pas forcément la même. 

Quand on est sur occtax, c'est bien de rechercher sur une liste (taxons saisissables en l'occurrence) et pas forcément sur les taxons présents dans la Synthèse, tandis que dans la Synthèse on veut remonter une fois chaque espèce présente au moins une fois dans la Synthèse.

**Comment by gildeluermoz** [comment]
Pas sûr de tout bien voir.

Je dirais que le mécanisme du select doit être identique mais que le filtrage : clause where ou condition de jointure doivent varier selon le besoin.

Par ex, créer une vue ou une VM qui remonte les champs du select attendus avec une assise très large, genre le taxref. Ensuite pour occtax jointer sur bib_noms avec les listes, pour la synthèse sur les cd_nom de la synthèse, pour flore la liste dédiée, etc...

Donc on a une base commune qui donne tjs les mêmes champs (le select) et un joint ou un where qui filtre au besoin.


Même avis sur un exit progressif de bib_noms qui est contraignant mais qui est dans le MCD de taxhub (gros travail de migration pour son abandon)

Le cor_nom_liste pourrait s'appuyer sur taxref au lieu de bib_noms

Et cor_taxons_attribut aussi (avec une contrainte check sur cd_ref)


Au passage, je serais d'avis de revoir le MCD de taxonomie pour une v2 pour s'appuyer bcp plus sur taxref.

Supprimer le id_nom

Supprimer bib_noms et la remplacer par une liste du genre 'les_noms_de_ma_structure'

Etendre taxref par  une table 'extent_taxref' ou 'taxref_structure' de manière à stocker tout ce qui est hors référentiels (nouveaux taxons, taxons fournis par des partenaires mais non rattachables, groupes spécifiques ayant du sens localement, etc...). Cette table doit avoir les mêmes champs que taxref de manière à pourvoir faire un union dessus avec taxref.

Appuyer liste et attributs sur taxref et sa fille extent_taxref ou une VM faisant l'UNION des 2.


Sur ce dernier point, il faut creuser la question de l'héritage et des FK dont le contenu serait référencé dans deux tables... Si on ne veut pas faire une vue.





Envoyé de là où je me trouve.

**Comment by camillemonchicourt** [comment]
Oui très intéressant et en effet on est bien raccord sur cette proposition.

**Comment by gildeluermoz** [comment]
> Sur ce dernier point, il faut creuser la question de l'héritage et des FK dont le contenu serait référencé dans deux tables... Si on ne veut pas faire une vue.

J'ai un peu creusé ça et c'est pas possible.

Du coup j'essaie de résumer qq chose qui serait peut-être plus en lien avec une évolution importante de TaxHub :

L'idée de structurer la taxonomie en 2 parties me parait indispensable :
1- le référentiel national taxref,
2- le référentiel de la structure, 
Actuellement bib_noms n'est pas un référentiel. C'est ni plus ni moins qu'une liste extraite de taxref. Du coup on ne peut pas ajouter des taxons absents de taxref. Donc on n'a pas de référentiel de la structure mais on a la contrainte de gérer le contenu de bib_noms comme préalable à tout le reste.

Vient ensuite l'usage et l'enrichissement de ces référentiels avec les notions de listes et d'attributs permettant de développer les besoins locaux.
Si on a deux référentiels dans 2 tables, on aura tjs un dilème : 

- lequel utiliser ? sur quelle table faire pointer les FK ?
- quand 
- et si on a besoin des deux on fait comment ? 

Actuellement bib_noms est au centre des listes et des attributs alors qu'on se base sur cd_nom ou cd_ref, présents dans taxref. En gros bib_noms n'apporte que le choix du nom_fr et depuis peu la possibilité de commentaires.

Je fais les propositions suivantes :

- supprimer `bib_noms` et donc du coup le `id_nom` pourri et totalement inutile car chaque `cd_nom` unique a un `id_nom` unique...
- ajouter un champ `inpn` (true/false) à taxref 
- ajouter les qq taxons du référentiel de la structure à la table taxref avec `inpn`  = false
- ajouter une liste "taxons_structure"
- faire pointer `cor_nom_liste` sur le `cd_nom` de taxref
- faire pointer` cor_taxon_attribut` sur le `cd_nom` de taxref (avec check where cd_nom = cd_ref)
- gérer le nom_français à retenir dans un attribut `nom_fr`

Ainsi :
* on garde toute la richesse de la hiérarchie taxonomique pour nos deux référentiels. 
* on peut les isoler facilement avec le champ `inpn` (migration taxref, export, etc...), 
* on peut établir des correspondances entre le référentiel de la structure et le référentiel INPN avec les champ `cd_ref` et `cd_taxsup` si elles existent,
* TOUTES les références vers cd_nom ou cd_ref (FK ou jointures) se font sur une seule table,
* on peut limiter les requêtes aux taxons de la structure avec la liste "taxons_structure".
* on répond peut-être, au moins partiellement à ce besoin : https://github.com/PnX-SI/TaxHub/issues/159

En complément :
- éventuellement faire une table `t_comments` et `cor_nom_comment` pour attacher un ou des commentaires à un ou pls taxons (ou gérer les commentaires dans un attribut commentaire mais c'est moins souple)
- se poser la question de pourquoi les listes références les noms et pas les taxons et pourquoi les attributs ne référencent que des taxons et pas des noms.
- voir s'il serait pertinent,dans ce contexte, de pouvoir attacher des attributs au cd_nom et pas seulement au cd_ref en créant une table `cor_nom_attribut` et pourquoi pas une `cor_taxons_liste`. Ça devient subtil et ça nécessite de revoir l'interface de TaxHub avec une dichotomie claire entre les noms (cd_nom) et les taxons de référence (cd_ref). Ceci à condition de trouver une bonne raison d'attacher un même attribut avec une valeur différente à deux synonymes. Pour les listes il peut sembler plus évident qu'une liste n'ait pas vocation à accueillir les synonymes mais seulement les taxons de références.

**Comment by camillemonchicourt** [comment]
OK super, intéressant. 
La discussion a été élargie à TaxHub et son MCD et continue ici : https://github.com/PnX-SI/TaxHub/issues/163

Concernant la liste des taxons, on part sur ce qu'on a dit, c'est-à-dire faire une VM dans ``gn_synthese`` avec un ``SELECT DISTINCT`` des taxons présents dans la Synthèse. 

C'est fait : https://github.com/PnX-SI/GeoNature/commit/ec059aa1f89ca3e57616f2af08ce1b3f68ce8aee
