### ISSUE TITLE
SYNTHESE - Basculer le validateur en texte

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#396]
Actuellement il y a un champ ``id_validator`` dans la table ``synthese`` avec une clé étrangère sur ``utilisateurs.t_roles``.
Cela impose d'avoir les validateurs dans la liste des utilisateurs ce qui peut être lourd pour des données n'ayant pas été validées dans GeoNature. 
Pour la synthèse on bascule donc ce champs en texte (character varying) pour faciliter son renseignement. 
D'autant plus que stocker l'``id_role`` du validateur au niveau de la Synthèse n'apporte pas de fonctionnalité. 

Par contre on stocke bien l'``id_role`` du validateur au niveau des données sources saisies dans GeoNature, dans la table transversale de validation.

**Comment by gildeluermoz** [comment]
Il me semble qu'en passant le script d'insertion v1tov2 en synthese j'ai vu que c'était fait.
Closed ?

**Comment by gildeluermoz** [comment]
Vérif en base, c'est fait. 
Mais je ne vois pas la modif dans le sql d'update : 2.0.0beta5to2.0.0.sql
J'ai aussi vu passer d'autres modif sur la taille des varchar qui serait à mettre en update aussi.

**Comment by camillemonchicourt** [comment]
On ne fait pas d'update du schéma Synthèse car il n'était pas installé dans la Beta5 donc personne ne l'a pour le moment. Volontairement car il était pas mur en beta5

**Comment by gildeluermoz** [comment]
Yes ! Bonne nouvelle. Du coup je vais retirer ce que j'ai ajouté concernant le champ id_area.

**Comment by camillemonchicourt** [comment]
Oui, heureusement ! :-)
