### ISSUE TITLE
Occtax - Ne pas renvoyer tous les JDD

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#399]
Certains JDD peuvent correspondre à des données importées ou à d'autres modules et ne doivent pas pouvoir être associés à des observations faites dans Occtax. 

A voir comment filtrer les JDD affichés. 
Certainement en travaillant sur l'association JDD et protocoles/modules. 
A voir aussi si il faut ajouter un champs ``actif`` (ou/non) dans la table des JDD pour ne pas retourner un JDD qui a été utilisé dans Occtax mais qui ne serait plus en cours et donc auquel on ne doit plus pouvoir associer de nouvelles observations. Attention dans ce cas, comment gérer si on modifie une ancienne donnée qui était associée à ce JDD. 

Cela est vrai pour le module Occtax mais aussi potentiellement pour d'autres modules.

**Comment by DonovanMaillard** [comment]
L'association JDD protocoles/modules sera vite indispensable avec l'arrivée de nouveaux modules en effet.

Le "actif oui/non" me semble intéressant pour des programmes terminés par exemple ou des programmes importés, sur lesquels on n'est plus censés écrire de données à minima, voire les modifier (à discuter). Concernant les mises à jours etc, à discuter plus collégialement, mais qu'un jeu soit totalement figé quand "inactif" ne me choque pas, comme c'était plus ou moins le cas sur la V1. Dans ce cas seule la validation reste possible puisque le module validation écrit ces informations de son coté ? 

On pourrait imaginer que le module 'admin", qui permet déjà de gérer les CA et JDD, puisse par la suite permettre de gérer cet aspect ? Que en base, via des tables de correspondance, on puisse dire qui a accès à tel jeu de données et définir s'ils sont actifs ou non ? 
En faisant ça coté métadonnées et éventuellement via le module admin, ca permet de couvrir le cas pour tous les protocoles. 

Une autre idée détail pour la suite, coté occtax. Dans les valeurs par défaut (actuellement limité aux nomenclatures par défaut), pouvoir définir un jeu de données par défaut pour les différents organismes.

**Comment by camillemonchicourt** [comment]
Pour actif (oui/non), ça semble assez utile et relativement simple, même si il faut ne pas renvoyer les JDD au niveau de la saisie mais potentiellement les renvoyer au niveau de la recherche...

Pour les JDD, il faut dissocier le fait de les associer à des modules ou protocoles et les associer à des utilisateurs, groupes ou organismes. 
Cela peut être 2 besoins complémentaires et il faut bien poser le sujet.

**Comment by DonovanMaillard** [comment]
totalement.

Pour le actif, je parle bien niveau saisie, je ne sais pas s'il est pertinent qu'un jdd disparaisse de la recherche (au pire on peut les filtrer dans la synthèse si on veut exclure des JDD).

**Comment by camillemonchicourt** [comment]
Pour commencer, on ajoute le champs ``active`` à ``t_datasets``.
Fait en partie ici : https://github.com/PnX-SI/GeoNature/commit/11be0f94cbb88be2884e44639c8cfac1bb723304
Reste à faire dans le SQL de création de la table et dans le SQL d'update beta5to2.0.0

Ça ne résout pas tous les problèmes car il va vite falloir pouvoir associer des JDD à des modules (et/ou des rôles, et/ou des organismes). 

Mais déjà on liste tous les datasets dans la Synthèse, mais on ne liste que les actifs dans la saisie Occtax. Ainsi on peut intégrer des JDD externes ou historiques qui seront affichés dans la Synthèse mais pas proposés en saisie Occtax.

**Comment by camillemonchicourt** [comment]
En effet il faut donc ajouter une table ``gn_commons.cor_module_dataset`` permettant d'associer des JDD à un module.

**Comment by camillemonchicourt** [comment]
Ce besoin d'associer un JDD à un module s'accentue avec le développement du module Occurrence d'habitats (https://github.com/PnX-SI/GeoNature/issues/735).
A voir où on stocke cette information.

**Comment by jbrieuclp** [comment]
Je pense qu'il est aussi important de gérer l'accès au JDD de manière autonome, sans passer par la notion d'organisme.
C'est à dire avec une table associative de gestion des droits CRUVED par module entre role/groupe et JDD et entre role/groupe et CA.

Peut être qu'en ajoutant la notion de jdd et/ou ca dans `gn_permissions.cor_role_action_filter_module_object` à défaut d'avoir une table associative propre suffirait.

Ceci pour permettre l'accès à des JDD au moins en consultation à des personnes sans lien d'organismes avec ceux renseignés dans les JDD/CA.
De plus l'ensemble des données d'un organismes n'a pas forcément vocation à être diffusé à tous ces membres.

**Comment by camillemonchicourt** [comment]
J'ai l'impression que ça complique les choses et que ça ne permet d'associer des droits par organisme, à moins de recréer des groupes correspondant à des organismes....

Sinon, on pourrait juste permettre de mettre des rôles de type Groupe comme acteur. 
On avait volontairement bloqué cela car un acteur est censé être un utilisateur ou un organisme, mais pas un groupe d'utilisateurs. Cependant c'est peut-être ça qu'il faut revoir.

**Comment by camillemonchicourt** [comment]
C'est surement un autre sujet à traiter dans un sujet dédié du coup.

**Comment by jbrieuclp** [comment]
Pour moi le lien entre un JDD/CA et un organisme ou role est une donnée informative, qui finance, qui produit, qui administre c'est le SINP. Par contre cette association n'a rien à voir, dans la réalité, avec une gestion de droits d'accès aux données.
Là il faudrait porter une grosse réflexion sur le lien utilisateurs/(organisme|groupe) - JDD - Module -CRUVED 
En fait c'est la notion d'organisme et de groupe qu'il faut spécifié, on veut gérer des droits avec l'organisme et des regroupement d'utilisateurs pour simuler un organisme avec les groupes, c'est le bordel !

**Comment by camillemonchicourt** [comment]
Oui sujet complexe, à bien poser et réfléchir avec les autres sujets non réglés sur les questions d'observateurs (notamment https://github.com/PnX-SI/GeoNature/issues/182).
Par contre, pour nous (et le SINP de mémoire) les gestions de droits sont au contraire très liées aux notions d'acteurs des JDD et notamment d'organismes. 
Mais en effet les groupes d'utilisateurs permettent de définir des profils qui ont des permissions et cela n'est pas vraiment le cas dans GeoNature actuellement, donc à clarifier et améliorer en effet.

**Comment by TheoLechemia** [comment]
Fait ici: https://github.com/PnX-SI/GeoNature/commit/ab761dd9711ed832c943a0261506a64913962596

**Comment by camillemonchicourt** [comment]
L'association entre JDD et module a été implémentée avec une table de correspondance dédiée. 
Le module Occtax ne renvoie que les JDD associés au module. 
Lors de la migration, tous les JDD actifs sont associés par défaut au module Occtax (https://github.com/PnX-SI/GeoNature/blob/develop/data/migrations/2.2.1to2.3.0.sql#L17-L22), à chacun d'adapter si besoin, en en retirant certains.

L'association d'un JDD à un (ou plusieurs) module(s) a aussi été implémentée dans le formulaire des JDD : 
![image](https://user-images.githubusercontent.com/4418840/67242694-57dd5a80-f456-11e9-9716-0a989e6d182b.png)

La question des droits sur les JDD et CA par groupe est un autre sujet, à traiter dans un autre sujet. 
@jbrieuclp je te laisse rouvrir un ticket sur ce sujet si tu souhaites.

**Comment by camillemonchicourt** [comment]
Du coup dans le Map-List d'Occtax, le filtre JDD ne renvoie que les JDD associés au module Occtax actifs et inactifs.
Dans le formulaire de saisie d'un relevé Occtax, le champs JDD ne renvoie que les JDD actifs associés au module Occtax.

Idem pour le module Occhab.
