### ISSUE TITLE
GN_monitoring / Date début et fin d'une visite ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#400]
Actuellement on a une date par visite (``gn_monitoring.t_base_visits.visit_date``).
Cependant une visite peut être faite en plusieurs fois pour certains protocoles de suivi. 

Du coup basculer sur 2 champs : 
- ``gn_monitoring.t_base_visits.visit_date_min``
- ``gn_monitoring.t_base_visits.visit_date_max``

A voir ?

**Comment by DonovanMaillard** [comment]
Intéressant aussi pour les suivis chiroptères, papillons de nuit etc qui se font à cheval sur 2 dates, ou les suivis par piégeages par exemple?

**Comment by lpofredc** [comment]
Oui, primordial pour les sessions d'inventaires sur une durée (protocoles d'échantillonages automatisés en général, sessions captures nocturnes). Permet également d'évoquer la notion de pression d'observation (durée d'échantillonnage). Pour cela un timestamp serait idéal mais pas toujours pratique. Pour le projet dbChiro, j'ai scindé l'info en 4 champs (date départ, heure départ, date fin, heure fin).

A voir par contre s'il n'est pas plus judicieux de limiter la date de fin à j+1. Car au delà, on perd de la qualité d'information. En tout cas pour les chiroptères.

--
Frédéric CLOITRE
LPO Ardèche
4bis, rue de la Halle
07110 LARGENTIERE

4 septembre 2018 15:31 "DonovanMaillard" <notifications@github.com (mailto:notifications@github.com?to=%22DonovanMaillard%22%20<notifications@github.com>)> a écrit:
	Intéressant aussi pour les suivis chiroptères, papillons de nuit etc qui se font à cheval sur 2 dates, ou les suivis par piégeages par exemple?

**Comment by camillemonchicourt** [comment]
Fait dans gn_monitoring : https://github.com/PnX-SI/GeoNature/commit/310ba8bee70f8b6da38cb82fd15166b56ab31029

A reporter dans les modules qui l'utilisent (Suivi chiro et Suivi Flore Territoire)
