### ISSUE TITLE
/geonature et /geonature/api sont inaccessibles après une install neuve

### ISSUE THREAD

**Issue by Gustry** [PnX-SI/GeoNature#406]
Après l'installation de `install_all.sh`:
* http://192.168.179.47:8080/taxhub :heavy_check_mark: 
* http://127.0.0.1:8080/usershub :heavy_check_mark: 
* http://192.168.179.47:8080/geonature :negative_squared_cross_mark: 
```
Forbidden

You don't have permission to access /geonature on this server.
Apache/2.4.25 (Debian) Server at 192.168.179.47 Port 8080
```

* http://192.168.179.47:8080/geonature/api :negative_squared_cross_mark: 
```
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /geonature/api.

Reason: Error reading from remote server

Apache/2.4.25 (Debian) Server at 192.168.179.47 Port 8080
```

Je suis allé voir les logs:
```
root@debian9:/home/vagrant/geonature/frontend# tail -n 10 /var/log/apache2/error.log
[Fri Sep 07 11:46:21.028038 2018] [authz_core:error] [pid 7206] [client 10.0.2.2:45368] AH01630: client denied by server configuration: /home/vagrant/geonature/frontend/dist
[Fri Sep 07 11:46:21.216742 2018] [authz_core:error] [pid 7206] [client 10.0.2.2:45368] AH01630: client denied by server configuration: /home/vagrant/geonature/frontend/dist
```
La config d'apache est celle par défaut de l'installation. Mais le chemin indiqué dans la config d'apache n'existe pas:
```
root@debian9:/home/vagrant/geonature/frontend# ls /home/vagrant/geonature/frontend/dist
ls: cannot access '/home/vagrant/geonature/frontend/dist': No such file or directory
```

Je ne suis pas sur de pourquoi je n'ai pas ce répertoire.

**Comment by camillemonchicourt** [comment]
Tu es sur la beta5 ou la develop?

**Comment by Gustry** [comment]
Ah oui, je voulais préciser. Geonature2beta

**Comment by camillemonchicourt** [comment]
Bizarre on a fait plusieurs installations de cette Beta5

**Comment by Gustry** [comment]
C'était sur une debian 9 toute neuve. Je n'ai fait rien d'autres que faire un wget du fichier ini, du fichier SH. J'ai juste modifié le nom de l'utilisateur dans le ini et lancer le script.

**Comment by camillemonchicourt** [comment]
OK idem sur la branche develop ?

**Comment by camillemonchicourt** [comment]
OK merci pour ces retours précieux. On finalise différents points puis on va se lancer dans les nettoyages de l'installation et les tests en vue de la sortie de la 2.0.0 avant le workshop

**Comment by DonovanMaillard** [comment]
La dernière fois que j'ai regardé, les droits geonature n'étaient pas donnés par défaut au compte administrateur test de mémoire ;)

**Comment by Gustry** [comment]
Donc je suis censé ajouter un compte admin dans UserHub?

Et concernant l'atlas, il n'est pas installé par 'install_all.sh'?

**Comment by camillemonchicourt** [comment]
Faut qu'on reteste toute l'installation. C'est possible que le CRUVED de l'utilisateur Admin par défaut ne soit pas correctement renseigné. 

Non pour le moment GN-atlas n'est pas intégré dans le install_all, car on n'a pas encore bossé sur une version de GN-atlas compatible avec la V2. On doit adapter GN-atlas au nouveau schéma de la BDD. 
C'était le cas de l'install_all de la V1 de GeoNature et ça sera le cas plus tard pour celui de la V2. 

Mais là on se concentre sur la sortie de la V2 de GeoNature.

**Comment by DonovanMaillard** [comment]
Pour les tests il suffit, dans l'interface usershub, de donner les droits au compte administrateur déjà existant sur l'application geonature et occtax ;)

**Comment by TheoLechemia** [comment]
Corrigé dans la dévelop

**Comment by Gustry** [comment]
Ok merci

**Comment by Gustry** [comment]
Je viens de retester la version `develop`, et j'ai le même soucis que lors du message initial:
/geonature et /geonature/api sont inaccessibles.

![screenshot from 2018-09-21 08-39-18](https://user-images.githubusercontent.com/1609292/45881677-e24a1b00-bd79-11e8-823f-0deafae18cbd.png)

Je vais essayer de creuser un peu

**Comment by gildeluermoz** [comment]
pourquoi t'es sur le port 8080 ?

**Comment by Gustry** [comment]
GN tourne dans une VM, le port 8080 externe est redirigé vers le port 80 interne de la VM:
https://github.com/PnGuadeloupe/GeoNature-VM-setup/blob/master/Vagrantfile#L8

UsersHub et TaxHub fonctionnent très bien:
![screenshot from 2018-09-21 08-42-34](https://user-images.githubusercontent.com/1609292/45882045-f04c6b80-bd7a-11e8-9766-ec793e885739.png)

**Comment by camillemonchicourt** [comment]
Tu as fait une install-standalone ou un install_all ?
En standalone, il faut que tu fasses la conf Apache.

**Comment by Gustry** [comment]
`install_all`

**Comment by Gustry** [comment]
Même problème, le dossier que cherche à joindre Apache est inexistant: 

 ```
vagrant@debian9:~$ cat /etc/apache2/sites-enabled/geonature.conf | grep 'Alias'
Alias /geonature /home/vagrant/geonature/frontend/dist
vagrant@debian9:~$ ls  /home/vagrant/geonature/frontend/dist
ls: cannot access '/home/vagrant/geonature/frontend/dist': No such file or directory
vagrant@debian9:~$ 
```

**Comment by gildeluermoz** [comment]
sur mon ubuntu, 
cat /etc/apache2/sites-available/geonature2.conf | grep 'Alias'
renvoi
Alias /geonature/ /home/gil/geonature2

**Comment by gildeluermoz** [comment]
EN fait je vois que j'ai une conf apache un peu spéciale ar j'ai aussi GN1 sur ma machine.
Mon alias geonature/ est un lien symbolique placé dans /var/www/html/ !

Je laisse Théo voir ce soucis car je ne sais plus trop comment est géré "officiellement" la conf apache.

**Comment by Gustry** [comment]
Teamviewer a été bénéfique ! :+1: 

On a relancé la commande manquante et c'est bon. Reste à savoir pourquoi elle était pas dans le script SH.

**Comment by xavyeah39** [comment]
Hello, même problème qu'Etienne sur environnement similaire virtual box (à part vagrant) et mêmes logs apache. Par contre j'accède seulement à la page d'authentification de Usershub et quand je me log --> connexion impossible. Intéressé par la commande manquante ;)

**Comment by Gustry** [comment]
@TheoLechemia peut confirmer, mais voila ce que l'on a fait:

```
npm install
npm run start
npm run build
sudo apachectl restart
```

**Comment by TheoLechemia** [comment]
Le ``npm run start`` ne sert à rien, c'était un test (cela lance le frontend en mode develop)
