### ISSUE TITLE
Migration data V1 >> V2

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#407]
Un premier script a été réalisé (à adapter à chaque contexte) : https://github.com/PnX-SI/GeoNature/tree/develop/data/migrations/v1tov2

Il contient : 
- Un fichier de configuration
- Un fichier SH à exécuter pour pour créer une connexion en FDW vers votre BDD GeoNature V1
- Un script SQL qui va récupérer en FDW les données de votre BDD GN1 dans un schéma ``v1_compat``. Il va ensuite vides les tables du schéma ``utilisateurs`` et les remplir avec les données de la V1, puis faire pareil avec le contenu du schéma ``taxonomie``, puis les métadonnées, faire les correspondances des nomenclatures de la V1 avec celles de la V2 basées sur les standards SINP et enfin rapatrier les données dans la Synthèse de GeoNature V2.

**Comment by camillemonchicourt** [comment]
Scripts testés sur les données du PnMercantour

**Comment by camillemonchicourt** [comment]
A nettoyer avant de sortir la 2.0.0 ?

**Comment by gildeluermoz** [comment]
Je ne sais pas ce que tu veux dire par nettoyer. Mais ces scripts ne sont pas du tout aboutis. Il est préférable de les retirer.

**Comment by camillemonchicourt** [comment]
Je pensais à refaire un tour des scripts avec la 2.0.0. 
Les retirer serait dommage je pense, car ils ont déjà été bien utile au PnMercantour.

**Comment by gildeluermoz** [comment]
Oui ils sont certainement à revoir. Mais si on attend d'avoir des scripts de migration propres V1toV2, la V2 n'est pas prête de sortir. 
Il faut décorréler les deux et plutôt sortir la V2 sans ces scripts. Puis migrer des données réelles de la V1 vers la V2 sur la base de ces scripts en les modifiants au fur et à mesure des soucis corrigés en pousser ces modif dans la branch develop. Ce sera déjà un gros chantier. Faire ça à vide n'est pas réaliste. Et de toutes manières on aura jamais un script "presse-bouton", l'écart GN1-GN2 et la personnalisation de chaque instance de GN1 fait qu'on ne peut que proposer des exemples à adapter.
Donc si des utilisateurs ont appliqués les drafts des scripts proposés, ils ont certainement du les modifier pour que ça fonctionne. Il serait bien qu'ils proposent leurs corrections fonctionnelles chez eux.
Pour ce qui me concerne, je ne me pencherai pas sur ces scripts avant le vrai chantier de migration.

**Comment by camillemonchicourt** [comment]
Oui c'est une base à ne pas exécuter les yeux fermés. C'est bien présenté comme ça et il est important de ne pas les retirer du dépôt, pour avoir des retours éventuels. 
Celui du PNM est qu'ils n'ont pas eu d'ajustements particuliers à faire.

**Comment by samuelpriou** [comment]
Effectivement ces scripts nous ont bien servi à migrer nos données de la V1 à  la V2. Cyprien peut en témoigner. Je crois qu'il a fait quelques ajustements notamment pour des scripts sur des protocoles qui ne nous concernaient pas.
Un grand Merci à Gil pour les informations qu'il nous a transmis ! Une vraie réussite ce GeoNature V2 !

**Comment by camillemonchicourt** [comment]
Le PNE est en train de migrer ses données de GN1 vers GN2, du coup les scripts sont entièrement revus en ce moment : https://github.com/PnX-SI/GeoNature/tree/develop/data/migrations/v1tov2

Les précédents ont été mis de côté dans un répertoire ``old``.

**Comment by skerdreuxNaomis** [comment]
Bonjour,

Pour le PNRNM, nous effectuons la migration des données.
A partir d'un clone de la V1 on a effectué une mise à jour de taxhub et userhub vers les version 1.6.2 et 2.0.3 afin de faire un backup de la base v1 pour la restaurer sur une machine disposant de Geonature 2.1.0
Or en lançant un par un les scrips nous avons rencontré une erreur sur le script "users.sql" au niveau de la commande suivante : 

`INSERT INTO utilisateurs.bib_unites(
  nom_unite,
  adresse_unite,
  cp_unite,
  ville_unite,
  tel_unite,
  fax_unite,
  email_unite,
  id_unite
)
SELECT   
  nom_unite,
  adresse_unite,
  cp_unite,
  ville_unite,
  tel_unite,
  fax_unite,
  email_unite,
  id_unite 
FROM v1_compat.bib_unites 
WHERE id_unite NOT IN (SELECT id_unite FROM utilisateurs.bib_unites);
`

après analyse du contenue de la v1 on constate que "bib_unites" n'est pas présente dans la v1 puisque cette dernière a été supprimé par le script "update_1.3.3to2.0.0.sql " de userhubs :
`ALTER TABLE utilisateurs.bib_unites SET SCHEMA save;`

il semble donc que le script de "users.sql" correspondent à une ancienne version de userhubs (1.3.3 ?).

est-ce le script "users.sql" va être prochainement mis à jour ?
de façon plus général est-ce les autres scripts à exécuter pour la montée de version sont à jours ou nécessitent des modifications ?

merci d'avance pour vos réponse.

**Comment by camillemonchicourt** [comment]
Les scripts v1tov2 présents dans la branche ``master`` sont compatibles GeoNature 2.0.1. 
La compatibilité GeoNature 2.1.0 est en cours dans la branche ``develop``. 
Votre problème lié à la table ``utilisateurs.bib_unites`` a été identifié et a été corrigé dans la branche ``develop`` : https://github.com/PnX-SI/GeoNature/commit/559ba4197ff50715c99cb3335c73fca617715271

En effet cette table a été supprimée lors de la mise en place de UsersHub 2.0.0 et nous ne l'utilisons que spécifiquement dans notre contexte PNE.

Sans garantie car en cours de tests, mais les scripts v1tv2 actuellement dans la branche ``develop`` sont plus à jour et compatibles avec GeoNature 2.1.0. 

Ils sont aussi éventuellement à adapter à votre contexte.
