### ISSUE TITLE
Mettre à jour Flask

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#410]
Celui utilisé actuellement a une faille de sécurité.

Passer en 0.12.4

Sinon la 1.0 est sortie récemment.
https://www.developpez.com/actu/200793/Python-Flask-passe-a-la-version-1-0-le-micro-framework-de-developpement-web-se-dote-de-nouvelles-fonctionnalites/

Mais y basculer directement est peut être un peu plus lourd ?

**Comment by camillemonchicourt** [comment]
Fait.
Reste à faire au niveau de Travis.

**Comment by TheoLechemia** [comment]
Fait
