### ISSUE TITLE
Synthèse - Calcul de la sensibilité

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#413]
Le travail de calcul automatique de la sensibilité d'une espèce a été amorcé (https://github.com/PnX-SI/GeoNature/issues/284) mais n'est pas abouti.
Du coup pour le moment on n'est pas en capacité de calculer automatiquement le niveau de sensibilité d'une observation dans la synthèse.

Par ailleurs, une question sur son stockage : 

Le champ sensible de la nomenclature 17 d’occurrence de taxon est égale à oui (97) ou non (96). On peut déduire la sensibilité de la nomenclature 16. Si le cd_nomenclature est = à 0 (68) l’observation n’est pas sensible.
Faut-il ajouter cette nomenclature à la synthèse comme les autres ?
Faut-il ajouter cette information non pas sous forme de nomenclature mais sous forme de boolean ?

A traiter prochainement.

**Comment by TheoLechemia** [comment]
En attendant on ne remplit pas ces champs dans la synthese, ni dans occtax. On vire la ligne de la nomenclature par défaut de la sensibilité dans les deux schémas.

**Comment by camillemonchicourt** [comment]
:-D

**Comment by camillemonchicourt** [comment]
Fin du chapitre 1 sur le sujet !

- Dans la version 2.1.0 de GeoNature les tables, règles et fonctions permettant de calculer et stocker la sensibilité des observations avaient été ajoutées (https://github.com/PnX-SI/GeoNature/issues/284)
- La version 2.6.0 a intégré des triggers pour automatiser le calcul de la sensibilité d'une observation, et le niveau de diffusion qui en découle (https://github.com/PnX-SI/GeoNature/issues/871)
- Les triggers calculant ces informations automatiquement, la possibilité d'avoir des valeurs par défaut pour ces 2 nomenclatures comme évoqué ci-dessus a été supprimé dans la version 2.6.0
- Comme des valeurs par défaut existaient dans des versions antérieures de GeoNature, il est possible que vous ayez déjà des valeurs pour ces champs, remplis avec les valeurs par défaut définies auparavant dans la BDD, et non pas sur les règles de sensibilité
- Certains ont aussi pu renseigner explicitement ces champs pour forcer des valeurs de niveau de sensibilité ou de niveau de diffusion
- C'est pourquoi dans le script d'update des données existantes, on ne calcule la sensibilité et le niveau de diffusion, uniquement si leurs valeurs sont nulles : https://github.com/PnX-SI/GeoNature/blob/develop/data/migrations/2.5.5to2.6.0-update-sensitivity.sql
- A chacun de voir si il veut aller plus loin et écraser les éventuelles valeurs qu'il aurait déjà renseigné pour ces 2 nomenclatures
- On relance le calcul de la sensibilité si certains champs d'une observations sont modifiés (https://github.com/PnX-SI/GeoNature/blob/develop/data/core/synthese.sql#L1042), mais cela ne modifie pas le niveau de diffusion qui n'est calculé que si il est nul. A affiner...
- Lors de l'insertion, on ne calcule le niveau de sensibilité automatiquement, que si il n'est pas fourni explicitement
- Un autre principe retenu est de privilégier le fait que le niveau de sensibilité est toujours calculé automatiquement, en se basant de manière objective sur les règles de sensibilité dans la BDD, alors que le niveau de diffusion peut être surcouché manuellement, de manière subjective, pour avoir une diffusion plus précise ou moins précise que ce qu'indique le niveau de sensibilité

Pour cette première phase, on a donc retenu une approche prudente, pour éviter d'écraser des éventuelles valeurs renseignées manuellement dans ces 2 nomenclatures.

Cependant il est important de garder en tête le principe fort de la synthèse, dont toutes les informations doivent être calculables (automatiquement ou depuis une table source).
Ainsi si vous avez des données dont vous souhaitez spécifier un niveau de sensibilité ou de diffusion différent que ceux calculés automatiquement, vous devez les stocker dans la table source, ou dans une table dédiée pour en garder l'information source, et pas uniquement stocker l'information surcouchée dans la synthèse.

A noter aussi que les nomenclatures des niveaux de sensibilité actuellement fournis par le SINP ne sont pas claires ni cohérentes. En accord avec le SINP, nous avons fait évoluer leurs intitulés : ticket https://github.com/PnX-SI/Nomenclature-api-module/issues/39

A venir dans un chapitre 2 : 

- Mettre en place un vrai mécanisme de stockage d'un niveau de diffusion surcouché, pour pouvoir identifier une valeur renseignée automatiquement par les règles ou surcouchée manuellement. Idem pour les niveaux de sensibilité ? Même si ceux-ci sont moins censés être surcouchés manuellement et entièrement être basés sur les règles de la table dédiée que l'on peut désactiver ou enrichir
- Mettre en place un système pour calculer les niveaux maximum quand plusieurs règles ou valeurs s'appliquent
- Mettre en place un mécanisme permettant de mettre à jour les niveaux de sensibilité et de diffusion quand une donnée ou une règle évolue, en écrasant les valeurs automatiques, mais pas les éventuelles valeurs manuelles
- Mettre en place un mécanisme de recalcul régulier des sensibilités temporaires
- Et bien sur, permettre le floutage des données en fonction du niveau de diffusion et des droits de l'utilisateur (https://github.com/PnX-SI/GeoNature/issues/877)

**Comment by camillemonchicourt** [comment]
A voir aussi sans trop traîner : 
- Les actions à réaliser quand on fait évoluer le référentiel de sensibilité ou qu'on ajoute des règles dans la table des règles de sensibilité. Actuellement il faut à minima rafraîchir la VM ``gn_sensitivity.t_sensitivity_rules_cd_ref`` (https://github.com/PnX-SI/GeoNature/blob/master/data/core/sensitivity.sql#L107) mais ce n'est actuellement ni automatisé, ni clairement indiqué quelque part...

**Comment by amandine-sahl** [comment]
A mon sens le plus simple c'est de faire une vue. Ce n'est pas une requête très complexe
