### ISSUE TITLE
Fonds carto - Configuration en double ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#414]
Les fonds sont dans 2 fichiers : 
- frontend/src/conf/app.config.sample.ts
- frontend/src/conf/map.config.ts.sample

Normal ?

**Comment by TheoLechemia** [comment]
Ces fichiers ne sont pas utilisés car il sont généré par la conf du backend.
On les supprime.

**Comment by camillemonchicourt** [comment]
``map.config.ts.sample`` est gardé car utile. En effet la conf carto est à part dans ``frontend/src/conf/map.config.ts.sample``
