### ISSUE TITLE
ID auto-incrémentés

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#416]
Au niveau des créations de table, certains sont en INTEGER avec une SEQUENCE créée en SQL.
D'autres sont en SERIAL. 

Il me semble que des SERIAL c'est plus simple et niveau SQL mais surtout c'est plus lisible que c'est auto-incrémenté quand on consulte la structure de la table. 

@gildeluermoz , une raison pour faire plutôt des INTEGER avec une séquence ?

**Comment by gildeluermoz** [comment]
A vérifier mais si tu ajoutes une séquences et que tu l'utilises le champs qui l'utilise pas en serial.

Pas d'intérêt particulier sinon que d'avoir le code de création de la séquence sous la main pour la dropper ou la modifier et de gérer son nom. Mais on peut parfaitement faire autrement et plus simple en mettant directement le champ en serial.

**Comment by camillemonchicourt** [comment]
Exact, si la table a été créée en INTEGER avec une séquence, quand on consulte la table, le type est indiqué en SERIAL.

Top ça.
