### ISSUE TITLE
Admin - Dataset - Update non fonctionnel

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#420]
Impossible de MAJ un JDD

**Comment by TheoLechemia** [comment]
Fait avec https://github.com/PnX-SI/GeoNature/commit/f9f82002c9a73ac88c74c34d86b0e546762e4343, https://github.com/PnX-SI/GeoNature/commit/85b703e508ee92e47e041b93a63d22b5e319c3c4 et https://github.com/PnX-SI/GeoNature/commit/e67abc03089cd79de201e2df661e62c318d26aa4
