### ISSUE TITLE
Sidebar - Ajouter numéro de version

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#421]
Lire le fichier VERSION et afficher sa valeur dans le footer : 

```
Réalisé avec <a href="http://geonature.fr" target="_blank">GeoNature</a> version <a href="https://github.com/PnX-SI/GeoNature/releases" target="_blank">XYZ</a>
```

**Comment by gildeluermoz** [comment]
DONE : 5aec0eaa9592b9ac4313b40f052ec37867ff6ce3

**Comment by gildeluermoz** [comment]
Camille, je te laisse checker la meilleure manière d'intégrer le nouveau paramètre dans les notes de version. J'ai mis qq chose dans le changelog mais ... pas trop sur de moi.

**Comment by camillemonchicourt** [comment]
Ah OK c'est dommage de devoir rajouter un paramètre pour ça. 
J’espérai que le frontend puisse lire le fichier VERSION en direct mais il ne lui est peut-être pas accessible.

**Comment by camillemonchicourt** [comment]
Mais en plus là, ça va pas se mettre à jour à chaque MAJ de GeoNature... ?

**Comment by camillemonchicourt** [comment]
Concernant les nouveaux paramètres, l'idée est de ne pas imposer de les ajouter et ne pas avoir à les mentionner dans les Notes versions. 

On maintient un fichier ``config/default_config.toml.example`` qui liste tous les paramètres surcouchables et leurs valeurs par défaut.

**Comment by gildeluermoz** [comment]
Oui j'ai essayé mais je n'ai pas réussi. On peut le faire si le fichier se nomme version.js et si le texte est entouré de quotes car les points du numéro de version correspondent à de la notation objet en json.
Il y'a certainement d'autres pistes, notamment de demander a python de lire ce fichier et de mettre a jour un fichier de conf  js ou json. 
Côté front, on peut pas lire un fichier coté serveur. Faut que ça se passe lors du build et donc que ça finisse dans un .ts ou un .js ou un .html
Je reprendrai ça proprement mais tu ne peux pas changer le contenu du fichier VERSION et que le front le charge directement sans lancer qq chose comme un update_configuration.

**Comment by gildeluermoz** [comment]
Simplification et nettoyage : 5a2ea7ef24e3adef526ed1ad1532080f6f274d0a b9461590f277c8797812c27ce9e1349d70dd3c2f

**Comment by gildeluermoz** [comment]
Si le contenu du fichier VERSION change : 
```
cd backend
source venv/bin/activate
geonature update_configuration --build false
```

**Comment by camillemonchicourt** [comment]
Ça me semble joli comme ça. A voir si cette commande est intégrée dans le script migration.sh exécuté quand on met à jour GeoNature.

**Comment by sig-pnrnm** [comment]
question bête : ne serait-il pas envisageable/utile de stocker (aussi) le numéro de version en BDD ?
