### ISSUE TITLE
Conflits sessions GeoNature / TaxHub

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#423]
Quand TaxHub et GeoNature sont installés sur le même serveur (la plupart des cas), quand on se connecte sur TaxHub cela créé une nouvelle sessions pour le même domaine. 
Du coup si on retourne sur GeoNature après cela, GeoNature détecte le token mais il ne correspond plus. 
Cependant il ne nous déconnecte pas. Du coup on reste dans GeoNature mais avec seulement 2 modules et ceux-ci sont vides de données. 

Il serait mieux d'être déconnecté dans ce cas.

**Comment by TheoLechemia** [comment]
Fix provisoire.
On déconnecte l'utilisateur de geonature si la route '/modules' renvoie une 403 lié au problème de token.
Il serait mieux que taxhub et geonature mette un nom de token différent dans le localstorage. 
Il y a surement des modif à faire au niveau du sous module d'authentification

**Comment by camillemonchicourt** [comment]
Corrigé plus globalement dans le sous-module d'authentification version 1.3.2 : https://github.com/PnX-SI/UsersHub-authentification-module/releases/tag/1.3.2
