### ISSUE TITLE
soucis avec les altitudes

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#424]
2 soucis :
1/ sur le front il est possible de saisir une altitude min supérieure à l'altitude max, pas d'alerte mais comme en base il y a une contrainte check, l'enregitrement ne passe pas.
2/ les altitudes min et max présentes en base ne remontent dans le formulaire en modification

**Comment by camillemonchicourt** [comment]
En effet pour le soucis 1, ça indique "Une erreur s'est produite" et on ne peut plus modifier le formulaire pour corriger en Enregistrer.

En effet pour le soucis 2, si on modifie à la main une altitude, c'est bien celle-ci qui est enregistrée, mais quand on revient éditer le relevé, il l'affiche puis instantanément, il réaffiche la valeur calculée par le marqueur. Peut-être à garder pour une prochaine version.

**Comment by gildeluermoz** [comment]
Dans ma base je n'ai pas les MNT. Donc il n'affiche rien sur les altitudes calculées du marqueur.
Si on garde ce comportement, potentiellement on scratche les altitudes non calculées mais fournies/corrigées par l'utilisateur qui seront remplacées silencieusement par l'interface, chaque fois qu'il ouvrira son obs en modification...
Si tu n'installes pas de MNT, toutes les altitudes fournies sont effacées...
Un peu lourd comme bug je trouve.

**Comment by camillemonchicourt** [comment]
Oui oui c'est à régler pour la 2.0.0, pas forcément pour la 2.0.0.rc1. :-)

**Comment by camillemonchicourt** [comment]
Vérification que altitude MAX soit supérieur MIN fait : https://github.com/PnX-SI/GeoNature/commit/4ca35f86173c695740ec911602007d7a27a81f1c
Ainsi que le bouton VALIDER réactivé après message d'erreur.

Reste à voir les altitudes modifiées recalculées par le Front quand on édite un relevé. 
Il faudrait relancer le calcul que si on modifie la géométrie du relevé.

**Comment by gildeluermoz** [comment]
oui c'est ça ou si `altitude_min AND altitude_max IS NULL`

**Comment by camillemonchicourt** [comment]
Quand on modifie manuellement une altitude, c'est pris en compte dans la BDD.
Par contre si on édite un relevé, le formulaire s'ouvre et recalcule alti_min et max directement car la valeur modifiée précédemment n'est pas affichée.

**Comment by gildeluermoz** [comment]
vérifier s'il n'y a pas d'effet de bord ? 6f13c7aca6d46e36ad8bb026dd007dae4be1257c

**Comment by camillemonchicourt** [comment]
Ça garde bien la valeur si on l'a modifié précédemment. 

Par contre j'ai trouvé un effet de bord : l'altitude n'est pas recalculée quand on déplace le marqueur. Uniquement quand on recréé un marqueur.

**Comment by gildeluermoz** [comment]
9719375b368275481a64e371d736119ba55ed062
Y aurait-il encore des effets de bord ? ;-)

**Comment by camillemonchicourt** [comment]
Ça me semble OK
