### ISSUE TITLE
soucis triggers update concernant les observateurs

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#426]
1/ Si on modifie les observateurs d'un relevé, ça ne se passe pas comme prévu.
plusieurs soucis. A la suppression d'un des 2 observateurs, c'est Ok sur l'interface mais en base il ne s'est rien passé. Je refais une deuxième fois la manip. Ca passe en base. Mais depuis, impossible d'ajouter ou modifier l'observateur (plantage du front suite à une erreur d'enregistrement)
Triggers ?
2/ En rechargeant le formulaire ouvert en modification sur un relevé, ça recharge une liste des observateurs complète qui comporte le ou les observateurs déjà renseigné...

**Comment by TheoLechemia** [comment]
Je n'arrive pas à reproduire le problème avec la dernière version des triggers...
Si tu est en mode dev, c'est peut-être le soucis de "queue pool exeed" (problème de session non fermée) identifié depuis le passage a flask 1.0.2.

**Comment by camillemonchicourt** [comment]
En effet moi j'arrive bien à supprimer un observateur. Par contre, en édition j'ai "Une erreur s'est produite" quand j'essaie d'ajouter un observateur à un relevé.

**Comment by camillemonchicourt** [comment]
OK je n'ai plus le bug apres el correctif que Gil vient de passer sur un trigger : https://github.com/PnX-SI/GeoNature/commit/b2fcae0d4be825de19d0aa366176493818dcee5c

Ah ces triggers, c'est rude !

**Comment by gildeluermoz** [comment]
oui c'est fragile. Et faut tester et retester pour être sur de bien croiser toutes les situations qu'ils gèrent.
C'est assez fatiguant !
Juju était excellent pour ça.

**Comment by gildeluermoz** [comment]
y'a peut-être plus simple : 
SELECT b.toto->'altitude_min' FROM(SELECT row_to_json(a.alts) AS toto FROM (SELECT (ref_geo.fct_get_altitude_intersection(geom_local)) AS alts FROM pr_occtax.t_releves_occtax) a) b 



		
	Gil DELUERMOZ 
Chargé de mission développement web et bases de données 

Parc national des Écrins 
Tél : +33 (0) 4 92 40 20 38 (lundi et mardi) 
+33 (0)4 92 21 08 49 (mercredi et jeudi matin) 
[ http://www.ecrins-parcnational.fr/ | www.ecrins-parcnational.fr ] 

[ http://actu.ecrins.info/ ] 


De: "Camille Monchicourt" <notifications@github.com> 
À: "PnEcrins" <GeoNature@noreply.github.com> 
Cc: "Gil DELUERMOZ" <gil.deluermoz@ecrins-parcnational.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 20 Septembre 2018 23:51:22 
Objet: Re: [PnX-SI/GeoNature] soucis triggers update concernant les observateurs (#426) 



Closed [ https://github.com/PnX-SI/GeoNature/issues/426 | #426 ] .
