### ISSUE TITLE
heures min et max

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#428]
Dans la vraie vie l'heure max peut être < à l'heure min.
Ex : début 2001-09-**11** **09:59:00** et fin 2011-09-**12** **06:17:00**

La condition est donc à tester en comparant les 2 timestamp complets
```
IF (2001-09-11 09:59:00 < 2011-09-12 06:17:00) THEN ok !
ELSE bip !
END IF;
```
Mais attention à bien gérer quand l'heure n'est pas fournie...

**Comment by camillemonchicourt** [comment]
Done
