### ISSUE TITLE
Script de Mise à jour - migrate.sh

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#430]
La procédure de mise à jour de GeoNature (https://geonature.readthedocs.io/fr/latest/installation-standalone.html#mise-a-jour-de-l-application) s'appuie sur le script ``install/migration/migration.sh``.

Il semble y avoir un problème lors de la commande ``cp -r /home/$USER/geonature_old/external_modules/* external_modules`` de celui-ci. Certainement à cause du lien symbolique. Car cela supprime le fichier ``geonature/external_modules/occtax/config/conf_gn_module.toml`` et du coup le build du Front ne se déroule pas comme il faut.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.0.0-rc.2

**Comment by camillemonchicourt** [comment]
Je suis en train de tester une mise à jour de la Beta5 vers la RC3.

- Il faut bien jouer les mises à jour de la BDD successives avant de lancer le ``migrate.sh`` sinon j'ai la même erreur que https://github.com/PnX-SI/GeoNature/issues/437
- Dans le script ``data/migrations/2.0.0beta5-to-2.0.0rc1.sql``, on est parti du principe que la Beta5 ne comprenait pas la Synthèse. Hors le ``install_db.sh`` de la Beta5 intégrait bien la création du schéma ``synthese`` : https://github.com/PnX-SI/GeoNature/blob/geonature2beta/install/install_db.sh#L306-L315
Vu qu'on n'a pas les update de ce schéma entre la Beta5 et la RC1 (changements trop lourds), il faudrait supprimer le schéma et le recréer à partir du bon SQL de création du schéma et ensuite certainement rejouer ces 2 lignes : https://github.com/PnX-SI/GeoNature/blob/develop/data/migrations/2.0.0beta5-to-2.0.0rc1.sql#L1415-L1416
- Dans le SQL beta5 vers 2.0.0-rc1 on créé 2 fois une table ce qui renvoie une erreur : https://github.com/PnX-SI/GeoNature/blob/develop/data/migrations/2.0.0beta5-to-2.0.0rc1.sql#L233-L255
- A ce moment ``gn_synthese.t_sources.id_source`` n'était pas un serial donc ça fonctionne pas de ne pas insérer d'``id_source`` : https://github.com/PnX-SI/GeoNature/blob/develop/data/migrations/2.0.0beta5-to-2.0.0rc1.sql#L1415-L1416
- Quelques corrections : https://github.com/PnX-SI/GeoNature/commit/e9cc043fe069d416db84ce6b93d735a9469796b5

A suivre...

**Comment by gildeluermoz** [comment]
Eviter de drop le schéma synthese dans un script sql. Il serait préférable de le renommer. 
Par contre cela risque de générer des conflits de nommage des contraintes et des index.
Il est probable qu'il faille les renommer aussi por que le nouveau schéma synthèse s'installe proprement.
A creuser.

**Comment by camillemonchicourt** [comment]
Pour migrer depuis la BETA5, ça reste compliqué. Les tests réalisés : 

- Installation BETA5 avec branche ``geonature2beta``
- Ouvrir connexions à la BDD
- Dans la Beta5, on avait déjà un schéma ``gn_synthese`` mais celui-ci n'était pas utilisé 
- Supprimer schéma gn_synthese : ``DROP SCHEMA gn_synthese CASCADE;`` >> Bloqué
``sudo -n -u postgres -s psql -d geonaturedb -c "DROP SCHEMA gn_synthese CASCADE;"`` >> Bloqué
Donc je supprime les tables du schéma à la main puis ``sudo -n -u postgres -s psql -d geonaturedb -c "DROP TABLE gn_synthese.defaults_nomenclatures_value;" >> Bloqué >>>>> Bloque
- Recréer le schéma ``gn_synthèse`` à partir de sa version RC1
https://github.com/PnX-SI/GeoNature/blob/2.0.0-rc.1/data/core/synthese.sql (MASTER !!!!!)
- Puis lancer le script ``synthese_data.sql`` de la RC1
https://github.com/PnX-SI/GeoNature/blob/2.0.0-rc.1/data/core/synthese_data.sql (MASTER !!!!!)
- Pousser les données existantes (Occtax notamment) dans la Synthèse : XXXXXXXXXXX
- Lancer le SQL d'updaet Beta5 to RC1 et ses compléments
- Enchaîner sur les MAJ de BDD RC1 to RC2 puis RC2 to RC3
- Mettre à jour les dépendances et faire leurs éventuels MAJ de BDD
- Suivre la doc de MAJ (https://geonature.readthedocs.io/fr/latest/installation-standalone.html#mise-a-jour-de-l-application) en installant directement la RC3

Donc pour le moment je bloque sur le passage Beta5 vers 2.0.0-rc.1 à cause de la suppression du schéma ``gn_synthese`` pour ensuite le recréer.

**Comment by camillemonchicourt** [comment]
Par contre le mise à jour de la RC2 vers la RC3 s'est bien passé en suivant la procédure de mise à jour classique (https://geonature.readthedocs.io/fr/latest/installation-standalone.html#mise-a-jour-de-l-application) et en exécutant les scripts SQL de mise à jour de la BDD.

**Comment by gildeluermoz** [comment]
Si tu ne peux pas drop la table des nomenclatures par défaut de synthèse c'est carrément bizarre. Cette table n'a pas de dépendance attachée. Sinon des fonctions et des default. Il faut peut-être voir côté droit du user. Si même le user postgres ne peut pas le faire... Très bizarre.
Cherche comment on liste les dépendances sur un objet, genre le schéma.
Sinon pètes les FK et test. Richard peut peut-être t'aider.

**Comment by camillemonchicourt** [comment]
Ouais je sais pas pourquoi il bloque sur la suppression du schéma ``gn_synthese``. Il reste dessus sans fin, sans message. 
Bref, c'est pas grave, la mise à jour RC2 vers RC3 fonctionne bien.
