### ISSUE TITLE
Occtax - Zoom

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#436]
Je zoome sur une zone. 
Je créé un relevé, je suis revenu sur l'étendue générale.

Plutot rester sur zoom précédent.

**Comment by TheoLechemia** [comment]
Fait dans le commit précedent.
Par contre quand on retourne à la liste (après avoir avoir saisi un releve), on perd l'emprise, car le zoom est fait sur l'emprise de toute les données de la liste (comportement lié au composant `pnx-geojson`)

**Comment by camillemonchicourt** [comment]
OK pour ce fonctionnement. Si un utilisateur veut enchaîner des relevés sur la même zone, alors il utilise la fonction d'enchaînement des relevés et ne repasse pas par la liste.

Il faudrait vérifier que quand on enchaîne les relevés on garde bien le zoom du relevé précédent.

**Comment by TheoLechemia** [comment]
> Il faudrait vérifier que quand on enchaîne les relevés on garde bien le zoom du relevé précédent.

Oui c'est bon.

Pour le retour sur l'interface, c'est bon aussi. Le zoom sur l'emprise des données se fait uniquement lorsqu'on fait une recherche
