### ISSUE TITLE
Privilégier l'utilsiation de PostGIS Raster

### ISSUE THREAD

**Issue by mathieubossaert** [PnX-SI/GeoNature#439]
https://github.com/PnX-SI/GeoNature/blob/b508c80e69d5d26d04c06cabded6214b83874d56/data/core/ref_geo.sql#L194
En optimisant l'intégration du raster avec l'option t de raster2pgsql
```sql
CREATE OR REPLACE FUNCTION ref_geo.fct_get_altitude_intersection(IN mygeom public.geometry)
  RETURNS TABLE(altitude_min integer, altitude_max integer) AS
$BODY$
BEGIN
    RETURN QUERY
		SELECT min((altitude).val)::integer AS altitude_min, max((altitude).val)::integer AS altitude_max
		FROM (
			SELECT ST_DumpAsPolygons(ST_clip(rast, 1
			, st_transform(myGeom,gn_commons.get_default_parameter('local_srid', NULL)::integer), true)) AS altitude
			FROM ref_geo.dem AS altitude 
			WHERE st_intersects(rast,st_transform(myGeom,gn_commons.get_default_parameter('local_srid', NULL)::integer))
		) AS valeur_des_differents_raster;		
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100
ROWS 1000;
```
L'intégration du raster peut être optimisée avec l'option -t de raster2pgsql

```sh
    raster2pgsql -s 2154 -I -t 5x5 /home/geonatureadmin/BDALTIV2_250M_FXX_0098_7150_MNT_LAMB93_IGN69.asc | psql -h localhost -U dba geonaturedb
```
En terme de taille sur disque, 
- la table ref_geo.dem_vector pèse en tout 2,135 Go dont 688 Mo d'index
- la table raster en (5x5) pèse en tout  238 Mo dont 64 Mo d'index

**Comment by gildeluermoz** [comment]
Bien. Merci Mathieu.
J'ai fait qq tests et la vectorisation reste tout de même plus performante:
```
--Solution directement depuis le dem en 5x5 non vectorisé mais bien indexée
--1.4s
SELECT id_synthese, altitude_min, altitude_max, 
(ref_geo.fct_get_altitude_intersection_mathieu(the_geom_local)).altitude_min,
(ref_geo.fct_get_altitude_intersection_mathieu(the_geom_local)).altitude_max
FROM gn_synthese.synthese
LIMIT 1000;

--solution vectorisée
--330ms
SELECT id_synthese, altitude_min, altitude_max, 
(ref_geo.fct_get_altitude_intersection(the_geom_local)).altitude_min, 
(ref_geo.fct_get_altitude_intersection(the_geom_local)).altitude_max
FROM gn_synthese.synthese
LIMIT 1000;
```
Du coup, comme il y a tout de même un soucis de taille de stockage et de temps de calcul. Je ne sais pas trop comment faire. Pour un calcul unique, il n'est pas trop impactant d'utilisée la solution que tu proposes. Pour un calcul en masse, genre insertion dans la synthese avec besoin de calculer l'altitude, je ne sais pas trop.

**Comment by gildeluermoz** [comment]
J'ai retenu l'idée de ne pas vectoriser par défaut car les perf sont acceptable en raster et que la vectorisation est lourde. celui qui a besoin de performance pour des INSERT en synthèse en masse peut la mettre en place en changeant un paramètre lors de l'installation.
DONE : 477704006434c73c88466506fcfe62471e696c1e

**Comment by camillemonchicourt** [comment]
OK vu pour choisir au moment de l'installation si on vectorise ou non le Raster. 
Mais du coup ça complique l'usage du MNT avec des instances où il est vectorisé et d'autres non, donc on requête pas dans la même table et pas forcément de la même façon ???

**Comment by gildeluermoz** [comment]
On requête avec la même fonction que l'on adapte au contexte (soit à l'install, soit après comme expliqué dans la doc) 
Pour faire plus simple, on pourrait, dans la fonction, tester si `dem_vector` renvoi `NULL`, alors on essaie avec la table `dem`. TODO

**Comment by mathieubossaert** [comment]
ok je serai preneur d'un jeu de données test (les 1000 données testées par exemple)

**Comment by gildeluermoz** [comment]
Je t'ai envoyé ça sur ton mail.

**Comment by gildeluermoz** [comment]
Suppression du mécanisme avec 2 fonctions, la fonction `ref_geo.fct_get_altitude_intersection` est maintenant plus intelligente et gère les 2 cas de figure en privilégiant l'usage du dem_vector
https://github.com/PnX-SI/GeoNature/commit/000a031d720fa1845c3007b10f116751dd0cfb4c

**Comment by camillemonchicourt** [comment]
OK super.
