### ISSUE TITLE
Install_all : Installation incomplète (pb avec Fiona ?)

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/GeoNature#442]
J'ouvre le ticket suite au problème rencontré en Workshop sur au moins 2 machines.
(ça me permettra de suivre la résolution du problème)

Mon contexte (mais je crois que d'autres contextes sont aussi touchés) : 
- VM Debian 9 sur Serveur Dédié (OVH) hypervisé avec ESXi (vSphere)

Suite à l'execution de `install_all.sh`, TaxHub et UsersHub sont bien opérationnels, mais pas Geonature.
Si je me connecte sur http://monIP/geonature/, j'ai un : 

> **Forbidden**
> You don't have permission to access /geonature/ on this server.
> Apache/2.4.25 (Debian) Server at monIP Port 80

Voici quelques messages d'erreur du log (`/home/geonatureadmin/geonature/var/log/gn_errors.log`)  : 

`ImportError: /home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/fiona/ogrext.cpython-35m-i386-linux-gnu.so: undefined symbol: OGR_F_IsFieldNull`

`[2018-09-24 16:22:36 +0200] [21731] [ERROR] Exception in worker process`

**Comment by jbrieuclp** [comment]
L'installation fonctionne sous Debian 9 64bits (amd64).
Sous Debian 9 32bits (i386) l'installation renvoie des erreurs liées à fiona et GDAL et ne compile pas le front. 
On dirait que fiona 1.7.13 nécessite GDAL >= 2.2, il n y a que la version 2.1 de stable pour Debian 9 (stretch). Il faudrait essayer de forcer une version supérieure de GDAL.

**Comment by camillemonchicourt** [comment]
Oui je comprends pas pourquoi certains ont monté une 32 bits. Peut être que quelque chose m'échappe. 
C'est maintenant vérifié dans le script d'installation.

**Comment by sig-pnrnm** [comment]
> je comprends pas pourquoi certains ont monté une 32 bits

Pour ce qui nous concerne, c'est juste une erreur de notre informaticien ;-)

A+

**Comment by gildeluermoz** [comment]
Oui c'est certainement une erreur pour les autres également. Il n'y a plus de raison d'utiliser le 32-bits sur un serveur récent désormais.

**Comment by sig-pnrnm** [comment]
Juste pour info : j'ai enfin récupéré ma VM Debian 9 64 bits, dans le même contexte (*), et l'installation s'est déroulée sans accroc !
 :sunglasses:  :sunglasses:  :sunglasses:


(*) Serveur Dédié (OVH) hypervisé avec ESXi (vSphere)

**Comment by camillemonchicourt** [comment]
OK merci pour le retour.
