### ISSUE TITLE
Bug avec npm lors de la customisation de geonature

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#443]
Lorsque j'essaie de mettre à jour le contenu de l'introduction de geonature, je modifie le fichier ``introduction.component.html``, situé dans le répertoire ``geonature/frontend/src/custom/components/introduction``. 

Après ça, je lance les commandes : 
cd /home/MONUSER/geonature/frontend
    npm run build
    sudo supervisorctl reload

(non, je n'ai pas oublié de changer MONUSER ;) )

Sur mes deux essais, même réponse de mon navigateur : erreur 403, je ne peux pas accéder à /geonature sur ce serveur.

La commande npm me renvoie vers ses logs, qui indiquent notamment 

> 21 error code ELIFECYCLE
22 error errno 134
23 error geonature@0.0.0 build: `ng build --prod --aot=false`
23 error Exit status 134
24 error Failed at the geonature@0.0.0 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 134, true ]

Je l'ai pourtant fait hier, il me semble de la même manière, et ça marchait... il n'est donc pas à exclure que le bug se situe entre la chaise et le clavier, comme souvent, mais au cas où je vous transmets les infos ;)

**Comment by DonovanMaillard** [comment]
Trouvé, c'était bien une erreur, mais dans le fichier css et non pas dans l'introduction. Désolé !

**Comment by TheoLechemia** [comment]
NB: Le sudo supervisorctl reload (qui relance les API GeoNature et Taxhub) n'est pas nécessaire ici. 
Commande qui peut mettre en échec les relevés en train d'être saisis par ses utilisateurs.

**Comment by camillemonchicourt** [comment]
OK donc il faut revoir cet ajout à la doc https://github.com/PnX-SI/GeoNature/pull/444/files ? 
Car la commande y est indiquée à lancer.

**Comment by DonovanMaillard** [comment]
je viens de le virer de la doc du coup ;)
