### ISSUE TITLE
Install-all : Données exemple

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#446]
Dans l'install_all, les données exemples concernent également les nomenclatures par défaut de la synthèse. Voir pour mettre des nomenclatures par défaut même quand données exemple = false? 

Par ailleurs, les taxons saisissables (l'ablette etc) ne font pas partie des mêmes "données exemple". Ils sont donc par défaut dans les tables et listes, même si données exemple = false à l'installation.

**Comment by camillemonchicourt** [comment]
Concernant les taxons exemples, cela a été ajouté dans la version 1.5.0 de TaxHub : https://github.com/PnX-SI/TaxHub/blob/master/settings.ini.sample#L52-L59
Mais pas encore pris en compte dans le script ``install_all.sh``.

Pour le moment, si on indique à l'installation GeoNature de ne pas mettre les données exemples, il n'y a que 3 SQL qui ne sont pas joués : https://github.com/PnX-SI/GeoNature/blob/master/install/install_db.sh#L362-L366

Du coup si ``add_sample_data`` est à ``false``, ça n'insère pas les nomenclatures par défaut dans gn_synthese (https://github.com/PnX-SI/GeoNature/blob/master/data/core/synthese_data.sql n'étant pas joué). 
On pourrait ajouter un paramètre, mais ça ajoute encore des choses un peu complexes à comprendre quand on débarque dans l'installation.

**Comment by DonovanMaillard** [comment]
Sauf à diviser en deux scripts sql, l'un qui se joue tout le temps (nomenclatures) et l'autre qui se joue selon le paramètre exemple. 
Je le mets ici pour mémo, mais gil avait vu ça et y jetera sans doute un oeil un de ces jours.

**Comment by gildeluermoz** [comment]
Je pense que les valeurs par défaut des nomenclatures ne sont pas des données exemples. Elles sont nécessaires au fonctionnement de l'appli. Comme les paramètres par défaut de l'appli dans `gn_commons.t_parameters`. Il faut les installer quoi qu'il en soit. 
Quand tu mets `DEFAULT  'tauto'` dans le `CREATE TABLE`, tu le fais car tu préfères avoir la valeur `'tauto'` plutôt que `NULL`. Ici c'est pareil, si tu n'insères rien dans la table `defaults_nomenclatures_value`, c'est un peu comme si on disait `DEFAULT NULL` (une tautologie quoi :+1: )
Il faut livrer des valeurs par défaut et chacun peut les modifier mais ce ne sont pas des données exemples. Donc pas de paramètre supplémentaire pour ça.
Par contre les taxons exemples présents dans la liste des taxons saisissables ne devraient pas être installés si `add_sample_data` est à `false`.

**Comment by camillemonchicourt** [comment]
OK on est d'accord. 
Donc si add_sample_data = false, il faut quand même insérer les valeurs par défaut dans ``gn_synthese``.

**Comment by gildeluermoz** [comment]
Oui

**Comment by gildeluermoz** [comment]
Voilà pour les valeurs par défaut des nomenclatures : 13cc246c35e20690d63f7b4cfaeab2a39a5212ee

**Comment by gildeluermoz** [comment]
Et pour les taxons : 08f0ca836f58ae072f7975b9305a1e791491a89d
