### ISSUE TITLE
Synthese: problème barre de téléchargement

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#451]
Sur le serveur de test, la barre qui indique le % de chargement ne va jamais jusqu'à 100% alors que le fichier est bien téléchargé.
Mettre un spinner plutôt, car le % de téléchargement est completement fictif

**Comment by gildeluermoz** [comment]
DONE : 44c979eb37926ddadb38d6faab33bc60e207fe9c

**Comment by camillemonchicourt** [comment]
Hum je comprends pas pourquoi avoir enlever la barre de téléchargement. 
Elle marchait bien dans la plupart des cas, juste à ajuster.
Et maintenant l'export SYNTHESE ne fonctionne plus chez moi. J'ai un message "Une erreur s'est produite"

**Comment by camillemonchicourt** [comment]
Pour la Synthèse, le problème est avec le champs WKT. 

Les logs PostgreSQL indiquent : 

2018-10-15 22:47:20.883 CEST [4111] geonatadmin@geonature2db ERREUR:  la colonne v_synthese_for_export.wkt n'existe pas au caractère 2424

**Comment by gildeluermoz** [comment]
Le soucis avec l'export synthese est corrigé ici : f99313a553382452058b60f7d75f797955fb98e0
J'ai remplacé la barre de défilement par un spinner sur proposition de Théo. C'est l'objet de ce ticket.

**Comment by camillemonchicourt** [comment]
Le message Export téléchargé s'affiche bien après le spinner pour le GeoJSON et SHP.
Mais le spinner tourne sans fin pour le CSV et le CSV statuts.

**Comment by gildeluermoz** [comment]
J'avais pas du tout ça en dev. Testé plus fois.
Et le csv rentre ou il ne se charge jamais ?

**Comment by camillemonchicourt** [comment]
Matte sur notre serveur TEST si jamais.

Les CSV (obs ou statuts) sont bien téléchargés mais le spinner tourne indéfiniment avec le message "Téléchargement en cours".

**Comment by gildeluermoz** [comment]
Ok je regarderai demain mais j'ai jamais eu ce comportement. C'est bizarre.
En même temps je teste sur un dev en localhost, donc pour les téléchargements c'est pas le même contexte.

**Comment by gildeluermoz** [comment]
T'as identifié le soucis ?

**Comment by camillemonchicourt** [comment]
Non, sur le serveur TEST, poru les CSV, le spinner tourne indéfiniment. Je sais pas pourquoi.
