### ISSUE TITLE
Déclarer SRID du geom de t_base_sites

### ISSUE THREAD

**Issue by richardvergely** [PnX-SI/GeoNature#452]
Le champs geom de ``gn_monitoring.t_base_sites`` a une contrainte de SRID (4326) mais le SRID n'est pas déclaré au niveau du champs (
https://github.com/PnX-SI/GeoNature/blob/master/data/core/monitoring.sql#L17-L29). 

Contrainte : https://github.com/PnX-SI/GeoNature/blob/master/data/core/monitoring.sql#L122-L123

Du coup la vue ``public.geometry_columns`` ne reconnait son SRID et cela semble poser des problèmes quand on essaie d'ouvrir cette table dans QGIS. 

On pourrait modifier le type du champs geom : 

```
ALTER TABLE gn_monitoring.t_base_sites ALTER COLUMN geom type geometry(geometry,4326);
```

Mais ce champ a pas mal de dépendances à supprimer/recréer pour pouvoir modifier le type du champs : 

- gn_monitoring.fct_trg_cor_site_area()
- trg_cor_site_area

**Comment by gildeluermoz** [comment]
Merci Richard.
Il faut utiliser le type ``public.geometry`` sinon parfois ça ne passe pas. Notamment si on fait un `SET search_path`.
Done : cffcf758313c9a2d2181fdaa133c152ea8fea023
