### ISSUE TITLE
Input de connexion : largeur minimum

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/GeoNature#454]
Si la page de connexion est affichée sur un petit écran, les inputs de connexion sont trop petits pour être lisibles.
Il faudrait leur donner un `min-width` (250px sembleraient suffisants)

Les inputs en question sont là : 
https://github.com/PnX-SI/GeoNature/blob/3ad8d9a83fec75b7c91d4020eeb915646cea9eb1/frontend/src/app/components/login/login.component.html

Voici ce que ça donne chez nous avec un background image sur le body : 
![screenshot_2018-10-04 geonature 2 - pnrnm](https://user-images.githubusercontent.com/26482054/46486084-4dc1cd00-c7fd-11e8-8f02-b216be8767ba.png)

**Comment by camillemonchicourt** [comment]
Oui le formulaire de Login est une première version basique dont le Responsive n'a pas été travaillé.

**Comment by camillemonchicourt** [comment]
La 2.0.0 se préparant, voila une page login plus aboutie et responsive : 

![image](https://user-images.githubusercontent.com/4418840/52130816-7f2b9780-263b-11e9-9e13-38b94dd782ec.png)

Commit : https://github.com/PnX-SI/GeoNature/commit/88159466e9e2b9baf9f70a78ad98b3fe5d8300dc
