### ISSUE TITLE
Synthèse : paramétrage de l'export

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#456]
Actuellement l'export de la synthèse ne comporte ni geom, ni x, y alors que ces infos sont dans la vue correspondant (d'après son nom). 

Du coup ça m'amène à une question : à quel endroit on paramètre les champs et le contenu de l'export de la synthèse ?

Merci d'avance !

**Comment by camillemonchicourt** [comment]
On a identifié le problème sur la RC2 au niveau du GeoJSON et cela a été corrigé depuis, dans la RC3 qu'on est en train de packager : https://github.com/PnX-SI/GeoNature/issues/449

Il y a le même problème dans le CSV et/ou les SHP ?
Tu ne précises pas sur quel export ?

**Comment by camillemonchicourt** [comment]
Pour la conf : https://geonature.readthedocs.io/fr/latest/admin-manual.html#configuration-generale-de-l-application : 

> Par défaut, le fichier <GEONATURE_DIRECTORY>/config/geonature_config.toml est minimaliste et généré à partir des infos présentes dans le fichier config/settings.ini.
> 
> Il est possible de le compléter en surcouchant les paramètres présents dans le fichier config/default_config.toml.example.

**Comment by DonovanMaillard** [comment]
OK super. Je parlais de l'export csv

Cela dit l'export est il défini en dur dans le module ou est-il paramétrable ? Et si oui à quel endroit ?

**Comment by camillemonchicourt** [comment]
RTFD

**Comment by camillemonchicourt** [comment]
En effet dans l'export CSV de la Synthèse, il n'y a pas la géométrie. 
Elle y est dans les exports CSV Occtax. 
Par contre si on l'ajoute dans l'export pour le CSV, le champs sera aussi présent dans le Geojson et le SHP, car c'est basé sur la même vue.

**Comment by gildeluermoz** [comment]
C'est un peu utile le x, y, non ?

**Comment by camillemonchicourt** [comment]
Oui dans le CSV en tout cas.
Enfin pour le moment c'est plutôt le WKT, ce qui va bien aussi. 
Mais comme c'est la même vue, ça le met aussi dans le GeoJSON et le SHP, ce qui est moins utile mais pas grave.

**Comment by gildeluermoz** [comment]
https://github.com/PnX-SI/GeoNature/commit/f097c3840cc5dc73a5b19aceec0a54dcb785b5ac
A vérifier, l'ordre des champs semble aléatoire malgré la fonction spéciale de sérialisation sur l'export.

**Comment by camillemonchicourt** [comment]
En effet l'export Synthese ne fonctionne plus. 
J'ai un message "Une erreur s'est produite".

Les logs PostgreSQL indiquent :
```
2018-10-15 22:47:20.883 CEST [4111] geonatadmin@geonature2db ERREUR: la colonne v_synthese_for_export.wkt n'existe pas au caractère 2424
```
Je ne vois pas où tu génères la valeur du champs WKT dans ton commit. 

Et les colonnes à exporter sont aussi indiqué dans la conf générale de GeoNature : https://github.com/PnX-SI/GeoNature/blob/develop/config/default_config.toml.example#L106-L148

**Comment by camillemonchicourt** [comment]
En tout cas, le champs WKT n'est pas dans la vue gn_synthese.v_synthese_for_export

**Comment by camillemonchicourt** [comment]
Done https://github.com/PnX-SI/GeoNature/commit/f99313a553382452058b60f7d75f797955fb98e0
