### ISSUE TITLE
Occtax - Edition relevé et Date debut/fin

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#457]
Quand on saisit un relevé dont la date début est différente de la date fin, cela s'enregistre bien dans la BDD et dans la Synthèse. 

Par contre quand on édite le relevé, la date de fin est modifiée au niveau de l'interface en prenant la date de début.

**Comment by camillemonchicourt** [comment]
Voir commit Gil : https://github.com/PnX-SI/GeoNature/commit/a6fa71618d148232cccad457dd0dd1f245a7a2ec
Pour ne déclencher l'action que quand old_date_max = old_date_min ou si date_max = vide (ouverture du formulaire en création d'un relevé)

**Comment by camillemonchicourt** [comment]
Ça fonctionne bien quand je créé un nouveau relevé (sauf quand je mets une date_fin != date_debut puis que je remets une date_fin = date_debut).

Par contre si je modifie un relevé dont date_fin = date_debut et que je modifie la date_debut, ça ne modifie pas la date_fin

**Comment by gildeluermoz** [comment]
Deux objets différents avec le même contenu ne sont pas égaux. Il fallait les "strigifier" avant de les comparer...
https://github.com/PnX-SI/GeoNature/commit/b6d17b1d9e856b8411ed78a177c243d85aa916cf

**Comment by camillemonchicourt** [comment]
Je viens de retester. 
Je créé un relevé dont la date_debut est différente de la date_fin. 
Quand je reviens le modifier, le formulaire s'est remis en date_fin = date_debut. 

Idem si je le remodifie et reviens sur le formulaire.

**Comment by gildeluermoz** [comment]
ok, vu. C'est carrément dans la base, dans `pr_occtax.t_releves_occtax` que la `date_max` se crée avec la même valeur que la `date_min`... Je creuse

**Comment by camillemonchicourt** [comment]
Ah bah mince, j'avais l'impression que c'était OK niveau BDD. 
Et je viens de retester en CREATE ou en UPDATE du RELEVE, les dates debut et fin sont bien différentes dans la BDD.
Donc en testant rapidos, je vois pas de pb niveau BDD.

**Comment by gildeluermoz** [comment]
Non, non c'est Ok en BDD, c'est moi qui bug !
Voici la correction : e451f2da64b034d4ed0927443311502283fd3246

**Comment by camillemonchicourt** [comment]
Testé, validé.
