### ISSUE TITLE
Map - Affichage des lignes

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#458]
Il y a un problème d'affichage des lignes sur les cartes : 

![leaflet-lines](https://user-images.githubusercontent.com/4418840/46537588-f3367880-c8b1-11e8-97b1-aacdbf803f35.jpg)

**Comment by gildeluermoz** [comment]
Ca ressemble à un bug de Leaflet.
Si tu n'as pas la pointe droite de la ligne tout va bien :
![image](https://user-images.githubusercontent.com/10024739/46951085-339eaf00-d087-11e8-92e1-5be48241a7dd.png)
Si tu fais apparaître la pointe le bug apparait : 
![image](https://user-images.githubusercontent.com/10024739/46951190-8c6e4780-d087-11e8-80eb-fcfc84d25579.png)
A noter également que la partie remplie n'est pas complète, elle se dessine entre les 2 intersections de la ligne avec le bord de la carte...
Si la pointe à droite est seulement un peu masquée, ça le fait quand même.

**Comment by gildeluermoz** [comment]
Même si le comportement de Leaflet n'est pas parfait, il est préférable de définir un style sans contenu et sans opacité pour les géométries de type ligne : 2b18b85dd731b03c5a3491878aaad1de67a9efed
Ceci devrait résoudre cela.

**Comment by camillemonchicourt** [comment]
En tout cas les lignes étaient affichées correctement sans avoir besoin de leur appliquer un style particulier.

**Comment by gildeluermoz** [comment]
non les lignes s'affichaient avec un genre de contenu en transparence comme les polygones et l'intérieur du cercle des points

**Comment by camillemonchicourt** [comment]
Exact, je pensai que c'était nouveau, mais non, en effet.

**Comment by camillemonchicourt** [comment]
Complété par https://github.com/PnX-SI/GeoNature/commit/527ad2800b0af0e34ac3e935161883800f7c41c1
