### ISSUE TITLE
Synthese - Export geojson et SRID

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#461]
L'export geojson de la Synthèse est bien géographique désormais. 
Par contre il doit y avoir un problème de projection car les points exportés sont mal localisés.

L'export geojson de Occtax est OK par contre.

**Comment by gildeluermoz** [comment]
Spécification du geojson : https://tools.ietf.org/html/rfc7946

> The coordinate reference system for all GeoJSON coordinates is a
>    geographic coordinate reference system, using the World Geodetic
>    System 1984 (WGS 84) [WGS84] datum, with longitude and latitude units
>    of decimal degrees.

Effectivement l'export fournit les coordinates en 2154.

**Comment by gildeluermoz** [comment]
DONE : https://github.com/PnX-SI/GeoNature/commit/8123de1ad72905e97cd623e586242fa1b4a94f1f
