### ISSUE TITLE
Occtax - Export et doublons

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#462]
Dans l'export Occtax (testé sur CSV et geojson), il y a des occurrences en doublons. 
Dans mon cas j'ai 7 occurrences (au niveau de Occtax et de la Synthèse) mais dans les exports j'en ai 9. 

A priori toutes celles qui ont 2 observateurs sont doublées. 
C'est bien ça, je viens d'ajouter un 3° observateur sur un relevé qui a 3 taxons et je passe à 12 occurrences dans les exports. 

Voir donc la vue des exports d'Occtax.

**Comment by gildeluermoz** [comment]
je viens de tester en ajoutant des observateurs sur un relevés avec 2 taxons et aussi sur un relevé avec un seul taxons. Avant j'avais 10 relevés et 11 counting = 11 lignes en synthese. Avant et après j'ai bien 11 lignes dans les exports.
Soit j'ai pu su reproduire ta manip pour provoquer le bug, soit il est corrigé avec les corrections  des triggers mais je ne vois pas trop le lien.
Refais une install de la base avec la correction des triggers et on va voir si ça perdure.

**Comment by gildeluermoz** [comment]
Le soucis se situait au niveau des organismes dans le `GROUP BY` et le `COALESCE`.
Il est possible qu'un soucis subsiste avec en cas de mix entre `observers_txt` et observers dans `cor_role_releves_occtax`
DONE : https://github.com/PnX-SI/GeoNature/commit/55aac7d5d3be11b49d31eab33fd3ddc11b076d82

**Comment by camillemonchicourt** [comment]
OK super.
Je suis en train de faire des tests d'install, je vais tester ça. 
Par contre, je pense pas qu'il fallait trop modifier l'export DLB, car c'est celui qui a été calé pour les attentes du Dépot Legal de Biodiversité (DLB).

**Comment by camillemonchicourt** [comment]
OK c'est car par défaut on utilise l'export occtax_dlb ! 
Je vais voir pour changer dans la conf par défaut pour utiliser occtax_sinp

**Comment by gildeluermoz** [comment]
On en recause. L'erreur de doublon était sur les deux exports.

**Comment by gildeluermoz** [comment]
> Par contre, je pense pas qu'il fallait trop modifier l'export DLB, car c'est celui qui a été calé pour les attentes du Dépot Legal de Biodiversité (DLB).

https://github.com/PnX-SI/GeoNature/commit/2e6e34e9c35887d7d3502fa02344da3af8c910ed

**Comment by gildeluermoz** [comment]
j'ai passé la correction sur le serveur de test; Il n'y a plus de doublons sur le module export. Je regarde les autres exports.

**Comment by gildeluermoz** [comment]
> OK c'est car par défaut on utilise l'export occtax_dlb !
Je vais voir pour changer dans la conf par défaut pour utiliser occtax_sinp

l'export occtax refonctionne sur le serveur de test. Je regarde pour le basculer sur le vue export_sinp

**Comment by camillemonchicourt** [comment]
Dans le fichier data/migrations/2.0.0rc2-to-2.0.0rc3.sql, il ne faut pas dropper les vues avant de les recréer ?
C'est ce que j'ai du faire pour appliquer les modifications des vues lors de mes tests.

**Comment by gildeluermoz** [comment]
Oui, c'est un oubli. J'ai du je faire aussi. Tu l'ajoutes ?

**Comment by camillemonchicourt** [comment]
OK

**Comment by camillemonchicourt** [comment]
DONE : https://github.com/PnX-SI/GeoNature/commit/6888287f6e9e5fab5a452cd4b2a7252aa2ca0ca5

**Comment by camillemonchicourt** [comment]
Je viens de reinstaller la develop.
Quand je teste un export depuis Occtax, j'ai une Internal Server Error.
gn_errors.log indique ``[2018-10-15 22:52:05 +0200] [29453] [INFO] id_releve_occtax``. Ca doit être un problème dans l'ordre des colonnes.

**Comment by camillemonchicourt** [comment]
Ça semble être autre chose. 
Dans la vue précédente (``pr_occtax.export_occtax_dlb``), on avait le champs ``id_releve_occtax`` qui n'est pas présent dans ``pr_occtax.export_occtax_sinp``.
Et la Synthèse doit utiliser ce champs au moment de l'export.

**Comment by camillemonchicourt** [comment]
J'ai refait une install ce soir sur le serveur TEST. 
J'ai fait des exports Occtax il y a une heure et ils fonctionnaient bien. 
Entre temps j'ai saisi des données en plus. 
Là je retente un export Occtax et j'ai une Internal server error et toujours dans ``gn_errors.log`` le message ``[2018-10-16 23:02:39 +0200] [29464] [INFO] id_releve_occtax``

Je comprends pas.

**Comment by gildeluermoz** [comment]
Ok. + Une
Faut voir les spécificités du contenu, l'encodong, les ;, les join, les champs vides, les caractères spéciaux, ceux avec 1 ou pls occurrences, observateurs, etc.
Essaye de supprimer des relevés et voir après la suppression du quel ça revient.
Si ça revient

**Comment by TheoLechemia** [comment]
Je viens de refaire de gros tests de CRUVED. Création d'un role, mise dans un groupe, retirer du groupe, mise d'un CRUVED individuel, modification successive du CRUVED au niveau des modules et de GeoNature.
Tout me parait OK.
