### ISSUE TITLE
occtax - id_role présent même si observers_txt = true

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#463]
Je suis passé en `"observers_txt" : true,` dans `/home/gil/geonature2/contrib/occtax/frontend/app/module.config.ts`
J'ai créé plusieurs relevés avec des observateurs en mode texte (je n'ai choisi aucun observateurs issu de `utliisateurs.t_roles` car la liste des observateurs n'est pas disponible dans ce mode de saisie). 
Malgré cela, la table `pr_occtax.cor_role_releves_occtax` a été peuplée avec l'utilisateurs logué.
Même chose du coup dans la synthese, c'est l'observateur logué et non l'observateur_txt saisi qui est écrit dans le champs `observers`.

**Comment by camillemonchicourt** [comment]
Normalement ce n'est pas ce fichier qu'il faut modifier pour la conf : 
- https://geonature.readthedocs.io/fr/latest/admin-manual.html#configuration
- https://geonature.readthedocs.io/fr/latest/admin-manual.html#module-occtax

Mais sinon, en effet, pour ton problème c'est pas normal. 

C'est peut-être un effet de bord de la nouvelle fonctionnalité : https://github.com/PnX-SI/GeoNature/issues/438 ?

**Comment by gildeluermoz** [comment]
DONE : 8a3a3d3c8f437f55ae9eeedb74b7d4ce610a4da1

**Comment by camillemonchicourt** [comment]
Joli !
