### ISSUE TITLE
OccTax : filtre de recherche Observateurs non fonctionnel

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/GeoNature#464]
Sur mon instance de tests de GeoNature V2, je viens de récupérer les Observateurs de la V1.
Je les ai bien associés à l'application OccTax dans UsersHub, et ils apparaissent bien dans la liste déroulante de saisie de relevé.

Cependant, le filtre de recherche d'observateur n'est semble-t-il pas (encore ?) opérationnel : quand j'écris les premières lettre des observateurs (j'ai essayé en majuscule, minuscule, par prénom ou nom), la liste déroulante n'est pas filtrée.

Est-ce un problème déjà identifié ?
![observateurs](https://user-images.githubusercontent.com/26482054/46743765-0bd7d180-ccaa-11e8-869e-bbd61546c0b6.png)

**Comment by camillemonchicourt** [comment]
Je sais pas, je viens de tester et ça marche bien sur mon instance ...

**Comment by sig-pnrnm** [comment]
Au cas où, mais je crois pas que ça n'ait de lien, je viens de constater dans la console Firefox que j'ai des messages d'erreur de ce type : 

> ERROR TypeError: "t.nom_complet is null"

**Comment by sig-pnrnm** [comment]
Bon, je viens de résoudre le problème en supprimant des Observateurs qui n'avaient pas de prénom !
(`null` au lieu de `''` je crois )

Affaire résolue !

**Comment by camillemonchicourt** [comment]
Oui et ton problème était bien lié au message dans la console ``t.nom_complet is null``

Dans tous les cas, c'est intéressant, il y a des améliorations à apporter à l'outil de recherche dans les observateurs.
