### ISSUE TITLE
Formulaire des cadres d'acquisitions : bugs ?

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/GeoNature#466]
Suis en train de m'approprier les notions des cadres d'acquisitions / jeux de données.
Pour commencer, je tente de créer un nouveau cadre via le formulaire dédié du menu "Admin".

J'avais mis un seul acteur sur ce cadre (point de contact), puis enregistré.

Or, à la réouverture du cadre, je me retrouve avec 2 blocs d'acteurs, et si j'en supprime un et tente d'enregistrer, j'ai le message rouge "Une erreur s'est produite".

J'ai le même comportement sur mon instance et sur celle de demo ( http://demo.geonature.fr/geonature )

Comme Camille, je tente une capture d'écran pour illustrer mes propos :wink:  :

![cadres_acquisition](https://user-images.githubusercontent.com/26482054/46803597-c5917980-cd60-11e8-9ade-80e70c9e7b2b.gif)

**Comment by camillemonchicourt** [comment]
Utilise le groupe Grp_en_poste il a un CRUVED qui va bien. Ou mets à ton groupe le même CRUVED. Et ensuite ajoute ce groupe en tant qu'acteur du JDD

**Comment by camillemonchicourt** [comment]
Ah non je dis n'importe quoi. C'est l'organisme qu'il faut mettre en acteur

**Comment by DonovanMaillard** [comment]
Bonjour à vous, 

Sylvain, un exemple de script pour créer des cadres, jdd et le associer à des rôles ;) 

`
-- Création du métacadre d'acquisition Atlas de la Biodiversité Communale
INSERT INTO gn_meta.t_acquisition_frameworks (
	acquisition_framework_name,
	acquisition_framework_desc,
	id_nomenclature_territorial_level,
	territory_desc,
	keywords,
	id_nomenclature_financing_type,
	target_description,
	acquisition_framework_start_date,
	is_parent
	)
VALUES
	('Atlas Biodiversite Communale',
	'Données de papillons acquises dans le cadre de programmes ABC',
	'359',
	'Etudes à l''échelle communale de communes de France Métropolitaine',
	'ABC, Atlas de la Biodiversité Communale, Papillons, Lépidoptères',
	'390',
	'Papillons diurnes et nocturnes - Lépidoptères',
	'01/01/2018',
	'1')


-- Création des cadres d'acquisition enfants ABC Embrun et ABC Saint-Jean-Saint-Nicolas
INSERT INTO gn_meta.t_acquisition_frameworks (
	acquisition_framework_name,
	acquisition_framework_desc,
	id_nomenclature_territorial_level,
	territory_desc,
	keywords,
	id_nomenclature_financing_type,
	target_description,
	acquisition_framework_start_date,
	is_parent,
	acquisition_framework_parent_id
	)
VALUES
	('ABC de la commune d''Embrun',
	'Données de papillons acquises dans le cadre de l''ABC d''Embrun',
	'359',
	'Echelle communale : commune d''Embrun (05)',
	'ABC, Atlas de la Biodiversité Communale, Papillons, Lépidoptères, Embrun',
	'390',
	'Papillons diurnes et nocturnes - Lépidoptères',
	'01/01/2018',
	'0',
	'9'),
	
	('ABC de la commune de Saint-Jean-Saint-Nicolas',
	'Données de papillons acquises dans le cadre de l''ABC de Saint-Jean-Saint-Nicolas',
	'359',
	'Echelle communale : commune de Saint-Jean-Saint-Nicolas (05)',
	'ABC, Atlas de la Biodiversité Communale, Papillons, Lépidoptères, Saint-Jean-Saint-Nicolas',
	'390',
	'Papillons diurnes et nocturnes - Lépidoptères',
	'01/01/2018',
	'0',
	'9')


-- Création des jeux de données diurnes/nocturnes pour les ABC d'Embrun et Saint-Jean-Saint-Nicolas
INSERT INTO gn_meta.t_datasets (
	id_acquisition_framework,
	dataset_name,
	dataset_shortname,
	dataset_desc,
	id_nomenclature_data_type,
	keywords,
	marine_domain,
	terrestrial_domain,
	id_nomenclature_dataset_objectif,
	id_nomenclature_collecting_method,
	id_nomenclature_data_origin,
	id_nomenclature_source_status,
	id_nomenclature_resource_type,
	default_validity
	)
VALUES
	('10',
	'Inventaire des papillons diurnes - ABC d''Embrun',
	'Lepidopteres diurnes ABC EMBRUN',
	'Inventaire des papillons diurnes réalisé dans le cadre de l''ABC de la commune d''Embrun',
	'326',
	'ABC, Atlas de la Biodiversité Communale, Embrun, Papillons diurnes, Lépidoptères, Rhopalocères, Inventaire, Flavia APE',
	'FALSE',
	'TRUE',
	'425',
	'403',
	'78',
	'75',
	'324',
	'TRUE'),

	('10',
	'Inventaire des hétérocères - ABC d''Embrun',
	'Hétérocères ABC EMBRUN',
	'Inventaire des hétérocères réalisé dans le cadre de l''ABC de la commune d''Embrun',
	'326',
	'ABC, Atlas de la Biodiversité Communale, Embrun, Lépidoptères, Hétérocères, Inventaire, Flavia APE',
	'FALSE',
	'TRUE',
	'425',
	'403',
	'78',
	'75',
	'324',
	'TRUE'),

	('11',
	'Inventaire des papillons diurnes - ABC Saint-Jean-Saint-Nicolas',
	'Lepidopteres diurnes ABC SJSN',
	'Inventaire des papillons diurnes réalisé dans le cadre de l''ABC de la commune de Saint-Jean-Saint-Nicolas',
	'326',
	'ABC, Atlas de la Biodiversité Communale, Saint-Jean-Saint-Nicolas, Papillons diurnes, Lépidoptères, Rhopalocères, Inventaire, Flavia APE',
	'FALSE',
	'TRUE',
	'425',
	'403',
	'78',
	'75',
	'324',
	'TRUE'),

	('11',
	'Inventaire des hétérocères - ABC Saint-Jean-Saint-Nicolas',
	'Hétérocères ABC SJSN',
	'Inventaire des hétérocères réalisé dans le cadre de l''ABC de la commune de Saint-Jean-Saint-Nicolas',
	'326',
	'ABC, Atlas de la Biodiversité Communale, Saint-Jean-Saint-Nicolas, Lépidoptères, Hétérocères, Inventaire, Flavia APE',
	'FALSE',
	'TRUE',
	'425',
	'403',
	'78',
	'75',
	'324',
	'TRUE')


-- Création du jeu de données "Données opportunistes sans cadre établi" id
INSERT INTO gn_meta.t_datasets (
	id_acquisition_framework,
	dataset_name,
	dataset_shortname,
	dataset_desc,
	id_nomenclature_data_type,
	keywords,
	marine_domain,
	terrestrial_domain,
	id_nomenclature_dataset_objectif,
	id_nomenclature_collecting_method,
	id_nomenclature_data_origin,
	id_nomenclature_source_status,
	id_nomenclature_resource_type,
	default_validity
	)
VALUES
	('5',
	'Données opportunistes - Lépidoptères',
	'Données opportunistes Lépidoptères',
	'Données collectées de manière opportuniste, sans stratégies établies, dans un but d''amélioration des connaissances',
	'326',
	'Amélioration des connaissances, données opportunistes, Papillons, Lépidoptères, Rhopalocères, Hétérocères, Inventaire, Flavia APE',
	'FALSE',
	'TRUE',
	'415',
	'403',
	'77',
	'75',
	'324',
	'TRUE')

-- Renseignement acteurs dans les métadonnées (à voir, mis au groupe adhérents flavia, plutôt mettre les personnes voire Yann)
-- Accordé à tout le groupe Adhérents flavia 1000001
INSERT INTO gn_meta.cor_dataset_actor (
	id_dataset,
	id_role,
	id_organism,
	id_nomenclature_actor_role
)
VALUES
	('10','1000001','3','371'),
	('11','1000001','3','371'),
	('12','1000001','3','371'),
	('13','1000001','3','371')`

**Comment by sig-pnrnm** [comment]
Merci @DonovanMaillard 
Je vais tenter cela avec mon contexte.

@camillemonchicourt 
> Utilise le groupe Grp_en_poste il a un CRUVED qui va bien.

C'est ce que j'ai commencé à faire : je l'ai renommé en "PNRNM_Equipe", mais je lui ai laissé le même CRUVED.

A suivre !

**Comment by sig-pnrnm** [comment]
> Merci @DonovanMaillard
> Je vais tenter cela avec mon contexte. 

C'est bon, ça marche bien chez moi !  :+1: 
> Oui la partie acteurs des formulaires Metadonnees n'est pas terminé

Est-ce que malgré tout, c'est utile que je signale d'autres "bugs" ou "améliorations" ?
Par exemple, je pense qu'il manque un bouton "Annuler" dans les formulaires "Cadres" et "Jeu de données". A bons entendeurs ! :wink:

**Comment by sig-pnrnm** [comment]
Dernière question (de la semaine ! :wink: ) relative aux cadres d'acquisition.
Mes agents doivent pouvoir ajouter des données sur des jeux de données d'un cadre d'acquisition de ma structure.

Ils ne doivent pour autant pas pouvoir modifier les jeux de données (en tout cas, pas pour le moment et pas tous).

Comment faire en sorte de masquer le menu "Admin" pour les agents, tout en leur permettant d'ajouter des données dans un jeu/cadre ?

**Comment by DonovanMaillard** [comment]
La gestion des Cadres et jeux de données est différente d l'ajout de données dans ces cadres ou jeux. 

Le module admin sert uniquement à gérer les métadonnées (cadres + jeux), donc les agents dans ton cas ne doivent pas y avoir accès, ca se gère avec le cruved comme pour tous les modules. 

Ensuite, chaque role a accès ou non à tel jeu de données. Si un utilisateur a accès à occtax et qu'il est dans les roles d'un jeu de données, il pourra ajouter des données dans ce jeu de données. 

Le jeu de données est lui meme dans un cadre d'acquisition, ce sont deux notions qui s'imbriquent. Donc ils saisiront des données dans occtax, ces données seront rattachées à un jeu de données. Et ce jeu lui meme sera rattaché à un cadre d'acquisition, mais ca c'est transparent pour l'utilisateur au niveau de la saisie. 

Du coup, dans ton cas, tu retire les droits aux agents sur le module admin, mais tu rattraches les jeux de données au groupe "equipe PNRNM" et ça sera bon :)

**Comment by camillemonchicourt** [comment]
En fait, par défaut on attribue un CRUVED global sur GeoNature à chaque groupe. 
Mais tu peux surcoucher ce CRUVED à un rôle (utilisateur ou groupe), module par module.
Pour masquer un module à un rôle, il faut lui mettre un R (read), à 0. 
UsersHub V2 permettra de gérer ça en interface.

En attendant pour désactiver l'accès au groupe EN POSTE : 

```SQL
INSERT INTO utilisateurs.cor_app_privileges (id_tag_action, id_tag_object, id_application, id_role)
VALUES
(12, 20, 4, 7);
```

Je vais ajouter ça et faire quelques ajustements aux droits et groupes qu'on attribue par défaut, pour la RC3.

OK avec toi Donovan, mais pour qu'un utilisateur puisse saisir ou non dans un JDD, ça peut passer aussi (plutôt) par les JDD pour lesquels son organisme est acteur.

**Comment by DonovanMaillard** [comment]
Ok, merci pour la précision! Et désolé pour la fausse piste alors!

**Comment by camillemonchicourt** [comment]
C pas une fausse piste, ça en est une autre.
Faudra qu'on précise ça dans la doc.

**Comment by sig-pnrnm** [comment]
> Faudra qu'on précise ça dans la doc

En effet, mais je me doute qu'il y a encore plein de choses plus urgentes
Bon courage et merci pour vos éclaircissements !

**Comment by camillemonchicourt** [comment]
@TheoLechemia est en train de travailler sur les corrections des formulaires de métadonnées (https://github.com/PnX-SI/GeoNature/commits/develop). 
Par ailleurs, concernant les acteurs, il nous semble qu'il faut privilégier de les attribuer à des Organismes. Et éventuellement à des Personnes quand il s'agit d'indépendants, de bénévoles individuels ...
Mais de ne pas les associer à des Groupes de UsersHub qui sont des notions de groupes de droits et non pas de métadonnées. 
On a donc désactivé les groupes dans la liste des Acteurs des métadonnées : https://github.com/PnX-SI/GeoNature/commit/f9f82002c9a73ac88c74c34d86b0e546762e4343
De toute façon l'appartenance à un groupe n'était pas vérifié au niveau du CRUVED côté GeoNature.

**Comment by DonovanMaillard** [comment]
Merci pour linfo. Côté méta-données la notion de publications, qui est dispo dans la base, est prévue prochainement dans le module admin ou c'est pas planifié ? :)

**Comment by gildeluermoz** [comment]
A ma connaissance pas planifié. En tous pas le souvenir d'en avoir parlé. Si ça doit se faire il faudra en prévoir l'usage coté front dans GeoNature. Car s'il y a admin, c'est pour que ça serve qq part. Pour le moment, un remplissage en base n'est pas trop complexe à faire si besoin urgent. Et puis il y a tellement de sujet centraux à traiter avant celui-ci...

**Comment by DonovanMaillard** [comment]
Oui biensur pour l'urgence et idem pour l'interface ;) simplement pour savoir si c'était planifier ou si c'est à faire, par les partenaires par exemple (ça représente "pas grand chose à faire" à priori)

**Comment by TheoLechemia** [comment]
La vérification que les acteurs des JDD ou CA ne sont pas des groupes a été rajouté en base via une contrainte. Il faudra donc que les personnes qui ont mis des groupes dans les acteurs les remplace par des organismes (en interface en mettant une ligne vide dans la liste déroulante, ou directement en BDD)
