### ISSUE TITLE
Affichage des relevés dans OccTax

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/GeoNature#467]
Une petite suggestion, pas du tout urgente, mais que je trouverais pratique.

Dans Occtax, la vision des derniers relevés est en fait une synthèse des relevés, dans le sens ou 1 ligne = 1 relevé (donc potentiellement x occurences de y taxons).
Dans la synthèse, le tableau est bien un tableau des occurences (1 ligne = 1 occurence = 1 taxon).

On peut avoir tendance, dans Occtax, à penser que c'est la même chose, puisque seul le premier taxon est généralement visible dans le tableau (j'ai bien vu que la liste des taxons du relevés est concaténé comme cela : `taxon1, taxon2, taxon 3, ... taxon n`).

Donc, plutôt que d'afficher uniquement le premier taxon, il serait utile d'avoir le nombre de taxons du relevés.
(ça marche aussi avec les observateurs, du coup)

Voici ce que ça pourrait donner avec un badge de Bootrstap `(<spanclass="badge badge-pill badge-dark">Dark</span>` ) : 

![occtax_releves](https://user-images.githubusercontent.com/26482054/46871256-2a1c0980-ce31-11e8-80a9-bd038f276514.png)

**Comment by gildeluermoz** [comment]
Excellente proposition. 
Il faut même se poser la question d'afficher seulement les occurrences, car taxons, date et jjd sont les entrées principales pour trouver une occurrence à éditer.
Mais Camille va dire qu'il ne faut pas créer de confusion avec la synthèse.
Beau sujet 😊

**Comment by camillemonchicourt** [comment]
Oui oui ça sera bien plus clair et lisible avec des compteurs.

En effet on a déjà pas mal discuter de lister des relevés ou des occurrences dans Occtax.
Et oui on a pas voulu créer de confusion avec la synthese (même si il y a d'autres éléments prévus pour réduire le risque de confusion) et aussi on a pris un principe qui est de se dire que dans les modules on présente les données telles qu'elles ont été saisies (donc par relevés dans Occtax) et dans la synthese on les met à plat.

Car nos histoires de modules, protocoles, données sources et synthèse sont pas forcément instinctives de premier abord pour les utilisateurs.

**Comment by DonovanMaillard** [comment]
Concernant l'affichage des relevés dans occtax, il serait intéressant de les ordonner par date (de début ou de fin), le plus récent en premier. Sur notre instance avec 30 relevés, j'ai un ordre qui ne semble correspondre à rien (dates d'updates peut être?)
