### ISSUE TITLE
Occtax - Impossible de créer des relevés ligne et polygone

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#469]
Ça fonctionnait bien il y a quelques temps.
Quand on dessine une ligne ou un polygone, ça ne dégrise plus la partie formulaire.

**Comment by gildeluermoz** [comment]
C'est nouveau ça ou on avait pas testé ?

**Comment by camillemonchicourt** [comment]
Ça me semble relativement nouveau car ça fonctionnait il y a peu de temps mais je ne sais pas dire exactement quand.

**Comment by gildeluermoz** [comment]
DONE : 7de6c598dcfaea4356795fe030f95560e12af66c
