### ISSUE TITLE
Occtax - permettre l'édition d'un polygone ou d'une ligne

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#470]
Si un relevé est créé avec une ligne ou un polygone, on ne peut pas éditer la géométrie. il faut la supprimer et la recréer.

**Comment by camillemonchicourt** [comment]
L'interface le permet avec le bouton MODIFIER au niveau des outils de la carte. 
Mais l'enregistrement n'est pas pris en compte : https://github.com/PnX-SI/GeoNature/issues/473

**Comment by gildeluermoz** [comment]
OK. C'est une erreur de ma part. L'enregistrement non pris en compte est corrigé : 6093095c59c5ce7d28c86ac59703eb4121171175
