### ISSUE TITLE
MAP - Le type ligne n'est plus disponible en édition

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#472]
Je créé un relevé de type ligne
j'édite ce relevé et l'outil de création de ligne n'est pas disponible. Seulement point, polygone, rectangle et cercle.
![image](https://user-images.githubusercontent.com/10024739/46951794-4619e800-d089-11e8-8e1f-963507be5494.png)

**Comment by gildeluermoz** [comment]
A priori résolu. C'est probablement ce commit 2b18b85dd731b03c5a3491878aaad1de67a9efed qui a corrigé ce bug qui devait venir du fait que le style avec les propriétés `fill` et `fillOpacity` présentaient les lignes à LeafletDraw comme un Polygon.

**Comment by camillemonchicourt** [comment]
Désormais le type Lignes n'est plus disponibles ni en Création ni en Modification de relevés.

**Comment by camillemonchicourt** [comment]
Autant pour moi je devais encore avoir le JS de ma précédente installation dans le cache. 
Après un CTRL + F5, c'est OK.

**Comment by gildeluermoz** [comment]
Ouf. Je ne comprenais plus là. J'ai testé ça plusieurs fois avant de le comiter.
