### ISSUE TITLE
Export Occtax - Commentaire

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#478]
Le champs ``obsCtx`` ne contient que le commentaire du relevé mais pas celui de l'occurrence.

**Comment by TheoLechemia** [comment]
Il y a deux champs commentaire dans le standard. Le commentaire de l'occurrence n'était pas fournit dans l'export. C'est corrigé:
![comment](https://user-images.githubusercontent.com/15265745/47647035-20efa400-db76-11e8-9a05-fbfa383bdba2.png)

**Comment by camillemonchicourt** [comment]
OK mais du coup, désormais on va générer les exports SINP à partir de la Synthèse et non plus depuis OccTax (voir https://github.com/PnX-SI/gn_module_export/issues/22). 

Hors dans la Synthèse on n'a qu'un champs COMMENTAIRE et on s'est galéré à concaténer les commentaires du Relevé avec celui de l'Occurrence : https://github.com/PnX-SI/GeoNature/issues/459

Mais du coup quand on va faire un export SINP depuis la Synthèse, on ne pourra plus dissocier les 2 champs pour les sortir selon le standard SINP.
Le mieux serait peut-être de garder ces 2 commentaires dans la Synthèse pour mieux coller au standard SINP ?

**Comment by gildeluermoz** [comment]
très bonne remarque.
Si tout le monde est d'accord on migre vers la solution proposé par Camille (pas mal de petite modif à faire et à tester car cela impact les triggers synthèse mais ça va vers une simplification)
De mon coté je la trouve cohérente.

**Comment by camillemonchicourt** [comment]
C'est OK pour le faire côté Synthèse.
