### ISSUE TITLE
Occtax - Ne pas afficher le bouton Supprimer si on n'a pas les droits

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#480]
Le bouton est affiché mais si on n'a pas les droits, l'appli renvoie le message "Vous n'avez pas le droit d'effectuer cette action".

**Comment by TheoLechemia** [comment]
Pareil, je n'arrive pas à reproduire. J'ai un utilisateur avec R=3 et D=1, le bouton est bien grisé et on ne peut pas cliquer dessus.
Tu étais sur la fiche "info" en venant de la synthese ?

**Comment by TheoLechemia** [comment]
Revérifier, OK
