### ISSUE TITLE
Update Relevé et digitiser

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#481]
Je modifie un relevé créé par un autre utilisateur, j'en deviens le Digitiser. 
Est-ce souhaitable qu'à chaque modification d'un relevé, la personne qui a fait la dernière modification devienne le digitiser ?
Je pense que c'est plutôt celui qui a créé le relevé initialement qu'il faut garder. 

Autre effet de bord. 
Je n'ai le droit de supprimer que mes données mais je peux modifier toutes les données de mon organisme. 
Je modifie le relevé d'un collègue de mon organisme. 
J'en deviens donc Digitiser. 
Et du coup je peux maintenant le supprimer car il considère que c'est ma donnée.

**Comment by gildeluermoz** [comment]
Je penche pour un comportement équivalent à `initial_digitiser`. Principalement pour l'effet de bord que tu décris qui est une faille permettant de contourner le CRUVED. On ne peut pas s'arroger les droits correspondant à l'auteur d'une obs en la modifiant.
Au delà, quels sont/doivent être les droits du digitiser pour les exports ?

**Comment by camillemonchicourt** [comment]
Oui le digitiser est celui qui a créé un objet, pas le dernier qui l'a modifié. 
Le digitiser est utilisé par le CRUVED comme si il était observateur
