### ISSUE TITLE
Export occtax sinp - date / heure

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#485]
Un détail, mais dans la vue export sinp de occtax, le format de la date donne une heure (toujours minuit) alors que l'heure début renseignée est à 20h. 

2 infos différentes selon le champ qu'on utilise, il faudrait pas retirer l'heure du champ date début?

**Comment by camillemonchicourt** [comment]
Oui il y a une homogénéisation à faire à ce niveau sur les format des dates par rapport aux heures.
Et à coordonner avec ce qu'il y a dans la synthèse.
