### ISSUE TITLE
Concaténation des commentaires (Relevé et Occurence)

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/GeoNature#487]
Je trouve que la concaténation des commentaires de relevés et occurences, pour la synthèse ou les exports par exemple, pourrait être améliorée.
Avant de proposer une éventuelle PR, je préfère proposer une amélioration ici.

Voici la formule actuelle, [par exemple ici](https://github.com/PnX-SI/GeoNature/blob/9f3589d1f1cc13c906c401d18fa3897101f3a6ee/contrib/occtax/data/occtax.sql#L733).

```sql
CONCAT(COALESCE('Relevé : '||releve.comment || ' / ', NULL ), COALESCE('Occurrence: '||occurrence.comment, NULL)),
```
Outre le fait qu'il y a un espace après `Relevé :` mais pas après `Occurence:` (+une petite faute d'orthographe : il n'y a qu'un seul `r` à `occurence` [*]), le résultat n'est pas très lisible dans les export, d'autant plus si les commentaires sont sur plusieurs lignes.

Voici ce que ça donne avec une occurence bidon : 

```
Relevé : Commentaire de relevé bidon.
Avec retour à la ligne en plus !Occurrence: Commentaire occurence : avec retour à la ligne.
Là, c'est une deuxième ligne
```
Personnellement, je trouverais plus lisible d'avoir des caractères d'encadrements entre les 2 commentaires, un peu à la manière du JSON. Voici une proposition : 

```sql
	CASE	WHEN releve.comment IS NOT NULL
		THEN '{Relevé : ' || releve.comment || '}'
		ELSE ''
	END
	||
	CASE	WHEN occurence.comment IS NOT NULL
		THEN '{Occurence : ' || occurence.comment || '}'
		ELSE ''
	END
```

On pourrait sinon simplement ajouter au moins un retour à la ligne ( `\n` ) entre les 2 commentaires (quand les 2 sont présents).

Merci pour vos avis !

Sylvain qui pinaille

[*] En fait, je viens de me rendre compte que c'est carrément le nom de la table `pr_occtax.t_occurrences_occtax` qui a une fote d'ortografe. Booouhhh :laughing:

**Comment by gildeluermoz** [comment]
👎 https://www.larousse.fr/dictionnaires/francais/occurrence/55515
occu**rr**ence

Merci pour la proposition d'amélioration. Ca m'a l'air bien. La difficulté c'est d'intégrer ça proprement sans péter les triggers qui commence seulement à bien fonctionner. On va se garder ça pour une future version.
Les `{` c'est pour faire joli ?

Merci

**Comment by camillemonchicourt** [comment]
Oui pour le 2 rr on a vérifié plusieurs fois quand même avant. :-)
Et l'INPN sait bien comment ça s'écrit ;-)
https://inpn.mnhn.fr/telechargement/standard-occurrence-taxon

Oui pour l'espace je l'avais vu, je vais le corriger. 
Pour le reste, on a bien galéré sur les triggers (https://github.com/PnX-SI/GeoNature/issues/459) donc on va y aller doucement. 
Mais oui ça peut être un peu mieux. 
Mais pour les ``{``, je suis pas sur que ça soit le signe le plus parlant pour les utilisateurs.

**Comment by sig-pnrnm** [comment]
> :-1: https://www.larousse.fr/dictionnaires/francais/occurrence/55515
> occu**rr**ence

Oops :stuck_out_tongue_closed_eyes:  : voila ce que c'est de se servir de G**gle comme dictionnaire (qui donne les résultats anglais avant Français...)

> Les `{` c'est pour faire joli ?
C'est pour "encadrer" mais en fait, peu importe le caractère d'encadrement.
Je me suis inspiré du format JSON, mais c'est une habitude.
Un retour à la ligne fera l'affaire si on veut rester simple.

**Comment by camillemonchicourt** [comment]
Espace après "Occurrence" corrigé dans la future RC3.

**Comment by gildeluermoz** [comment]
Pour les `{` je ne suis pas fan. Justement par ce que ça peut poser des soucis de conflit quand tu vas utiliser le commentaire dans un json. Genre dans l'API backend... On a mis un `/` mais le pipe serait mieux je pense.

**Comment by sig-pnrnm** [comment]
> On a mis un `/` mais le pipe serait mieux je pense.
Oui, le pipe serait mieux en effet pour la lisibilité.
Mais comme les commentaires peuvent comporter des retours à la ligne (saisis par les utilisateurs), il est selon moi important - aussi - d'ajouter un retour à la ligne (` \n `) entre les deux commentaires.

**Comment by sig-pnrnm** [comment]
Et vu que l'utilisateur peut saisir toute sorte de caractères dans les commentaires, il faudrait peut-être avoir des contrôles sur la présence de caractères spéciaux dans ces champs là ?
(peut-être est-ce déjà présent ?)
