### ISSUE TITLE
Deconnexion - redirection

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#490]
Rediriger l'utilisateur sur la page de Login quand il est déconnecté.

**Comment by TheoLechemia** [comment]
Normalement c'est déjà le cas. 
A chaque requête envoyé au serveur on regarde s'il y a toujours un token en cookie. Si non, on le redirige vers la page de login.
La redirection se fait donc au prochain appel serveur de l'utilisateur (s'il change de page par exemple)

https://github.com/PnX-SI/GeoNature/blob/master/frontend/src/app/services/http.interceptor.ts#L29

**Comment by TheoLechemia** [comment]
Dorénavant, si l'utilisateur ne fait aucune action pendant 20 minutes (paramétrable), il sera deconnecté, s'il ne fait aucune appel server.
Utilisation de la librairie ng-idle: https://github.com/HackedByChinese/ng2-idle/tree/master/modules/core/src

**Comment by RomainBaghi** [comment]
Bonjour, 

J'ai pas pu testé les 20 minutes mais il m'arrive souvent de m'apercevoir que je ne suis plus loggé au moment d'enregistrer un relevé. C'est assez frustrant de perdre sa saisie en cours ! 
Ce qui veut dire qu'il y a des cas où l'on est pas redirigé vers la page de login automatiquement même
si on est plus loggé.
Je ne comprends pas encore très bien comment fonctionnent les "tokens" mais
est-ce qu'on peut pas ajouter un test sur la validité du token toute les minutes ? ou X secondes ?

**Comment by TheoLechemia** [comment]
Est-ce que tu as a changé le paramètre `COOKIE_EXPIRATION` dans ta conf? Par défaut le cookie dure 7 jours et est renouvelé à chaque appel à la base (si le paramètre `COOKIE_AUTORENEW = true`)

**Comment by ca-rock** [comment]
Bonjour,
Je me fais déconnecter de GeoNature quand je me logge avec le même utilisateur sur Usershub, est-ce que c'est un comportement attendu ?
Merci

**Comment by TheoLechemia** [comment]
C'est volontaire mais pas idéal. Comme généralement Usershub et GN sont sur le même domaine, ils partagent le même cookie. Celui-ci encapsule le nom de l'utilisateur et ses droits. En passant d'un GN à UserHub on pourrait récupérer les droits d'une application à l'autre. Du coup quand l'id_application du cookie est differente de celui sur lequel on se trouve, alors on force la destruction du cookie, et donc la deconnexion.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.14.0.
Et on peut désormais être connecté sur UsersHub et/ou TaxHub en parallèle de GeoNature.
