### ISSUE TITLE
Sous-module GN et connexion BDD

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#498]
Actuellement dans les modules GeoNature externes, on duplique la connexion à la BDD dans le ``settings.ini`` spécifique du module.
Cela ne semble pas necessaire. 
On pourrait faire appel au ``settings.ini`` global de la BDD lors de l'installation d'un module externe.

**Comment by TheoLechemia** [comment]
La fonction ``gnmodule_install_app(gn_db, gn_app)`` du fichier ``install_gn_module.py`` de chaque module fournit une instance de la base de donnée: ``gn_db``, ce qui permet de directement lancer des scrpits SQL sans dupliquer le fichier ``settings.ini``. Voir cet exemple dans le module CMR:
https://github.com/PnX-SI/gn_module_cmr/blob/master/install_gn_module.py#L21

**Comment by camillemonchicourt** [comment]
OK donc il faudra qu'on utilise ça plutôt que de dupliquer la connexion à la BDD dans le settings.ini des modules comme gn_module_export et gn_module_suivi_flore_territoire

Peut-être à indiquer dans la doc de développement d'un module et/ou dans le module exemple si c'est pas déjà le cas.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.0.0-rc.4 en l'indiquant dans la doc ainsi que dans le template d'exemple de module GeoNature : https://github.com/PnX-SI/GeoNature/tree/master/contrib/module_example
