### ISSUE TITLE
SYNTHESE : Bounding box des résultats

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#500]
Ajouter un bouton pour caler la carte sur la bounding box de la requête ?
Ou se recentrer automatiquement sur la bounding box des résultats quand on lance une recherche ?

**Comment by gildeluermoz** [comment]
Plutôt se caler sur la BBox automatiquement.
Ne pas compliquer l'interface avec un bouton inutile  ;-)
Ce comportement est parfait et bien compréhensible.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.0.0 à venir
