### ISSUE TITLE
Relancer INSTALL_ALL et conf Apache

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#502]
En cas de nouvelle installation globale (``install_all.sh``) de GeoNature V2 sur le serveur, penser à modifier les fichiers de conf Apache car ils conservent les paramètres de la première installation : 
```
sudo nano /etc/apache2/sites-available/geonature.conf 
sudo nano /etc/apache2/sites-available/taxhub.conf
sudo nano /etc/apache2/sites-available/usershub.conf
```

En effet, si l'utilisateur lance plusieurs fois l'installation globale, les configs Apache s'empilent dans le fichier ``sites-available/geonature.conf``

Mais est-ce bien fonctionnel de relancer un ``install_all.sh`` sur un serveur sur lequel on l'a déjà lancé ?

**Comment by gildeluermoz** [comment]
Il n'y a pas que la conf apache à vérifier en cas de relance du script.
Je propose de ne pas gérer ça dans la 2.0.0.
Non urgent.
Plutôt documenter le snapshot qui est de toute manière une bonne pratique.

**Comment by gildeluermoz** [comment]
Non pas dans la V2.0.0
Plus tard.
Conseiller le snapshot qui est de toute manière une bonne pratique

**Comment by camillemonchicourt** [comment]
Oui c'est à éviter mais on l'a fait hier et ça s'est bien passé. 
Mais la première installation n'avait été que très partielle.

Dans tous les cas, ça serait une bonne chose que, dans le processus d'installation, on vérifie les fichiers de conf Apache et on les supprime si il existe avant de créer les nouveaux.

**Comment by camillemonchicourt** [comment]
C'est maintenant géré, avec vérification si la conf Apache existe : https://github.com/PnX-SI/GeoNature/commit/6f03f6de58a3dd7c52e2d5e9de611f1ce400a152
