### ISSUE TITLE
Installation et commande GeoNature

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#505]
Installation requierement python :
```
    Could not install packages due to an EnvironmentError: [Errno 13] Permission non accordée: '/usr/local/lib/python2.7/dist-packages/chardet'
Consider using the `--user` option or check the permissions.
```

La commande geonature doit être installée indépendamment du fait que les packets python ont bien été installés.

**Comment by TheoLechemia** [comment]
Je ne connais pas le contexte de l'installation de ces requirements. Mais à mon avis, elle n'a pas été lancée dans un virtualenv (c'est python 2.7 qui est exécuté pour installer les paquets, et ils semble qu'on les installe globalement sur la machine ``/usr/local/lib/python2.7/dist-packages``)
ça peut peut-être venir d'un problème de création du virtualenv en amont.

**Comment by camillemonchicourt** [comment]
Je sais pas j'ai copie colle un message que tu avais noté sur la Framapad lors du workshop

**Comment by TheoLechemia** [comment]
Ok. Dans ce cas j'avais réglé ça avant mes congés.
