### ISSUE TITLE
redirection automatique vers https de geonature

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#507]
Dans mon fichier de conf apache pour l'atlas `/etc/apache2/sites-available/atlas.conf` , j'ai les lignes suivantes : 

```
<VirtualHost *:443>
ServerName mon-url.fr
<Location />
    ProxyPass http://127.0.0.1:8080/
    ProxyPassReverse http://127.0.0.1:8080/
</Location>
RewriteEngine on
RewriteCond %{SERVER_NAME} =mon-url.fr
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
/VirtualHost>
```

Dont les trois dernières ajoutées par let's encrypt pour (si j'ai bien compris) rediriger automatiquement vers l'url en https. Cette configuration fonctionne très bien.

J'essaye de réutiliser ces 3 lignes pour faire de même pour mon instance géonature qui est sur un sous domaine avec ce fichier de conf (ci dessous) mais sans succès. Si quelqu'un a une idée du pb je suis preneur... 
ps : mon appli geonature fonctionne tres bien a l'adresse `https://sousdomaine.domaine.fr` mais si l'on ne renseigne que `sousdomaine.domaine.fr` on tombe sur la page apache par defaut.

```
<VirtualHost *:443>
ServerName sousdomaine.domaine.fr
DocumentRoot "/home/geonatureadmin/geonature/frontend/dist"
<Directory /home/geonatureadmin/geonature/frontend/dist>
Require all granted
</Directory>
<Location /api>
ProxyPass http://127.0.0.1:8000
ProxyPassReverse  http://127.0.0.1:8000
</Location>
SSLCertificateFile /etc/letsencrypt/live/sousdomaine.domaine.fr/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/sousdomaine.domaine.fr/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
 
RewriteEngine on
RewriteCond %{SERVER_NAME} =sousdomaine.domaine.fr
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```

**Comment by RomainBaghi** [comment]
J'ai testé et il ne se passe rien. Je fais un restart d'apache après la modif du fichier de conf mais peut être que cela ne suffit pas ?

**Comment by camillemonchicourt** [comment]
Voir la doc qu'on a fait sur le HTTPS : https://geonature.readthedocs.io/fr/latest/https.html

Mais là c'est pas notre fort et ça concerne la conf APACHE et le HTTPS et pas GeoNature. 

Sinon les redirections de HTTP vers HTTPS sont souvent gérées directement au niveau de l'appli dans un ``.htaccess`` : https://docs.ovh.com/fr/hosting/htaccess-reecriture-url-mod-rewrite/

https://docs.ovh.com/fr/hosting/eviter-les-pieges-du-ssl-avec-mon-site-web/

**Comment by RomainBaghi** [comment]
Du coup la solution est de faire faire le "rewrite" depuis le port 80 : 

```
<VirtualHost *:80>
  ServerName sousdomaine.domaine.fr

  RewriteEngine on
  RewriteCond %{HTTPS} !on
  RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}

</VirtualHost>

<VirtualHost *:443>
...
```

**Comment by camillemonchicourt** [comment]
Ces éléments ont été intégrés dans la DOC de la 2.0.0-rc.4 avec des compléments de la doc HTTPS et la création d'une doc APACHE : https://geonature.readthedocs.io/fr/latest/conf-apache.html
