### ISSUE TITLE
Intégrer le ou les organismes à la synthèse et dans les filtres de recherche

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#512]
A discuter pour la synthèse, 

Il semble très important que le ou les organismes soient rattachés aux occurrences dans la synthèse et les exports. Comme camille me l'a rappelé, plusieurs acteurs peuvent être mobilisés pour une seule donnée. 

Le plus simple serait peut être de concaténer le ou les acteurs avec leur rôle : 
Parc national des Ecrins (Financeur) - Flavia APE (Producteur) par exemple? 

Une autre solution, moins claire pour moi mais qui se prête peut être davantage à certaines analyses de données : prévoir un champ par type d'acteur (pas le plus intéressant à mon avis, mais c'est une possibilité) 

2eme aspect : est-il possible (et est-il pertinent selon vous) de rendre les organismes filtrables dans la synthèse? Je pense que la fonction peut être intéressante, notamment pour filtrer "les données de mon organisme" ou "tout ce que j'ai" lorsque je fais des recherches dans la synthèse, autrement qu'en prenant les jeux de données pour faire ce tri, ce qui devient vite inutilisable avec quelques dizaines de JDD de plusieurs organismes.

**Comment by camillemonchicourt** [comment]
Je pense qu'en peut filtrer et afficher les Organismes d'une donnée sans avoir à dupliquer l'information dans la Synthèse mais en faisant une jointure sur les métadonnées d'une donnée.

**Comment by DonovanMaillard** [comment]
Oui le but était de le rendre dispo dans l'export ;) mais la même chose peut se faire pour l'export, je sais pas le plus intéressant entre faire des jointures pour chacun des deux aspects, Ou intégrer l'information directement dans la table synthèse

**Comment by TheoLechemia** [comment]
Ok pour les filtres par organisme + les "acteurs" dans l'export (pour chaque acteur on associe son role - producteur/financeur...)
https://github.com/PnX-SI/GeoNature/commit/add4b405ed0d3225fdcbab16abb943e5f2073919
et
https://github.com/PnX-SI/GeoNature/commit/34c8154d75f4f95e0b410ac1a46ae22e2a17a00c

**Comment by camillemonchicourt** [comment]
Et aussi affiché dans les fiches détails de la Synthèse ?

**Comment by TheoLechemia** [comment]
Done
