### ISSUE TITLE
Occtax - supprimer la validation d'une occurrence supprimée ?

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#513]
Actuellement lorsqu'on supprime un relevé ou une occurence ou un counting dans occtax, on trace ces actions dans `gn_commons.t_history_actions` mais les validations successives dans `gn_commons.t_validations` restent orphelines. 
Faut-il mettre à jour les triggers DELETE d'occtax pour supprimer les validations concernant des enregistrements qui n'existent plus dans la base ?  OU, faut-il conserver ces statuts de validation considérant qu'avec la table `gn_commons.t_history_actions` on peut éventuellement 'réabiliter' une observation supprimée ?

**Comment by camillemonchicourt** [comment]
A chaud je dirai que ce n'est pas grave d'avoir des validations orphelines et qu'en effet ça peut être utile si on réhabilite une occurrence supprimée.

**Comment by DonovanMaillard** [comment]
la difficulté, come from naturaliste ;) , c'est que ça devrait dépendre des champs :D 
j'ajoute un sexe un dénombrement, ca change pas la validation. Je change l'espèce, le déterminateur, la méthode de détermination... ba ça dépend :D Tu le sens le truc chiant qui arrive à petit pas?

**Comment by camillemonchicourt** [comment]
Oula alors là, à chaud, je dirai BOF. 
:-D
Déjà que bon...

**Comment by sig-pnrnm** [comment]
Pour ma part, je partirais du principe que, dès qu'une occurence est modifiée, quelle que soit la modification (sinon, on n'en fini plus), elle repasse en statut "`en attente de validation`" (j'ai oublié le terme exact)

**Comment by gildeluermoz** [comment]
C'est pas vraiment le sujet mais autant je comprends la logique de ta proposition Donovan, autant je dirais : Oulala ! J'aimerais pas être validateur. Tu valides qq chose mais c'est pas définitif, faut y revenir... Encore et encore. Tout ça parce que machin chouette qui à les droit a corrigé une faute d'orthographe dans les commentaires ou a modifié de qq mètre l'altitude, parce que quand même faut être précis ! Et là le validateur va dire : "Mais je l'ai déjà validée cette obs !"
Et moi je vous dirai : "mais qu'elle usine à gaz cette notion de validation !".

**Comment by gildeluermoz** [comment]
Camille, ça veut dire quoi ta réponse ? On garde les orphelins ou pas ? En gros si on supprime une obs, on perd le statut de validation ou on le garde au cas où ?

**Comment by camillemonchicourt** [comment]
On garde les orphelins du coup.

**Comment by gildeluermoz** [comment]
Ok ! C'est plus simple. Et de toute façon réabilité des obs supprimées demande un bon gros boulot d'admin pas simple à partir du json de la table des historiques. A l'admin de voir ce qu'il fait à ce moment là pour le statut de validation, sachant qu'il est dispo aussi. Ca roule ! On fait ça. Et puisqu'il n'y a rien à faire, je veut bien le faire...

**Comment by gildeluermoz** [comment]
Vous voulez ouvrir un ticket pour la discussion concernant le que faire du statut de validation des obs modifiées ? Ou on change le titre de celui-ci pour l'élargir ?

**Comment by camillemonchicourt** [comment]
Oui impec. A l'admin aussi de voir si il veut faire du ménage dans les validations orphelines. :+1:

**Comment by camillemonchicourt** [comment]
Oui OK, je m'en occupe.

**Comment by sig-pnrnm** [comment]
> "mais qu'elle usine à gaz cette notion de validation !"

Personnellement, je pense que c'est moins "usine à gaz" si on part du principe que toute modification implique re-validation. Si on doit identifier les modification qui implique modification ou non, là on tombe vraiment dans l'usine à gaz !

Sinon, si je comprends que ce sujet soit complexe à modéliser d'un point de vue informatique. Mais je reviens d'une réunion dans le cadre de notre plateforme SINP régionale, avec tous les acteurs naturalistes Normands autour de la table, et cet impératif de validation **scientifique** des données est revenu à plusieurs reprises.
Notamment, en citant le site de l'INPN qui affiche maintenant, avec la remontée croissante de données dans le cadre SINP, des données clairement fausses...
