### ISSUE TITLE
Mettre à jour vers Standard Occurrence de taxons V2

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#516]
On est actuellement sur la version 1.2.1.
La V2 est sortie il y a 6 mois.

Les évolutions ne sont pas majeures mais certaines intéressantes.

Les modifications sont listées au début du document : https://inpn.mnhn.fr/docs/standard/Occurrences_de_taxon_v2_0_FINALE_LONGUE.pdf

**Comment by camillemonchicourt** [comment]
Il semblerait que la version suivante soit sortie mi-janvier : http://standards-sinp.mnhn.fr/observations-et-suivis-de-taxons-v4-0/

Il s'agit de la V4.0, sans être passé par une V3.0. Et en étant renommé Standard et Dictionnaire de données "Observations et suivis de Taxon" : http://standards-sinp.mnhn.fr/observations-et-suivis-de-taxons-v4-0/

Pas certain que cela soit définitif car le document n'est pas référencé partout, par exemple ici : https://inpn.mnhn.fr/telechargement/standard-occurrence-taxon

**Comment by jbdesbas** [comment]
Merci pour le lien, la suppression des champs _dsPublique_, _organismeGestionnaireDonnées_, etc.. dans le standard va dans le sens de ce qui ce fait déjà dans GN : la gestion de ces questions au niveau des métadonnées : cool ! :+1:

**Comment by camillemonchicourt** [comment]
A l'occasion de la refonte en cours du module Occtax (https://github.com/PnX-SI/GeoNature/issues/758), on en profite pour passer de la version 1.2.1 à la version 2.0 du standard SINP Occurrences de taxons. 

@TheoLechemia y travaille dans une branche dédiée : https://github.com/PnX-SI/GeoNature/tree/occtax-v2

- Ajout de la nomenclature "Comportement" (http://standards-sinp.mnhn.fr/nomenclature/110-comportement-des-occurrences-observees-2018-05-14/) / Voir https://github.com/PnX-SI/GeoNature/issues/566
- Ajout de l'habitat sur le relevé (cd_hab)
- Ajout de la méthode de regroupement
- Ajout de la nature de l'objet géographique
- Ajout de la profondeur (min et max)

**Comment by gildeluermoz** [comment]
De mémoire il y a des nomenclatures à mettre à jour. Notamment toutes les nomenclatures concernant les stades de végétation.
Et très probablement d'autres... Forza !

**Comment by camillemonchicourt** [comment]
Oui il y en a quelques unes.
Malheureusement les stades de végétation n'ont pas encore été intégrés.
Les ajouts de nomenclature entre la 1.2.1 et la 2.0 : 

**Ajouts d’éléments dans des nomenclatures** : 

DEEFloutageValue :
- NSP

ObservationTechniqueValue (anciennement ObservationMethodeValue) :
- Contact olfactif
- Empreintes et fèces

OccurrenceComportementValue :  
- Toutes les valeurs

OccurrenceStadeDeVieValue :
- Fruit

OccurrenceStatutBiologique :
- Végétatif

TypeAttributValue :
- NSP

TypeValValue : 
- NSP

**Comment by samuelpriou** [comment]
Une belle avancée en attendant avec impatiente les nomenclatures concernant les stades de végétation !
Merci

**Comment by camillemonchicourt** [comment]
Le champs "Niveau de précision de la diffusion" (``diffusion_level``) était présent jusqu'à présent dans Occtax.

Pour les données sensibles, ce champs est calculé automatiquement dans la Synthèse, en fonction de la valeur du champs calculé "Niveau de sensibilité".

Cependant, pour les données privées non sensibles, certains observateurs souhaitent pouvoir définir un niveau de diffusion dégradé ou nul pour certaines observations. 
Du coup il parait nécessaire de garder le champs ``diffusion_level`` dans Occtax, alimentant le champs correspondant dans la Synthèse dans le trigger Occtax >> Synthèse.

Le standard Occurrences de taxon du SINP indique : 

> diffusionNiveauPrecision : NiveauPrecisionValue
> Alias : difNivPrec 
> Multiplicité : [0..1] 
> Niveau maximal de précision de la diffusion souhaitée par le producteur vers le grand public. Ne concerne que les DEE non sensibles (i.e. données dont le niveau de sensibilité est de 0). Cet attribut indique si le producteur souhaite que sa DEE non sensible soit diffusée comme toutes les autres, à la commune ou à la maille, ou de façon précise.  
> Règle : Il ne peut être utilisé pour diffuser moins précisément des données que dans le cas de données dont au moins une, au sein d'un regroupement, est sensible suivant la définition du GT sensible. Si aucune donnée n'est sensible, alors le niveau maximal de précision de diffusion sera celui par défaut. 
> Cet attribut est FACULTATIF.

La limite de cela est que : 
- la fonction de calcul automatique de la sensibilité dans la Synthèse pourrait écrasé ce qui a été défini manuellement dans Occtax
- les calculs automatiques de niveau de diffusion basé sur le niveau de sensibilité sont stockés dans la Synthèse, mais pas répercuté dans Occtax, donc il peut y avoir une divergence des informations entre le niveau de diffusion dans Occtax et dans la Synthèse pour une même observation

**Comment by camillemonchicourt** [comment]
Certains utilisent l'actuel champs "Technique d'observation" qu'on avait rajouté hors-standard, on propose de ne pas le supprimer brutalement.

Voila donc ce qui a été fait :

- Dans Occtax, renommer le champs "Méthode d'observation" en "Technique d'observation", basé sur l'actuelle nomenclature de "Méthode d'observation"
- Garder l'actuel champs "Technique d'observation" mais le cacher par défaut et le renommer "Technique de collecte Campanule" (ou du genre), pour ne pas perdre les données, toujours permettre sa saisie dans Occtax et son usage dans Occtax et se le garder en attendant que son positionnement soit clarifié avec Campanule
- Supprimer l'actuel champs "Technique d'observation" de la Synthèse, et y renommer le champs "Methode d'observation" en "Technique d'observation" pour limiter les risques de confusion au niveau de la synthèse, des exports Synthèse etc...

Le champs n'est donc gardé que dans Occtax pour ne pas perdre cette possibilité pour ceux qui l’utilisent déjà.

-------------------------------------------

Pour la version de Taxref, on prévoit de supprimer le champs de la Synthèse, mais garder la valeur dans t_parameters, qui permet de savoir dans quelle version est un GeoNature et éventuellement de l'utiliser pour les exports.
Quand on met à jour Taxref, on le modifie pour les éventuelles données où on a mis à jour le cd_nom (après remplacement, split ou merge d'un cd_nom) et ça serait galère, donc potentiellement faux.

Cela reste à faire.

**Comment by camillemonchicourt** [comment]
Réalisé dans la 2.5.0. Reste le champs ``version_taxref`` à supprimer et quelques champs à discuter.
