### ISSUE TITLE
Dysfonctionnement dans l'autocomplete des taxons de occtax

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#518]
Bonjour, 

2 choses repérées sur l'autocomplete des taxons dans occtax, qui rendent la saisie un peu aléatoire. 

- L'autocomplete semble rechercher les noms sur la base de 20 caractères. Du coup si je copie-colle ou si je saisis rapidement un nom complet de plus de 20 caractères, je n'ai aucun taxon qui ressort, même s'il est dans la base. 

- Outre ce problème, il y a des resultats qui apparaissent, ou non, selon le nombre de lettres qu'on saisit. 
Par exemple si je tape phig : j'ai bien phigaliohybernia marginaria et phigaliohybernia marginaria marginaria qui ressortent. Si je tape phi, seule phigaliohybernia marginaria marginaria ressort.

**Comment by TheoLechemia** [comment]
Le 1er point est corrigé.
Par contre le 2ème, je n'arrive pas à reproduire:
![phi](https://user-images.githubusercontent.com/15265745/50144668-0e5d3580-02b0-11e9-8890-346328322841.png)
![phig](https://user-images.githubusercontent.com/15265745/50144683-12895300-02b0-11e9-8646-53aa3adcc3be.png)

J'ai quand même rajouté la possibilité de modifier le nombre de taxon retourné par la recherche. On n'affichait que les 20 premiers résultat avant, c'est maintenant paramétrable.

**Comment by DonovanMaillard** [comment]
Super ! Veux tu un accès à notre instance pour le second bug ?

**Comment by TheoLechemia** [comment]
Oui envoie !

**Comment by camillemonchicourt** [comment]
Amélioration de la recherche des taxons dans la 2.0.0-rc.4 avec l'implémentation de http://si.ecrins-parcnational.com/blog/2019-01-fuzzy-search-taxons.html
