### ISSUE TITLE
UTILISATEURS et DROITS par protocole

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#52]
Aujourd'hui il n'y a qu'une application générale GeoNature dans UsersHub.
Il pourrait être intéressant de dissocier les droits des utilisateurs par protocole. 
Une application Synthèse, une application Contact-Faune, une Faune-Invertébrés, une Flore-Station...

Actuellement il n'y a que 2 types de droits dans GeoNature :
- Rédacteur (niveau 2) qui peuvent saisir dans tous les protocoles et modifier leurs propres données
- Administrateur (niveau 6) qui peuvent modifier toutes les données.

**Comment by sylvain-m** [comment]
J'allais justement faire cette proposition, et je constate que Camille à déjà eu cette idée.
Dans le cadre de notre réflexion partenariale (et de mutualisation), il nous est capital de pouvoir ouvrir ou fermer certains protocoles par utilisateur.

Du coup, on pourrait de ce fait créer un protocole "Contact-Faune" (ou Flore, ou ...) par structure (duplication du protocole de base), afin de ne pas mélanger les données de chaque structure qui pourraient avoir des droits différents.

**Comment by camillemonchicourt** [comment]
Oui ça permettrait éventuellement de faire même si pour cela il vaudrait bien mieux une seule application et schéma par protocole avec des droits différents selon la structure de l'utilisateur.

La duplication serait une alternative que je deconseillerai fortement.

**Comment by gildeluermoz** [comment]
La saisie multi-structures est un sujet à part entière. Il y a d'autres aspects que l'authentification et la gestion des droits. Il faut notamment intégrer la propriété des données (id_organisme). N'oublions pas que le GeoNature actuel est un outil PNE rendu progressivement générique et qu'il est tout sauf multi-structures. 
Pour faire celà, il faut que la donnée saisie soit "taguée" avec un "id_organisme" correspondant à l'organisme propriétaire de la donnée. 
Chaque porteur d'une instance GeoNature aura des logiques potentiellement différentes. 
Pour exemple, actuellement au PNE, si un naturaliste fourni des données au PNE via l'interface de GeoNature (hors convention), elles sont taguées PNE. 
Il n'y a rien dans l'interface qui permette de réaffecter une donnée à un autre organisme. Le seul et unique organisme est déclaré dans la config comme propriétaire de TOUTES les données saisies. 
Sur ce point, seule la V2 permettra une autre approche. 




		
	Gil DELUERMOZ 
Chargé de mission développement web et bases de données 

Parc national des Écrins 
Tél : +33 (0) 4 92 40 20 38 (lundi et mardi) 
+33 (0)4 92 21 08 49 (mercredi et jeudi matin) 
www.ecrins-parcnational.fr 
----- Mail original -----

De: "Camille Monchicourt" <notifications@github.com> 
À: "PnEcrins/GeoNature" <GeoNature@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Mercredi 18 Janvier 2017 10:56:07 
Objet: Re: [PnEcrins/GeoNature] UTILISATEURS et DROITS par protocole (#52) 


Oui ça permettrait éventuellement de faire même si pour cela il vaudrait bien mieux une seule application et schéma par protocole avec des droits différents selon la structure de l'utilisateur. 
La duplication serait une alternative que je deconseillerai fortement.

**Comment by sylvain-m** [comment]
> Sur ce point, seule la V2 permettra une autre approche.

J'en suis bien conscient, et c'est en prévision de cette V2 que je faisais la réflexion.
Mais cette solution détournée 

> il vaudrait bien mieux une seule application et schéma par protocole avec des droits différents selon la structure de l'utilisateur.

C'est bien comme ça que je verrais les choses aussi.

**Comment by camillemonchicourt** [comment]
Fait dans la V2 avec de droits globaux sur GeoNature surcouchables par module.

Par ailleurs il est possible de définir des droits fins par module.

Et de définir des organismes par jeu de données.
