### ISSUE TITLE
Occtax et Validation

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#520]
En appliquant le standard SINP dans la BDD de Occtax, on y avait intégré un champs pour le statut de Validation. 

Désormais on a implémenté la table verticale de stockage de la validation (``gn_commons.t_validations``). Du coup il faut retirer ce champs de Occtax car il pourrait entrainer des erreurs. 

Par contre quand on créé une occurrence de taxon, il faut pousser la valeur de validation par défaut (présente dans la BDD) du coup dans la table transversale. 

- Créer une vue au niveau de ``gn_commons`` pour facilement retourner le dernier statut de validation d'une observation ?
- Revoir Export Occtax
- Revoir trigger Occtax >> Synthèse

On peut utiliser la vue qui avait été faite dans le module Validation (https://github.com/PnX-SI/gn_module_validation/blob/6ec8532882aa7d68e6bb7c519eec4804d039052c/data/validations.sql) puis supprimée car elle n'est plus utilisée depuis qu'on remet à plat la dernière Validation d'une occurrence dans la Synthèse.

**Comment by camillemonchicourt** [comment]
Le champs Statut de Validation n'est plus présent dans les tables d'Occtax.
Par contre il est présent dans la fiche détail d'une occurrence dans le module Occtax mais vide.

J'ai changé la valeur par défaut de la nomenclature "STATUT_VALID" de 466 à 321 dans la table ``pr_occtax.defaults_nomenclatures_value`` mais quand je créé un relevé Occtax, ça continue à lui attribuer le statut de validation 466 dans la table ``gn_commons.t_validations``.

Il y a aussi un statut de validation par défaut dans ``gn_synthese.defaults_nomenclatures_value`` mais sa valeur est à 319 (Probable).
Donc ce n'est pas celle-ci qui est utilisée et je ne vois pas trop si elle est utile.

Il y a aussi une valeur par défaut globale dans ``ref_nomenclatures.defaults_nomenclatures_value`` définie à 466. J'ai modifié celle-ci à 320 (Douteux) pour tester, j'ai créé une nouvelle occurrence et là ça a pris cette valeur dans ``gn_commons.t_validations``. 

La répercussion à plat de ces valeurs dans ``gn_synthese.synthese`` est bien fonctionnelle. 466 pour les premières occurrences et 320 pour la dernière saisie. 

Les 2 problèmes restants sont donc : 
- Que le renseignement du statut par défaut n'utilise pas la valeur définie au niveau de Occtax mais prend que la valeur globale. Il devrait l'utiliser uniquement si il n'est pas renseigné au niveau de Occtax.
- Que l'affichage du dernier statut de validation dans les fiches détail de Occtax ne va pas chercher l'info dans la table ``gn_commons.t_validations``. En affichant l'historique des validations accompagnées du validateur et du commentaire ? Et intégrer le dernier statut de validation dans les exports Occtax ?

**Comment by camillemonchicourt** [comment]
Par contre @gildeluermoz, je ne vois pas qu'il prenne le dernier statut de validation avec un max sur la date quand il alimente la Synthèse ? 
https://github.com/PnX-SI/GeoNature/blob/master/contrib/occtax/data/occtax.sql

Mais je me suis peut-être embrouillé. Ce n'est pas au trigger Occtax >> Synthèse de faire ça mais au trigger ajouté depuis la table transversale ``gn_commons.t_validations``. 

A supprimer du trigger Occtax > Synthese ?

**Comment by TheoLechemia** [comment]
Pour précision, c'est bien la valeur de la table ``ref_nomenclature.defaults_nomenclatures_value`` qui est prise comme valeur par défaut pour la validation pour le module occtax (pas de possibilité de mettre une valeur par défaut par module en l'état actuel des choses).

Le champ concernant le statut de validation par défaut de la table ``pr_occtax.defaults_nomenclatures_value`` a été retiré puisque inutilisé.
