### ISSUE TITLE
Occtax - Heure min / Heure max par défaut

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#522]
Un petit "bug" (en est-ce bien un?) repéré sur occtax. 

On saisit une date unique. Et une heure de début. 
Si je ne mets pas d'heure de fin, je me fais renvoyer. J'imagine que la base mets 0:00:00 par défaut donc ma date fin < date de début ? 

Est-il possible de mettre heure fin = heure début comme c'est le cas pour le date? ou ce fonctionnement est-il intentionnel?

**Comment by TheoLechemia** [comment]
En effet, quand on ne remplit pas la date max, la contrainte en synthese (date_min > date_max) ne passe pas car la base met 00:00.
Le formulaire d'occtax remplit maintenant heure_max=heure_min par défaut.
