### ISSUE TITLE
Requête occtax

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#530]
Dans occtax, les filtres permettent de rechercher sur le critère "preuve d'existence" de manière binaire. Pour retrouver des individus collectés ou référencés (adn etc), il serait intéressant que quand on filtre "preuve d'existence = oui", on puisse saisir la référence de la preuve.

**Comment by DonovanMaillard** [comment]
Bonnjour, 

Je ressors ce sujet. 

Je m'apprêtais à récupérer les filtres dans la synthèse et le module validation pour le dupliquer dans occtax (enfin, j'allais tester...). 

Je me rends compte que les filtres sur les preuves, numériques ou non, ne sont pas fonctionnels, ni sur le module de validation, ni sur la synthèse. Reproduit sur la démo...

**Comment by camillemonchicourt** [comment]
OK, peux-tu préciser "non fonctionnel".

A noter que le bloc de filtre du module Synthèse vient d'être basculé dans les composants génériques et communs de GeoNature pour pouvoir être factorisé et partagé entre les modules Synthèse et Validation (et autres à venir ?) : https://github.com/PnX-SI/GeoNature/commit/79e87985ac887850f27f05a7f61471acb143f361

**Comment by DonovanMaillard** [comment]
Oui biensur. L'interface se grise et ne répond plus.

En l'occurrence je tenterai de l'ajouter à occtax mais le principal est de ke corriger la ou il existe déjà actuellement.

Pour faire un test j'ai saisi une donnée sur la demo (aaptos) avec une preuve non numérique "101" (je crois, à vérifier). Si je cherche sur ce critère le spinner tourne et la navigation reste bloquée

**Comment by TheoLechemia** [comment]
Corrigé

**Comment by DonovanMaillard** [comment]
Merci bien! :)
