### ISSUE TITLE
Retours utilisateurs et propositions synthèse

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#531]
J'ouvre une issue ici qui est assez large, sur les différents retours qu'on me fait sur la synthèse. Je ne dis pas que tout doit être implémenté, encore moins par les parcs :) simplement je récapitule ici pour mémoire et ajouts, les retours qui sont faits sur la synthèse.  

- Demande de pouvoir filtrer par organisme (déjà abordé dans le #512  )

- Le filtre des taxons sur "Règne" et "Groupe" n'est pas bien compris par une partie des utilisateurs (j'en suis!). J'ai pensé qu'il servait à filtrer "tous les animaux", ou "tous les animaux du groupe Oiseaux" dns la recherche.. En fait non, il filtre simplement les noms dans l'autocomplétion à la saisie. 

- Les filtres prévoient les listes rouges, pour le moment simplement les listes rouges nationales sont disponibles, il faut que j'approfondisse sur les listes rouge régionales et la manière de les implémenter proprement pour qu'elles puissent être prises en compte dans ce filtre (déjà abordé sur taxhub).  

- Pas de filtre sur les espèces protégées actuellement. Demandé par certains, notamment dans le cadre d'études réglementaires. 

- Pas encore de possibilité d'importer un shapefile qui définisse la zone de recherche des données, demandé par quelques utilisateurs également. Camille me disait que c'etait envisagé à termes.

- Pas encore d'affichage différencié des données sensibles en fonction de l'utilisateur, à voir par la suite

- Affichage de 10.000 données très long, et difficile d'aller au dessus. Réfléchir à la pertinence d'en afficher plus, et éventuellement chercher les solutions pour en afficher plus si jugé nécessaire

- La liste déroulante des communes s'arrête au bout de X communes. Surprenant pour certains utilisateurs. De plus, si je saisi la commune 'toto' et que je supprime les filtres, la liste reste sur 'toto' jusqu'à ce que 3 nouvelles lettres soient cherchées dans la barre de recherche. D'ailleurs, il existe quelques communes dont le nom ne fait que 2 lettres, on ne peut pas les chercher du coup, comme Eu. 
Demandé aussi, la possibilité de filtrer par département en plus des communes. Pour le coup sous forme de paramètre puisque peu de structures travaillent sur beaucoup de départements. 

Une prestation pour certaines évolutions de la synthèse (notamment sur les données sensibles) pourra être prévue par le pôle en 2019, à voir ce qu'il est pertinent d'y inclure et comment le prioriser selon les couts.

**Comment by camillemonchicourt** [comment]
Merci pour ces retours.

> Demande de pouvoir filtrer par organisme (déjà abordé dans le #512)

Oui

> Le filtre des taxons sur "Règne" et "Groupe" n'est pas bien compris par une partie des utilisateurs (j'en suis!). J'ai pensé qu'il servait à filtrer "tous les animaux", ou "tous les animaux du groupe Oiseaux" dans la recherche.. En fait non, il filtre simplement les noms dans l'autocomplétion à la saisie.

En fait ces filtres avait beaucoup d'intérêt dans la V1 quand la liste déroulante affichait tous les taxons mais en a moins désormais que le champs fonctionne en auto-complétion. A voir pour le clarifier ou le supprimer.

> Les filtres prévoient les listes rouges, pour le moment simplement les listes rouges nationales sont disponibles, il faut que j'approfondisse sur les listes rouge régionales et la manière de les implémenter proprement pour qu'elles puissent être prises en compte dans ce filtre (déjà abordé sur TaxHub).

Oui sujet qui reste encore à creuser : https://github.com/PnX-SI/TaxHub/issues/157

> Pas de filtre sur les espèces protégées actuellement. Demandé par certains, notamment dans le cadre d'études réglementaires.

A voir aussi si on peut récupérer cette info dans Taxref, pas sur. A creuser aussi sur https://github.com/PnX-SI/TaxHub/issues/157

> Pas encore de possibilité d'importer un shapefile qui définisse la zone de recherche des données, demandé par quelques utilisateurs également. Camille me disait que c’était envisagé à termes.

Oui c'est prévu même si ça sera surement plutôt du GeoJSON. Ça sera peut-être possible de le traiter avec https://github.com/PnX-SI/GeoNature/issues/256

> Pas encore d'affichage différencié des données sensibles en fonction de l'utilisateur, à voir par la suite.

Oui la réintégration du CRUVED dans GeoNature (https://github.com/PnX-SI/GeoNature/issues/517) est une avancée pour permettre de faire ça. Mais il reste à l'implémenter ces droits au niveau de l'application et à finaliser le calcul de la sensibilité (https://github.com/PnX-SI/GeoNature/issues/284).

> Affichage de 10.000 données très long, et difficile d'aller au dessus. Réfléchir à la pertinence d'en afficher plus, et éventuellement chercher les solutions pour en afficher plus si jugé nécessaire.

La valeur limite de 10.000 est un paramètre que chacun peut ajuster. Pour les performances des choses ont été faites, mais il y a une réflexion à pousser du côté de la pagination (https://github.com/PnX-SI/GeoNature/issues/357) et de le clusterisation.

> La liste déroulante des communes s'arrête au bout de X communes. Surprenant pour certains utilisateurs. De plus, si je saisi la commune 'toto' et que je supprime les filtres, la liste reste sur 'toto' jusqu'à ce que 3 nouvelles lettres soient cherchées dans la barre de recherche. D'ailleurs, il existe quelques communes dont le nom ne fait que 2 lettres, on ne peut pas les chercher du coup, comme Eu.

OK à investiguer si il y a un bugs ou à améliorer.

> Demandé aussi, la possibilité de filtrer par département en plus des communes. Pour le coup sous forme de paramètre puisque peu de structures travaillent sur beaucoup de départements.

C'est déjà possible puisque tu peux paramétrer les TYPES AREAS qui sont proposés comme filtres.

**Comment by sig-pnrnm** [comment]
> > Pas encore de possibilité d'importer un shapefile qui définisse la zone de recherche des données, demandé par quelques utilisateurs également. Camille me disait que c’était envisagé à termes.
> 
> Oui c'est prévu même si ça sera surement plutôt du GeoJSON. Ça sera peut-être possible de le traiter avec #256

Sur ce point, je rajoute une demande qui m'a été faite : rechercher par périmètre déjà présent en base (ZNIEFF, Site Natura 2000, Réserve, ...). Cela éviterait d'avoir à importer une géométrie (SHP, GeoJson, ...).

**Comment by sig-pnrnm** [comment]
> C'est déjà possible puisque tu peux paramétrer les TYPES AREAS qui sont proposés comme filtres.

Pardon, je n'avais pas encore lu cette réponse qui solutionne ma proposition !

**Comment by camillemonchicourt** [comment]
Pour le GeoJSON on peut gérer ça assez simplement car c'est un fichier qui peut être chargé et affiché uniquement coté client (navigateur). C'est simple de le générer avec QGIS depuis un SHP ou autre.
Pour le SHP c'est une autre affaire. Il y a plusieurs fichiers, il faut que l'utilisateur les zippe, charge le ZIP, qu'il soit envoyé au serveur, que le serveur le dézippe, vérifie qu'il a bien les fichiers et qu'il renvoie un geojson au client (navigateur) et il faut aussi gérer les projections. 
Donc rien à voir en terme de complexité. En plus on peut surement gérer le chargement du ZIP avec le plugin Leaflet.Filelayer qui a été développé pour Geotrek - https://github.com/PnX-SI/GeoNature/issues/256
Donc on va surement commencer par le GeoJSON et pour le SHP on verra ce qui est possible.

Concernant les données, la BDD aura aucun problème a renvoyé 120.000 données ou même bien plus. Mais c'est le navigateur de l'utilisateur qui va tomber. D'abord car ce sera long à télécharger mais ensuite et surtout car ça va lui demander beaucoup de ressources en RAM de gérer, manipuler et afficher 120.000 objets vectoriels au niveau du navigateur. 
C'est pour ça qu'on a déjà limité le GeoJSON aux infos minimales affichés dans la liste et que les infos de détails sont téléchargés à la demande en Ajax quand on affiche le détail d'une observation. 
Pour limiter le poids et les ressources mobilisées côté client, il y a plusieurs pistes : 
- Paginer côté serveur mais c'est peu satisfaisant car on affiche sur la carte que les observations de la page en cours (https://github.com/PnX-SI/GeoNature/issues/357)
- N'afficher les lignes et polygones qu'à partir d'un certain niveau de zoom (mais ça demande de relancer des requêtes au serveur à partir d'un certain zoom et de télécharger le résultat, ce qui réduirait fortement la fluidité de navigation dans la carte)
- Mettre en place un mécanisme avancé de clusterisation (https://makina-corpus.com/blog/metier/2018/clustering-pour-lanalyse-de-la-biodiversite), solution complexe mais certainement la plus intéressante

**Comment by lpofredc** [comment]
Pour les statuts, liste rouge et protection, j'ai prévu de me pencher sur le sujet cet hiver. Pour un côté fonctionnel et relationnel, je pensais mettre en place une relation (fk) entre le statut et son zonage dans la table l_areas (en ce cas casse-t-on l'indépendance de taxhub...). 

J'ai vu que dans les tables `taxref_liste_rouge_fr` et `taxref_protection_xxx` issues des données INPN étaient d'ores  et déjà intégrées.

Il faudrait sans doute réfléchir sur cette implémentation de manière à disposer d'une structure générique pouvant prendre différents statuts à différentes échelles (en tout cas pour les listes rouges puisque c'est déjà intégré pour les protections réglementaires) mais aussi d'autres statuts tel les listes déterminantes znieffs, tvb). Nous avons déjà avancé sur cette question dans la LPO AuRA (plus d'infos bientôt :).

**Comment by DonovanMaillard** [comment]
Merci Frédéric, en effet le rattachement des textes à leur territoire est déjà abordé (#157 du dépot taxhub). 

Coté imports des données, nous préparons un module d'import générique directement dans GeoNature, il y a peut être des choses qui peuvent être repris pour vos imports depuis visionature dans le cadre du stage que tu viens de diffuser, à voir.

Merci pour ces infos,

**Comment by camillemonchicourt** [comment]
Oui sujet à creuser côté TaxHub (https://github.com/PnX-SI/GeoNature/pull/157). 
Dans l'API taxref, on un CDSIG associé à chaque réglementation. On voulait utiliser pour automatiser le rattachement des réglementations à des territoires. Pour ne renvoyer dans GN que les réglementations relatives au territoire concerné par l'instance ou la localisation de la donnée.

**Comment by DonovanMaillard** [comment]
Pour l'ajout de filtres sur le référentiel géographique, j'ai testé avec les coeurs des parcs nationaux. 

La couche est bien chargée, et bien calée dans le référentiel (elle est au bon endroit quand je la lis avec QGis). J'ai pu ajouter le filtre "Parcs nationaux" sans soucis à l'interface et le menu déroulant est adapté. En revanche, l'intersection n'est pas fonctionnelle. La requête me donne systématiquement 0 donnéesmalgré que j'ai bien des données dans cette zone, et que l'intersection avec les communes fonctionne. 
Reste à voir, comme toujours, si ça vient de geonature, ou de l'utilisateur ;)

**Comment by TheoLechemia** [comment]
Pour la question du statut de protection. Jusqu'à maintenant, on avait un champ boolean ``concerne_mon_territoire`` dans la table ``taxonomie.taxref_protection_articles``. A voir si celà suffit en le couplant, comme le disait Camille, à une d'intérogation de l'API Taxref pour maintenir ce champ à jour.
L'idée  de @lpofredc,  d'une corespondance entre l_area et statut_protection est plus interessante et plus générique, mais a l'inconvénient de faire dépendre le Taxhub du ``ref_geo``. C'était un peu une limite qu'on s'était fixé, de ne pas faire dépendre les référentiels entre eux. A voir.

Pour le bug des communes et de filtre géo, je regarde Donovan.

**Comment by gildeluermoz** [comment]
Le champ concernant la protection pour le territoire a été déplacé ici `taxonomie.taxref_protection_articles_structure`  pour ne pas modifier la table diffusée par l'INPN. 
La dépendance du schéma `taxonomie` au `ref_geo` n'est pas une bonne idée. Comme le fait remarquer Théo, si cette correspondance doit être faite, il faut en évaluer et en assumer toutes les conséquences, notamment sur la modularité et la complexification de la maintenance des scripts d'installation de la base.
Une alternative est de considérer ces liens comme propre à GéoNature et à les installer dans un schéma gn_...

**Comment by DonovanMaillard** [comment]
Nouveau retour sur les exports de la synthèse. Je ne sais pas si ca a été testé ou pas, @TheoLechemia  m'avait dit que ce n'était pas encore tout à fait fini la dernière fois qu'on en avait parlé. 
Mais si j'ajoute des champs à ma vue "v_synthese_for_export" (les informations remontent bien dans la vue) avec AS ma_colonne, et que j'ajoute ces colonnes dans "Export column" sur le fichier synthese_config.py, l'export n'est pas pleinement fonctionnel. Les nouveaux champs apparaissent (dans un ordre visiblement aléatoire?), mais les informations correspondantes ne sont pas renseignées, les champs restent vides. Quelqu'un d'autre aurait testé pour voir si ca vient de moi? :)

**Comment by TheoLechemia** [comment]
Après discussion avec Camille, la possibilité de modifier sa vue ``v_synthese_for_export`` apparait dangereuse. La vue nécessite d'avoir des champs obligatoires si on veux que les filtres de l'interface fonctionnent (tous les champs de nomenclatures, le champs id_dataset pour la jointure avec la table dataset, les champs date_max, date_min etc...).
L'ajout d'un champ X-Y dans l'export peut aussi être trompeur lorsqu'on a des lignes ou polygones...
Pour l'ajout des organisme c'est prévu.

A noté que le mécanisme actuel permet de masquer et de modifier le nom des champs disponibles dans l'export en éditant le fichier ``geonature_config.toml``, section ``[SYNTHESE.EXPORT_COLUMNS]``

**Comment by DonovanMaillard** [comment]
J'arrive un peu après la guerre, mais la date d'update serait bien utile aussi dans l'export. Si on a deux données avec un meme uuid qui arrivent de 2 endroits, on garde la plus récente.... si on a l'info ;)

**Comment by TheoLechemia** [comment]
En attendant d'avancer sur la question des statuts de protection, il est déjà possible de filtrer par ces statuts dans la synthèse via les attributs Taxhub.
Pour cela, ajouter d'abord un attribut "protection" en base dans la table "taxonomie.bib_attributs" avec comme valeur possible "oui/non". Puis peupler la table "cor_taxon_attribut" en conséquence. 
Editer ensuite le fichier `geonature_config.toml`` pour ajouter l'ID de ce filtre:

```
[SYNTHESE]
    # id_attribut taxhub pour l'affichage dans la modale du détail d'une observation et dans les filtres taxonomique avancés
    ID_ATTRIBUT_TAXHUB = [101,102,103]
```

Le filtre s'affiche alors dans le formulaire de recherche
![taxhub](https://user-images.githubusercontent.com/15265745/52213717-2e60ac80-2890-11e9-9ce3-ef8572a3083d.png)

**Comment by camillemonchicourt** [comment]
Fait pour la plupart. 
Pour les détails, faire des tickets dédiés.
