### ISSUE TITLE
REF_GEO : Articulation li_grids & l_areas

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#534]
Bonjour, 

Petite question car je n'ai pas trouvé de doc sur ce point. 

Quand on intègre une grille (1x1km de l'inpn par exemple : pas implémentée à l'install, je ne sais pas si c'est normal d'ailleurs?), comment cela s'articule dans le référentiel geo? Est-ce qu'on intègre la grille dans l_areas, ou l_areas+li_grids? A priori je ne peux pas l'intégrer à li_grids uniquement car il y a une fk depuis la table l_areas. 

Merci à vous!

**Comment by xavyeah39** [comment]
Salut,

Je me suis posé la même question sur le fait que les mailles inpn ne soient pas insérées lors de l'install. 
Pour ce qui est de l'utilité de peupler li_grids, j'imagine que cela permet de stocker des attributs non-génériques et autres que ceux de l_areas (ici propres aux communes (li_municipalities) ou aux mailles (li_grids)). Peut-être aussi pour des questions de perf. sur certaine requêtes ?

Même si il me semble que les mailles (et donc li_grids) ne sont pas encore utilisées dans la version actuelle de GN et ses modules (peut-être Suivi-Flore ?), je les ai intégrées dans l_areas + li_grids dans cet ordre pour respecter la FK (exemple avec les mailles 5*5 où il m'a fallu ajouter le type dans bib_areas_types car absent. j'ai aussi ajouté un filtre spatial sur la région AuRA dont la geom se trouve dans une table temporaire : tmp_region_aura) :

```
INSERT INTO ref_geo.bib_areas_types(
	type_name, type_code, type_desc)
	VALUES ('Mailles5*5', 'M5', 'Type maille INPN 5*5km');

INSERT INTO ref_geo.l_areas(
	id_type, area_name, area_code, geom, centroid, source, enable, meta_create_date)
(	SELECT
	32::integer as id_type,
	code5km::text,
	cd_sig::text,
	t1.geom::geometry(MULTIPOLYGON,2154) as geom,
	st_centroid(st_makevalid(t1.geom))::geometry(POINT,2154) as centroid,
	'https://inpn.mnhn.fr/docs/Shape/L93_5K.zip' as source,
	true::boolean as enable,
	now():: timestamp without time zone as meta_create_date
   FROM _imports_ref_geo.l93_5k AS t1
   JOIN  _imports_ref_geo.tmp_region_aura t2 ON st_intersects(t1.geom,t2.geom) --> ### Filtre spatial sur AuRA ###
   ORDER BY code5km);

INSERT INTO ref_geo.li_grids(
	id_grid, id_area, cxmin, cxmax, cymin, cymax)
(	SELECT 
	area_code::text,
	id_area::integer,
	st_xmin(geom)::integer,
	st_xmax(geom)::integer,
	st_ymin(geom)::integer,
	st_ymax(geom)::integer
	FROM ref_geo.l_areas
	WHERE source ILIKE '%L93_5K.zip');`
```
++

**Comment by camillemonchicourt** [comment]
En effet pour le moment, on n'intègre pas les mailles INPN dans GeoNature, car elles ne sont pas utilisées et car on n'a pas encore mis en place de mécanisme avancé pour les limiter à son territoire. 
Nous intégrons pour le moment (en option) toutes les communes de métropole et le sujet de les limiter au territoire est à mettre en place : https://github.com/PnX-SI/GeoNature/issues/49

En attendant, ceux qui le souhaitent peuvent les ajouter comme @xavyeah39 l'explique dans la table ``l_areas`` avec ses éventuels compléments dans ``li_grids``.
Le préfixe ``l`` signifie "layer" et ``li`` signifie "layer_information". Ainsi comme pour les communes, on stocke la géométrie; le nom et le type dans la table commune et générique ``l_areas`` et les infos complémentaires spécifiques aux communes dans ``li_municipalities``. Voir https://github.com/PnX-SI/GeoNature/issues/245

Pour les grilles on a le même mécanisme avec la possibilité (optionnelle) de compléter la table spécifique aux mailles ``li_grids`` après avoir inséré les mailles dans ``l_areas``.

**Comment by camillemonchicourt** [comment]
Attention c'est jamais à jour...
Il y a encore des communes qui ont fusionné au 1er janvier 2019 : https://fr.m.wikipedia.org/wiki/Liste_des_communes_nouvelles_cr%C3%A9%C3%A9es_en_2019
De mémoire je crois que les communes qu'on intègre datent de 2017.
Et ça c'est la galère car il faudrait les fusionner et ensuite relancer les calculs d'intersection avec les données dans la Synthèse notamment car (de mémoire) les triggers se declenchent quand on insere ou modifie une donnée dans la Synthèse mais pas à l'inverse quand une area est modifiée.

**Comment by DonovanMaillard** [comment]
Oui en effet. Dans notre cas on a pas la couche gratuite fournie, mais la couche de la DREAL, topo 2017 pour la région uniquement. et j'ai utilisé ça pour découper mes mailles 1km sur qgis et définir mon territoire régional. Me reste le MNT 25m à intégrer, une fois que je m'en serai sorti avec les fdw de l'atlas ;)
