### ISSUE TITLE
Comment optimiser la suppression un lot de données de la table synthese ?

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#535]
Bonjour, 

J'ai un jeu de données mal importé dans la synthèse. 
Je veux le supprimer mais la requête est trèèèèèèès lente (en fait elle abouti pas pour l'instant : + 7h).
Est-ce qu'il y a une façon d'optimiser ce genre d'opération ?

voici ma requete : 
`DELETE FROM gn_synthese.synthese WHERE  id_dataset = X`

Elle concerne  300 000 obs.

merci

**Comment by camillemonchicourt** [comment]
Je ne vois pas de raison à ça. Ça devrait être bien plus rapide.
Peut-être essaie juste de redémarrer PostgreSQL et de la relancer ?

**Comment by DonovanMaillard** [comment]
Pas un soucis avec la correspondance area synthese? Une simple idée, j'ai pas eu le soucis perso...

**Comment by TheoLechemia** [comment]
Est-ce que tu as fais la manip avec PgAdmin ? Parfois, et je ne sais pas pourquoi, PgAdmin met un temps extremement long pour traiter des requêtes. Tu peux essayer de le faire en ligne de commande avec "psql", c'est généralement beaucoup plus rapide.
Si tu as redémarré PostgreSQL, n'oublie pas de relancer GeoNature ensuite (`sudo supervisorctl restart geonature2`)

**Comment by RomainBaghi** [comment]
Je l'ai fait depuis un script python sur le serveur. Le weekend est passé et la requête s'est terminée donc on verra la prochaine fois (s'il y a). Merci pour vos suggestions.

**Comment by gildeluermoz** [comment]
Le soucis vient probablement des triggers.
Il y a 3 triggers sur la table dont 1 sur DELETE : `gn_synthese.fct_trg_refresh_taxons_forautocomplete()`
Pour mémoire, la synthèse est une partie de la base un peu spéciale et conçue avec pas mal d'automatisation permettant de maintenir une cohérence. D'où les triggers. Lorsqu'il y a des opérations d'admin à faire sur la synthèse, **il faut bien comprendre les liens existants pour ne pas créer des incohérences**. 
Si les opérations concernent de gros lots de données, il est préférable de désactiver les triggers qui sont joués chaque fois pour chacun des enregistrements (300 000 fois dans ton cas)
Mais il faut ensuite jouer les requêtes des triggers manuellement pour tout le lot de données. Puis réactiver le trigger. C'est généralement beaucoup, beaucoup plus rapide.

Donovan avait bien pisté le soucis en pointant le lien avec `cor_area_synthese`. Il y a un trigger qui fait le job sauf que ce trigger n'est pas concerné par `DELETE`. Ce qui n'est pas normal. A creuser.

A noter que le futur module d'import va se heurter à ce soucis des triggers qui vont plomber les perfs d'import.

**Comment by gildeluermoz** [comment]
> Donovan avait bien pisté le soucis en pointant le lien avec cor_area_synthese. Il y a un trigger qui fait le job sauf que ce trigger n'est pas concerné par DELETE. Ce qui n'est pas normal. A creuser.

En fait il y a un `DELETE CASCADE` sur `id_synthese` dans `cor_area_synthese`. C'est lui qui fait le job, ce qui est cohérent.

**Comment by RomainBaghi** [comment]
Le fait de désactiver les triggers rend la requête super rapide ! Merci pour le conseil !
