### ISSUE TITLE
Pas de contrainte sur l'UUID dans la synthese ?

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#536]
Je me demande pourquoi il n'y a pas de contrainte pour empêcher d'avoir deux fois le même uuid dans la table synthese. C'est voulu ? 
Si j'en rajoute un (parce que ça m'arrange), je risque de me heurter à des pb ?

**Comment by camillemonchicourt** [comment]
Car les UUID sont uniques de part la manière dont ils sont générés

**Comment by RomainBaghi** [comment]
Dans mon cas j'importe des données depuis plusieurs sources/bases et il arrive que la même donnée soit présente dans plusieurs bases. En l'état, je rien ne m'empêche d'importer deux fois la même donnée. 
C'est pour éviter ce genre de pb que je me renseigne :)

**Comment by camillemonchicourt** [comment]
OK intéressant. En effet si tes UUID ont été générés en amont (ce qui est idéal), ça permettrait de vérifier les doublons.
