### ISSUE TITLE
Erreur à la compilation du frontend sur la v2.0.0rc4

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature#538]
Les paquests ng-idle/core et ng-idle/keepalive ont été retirés de package.json mais la librairie est toujours appelée dans `frontend/src/app/app.module.ts`.

**Comment by camillemonchicourt** [comment]
Du coup ça a planté la compilation du frontend ?
Bizarre car on a testé de nombreuses installations et mises à jour de la 2.0.0-rc.4.

**Comment by camillemonchicourt** [comment]
OK à creuser car on n'a pas rencontré ces problèmes lors de nos tests.

Tu es sur quel OS ?

Merci.

**Comment by camillemonchicourt** [comment]
OK problème identifié et corrigé dans la branche ``develop`` : https://github.com/PnX-SI/GeoNature/commit/4c894fe910c9602c8157f4ac5ac1313abb1e401e

Donc pour le moment, soit utiliser cette branche soit attendre la version corrective de la RC4 qu'on sortira vendredi.

**Comment by camillemonchicourt** [comment]
On n'a pas reproduit le problème, mais on a corrigé les paquets dans la RC4.1
