### ISSUE TITLE
gestion des dates dans la synthèse

### ISSUE THREAD

**Issue by ybuthion** [PnX-SI/GeoNature#540]
- filtre par date dans le calendrier de la synthèse :
on ne peut pas faire de recherche avant 2009   
- tri par date dans la synthèse : 
le tri se fait sur jour/mois/année et non sur année/mois/jour

ps : c'est mon premier post, alors, dîtes moi je dois faire autrement ...
merci

**Comment by camillemonchicourt** [comment]
C'est impeccable, merci pour ces retours.
