### ISSUE TITLE
Autocomplete recherche taxons - afficher l'information du rang

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoNature#549]
Retour d'utilisation :
Pour la recherche par autocomplétion de certaines espèces (et pour éviter de possibles confusions), il pourrait être intéressant d'avoir l'information du rang pour les taxons proposés. Pour illustrer : 
![taxon_autocomplete](https://user-images.githubusercontent.com/16793813/51612532-eea9d480-1f21-11e9-8610-ffea9087912a.jpg)

**Comment by camillemonchicourt** [comment]
Oui

**Comment by camillemonchicourt** [comment]
Pour Occtax c'est à faire côté TaxHub ?

**Comment by TheoLechemia** [comment]
Oui, c'est fait.
