### ISSUE TITLE
Métadonnées - Module à part entière

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#550]
Le module de gestion des CA et JDD a été intégré dans le module Admin. 
Cependant, il a une dimension métier forte et peut avoir un intérêt, au moins en lecture pour les agents. 

Il est donc préférable d'en faire un module à part entière, sans nécessairement passer par l'Admin, dédiée aux administrateurs. 

Travail initié : https://github.com/PnX-SI/GeoNature/commit/e1acf7a0ba532f8c18b5dec7cc44187d658d75a9

**Comment by DonovanMaillard** [comment]
Alors je viens faire le pénible en complement.

Il est probable que par la suite les utilisateurs sinp comme nous aient besoin que ces données soient publiques, donc accessibles sans identofication. Je n'ai pas approfondi le truc mais pour info et discussion éventuelle si besoin dans le cadre de ces ajustements.

**Comment by camillemonchicourt** [comment]
Oui ça le rend plus possible mais c'est une question plus large.

Actuellement GeoNature n'est pas fait pour être consultable sans connexion. 

Ça peut être une piste pour plus tard. 
Sinon il peut être envisagé d'utiliser des données de GeoNature pour les afficher dans un autre site ouvert.

**Comment by DonovanMaillard** [comment]
En effet j'avais 2 pistes en tête, avoir une page dédiée à ça dans l'atlas mais à mon sens, c'est 0as des données grand public.

Ou avoir, sur la page de login, un bouton "consulter les méta-données" qu'on active ou non. Si on l'active ça "connecte" la personne avec un compte générique pour la lecture, et où l'export des méta-données selon comment on configuré le compte en question par exemple. A voir pour une 3eme piste que vous jugeriez plus propre

**Comment by camillemonchicourt** [comment]
- Avoir une page sur l'atlas = Relativement simple et pertinent
- Se connecter avec un compte générique avec GeoNature = Pas une bonne piste je pense. Si on veut cela, il vaudrait mieux prévoir une partie de GeoNature consultable sans être connecté. Un peu comme on a dans TaxHub
- Tu peux aussi imaginer accéder à l'API de GeoNature depuis ton site web et afficher le contenu des métadonnées publiquement sur ton site web

**Comment by DonovanMaillard** [comment]
Je creuserai cette 3eme piste et ce que ça implique pour mettre ça en place, en effet :) la 2eme piste peut être bien aussi mais à rendre paramétrable (dans le cas d'une réserve ou d'une asso ça a pas forcément vocation à être consultable en ligne quand l'étude est pas terminée/publiée.

Pour l'atlas ça reste un public différent à mon sens. C'est dommage de passer par l'atlas pour avoir les méta-données et passer par GN pour accéder aux données... A voir.

**Comment by TheoLechemia** [comment]
Discussion a continuer dans un autre ticket.
Le module a été déplacé
