### ISSUE TITLE
Module Admin - Problème de CRUVED

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoNature#551]
Suite à [#517](https://github.com/PnX-SI/GeoNature/issues/517) et [#496](https://github.com/PnX-SI/GeoNature/issues/496) dans lesquels je n'ai pas trouvé de solution, j'ai un soucis pour le module d'admin auquel je souhaiterais donner l'accès seulement en lecture à toutes les données pour les volets "Nomenclatures" et "Métadonnées" à un groupe de "référents biodiv".

En ajoutant le CRUVED suivant (capture d'écran ci-dessous) sur le groupe en question, le lien vers l'Admin est bien visible dans la side-bar mais rien ne s'affiche dans ce dernier.  

*Note :* les CRUVED pour SYNTHESE et GEONATURE sont les même que celui d'OCCTAX.

Merci d'avance !

![capture d ecran 2019-01-24 a 11 15 01](https://user-images.githubusercontent.com/16793813/51671647-aa720f00-1fc9-11e9-9a86-7d047fbf57bc.png)

**Comment by TheoLechemia** [comment]
Bien vu ;)

Malheureusement c'est volontaire.
Pour le module nomenclature, c'est une appli auto-généré par Flask dans lequel on ne gère pas le CRUVED. On y a accès ou pas, pas de question de lecture/edition/validation etc... Et quand on y a accès on peut TOUT faire. Donc seule la portée 'C' est checké à l'entrée du module d'admin. Un utilisateur doit avoir un C > 0 pour y avoir accès.
Pour le module métadonnées tel qu'il est aujourd'hui, c'est le même problème. Il y a pas pour l'instant la possibilité de donner accès en lecture seule au module (on a pas fais de fiche JDD ou CA pour l'instant). Quand on a accès au module, on peut tout faire, donc il faut un C > 0. C'est cependant prévu dans la V2 d'en faire un module à part pour permettre de gérer plus finement les droits.

Je concède que d'avoir les différentes actions disponible (C-R-U-V-E-D) sur des modules ou cela ne s'applique pas est paumatoire, mais on a pensé le truc générique, donc ça s'applique à tous les modules. Un boulot est donc à faire dans la doc pour préciser quelle actions sont possibles pour chaque module. Une doc par module ? Ou une doc générale sur les permissions ?

**Comment by xavyeah39** [comment]
Ok merci Théo, je comprend mieux le comportement des différents essais que j'ai pu faire.
Bien noté toutes ces nuances.
Pour la doc en ce qui me concerne, j'opterai plutôt pour une doc générale sur la gestion des permissions histoire de centraliser.
++
