### ISSUE TITLE
Conflit de CRUVED

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#552]
Une route peut-être utilisé dans différents contextes, ce qui peux entraîner des conflits de CRUVED.
Par exemple la route qui renvoie les JDD est définit comme ça: 

```
@permissions.check_cruved_scope('R', True)
@json_resp
def get_datasets(info_role):)
```

On ne passe pas de ``module_code`` dans le décorateur qui protège la route et qui renvoie le CRUVED. Quand on utilise la route dans Occtax, on aura donc tous les JDD de l'utilisateur connecté, selon le CRUVED de GeoNature. Si on surcouche le CRUVED d'Occtax, c'est toujours le CRUVED de GeoNature qui est pris en compte pour ce genre de routes utilisé dans pleins de module.
C'est encore plus trompeur dans le module METADATA.

Que faire sur ce genre de cas ? Réécrire la route dans chacun des modules (en sachant qu'on a déjà un repository qui renvoie les JDD, CA, donc il n'y a pas grand chose à réécrire). Ou alors être en mesure de connaître le module depuis lequel la route a été appelé (via le token par exemple) ? Beaucoup plus complexe

**Comment by gildeluermoz** [comment]
Éternel dilemme entre factorisation qui créer de la complexité et duplication qui crée des soucis de maintenance...
Sans vraiment connaître la complexité, je dirais qu'il faudrait un id_module passé en paramètre pour les appels de routes génériques depuis un module.
Côté route, tu as un id_module facultatif avec une valeur par défaut = "core" ou "geonature".
Ça oblige à réécrire au moins les routes génériques pour lesquelles c'est pertinent et comme il y a la valeur par défaut tu ajoutes le paramètre uniquement dans les appels depuis les modules où c'est nécessaire.
Ça le ferait ?

**Comment by TheoLechemia** [comment]
Oui, c'est une idée. Le truc c'est que le décorateur ``@permissions.check_cruved_scope('R', True)`` qui renvoie le CRUVED pour GeoNature ou un module, est exécuté avant l’exécution de la fonction de la route. Si on passe en paramètre GET le code du module, il faut enlevé le décorateur, et donc réécrire la logique à l'interieur de la fonction. C'est faisable.
