### ISSUE TITLE
occtax : obligé de saisir le dénombrement 2 fois ( min / max) ?

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#554]
Quand je saisi un taxon et que je mets un _effectif min_  je dois aussi saisir le même effectif dans la case _effectif max_ . C'est fastidieux...
Est-ce qu'il serait possible de faire ajuster l'effectif max à l'effectif min dynamiquement, en laissant bien sur la main ensuite pour modifier l'effectif max dans un second temps.
Je ne sais pas si je suis très clair...

**Comment by TheoLechemia** [comment]
C'est censé être le cas. A corriger si non

**Comment by RomainBaghi** [comment]
J'ai retenté et effectivement ça marche. J'ai du toucher à l’effectif max en premier.
dsl
