### ISSUE TITLE
synthèse, recherche par communes : comment faire avec les communes de même nom dans des départements différents ?

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#555]
Tout est dans le titre :)
Est-ce qu'il serait possible d'ajouter le numéro de département entre parenthèse après le nom de la commune exemple : Toulouse (31) ?
Questions qui en découle :
Avez vous prévu une recherche par départements ? 
(Et oui y'en a qui déploient des géonature sur la france entière;)

**Comment by TheoLechemia** [comment]
Ok pour ta 1ere proposition.

Rechercher par département est possible. Dans la config (https://github.com/PnX-SI/GeoNature/blob/master/config/default_config.toml.example#L83) tu peux ajouter d'autres "type aires" que les communes pour les intersections. Cela va t'ajouter un nouveau champ dans la rubrique "Ou". A toi d'ajouter tes départements dans "ref_geo.l_areas" en créant un nouveau type "département" dans "ref_geo.bib_type_area"

**Comment by RomainBaghi** [comment]
Top, je ne savais pas pour la config. merci

**Comment by camillemonchicourt** [comment]
Ouais on devrait ajouter ça dans la doc d'administration de Synthèse si c'est pas déjà fait

**Comment by TheoLechemia** [comment]
Oui déjà fais dans la branche develop: 
https://geonature.readthedocs.io/fr/develop/admin-manual.html#module-synthese
