### ISSUE TITLE
Synthese: ajout plugin leaflet clusterMarker

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#559]
Le plugin leaflet cluster marker a été ajouté en synthese. Il permet d'augmenter largement le nombre de résultat affichable sur la carte (anciennement limité à 10 000 obs). Le paramètre par défaut limite maintenant le nombre d'obs affichable par requête à 50 000. 
Ce mode est désactivable via le paramètre  ``ENABLE_LEAFLET_CLUSTER`` de la synthèse. Dans ce cas ci, il est conseillé de repassé le paramètre ``NB_MAX_OBS_MAP`` à 10000

https://github.com/PnX-SI/GeoNature/commit/bdb2cb75b9769733461dc55e537e75e9eddb3ba5

**Comment by gildeluermoz** [comment]
C'est une belle avancée. Tout ce qui tourne autour des perfs va devenir déterminant sur de grosses instances.
