### ISSUE TITLE
OccTax / accès à la modification d'une observation malgré des droits restreints

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#561]
Bonjour, 

Je ne sais pas si cela a déjà été signalé mais je me suis aperçu qu'un utilisateur qui a le droit de lecture (uniquement) sur d'autres données que les siennes dans occtax peut accéder au formulaire pour les modifier via la petite icone (i) d'info puis en cliquant sur "éditer le relevé", bouton vert en haut à droite.
Il ne peut pas enregistrer les modifications donc ce n'est pas critique mais je ne pense pas que cela soit voulu qu'il puisse accéder à la modification du relevé.

**Comment by TheoLechemia** [comment]
Corrigé, merci !
