### ISSUE TITLE
Groupes créés dans taxhub n'apparaissent pas

### ISSUE THREAD

**Issue by jbdesbas** [PnX-SI/GeoNature#562]
Bonjour,

Bug constaté sur la 2.0.0-rc.4.2 : un groupe créé sur huserhub n’apparaît pas dans la liste des rôles du module Admin.
Le souci est résolu en passant les champs _pn_ et _active_ de NULL à TRUE pour ce rôle dans la table _t_roles_

**Comment by camillemonchicourt** [comment]
Oui le problème était lié au champs ``active`` qui a bien une valeur par défaut dans la BDD mais lors de la création avec le formulaire le champs était basculé à NULL. 

Le problème a été décrit et corrigé au niveau de UsersHub : https://github.com/PnEcrins/UsersHub/issues/71

Et il sera disponible dans la prochaine version de UsersHub.
