### ISSUE TITLE
[Question ] Droits et permissions

### ISSUE THREAD

**Issue by jbdesbas** [PnX-SI/GeoNature#563]
Bonjour à tous,

Je suis en train d'étudier les possibilité de passage à GeoNature pour ma structure. J'avoue avoir quelques difficultés à comprendre le fonctionnement des droits dans GeoNature.

Est-il possible, à ce jour, de gérer des droits différents en fonction d'un groupe taxonomique ou liste d'espèces ? (par ex : un groupe d'utilisateurs autorisés à consulter et valider les données chiro uniquement) Il y'a un bien une possibilité de filtre taxonomique, mais je n'en comprend pas bien l'utilisation.

Merci d'avance,

**Comment by camillemonchicourt** [comment]
En effet. 

Voici un état des lieux : 

- UsersHub permet de créer des utilisateurs, de les associer à des organismes et groupes et d'associer éventuellement des profils par application à des utilisateurs et groupes
- Pour accéder à GeoNature, un utilisateur (ou idéalement un groupe auquel il appartient), doit être associé au profil LECTEUR au niveau de l'application GeoNature. On le fait par défaut pour les groupes fournis par défaut.
- Ensuite les droits applicatifs sont maintenant définis au niveau de GeoNature (CRUVED dans le schéma ``gn_permissions`` depuis https://github.com/PnX-SI/GeoNature/issues/517)
- Là aussi, on a appliqué un CRUVED par défaut aux groupes créés par défaut
- Pour en savoir plus sur la gestion des droits de GeoNature : https://geonature.readthedocs.io/fr/develop/admin-manual.html#gestion-des-droits
- En terme de BDD, on a modélisé les permissions pour pouvoir avoir différents types (portée, précision, territorial, taxonomique...)
- Au niveau applicatif seulement le CRUVED de type portée est implémenté (Mes données, Données de mon organisme, Toutes les données)

**Comment by TheoLechemia** [comment]
Bonjour,

La gestion des permissions de GeoNature est actuellement centré autour du CRUVED. Pour un groupe d'utilisateur ou un utilisateur on affecte des portée (mes données, les de mon organisme, toutes les données) à des actions (Create, Read, Update, Validate, Export, Delete) https://geonature.readthedocs.io/fr/latest/admin-manual.html#gestion-des-droits

Cependant le modèle de données permet théoriquement d'aller plus loin. Nous avons anticiper d'autre type de "permissions", tel que des permissions par groupe taxonmomique ou par niveau de sensibilité, puisque certains module de GeoNature (voir directement le coeur dans le futur) auront des besoins plus fin en terme de gestion des permissions (c'est le cas pour le futur module de validation par exemple). Ces modules pourront s'appuyer sur ces nouveaux type de permissions, mais actuellement rien n'est implémenté côté API pour les utiliser.

Actuellement il est seulement possible de masquer le module chiro a un certain nombre d'utilisateur.

**Comment by camillemonchicourt** [comment]
A noter aussi que l'on peut attribuer des CRUVED au niveau de tout GeoNature et/ou par module.

Mettre un READ à 0 sur un module le masque pour les utilisateurs concernés.

Il est conseillé d'attribuer des permissions à des groupes plutôt qu'à des utilisateurs.

Et la DOC indique qu'il reste à détailler les permissions qui sont implémentées. TODO :-)

**Comment by jbdesbas** [comment]
Merci pour vos réponses et votre réactivité !
J'ai rajouté une petite note à ce sujet sur la doc.

**Comment by camillemonchicourt** [comment]
Merci.
