### ISSUE TITLE
OccTax : comportement de l'affichage de la carte entre deux relevés

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#570]
Quand on valide un relevé, l'affichage de la carte revient à la position par défaut. Il faut rejouer de la molette pour retrouver où on était et saisir un autre relevé.
On peut imaginer un bouton pour réinitialiser l'affichage de la carte au lieu de le faire à chaque fois que l'on valide le relevé.
(Une barre de recherche de la commune manque aussi beaucoup pour positionner la carte rapidement sur la zone voulue et ainsi éviter de chercher sur la carte... )
Vous en pensez quoi ?

**Comment by camillemonchicourt** [comment]
Oui, de mémoire un développement avait été amorcé sur ce sujet (mais non abouti pour des raisons techniques). 
Pour éviter d'ajouter un bouton, le comportement par défaut serait de rester sur la même étendue carto quand on enregistre un relevé (comportement éventuellement désactivable au niveau de la conf).
Et idem pour l'inverse. Quand on est sur la carte générale et qu'on rentre dans le formulaire de création d'un relevé, rester sur la même étendue. 

Pour la localisation par commune, au départ on avait un champs de recherche libre de localisation basé sur Nominatim qui était intéressant pour cela et plus large que les simples communes, qu'il serait bien de réactiver (désactivable ?) : https://github.com/PnX-SI/GeoNature/issues/476
A voir ensuite si il faut lui ajouter un filtre par commune dédié.

**Comment by RomainBaghi** [comment]
Oui, c'est mieux d'éviter le bouton supplémentaire et de choisir ce comportement en conf.
Ce serait super de pouvoir faire une recherche avec Nominatim, pour quelles raisons vous aviez choisi de 
l'enlever ?

**Comment by TheoLechemia** [comment]
Ok pour nominatim et le retour au zoom précédent.

**Comment by RomainBaghi** [comment]
yeah !

**Comment by camillemonchicourt** [comment]
Pour voir le fonctionnement (et pour vos derniers tests avant la sortie de la 2.0.0 très bientôt), vous pouvez jeter un œil sur http://test.ecrins-parcnational.net/geonature (admin / admin).

Attention il s'agit d'un serveur de tests qui est parfois indisponible.
