### ISSUE TITLE
Utilisation d'attributs hybrides à la place des triggers 

### ISSUE THREAD

**Issue by jbdesbas** [PnX-SI/GeoNature#571]
Bonjour,
Une petite curiosité/suggestion, pourquoi ne pas utiliser les [attributs hybrides](https://docs.sqlalchemy.org/en/latest/orm/extensions/hybrid.html?highlight=hybrid) de SQLAlchemy au lieu des [triggers](https://geonature.readthedocs.io/fr/develop/admin-manual.html#triggers-vers-la-synthese) pour récupérer le dernier statuts de validation dans la table _t_validation_ sans dupliquer l'info dans les tables _occtax_ et _synthese_ ?

**Comment by TheoLechemia** [comment]
Bonjour,
Je ne suis pas sûr de bien comprendre l'utilisation des attributs hybrides dans notre cas.
Juste pour rappel des choix:
- Le statut de validation n'est pas présent dans les tables d'occtax (seulement dans la table verticale ``t_validations``)
- On remet à plat le statut de validation dans la synthese pour des questions de performance (eviter de faire un JOIN à chaque fois).

De manière générale on est assez méfiant de trop utiliser l'ORM pour des questions de consistance de la BDD. Cela nous arrive souvent d’insérer directement des données en base, ou de construire des vues à partir des données présentes en base. Avec des mécanismes comme les attributs hybrides (ou autres fonctions super pratiques que proposent les ORM), la logique est déporté du côté du code, ce qui est un problème lorsqu'on veut garder une logique "DB first".

**Comment by jbdesbas** [comment]
OK merci de la précision, j'avais effectivement cru que le statut de validation était repris dans la table occtax. Pour moi l’intérêt des attributs hybrides (et des ORM en général) c'est surtout d'offrir plus de souplesse entre la structure de la BDD et l'application, et de ne devoir modifier que la classe modèle en cas de changement de structure de BDD (et ça évite de tomber dans le piège d'être tenté d'adapter la BDD à l'application.)
L’intérêt que je voyais était bien faire abstraction du fait que le statut de validation se trouve dans une autre table en allant chercher directement le statut le plus récent lors de l'appel de l'attribut hybride "validation" de la table _occtax_ ou _synthèse_. Mais en effet niveau performance, je pense qu'on y perd énormément (à moins que SQLAlchemy utilise un système de cache ?). 

A titre perso, je suis beaucoup moins à l'aise sur la logique coté DB que côté code, mais je comprend mieux maintenant pourquoi les models sont si "épurés" dans le code de GeoNature.
Merci encore pour ces précisions. :smile:
