### ISSUE TITLE
Configuration cartes: ajouter des éléments de repérage (sentiers...)

### ISSUE THREAD

**Issue by AudreyEnGuyane** [PnX-SI/GeoNature#572]
Bien le bonjour!
J'ai vu circuler quelques échanges sur la configuration des cartes et j'aimerai y ajouter mon grain de sel/poivre/sable.
J'ai bien vu la proposition de Camille pour ajouter un "arbre à couches" basé sur la table ref_geo.l_areas (je suis pour!!).
Pour ma part, j'ai besoin d'afficher les sentiers de randonnée (urgent!) car nous avons des secteurs où les seuls repères géographiques sont les sentiers.
Comment les ajouter/intégrer par défaut à mes cartes?
(NB: la question pourrait se reposer pour d'autres éléments comme les principaux sauts des fleuves, etc)

**Comment by camillemonchicourt** [comment]
Bonjour.
Pouvoir afficher des zonages présents dans la table ``ref_geo.l_areas`` est prévu mais à développer.
Pouvoir ajouter d'autres types d'objets n'est pas prévu mais serait intéressant à développer. 
Il pourrait être imaginé de pouvoir lister (dans une table ou un fichier de conf) des geoJSON (distants ou locaux), en leur associant un nom d'objet et un style pour que Leaflet les propose dans un arbre des couches avec les zonages.
A développer.

**Comment by AudreyEnGuyane** [comment]
Je reste donc en stand by... (je cloture ou je le laisse en attente pour que le sujet reste ouvert?)

**Comment by DonovanMaillard** [comment]
Bonjour,

Cest une idée qu'on a déjà évoqué en effet. Pas un besoin pour nous (l'Auvergne Rhône Alpes c'est pas tout à fait la Guyane) mais c'est un confort aussi de pouvoir afficher par exemple les contours de la région. 
Pas une grosse priorité pour nous donc pas de prestation prévue pour le moment sur le sujet mais ça viendra peut être si personne ne l'a fait avant ;)

**Comment by camillemonchicourt** [comment]
C'est une idée d'évolution donc à ne pas fermer pour en garder la trace si quelqu'un veut le développer ou le financer.

**Comment by patkap** [comment]
Par curiosité, @AudreyEnGuyane , sous quel format les données de sentiers sont-elles disponibles ? Merci.

**Comment by AudreyEnGuyane** [comment]
Etant donné que j'ai qGis, postgis et qu'on a un GeoTrek, je dirai que le spectre des formats possibles peut être trèèèès large....
A vrai dire, il peut s'adapter aux développements qui seront faits.

**Comment by camillemonchicourt** [comment]
Je pense que geoJSON serait idéal car ça permettrait d'utiliser des fichiers venant d'un SIG mais aussi de faire afficher des données depuis une API (Geotrek, GeoNature d'un partenaire, autres flux....)

**Comment by camillemonchicourt** [comment]
Fait avec https://github.com/PnX-SI/GeoNature/issues/974
