### ISSUE TITLE
SYNTHESE: requêtage sur une commune

### ISSUE THREAD

**Issue by AudreyEnGuyane** [PnX-SI/GeoNature#573]
Re-bonjour ,

Nous avons injecté nos référentiels géographiques dans l_areas et référencé les communes dans li_municipalities. 
Le formulaire SYNTHESE liste bien les communes. Quand j'en sélectionne une où je sais qu'il y a de la donnée, la sélection est vide. Ces données sont pourtant bien affichées/géoréférencées sur la carto IGN lorsqu'on lance l'api.
Dans quelle projection doivent être les objets de ref_geo? Doit-on utiliser le 4326 ou la projection "locale" définie dans le fichier install_all.ini?
Y aurait-il une autre raison possible pour laquelle je n'aurait aucun résultat?

(désolée si je multiplie les messages: je prend les choses en main sérieusement. Un jour, je serai une bête de concours estampillée "GéoNature For Ever" et c'est moi qui répondrait aux p'tits jeunes...)

**Comment by camillemonchicourt** [comment]
C'est bien de faire un ticket par sujet. 
Mais y a pas d'accent à GeoNature. :-D

**Comment by AudreyEnGuyane** [comment]
> Mais y a pas d'accent à GeoNature. :-D
Mais c'est que ça chipotte sur les moindres détails!! Bon, au moins, je suis mise au pas d'entrée de jeu :-D

**Comment by camillemonchicourt** [comment]
C'est important pour être "GeoNature for Ever" !

**Comment by AudreyEnGuyane** [comment]
Dans le doute, j'ai fait un tour de passe-passe dans la BD:
1. renommer les champs geom et centroid
2. créer 2 nouvelles colonnes geom et centroid 
3. y balancer mes objets géo avec un st_transform(col, 4326). 

Apparemment, ça lui plaît un peu plus car le visuel dans pgAdmin4 me superpose désormais les zonages avec le fond IGN (y'a du mieux dites donc).
Par contre, le choix d'une commune ne me renvoie toujours pas de données...

**Comment by DonovanMaillard** [comment]
Pour ma part ça fonctionne, mais j'utilise bien la projection locale définie dans la conf.

**Comment by AudreyEnGuyane** [comment]
Mince. Dans les 2 cas, ça merdoie, que mes objets géo soient en 4326 ou en projection locale.

> Pour ma part ça fonctionne, mais j'utilise bien la projection locale définie dans la conf.

projection locale pour les objets de l_areas?

**Comment by AudreyEnGuyane** [comment]
Têtue je suis, têtue je reste. J'ai fini par trouver le pourquoi du comment et je vous donne la solutionau cas où quelqu'un serait confronté au même problème.

Sur le formulaire Synthèse, le filtrage par commune se fait en allant chercher tous les id_synthese dans la table cor_area_synthese. Cette dernière enregistre tous les croisements géo entre les données naturalistes et les objets du référentiel géographique. Notez que si vous intégrez vos données avant d'avoir ajouté vos référentiels géographiques, il n'y aura pas d'ajout automatique du couple (id_synthese, id_area).

Pour ma part, seules les données historiques ont été insérées dans GeoNature. Or, le géoréférencement des communes n'était pas le bon lors de cette insertion: mauvaise projection attribuée = données dans les choux = pas de lien géographique commune/donnée naturaliste. 
De fait, aucun lien n'était référencé dans la table gn_synthese.cor_area_synthese.
Par contre, si on avait la possibilité de faire une requête avec un autre objet (une ZNIEFF, etc), j'aurai bien eu des résultats.

Maintenant que j'ai corrigé les objets géographiques de mes communes, je peux corriger le tir "à la main".
Si vous rencontrez le même soucis, ou que vous avez ajouté des zonages géographiques après avoir intégré des données naturalistes, pensez à mettre à jour cette table de liaison avec un petit croisement (allez, un peu de sql pour le sport):
```
insert into cor_area_synthese (id_synthese, id_area)
select id_synthese, id_area
      from gn_synthese.synthese, ref_geo.l_areas
      where ST_intersects(l_areas.geom, synthese.the_geom_local)
      group by id_synthese, id_area
except select id_synthese, id_area from gn_synthese.cor_area_synthese

```

Voilà-voilà.
C'est résolu!

**Comment by camillemonchicourt** [comment]
Oui bien vu.
Comme il y a un trigger sur la table synthèse qui calcule les intersections avec les zonages, on pourrait aussi avoir un trigger inverse qui relance le calcul quand on modifie ou ajoute des zonages.

**Comment by gildeluermoz** [comment]
Attention si la synthèse est chargée, comme se sera le cas sur pls instances un trigger inverse pourrait très fortement plomber les ajouts de geom dans l_area. Genre j'insère le maillage 1km de l'INPN. T'es pas rendu si le trigger se joue pour chaque maille pour plus millions d'obs.

**Comment by camillemonchicourt** [comment]
C sur mais si on ajoute les mailles il faudra bien relancer cette intersection.

Mais en effet il faut surement la relancer manuellement après import des mailles

**Comment by gildeluermoz** [comment]
Oui biensur l'intersection est à faire mais rien de comparable entre une intersection dans une requêtes sql dédiée et un trigger qui se lance n fois, de manière obscure.
L'insertion de geom est un travail d'admin, donc à lui (ou elle) de faire le taf d'intersection. Le trigger est à réserver au maintient de cohérence des données qui viennent des actions réalisées via l'interface.
