### ISSUE TITLE
OccTax: Une erreur s'est produite

### ISSUE THREAD

**Issue by AudreyEnGuyane** [PnX-SI/GeoNature#574]
Bonjour,

j'ai essayé de saisir une obs dans occtax mais, lors de l'enregistrement, la vignette rouge "Une erreur s'est produite" apparaît, sans enregistrer le relevé ni l'observation.
J'ai bien un observateur, une date, un jeu de données et  - dans le doute -  des alti min et max pour le relevé.
Pour la bestiole, apparaît "1 taxon(s) enregistré(s)".

Où pourrais-je trouver plus de détails sur ce bug?
A quoi pourrait être due cette erreur?

**Comment by camillemonchicourt** [comment]
Pour les questions et remontées d'éventuels bugs, pensez à préciser votre version de GeoNature. 
Du coup, quelle version ?

**Comment by AudreyEnGuyane** [comment]
Bah, GeoNature v2, quoi!
(bon, je fais ma blonde. Pour de vrai: 2.0.0-rc.4.2)

**Comment by camillemonchicourt** [comment]
OK précision importante. Merci.

**Comment by camillemonchicourt** [comment]
Je ne maitrise pas bien le sujet, mais c'est possible qu'il trace ça dans les logs d'erreur de GeoNature : https://geonature.readthedocs.io/fr/latest/admin-manual.html#logs

**Comment by AudreyEnGuyane** [comment]
En effet, j'ai un fichier install_occtax_schema.log. Mais c'est le fichier d'installation et non le log de fonctionnement, isn't it? Il semble y avoir eu un problème: 
> psql:tmp/occtax.sql:1142: ERROR:  insert or update on table "cor_role_liste" violates foreign key constraint "fk_cor_role_liste_id_role"
> DÃ‰TAIL : Key (id_role)=(4) is not present in table "t_roles".

(en effet, je n'ai pas de role avec un id_role = 4)
Dans le doute, j'ai également essayé de changer l'observateur mais le message reste le même: "une erreur s'est produite"

**Comment by AudreyEnGuyane** [comment]
J'ai compris pourquoi je ne pouvais pas saisir d'observation: la date de début du cadre d'acquisition était postérieure à ma donnée. Plutôt embêtant mais facilement corrigé. 
Fallait juste y penser et être vigilant lors de la création du cadre d'acquisition (au moins, on voit que les champs saisis ne sont pas que là pour faire joli!)

Au final: 
1/ mon relevé est bien créé.
2/ mon occurence est bien créée: mon motmot est bien référencé dans la table.
3/ mon observation est bien transférée dans la synthèse.
mais 
4/ l'affichage de la donnée sur le mapList me donne un taxon " " (cf. image 1...);
![1_bug_maplist](https://user-images.githubusercontent.com/37804139/53763346-50f2df00-3ea9-11e9-8dc9-da1c60b10b6f.png)
le réaffichage de la donnée dans le form OccTax me liste un taxon " " (cf. image 2...)
![2_bug_releve](https://user-images.githubusercontent.com/37804139/53763358-55b79300-3ea9-11e9-83e8-93cedbccef98.png)
et le réaffichage du taxon pointe vers un taxon "Undefined" (cf. image 3...).
![3_bug_taxon](https://user-images.githubusercontent.com/37804139/53763361-59e3b080-3ea9-11e9-8659-d861f77c4f21.png)

Pourtant mon motmot est bien présent dans la table des occurrences. Un "enregistrer le relevé" me renvoie vers ma belle erreur très parlante "Une erreur s'est produite".

A fouiller, j'ai trouvé d'où vient le problème: mon champ "nom_valide" pour mon motmot est null. ==> de fait, erreur! Le lien entre la zone de liste déroulante et la donnée se fait par le champ "nom_valide"??! Elle n'utilise pas le cd_nom ou l'id_nom??
Si je comprend bien, pour résoudre mon problème, il faut que tous mes taxons de taxref aient un nom_valide. Soit. Je mets le lb_nom du cd_ref correspondant? Que se passe-t-il si on a 2 lb_noms identiques?

**Comment by TheoLechemia** [comment]
Bonjour Audrey.
L'interface carte-liste d'occtax utilise le cd_nom pour retrouver le taxon dans le table taxref. (voir la vue ``pr_occtax.v_releve_list`` sur laquelle elle s’appuie). 
Ton champs "nom_valide" est null dans ta table taxonomie.taxref ? Est ce que ton taxon est celui là: https://inpn.mnhn.fr/espece/cd_nom/442160 ? Si oui tu as un problème dans ta table taxref (il a bien un nom_valide)...
Est-ce que ta table ``pr_occtax.t_occurrences_occtax`` a un cd_nom pour ton occurrence ?
Tu peux aussi regarder les logs (gn_errors.log) ou ouvrir la console de ton navigateur pour avoir des infos plus détaillé sur l'erreur qui s'est produite.

**Comment by camillemonchicourt** [comment]
Il n'y a pas de lien entre la période définie pour un cadre d'acquisition et la date des occurrences. 
Il n'y a pas de contrôle que la date de l'occurrence soit comprise dans la période définie au niveau du cadre d'acquisition, donc l'erreur n'était pas liée à cela.

**Comment by camillemonchicourt** [comment]
Et le fichier ``install_occtax_schema.log`` renvoie des problèmes lors de l'installation du schéma du module Occtax, mais ne trace rien ensuite quand on utilise le module. 
Par contre si tu as eu une erreur lors de l'installation du schéma du moduel Occtax, alors il faut voir pourquoi et corriger ça.

**Comment by AudreyEnGuyane** [comment]
TeoLechemia,

> L'interface carte-liste d'occtax utilise le cd_nom pour retrouver le taxon dans le table taxref. (voir la vue pr_occtax.v_releve_list sur laquelle elle s’appuie).

la vue v_releve_list n'inclue pas de cd_nom! Voici la liste des colonnes: 
`id_releve_occtax, id_dataset, id_digitiser, date_min, date_max, altitude_min, altitude_max, meta_device_entry, comment, geom_4326, "precision", dataset_name, taxons, leaflet_popup, observateurs`
Mais, du coup, ta question m’interpelle! Devrait-il y avoir cette colonne cd_nom??!? Pourquoi n'y serait-elle pas?

> Ton champs "nom_valide" est null dans ta table taxonomie.taxref ? ... tu as un problème dans ta table taxref (il a bien un nom_valide)...

Je pense qu'en effet, un sérieux contrôle s'avère nécessaire. Mais si le lien se fait sur cd_nom, ça ne devrait pas poser de problème.
En tous cas, j'ai rajouté un nom_valide à la main et le problème persiste.

> Est-ce que ta table pr_occtax.t_occurrences_occtax a un` cd_nom `pour ton occurrence ?

oui, c'est bon du côté de t_occurrences_occtax et de t_releves_occtax. C'est le ré-affichage des données qui merdoie.

> Tu peux aussi regarder les logs (gn_errors.log) ou ouvrir la console de ton navigateur pour avoir des infos plus détaillé sur l'erreur qui s'est produite.

Pas de gn_errors.log...
En affichant la console message, je n'ai aucun bug à l'affichage mais j'en ai un si j'essaie d’enregistrer le relevé avec mon taxon " ":
```
Object { headers: {…}, status: 500, statusText: "INTERNAL SERVER ERROR", url: "http://51.77.193.85/geonature/api/occtax/releve", ok: false, name: "HttpErrorResponse", message: "Http failure response for http://51.77.193.85/geonature/api/occtax/releve: 500 INTERNAL SERVER ERROR", error: {…} }
Http failure response for http://51.77.193.85/geonature/api/occtax/releve: 500 INTERNAL SERVER ERROR main.ad53203774c65d98ee29.bundle.js:1:101253
internal server error 1.f8677022f1164b1382bb.chunk.js:1:33641 
```

**Comment by AudreyEnGuyane** [comment]
> Et le fichier `install_occtax_schema.log` renvoie des problèmes lors de l'installation du schéma du module Occtax, mais ne trace rien ensuite quand on utilise le module.
> Par contre si tu as eu une erreur lors de l'installation du schéma du moduel Occtax, alors il faut voir pourquoi et corriger ça.

Voici le fichier log.
Pas très verbeux tout ça...
[install_occtax_schema.log](https://github.com/PnX-SI/GeoNature/files/2930841/install_occtax_schema.log)

**Comment by TheoLechemia** [comment]
> la vue v_releve_list n'inclue pas de cd_nom! Voici la liste des colonnes:

Oui mais la jointure entre t_occurrences_occtax et taxref  est faite le cd_nom...

Le fichier de logs se trouve ici : 
``/home/<MON_USER>/geonature/var/log/gn_errors.log``. Si il n'y est pas c'est qu'il a été supprimé ou qu'il y a eu une erreur lors de la monté de version.

> Voici le fichier log.
> Pas très verbeux tout ça...

Les fichiers de logs SQL permettent simplement de voir si des erreurs sont survenu lors de l'execution de l'installation SQL. En l'occurrence tout s'est bien passé sauf une erreur d'un rôle manquant (l.168)

**Comment by AudreyEnGuyane** [comment]
> Oui mais la jointure entre t_occurrences_occtax et taxref est faite le cd_nom...

Je te listai les colonne de la vue sur laquelle tu m'interrogeai (v_releve_list). J'ai bien compris cette jointure entre occtax et taxref et il y a bien le cd_nom dans t_occurrences_occtax. 
Le problème ne viendrai pas des tables puisque j'ai bien mon cd_nom stocké dans t_occurrences_occtax et même transféré dans synthese. Je le retrouve dans la vue v_releve_occtax.

> Le fichier de logs se trouve ici :
/home/<MON_USER>/geonature/var/log/gn_errors.log. 

C'est bien ce que je dis: il n'y a pas de gn_errors.log.

**Comment by TheoLechemia** [comment]
Si tu as a fais une monté de version: 
https://github.com/PnX-SI/GeoNature/releases
> Afin que les logs de l'application soient tous écrits au même endroit, modifier le fichier geonature-service.conf (sudo nano /etc/supervisor/conf.d/geonature-service.conf). A la ligne stdout_logfile, remplacer la ligne existante par stdout_logfile = /home/<MON_USER>/geonature/var/log/gn_errors.log (en remplaçant <MON_USER> par votre utilisateur linux).
> Exécutez ensuite la commande sudo supervisorctl reread

Si tu as installé la RC4.2:

https://github.com/PnX-SI/GeoNature/blob/2.0.0-rc.4.2/backend/geonature-service.conf

Voir le contenu du fichier  ``/etc/supervisor/conf.d/geonature.conf``

**Comment by AudreyEnGuyane** [comment]
Ha haaa!! En effet, le fichier conf n'avait pas été modifié.
Je dois recompiler l'appli avec un update_configuration pour que ce soit pris en compte?

**Comment by TheoLechemia** [comment]
Non même pas besoin. Là, il s'agit de la conf serveur, pas vraiment GeoNature.
Dans le doute relance aussi un ``sudo supervisorctl restart geonature2``

**Comment by AudreyEnGuyane** [comment]
En fait, la doc sur la release conseille un `sudo supervisorctl reread`.
Cependant, j'ai fait un `restart de geonature2`, un `reread`, j'ai même fermé mon navigateur, réouvert une session, reproduit le bug, rien à faire:
1/ aucun moyen de mettre à jour ma donnée ("_une erreur s'est produite_") (ni maj de la date, ni ajout/suppression d'une espèce, etc)
2/ aucune inscription dans le fichier gn_errors.log (que j'ai créé à la main dans /home/user/geonature/var/log/).

Je viens de voir, dans la console de messages de mon navigateur, que j'ai un message "_Http failure response for http://51.77.193.85/geonature/api/occtax/releve: 500 INTERNAL SERVER ERROR_"
Or, l'url _http://51.77.193.85/geonature/api/occtax/releve_ donne une page "_Method not allowed._"

**Comment by TheoLechemia** [comment]
Le ``reread`` doit être fait avant le `restart`. 

> Or, l'url http://51.77.193.85/geonature/api/occtax/releve donne une page "Method not allowed."

C'est normal car cette route est un POST et que tu essaye d'y acceder en GET via ton navigateur.

On peut continuer par mail ou par téléphone si tu veux, pour ne pas polluer toutes les personnes abonnées aux issues GeoNature.

**Comment by AudreyEnGuyane** [comment]
On va faire ça, en effet...

**Comment by AudreyEnGuyane** [comment]
Tout ceci était lié non pas à la création de jeux de données mais à leur affichage/modification. Puisqu'on a réussi à débloquer la situation (_Standing ovation pour Théo!_), voici la/les solutions.

**Pour la taxonomie qui apparaissait vide**: le nom_valide de ma bestiole était _null_. Juste en remplissant ce champ, ça corrige la situation. Cependant, je réinterroge: quand le nom_valide n'est pas saisi, pourquoi le formulaire de saisie (quand on revient sur notre occurrence de taxon pour la modifier) nous affiche un taxon _Undefined_? On dirait que l'appli cherche un lien en se basant sur le texte. Le lien ne se fait-il pas sur le cd_nom?

**Pour le "Une erreur s'est produite"**: il y avait un soucis de récupération des coordonnées sur la carte lorsque l'objet géographique n'avait pas été modifié. Ici, la solution est de modifier la fonction ref_geo.fct_trg_calculate_geom_local():
```
CREATE OR REPLACE FUNCTION ref_geo.fct_trg_calculate_geom_local()
  RETURNS trigger AS
-- trigger qui reprojete une geom a partir d'une geom source fournie
-- en prenant le parametre local_srid de la table t_parameters
-- 1er param: nom de la colonne source
-- 2eme param: nom de la colonne a reprojeter
-- utiliser pour calculer les geom_local à partir des geom_4326
$BODY$
DECLARE
	the4326geomcol text := quote_ident(TG_ARGV[0]);
	thelocalgeomcol text := quote_ident(TG_ARGV[1]);
        thelocalsrid int;
        thegeomlocalvalue public.geometry;
        thegeomchange boolean;
BEGIN
	-- si c'est un insert ou que c'est un UPDATE ET que le geom_4326 a été modifié
	IF (TG_OP = 'INSERT' OR (TG_OP = 'UPDATE' AND NOT ST_EQUALS(hstore(OLD)-> the4326geomcol, hstore(NEW)-> the4326geomcol)  )) THEN
		--récupérer le srid local
		SELECT INTO thelocalsrid parameter_value::int FROM gn_commons.t_parameters WHERE parameter_name = 'local_srid';
		EXECUTE FORMAT ('SELECT ST_TRANSFORM($1.%I, $2)',the4326geomcol) INTO thegeomlocalvalue USING NEW, thelocalsrid;
                -- insertion dans le NEW de la geom transformée
		NEW := NEW#= hstore(thelocalgeomcol, thegeomlocalvalue);
	END IF;
  RETURN NEW;
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
```

Théo l'a déjà intégré dans la 2.0.1.

**Comment by TheoLechemia** [comment]
> Le lien ne se fait-il pas sur le cd_nom?

Si le lien est bien fait sur le cd_nom. Mais en gros l'appli fait un ``SELECT nom_valide WHERE cd_nom => X ``. Et quand le ``nom_valide`` n'est pas rempli dans la table taxref, il en résulte un "undefined" sur l'interface.

**Comment by AudreyEnGuyane** [comment]
Ok, c'est noté.
En tous cas, c'est résolu.
:-)

**Comment by gildeluermoz** [comment]
Un coalesce ?
