### ISSUE TITLE
[Frontend] Affichage des JDD dans les listes de choix

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoNature#583]
Depuis mon upgrade en 2.0.0, les listes de choix des jeux de données (OccTax, Synthese et Export) affichent les valeurs du champ `dataset_shortname` au lieu de `dataset_name`. En revanche c'est bien `dataset_name` qui s'affiche sur l'instance de démo.

**Comment by TheoLechemia** [comment]
C'est voulu pour le pas trop surcharger les listes déroulantes.
A voir si le shortname est suffisant dans tous les cas en effet.

**Comment by xavyeah39** [comment]
OK. A moi de revoir les intitulés de mes noms courts pour les rendre plus présentable alors ;) : 

![capture d ecran 2019-03-07 a 09 00 54](https://user-images.githubusercontent.com/16793813/53941122-94bb3380-40b7-11e9-94a2-0f6c6df20763.png)

**Comment by DonovanMaillard** [comment]
Salut à vous. Je suis aussi favorable à remettre les noms longs comme pour les cadres d'acquisition.

Le nom court est limité à 30 caractères dans le standard (à limiter aussi sur GN ?)
En 30 caractères on a fait le test. Pas possible d'identifier clairement un jeu de données

**Comment by xavyeah39** [comment]
Hello, 
Oui effectivement @DonovanMaillard, j'étais justement entrain de regarder la définition dans le standard :) 
J'ai provisoirement contourné en reportant les valeurs de `dataset_name` dans 'dataset_shortname` qui est bien un champ de type `character varying(255)`. Mais comme le suggère Donovan, il semble pertinent de le limiter à 30 pour coller au standard.

**Comment by DonovanMaillard** [comment]
Oui et pour aller plus loin le nom classique ne devrait pas non plus excéder 150 caractères. J'imagine que rajouter la contrainte uniquement dans la base ne suffit pas pour que ça se traduise dans l'interface ? Jai espoir que ça soit si simple ^^

**Comment by camillemonchicourt** [comment]
Retour à l'affichage du Nom long dans la 2.0.1 à venir.

**Comment by GwenUrcpie** [comment]
Bonjour,

Je réveille cette issue qui est fermée depuis longtemps mais je me demandais s'il était justement possible de choisir entre l'affichage du nom court et du nom long ? Je me dis qu'on a pas forcément tous les mêmes pratiques sur le nommage des jeux de données et j'ai eu pas mal de retours d'utilisateurs sur l'affichage des noms de jdd qui sont encombrants dans les listes déroulantes. Est-ce que c'est une question qui a été retraitée depuis ?

**Comment by camillemonchicourt** [comment]
Non, ça fonctionne comme indiqué dans la fin du ticket.
On affiche le nom long.

A voir si vous voulez prendre en charge un développement pour permettre de choisir si on affiche le nom long ou le nom court ?
