### ISSUE TITLE
[Synthèse] Bug filtres de recherche géographiques

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoNature#585]
Après personnalisation du fichier de configuration pour afficher des filtres de recherche géographiques supplémentaires basés sur la table `ref_geo.l_areas` et `ref_geo.bib_areas_types` (par exemple ici les zones Natura 2000) : 
- Les champs de recherche s'affichent bien avec les valeurs choisies
- Mais la recherche ne renvoi aucun résultats (sur une zone où des données sont pourtant bien présentes).

**Comment by AudreyEnGuyane** [comment]
xavyeah39,
j'avais eu le même problème mais pour les communes: bien qu'intégrées dans la projection locale, les polygones étaient décallés donc les données pointaient à côté. cf. [issues/573](https://github.com/PnX-SI/GeoNature/issues/573)
Avez-vous vérifié que vos zonages sont bien dans la projection "locale" et bien calés? (une ouverture sous qGis de la table l_areas permettra d'éliminer cette possibilité...)

**Comment by DonovanMaillard** [comment]
J'avais également eu et fait remonter ce soucis, je nai pas re-testé depuis.

Attention xavier, une ou deux couches du référentiel de l'inpn sont sans un Lambert 93 douteux, c'est le cas des parcs nationaux. J'ai fait remonter linfo ils ont corrigé la couche y a 2 semaines environ...

**Comment by xavyeah39** [comment]
Salut à vous,
Merci @AudreyEnGuyane. Pas de soucis de projection ni de géométries mais tu m'a mis sur la voie de la solution :) : 
Comme j'ai testé ça un vendredi en fin de journée je n'ai percuté sur le coup mais pour que les filtres fonctionnent, **il faut absolument recalculer les valeurs de `gn_synthese.cor_area_synthese` à partir du moment où la synthèse est déjà peuplée... !!**

Je vous fais une PR pour mettre un point d'attention à ce sujet dans la doc et près du paramètre `AREA_FILTERS` dans le fichier `default_config.toml.example`.

En tout cas, corrigé chez moi avec la requête suivante : 

	ALTER TABLE gn_synthese.synthese DISABLE TRIGGER ALL;
	
	-- /!\ --
	TRUNCATE TABLE gn_synthese.cor_area_synthese;
	
	INSERT INTO gn_synthese.cor_area_synthese
	SELECT id_synthese, id_area
	FROM gn_synthese.synthese s
	JOIN ref_geo.l_areas l
	ON st_intersects(s.the_geom_local, l.geom);
	
	ALTER TABLE gn_synthese.synthese ENABLE TRIGGER ALL;

Merci et a++
