### ISSUE TITLE
Liens morts dans la synthese

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#586]
Actuellement, impossible de retourner vers le module de saisie depuis la synhèse, les liens sont morts.

**Comment by TheoLechemia** [comment]
Est-ce que tu peux me donner le lien qui est généré ?
Et également la valeur de la colonne "url_source" de la table gn_synthese.t_sources pour occtax ?

Merci

**Comment by DonovanMaillard** [comment]
L'URL dans la t_sources est resté par défaut, pas de modif de ce coté. 

Je parle bien du bouton "voir dans le module de siaisie" qui est présent en haut de la fiche dans la modale info. Sauf erreur l'erreur est présente sur toutes les instances y compris la démo ;)

**Comment by TheoLechemia** [comment]
Quel est l'URL vers laquelle tu es redirigé ?

**Comment by DonovanMaillard** [comment]
aucune. Le bouton renvoie vers rien il ne génère pas de lien à priori. J'ai pas de "copier l'adresse du lien" en cliquant droit, pas d'URL affiché n bas de mon navigateur comme c'est le cas normalement etc.

**Comment by AudreyEnGuyane** [comment]
J'ai le même soucis... Une solution a-t-elle été trouvée?

**Comment by TheoLechemia** [comment]
Non, on regarde ça avec Donovan lundi.

**Comment by xavyeah39** [comment]
Hello,
Je retrouve le comportement que vous décrivez sur mon instance MAIS, seulement sur les données dont la source n'est pas OccTax (mon historique de données intégré dans la synthèse et qui ne renvoi donc vers aucun module de saisie de GN).
EN REVANCHE, **tout fonctionne bien pour les données qui ont été saisies via OccTax** (depuis le lien direct via le picto de la table de la synthèse ET depuis le bouton "voir dans le module de siaisie" de la fiche info).
A vous,

**Comment by camillemonchicourt** [comment]
Oui si c'est ça, tu me rassures. 
C'est sur que les données non saisies dans Occtax ne peuvent pas renvoyer à un module GeoNature qui n'existe pas. 
Il y a une amélioration à faire pour n'afficher le bouton que quand la donnée vient d'un module GeoNature.

**Comment by AudreyEnGuyane** [comment]
Pour mon cas, le bouton ne renvoie vers rien, même pour les données saisies dans occtax (suis toujours sur la rc4.2)

**Comment by TheoLechemia** [comment]
Problème lié à la compatibilité Firefox.
Résolé
