### ISSUE TITLE
Encodage des fichiers exportés

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#587]
Bonjour, 

Je ne sais pas pour vous, mais sur nos instances, les fichiers exportés sont encodés en UTF8 nous faisant buguer tous les accents etc. 

Quelqu'un a-t-il une soluion sur ce point? Une configuration de postgre quelque part? de geonature? :)

**Comment by xavyeah39** [comment]
Hello,
Pas de soucis chez moi avec la BDD qui est bien en UTF8 (vérifie dans la définition SQL de ta BDD depuis PGAdmin) et ouverture avec LibreOffice (qui lui, demande bien les paramètres du fichier à l'ouverture contrairement à Excel qui utilise par défaut le Latin1).
Tu ouvre ton fichier avec Excel ou LibreOffice ?

**Comment by DonovanMaillard** [comment]
les collegues utilisent excel en effet. A voir si ca se configure...

**Comment by xavyeah39** [comment]
Solution 1 : changer les habitudes des utilisateurs pour ouvrir un CSV UTF8 depuis Excel : 
http://www.idweb.fr/pages/ouvrir-un-fichier-csv-encode-en-utf8-sur-excel/

Solution 2 : oui ça se configure par défaut mais ça à l'air relou et dépendant de ton système : 
https://superuser.com/questions/911369/change-default-encoding-of-excel-to-utf-8

Solution 3 : il semble que si on génère un CSV en UTF-8 mais avec BOM (Byte Order Mark) ça force excel à l'ouvrir dans le bon encodage...
https://stackoverflow.com/questions/155097/microsoft-excel-mangles-diacritics-in-csv-files

**Comment by xavyeah39** [comment]
Solution 4 : Utiliser LibreOffice ;)'

**Comment by AudreyEnGuyane** [comment]
> Solution 4 : Utiliser LibreOffice ;)'

Surtout qu'excel tronque les gros fichiers!!
