### ISSUE TITLE
Occtax : erreur sur l'action update

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#588]
Lors que je saisis un relevé avec 3 occurrences, et que je l'enregistre, ça passe. 

Si je reviens dessus pour ajouter 2 espèces, ça a l'air de marcher. Mais si j'enregistre, je ferme et je reviens, j'ai moins d'espèces qu'il ne le faudrait, et certaines espèces sont supprimées du relevé. Y compris coté BDD.

**Comment by xavyeah39** [comment]
Bien vu dis donc ! Même comportement chez moi.

**Comment by AudreyEnGuyane** [comment]
Idem!
J'avais fait remonter à Théo mais on a pensé qu'il s'agissait d'un problème lié à la projection "exotique" guyanaise.
Le log d'erreur faisait mention d'un problème de récupération des coordonnées avec la fonction `ref_geo.fct_trg_calculate_geom_local():`

> CONTEXT:  SQL statement "SELECT ST_EQUALS($1.geom_4326, $1.geom_local)"
> PL/pgSQL function ref_geo.fct_trg_calculate_geom_local() line 10 at EXECUTE
>  [SQL: 'UPDATE pr_occtax.t_releves_occtax SET date_min=%(date_min)s, date_max=%(date_max)s, geom_4326=ST_GeomFromWKB(%(ST_GeomFromWKB_1)s, %(ST_GeomFromWKB_2)s) WHERE pr_occtax.t_releves_occtax.id_releve_occtax = %(pr_occtax_t_releves_occtax_id_releve_occtax)s'] [parameters: {'date_min': '2019-03-04', 'pr_occtax_t_releves_occtax_id_releve_occtax': 20, 'ST_GeomFromWKB_2': 4326, 'ST_GeomFromWKB_1': <memory at 0x7f0bc0c16b88>, 'date_max': '2019-03-04'}]

Finalement, je ne suis peut-être pas isolée...

En tous cas, vous pouvez contourner le problème: refaites votre manip mais, avant de valider votre modification, cliquez sur la carte: ça devrait fonctionner.

**Comment by DonovanMaillard** [comment]
Merci Audrey, 

Après avoir testé, même en déplacant un peu notre point, ca ne marche pas ici. Dommage pour nous!

**Comment by TheoLechemia** [comment]
@AudreyEnGuyane 
Le bug que tu décrit est autre chose.
J'investigue et vous tiens au courant

**Comment by TheoLechemia** [comment]
Merci pour la remonté du bug Donavan. 
Il s'agit d'un problème obscure d'ORM que je n'arrive pas à comprendre. J'ai posé une question sur stack:
https://stackoverflow.com/questions/55107485/sqlalchemy-error-while-merging-relationnship
D'ici là, si certains on des lumières (@lpofredc, @patkap ) ?

**Comment by TheoLechemia** [comment]
Fix.
Pour info, le merge d'une relation enfant ne fonctionne pas si son "id" est passé dans la construction du modèle, et ce même si l'id est égal à ``None``.

**Comment by DonovanMaillard** [comment]
Attention pour info, et vérifier si la correction faite rectifie également ce point. 

L'action update a le même comportement quand on ajoute des dénombrements, pas uniquement des espèces sur un relevé. SI j'ai un relevé avec une espèce, et que je viens préciser "3 males et 6 femelles", l'application ne garde que les 6 femelles.

**Comment by TheoLechemia** [comment]
C'est corrigé aussi oui
