### ISSUE TITLE
Doublons sur un relevé occtax

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#590]
Une simple remontée d'utilisateur pour plus tard (mais je la mets ici avant de l'oublier). 

Sur occtax, un utilisateur peut saisir 2 fois une même information (même espèce, meme méthode, etc) sans avoir d'alerte. Dans le cas où l'on saisit des relevés type piégeage ou autre avec beaucoup de taxons relevés, une alerte pour signaler que la meme info a été saisie plusieurs fois pourrait éviter des doublons. Une idée pour plus tard donc, car ça implique quand meme de vérifier sur chaque revelé que l'info a déjà été saisie totalement a l'identique auparavant...

**Comment by camillemonchicourt** [comment]
Depuis pas mal de versions, si on essaie d'ajouter sur un même relevé, un taxon que l'on a déjà renseigné, cela lève une alerte : 

![image](https://github.com/PnX-SI/GeoNature/assets/4418840/2f59d079-8c3b-4dd8-871f-502274762a3d)
