### ISSUE TITLE
Problème d'authentification dans Geonature

### ISSUE THREAD

**Issue by MaelaRenaudOEB** [PnX-SI/GeoNature#591]
Bonjour,
C'est la première fois que je poste ici : je suis administratrice du projet de plateforme des données naturalistes bretonnes (et future plateforme régionale SINP) et nous avons choisi Geonature comme support pour le développement de celle-ci.
Après pas mal de bidouillages, nous avons installé la version stable la plus récente (2.0.0-rc.4.2) mais je rencontre un souci : j'arrive à me connecter à UsersHub avec mon compte admin mais impossible de le faire via Géonature, un message d'erreur apparait systématiquement : "Identifiant ou mot de passe incorrect". Le truc étrange c'est que si je suis connectée avec UsersHub, je peux éviter l'interface de connection en tapant juste localhost/geonature (sans le "/#/login") mais dans ce cas il semble que je sois considée comme un membre non autorisé puisque je ne vois pas le module Admin et que l'accès au module synthèse m'est refusé... Pourtant dans UserHub j'ai défini les droits du compte admin à Administrateur pour tous les modules.
J'espère être claire dans mon explication car je m'arrache les cheveux par touffes du coup!
Merci d'avance!

**Comment by DonovanMaillard** [comment]
Bonjour, 

En effet, sur la rc4.2 il y a eu des soucis d'authentification, qui ont été réglés désormais. Vous pouvez mettre à jour votre instance vers la version 2.0.0 sortie le 28 février. Les notes de version sont à voir ici pour la mise à jour : [ici](https://github.com/PnX-SI/GeoNature/releases) et la doc de mise à jour [ici](https://geonature.readthedocs.io/fr/latest/installation-standalone.html#mise-a-jour-de-l-application)


Par ailleurs, je suis en train de monter une plateforme SINP en Auvergne Rhone Alpes sur la base de GeoNature. Nos besoins seront sans doute équivalents, n'hésitez pas à prendre contact avec moi par la suite pour qu'on échange sur nos manières de fonctionner ou nos besoins de développements respectifs. Nous développerons prochainement le module d'import de données dans ce cadre par exemple.

**Comment by camillemonchicourt** [comment]
Oui la version la plus récente est la 2.0.0.
Mais sur la 2.0.0 l'authentification fonctionnait aussi.
Il faudrait voir ce que renvoie la console comme message ?
Et le plus simple est de faire une installation globale, il n'y a pas de bidouillages à faire.
Le mieux je pense est de refaire un install_all sur votre serveur remis à zéro.

**Comment by MaelaRenaudOEB** [comment]
Merci beaucoup à vous deux ! Je vais essayer la mise à jour et si cela ne fonctionne pas je referais un install_all.
@DonovanMaillard effectivement je pense que cela peut être intéressant que l'on reste en contact sur le sujet SINP, je reviendrais vers toi !

**Comment by MaelaRenaudOEB** [comment]
Je viens de remarquer que je n'ai pas de schéma pr_occtax... Ce qui est étrange... Je vais voir avec notre informaticien comment il a bidouillé l'install et s'il peut faire la maj ou la réinstall car étant une "simple" DBA je ne suis pas assez calée pour comprendre le soucis je crois (et vu que c'est pas moi qui ait fait l'install c'est d'autant plus compliqué...)

**Comment by camillemonchicourt** [comment]
Oui dans ce cas, une réinstallation propre s'impose. :-)

**Comment by MaelaRenaudOEB** [comment]
@camillemonchicourt Effectivement! J'ai fais une réinstall toute propre et tout fonctionne nickel! Merci!
