### ISSUE TITLE
mot de passe oublié

### ISSUE THREAD

**Issue by Amegilla** [PnX-SI/GeoNature#593]
Bonjour, 

Est-ce que quelqu'un a prévu d'ajouter à la page d'accueil un lien/page pour gérer le cas d'un oubli de mot de passe ?

**Comment by camillemonchicourt** [comment]
Oui c'est un chantier qui est en lien fort avec UsersHub. 
Pour le moment le PnCevennes a fait un travail conséquent sur la mise en place d'une API UsersHub pour pouvoir interagir avec la BDD de UsersHub depuis une application tierce. 
C'est en cours d'intégration dans UsersHub. 
Une fois qu'on aura cette API, on pourra imaginer des outils de création de compte et de réinitialiser de mot de passe dans GeoNature ou autre. 
Restera à les développer :-D

**Comment by RomainBaghi** [comment]
Super merci pour l'info. à suivre donc.

**Comment by laurentbarthe** [comment]
Bonjour.
Super !
Après attribution du login et du mot de passe par l’administrateur, est-il également prévu que la personne puisse changer son mot de passe ?

**Comment by camillemonchicourt** [comment]
Idem, il sera envisageable de le faire en utilisant l'API UsersHub. 
Comme pour la réinitialisation de mot de passe, il faudra le développer, mais ça sera possible.

**Comment by laurentbarthe** [comment]
Ok, merci. Dès lors que tu as beaucoup d'utilisateurs ça devient en effet indispensable.

**Comment by camillemonchicourt** [comment]
Oui surtout dans un contexte associatif. 
Ca l'est moins pour nous qui gérons les comptes de nos agents.

**Comment by laurentbarthe** [comment]
Exactement ! Chaque utilisateur doit pouvoir à terme gérer son code d'accès et même plus globalement son profil utilisateur.
Au niveau des profils, ce qui serait génial dans un 2nd temps c'est de pouvoir avoir des synthèses par personne comme nous l'avions dans WebObs. C'est du gadget par les naturalistes aiment bien ce type d'outils. http://www.webobs.cen-mp.org/
Il s'agit de voir le nombre d'espèces déjà saisie. Nous pourrions même imaginer avec le nombre de données saisie.

**Comment by camillemonchicourt** [comment]
On n'a pas prévu de faire de page Profil dans GeoNature. 
L'utilisateur peut aller dans un module ou dans la synthèse et filtrer sur son nom en tant qu'observateur. 
Par contre notre stagiaire arrive mercredi pour travailler sur un module Statistiques/Reporting qui proposera des graphiques et cartes de synthèse (par commune, par maille...) avec des paramètres ajustables pour chaque élément (règne, rang, JDD, organisme...)

**Comment by laurentbarthe** [comment]
Dommage, ces aspects sont sympas mais ils ne sont pas vraiment indispensables / utiles. Y a bien plus urgent... 
Justement les synthèses pour nous c'est bien plus important. C'est ce qui nous manque le plus actuellement avec le passage de webobs à GeoNature et notamment les synthèses par commune et par maille. Vous pensez le faire par nombre d'espèces, nombre de données et par groupe taxo ?

**Comment by camillemonchicourt** [comment]
Oui sur tout ce qui est reporting on se concentre sur l'aspect collectif plutôt qu'individuel = Avoir des synthèses et analyses sur l'ensemble des données plutôt qu'uniquement sur ses propres données. 

Par contre il serait assez simple d'afficher le nombre de données et le nombre d'espèces de l'utilisateur connecté, comme on affiche déjà ces infos sur la page d'accueil mais au niveau global.

**Comment by camillemonchicourt** [comment]
Formulaire de réinitialisation et de changement de MDP mis en place dans la version 2.2.0 de septembre 2019.
