### ISSUE TITLE
Un dépot de pictos?

### ISSUE THREAD

**Issue by AudreyEnGuyane** [PnX-SI/GeoNature#595]
Bonjour à tous,

J'étais en train de me créer un lot de pictogrammes quand je me suis souvenue du message de sig-pnrnm [là](https://github.com/PnX-SI/GeoNature/issues/392)

Pourrait-on se faire un dépôt de pictos pour éviter les doublons? (pour ceux qui voudraient partager leurs œuvres)
Quelle est la taille des images à créer? 25*25 px? autre?
Quel format? gif obligatoire?
Noir et blanc? Ou peut-on partir en cacahuète et faire des orange sur blanc pour les animaux, vert sur blanc pour les végétaux et marron sur blanc pour les champis?

**Comment by Splendens** [comment]
Et ne pas oublier de partager vos œuvres sur http://phylopic.org/ ;-)

**Comment by camillemonchicourt** [comment]
Des pictogrammes pour quoi ?
Dans GeoNature-atlas je vois bien mais dans GeoNature ?

**Comment by sig-pnrnm** [comment]
Ceux que j'avais mis sur ma capture d'écran étaient ceux de GeoNature-Atlas : https://github.com/PnEcrins/GeoNature-atlas/tree/master/static/images

**Comment by AudreyEnGuyane** [comment]
Bon, bah, voilà. Ca répond à ma question et, je pense à tous mes besoins...
J'avais jeté un oeil dans mon dossier pictos de taxhub et n'avais pas tous ces pictos.
Si je dois en créer un autre, je le partagerai.
Merci!
