### ISSUE TITLE
Gros jeu de données

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature#599]
L'outil d'importation automatique et incrémentale des données  des données VisioNature (https://framagit.org/lpo/Client_API_VN/tree/develop) étant maintenant fonctionnel, je  m'attèle maintenant à l'intégration dans la synthèse visionature (données de toute la région AuRA). L'occasion de tester le fonctionnent avec un gros lot de données 15 millions. Sans surprises, quelques lenteurs liées aux consultations de la bdd. Les statistiques générales de la page d'accueil prennent 30 secondes à charger, je pense le désactiver.

Je vous ferrai plus de retours dès que j'aurai le temps de faire plus de tests, notamment sur le module synthèse.

![Sélection_281](https://user-images.githubusercontent.com/22891423/54807264-003afe80-4c7d-11e9-9f86-28d4e915b03e.png)

**Comment by camillemonchicourt** [comment]
OK excellent et très intéressant.
Oui c'est pas étonnant.
Il y a encore des choses à optimiser et des choses à pouvoir masquer selon les contextes.

Merci.

**Comment by TheoLechemia** [comment]
Le paramètre pour masquer le bloc est à améliorer également, car l'appel à la BDD est fait quoiqu'il arrive.

**Comment by lpofredc** [comment]
Oui, en faire des composants distincts appelés sous condition?

**Comment by camillemonchicourt** [comment]
C'est du au fait que l'on applique le CRUVED aux chiffres affichés qui impose de nombreuses jointures et vérifications.
La question qui se pose est "Doit-on appliquer le CRUVED sur les graphiques et statistiques globales pour les limiter aux données que les utilisateurs verront ensuite dans les modules Synthèse et autres ou alors baser les statistiques et graphiques sur toutes les données de la BDD ?"
C'est cette deuxième solution qu'on a retenu pour le moment dans le nouveau module https://github.com/PnX-SI/gn_module_dashboard

**Comment by TheoLechemia** [comment]
Corrigé
