### ISSUE TITLE
droits metadonnées et admin

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#601]
bonjour, 

J'aimerais donner des droits de création/update pour le module métadonnées sans donner les droits sur les nomenclatures dans le module admin mais je n'y arrive pas. 

Exemple de CRUVED :
METADATA
Action de créer :  3 
Action de lire :  2  
Action d'exporter :  2   
Action de valider :  0  
Action de mettre à jour :  2  
Action de supprimer :  0

**Comment by DonovanMaillard** [comment]
Bonjour, 

Depuis la version 2.0.0, les métadonnées et les nomenclatures ne sont plus dans le même module. 

Les nomenclatures + les permissions sont dans le module admin, les métadonnées sont dans un module à part entière. Chacun devrait donc avoir son propre cruved.

**Comment by RomainBaghi** [comment]
J'ai oublié de préciser ma version, je suis sur la 2.0 et j'ai bien les deux modules séparés. Mais avec le cruved que j'ai noté ci dessous je n'ai pas le droit d'enregistrer un JDD ou CA.

**Comment by DonovanMaillard** [comment]
Sur le fond, il y a une incohérence dans ce cruved. Lire 2, Créer 3... ca suppose que quelqu'un peut créer des objets qu'il ne peut pas lire. 
Mais je ne pense pas que ca soit l'origine du problème, je teste.

**Comment by DonovanMaillard** [comment]
En effet, même problème sur mon instance avec Lire, Créer et Mettre à jour = 3. Y compris si le CA concerne uniquement mon role. Idem pour le JDD. :) Il semble bien y avoir un petit bug de ce coté

**Comment by RomainBaghi** [comment]
merci Donovan, j'attends ton retour :)

**Comment by RomainBaghi** [comment]
ouf, je me sens moins seul !

**Comment by RomainBaghi** [comment]
Pour pallier à ça, je n'ai pas trouvé d'autres solutions que d'ouvrir les droits sur le module admin (nomenclature seulement).

**Comment by DonovanMaillard** [comment]
oui, les métadonnées et les nomenclatures étaient ensemble avant l'apparition des permissions. Sans doute un petit oubli dans le code au moment de la séparation des deux modules :)

**Comment by TheoLechemia** [comment]
Merci messieurs ! C'est corrigé. En effet c'est le CRUVED du module ADMIN qui était vérifié et non celui de METADATA

**Comment by TheoLechemia** [comment]
https://github.com/PnX-SI/GeoNature/commit/40e074a67e011e7327414ea12ae8fa0e317e0131#diff-70b84ebce832827ebc15b8c37fb33c28R101
