### ISSUE TITLE
Page de login non surcouchée par custom.scss?

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#606]
Après plusieurs essais, j'ai l'impression que la page de login ne peut pas être surcouchée par les infos de custom.scss à l'heure actuelle. 

Une petite évolution pour la suite ? :)

**Comment by camillemonchicourt** [comment]
C'est parce qu'elle est déjà assez belle 😄

**Comment by DonovanMaillard** [comment]
Oups! Au temps pour moi, j'avais pas vu! :p Bon, j'ai changé ça dans le css de la page directement puisque c'est ça. :)
