### ISSUE TITLE
CRUVED et exports synthèse

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#608]
A priori, une petite coquille au niveau du CRUVED (v2.0.1). 

Mes utilisateurs ne devraient pas avoir droit de télécharger dans la synthèse mais ils le peuvent. L'uilisateur en question n'a pas de droit qui lui sont propres (seulement ceux de son groupe), et il n'appartient bien qu'à un groupe, il n'acquiert donc pas le droit de télécharger par ailleurs. (CRIVED de son groupe, uniquement lire la synthèse et les métadonnées).

**Comment by TheoLechemia** [comment]
https://github.com/PnX-SI/GeoNature/commit/a46fb0c9349e80202ef585dc808c66b847415059
Corrigé
