### ISSUE TITLE
Proposition : observations et organismes

### ISSUE THREAD

**Issue by jbdesbas** [PnX-SI/GeoNature#610]
Bonjour,

Actuellement l'organisme auquel appartient un utilisateur est codé dans la table _utilisateur.t_roles_.
C'est également la démarche que nous avions adoptés, mais qui nous a rapidement posé des soucis : il est très fréquent que des naturalistes observes pour le compte de différents organismes, à titre pro ou bénévole.
Je trouverais donc cohérent d'ajouter dans les table _pr_occtax.cor_role_releves_occtax_ et _gn.synthese.cor_observer_synthese_ les champs suivants : 
- _id_organisme_ (int)
- _benevole_ (bool)
(en plus des champs _id_role_ et _id_releve_ )

L'id_organisme de la table utilisateur pourrait conservé comme organisme par défaut.

Sans ça, les utilisateurs sont obligés de créer plusieurs comptes, et cela rend le rapprochement des référentiels utilisateurs de différentes structure encore plus compliqué que ce que ça n'est déjà. Niveau conceptuel, je trouve ça assez cohérent qu'un **utilisateur soit une personne physique**, et que ca soit bien **l'observation par cet utilisateur qui soit faite pour le compte d'un organisme**. Le booléen "bénévole" a surtout une finalité statistique pour les bilans, mais qui risque d'être très demandé.

Au niveau de la saisie sur occtax, il devrait donc être possible pour chaque observateur de choisir un organisme et de cocher s'il s'agit d'une observation bénévole.

**Comment by camillemonchicourt** [comment]
Sujet lié à https://github.com/PnX-SI/GeoNature/issues/182

C'est une très bonne chose que de gérer les organismes au niveau des Jeux de données et non pas au niveau de chaque donnée.
Mais ça pose aussi quelques questions, comme celle-là que tu évoques.

Et il y a cet autre sujet d'avoir des utilisateurs multi-casquettes, associés à plusieurs organismes.
Ce deuxième complexifie pas mal de choses mais n'a pas de conséquences fonctionnelles identifiées.

**Comment by jbdesbas** [comment]
En effet c'est exactement ça !

**Comment by camillemonchicourt** [comment]
Concernant la question Bénévole ou Salarié il ne faut pas le gérer à chaque observation mais au niveau des observateurs eux-mêmes. 
C'est déjà possible en créant un groupe Salarié et un groupe Bénévole dans UsersHub.

**Comment by DonovanMaillard** [comment]
Sur la partie bénévole / salarié, effectivement, je gérerais ça à l'échelle d'un groupe.... voire d'un jeu de données (en général, dans notre asso en tous cas, les études sont dans un cadre salarié, les données opportunistes dans un cadre bénévole). Mais oui, les groupes répondent sans soucis au besoin..  Au détail près que ca marche si on reste dans l'idée de choisir ça pour toutes les données d'une personne, ou d'un jeu. Si ca se fait donnée par donnée, le problème se pose autrement, mais j'ai donné ma vision des choses sur l'autre discussion ;)
