### ISSUE TITLE
Comment recalculer Synthèse ?

### ISSUE THREAD

**Issue by CistudeNature** [PnX-SI/GeoNature#611]
Bonjour,

Nous avons supprimé par erreur tout le contenu de la table synthese du schéma gn_synthese, avez-vous une méthode pour reconstruire le contenu de cette table?
Merci d'avance pour votre retour.

**Comment by TheoLechemia** [comment]
Bonjour,
Sans sauvegarde de la base, il n'y a malheureusement pas de méthode magique pour retrouver ses données...
Voici la doc pour faire des sauvegardes et des restaurations de base: 
https://geonature.readthedocs.io/fr/latest/admin-manual.html#sauvegarde-et-restauration
Il est recommandé de mettre en place des CRON qui font cette tâche toute les nuits par exemple

**Comment by DonovanMaillard** [comment]
Bonjour, 

Une autre solution est de prende un backup automatique chez l'hébergeur par exemple. 

Si vos données proviennent uniquement de occtax, vous pouvez sans doute les récupérer depuis pr_occtax, et les rebasculer dans la synthèse en adaptant la fonction pr_occtax.insert_in_synthese ? Si ca vient d'autres sources, repartir de vos scripts d'intégrations de données à la main...

**Comment by camillemonchicourt** [comment]
Oui cela dépend des données qui y étaient intégrées.
Pour les données saisies depuis Occtax, elles sont intégrées dans la Synthèse automatiquement avec un trigger.
Vous pouvez les réintégrer dansa synthèse en vous inspirant des triggers Occtax vers Synthèse.

Vous pouvez essayer de simuler une modification des données d'occtax pour que les triggers se déclenchent.

**Comment by camillemonchicourt** [comment]
Bonjour @CistudeNature, avez-vous réussi à régler votre problème ou des précisions sur la source des données ?
