### ISSUE TITLE
Nomenclature UICN

### ISSUE THREAD

**Issue by jbdesbas** [PnX-SI/GeoNature#612]
Bonjour,

Je souhaite proposer une PR avec l'ajout de la nomenclature des niveau de menace UICN.
L'idée derrière étant de pouvoir afficher la définition d'un niveau de menace au survol.
1 - Cela vous parait-il pertinent ? (je m'en sert pour afficher et expliciter le niveau de menace régionale sur les fiches atlas)
2 - Que signifie le champs "statut" (validé/non validé/validation en cours) ? Validé par qui ? Les définitions UICN doivent être validées ?

**Comment by TheoLechemia** [comment]
Bonjour,

Oui c'est tout à fait le genre de nomenclature qui pourront être utile dans GeoNature, ta PR est la bienvenue.
Par contre à l'heure actuelle, l'atlas ne dépend pas du schéma "ref_nomenclature" de la base GeoNature, mais ça c'est une autre histoire.
Le champs "valide" renseigne s'il s'agit d'un item de nomenclature "officiel". Dans ton cas, c'est "true" partout, à moins que tu t'amuses à rajouter des nomenclatures exotiques qui ne dépende pas de l'UICN

**Comment by jbdesbas** [comment]
Ok merci !
J'ai créé un PR dans le [bon dépôt ](https://github.com/jbdesbas/Nomenclature-api-module/pull/1)

**Comment by gildeluermoz** [comment]
Rien n'empèche d'utiliser ces nomenclatures en FDW dans une évolution de l'atlas
