### ISSUE TITLE
Mise à jour des lib Angular

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#614]
En lien avec https://github.com/PnX-SI/GeoNature/pull/613

Problème de la compilation en AOT avec ngx-translate et/ou ngx-toastr qui ne se chargent pas dans le module occtax.

Dans occtax, au niveau du formulaire du relevé, une erreur à obliger à modification les accès aux différents controls du form par .get('nomDuControle') plutôt que .controls.nomDuControle. La même manip serait à faire dans les autres formulaires.

**Comment by Adrien-Pajot** [comment]
En lien avec #1547 ?

**Comment by Adrien-Pajot** [comment]
Vu avec @jbrieuclp , fermable
