### ISSUE TITLE
Utilisation de ng-select dans les formulaires

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#616]
Je vais proposer une PR intégrant l'utilisation de la lib select2 (ici pour la [demo](https://select2.org/getting-started/basic-usage)) en surcharge des différentes zone de listes.
Select2 permet en natif d'avoir des liste déroulante avec une fenêtre de filtre pour trier les données de la liste.
Au passage, je propose de faire un trie alphabétique sur les valeurs ?

Pour les multiselect il faut voir si select2 est préférable au multiselect.component ?

**Comment by TheoLechemia** [comment]
Ok merci. 
Tu as testé son intégration avec les reactive form angular ? ça fonctionne bien ?
A tester, mais oui il pourrait remplacer le composant mutliselect, qu'on a réécrit à la mano, mais c'est plus judicieux d'utiliser un lib existante.

**Comment by jbrieuclp** [comment]
C'est testé pour le form/datasets/datasets.component qui est utilisé pour occtax et c'est fonctionnel.
Je teste en mode multiselect toujours avec les jeux de données sur le formulaire de la synthèse.
L'idée serait de créer un composant commun form/select sur le même fonctionnement que le form/multiselect actuel.
Pour select2 il y a un problème avec l'installation de @types/select2 qui indiqué comme une dev-dependance, mais ça fonctionne sans cette lib.

**Comment by camillemonchicourt** [comment]
OK super. Et de ce que je vois, ça pourrait nous être utile pour les nomenclatures à 2 niveaux, pour regrouper les nomenclatures filles d'une même nomenclature mère.

**Comment by jbrieuclp** [comment]
Dans le projet angular geonature, le type require de require.js utilisée par select2 rentre en conflit avec l'utilisation du type noderequire de geonature. L'usage de select2 en devient donc bancale. [Ng-Select](https://github.com/ng-select/ng-select) est une bonne alternative seulement il n'est que compatible angular 5+

**Comment by camillemonchicourt** [comment]
OK bien vu, en effet ça semble une bonne solution à combiner avec le passage à Angular7 : https://github.com/PnX-SI/GeoNature/pull/613
Merci.

**Comment by jbrieuclp** [comment]
Pour fêter l'anniversaire de cette issue je la relance. 
J'ai pu tester dernièrement ng-select2 qui ne fonctionnait pas il y a 1 an (il y avait des incompatibilité de lib), mais qui fonctionne dorénavant sous ce projet geonature. La lib ng-select2 intègre la bibliothèque [select2](https://select2.org/getting-started/basic-usage) à Angular pour générer des listes déroulantes avec zone de recherche, ça facilite vachement l'usage des formulaires en simplifiant le code sans réinventer la roue.

L'année dernière a défaut d'utiliser ng-select2, j'avais pu déployer la librairie ng-select à geonature (Core, Occtax, Synthèse, Metadata et Validation). Les dev sont sur ma branche [occtax-select2](https://github.com/jbrieuclp/GeoNature/tree/occtax-select2/frontend) et sont déployés en prod sur notre version de geonature.

Pour ma part, je trouve ng-select moins intéressante que ng-select2, la zone de recherche écrase la zone des valeurs. L'affichage pose parfois problème sur les longues valeurs. 
Les pages de démo ici :
[ng-select](https://ng-select.github.io/ng-select#/data-sources)
[ng-select2](https://tealpartners.github.io/ng-select2/)

Sachant qu'il n'y a pas beaucoup de changement au niveau du fonctionnement et du code des 2 lib, il devrait être possible de passer de ng-select à ng-select2 sans trop de problème.

La question est comment faire pour intégrer cette lib aux liste déroulantes des différents modules non intégrés par défaut à geonature et qui n'utilisent pas les components présent dans le GNCoreModule ?

**Comment by camillemonchicourt** [comment]
Oui intéressant. Tu veux dire que si on bascule sur cet librairie de sélection des listes, cela casserait les modules externes si ils ne sont pas modifiés ?
Pas possible de garder les 2 le temps que les modules externes modifient leurs listes ?

**Comment by TheoLechemia** [comment]
Je pense que pour la rétrocompatibilité il faut conservé l'ancien "multiselect" pour que les modules externes fassent la migration à leur rythme.
Pour le coeur on crée un nouveau composant et un gros rechercher/remplacer devrait faire l'affaire

**Comment by jbrieuclp** [comment]
Non je dis qu'au sein d'une même pas tu pourrais avoir une liste avec select2, si il est intégré au core et une liste basique si il est spécifique au module tiers. Du passage de la branche occtax-select j'avais pu conserver la rétrocompatibilité sur les différents modules.
Mais c'est surtout au niveau visuel que ça peut "choquer".

**Comment by camillemonchicourt** [comment]
OK dans ce cas, il faut pas se priver je pense, et ça motivera à basculer sur la nouvelle version.

**Comment by camillemonchicourt** [comment]
Passage à ``ng-select2`` dans la 2.9.0.
