### ISSUE TITLE
Export des données et droits des utilisateurs

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#62]
**AFFECTION DES DONNÉES A UN ORGANISME**

Actuellement toutes les données saisies par l'interface web sont associées à l'organisme principal (défini dans le paramètre `$id_organisme` dans le fichier `lib/sfGeonatureConfig.php` - https://github.com/PnEcrins/GeoNature/blob/master/lib/sfGeonatureConfig.php.sample#L36). 
Si des données sont intégrées autrement (SQL, ETL... par exemple), il est possible de les affecter à un autre organisme (par exemple dans le champs `id_organisme` dans `contacfaune.t_fiches_cf`).
A terme il serait mieux que l'association de l'organisme à une donnée saisie dépendent de l'organisme de l'utilisateur connecté.

**CONSULTATION et EXPORT DES DONNÉES**

Actuellement un utilisateur utilisant la synthèse ne peut exporter que les données saisies par les utilisateurs de son organisme (défini dans UsersHub). 

Par contre quand il consulte la synthèse, il voit les données de tous les organismes. 

Une autre possibilité est qu'un utilisateur ne puisse exporter que ses propres données. 
Pour cela il faut le mettre dans une unité spécifique (définie dans UsersHub) et dont `id_unite` est renseignée le paramètre `$id_unite_fournisseur` dans le fichier `lib/sfGeonatureConfig.php` - https://github.com/PnEcrins/GeoNature/blob/master/lib/sfGeonatureConfig.php.sample#L39).

Pour illustrer, tous les retraités du PnEcrins appartiennent à l'unité "Anciens du PNE" dans l'organisme PNE et ainsi ils peuvent continuer à saisir et consulter toutes les données de la synthèse mais ils ne peuvent exporter que leurs propres données et non pas toutes celles du PNE comme le peuvent les agents en poste.

**Comment by gildeluermoz** [comment]
Sujet à traiter en V2. 
L'organisme producteur ne peut pas être lié à l'observateur ni à la personne identifiée faisant la saisie. A titre d'exemple, le CBNA saisi des fiches observations faites par les agents du PNE.
Distinction à faire entre propriétaire et producteur de la donnée.
Par exemple, les données produites dans le cadre de l'ATBI par Flavia sont propriété du PNE par convention mais le producteur est Flavia.

**Comment by camillemonchicourt** [comment]
Depuis la 1.8.3 (https://github.com/PnEcrins/GeoNature/releases/tag/1.8.3) l'organisme associé à une donnée n'est plus liée au paramètre `$id_organisme` qui a été supprimé mais est lié à la structure de l'utilisateur connecté. 

Concernant les exports dans la synthèse, désormais les utilisateurs ne peuvent télécharger que les données de leur propre organisme. 

A affiner dans la V2 pour avoir un niveau de droit où les utilisateurs ne peuvent télécharger que leurs propres données et un niveau admin qui peut télécharger toutes le données.

**Comment by camillemonchicourt** [comment]
Dans la V2 des droits plus fins ont été mis en place avec le CRUVED.

L'association d'un organisme à une donnée n'est pas lié a l'observateur mais aux acteurs associés au jeu de donnée dans lequel l'observation est saisie.
