### ISSUE TITLE
[Module OccTax] Associer média à une occurence

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/GeoNature#620]
Est-ce qu'une réflexion a été initiée concernant la possibilité d'associer des médias (le plus souvent une ou plusieurs photos) à une occurence de Taxon ?
Je me doute que cela soulève beaucoup de questions concernant l'hébergement de ces médias, et donc l'espace de stockage de nos instances, mais ce point serait quand même bien pratique, et utile aussi pour le module de Validation.

**Comment by camillemonchicourt** [comment]
Oui oui. Des choses ont été faites au niveau BDD et au niveau backend : https://github.com/PnX-SI/GeoNature/issues/336

**Comment by camillemonchicourt** [comment]
L'upload et l'affichage des médias a été intégré dans le module (https://github.com/PnX-SI/gn_module_monitoring) et pourra servir de base à leur implémentation dans Occtax : 

- https://github.com/PnX-SI/gn_module_monitoring/tree/develop/frontend/app/components/upload-media
- https://github.com/PnX-SI/gn_module_monitoring/tree/develop/frontend/app/components/medias

**Comment by jbdesbas** [comment]
C'est prévu dans le cahier des charges de la SHF il me semble ? (@RomainBaghi)

**Comment by camillemonchicourt** [comment]
Oui c'est ça. https://geonature.fr/documents/cctp/2020-01-SHF-CC-Developpement-modules-GeoNature.pdf

**Comment by camillemonchicourt** [comment]
En cours de développement par @joelclems dans la branche dédiée ``medias``. 
Voir les premiers commits : https://github.com/PnX-SI/GeoNature/commit/b4e65eb4be7bb0f71feb4d51452ee2251d5b3a73

**Comment by camillemonchicourt** [comment]
En cohérence avec le modèle de données, les médias sont stockés dans la table transversale ``gn_commons.t_medias``. Cela permet de les retrouver au niveau de la donnée source (Occtax dans ce cas), mais aussi dans la Synthèse, le module Validation etc...
Pour cela on utilise l'UUID de l'occurrence de taxons, en lien avec le champs ``gn_commons.t_medias.uuid_attached_row``. 
Dans Occtax, l'UUID de l'occurrence est au niveau du dénombrement. Donc les médias sont associés au niveau de chaque dénombrement dans la formulaire Occtax : 

![image](https://user-images.githubusercontent.com/4418840/91941635-cab39500-ecf9-11ea-9cf5-a09de676f1de.png)

Par défaut, on propose d'ajouter un média de type "Photo" à uploader et de le nommer avec la date et le nom du taxon choisi, avec l'utilisateur connecté comme auteur du média.
Cependant il est possible d'afficher les champs avancés, de modifier le nom, la description et l'auteur du média. Il est aussi possible de renseigner une URL du média plutôt que de l'uploader.
Et il est possible d'utiliser d'autres types de médias (audio, PDF, vidéo fichier, youtube ou Dailymotion...).

Des contrôles sur les formats des médias sont réalisés en fonction du type de média choisi.

Les médias sont ensuite affichés dans la liste des taxons enregistrés. En cliquant sur le nom du média, on ouvre celui-ci dans un nouvel onglet. 

![image](https://user-images.githubusercontent.com/4418840/91943015-2da62b80-ecfc-11ea-893b-ced75ad61b23.png)

Les médias sont ensuite aussi affichés dans la fiche info d'un relevé : 

![image](https://user-images.githubusercontent.com/4418840/91943318-adcc9100-ecfc-11ea-8f64-52794f39d402.png)

Ainsi que dans le fiche détail d'une observation dans la Synthèse : 

![image](https://user-images.githubusercontent.com/4418840/91943141-61815100-ecfc-11ea-9549-4c85acb748e4.png)

Et dans le module Validation : 

![image](https://user-images.githubusercontent.com/4418840/91943203-78c03e80-ecfc-11ea-97be-a37809ec12a8.png)

**Comment by camillemonchicourt** [comment]
Les développements réalisés sur les médias sont aussi répercutés sur les autres modules utilisant les médias.
C'est ainsi le cas dans le module Monitoring, en cours d'évolution, et dont la version en cours de développement a été déployée sur le serveur de démo : https://demo.geonature.fr/geonature/ - Module Monitorings.

**Comment by camillemonchicourt** [comment]
Intégré dans la version 2.5.0.
