### ISSUE TITLE
Gérer les acteurs uniquement sur les JDD

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#623]
Voir les discussions sur https://github.com/PnX-SI/GeoNature/issues/621

- Revoir la BDD pour ne pouvoir associer des acteurs qu'aux JDD et non plus aux CA
- Revoir le module METADONNEES pour ne pouvoir associer des acteurs qu'aux JDD. Sur la fiche d'un CA, afficher la somme des acteurs des JDD du CA.

Certainement à mûrir un peu avant de le faire.

**Comment by gildeluermoz** [comment]
Je laisserais comme c'est en base et dans l'admin pour le moment. C'est la traduction du standard. Il faudrait en causer avec le MNHN pour ne rien rater.
Une traduction du standard tel qu'il est pourrait être d'ampiler les acteurs JDD et CA dans une vue des acteurs des JDD. Ensuite on utilise cette vue pour le CRUVED.

**Comment by camillemonchicourt** [comment]
OK, réponse du MNHN : certains types d'acteurs sont recommandés au niveau du JDD et d'autres au niveau du CA : 

JDD : Producteur et Fournisseur
CA : Maître d'oeuvre, maître d'ouvrage et financeur

**Comment by gildeluermoz** [comment]
Il y a une certaine cohérence...
* A voir si on retien cette logique en contournant via une vue comme je proposait (faisabilité à creuser)
OU
* si on vire les acteurs des CA et que l'on considère que ce n'est qu'une recommandation théorique que la mise en pratique dans GN serait contre porductive.

**Comment by DonovanMaillard** [comment]
Autre possibilité : Filtrer les nomenclatures du type d'acteur, pur qu'on puisse saisir les financeurs qu'au niveau du cadre, et les producteurs / fournisseurs qu'au niveau du jdd...

Ou encore, c'est peut être le plus ergonomique. Ne faire la saisie des acteurs que sur l'interface des JDD. Et qu'à l'arrivée, le cadre hérite des financeurs, maitres d'oeuvres et maitres d'ouvrages de l'ensemble de ses jeux... avec le bémol que l'utilisateur saura pas forcement que son financeur du jeu 1 ira sur le cadre d'acquisition qui comprend aussi les autres jeux, à voir.

**Comment by gildeluermoz** [comment]
Encore une fois, cela dépend de la logique de chacun. Pas facile de trouver une logique commune.
Il faut poser les différents cas et voir quelle est la solution le plus générique, même si elle provoque des contraintes ou des lourdeurs de saisie. 
Sinon il faut assumer des cas non gérés.

**Comment by camillemonchicourt** [comment]
Le fait de gérer les acteurs seulement au niveau des JDD n'est pas pertinent et pas d'actualité.
