### ISSUE TITLE
[OCCTAX] - Pointage par latitude / longitude

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#624]
Il était possible avant de saisir un point en inscrivant les coordonnées. Pourquoi la fonction a été supprimée ?

**Comment by camillemonchicourt** [comment]
Hum, je ne crois pas que cela soit volontaire.
@TheoLechemia ?

**Comment by TheoLechemia** [comment]
Si, on l'a supprimé. Il y a l'import GPS et GeoJson à la place.
Les deux sont peut-être utiles

**Comment by jbrieuclp** [comment]
Ben ouai pour saisir des données préalablement saisies sur un carnet c'est vachement bien !

**Comment by TheoLechemia** [comment]
Le composant est toujours là, il faut juste le remettre sur la carto Occtax.

**Comment by jbrieuclp** [comment]
Ok, j'va voir ça ! Je n'ai pas encore pris le temps de creuser la carto jusqu'à présent. C'en sera l'occaz !

**Comment by camillemonchicourt** [comment]
Ouais ça vaudrait de le remettre pour tous dans une prochaine version car c'est complémentaire.
Quitte à avoir 2 paramètres MAP pour afficher ou non les outils : 
- GPS_tool
- UPLOAD_tool

**Comment by TheoLechemia** [comment]
Voir ici pour l'exemple qui fonctionnait:
https://github.com/PnX-SI/GeoNature/blob/2.0.0-rc.2/contrib/occtax/frontend/app/occtax-map-form/occtax-map-form.component.html#L4

**Comment by jbrieuclp** [comment]
Yep ! C'est impec !
