### ISSUE TITLE
[OCCTAX] v_releve_list

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#627]
Quel est le projet pour cette table concernant les observateurs ? Les ids des utilisateurs doivent ils réintégrer cette table. Actuellement, la définition de la table sous sqlalchemy n'est plus en accord avec la def postgres de la table et du coup ça pète un peu partout.

**Comment by camillemonchicourt** [comment]
C'est une vue, envoyée au composant MapList du module Occtax pour lister les relevés : https://github.com/PnX-SI/GeoNature/blob/master/contrib/occtax/data/occtax.sql#L1048

**Comment by TheoLechemia** [comment]
La vue ne stocke pas les id. Coté sqlachemy, il y a une relationnship qui sert à récupérer un objet "User" utile pour le CRUVED. Il y a surement une optimisation à faire en effet car la jointure est faite deux fois.
Qu'est ce que tu veux dire "ça pète un peu partout" ? Tu peux fournir un exemple ?
Merci

**Comment by jbrieuclp** [comment]
Alley, la clé était là : data/migration/2.0.1to2.0.2.sql... Merci @TheoLechemia
