### ISSUE TITLE
Pour corriger le prob du passage du module occtax vers un autre.

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#629]
le "[matTooltip]" seul comme ça dans la balise <ng-template> fait planter le passage du module occtax à un autre module. Soit mettre un contenu d'infobulle [matTooltip]="plop" soit le supprimer.
https://github.com/PnX-SI/GeoNature/blob/6358f7e6c098e1661ae07ceb53a40475c65b533b/contrib/occtax/frontend/app/occtax-map-list/occtax-map-list.component.html#L139

**Comment by TheoLechemia** [comment]
Merci, corrigé.
