### ISSUE TITLE
import gpx sur occtax

### ISSUE THREAD

**Issue by ybuthion** [PnX-SI/GeoNature#631]
Je ne peux importer de points depuis un fichier gpx (pourtant en version 2.0.1)

- une erreur s'affiche lors de l'enregistrement du relevé : "Une erreur s'est produite"
- la console affiche : 
Failed to load resource: the server responded with a status of 403 (FORBIDDEN)
Http failure response for http://46.105.181.203/geonature/api/gn_commons/modules: 403 FORBIDDEN
e.handle
Error @ main.31fc31d89f86b8070a3d.bundle.js:1

ERROR 
e
error: "No token"headers: t {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}message: "Http failure response for http://46.105.181.203/geonature/api/gn_commons/modules: 403 FORBIDDEN"name: "HttpErrorResponse"ok: falsestatus: 403statusText: "FORBIDDEN"url: "http://46.105.181.203/geonature/api/gn_commons/modules"__proto__: Object
mt @ vendor.c1f540e102afbe2bdc3c.bundle.js:1

je ne vois pas d'où ça peut venir, sachant que cela fonctionnait en version 2.0.0

merci
(J'espère que j'ai bien fait de le poster sur le github)

**Comment by TheoLechemia** [comment]
Salut Yann,

L'erreur qui est dans la console n'est pas lié à l'import GPX.
Est-ce que tu peux envoyer l'ensemble du contenu du debugger ? Ou un capture d'écran?

Merci

**Comment by camillemonchicourt** [comment]
Je viens de tester sur http://demo.geonature.fr/geonature/#/occtax et n'ai pas eu de problème : 

![2019-05-occtax-gpx](https://user-images.githubusercontent.com/4418840/57275764-bc228280-709f-11e9-923f-99bc9e6b2f86.gif)

**Comment by ybuthion** [comment]
**voici le log de l'erreur :** 

Ouverture de http://46.105.181.203/geonature/#/occtax/form
Object { headers: {…}, status: 500, statusText: "INTERNAL SERVER ERROR", url: "http://46.105.181.203/geonature/api/occtax/releve", ok: false, name: "HttpErrorResponse", message: "Http failure response for http://46.105.181.203/geonature/api/occtax/releve: 500 INTERNAL SERVER ERROR", error: {…} }
main.31fc31d89f86b8070a3d.bundle.js:1:107515
Http failure response for http://46.105.181.203/geonature/api/occtax/releve: 500 INTERNAL SERVER ERROR main.31fc31d89f86b8070a3d.bundle.js:1:107674
    handleError http://46.105.181.203/geonature/main.31fc31d89f86b8070a3d.bundle.js:1
    intercept http://46.105.181.203/geonature/main.31fc31d89f86b8070a3d.bundle.js:1
    error http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    u http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    invokeTask http://46.105.181.203/geonature/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
    onInvokeTask http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    invokeTask http://46.105.181.203/geonature/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
    runTask http://46.105.181.203/geonature/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
    invokeTask http://46.105.181.203/geonature/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
    k http://46.105.181.203/geonature/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
    _ http://46.105.181.203/geonature/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
internal server error 1.362f4c8a7150224bd4f9.chunk.js:1:34310
    submitData http://46.105.181.203/geonature/1.362f4c8a7150224bd4f9.chunk.js:1
    __tryOrUnsub http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    error http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    _error http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    error http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    _error http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    error http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    _error http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    error http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    notifyError http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    _error http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    error http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    notifyError http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    _error http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    error http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    _subscribe http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    _trySubscribe http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    subscribe http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    a http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    error http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    u http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    invokeTask http://46.105.181.203/geonature/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
    onInvokeTask http://46.105.181.203/geonature/vendor.c1f540e102afbe2bdc3c.bundle.js:1
    invokeTask http://46.105.181.203/geonature/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
    runTask http://46.105.181.203/geonature/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
    invokeTask http://46.105.181.203/geonature/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
    k http://46.105.181.203/geonature/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
    _ http://46.105.181.203/geonature/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1

merci

**Comment by camillemonchicourt** [comment]
Je suis pas sur que le problème vienne de l'import d'un GPX. Je laisse @TheoLechemia dire ça.

Par contre, en passant, je vois 2 problèmes : 
- Quand on clique sur l'outil pour ouvrir un fichier, ça pose un point derrière le bouton
- Quand on sélectionne un des points du fichier GPX, cela ne calcule pas son altitude

**Comment by TheoLechemia** [comment]
Oui l'erreur que tu remonte est une erreur de l'API lors de interrogation des données d'Occtax.
Voir le fichier "/home/<MON_USER>/geonature/var/log/gn_errors.log"

**Comment by camillemonchicourt** [comment]
Calcul altitude OK, c'était juste un peu long.

**Comment by ybuthion** [comment]
est ce que ça vous ennuie de tester depuis un de mes fichiers gpx pour être sûr que ça ne vienne pas de là quand même.
[fichier gpx](http://www.parc-du-vercors.fr/plugins/files/index.php?action=download&path=files/Telechargements_site_PNRV/tmp/stag7.gpx)
merci

**Comment by camillemonchicourt** [comment]
OK, il y a bien un soucis avec ton GPX en particulier. 
Celui-ci contient une info sur le Z qui pose problème lors de l'envoi de la géométrie. 
On va gérer ce cas du coup.

**Comment by ybuthion** [comment]
Chouette, z'êtes au top !
merci

**Comment by TheoLechemia** [comment]
C'est corrigé, merci pour le retour
