### ISSUE TITLE
OccTax : pouvoir enchainer la saisie de plusieurs relevés

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#633]
Bonjour, 

Dans le but de rendre le plus efficient possible la saisie d'observations dans le module Occtax, je pense qu'il serait plus rapide de pouvoir enchainer la saisie de plusieurs relevés au lieu d'être redirigé vers la page d'accueil du module Occtax systématiquement. 

Par exemple au lieu d'avoir un bouton Enregistrer le relevé, il pourrait y en avoir 2  :
 "Enregistrer le relevé et continuer à saisir" et "Enregistrer le relevé et revenir à la liste"

Dans le cas où l'on choisi la première option, il est important que la carte reste sur la zone du précédent relevé. (cf https://github.com/PnX-SI/GeoNature/issues/570 )

**Comment by camillemonchicourt** [comment]
Oui ça serait pratique de pouvoir enchaîner les relevés.

Sur le fait d'avoir 2 boutons, je reste partagé. 

Il y a ça sur Django-admin : 

![image](https://user-images.githubusercontent.com/4418840/57445455-adc89800-7252-11e9-9745-c2fc7dfd2c9a.png)

Et c'est aussi pratique que lourd. Ça fait autant gagner du temps que ça en fait perdre. 
Car à chaque fois que l'on doit Enregistrer une fiche, on doit bien réfléchir à quelle action on veut et pas se tromper de bouton.

**Comment by RomainBaghi** [comment]
Je viens de passer quelques heures à saisir des données, ce qui est lourd c'est de revenir sur la page d'accueil du module, de recliquer sur "ajouter un relevé", de rezoomer sur la même zone etc...etc...
Je préfère 10 boutons "enregistrer" différents que de devoir faire tout ça :)
Le fait de devoir retrouver sa zone d'observation sur la carte à chaque fois contribue beaucoup à la lourdeur de l'opération aussi.

**Comment by TheoLechemia** [comment]
On a trouvé un mécanisme qui plaire toute le monde !
![back_maplist](https://user-images.githubusercontent.com/15265745/57447531-9b049200-7257-11e9-8208-cd49a7c14482.png)
Il y a un petit bouton slider au niveau du relevé qui contrôle le fait de retourner à l'interface carte/liste ou d'enchaîner les relevés.
On réfléchit aussi à garder certaines valeurs (JDD, observateur, nomenclatures). Est-ce que ça vous parait judicieux ?

**Comment by RomainBaghi** [comment]
à première vue cela me parait très bien et pour l'instant la seule inquiétude que j'ai c'est de savoir ce qui se passe si l'on clique sur le slider alors qu'on a un relevé en cours qui n'est pas encore enregistré.
Cela rejoins mon ticket : https://github.com/PnX-SI/GeoNature/issues/578
sur le fait d'avoir un popup(ou autre) de confirmation avant de quitter un relevé en cours.

**Comment by camillemonchicourt** [comment]
A décaler à droite sur le même ligne et à associer à une icone du genre https://fontawesome.com/icons/sync?style=solid ou plutôt https://fontawesome.com/icons/redo?style=solid

Le slider ne change rien au relevé en cours. Il influe juste sur le fonctionnement du bouton ENREGISTRER. 
Du coup quand on est en mode "Enchaînement de relevés", on propose de garder pas mal de valeurs du relevé précédent (JDD, observateurs, date, nomenclatures...) d'un relevé à l'autre. 
Cela en lien avec les tickets https://github.com/PnX-SI/GeoNature/issues/475 et https://github.com/PnX-SI/GeoNature/issues/280
Sur le principe que quand on veut enchaîner les relevés, plusieurs valeurs restent les mêmes d'un relevé à l'autre, et si c'est pas le cas, alors on modifie que celles qui sont différentes. 

Du coup, plus besoin de verrous par champs, ni de duplication de relevés. 

Bien plus simple et propre.

**Comment by RomainBaghi** [comment]
Ok, je comprends mieux et du coup je trouve ça encore plus chouette, surtout si l'on peut répondre à ces besoins identifiés précédemment. 
Effectivement quand j'enchaine les relevés, c'est typiquement sur la même journée de terrain (même date), avec les mêmes observateurs, pour le même projet(=jdd),  souvent le même commentaire de relevé ou je parle des conditions météo etc...

**Comment by TheoLechemia** [comment]
C'est OK.
L'ensemble des infos du niveau "relevé" sont conservés.

**Comment by DonovanMaillard** [comment]
En effet, une solution pour conserver un certain nombre de champs et pouvoir enchainer les relevés sur une même zone. 

Pour être vraiment pénible mais apporter une meilleure souplesse je trouve, est-ce qu'il est lourd de mettre en place un paramètre pour définir les champs "figés" dans le mode à la volée? Par exemple le commentaire, s'il concerne le milieu ou la localisation, ne devrait pas être conservé... et ça dépend des habitudes de l'utilisateur/de la structure. 

Si c'est lourd à développer, on fera avec, ça répond de toutes manière à la plupart des besoins soulevés jusqu'à maintenant sur cette question,

**Comment by camillemonchicourt** [comment]
On n'a pas prévu de paramètre par champs. 
Par contre on ne récupère pas la géométrie du relevé précédent, et on va retirer la récupération du commentaire du relevé précédent. 
Car globalement, autre relevé = autre contexte = autre commentaire relevé

**Comment by camillemonchicourt** [comment]
Fait dans la 2.1.0
