### ISSUE TITLE
Problème affichage info et modification de releve

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#641]
Comme indiqué dans le titre, les modifs de relevé ou l'affichage des infos depuis l’accueil occtax ne fonctionne plus. On revient constamment sur cette accueil occtax. 
Il y a le petit "s" (ref dessous) manquant au nom de la table qui peut être accusé de mettre la zone.
https://github.com/PnX-SI/GeoNature/blob/c4acd8a934ce546a1ad326617878438b0ede2159/backend/geonature/core/gn_commons/models.py#L95-L99

Par contre je suis peut-être en avance sur les commits, mais dans le script de migration [2.0.1 > 2.1.0](https://github.com/PnX-SI/GeoNature/blob/develop/data/migrations/2.0.1to2.1.0.sq) il manque le creation de cette vue v_latest_validationS
https://github.com/PnX-SI/GeoNature/blob/c4acd8a934ce546a1ad326617878438b0ede2159/data/migrations/2.0.1to2.1.0.sql#L225-L229

A moins que le _for_web_app soit en trop ?

**Comment by camillemonchicourt** [comment]
OK donc tu parles de la branche ``develop``actuelle. 
En effet @TheoLechemia est en train d'intégrer le module Validation dans le cœur de GeoNature et du coup il a commencé à faire du ménage entre les vues existantes et routes en doublon entre celles qui étaient déjà dans le cœur de GN et celles qui avaient été ajoutées dans le module. 
C'est peut-être pas encore tout nickel.

Je crois que le nom correct de la vue à terme est ``v_latest_validations``.

**Comment by jbrieuclp** [comment]
Oui, la vue postgres est bien v_latest_validations, mais le model du backend est toujours configuré pour aller taper sur la vue v__latest_validation, sans S. D'où ce "s" qui met la zone. Il y a eu une grosse modif sur ce model dans le dernier commit, mais le nom de la table est resté sur l'ancien nom, donc c'est plus au cas où le nom était passé à la trappe.

**Comment by camillemonchicourt** [comment]
OK je vois. 
Maintenant que plusieurs personnes collaborent sur la base de la branche ``develop``, il faut donc que l'on travaille plus par branche. Ce genre d'évolution mériterait d'être travaillé dans une branche dédiée.

**Comment by TheoLechemia** [comment]
C'est corrigé dans le script 2.0.1to2.1.0.sql

**Comment by jbrieuclp** [comment]
Du coup les vues **gn_commons.v_validation** ou **gn_commons.v_validations** n'existent plus. Seule **gn_commons.v_validations_for_web_app** est utilisée ?

**Comment by TheoLechemia** [comment]
Il reste **gn_commons.v_latest_validations_for_web_app** et **gn_commons.v_validations_for_web_app**
