### ISSUE TITLE
modifications de multipolygons impossibles

### ISSUE THREAD

**Issue by stipnrb** [PnX-SI/GeoNature#643]
Si on importe un geojson contenant un multipolygon dans occtax, ça marche et on peux enregistrer le relevé, mais lorsqu'on essaye de l'éditer après (si on a fait une erreur sur la date ou que l'on veux rajouter un taxon), il charge juste indéfiniment.

**Comment by camillemonchicourt** [comment]
Des évolutions viennent d'être apportées au niveau de l'affichage des géométries multiples et la fonctionnalité sera disponible dans la prochaine version. 
Mais pas testé dans Occtax en effet car la saisie d'objets multiples n'est pas possible actuellement. 
Mais en effet par un import GeoJSON c'est possible donc à corriger.

**Comment by TheoLechemia** [comment]
C'est corrigé : https://github.com/PnX-SI/GeoNature/commit/f9140649fd09da82acc338283b23dcf0c45ee150
