### ISSUE TITLE
OccTax / simplifier la liste des taxons

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#644]
Bonjour, 

J'essaye de simplifier les résultats de la recherche de taxons dans occtax et je me demande comment faire. 
Ci-dessous un exemple de résultat. J'ai l'impression que pour chaque taxon il y a un doublon : "nom latin : nom latin" et "nom français : nom latin".

Je vois dans ma bdd qu'il y a deux fonctions qui remplissent/mettent à jour la table vm_taxref_list_forautocomplete.
Ces fonctions sont : 
- trg_fct_refresh_mv_taxref_list_forautocomplete() (appelée par le trigger de la table cor_nom_liste)
- trg_fct_refresh_nomfrancais_mv_taxref_list_forautocomplete (appelée par le trigger de la table bib_noms)

Je me demande si ce 'nest pas un reste d'une version antérieure et qu'il ne devrait y avoir qu'un seul de ces mécanismes ?
 
![search_taxon_occtax](https://user-images.githubusercontent.com/8653849/57950508-bd498000-78e7-11e9-81bf-6ccb4f8f0c3a.png)

**Comment by camillemonchicourt** [comment]
Je n'ai plus la raison en tête mais c'est normal.

Et sur la recherche plus d'infos ici : https://si.ecrins-parcnational.com/blog/2019-01-fuzzy-search-taxons.html

**Comment by DonovanMaillard** [comment]
Bonjour, ce sont en effet 4 synonymes... pas besoin, dans ce cas, de rentrer les 4 dans la liste "saisie occtax", mais ne laisser que Podarcis muralis qui semble le nom valide. En les gardant dans la base, mais en les supprimant de la liste, ca simplifiera la saisie.

**Comment by DonovanMaillard** [comment]
D'ailleurs de manière générale, chez nous je suis parti du principe que occtax set à saisir des données actuelles, et donc j'ai jugé qu'il était pertinent de ne saisir que des noms actuellement valides.avec une requête SQL on peut donc facilement trier et supprimer tous les noms de la saisie dès lors que cd_nom != cd_ref.

**Comment by TheoLechemia** [comment]
En supprimant les synonymes tu aura toujours le doublon:
nom_français = nom_valide
lb_nom = nom_valide
La requête SQL construisant la table "vm_taxons_for_autocomplete" est faite comme ça. ça permet de rechercher à la fois sur le nom vernaculaire et le nom scientifique (regarde ici: https://github.com/PnX-SI/TaxHub/blob/master/data/taxhubdb.sql#L702)
Avant on ne cherchait que sur le début du taxon, donc si tu tapais "podarcis muralis", tu n'avais que la ligne "nom_latin=nom_valide" qui ressortais, mais c'était génant sur certains groupes ou les gens tapent le genre en 1er (@DonovanMaillard m'avait fait remonté ça via Yann il me semble).

Et pour les triggers, c'est normal qu'il y'en ai deux. Celui sur "cor_nom_list" en cas d'ajout ou de suppression dans une liste, et celui sur "bib_nom" si tu modifie le "nom_francais". NB, c'est bien le "nom_francais" de la table "bib_noms" qui est utilisé et nom le "nom_vern" de taxref, ce qui permet de se "customiser/simplifier" les noms vernaculaires (rajouter une dénomination locale, simplifier le nom_vernaculaire qui est parfois très long)

**Comment by DonovanMaillard** [comment]
Oui il y aura toujours ce doublon mais il a 3 noms latins synonymes dans ce cas, il peut économiser la moitié de sa liste ;)

**Comment by camillemonchicourt** [comment]
Oui le principe des listes gérées au niveau de TaxHub permet de choisir ce qu'on veut proposer à la saisie ou non

**Comment by RomainBaghi** [comment]
Bonjour, 

Merci pour vos retours, je comprends mieux maintenant ce qu'il y a derrière ce résultat.
Dans ce cas les taxons proposés (espèce et sous-espèces) ont étés volontairement ajoutés à la liste de saisie, il ne s'agit pas de synonymes pour nos spécialistes.

En fait, en tapant "Podarcis muralis muralis" je pensais qu'il éliminerait l'espèce et qu'il ne garderait que la sous espèce. Mais ce n'est pas très embêtant.

Par contre, si dans la table de recherche, j'élimine les lignes "lb_nom = nom_valide" et que je ne garde que les lignes "nom_français = nom_valide" (là ou le nom français existe). 
Je vais en fait dégrader la pertinence des résultats de l'algorithme ?
J'ai envie de faire ça car le lb_nom et le nom_valide sont toujours les mêmes donc en ne gardant que la ligne "nom_français = nom_valide" on a toutes les infos.

Je sais pas si je suis clair...

**Comment by DonovanMaillard** [comment]
Je te conseille d'ignorer les noms, ce qui compte c'est les CD. En clair si tu as 3 CD nom qui pointent sur un même cf réf, et je crois que c'est ton cas ici, t'es gardes saisissent la même chose en pensant saisir des trucs différents, car derrière ces 3 CD noms se cachent une même entité biologique (CD réf).

Dans ce cas même si les nom sont différents, si le CD réf est le même, ça veut dire que tous ces noms differents ont été reconnus comme des synonymes désignant un seuk et même taxon

**Comment by RomainBaghi** [comment]
Non non, ce sont bien des taxons à part entière avec un cd_ref propre à chacun.

Mais ce n'est pas le sujet ici, ce que je questionne c'est le doublon : 
nom_français = nom_valide
lb_nom = nom_valide

**Comment by TheoLechemia** [comment]
lb_nom = nom_valide ne sont égaux que si il s'agit d'un taxon de réference (cd_nom=cd_ref)

> Je vais en fait dégrader la pertinence des résultats de l'algorithme ?

En faisant ça tu vas dégradé la recherche sur les synonymes oui.

**Comment by RomainBaghi** [comment]
Ok, alors dans mon cas comme je n'utilise que les noms valides cela ne me pose pas de problèmes et je peux donc éliminer ce doublon sans perte de performance sur les résultats.

**Comment by TheoLechemia** [comment]
Le fonctionnement actuel semble le meilleur compromis.
En supprimant les lignes lb_nom = nom_valide on se prive de la recherche sur les synonymes
