### ISSUE TITLE
Import Geojson dans occtax

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#647]
Bonjour, 

Peut être lié à #631 , mais pas sur. 

On a un fichier geojson, bien projeté, à priori sans variable z mais je n'en suis pas sur (qgis me dit qu'automatiquement il n'exporte pas le z). 

Quand je fais une saisie, je charge le json, ca passe. Je note mes occurrences, je valide, tout est ok. En revanche, je ne peux pas éditer le relevé car GN n'arrive pas à charger la géométrie. 

De la même manière, la synthèse ne s'ouvre plus, ça tourne en rond... j'imagine que le problème est le même, il ne trouverait pas la géométrie... je vais aller vérifier. 

En tous cas le déboggeur coté occtax, quand j'update la donnée avec cette géométrie, me renvoie ça = 

> 
> ERROR TypeError: "t is undefined"
>     loadDrawfromGeoJson https://geonature.flavia-ape.fr/main.955b1d5af23b11f6a559.bundle.js:1
>     ngOnChanges https://geonature.flavia-ape.fr/main.955b1d5af23b11f6a559.bundle.js:1
>     zo https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     zo https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     zo https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     hs https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     View_e_0 ng:///e/e.ngfactory.js:68
>     updateDirectives https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     Bo https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     $o https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     Zo https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     Bo https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     $o https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     Xo https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     Bo https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     $o https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     Zo https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     Bo https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     $o https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     Xo https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     Bo https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     $o https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     Zo https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     Bo https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     detectChanges https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     tick https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     tick https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     next https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     invoke https://geonature.flavia-ape.fr/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
>     onInvoke https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     invoke https://geonature.flavia-ape.fr/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
>     run https://geonature.flavia-ape.fr/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
>     run https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     next https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     r https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     __tryOrUnsub https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     next https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     _next https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     next https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     next https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     emit https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     Re https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     Ae https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     onInvokeTask https://geonature.flavia-ape.fr/vendor.c1f540e102afbe2bdc3c.bundle.js:1
>     invokeTask https://geonature.flavia-ape.fr/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
>     runTask https://geonature.flavia-ape.fr/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
>     invokeTask https://geonature.flavia-ape.fr/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
>     k https://geonature.flavia-ape.fr/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
>     _ https://geonature.flavia-ape.fr/polyfills.8e6e0bba10da36e1f3ae.bundle.js:1
> vendor.c1f540e102afbe2bdc3c.bundle.js:1:70764

**Comment by DonovanMaillard** [comment]
je précise que sur l'accueil d'occtax, quand je clique sur le relevé en question pour le sélectionner, ma géométrie s'affiche correctement.... mystère!

**Comment by TheoLechemia** [comment]
Est-ce que tu peux envoyer le geojson pour que je puisse tester ?
