### ISSUE TITLE
affichage des données en double/triple dans la synthese

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#651]
Bonjour, 

J'ai un souci avec le module synthèse et les observations saisies dans occtax.
En effet pour une observation saisie dans Occtax, elle apparaitra X fois dans le module synthese avec X étant le nombre d'observateurs. 
Dans la table gn_synthese.synthese, il n'y a bien qu'une seule ligne, donc le problème est au niveau de l'appli.

Problème connu ?

**Comment by camillemonchicourt** [comment]
Je viens de tester sur http://demo.geonature.fr/geonature/ et je ne reproduis pas.
J'ai créé une observation d'un taxon avec 3 observateurs dans Occtax. 
Et je n'ai bien qu'une seule ligne dans le module Synthèse.

**Comment by DonovanMaillard** [comment]
Pour simple info, je viens de regarder sur mon instance et je n'ai pas le soucis ;)

**Comment by DonovanMaillard** [comment]
Je reviens par ici : Yann a constaté le problème mais sur occtax, pas sur le module synthèse : Quand un relevé a 2 observateurs, chaque taxon y est répété 2 fois sur le module occtax. 

A priori dans la synthèse elles ne sont bien renvoyées qu'une fois... 

![0](https://user-images.githubusercontent.com/23358384/59849289-7f68cd00-9367-11e9-9b90-9c4ec6f16a50.png)

**Comment by DonovanMaillard** [comment]
Au passage, ca renvoit au sujet d'avoir un scroll sur la liste pour les relevés importants ;)

**Comment by TheoLechemia** [comment]
Je ne reproduit pas ni en local ni sur démo.
Est-ce que vous pouvez me préciser le CRUVED Occtax des compte avec lesquels vous avez eu le soucis.

Merci

**Comment by DonovanMaillard** [comment]
Je laisse @RomainBaghi  te répondre, pour ma part je n'ai pas réussi à reproduire le soucis. Yann l'a rencontré, mais sur le même relevé que lui avec les mêmes droits je n'ai pas observé ça...

**Comment by camillemonchicourt** [comment]
A priori il s'agit de ce problème réglé ici : https://github.com/PnX-SI/GeoNature/commit/4973c60cec61b0d4b8fc52d35e3a697d7fa05ac4

**Comment by jbrieuclp** [comment]
Pour moi c'est la requête de la vue v_releve_list et plus particulièrement l’absence d'un distinct pour les taxons `string_agg(t.nom_valide::text, ','::text) AS taxons,` VS `string_agg(DISTINCT t.nom_valide::text, ','::text) AS taxons,` et idem pour l'infobulle. Correction général de cette vue ici #690 (en base de post)

**Comment by TheoLechemia** [comment]
C'était un problème de requête SQL. Corrigé au commit que Camille indique.
Pour Occtax c'est égalemen corrigé.
Je ferme
