### ISSUE TITLE
[Frontend code] : [defaultToday] présent 2 fois

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#658]
https://github.com/PnX-SI/GeoNature/blob/bab3dba6e2259933719de5d0e67dbfd579aa38ae/contrib/occtax/frontend/app/occtax-map-form/form/releve/releve.component.html#L34

Au passage, est-ce que je continue de faire des issues de ce type quand je vois des p'tits bugs comme çà ou vous préférez que je me fasse une branch spécifique en PR ?

**Comment by TheoLechemia** [comment]
Merci.
C'est toujours bien d'ouvrir un ticket pour le suivi et l'historique d'un bug. Après sur un petit truc comme ça, branche + PR ça peut être un peu lourd. On le corrige dans la foulée.

**Comment by TheoLechemia** [comment]
Corrigé: https://github.com/PnX-SI/GeoNature/commit/cfed787a784c8bf5664f2ec70d5e17648dcc0536
