### ISSUE TITLE
Module Métadonnées - listes déroulantes Type de role 

### ISSUE THREAD

**Issue by Eric-a-BRUNO** [PnX-SI/GeoNature#661]
Bonjour,
Sur une installation V 2.0.1 les listes déroulantes 'Type de rôle' lorsque l'on essai de créer une fiche pour un nouveau CA ou un nouveau JDD sont vides sous Windows (testé sur W7-32 bits et sur W10-64bits). Elles fonctionnent parfaitement depuis une session debian9. Avez-vous une idée de l'origine de ce problème ?
Merci

**Comment by TheoLechemia** [comment]
Bonjour,

Pouvez-vous nous dire sur quel navigateur web vous avez fait ces tests (version etc..)? Il s'agit surement d'un problème de navigateur plutôt que d'OS. 
Est-t-il possible d'avoir une capture d'écran du débogueur du navigateur ?
Est-ce que les autres listes déroulantes fonctionnent ? (Y compris dans Occtax par exemple)

**Comment by Eric-a-BRUNO** [comment]
Navigateur : Firefox Quantum 60.6.3 esr (32 bits)
![image](https://user-images.githubusercontent.com/51153829/59278944-552a5780-8c63-11e9-8c55-b4cacd59fe0e.png)

J'ai le même pb avec Google chrome Version 74.0.3729.169 (Build officiel) (32 bits) tjr sous W7-32bits

capture débogueur ??? c'est cela :  
![image](https://user-images.githubusercontent.com/51153829/59279568-6fb10080-8c64-11e9-8498-0eb21f1820ec.png)

Oui les autres listes semblent fonctionner : 
![image](https://user-images.githubusercontent.com/51153829/59279724-c0285e00-8c64-11e9-9ced-0b5250197cc9.png)

ou 
![image](https://user-images.githubusercontent.com/51153829/59279847-f1089300-8c64-11e9-9e30-b317e1059d49.png)

**Comment by camillemonchicourt** [comment]
Je ne reproduis pas avec Windows, sur le serveur de démo (http://demo.geonature.fr/geonature/ admin / admin).
Pour le débogueur il faudrait les éventuels messages d'erreur dans la partie CONSOLE.

**Comment by TheoLechemia** [comment]
> capture débogueur ??? c'est cela : 

C'est ça, mais sur l'onglet "console". 

Sinon est-ce qu'on peut se connecter à votre instance ? j'imagine qu'elle est encore en test ?

**Comment by camillemonchicourt** [comment]
Il semblerait que le blocage était lié à un contrôle d'accès local du réseau.
