### ISSUE TITLE
[Synthèse] Erreur sur ouverture du filtre taxons avancé

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoNature#664]
Salut à tous,
Suite à mise à jour en 2.1.0, le filtre avancé sur les taxons de la synthèse ne s'ouvre plus et lève une erreur.
Même comportement et même erreur sur l'instance de démo.
Une idée ?

Voici ce que cela donne dans la console navigateur : 
![image](https://user-images.githubusercontent.com/16793813/59411884-92eec380-8dbc-11e9-988a-1c49eec5edc2.png)

**Comment by camillemonchicourt** [comment]
Je crois que @jbrieuclp a identifié et corrigé ça quelque part depuis mais je m'embrouille peut-etre

**Comment by jbrieuclp** [comment]
Normalement c'est cette issue : [](https://github.com/PnX-SI/GeoNature/issues/628)

**Comment by xavyeah39** [comment]
OK merci messieurs.
Identifié donc mais pas encore corrigé c'est ça ?

**Comment by jbrieuclp** [comment]
Ok, j'me suis emballé... En fait j'avais déjà publié une PR de correction [#646](https://github.com/PnX-SI/GeoNature/pull/646)
Pour le détail des modifs c'est [ce commit](https://github.com/PnX-SI/GeoNature/pull/646/commits/1388db9e70101f0f98d17611b6aa06e65a97cb64)

**Comment by xavyeah39** [comment]
Ok cool. 
Ca fonctionne en appliquant ton commit et en laissant les arguments dans la fonction de :
GeoNature/frontend/src/app/syntheseModule/synthese-search/synthese-search.component.html
Merci !

**Comment by TheoLechemia** [comment]
Mes excuses. ça été mal testé de notre côté.
C'est corrigé.
