### ISSUE TITLE
[Métadonnées] Problème de CSS sur affichage des JDD

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoNature#667]
Suite à révision de l'interface du module métadonnée dans la version 2.1.0, il me semble qu'il manque une classe CSS sur les intitulés des jeux de données listées sous les cadres d'acquisitions. 
Le texte hérite donc de la couleur de la classe `mat-list-item-content` (utilisée aussi pour la liste des module dans le menu de navigation de gauche) et du coup, le texte est blanc sur fond blanc.
Corrigé provisoirement sur notre instance en ajoutant une classe CSS dans la balise `<span>` du template `metadata.component.html` et dans le CSS correspondant.

**Comment by TheoLechemia** [comment]
C'est lié à ta surcouche CSS. 

Tu as dû ajouter cette règle dans ton custom.css:
```
.mat-list-item-content {
   color: white;
   font-weight: bold !important;
}
```
Du coup, ça applique cette règle sur tous les composants `mat-list-item` (celui de la sidebar mais aussi celui des métadonnées).
Pour n'appliquer le style que sur ta sidebar, utilise ce selecteur: `.sidenav-item.mat-list-item .mat-list-item-content `

**Comment by xavyeah39** [comment]
Ok. Je vérifie dès que je peux mais de mémoire, le seul surcouchage de `mat-list-item` que j'ai fais n'est pas sur la couleur de texte. En tout cas, le soucis est présent aussi sur votre instance de démo.

**Comment by xavyeah39** [comment]
Effectivement j'étais passé à côté... J'avais bien une surcouche de couleur sur `mat-list-item-content` sans préciser `.sidenav-item.mat-list-item` dans le sélecteur. J'ai regardé un peu vite en voyant qu'il en était de même sur demo.geonature.fr.  Merci.
