### ISSUE TITLE
Multipolygones dans les syntheses

### ISSUE THREAD

**Issue by jbdesbas** [PnX-SI/GeoNature#668]
Bonjour à tous,

Parvenez-vous à afficher des multi-polygones dans la synthèse ?
Quand des données sur des multipolygones sortent dans la synthèse, le frontend plante systématiquement (la console donne : _ERROR TypeError: "t is undefined"_  ou _ERROR Error: "Invalid LatLng object:_ )

J'ai vérifier, pas de problème de géométries invalides. Le json renvoyé par l'API ("for_web") semble OK également.

**Comment by jbdesbas** [comment]
J'ai été un peu vite, il semble que ca soit régler #609

**Comment by camillemonchicourt** [comment]
Oui, normalement corrigé dans la 2.1.0.

**Comment by jbdesbas** [comment]
> Oui, normalement corrigé dans la 2.1.0.

Je viens de passer à la 2.1.0 et je confirme :heavy_check_mark: 
Beau travail
