### ISSUE TITLE
[occtax] bug : slider "enchaîner les relevés" et modification

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#669]
Quand on fait une modification d'un relevé et qu'on active au passage le slider enchaîner les relevés, on boucle sur le même relevé. Du coup on modifie en boucle le même relevé = suppression des observations saisies préalablement + ajout d'un nouveau d'observation en BD.

Donc il faudrait désactiver cette option en mode modification de relevé. Ce qui est d'ailleurs plus logique, on a à pas à devoir enchaîner une saisie alors qu'on fait une modification ponctuelle.

Un petit *ngIf avec l'identifiant du relevé doit faire le taf.

**Comment by camillemonchicourt** [comment]
Bien vu.

**Comment by TheoLechemia** [comment]
Corrigé
