### ISSUE TITLE
Non prise en compte du paramètre DATE_FORM_WITH_TODAY

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#670]
En lien avec [#658](https://github.com/PnX-SI/GeoNature/issues/658) [defaultToday] prend "true" en dur au lieu de "occtaxConfig.DATE_FORM_WITH_TODAY". C'est volontaire ou c'est le mauvais qui a sauté ?

https://github.com/PnX-SI/GeoNature/blob/b8983b1c0800c631440ccd4412cfd34bfaf46998/contrib/occtax/frontend/app/occtax-map-form/form/releve/releve.component.html#L34

**Comment by TheoLechemia** [comment]
Corrigé, merci
