### ISSUE TITLE
Frontend package.json : version @angular/common ?

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#671]
Version 43.0 d'indiquée au lieu de 4.3.0. J'ai pas testé l'instal, mais pas dit que ça se passe bien.
https://github.com/PnX-SI/GeoNature/blob/b8983b1c0800c631440ccd4412cfd34bfaf46998/frontend/package.json#L20

**Comment by camillemonchicourt** [comment]
Fix : https://github.com/PnX-SI/GeoNature/commit/4949a3d6813b236a8223797c38fa47564a648b9a
