### ISSUE TITLE
Documentation / Amélioration et automatisation API et Frontend

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#673]
Jusqu'à présent la documentation de GeoNature était entièrement manuelle et accessible sur https://geonature.readthedocs.io

La partie documentant l'API et les composants Frontend était manuelle aussi donc difficilement à jour. 

@TheoLechemia a amélioré cela pour que ces parties soient générés automatiquement. Les docstring présents dans le code génèrent automatiquement cette documentation et reste ainsi à jour. 

Pour cela, on utilise Sphinx (plus un petit plugin pour la génération de la doc sur les routes) pour la backend et compodoc pour le front.

Le tout est couplé à Travis, l'outil utilisé pour les tests d'intégration continue. A chaque commit dans la branche ``master``, Travis lance la batterie de test et regénère la documentation à partir du nouveau code puis la pousse automatiquement dans la branche dédiée ``gh-pages``. ReadTheDocs n'était pas capable de faire cela, donc on doit l'abandonner au profit des pages GitHub Pages, branchées sur Travis.

Ainsi à partir de la prochaine version de GeoNature, sa documentation sera accessible à l'adresse http://docs.geonature.fr

Voilà la partie de la doc générée pour l'API backend : http://docs.geonature.fr/development.html#documentation-api-backend
et pour les composants Frontend : http://docs.geonature.fr/frontend/modules.html

Cela nécessite une certaine rigueur dans l'écriture des docstring.
En python il faut les écrire en RST en respectant les balises du plugin Sphinx-httpdoc. Voir les exemple déjà écrits (ici dans occtax, un exemple un peu compliqué mais complet : https://github.com/PnX-SI/GeoNature/blob/master/contrib/occtax/backend/blueprint.py#L213). NB le ``.. :quickref: Occtax;`` permet de regrouper les routes par "catégorie" dans la doc.
Côté front, c'est un peu plus simple, il suffit de mettre une "jsdoc" au dessus de l’élément que l'on veut documenter (un composant, un input) etc...

Les commits correspondants sont consultables ici : https://github.com/PnX-SI/GeoNature/compare/83abf47...ef91706

**Comment by dthonon** [comment]
Il est aussi possible d'écrire la documentation python dans un style plus simple, sans passer par RST. Voir le plugin https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html.
Je peux tester et faire une PR, si vous êtes intéressés.

**Comment by TheoLechemia** [comment]
Bien volontiers !

**Comment by TheoLechemia** [comment]
Je viens d'essayer rapidement, mais je n'arrive pas à avoir un résultat satisfaisant.

Ma docstring numpy:

    Return synthese and t_validations data filtered by form params
    Params must have same synthese fields names

    .. :quickref: Validation;

    Parameters:
    ------------
    info_role (User): 
        Information about the user asking the route. Auto add with kwargs
    truc (int): 
        essai
    

    Returns
    -------
    dict
        test

Le résultat:
![numpy](https://user-images.githubusercontent.com/15265745/59831175-8d0b5c00-9341-11e9-99e1-e58519e2c6e7.png)

On ne retrouve pas les intitulés "parameters" et "return". 

Pareil avec le "google style".

Mon conf.py ressemble à ça:
```
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinx.ext.autodoc",
    "sphinxcontrib.httpdomain",
    "sphinxcontrib.autohttp.flask",
    "sphinxcontrib.autohttp.flaskqref",
    "sphinx.ext.napoleon",
]

napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
```

Par contre je lance la génération de la doc avec la commande `make html` (qui elle même lance la commande autodoc: https://github.com/PnX-SI/GeoNature/blob/master/docs/development.rst#liste-des-routes) et non `sphinx-apidoc -f -o docs/source projectdir` comme indiqué dans ta doc.

Tu as une idée ?

**Comment by dthonon** [comment]
Bonjour,
Le docstring à l'air correct. Il faut que je creuse le conf.py. En
attendant, voir
https://client-api-vn1.readthedocs.io/en/develop/api/export_vn.html#export_vn.biolovision_api.ObservationsAPI
pour un exemple.
Daniel

Le jeu. 20 juin 2019 à 10:01, Théo Lechémia <notifications@github.com> a
écrit :

**Comment by dthonon** [comment]
Bonjour,
En fait, la documentation style NumPy ou Google, via sphinx.ext.napoleon,
fonctionne pour les modules python, donc très bien pour les classes et
fonctions. Mais je pense que sphinxcontrib.autohttp.flask ne reconnait pas
cette syntaxe.

On peut forcer l'execution de sphinx-apidoc depuis conf.py, mais ceci lève
des quantités d'erreur du fait des effets de bord lors de l'import des
modules (du genre sqlalchemy qui tente d'ouvrir la connexion à la BD).

Ce n'est donc pas faisable pour décrire l'API REST. A voir éventuellement
s'il faut décrire des API python par classes/foncions standard.

En passant, j'ai quand même supprimé quelques warnings dans la génération
de la doc. Je créerai un PR pour les publier

Daniel

Le jeu. 20 juin 2019 à 10:01, Théo Lechémia <notifications@github.com> a
écrit :

**Comment by TheoLechemia** [comment]
Oui en effet, on est obligé de passer une instance notre app Flask pour que sphinxcontrib.autohttp.flask gère tous les imports des modules. 
Merci pour le retour en tout cas

**Comment by dthonon** [comment]
Bonjour,

Je comprends un peu mieux comment documenter les routes Flask, car ce n'est
pas vraiment bien décrit et je ne connais pas Flask. J'ai encore des doutes
sur l'utilisation de :param:, qui devrait décrire la partie paramétrable de
l'URL mais qui est affiché comme paramètre de fonction Python. Sinon, les
champs principaux sont :

   - :qparam str nom_param: décrit le champs correspondant dans l'URL,
   après le ?
   - :>json type name: ou :>jsonarr type name: décrivent le JSON retourné

Note : il est important de séparer les directives (p. ex. ".. :quickref:")
par des lignes vides.

A titre d'exemple, j'ai repris la documentation de
'core/gn_synthese/routes.py', 'for_web' ainsi :
"""Optimized route to serve data for the frontend with all filters.

.. :quickref: Synthese; Get filtered observations

Query filtered by any filter, returning all the fields of the
view v_synthese_for_export::

properties = {
"id": r["id_synthese"],
"date_min": str(r["date_min"]),
"cd_nom": r["cd_nom"],
"nom_vern_or_lb_nom": r["nom_vern"] if r["nom_vern"] else r["lb_nom"],
"lb_nom": r["lb_nom"],
"dataset_name": r["dataset_name"],
"observers": r["observers"],
"url_source": r["url_source"],
"entity_source_pk_value": r["entity_source_pk_value"],
}
geojson = ast.literal_eval(r["st_asgeojson"])
geojson["properties"] = properties

:param str info_role: Role used to get the associated filters, **TBC**
:qparam str limit: Limit number of synthese returned. Defaults to
NB_MAX_OBS_MAP.
:qparam str cd_ref: Filter by TAXREF cd_ref attribute
:qparam str taxonomy_group2_inpn: Filter by TAXREF group2_inpn attribute
:qparam str taxonomy_id_hab: Filter by TAXREF id_habitat attribute
:qparam str taxonomy_lr: Filter by TAXREF cd_ref attribute
:qparam str taxhub_attribut*: Generig TAXREF filter, given attribute & value
:qparam str observers: Filter on observer
:qparam str id_organism: Filter on organism
:qparam str date_min: Start date
:qparam str date_max: End date
:qparam str id_acquisition_framework: *tbd*
:qparam str geoIntersection: Intersect with the geom send from the map
:qparam str period_start: *tbd*
:qparam str period_end: *tbd*
:qparam str area*: Generic filter on area
:qparam str *: Generic filter, given by colname & value
:>jsonarr array data: Array of synthese with geojson key
:>jsonarr int nb_total: Number of observations
:>jsonarr bool nb_obs_limited: Is number of observations capped
"""


Le résultat est visible ici
<http://srv12.daniel-thonon.net/development.html#get--synthese-for_web>

Si c'est bon pour vous, je publierai la PR et je continuerai ensuite, à
petite vitesse, à compléter la documentation du backend.

Cordialement
Daniel

Le ven. 21 juin 2019 à 09:25, Théo Lechémia <notifications@github.com> a
écrit :

**Comment by TheoLechemia** [comment]
Ok merci.
A noter que le paramètre GET peuvent s'écrire simplement avec la directive "query"
voir : http://docs.geonature.fr/development.html#get--occtax-vreleve et https://github.com/PnX-SI/GeoNature/blob/master/contrib/occtax/backend/blueprint.py#L213

On est bien-sûr preneur de toute PR qui complétera tout ça !
