### ISSUE TITLE
OccTax : Problème de récupération des géométries à l'update avec la saisie à la volée

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#677]
Bonjour, 

Un problème, un peu bizarre et difficile à diagnostiquer précisément... 

Je fais une saisie à la volée, avec un polygone
Je repars à l'accueil occtax
Je viens modifier mon relevé : la géométrie n'est pas récupérée..... des fois. J'ai reproduit le soucis sur le geonature de démo. 

Par dessus ce soucis là (lié, je ne le mets pas dans un ticket à part). Après avoir eu ce premier soucis, je fais "précédent" sur mon navigateur pour revenir à l'accueil d'occtax. Et toutes les bulles (observateurs, espèces) s'affichent au survol et ne disparaissent pas. Je peux donc avoir une vingtaine de bulles qui se superposent. Reproduit aussi sur la démo.

**Comment by TheoLechemia** [comment]
Lié à ce problème et corrigé : https://github.com/PnX-SI/GeoNature/issues/684
