### ISSUE TITLE
Synthèse : le bouton "avancé" de la taxonomie ne fonctionne plus

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#678]
Bonjour, 

Le bouton "avancé" dans l'onglet de requête "quoi" de la synthèse ne fonctionne plus. La page se grise et reste grisée. 

Reproduit sur le serveur de demo geonature.fr :)

**Comment by DonovanMaillard** [comment]
déjà traité : #628

**Comment by camillemonchicourt** [comment]
Oui détaillé ici aussi  https://github.com/PnX-SI/GeoNature/issues/664
