### ISSUE TITLE
Occtax : update des preuves d'existence à améliorer

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#679]
Dans l'action update d'une donnée/d'un relevé, les preuves d'existence ne peuvent pas être mises ) jour correctement. Si je mets "oui" et "en photo" dans les preuves, que je valide, et que je reviens dessus. Si je veux préciser le "en photo", il faut repasser la preuve sur non puis sur oui, sinon la cellule reste grisée. 

Pas bien grave, mais à noter dans les améliorations sans doute :)

**Comment by TheoLechemia** [comment]
Corrigé
