### ISSUE TITLE
Occtax / impossible de modifier un relevé dont la geometrie est une "polyline"

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#684]
Bonjour, 

Plusieurs utilisateurs m'ont fait remonté ce bug. 
En effet, dans occtax, les relevés dont la géométrie est un transect (polyline) ne peuvent pas être modifié.
Bug connu ?

merci

**Comment by TheoLechemia** [comment]
Merci.
Je viens de corriger le bug: https://github.com/PnX-SI/GeoNature/commit/a82860331f28f298096b8f74ca4dced8949f9f83

**Comment by RomainBaghi** [comment]
Super merci !
