### ISSUE TITLE
Restauration base de données

### ISSUE THREAD

**Issue by skerdreuxNaomis** [PnX-SI/GeoNature#689]
Bonjour,

Après avoir suivi la documentation sur la sauvegarde et restoration d'une base de données : 
http://docs.geonature.fr/admin-manual.html#restauration

j'obtiens systématiquement une erreur au moment de la restoration : 
`pg_restore: [programme d'archivage (db)] could not execute query: ERREUR:  la relation « spatial_ref_sys » n'existe pas
LIGNE 1 : SELECT proj4text FROM spatial_ref_sys WHERE srid = 2154 LIMI...
                                ^
REQUÊTE : SELECT proj4text FROM spatial_ref_sys WHERE srid = 2154 LIMIT 1
    La commande était : REFRESH MATERIALIZED VIEW cbnb_export;
`

or j'ai bien exécuté les commandes SQL pour rajouter les extensions et avant le lancement de la phase de restoration j'ai bien dans ma base de données vide la table "spatial_ref_sys"

Quelqu'un aurait déjà rencontré cette erreur ?

PS : Il s'agit d'une base de données V1

**Comment by jbrieuclp** [comment]
spatial_ref_sys est une table postgis, est-ce que l'extension Postgis a été activée sur la base ?

La commande devrait permettre de l'activer:
`CREATE EXTENSION postgis;`

**Comment by skerdreuxNaomis** [comment]
> spatial_ref_sys est une table postgis, est-ce que l'extension Postgis a été activée sur la base ?
> 
> La commande devrait permettre de l'activer:
> `CREATE EXTENSION postgis;`

oui justement j'ai bien lancé la commande
`CREATE EXTENSION IF NOT EXISTS postgis;`

et via psql avec un \dx sur la base j'ai bien l'extension postgis (v2.3.1) de présent sur la table

**Comment by jbrieuclp** [comment]
La table public.spatial_ref_sys est présente ?

Sinon peut être qu'il faut lancer manuellement (à l'ancienne) les scripts d'installation de postgis : http://postgis.refractions.net/documentation/manual-1.4/ch02.html
En utilisant des commandes de ce type :
```
psql -d yourdatabase -f postgis.sql
psql -d yourdatabase -f postgis_comments.sql
psql -d yourdatabase -f spatial_ref_sys.sql
```
En adaptant les paramètres des commandes psql, l'utilisateur entre autres.
Normalement ces fichiers sont dans le répertoire /usr/share/postgresql/{version}/contrib/postgis-2.3/

**Comment by camillemonchicourt** [comment]
Il faut se référer à la doc, mais @TheoLechemia a fait une migration récemment avec un partenaire et voici ce qu'ils ont noté : 

Après avoir mis à jour localement les tables de GeoNature (vers 1.9.2) ainsi que les schémas "utilisateurs" et "taxonomie" dans leurs dernières versions, on crée un backup de la BDD V1 qu'on va remonter sur le serveur où se trouve la BDD GeoNature 2.

- On recrée un backup en SQL (pour des questions compatibilité entre les versions de PG - on passe d'un v10 à une v9.6 ). Sinon faire un backup binaire ordinaire.

``sudo -n -u postgres pg_dump -Fp geonaturedb  > ./backup_1.x.sql``

- Créer un user qui correspond à l'utilisateur de geonature1 et tous les utilisateurs que la BDD geonature1 utilise

```
    sudo -n -u postgres -s psql -c "CREATE ROLE geonatuser WITH LOGIN PASSWORD 'password';"
    sudo -n -u postgres -s psql -c "CREATE ROLE myuser2 WITH LOGIN PASSWORD 'password';"
    sudo -n -u postgres -s psql -c "CREATE ROLE myuser3 WITH LOGIN PASSWORD 'password';"
```

- Recreer la base sur le serveur de prod 

``sudo -n -u postgres -s createdb -O geonatuser geonature1``

- Creer les extensions PostgreSQL

```
    sudo -n -u postgres -s psql -d geonature1 -c "CREATE EXTENSION IF NOT EXISTS postgis;"
    sudo -n -u postgres -s psql -d geonature1 -c "CREATE EXTENSION IF NOT EXISTS hstore;"
    sudo -n -u postgres -s psql -d geonature1 -c "CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog; COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';"
    sudo -n -u postgres -s psql -d geonature1 -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
    sudo -n -u postgres -s psql -d geonature1 -c "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
```

- Restaurer la BDD :

``psql -h localhost -U geonatuser -d geonature1 -f backup_prod_2.0.0.sql``

On va ensuite migrer les données de cette BDD v1 vers la BDD v2 installée avec le script ``install_all.sh``

**Comment by camillemonchicourt** [comment]
Donc vous avez surement un problème de version ou autre car ils ne semblent pas avoir rencontré ces erreurs.

**Comment by skerdreuxNaomis** [comment]
> La table public.spatial_ref_sys est présente ?
> 
> Sinon peut être qu'il faut lancer manuellement (à l'ancienne) les scripts d'installation de postgis : http://postgis.refractions.net/documentation/manual-1.4/ch02.html
> En utilisant des commandes de ce type :
> 
> ```
> psql -d yourdatabase -f postgis.sql
> psql -d yourdatabase -f postgis_comments.sql
> psql -d yourdatabase -f spatial_ref_sys.sql
> ```
> 
> En adaptant les paramètres des commandes psql, l'utilisateur entre autres.
> Normalement ces fichiers sont dans le répertoire /usr/share/postgresql/{version}/contrib/postgis-2.3/

oui la table est bien présente : 

```
geonature1=# \dt
               Liste des relations
 Schéma |       Nom       | Type  | Propriétaire
--------+-----------------+-------+--------------
 public | spatial_ref_sys | table | postgres
(1 ligne)

```

et pas de problème pour y effectuer des requêtes dont celles qui ne fonctionnent pas à la restauration : 
```
geonature1=# SELECT proj4text FROM spatial_ref_sys WHERE srid = 2154 LIMIT 1;
                                                             proj4text
------------------------------------------------------------------------------------------------------------------------------------
 +proj=lcc +lat_1=49 +lat_2=44 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
(1 ligne)

geonature1=#
```

> Il faut se référer à la doc, mais @TheoLechemia a fait une migration récemment avec un partenaire et voici ce qu'ils ont noté :
> 
> Après avoir mis à jour localement les tables de GeoNature (vers 1.9.2) ainsi que les schémas "utilisateurs" et "taxonomie" dans leurs dernières versions, on crée un backup de la BDD V1 qu'on va remonter sur le serveur où se trouve la BDD GeoNature 2.
> 
> * On recrée un backup en SQL (pour des questions compatibilité entre les versions de PG - on passe d'un v10 à une v9.6 ). Sinon faire un backup binaire ordinaire.
> 
> `sudo -n -u postgres pg_dump -Fp geonaturedb > ./backup_1.x.sql`
> 
> * Créer un user qui correspond à l'utilisateur de geonature1 et tous les utilisateurs que la BDD geonature1 utilise
> 
> ```
>     sudo -n -u postgres -s psql -c "CREATE ROLE geonatuser WITH LOGIN PASSWORD 'password';"
>     sudo -n -u postgres -s psql -c "CREATE ROLE myuser2 WITH LOGIN PASSWORD 'password';"
>     sudo -n -u postgres -s psql -c "CREATE ROLE myuser3 WITH LOGIN PASSWORD 'password';"
> ```
> 
> * Recreer la base sur le serveur de prod
> 
> `sudo -n -u postgres -s createdb -O geonatuser geonature1`
> 
> * Creer les extensions PostgreSQL
> 
> ```
>     sudo -n -u postgres -s psql -d geonature1 -c "CREATE EXTENSION IF NOT EXISTS postgis;"
>     sudo -n -u postgres -s psql -d geonature1 -c "CREATE EXTENSION IF NOT EXISTS hstore;"
>     sudo -n -u postgres -s psql -d geonature1 -c "CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog; COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';"
>     sudo -n -u postgres -s psql -d geonature1 -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
>     sudo -n -u postgres -s psql -d geonature1 -c "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
> ```
> 
> * Restaurer la BDD :
> 
> `psql -h localhost -U geonatuser -d geonature1 -f backup_prod_2.0.0.sql`
> 
> On va ensuite migrer les données de cette BDD v1 vers la BDD v2 installée avec le script `install_all.sh`

J'ai suivi cette procédure mais en éditant le fichier de backup j'ai remarqué que le search_path est souvent modifié et qu'il exclu le schéma public.
or la table spatial_ref_sys est dans ce schéma public.
Après les erreurs concernent des vues qui ne seront pas peuplés (exemples : MATERIALIZED VIEW DATA vm_synthese_ornitho_serena_geonature geonatuser). 
est-ce que ces vues sont essentielles au fonctionnement de geonature ?

**Comment by camillemonchicourt** [comment]
On n'a pas connaissance de ces vues ``vm_synthese_ornitho_serena_geonature`` car elles vous sont spécifiques et ont certainement été ajoutées en plus dans votre BDD.

**Comment by skerdreuxNaomis** [comment]
> On n'a pas connaissance de ces vues `vm_synthese_ornitho_serena_geonature` car elles vous sont spécifiques et ont certainement été ajoutées en plus dans votre BDD.

**Comment by skerdreuxNaomis** [comment]
Merci pour votre réponse !
je clos le ticket en conséquence

**Comment by camillemonchicourt** [comment]
Oui car j'avais pas bien regardé le message initial mais de la même manière le schéma ``cbnb_export`` n'existe pas dans GeoNature. Cela fait donc partie de vos ajouts à traiter spécifiquement.
