### ISSUE TITLE
[OccTax] Enchainer les taxons

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/GeoNature#692]
Je viens de faire ma première séance de grosse saisie "réelle" sur GeoNature v2.
Il s'agissait d'une chasse de nuit (Hétérocères), avec 71 taxons.
Comme il s'agissait à 100% de données de papillons adultes, il était à chaque fois nécessaire d'aller modifier le dénombrement pour préciser le stade de vie (imago).

Dans le même ordre d'idée de ce qui a été fait pour l'enchainement des relevés (#633), je me suis dit qu'il serait possible d'optimiser la saisie en proposant un moyen de dupliquer une occurence de Taxon, en n'effaçant que le nom de celui-ci, et en conservant les autres champs saisis.

Voici une proposition d'intégration de cette fonctionnalité dans l'interface :
![occtax_taxons](https://user-images.githubusercontent.com/26482054/61230546-83033000-a72a-11e9-9e59-3484bc56f7fd.png)

**Comment by DonovanMaillard** [comment]
Salut,

Pour rappel tu peux définir des nomenclatures par défaut pour les différents groupe 2 inon. Tu peux donc mettre par défaut imago pour les insectes, puisque ça représente une grande majorité des occurrences. Ça peut accélérer la saisie même si l'idée de pouvoir "bloquer" un champ est souvent soulevée et reste demandée, et sans doute à rediscuter à l'avenir

**Comment by sig-pnrnm** [comment]
> Pour rappel tu peux définir des nomenclatures par défaut pour les différents groupe 2 inon.

Oui, c'est un point qui peut faire gagner du temps en effet. @jbrieuclp , qu'en penses-tu pour votre instance, justement dédiée aux insectes/invertébrés majoritairement ?

Mais je pense que le fait de pouvoir dupliquer une occurence taxon, en ne modifiant l'occurence qu'au niveau du nom et éventuellement des effectifs, ça serait assez utile aussi et peut-être pas trop compliqué en développement.
Dans mon cas, mes occurences avaient toutes ces infos que je devais ressaisir à chaque fois : 

- `méthode de détermination` = `examen visuel sur photo ou vidéo`
- `déterminateur` = `Prénom Nom` du déterminateur, à saisir manuellement
- `preuve d'existence` = `oui` (photo)
- `stade de vie` = `imago`
- `type de dénombrement` = `compté`

Pour le reste, seul le nom du taxon et l'effectif changeait.

Je pense que ce cas de figure doit être assez fréquent, dans pas mal de groupes taxonomiques.

**Comment by DonovanMaillard** [comment]
Oui je suis sur des instances spécifiques invertébrés aussi mais ton idée pourrait être détournée pour être plus instinctive.

Copier coller une occurrence je pense que ça fait un peu "bricole" dans le sens où pour l'utilisateur c'est pas forcément un mécanisme instinctif.
 Par contre avoir un bouton au niveau de l'occurrence (le même que celui mis en place au niveau relevé) qui permette de garder tous les champs sauf espèce commentaire et nombre, ça deviendrait plus cohérent avec la fonctionnalité qui existe déjà au niveau du révélé

**Comment by sig-pnrnm** [comment]
> je pense que ça fait un peu "bricole" dans le sens où pour l'utilisateur c'est pas forcément un mécanisme instinctif.

C'est ton avis que je respecte, mais ne partage pas :wink: (pour moi, au contraire, c'est plus instinctif)

> Par contre avoir un bouton au niveau de l'occurrence (le même que celui mis en place au niveau relevé) qui permette de garder tous les champs sauf espèce commentaire et nombre, ça deviendrait plus cohérent avec la fonctionnalité qui existe déjà au niveau du révélé

Cela me convient aussi. C'est complémentaire.

Mais dans mon cas, j'avais certains taxons qui avaient été validés sur photo, d'autre non : du coup, copier depuis un taxon validé saisis plusieurs occurrences plus tôt n'est pas possible avec le bouton en fin d'occurrence (à moins de rouvrir complètement l'occurrence, ce qui fait perdre en ergonomie)

**Comment by DonovanMaillard** [comment]
> C'est ton avis que je respecte, mais ne partage pas 😉 (pour moi, au contraire, c'est plus instinctif)

C'est bien la limite de l'exercice en effet, on a tous un instinct et une utilisation du logiciel différent :) Mais c'est aussi tout l'intérêt des échanges, garder et trouver ce qui convient le mieux à tout le monde. 

Pour ces cas en effet, il faut voir quels champs garder, les quels supprimer, ou voir comment rendre paramétrables dans la conf les champs à garder ou non. A voir avec les autres utilisateurs en effet :)

**Comment by sylvain-m** [comment]
_(ce n'est pas le même compte, mais c'est toujours le même Sylvain 😉 )_

Je me permets de relancer cet issue, car je viens de me taper de la saisie dans l'instance Geonature du GRETIA, et je dois reconnaitre que niveau rapidité de saisie, c'est très perfectible.

Dans mon cas précis (assez standard : une chasse de nuit aux papillons, mais avec quelques coléos aussi), j'avais 25 taxons sur un relevé, et d'aller rechercher à chaque fois le stade de vie (imago), la preuve d'existence (photo), ou le type de dénombrement (compté), c'était vraiment pénible...
(et encore, je ne fais pas des chasses très souvent : pour ceux qui font de la saisie intensive, ce serait rédhibitoire)

Finalement, malgré nos désaccord sur ma proposition, @DonovanMaillard  avait une suggestion qui me convient très bien : 

> Par contre avoir un bouton au niveau de l'occurrence (le même que celui mis en place au niveau relevé) qui permette de garder tous les champs sauf espèce commentaire et nombre, ça deviendrait plus cohérent avec la fonctionnalité qui existe déjà au niveau du révélé

Je n'ai pas suivi les derniers développements, du coup je ne sais pas quelles sont les priorités actuelles. Peut-être également que je suis passé à côté de quelque chose ?
Mais je fait remonter ce besoin de la part d'un naturaliste qui préfère passer son temps sur le terrain que derrière l'écran 😉 

Bon courage à tous !
(pour le taf sur GeoNature, et pour le confinement)

**Comment by DonovanMaillard** [comment]
Bonjour Sylvain !

25 espèces sur une nocturne? Ha, la normandie ;)

Sur le fait d'avoir suivi les nouveautés, une interface a été totalement revue et est en train d'être modifiée sur occtax pour améliorer la lisibilité et optimiser l'espace dispo pour la saisie. Je pense que c'est à relancer en parallèle de la nouvelle interface , d'autant que j'ai souligné la question de récupérer les précédentes infos de relevés (comme actuellement). On pourrait imaginer que le même mode de récupération des infos soit fait au niveau de l'occurrence si ça convient à tout le monde.

**Comment by sylvain-m** [comment]
< hors-sujet >
> 25 espèces sur une nocturne?

bah, c'est encore un peu tôt quand même !
Tu tournes à combien en ce moment ?
(en plus, j'ai compté des coléos en même temps !)

< /hors-sujet >

> une interface a été totalement revue et est en train d'être modifiée sur occtax pour améliorer la lisibilité et optimiser l'espace dispo pour la saisie. Je pense que c'est à relancer en parallèle de la nouvelle interface

Ok, du coup, j'ai hâte de tester la prochaine interface ! Les soirées à plus de 60 espèces arrivent !
(jamais fait beaucoup plus que 80 dans notre secteur de Normandie ;) )

**Comment by camillemonchicourt** [comment]
Discussion et aperçus ici : https://github.com/PnX-SI/GeoNature/issues/758
En démo sur le serveur de démo (http://demo.geonature.fr).
Et retour des premiers tests sur https://github.com/PnX-SI/GeoNature/pull/860

L'objectif principal est d'améliorer l'interface et l'ergonomie en découpant le formulaire en 2 parties (Relevé / Taxons) et de permettre d'enregistrer les données au fur et à mesure de la saisie, et pas uniquement d'un seul coup à la fin de la saisie d'un relevé. 
Le fait de pouvoir enchaîner les taxons en gardant une partie des infos du taxon précédent n'a pas été intégré dans ce développement.

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.5.0 avec l'outil (désactivable) permettant de paramétrer les champs à conserver d'un taxon à l'autre.
