### ISSUE TITLE
"internal server error" en cliquant sur "nomenclature" dans le module d'administration

### ISSUE THREAD

**Issue by olivier8064** [PnX-SI/GeoNature#695]
Bonjour, 
J'ai installé récemment la v2 sur un vps ovh (Debian 9). Tout fonctionne très bien sauf une fonctionnalité : lorsque je vais dans le backoffice, en cliquant sur "nomenclatures" dans le menu d'administation des nomenclatures, j'ai une page blanche avec ce message d"erreur : 

{"message": "internal server error"}

L'adresse correspond à xxx.xxx.xxx.xxx/geonature/api/nomenclatures/admin/bibnomenclaturestypesadmin/

Merci de votre aide.

**Comment by TheoLechemia** [comment]
Bonjour,

Pouvez-vous nous envoyer les logs de l'application correspondant à cet erreur : ``geonature/var/log/gn_errors.log`` ?

Merci

**Comment by olivier8064** [comment]
Bonjour, 

Oui, voici le fichier : 
https://drive.google.com/file/d/1NLQx5zfGb2undRzjUTASPLIyY-Zs9G9Z/view?usp=sharing
Je vais essayer de mettre à jour l'appli avec la dernière version. On verra si ça change quelque chose..
A+

**Comment by olivier8064** [comment]
Pour info la mise à jour vers 2.1.1 a résolu le problème, le backoffice permet d'accéder au module nomenclature.. Mais cette mise à jour a créé un autre problème (cf #696).
Olivier Pichard

**Comment by TheoLechemia** [comment]
` (psycopg2.OperationalError) SSL connection has been closed unexpectedly
``Can't reconnect until invalid transaction is rolled back`
De ce que je vois, le serveur (surement PostgreSQL) a été stopé de manière anormale. Derrière, les requête à l'API ne fonctionnent plus sans un rollback. 
La MAJ de GeoNature qui a relancé l'API a résolu le problème

**Comment by jbrieuclp** [comment]
Salut,
j'ai aussi ces logs curieux de mon côté dans mon fichier var/log/gn_error.log
`/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_obs_meth, 'METH_OBS'::character varying)) NOT VALID"
util.warn("Could not parse CHECK constraint text: %r" % src)` 
C'est un extrait de toute la série similaire du post d'Olivier du dessus.
C'est un warning, donc ça ne bloque pas, mais c'est volumineux !
Zavez une idée de l'origine de ça ? Je n'ai pas trouvé de référence "CheckConstraint" dans le code. Est-ce qu'un warning postgres est retranscrit dans ce fichier de log ? (Je pose la question avant d'aller checker)

**Comment by lpofredc** [comment]
Pour les pesages SAWarning SqlAlchemy), ce que j'ai pu constater c'est que ces messages apparaissent sur des delà non générés par l'orm (dans geonature, tout est créé par exécution de fichiers SQL. Peut être parce que non conformes aux pratiques automatisées de sqlalchemy.

**Comment by TheoLechemia** [comment]
Oui il y a ces warnings qui polluent les logs depuis la monté de version de SQLAlchemy. Je n'ai pas réussi à trouver leur origine.
En attendant j'ai fais un vieux "hack", seulement pour en mode production:
https://github.com/PnX-SI/GeoNature/blob/develop/backend/wsgi.py
