### ISSUE TITLE
erreur lors de l'insertion de tous les taxons pour occtax

### ISSUE THREAD

**Issue by olivier8064** [PnX-SI/GeoNature#700]
Bonjour, 
J'ai installé (installation globale) la version 2.1.1 de Geonature. 
J'ai voulu inclure tous les taxons dans occtax comme indiqué ici : 
https://geonature.readthedocs.io/fr/latest/admin-manual.html#personnaliser-la-liste-des-taxons-saisissables-dans-le-module
Je l'ai fait à partir de pgadmin 4 avec l'utilisateur postgres. Je l'avais déjà fait avec la version 2.1.0 et ça avait bien marché mais là j'ai ce message d'erreur : 
_______________________
ERROR:  ERREUR:  erreur de syntaxe sur ou près de « INSERT »
LINE 10: INSERT INTO taxonomie.cor_nom_liste (id_liste,id_nom)
         ^

SQL state: 42601
Character: 377
_______________________
et la ligne "INSERT INTO taxonomie.cor_nom_liste (id_liste,id_nom)" est en rouge comme ceci : 

![Screenshot - 28_07_2019 , 20_53_44](https://user-images.githubusercontent.com/7148321/62011632-08e79800-b17b-11e9-823e-6ae207206f68.png)

D'où peut venir le problème ? 
Merci

**Comment by lpofredc** [comment]
Bonjour @olivier8064,

Il semble manquer un point virgule à la fin de la ligne 8 pour faire la séparation des deux requêtes `INSERT`.

La fois précédente, cela avait du fonctionner car les requêtes avaient sous doute été exécutées indépendamment les unes après les autres. C'est un point à corriger dans la doc.

**Comment by camillemonchicourt** [comment]
Attention il ne faut jamais travailler avec l'utilisateur postgres. Il est superutilisateur uniquement pour les opérations de création de BDD ou de création d'utilisateur ou de backup.

**Comment by olivier8064** [comment]
Ahhh mais oui ! En effet la première fois j'avais dû le faire en ligne de commande avec putty requête par requête ! 
J'avais un doute pour l'utilisateur postgres c'est pour ça que je l'ai précisé ;) 
Comme ça avait marché avec postgres, j'ai fait avec cet utilisateur un : 
DELETE FROM taxonomie.cor_nom_liste;
DELETE FROM taxonomie.bib_noms;
et je me suis reconnecté avec l'utilisateur geonatadmin puis relancé toute la requête. Ca devrait être bon (requête en cours d'exécution ;)
Merci @lpofredc et @camillemonchicourt 
Olivier

**Comment by olivier8064** [comment]
requête terminée, je confirme, tout marche impec ;) 👍

**Comment by camillemonchicourt** [comment]
Et @lpofredc bien de proposer la correction de la doc : https://github.com/PnX-SI/GeoNature/pull/701

Merci
