### ISSUE TITLE
[OCCTAX] - Quelques bugs sur l'action updates

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#706]
Bonjour, 

Quelques bugs repérés sur l'action update d'occtax : 

- A l'update, l'interface récupère toujours une info date fin = date début. 
Ce qui fait que pour un relevé nocturne, je crée un relevé qui commence J1-20h et qui fini J2-8h. Je valide. Quand j'update, pu moyen de valider la modif car il me met début J1-20h et fin J1-8h -> ne respecte pas la contrainte (ce bug est bien présent sur l'instance de démo)

- A la création d'une donnée, je renseigne preuve=Oui et j'indique quelque chose comme "photo n°34". A l'update, l'appli recharge la valeur par défaut NON, et ça fait un conflit car la photo reste mentionnée. Pour celle là, il y a surement une histoire de cache qui entre en jeu. Si je crée, valide, et édite la donnée dans la foulée, ca marche. Je vois aussi que ca ne se reproduit pas dans l'instance de démo, peut etre un problème de cache, ou de mon instance... quelqu'un d'autre a eu ce soucis ?

- Enfin un dernier que je viens de réussir à reproduire :
Je crée un relevé avec de nombreux taxons A, B, C etc. 
Si je vais éditer le B pour changer le nom d'espèce, à la fin j'ai toujours le même nombre de taxons. Mais j'ai toujours le taxon B dans la liste, et j'ai bien mon nouveau nom D.... ce qui veut dire que la nouvelle espèce que j'ai mise lors de la correction a écrasé au pif, A ou C..... Autant dire qu'avec un relevé de 100 espèces, on joue à "où est charly" pour trouver le quel a été écrasé. Par reproduit sur le serveur de démo non plus, je vais tenter de le reproduire dessus ou sur mon autre instance.

**Comment by TheoLechemia** [comment]
Merci pour les retours.
Le 1er je reproduit, le deux autres non.
Je regarde

**Comment by camillemonchicourt** [comment]
Point 1 et 2 réglés.
@DonovanMaillard, Point 3 reproduit ?
Sinon on ferme le ticket.

**Comment by DonovanMaillard** [comment]
Occtax refondu depuis
