### ISSUE TITLE
[SQL Validation] Performance v_synthese_validation_forwebapp

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#710]
Jointure qui ne sert à rien (aucune référence dans le select) par contre niveau perf ça flingue la base : l'explain analyze n'arrive pas à aboutir, en supprimant la jointure le résultat est obtenu en quelques secondes

https://github.com/PnX-SI/GeoNature/blob/3adb014d95570c32dd44cd3790160203cd84c8b2/data/migrations/2.1.0to2.1.1.sql#L123

[Edit]
En remplacant la jointure vers la vue v_latest_validation pour la table `t_validations` et en utilisant un `DISTINT ON` pour récupérer la dernière validation, sur le l'execution de la requête SELECT LIMIT 500 sur cette vue (réalisé par la route /validation) je passe de 2.09min d’exécution à 20 seconde (45sec avec LIMIT 5000), c'est mieux, mais pas encore dingo. (mes perfs serveur sont aussi à augmenter)
```
SELECT DISTINCT ON (s.id_synthese) s.id_synthese,
    s.unique_id_sinp,
    [...]
    v.validation_auto,
    v.validation_date
   FROM gn_synthese.synthese s
     JOIN taxonomie.taxref t ON t.cd_nom = s.cd_nom
     JOIN gn_meta.t_datasets d ON d.id_dataset = s.id_dataset
     LEFT JOIN ref_nomenclatures.t_nomenclatures n ON n.id_nomenclature = s.id_nomenclature_valid_status
     LEFT JOIN gn_commons.t_validations v ON v.uuid_attached_row = s.unique_id_sinp
  WHERE d.validable = true
  ORDER BY s.id_synthese, v.validation_date DESC;
```

**Comment by jbrieuclp** [comment]
Je rouvre !
Il manque `DISTINCT ON (s.id_synthese)` dans le fichier de migration 2.1.2to2.2.0.sql pour la mise à jour de cette vue. Sans ce DISTINCT ON on se retrouve avec autant de doublons de synthèse qu'il y a eu de validation (=jointure complète)

https://github.com/PnX-SI/GeoNature/blob/1a45291efe069add719afb8a84da468b4ceae262/data/migrations/2.1.2to2.2.0.sql#L48-L50

**Comment by TheoLechemia** [comment]
Alors j'ai mis un peu de temps à comprendre car en interface je n'ai pas ces doublons, alors que la vue les a bien. La requête à la vue devrait bien renvoyer des doublons, mais comme on a mis une primary key sur "id_synthese" dans le modèle SQLAlchemy, ils sont automatiquement éliminés. Comportement bizarre. 
La vue est corrigée
