### ISSUE TITLE
[Backend Geonature] plantage supervisor

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#713]
L'absence du "s" à `import warnings` fait planter supervisorctl.

https://github.com/PnX-SI/GeoNature/blob/4cfc73dd8bbcfb9a661eca677ec21b50f2a0fdb7/backend/wsgi.py#L4-L6

**Comment by TheoLechemia** [comment]
Je m'en suis rendu compte ce matin, c'est corrigé mais pas poussé !
