### ISSUE TITLE
"internal server error" en cliquant sur "nomenclature" dans le module d'administration

### ISSUE THREAD

**Issue by olivier8064** [PnX-SI/GeoNature#718]
Bonjour, 
J'ai encore une fois ce message lorsque je vais dans le module d'administration et que je clique sur type ou items de nomenclature. 
Pourtant, je suis reparti de zéro en réinstallant de a à z Geonature 2.1.2. 
J'ai ensuite uniquement fait la mise à jour des taxons à partir de pgadmin et en prenant bien soin de me connecter avec l'utilisateur geonatadmin et pas postgres ;) 
Je n'ai fait que ça comme manip. 
Je joins le ficher gn_errors.log
Je ne vois pas d'où peut venir le problème. 
Merci :)
[gn_errors.log](https://github.com/PnX-SI/GeoNature/files/3488640/gn_errors.log)

**Comment by TheoLechemia** [comment]
Bonjour,

Au vu de logs, c'est le serveur PostgreSQL qui a été redémarré. Cela pose des problèmes s'il il y a des transactions en cours au niveau de GeoNature.

```
arr��t des connexions suite �� la demande de l'administrateur
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

La solution est de redémarer l'application GeoNature: ``sudo supervisorctl restart geonature2`` pour que tout reparte en ordre.

Pouvez-vous me confirmer que vous avez redémarré PostgreSQL manuellement ?

**Comment by olivier8064** [comment]
Bonjour, 
Merci Théo, oui tout est rentré dans l'ordre après avoir fait un sudo supervisorctl restart geonature2
J'avais redémarré manuellement postgresql mais de mémoire seulement après ce "internal server error" en espérant que ça puisse résoudre le problème après la mise à jour des taxons dans occtax. Mauvaise idée donc ;)  je l'f'rais plus ;) 
Olivier

**Comment by camillemonchicourt** [comment]
C'est pas grave de redémarrer PostgreSQL si besoin, mais en effet, c'est pas évident de savoir qu'il faut aussi relancé supervisor ensuite. 

On l'a indiqué dans la FAQ : http://docs.geonature.fr/FAQ.html#problemes-lies-a-la-bdd
