### ISSUE TITLE
CARTO - permettre l'affichage de plusieurs couches simultanément

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#728]
Seul BASEMAP est disponible dans geonature_config.toml. Du coup on ne peut choisir qu'un seul fond de carte. Il serait utile de pouvoir ajouter des couches en surimposition. Par exemple les parcelles cadastrales en surimposition de l'ortho ou du scan par exemple.

**Comment by camillemonchicourt** [comment]
OK bien vu. 
Dans ce cas il faut 2 paramètre passés à Leaflet. Un avec les base layers, exclusives, non superposables. 
Et un avec les overlays layers cochables et superposables aux baselayers.
Voir https://leafletjs.com/examples/layers-control/

**Comment by mgageo** [comment]
Nous (Bretagne Vivante) voudrions aussi disposer de cette fonctionnalité pour ajouter par exemple les limites de nos réserves.
Les couches que nous voudrions ajoutées sont au format vecteur. Hors le format kml qui peut embarquer le style (mais que Leaflet ne traite que très partiellement) le format vecteur nécessite une fonction pour styler les features.
Est-il envisageable d'avoir un fichier javascript "utilisateur" qui contiendrait ces fonctions, fonctions référencées dans ~/geonature/config/geonature_config.toml ?

**Comment by camillemonchicourt** [comment]
Pour l'affichage de couches vectorielles, on a plutôt prévu de pouvoir afficher sur les cartes les zonages présents dans le ref_geo. Ça offrirait plus de possibilités et les couches y sont déjà présentes.
Voir https://github.com/PnX-SI/GeoNature/issues/474

**Comment by mgageo** [comment]
Que la couche soit stockée dans ref_geo ou ailleurs ne change pas la problématique du stylage de la couche.
À ma connaissance, on ne peut pas appliquer un style SLD dans Leaflet comme dans QGIS par exemple.
Le stylage passe généralement par du code javascript.
Sinon, il est possible comme le fait l'IGN dans son api geoportail d'offrir le paramétrage d'un certain nombre de styles

**Comment by jbdesbas** [comment]
Dans ce cas, il me parait plus simple de passer par [GeoServer](geoserver.org) pour générer des flux WMS avec le style (SLD) qui vous convient, et ensuite de les ajouter en layer cochable sur Leaflet. Peut-être voir du coté de [GeoBretagne](https://cms.geobretagne.fr/) si vous ne souhaitez pas gérer votre propre geoserver ?

**Comment by camillemonchicourt** [comment]
Le besoin est de pouvoir afficher sur la carte une couche de zonages (communes, réserves, znieff...) et idéalement pouvoir identifier son nom au clic ou au survol.
Le besoin de styler les couches de manière très souples n'est pas identifié, surtout que GeoNature n'a pas vocation à être un WebSIG.
Cependant on peut avoir une palette de couleur par défaut et imaginer une colonne pour définir la couleur d'affichage d'une couche dans la table des types de zonage du ref_geo.

**Comment by mgageo** [comment]
Camille résume bien le besoin. Le popup, la couleur et la transparence en paramètres cela couvre déjà beaucoup des utilisations.

**Comment by camillemonchicourt** [comment]
Fait avec https://github.com/PnX-SI/GeoNature/issues/974 il me semble
