### ISSUE TITLE
Occurrences d'habitats

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#735]
Le standard Occurrences d'habitats du SINP est sorti cette année : http://standards-sinp.mnhn.fr/standard-doccurrences-habitats-v1-0/

Un module de saisie d'occurrences d'habitats va ainsi être développé dans GeoNature sur la base de ce standard. 

Pour commencer, il a été retenu avec l'UMS Patrinat de n'en intégrer qu'une partie minimaliste. 
- Une table des stations (géométrie, UUID, JDD, Observateurs, Date début et fin, Altitude min et max, type_sol, ...)
- Une table des habitats de chaque station (id_station, cd_hab, nomCité, preuveNumerique, TypeDetermination, Determinateur, TechniqueCollecte, recouvrement, abondance...)

Pour les métadonnées, ce module s'appuie sur les tables des jeux de données et des cadres d'acquisition existants. 

Ce module s'appuiera sur le référentiel Habref, qui va être intégré dans un schéma dédié ``ref_habitat`` au niveau de TaxHub (https://github.com/PnX-SI/TaxHub/issues/198).

**Comment by sig-pnrnm** [comment]
Super nouvelle ! :+1: 
Fera-t-il l'objet d'un dépot spécifique (si oui, merci de nous donner le lien ici), ou est-ce que les développements seront sur le dépôt de GeoNature ?

**Comment by camillemonchicourt** [comment]
Du fait que c'est un besoin basique, partagé et surtout basé sur un standard alors on considère qu'il a sa place dans le cœur de GeoNature, au même titre que Occtax.
Il est cependant possible de le désactiver voire même de ne pas l'installer.

**Comment by camillemonchicourt** [comment]
@TheoLechemia a bien avancé les développements dans la branche dédiée (https://github.com/PnX-SI/GeoNature/tree/occhab) : 

Consultation (carte-liste) des stations et affichage de leurs habitats : 

![map-list-occhab](https://user-images.githubusercontent.com/4418840/69809970-28ef9c80-11eb-11ea-8a69-7a6d8582d25e.png)

Recherche (et export) des stations par jeu de données, habitats ou dates : 

![occhab-maplist-filter](https://user-images.githubusercontent.com/4418840/69810112-7409af80-11eb-11ea-95d3-10f639f7bff4.png)

Saisie d'une station et de ses habitats : 

![occhab-form](https://user-images.githubusercontent.com/4418840/69810136-8257cb80-11eb-11ea-9f3c-bb3ade43bbd7.png)

**Comment by camillemonchicourt** [comment]
Première version du module Occhab fonctionnel : https://github.com/PnX-SI/GeoNature/pull/818
Préparation de la version 2.3.0 en cours intégrant ce module.
