### ISSUE TITLE
bug affichage des jdd module métadonnées

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#743]
j'ai trouvé un bug qui empêche l'affichage des jdd dans le module métadonnées.
En effet, j'avais un jdd associé à un organisme(1) mais son carde d'acquisition affecté à une autre organisme(2). 
Les salariés de l'organisme(1) ne voyaient plus aucun jdd s'afficher dans le module metadonnées à cause d'une erreur sur le jdd dont le CA n'était pas associé à organisme(1).
Dans la console cela donne une errueur "cannot read properties "datasets" of undefined", on comprend bien pourquoi.

**Comment by camillemonchicourt** [comment]
Corrigé dans la version 1.4.1
