### ISSUE TITLE
disparition de relevés

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#744]
Un collègue mécontent m'explique que ces relevés disparaissent.... 
Après plusieurs échanges avec lui j'arrive enfin à reproduire le bug.

Pour gagner du temps, dans occtax,, il clique sur modifier un relevé, active le slider, revalide le relevé
puis enchaine sur des relevés. Le problème c'est qu'en faisant ça , aucun des relevés n'est enregistré sauf le dernier et surtout le premier relevé modifié est supprimé !

Vous reproduisez ce comportement ?

(Cela se passe sur une instance v2.1.1)

**Comment by jbrieuclp** [comment]
C'est ça ? https://github.com/PnX-SI/GeoNature/issues/669
C'était en lien avec l'URL si je me souviens bien.

**Comment by RomainBaghi** [comment]
oui ça semble coller ! mince j'ai loupé ce correctif !

**Comment by RomainBaghi** [comment]
comment savoir à quelle version est ajouté ce correctif ?

**Comment by camillemonchicourt** [comment]
Dans les notes de version des releases

**Comment by jbrieuclp** [comment]
Présent en 2.1.1, mais pas en 2.1.0

**Comment by TheoLechemia** [comment]
Le patch correctif ne semble pas fonctionner.
Je regarde

**Comment by jbrieuclp** [comment]
En fait la variable displayStayOnFormInterface de [occtax-form.service](https://github.com/PnX-SI/GeoNature/blob/develop/contrib/occtax/frontend/app/occtax-map-form/form/occtax-form.service.ts) n'est jamais passée à false.

Ca peut être fait avec le patch du formulaire quand le relevé est récupéré 
https://github.com/PnX-SI/GeoNature/blob/08356a369c058e31f0f0fc255c9b63225dc6f36a/contrib/occtax/frontend/app/occtax-map-form/occtax-map-form.component.ts#L116-L120

**Comment by TheoLechemia** [comment]
C'est corrigé, pour de bon
