### ISSUE TITLE
[Inscription] Erreur si pas de champ additionnel en paramètre

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#746]
Si aucun champ supplémentaire n'est paramétré (=`user_dict["champs_addi"] is None`) et bien la boucle avec `user_dict["champs_addi"].items()` n'est pas possible. Le backend plante et l'inscription aussi.

J'ai fait ça a moins qu'il y ait plus optimisé ailleurs ?
```
    if user_dict["champs_addi"] is None:
        additional_fields = []
    else:
        additional_fields = [
            {"key": key, "value": value} for key, value in user_dict["champs_addi"].items()
        ]
```

https://github.com/PnX-SI/GeoNature/blob/0cbfcfd3a78dddc3a2972d66a8e73847945e9fc2/backend/geonature/core/users/register_post_actions.py#L49-L51

**Comment by TheoLechemia** [comment]
Merci, j'intègre
