### ISSUE TITLE
petit bug sur les stats de la page d'accueil

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#752]
Le décompte des JDD affiché dans le bandeau de stats de la page d'accueil ne prends pas en compte tout les jdd pour un role qui a une portée 3.

En effet la requête utilisée (voir [ici](https://github.com/PnX-SI/GeoNature/blob/6b88d5e05df06dcfa0a75386f22b2786a194fc86/backend/geonature/core/gn_meta/models.py#L222)) : 

```
SELECT .... FROM gn_meta.cor_dataset_actor
WHERE gn_meta.cor_dataset_actor.id_organism = %(id_organism_1)s OR gn_meta.cor_dataset_actor.id_role = %(id_role_1)s
```
ne voit que les jdd qui sont directement associés au role ou associés via l'organisme.
En fait pas besoin de filtrer la requete quand le user a filter=3 et filter_type='SCOPE' ?

**Comment by DonovanMaillard** [comment]
Juste pour savoir s'il y a eu des avancées aussi ce jour? 

Pour ma part je ne sais pas si ca vient du cruved ou pas, mais seul 1 JDD créé dans GN est pris en compte. Mes 130 et quelques jdd importés ne sont pas comptés, j'affiche donc un seul jeu de données en accueil de mon instance régionale.

**Comment by camillemonchicourt** [comment]
OK alors il est possible qu'il y ait un problème sur les JDD qui sont comptés. 

Mais plus largement, on souvent posé une question sur ces stats générales affichées sur la Home : Ces chiffres doivent-il se baser sur le CRUVED et donc ce que voit l'utilisateur ou sur tout ce qu'il y a dans la BDD ?
Les 2 réponses se tiennent selon comment on aborde ces chiffres. 

Mais dans le module Dashboard qui donne des synthèses globales, on s'est basé sur tout ce qu'il y a dans la BDD, sans appliquer le CRUVED.

**Comment by DonovanMaillard** [comment]
Je viens de creuser un peu, et en effet il y a une incohérence : 
- Le nombre de données affiché est le nombre total
- Idem pour les taxons et les observateurs, qui se basent sur toute la synthèse

Pour les jeux de données en reavanche le cruved est appliqué. Comme pour le module dashboard, le plus simple et cohérent serait sans doute de ne pas tenir compte du tout du cruved. 

Je crois avoir compris comment ça marche, je dois pouvoir proposer une PR qui fonctionne... normalement ^^ :)

**Comment by DonovanMaillard** [comment]
Autre incohérence, le décompte des données est basé sur un compte de toutes les lignes pour un champ pris au pif, l'id_dataset justement. Sauf que le champs id_dataset n'est pas NOT NULL. 

En cas d'imports manuels on peut donc rentrer des données sans id_dataset, ces données ne ressortent pas dans les stats globales. J'en profite pour compter les id_synthese, c'est plus cohérent. 

On peut quand meme se poser la question d'avoir un id_dataset qui peut rester nul au passage.

**Comment by TheoLechemia** [comment]
Le décompte des observations, des espèces et des observateurs était déjà filtré sur le CRUVED mais pas les JDD.
Pour être cohérent, on applique le CRUVED sur toutes les stats.
On utilise le change "id_synthese" pour le décompte des obs.
