### ISSUE TITLE
Bug après mise à jour vers 2.1.2 (CentOS 7)

### ISSUE THREAD

**Issue by patricklbs** [PnX-SI/GeoNature#753]
J'ai cette erreur après avoir fait les mises à jour 
2.0.1 à 2.1.0 - 2.1.0 à 2.1.2 en repectant les notes de versions, montée de version de taxhub 1.6.3.

le module OCCTAX n'affiche plus rien une bulle rouge avec "une erreur s'est produite" 

la log geonature

`[2019-10-18 10:59:10 +0200] [5554] [INFO] (psycopg2.ProgrammingError) ERREUR:  droit refusé pour la vue v_releve_list

[SQL: SELECT count(*) AS count_1
FROM (SELECT pr_occtax.v_releve_list.id_releve_occtax AS pr_occtax_v_releve_list_id_releve_occtax, pr_occtax.v_releve_list.id_dataset AS pr_occtax_v_releve_list_id_dataset, pr_occtax.v_releve_list.id_digitiser AS pr_occtax_v_releve_list_id_digitiser, pr_occtax.v_releve_list.date_min AS pr_occtax_v_releve_list_date_min, pr_occtax.v_releve_list.date_max AS pr_occtax_v_releve_list_date_max, pr_occtax.v_releve_list.altitude_min AS pr_occtax_v_releve_list_altitude_min, pr_occtax.v_releve_list.altitude_max AS pr_occtax_v_releve_list_altitude_max, pr_occtax.v_releve_list.meta_device_entry AS pr_occtax_v_releve_list_meta_device_entry, pr_occtax.v_releve_list.comment AS pr_occtax_v_releve_list_comment, pr_occtax.v_releve_list.geom_4326 AS pr_occtax_v_releve_list_geom_4326, pr_occtax.v_releve_list.taxons AS pr_occtax_v_releve_list_taxons, pr_occtax.v_releve_list.leaflet_popup AS pr_occtax_v_releve_list_leaflet_popup, pr_occtax.v_releve_list.observateurs AS pr_occtax_v_releve_list_observateurs, pr_occtax.v_releve_list.dataset_name AS pr_occtax_v_releve_list_dataset_name, pr_occtax.v_releve_list.observers_txt AS pr_occtax_v_releve_list_observers_txt, pr_occtax.v_releve_list.nb_occ AS pr_occtax_v_releve_list_nb_occ, pr_occtax.v_releve_list.nb_observer AS pr_occtax_v_releve_list_nb_observer
FROM pr_occtax.v_releve_list) AS anon_1]
(Background on this error at: http://sqlalche.me/e/f405)
`

Lorsque je clic sur "validation" 

`/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: 'CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature, mnemonique_type)) NOT VALID'
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK ((taxonomie.check_is_group2inpn((group2_inpn)::text) OR ((group2_inpn)::text = '0'::text))) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK ((taxonomie.check_is_regne((regne)::text) OR ((regne)::text = '0'::text))) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_financing_type, 'TYPE_FINANCEMENT'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_territorial_level, 'NIVEAU_TERRITORIAL'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_collecting_method, 'METHO_RECUEIL'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_data_origin, 'DS_PUBLIQUE'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_data_type, 'DATA_TYP'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_dataset_objectif, 'JDD_OBJECTIFS'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_resource_type, 'RESOURCE_TYP'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_source_status, 'STATUT_SOURCE'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_bio_condition, 'ETA_BIO'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_bio_status, 'STATUT_BIO'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_blurring, 'DEE_FLOU'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_diffusion_level, 'NIV_PRECIS'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_exist_proof, 'PREUVE_EXIST'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_geo_object_nature, 'NAT_OBJ_GEO'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_info_geo_type, 'TYP_INF_GEO'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_life_stage, 'STADE_VIE'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_naturalness, 'NATURALITE'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_obj_count, 'OBJ_DENBR'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_obs_meth, 'METH_OBS'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_obs_technique, 'TECHNIQUE_OBS'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
[2019-10-18 11:01:20 +0200] [5563] [INFO] (psycopg2.ProgrammingError) ERREUR:  droit refusé pour la vue v_tree_taxons_synthese

[SQL: SELECT gn_synthese.v_tree_taxons_synthese.cd_ref AS gn_synthese_v_tree_taxons_synthese_cd_ref, gn_synthese.v_tree_taxons_synthese.nom_latin AS gn_synthese_v_tree_taxons_synthese_nom_latin, gn_synthese.v_tree_taxons_synthese.nom_francais AS gn_synthese_v_tree_taxons_synthese_nom_francais, gn_synthese.v_tree_taxons_synthese.id_regne AS gn_synthese_v_tree_taxons_synthese_id_regne, gn_synthese.v_tree_taxons_synthese.nom_regne AS gn_synthese_v_tree_taxons_synthese_nom_regne, gn_synthese.v_tree_taxons_synthese.id_embranchement AS gn_synthese_v_tree_taxons_synthese_id_embranchement, gn_synthese.v_tree_taxons_synthese.nom_embranchement AS gn_synthese_v_tree_taxons_synthese_nom_embranchement, gn_synthese.v_tree_taxons_synthese.id_classe AS gn_synthese_v_tree_taxons_synthese_id_classe, gn_synthese.v_tree_taxons_synthese.nom_classe AS gn_synthese_v_tree_taxons_synthese_nom_classe, gn_synthese.v_tree_taxons_synthese.desc_classe AS gn_synthese_v_tree_taxons_synthese_desc_classe, gn_synthese.v_tree_taxons_synthese.id_ordre AS gn_synthese_v_tree_taxons_synthese_id_ordre, gn_synthese.v_tree_taxons_synthese.nom_ordre AS gn_synthese_v_tree_taxons_synthese_nom_ordre
FROM gn_synthese.v_tree_taxons_synthese]
(Background on this error at: http://sqlalche.me/e/f405)`

avez-vous eu déjà le cas ? Merci.

**Comment by camillemonchicourt** [comment]
Il me semble que votre instance GeoNature est en mauvais état du au fait des manipulations spécifiques que vous avez réalisés.
Car ces mises à jour ont été testées puis réalisées par plusieurs utilisateurs sans ces problèmes.

**Comment by jbrieuclp** [comment]
Comme dit camille, c'est vrai que c'est curieux. 
Le message "ERREUR: droit refusé pour la vue v_releve_list" me fait penser à un blocage côté postgres. Est-ce que l'attribution des droits de l'utilisateur de la BD (celui renseigné à la rubrique `user_pg` du fichier de config `config/settings.ini`) est correctement géré sous postgres ? En gros est-ce qu'il a des droits de lecture sur ces tables.

**Comment by camillemonchicourt** [comment]
Ah oui exact, bien vu.
Ce problème a déjà été remonté (https://github.com/PnX-SI/GeoNature/issues/700). 
C'est normal si vous avez lancé les scripts avec l'utilisateur ``postgres``. Seul lui a alors les droits sur les tables qu'il a créé. Et votre utilisateur de BDD utilisé par l'application ne les a pas...

C'est pour ça qu'on a récemment ajouté une mention sur cela dans la doc de mise à jour (http://docs.geonature.fr/installation-standalone.html#mise-a-jour-de-l-application) : 
⚠️ Si la release inclut des scripts de migration SQL : lancer ces scripts avec l’utilisateur de BDD courant (généralement geonatadmin) et non le super-utilisateur postgres.

**Comment by patricklbs** [comment]
Effectivement il y avait un problème de droit  : pour occtax tout s'affiche bien, me reste l'erreur sur validation 

`/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_life_stage, 'STADE_VIE'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_naturalness, 'NATURALITE'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_obj_count, 'OBJ_DENBR'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_obs_meth, 'METH_OBS'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)
/appli/vgn/geonature/backend/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:3416: SAWarning: Could not parse CHECK constraint text: "CHECK (ref_nomenclatures.check_nomenclature_type_by_mnemonique(id_nomenclature_obs_technique, 'TECHNIQUE_OBS'::character varying)) NOT VALID"
  util.warn("Could not parse CHECK constraint text: %r" % src)`

Sinon pour la requête 
`Exécution réussie. Temps total :  143 msec.
1 lignes affectées.`

**Comment by jbrieuclp** [comment]
Ce sont "juste" des warnings. C'est évoqué ici [#695](https://github.com/PnX-SI/GeoNature/issues/695)

**Comment by patricklbs** [comment]
Tout est ok c'était des problèmes de droits, j'avais pourtant fait un grant all privileges mais à priori ce n'est pas suffisant, beaucoup de vues était postgres. 

Merci beaucoup pour votre aide !! Vous pouvez fermer le ticket !
