### ISSUE TITLE
Mystère SQLAlchemy

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#754]
Pour résoudre le bug remonté par Donovan (#751), j'ai rajouté une "relationship" sur le modèle `TOccurrencesOccurrence` (afin d'éviter un appel systematique à l'API TaxHub pour récupperer les infos taxonomique d'une occurrence).
Tout fonctionne bien sur mon instance de dev (et sur mon pc perso), mais pas sur l'instance de démo (pourtant avec les mêmes versions de python et SQLAlchemy).

Voilà le code:

```
from geonature.core.taxonomie.models import Taxref

@serializable
class TOccurrencesOccurrence(DB.Model):
    __tablename__ = "t_occurrences_occtax"
    __table_args__ = {"schema": "pr_occtax"}
    id_occurrence_occtax = DB.Column(DB.Integer, primary_key=True)
    id_releve_occtax = DB.Column(
        DB.Integer, ForeignKey("pr_occtax.t_releves_occtax.id_releve_occtax")
    )
    id_nomenclature_obs_meth = DB.Column(DB.Integer)
    id_nomenclature_bio_condition = DB.Column(DB.Integer)
    id_nomenclature_bio_status = DB.Column(DB.Integer)
    id_nomenclature_naturalness = DB.Column(DB.Integer)
    id_nomenclature_exist_proof = DB.Column(DB.Integer)
    id_nomenclature_diffusion_level = DB.Column(DB.Integer)
    id_nomenclature_observation_status = DB.Column(DB.Integer)
    id_nomenclature_blurring = DB.Column(DB.Integer)
    id_nomenclature_source_status = DB.Column(DB.Integer)
    determiner = DB.Column(DB.Unicode)
    id_nomenclature_determination_method = DB.Column(DB.Integer)
    cd_nom = DB.Column(DB.Integer, ForeignKey(Taxref.cd_nom))
    nom_cite = DB.Column(DB.Unicode)
    meta_v_taxref = DB.Column(
        DB.Unicode,
        default=select([func.gn_commons.get_default_parameter("taxref_version")]),
    )
    sample_number_proof = DB.Column(DB.Unicode)
    digital_proof = DB.Column(DB.Unicode)
    non_digital_proof = DB.Column(DB.Unicode)
    comment = DB.Column(DB.Unicode)

    cor_counting_occtax = relationship(
        "CorCountingOccurrence",
        lazy="joined",
        cascade="all,delete-orphan",
        uselist=True,
    )

    taxonomie = relationship(
        "Taxref",
        primaryjoin=(Taxref.cd_nom==cd_nom),
         lazy="joined")
```

et l'erreur:

`sqlalchemy.exc.ArgumentError: Could not locate any simple equality expressions involving locally mapped foreign key columns for primary join condition 'taxonomie.taxref.cd_nom = pr_occtax.t_occurrences_occtax.cd_nom' on relationship TOccurrencesOccurrence.taxonomie.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or are annotated in the join condition with the foreign() annotation. To allow comparison operators other than '==', the relationship can be marked as viewonly=True.`

Après avoir retourné le truc dans tout les sens, j'ai trouvé une solution très moche qui fonctionne... en réimpléntant le modèle Taxref dans le fichier de modèle d'occtax...

```
@serializable
class TaxTest(DB.Model):
    __tablename__ = 'taxref'
    __table_args__ = {'schema': 'taxonomie', 'extend_existing':True}
    cd_nom = DB.Column(DB.Integer, primary_key=True)
    id_statut = DB.Column(DB.Unicode)
    id_habitat = DB.Column(DB.Integer)
    id_rang = DB.Column(DB.Unicode)
    regne = DB.Column(DB.Unicode)
    phylum = DB.Column(DB.Unicode)
    classe = DB.Column(DB.Unicode)
    regne = DB.Column(DB.Unicode)
    ordre = DB.Column(DB.Unicode)
    famille = DB.Column(DB.Unicode)
    sous_famille = DB.Column(DB.Unicode)
    tribu = DB.Column(DB.Unicode)
    cd_taxsup = DB.Column(DB.Integer)
    cd_sup = DB.Column(DB.Integer)
    cd_ref = DB.Column(DB.Integer)
    lb_nom = DB.Column(DB.Unicode)
    lb_auteur = DB.Column(DB.Unicode)
    nom_complet = DB.Column(DB.Unicode)
    nom_complet_html = DB.Column(DB.Unicode)
    nom_vern = DB.Column(DB.Unicode)
    nom_valide = DB.Column(DB.Unicode)
    nom_vern_eng = DB.Column(DB.Unicode)
    group1_inpn = DB.Column(DB.Unicode)
    group2_inpn = DB.Column(DB.Unicode)
    url = DB.Column(DB.Unicode)

    def __repr__(self):
        return '<TaxTest %r>' % self.nom_complet

@serializable
class TOccurrencesOccurrence(DB.Model):
    __tablename__ = "t_occurrences_occtax"
    __table_args__ = {"schema": "pr_occtax"}
    id_occurrence_occtax = DB.Column(DB.Integer, primary_key=True)
    id_releve_occtax = DB.Column(
        DB.Integer, ForeignKey("pr_occtax.t_releves_occtax.id_releve_occtax")
    )
    id_nomenclature_obs_meth = DB.Column(DB.Integer)
    id_nomenclature_bio_condition = DB.Column(DB.Integer)
    id_nomenclature_bio_status = DB.Column(DB.Integer)
    id_nomenclature_naturalness = DB.Column(DB.Integer)
    id_nomenclature_exist_proof = DB.Column(DB.Integer)
    id_nomenclature_diffusion_level = DB.Column(DB.Integer)
    id_nomenclature_observation_status = DB.Column(DB.Integer)
    id_nomenclature_blurring = DB.Column(DB.Integer)
    id_nomenclature_source_status = DB.Column(DB.Integer)
    determiner = DB.Column(DB.Unicode)
    id_nomenclature_determination_method = DB.Column(DB.Integer)
    cd_nom = DB.Column(DB.Integer, ForeignKey(TaxTest.cd_nom))
    nom_cite = DB.Column(DB.Unicode)
    meta_v_taxref = DB.Column(
        DB.Unicode,
        default=select([func.gn_commons.get_default_parameter("taxref_version")]),
    )
    sample_number_proof = DB.Column(DB.Unicode)
    digital_proof = DB.Column(DB.Unicode)
    non_digital_proof = DB.Column(DB.Unicode)
    comment = DB.Column(DB.Unicode)

    cor_counting_occtax = relationship(
        "CorCountingOccurrence",
        lazy="joined",
        cascade="all,delete-orphan",
        uselist=True,
    )

    taxonomie = relationship(
        "TaxTest",
        primaryjoin=(TaxTest.cd_nom==cd_nom),
         lazy="joined")

```

Est-ce que quelqu'un a une idée d'ou ça pourrait venir?

Ps: c'est testable sur la branche ``patch_occtax``

**Comment by jbrieuclp** [comment]
'lu,
J'ai fait la même chose ma branche [perf-occtax-list](https://github.com/jbrieuclp/GeoNature/blob/e0b874f57555c9a225ea421b2de8580efbd53218/contrib/occtax/backend/models.py#L167-L172)  par contre pour la jointure avec cd_nom j'ai ça : `cd_nom = DB.Column(DB.Integer, ForeignKey("taxonomie.taxref.cd_nom"))`

J'ai pas rencontré le problème que tu évoques, ni en local ni en prod par contre ça lève un autre problème : tu va envoyer au front un json avec la clé taxonomie liée à ton occurrence. Cette clé même si non présente dans le formulaire occurrence d'angular elle restera présente dans la soumission du formulaire et ca va faire planter la mise à jour de la donnée.
C'est pas claire, mais c'est le b****l. En gros lors de la soumission d'une édition d'un relevé (sans modification d'une occurrence), l'arbre complet du json (de relevé aux dénombrements est POSTé) est envoyé au serveur. Les occurrences ont alors une clé taxonomie qui n'est pas (de)serializée dans la fonction insertorupdatereleve() du coup ça plante. 
La solution la plus simple est de faire un occ.pop(taxonomie) si il existe dans le POST.

**Comment by TheoLechemia** [comment]
J'ai essayé aussi avec `cd_nom = DB.Column(DB.Integer, ForeignKey("taxonomie.taxref.cd_nom"))`

Et oui j'ai geré le problème que tu évoque (en le faisant côté front). On vera au moment du merge comment on fera.

**Comment by jbrieuclp** [comment]
Mais tu n'as pas `foreign_keys=[cd_nom]` en option de ta relationship. Est-ce que ça joue ?

**Comment by TheoLechemia** [comment]
Toujours pas...

**Comment by bouttier** [comment]
À priori obsolète, je ferme, à rouvrir si toujours d’actu.
