### ISSUE TITLE
décalage entre openstreet map et google photo

### ISSUE THREAD

**Issue by Amegilla** [PnX-SI/GeoNature#756]
On me signale aujourd'hui un décalage entre les deux fonds carto dans occtax.
Vous avez déjà eu pb comme ça ?

**Comment by camillemonchicourt** [comment]
Je viens de faire un test rapide sur le serveur de démo et je n'ai pas constaté de décalage. 
Mais c'est fort possible car ce sont des fonds et référentiels différents.

**Comment by RomainBaghi** [comment]
Je ne l'avais as constaté auparavant donc qq a changé  du coté des serveurs carto peut-être !

**Comment by sig-pnrnm** [comment]
A vérifier si le décalage est visible ici : 
https://tools.geofabrik.de/mc/#16/44.8305/5.6063&num=2&mt0=mapnik&mt1=google-hybrid

- Si oui : c'est un problème de référentiels comme le suggère Camille
- Si non : c'est un problème de paramétrage de layer dans Leaflet

**Comment by RomainBaghi** [comment]
ok merci, je ne reproduis pas le soucis sur ce site.
Je n'ai rien touché à la config par défaut de geonature, et je m'aperçois que j'ai ce pb sur toute mes instances...

**Comment by camillemonchicourt** [comment]
Et sur l'instance de démo tu reproduis ?
Moi non.

**Comment by jbrieuclp** [comment]
Montre ce que tu peux avoir au niveau de ton [MAPCONFIG] -> BASEMAP de ton fichier geonature_config.toml, au cas où..
C'est visiblement pas une histoire de navigateur si c'est plusieurs poste. C'est sous chrome, firefox, IE.. ?

**Comment by RomainBaghi** [comment]
J'ai creusé un peu le pb. En fait c'est identifiable quand je suis dans la synthese, que je clique sur donnée (la carte s'ajoute alors sur le point ou polygone) et là quand je change le fond carto, il y a un décalage.
C'est visible que pour quelques données saisies dans occtax sur deux dates consécutives (20 et 21 sept) en particulier. Je ne l'ai pas observé sur d'autres données. 
Pas de décalage des fonds observés dans d'autre situation.
J'ai fait un gif pour vous montrer mais je cherche un moyen pour réduire sa taille (100mo!) et je partage.
