### ISSUE TITLE
question : comment configurer la page de maintenance ?

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#757]
J'ai tenté d'activer la page de maintenance comme mis dans la doc de geonature
mais elle ne pointe pas au bon endroit.
Mon geonature est sur un sous domaine : https://geonature.mondomaine.fr
Quand je fais la manip en suivant la doc, j'ai une alerte sécurité pour un mauvais certificat https et
en confirmant l’exception, j'arrive sur la page de mon atlas (qui est à l'adresse https://mondomine.fr) mais j'ai quand même l’adresse https://geonature.mondomaine.fr dans mon navigateur.

J'imagine qu'il faut modifier la conf apache qq part ?

Quelqu'un à déjà eu à faire cette manip ?

merci

**Comment by DonovanMaillard** [comment]
Bonjour Romain,

Conf apache à adapter en effet exactement sur le modèle de la conf de geonature mais en laissant le répertoire pointer vers le fichier html correspondant à la page de maintenance.

Il te faut donc faire un mix de la conf d'origine de la maintenance et la conf de geonature

**Comment by maximetoma** [comment]
Bonjour, je suis tombé sur ce ticket et je me retrouve dans la même problématique...
Mais je n'arrive pas trouver la bonne combinaison

Quelqu'un a-t-il été confronté à cette problématique sur les versions récentes de GeoNature ?
