### ISSUE TITLE
[Synthese] - recherche avancée taxons - bug champ dynamiques attributs

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoNature#763]
Salut,
Je rapporte un petit bug sur notre instance : 
Dans la recherche avancée de taxons de la synthèse, j'ai activé des champs de filtres dynamiques  sur les attributs "patrimonial" et "protégé" (boutons radios oui/non). J'ai un soucis de front semble-t'il car impossible de cocher le 2nd champ (protégé). Il semble lié au champ précédent (patrimonial) puisque que la coche se fait sur celui-ci...

En image ça donne ça : 
![synthese_taxo_avancee](https://user-images.githubusercontent.com/16793813/67370609-3fb32b80-f57b-11e9-9037-e9ddc337eb7f.gif)

Et côté log dans la console du navigateur j'ai ça : 
![synthese_taxo_avancee](https://user-images.githubusercontent.com/16793813/67370761-902a8900-f57b-11e9-86d4-84c108179abb.jpg)

Et chez vous ça fonctionne bien ?

**Comment by TheoLechemia** [comment]
Ok je vois le problème, c'est dû au passage à ces "jolies" checkbox bootstrap... Je regarde quand on a fini notre migration.

**Comment by TheoLechemia** [comment]
Tu as de la chance, on avait le même bug en prod... 
C'est corrigé.

**Comment by xavyeah39** [comment]
Top merci !
