### ISSUE TITLE
installation des requirements à l'installation d'un module

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#764]
Salut,

La procédure d'installation d'un module vérifie dans un premier temps la conformité des fichiers du module et procède à l'installation des dépendances dans un deuxième temps.

Dans un premier elle vérifie s'il y a un fichier blueprint.py et s'il contient une variable nommée blueprint
cela peut générer une erreur si des librairie dont dépend le module ne sont pas déjà installées.

Est il possible de mettre l'installation des librairies du fichier requirements.txt avant la vérification de la conformité des fichiers du module?

**Comment by TheoLechemia** [comment]
Oui tout à fait d'accord.
Il y a avait déjà eu le problème, mais ça a avait été contourné en installant préalablement les requirements dans la fonction "install_gn_module" de mémoire.
Tu propose une PR ?

**Comment by joelclems** [comment]
PR de la branche install_gn_module :
j'ai deplacé l'installation des dépendance et j'ai changé l'import de pip et la fonction import_requirements dans utils/env.py qui posaient problème :
la fonction pip.main n'existe plus dans les nouvelles versions de pip

**Comment by TheoLechemia** [comment]
Mergé
