### ISSUE TITLE
mail de validation d'inscription

### ISSUE THREAD

**Issue by Idaline** [PnX-SI/GeoNature#767]
Possibilité d'envoyer un mail de confirmation d'inscription automatique lorsque l'administrateur a validé l'inscription (quand AUTO_ACCOUNT_CREATION = false).

**Comment by jpm-cbna** [comment]
Cela vient d'être implémenté dans la pull-request #1036 qui a été fusionné à la branche "develop".
Cela devrait être disponible dans la version v2.5 de GeoNature.
