### ISSUE TITLE
Définition du champs synthese.meta_create_date

### ISSUE THREAD

**Issue by jbdesbas** [PnX-SI/GeoNature#768]
Salut,

Petite précision pour préciser l'utilisation du champs _meta_create_date_, notamment dans le cas d'import de données : est-ce que cela correspond à la date d'insertion de la données dans la base de données, ou la date de création de la données source (et qui est donc fixe et intrinsèquement lié à l'uuid) ?

Je me pose la question dans le cadre de bilans, où j'ai besoin de sortir les données _intégrées en base_ sur une période donnée.

Peut-il être pertinent d'ajouter un champs _insertion_date_ , ou alors la table d'historisation est là pour ça et ferait le boulot ?

**Comment by TheoLechemia** [comment]
C'est la date "d'insertion" de la donnée dans la table.
D'ou le "meta_create_date timestamp NULL DEFAULT now()". Par défaut rempli à la date d'insertion.
Après libre à toi de remplir cette colonne par la date de création de la donnée source si c'est de la donnée importée.

**Comment by jbdesbas** [comment]
OK merci.
A garder en tête pour les imports donc, et a priori laisser ce champs en NULL si la date de création est inconnue.

**Comment by TheoLechemia** [comment]
Ben tout dépend comme tu veux l'utiliser. Mais à la base c'est un champs "métadonnées" de date d'insertion, pas de date de création. Si tu pousse NULL, ça va mettre la date du jour, pour remettre NULL, il faut updater manuellement les données en question.
