### ISSUE TITLE
Occtax - Filtre > Info > Retour

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#772]
Dans Occtax, je fais un filtre, je consulte la fiche d'un des relevé, je reviens en arrière avec le Retour du navigateur.
La liste est toujours filtrée, mais les filtres sont RAZ. 
Il serait donc souhaitable que les filtres gardent leur valeur pour coller au contenu de la liste.

**Comment by jbrieuclp** [comment]
Oui et le nombre de relevé est aussi passé à zéro et la liste des pages supprimée. 
Pour les filtres et lae numéro de page je pense qu'il peuvent être placé en GET (sans rechargement de page) dans l'URL pour être sauvegardés.
