### ISSUE TITLE
Permettre une plus grande flexibilité pour les exports de la synthèse ?

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#773]
Je voudrais savoir si d'autres que moi trouveraient pertinent d'offrir davantage de flexibilité pour les exports de la synthèse ? 

Plus précisément, sur le principe du module d'export globalement, il s'agirait de configurer pour les exports synthèse "un export - un nom - une vue". En base, ca permettrait de créer une ou des vues un peu spéficifiques à chacun. En interface, ca rajoute n boutons dans la modale de téléchargement. 

L'usage que j'y vois c'est par exemple pour le cas SINP, d'ajouter un export "sources" qui définit globalement les structures fournisseurs sans avoir toute la métadonnée. Ca permet aussi, dans notre cadre producteur, d'avoir un export "transmission" assez simple, et un export "analyse", qui comporte un certain nombre de croisements sur le taxref, les géométries, les statuts etc, et qui derrière nous sert dans nos analyses R etc. Sans pour autant filer 50 colonnes, ou toutes les métadonnées,quand on a besoin d'une info simple. Ni limiter nos exports à quelque chose de trop simple qui ne convient pas selon les usages. 

A priori ca semble simple à gérer en base ou en conf, simple à administrer. Mais la somme de plein de choses simples reste à prendre à modération, je lance donc le débat ici :)

**Comment by TheoLechemia** [comment]
L'interet par rapport au module d'export, c'est de pouvoir filtrer en amont depuis le module synthese ?

**Comment by DonovanMaillard** [comment]
Oui, le module export permet pas d'anticiper la recherche de l'utilisateur. 

Dans notre charte on oblige les utilisateurs à citer les sources sous un format définit : 
- Parc national des Ecrins - 1832 données, 121 espèces
- Flavia et Parc national de la Vanoise - 156 données, 38 espèces
Etc. Mais pour ca je peux pas faire un export qui porte sur toute la base. Et si j'utilise l'export métadonnées pour ca, ca veut dire que je ne peux plus réellement exporter les métadonnées par exemple. 

Autre cas, Yann a besoin d'un paquet d'infos quand il travaille lui meme sur les données, mais fais le tri manuellement dans ses colonnes quand il transmet les données brutes à des tiers, pas pour dégrader les données mais simplement pour permettre une meilleure lisibilité en enlevant les données destinées à l'analyse. 

Je me dis qu'à terme s'il y a par exemple 3 ou 4 modules de suivi avec des données communes, ce système permettra d'exporter depuis la synthèse, les infos de synthèse qui sont propres à ces 2, 3 modules en ayant par exemple un nom de site, sans pour autant devoir passer par les 3 ou 4 modules de suivis utilisés.

**Comment by camillemonchicourt** [comment]
Même si il ne permet pas d'appliquer des filtres, ce que tu évoques est clairement le rôle du module EXPORT, qui est complètement modulable et travail en tache de fond.

Je comprends l'intérêt de pouvoir ajouter des exports dans la Synthèse, donc auxquels s'appliquent CRUVED et filtres mais ça peut être contraire aux besoins en terme de performances. 
Il faudrait donc être vigilent sur ce point.

**Comment by DonovanMaillard** [comment]
Oui, je suis d'accord qu'il faut faire attention, tant sur les performances que sur la complexité de tout paramétrer dans tous les sens en terme de lisibilité pour administrer l'outil d'ailleurs. 

Cependant le module export est confiné à des exports récurrents et prévisibles sur lesquels on est capable d'anticiper les requêtes. Ce n'est pas le cas dans ce contexte ou la synthèse doit renvoyer certaines infos choisies au coup par coup par l'utilisateur. 

Actuellement, seuls quelques champs dont l'id_synthese sont obligatoires dans une vue, et l'appli renvoie une liste d'id_synthèse à intégrer à l'export. Ce fonctionnement permettrait d'être plus souple sans (à priori) changer profondément les choses.

Pour le fait de travailler en tache de fond et faire un envoi mail, c'est qu'un avis perso mais j'avoue ne pas être emballé... ca me semble toujours plus simple d'avoir directement son export depuis l'appli sur laquelle on fait la demande. A voir mais pour le coup je ne généraliserais pas ça sur la synthèse;

**Comment by camillemonchicourt** [comment]
C'est ce qui a été fait dans : https://github.com/PnX-SI/GeoNature/issues/2955
Dans cette PR : https://github.com/PnX-SI/GeoNature/issues/2955

On ne modifie la vue d'export fournie par défaut, mais on se créé ses propres exports d'observations custom dans la Synthèse avec des vues custom.
