### ISSUE TITLE
Importation de données dans la table Synthèse

### ISSUE THREAD

**Issue by skoliad** [PnX-SI/GeoNature#779]
Nous installons Géonature dans l'association Bretagne vivante et nous rencontrons des problèmes dans nos tests d'imports de données.

Pouvez vous préciser s'il y a des précautions à prendre lorsque l'on supprime les données d'un "dataset" dans la table synthèse ?

Par ailleurs existe-t-il des outils pour suivre l'avancement d'une intégration de données dans la table synthèse quand celle-ci est très longue ?(par exemple un trigger qui génèrerait, , dans une  une table de suivi, un message, toutes les n lignes traitées ) ? Précision

PRECISIONS----
Pour nos tests nous intégrons plusieurs fois le même jeu de données.
Nous l'adaptons  pour qualifier nos nos interfaces.
Il s'agit de 22 000 observations d'oiseaux sur l'ensemble de la Bretagne

Entre chaque essai  nous  supprimons les données ("delete from gn_synthese.synthese where id_dataset = ....") 
La première intégration est relativement rapide (environ 5 minutes) 
Mais les fois suivantes elle est beaucoup plus longue. ou bien elle n'aboutit pas car nous l'arrêtons au bout d'un certain délai.
Le fait d'intégrer une petite partie des données (mettre Limit, puis limite 100... dans le sql ) puis recommencer sur l'ensemble du jeu de données semble améliorer la situation.

La mémoire de l'ordinateur ne semble pas saturée, les accès disques semblent limités  mais le processeur est sollicité à plus de 99 % par Postgres.

Avez-vous déjà rencontré ce problème ?Est il lié aux tables annexes que la procédure mets à jour lors des insertions dans la table synthèse (gn_synthese.cor_area_taxon, gn_synthese.cor_area_synthese...)Y a-t-il un moyen de le résoudre ?

Nous avons rencontré le même problème 
* sur plusieurs configuration
(Poste fixe sous Débian, serveur Ovh sous Débian et ordinateur portable sous Ubuntu 18)

* avec les version 2.1.0 et 2.2.1 de Géonature

**Comment by camillemonchicourt** [comment]
Oui les triggers qui calculent les zonages de chaque observation peuvent être longs. 
Voir le ticket https://github.com/PnX-SI/GeoNature/issues/535 assez similaire.

Vous pouvez désactiver les triggers, mais il faudra alors faire attention à bien relancer après coup et manuellement les calculs qu'ils réalisent. 

Voir http://docs.geonature.fr/admin-manual.html#triggers-dans-la-synthese

A noter aussi que par défaut, GeoNature installe les communes et mailles sur toute la France. 
Ne garder que ceux de votre territoire (en supprimant ou désactivant les autres dans ``ref_geo.l_areas``) peut grandement accélérer les calculs d'intersections réalisés par les triggers

**Comment by skoliad** [comment]
Merci pour votre réponse et effectivement le delete sur la table synthèse
est un peu lent (enviro 5 miniutes) mais ce n est pas rédhibitoire.

Ce qui nous surprend c est la variabilité des performances en intégration,
comme si un autre facteur intervenait.


Nous allons tester l inactivation des triggers, puis les faire executer sur
l ensemble du dataset en fin d intégration

 (ce qui en soit sera peut etre plus performant qu une mise à jour a chaque
ligne quand le serveur n est pas très puissant) .


Bon week end
