### ISSUE TITLE
OCCTAX - pagination faites sur les occurrences de taxon et non les relevés

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature#784]
Si on fait une recherche dans le maplist d'Occtax et que le résultat réel est par exemple de 3 relevés. Si ces 3 relevés comportent chacun plusieurs taxons, par exemple 7, 5 et 1 taxons (soit 13 taxons pour 3 relevés) : la pagination dit `13 Relevé(s) au total` alors qu'il n'y en a que trois et surtout, seulement 2 relevés sont présents sur la 1ère page et le 3ème est sur la 2ème page.

![Capture du 2019-11-05 16-43-52](https://user-images.githubusercontent.com/10024739/68222612-8da04880-ffeb-11e9-9ea6-23877fc7d92d.png)

On voit ici `35 Relevé(s) au total` pour 3 pages. Il y a en fait 6 relevés seulement sur la première page (comme on peut le voir sur l'image) 10 sur la 2ème page et 11 sur la dernière. 
Soit 6+10+11 = 27 relevés et non 35. 35 est en fait le nombre de taxons pour les 27 relevés.

A noter que ce bug est remonté sur des tests avec une seule espèce dans les filtres **donc plusieurs fois le même taxon pour un même relevé**.
Si on a des relevés avec des taxons différents, on a pas ce soucis. Comme ci-dessous ou l'on a 15 taxons dans 10 relevés et tout est bon.

![Capture du 2019-11-05 16-56-22](https://user-images.githubusercontent.com/10024739/68223597-5b8fe600-ffed-11e9-9b82-318572a688a1.png)

**Comment by camillemonchicourt** [comment]
Voir si la correction de https://github.com/PnX-SI/GeoNature/issues/777 a corrigé cela aussi
