### ISSUE TITLE
MENU - Ordre des modules

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/GeoNature#787]
L'ordre et les labels des menus du panel de gauche est à revoir .

![Sans titre](https://user-images.githubusercontent.com/1989428/68381596-5ac49480-0152-11ea-9eeb-9360c8b5aeb0.png)

Je propose :

Dashboard
Voir toutes les données (Synthese)

Gestion des Imports
Gestion des Validation
Gestion des Exports

Saisie - Occurrence de taxons
Saisie - Suivi Hab territoire
Saisie - Suivi Flore territoire
Saisie - Flore prioritaire

Administration des Métadonnées
Administration des Vocabulaires 
Administration des Droits

**Comment by TheoLechemia** [comment]
Les labels sont déjà éditable depuis la table "gn_commons.t_modules", il manquerait un colonne ordre en effet

**Comment by orovellotti** [comment]
Ok super est un treeview?

**Comment by TheoLechemia** [comment]
Il est pas prévu pour l'instant d'avoir des "sous-modules". Mais il y a déjà dejà une colonne "groupe" qui servait dans GN1 de regrouper les module par entité faune, flore ... On pourrait la réutiliser.

**Comment by orovellotti** [comment]
Super merci

**Comment by camillemonchicourt** [comment]
- Ajouter un champs ``order`` dans la table ``gn_commons.t_modules`` permettant d'ordonner leur affichage dans le menu. Si le champs n'est pas rempli, alors affichage ensuite et alphabétiquement.
- Dans un second temps, ajouter la possibilité de grouper les modules

**Comment by camillemonchicourt** [comment]
Premier point (ordre des modules) géré dans la 2.5.0.
Reste le deuxième point (grouper les modules) à réaliser.
