### ISSUE TITLE
IMPORT NIVEAU 2 : échec de l'import du fichier CSV

### ISSUE THREAD

**Issue by mgageo** [PnX-SI/GeoNature#795]
Bonjour à tous,
J'ai mis en place une instance GeoNature 2.2.1 sur une machine virtuelle en Debian 9.
L'installation s'est déroulée sans problème.
J'essaye maintenant de faire un import de niveau 2 en suivant le guide https://geonature.readthedocs.io/fr/latest/import-level-2.html
Sur le la commande psql, j'ai une erreur
postgres@geonature:/home/marc$ psql -d geonature2db -f sql
psql:sql:1: NOTICE:  la table « testimport » n'existe pas, poursuite du traitement
psql:sql:1: ERREUR:  erreur de syntaxe sur ou près de « ; »
LIGNE 1 : create table gn_imports.testimport ( text);
                                                    ^
REQUÊTE : create table gn_imports.testimport ( text);
CONTEXTE : fonction PL/pgsql gn_imports.load_csv_file(text,text), ligne 26 à EXECUTE
psql:sql:2: ERREUR:  la relation « gn_imports.testimport » n'existe pas
postgres@geonature:/home/marc$

La commande fait aussi référence à un utilisateur geonatuser qui n'existe pas :
postgres@geonature:/home/marc$ psql -c '\du+'
                                                     Liste des rôles
 Nom du rôle |                                    Attributs                                    | Membre de | Description
-------------+---------------------------------------------------------------------------------+-----------+-------------
 geonatadmin |                                                                                 | {}        |
 postgres    | Superutilisateur, Créer un rôle, Créer une base, Réplication, Contournement RLS | {}        |

postgres@geonature:/home/marc$

J'ai oublié d'installer quelque chose ?

Marc

**Comment by camillemonchicourt** [comment]
J'ai transféré le ticket dans le bon ticket car il avait été mis dans le dépôt du module Import, en cours de développement.
