### ISSUE TITLE
Erreur 404 occtax

### ISSUE THREAD

**Issue by NatureFaune06** [PnX-SI/GeoNature#815]
Bonjour je rencontre un bug après installation de Geonature sur Debian 9 
L'installation s'est effectuée avec succès et sans aucune erreur. 
Lorsque je lance l'interface web : Domaine.com/geonature/ tout fonctionne. 
En revanche l'occtax et validation ne fonctionnent pas en cliquant sur ceux-ci dans le menu j'ai l'erreur 404...

y'a t'il une manipulation a effectuer? 

Quelqu'un a déjà eu ce problème?
 
Merci d'avance.

**Comment by TheoLechemia** [comment]
Bonjour,
Pouvez-vous fournir le fichier de log complet de l'installation ?
Merci

**Comment by jbrieuclp** [comment]
Si c'est comme chez moi (depuis ma dernière mise à jour) les routes occtax, synthese, etc. sont mise à la racine du serveur : 
Avant : domaine.fr/geonature/# -> domaine.fr/geonature/#/occtax
Maintenant : domaine.fr/geonature/# -> domaine.fr/#/occtax

J'suis à la recherche du blem là... La p'tite surprise qui ne se voit pas en mode dev..

**Comment by jbrieuclp** [comment]
C'est ce commit qui met le bazar https://github.com/PnX-SI/GeoNature/commit/27bb36c82293e5f92de94861a1b3343ffee0b1c5#diff-2ed0455f386ab9cd51dceaa8108533f9

Il faut restaurer la version initiale (de-commenter les commentaires)

**Comment by camillemonchicourt** [comment]
OK bien vu, merci pour l'info mais je ne pense pas que la personne ait installé une version en cours développement.

**Comment by joelclems** [comment]
J'avais fait ce commit pour que le menu marche en mode quand il y a un port dans l'adresse dev avec localhost:4200
mais ça ne marche si geonature n'est pas à la racine

**Comment by joelclems** [comment]
J'ai remis comme c'était avant. C'est que pour le dev, mais quelqu'un aurait une idée pour prendre en compte le port dans l'adresse?

**Comment by TheoLechemia** [comment]
Avec urlparse ?
https://docs.python.org/2/library/urlparse.html

**Comment by joelclems** [comment]
Comment peux t'on savoir l'url du frontend depuis le backend?
dans ce [lien](https://stackoverflow.com/questions/28448991/flask-how-to-get-the-http-origin-of-a-request) ils proposent
`request.environ['HTTP_ORIGIN'])`
mais j'obtiens None et je ne trouve pas de :4200 dans les valeurs de`request.environ`

**Comment by joelclems** [comment]
Il suffit de changer `URL_APPLICATION = 'http://localhost:4200'`  dans  config/geonature_config.toml

**Comment by TheoLechemia** [comment]
Attention à bien mettre ``API_ENDPOINT`` sur localhost aussi si tu fais ça, sinon tu n'arrivera pas à t'authentifier (cookier cross domain)

**Comment by joelclems** [comment]
J'avais déjà rencontré ce problème

avec cette config c'est bon pour moi :

```
URL_APPLICATION = 'http://localhost:4200' 
API_ENDPOINT = 'http://localhost:8000/'
```

**Comment by NatureFaune06** [comment]
Je vous apporte plus de précision sur mon problème: 
- Installation d'une version stable  => 1.4.1
- installation sur un vps sous débian 9 à jour. 
- j'ai suivi l'installation via le install all sur la documentation afin de me familiariser à l'outil.

TaxHub : fonctionne sans problème 
usershub fonctionne aussi 
L'affichage web de géonature fonctionne mais dans le menu occtax et validations ne fonctionnent pas erreur 404. 

J'ai donc vérifié les logs aucune erreur sur geonature.

En ce qui concerne mon installation je ne peux utiliser localhost (sauf base de donnée)  car je suis sur un serveur distant hébergé. 
Je vous avoue que je suis un peu perdu dans la configuration du programme malgré une bonne lecture de la doc.

**Comment by camillemonchicourt** [comment]
@NatureFaune06, désolé la discussion a un peu dévier ici ;-)

Oui oui vous ne devez pas mettre ``localhost`` pour l'API mais uniquement pour la BDD.
Exemple de configuration dans ``/home/myuser/geonature/config/geonature_config.toml`` pour le serveur http://demo.geonature.fr/geonature : 

```
URL_APPLICATION = 'http://demo.geonature.fr/geonature' 
API_ENDPOINT = 'http://demo.geonature.fr/geonature/api'
API_TAXHUB = 'http://demo.geonature.fr/taxhub/api'
```

Il nous faudrait vraiment les logs pour vous aider.

Leur emplacement est indiqué dans la doc (http://docs.geonature.fr/installation-all.html) : 

> Si vous rencontrez une erreur, se reporter aux fichiers de logs : 
> - Logs de l’installation de la base de données : /home/myuser/geonature/var/log/geonature/install_db.log
> - Log général de l’installation de l’application : /home/myuser/var/log/geonature/install_app.log

**Comment by NatureFaune06** [comment]
Bonjour merci pour votre réponse. 
Je viens de re-effectuer une installation complète 
En revanche le dossier de log est vide ( même après reboot ) 

Seulement le fichier gn_errors.log qui ne comporte aucune erreur: 

Starting 
/home/geonatureadmin/geonature/backend
/home/geonatureadmin/geonature/backend/config/settings.ini
/home/geonatureadmin/geonature
[2019-12-11 18:47:14 +0100] [10252] [INFO] Starting gunicorn 19.7.0
[2019-12-11 18:47:14 +0100] [10252] [INFO] Listening at: http://0.0.0.0:8000 (10252)
[2019-12-11 18:47:14 +0100] [10252] [INFO] Using worker: sync
[2019-12-11 18:47:14 +0100] [10282] [INFO] Booting worker with pid: 10282
[2019-12-11 18:47:14 +0100] [10285] [INFO] Booting worker with pid: 10285
[2019-12-11 18:47:14 +0100] [10286] [INFO] Booting worker with pid: 10286
[2019-12-11 18:47:15 +0100] [10291] [INFO] Booting worker with pid: 10291

**Comment by jbrieuclp** [comment]
Quel est le contenu du fichier `frontend/src/app/routing/app-routing.module.ts` ?
Quel est le contenu de la table gn_commons.t_modules ?

**Comment by TheoLechemia** [comment]
C'est le fichier ``install_all.log`` qu'il faudrait, il doit être à la racine de votre utilisateur si vous avez suivi la doc http://docs.geonature.fr/installation-all.html

**Comment by NatureFaune06** [comment]
https://pastebin.com/6G9d5z7z

Voici le lien pastbin avec le contenu du install_all.log

Il y'a en effet des erreurs

**Comment by camillemonchicourt** [comment]
OK en effet là ça commence à être intéressant :-)
Et pour la documentation, on va corriger les fichiers de logs à consulter en cas d'erreurs après l'installation.

**Comment by NatureFaune06** [comment]
L'installation semble bonne non? j'ai suivi étape par étape toutes les commandes et modifications a éffectuer.

**Comment by camillemonchicourt** [comment]
Certainement que non, on va regarder demain

**Comment by NatureFaune06** [comment]
D'accord un grand merci pour vos réponse rapides! je vais aussi rechercher de mon côté ce qui ne va pas!

**Comment by TheoLechemia** [comment]
Il semblerait que l'installation ai été lancé plusieurs fois. Le seconde fois la base n'a pas été réinstallé: on le voit ici
`Database exists but the settings file indicate that we don't have to drop it.`
passez le paramètre `drop_db` à `true` dans le fichier `install_all.ini,` redémarrez postgres: `sudo service postgresql stop`. Relancer ensuite l'installation puis renvoyez nous les logs

**Comment by lpofredc** [comment]
Cela ne concerne-t-il pas OccTax & le module Validation? car le log montre les erreurs suivantes. Peut-être suffit-il de les activer?
```
[91mError while installing GN module 'OCCTAX' [0m.The process returned:
    The module OCCTAX is already installed, but maybe not activated
/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 
[91mError while installing GN module 'VALIDATION' [0m.The process returned:
    The module VALIDATION is already installed, but maybe not activated
Build du frontend...
npm WARN using --force I sure hope you know what you are doing.
```

**Comment by TheoLechemia** [comment]
> Cela ne concerne-t-il pas OccTax & le module Validation? car le log montre les erreurs suivantes. Peut-être suffit-il de les activer?

Ce message est dû a une installation lancée 2 fois. L'erreur vient d'ailleurs. Peut être le fichier de routing comme l'indique Jean-Brieuc.

**Comment by NatureFaune06** [comment]
Problème de l'erreur 404 corrigé un grand merci à TheoLechemia. 
En revanche je n'ai pas très bien compris sur la doc comment synchroniser l'Atlas a la base de donne de geonature.

**Comment by TheoLechemia** [comment]
https://github.com/PnX-SI/GeoNature-atlas/blob/master/docs/installation.rst
Le bloc **4. Installation de la base de données**. Le principe est de créer une nouvelle BDD que l'on vient connecter en foreign data wrapper à la base GeoNature.
N'hésitez pas à ouvrir des tickets sur le dépôt concerné

**Comment by camillemonchicourt** [comment]
OK super, donc c'était bien le fait d'avoir installé plusieurs fois GeoNature sans avoir supprimé la BDD qui posait problème. 
On va voir si on peut clarifier la documentation sur cet aspect aussi, dans le cas d'une réinstallation sur une installation...
