### ISSUE TITLE
Problème sidenav module

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature#822]
Désolé, mais ce commit https://github.com/PnX-SI/GeoNature/commit/4ad5c56939c908f8e59cd11cd8f95cf4860ce0d3 fait qu'il n'est plus possible d'ajouter des module externe au sidenav. 
Dans la table `gn_commons.t_modules`, si `active_frontend = true` c'est la route du champ module_path qui est prise. Sinon c'est la route `module_external_url`. Dans le commit, seuls les modules avec active_frontend = true sont affiché dans le menu, de fait les externes ne sont plus présent.
Est-ce qu'il faut modifier quelque chose dans la BD dans le back ou restaurer le front ? J'sais pas, faut en discuter, mais je pause le problème là et je pars en week-end ! 😁

**Comment by joelclems** [comment]
J'avais fait cette modif pour ne pas afficher les modules avec `active_frontend` à `false`
Si j'ai bien compris il faut les afficher quand `module_external_url` est renseigné

j'ai corrigé ça dans le commit 7450c96

Les modules affichés ceux qui ont `active_frontend` à `true` et ceux qui ont une valeur  pour `module_external_url`

Les modules sans `module_external_url` et avec `active_frontend` à `false` ne sont pas affichés

Désolé pour le bug
