### ISSUE TITLE
fiche info relevé occtax, ajout du nom vernaculaire

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#826]
Bonjour, 

J'ai des utilisateurs qui aimeraient que le nom français soit aussi visible sur la fiche d'info d'un relevé dans occtax. Je trouve ça utile effectivement.
Il suffit de rajouter {{occ.taxon?.nom_vern}} ici : https://github.com/PnX-SI/GeoNature/blob/ff0e4ff94665cba7830b6d8c832425ef08ac6f09/contrib/occtax/frontend/app/occtax-map-info/occtax-map-info.component.html#L78

à voir comment l'afficher plus proprement (juste une virgule qui sépare les deux noms, ou faire une colonnes mais ça devient lourd)... avec la gestion des cas ou il n'y a pas de nom_vern.

**Comment by camillemonchicourt** [comment]
Oui il faudrait faire comme dans les fiches de la synthèse : Épervier d'Europe - Accipiter nisus (Linnaeus, 1758)

C'est à dire : Nom FR - Nom scientifique

**Comment by jbrieuclp** [comment]
Faire un énième paramètre ? 😃

**Comment by camillemonchicourt** [comment]
On peut... Mais je pense que Nom FR - Nom scientifique conviendra à tout le monde.

**Comment by jbrieuclp** [comment]
Pas trop en entomo (sauf peut être sur les groupes/espèces très communs), mais je pourrais changer si c'est comme ça par défaut

**Comment by RomainBaghi** [comment]
Nom FR - Nom scientifique , c'est parfait et si le nom fr n'existe pas il n'y a que le nom scientifique.

(C'est vrai qu'en entomo, il y a des nom_fr dans taxref assez farfelus qu'il vaudrait mieux ne pas afficher.)

**Comment by RomainBaghi** [comment]
Un petit détail que j'avais oublié : ne prendre que le premier nom français et pas la liste des synonymes.

**Comment by RomainBaghi** [comment]
J'en rajoute une couche mais c'est un peu dommage que cette page n'affiche "que" la liste des espèces et pas un petit résumé du relevé (commentaires, nb d'individus total par espèces, etc...). 
J'ai des demandes de bénévoles qui se servaient de l'affichage équivalent dans notre ancien outil pour en faire des capture d'écran et l'envoyer aux partenaires.

**Comment by camillemonchicourt** [comment]
Si tu cliques sur une espèce, tu as le détail de l'occurrence et des denombrements.
Il manque les commentaires, c'est un oubli.

**Comment by camillemonchicourt** [comment]
Fait dans la 2.3.1
