### ISSUE TITLE
Permissions Occtax

### ISSUE THREAD

**Issue by Idaline** [PnX-SI/GeoNature#830]
Bonjour,

Lorsque le CRUVED est ajusté comme "créer uniquement mes données", la création d'un nouveau relevé est interdit, et ne fonctionne que comme "créer toutes les données". Cependant de cette dernière façon, l'utilisateur peut modifier comme il veut les relevés des autres (même si mise à jour est sur "mes données"), et ne peut seulement pas les supprimer. 

Note : je n'ai pas sur-couché les permissions, tout le monde est dans un groupe.

Est ce que c'est comme ça pour tout le monde ? Merci !

**Comment by camillemonchicourt** [comment]
Salut. J'ai fait des tests et n'ai pas eu ce problème.

En fait la notion de portée de l'action C (créer) s'applique au niveau des JDD. 
Si un utilisateur a une portée de création de 1 (Mes données) alors il ne peut créer des données uniquement dans des JDD pour lesquels il est lui-même acteur. 
Si il a un C de portée 2, alors il peut créer des données dans les JDD dont lui ou son organisme est acteur. 

Ton problème doit être là. Ton utilisateur ne doit pas avoir de JDD dont il est acteur et il ne peut donc pas associer son relevé à un JDD, donc il ne peut pas créer de relevé. Merci de confirmer ?

Voici le test que j'ai réalisé sur un serveur de test : 

1. Je créé un utilisateur dans UsersHub : thierry.loufoque / toto 
Organisme : Autre
Dans aucun groupe
2. Je lui mets les droits de lecteur dans l'application GeoNature pour qu'il puisse s'y connecter
3. Il peut se connecter à GeoNature mais n'a pas encore de CRUVED donc il ne voit aucun module
4. Avec un compte Administrateur, je lui ajoute un CRUVED dans GeoNature (Admin / Permissions)
110000. Il peut accéder à la création de données dans Occtax, mais ne peux pas valider car il n'a pas de JDD
5. Je créé un JDD et l'ajoute en tant qu'acteur
C'est OK, il peut bien créer un relevé dans son JDD

J'ai aussi testé un utilisateur qui une portée 1 (Mes données) sur l'action U (Mettre à jour) et il ne peut bien mettre à jour que ses données et pas celles des autres utilisateurs.

**Comment by Idaline** [comment]
Super, ça marche ! Merci beaucoup !
