### ISSUE TITLE
Erreur à l'installation du module OccHab

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoNature#832]
Bonne année à tous !
Et merci pour ces belles évolutions de GeoNature très prometteuses pour 2020 :)

J'ai testé l'upgrade vers la 2.3.0 sur une instance (Debian 9) + install du module OccHab.

Pas de soucis la MàJ en revanche une erreur lors de l'install de OccHab qui laisse penser à une incompatibilité de versions entre NodeJS et Angular :

```
> geonature@0.0.0 build /home/admin/geonature/frontend
> ng build --prod --aot=false --build-optimizer=false

You are running version v8.1.1 of Node.js, which is not supported by Angular CLI v6.
The official Node.js version that is supported is 8.9 and greater.

Please visit https://nodejs.org/en/ to find instructions on how to update Node.js.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! geonature@0.0.0 build: `ng build --prod --aot=false --build-optimizer=false`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the geonature@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/admin/.npm/_logs/2020-01-02T13_31_00_110Z-debug.log
geonature2: stopped
geonature2: started
```

Le module est bien présent dans la sidebar mais si en y accédant j'ai une erreur 404.
Ma version de node.js est en 6.17.1 (cf `install_all.sh`) or dans le log ci-dessus il est indiqué 8.1.1 ...

ça me dépasse un peu... des idées ? 
Merci d'avance !

**Comment by DonovanMaillard** [comment]
salut Xavier! 

Je l'ai eue également, @TheoLechemia  n'a pas pu reproduire donc ca n'a pas été traité ici. 

Il te suffit d'installer la bonne version d'nvm, ce que le  script sh est censé faire mais ne semble pas faire correctement.
 
```
nvm install v10.15.3
nvm alias default 10.15.3
```

Puis dans geonature/frontend
`npm run build`

**Comment by xavyeah39** [comment]
Salut Donovan !
Effectivement ça fonctionne. Je n'ai pas pensé à relancer un build du frontend (persuadé qu'il était passé avec le script d'install du module). Mais en fait, ça ne semble pas être le cas. Et si on suit la note de version en installant OccHab à la fin, on ne relance pas la commande `npm run build` après. Il faudrait l'ajouter en fin de note de version non ?
Les commandes précédentes elles étaient bien passées puisque `nvm install v10.15.3` est bien dans le script `migration.sh` et `nvm alias default 10.15.3` est bien indiquée dans la note de version.
Merci !

**Comment by camillemonchicourt** [comment]
Je pense quand même que l'installation de nvm v10 n'avait pas fonctionné dans le script de migration. Car l'erreur indique que tu avais la version 8. 
Je vais voir pour l'indiquer dans les notes de version 2.3.0 quitte à ce que cela fasse doublon.
Attention pour le moment une incompatibilité avec la version 7 d'Angular rend le module Dashboard incompatible avec la version 2.3.0 de GeoNature.

**Comment by xavyeah39** [comment]
En fait elle a bien fonctionnée car je n'ai pas relancé les commandes d'install de nodejs v10 (`nvm install v10.15.3` et `nvm alias default 10.15.3`)
A la place j'ai vérifié les versions (et celle active) avec` nvm ls` : j'étais bien passé en 10.15.3 mais j'ai aussi la 8.1.1 d'installée. 
Comme nvm permet de gérer différentes versions de nodej, le front était probablement toujours construit avec la v8.
J'ai donc juste relancé le build du front avec `npm run build` pour régler le soucis.
++

**Comment by camillemonchicourt** [comment]
Donc si je comprends bien, il faudrait juste relancer un npm run build dans le script sh de migration, avant d'installer le module OccHab

**Comment by xavyeah39** [comment]
Je pense oui. Je teste sur une autre instance et je te redis.

**Comment by xavyeah39** [comment]
En fait il y a bien déjà un rebuild du front qui s'execute à la fin du script migration.sh.
Le problème est ailleurs semble-t'il. 

En fait a commande `nvm alias default 10.15.3` qui est sensée nous faire basculé sur la version 10.15.3 est exécutée APRES le script migration.sh (comme elle se situe dans la note de version).
Je dis "sensée" car là ça n'a pas suffit chez moi --> Je vérifie après l'avoir exécutée avec `nvm ls` et surprise : la 10.15.3 est bien installée mais je n'ai pas basculé dessus (toujours sur la 8.1.1). Du coup si je lance `npm run build`, ça ne passe pas.
La solution : j'ai lancé `nvm use 10.15.3` et là c'est bon : je bascule bien sur la 10.15.3 et le build du front se fait correctement.

A mon avis (non-expert) il faudrait ajouter `nvm use 10.15.3` dans le script migration.sh et aussi déplacer la commande `alias default 10.15.3` de la note de version vers ce script (permet de rendre le changement de version persistant) --> ligne 79 après l'install de la v10.15.3. 
Comme cela le rebuild du front en fin de script devrait s'exécuter convenablement et plus de soucis avec l'install OccHab.
En tout cas chez moi ça l'a fait.
++

**Comment by camillemonchicourt** [comment]
Corrigé dans https://github.com/PnX-SI/GeoNature/pull/841 pour Debian 9. 
A venir dans une version corrective.

**Comment by camillemonchicourt** [comment]
Fixé dans la version 2.3.1
