### ISSUE TITLE
pb de renouvellement de certificat https sur les sous domaines

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#833]
Bonjour,

J'ai une erreur lorsque je lance le renouvellement des certificats https pour mes sous domaines geonature/atlas/taxhub/usershub.
J'utilise la même commande que pour la création du certificat (qui avait fonctionné) : 
`sudo certbot certonly --webroot --webroot-path /var/www/html --domain geonature.lashf.org`

Voici ci-dessous le détails de l'erreur. 
Si quelqu'un a déjà rencontré ce pb et a trouvé une solution je suis preneur !
mercii

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for geonature.lashf.org
Using the webroot path /var/www/html for all unmatched domains.
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. geonature.lashf.org (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from https://geonature.lashf.org/.well-known/acme-challenge/-wnCoGuwj3gJ58DFdjDkpcVZiy1_eBJdgHAbWCcCo58 [5.39.93.81]: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p"

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: geonature.lashf.org
   Type:   unauthorized
   Detail: Invalid response from
   https://geonature.lashf.org/.well-known/acme-challenge/IGFwZv0vWoMnWdTe_iW8wtJxUorzORpYti5SLqw7fZQ
   [5.39.93.81]: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML
   2.0//EN\">\n<html><head>\n<title>404 Not
   Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```
Je n'ai pas configuré le fichier `/etc/apache2/sites-available/000-default.conf ` car j'imagine que pour les sous domaines, il n'en a pas besoin mais peut-être que je me trompe ?

**Comment by DonovanMaillard** [comment]
Bonjour Romain, 

En effet, la méthode utilisée ne semble pas adaptée pour nos applis avec une conf apache proxyapass etc. (a priori ca marche surtout pour les applis style php qui ont leur propre index html, mais je suis loin de maitriser le sujet dans le détail). 

Malgré tout. J'ai réussi a contourner le problème de manière temporaire, en créant une conf apache qui réoriente le bot letsencrypt lors du renouvellement. Je désactive tous les sites actifs (sudo a2dissite geonature.conf etc), j'active letsenscrypt.conf, je lance le renouvellement (certbot renew), puis je réactive les sites et désactive la conf apache de letsenscrypt. C'est sans doute pas bien propre. Mais ça marche...

La conf apache que j'utilise pour letsenscrypt est la suivante : 

```
# Renvoi de l'alias pour LetsEncrypt

Alias /.well-known/acme-challenge/ "/var/www/html/.well-known/acme-challenge/"

        ProxyPass /.well-known !
        ProxyPass / http://127.0.0.1:9999/

<Directory "/var/www/html/">
    AllowOverride None
    Options MultiViews Indexes SymLinksIfOwnerMatch IncludesNoExec
    Require method GET POST OPTIONS
</Directory>



```

Ca a aussi fonctionné pour un partenaire. Pour ma part, j'ai fait un script shell qui fait toute cette tambouille toutes les semaines, mes applis sont donc inaccessibles quelques secondes la nuit du dimanche au lundi, mais je n'ai pas à me soucier des renouvellements comme ca.

**Comment by lpofredc** [comment]
As-tu tout simplement essayé. 
```
certbot --domain geonature.lashf.org
```
De mon côté, c'est ce que j'utilise et ça fonctionne sans pb.

Ne veux-tu pas plutôt renouveler ton certificat plutôt que d'en créer un nouveau (je vois qu'il expire au 25/12)? En ce cas, simplement un `certbot renew` devrait renouveler tout tes certificats le nécessitant.

Sinon, logiquement, remplacer `/var/www/html` par le chemin du build de ton front devrait surement résoudre le pb, puisque c'est ce dossier qui est diffusé par ton serveur web (geonature étant à la racine de ton sous-domaine).

**Comment by RomainBaghi** [comment]
Bonjour, 
Alors merci beaucoup pour vos réponses et il s'avère que la commande :
`certbot --domain geonature.lashf.org`
a fonctionné, sans que je touche quoique ce soit du reste !

**Comment by camillemonchicourt** [comment]
OK tant mieux. 
Sujet périphérique à GeoNature mais tant mieux si c'est solutionné.

**Comment by DonovanMaillard** [comment]
Juste pour informer @xavyeah39  de cette possibilité, qui nous simplifiera bien les choses à tous les deux!

**Comment by xavyeah39** [comment]
Yes merci @DonovanMaillard . Et merci @lpofredc  pour l'astuce. 
Le dernier renouvellement m'a fait un peu galérer de nouveau mais j'ai solutionné/simplifié avec cette commande chez moi (qui semble faire le job aussi) : `certbot renew --dry-run >/dev/null 2>&1`
