### ISSUE TITLE
Option d'exclusion d'export d'une donnée en synthèse

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature#835]
Un besoin exprimé dans notre milieu associatif, en raison de conventions avec des partenaires, c'est d'exclure leurs données de tout export, transmission de données (nous n'en avons l'usage que pour des besoins internes). D'autres sont-ils dans cette situation. 

Ce qui peut être envisagé dans ce cas de figure, c'est un champ booléen dans l'export et éventuellement un dictionnaire de règles appelé par un trigger lors des `insert` & `update` dans la synthèse.

**Comment by camillemonchicourt** [comment]
Hum hum, je vois pas trop un champs booléen où ?
Je pense qu'il vaudrait mieux gérer ça de manière plus générique et globale, pour ne pas faire de cas particulier, au niveau du JDD avec les notions existantes de publiques/privées et de niveau de diffusion.

**Comment by jbdesbas** [comment]
OK aussi pour gérer ça plutôt au niveau des métadonnées. L'ajout du système _Attributs additionnels_ ("clé-valeur") du SINP aux JDD permettrait de gérer ce genre de cas.

**Comment by lpofredc** [comment]
Ben oui... en effet, ça semble plus cohérent. Merci!
