### ISSUE TITLE
Erreur compilation de typescript : '"moveend"' is not assignable to parameter of type '"tileunload" | "tileloadstart" | "tileload"'.

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/GeoNature#836]
Après avoir regénéré les nodes_modules, la compilation en type script lance l'erreur suivante : 

`
ERROR in src/app/GN2CommonModule/map/map.service.ts(213,22): error TS2345: Argument of type '"moveend"' is not assignable to parameter of type '"tileunload" | "tileloadstart" | "tileload"'.
src/app/GN2CommonModule/map/marker/marker.component.ts(91,15): error TS2345: Argument of type '"moveend"' is not assignable to parameter of type '"tileunload" | "tileloadstart" | "tileload"'.
`

Le correctif suivant fonctionne mais je ne suis pas sur que ce soit une bonne idée de supprimer le typage
`
    marker.on('moveend', (event: MouseEvent) => {
 `

`
  marker.on('moveend', (event) => {
`

**Comment by camillemonchicourt** [comment]
Quelle version ? Branche ``Develop`` ?

**Comment by amandine-sahl** [comment]
Sur la 2.3.0

**Comment by jbrieuclp** [comment]
Et si tu type la fonction `createMarker(x, y, isDraggable): Marker`, là on lui indique que l'event est sur un Marker pas un TileLayer...
https://github.com/PnX-SI/GeoNature/blob/4fb642564767a1c0b23e0b9960806b1d624ad43a/frontend/src/app/GN2CommonModule/map/map.service.ts#L141
