### ISSUE TITLE
Erreur lors d'une nouvelle installation en 2.3.0

### ISSUE THREAD

**Issue by mgageo** [PnX-SI/GeoNature#837]
Bonsoir à tous et bonne année et plein de succès dans tous vos projets,

Je viens d'installer sur Debian 9.11 "fraiche" la version 2.3.0.
J'ai une erreur
```
> geonature@0.0.0 build /home/geonatureadmin/geonature/frontend
> ng build --prod --aot=false --build-optimizer=false

You are running version v6.17.1 of Node.js, which is not supported by Angular CLI v6.
The official Node.js version that is supported is 8.9 and greater.

Please visit https://nodejs.org/en/ to find instructions on how to update Node.js.

npm ERR! Linux 4.9.0-11-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
```
Cela ressemble étrangement à https://github.com/PnX-SI/GeoNature/issues/832

J'applique la même correction et je reprends comment l'installation ?

Marc

**Comment by camillemonchicourt** [comment]
Oui je pense que vous pouvez suivre ce qui est indiqué dans cet autre ticket. Et nous dire car on n'a pas rencontré ce problème lors de nos tests d'installation et de mise à jour de la 2.3.0.

**Comment by mgageo** [comment]
Est-il possible d'avoir l'install-all.log d'une installation réussie ?
Je voudrais faire une comparaison avec le mien : https://curl.libriciel.fr/Gtasc/install-all.log
Ligne 3242, ça parle de la version 6.x LTS Boron
`## Installing the NodeSource Node.js 6.x LTS Boron repo...


## Populating apt-get cache...

+ apt-get update
Atteint:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://ftp.fr.debian.org/debian stretch InRelease
Atteint:3 http://ftp.fr.debian.org/debian stretch-updates InRelease
Atteint:4 http://ftp.fr.debian.org/debian stretch Release
Lecture des listes de paquets…

## Installing packages required for setup: apt-transport-https...

+ apt-get install -y apt-transport-https > /dev/null 2>&1

## Confirming "stretch" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/stretch/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK`

**Comment by camillemonchicourt** [comment]
Je pense qu'il y a un problème dans le install_all.sh qui indique d'installer NodeJS 6 alors que l'application doit désormais fonctionner sur la version 10 (voit ticket 832). C'est peut-être une erreur de notre part qui sera corrigée dans une version corrective prochaine.

**Comment by xavyeah39** [comment]
Bonjour,
Tout comme moi, tu es peut-être encore sur la version 8.1.1 de NodeJS.

- Pour vérifier ça, lancer la commande `nvm ls` qui devrait indiquer les différentes versions de node installées, celle par défaut et celle qui est active (->). Ca devrait ressembler à ça : 
![node_v8](https://user-images.githubusercontent.com/16793813/72200953-95e38c80-344f-11ea-8865-750fc6ab4340.png)

- Si c'est le bien le cas, lancer les  commandes suivantes pour basculer sur NodeJS v10.15.3 : 
```
nvm use 10.15.3
nvm alias default 10.15.3
```

- Re-vérifier avec `nvm ls` et cette fois ça devrait resembler à ça : 
![node_v10](https://user-images.githubusercontent.com/16793813/72201052-5ec1ab00-3450-11ea-9c4d-2fc496408572.png)

- Ensuite, reprendre la fin de la note de version et relancer l'install du module OccHab : 
```
cd /home/`whoami`/geonature/backend
source venv/bin/activate 
geonature install_gn_module /home/`whoami`/geonature/contrib/gn_module_occhab /occhab
```

- Enfin relancer le build du frontend : 
```
cd /home/`whoami`/geonature/frontend
npm run build
```

Normalement plus d'erreurs dans les logs et OccHab devrait fonctionner.

Fais-nous un retour. Si ça règle le problème on remettra au clair dans la note de version (ce sera plus clair que dans #832 )
a+

**Comment by mgageo** [comment]
Ma version de npm en fin d'installation est bonne
[https://i.imgur.com/nFq4bSF.png](url)

**Comment by mgageo** [comment]
En fin d'installation la version de npm est bonne
![image](https://user-images.githubusercontent.com/2681495/72204385-97c14600-3477-11ea-97ac-063fed562533.png)
et la suite n'est pas concluante
![image](https://user-images.githubusercontent.com/2681495/72204416-fedefa80-3477-11ea-9ad5-70255080d165.png)

Suite à un
./install_app.sh 2>&1 | tee install_app.log
geonature est fonctionnel

**Comment by sogalgeeko** [comment]
Hi,
Just for the record, I encountered the same problem, after an apparently successful install, the *dist* dir was absent from *$HOME/geonature/frontend*.
The following commands solved the problem (on Debian 9.11):

```
nvm use 10.15.3
nvm alias default 10.15.3
cd geonature/backend/
source venv/bin/activate
geonature install_gn_module /home/`whoami`/geonature/contrib/gn_module_occhab /occhab
cd /home/`whoami`/geonature/frontend
npm run build
```

**Comment by camillemonchicourt** [comment]
Corrigé dans https://github.com/PnX-SI/GeoNature/pull/841, pour Debian 9. 
A venir dans une version corrective.

**Comment by camillemonchicourt** [comment]
Fixé dans la version 2.3.1

**Comment by DonovanMaillard** [comment]
Sans doute des pistes pour #1190. Voir aussi #832

**Comment by DonovanMaillard** [comment]
Idem #1242
