### ISSUE TITLE
flask-admin non sécurisé

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature#839]
L'accès aux outils d'administration flask-admin ne sont pas protégé. On peut y accéder sans connexion.
cf. http://demo.geonature.fr/geonature/api/admin/

**Comment by sogalgeeko** [comment]
C'est en effet un problème assez important qui donne accès aux informations et permet de les supprimer. L'accès à cet URL doit être limitée à l'administrateur de Geonature ou renvoyer vers la page d'authentification.
En attendant que cela soit corrigé niveau applicatif, j'ai mis une authentification Apache en place sur l'instance qu'on est en train de monter:
```
mkdir /etc/apache2/passwd
htpasswd -c /etc/apache2/passwd/geonature admin
vim /etc/apache2/sites-enabled/geonature.conf
```
ajouter:
```
<Location /geonature/api/admin>
AuthType Basic
AuthName "Restricted Area"
AuthBasicProvider file
AuthUserFile "/etc/apache2/passwd/geonature"
Require user admin
</Location>
```
Aux développeurs: vous devriez ajouter un avertissement dans la documentation, le temps que le correctif soit en place, histoire que d'autres utilisateurs ne mettent pas en ligne des instances Geonature non sécurisées.

**Comment by camillemonchicourt** [comment]
Oui c'était le cas précédemment, il faut que l'on regarde ce qui a sauté.

**Comment by TheoLechemia** [comment]
Non ça n'a jamais été le cas. Le système d'authentification "maison" mis en place n'a pas été branché sur les outils flask-admin

**Comment by camillemonchicourt** [comment]
https://github.com/PnX-SI/GeoNature/commit/7c2fe12e506270e42cfa11d2708993da71f2fdf0

**Comment by camillemonchicourt** [comment]
Fait dans la 2.9.0.
