### ISSUE TITLE
Import et saisie de données sans géométrie

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#845]
Le standard Occtax définit la possibilité de stocker des données sans géométrie précise.
La donnée doit fournir à minima un rattachement géographique parmi les les types de géometrie suivants:
- commune (code insee + nom de la commune)
- département (code département)
- région (code région)
- maille (code maille)

A partir de cette info, il faut retrouver la correspondance avec le ``ref_geo`` de GeoNature. Un nouveau champs sera créé dans la synthese, on y stockera l'``id_area`` du ``ref_geo`` de la données.
Si la donnée comporte plusieurs rattachement, on prend le ``type_info_geo = 1`` pour calculer les autres rattachements (permet d'éviter les erreurs de rattachement du fournisseur de données).
Les rattachements **calculés et fournies** doivent être stockés.
Les rattachement calculés seront stockés dans la table ``synthese.cor_area_synthese``. Se pose la question du stockage de l'information des rattachement fournis ? Rajouter des champs dans la table synthese ? Une autre table de correspondance ? Ou est-ce que le fichier source suffit ?

La question de la saisie sera traitée dans un second temps. Dans un module dédié (biblio) ?

Voir note sur le rattachement géographique du SINP.

**Comment by jbdesbas** [comment]
Je ne sais pas comment c'est géré dans le SINP, mais le mécanisme de rattachement implique de stocker les différents millésimes des référentiels administratifs, les fusions de communes pouvant être assez fréquents par moments.

**Comment by TheoLechemia** [comment]
Ticket à diviser en plusieurs taches
- [ ] Modélisation en base (ajout champs id_area, double stockage de la geom ?)
- [ ] Ajout des couches départements et régions dans la ref_geo
- [ ] Modification du module d'import pour implémenter le rattachement
- [ ] Modification de l'API Synthese (aggrégation des données rattachées)
- [ ] Gestion de l'affichage carto ( aggrégation et affichage différencié - mailles/communes/departements)
- [ ] Gestion des exports

**Comment by camillemonchicourt** [comment]
Amorcé dans la version 2.4.1. 
Pour le rattachement on s'est posé la question du stockage des géométrie dans la table ``gn_synthese.synthese``. Il nous a semblé qu'il n'y a une bonne réponse et on est parti sur le fait de stocker un ``id_area`` mais aussi la géométrie de l'objet de rattachement. Cela fait dupliquer la géométrie mais celle-ci a un rôle central pour les calculs des zonages, de la sensibilité, les exports, l'affichage etc... A voir à l'usage.
