### ISSUE TITLE
Fiche info JDD et CA

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#846]
Faire des fiches info pour les JDD et CA.
Elles récapituleront:

* Les données attributaires du JDD ou CA
* Le nombre de données
* Le nombre de taxons 
* La bounding-box (?)
* Pour la CA: la liste des JDD associés

Un lien pourra être fait avec le module d'import (controlé par un paramètre - necessite son intégration dans le coeur ?).
La fiche info JDD et CA récapitule tous les imports réalisé.
Cette fiche doit être exportable en PDF (CF certificat de dépôt par étude pour projet DEPOBIO).

**Comment by camillemonchicourt** [comment]
Ajouter une icône (œil) pour chaque jeu de données sur le tableau des cadres / jeux de données.

Au clic sur cette icône, afficher une nouvelle page comprenant une synthèse des informations (nombre de taxons, nombre d’espèces) du jeu de données.

+ Vérifier les droits avec le CRUVED de l’utilisateur.

Voir https://github.com/PnX-SI/GeoNature/pull/864

**Comment by jpanijel** [comment]
Est-il possible d'avoir des CA qui combinent différents types de JDD Taxons et Habitats ?
Dans ce cas, je trouve qu'il serait intéressant de prévoir une icone supplémentaire au niveau de la fiche CA qui indiquerait le type de jeux de données associés > Taxons ou Habitats.

**Comment by jpanijel** [comment]
**Besoin GINCO / DEPOBIO**

En tant qu’utilisateur de l'application, je veux pouvoir visualiser la fiche récapitulative d’un cadre d’acquisition de données pour avoir une vue synthétique des données qui y sont associées.

**Spécifications**

le gabarit de visualisation d’un CA doit correspondre à une page de type Dashboard intégrant différents “modules” . 
On pourrait se baser sur un template Bootstrap tout fait pour aller plus vite;

Ex : (https://themes.getbootstrap.com/preview/?theme_id=6063) 

Widgets attendus sur la page : 
- Nb de jeux de données associés au CA
- NB de Taxons (ie total de taxons distincts sur l’ensemble des JDD associés au CA dans la Synthèse)
- Nb d’observations (ie total d’observation sur l’ensemble des JDD associés au CA dans la Synthèse)
- Fiche descriptive du CA
- Liste des jeux de données associés au cadre avec liens de visualisation
- Export PDF

Priorité 2 : 
- Zone géographique (carte avec bounding box des JDD associés au CA)
[Liste champs MTD_SINP_CA_export.xlsx](https://github.com/PnX-SI/GeoNature/files/4358961/Liste.champs.MTD_SINP_CA_export.xlsx)

- Répartition des espèces (camembert avec pourcentages de répartition des taxons par règne/famille…)
- NB d’Habitats (ie total d'Habitats distincts sur l’ensemble des JDD associés au CA dans OccHab)

Champs figurant sur la fiche descriptive : 
- Il faut reprendre tous les champs de MTD INPN plus ceux de GeoNature. 
- Il semble que certains champs INPN ne soient pas encore dans la base GeoNature, notamment : Instance MTD, statut d'avancement et attributs additionnels. **A vérifier**

Structuration des champs dans la fiche descriptive : voir pièce jointe

Gabarit graphique : voir pièce jointe
![Dash_CA](https://user-images.githubusercontent.com/56294090/77155146-67141300-6a9d-11ea-846d-695a3a5319f4.png)

**Comment by TheoLechemia** [comment]
> Est-il possible d'avoir des CA qui combinent différents types de JDD Taxons et Habitats ?

Rien ne l'empêche au niveau BDD.
En revanche il n'y a pas de champs dans la table des JDD qui informe du rattachement de celui-ci au standard "Occurrence d'habitat" ou "Habitat", si ce n'est leur rattachement au module de saisi Occtax ou Occhab (gn_commons.cor_module_dataset), mais ce n'est pas suffisant (cf cas d'un JDD qui appartient à un autre module de saisi qui n'est pas Occtax mais qui concerne des taxons).
Que dit le standard metadonnée sur cette question ?

**Comment by jpanijel** [comment]
il y a un champ spécifique avec une nomenclature pour ce point : TypeDonneesValue

**Comment by camillemonchicourt** [comment]
Utiliser un thème Bootstrap est intéressant pour faire une application complète. Là juste pour une page web, ça va rendre le truc plus complexe et plus difficile à ajuster. On a déjà ce qu'il faut pour faire des blocs et du responsive dans Bootstrap. Et pour les graphiques, on a ChartJS utilisé par le Dashboard.

La première info sur la page devrait être le nom du CA, en gros en titre : 
"CADRE D'ACQUISITION - NOM-DU-CA"

Pour les champs, il faudrait identifier puis ajouter dans la BDD : 
- Les champs du standard MTD qu'on avait pas encore implémenté
- Les champs du standard MTD à ajouter du aux nouvelles versions du standard

**Comment by camillemonchicourt** [comment]
Fait sur : https://github.com/PnX-SI/GeoNature/pull/864

Aperçu : 

![image](https://user-images.githubusercontent.com/4418840/82305201-a2f42780-99bd-11ea-8e2e-e5dfcdbb8cb1.png)

**Comment by camillemonchicourt** [comment]
Première version de s fiches JDD et CA intégrées dans la 2.4.0.
