### ISSUE TITLE
Occtax - Calcul altitude non postée

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#848]
Dans le module web Occtax, une altitude min et max est calculée automatiquement dans le formulaire et posté à la BDD.

Mais si on alimente Occtax sans passer par le formulaire Web, on n'a pas l'altitude calculée. 
C'est le cas de Occtax-mobile notamment.

Quand on ne poste pas d'altitude, il faudrait qu'elle soit calculée automatiquement. Avec une valeur par défaut dans le champs ? Il faut certainement plutôt faire un trigger car il faut disposer du geom pour calculer altitude_min et altitude_max.

**Comment by TheoLechemia** [comment]
Fait en trigger.
