### ISSUE TITLE
Enrichir t_modules et son API pour les applications mobiles

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#852]
Ajouter des champs dans la table ``gn_commons.t_modules`` pour pouvoir indiquer les éventuelles applications mobiles associées (numéro APK et chemin) et les ajouter à l'API des modules.

Pour chaque module GeoNature, on pourra ainsi indiquer si il a une application mobile correspondante, son numéro de dernière version et le chemin de l'APK (relatif au dossier ``/static/`` de GeoNature ? Comment rapatrier le contenu des APK quand on met à jour GeoNature ?)

Comment faire pour l'application Sync-mobile qui ne correspond à aucun module dans GeoNature ? La renseigner dans le module global ``GeoNature`` ?

**Comment by TheoLechemia** [comment]
On en a discuté avec Gil, on est plus partant pour faire une autre table ``gn_commons.t_mobile_apps``. On commence a beaucoup torde la table ``gn_commons.t_modules`` qui est par ailleurs très centrale dans l'installation et l'affichage des modules.
Pour la localisation des APK, on peut mettre 2 champs: un relatif ``relativ_path_apk`` pour les modules du coeur qui va taper dans le répertoire ``static`` (ça veut dire qu'il est derrière `/api`), et un ``url_apk`` pour les modules externes ?

**Comment by camillemonchicourt** [comment]
Oui bien vu.
Avec une clé étrangère optionnelle vers t_module dans cette table, pour pouvoir retrouver l'appli éventuelle d'un module en passant son code_module.
Dans cette table il faudrait aussi un code_app fixe en plus d'un id.

**Comment by TheoLechemia** [comment]
Fait dans une table ``gn_commons.t_mobile_apps``. La colonne ``app_code`` permet de retrouver l'application via son code. Pas de clé étrangère vers ``gn_commons.t_modules`` car une application mobile n'est pas forcément relié à un module GN.
On fait appel à la route comme ceci: ( @sgrimault )
`http://URL_API/gn_commons/t_mobile_apps` -> toutes les apps
`http://URL_API/gn_commons/t_mobile_apps?app_code=OCCTAX` -> seulement l'app OCCTAX

**Comment by camillemonchicourt** [comment]
OK merci, je pensais qu'on pouvait avoir une clé vers t_modules, renseignée uniquement quand une application mobile correspond à un module et sinon la laisser vide. Pour pouvoir retrouver les infos d'une application mobile à partir de son module_code.
Mais c'est peut-être pas utile.
En tout cas si on passe par le code de l'application et non du module alors il faut bien tous avoir le même app_code car il sera écrit en dur dans l'application mobile.

A voir à quel moment on ajoutera des lignes dans cette table pour Occtax-mobile et Sync-mobile avec leurs codes.

Pour le chemin de l'APK on pourrait gérer au niveau de l'API de t_mobile_apps pour que celle-ci renvoit toujours une URL complète selon si on a renseigné le chemin absolu ou relatif (en recréant le chemin absolu à partir du paramètre GeoNature qui indique l'URL de GeoNature.

**Comment by TheoLechemia** [comment]
> OK merci, je pensais qu'on pouvait avoir une clé vers t_modules, renseignée uniquement quand une application mobile correspond à un module et sinon la laisser vide

Si on la laisse vide, on peut pas retrouver une application par son code du coup.

> Pour le chemin de l'APK on pourrait gérer au niveau de l'API de t_mobile_apps pour que celle-ci renvoit toujours une URL complète selon si on a renseigné le chemin absolu ou relatif (en recréant le chemin absolu à partir du paramètre GeoNature qui indique l'URL de GeoNature.

Oui, il faut se mettre d'accord sur l'emplacement. Il y a deux endroit accessibles en HTTP: le répertoire ``backend/static`` ou le répertoire ``frontend/dist``

**Comment by camillemonchicourt** [comment]
Table ajoutée dans la version en développement.

```SQL
CREATE TABLE gn_commons.t_mobile_apps(
  id_mobile_app serial,
  app_code character varying(30),
  relative_path_apk character varying(255),
  url_apk character varying(255),
  package character varying(255),
  version_code character varying(10)
);

COMMENT ON COLUMN gn_commons.t_mobile_apps.app_code IS 'Code de l''application mobile. Pas de FK vers t_modules car une application mobile ne correspond pas forcement à un module GN';

ALTER TABLE ONLY gn_commons.t_mobile_apps
    ADD CONSTRAINT pk_t_moobile_apps PRIMARY KEY (id_mobile_app);

ALTER TABLE gn_commons.t_mobile_apps
    ADD CONSTRAINT unique_t_mobile_apps_app_code UNIQUE (app_code);
```

Avec les routes qui vont avec (``geonature/api/gn_commons/t_mobile_apps``...).

**Comment by camillemonchicourt** [comment]
La route ``geonature/api/gn_commons/t_mobile_apps?app_code={{app_code}}`` récupère le fichier de configuration de l'application. Celui-ci doit s'appeler "settings.json" et se trouver au même niveau que l'APK.

Il n'existe plus qu'une clé ``url_apk`` qui donne l'URL complète de téléchargement de l'APK. Celui-ci est accessible en HTTP, donc à mon sens il n'y a pas besoin d'une autre route pour le téléchargement de l'APK.

Petit détail, si on demande la route ``geonature/api/gn_commons/t_mobile_apps?app_code={{app_code}}`` on retourne un dictionnaire.
Si on demande la route sans la querystring ``geonature/api/gn_commons/t_mobile_apps`` on retourne un tableau.

Exemple de ce que renvoie l'API : 

http://mongeonature.fr/gn_commons/t_mobile_apps?app_code=OCCTAX
```json
{
  "id_mobile_app": 1, 
   "app_code": "OCCTAX", 
   "url_apk": "http://url.fr/static/mobile/occtax/my_apk.apk", 
   "package": "lala", 
   "version_code": "40", 
   "settings": {"la": "la"}
}
```

http://mongeonature.fr/gn_commons/t_mobile_apps
```json
[
  {
   "id_mobile_app": 1, 
   "app_code": "OCCTAX", 
   "url_apk": "http://url.fr/static/mobile/occtax/my_apk.apk", 
   "package": "lala", 
   "version_code": "40", 
   "settings": {"la": "la"}
  }, 
  {
  "id_mobile_app": 2, 
  "app_code": "LA", 
  "url_apk": "la", 
  "package": "lala", 
  "version_code": 40, 
  "settings":  
    {"sett_1": "lala"}
  }]
```

**Comment by camillemonchicourt** [comment]
OK dans 2.4.0
