### ISSUE TITLE
Version 2.3.1 : erreur en finalisation de l'installation

### ISSUE THREAD

**Issue by mgageo** [PnX-SI/GeoNature#855]
Bonjour à tous,

En fin d'installation il est indiqué de recharger la configuration apache, lors de ce rechargement j'ai une erreur

Enabling site usershub.
To activate the new configuration, you need to run:
  systemctl reload apache2
default -> v10.15.3
L'installation est terminée!
geonatureadmin@geonature:~$ systemctl reload apache2
Failed to reload apache2.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
See system logs and 'systemctl status apache2.service' for details.
geonatureadmin@geonature:~$

Après reboot, et un http 403 sur http://192.168.10.15/geonature
j'ai ce message dans error.log

[Wed Feb 26 07:37:23.683092 2020] [mpm_event:notice] [pid 510:tid 140586389786688] AH00489: Apache/2.4.25 (Debian) mod_wsgi/4.5.11 Python/2.7 mod_perl/2.0.10 Perl/v5.24.1 configured -- resuming normal operations
[Wed Feb 26 07:37:23.767487 2020] [core:notice] [pid 510:tid 140586389786688] AH00094: Command line: '/usr/sbin/apache2'
[Wed Feb 26 07:39:13.546241 2020] [authz_core:error] [pid 512:tid 140586276763392] [client 192.168.10.1:54880] AH01630: client denied by server configuration: /home/geonatureadmin/geonature/frontend/dist
[Wed Feb 26 07:44:34.865143 2020] [authz_core:error] [pid 512:tid 140586259977984] [client 192.168.10.1:55004] AH01630: client denied by server configuration: /home/geonatureadmin/geonature/frontend/dist
root@geonature:/var/log/apache2#

**Comment by jbrieuclp** [comment]
Tu n'as pas l'air d'être logué en root, réessayes la commande avec sudo :`sudo systemctl reload apache2`

**Comment by camillemonchicourt** [comment]
Je me demande plutôt si vous n'avez pas fait des commandes en tant qu'utilisateur "root", ce qu'il ne faut pas du tout faire, au risque que l'utilisateur courant ne puisse pas accéder à l'application ?

**Comment by mgageo** [comment]
Jean-Brieuc,,
la commande avec sudo passe bien mais j'ai toujours un http 403
Camille,
Je pense bien avoir lancé l'installation sous l'utilisateur geonatureadmin
Le log de l'install est disponible à cette adresse https://curl.libriciel.fr/a6K0z/install-all.log

**Comment by jbrieuclp** [comment]
C'est une installe sur un serveur vide ? 
Il y a de nombreux paquet qui n'ont pu être installé (ex: `Impossible d'initialiser la connexion à ftp.fr.debian.org: 80 (2a01:e0c:1:1598::2). - connect (101: Le réseau n'est pas accessible) [IP : 2a01:e0c:1:1598::2 80]
Err:93 http://ftp.fr.debian.org/debian stretch/main amd64 liburiparser-dev amd64 0.8.4-1+deb9u1`) le paquet postgis ne semble pas avoir été installé. 
il y a ça qui traîne `ERROR: Module mod_pyth does not exist!`, donc c'est pas étonnant qu'apache galère.

Moi je relancerais une installe globale tout en surveillant dans le log si les paquets manquants ont bien été installés, il faudrait que `ftp.fr.debian.org` soit de nouveau joignable...

**Comment by mgageo** [comment]
Je viens de ré-installer la machine virtuelle puis geonature.
Avec le 'sudo systemctl reload apache2', le service geonature est disponible.
Est-il possible que l'installation s'arrête sur ce genre d'erreur ? (avec un set -e par exemple).
Merci pour votre aide
