### ISSUE TITLE
Role créé à partir de "Userhub" non accessible à partir de "Backoffice GeoNature - Administration des permissions" 

### ISSUE THREAD

**Issue by jacquesnicolau** [PnX-SI/GeoNature#856]
Bonjour,

J'ai créé un nouveau rôle à partir de Userhub -> Groupes -> Ajouter un groupe
Je souhaite attribuer des droits spécifiques à ce rôle à partir de "Backoffice GeoNature - Administration des permissions (CRUVED)" mais le nouveau rôle n'apparait pas dans la liste des rôles.
Y-a-t-'il une opération spécifique à réaliser ?

Merci

**Comment by camillemonchicourt** [comment]
Bonjour,
Pour pouvoir attribuer des permissions (CRUVED) à un rôle (utilisateur ou groupe) dans GeoNature, il faut d'abord lui attribuer un profil de "Lecteur" pour l'application GeoNature dans UsersHub.

Si ce n'est pas déjà le cas, il faut que l'on ajoute cette info dans la doc http://docs.geonature.fr/admin-manual.html#gestion-des-droits

**Comment by jacquesnicolau** [comment]
Bonjour,

merci pour cette information
J'ai ajouté le nouveau groupe au groupe "Agents en poste"
Il est effectivement alors possible de lui attribuer des permissions

Merci pour votre aide

Bien cordialement
Email Signature

<http://www.corse.developpement-durable.gouv.fr/> 	*Jacques NICOLAU
* Chef SICP
Direction Régionale de l'Environnement, de l'Aménagement et du Logement 
de Corse SICP
Téléphone fixe :04 95 51 79 87 <tel:04%2095%2051%2079%2087>
http://www.corse.developpement-durable.gouv.fr/

Pensez environnement !
N'imprimez ce message que si c'est vraiment nécessaire
	logo

**Comment by camillemonchicourt** [comment]
Précision ajoutée dans la doc : https://github.com/PnX-SI/GeoNature/commit/8364b1ec27dc400f393e629acf4de2786bc361f2
