### ISSUE TITLE
Problème sur la montée de version 2.3.0->2.3.2

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#857]
En passant de la 2.3.0 à la 2.3.2, npm run build renvoie l'erreur suivante : 

ENOENT: no such file or directory, stat '/home/outilsflavia/geonature/frontend/src/tsconfig.app.json'

Je ne me trompe pas, on peut bien ne pas passer par la 2.3.1 dans la mesure ou i n'y a pas de changements en BDD?

**Comment by TheoLechemia** [comment]
Oui pas de changement en base. 
Essaye de lancer à la main la commande et envoie le retour.
`geonature geonature generate_frontend_tsconfig_app`
Je veux bien le log complet du "migrate.sh" aussi

**Comment by camillemonchicourt** [comment]
Même quand il y a des changements en base, il n'est pas nécessaire d'installer les versions intermédiaires, uniquement de bien suivre les éventuelles notes de version intermédiaires et notamment les scripts successifs de mise à jour de la BDD.

**Comment by DonovanMaillard** [comment]
En fait, il s'agit précisément du même problème qu'évoqué pour la MAJ d'UsersHub ce matin. 

Il m'a fallu lancer avant la mAJ :
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install python3-pip
sudo pip3 install virtualenv==20.0.1
```

Une fois virtualenv bien installé pour python3, ca roule! 

Merci à vous!

**Comment by DonovanMaillard** [comment]
merci théo de m'avoir demandé le log complet, j'ai vu trainer un "deactivate, la commande n'existe pas" qui m'a sorti de là

**Comment by camillemonchicourt** [comment]
OK, à voir si il faut ajouter ça dans la doc ou bien dans les scripts d'installation pour éviter à d'autres le soucis ?

**Comment by TheoLechemia** [comment]
ça concerne que les migration post 2.3.0. Donc à faire dans les notes de version
