### ISSUE TITLE
association JDD - module dans admin

### ISSUE THREAD

**Issue by lolofr** [PnX-SI/GeoNature#861]
Bonjour,
bravo pour votre excellent travail!
Je tente de m'approprier la chose pour mon association.
Je comprends de #399 qu'un JDD doit être associé à un module (par ex. occtax) pour qu'il puisse être utilisé dans le module (par ex. lors de la saisie d'un relevé taxon).
Or il semble que le cadre destiné à référencer les modules dans le module métadonnées (voir  https://github.com/PnX-SI/GeoNature/issues/399#issuecomment-544708357) ne soit pas fonctionnel (il reste désespéremment vide).
bug constaté sur une installation fraiche v2.3.2 et sur votre site démo.

J'ai contourné le pb en utilisant un SQL que je donne ici à toutes fins utiles
```SQL
INSERT INTO gn_commons.cor_module_dataset
(id_module, id_dataset)
VALUES(4, 4);
```

**Comment by camillemonchicourt** [comment]
Je viens de tester et n'ai pas le problème sur notre GeoNature en production en version 2.3.2, ni sur le GeoNature de démo : 

![image](https://user-images.githubusercontent.com/4418840/75930087-2ba90000-5e72-11ea-9449-72287ed3903b.png)

J'ai juste constaté que parfois le contenu de la liste des modules met un peu de temps à être disponible.
Quel navigateur utilisez-vous ?
La console du navigateur renvoie t-elle des erreurs ?

**Comment by lolofr** [comment]
Le pb semble à première vue aléatoire, possiblement lié à un pb de lenteur de récupération des listes. J'ai testé avec plusieurs config (plusieurs pc, mon mobile, à la maison débit lent, au boulot sur fibre, sur firefox et sur chromium...), parfois cela fonctionne, parfois non. ci-dessous la copie d'écran du JDD "Contact aléatoire tous règnes confondus" du site démo quand cela ne fonctionne pas.
![image](https://user-images.githubusercontent.com/8258712/76111029-dab71a00-5fdf-11ea-9fe0-1cac22116389.png)
Je joins le log chromium de l'élément qui semble correspondre à la boite à dérouler [erreur 403]
[demo.geonature.fr-1583526477947.log](https://github.com/PnX-SI/GeoNature/files/4300285/demo.geonature.fr-1583526477947.log)

après de nombreuses tentatives avec firefox (confirmé sous chromium, les deux sur un ubuntu 18.04 à jour), j'arrive à reproduire le pb de manière consistente :

1. si lors du chargement de la page de connexion initiale, la console est dans l'état suivant :
![Screenshot_20200306_215150__ok](https://user-images.githubusercontent.com/8258712/76122567-9e42e880-5ff6-11ea-872b-362dfad5f9f1.png)
je vais réussir à avoir un affichage correct. Je me déconnecte et au chargement de la page de connection initiale, j'ai la console dans l'état suivant :
![Screenshot_20200306_215632_down](https://user-images.githubusercontent.com/8258712/76122622-c894a600-5ff6-11ea-8659-9a3fe9289771.png)
dans ce cas je n'arrive pas à avoir un affichage correct. Il suffit que je me déconnecte pour avoir de nouveau un état normal.

1. si je m'aperçois que je suis avec la console dans le mauvais état (avec l'erreur 403) sur la page de connexion, il suffit que je recharge cette page pour avoir de nouveau un état normal de la console (et de l'affichage)

1. si je veux regénérer le pb il suffit que je me connecte et que je me redéconnecte (même pas besoin d'aller sur le formulaire métadata) pour revenir à une console anormale avec l'erreur 403 (et si me connecte avoir un affichage anormal). Si au lieu de me connecter je recharge la page, je reviens avec un affichage normal

Voici le détail de la console firefox avec l'erreur 403
[console-export-2020-3-6_21-48-48.txt](https://github.com/PnX-SI/GeoNature/files/4300428/console-export-2020-3-6_21-48-48.txt)
