### ISSUE TITLE
Erreur lors de la création de comptes utilisateurs via le formulaire

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature#862]
Bonjour, 

Je viens d'activer la création de comptes via formulaire sur notre instance, avec validation par un administrateur.

 Avec 2 tests, tout se passe bien au niveau du formulaire, le mail part bien à l'admin, mais lors qu'un admin veut valider, le navigateur lui renvoie l'erreur suivante :

{"msg": "pas d'utilisateur trouv\u00e9 avec le token user demand\u00e9"}

Quelqu'un a-t-il déjà eu ce soucis?

**Comment by camillemonchicourt** [comment]
A priori corrigé dans la 2.5.0 ?

**Comment by jpm-cbna** [comment]
Non, je pense que ce fonctionnement est toujours présent.
C'est normal d'avoir ce message lors du clique sur le lien de l'email si l'utilisateur a été préalablement validé.
Par contre, il serait peut être bien de renvoyer l'utilisateur sur une page d'interface plus sympa...

**Comment by camillemonchicourt** [comment]
Message clarifié dans la version 2.3.4 de UsersHub.
