### ISSUE TITLE
[OBS SANS GEOM] - Modélisation

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#867]
Ajouts des champs en BDD permettant le stockage d'observations rattachées

**Comment by TheoLechemia** [comment]
Pour améliorer les performances de lecture de géométrie rattachées (ou floutées) dans la table ``ref_geo.l_areas`` on crée un colonne ``geojson_4326``. Cette colonne pourra directement être mobilisée par la synthese pour les affichages cartographique sans pré-calcul.

**Comment by gildeluermoz** [comment]
:+1: 
Bonne approche il me semble. Ces geom de rattachement sont potentiellement lourdes (complexes avec bcp de sommets) et peuvent générer de gros gros calculs spatiaux si fort taux de duplication. Une solution de factorisation est essentielle de mon point de vue. IL faudra que la requête spatiale utilise bien cette factorisation des geom.

**Comment by camillemonchicourt** [comment]
Dans la 2.4.1, ajout d'un champs ``id_area_attachment`` dans la table ``gn_synthese.synthese`` permettant d'associer une observation à un zonage dans le référentiel géographique (``ref_geo.l_areas.id_area``). 
Ajout aussi d'un champs ``geojson_4326`` dans ``ref_geo.l_areas`` pour pouvoir leur futur affichage cartographique. Pour le calcul de ce champs, on s'est demandé si on pouvait avoir une commande SQL manuelle à lancer après import de nouveaux zonages et ainsi éviter un nouveau trigger, mais ça nous a semblé risqué si des administrateurs ajoutent ou modifient des zonages avec QGIS ou autre, que le champs ne soit pas calculé dans tous les cas. On a donc mis un trigger sur l'insertion ou le modification de la géométrie d'un zonage.

**Comment by DonovanMaillard** [comment]
`ajout d'une contrainte entre id_nomenclature_type_info_geo et id_area`

Pour les données "anciennes" rentrées sous GN dans les versions précédentes, il n'était pas possible de stocker un id_area. Elles sont donc potentiellement avec un type info géo "rattaché" mais sans id_area pour dire à quoi elles sont rattachées. 

C'était le cas dans l'une de mes instances. La contrainte a été mise en place malgré tout (ce qui me surprend), en revanche je ne peux plus faire d'update sur d'autres champs de ces données sans régler ce problème là. 

A terme je vais voir pour récupérer l'id_area de la commune pour ces données là, puisque sauf erreur tous nos rattachements sont faits à la commune. Reste à voir comment fonctionner pour les fusions de communes (il faut garder les référentiels communes successifs? :/ )

**Comment by camillemonchicourt** [comment]
OK le champs et la contrainte qui va avec ont été ajoutés dans la version 2.4.1.
Voir https://github.com/PnX-SI/GeoNature/blob/master/data/migrations/2.4.0to2.4.1.sql#L9
Je ne comprends pas non plus comment tu as pu passer cette mise à jour en 2.4.1 sans que la BDD ne lève une erreur sur la contrainte ?

**Comment by camillemonchicourt** [comment]
Pour la question du lien avec les référentiels géographiques et de leur historique, on hésite encore un peu sur le sujet.
Pour le moment, on a pris le partie de stocker un ``id_area`` pour avoir un lien, mais de stocker aussi la géométrie de l'area dans la géométrie de l'observation, justement dans le cas où l'area évoluerait. On garderait ainsi sa géométrie originelle dans la géométrie de l'observation.
Aussi car ce serait trop complexe en l'état d'avoir des observations sans géométrie, avec tous les calculs qui sont liées à celle-ci.

Mais à creuser si besoin car pas forcément idéal, en terme de stockage, de performances, d'historique etc...

**Comment by DonovanMaillard** [comment]
Oui, se pose aussi la question des performances. Est ce que si j'ai 150 donnees a la commune la synthese  charge 150 fois la géométrie ? Ou est ce la grippe ne se charge qu'une seule fois?

**Comment by camillemonchicourt** [comment]
Oui l'affichage est un autre sujet, il y a un sujet dédié de mémoire.
Là on va faire en sorte d'agréger les occurrences qui ont une même observation pour ne pas charger 50 fois les mêmes géométries.
Idem pour les données sensibles floutées où se pose la même problématique.

**Comment by jbrieuclp** [comment]
#924

**Comment by jbdesbas** [comment]
Pour moi, une piste pour ce genre de truc sera de creusé au niveau de l'héritage de table de Postgres. Cette fonctionnalité n'est pas (peu ?) utilisée sur GN.
Dans les grandes lignes, on aurait une table mère _synthese_, et deux tables filles _synthese_localisees_ et _synthese_rattachees_ avec chacune un ou des champs supplémentaires par rapport à la table mère (respectivement _geom_ et _id_area_)
Et pour l'usage, pourquoi pas une vue pour avoir facilement les geom (de rattachement ou de saisie)

**Comment by jbrieuclp** [comment]
Salut,
Est-ce que des réflexions ou des travaux sur ce sujet ont eu lieux depuis la fermeture de cette issue ? 
Je viens de faire un check de ma BD résultat : 
- la base Geonature pèse ~32GB ; 
- la table synthèse en bouffe à elle seule plus de 9 178MB (après VACUUM FULL) pour 1 496 338 données; 
- le champ the_geom_4326 prend là dedans 5 866MB (64% de la synthèse) ;
- J'ai 13 622 données rattachées à un id_area (localisées au département ou région uniquement, donc sans prise en compte des données communales). Ces 13 622 occupent 4 621MB (50%) dans la synthèse. 

Donc est-ce que ca reste une super idée de stocker la géométrie en parallèle de l'id_area ? Face à ce constat bien crado j'ai bien ma petite idée... Parce qu'au final, des jointures ça marchent plutôt bien en vrai ;-) Reste à voir côté applicatif ce que ca peut engendrer, mais je suis certain que si l'on se pose pour en discuter il y a moyen de trouver un truc bien plus fonctionnel facilement.

**Comment by camillemonchicourt** [comment]
Au final, on supprime le champs `ref_geo.l_areas.geojson_4326` au profit d'un champs `ref_geo.l_areas.geom_4326`.
Voir https://github.com/PnX-SI/RefGeo/issues/6.
