### ISSUE TITLE
Floutage des données sensibles et privées

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#877]
En fonction du niveau de diffusion définie pour une donnée sensible ou privée, un utilisateur pourra ne voir et exporter la géométrie floutée (dégradée) de l'observation. Dépend du CRUVED de l'utilisateur sur les objets "Sensibilité" et "Données privées".

**Comment by camillemonchicourt** [comment]
Voir peut-être du côté de https://blog.dalibo.com/2019/09/24/postgresql_anonymizer_0.3.html pour la dégradation des données.

**Comment by theodorlobster** [comment]
Bonjour,
Comme évoqué par Camille hier nous pourrions utiliser l'extension en cours de développement PostgreSQL Anonymizer. J'ai défini quelques méthodologies simples pour cela et ces dernières seront en développement dans les semaines à venir (dont à priori je m'occuperai).
Je vous invite à viser le fonctionnement prévu de l'extension et de faire des propositions ici ou sur le gitlab.
Il serait interessant de croiser nos besoins à ceux de la communauté PostgreSQL et Européenne.
