### ISSUE TITLE
Export PDF des fiches de métadonnées CA et JDD

### ISSUE THREAD

**Issue by jpanijel** [PnX-SI/GeoNature#882]
**Besoin**
En tant qu'utilisateur je veux pouvoir exporter la page récapitulative d'un CA ou d'un JDD au format PDF. Au clic sur le bouton Export PDF”, un téléchargement de la fiche au format PDF est proposé.

**Spécifications**
Un export PDF reprend l'ensemble des informations et widgets figurant sur les fiches de métadonnées CA et JDD. 
Il comprend aussi un en-tête et un pied de page.
* L'en-tête comprend : un logo + une image bandeau
* Le pied-de-page comprend : L'url source de la fiche CA dans l'appli + la date de l'export
La mise en page du document est régit par un template python qui appelle un fichier CSS ainsi qu'un fichier de conf ou sont stockés certains paramètres "personnalisables".

**Comment by jpanijel** [comment]
**Besoin Fiche CA**
En tant qu'utilisateur je veux pouvoir exporter la page récapitulative d'un CA au format PDF. Au clic sur le bouton, un téléchargement de la fiche au format PDF est proposé.

Eléments personnalisables :
**En-tête**
* Logo
* Image Bandeau
* Nom de la palette de couleur et 5 codes couleur associés

** Palette couleur SINP
*** Bloc Widget Nb de jdd : #E3EAD2
*** Bloc Widget Nb de taxons : #F0F4CF
*** Bloc Widget Nb d'habitats : #A8BE73
*** Bloc Widget Nb de données : #FEE9CA
*** Traits de séparation : #F69200

** Palette couleur DEPOBIO
*** Bloc Widget Nb de jdd : #E3F7F4
*** Bloc Widget Nb de taxons : #DDF5FE
*** Bloc Widget Nb d'habitats : #B5EBE2
*** Bloc Widget Nb de données : #63D4C1
*** Traits de séparation : #07A9E7

Spécificités DEPOBIO :
* Titre Page : Certificat de dépôt
* Ajout des champs suivants :
** N° de dossier 'TPS' 
** Date de dépôt des JDD ou Date de dépôt du CA
** Depositaire : Nom et organisme de l'utilisateur
** Url publique d'accès aux données du CA (visu et téléchargement)

**Comment by camillemonchicourt** [comment]
OK, pour les spécificités DEPOBIO, il faut voir comment ces champs sont utilisés et comment leur contenu sera géré ?

A voir si ces champs peuvent être généralisés avec un usage plus large, ou si ils sont vraiment spécifiques et à gérer dans un champs générique "Champs additionnels" en jsonb par exemple ?

**Comment by camillemonchicourt** [comment]
En cours. Voir https://github.com/PnX-SI/GeoNature/pull/909

Aperçu : 
![image](https://user-images.githubusercontent.com/4418840/82305505-ff574700-99bd-11ea-8e13-f546ccea3ace.png)

**Comment by camillemonchicourt** [comment]
Première version des exports PDF des fiches JDD et CA intégrées dans la 2.4.0.
