### ISSUE TITLE
 [Synthese]Export metadata/statuts ERROR 414: Request-URI Too Long

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/GeoNature#883]
Lorsque l'on filtre les données avec une emprise d'une certaine complexité. Une erreur 414 est retournée lors de l'export des métdaonnées et des statuts.

Pour éviter cela il faudrait passer par une requête POST plutôt que GET. cf #704

**Comment by camillemonchicourt** [comment]
Complété par https://github.com/PnX-SI/GeoNature/commit/ba8a1c84fff5dfd423891e1665ed63ea29c55662 car il y avait encore des plantages lors de l'export de données de la synthèse quand on intersectant avec des geojson complexes.
