### ISSUE TITLE
Ajout d'un sous-module MTD : Tableau de suivi et de gestion des JDD

### ISSUE THREAD

**Issue by jpanijel** [PnX-SI/GeoNature#889]
En tant qu'utilisateur, je veux dans le contexte SINP avoir une vue globale de l'état des différents jeux de données diffusés dans la synthèse et gérer les échanges de fichiers DEE de ces jeux de données avec la plateforme nationale INPN.

La gestion des JDD et des échanges de fichiers DEE s’inscrivent dans deux workflows distincts.
Le workflow des DEE dépend néanmoins de celui des JDD. Pour générer le fichier DEE, il faut que le JDD soit publié donc partagé sur la plateforme c-a-d visible pas tous les utilisateurs de la plateforme (adhérents/ membres du SINP). 

L'ensemble des spécifications sont rassemblées dans ce document.
[Tableau_JDD_DEE_GeoN.pdf](https://github.com/PnX-SI/GeoNature/files/4427061/Tableau_JDD_DEE_GeoN.pdf)

**Comment by jpanijel** [comment]
En complément voici les informations transmises dans les différents rapports lors des imports dans GINCO.
[Complement_Rapports.pdf](https://github.com/PnX-SI/GeoNature/files/4428169/Complement_Rapports.pdf)

**Comment by camillemonchicourt** [comment]
- A noter que dans GeoNature, toutes les données d'un JDD ne proviennent pas forcément d'un import. Certains JDD n'ont aucune donnée importée mais uniquement des données saisies
- A clarifier l'existence des DSR et DEE potentiellement décorrélées
- A voir comment on souhaite publier/envoyer/transmettre/exporter un JDD vers un partenaire ou l'INPN. On avait évoqué le fait de le rendre inactif avec le champs "active" existant mais ce n'est pas forcément suffisant ou adapté. On peut être en train de construire les données d'un JDD (par saisie ou import) et quand il est terminé, vouloir le transmettre. On peut aussi le compléter ou corriger plus tard et souhaiter le retransmettre. On a d'autres JDD qui ne sont jamais terminés, mais qu'on souhaite transmettre régulièrement. Le mieux est peut-être d'avoir la possibilité de tracer et suivre les transmissions (exports ?) d'un JDD. Sachant qu'un export n'est pas forcément associé/associable à 1 JDD.

**Comment by camillemonchicourt** [comment]
Ce travail a été initié dans la PR https://github.com/PnX-SI/GeoNature/pull/1005, en cours de révision par @TheoLechemia.
C'est plus qu'un sous-module MTD, c'est plutôt une refonte/révision de la liste des métadonnées. 

Aperçu : 
![image](https://user-images.githubusercontent.com/4418840/98674888-c212b700-2359-11eb-8980-1ae91b9dd155.png)

Selon moi, il y a des choses intéressantes, mais aussi certaines qui alourdissent et compliquent la liste des MTD et c'est dommage.

- Les blocs des CA avec leurs JDD sont bien faites et mises en forme
- La liste est enrichie d'informations intéressantes
- Mais il y a des informations peu utiles. Par exemple le champs créateur ne devrait pas apparaitre dans la liste. De plus cette info ne semble pas fonctionner. A virer selon moi car peu utile et alourdit la liste.
- Les acteurs sont affichés pour les CA mais pas pour les JDD, alors qu'ils y sont souvent plus précis. Je les mettrai sur les 2 ou sur aucun
- Le nombre de données d'un CA serait intéressant aussi. 
- Je ne vois pas trop l'intérêt d'afficher la date de création des CA et JDD dans la liste
- Le bloc ACTIONS est complexe
- L'action Afficher dans la synthèse n'est pas fonctionnelle. Elle amène à la Synthèse avec le JDD renseigné dans les filtres, mais la recherche n'est pas lancé donc c'est source d'incompréhension. Le lien doit lancer la recherche en même temps sinon cette fonctionnalité n'est pas pertinente. Par ailleurs, cette action ne devrait pas être masquée quand le JDD est désactivé.
- Pour alléger la liste je propose que les rapports soient téléchargeables depuis la fiche détail d'un JDD et non pas depuis la liste. Ça simplifierait aussi l'ergonomie et l'intuitivité, car là on s'y perd.
- Dans tous les cas, les boutons des 2 rapports sont parfois collés, parfois non : 
![image](https://user-images.githubusercontent.com/4418840/98678116-5e3ebd00-235e-11eb-8e2e-317f9a969058.png)
- Le bouton pour Activer/Désactiver un JDD a un tooltip correspondant à une info et non pas une action. Il faut le changer en "Activer le JDD" / "Désactiver le JDD" pour comprendre que c'est une action.
- Vérifier le CRUVED des actions Supprimer, Modifier, Activer (à baser sur l'action U) car j'ai pas l'impression qu'il soit appliqué. Avec un CRUVED de 131111, j'ai accès à la modification, activation et suppression de tous les CA et JDD, pas normal
- Pour pouvoir importer dans un JDD, il faut vérifier que j'ai les droits d'accéder et d'importer dans ce JDD (= que je l'aurai dans la liste des JDD quand je créé un nouvel import)
- Quand un JDD n'a aucune donnée, on ne peut pas accéder aux rapports. Logique mais autant griser les boutons dans ce cas, et la tooltip "Impossible de télécharger le rapport" laisse penser à une erreur. "Aucune donnée dans ce JDD" serait plus clair.
- L'icône de l'action Importer n'est pas la bonne. Celle-ci correspond à Export. Import a la flèche vers le bas et non vers le haut.

**Comment by TheoLechemia** [comment]
- Ok pour le créateur qui est une info plutôt secondaire. Je le mettrais sur la fiche info.
- Pour les rapport aussi, pourquoi pas. Au même niveau que les exports pdf ça aurait du sens.
- Le bouton "activer" n'est pas nécessaire selon moi. On peut le faire depuis le formulaire. On en a reparlé avec Judith, cette action correspondait initalement à l'action "déposer" dans Depobio, donc encore autre chose. Je l'ai enlevé pour l'instant

> L'icône de l'action Importer n'est pas la bonne. Celle-ci correspond à Export. Import a la flèche vers le bas et non vers le haut.

- Pas sûr ? L'action de télécharger est toujours une fleche vers le bas. Là on a une fleche vers le haut: on envoie les données dans sur le serveur qui est dans les nuages ;)
- J'ai corrigé l'affichage sur la synthèse au pasage.

**Comment by TheoLechemia** [comment]
Le CRUVED sur les actions avait sauté dans la PR en effet. C'est corrigé

**Comment by jpm-cbna** [comment]
À la marge, au niveau ergonomie, je supprimerai le souligné du titre.
Les textes soulignés sont plus difficile à lire.
C'est pourquoi aussi, ils sont souvent supprimé des liens...

**Comment by TheoLechemia** [comment]
Un consensus sur le fait de passer le créateur dans la fiche info et de mettre les acteurs aux deux niveaux (JDD et CA) ?

**Comment by camillemonchicourt** [comment]
- On bascule les rapports dans les fiches détails
- On garde le créateur, mais on le met dans la colonne "Acteurs"
- Ajouter un picto "i" pour accéder à la fiche détail dans les ACTIONS
- ACTIONS : Info / Import / Synthèse / Modifier / Supprimer
- On vire le lien sur l'ID du JDD
- Tooltips : "jeu de données" et non pas "jeux de donnée" ou "jeu de donnée"
- Tableau : visualiser si un JDD est actif ou non
- Icône : Homogénéiser les actions inactives. Passer en disables et gris (opacité 50%)
- Indiquer dans la liste si un JDD est actif ou non (plus tard ?)

**FICHES :**

- Passer RETOUR à gauche
- Ajouter export UUID et sensibilité avec EXPORT PDF
- Ajouter Modifier / Supprimer dans un bloc en-dessous (attention CRUVED)
- Ajouter "IMPORTER DANS JDD" avec les 2 actions précedentes
- Ajouter "Afficher les données dans la Synthèse" avec la carte bounding box
- Faire pareil dans les CA mais avec beaucoup moins d'actions/boutons, ainsi que le bouton DEPOSER
- Liste des imports >> Faire une liste des sources (avec date de dernière observation d'une source)

**DEPOT :** 

- Ajouter un booleen ``finished`` ou ``opened`` dans la table des CA (``true`` par défaut)
- Action ajoutée dans le tableau à côté de "Modifier CA"
- Label customisable
- Quand je dépose un CA, cela désactive tous ses JDD
- Envoi d'une notification au créateur et à la personne connectée (si différent)
- Je ne peux plus y associer de JDD (filtrer la liste des CA du formulaire JDD)

**Comment by camillemonchicourt** [comment]
La partie DEPOT a été intégrée et rendue plus générique, paramétrable et désactivée par défaut.

Reste à voir : 
- Liste des imports >> Faire une liste des sources (avec date de dernière observation d'une source)
- Passer l'action de pouvoir DEPOSER actuellement sur le E, sur le U ou le V
- Pouvoir désactiver (par défaut) le bouton IMPORTER DANS CE JDD de la liste des JDD ainsi que de la fiche d'un JDD, car il pose des soucis de cohérence de CRUVED au niveau du module IMPORT (https://github.com/PnX-SI/gn_module_import/issues/175) et ne fonctionne pas si le module n'est pas installé.

**Comment by camillemonchicourt** [comment]
Cette refonte de la liste des métadonnées a été intégrée dans la version 2.6.0.
Les 2 petits points restants (liste des sources et fermeture des CA) seront traités par ailleurs
