### ISSUE TITLE
Trigger synthese meta_create_date

### ISSUE THREAD

**Issue by jbdesbas** [PnX-SI/GeoNature#895]
Bonjour,

J'ai une petite interrogation concernant le trigger de mise à jour des dates de création et de mise à jour des occurrences dans la synthèse (_fct_trg_meta_dates_change()_). Je comprend bien l’exécution du trigger pour la mise à jour du champs, mais son exécution lors de l'insertion peut poser problème : 
- si l'administrateur explicite une valeur différente pour le champs _creation_date_ lors de l'insertion (lors de migration de base ou insertion de DEE #768 ), celle-ci est fourbement remise à la date du jour (je me suis fait avoir).
- procédure inutile vu que la valeur par défaut du champs est _now()_

Pensez vous que la modification de ce trigger pour une exécution seulement en cas d'UPDATE pourrait poser des problèmes par ailleurs ?

```
CREATE OR REPLACE FUNCTION public.fct_trg_meta_dates_change()
  RETURNS trigger AS
$BODY$
begin
        if(TG_OP = 'INSERT') THEN
                NEW.meta_create_date = NOW();
        ELSIF(TG_OP = 'UPDATE') THEN
                NEW.meta_update_date = NOW();
                if(NEW.meta_create_date IS NULL) THEN
                        NEW.meta_create_date = NOW();
                END IF;
        end IF;
        return NEW;
end;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
```

**Comment by camillemonchicourt** [comment]
Oui bien vu, il faut pouvoir indiquer une date_create différente de celle d'insertion.

Nous aussi ça a écrasé l'info en mettant la date de la migration et c'est pas une bonne chose
