### ISSUE TITLE
Remplacer exports SHP par GeoPackages

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#898]
Le format SHP est galère et peu pratique (multi-fichier, mono-type-géométrique...) et peu pratique. De plus les noms de champs sont limités à 10 caractères ce qui nous a conduit à mettre des noms de champs peu explicites dans l'export de la Synthèse. 

Je propose de le remplacer par le format GeoPackage bien plus pratique (mono-fichier, multi-type-géométrique...) et plus performant sur les gros volumes notamment (voir les tests de @raphael-bres récemment - https://si.ecrins-parcnational.com/blog/2020-02-geojson-shapefile-geopackage.html).

Si certains y tiennent encore, on peut garder les 2, ou proposer l'un ou l'autre en paramètre, mais sans se contraindre à 10 caractères pour les noms de colonnes des exports.

![SHP must die](http://switchfromshapefile.org/images/ban-shapefile.png)

**Comment by jbdesbas** [comment]
Si ça peut aider à la disparition du shapefile 👍👍👍

**Comment by samuelpriou** [comment]
Bonne idée de passer sur du .gpkg

**Comment by camillemonchicourt** [comment]
Export GeoPackages en cours d'intégration dans la libraire Utils-Flask-SQLAlchemy-Geo sur laquelle s'appuie GeoNature : https://github.com/PnX-SI/Utils-Flask-SQLAlchemy-Geo/compare/master...geopackage et son intégration dans le module Export : https://github.com/PnX-SI/gn_module_export/issues/54

**Comment by camillemonchicourt** [comment]
Dans la 2.6.0 à venir, on a ajouté la possibilité d'exporter en GPKG.
Il est toujours possible d'activer les exports en SHP, mais par défaut on est passé sur le GPKG.
Mais lors des premiers tests, @TheoLechemia a identifié que les exports en GPKG étaient plus longs à se générer, et du coup n'aboutissent même avec un volume assez limité de données (10.000 ?).

Pas certain du coup que cela soit pertinent de remplacer le SHP par le GPKG par défaut.
@amandine-sahl ?

**Comment by camillemonchicourt** [comment]
En attendant d'avoir plus de retours sur les performances des exports en GPKG, on a remis le SHP par défaut au niveau des exports SIG des modules Occtax, Occhab et Synthèse.
Il est possible de remplacer (ou ajouter) le GPKG, dans la configuration de GeoNature. 
On est preneur de retours de tests sur le sujet.
