### ISSUE TITLE
Désinstaller un module

### ISSUE THREAD

**Issue by Idaline** [PnX-SI/GeoNature#900]
Bonjour, est-il possible de désinstaller totalement/proprement un module ?

Raison du propos : suite à une mauvaise manip, je supprime les dossiers dans contrib/ et external_modules/ et veut ré-installer le module mais j'ai un message d'erreur me disant que le module est déjà installé. 

Merci d'avance !

**Comment by DonovanMaillard** [comment]
Bonjour, pour éviter cette erreur, il faut supprimer dans gn_commons.t_module la ligne qui correspond au module en question, lorsque vous le supprimez.

**Comment by Idaline** [comment]
Ok, très bien, merci beaucoup !

**Comment by camillemonchicourt** [comment]
Je ne pense pas que cela suffise à régler ton problème. 
Car tu as supprimé des modules du cœur de GeoNature, ainsi que le dossier node_modules du cœur de GeoNature donc il faut faire une réinstallation plus générale à mon avis. 
@TheoLechemia, tu procéderais comment ?

**Comment by Idaline** [comment]
Ah mince, j'essaye en récupérant mon dossier geonature avant l'installation, et en nettoyant la BDD. Je vous dis. Cela dit, est ce qu'il serait envisageable de prévoir une commande gn_uninstall_module ?

**Comment by camillemonchicourt** [comment]
Je referai plutôt une installation à côté ou une mise à jour de GeoNature car c'est pas juste une désinstallation d'un module. Ou sinon il faut remonter une sauvegarde propre de GeoNature.

**Comment by TheoLechemia** [comment]
De quel module il s'agit @Idaline ? Si tu as supprimer le dossier contrib, l'installation ne va plus marcher car tu n'as plus le code ... Sans cette fausse manip, ce que Donovan t'as dit doit fonctionner
On a volontairement pas fait de gn_uninstall_module pour pas que les gens supprime leur schéma de BDD avec toutes les données du module dedans.

**Comment by Idaline** [comment]
C'est tout bon en restaurant ma base de donnée ça a marché. Merci à vous 3 !

**Comment by Idaline** [comment]
(Je me lance à l'installation du module de suivi)

**Comment by DonovanMaillard** [comment]
Attention ! le module de suivi n'est pas terminé ni pleinement fonctionnel ;)

**Comment by camillemonchicourt** [comment]
OK super que tu aies pu restaurer tout ça.
Pour le module de suivi, en effet, la branche ``develop`` est maintenant bien avancée et en cours de finalisation (https://github.com/PnX-SI/gn_module_monitoring/tree/develop), mais il n'y a pas encore de Release officielle donc il est déconseillé de l'installer sur un serveur en production.
Les finalisations et dernières corrections sont en cours.
