### ISSUE TITLE
pb affichages des jdd

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#908]
Bonjour, 

Suite à migration de la 2.2.1 à 2.3.2, les jdd ne s'affichent plus quand on sélectionne un cadre d'acquisition dans le module métadonnées.
Le déroulant s'ouvre, on voit l'intitulé des colonnes mais la liste est vide.
Il y a qq chose à faire coté bdd ?

merci

**Comment by RomainBaghi** [comment]
résolu, la table gn_commons.cor_module_dataset n'était qu'a moitié remplie.

**Comment by camillemonchicourt** [comment]
Le lien entre les JDD et les modules ne devrait pas avoir de conséquences sur la liste des JDD.
Mais d'ailleurs j'ai pas compris à quel endroit tu as rencontré le problème ?
Quand on sélectionne un CA ? Je comprends pas où ?

**Comment by RomainBaghi** [comment]
Sur la page d'accueil du module métadonnée, j'ai la liste de CA qui s'affiche et quand je clique sur un CA le déroulant me montre les jdd qu'il contient. Là c'est à ce niveau là que c'était vide.

**Comment by RomainBaghi** [comment]
Non en fait c'est pas résolu, je ne comprends pas d’où cela vient mais des fois cela s'affiche et la plupart du temps il n'y a rien... vraiment bizarre

**Comment by jbrieuclp** [comment]
C'est pas une histoire de timing ? 
Regarde dans tes logs de navigateur si la requête des JDD est en train de tourner ou si elle a plantée et potentiellement ce qu'elle te retourne (onglet network du debuggeur sous chrome ou ff).

**Comment by camillemonchicourt** [comment]
Oui et indique nous les éventuelles erreurs dans la console du navigateur quand le problème se produit.

**Comment by RomainBaghi** [comment]
J'ai surtout une erreur js : ERROR TypeError: "right-hand side of 'in' should be an object, got undefined".
Le json des jdd a l'air de bien passer en 500ms.

**Comment by RomainBaghi** [comment]
Peut être que j'ai des champs null dans certains jdd qui font planter le front ?

**Comment by jbrieuclp** [comment]
Ce doit être ce `in` : https://github.com/PnX-SI/GeoNature/blob/7e345c269fe81bb177c4fe567e3fd784f1968af7/frontend/src/app/metadataModule/metadata.component.ts#L70
Si la variable af est undefined c'est que tu as un JDD sans rattachement à un CA (`gn_meta.t_datasets.id_acquisition_framework IS NULL`)
Check de ce côté là, tu devrais pouvoir trouver ton loup.

Il y a pourtant une contrainte NOT NULL sur ce champ de la table gn_meta.t_datasets ???

**Comment by RomainBaghi** [comment]
Non ils sont tous rattachés à un CA...

**Comment by jbrieuclp** [comment]
Ok, j'ai le problème... enfin j'crois !
Dans le backend, la fonction du repository qui doit retourner les CA est en INNER JOIN entre t_acquisition_f et ses acteurs si ton role == 2 (j'sais plus à quoi ça correspond CA de l'organisme ?)
https://github.com/PnX-SI/GeoNature/blob/7e345c269fe81bb177c4fe567e3fd784f1968af7/backend/geonature/core/gn_meta/repositories.py#L100-L105

Donc tu dois avoir un JDD qui doit être associé à ton organisme, mais le CA de ce JDD n'est pas associé à ton organisme.
Du coup avec le INNER JOIN sur ton organisme tu ne récupères pas de CA, mais tu récupères bien le JDD. Au niveau du front, l'app va essayer de refaire le lien entre le JDD et le CA 'dataset' in af, mais le CA (af) n'existe pas => undefined crash boum crac.

**Comment by RomainBaghi** [comment]
Bien joué ! En effet, 1 CA était avec comme acteur l'organisma "ALL" (id = 0) et c'est cela qui posait problème.
Merci !

**Comment by jbrieuclp** [comment]
Ce serait bien de le prendre en compte cet organisme "ALL" pour permettre de rendre open un JDD ou CA à tout le monde !

**Comment by camillemonchicourt** [comment]
Je crois plutôt qu'un organisme ALL ne devrait pas exister car c'est source d'incompréhension et d'erreurs

**Comment by jbrieuclp** [comment]
Oui, c'est vrai que c'est passé le top. Mais en tout cas il faudrait un mécanisme permettant d'ouvrir un JDD/CA

**Comment by camillemonchicourt** [comment]
Oui déjà il faudrait voir où est créé cet organisme "ALL" pour le virer. Là je ne vois que la création d'un organisme "Autre" qu'il faudrait virer aussi je pense : https://github.com/PnX-SI/UsersHub/blob/master/data/usershub-dataset.sql#L9

Actuellement avec un CRUVED de portée 3, on voit tous les JDD. 
Cependant ce que tu évoques serait d'avoir des JDD qui seraient utilisables/consultables par tous, même avec un CRUVED de niveau 2 (mon organisme), sans être acteur du JDD ?

**Comment by RomainBaghi** [comment]
Cet organisme ALL est peut-être une relique de la version beta puisque ma bdd date des premières versions.

**Comment by camillemonchicourt** [comment]
Et de UsersHub v1 je pense.

**Comment by jbrieuclp** [comment]
Ouai de mémoire ALL fait parti du package de données de l'installation d'usershub, est-ce qu'il est encore présent, j'sais pas.
> Cependant ce que tu évoques serait d'avoir des JDD qui seraient utilisables/consultables par tous, même avec un CRUVED de niveau 2 (mon organisme), sans être acteur du JDD ?

C'est exactement ça, avoir la possibilité d'ouvrir les données d'un JDD (données sensibles exclues) a un utilisateur ayant un cruved 1 ou 2 et sans qu'il soit en lien avec  un organisme du JDD.
Un JDD en mode open data en gros

**Comment by RomainBaghi** [comment]
> d'ouvrir les données d'un JDD (données sensibles exclues) 
Oui ce serait top (en attendant la gestion des données sensibles dans la synthèse avec "floutage" adapté).

**Comment by camillemonchicourt** [comment]
Ah OK, je pensai qu'on était au niveau du JDD encore, pas des données d'un JDD.
Dans ce cas oui, c'est prévu dans le cadre des développements pour les plateformes SINP, avec les notions de données publiques et privées. Il sera possible d'afficher les données précises d'un JDD publique (indépendamment du CRUVED sur les portées) et floutées si sensibles et/ou privées, selon les utilisateurs.

Voir les tickets du projet : https://github.com/PnX-SI/GeoNature/projects/5

**Comment by TheoLechemia** [comment]
@jbrieuclp je vois pas le problème du innerjoin. C'est normal de ne pas faire un left join. Si le cadre n'est pas dans la table des acteurs on ne le veut pas, car R = 2. 
@RomainBaghi est-ce que tu as compris le problème du coup, vous m'avez perdu avec tout ces échanges !

**Comment by jbrieuclp** [comment]
@TheoLechemia ce n'est pas un problème, c'est une explication.

**Comment by TheoLechemia** [comment]
Tu m'expliques l'explication alors ? ;)

**Comment by jbrieuclp** [comment]
C'est un INNER JOIN : du coup des CA vont être filtrés s'ils ne sont pas liés à l'organisme de Romain, du coup si des CA sont filtrés mais qu'un JDD lié à l'organisme de Romain fait référence à un CA filtré, alors il y a un problème de cohérence dans le BD au niveau de l'appariement d'organismes entre JDD et CA.

**Comment by jbrieuclp** [comment]
De fait le front devrait être à reprendre en faisant peut être une jointure des 2 observables qui récupère d'un coté CA et JDD. Mais en même temps que faire d'un JDD récupéré alors que le CA est exclue de la liste ?
Est-ce qu'il ne faudrait tout récupérer d'un coup CA et JDD ? Apres c'est questions sont peut être en train d'être vus sur le taf qui se passe sur ce module ?

**Comment by TheoLechemia** [comment]
Oui merci, c'est ce dont on vient de se rendre compte avec Camille. 
Comme il n'y a pas de cohérence imposé en base entre les acteur d'un CA et d'un JDD, on ne peut pas trop se permettre ce genre d'affichage en front... Ou alors si tu es acteur d'un JDD, tu vois obligatoirement (en lecture) le CA associé, même si tu n'a pas de droit sur celui-ci
Et non ce n'est pas prévu dans les devs du modules, mais il va falloir que ça le soit à priori !

**Comment by camillemonchicourt** [comment]
Oui c'est souhaitable que les acteurs des CA et des JDD ne soient pas forcément cohérents. 
Au niveau du CA, on peut mettre les acteurs globaux, et le détail précis des acteurs dans les JDD.

**Comment by TheoLechemia** [comment]
Fait dans le dernier commit réferencé.
On récupère d'abord tous les JDD filtrés par le CRUVED, puis l'ensemble des CA, peut importe les droit de l'utilisateur.
En lien avec https://github.com/PnX-SI/GeoNature/issues/911. Les actions (édition, voir la fiche) sont elle activées et désactivées en fonction du CRUVED de l'utilisateur
