### ISSUE TITLE
Occtax : comportement de la carte (zoom)

### ISSUE THREAD

**Issue by sylvain-m** [PnX-SI/GeoNature#912]
Bonjour à tous,

Excusez moi si cela a déjà été discuté (j'ai trouvé l'issue #570 en lien, mais ça commence à dater).
Je commence à saisir "en conditions réelles" des données dans OccTax.
Lorsque j'ouvre OccTax, j'ai tendance à zoomer directement sur le lieu de ma saisie, pour faire un premier repérage (aussi parce-que, instinctivement, j'oublie que je ne suis pas encore dans le formulaire de saisie du relevé).
Sauf que, quand je clique sur "ajouter un relevé", je perds tout le zoom que j'avais fait pour revenir au zoom initial : dommage de devoir re-géolocaliser notre relevé ensuite.
S'il était possible de conserver la bbox de la carte au moment de l'ouverture du relevé, ce serait top !

Par ailleurs, j'ai constaté que, lorsqu'on pointe un relevé, et uniquement en mode "point" (pas pour les lignes ou les polygones), la carte dézoome automatiquement : personnellement, je trouve ce comportement inutile, et même perturbant (on se demande si on a cliqué au bon endroit, parce qu’une fois dézoomé, on ne voit pas précisément où a été placé le point).

Je peux regarder plus précisément si j'identifie les lignes de codes responsables, mais avant, je veux bien savoir si vous avez déjà discuté de ça, ou si vous partagez mes 2 suggestions : 
- conserver le zoom entre ouverture Occtax et saisie relevé
- annuler le "dé-zoom" automatique à la saisie d'un point

A+

Sylvain

**Comment by sylvain-m** [comment]
Je pense que le problème du "dé-zoom" vient de là : 
https://github.com/PnX-SI/GeoNature/blob/52e63649c4f610cf3447c1e47f0142fa1d697db0/frontend/src/app/GN2CommonModule/map/leaflet-draw/leaflet-draw.component.ts#L31-L33

Du coup, on se rend compte que c'était sensé être un zoom vers le niveau 8, mais lorsqu'on est déjà à plus de 8, ça se transforme en "dé-zoom".
Je proposerais bien de mettre false pour ce paramètre, ou alors au contraire, de mettre 14 pour le niveau après saisie.

**Comment by samuelpriou** [comment]
Bonjour à tous,

Je partage le point de vue de Sylvain. 
Lorsque j'ouvre OccTax, j'ai moi aussi tendance à :

_"à zoomer directement sur le lieu de ma saisie, pour faire un premier repérage (aussi parce-que, instinctivement, j'oublie que je ne suis pas encore dans le formulaire de saisie du relevé).
Sauf que, quand je clique sur "ajouter un relevé", je perds tout le zoom que j'avais fait pour revenir au zoom initial : dommage de devoir re-géolocaliser notre relevé ensuite."_

Je suis également d'avis de conserver la bbox de la carte au moment de l'ouverture du relevé !

**Comment by jbrieuclp** [comment]
Ça se règle avec un énième service Angular, mais lui général au module occtax.

**Comment by sylvain-m** [comment]
> Ça se règle avec un énième service Angular, mais lui général au module occtax.

Je suppose que ça veut dire que c'est pas compliqué 😉

**Comment by camillemonchicourt** [comment]
Doublon avec https://github.com/PnX-SI/GeoNature/issues/436

**Comment by sylvain-m** [comment]
Pour ce qui est du niveau de zoom après pointage du relevé, j'ai tenté une PR :
https://github.com/PnX-SI/GeoNature/pull/932
(en espérant l'avoir fait "dans les règles", car je ne sais pas faire de PR 😉 )

**Comment by camillemonchicourt** [comment]
Réglé dans la 2.5.0 où l'on conserve le zoom de la page Carte/Liste quand on passe sur la création d'un nouveau relevé.
