### ISSUE TITLE
creation de compte automatique / association jdd-module

### ISSUE THREAD

**Issue by Amegilla** [PnX-SI/GeoNature#913]
Bonjour, 

Depuis la dernière mise à jour de GN, les bénévoles qui se créent des comptes automatiquement ne peuvent pas saisir de données car ils ne voient pas leur jdd personnel (créé automatiquement).
Après qq recherches je comprends que cela vient du fait que ces nouveaux jdd ne sont pas associés à la nouvelle table table cor_module_dataset. 
Est-ce qu'il est prévu quelque chose dans la config pour gérer ça ? 
merci

**Comment by jbrieuclp** [comment]
Tu m'enlèves le post du clavier ! J'allais justement faire remonter ce problème que je viens également de rencontrer ! (Pour pallier  en urgence à ça j'ai fait un fix dégueu avec un trigger qui ajoute une ligne id_jdd id_module occtax dans cor_module_dataset)

**Comment by camillemonchicourt** [comment]
Bien vu !

**Comment by RomainBaghi** [comment]
Merci pour vos retours, je me sens moins seul :)
Cela m'amène à une autre question est-ce qu'il faut systématiquement associer un jdd à occtax et à la synthèse et au module validation etc... bref à tout les modules pour pouvoir les utiliser ?
Pour l'instant je ne les ai ajouté qu'au module occtax.

**Comment by TheoLechemia** [comment]
C'est uniquement pour la saisie. Donc pour occtax, occhab etc...

**Comment by RomainBaghi** [comment]
ok, merci

**Comment by RomainBaghi** [comment]
Je remets cette discussion sur le tapis. 
J'utilise un trigger écrit par @jbrieuclp (si tu veux le partager ici?) mais c'est une solution temporaire.
Le trigger associe les jdd automatiquement créés à occtax. 
C'est le minimum requis car par défaut un bénévole qui se crée un compte veut pouvoir saisir des obs faune/flore. Pour Occhab c'est autre chose.
Il faudrait activer ce trigger quand le fonctionnement de la création de compte est configurée en mode automatique.

**Comment by camillemonchicourt** [comment]
Je pense pas que cela devrait être géré en trigger.

**Comment by TheoLechemia** [comment]
@jpm-cbna ça peut compléter ta PR recette sur l'envoie de mail automatique à la création de compte ? Par contre à faire dans le code python plutôt qu'en trigger

**Comment by RomainBaghi** [comment]
ça me va en python aussi :)

**Comment by bouttier** [comment]
doublon #1555
