### ISSUE TITLE
mise à jour Debian 9 vers Debian 10 sur VPS OVH

### ISSUE THREAD

**Issue by pguillermin** [PnX-SI/GeoNature#919]
Bonjour,
Ayant un geonature + geonature-atlas installé sur un VPS OVH en Debian 9, je me pose la question de la mise à jour de l'OS en Debian 10. Mais est-ce que c'est nécessaire? Certains l'ont fait? Des conseils?

**Comment by camillemonchicourt** [comment]
On réalise désormais la plupart des tests sur un Debian 10. 
On fait au mieux pour continuer à maintenir une version précédente, donc pour le moment encore Debian 9, mais c'est lourd de tout tester (installation, mise à jour, fonctionnement) sur différents OS. 

Normalement tu peux rester encore en Debian 9, mais il ne faut pas non plus avoir trop de retard, car quand on va passer sur Debian 11, on ne pourra plus garantir en plus un fonctionnement et des mises à jour sur Debian 9 et 10.

Donc c'est bien de rester à jour au niveau OS si possible.

Le plus sur est de migrer sur un nouveau serveur en Debian 10, mais c'est un peu lourd. Donc il est aussi faisable de mettre à jour ton OS de Debian 9 à 10 (``sudo apt-get update && sudo apt-get dist-upgrade``, voir https://vive-gnulinux.fr.cr/mise-a-jour-debian/), mais cela est une grosse mise à jour de l'OS, non sans risques et peut nécessiter des ajustements. 
Le mieux est de le tester sur un serveur de test avant. A minima à faire après un gros backup de ton GeoNature fonctionnel en Debian 9, idéalement un snapshot du serveur si besoin de revenir en arrière. 

Si tu le fais, on est preneur de ta procédure et de ton retour.

**Comment by pguillermin** [comment]
C'est sûr, ce serait plus propre de refaire une install à neuf, mais j'aimerai éviter de restaurer les bases, les fichiers de config, les certificats https... Je vais faire le test ce weekend et je vous ferai un retour.

**Comment by jbrieuclp** [comment]
De mon côté j'ai pu faire une migration de Debian 9 vers 10 sans me taper une reinstalle complète, que je n'aurais dans ce cas pas faite.
Pour la procédure de mise à jours : 
1 - sauvegarde des données (sources, fichiers de conf, base de données, app et compagnie)
2 - mise à jours de Debian 9, j'sais pas s'il fallait, mais j'ai fait. (apt dist-upgrade)
3 - modif des source.list pour passer sous Debian 10
4 - mise jours sous Debian 10  (apt upade et dist-upgrade)

Là, no panic, ça m'a flingué geonature, dont pip.
La réinstallation de geonature par ./install/migration/migration.sh plantait à cause d'un problème de virtualenv.
J'ai du relancer la commande de réinstallation de venv en pip3 (pip3 install virtualenv), avant de relancer une migration. Après il suffit de lire les erreurs remontées par la console, d'une recherche sous google pour trouver la solution au problème et de l'appliquer.

Par contre, même s'il va tourner, je crois que Postgresql 9.6 n'est plus maintenu sous Debian10, j'suis passé sous Postgresql 12 et postgis 3. Pour la migration des bases, je l'ai faite à coup de pg_dump et pg_restaure en effectuant un dump par section : pre-data, data et post-data dans 3 fichiers séparés. Ceci pour éviter des éventuels problèmes lors la restaurations. Forcement il faut aussi restaurer dans l'ordre pre-data < data < post-data.

Je crois que c'est lors de la restauration de la section post-data, il y aura un problème la table `utilisateurs.cor_role_app_profil` avec un problème de cohérences au niveau des contraintes des FK, comme si un ordre de reconstruction n'était pas respecté (PK < FK)... Mais elle accepte d'être repeuplée une fois la restauration effectuée, avec des INSERT INTO.

Postgres 11 est installé par defaut pour debian 10. Donc pour installer postgres12 il faut ajouter les sources à Debian. Et potentiellement désinstaller la version inutile de Postgresql 11 installée lors de la migration (et la 9.6 une fois la migration effectuée si tout est ok).

En ce qui concerne usershub, y'a juste un problème sur la version d'un paquet, j'avais ouvert une issue à ce propos : https://github.com/PnX-SI/UsersHub/issues/103

Voilà pour mon retour sur la mise à jour d'un Debian 9 vers 10.

Bon et après faut quand même repasser sur les différents soft du serveur voir si tout est ok. (fail2ban, rkhunter et toute la smala associée)

**Comment by camillemonchicourt** [comment]
OK merci beaucoup pour ce retour. Du coup ça fait un peu peur si on maîtrise pas bien tous ces aspects.

**Comment by jbrieuclp** [comment]
Baa, c'est de l'administration de serveur. Debian ou un autre, même combat, il faut un savoir ce qu'on y fait.

**Comment by camillemonchicourt** [comment]
Oui c'est normal, mais du coup en tant que noob dans le domaine une migration vers un serveur nouveau en Debian 10 me ferait moins peur.

**Comment by pguillermin** [comment]
Bon testé ce weekend. Pas de soucis pour la mise à jour de Debian sur un VPS Cloud Ram (j'étais pas sur d'être sur une Debian clean). J'ai fait 1,2,3,4 comme jbrieuclp. J'ai eu des avertissement concernant postgres 9.6 qui n'est plus supporté.
A la fin de le maj, je ne pouvait plus m'identifier sur GN, ni accéder à usershub ou taxhub. GN-atlas continuait à fonctionner, lui.
Les logs de GN, usershub et taxhub montrent des erreur de gunicorn. Donc install à refaire de python, de pip, du venv. Mais la lecture du post de jbrieuclp au-dessus et la montée en version de postgres m'ont fait stopper là pour l'instant: je restaure le VPS. Plus tard je prévoirai la migration des bases et une réinstallation propre sur un nouveau serveur Debian 10.
Il faut peut-être préciser dans la doc d'installation globale de GN que Debian 10 est aussi un prérequis https://geonature.readthedocs.io/fr/latest/installation-all.html (seuls 8 et 9 sont mentionnés).

**Comment by jbrieuclp** [comment]
@camillemonchicourt c'est sur qu'il peut être plus facile (et moins stressant) de partir de zéro par moment.

En complément, il m'a également fallut relancer une install (en suivant la procédure de mise à jour) de geonature, usershub et taxhub pour remettre gunicorn d'équerre.

**Comment by camillemonchicourt** [comment]
Tu n'es pas sur la bonne documentation. Ça c'est l'ancienne que l'on n'a pas pu supprimer encore.
La bonne doc à jour est sur http://doc.geonature.fr

**Comment by pguillermin** [comment]
Oups, merci, c'est tout bon alors.

**Comment by JulienCorny** [comment]
Salut,

Je viens juste de faire aussi une mise à jour de debian 9 à 10 sur un serveur. 

Merci pour les commentaires précédents qui ont bien aidé. 

J'ajoute 1 ou 2 infos pour compléter :

Pour la bdd, avant de commencer, j'ai fait un dumpall de la bdd (postgresql 9.6) et une fois sur debian 10 j'ai restauré la bdd (postgresql 11). Ne pas oublier de réinstaller postgis avant de restaurer sinon il va manquer des tables.

Bien sûr avant de commencer il faut aussi faire un backup de tout ce qu'on peut (configs geonature, usershub, taxhub, apache, cron, fail2ban, iptables,...), et un snapshot pour le confort et le stress :)

Quelques lignes de code qui peuvent servir : 

sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade

La source list de debian 10 :
sudo cat /etc/apt/sources.list
	deb http://deb.debian.org/debian/ buster main
	deb-src http://deb.debian.org/debian/ buster main
	deb http://deb.debian.org/debian/ buster-updates main
	deb-src http://deb.debian.org/debian/ buster-updates main
	deb http://security.debian.org/debian-security buster/updates main
	deb-src http://security.debian.org/debian-security buster/updates main

sudo apt-get update
sudo apt list --upgradable
sudo apt-get upgrade && sudo apt-get dist-upgrade

A partir de là on est sur debian 10 mais il manque des dépendances qui doivent être réinstallées. Là il faut prendre la doc : https://docs.geonature.fr/installation-standalone.html et réinstaller les dépendances listées à "Lancez les commandes suivantes pour installer les dépendances de GeoNature (Debian 10)". Dont effectivement celles liées à pip et au virtualenv : 
python3 -m pip install pip==20.0.2
pip3 install virtualenv==20.0.1

Ensuite j'ai viré postgresql 9.6 pour ne garder que la version 11. Puis j'ai restauré le dumpall. 

Ensuite j'ai réinstallé geonature, taxhub et usershub (faire bien le tour des settings.ini et autres config avant de lancer les installation car il y a des options qui ne sont plus forcément pertinentes par rapport à la premiere install)

Quand j'ai redémarré tous les services, il restait des erreurs à cause de lib python manquantes liées à des modules. Donc il faut aussi bien penser aussi à réinstaller les lib dans les requirements.txt des différents modules (penser à se mettre dans le virtualenv avant de lancer les pip install -r requirements.txt)

**Comment by camillemonchicourt** [comment]
Merci pour ces retours, utiles pour les suivants

**Comment by JulienCorny** [comment]
Je viens de voir qu'il faut aussi remettre en place les règles de iptables qui ont sauté pendant la mise à jour.

**Comment by christianbieche** [comment]
Merci Julien pour les infos et la marche à suivre.
C'est parfait. je suis passé d'une version 1.4.1 de geonature à la version 2.5.5 en mettant à jour la version de debian 9.6 à 10.
J'ai mis à jour aussi les versions de taxhub, userhub et Atlas pour être en ligne avec cette version.
j'ai donc maintenant une version geonature 2.5.5,  Taxhub 1.7.3, Userhub 1.4.2, Atlas 1.4.2

J'ai suivi la démarche de Julien en faisant un pg_dumpall de la base (j'avais tenté de refaire individuellement les bases mais cela ne fonctionne pas bien - le plus simple est de faire effectivement un dump_all)

Par contre pour le changement de version, avant la suppression définitive de la version 9.6. J'ai laissé les 2 versions sur le système dans 1 er temps, en passant le port de la version 11 en 5432 (défaut postgress et Geonature).

Pour le passage de la 4.2.1 à la version 2.5.5. Comme le pensait Camille, on peut passer directement à la dernière  version en effectuant les mises à jours nécessaires en base au préalable (suivre les releases notices).

Pour info, les fichiers qui sont à remodifier éventuellement avec des url spécifiques de domaines ou d'adresse ip sont 
./usershub/config/config.py
./geonature/config/settings.ini
./geonature/config/geonature_config.toml
./atlas/atlas/configuration/config.py

Remarque : le script migration.sh de geonature reprend les configurations.

Christian 
Cistude Nature

**Comment by camillemonchicourt** [comment]
Merci pour ce retour et super pour votre mise à jour 🚀
