### ISSUE TITLE
question : usage des tables gn_synthese.cor_role_synthese et gn_synthese.cor_observer_synthese

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#920]
J'ai ces deux tables dans mon schéma synthese, et j'ai l'impression qu'une des deux n'est pas (plus) utilisée : gn_synthese.cor_observer_synthese.

Pour l'autre c'est bien celle qui sert à faire le lien entre une obs dans la synthese et un login via le champ id_digitiser ?

**Comment by RomainBaghi** [comment]
erratum, c'est indépendant du champ id_digitiser à ce que je comprends. Donc une donnée sera associée (au niveau des droits)  à un login si l'id_digitiser et rempli ou si une association id_synthese - id_role existe dans cor_observer_synthese.

**Comment by camillemonchicourt** [comment]
En effet, j'ai l'impression que ce sont des restes des versions avant la 2.0.0. Mais même dans les RC je ne trouve pas de trace de ``gn_synthese.cor_role_synthese``.
On voit bien dans le SQL de création du schéma ``gn_synthese`` que la table ``cor_role_synthese`` n'existe plus : https://github.com/PnX-SI/GeoNature/blob/master/data/core/synthese.sql. 
Je pense qu'elle a été renommée ``cor_observer_synthese`` pour être moins ambiguë sur son contenu.

Dans la synthèse on stocke tout le temps les observateurs en texte dans le champs ``gn_synthese.synthese.observers``. Mais il est possible, en plus de stocker les observateurs avec leurs ``id_role`` dans cette table et cela permet d'appliquer les éventuelles CRUVED de portée 1 (Mes données). Pas d'autre utilité de mémoire.

Cette table est remplie par le trigger Occtax > Synthese, qui déclenche un autre trigger (https://github.com/PnX-SI/GeoNature/blob/master/data/core/synthese.sql#L600) alimentant le champs texte ``gn_synthese.synthese.observers``.

**Comment by RomainBaghi** [comment]
ok, merci pour ton analyse. Je suis en train de faire le point pour ré-associer des utilisateurs à leur données importées dans la synthèse.

**Comment by camillemonchicourt** [comment]
OK mais utilité à voir car seulement nécessaire si on utilise un CRUVED de portée 1.

**Comment by camillemonchicourt** [comment]
As-tu identifié d'où venait ta table "gn_synthese.cor_role_synthese" et si elle est utilisée ?

A supprimer selon moi, un reste de je ne sais pas quand, mais à vérifier avant.
