### ISSUE TITLE
JDD - Import depuis API MTD et acteurs

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature#922]
Actuellement quand on importe des JDD depuis le webservice MTD, on associe automatiquement l'utilisateur en tant qu'acteur.
Suite à l'ajout du champs ``id_digitiser`` (https://github.com/PnX-SI/GeoNature/issues/921), c'est plutôt ce champs qu'il faudrait remplir.

**Comment by DonovanMaillard** [comment]
Quand tu parles d'imports depuis l'api mtd ? Ca veut dire que la fonction a été ajoutée récemment, ou tu parles du script d'import ?

**Comment by camillemonchicourt** [comment]
Ça existe depuis le début.
Pour DEPOBIo on n'utilise pas le module Métadonnées de GeoNature mais on se base sur les métadonnées de MTD de l'INPN : http://docs.geonature.fr/installation-mtes.html#recuperation-des-jdd

**Comment by DonovanMaillard** [comment]
ok au temps pour moi, je pensais que tu parlais de l'import de MTD (donc vers le module MTD)

**Comment by camillemonchicourt** [comment]
Oui ça importe des métadonnées dans gn_meta depuis MTD INPN

**Comment by TheoLechemia** [comment]
Fait.
Todo: vérifier que l' `id_creator `de MTD existe bien dans GN. Voir la clé étrangère entre `t_dataset/t_acquisition_framework` et `utilisateurs.t_roles`
