### ISSUE TITLE
optimisation du temps de chargement dans le module validation

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature#923]
Bonjour, 

Je cherche désespérément à faire fonctionner correctement le module validation sur mon instance.
Le problème se pose quand je fais une recherche qui va concerner un volume de donnée "conséquent" (> 1000 lignes). Là le chargement n'abouti pas. 
Quand je lance une requete équivalente directement sur ma bdd ( via dbeaver), c'est effectivement très long (40sec pour mon exemple, 3502lignes).

Voici ci dessous ce que me donne le "Explain analyse"  pour cette requete, si certains savent lire ce rapport, je veux bien des pistes d’améliorations (voici la structure de la vue que j'utilise : https://github.com/PnX-SI/GeoNature/blob/5c0c702ae9a71d50de959a95f85a165136f2d32d/data/migrations/2.3.2to2.3.3.sql#L84)

  QUERY PLAN                                                                                                                                                          |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------|
Limit  (cost=2410.01..143503.96 rows=59 width=892) (actual time=22.065..37514.189 rows=3523 loops=1)                                                                |
  ->  Nested Loop Left Join  (cost=2410.01..143503.96 rows=59 width=892) (actual time=22.065..37511.881 rows=3523 loops=1)                                          |
        ->  Nested Loop Left Join  (cost=1.40..1247.00 rows=59 width=851) (actual time=0.177..90.048 rows=3523 loops=1)                                             |
              ->  Nested Loop  (cost=1.13..1176.46 rows=59 width=791) (actual time=0.163..68.183 rows=3523 loops=1)                                                 |
                    ->  Nested Loop  (cost=0.71..1167.28 rows=59 width=702) (actual time=0.110..59.938 rows=3523 loops=1)                                           |
                          ->  Index Scan using i_synthese_cd_nom on synthese s  (cost=0.43..934.21 rows=268 width=655) (actual time=0.079..24.863 rows=3706 loops=1)|
                                Index Cond: (cd_nom = 444427)                                                                                                       |
                          ->  Index Scan using pk_t_datasets on t_datasets d  (cost=0.28..0.86 rows=1 width=51) (actual time=0.007..0.007 rows=1 loops=3706)        |
                                Index Cond: (id_dataset = s.id_dataset)                                                                                             |
                                Filter: validable                                                                                                                   |
                                Rows Removed by Filter: 0                                                                                                           |
                    ->  Materialize  (cost=0.42..8.45 rows=1 width=93) (actual time=0.000..0.001 rows=1 loops=3523)                                                 |
                          ->  Index Scan using pk_taxref on taxref t  (cost=0.42..8.44 rows=1 width=93) (actual time=0.047..0.047 rows=1 loops=1)                   |
                                Index Cond: (cd_nom = 444427)                                                                                                       |
              ->  Index Scan using pk_t_nomenclatures on t_nomenclatures n  (cost=0.27..1.19 rows=1 width=64) (actual time=0.003..0.005 rows=1 loops=3523)          |
                    Index Cond: (id_nomenclature = s.id_nomenclature_valid_status)                                                                                  |
        ->  Limit  (cost=2408.61..2408.62 rows=1 width=9) (actual time=10.603..10.603 rows=0 loops=3523)                                                            |
              ->  Sort  (cost=2408.61..2408.62 rows=1 width=9) (actual time=10.601..10.601 rows=0 loops=3523)                                                       |
                    Sort Key: v.validation_date DESC                                                                                                                |
                    Sort Method: quicksort  Memory: 25kB                                                                                                            |
                    ->  Seq Scan on t_validations v  (cost=0.00..2408.60 rows=1 width=9) (actual time=10.563..10.590 rows=0 loops=3523)                             |
                          Filter: (uuid_attached_row = s.unique_id_sinp)                                                                                            |
                          Rows Removed by Filter: 86960                                                                                                             |
Planning time: 1.440 ms                                                                                                                                             |
Execution time: 37515.622 ms                                                                                                                                        |

**Comment by camillemonchicourt** [comment]
OK à noter que suite à vos investigations, Théo a apporté des améliorations significatives du chargement aujourd'hui : https://github.com/PnX-SI/GeoNature/commit/1f31e7edf511fa1011de5f05d0775bc0855cf364

En changeant la manière de faire les requête et en déportant la génération du geojson côté BDD, ça passe de 20 à 2 secondes pour les 100 dernière données.
Pareil sur les filtres, sur 1.9 millions de données ça ne marchait pas du tout, là c'est largement acceptable.
Avant cela on devait mettre la limite des observations à 500, là on est passé à 5000 et ça fonctionne.

Plus globalement il y avait un important d'optimisation sur le module Synthèse qui mériteraient d'être factorisées et reportées sur le module Validation.

**Comment by jbrieuclp** [comment]
C'est très bon ça,
Pour ta requête Romain, vérifie si tu as un index sur le champ cd_nom de la table `taxonomie.taxref`. Je viens de me rendre compte que je n'en avais pas sur ma BD et toi rien n'indique dans ton explain qu'il y en ait un. Au passage s'il y a des indexs sur des champs de la table taxref qui ne te servent pas (habitat, nom_vern...) il vaut mieux les virer.
```
CREATE INDEX i_taxref_cd_nom
    ON taxonomie.taxref USING btree
    (cd_nom ASC NULLS LAST)
    TABLESPACE pg_default;
```

Sinon pour la requête de cette vue, javais ouvert cette issue en proposant une correction SQL https://github.com/PnX-SI/GeoNature/issues/710

**Comment by RomainBaghi** [comment]
Bizarrement, cela n'améliore pas le chrono (même temps). Et effectivement je n'avais pas d'index sur le cd_nom (sur cd_ref uniquement). En fait dans l'appli j'ai mis une limite à 500 obs mais je n'ai pas l'impression que cette limite soit prise ne compte par le backend. Car dans dbeaver quand je mets une limite à 500, toutes les requêtes aboutissent en 7sec. Peut être que les contraintes de cruved rajoute de la lourdeur à la requete coté appli.

**Comment by TheoLechemia** [comment]
Tu peux "printer" les requêtes construites par SQLAlchemy et les partager ? (et les lancer dans dbeaver)

**Comment by camillemonchicourt** [comment]
Amélioration intégrées dans la 2.4.0

**Comment by jbdesbas** [comment]
Salut à tous,
Confronté au même problème, j'ai eu une amélioration très très significative (~30 seconde --> 40 ms) en ajoutant un index (non unique) sur le champs _uuid_attached_row_ de la table _gn_commons.t_validation_
Sauf erreur de ma part, cet index n'est pas crée lors de l'installation/migration de la base, alors qu'il est clairement indispensable https://github.com/PnX-SI/GeoNature/blob/c0e2124f4545b62190203d19bf7e230dcacd35d7/data/core/commons.sql#L360

**Comment by gildeluermoz** [comment]
👍
J'aime les optimisations !

**Comment by TheoLechemia** [comment]
Merci pour le retour. Je l'ai rajouté

`CREATE INDEX i_t_validations_uuid_attached_row ON gn_commons.t_validations USING btree (uuid_attached_row);
`
@RomainBaghi tu peux tester de ton côté ?

**Comment by RomainBaghi** [comment]
J'ai l'impression que c'est effectivement bien plus rapide chez moi depuis mais comme j'ai limité le nombre de résultats avec NB_MAX_OBS_MAP = 500, il faut que je teste avec 5000 au moins.
Je vous tiens au courant

**Comment by jbdesbas** [comment]
De mon côté c'était particulièrement lent sans index car la table _t_validations_ contient environ 2M de lignes (donc la jointure avec la synthèse, 2M également, ca fait mal)

**Comment by RomainBaghi** [comment]
Bon, je viens de tester et c'est le jour et la nuit ! Avec une limite à 5000 obs le temps de chargement est à 5-7sec pour +1min (voire plantage) avant donc ... MERCI !
