### ISSUE TITLE
Blocage lors de "Personnaliser la liste des taxons saisissables dans le module"

### ISSUE THREAD

**Issue by olivier8064** [PnX-SI/GeoNature#928]
Bonjour, 
Après avoir installé géonature avec succès j'ai voulu inclure l'ensemble des taxons pour la saisie dans occtax d'après la doc : https://geonature.readthedocs.io/fr/latest/admin-manual.html#personnaliser-la-liste-des-taxons-saisissables-dans-le-module

mais au moment d’exécuter la dernière instruction : 
INSERT INTO taxonomie.cor_nom_liste (id_liste,id_nom) SELECT 100,n.id_nom FROM taxonomie.bib_noms n;

il ne se passe plus rien, même en attendant plus d'une heure... 
Je me suis souvenu que c'est probablement parce que j'ai fait l'import avec l'utilsateur postgres et non geonatadmin...  (https://github.com/PnX-SI/GeoNature/issues/700)

Mais quand je veux me connecter à geonatadmin avec putty, j'ai un message me disant "No passwd entry for user 'geonatadmin'" Pourtant je suis persuadé d'avoir indiqué un mot de passe pour geonatadmin dans le script d'installation... 
Je ne sais pas pourquoi j'ai ce message, j'ai réussi toutefois à me connecter à geonatadmin avec pgadmin cf ci-dessous

**Comment by olivier8064** [comment]
Pour info, j'ai pu en utilisant pgadmin me connecter avec l'utilisateur geonatadmin et non postgresql. Mais le problème de blocage au moment de la dernière instruction est toujours là...(déjà 15 mn que c'est bloqué..) : 
![Screenshot - 25_05_2020 , 08_50_24](https://user-images.githubusercontent.com/7148321/82786477-faceda80-9e64-11ea-88bb-15269654c152.png)

**Comment by DonovanMaillard** [comment]
Bonjour. Selon le nombre de cd_nom dans la bib_noms (si vous avez tout le taxref notamment), l'écrite de 550.000 lignes dans la base peut prendre beaucoup de temps. Est-ce que ca passe en faisant un premier essai avec "LIMIT 100" par exemple ? Vous verrez si c'est un problème de la requête, ou si ca vient bien du volume d'information à écrire dans la table

**Comment by camillemonchicourt** [comment]
Oui c'est bizarre qu'une requête simple comme ça pose soucis. En effet il vaut mieux l'exécuter avec l'utilisateur applicatif "geonatadmin". Il y a peut-être un doublon qui coince. Les tables étaient bien vides avant l'intégration de ces données ?

**Comment by olivier8064** [comment]
Ca fait déjà 1 heure que la requête est lancée.. je vais attendre encore un peu sinon je ferai un limit 100. 
Oui Camille, j'ai bien fait DELETE FROM taxonomie.cor_nom_liste; et DELETE FROM taxonomie.bib_noms; avant de lancer les autres requêtes.

**Comment by jbrieuclp** [comment]
Trigger trigger trigger... 
Il y a un trigger sur l'INSERT de la table `taxonomie.cor_nom_liste` qui exécute la fonction  `taxonomie.trg_fct_refresh_mv_taxref_list_forautocomplete()`.

Dans pg_admin, tu peux dérouler le détail de ta table `cor_nom_liste` > `déclencheurs (1)` > clic droit sur `trg_refresh_mv_taxref_list_forautocomplete` > `Désactiver le déclencheur`
Tu envoies ta requête INSERT qui met du temps
Tu peux réactiver le trigger par la même manip quand c'est fait.

Maintenant il faut s'occuper de la table `taxonomie.vm_taxref_list_forautocomplete` qui n'a pas été renseignée avec le trigger désactivé.

Potentiellement tu vides ce qui était déjà présent (si ton id_liste est bien **100**, sinon réadapte) :
`DELETE FROM taxonomie.vm_taxref_list_forautocomplete WHERE id_liste = 100;`

Tu lance la fonction appelée par le trigger pour remplir cette table (avec toujours le id_liste = 100 à réadapter) :
```
INSERT INTO taxonomie.vm_taxref_list_forautocomplete
SELECT t.cd_nom,
t.cd_ref,
concat(COALESCE(nom_francais, t.lb_nom), ' =  <i> ', t.nom_valide, '</i>', ' - [', t.id_rang, ' - ', t.cd_nom , ']') AS search_name,
t.nom_valide,
t.lb_nom,
t.regne,
t.group2_inpn,
100
FROM taxonomie.taxref t;
```

**Comment by TheoLechemia** [comment]
Merci @jbrieuclp , j'allais répondre la même chose ;) 
On est en train de discuter pour revoir la modélisation de cette table

**Comment by camillemonchicourt** [comment]
En effet, bien vu.
A chaque fois qu'on ajoute un taxon dans une liste (``taxonomie.cor_nom_liste``), un trigger est exécuté pour l'ajouter dans ``taxonomie.vm_taxref_list_forautocomplete``. Cette table (qui était anciennement une vue matérialisée, d'où son nom) permet de disposer de tous les noms d'une liste à plat pour les formulaires de recherche.

Donc quand on ajouter tout Taxref dans ``bib_noms`` et à la saisie dans la liste 100, alors c'est très long.
Initialement, ``bib_noms`` ainsi que les listes sont justement faits pour limiter les listes de saisie et ne pas embarquer tout le temps tout Taxref. Ainsi alléger les listes déroulantes, éviter les erreurs de saisie, ...
Au PNE, on n'a mis que les 7000 taxons connus du territoire. Donc c'est un peu contre-productif de mettre tout Taxref dans bib_noms et dans la liste des taxons saisissables, mais c'est possible.
Mais c'est long. Ou alors il faut désactiver le trigger puis lancer à la main ce qu'il fait.

Cependant cette table est au cœur de plusieurs discussions et soucis ces derniers temps : https://github.com/PnX-SI/TaxHub/issues. Donc il est possible que l'on revoie son fonctionnement.

**Comment by olivier8064** [comment]
Merci à tous, en particulier @jbrieuclp , 
Ca fonctionne ! mon id_liste était bien 100. Mis à part que pour l’exécution de la requête finale j'ai eu un message d'erreur me disant que "nom_francais" n'existait pas. En effet dans taxonomie.taxref c'est nom_vern. Donc si j'ai bien tout suivi, j'ai exécuté à la place : 

`INSERT INTO taxonomie.vm_taxref_list_forautocomplete
SELECT t.cd_nom,
t.cd_ref,
concat(COALESCE(nom_vern, t.lb_nom), ' =  <i> ', t.nom_valide, '</i>', ' - [', t.id_rang, ' - ', t.cd_nom , ']') AS search_name,
t.nom_valide,
t.lb_nom,
t.regne,
t.group2_inpn,
100
FROM taxonomie.taxref t;`

Par contre il doit y avoir un bug pour le listage des noms car si je tape lierre terrestre par exemple, j'ai autant de fois ce nom qu'il y a de synonymes dans taxref (tout est identique dans la liste sauf le code espèce) alors qu'en principe seul la ligne où code nomen = code ref devrait être affichée ?

**Comment by olivier8064** [comment]
ah, c'est probablement qu'il faut remplacer "concat(COALESCE(nom_vern, t.lb_nom)" par "concat(COALESCE(nom_vern, t.nom_valide)" ?

**Comment by camillemonchicourt** [comment]
Et pour en savoir plus sur le mécanisme de recherche de taxons dans GeoNature, voir

**Comment by camillemonchicourt** [comment]
Et pour en savoir plus sur le mécanisme de recherche de taxons dans GeoNature, voir https://si.ecrins-parcnational.com/blog/2019-01-fuzzy-search-taxons.html

**Comment by jbrieuclp** [comment]
Oups ! J'ai zappé la jointure avec la table bib_noms...

INSERT INTO taxonomie.vm_taxref_list_forautocomplete
SELECT t.cd_nom,
t.cd_ref,
concat(COALESCE(b.nom_francais, t.lb_nom), ' =  <i> ', t.nom_valide, '</i>', ' - [', t.id_rang, ' - ', t.cd_nom , ']') AS search_name,
t.nom_valide,
t.lb_nom,
t.regne,
t.group2_inpn,
100
FROM taxonomie.taxref t
INNER JOIN taxonomie.bib_noms b ON t.cd_nom = b.cd_nom;

En plus sans cette jointure c'est tout taxref qui part dans la table `taxonomie.vm_taxref_list_forautocomplete`.

**Comment by olivier8064** [comment]
Ah ok c'est plus clair comme ça :) 
J'ai repris du début et tout est ok maintenant. 
Merci ! et ça m'aura permis de comprendre comment personnaliser l'affichage dans occtax.

**Comment by TheoLechemia** [comment]
Corrigé par #219
