### ISSUE TITLE
interface de démo de GeoNature bloquée sur enregistrement du relevé

### ISSUE THREAD

**Issue by olivier8064** [PnX-SI/GeoNature#930]
Bonjour, 
Pour info, en voulant tester l'interface de démo, il se trouve qu'après avoir entré un point et une date puis sur "enregistrer", l'interface reste bloquée 

![Screenshot - 25_05_2020 , 19_07_00](https://user-images.githubusercontent.com/7148321/82832423-4d3ae600-9ebb-11ea-9e3d-de502a1db498.png)

**Comment by camillemonchicourt** [comment]
Oui en effet.
C'est du au fait qu'on a déployé sur le serveur de DEMO le développement en cours de refonte du formulaire d'Occtax (https://github.com/PnX-SI/GeoNature/issues/758).
Cependant, voulant tester les récentes version d'Occtax-mobile connecté au serveur de DEMO, cela a levé un problème d'incompatibilité (https://github.com/PnX-SI/GeoNature/pull/860#issuecomment-625170306). Du coup le module Occtax du serveur de DEMO est actuellement dans un état intermédiaire non fonctionnel.
