### ISSUE TITLE
Commande geonature introuvable - passage en mode dev

### ISSUE THREAD

**Issue by sallib** [PnX-SI/GeoNature#933]
Bonjour, 
Suite à une installation globale de geonature (sur une Debian 9), j'ai suivi la doc pour passer en [mode développement](https://geonature.readthedocs.io/fr/latest/installation-standalone.html#passer-en-mode-developpement). 

Le coté front se lance sans soucis avec AngularCLI. 
En revanche, du coté back, la commande geonature n'est pas reconnue. 
`$ geonature dev_back
-bash: geonature : commande introuvable
`

J'ai relancé le fichier install_app.sh - qui génère des erreurs. Je met les log en PJ. 

Une idée d'où vient le problème ? 
Merci de votre aide. 
[install_app.log](https://github.com/PnX-SI/GeoNature/files/4727904/install_app.log)

Sandy

**Comment by camillemonchicourt** [comment]
A noter que la documentation officielle est sur http://docs.geonature.fr et que la dernière version de GeoNature est compatible Debian 10.
La documentation sur https://geonature.readthedocs.io/ n'est plus à jour et va être supprimée après la prochaine Release de GeoNature.

**Comment by joelclems** [comment]
Il faut activer l'environnement virtuel de python
Depuis le répertoire de géonature, exécuter: 
```
. backend/venv/bin/activate
```

puis 
```
geonature dev_back
```

**Comment by sallib** [comment]
Merci pour la précision concernant la documentation. 

J'ai bien activé l'environnement virtuel de python, mais la commande geonature reste introuvable. Il doit y avoir un hic à un moment de l'installation...

**Comment by TheoLechemia** [comment]
Bonjour,
D'après les logs il y a bien eu une erreur d'installation de la commande `geonature`. 
Vous avez lancez une installation indépendante de GeoNature ?
Le fichier de log ne semble pas complet (il manque le début qui concerne la création du virtualenv), pouvez-vous vérifier qu'il est complet ?
Sinon que renvoie la commande : `python3 -m virtualenv -p /usr/bin/python3 venv` ?

**Comment by sallib** [comment]
J'ai fais une installation globale de GeoNature. 

Voilà ce que renvoie la commande : 
`(venv) geonatureadmin@geonature:~/geonature/backend$ python3 -m virtualenv -p /usr/bin/python3 venv`
`/home/geonatureadmin/geonature/backend/venv/bin/python3: No module named virtualenv`

J'ai relancé le script `ìnstall_app.sh`, en PJ les log au complet.

[install_app.log](https://github.com/PnX-SI/GeoNature/files/4729352/install_app.log)

**Comment by camillemonchicourt** [comment]
Voir https://github.com/PnX-SI/GeoNature/commit/a0932a8ead9185f949a223024f9c368af282f130

**Comment by TheoLechemia** [comment]
D'apèrs les logs, l'installation a fonctionné. La commande `geonature` doit être disponible dans le virtualenv comme l'a indiqué Joel

**Comment by sallib** [comment]
J'ai finalement repris l'installation de zéro. La commande `geonature` fonction désormais correctement. Merci pour votre aide !
