### ISSUE TITLE
Occtax - Preuve d'existence

### ISSUE THREAD

**Issue by MNourrisson** [PnX-SI/GeoNature#937]
Bonjour,
pour renseigner le champ "preuve numérique", est-il possible de lier directement la preuve de l'observation (photo, son, vidéo,...) du taxon lors de la saisie ? Ou faut-il indiquer une référence ou un lien vers la preuve ?
Car comme ce champ est un champ texte, je ne sais pas trop quoi renseigner comme justification mise à part un lien vers la preuve mais qui serait du coup stockée séparément.

Merci

**Comment by TheoLechemia** [comment]
Bonjour,
Il n'y a pas actuellement la possibilité de stocker une image/son/video associé à une observation. La fonctionnalité est prévu dans une prestation en cours. En attendant vous ne pouvez mettre qu'un lien externe en effet.

**Comment by MNourrisson** [comment]
Ok, pas de soucis. Merci beaucoup pour la réponse

**Comment by camillemonchicourt** [comment]
Oui à suivre : https://github.com/PnX-SI/GeoNature/issues/620
