### ISSUE TITLE
OccHab - Bug suppression / édition

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature#939]
Bonjour,

Nous sommes, en ce moment, en train d’implémenter GéoNature pour la LPO France et la gestion de ses Réserves Naturelles.

Nous avons fait quelques tests et avons découvert un petit bug concernant l'import de géométrie multiple (via un GeoJSON) dans le module OccHab.

Il s'agit, en fait, d'une non-possibilité de modifier ou supprimer l'enregistrement portant cette géométrie via le module. Et une fois avoir cliqué sur le bouton de suppression de cet occurrence (sans effet), on ne peut plus supprimer d’occurrences dans OccTax et OccHab à moins de recharger la page.

Sauriez-vous d'où pourrait venir ce problème ?

A vous lire,
Maxime

**Comment by camillemonchicourt** [comment]
En effet cela ressemble à un problème similaire que l'on a rencontré sur Occtax et qui a été corrigé. 
Mais qui est peut-être présent dans Occhab.

**Comment by LPOMaximeToma** [comment]
Après un nouveau test, il semblerait que le problème ne viendrai finalement pas de la géométrie multiple mais d'une suppression d'habitat après modification. Et s'il n'y a plus d'habitat sur une station, impossible de la supprimer/modifier via OccHab

**Comment by LPOMaximeToma** [comment]
(Je précise que je suis en version 2.3.2) Je rajoute sur ce ticket, après manipulation plus approfondie, que une personne qui ne peut pas modifier ou supprimer un élément peut cliquer sur les icônes de l'interface principale, contrairement à OccTax, affichant des messages d'erreurs:

**Suppression** 
![image](https://user-images.githubusercontent.com/66769358/85990594-8f8f9f80-b9f2-11ea-9c4e-6896c172bfbb.png)
![image](https://user-images.githubusercontent.com/66769358/85990668-a930e700-b9f2-11ea-9ca4-ba08b524fd68.png)

**Edition**
![image](https://user-images.githubusercontent.com/66769358/85990953-09c02400-b9f3-11ea-89f4-7dc114bd43d7.png)

**Comment by camillemonchicourt** [comment]
Problème de suppression d'une station sans habitat non reproduit dans la 2.12.0
