### ISSUE TITLE
Occhab-Occtax - Problème de filtre dans les listes d'observateurs

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/GeoNature#942]
Bonjour,

Nous avons remarqué quelques petits problèmes avec le module OccHab. Nous ne savons en revanche pas si cela vient d'un problème d'installation du module ou non.

Pour la liste des observateurs, lorsque l'on veut chercher un observateur en particulier avec les trois premières lettres, cela affiche des users n'ayant pas cette suite de trois lettres (problème intervenant aussi dans OccTax).
![image](https://user-images.githubusercontent.com/66769358/84988524-71988400-b142-11ea-92af-f0b2b015d37f.png)

Enfin, a-t-il été prévu de lier OccHab au module synthèse ou validation ?

Bien à vous,
Maxime

**Comment by camillemonchicourt** [comment]
OK je viens de reproduire le problème en version 2.3.2. A retester en 2.4.0.
Pour Occhab et synthèse/validation, c'est un autre sujet. Mais les les données d'occurrences d'habitat n'ont rien à voir et pas la même structure que celles d'occurrences de taxons. Donc on ne peut pas du tout intégrer les occurrences d'habitat dans la Validation ni la Synthèse. 
D'autant plus que Occhab permet de saisir des occurrences d'habitat mais permet aussi d'y importer des données externes, donc il peut faire office de synthèse des occurrences d'habitat (saisis ou pas dans l'outil).
Cependant on pourrait imaginer à terme intersecter les occurrences de taxons avec les stations d'habitat, mais c'est un autre sujet.

Je recentre ce ticket sur le bug des filtres dans la liste des observateurs.

**Comment by TheoLechemia** [comment]
Corrigé sur la branche develop.  Voir http://demo.geonature.fr/geonature
