### ISSUE TITLE
Migration 2.4.x : erreurs avec les modules import et export

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/GeoNature#956]
Bonjour,

J'ai fait une migration de GN 2.3.2 vers 2.4.0 (puis 2.4.1) sans aucun problème, à condition qu'il n'y ait pas de module import ou export.

Par contre, avec ces 2 modules installés, la migration plante.  

- Module Export : il faut vérifier que le fichier `home/MYUSER/geonature/var/log/gn_export/cron.log` existe bien, sinon ça fait planter la fin du migration.sh.

- Module Import : au moment de l'installation du requirements.txt du module import, j'ai cette erreur :

`ERROR: botocore 1.17.10 has requirement docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.`

En ajoutant une ligne sur docutils dans le requirements.txt (`docutils==0.15.2`) de geonature, les migrations de la 2.4.0 puis 2.4.1 fonctionnent.

**Comment by camillemonchicourt** [comment]
OK merci pour ce retour.
Oui c'est identifié au niveau du module Exports. Corrigé depuis : 
- https://github.com/PnX-SI/gn_module_export/commit/fdb0b7a75ee78ba59888faeff439186e4a48a0ae
- https://github.com/PnX-SI/gn_module_export/commit/96669ae29497222a62967dbdb4b16aaabaa110ce
Ainsi qu'une correction dans GeoNature 2.4.1 : https://github.com/PnX-SI/GeoNature/commit/7ac48c9a474f5a0edd10121f58442326d6e8d75c

Pour le module d'Import, on a identifié plusieurs soucis de la version 1.0.0. On prépare une version 1.1.0, merci pour ce retour qu'on va regarder aussi.

**Comment by sogalgeeko** [comment]
Bonjour,
Je rejoins le point 1 de @Splendens 

> Module Export : il faut vérifier que le fichier home/MYUSER/geonature/var/log/gn_export/cron.log existe bien, sinon ça fait planter la fin du migration.sh.

J'allais faire la remontée dans une nouvelle issue: avec plusieurs autres modules, si le dossier $MODULE/var/log n'est pas créé, l'installation plante.

**Comment by camillemonchicourt** [comment]
OK dans cette contribution en attente (https://github.com/PnX-SI/GeoNature/pull/952) on vérifie la présence de certains fichiers lors de la migration, mais il y a peut-être quelques autres vérifications à ajouter ?

**Comment by TheoLechemia** [comment]
Dans la 2.4.1 le problème doit être levé par le commit d'Amandine (https://github.com/PnX-SI/GeoNature/commit/7ac48c9a474f5a0edd10121f58442326d6e8d75c)
Pour l'erreur de `docutils` ce n'en n'est pas vraiment une. C'est une dépendance de dev d'un des paquet qu'on utilise. Je monte la version de `docutils` côté GeoNature pour enlevé ce warning
