### ISSUE TITLE
Contrainte d'unicite pour la table gn_commons_bib_tables_location

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature#962]
Avec les installation de modules échouées et recommencées, on peut se retrouver avec des ligne doublons dans la table gn_commons_bib_tables_location.

Je propose d'ajouter une contrainte d'unicité pour la table sur les champs schema_name et table_name 

```
ALTER TABLE gn_commons.bib_tables_location ADD CONSTRAINT gn_commons_bib_tables_location_unique UNIQUE (schema_name, table_name);

```

**Comment by camillemonchicourt** [comment]
Oui en effet il faut ajouter cette contrainte. Merci
