### ISSUE TITLE
/api/users/role/ non protégée

### ISSUE THREAD

**Issue by jbdesbas** [PnX-SI/GeoNature#966]
Salut,

La vue /api/users/role/<id_role> n'est pas protégée par le CRUVED, ce qui permet à n'importe qui de récupérer l'intégralité des nom, prénom, adresse e-mail et organisme (exemple : http://demo.geonature.fr/geonature/api/users/role/13 )

**Comment by camillemonchicourt** [comment]
Corrigé depuis plusieurs versions.
