### ISSUE TITLE
OFFEST négatif

### ISSUE THREAD

**Issue by CistudeNature** [PnX-SI/GeoNature#967]
Bonjour,

Nous venons d'installer les dernières releases de geonature (2.4.1), de taxhub (1.7.1) et d'usershub (2.1.2).
Sur geonature, nous rencontrons une erreur sql "OFFSET ne doit pas être négatif" sur la requête suivante :

 geonatadmin@geonature2db INSTRUCTION :  SELECT taxonomie.vm_taxref_list_forautocomplete.cd_nom AS taxonomie_vm_taxref_list_forautocomplete_cd_nom, taxonomie.vm_taxref_list_forautocomplete.search_name AS taxonomie_vm_taxref_list_forautocomplete_search_name, taxonomie.vm_taxref_list_forautocomplete.cd_ref AS taxonomie_vm_taxref_list_forautocomplete_cd_ref, taxonomie.vm_taxref_list_forautocomplete.nom_valide AS taxonomie_vm_taxref_list_forautocomplete_nom_valide, taxonomie.vm_taxref_list_forautocomplete.lb_nom AS taxonomie_vm_taxref_list_forautocomplete_lb_nom, taxonomie.vm_taxref_list_forautocomplete.regne AS taxonomie_vm_taxref_list_forautocomplete_regne, taxonomie.vm_taxref_list_forautocomplete.group2_inpn AS taxonomie_vm_taxref_list_forautocomplete_group2_inpn, similarity(taxonomie.vm_taxref_list_forautocomplete.search_name, 'Grenouille rouss') AS idx_trgm
        FROM taxonomie.vm_taxref_list_forautocomplete JOIN taxonomie.bib_noms ON taxonomie.bib_noms.cd_nom = taxonomie.vm_taxref_list_forautocomplete.cd_nom JOIN taxonomie.cor_nom_liste ON taxonomie.cor_nom_liste.id_nom = taxonomie.bib_noms.id_nom AND taxonomie.cor_nom_liste.id_liste = 100
        WHERE taxonomie.vm_taxref_list_forautocomplete.search_name ILIKE '%Grenouille%rouss%' ORDER BY idx_trgm DESC, taxonomie.vm_taxref_list_forautocomplete.cd_nom = taxonomie.vm_taxref_list_forautocomplete.cd_ref DESC
         LIMIT 20 OFFSET  -20
Merci d'avance pour votre retour.

Cistude Nature

**Comment by camillemonchicourt** [comment]
Oui la version 1.7.2 corrige ce soucis, c'est indiqué dans les notes de version de TaxHub.
