### ISSUE TITLE
Dockerisation de Geonature  

### ISSUE THREAD

**Issue by AJambon** [PnX-SI/GeoNature#969]
Bonjour, 

Nous aimerions dockeriser Geonature pour faciliter l'installation. Quelqu'un a-t-il déjà entrepris de le faire ?

**Comment by camillemonchicourt** [comment]
Il y a eu des tests, mais aussi des réalisations plus abouties, mais elles n'ont pas été partagées pour le moment.

**Comment by camillemonchicourt** [comment]
Voir https://github.com/PnX-SI/GeoNature/issues/2206
