### ISSUE TITLE
Interraction CAS/UsersHub/GeoNature

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#972]
Quand on se connecte sur UH puis qu'on revient sur GN sans s'être déconnecté, le token de vérification des droits n'est plus bon car il est associé à UH, mais on est pas déconnecter de GN. 
Si token absent on incorrect on devrait être déconnecté.

**Comment by jacquesfize** [comment]
Résolu dans la 2.14 : https://github.com/PnX-SI/GeoNature/commit/840a6d090892984f5d222afd64624ba58d4d9450
