### ISSUE TITLE
Synthese: filtre par UUID JDD et CA et observation

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoNature#973]
Ajouter la possibilité de filtrer par UUID JDD, CA et observation.
L'API synthese offre déjà la possibilité de filtrer sur tous les champs de la vue `gn_synthese.v_synthese_for_web_app`.
Il faut donc rajouter les champs uuid JDD et uuid CA dans cette vue. 

Pour le frontend, on se base sur le mécanisme existant du dynamic-form. Il faut simplement éditer ce fichier pour y ajouter les 3 champs: https://github.com/PnX-SI/GeoNature/blob/master/frontend/src/app/GN2CommonModule/form/synthese-form/dynamycFormConfig.ts 
Les filtres seront rajoutés automatiquement dans le bloc "filtres avancés"

**Comment by camillemonchicourt** [comment]
Filtre par UUID des observations ajouté dans la 2.9.0.
