### ISSUE TITLE
Occtax : modification date

### ISSUE THREAD

**Issue by jbdesbas** [PnX-SI/GeoNature#977]
Bonjour,

En cas de modification de la date d'un relevé, seul le champs date_début est modifié. Le champs date_fin (masqué par défaut) reste à sa valeur d'origine.

**Comment by jbrieuclp** [comment]
Pour moi c'est logique si date début est différentes de date de fin, par contre la question se pose pour une même date.
Peut-être aussi qu'il faut directement afficher la date de fin lors d'une modif quand les 2 dates sont différentes.

**Comment by jbdesbas** [comment]
Oui effectivement, je n'ai pas précisé mais c'est problématique seulement lorsqu'on une date unique de renseignée. Ta solution d'afficher directement la date fin si elle est différente me parait intuitive pour l'utilisateur et la plus simple à mettre en œuvre :+1:

**Comment by camillemonchicourt** [comment]
Oui OK. 
Donc si la date_fin est égale à la date_debut, et que l'on modifie la date_debut, alors on modifie la date_fin en cohérence.
Mais si la date_fin est différente de date_debut, et qu'on modifie date_debut, alors on modifie pas date_fin.
