### ISSUE TITLE
Utilisation des API avec CURL

### ISSUE THREAD

**Issue by Heg0Damask** [PnX-SI/GeoNature#982]
Je souhaiterais savoir si il y a un moyen d'utiliser directement les API GeoNature avec l'application curl (ou autre) ?
J'aimerais par exemple pouvoir réaliser une moulinette pour créer des comptes automatiquement avec mot de passe (à partir d'un fichier Excel), ou bien créer un relevé via une ligne de commande.

Je viens d'essayer avec la route occtax/releve/(numero) http://docs.geonature.fr/development.html#get--occtax-releve-(int-id_releve) cela fonctionne bien je récupère bien mon relevé par contre je n'arrive pas à "poster" un relevé avec la route occtax/releve (http://docs.geonature.fr/development.html#post--occtax-releve) j'ai directement internal server error, pourtant ma commande curl à l'air d'être bien écrite.

**Comment by camillemonchicourt** [comment]
Pour poster il faut peut-être s'authentifier avant. Il faudrait regarder les logs de GeoNature pour voir à quoi l'internal server error. 

Pour créer un utilisateurs, c'est au niveau de l'API de UsersHub et non pas de GeoNature (https://github.com/PnX-SI/UsersHub/issues/47)

**Comment by Heg0Damask** [comment]
@camillemonchicourt 
je suis authentifié, j'arrive à utiliser l'API http://docs.geonature.fr/development.html#get--occtax-releve-(int-id_releve) ça fonctionne je récupère bien mon relevé, mais je n'arrive pas à le mettre à jour.
Je récupère le relevé avec son numéro, je modifie juste le commentaire et j'essaye de le renvoyer au serveur, mais ça ne fait rien du tout.

Je vais regarder l'API usershub merci pour l'info, j'avais pas fait le lien.

**Comment by amandine-sahl** [comment]
En cas de problème d'authentification l'api retourne une reponse avec le code 403 FORBIDEN.

Le code 500 indique qu'il y a une erreur (non gérée). Il faut aller voir les logs pour comprendre le problème.

**Comment by Heg0Damask** [comment]
En fait c'était juste un problème dans le champs "observers" 
En cas de lecture du relevé on obtient observers :  [{.......}], pour modifier le relevé il suffit de mettre la variable à "observers" : [1] (1 = admin) et conserver uniquement les 2 variables { "geometry": ... , "properties" : {}}

ça fonctionne !
