### ISSUE TITLE
venv installé avec python2 par défaut

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature#998]
Sous Debian Buster (10) avec Python2 et Python3 installé, le script `install_app.sh` m'a créé un environnement virtuel contenant le binaire `python2` par défaut. Cela provoque l'échec de l'installation car la commande "geonature" ne s'installe pas correctement. Ceci est surement dû au fait que Python 2 est lié par défaut au binaire `python`. Sur le système `python --version` affiche : `Python 2.7.16`

Pour résoudre ce problème, j'ai utilisé la commande : `python3 -m venv venv` dans le script  install_app.sh au lieu de `python3 -m virtualenv venv`. Le venv contient bien python3 par défaut dans ce cas là.
Cela semble être [la façon de faire recommandée](https://docs.python.org/3/library/venv.html).
Doit on corriger le script d'installation ?

Une autre solution (non testée) pour ne pas toucher au script d'installation semble être d'ajouter une alternative pour Python au niveau système (à l'aide de `update-alternatives`) [comme indiqué dans cet article](https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux).

**Comment by TheoLechemia** [comment]
C'est prévu dans la branche en dev. On va fixer la version de python à 3.8.

**Comment by jpm-cbna** [comment]
> On va fixer la version de python à 3.8.

Pour Ubuntu 20.04, la v3.8 est dispo mais sur Debian 10, la seule version de Python 3 disponible dans les dépôts officiels est la 3.7. Cela signifie qu'il faudra la compiler ou la récupérer depuis le dépôt testing (elle sera dispo dans la v11)...

Il y a un ticket sur le fait de fixer la version de Python ?

**Comment by TheoLechemia** [comment]
3.7 pardon. 
La 3.8 est encore récente et bug avec beaucoup de librairies (psycopg notamment). 
Non pas de ticket la dessus pour l'instant

**Comment by camillemonchicourt** [comment]
Voir les commits en lien avec l'installation Python, dans la branche en cours de développement : https://github.com/PnX-SI/GeoNature/commits/jbrieuclp-occtax-multi-records

**Comment by jpm-cbna** [comment]
Ok ça marche.
Dans [le changelog à la ligne 13](https://github.com/PnX-SI/GeoNature/blame/jbrieuclp-occtax-multi-records/docs/CHANGELOG.rst#L13), il est fait mention de la 3.8 alors que la méthode d'installation est décrite avec la 3.7.
