### ISSUE TITLE
Autocomplétion commande geonature

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature#999]
Voici un [Gist contenant l'autocomplétion de la commande geonature](https://gist.github.com/jpm-cbna/9d808eff4d3f7f2fcc7d2a901f4b7631).

Pour l'activer, il est nécessaire de le sourcer. Il est possible de l'activer automatiquement en même tant que l'env virtuel python du backend en ajoutant `source ~/<path-to-completion-file>/geonature_completion` à la fin du fichier `venv/bin/activate`.

C'est possible de le faire lors de la création du venv dans le script `install_app.sh`. Est ce que cela irait ?
Autre question, est ce que je place le fichier `geonature_bash_completion` dans le dossier `install/` ou dans le dossier `backend/` ou ailleurs ?

**Comment by joelclems** [comment]
Excellent! Je me suis toujours demandé comment ça marchait l’auto complétion en bash.
ça me parait très bien de le mettre à l'installation.
Je le mettrai dans le dossier `install` ou `install/scripts`

**Comment by jpm-cbna** [comment]
C'est intégré à la branche `develop` depuis le 19 août dans le commit 82bf035.
